hashicorp/terraform

- builtin/providers/vault/provider.go
- builtin/providers/vault/resource_mount.go
- builtin/providers/vault/resource_mount_test.go
- website/source/docs/providers/vault/r/mount.html.md
- website/source/layouts/vault.erb
Part of  #12167
Note that remounting hasn't been implemented because the `path` is being used as the ID. The attributes `force_no_cache` & `local` are not able to be set as the Vault API doesn't expose these values.
> provider/vault: vault_mount resource

- command/init.go
- config/config.go
- config/config_test.go
- config/test-fixtures/validate-provider-version-invalid/main.tf
- plugin/discovery/version.go
- plugin/discovery/version_set.go
When running `terraform init` with providers that are unconstrained, we will now produce information to help the user update configuration to constrain for the particular providers that were chosen, to prevent inadvertently drifting onto a newer major release that might contain breaking changes.
A `~>` constraint is used here because pinning to a single specific version is expected to create dependency hell when using child modules. By using this constraint mode, which allows minor version upgrades, we avoid the need for users to constantly adjust version constraints across many modules, but make major version upgrades still be opt-in.
Any constraint at all in the configuration will prevent the display of these suggestions, so users are free to use stronger or weaker constraints if …
> command init: show suggested constraints for unconstrained providers

- builtin/providers/google/resource_compute_instance_group.go
- builtin/providers/google/resource_compute_instance_group_test.go
Fixes: #15024
```
% make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccComputeInstanceGroup_'
2017/06/02 20:48:54 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccComputeInstanceGroup_ -timeout 120m
=== RUN   TestAccComputeInstanceGroup_basic
--- PASS: TestAccComputeInstanceGroup_basic (123.64s)
=== RUN   TestAccComputeInstanceGroup_update
--- PASS: TestAccComputeInstanceGroup_update (150.37s)
=== RUN   TestAccComputeInstanceGroup_outOfOrderInstances
--- PASS: TestAccComputeInstanceGroup_outOfOrderInstances (103.71s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	377.737s
```
> provider/google: Set instances to computed in compute_instance_group

- builtin/providers/aws/resource_aws_cloudwatch_log_group.go
- builtin/providers/aws/resource_aws_cloudwatch_log_group_test.go
1) Removing tags from terraform doesn’t actually get removed in AWS
2) Trying to update a tag with empty value (“”) to a non-empty value causes terraform to loop forever
The issue was caused by a mixup of using tag values where tag name
should have used and is corrected in this patch.
This patch also removes the comparison of old and new tag values,
because AWS api takes care of updates by itself and there is no need to
perform an unnecessary UnTag API to update an existing tag value
> Fix issues in Cloudwatch Log Group tag

- website/source/docs/commands/import.html.md
Updated import command provider flag documentation to explicitly specify syntax.
The [providers documentation](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances) explicitly specifies the format of the value for the `provider` field in a resource, but the [import provider flag](https://www.terraform.io/docs/commands/import.html#provider-provider) documentation does not.
It was unclear to me when first looking at the page that `aws.eu` meant an `aws` provider with the alias `eu`, and not an alias of `aws.eu`. This way, the formatting of the expected value should be more clear for readers in the future.
Related to #14998
> [docs] Updated import command provider to specify syntax

- builtin/providers/kubernetes/provider_test.go
- builtin/providers/kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go
- builtin/providers/kubernetes/resource_kubernetes_persistent_volume_claim_test.go
- builtin/providers/kubernetes/resource_kubernetes_persistent_volume_test.go
- builtin/providers/kubernetes/structures.go
- builtin/providers/kubernetes/structures_test.go
- builtin/providers/kubernetes/test-infra/main.tf
I somehow missed these failures after upgrading to K8S 1.6.1, possibly because I was running tests against the old version of K8S. 🙈  On the positive side it means 1.6 code is fully compatible with 1.5 API.
1.6 introduced tighter validation of persistent volumes, so our test data containing volumes which didn't exist started to fail. I decided to add `google` provider to the test suite and provision temporary volume for each test.
I also had to remove a test with AWS EBS volume, because our tests are running on GKE. We might add those back later as there are plans on running acceptance tests on AWS too, but it will take time to build that test environment.
Closes #13716
This time with the right version 😃 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", …
```
> provider/kubernetes: Fix acc tests after upgrading to 1.6

- builtin/providers/alicloud/provider.go
- builtin/providers/alicloud/resource_alicloud_nat_gateway.go
This PR fix the following bugs:
1. When setting access_key to "", running 'terraform apply' will raise ACCESS KEY NOT FOUND error.  And the PR fix the bug by using ENV ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY.
2. When creating nat gateway, if set "zone" is nil, diff resource will appear error. Now, the PR set "zone" Compute is true.
The running result of nat gateway testcase as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudNatGateway -timeout 120m
=== RUN   TestAccAlicloudNatGateway_basic
--- PASS: TestAccAlicloudNatGateway_basic (76.65s)
=== RUN   TestAccAlicloudNatGateway_spec
--- PASS: TestAccAlicloudNatGateway_spec (69.36s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  146.017s
> provider/alicloud: Fix access_key NOT FOUND bug and nat_gateway diff bug

- website/source/intro/examples/index.html.markdown
Provided what I believe to the the new correct address for the example url.
> Url to aws-two-tier example changed.

- builtin/providers/pagerduty/structure.go
There was a spelling mistake in the name of a map. The fix will not affect functionality and all tests pass.
> fix simple spelling mistake

- website/source/docs/import/importability.html.md
Reasoning for docs update: These were already importable, but the docs hadn't been updated to reflect that.
Relevant Terraform version: Importing compute disk is only available on master, the rest are already available.
> Update importable Google resources

- builtin/providers/aws/resource_aws_lambda_function.go
```
=== RUN   TestAccAWSLambdaFunction_importLocalFile_VPC
--- FAIL: TestAccAWSLambdaFunction_importLocalFile_VPC (16.48s)
* aws_lambda_function.lambda_function_test: 1 error(s) occurred:
* aws_lambda_function.lambda_function_test: Error creating Lambda function: InvalidParameterValueException: The provided execution role does not have permissions to call CreateNetworkInterface on EC2
status code: 400, request id: ddb1a6a7-48e4-11e7-9d99-9d3b481e3ff0
FAIL
```
Here's a snippet from the debug log proving this is the API call that returned the error:
```
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 119 …
```
> provider/aws: Retry Lambda func creation on IAM error

- builtin/providers/librato/resource_librato_alert.go
- builtin/providers/librato/resource_librato_metric.go
- builtin/providers/librato/resource_librato_service.go
- builtin/providers/librato/resource_librato_space.go
- builtin/providers/librato/resource_librato_space_chart.go
- vendor/github.com/henrikhodne/go-librato/librato/alerts.go
- vendor/github.com/henrikhodne/go-librato/librato/client.go
- vendor/github.com/henrikhodne/go-librato/librato/metrics.go
- vendor/github.com/henrikhodne/go-librato/librato/services.go
- vendor/github.com/henrikhodne/go-librato/librato/spaces.go
- vendor/github.com/henrikhodne/go-librato/librato/spaces_charts.go
- vendor/vendor.json
Recently, the underlying Librato client API was updated; this PR brings these changes into the Librato provider.
Also cleaned up a few lint errors and refactored a few items to remove extraneous "&schema.Schema" items.
> provider/librato: Update based on Librato API changes

- builtin/providers/aws/resource_aws_ecs_service.go
This is to address the following intermittent test failure:
```
=== RUN   TestAccAWSEcsService_withDeploymentValues
--- FAIL: TestAccAWSEcsService_withDeploymentValues (4.09s)
* aws_ecs_service.mongo: 1 error(s) occurred:
* aws_ecs_service.mongo: ClusterNotFoundException: Cluster not found.
status code: 400, request id: 8968a32f-48eb-11e7-b6ba-119633763b81 "mongodb-8799254687846428972"
FAIL
```
Here's a snippet from the debug log which proves this is the API call the error is coming from:
```
2017/06/04 06:03:31 [DEBUG] [aws-sdk-go] DEBUG: Response ecs/CreateService Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 68
Content-Type: …
```
> provider/aws: Retry ECS svc creation on ClusterNotFoundException

- builtin/providers/datadog/resource_datadog_user.go
- builtin/providers/datadog/resource_datadog_user_test.go
It's read-only and generates supurious diffs for verified users.
> provider/datadog: make datadog_user verified a computed attribute

- builtin/providers/aws/resource_aws_default_vpc.go
Found as part of #15065, when there is no default VPC, Terraform will
throw a panic. This prevents that as a user should never get that
```
% make testacc TEST=./builtin/providers/aws/ TESTARGS='-run=TestAccAWSDefaultVpc_'
2017/06/05 12:16:09 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws/ -v -run=TestAccAWSDefaultVpc_basic -timeout 120m
=== RUN   TestAccAWSDefaultVpc_basic
--- PASS: TestAccAWSDefaultVpc_basic (44.65s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	44.669s
```
> provider/aws: Guard against panic when no aws_default_vpc found

- builtin/providers/aws/resource_aws_db_option_group.go
- builtin/providers/aws/resource_aws_db_option_group_test.go
- website/source/docs/providers/aws/r/db_option_group.html.markdown
Fixes: #14995
Adds a timeout block to configure deletes
```
% make testacc TEST=./builtin/providers/aws/ TESTARGS='-run=TestAccAWSDBOptionGroup'                                                      
2017/06/02 19:54:18 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws/ -v -run=TestAccAWSDBOptionGroup -timeout 120m
=== RUN   TestAccAWSDBOptionGroup_importBasic
--- PASS: TestAccAWSDBOptionGroup_importBasic (57.03s)
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (32.69s)
=== RUN   TestAccAWSDBOptionGroup_timeoutBlock
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (31.59s)
=== RUN …
```
> provider/aws: Add support for a configurable timeout in db_option_group

- builtin/providers/kubernetes/provider.go
- website/source/docs/providers/kubernetes/index.html.markdown
> provider/kubernetes: Allow sourcing config_path from KUBECONFIG env var

- builtin/providers/aws/resource_aws_elasticache_replication_group.go
This fixes the crash I reported in #13487 but I don't quite understand why (other than the fact that the array obviously was empty but we try to access element 0 of it... but terraform plan does complete successfully after this change. Unclear if this is leaving the system in a weird state though.
> [provider/aws] check that we actually have NodeGroupMembers

- website/source/docs/providers/aws/r/cloudwatch_log_subscription_filter.html.markdown
Title should be `aws_cloudwatch_log_subscription_filter` instead of `aws_cloudwatch_logs_subscription_filter`
> doc(typo): fix title in aws_cloudwatch_log_subscription_filter

- builtin/providers/google/resource_compute_disk.go
- builtin/providers/google/resource_compute_disk_test.go
```
make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccComputeDisk_updateSize'
2017/06/05 11:31:09 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccComputeDisk_updateSize -timeout 120m
=== RUN   TestAccComputeDisk_updateSize
--- PASS: TestAccComputeDisk_updateSize (28.37s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	28.377s
```
> Allow resizing of Google Cloud persistent disks

- builtin/providers/alicloud/errors.go
- builtin/providers/alicloud/resource_alicloud_vpc.go
- builtin/providers/alicloud/resource_alicloud_vswitch.go
This PR fixed the vpc and vswitch bugs that there will raise error when creating multiple vpc or vswitch simultaneously, and the PR using retry to solve them.
The running results of vpc and vswitch testcase as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVpc -timeout 120m=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (20.17s)
=== RUN   TestAccAlicloudVpc_update
--- PASS: TestAccAlicloudVpc_update (34.13s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  54.323s
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudVswitch -timeout 120m 
=== RUN   TestAccAlicloudVswitch_basic
--- PASS: TestAccAlicloudVswitch_basic (30.97s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  30.982s
> provider/alicloud: Fix vpc and vswitch bugs while creating vpc and vswitch

- builtin/providers/alicloud/resource_alicloud_instance.go
This PR fixed the bug that ensure ecs instance is already existed before allocating its public ip.
In addition, return error when some one operation failed.
> provider/alicloud: Fix allocating public ip bug

- website/source/docs/providers/aws/r/kinesis_stream.html.markdown
> provider/aws: Change aws_kinesis_stream docs to not have id and name the same

- builtin/providers/aws/resource_aws_elastic_beanstalk_application_version_test.go
This is to address the following test failure (likely caused by race condition):
```
=== RUN   TestAccAWSBeanstalkEnv_version_label
--- FAIL: TestAccAWSBeanstalkEnv_version_label (372.11s)
testing.go:280: Step 1 error: Error applying: 1 error(s) occurred:
* aws_elastic_beanstalk_application_version.default: 1 error(s) occurred:
* aws_elastic_beanstalk_application_version.default: InvalidParameterValue: No Application named 'tf-test-name-3608794125069207226' found.
status code: 400, request id: 3e206972-48ed-11e7-88fc-83faf60662ac
```
We'll see in the coming days/weeks if it's eventual consistency or not.
> provider/aws: Fix Beanstalk App Version acceptance test

- builtin/providers/aws/resource_aws_vpc_dhcp_options.go
```
=== RUN   TestAccAWSDHCPOptions_importBasic
--- FAIL: TestAccAWSDHCPOptions_importBasic (4.55s)
* aws_vpc_dhcp_options.foo: 1 error(s) occurred:
* aws_vpc_dhcp_options.foo: Error waiting for DHCP Options (dopt-901858f7) to become available: InvalidDhcpOptionID.NotFound: The dhcpOption ID 'dopt-901858f7' does not exist
status code: 400, request id: 3ad6e7c3-b5de-493e-baf0-1150e2b6478d
```
> provider/aws: Raise timeout for DHCP opts creation

- builtin/providers/aws/resource_aws_security_group.go
- builtin/providers/aws/resource_aws_security_group_test.go
Fixes: #14522
To follow similar work in IPv4, we are now going to revoke the default
IPv6 egress rule from an empty AWS security group
```
% make testacc TEST=./builtin/providers/aws/ TESTARGS='-run=TestAccAWSSecurityGroup_ipv4andipv6Egress'
2017/06/05 14:01:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws/ -v -run=TestAccAWSSecurityGroup_ipv4andipv6Egress -timeout 120m
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (63.39s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	63.423s
```
> provider/aws: Revoke default ipv6 egress rule for aws_security_group

- website/source/layouts/openstack.erb
I missed this update earlier in PR #14196
> Correct openstack_lbaas_* to openstack_lb_* sidebars to reflect correct resource type names.

- builtin/providers/aws/data_source_aws_ssm_parameter.go
- builtin/providers/aws/data_source_aws_ssm_parameter_test.go
- builtin/providers/aws/provider.go
- builtin/providers/aws/resource_aws_ssm_parameter.go
- builtin/providers/aws/resource_aws_ssm_parameter_test.go
- builtin/providers/aws/validators.go
- builtin/providers/aws/validators_test.go
- website/source/docs/providers/aws/d/ssm_parameter.html.markdown
- website/source/docs/providers/aws/r/ssm_parameter.html.markdown
- website/source/layouts/aws.erb
Hi - I have taken the work from #14043 / #11433 . I have done the following:
1. Addressed the code review comments
2. Added the ability to specify the KMS key to be used for `SecureString`
3. ForceNew when the `type` is changed (AWS Imposed Limitation)
4. Added a data source for ssm parameters
@tomelliff - Did most of the work, but since this is such a great community I thought I would pitch in an bring it over the finish line. Plus I could really use this provider ;)
@radeksimko Since you did the review on the other PR, ping. If you have free time.
> provider/aws: New SSM Parameter resource

- builtin/providers/aws/resource_aws_ssm_maintenance_window_task.go
- builtin/providers/aws/resource_aws_ssm_maintenance_window_task_test.go
- website/source/docs/providers/aws/r/ssm_maintenance_window.html.markdown
- website/source/docs/providers/aws/r/ssm_maintenance_window_task.html.markdown
This adds support for task_parameters to the aws_ssm_maintenance_window_task resource.
The [ssm:RegisterTaskWithMaintenanceWindow](http://docs.aws.amazon.com/systems-manager/latest/APIReference/API_RegisterTaskWithMaintenanceWindow.html) AWS API method includes a `TaskParameters` parameters, which isn't currently supported by TF. This adds support that parameter.
Additionally, the docs had an incorrect name for the `aws_ssm_maintenance_window`'s `allow_unregistered_targets` parameter (it was actually `allow_unassociated_targets` in the TF resource and the AWS API), so updating the doc to correct the name for that.
> Add task_parameters parameter to aws_ssm_maintenance_window_task resource

- builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
Similar to https://github.com/hashicorp/terraform/pull/15083 - this is to fix the following test failure:
```
=== RUN   TestAccAWSBeanstalkEnv_version_label
--- FAIL: TestAccAWSBeanstalkEnv_version_label (381.45s)
testing.go:280: Step 1 error: Error applying: 1 error(s) occurred:
* aws_elastic_beanstalk_application_version.default: 1 error(s) occurred:
* aws_elastic_beanstalk_application_version.default: InvalidParameterValue: No Application named 'tf-test-name-69597012152946852' found.
status code: 400, request id: 1e32ff6e-4a7f-11e7-847e-d3bbf7943c8b
```
> provider/aws: Fix race condition in Beanstalk acc test

- builtin/providers/alicloud/resource_alicloud_instance.go
- builtin/providers/alicloud/resource_alicloud_security_group_rule.go
- website/source/docs/providers/alicloud/r/instance.html.markdown
This PR fixed security group rule bug that when authorizing rules for an existed security group or VPC's security group, its nic_tyep only is 'intranet'.
The testcast running result of security group rule as follows:
TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudSecurityGroupRule -timeout 120m
=== RUN   TestAccAlicloudSecurityGroupRule_Ingress
--- PASS: TestAccAlicloudSecurityGroupRule_Ingress (4.90s)
=== RUN   TestAccAlicloudSecurityGroupRule_Egress
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (5.63s)
=== RUN   TestAccAlicloudSecurityGroupRule_EgressDefaultNicType
--- PASS: TestAccAlicloudSecurityGroupRule_EgressDefaultNicType (4.66s)
=== RUN   TestAccAlicloudSecurityGroupRule_Vpc_Ingress
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (27.14s)
=== RUN …
> provider/alicloud: Fix security group rules bug

- website/source/docs/providers/google/r/storage_bucket_acl.html.markdown
This points to the new location for the list of canned ACL's.
> Update link to canned GCS ACL's

- builtin/providers/google/import_compute_autoscaler_test.go
- builtin/providers/google/resource_compute_autoscaler.go
- builtin/providers/google/resource_compute_autoscaler_test.go
It looks like our vendored code thinks that Patch has "autoscaler" as an optional field, but the [documentation](https://cloud.google.com/compute/docs/reference/latest/autoscalers/patch) suggests that it is required. It probably regressed when we vendored a [new copy of the client code](https://github.com/hashicorp/terraform/commit/c9640e40dfb7b282246ea18af4bfac0384d60b78#diff-981842c12447ae1d1f29443c53b63787R336) around a month ago.
We didn't catch this because the `_update` test didn't perform an `Update` - it performed a `Destroy` followed by a `Create` instead. This PR updates the tests so that an actual `Update` is performed.
Patch doesn't make much sense in this context - we pass in an entire copy of the resource, so we should be using Update anyways.
Fixes: #15056
@danawillow
> provider/google: Make google_compute_autoscaler use Update instead of Patch.

- website/source/docs/providers/google/r/compute_region_backend_service.html.markdown
Update the regional backend service documentation to reflect that instance groups cannot be empty.
Related to #15027 
@danawillow
> provider/google: Add note about instance group restrictions in region backend service docs.

- builtin/providers/google/resource_compute_disk.go
- builtin/providers/google/resource_compute_disk_test.go
A number of `compute_disk` acceptances test are failing because of mishandling of `snapshot`. We need to store the full link returned to us and not parse it, because we can't know what we got, but we'll always get the full url back. Should update docs too but I will have a follow up PR regarding waiting for size change that should address this and will come tomorrow.
> provider/google: Update compute_disk to read after update, always set size

- builtin/providers/aws/aws_sweeper_test.go
- builtin/providers/aws/resource_aws_autoscaling_group_test.go
- builtin/providers/aws/resource_aws_db_option_group_test.go
- builtin/providers/aws/resource_aws_key_pair_test.go
- builtin/providers/aws/resource_aws_launch_configuration_test.go
- builtin/providers/google/gcp_sweeper_test.go
- builtin/providers/google/resource_sql_database_instance_test.go
- helper/resource/testing.go
- helper/resource/testing_test.go
Terraform's acceptance testing framework is responsible for creating the infrastructure in the configuration, and then destroying all resources created. While by itself it is largely successful in destroying all resources created, configurations can be constructed that prevent successful teardown. Additionally, any test that panics or hits the Test Runner timeout can result in dangling, leaked resources.
Here we introduce "Sweepers" into helper/resource and adds example implementations for:
- `aws_db_option_group`
- `aws_key_pair`
- `aws_launch_configurations`
- `aws_autoscaling_group`
- `google_sql_database_instances`
We use the CLI flag `sweep` to provide a list of regions to run the Sweepers in. This flag will intercept the normal test flow, and instead run the Sweepers that have been …
> provider/aws: Add Sweeper setup, Sweepers for DB Option Group, Key Pair

- terraform/context.go
- terraform/context_plan_test.go
- terraform/plan.go
- terraform/plan_test.go
The information stored in a plan is tightly coupled to the Terraform core and provider plugins that were used to create it, since we have no mechanism to "upgrade" a plan to reflect schema changes and so mismatching
versions are likely to lead to the "diffs didn't match during apply" error.
To allow us to catch this early and return an error message that _doesn't_ say it's a bug in Terraform, we'll remember the Terraform version and plugin binaries that created a particular plan and then require that those match when loading the plan in order to apply it.
The `planFormatVersion` is increased here so that plan files produced by earlier Terraform versions _without_ this information won't be accepted by this new version, and also that older versions won't try to process plans created by …
> core: don't allow core or providers to change between plan and apply

- command/init.go
- website/source/docs/commands/init.html.markdown
- website/source/docs/commands/providers.html.markdown
- website/source/docs/configuration/providers.html.md
- website/source/intro/examples/index.html.markdown
- website/source/intro/getting-started/build.html.md
- website/source/layouts/downloads.erb
- website/source/upgrade-guides/0-10.html.markdown
This PR has an assortment of updates to the docs for changes planned in 0.10, focusing primarily on the core/provider split.
Since the release plan is not final, this is likely to require further iteration as we get closer, but this is intended as a starting point.
Since this PR is a bit of a grab-bag of different updates, it may help to view it on a commit-by-commit basis.
---
Although most of this is documentation updates, in the process of trying out automatic plugin installation in order to write the docs for it (using a mock releases server, of course!) I found that the lack of progress information on provider installation can feel a little disconcerting, so there's a commit amongst all of this that adds an extra line of output for each plugin being downloaded, to give a stronger …
> website/ux: various docs and usage tweaks for 0.10

- builtin/providers/aws/data_source_aws_acm_certificate.go
- builtin/providers/aws/data_source_aws_acm_certificate_test.go
GH-15063 - In case there are multiple acm certificates with the same domain name, it must be possible to configure which one to use by specifying required certificate type.
```hcl
data "aws_acm_certificate" "test" {
domain = "test.com"
types = ["IMPORTED"]
}
```
- GH-12650 - in case there are multiple certificates with the same domain name...
- GH-12111 - more than one cert present with equal domain names...
> provider/aws: Filter acm certificates by type

- website/source/docs/providers/google/r/storage_bucket.html.markdown
- website/source/docs/providers/google/r/storage_bucket_acl.html.markdown
- website/source/docs/providers/google/r/storage_bucket_object.html.markdown
- website/source/docs/providers/google/r/storage_object_acl.html.markdown
Minor formatting changes + adding related links to overview documentation and API specifications for GCS resources other than `google_storage_bucket`.
@danawillow
> provider/google: Update bucket storage docs introductions

- website/source/docs/providers/aws/r/db_instance.html.markdown
The current link leads to the main page, which is not terribly useful.
Also provided a more verbose explanation of what `backup_window` means and how it can be used.
> provider/aws: Fix link and add better reference to a parameter in RDS docs

- website/source/docs/providers/azurerm/index.html.markdown
I've noticed a number of issues arisen from confusion around the AzureRM Service Principal setup process. This PR updates the AzureRM Provider Page to reference the AzureCLI first for simpler set-up, corrects out-of-date references and removes reference to the old Portal.
> provider/azurerm: Updating the AzureRM Provider Guide

- website/source/docs/providers/azurerm/index.html.markdown
Fixed an issue identified in #15148 - where China/German/Government clouds need to be configured differently
> provider/azurerm: China/German/Government Clouds updates for the Provider guide

- builtin/providers/google/resource_compute_instance_group.go
- builtin/providers/google/resource_compute_instance_group_test.go
- website/source/docs/providers/google/r/compute_instance_group.html.markdown
If you want to add an instance group to a backend service, the `network` filed of the instance group must be set.
Formerly this field is set based on the network where instances are in (this is computed by Google API). It means; if you create the empty instance group, the `network` field will be empty, and you cannot add it to a backend service.
In this PR, I changed `network` field in `google_compute_instance_group` from the computed attribute to the configurable optional argument.
Now user can specify network the group is in and add it to a backend service.
> provider/google: Changed network argument in google_compute_instance_group as optional

- builtin/providers/google/resource_compute_backend_service.go
- builtin/providers/google/resource_compute_backend_service_test.go
- website/source/docs/providers/google/r/compute_backend_service.html.markdown
Add support for the connection_draining block and draining_timeout_sec to compute_backend_service.
Part 1/2 of #13925.
@danawillow
> provider/google: Add support for draining_timeout_sec to compute_backend_service.

- backend/local/hook_state.go
- backend/local/hook_state_test.go
This reverts commit b73d03776163466e6ed9a11d08670d78f408dd46.
This commit seems to have introduced a race condition where we can concurrently keep updating state after we've checked if we need to increase the serial, and thus end up writing partial changes to the state backend.
In the case of Terraform Enterprise, this fails altogether becauseof the state hash consistency check it does.
This fixes #15175.
> Revert "have StateHook periodically PersistState"

- builtin/bins/provider-kubernetes/main.go
- builtin/providers/kubernetes/diff_supress_funcs.go
- builtin/providers/kubernetes/provider.go
- builtin/providers/kubernetes/resource_kubernetes_pod.go
- builtin/providers/kubernetes/resource_kubernetes_pod_test.go
- builtin/providers/kubernetes/schema_container.go
- builtin/providers/kubernetes/schema_pod_spec.go
- builtin/providers/kubernetes/schema_volume_source.go
- builtin/providers/kubernetes/structures.go
- builtin/providers/kubernetes/structures_container.go
- builtin/providers/kubernetes/structures_pod.go
- builtin/providers/kubernetes/validators.go
- website/source/docs/providers/kubernetes/r/pod.html.markdown
- website/source/layouts/kubernetes.erb
I was just testing it and looks default volumes are created as part of Pod creation which is leading to the below error.
```
2017/04/12 17:58:48 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/kubernetes -v -run TestAccKubernetesPod_basic -timeout 120m
=== RUN   TestAccKubernetesPod_basic
--- FAIL: TestAccKubernetesPod_basic (3.24s)
testing.go:280: Step 0 error: After applying this step, the plan was not empty:
DIFF:
UPDATE: kubernetes_pod.test
spec.0.containers.0.resources.#:                "1" => "0"
spec.0.containers.0.resources.0.limits:         "" => ""
spec.0.containers.0.resources.0.requests:       "" => "" …
```
> Add support for K8s pod

- builtin/providers/heroku/resource_heroku_space_test.go
Heroku has kindly created a special organization on their end and added our test account to it. Using this organization, we can now test the Heroku Provider's support for Heroku Spaces. Here I add super for a special env var `HEROKU_SPACES_ORGANIZATION` the `TestAccHerokuSpace_Basic` test. This allows all our existing tests to use our existing organization, and only run this specific test in the new organization. 
Thanks to @danp and others for making it happen 😄 
-------
Waiting on tests to pass, but I've added support for this to our internal CI
> provider/heroku: enable TestAccHerokuSpace_Basic to pass with new Heroku Organization 

- website/source/docs/import/importability.html.md
First of all, thanks for Terraform!
While reading the docs I noticed an inconsistency between `Import` section under each resource document and the `Resource Importability` document.
Example:
* [Import azurerm_virtual_machine](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#import)
* [Resource Importability](https://www.terraform.io/docs/import/importability.html#azure-resource-manager-)
This PR is based on other documentation that might be outdated as well. How I get there:
```console
$ git grep "terraform import azurerm"
```
[Output](https://gist.github.com/thiagocaiubi/6a527fe658351e7db56e1e89b0afa334)
Every resource that has an `Import` section with an example was promoted to `Resource Importability` section.
Edit:
This kind of documentation can encourage more …
> provider/azurerm: Add missing resources to importability section

- builtin/providers/google/sqladmin_operation.go
This should fix #13091, as well as some of our failing tests.
The failures are happening because for some reason, creating an operation and then immediately reading it back does not always succeed. This adds a bit of a delay between the create and read portions of the operation. We may need to fiddle with the numbers a bit in the future (this is hard to test since _most_ of the time, things do work as expected), but it's at least a start.
> provider/google: Add an additional delay when checking for sql operations

- builtin/providers/aws/provider.go
- builtin/providers/aws/resource_aws_route_table.go
- builtin/providers/aws/resource_aws_vpn_gateway_route_propagation.go
- builtin/providers/aws/resource_aws_vpn_gateway_route_propagation_test.go
- website/source/docs/providers/aws/r/route_table.html.markdown
- website/source/docs/providers/aws/r/vpn_gateway.html.markdown
- website/source/docs/providers/aws/r/vpn_gateway_route_propagation.html.markdown
- website/source/layouts/aws.erb
This is a separate resource that serves a similar purpose to the `propagating_vgws` argument on `aws_route_table`, but allows route propagations to be created independently of the route table, which in
turn allows the VPN gateway to be created after the route table it will contribute to, possibly in a separate Terraform module.
To make this work, `propagating_vgws` on `aws_route_table` is now marked as `Computed`, meaning that it won't try to delete any existing propagation edges if there is no setting for it in configuration at all. This allows the user to choose whether to use the argument or the separate resource, though using both together will not work, as explained in the docs.
This is a slight change in existing behavior, because previously the `aws_route_table` resource would …
> provider/aws: aws_vpn_gateway_route_propagation resource

- command/providers.go
- command/providers_test.go
If you run `terraform providers` in a path where there are no configs it crashes:
```
$ terraform providers
2017/06/10 10:15:52 [DEBUG] Detected home directory from env var: /Users/radeksimko
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x158ce12]
goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.(*Tree).Loaded(0x0, 0x0)
/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:118 +0xb2
github.com/hashicorp/terraform/config/module.(*Tree).Validate(0x0, 0xc42001a004, 0x59)
/Users/radeksimko/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:279 +0x7c
github.com/hashicorp/terraform/command.(*ProvidersCommand).Run(0xc420203a40, 0xc42000a270, 0x0, …
```
> command/providers: Avoid crash when no configs found

- config_unix.go
The extra output shouldn't be seen by the user, and is causing TFE to
fail.
> prevent log output during init

- website/source/docs/enterprise/vcs/bitbucket.html.md
- updates content referring to GitHub rather than Bitbucket Cloud
- expands on the results from repository fetch as well as provides instructions for repos not contained in first page of results (paginated responses are not supported in the TFE UI)
- notes scopes that users must have within Bitbucket Cloud to create webhooks
> Add more context about user scopes to bitbucket cloud docs

- command/init.go
- command/init_test.go
- command/plugins.go
- command/plugins_test.go
- plugin/discovery/get.go
- plugin/discovery/get_test.go
- plugin/discovery/meta_set.go
- plugin/discovery/version.go
Now when -upgrade is provided to `terraform init` (and plugin installation isn't disabled) it will:
* ignore the contents of the auto-install plugin directory when deciding what is "available", thus causing anything there to be reinstalled, possibly at a newer version.
* if installation completes successfully, purge from the auto-install plugin directory any plugin-looking files that aren't in the set of chosen plugins.
As before, plugins outside of the auto-install directory are able to take precedence over the auto-install ones, and these will never be upgraded nor purged.
The thinking here is that the auto-install directory is an implementation detail directly managed by Terraform, and so it's Terraform's responsibility to automatically keep it clean as plugins are upgraded.
We don't …
> command: init -upgrade for modules and provider plugins

- command/init.go
- command/init_test.go
- command/meta.go
Now that init can take a directory for configuration, the old behavior
of writing the .terraform data directory into the target path no longer
makes sense. 
Clean up all references to Meta.dataDir, and only use the getter method
in case we chose to dynamically override this at some point.
> init with target dir should still write .terraform in the current directory

- helper/resource/id.go
- helper/resource/id_test.go
The timestamp prefix added in #8249 was removed in #10152 to ensure that
returned IDs really are properly ordered.  However, this meant that IDs were no
longer ordered over multiple invocations of terraform, which was the main
motivation for adding the timestamp in the first place.  This commit does a
hybrid: timestamp-plus-incrementing-counter instead of just incrementing counter
or timestamp-plus-random.
> Fix resource.UniqueId to be properly ordered over multiple runs

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner_test.go
- helper/schema/provisioner.go
- helper/schema/provisioner_test.go
It turns out that `d.GetOk` also returns `false` when the user _did_ actually supply a value for it in the config, but the value itself needs to be evaluated before it can be used.
@mitchellh I must admit this is a bit different then my perception was about how (and when) to use `d.GetOk`.
I was fully under the impression that it would only return `false` if a value was not set in the config by the user and in all other cases it would return `true`. Regardless whether the value needed any kind of interpolation or evaluation.
That way you could always safely use this function to determine if the value you retrieved was put there by the user or was written back to the state during the execution of a `Read()` function of a resource.
The docs seem to (in part) support my assumptions:
``` …
```
> provisioner/file: don’t use `d.GetOk` in validation functions

- command/apply.go
- command/command.go
- command/init.go
- command/init_test.go
- command/meta.go
- command/plan.go
- command/plugins.go
- command/plugins_test.go
- command/refresh.go
- plugin/discovery/find.go
Add support for the `terraform.d/plugins/` directory, as well as directories supplied via the `-plugin-dir` flag.
Users can manually add plugins in a `terraform.d/plugins/` directory, located in the working directory.
The -plugin-dir option lets the user specify custom search paths for plugins. This overrides all other plugin search paths, and prevents the auto-installation of plugins. This flag can be specified multiple times.
This also make sure that the availability of plugins is always checked during init, even if `-get-plugins=false` or `-plugin-dir` is set.
> plugin vendor directories

- command/command.go
- command/init_test.go
- plugin/discovery/find.go
- plugin/discovery/find_test.go
Since the command package also needs to know about the specific OS_ARCH
directories, remove the logic from the discovery package.
> remove OS_ARCH knowledge from discovery

- command/init.go
- plugin/discovery/find.go
- plugin/discovery/meta_set.go
- plugin/discovery/meta_set_test.go
- plugin/discovery/version.go
Don't suggest constraints when the available plugin isn't versioned.
Add zero version const for comparisons.
> remove "~> 0.0" constraint suggestions

- terraform/context_apply_test.go
- terraform/graph_builder_plan.go
- terraform/graph_builder_refresh.go
- terraform/resource_address.go
- terraform/resource_address_test.go
- terraform/test-fixtures/apply-targeted-module-recursive/child/main.tf
- terraform/test-fixtures/apply-targeted-module-recursive/child/subchild/main.tf
- terraform/test-fixtures/apply-targeted-module-recursive/main.tf
- terraform/transform_targets.go
- website/docs/commands/apply.html.markdown
- website/docs/commands/plan.html.markdown
(This is adapted from #9236, originally submitted by @uhef. It is rebased and altered slightly in approach to be compatible with other changes that were made to `ResourceAddress` since the original PR was submitted.)
---
Previously the behavior for `-target` when given a module address was to target only resources directly within that module, ignoring any resources defined in child modules.
This behavior turned out to be counter-intuitive, since users expected the `-target` address to be interpreted hierarchically.
We'll now use a new `Contains` function for addresses, which provides a hierarchical "containment" concept that is more consistent with user expectations. In particular, it allows `module.foo` to match
`module.foo.module.bar.aws_instance.baz`, where before this would not have …
> core: -target option to also select resources in descendant modules

- website/guides/running-terraform-in-automation.html.md
- website/layouts/guides.erb
This guide covers assorted best practices and caveats for running Terraform within orchestration tools and other automation. It provides general examples and guidance, with the intent that this advice can be
adapted by the reader to a concrete implementation within a selected orchestration tool.
This guide is based both on our in-house experience with Terraform Enterprise and on in-house solutions we are aware of in certain organizations.
> website: guide to running Terraform in automation

- command/init.go
- command/meta_backend.go
- command/push_test.go
Don't show plugin init message if there aren't any.
Fix the whitespace around backend init messages to match other output.
> ux with no plugins

- command/init.go
- plugin/discovery/error.go
- plugin/discovery/get.go
- plugin/discovery/get_test.go
This improves the error reporting for failure to install plugins, by recognizing three cases as special:
* There are no versions of a given provider available at all. This suggests either a typoed name or that the provider is third-party and needs to be manually installed.
* No available versions match the given constraints. This suggests either that a single set of constraints are incorrect (require a version that doesn't exist yet, for example) or that there are multiple modules in the configuration that impose conflicting constraints.
* All of the available constraint-matching versions have the wrong protocol version. This suggests that the user has upgraded Terraform past a protocol compatibility boundary but has a provider constrained to a major version that doesn't work with the new …
> Better messaging for plugin installation

- command/init.go
- command/init_test.go
Previously we only did this when _upgrading_, but that's unnecessarily specific and confusing since e.g. plugins can get upgraded implicitly by constraint changes, which would not then trigger the purge process.
Instead, we'll assume that the user is able to easily re-download plugins that were purged here, or if they need more specific guarantees they will manage manually a plugin directory and disable the auto-install behavior using `-plugin-dir`.
> command: purge unused plugins as a side effect of plugin installation

- examples/aws-ecs-alb/instance-profile-policy.json
The StartTelemetrySession action has to be enabled for metrics collection by the ECS agent
> allow instance metrics collection in aws-ecs-alb example

- command/init.go
- command/init_test.go
Previously init would crash if given these options:
```
-backend=false -get-plugins=true
```
This is because the state is used as a source of provider dependency information, and we need to instantiate the backend to get the state.
To avoid the crash, we now use the following adjusted behavior:
- if `-backend=true`, we behave as before
- if `-backend=false`, we instead try to instantiate the backend the same way any other command would, without modifying its configuration
- if we're able to instantiate the backend, we use it to fetch state for dependency resolution purposes
- if the backend is not instantiable then we assume it's not yet configured and proceed with a nil state, which may cause us to see an incomplete picture of the dependencies but still allows the install to succeed. …
> command: init to allow plugin init without backend init

- command/format/plan.go
- command/format/plan_test.go
- terraform/resource_address.go
- terraform/resource_address_test.go
This change makes various minor adjustments to the rendering of plans in the output of `terraform plan`:
- Resources are identified using the standard resource address syntax, rather than exposing the legacy internal representation used in the module diff resource keys. This fixes #8713.
- Subjectively, having square brackets in the addresses made it look more visually "off" when the same name but with different indices were shown together with differing-length "symbols", so the symbols are now all padded and right-aligned to three characters for consistent layout across all operations.
- The `-/+` action is now more visually distinct, using several different colors to help communicate what it will do and including a more obvious `(new resource required)` marker to help draw attention to …
> command/format: minor adjustments to plan rendering

- README.md
```
$ make core-dev
make: *** No rule to make target `core-dev'.  Stop.
```
This was removed in #15258
> Remove core-dev from README

- backend/local/backend.go
- backend/local/backend_local.go
- command/plugins.go
- terraform/context_refresh_test.go
- terraform/resource_provider.go
During plan and apply, because the provider constraints need to be built
from a plan, they are not checked until the terraform.Context is
created. Since the context is always requested by the backend during the
Operation, the backend needs to be responsible for generating contextual
error messages for the user.
Instead of formatting the ResolveProviders errors during NewContext,
return a special error type, ResourceProviderError to signal that
init will be required. The backend can then extract and format the
errors.
This also provides some more detail, like specifying a checksum mismatch, and showing the required and found versions of plugins.
> better UI output for requesting plugin related init

- website/docs/import/importability.html.md
Add `google_sql_database` and `google_sql_database_instance` to Importability page.
@danawillow
https://github.com/terraform-providers/terraform-provider-google/pull/11
https://github.com/terraform-providers/terraform-provider-google/pull/12
> provider/google: SQL Database Importability

- helper/schema/resource.go
- helper/schema/resource_test.go
Timeout information is read from config and encoded into state. On delete, the config information isn't there, so we were failing to read it and then failing to respect the `Delete` timeout setting. This was original reported in https://github.com/hashicorp/terraform/issues/14444. This PR fixes that by reading the Timeout meta data from state, if it's not first found in the config. 
I've included `TestResourceApply_Timeout_destroy`, which checks the value of `TimeoutDelete` inside the delete method, and fails on `master`. 
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/767
------
Original fix part of https://github.com/hashicorp/terraform/pull/14396, but after our repo split, ~I couldn't get the patch to apply even after butchering it locally 😦~ I kind of fixed …
> helper/schema: fix issue reading Timeout data on delete operations 

- backend/remote-state/s3/backend_state.go
- backend/testing.go
The s3.Backend was using it's own code for DeleteState, but the dynamo
entries are only handled through the RemoteClient. Have DeleteState use
a RemoteClient for delete.
Fixes #15161
> Use RemoteClient.Delete for s3.Backend.DeleteState

- command/state_meta.go
- command/state_mv.go
- command/state_mv_test.go
- command/state_rm.go
- command/state_rm_test.go
The state commands were always loading a state from a Backend, and ignoring the `-state` flag.
The docs for the `-backup` flag also didn't match the current behavior, which was passing tests by accident. Update the docs to reflect that one and only one backup will be created, and reevaluate the multiple backup behavior later. 
Fixes #15359
> terraform state commands ignore the -state flag

- flatmap/expand.go
- flatmap/expand_test.go
We use the `.#` key primarily as a hint that we have a list, but its value describes how many items the writer thinks were in the list.
Since this information is redundant with the _actual_ data, it's potentially useful as a form of corrupted data detection but this function isn't equipped to actually report on such a problem (no error return value, and not in a good place for UI feedback anyway), so instead we'll largely ignore this value and just go by the number of items we encounter.
The result of this is that when the counts mismatch we will go by the number of items actually holding the prefix, rather than panicking as we would've before.
This fixes the crashes in #15300, #15135 and #15334, though it does not address any root-cause for the count to be incorrect in the first place, …
> flatmap: be resilient to lying "foo.#" key

- command/meta.go
The "confirm" method was directly checking the meta struct's input field, but that only represents the `-input` command line flag, and doesn't consider the `TF_INPUT` environment variable.
By calling the `Input` method instead, we check both.
This fixes #15338.
> command: don't prompt for state migration if TF_INPUT is set

- helper/validation/validation.go
- helper/validation/validation_test.go
Add IntAtLeast and IntAtMost validation functions so that we can validate that an integer is above or below some number without having to specify both sides of the range if there isn't a relevant upper or lower limit.
> Added IntAtLeast and IntAtMost validation functions.

- backend/remote-state/s3/backend.go
- backend/remote-state/s3/backend_state.go
- backend/remote-state/s3/backend_test.go
- website/docs/backends/types/s3.html.md
Fixes #13184, addresses part of #15358
@jbardin @apparentlymart this is my first foray into the world of Go so go please go easy :)
Does this address the points raised in the other issue? The tests still pass although I'm not sure how to add some specifically related to this. I've also tested it locally and it successfully migrated my dummy setup from the old state structure to the new.
```
$ tree
.
├── env: # Old structure
│   ├── testing
│   │   └── v1
│   │       └── terraform-remote-state-example
│   ├── testing2
│       └── v1
│           └── terraform-remote-state-example
├── terraform-state # New Structure
│   ├── testing
│   │   └── v1
│   │       └── terraform-remote-state-example
│   └── testing2
│       └── v1
│           └── terraform-remote-state-example
└── v1 # Default …
```
> Add configurable workspace prefix for S3 Backend

- command/meta_backend.go
Fixes #15306 
Display correct to and from backends in copy message when
migrating to new remote state
There are no existing tests I can find that test output of messages. Is that
something desirable to test?
> Correct to and from backends when migrating

- command/import.go
- command/import_test.go
- plugin/discovery/find.go
Import was only searching the current directory for plugins. Make sure it uses the Complete path, including any `-plugin-dir` directories provided during init.
> Make sure import uses complete plugin path

- backend/local/backend_local.go
- terraform/plan.go
When applying a plan, a copy of the plan's state is initially persisted to state storage, which may in turn increment the serial number. The apply operation stil uses the state stored in the plan, which may have a lower serial number.
Now we no longer use the plan state when building the apply context, but still perform a sanity check to ensure that the state be used is equivalent.
---
This is the same as #15421, but adapted to apply to the 0.9 line so we can release it before 0.10.0 final.
> applying a plan should use the refreshed state

- examples/aws-networking/subnet/subnet.tf
The current AWS Networking example (https://github.com/hashicorp/terraform/tree/master/examples/aws-networking) should create the subnets in the availability zones specified in `module "primary_subnet"` & `module "secondary_subnet"` definitions in the [region/subnets.tf](https://github.com/hashicorp/terraform/blob/master/examples/aws-networking/region/subnets.tf) file but the subnet module ignores these (while it does set a `data` item in `variables.tf`, it isn't used in the creation of the resources).
**Current behaviour:** the subnets are created in random AZs including sometimes putting both in one zone (more common in Regions with only a couple of AZ. The plan/apply shows the AZ is `computed`. This is made more confusing by some of the naming/labelling that is correctly picking up the …
> Fixes the AWS networking example ensuring that subnets are created in the desired AZ

- terraform/plan.go
Plan application was using the wrong copy of the state, causing serial
numbers to step backewards. After fixing this a sanity check comparing
the states was added, but that fails due to some states be altered by
the serialization itself.
Change the error condition to only log the error for reference, as these
state should be equal. We can address the overall state handling in the
next major release, hopefully negating the need for any of these
changes.
> Remove error from mismatched plan state

- command/init.go
- command/meta.go
- terraform/context.go
Skips checksum validation if the `TF_SKIP_PROVIDER_VERIFY` environment variable is set. Undocumented variable, as the primary goal is to significantly improve the local provider development workflow.
> core: Skip provider checksum validation based on env var

- command/test-fixtures/validate-invalid/missing_defined_var/main.tf
- command/validate.go
- command/validate_test.go
- website/docs/commands/validate.html.markdown
Closes #8588
This is a rebased #8588. All the hard work is still credited to @dtolnay - I just patched his PR to comply with the recent changes to context.
This is introducing BC in the sense that default behaviour is changing, but previous behaviour is still available under a flag.
Either way we should mark this as BC in Changelog and also I'd like someone to review this patched PR before I merge it.
> command/validate: Add flag to check that all variables are specified

- plugin/discovery/get.go
- plugin/discovery/get_test.go
- tools/terraform-bundle/README.md
- tools/terraform-bundle/config.go
- tools/terraform-bundle/main.go
- tools/terraform-bundle/package.go
Normally `terraform init` will download and install the plugins necessary to work with a particular configuration, but sometimes Terraform is deployed in a network that, for one reason or another, cannot access the official plugin repository for automatic download.
`terraform-bundle` provides an alternative method, allowing the auto-download process to be run out-of-band on a separate machine that _does_ have access to the repository. The result is a zip file that can be extracted onto the target system to install both the desired Terraform version and a selection of providers, thus avoiding the need for on-the-fly plugin installation.
This is provided as a separate tool from Terraform because it is not something that most users will need. In the rare case where this is needed, we will …
> terraform-bundle tool for bundling Terraform with providers

- command/workspace_command.go
- command/workspace_command_test.go
- command/workspace_show.go
- commands.go
I didn't see an easy way to display the current env (except for `env list` and the `*` next to the current env)
This pull request adds `terraform env show` which looks something like this:
```
mikehelmick@local [dev-env-show] ✅  bin/terraform env show
default
```
> Add `workspace show` command

- command/state_rm.go
- command/state_rm_test.go
Due to how the state filter machinery works, passing no arguments is valid and matches _all_ resources.
It is very unlikely that someone wants to remove everything from state, so this ends up being a very dangerous default for the `terraform state rm` command, and surprising for someone who perhaps runs it looking for the usage information.
So we'll be pragmatic here and reject the no-arguments case for this command, accepting that it makes the unlikely case of intentionally deleting all resources harder in order to make it less likely that it will happen _unintentionally_.
If someone does really want to remove all resources from the state, they can provide an explicit empty string argument, but this isn't documented because it's a weird case that doesn't seem worth mentioning.
This fixes …
> command: terraform state rm to require at least one argument

- command/apply_test.go
- command/command_test.go
- command/refresh_test.go
- command/workspace_command_test.go
- state/inmem.go
- state/local.go
- state/remote/state.go
- state/state.go
- state/testing.go
- terraform/state.go
- terraform/state_test.go
Previously we relied on a constellation of coincidences for everything to work out correctly with state serials. In particular, callers needed to be very careful about mutating states (or not) because many different bits of code shared pointers to the same objects.
Here we move to a model where all of the state managers always use distinct instances of state, copied when `WriteState` is called. This means that they are truly a snapshot of the state as it was at that call, even if the caller goes on mutating the state that was passed.
We also adjust the handling of serials so that the state managers ignore any serials in incoming states and instead just treat each Persist as the next version after what was most recently Refreshed.
(An exception exists for when nothing has been refreshed, …
> state: more robust handling of state Serial

- command/meta.go
- command/meta_test.go
#13306 allows multiple tfvars file arguments, and expects them to be in order, but does not sort the directory listing.
Meta.process was relying on the system readdir to order the arguments,
but readdir doesn't guarantee any ordering. Read the directory contents
as a whole and sort them in place before adding the tfvars files.
> meta process order

- command/workspace_command_test.go
- helper/shadow/value.go
Nothing major in the primary code path.
Some tests that shouldn't have been reusing a struct value were causing a race with the improved error scanner loop.
shadow.Value was being copied without a lock by copystructure.
> Fix a couple races

- helper/resource/testing.go
Provider import tests previously didn't have to supply a config, but
terraform now requires the provider to be declared for discovery.
testProviderConfig returns a stub config with provider blocks based
on the TestCase Providers. This allows basic import tests in providers
to remain unchanged.
> Automatically insert providers for import acceptance tests

- config/loader_hcl.go
- helper/schema/provider.go
- helper/schema/provider_test.go
- helper/schema/resource.go
- helper/schema/resource_test.go
Previously providers/resources could specify reserved field names, they'd be just caught by schema code and deleted prior to execution of CRUD, so any such field would be ignored anyway.
Nonetheless I think we should be more upfront about this and fail the provider `InternalValidate` test if any schema contains reserved name.
> Actively disallow reserved field names in schema

- README.md
This pull request adds a link to the GitHub organization which contains the formerly-built-in providers, and modifies the `plugin-dev` target documentation to use a provider which is unlikely to be moved out of the core repository.
> README: Add link to provider repos to "Developing"

- backend/testing.go
Remote state implementations may initialize a lineage when creating a
new named state (i.e. "workspace"). The tests were ignoring that initial
lineage to write a new state to the backend.
> backend state tests must honor lineage

- helper/schema/schema.go
- helper/schema/schema_test.go
This may look controversial, but it will actually hit a very small percentage of our official providers (4 fields across all providers in total).
Excluding deprecated & removed fields from the validation should allow us to phase out the fields with invalid names.
```sh
$ ls | xargs -I{} sh -c "cd {}; pwd; make test TESTARGS='-run=TestProvider'"
```
```
/Users/radeksimko/gopath/src/github.com/terraform-providers/terraform-provider-alicloud
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
xargs -t -n4 go test -run=TestProvider -timeout=30s -parallel=4
go test -run=TestProvider -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-alicloud …
```
> helper/schema: Force field names to be alphanum lowercase + underscores

- website/docs/commands/force-unlock.html.markdown
non-optional argument `LOCK_ID`  was omitted from documentation.
> Usage line for force-unlock is wrong.

- plugin/discovery/find.go
- plugin/discovery/find_test.go
On Windows systems the plugin binaries use a `.exe` suffix, which we were misparsing as part of either the "v" or "x" parts of the filename.
This fixes #15578.
> plugin/discovery: trim off .exe suffix when parsing filenames

- command/graph.go
- command/graph_test.go
The backends replace a nil module tree with an empty one before building
the graph, so the graph command needs to do the same.
Fixes #15564
> graph should not panic with no config

- README.md
- website/docs/plugins/provider.html.md
The intent here is just to introduce some initial docs on our recommended way to develop plugins in the same `GOPATH` as Terraform itself. The documentation in this area needs some more fundamental rework as it is rather outdated and mis-organized, but that's outside the scope of what this change is trying to achieve.
> documentation: explain provider dev environment setup

- backend/local/backend_apply.go
The message doesn't make much sense with an empty path.
> only show state path help if state is local

- backend/local/backend_local.go
- terraform/plan.go
- terraform/plan_test.go
Forward-port the plan state check from the 0.9 series.
0.10 has improved the serial handling for the state, so this adds relevant
comments and some more test coverage for the case of an incrementing
serial during apply.
Supersedes #15421
> Add warning to mismatched plan state

- website/docs/commands/index.html.markdown
This is documented for all other Hashicorp products using this service but was missed for Terraform.
This serves as a disclosure of the fact that Terraform reaches out to a Hashicorp service, an explanation of the purpose of that request, and instructions on how to disable it in environments where it is inappropriate or cannot be supported due to a firewall or other connectivity restrictions.
> website: document the Checkpoint service and how to disable it

- helper/acctest/random.go
I found a swallowed error in the acctest package where an SSH private key was being generated.
> Fix swallowed err in acctest package

- CHANGELOG.md
It came as a surprise to my team when migrating to Terraform v0.10.0-rc1 that our `terraform import` commands would fail, even though we had read the changelog and noticed no potentially breaking changes related to import commands. (Specifically, we were calling `terraform import` with a template that only contained a provider block.) For the benefit of others who may be in the same situation, I thought this might be worth calling out explicitly in the changelogs, with a link to the issue ([#11835](https://github.com/hashicorp/terraform/issues/11835)) that provides the reasoning behind the change.
Documentation is based on the notes in PR [#14561](https://github.com/hashicorp/terraform/pull/14561), and the commit message which changed import behavior, …
> Document changes to terraform import behavior (v0.10.0-beta1 onward) as a backwards incompatibility in changelog

- website/layouts/commands-workspace.erb
I think this is a remnant from when we moved from env->workspace. The sidebar renders fine but the actual `workspace` link is a 404
> website: Fix broken/old link in Commands/Workspace

- website/guides/terraform-provider-development-program.html.md
- website/layouts/guides.erb
Adds a Guide on the Terraform Provider Development Program. This guide aids Cloud Providers down the path of creating a provider and registering it with the Terraform Project, and applying for inclusion into the https://github.com/terraform-providers organization 
Requires assets from https://github.com/hashicorp/terraform-website/pull/12
> Add provider dev program guide

- website/docs/plugins/provider.html.md
- website/guides/writing-custom-terraform-providers.html.md
- website/intro/examples/consul.html.markdown
- website/intro/examples/count.markdown
- website/intro/examples/index.html.markdown
These links were casualties of the core/provider split. There was also
an example that suggested cloning a subdirectory of a git repo.
> Docs: Fix broken links and a broken example

- plugin/discovery/find.go
This is causing Terraform to spit out basically all filenames in the CWD, which isn't great from sensitivity/security point of view and I it causes the debug log to be just unnecessarily verbose while bringing low value (IMO).
I'm open to downgrading the level to `TRACE` though, if removal seems too brutal.
> Remove overly verbose DEBUG log

- helper/schema/field_reader_diff.go
The field reader code path is extremely inefficient, but refactoring
it all is much to invasive a change at the moment.
Have DiffFieldReader internally cache results for ReadField.
This is a reduced version of #15641. The DiffFieldReader is the hot entry point, and localizing the caching to a particular instance seems much safer.
> memoize DiffFieldReader.ReadField

- command/state_meta.go
- command/state_mv.go
- command/state_mv_test.go
- command/state_rm.go
- command/state_rm_test.go
- command/state_test.go
- commands.go
- website/docs/commands/state/mv.html.md
- website/docs/commands/state/rm.html.md
Some state commands worked with the backend configuration (push, pull, list, show), while others ignored it (mv, rm), leading to confusing behavior when trying to refactor state files. The website docs were also incorrectly updated, and did not match the behavior of the command, making the overall usage of the state commands confusing and possibly dangerous. 
This makes the `rm` and `mv` commands also work with a configured backend, reflecting the behavior of the other state commands, and the logical expectations of users. 
The one piece missing here is that there is no single command to move resources or modules from a local state file to a remote state, or between remote states. There are a number of ways we could introduce the behavior, a special identifier for `-state-out` like …
> state commands with remote state backends

- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
Adds `GetOkExists` as a schema function. This should only be used to verify
boolean attributes are either set or not set, regardless of their zero
value for their type. There are a few small use cases outside of the boolean
type where this will be helpful as well.
Overall, this shouldn't detract from the zero-value checks that `GetOK()`
currently has, and should only be used when absolutely needed. However,
there are enough use-cases for this addition without checking for the
zero-value of the type, that this is needed.
Primary use case is for a boolean attribute that is `Optional` and `Computed`,
without a default value. There's currently no way to verify that the boolean
attribute was explicitly set to the zero-value literal with the current
`GetOk()` function. This new function allows …
> core: Add `GetOkExists` schema function

- website/docs/commands/init.html.markdown
Reasoning for docs update: There was a typo
Relevant Terraform version: Valid against 0.10.0 but can probably wait for next release 😁
> Fix typo of additional

- website/docs/commands/init.html.markdown
The docs did not mention that it is possible to provide overrides for specific
plugins by placing them into a `terraform.d/plugins/os_arch/` directory inside
the working dir.
Closes #15727.
> Document how to provide provider plugin overrides

- website/docs/commands/init.html.markdown
- website/guides/running-terraform-in-automation.html.md
Update the recent addition to the init docs to better match the style of the rest of that section.
Add mention of the `terraform.d/plugins` directory in the "running in automation" doc.
> plugin docs

- backend/remote-state/s3/backend.go
- backend/remote-state/s3/backend_test.go
S3 accepts objects with a leading slash and strips them off. This works
fine except in our workspace hierarchy, which then can no longer find
suffixes matching the full key name.
Fixes #15645
> don't allow leading slashes in s3 remote state key

- website/guides/terraform-provider-development-program.html.md
"Website" and "Email" were the wrong way around.
> Fix titles on partner contact table on provider development program guide

- backend/remote-state/inmem/backend.go
- backend/remote-state/inmem/backend_test.go
- backend/remote-state/inmem/client.go
- backend/remote-state/inmem/client_test.go
- command/state_push_test.go
- command/test-fixtures/inmem-backend/main.tf
- command/unlock_test.go
- command/workspace_command_test.go
- state/remote/state.go
We can't check lineage in the remote state instance, because we may need to overwrite a state with a new lineage. While it's tempting to add an optional interface for this, like OverwriteState(), optional interfaces are never _really_ optional, and will have to be implemented by any wrapper types as well
Another solution may be to add a State.Supersedes field to indicate that
we intend to replace an existing state, but that may not be worth the
extra check either. That can be tested in future enhancements. 
This also implements workspaces in the inmem backend for better internal test coverage, and adds all known failure scenarios to the tests.
Fixes #15674
> Remove strict lineage check in remote.State

- command/init_test.go
- command/plugins.go
- command/test-fixtures/init-legacy-rc/main.tf
- plugins.go
Add the OS_ARCH directory to `~/.terraform.d/plugins` because Discovery  no longer searches for subdirectories.
Add the override paths from `Meta.PluginOverrides` for discovery.
Fixes #15705
> load legacy plugin paths

- command/import.go
- command/import_test.go
- command/state_rm.go
- command/test-fixtures/import-provider-remote-state/main.tf
- website/docs/commands/import.html.md
While the `local.Local` backend is the only implementation of
`backend.Local`, creating the backend with `ForceLocal` bypasses the
`backend.Backend` in the `local.Local` causing a local state to be
implicitly created rather than using the configured state backend.
Add a test that imports into a configured backend (using the "local"
backend as a remote state proxy). This further confirms the confusing
nature of ForceLocal, as the backend _is_ local, but not from the
viewpoint of meta.Backend.
Fixes #15735
TODO: It's becoming clear there needs to be some helpers for test fixture initialization in the command package.
> Don't ForceLocal for the import backend

- terraform/context_input_test.go
- terraform/eval_interpolate.go
- terraform/eval_state.go
- terraform/graph_builder_input.go
- terraform/graph_builder_plan.go
- terraform/node_module_variable.go
- terraform/test-fixtures/input-module-data-vars/child/main.tf
- terraform/test-fixtures/input-module-data-vars/main.tf
- terraform/transform_module_variable.go
It may not be possible to interpolate module variables during the Input phase. The common instance of this is when a module variable references a data source which needs to be refreshed to resolve. The usual workaround is to either disable input, or target specific resources to exclude the variable from the graph.
This fix allows interpolation of module variables to fail silently, only logging the warnings during Input, allowing terraform to continue on to the Refresh phase. If the variable is still not valid by that point it will be caught during Plan.
Fixes #10460
> Allow module variable interpolation to fail during Input

- dag/walk.go
- terraform/eval.go
- terraform/graph.go
I know we don't have a good way to filter by levels atm anyway, but it can be helpful even with simple `grep/awk`-based filtering.
I bumped into these messages messages when "decoding" big crash log and I'd love to have the ability to filter these out more easily - ideally in one step, rather than many.
> terraform+dag: Set lower log levels

- website/docs/backends/types/azure.html.md
Adding the `resource_group_name` back in which was chopped off in #8936.
Fixes #15610
> Fixing the Azure Remote State Backend Documentation

- command/init.go
- plugin/discovery/get.go
- plugin/discovery/get_test.go
In the spirit of transparency and improving UX I think we should be printing out chosen version & source for each plugin being downloaded.
1. When there's firewall in the way the user might not immediately realize what exactly is going on behind the scenes and what hostname/port should be whitelisted.
2. We display a single message ("Downloading") which is half-right as we might not end up downloading anything if discovery fails - e.g. no satisfiable version found.
3. ~The discovery phase actually takes some significant portion of the total time and splitting it can make the user feel it's "faster" because there's more feedback.~ (avoiding two lines to keep output short and brief)
```
- Downloading plugin for provider "google"...
- Downloading plugin for …
```
> plugin: Display version + source when initializing plugins

- plugin/client.go
The go-plugin package now uses hclog. The default Logger has a level set
to Info, but all plugin output is relayed via Debug. Create a new named
logger for plugins with the level set to Trace so that all output comes
through.
> specify a logger for go-plugin

- helper/schema/set.go
- helper/schema/set_test.go
Equality of `schema.Sets` gets tricky when dealing with nested sets -
`Set.Equal` only superficially compares the underlying maps and hence any
sets nested under the root sets cause issues.
This adds a simple method, `HashEqual`, that does a top-level hash
comparison, helping to work around this without any complex re-invention
of things like `reflect.DeepEqual`.
Of course, in order to make effective use of this function, the user
needs to make sure they are properly hashing their nested sets, however
this is trivial with things like `HashResource`.
> helper/schema: Add Set.HashEqual

- terraform/resource_provider_mock.go
Input can be called concurrently from multiple nodes in the graph.
> fix race in MockResourceProvider

- builtin/bins/provisioner-salt-masterless/main.go
- builtin/provisioners/salt-masterless/resource_provisioner.go
- builtin/provisioners/salt-masterless/resource_provisioner_test.go
- command/internal_plugin_list.go
- command/internal_plugin_test.go
- scripts/generate-plugins.go
- website/docs/provisioners/salt-masterless.html.md
This is practically copy-pasted from [Packer](https://github.com/hashicorp/packer/tree/master/provisioner/salt-masterless) - not sure how I should attribute the original authors. I just had to modify the Packer pieces to fit into the Terraform provisioner model (inspired by the existing chef provisioner).
Also, I need to write proper unit tests. This is a premature PR to get some eyeballs on it.
> Add salt-masterless provisioner

- command/hook_ui.go
- command/hook_ui_test.go
Output sample: `data.google_compute_zones.available: Destruction complete after 46.197682ms`
(For operations longer than a second, it will be truncated to the second; using the same timestamp rendering as the still-in-process updates.)
> Output duration in UiHook after successful operation completion.

- backend/init/deprecate_test.go
- backend/init/init.go
This is a simple wrapper to allow a backend to be marked as deprecated
during initialization. This let's us easily mark legacy backends as deprecated, as well as change the names of backends as needed in #13036.
> add the ability to mark a backend as deprecated

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
Regarding issue #9112, support in nested types in jsonencode would be beneficial for ECS task management. For example: instead of template with multiple variables (strings) for ECS task environment variables (which is list of maps in json), now it can be defined and passed as a single variable. Same story with ports or other ECS properties.
> core: nested types support in jsonencode

- website/docs/plugins/basics.html.md
- website/docs/plugins/provider.html.md
- website/intro/getting-started/build.html.md
- website/intro/getting-started/install.html.markdown
- website/layouts/guides.erb
Continuing https://github.com/hashicorp/terraform/pull/15865 by trying to surface our "Getting Started" guide better. 
- Adds link to "Getting Started" on our "Guides" layout
- Moves the `Advanced Topic!` notice higher on 2 plugin pages
- Adds `Installing Terraform Providers` section on "Installing" page of Getting Started
> Update our documentation to push "Getting Started" better

- builtin/provisioners/local-exec/resource_provisioner_test.go
TestResourceProvider_stop() is testing the ability to stop a Provisioner, while TestResourceProvider_Apply() is testing Apply().
TestResourceProvider_stop() uses a goroutine, which means that any function with *testing.T as its receiver within that goroutine will silently fail.
This PR changes the test to accept that an error that occurs within the goroutine is lost. It also adds some verbosity to the logs to explain what is happening.
> Drop untestable error in localexec tests

- state/remote/http.go
- state/remote/http_test.go
- website/docs/backends/types/http.html.md
This PR adds the ability to enable `supports_locking` for the http backend in a fully backwards compatible manner. 
```
terraform {
backend "http" {
address          = "http://localhost:8888/"
supports_locking = "true"
}
}
```
Once enabled additional REST calls will be made:
* Lock: `<address>/lock` - body will contain the json marshaled `LockInfo`
* Unlock: `<address>/unlock?ID=<lock_id>` - body will be empty
* State Put: `<address>?ID=<lock_id>` - no other changes.
The following implements quick-n-dirty handling of the state storage and locking functionality. It would be useless in a real situation since it doesn't actually persist data, but hopefully serves to further illustrate the behavior. 
```python
#!/usr/bin/env python
from tornado.escape import json_decode
from tornado.ioloop …
```
> Add optional locking support to the http state backend

- builtin/provisioners/local-exec/resource_provisioner.go
- builtin/provisioners/local-exec/resource_provisioner_test.go
- website/docs/provisioners/local-exec.html.markdown
Tested on Ubuntu and Windows. Use case is primarily for Windows users who desire Bash functionality. `interpreter_flag` may be added to any block, else OS-based defaults are used.
Example:
```
resource "null_resource" "test-local-exec-interpreter" {
provisioner "local-exec" {
command = "date /T > outfile-cmd.txt"
}
provisioner "local-exec" {
command = "date > outfile-bash.txt"
interpreter = "bash"
}
provisioner "local-exec" {
command = "date > outfile-bash-path.txt"
interpreter = "C:\\Program Files\\Cmder\\vendor\\git-for-windows\\bin\\bash.exe"
}
provisioner "local-exec" {
command = "date > outfile-powershell.txt"
interpreter = "PowerShell"
interpreter_flag = "-Command"
}
}
```
Code and documentation are included. There didn't appear to be a test fixture to update (open to guidance …
> Add choice of shell per issue 2974

- website/docs/commands/taint.html.markdown
Provides an example (with similar formatting as
https://www.terraform.io/docs/commands/state/list.html#example-filtering-by-module)
for tainting resources within a module.
> Provide example for terraform taint documentation

- website/docs/configuration/interpolation.html.md
- website/docs/provisioners/index.html.markdown
Hello,
This is just a small fix in docs examples where the attribute used doesn't match the resource attributes.
It generates messages like this: 
``` 
Resource 'aws_instance.instances.0' does not have attribute 'private_ip_address' for variable 'aws_instance.server.0.private_ip_address'
```
- Reasoning for docs update: `consistency`
- Relevant Terraform version: `0.8.1`
Best,
Gabriel
> Resource aws_instance does not have attr private_ip_address

- backend/remote-state/consul/backend.go
- website/docs/backends/types/consul.html.md
As per GH-15354 this pull-request allow to specify _ca_file_ _cert_file_ and _key_file_ in order to interact with a secured Consul backend.
Tested with consul 0.8.4
> GH-15354: Consul backend security options

- .github/ISSUE_TEMPLATE.md
This is just a few editorial tweaks to the issue template.
The primary motivation here was to shorten the section about provider issues now that we're no longer in the transitional state; I suspect that this scary wall of text is dissuading people from actually reading and following the template.
Otherwise, this is just some tweaks to the wording and some adjustments for the fact that we're now not expecting provider issues here.
> Revisions to ISSUE_TEMPLATE.md

- website/docs/modules/usage.html.markdown
Terraform modules encapsulate their resources, and dependencies can only
be expressed through outputs, which wasn't clear to me in the existing
documentation. I'm hoping a small change will make that more explicit.
e.g. https://stackoverflow.com/questions/45849165/do-you-need-an-output-to-express-a-dependency-on-a-resource-in-a-terraform-mod/45876522#45876522
Happy to revise if the core team thinks there's a better way to describe this.
> Describing Module Encapsulation

- config/config_string.go
- config/loader_hcl.go
- config/loader_test.go
- config/test-fixtures/basic.tf
- config/test-fixtures/basic.tf.json
We added the description field in 0.9 but we never parsed it because we
didn't have a use for it. As we prepare to use this field, let's start
parsing it out
> config: parse description field for outputs

- .travis.yml
- Makefile
- README.md
- Vagrantfile
- backend/testing.go
- command/command_test.go
- command/e2etest/main_test.go
- config/testing.go
- helper/schema/testing.go
- state/testing.go
- terraform/terraform_test.go
Using Go 1.9 allows us to:
* Simplify our Makefile by exploiting the fact that `./...` no longer includes `vendor/` packages by default
* Make use of the new `t.Helper()` function in our test helpers so that we get better source code references when they fail.
> Upgrade to Go 1.9

- command/test-fixtures/validate-valid/with-tfvars-file/main.tf
- command/test-fixtures/validate-valid/with-tfvars-file/terraform.tfvars
- command/validate.go
- command/validate_test.go
Enable variables support in meta-parameters processing in validate command.
Fixes #15733, #15894
> fix(validate): add variables support

- website/docs/configuration/providers.html.md
Previously the `-upgrade` option was covered only on the `terraform init` usage page. It seems also worth mentioning in the main docs on provider versioning, since we're already explaining here other mechanics of the versioning/constraints system.
> website: explain how to upgrade providers

- helper/validation/validation.go
- helper/validation/validation_test.go
This adds a `ValidateRegexp` validation helper to check to see if a field
has a valid regular expression.
Includes test for good regexp, and test for bad regexp.
> helper/validation: Add ValidateRegexp

- helper/resource/testing.go
- helper/resource/testing_test.go
I'd like to use this in the Kubernetes provider acceptance tests. There's a handful of tests which I want to run in most environments (hence not skip the whole test) without having to duplicate the whole test for each platform, just because one check has to be different.
By environments I mean minikube, GKE, custom-built K8S cluster etc. in this context - they should be the same, but there are some tiny differences which cause tests to fail.
Example: https://github.com/terraform-providers/terraform-provider-kubernetes/commit/c5bfdfda06eb9f5b6515b16c56d036fea8b1a515#diff-54c9acee9539dfc51361bc5424f74420R50
> helper/resource: Add TestStep.SkipFunc

- terraform/state.go
- terraform/state_test.go
When the InstanceState.Meta fields are marshaled, numeric values may
change types. The timeout system currently inserts integer values, which
will be unmarshal as float64s.
To ensure that a state which has round-tripped through json is equal to
itself, compare the json representation of the Meta values.
> make sure marshaled Meta fields are still equal

- builtin/provisioners/salt-masterless/resource_provisioner.go
The code here was previously assuming that d.State() was equivalent to the `schema.ProvRawStateKey` due to them both being of type `InstanceState`, but that is in fact not true since a state object contains some transient information that is _not_ part of the persisted state, including the connection information we need here.
Calling `ResourceData.State()` constructs a _new_ state based on its stored values, so the constructed object is lacking this transient information. We need to use the specific state object provided by the caller in order to get access to the transient connection configuration.
Unfortunately there is no automated test coverage for this because we have no good story for testing provisioners that use `communicator`. While such tests could potentially be written, we'd …
> provisioner/salt-masterless: fix crash processing connection config

- builtin/provisioners/salt-masterless/resource_provisioner.go
- builtin/provisioners/salt-masterless/resource_provisioner_test.go
- website/docs/provisioners/salt-masterless.html.md
In #15870 we got good feedback that it'd be more useful to have the various filename-accepting arguments on this provisioner instead accept strings that represent the contents of such files, so that they can be generated from elsewhere in the Terraform config.
This change does not achieve that, but it does make room for doing this later by renaming `minion_config` to `minion_config_file` so that we can later add a `minion_config` option alongside that takes the file content, and deprecate `minion_config_file`.
Ideally we'd just implement the requested change immediately, but unfortunately the release schedule doesn't have time for this so this is a pragmatic change to allow us to make the full requested change at a later date without backward incompatibilities.
This change is safe because …
> provisioner/salt-masterless: add "_file" suffix to "minion_config"

- backend/remote-state/consul/backend.go
A TLS config was being assigned to a Transport in a nil http.Client. The
Transport is built in the consul config by default, but the http.Client
is not built until later in NewClient.
No new tests, because the existing tests were sufficient to catch this. 
This was introduced in #15405, but there were no ACC tests run.
Fixes #15972
> Fix crash in consul backend

- config/append.go
- config/append_test.go
- config/config_test.go
- config/merge.go
- config/merge_test.go
- config/test-fixtures/validate-local-multi-file/local-def.tf
- config/test-fixtures/validate-local-multi-file/local-use.tf
- terraform/test-fixtures/apply-local-val/main.tf
- terraform/test-fixtures/apply-local-val/outputs.tf
It seems that this somehow got lost in the commit/rebase shuffle and wasn't caught by the tests that _did_ make it because they were all using just one file.
As a result of this bug, locals would fail to work correctly in any configuration with more than one .tf file.
Along with restoring the append/merge behavior, this also reworks some of the tests to exercise the multi-file case as better insurance against regressions of this sort in future.
This fixes #15969.
> config: merge/append for local values

- config/config.go
- config/config_test.go
- config/test-fixtures/validate-local-value-count/main.tf
- terraform/context_plan_test.go
- terraform/test-fixtures/plan-local-value-count/main.tf
There is some additional, early validation on the `count` meta-argument that verifies that only suitable variable types are used, and adding local values to this whitelist was missed in the initial implementation.
This fixes #15987.
> config: allow local value interpolations in count

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- command/format/plan.go
- command/format/plan_test.go
- command/hook_ui.go
- command/show.go
- terraform/context_apply_test.go
- terraform/diff.go
- terraform/eval_apply.go
- terraform/hook_test.go
- terraform/resource.go
- terraform/resource_address.go
- terraform/resource_address_test.go
- terraform/resource_test.go
As reported in #14048, we currently have a number of inconsistencies between the following:
* The detailed plan output for normal updates vs. destroying.
* The plan detail vs. the tally of resources to be created, updated and destroyed.
* The count of resources to destroy during plan and the count of resources destroyed during apply.
The root cause of these inconsistencies is that we have some leaky abstractions around the handling of data sources: internally we include data sources in the diff and act on them during apply to either refresh them or remove them from state (depending on what sort of apply we're doing), but in the user-facing model we think of data sources as being "read" in an apply and not appearing _at all_ in destroy.
The goal of this PR, then, is to ensure that this …
> Ensure consistency of details and tallies in plan and apply

- website/docs/backends/types/azurerm.html.md
- website/layouts/backend-types.erb
- Updating the sidebar to reference `azurerm`
- Including the former name of the Backend in the titles
- Clarifying that we're storing in Blob Storage
> Updating the AzureRM Backend Documentation

- backend/remote-state/consul/backend.go
Fixes #15972
Crash happens because `config.HttpClient` was not set in `consulapi.DefaultConfig()`, so instead of setting it directly, setting `config.TLSConfig` passing to `consul.NewClient` will do its work.
> Fix crash when using consul backend

- website/docs/configuration/variables.html.md
- website/intro/getting-started/build.html.md
- Having a map 'foo' with a key 'foo' is confusing.
- it's -> its
> Cosmetic doc changes

- website/docs/configuration/locals.html.md
Adds an example of using local values in a resource. There is one example in the block above, but it's nested in a ternary.
> docs: Add local values usage example

- website/docs/configuration/locals.html.md
Re-submission of #16042.
Additional documentation of using `locals` as a `map` - using AWS tags as an example.
> Example of using local with maps

- helper/resource/testing.go
- helper/resource/testing_import_state.go
- helper/resource/testing_import_state_test.go
Add an `ImportStateIdFunc` field to the ImportState testing functionality.
This will allow for more powerful generation of complex import state IDs
that can't be accomplished by `ImportStateId` or `ImportStateIdPrefix`
themselves.
> helper/resource: Add ImportStateIdFunc

- website/docs/internals/graph.html.md
- website/intro/getting-started/dependencies.html.md
Previously we just assumed the reader was familiar with the idea of a graph but didn't explain it.
Since graphs are an implementation detail of Terraform, rather than essential information needed for new users, this revises the introduction text to talk only about _dependencies_, which we assume the user is familiar with as a more practical concept.
Additionally, Paul Hinze did a great talk on how Terraform uses graphs at HashiConf 2016 which is good additional content for our existing "Graph Internals" page, which includes a concise explanation of the basics of graph theory.
This is a slightly different take on the same root problem as #16045. That PR took the approach of trying to explain graph theory in-place in the guide so that the term is at least _defined_, but that feels like a …
> website: don't talk about graphs in the Getting Started guide

- command/format/plan.go
- command/format/plan_test.go
In 3ea1592 the plan rendering was refactored to add an extra indirection of producing a display-oriented plan object first and then rendering from that object.
There was a logic error while adapting the existing plan rendering code to use the new display-oriented object: the core `InstanceDiff` object sets the `Destroy` flag (a boolean) for both `DiffDestroy` and `DiffDestroyCreate`, and so this code previously checked `r.Destroy` to recognize the "destroy-create" case. This was incorrectly adapted to a check for the display action being `DiffDestroy`, when it should actually have been `DiffDestroyCreate`.
The effect of this bug was to cause the "(forces new resource)" annotations to not be displayed on attributes, though the resource-level information still correctly reflected that a new …
> command/format: restore "(forces new resource)" caption

- command/fmt.go
- command/fmt_test.go
- website/docs/commands/fmt.html.markdown
This addresses #15304. There are a couple ways to solve this, but I chose to modify the `fmt` command with a `-check` flag that produces the desired behavior.
I chose not to put this functionality in `github.com/hashicorp/hcl/hcl/fmtcmd`, because that would have required a change to the API. That has broader implications. If the consensus is that said functionality would be useful outside of `terraform fmt`, I can move the logic to the `hcl` lib. 
Alternatively, `fmt` could have been updated to alter its return code without the `-check` flag - like `gofmt`. However, as pointed out, that changes the current behavior which could have a downstream impact. Additionally, the default semantics of `terraform fmt` are different from `gofmt`. Namely, `-write` defaults to `true` with `terraform …
> command: Add -check flag to fmt

- backend/cli.go
- backend/local/backend.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- backend/local/cli.go
- command/init.go
- command/meta.go
- command/meta_backend.go
- commands.go
- website/guides/running-terraform-in-automation.html.md
In #15884 we adjusted the plan output to give an explicit command to run to apply a plan, whereas before this command was just alluded to in the prose.
Since releasing that, we've got good feedback that it's confusing to include such direct instructions when Terraform is running in a workflow automation tool, because such tools usually abstract away exactly what commands are run and often require users to take different actions to proceed through the workflow.
To accommodate such environments while retaining helpful messages for normal CLI usage, here we introduce a new environment variable `TF_IN_AUTOMATION` which, when set to a non-empty value, is a hint to Terraform that it isn't being run in an interactive command shell and it should thus tone down this sort of "next steps" messaging. …
> cli: allow disabling "next steps" message in terraform plan

- command/version.go
I thought it would be more helpful if the message pointed directly to the downloads page.
I can take the PR a step further and try to calculate the download path based on the os type or  link directly to the releases page i.e `https://releases.hashicorp.com/terraform/0.10.5/`
It would be nice to be able to wget in the terminal right after running `terraform version`
> Add `/downloads` to the outdated version message

- command/import.go
- command/import_test.go
- command/meta.go
This addresses #15875
Some custom tools may depend on the old behavoir of the import command that does not require matching config. To allow backward compatability, the -ignore-missing-config flag has been added.
> Add ignore-missing-config flag to import command

- command/state_rm.go
This change adds a line with item count:
```
$ terraform state rm aws_launch_configuration.mylc1 aws_launch_configuration.mylc2
2 items removed.
Item removal successful.
```
I feel we can also log "Writing the new state...", which happens right after removal.
Fixes #16109
> cmd/state_rm: log removed item count

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
This commit adds new interpolation function `abs` which returns an absolute
value for a given float. Having an ability to obtain an absolute value remove
the need to use and abuse the `signum` function to achieve the same gaol.
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
> Add new interpolation function `abs`.

- helper/validation/validation.go
- helper/validation/validation_test.go
This adds `NoZeroValues`, a small `SchemaValidateFunc` that checks that a
defined value is not a zero value. It's useful for situations where you
want to keep someone from explicitly entering a zero value (ie: literally
`0`, or an empty string) on a required field, and want to catch it in
the validation stage, versus during apply using `GetOk`.
> helper/validation: Add NoZeroValues

- command/autocomplete.go
- command/autocomplete_test.go
- command/init.go
- command/workspace_delete.go
- command/workspace_list.go
- command/workspace_new.go
- command/workspace_select.go
- command/workspace_show.go
- main.go
- vendor/github.com/mitchellh/cli/cli.go
- vendor/vendor.json
- website/docs/commands/index.html.markdown
This set of changes enables tab-completion for `bash` and `zsh` users, building on the mechanisms provided by the `cli` package, which in turn delegates to [the `complete` package](https://godoc.org/github.com/posener/complete).
By turning on autocomplete, we get autocomplete of the sub-command names themselves for free.
We then need to augment each command object with some additional methods to define the expected options and arguments. This changeset does this for `terraform init` and for the `terraform workspace ...` family of commands. We can build out comprehensive support across all the commands over time in separate PRs.
> CLI autocomplete

- config/interpolate_funcs_test.go
These tests were written before subtest support was available. By running them as subtests we can get better output in the event of an error, or in verbose mode.
I made these changes while trying to repro a bug report. I wasn't able to reproduce it, but I think these changes still make interpolation function test debugging simpler, so figured I might as well submit the change anyway.
> config: improve interpolation function test output

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
The motivation for this new function comes from a desire to declare AWS IAM users/groups (and other similar constructs) in the following manner:
```
variable "users" {
default = {
"jon.snow"        = [ "Leaders", "Fighters" ]
"tyrion.lanister" = [ "Strategists" ]
"cersei.lanister" = [ "Leaders" ]
"arya.stark"      = [ "Fighters" ]
"oberyn.martell"  = [ "Fighters" ]
}
}
```
Each user could be created with existing functions:
```
resource "aws_iam_user" "user" {
count = "${length(keys(var.users))}"
name  = "${element(keys(var.users), count.index)}"
}
```
However, due to how group membership works with IAM, a user cannot be directly associated with a list of `aws_iam_group` resources. Instead, an `aws_iam_group` has to be created alongside a `aws_iam_group_membership` as follows:
``` …
```
> Add 'transpose' interpolation function

- terraform/context_apply_test.go
- terraform/eval_local.go
- terraform/node_local.go
- terraform/test-fixtures/apply-destroy-with-locals/main.tf
- terraform/test-fixtures/provider-with-locals/main.tf
Locals don't need to be evaluated during destroy.  Rather than simply
skipping them, remove them from the state as they are encountered. Even
though they are not persisted in the state, it keeps the state up to
date as the destroy happens, and we reduce the chance of other
inconstancies later on.
Fixes #16190
> Don't evaluate locals during destroy

- .travis.yml
- Makefile
- command/e2etest/automation_test.go
- command/e2etest/primary_test.go
- e2e/e2e.go
This PR cover three main changes to the end-to-end tests:
* The pre-existing TestPrimarySeparatePlan test is updated to expect that a data source won't be tallied as a destroy action on apply, since that is now the case.
* Three new tests mimic the workflow suggested by [Running Terraform in Automation](https://www.terraform.io/guides/running-terraform-in-automation.html).
* The tests are run in Travis-CI, so we can catch regressions sooner. (Unlike most "acceptance tests", this is safe because these tests only access network resources that don't require special credentials.)
> Assorted e2etest updates

- config/module/get.go
- config/module/get_test.go
A refactor introduced an extra `/` in the download url, which causes an
extra redirect during discovery.
Improve a registry test to verify that detection doesn't require the
registry after the modules have been fetched.
> remove extra slash from registry urls

- command/e2etest/init_test.go
- command/e2etest/test-fixtures/plugin-cache/cache/os_arch/terraform-provider-template_v0.1.0_x4
- command/e2etest/test-fixtures/plugin-cache/main.tf
- command/init.go
- command/meta.go
- command/plugins.go
- commands.go
- config.go
- main.go
- main_test.go
- plugin/discovery/find.go
- plugin/discovery/get.go
- plugin/discovery/get_cache.go
- plugin/discovery/get_cache_test.go
- website/docs/commands/cli-config.html.markdown
- website/docs/commands/index.html.markdown
- website/docs/configuration/providers.html.md
- website/docs/plugins/basics.html.md
- website/layouts/docs.erb
To avoid surprising users by creating a global plugin directory they don't know about, we elected to auto-install plugins into the local `.terraform` directory to keep things contained.
However, an implication of this decision is that by default a fresh set of plugins must be downloaded for each distinct working directory. This is bothersome for those on metered or slow Internet connections.
As a compromise, here we add an _opt-in_ mechanism to treat a local directory as a read-through cache of plugins. When the cache directory is enabled, Terraform will still fetch metadata from releases.hashicorp.com (to learn if new versions are available), but once a particular version is selected the local cache will be consulted first to avoid re-downloading the plugin distribution zip file.
After …
> cli: Opt-in local cache directory for plugins

- terraform/context_apply_test.go
- terraform/test-fixtures/provider-with-locals/main.tf
- website/docs/configuration/providers.html.md
Make sure this fails during destroy
Add a note in the documentation that local values may fail during
destroy. This should only be temporary until we update the graph to properly transform output and locals for destruction.
> Improve the test to show a failure when using locals in a provider

- website/layouts/docs.erb
Adding salt-masterless to the sidebar, and also rearranging null_resource -- everything else in Provisioners (and everything in Providers) is sorted alphabetically, don't think null_resource needs to be an exception.
> Fixes #16226 - two changes to the Provisioners sidebar on the website

- backend/local/backend.go
> Not to be confused with the const of the same name in the `command` package.
Hi, I'm familiarizing myself with the Terraform codebase, so here's a trivial cleanup fix :)
Best regards,
—octo
> backend/local: Remove unused const DefaultDataDir.

- backend/remote-state/s3/backend.go
- website/docs/backends/types/s3.html.md
This commit makes sts, metadata and other AWS related API calls optional, thus the backend initialization will not send non-AWS API tokens to AWS APIs.
This fixes #12377
> Allow non-AWS S3 backends

- communicator/ssh/communicator.go
I've been running into some EOF errors with the file provisioner (my fault -- deleting files that it's trying to scp), but debugging this was a lot harder than I expected. This change adds some more information that helps describe what's going on. 
`ssh.WaitMsg` / `ssh.ExitError` have a [`Signal()` method](https://godoc.org/golang.org/x/crypto/ssh#Waitmsg), but it doesn't work (on openssl installs). Otherwise, I'd suggest adding that too: 
```go
if exitErr.Signal() != "" {
msg += fmt.Sprintf(", signal=%s", exitErr.Signal())
}
```
Related Issues: 
- https://github.com/golang/go/issues/4115
- https://github.com/golang/go/issues/16597
> communicator/ssh: add what error details we can for the user

- website/docs/configuration/providers.html.md
With terraform 0.10.7, the `~` character is not resolved causing the creation of `~/.terraform.d/plugin-cache` directories in each directory where `terraform init` is run.
Using `export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"` works fine.
> Replace `~` by `$HOME` in documentation of TF_PLUGIN_CACHE_DIR

- dag/dag.go
- dag/dag_test.go
- dag/marshal.go
In the case of highly-connected graphs, the TransitiveReduction process was far
too computationally intensive. Since no operations are applied to the nodes,
and the walk order is not even user visible, we don't need to sort them n^2
times.
The `e == nil` checks aren't directly related, but short-circuit the `marshalVertex` calls in the debug path.
> faster DAG transitive reduction

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
The PR implements the explode function (the name isn't that good, can't find a good one: chunker, listexplode, ...). I do like `listexplode` but any better name would be welcomed!
@apparentlymart this follows what we spoke about on Slack, i.e. the highly dynamic structure that needs to be transformed in a highly dynamic structure. After we spoke, didn't plan to sort this out, but I wanted to learn more about the core, functions etc, so here this work. (spoil: I LOVE the ast-related API ❤️ )
> config: Added explode function to cut a list into smaller lists

- helper/logging/logging.go
- helper/resource/testing.go
- helper/resource/testing_test.go
We run nightly acceptance tests for and collect debug logs produced during the whole run. As we run tests in parallel for some providers (e.g. AWS), the **logs get written to the file in parallel too** which isn't very helpful for debugging, especially when you're trying to isolate a problem related to a single test and track down a chain of HTTP requests/responses and you have to skip unrelated messages just b/c another test happens to run at the same time.
This also means we only need to download a single ~0.5M file for the test that is actually failing instead of downloading debug log for the whole run (~650M in case of AWS).
This patch allows us to use a new ENV variable:
```
TF_LOG_PATH_MASK=/log/location/tf-test-%s.log
```
I have considered the option of using templating …
> helper: Allow logs isolation per acceptance test

- helper/didyoumean/name_suggestion.go
- helper/didyoumean/name_suggestion_test.go
Uses Levenshtein distance to decide if the input is similar enough to one of the given suggestions, and returns that suggestion if so.
The distance threshold of three was arrived at experimentally, and has no objective basis.
> helper/didyoumean: helper library for "Did you mean ...? suggestions

- tfdiags/hcl.go
HCL will be the most frequent origin of a source range, so this helper should make it easier to translate these between the two worlds so we can more easily use them in native Terraform diagnostics and other messaging.
> tfdiags: Helper to construct SourceRange from hcl.Range

- scripts/debug-terraform
This launches Terraform inside a headless dlv configured to accept a remote debugging process. It's configured this way so it can be easily used from a debugger GUI integrated into an IDE/editor, but it can also be used from the CLI by running the command it prints.
Using a remote debugger here is useful even when debugging with the CLI, since it keeps Terraform's verbose and colorful output from interfering with the debugger UI.
> scripts: helper for launching Terraform in the dlv debugger

- config/raw_config.go
- config/raw_config_test.go
Previously we were demoting HCL2 `RawConfig`s into empty old-school `RawConfig`s on copy.
> config: when copying a HCL2 RawConfig, don't corrupt it

- command/apply.go
- command/plan.go
- command/refresh.go
- tfdiags/diagnostics.go
```
command: use c.showDiagnostics for backend operation errors
This allows richer diagnostics produced by some subsystems to be displayed
in full-fidelity to the user.
```
```
tfdiags: show descriptions in diagnosticsAsError
Previously we were showing only the summaries when converting to a string
error, but HCL generates summaries that indicate only the _type_ of error,
expecting that the detail will give the details, and so we need to show
both in order to produce a useful error message.
```
> Miscellaneous diagnostic printing improvements

- config/interpolate.go
Having a reference to the originating source range will allow us to generate decent error messages if certain references can't be resolved at interpolation time.
This is not yet populated or used. It will never be populated nor used by the current HCL/HIL-based interpolation path, but will be used by the experimental HCL2-based interpolation path to give it the necessary info to produce diagnostics.
> config: source code ranges for InterpolatedVariable

- helper/schema/core_schema.go
- helper/schema/core_schema_test.go
- helper/schema/provider.go
- helper/schema/provider_test.go
- plugin/resource_provider.go
- terraform/resource_provider.go
- terraform/resource_provider_mock.go
- terraform/schemas.go
In order to parse provider, resource and data source configuration from HCL2 config files, we need to know the relevant configuration schema. This new method allows Terraform Core to request these from a provider.
This is a breaking change to this interface, so all of its implementers in this package are updated too. This includes concrete implementations of the new method in `helper/schema` that use the schema conversion code added in an earlier commit to produce a `configschema.Block` automatically.
Plugins compiled against prior versions of helper/schema will not have support for this method, and so calls to them will fail. Callers of this new method will therefore need to sniff for support using the `SchemaAvailable` field added to both `ResourceType` and `DataSource`.
This careful …
> core: ResourceProvider.GetSchema method

- backend/remote-state/consul/backend.go
- backend/remote-state/consul/backend_state.go
- backend/remote-state/consul/client.go
- backend/remote-state/consul/client_test.go
- Only initialize a single consul client in the backend, which will help with connection pooling.
- Lower the TCP KeepAlive duration. The default of 30s coincides with common network timeouts, and may be racing to keep the connection open.
- Add a test showing that the lock can be lost on certain patterns of network errors. This test will fail once the consul client is updated.
While simply lowering the KeepAlive duration may be enough to superficially fix #16098, an updated consul client should complete that issue.
> some consul lock improvements

- config/module/get.go
- config/module/get_test.go
- config/module/test-fixtures/discover-registry-local/exists-in-registry/identifier/provider/main.tf
- config/module/test-fixtures/discover-registry-local/main.tf
- config/module/test-fixtures/registry-subdir/main.tf
- config/module/tree.go
- config/module/tree_test.go
This makes the subdir notation work for registry modules.
It also instates the correct search order for registry modules, preventing local folders from possibly loading when a registry module is desired, and allowing us to surface any registry errors rather than only leaving warnings in the logs.
> make //subdir notation work for registry modules

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/chef/resource_provisioner_test.go
Fixes #15921
When terraform re-creates an existing node/client with chef provisioner,
the already existing client (which has old keys) must be removed from
the vault items. Afterwards, the chef-vault will be updated with the
newly created client (which has the new keys). Therefore, the recreated
client will be able to decrypt the vault items properly.
> FIX-15921 Clean clients from chef-vault on recreate_client enabled

- command/validate.go
Noticed this was missing from the validate command, which was causing some of our validate calls to incorrectly fail.
Fixes #15916
> Load plugins from plugin_path file if it exists

- commands.go
- config.go
- config_test.go
- main.go
- test-fixtures/credentials
In #16368 we added some new packages for dealing with discovery and authentication for so-called "service hosts", where Terraform-native services such as the module registry are served.
This follow-up set of changes makes it possible to configure the authentication credentials within the CLI config file, using new blocks `credentials` and `credentials_helper`.
In addition, we also allow multiple CLI config files by looking for files matching `~/.terraform.d/*.tfrc` and `~/.terraform.d/*.tfrc.json` (or the usual equivalent on Windows) so that it's possible to keep credentials in a separate file from other settings, and possibly to spread credentials blocks across multiple separate files for easier management.
Along the way here I also took the opportunity to do some light restructuring of …
> Configure service host credentials using the CLI Config file

- config/module/storage.go
- config/module/tree.go
- config/module/tree_test.go
To add registry support, a workaround in the local module storage was
added to record the subdirectory containing the module source from
within the archive file. Here we replace that temporary implementation
with the full manifest needed to record the necessary module metadata
for module loading.
In order to support versioned modules, the actual stored version needs
to be recorded. This can't be derived from the configuration, because
the configuration only contains the constraints, and at load time we need
to be able to enumerate the stored modules and all versions in order to
resolve them.
While the local storage key will be derived from the source and version, that
information is lost once it's hashed. While the entire storage layer
could be replaced to encode the needed data in the …
> new module storage manifest

- communicator/winrm/communicator.go
- communicator/winrm/provisioner.go
- communicator/winrm/provisioner_test.go
It appears that the cacert option for the winrm provisioner was
not getting passed correctly to the winrm package. Log output
showed that CACert was false regardless of configuration.
While the validation of the connector looked for cacert, the winrm
communicator looked for ca_cert.
> Fix winrm provisioner cacert option

- config/module/get.go
- config/module/storage.go
- config/module/test-fixtures/conficting-submodule-names/a/c/main.tf
- config/module/test-fixtures/conficting-submodule-names/a/main.tf
- config/module/test-fixtures/conficting-submodule-names/b/c/main.tf
- config/module/test-fixtures/conficting-submodule-names/b/main.tf
- config/module/test-fixtures/conficting-submodule-names/main.tf
- config/module/tree.go
- config/module/tree_test.go
This is another attempt to get just enough access to the module storage layer without completely ripping out the getter.Storage interface. While that interface may need to go away, it's too intrusive a change at the moment.
The module manifest needs to be read before we have loaded any modules, so the directory being used for the local storage needs to be known by the module.Tree somehow. This uses a couple assertions and a touch of reflection to get the FolderStorage directory, and manage the module manifest.
> more module storage updates

- config/loader.go
- config/loader_test.go
- config/test-fixtures/dir-only-override/main_override.tf
- Steps to reproduce:
- mkdir tf-test && cd tf-test
- touch empty_override.tf
- terraform init
- Verify command panics
> Fix panic when running `init` in a dir containing only overrides

- scripts/build.sh
https://github.com/hashicorp/terraform/pull/16406 changes the version constant our LD_FLAG uses
> Fix build.sh LD_FLAG

- svchost/disco/disco.go
For the same reason the disco tests need to override the http.Transport,
other test fixtures will need to as well. Provide a field to override
the default httpTransport.
> add Transport field to Disco

- registry/regsrc/friendly_host.go
- registry/regsrc/friendly_host_test.go
- registry/regsrc/module.go
- registry/regsrc/module_test.go
- registry/regsrc/regsrc.go
- registry/response/module.go
- registry/response/module_list.go
- registry/response/module_provider.go
- registry/response/module_versions.go
- registry/response/pagination.go
- registry/response/pagination_test.go
- registry/response/redirect.go
This PR copies the shared regsrc and response packages from the terraform registry. The registry will update to them them eventually, but we need these in place to move forward with the integration. The api boundaries can probably be cleaned up between these and the existing svchost packages, but these will work for now. 
The FriendlyHost implementation was updated to the more complete svchost.Hostname internally, and the tests were modified to show the stricter validation.
The github and bitbuckets names are also no longer valid for a registry source, as they have special usage in module source strings, and can't be valid registry hosts.
> Registry packages

- command/e2etest/version_test.go
- command/version.go
We encourage users to share the `terraform version` output as part of filing an issue, but previously it only printed the core Terraform version and this left provider maintainers with no information about which
_provider_ version an issue relates to.
Here we make a best effort to show versions for providers, though we will omit some or all of them if either `terraform init` hasn't been run (and so no providers were selected yet) or if there are other inconsistencies that would cause Terraform to object on startup and require a re-run of `terraform init`.
> command: Include provider versions in "terraform version"

- config/loader_hcl.go
- helper/schema/resource.go
- helper/schema/resource_test.go
As discussed in https://github.com/terraform-providers/terraform-provider-aws/pull/1626#issuecomment-328881415
> helper/schema: Loosen validation for 'id' field

- commands.go
- config.go
- config_test.go
- svchost/disco/disco.go
- svchost/disco/disco_test.go
- test-fixtures/hosts
For situations where the default network-based discovery is inappropriate or inconvenient, this allows users to provide a hard-coded discovery document for a particular hostname in the CLI config.
This is a new config block, rather than combined with the existing `credentials` block, because credentials should ideally live in separate files from other config so that they can be managed more carefully. However, this new `host` block _is_ designed to have room for additional host-specific configuration _other than_ credentials in future, which might include TLS certificate overrides or other such things used during the discovery step.
The main use-case imagined for this is when running Terraform in automation. In that case, if Terraform is always running against the same hosts it may be …
> Allow overriding host-based discovery in CLI config

- helper/schema/schema.go
Updated it so Elem is valid for TypeMaps too, and so that TypeSets can use a Resource as an Elem. I'm assuming Max/MinItems can still only be set on Lists/Sets (and not Maps), but it would be good to get some clarification on that before this goes in.
> update Schema.Elem documentation

- config/config.go
- config/module/detector_test.go
- config/module/get.go
- config/module/get_test.go
- config/module/registry.go
- config/module/registry_test.go
- config/module/storage.go
- config/module/test-fixtures/change-intermediate-source/a/b/main.tf
- config/module/test-fixtures/change-intermediate-source/a/main.tf
- config/module/test-fixtures/change-intermediate-source/c/b/main.tf
- config/module/test-fixtures/change-intermediate-source/c/main.tf
- config/module/test-fixtures/change-intermediate-source/main.tf
- config/module/test-fixtures/change-intermediate-source/main.tf.disabled
- config/module/tree.go
- config/module/tree_test.go
- config/module/versions.go
- config/module/versions_test.go
- registry/regsrc/module.go
This PR contains a bunch of necessary refactoring to get the module versioning enabled. There were a number of latent bugs in module handling, that really only arise if you change the source of intermediate level modules. This would have been a very rare event in with module previously, but now that versioning can cause module to change without changing their name, path, or source, we needed to overhaul the storage layer. The refactoring is not complete here, but this get's us into a more manageable state to move forward. 
The primary changes are:
- Metadata required for tracking the provenance of modules is added to the module.Tree. Every layer needs to have it's version and source recorded, so that submodules are always updated accordingly.
- regsrc and response packages are copied from …
> Module versions

- backend/remote-state/s3/client.go
Use fully consistent reads for backend operations.
> dynamoDB reads are not fully consisten by default

- backend/local/backend.go
- backend/local/backend_test.go
Previously we forced all remote state backends to be wrapped in a `BackupState` wrapper that generates a local `terraform.tfstate.backup` file before updating the remote state.
This backup mechanism was motivated by allowing users to recover a previous state if user error caused an undesirable change such as loss of the record of one or more resources. However, it also has the downside of flushing a possibly-sensitive state to local disk in a location where users may not realize its purpose and accidentally check it into version control. Those using remote state would generally prefer that state never be flushed to local disk at all.
The use-case of recovering older states can be dealt with for remote backends by selecting a backend that has preservation of older versions as a first-class …
> backend/local: disable local backup of remote state

- Dockerfile
The `MAINTAINER` command has been [deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) from the `Dockerfile` syntax.
This PR moves the content into the `maintainer` label instead.
> Updates deprecated MAINTAINER in Dockerfile

- command/init.go
- config/module/storage.go
- config/module/storage_test.go
Add GetModule for the cli to initialize from a regisry module source.
Storage.GetModule fetches a module using the same detection and
discovery as used by the normal module loading. The final copy is still
done by module.GetCopy to remove vcs files.
> init -from-module

- backend/remote-state/consul/backend_test.go
- backend/remote-state/consul/client_test.go
- vendor/github.com/hashicorp/consul/api/acl.go
- vendor/github.com/hashicorp/consul/api/agent.go
- vendor/github.com/hashicorp/consul/api/api.go
- vendor/github.com/hashicorp/consul/api/coordinate.go
- vendor/github.com/hashicorp/consul/api/kv.go
- vendor/github.com/hashicorp/consul/api/lock.go
- vendor/github.com/hashicorp/consul/api/operator_area.go
- vendor/github.com/hashicorp/consul/api/operator_autopilot.go
- vendor/github.com/hashicorp/consul/api/operator_keyring.go
- vendor/github.com/hashicorp/consul/api/operator_raft.go
- vendor/github.com/hashicorp/consul/api/operator_segment.go
- vendor/github.com/hashicorp/consul/api/semaphore.go
- vendor/github.com/hashicorp/consul/lib/freeport/freeport.go
- vendor/github.com/hashicorp/consul/testutil/server.go
- vendor/github.com/hashicorp/consul/testutil/server_methods.go
- vendor/vendor.json
This is from a commit just after the v1.0.0 release, because it removes
the Porter service dependency for tests. The client api package was not
changed.
Reuses the running consul server for all tests.
Update the lostLockConnection package, since the api client should no
longer lose a lock immediately on network errors.
The updated consul upstream package was last missing piece required for #16098
> update consul packages

- config/module/get_test.go
- config/module/registry.go
- config/module/registry_test.go
It's not always easy or convenient for a web application to determine its own absolute URL to return, so here we pragmatically allow the download source string from a registry to be a path relative to the download endpoint.
Since `X-Terraform-Get` is a `go-getter` string, not all valid values are valid URLs and so we sniff for certain relative-path-looking prefixes in order to decide whether to apply the relative lookup transform.
> config/module: allow registry download sources to be relative paths

- scripts/build.sh
I was struggling to figure out how to build terraform plugins cross-platform. Doing it for terraform itself is quite easy, and I realized eventually that the terraform `build.sh` script just needed a small tweak to work with plugins also.
This patch allows `build.sh` to be used with terraform plugins to easily create cross-platform packages, using the same method as the terraform Makefile:
```
mkdir scripts
curl https://raw.githubusercontent.com/hashicorp/terraform/master/scripts/build.sh -o scripts/build.sh
TF_RELEASE=1 sh -c "scripts/build.sh"  # make bin
```
> Uses current working directory to name the binary

- helper/resource/testing.go
This only affects tests, but basically https://github.com/hashicorp/terraform/pull/16356 introduced `TF_LOG_PATH_MASK` and unintentionally made it _the only way_ to send debug logs to a file.
> helper: Fall back to TF_LOG_PATH instead of os.Stderr

- .travis.yml
- command/e2etest/init_test.go
Pull down the hashicorp/vault/aws module into the current directory with
init.
> e2e test for `init -from-module`

- helper/resource/testing.go
The lack of this patch is currently causing our acceptance tests which leverage subtests (2 in total) to crash, because the log path contains `/` and we're not creating intermediate directories.
> helper: Escape test name in TF_LOG_PATH_MASK

- plugin/discovery/get.go
While the TLS handshakes are a fairly small overhead compared to
downloading the providers, clients in some situation are failing to
complete the TLS handshake in a timely manner. It's unclear if this is
because of heavily constrained clients are stalling while doing the
major crypto operations, or the edge servers are throttling repeated
requests from the same IPs.
This should allow reusing the open TLS connection to the release edge
servers during init.
> Use pooled http client for fetching providers

- builtin/providers/test/provider.go
- builtin/providers/test/resource_with_custom_diff.go
- builtin/providers/test/resource_with_custom_diff_test.go
- helper/schema/backend.go
- helper/schema/provider.go
- helper/schema/provisioner.go
- helper/schema/resource.go
- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
- helper/schema/resource_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
- helper/schema/testing.go
- terraform/diff.go
- terraform/diff_test.go
This is far along enough now that I think putting in a PR is warranted :)
See #8769 for more details!
---
This adds a new object, `ResourceDiff`, to the schema package. This object, in conjunction with a function defined in `CustomizeDiff` in the resource schema, allows for the in-flight customization of a Terraform
diff after the initial diff has been performed.
Use cases for this functionality include:
* Creating diffs off of computed values alone, for when a state transition requires action on a field that cannot be reasonably controlled via config
* Leaning on the provider's API as much as possible when said provider has diff logic of its own (ie: Nomad)
* Vetoing changes to the diff that could not be reasonably carried out (ie: illegal AWS RDS operations) by kicking back an error to …
> helper/schema: Custom diff logic support for providers

- command/meta.go
- commands.go
- website/docs/configuration/environment-variables.html.md
This flag allows to set the Meta.dataDir field, which was not previously possible.
For context: we'd like to be able to run Terraform from a read-only directory. This option allows us to direct all write access to a writable directory elsewhere.
While there, I simplified `"command".Meta.DataDir()`.
> command: Implement the "data-dir" flag.

- website/docs/state/workspaces.html.md
- website/layouts/backend-types.erb
Also cleans up an issue where the sidebar didn't render as originally intended:
Fixes #16530
> Adding `azurerm` to the list of supported backends

- website/docs/state/workspaces.html.md
As Manta backend has now been merged, this should have been done in the same PR - apologises for that
//cc @jbardin
> websites/workspaces: Add Manta to the list of workspace backends

- command/get_test.go
- command/init.go
- command/init_test.go
- config/module/registry.go
- config/module/storage.go
- config/module/tree.go
Make the output for init nice. We can refine this as we go, but this better matches the provider output, and hides the ugly go-getter urls.
Change "Downloading" to 'Initializing" to match the provider loading
dialog.
List each module being loaded.
If a regisry module is being downloaded, list the registry host, and the
version discovered.
Show the source string from the config that is being fetched, rather
than the go-getter url. The full source can be found in the logs for
debugging.
Add much more extensive logging
> update init output

- terraform/context_apply_test.go
- terraform/diff.go
- terraform/diff_test.go
- terraform/test-fixtures/apply-unstable/main.tf
We previously didn't compare values but had a TODO to start doing so, which we then recently did. unfortunately it turns out that we _depend_ on not comparing values here, because when we use EvalCompareDiff (a key user of Diff.Same) we pass in a diff made from a fresh re-interpolation of the configuration and so any non-pure function results (timestamp, uuid) have produced different values.
> core: don't compare attribute values in Diff.Same

- helper/schema/field_writer_map.go
- helper/schema/field_writer_map_test.go
There are situations where one may need to write to a set, list, or map
more than once per single TF operation (apply/refresh/etc). In these
cases, further writes using `Set` (example: `d.Set("some_set", newSet)`)
currently create unstable results in the set writer (the name of the
writer layer that holds the data set by these calls) because old keys
are not being cleared out first.
This bug is most visible when using sets. Example: First write to set
writes elements that have been hashed at 10 and 20, and the second write
writes elements that have been hashed at 30 and 40. While the set
length has been correctly set at 2, since a set is basically a map (as
is the entire map writer) and map results are non-deterministic, reads
to this set will now deliver unstable results in a random but …
> helper/schema: Clear existing map/set/list contents before overwriting

- website/docs/backends/types/azurerm.html.md
This PR includes a documentation fix for the access configuration variables of the azurerm backend. The prefix `arm_` has been added to match the implementation.
> Fix documentation of azurerm backend advanced access variables

- backend/remote-state/azure/backend.go
It looks like the ARM_ENVIRONMENT was ignored. According to the documentation, this variable can be set instead of manually setting it in the resource.
> Get the enviroment from the environment variable

- terraform/context_import_test.go
- terraform/test-fixtures/import-provider-alias/main.tf
- terraform/transform_provider.go
A missing provider alias should not be implicitly added to the graph.
Run the AttachaProviderConfigTransformer immediately after adding the
providers, since the ProviderConfigTransformer should have just added
these nodes.
> don't add missing provider aliases to the graph

- builtin/providers/test/resource.go
- builtin/providers/test/resource_gh12183.go
- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
- helper/schema/schema.go
We have seen a number of bugs in the past involving `Set("field_name", invalid data)` in the past. These are really hard to discover without explicit error checks.
It is not desired to add error checks to each `Set()` as it would make the CRUD unnecessarily verbose. Making `panic` default seems a bit too aggressive as it would affect user's experience negatively (crash).
This is a compromise which allows us to be strict where we can afford to be strict - e.g. when running acceptance tests for providers and keep the existing behaviour as is for users (i.e. avoid crashes at runtime).
I don't think it's necessary to document this - we can just make `TF_SCHEMA_PANIC_ON_ERROR=1` default in `make testacc` of all providers.
> helper/schema: Opt-in panic on invalid ResourceData.Set

- backend/remote-state/gcs/backend.go
- backend/remote-state/gcs/backend_test.go
I initially thought listing workspaces with the GCS backend was broken, but it turns out I just omitted the trailing `/` in my prefix path. Creating new workspaces worked fine, but I was unable to list or select existing workspaces:
```
$ grep -A4 gcs main.tf                        
backend "gcs" {                                                        
project = "planet-k8s-staging"                                      
bucket  = "terraflop-state"                            
prefix  = "terraflop/etcd"          
}                                                                                 
$ tf version                            
Terraform v0.11.0-beta1 (23caaf9feb50d566329f5b4aa07a57da8cd6f448)     
+ provider.google (unversioned)                                
+ provider.ignition …
```
> Support GCS backend prefixes without trailing /

- terraform/transform_provider.go
Our new resource-to-provider matching is stricter about explicitly matching aliases when config is present (no longer automatically inherited) and with locating providers to destroy removed resources.
With this in mind, this is an attempt to expand slightly on this error message now that users are more likely to see it.
In future it would be nice to do some explicit validation of this a bit closer to the UI, so we can have room for more explanatory text, but this additional messaging is intended to help users understand why they might be seeing this message after removing a provider configuration block from configuration, whether directly or as a side-effect of removing a module.
Here's how it looks with actual values interpolated:
```
* module.child.aws_instance.foo: configuration for …
```
> core: more explanation when a provider block cannot be found

- terraform/context_apply_test.go
- terraform/eval_state.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_plan.go
- terraform/node_module_removed.go
- terraform/node_output_orphan.go
- terraform/state.go
- terraform/terraform_test.go
- terraform/transform_orphan_output.go
- terraform/transform_reference.go
- terraform/transform_removed_modules.go
The OrphanOutputTransformer couldn't find orphaned modules, because it was only looking at the config. Walk the state to find all orphaned outputs and modules.
Create a NodeModuleRemoved and an associated EvalDeleteModule to track
the module in the graph then remove it from the state. The
NodeModuleRemoved dependencies are simply any other node which contains
the module path as a prefix in its path.
This could have probably been done much easier as a step in pruning the
state, but modules are going to have to be promoted to full graph nodes
anyway in order to support count.
> Remove modules and module outputs from state

- website/docs/configuration/providers.html.md
- website/docs/configuration/variables.html.md
- website/docs/modules/usage.html.markdown
- website/upgrade-guides/0-11.html.markdown
* Revise a little the provider configuration docs, to standardize some terminology that we can use elsewhere.
* Some additional clarifications on module/provider interactions in the module usage page.
* Re-title the variables configuration page as "Input Variables" to align with how we refer to these in the Getting Started guide and the module registry. (This is actually more of a forward-looking thing to give us a discriminator for when we need to use the generic term "variables" to refer to all of the things in the interpolation scope as we revamp the docs for the new HCL version.)
* Give a specific example on how one can hoist child module provider configurations up into the root, to go along with our recommendation that people refactor their configurations to do so.
> More documentation revisions for 0.11

- config/config.go
- config/config_test.go
- config/test-fixtures/validate-missing-provider/main.tf
- terraform/transform_provider.go
Missed validation when a module names a provider that doesn't exist. Catch the error in validation, and remove the panic.
This will also be caught during graph transformation in the next iteration of the provider handling code.
> Fix panic with invalid module providers

- terraform/context_apply_test.go
- terraform/transform_provider.go
The provider name coming from ProvidedBy may be resolved if it only
exists in the state. Make sure to strip the module and provider
prefixes for the provider name when adding missing providers.
> normalize missing provider names

- main.go
Now that we're expecting "credentials" blocks in the config (with auth tokens for private module registries, etc) we should not print out the config contents into the log, or else people will probably end up accidentally disclosing their credentials when sharing debug output with us, or will be reluctant to share debug output.
> main: don't print the CLI config into the logs

- website/upgrade-guides/0-11.html.markdown
* Add some previously-missing `hcl` syntax highlighting annotations to existing code blocks
* Talk specifically about outputs referencing resources where `count = 0`, since that seems to be a common error based on 0.11.0-rc1 testing/feedback.
> website: One more round of 0.11 upgrade guide edits

- website/docs/configuration/interpolation.html.md
Examples of chunklist are using a wrong function name
> Fix chunklist examples typo

- website/docs/configuration/providers.html.md
I tried to follow `terraform-provider-NAME-vX.Y.Z` pattern with terraform 0.10.7 and it was unable to locate the provider.
I checked the filenames of standard providers and concluded that the proper name is `terraform-provider-NAME_vX.Y.Z`
I also see that the fixed schema worked fine, terraform successfully executed `init` command.
The fix is general and does not attribute to a particular version
> Fix the naming scheme for terraform provider

- .github/ISSUE_TEMPLATE.md
By wrapping the instruction portions in comments we can get a cleaner rendering of the issue if a user posts it without removing the instructions first.
The content is otherwise the same as before.
> Issue template: comment out the instruction portions

- config/module/registry.go
- config/module/registry_test.go
- config/module/storage.go
- registry/regsrc/friendly_host.go
- registry/regsrc/friendly_host_test.go
- registry/regsrc/module.go
- registry/regsrc/module_test.go
Some basic cleanup to do before refactoring the config/module source. 
The registry's requirements for FriendlyHost are slightly different that those of terraform itself. Rather than try and unify the concepts of FriendlyHost and svchost.Hostname, I'm going to leave the FriendlyHost api as-is, and add `SvcHost` method to return a svchost.Hostname. The only test checks now omitted or changes from the original set are where a punycode source was allowed even though it was not valid.
> Clean up regsrc module

- backend/local/backend_local.go
- command/command.go
- command/init.go
- command/providers.go
- command/validate.go
- command/validate_test.go
- config/config.go
- config/config_test.go
- config/module/tree.go
- config/module/tree_test.go
- helper/resource/testing.go
- helper/resource/testing_config.go
- terraform/context.go
- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/context_refresh_test.go
- terraform/context_validate_test.go
When `count` is set to anything other than `1` on a resource it is necessary to access attributes of the resource via the splat syntax to get a list of all of the results.
This has always been an error, but due to the earlier bug that errors were swallowed for outputs there are some existing configs that have erroneous outputs that now fail in 0.11.0. While in some cases this problem is immediately obvious due to Terraform failing to even plan, it's problematic when the dynamic value of the count _happens to be_ `1` on the first plan after an upgrade, but then later becomes some other value in a subsequent change: now something that used to work doesn't anymore, and you've already updated your state to 0.11.0 and so downgrading isn't an option.
This change is intended as _part_ of the fix …
> Warn about potential errors when output interpolation expressions use a counted resource like a singleton

- config/config.go
- config/config_test.go
- config/test-fixtures/output-no-warnings/main.tf
- config/test-fixtures/output-warnings/main.tf
- terraform/eval_output.go
- terraform/features.go
Add a `TF_WARN_OUTPUT_ERRORS` flag to make output interpolation errors non-fatal.
Also includes a test fixture left from the previous PR to verify that the warning are present.
> Add flag to opt out of module output errors

- terraform/test-fixtures/transform-provider-implicit-module/main.tf
- terraform/test-fixtures/transform-provider-implicit-module/mod/main.tf
- terraform/test-fixtures/transform-provider-invalid/main.tf
- terraform/test-fixtures/transform-provider-invalid/mod/main.tf
- terraform/transform_provider.go
- terraform/transform_provider_test.go
Allow a module to receive a specific provider, even if there is no config block.
Fixes #16612
> Allow overriding an implicitly used provider

- website/docs/modules/usage.html.markdown
- website/intro/getting-started/modules.html.md
* Fix typo in [modules doc](https://www.terraform.io/docs/modules/usage.html#source). `-update` is not a valid `init` flag in `terraform 0.11.0`
> Rename -update to -upgrade.

- website/docs/configuration/providers.html.md
It was noted in #16401 that if the `plugin_cache_dir` doesn't exist, Terraform will still cache plugins to the filesystem, but it won't hardlink them and the `plugin_cache_dir` won't get created. Terraform could create the directory automatically, but I'm not sure which part of the code is the best place to do that, so it would at least be nice to document this behavior until code to create the directory is implemented 😄
> Document that plugin_cache_dir must already exist

- command/apply.go
- command/apply_test.go
- command/console.go
- command/meta.go
- command/plan.go
- command/plan_test.go
- commands.go
This adds cancellation support to the plan command. While plans are usually fairly uneventful, it can be useful to be able to cancel the plan during operation.
We also fix up the apply test to make it not rely on a sleep for verification. 
Also fixes #16652 which demonstrated the lack of cancellation waiting for a lock during plan.
> Make plan command cancellable 

- helper/validation/validation.go
- helper/validation/validation_test.go
`StringMatch` returns a validation function that can be used to match a
string against a regular expression. This can be used for simple
substring validations or more complex validation scenarios. Optionally,
an error message can be returned so that the user is returned a better
error message other than that their field did not match a regular
expression that they might not be able to understand.
> helper/validation: Add StringMatch

- builtin/provisioners/salt-masterless/resource_provisioner.go
current implementation doesn't wait until the salt download, install, apply commands are finished.
So current version is not working due to this. also piped output from this command to stdout.
> wait until salt-masterless commands are finished

- website/docs/commands/push.html.markdown
It's important to match the version of local Terraform with the remote Terraform version in Terraform Enterprise when using the "terraform push" command, or else the uploaded configuration package may not be compatible.
> website: "terraform push" version matching requirement

- builtin/providers/terraform/data_source_state.go
- website/docs/providers/terraform/d/remote_state.html.md
This should close out the existing PRs for this change in the soon to be defunct terraform-provider-terraform repo:
* https://github.com/terraform-providers/terraform-provider-terraform/pull/16
* https://github.com/terraform-providers/terraform-provider-terraform/pull/9
> Deprecate the environment key in favour of workspace in remote state

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
Added a interpolation function `timeadd(time, duration)`.
There is no way to designate relative time to the field [expiration_time](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#expiration_time) of google_sql_database_instance.
In our case, we want to allow access from the host which executes terraform only while  provisioning steps (e.g. grant users' privileges, create tables) and deny any access after that because it can be access via [CloudSQL proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy?hl=en).
With this function, we can specify expiration time e.g. after 1 hour as follows:
```
ip_configuration {
require_ssl = true
authorized_networks {
expiration_time = "${timeadd(timestamp(), "1h")}"
name            = "provisioner"
value           = …
```
> timeadd interpolation function

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
- website/docs/configuration/interpolation.html.md
This is the second half of the puzzle which was previously https://github.com/hashicorp/terraform/pull/5675.
This addresses issue https://github.com/hashicorp/terraform/issues/3148 which was moved to https://github.com/terraform-providers/terraform-provider-aws/issues/30.
The first half is https://github.com/terraform-providers/terraform-provider-aws/pull/2219 which enables you to get (Windows) password data from an instance.  This data is encrypted, and we don't want the decrypted password (or private key) to end up in the state file.
So to get around this, I added interpolation functions to allow decryption of this password data when setting the password in the connection section.  Since that section is not stored in the state file, we're ok.
So, for example, once both of these PR's are …
> Interpolation functions rsaencrypt and rsadecrypt

- backend/remote-state/s3/backend.go
- website/docs/backends/types/s3.html.md
Without the possibility to skip this check, it’s not possible to use a custom region with an S3 compatible solution.
> Add an option to skip the region check

- config/module/module_test.go
- website/docs/registry/api.html.md
This adds documentation of the public API endpoints for browsing and searching modules.
These are not actually new, we just released with a minimal set of endpoints in our "officially supported" API that were sufficient for terraform CLI to use the registry.
Now we have experience with a few different consumers, these endpoints are important for basic discovery and, for example, are used in Terraform Enterprise, so warrant standardising.
I tweaked a test here to verify that discovery code actually works regardless of whether the discovery document has a trailing slash. It does thanks to `url.ResolveReference`. we can change it back if there is no value in it - I was in two minds about whether to leave it anyway. We _could_ change the actual discovery documents to have no slash and it …
> Update registry API docs with browse and search

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- backend/local/backend_refresh.go
- command/apply.go
- command/apply_test.go
- command/meta.go
- command/plan.go
- command/plan_test.go
- terraform/resource_provider_mock.go
The backends need to specifically watch for and handle context cancellation because the context received for the operation is disjoint from the context used in the RunningOperation. This was only implemented in the apply operation, so the other operations couldn't be fully cancelled.
> Fully enable shutdown for plan and refresh in the local backend

- backend/remote-state/gcs/backend.go
- backend/remote-state/gcs/backend_test.go
- backend/testing.go
- The backend was creating the bucket named in the configuration if it didn't exist. We don't allow other backends to do this, because these are not managed resources that terraform can control.
- Have the test fixtures create their own buckets, so parallel tests don't collide, and leftover buckets don't cause future failures. This also properly removes test buckets regardless of contents.
- Add a test that fails the condition that #16852 was fixing. This is simply looking up a locked remote state, since a backend may need to take a lock to create a non-existent state. Reading an existing locked remote state should succeed.
- Match the operation of the google provider, by accepting either a file path or contents for both `credentials` and `GOOGLE_CREDENTIALS`
> gcs provider fixes

- config/config.go
- config/test-fixtures/output-no-warnings/main.tf
There should be no warning when accessing a resource's count value
directly in an output.
Fixes #16864
> accessing count directly in an output should is OK

- command/apply.go
- command/console.go
- command/graph.go
- command/import.go
- command/init.go
- command/meta_new.go
- command/plan.go
- command/providers.go
- command/push.go
- command/refresh.go
- command/validate.go
- config/config.go
- config/config_test.go
Previously we required callers to separately call `.Validate` on the root module to determine if there were any value errors, but we did that inconsistently and would thus see crashes in some cases where later code would try to use invalid configuration as if it were valid.
Now we run `.Validate` automatically after config loading, returning the resulting diagnostics. Since we return a `tfdiags.Diagnostics` here, it's possible to return both warnings and errors.
We return the loaded module even if it's invalid, so callers are free to ignore returned errors and try to work with the config anyway, though they will need to be defensive against invalid configuration themselves in that case.
As a result of this, all of the commands that load configuration now need to use diagnostic printing to …
> command: Always validate config as part of loading it

- website/docs/backends/types/s3.html.md
Users commonly ask how the S3 backend can be used in an organization that splits its infrastructure across many AWS accounts.
We've traditionally shied away from making specific recommendations here because we can't possibly anticipate the different standards and regulations that constrain each user. This new section attempts to
describe one possible approach that works well with Terraform's workflow, with the goal that users make adjustments to it taking into account their unique needs.
Since we are intentionally not being prescriptive here -- instead considering this just one of many approaches -- it deviates from our usual active writing style in several places to avoid giving the impression that these are instructions to be followed exactly, which in some cases requires the use of …
> website: guide for using the S3 backend with multiple AWS accounts

- backend/local/counthookaction_string.go
- backend/operationtype_string.go
- config/configschema/nestingmode_string.go
- config/resource_mode_string.go
- helper/schema/getsource_string.go
- helper/schema/valuetype_string.go
- terraform/graphtype_string.go
- terraform/instancetype_string.go
- terraform/walkoperation_string.go
- tfdiags/severity_string.go
**Context:** When setting up a new development environment the latest version of `stringer` is installed. This commit 26 days ago  (https://github.com/golang/tools/commit/bd4635fd25596cdd56c1fb399c53b351d1a81f2d) introduces functionality that changes generated files to use `strconv` instead of `fmt`.
After performing a `go get` and `make` or `make dev`, the changes in this pull request are made before any development occurs. This PR brings the auto-generated files up to date.
**Caveats:** If we don't want to do this, then we'll need to "pin" a version of stringer.
> [Update] Stringer replaces fmt with strconv

- helper/resource/testing.go
- helper/resource/testing_test.go
Looks like while we were checking errors correctly when ExpectError was
set, we weren't checking for the *absence* of an error, which is should
be checked as well (no error is still not the error we are looking for).
Added a few more tests for ExpectError as well.
> helper/resource: Fail tests with no error that have ExpectError set

- vendor/github.com/hashicorp/go-version/version.go
- vendor/vendor.json
We required updated version of `go-version`, because we have deployment of mariadb that has `~` in version name: https://github.com/hashicorp/go-version/commit/43575a7136563760458ce6756b50ac0ab7245adb
> vendor: github.com/hashicorp/go-version

- command/import.go
- command/import_test.go
- command/test-fixtures/empty/README
If users run `terraform import` in a directory with no Terraform configuration files, it's likely that they've made a mistake either by being in the wrong directory or forgetting to use the `-config` option on the command line.
To help users find their mistake in this case, we'll now produce a specialized error message for this situation:
Error: No Terraform configuration files
The directory /home/user/example does not contain any Terraform
configuration files (.tf or .tf.json). To specify a different
configuration directory, use the -config="..." command line option.
While here, this also converts some of the other existing messages to diagnostics so that we can show any configuration warnings along with the error message, and move towards the new standard error presentation.
This was …
> command: show a special error message when importing in an empty dir

- terraform/resource.go
- terraform/resource_test.go
The bounds checking in `ResourceConfig.get()` was insufficient: it detected when the index was greater than or equal to `cv.Len()` but not when the index was less than zero. If the user provided an (invalid)
configuration that referenced `"foo.-1.bar"`, the provider would panic, which is never a good thing to do.
> ResourceConfig.get: Check for negative slice indexes.

- website/docs/registry/private.html.md
- website/layouts/docs.erb
- website/layouts/guides.erb
This updates links on the menu with a few changes
- renames `classic` to `legacy`
- updates the links from `enterprise` to `enterprise-legacy`
- updates the links from `enterprise-beta` to `enterprise`
> Updating links to TFE docs

- terraform/diff.go
- terraform/eval_diff.go
- terraform/eval_diff_test.go
- terraform/terraform_test.go
Addresses https://github.com/terraform-providers/terraform-provider-aws/issues/1522, https://github.com/hashicorp/terraform/issues/15939
Previously, if an ignored resource attribute was updated, any other attributes related to that ignored resource were added to the diff, **specifically resource attributes that didn't change**.  
Please be aware that this doesn't fix redundant attributes if IgnoreChanges are not used.
FYI @nateww @rcarmstrong
> Ignore redundant IgnoreChanges attributes

- builtin/provisioners/habitat/resource_provisioner.go
- website/docs/provisioners/habitat.html.markdown
**Context:** Per @bixu's comment (https://github.com/hashicorp/terraform/pull/16280#issuecomment-350208983) on the original Habitat Provisioner PR, @nsdavidson and I moved forward with adding the ability to use private Habitat origins that require `HAB_AUTH_TOKEN`.
**This PR:** 
* Adds the `build_auth_token` option in terraform and necessary functionality through which a user's `HAB_AUTH_TOKEN` can be passed.
* Updates the docs
> Adds "build_auth_token" option to Habitat Provisioner

- website/docs/modules/sources.html.markdown
The current version of TFE can use centrally-managed SSH keys to access modules from git repos, which is better than embedded machine user credentials for most use cases. 
Also, as I understand it, any other CI-like systems can use the same mechanism TFE uses for accessing private Git-sourced modules, with the `GIT_SSH_COMMAND` env var, which might be preferable depending on your worker provisioning process.
> docs: Clarify the use of private github repos with TFE

- helper/customdiff/compose.go
- helper/customdiff/compose_test.go
- helper/customdiff/computed.go
- helper/customdiff/computed_test.go
- helper/customdiff/condition.go
- helper/customdiff/condition_test.go
- helper/customdiff/doc.go
- helper/customdiff/force_new.go
- helper/customdiff/force_new_test.go
- helper/customdiff/testing_test.go
- helper/customdiff/validate.go
- helper/customdiff/validate_test.go
The `CustomizeDiff` functionality in `helper/schema` is powerful, but directly writing single `CustomizeDiff` functions can obscure the intent when a number of different, orthogonal diff-customization behaviors are required.
This new library provides some building blocks that aim to allow a more declarative form of `CustomizeDiff` implementation, by composing a number of smaller operations. For example:
```go
&schema.Resource{
// ...
CustomizeDiff: customdiff.All(
customdiff.ValidateChange("size", func (old, new, meta interface{}) error {
// If we are increasing "size" then the new value must be
// a multiple of the old value.
if new.(int) <= old.(int) {
return nil
}
if (new.(int) % old.(int)) != 0 {
return fmt.Errorf("new size value must be an integer multiple of old value %d", …
```
> helper/customdiff: Helper functions for CustomizeDiff

- examples/README.md
- website/layouts/docs.erb
Don't merge this for the moment - I need to make similar changes in the Provider documentation.
- Renaming `Microsoft Azure` -> `Azure` at Microsoft's request, also bumping it up the sidebar
- Removing the legacy Azure (V1 / old portal) Provider from the Sidebar
- Adding a missing hint to the code block
> Renaming the Azure Provider

- helper/schema/resource_data.go
- helper/schema/resource_diff.go
- helper/schema/schema.go
- helper/schema/schema_test.go
Add a test case for this situation where a resource was using an empty string to indicate an unset computed value. This may have been too common in providers, so we need to evaluate reverting that behavior. 
Reverts one of the changes from 6a4f7b0 (#14887), which broke empty strings
being seen as unset for computed values (this breaks a number of newer tests).
Referencing https://github.com/terraform-providers/terraform-provider-aws/issues/2348
> Restore ability for an empty string to be considered unset in a computed value

- website/guides/writing-custom-terraform-providers.html.md
We succeeded, disable partial mode. This causes Terraform to save ~~save~~ all fields again.
> Small typo fix in provider documentation

- config/module/storage.go
The module related logs and errors should reference the full module name
including the source host.
> use the full module name with host for errors

- backend/remote-state/s3/backend.go
Wire up the terraform-aws-provider config's S3ForcePathStyle so a data "terraform_remote_state" can also set this config option.  Useful when using the endpoint config option.
> expose S3ForcePathStyle to s3 remote state config

- command/init_test.go
- command/meta.go
- command/meta_backend.go
- command/meta_backend_migrate.go
- command/meta_backend_test.go
The duplicate prompts can be confusing when the user confirms that a
migration should happen and we immediately prompt a second time for the
same thing with slightly different wording. The extra hand-holding that
this provides for legacy remote states is less critical now, since it's
been 2 major release cycles since those were removed.
Only check for input twice in the meta.confirm method. This prevents an
errant newline from aborting the run while allowing Terraform to exit if
there is no input available. We don't just check for a tty, since we
still rely on being able to pipe input in for testing.
Remove the redundant confirmation loops in the migration code, and only
use the confirm method.
fixes #16922
> remove extra backend migration prompts

- command/plugins.go
This is an improvement for this issue. https://github.com/hashicorp/terraform/issues/16874
simple improvement that adds the output of overridden providers from the `.terraformrc` file as output in debug mode allowing you to see that they exist.
> [Add] Pathing and Override to DEBUG Command

- config/interpolate_funcs.go
- config/interpolate_funcs_test.go
Fixes #17041
```
[terraform@check-substr-offset x]$ go test -v ./config -run TestInterpolateFuncSubstr
=== RUN   TestInterpolateFuncSubstr
=== RUN   TestInterpolateFuncSubstr/${substr("foobar",_0,_0)}
=== RUN   TestInterpolateFuncSubstr/${substr("foobar",_0,_-1)}
=== RUN   TestInterpolateFuncSubstr/${substr("foobar",_0,_3)}
=== RUN   TestInterpolateFuncSubstr/${substr("foobar",_3,_3)}
=== RUN   TestInterpolateFuncSubstr/${substr("foobar",_-3,_3)}
=== RUN   TestInterpolateFuncSubstr/${substr("",_0,_0)}
=== RUN   TestInterpolateFuncSubstr/${substr("",_1,_0)}
=== RUN   TestInterpolateFuncSubstr/${substr("foo",_-4,_-1)}
panic: runtime error: slice bounds out of range [recovered]
panic: runtime error: slice bounds out of range
goroutine 36 [running]:
testing.tRunner.func1(0xc4202a00f0) …
```
> Fix panic with substr interpolation function by invalid offset

- terraform/context_plan_test.go
- terraform/eval_provider_test.go
- terraform/test-fixtures/plan-close-module-provider/main.tf
- terraform/test-fixtures/plan-close-module-provider/mod/main.tf
- terraform/transform_provider.go
`CloseProviderTransformer` wasn't using the full provider when creating
the graph node, so the `Close` wasn't actually being called on the
provider.
fixes #17023
> Close providers

- command/init.go
- command/init_test.go
- command/internal_plugin.go
- command/internal_plugin_list.go
- command/internal_plugin_test.go
- command/plugins.go
- command/test-fixtures/init-internal/main.tf
Internal plugins were always listed in the set of missing plugins, and filtered out while trying to fetch the plugins. If missing plugins were not going to be downloaded at all because of the `-plugin-dir` flag, then the internal plugins still being populated in the missing set would raise an error.
Filter internal plugins out in `missingPlugins`, so we don't attempt to locate them at all.
Fixes #16994
> -plugin-dir short-circuits discovery of internal plugins

- command/init.go
- command/init_test.go
- terraform/context.go
- terraform/state.go
The init command needs to parse the state to resolve providers, but
changes to the state format can cause that to fail with difficult to
understand errors. Check the terraform version during init and provide
the same error that would be returned by plan or apply.
Fixes #16910
> check state version during init

- communicator/ssh/provisioner.go
- communicator/ssh/ssh_test.go
- terraform/eval_validate.go
- vendor/golang.org/x/crypto/ssh/agent/client.go
- vendor/golang.org/x/crypto/ssh/agent/server.go
- vendor/golang.org/x/crypto/ssh/buffer.go
- vendor/golang.org/x/crypto/ssh/certs.go
- vendor/golang.org/x/crypto/ssh/channel.go
- vendor/golang.org/x/crypto/ssh/cipher.go
- vendor/golang.org/x/crypto/ssh/client.go
- vendor/golang.org/x/crypto/ssh/client_auth.go
- vendor/golang.org/x/crypto/ssh/common.go
- vendor/golang.org/x/crypto/ssh/connection.go
- vendor/golang.org/x/crypto/ssh/doc.go
- vendor/golang.org/x/crypto/ssh/handshake.go
- vendor/golang.org/x/crypto/ssh/kex.go
- vendor/golang.org/x/crypto/ssh/keys.go
- vendor/golang.org/x/crypto/ssh/messages.go
- vendor/golang.org/x/crypto/ssh/mux.go
- vendor/golang.org/x/crypto/ssh/server.go
- vendor/golang.org/x/crypto/ssh/session.go
- vendor/golang.org/x/crypto/ssh/streamlocal.go
- vendor/golang.org/x/crypto/ssh/tcpip.go
- vendor/golang.org/x/crypto/ssh/transport.go
- vendor/vendor.json
- sort ssh agent signers by requested id
It's becoming more common for users to have many ssh keys loaded into an
agent, and with the default max auth attempts of an openssh server at 6,
one often needs to specify which id to use in order to avoid a `too many
authentication failures` error.
Add a connection field called `agent_identity` which will function
similarly to the ssh_config IdentityFile when used in conjunction with
an ssh agent. This uses `agent_identity` rather than `identity_file` to
specify that the file is not used directly for authentication, rather
it's used to choose which identity returned from the agent to
authenticate with first.
This feature tries a number of different methods to match the agent
identity. First the provisioner attempts to read the id file and extract …
> ssh connection `agent_identity`

- website/docs/backends/types/gcs.html.md
- website/docs/state/workspaces.html.md
Also add the term "workspaces" to the `prefix` documentation.
Fixes #16911
> add gcs to the backends that support workspaces in the documentation

- command/init_test.go
- command/plugins.go
- website/docs/commands/init.html.markdown
Remove the recorded -plugin-dir during init if the flag is not provided.
fixes #16904
> allow init to reset -plugin-dir

- backend/remote-state/gcs/backend.go
- backend/remote-state/gcs/backend_state.go
- backend/remote-state/gcs/backend_test.go
- backend/remote-state/gcs/client.go
- website/docs/backends/types/gcs.html.md
Currently all files in GCS are transparently encrypted at rest using Google's keys, and IAM/ACL can be used to restrict access to GCS buckets. Allowing state files in GCS to be encrypted with a custom key provides an additional layer of defense around sensitive Terraform state.
Objects created with a customer supplied encryption key can only be read when the key used for creation is passed in with the read request. See https://github.com/hashicorp/terraform/issues/16836 for further details.
> Support 'customer supplied encryption keys' in the GCS backend

- vendor/github.com/zclconf/go-cty/cty/types_to_register.go
- vendor/github.com/zclconf/go-cty/cty/value_ops.go
- vendor/vendor.json
Update `go-cty` to enable decode a gob encoded response from provider even if the provider uses vendored version of `go-cty`.
Refs: https://github.com/hashicorp/terraform/issues/16423#issuecomment-355560949
Refs: https://github.com/zclconf/go-cty/commit/14e23b14828dd12cc7ae0956813c7e91a196e68f
```
[terraform@master]$ govendor fetch github.com/zclconf/go-cty/...
```
> vendor: update zclconf/go-cty

- backend/local/backend_refresh.go
The condition in line 109 could never evaluate to true because the error returned from tfCtx.Refresh() was assigned to a different variable.
This is a follow-up to #16833.
> Handle refresh errors.

- backend/remote-state/s3/client.go
- builtin/provisioners/chef/resource_provisioner.go
- command/meta_backend.go
- command/plugins_lock.go
- plugin/discovery/find.go
- plugin/discovery/get.go
- registry/client.go
- svchost/disco/disco.go
- terraform/plan.go
Fixes #17103
The valid levels of logging are `TRACE`, `DEBUG`, `INFO`, `WARN` or `ERROR`.
However, there are some code using `[WARNING]` (not `[WARN]`).
I fixed all loggig code using `WARNING` to `WARN` except for `vendor/` dir.
> Fix log level `WARNING` to `WARN`

- backend/remote-state/s3/backend_state.go
- backend/remote-state/s3/backend_test.go
Ensure that the prefix is only split off a single time when the
workspace_key_prefix is a substring of the workspace or key name.
Fixes #17083
> only split the prefix string once from the s3 key

- helper/structure/normalize_json_test.go
In https://github.com/terraform-providers/terraform-provider-aws/pull/2935,
we have been cleaning code duplication by benefiting from the
"NormalizeJsonString" present in the "structure" helper.
It appears that tests in the AWS provider are covering more use-cases,
which are added in this work.
> Added more use-cases to normalize_json tests

- registry/client.go
- registry/client_test.go
The disco package doesn't return errors, and a nil value indicates that
the input isn't valid. Always check for nil.
Fixes #17119
> the trailing slash check caused a nil dereference

- config/config.go
- terraform/context_apply_test.go
- terraform/node_resource_apply.go
- terraform/test-fixtures/apply-provisioner-interp-count/provisioner-interp-count.tf
Previously we would interpolate the count config (`ResourceConfig.RawCount`) only while preparing to dynamic-expand aggregate resource nodes. This is problematic because we do not dynamic-expand any resource nodes during the apply walk, and so previously the count value was not available for interpolation during apply and would result in an error.
Now we interpolate `RawCount` once for each resource we visit during the apply walk -- even though that redundantly interpolates the same config multiple times when `count` > 1 -- to ensure that it's available by the time we interpolate any remaining expressions in the config and any expressions within `connection` and `provisioner` blocks.
This error was masked by us sharing a single `RawConfig` instance between the plan and apply walks when …
> core: interpolate the count config during the apply walk

- terraform/diff.go
- terraform/eval_diff.go
- terraform/eval_diff_test.go
- terraform/terraform_test.go
Revert the changes from #16780, but improve the diff behavior to match the intent of that PR.
Containers (maps, lists, sets) in an InstanceDiff need to be handled in
their entirety.  Unchanged values cannot be filtered out from diffs, as
providers expect attribute containers to be complete.
If a value in ignore_changes maps to a single key in an attribute
container, and there are other changes present, that ignored value must
be included in the diff as well. If there are no other changes outside of the ignored values, then all of the attributes can be removed from the diff.
Fixes #17117
>  don't ignore partial containers in diffs

- website/docs/configuration/interpolation.html.md
Documentation Update: Fix the anchor present in the docs for `file` function that points to the section explaining the content of the path variable.
> Fix path information anchor in interpolation docs

- command/workspace_command.go
Fixes #17165 
```
$ terraform workspace --help
Usage: terraform workspace
Create, change and delete Terraform workspaces.
Subcommands:
show      Show the current workspace name.
list      List workspaces.
select    Select a workspace.
new       Create a new workspace.
delete    Delete an existing workspace.
Subcommands:
delete    Delete a workspace
list      List Workspaces
new       Create a new workspace
select    Select a workspace
show      Show the name of the current workspace
```
```
$ terraform workspace --help
Usage: terraform workspace
Create, change and delete Terraform workspaces.
Subcommands:
delete    Delete a workspace
list      List Workspaces
new       Create a new workspace
select    Select a workspace
show      Show the name of the current workspace
```
> Remove duplicated help messages from `workspace --help`

- state/remote/http.go
- state/remote/http_test.go
Apache mod_dav returns 201 (created) and 204 (no content) during PUTs;
treat these as valid responses when using Apache as a http backend.
> allow HTTP 201 & 204 when storing remote state

- website/intro/getting-started/outputs.html.md
It's just a fix for a small typo.
> website: fix typo in getting started guide

- website/docs/modules/create.html.markdown
When writing an example for a submodule, the example should be placed in
`examples/{example name}` instead of
`modules/{module name}/examples/{example name}`.
> website: Clarify submodule examples location

- website/docs/configuration/providers.html.md
- website/docs/modules/usage.html.markdown
Simple update to duplicate the documentation for now. It could also be specified in one configuration page and linked in both places. 😄
> Documentation: Add version specifier information to provider version docs and clarify pessimistic specifier

- svchost/disco/disco.go
Extend the discovery timeout from 4 seconds to 11 seconds. This gives a
little more time for a slow host to response. The duration of 11s
keeps the delay reasonable, and puts it just after the default TLS
handshake timeout of 10s for easier differentiation of the error cases.
Related to #16751
> extend disco timeout

- website/docs/configuration/interpolation.html.md
This PR fixes the positioning of `chunklist()` in the interpolation functions list -- it is currently not in the proper place, alphabetically.
> Fix chunklist() order in interpolations function list

- website/docs/modules/sources.html.markdown
- website/docs/registry/index.html.md
- website/docs/registry/modules/use.html.md
* Adds cross-links within the Module Source page, which should help with navigation.
* Information about how to use modules from the Registry was scattered across a few places, and only fully documented in a somewhat buried page. This pull request removes the other examples, to point to that canonical place.
* Some spelling fixes.
Thanks!
> improve the Module Source documentation

- terraform/context_apply_test.go
- terraform/context_test.go
- terraform/graph_builder_apply.go
- terraform/interpolate.go
- terraform/interpolate_test.go
- terraform/node_local.go
- terraform/node_output.go
- terraform/test-fixtures/apply-provisioner-destroy-locals/main.tf
- terraform/test-fixtures/apply-provisioner-destroy-multiple-locals/main.tf
- terraform/test-fixtures/apply-provisioner-destroy-outputs/main.tf
- terraform/test-fixtures/apply-provisioner-destroy-outputs/mod/main.tf
- terraform/test-fixtures/apply-provisioner-destroy-outputs/mod2/main.tf
- terraform/transform_output.go
- terraform/transform_reference.go
Because destroy time provisioners are not evaluated until the destroy operation, and outputs and locals are "dynamic" in the sense that they can be evaluated on demand, we always need to evaluate them, even during destroy.
Since the destroy-time local and output nodes are no longer a
"destroy" operation, the order of evaluation need to be reversed. Take
the existing `DestroyValueReferenceTransformer` and change it to reverse
the outgoing edges, rather than in incoming edges. This makes it so that
any dependencies of a local or output node are destroyed after
evaluation.
Previously, outputs were removed during destroy from the same
"Applyable" node type that evaluates them. Now that we need to possibly
both evaluate and remove outputs during an apply, we add a new node - …
> Fix destroy-time handling of outputs and local values

- helper/schema/schema.go
- helper/schema/schema_test.go
We already perform the cleanup in here:
https://github.com/hashicorp/terraform/blob/1ba8691f35e7584087a83e26deaf82f0e4d3dada/helper/schema/schema.go#L524-L529
however `CustomizeDiff` was called _before_ this cleanup and therefore any `Get()`, `GetOk()` etc. may have caused a crash.
```
=== RUN   TestSchemaMap_Diff/80-optional,_computed,_empty_string_should_not_crash_in_CustomizeDiff
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x21 pc=0x169bc8b]
goroutine 258 [running]:
testing.tRunner.func1(0xc420476c30)
/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:711 +0x2d2
panic(0x18360e0, 0x1e1b3f0) …
```
> helper/schema: Prevent crash on removal of computed field in CustomizeDiff

- terraform/state.go
There was an upstream change to this vendored lib which introduced a breaking change. To get ahead of this, and to match all other uses of UUID's within HashiCorp tooling, just swap this out for our own `go-uuid` lib. Luckily we already have this vendored as well 💃 .
The panic is a bit ugly, but it appears to be very common in this code path so I just went with it. Failing to generate a UUID for lineage is a major problem, so it seems fitting that this might cause a crash.
> terraform: use hashicorp/go-uuid for lineage generation

- website/docs/configuration/outputs.html.md
- website/intro/getting-started/outputs.html.md
Reason: Make explicitly clear that output variable names must conform to variable naming conventions if they are to be used as input to other modules.
Terraform Version: `0.11.3`
- update the documentation regarding output naming
> Flag output variable naming conventions

- website/docs/registry/api.html.md
In [Registry HTTP API document](https://www.terraform.io/docs/registry/api.html), 
all links for [Pagination](https://www.terraform.io/docs/registry/api.html#pagination) is to `#Pagination` not `#pagination`. Therefore, it is move to top of the page instead the Pagination section.
> website: fix a wrong anchor

- backend/backend.go
- backend/local/backend.go
- backend/local/backend_apply.go
- backend/local/backend_plan.go
- backend/local/backend_refresh.go
- command/apply.go
- command/apply_test.go
- command/meta.go
- command/plan.go
- command/plan_test.go
- command/refresh.go
If the user wishes to interrupt the running operation, only the first
interrupt was communicated to the operation by canceling the provided
context. A second interrupt would start the shutdown process, but not
communicate this to the running operation. This order of events could
cause partial writes of state.
What would happen is that once the command returns, the plugin system
would stop the provider processes. Once the provider processes dies, all
pending Eval operations would return return with an error, and quickly
cause the operation to complete. Since the backend code didn't know that
the process was shutting down imminently, it would continue by
attempting to write out the last known state. Under the right
conditions, the process would exit part way through the writing of the
state …
> Fix race in writing state during hard cancelation

- builtin/provisioners/habitat/resource_provisioner.go
- website/docs/provisioners/habitat.html.markdown
This change allows the Habitat supervisor service name to be
configurable. Currently it is hard coded to `hab-supervisor`.
Signed-off-by: Nolan Davidson <ndavidson@chef.io>
> [provisioner-habitat] Allow custom service name

- builtin/provisioners/habitat/resource_provisioner.go
Currently the provisioner will fail if the `hab` user already exists on
the target system.
This adds a check to see if we need to create the user before trying to
add it.
Fixes #17159
Signed-off-by: Nolan Davidson <ndavidson@chef.io>
> [provisioner-habitat] Detect if hab user exists

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner.go
- builtin/provisioners/habitat/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner_test.go
- communicator/communicator.go
- communicator/communicator_test.go
- communicator/ssh/communicator.go
Previously, provisioners would always retry on error, even when they are not recoverable, e.g. invalid credentials, file not found, etc. They then need to be interrupted, or wait for the timeout which defaults to 5min. The remote-exec retryFunc was also not returning the stored error when it was finally interrupted.
First, this moves all the retryFunc implementations to the communicator package, using the most complete (remote-exec) version as the template. This new implementation also checks of the error implements the communicator.Fatal interface, as a signal to stop retrying. While in practice "retry-able" errors are more likely the exception, signaling off fatal errors is less likely to cause regressions in the providers, since not tagging an error as fatal will only continue the …
> Halt on provisioner errors

- website/docs/backends/types/etcd.html.md
- website/layouts/backend-types.erb
Add missing link to ectdv3.
Update etcd v2 link to the current v2 README, which highlights the pending
deprecation.
fixes #17299
> update etcd documentation links

- communicator/ssh/communicator.go
- communicator/ssh/communicator_test.go
- communicator/ssh/provisioner.go
- terraform/eval_validate.go
- vendor/golang.org/x/crypto/internal/chacha20/chacha_generic.go
- vendor/golang.org/x/crypto/poly1305/poly1305.go
- vendor/golang.org/x/crypto/poly1305/sum_amd64.go
- vendor/golang.org/x/crypto/poly1305/sum_amd64.s
- vendor/golang.org/x/crypto/poly1305/sum_arm.go
- vendor/golang.org/x/crypto/poly1305/sum_arm.s
- vendor/golang.org/x/crypto/poly1305/sum_ref.go
- vendor/golang.org/x/crypto/ssh/certs.go
- vendor/golang.org/x/crypto/ssh/cipher.go
- vendor/golang.org/x/crypto/ssh/client_auth.go
- vendor/golang.org/x/crypto/ssh/common.go
- vendor/golang.org/x/crypto/ssh/knownhosts/knownhosts.go
- vendor/golang.org/x/crypto/ssh/transport.go
- vendor/vendor.json
- website/docs/provisioners/connection.html.markdown
Add `host_key` and `bastion_host_key` fields to the ssh communicator
config for strict host key checking.
Both fields expect the contents of an openssh formated public key. This
key can either be the remote host's public key, or the public key of the
CA which signed the remote host certificate.
Support for signed certificates is limited, because the provisioner
usually connects to a remote host by ip address rather than hostname, so
the certificate would need to be signed appropriately. Connecting via
a hostname needs to currently be done through a secondary provisioner,
like one attached to a null_resource.
fixes #17269
> Verify host keys in ssh connections

- builtin/provisioners/local-exec/resource_provisioner.go
- builtin/provisioners/local-exec/resource_provisioner_test.go
- website/docs/provisioners/local-exec.html.markdown
Addresses #2054.
Added an optional "working_dir" argument. If unspecified, command will execute in current working directory. If specified, path must exist and can be a relative or absolute path.
> local-exec: optional "working_dir" argument

- website/intro/getting-started/variables.html.md
This PR fixes a typo in the `Input Variables`
section of the `Getting Started` documentation.
> Fix typo in Getting Started documentation

- Makefile
The test target will already cover vet, since it's run as part of the
test command now.
Also remove the `go test -i` since it's no longer needed with the new
build cache.
> finish removing vet from the makefile

- backend/local/backend_test.go
- backend/remote-state/azure/backend_test.go
- backend/remote-state/consul/backend_test.go
- backend/remote-state/etcdv3/backend_test.go
- backend/remote-state/gcs/backend_test.go
- backend/remote-state/gcs/client.go
- backend/remote-state/inmem/backend_test.go
- backend/remote-state/manta/backend_test.go
- backend/remote-state/s3/backend_test.go
- backend/remote-state/swift/backend_test.go
- backend/testing.go
The GCS backend uses the object generation as the state ID, but since it's not known until the object is written, it can't be written into the object itself.
Make sure that when we retrieve the lock info, the dummy ID is replaced with the generation ID.
This includes a new backend test helper that unlocks the state by the reported ID, which is the failing test case for this GCS issue. The test helpers were also refactored slightly, and the existing backend test updated to call the new functions. 
fixes #17328
> Fix reported GCS state lock ID

- command/state_list.go
- command/state_list_test.go
- website/docs/commands/state/list.html.md
This change adds an optional `-id` flag to `terraform state
list`. When that flag is used, the output of the command is restricted
to resources whose ID is equal to the value of that flag.
This is useful to answer questions of the type "where in my configs is
this resource". These questions can arise in large Terraform setups,
where an operator looking at resources that exist on the
provider (e.g. via AWS console) may not always be able to tell why a
given resource exists.
> [WIP] Allow searching by resource ID in `terraform state list`.

- website/docs/provisioners/salt-masterless.html.md
**Reasoning for docs update**: grains_file is currently not implemented
**Relevant terraform version**: current
> docs/salt-masterless: remove grains_file

- backend/backend.go
- backend/local/backend.go
- backend/local/backend_apply.go
- backend/local/backend_local.go
- backend/local/backend_plan.go
- backend/local/backend_refresh.go
- command/clistate/state.go
- command/meta_backend.go
- command/meta_backend_migrate.go
- command/taint.go
- command/untaint.go
- command/workspace_delete.go
- command/workspace_new.go
The additional UI code to report the status of obtaining a lock to the user broke the state locking order by having the state refreshed without a lock when creating the initial context. While the lock was still honored for the duration of the actual operations being applied, the command could be starting with a stale version of the state. Most of the time this is not a major issue, since the refresh phase would update the state again, but strict CAS operations used by the Consul backend (and other operations strictly comparing the state.Serial) would fail writing the new state. 
Fixes #17407
We start by simplifying the use of `clistate.Lock` by creating a `clistate.Locker` interface, which stores the context of locking a state, to allow unlock to be called without knowledge of how the …
> Add StateLocker interface to backend operations

- website/docs/commands/push.html.markdown
- website/docs/configuration/terraform-enterprise.html.md
- website/intro/getting-started/remote.html.markdown
- website/layouts/docs.erb
Also:
- In the getting started guide, the TFE content was all tailored to the older
run-locally workflow. I've replaced it with some brief explanation and a link
to the dedicated TFE getting started guide.
- Fixed a sidebar link glitch in the configuration section. (Both "Terraform"
and "Terraform Enterprise" were marked as active if you were on the TFE page.)
- Renamed the "Terraform Enterprise" page "Terraform Push." (Some people have
gotten confused and landed on this page when trying to set up the `atlas`
remote backend.)
> docs: Add deprecation notes to several pages about `terraform push`

- builtin/provisioners/local-exec/resource_provisioner.go
- builtin/provisioners/local-exec/resource_provisioner_test.go
- website/docs/provisioners/local-exec.html.markdown
> provisioner/local-exec: Allow passing env vars to commands

- builtin/providers/terraform/data_source_state.go
- builtin/providers/terraform/data_source_state_test.go
- builtin/providers/terraform/test-fixtures/null_outputs.tfstate
While null values should not normally appear in a state file, we should
filter the values rather than crash.
> filter null output values from state

- terraform/node_resource_refresh.go
While not normally possible, manual manipulation of the state and config
can cause us to end up with a nil config in
evalTreeManagedResourceNoState.
Regardless of how it got here, we can't ever assume the Config field is
not nil, and EvalInterpolate happily accepts a nil RawConfig
Fixes #17509
> Check for nil config in node_resource_refresh

- configs/resource.go
Previously we were erroneously highlighting the resource type name instead.
(This is in the new config loader, which is not yet being used.)
> configs: highlight resource name in diags when invalid

- configs/compat_shim.go
- configs/parser_config_test.go
This relates to the new form for references, like this:
```hcl
depends_on = [aws_instance.foo]
```
...which in the current version of the language must put the reference in quotes:
```hcl
depends_on = ["aws_instance.foo"]
```
The new config loader (not yet in use) has always allowed both of these forms, but before this change the latter form would generate a warning. This applies to `depends_on` and `ignore_changes` in resources, `type` in variables, and `when` and `on_failure` in provisioners. The test assertions about the warnings themselves are removed, but other remaining tests (not visible in the diff here) still parse these to test for their validity.
Although we do still consider this usage deprecated for 0.12, we'll defer actually generating warnings for them until a later minor …
> configs: Disable deprecation warning for quoted keywords/references

- configs/module_merge.go
- configs/module_merge_test.go
- configs/named_values.go
- configs/parser_config.go
- configs/parser_config_test.go
- configs/test-fixtures/invalid-files/variable-bad-default.tf
- configs/test-fixtures/invalid-modules/override-variable-causes-bad-default/base.tf
- configs/test-fixtures/invalid-modules/override-variable-causes-bad-default/override.tf
- configs/test-fixtures/valid-files/variables.tf
(This applies to the new configuration loader, which is not yet in use.)
Previously we just ported over the simple "string", "list", and "map" type hint keywords from the old loader, which exist primarily as hints to the CLI for whether to treat `-var=...` arguments and environment variables as literal strings or as HCL expressions.
However, we've been requested before (e.g. #6254) to allow more specific constraints here because it's generally better UX for a type error to be detected within an expression in a calling `module` block rather than at some point deep inside a third-party module.
To allow for more specific constraints, here we use the type constraint expression syntax defined as an extension within HCL, which uses the variable and function call syntaxes to represent types …
> configs: allow full type constraints for variables

- backend/local/backend_apply.go
- command/apply.go
- command/apply_destroy_test.go
- command/e2etest/primary_test.go
- website/docs/commands/destroy.html.markdown
Since an early version of Terraform, the `destroy` command has always had the `-force` flag to allow an auto approval of the interactive prompt. 0.11 introduced `-auto-approve` as default to `false` when using the `apply` command.
People often use wrappers when automating commands in Terraform, and the inconsistency between `apply` and `destroy` means that additional logic must be added to the wrappers to do similar functions. Both commands are more or less able to run with similar syntax, and I could not find a reason for the inconsistency between the two commands despite the functionality being the same.
This commit updates the command in `apply` to use the `-force` flag making working with the Terraform CLI a more consistent experience.
I searched PRs and issues and could not find any …
> Change -force to -auto-approve when destroying

- builtin/providers/terraform/data_source_state.go
- builtin/providers/terraform/data_source_state_test.go
The workspace attribute should only override the environment if it's not
the default value.
fixes #17525 and fixes #17189
> don't let default workspace override environment

- terraform/context_apply_test.go
- terraform/node_resource_apply.go
- terraform/test-fixtures/apply-interpolated-count/main.tf
If a count field references another count field which is interpolated
but is attached to a resource already in the state, the result of that
first interpolation will be lost when a plan is serialized. This is
because the result of the first interpolation is stored directly in the
module config, in an unexported config field.
This is not a general fix for the above situation, which would require
refactoring how counts are handles throughout the config. Ignoring the
error works, becuase in most cases the count will be properly
handled during the resource's interpolation. This is a stop-gap solution 
to the improved config handling that is in development.
Fixes #17368
>  ignore errors interpolating RawCount during apply

- backend/remote-state/manta/client.go
Fixes: #17314
We now deal correctly with the creation of the state file - we were
not dealing well with a ResourceNotFound error
Now that this has been changed around, we try and create the statefile
and if there is an error, we look for an existing statefile - previously
this was not the order of operations
https://asciinema.org/a/o9UGr3jgV36SFeuKvAybducaF
```
terraform [manta-backend] % acctests backend/remote-state/manta 2>~/tf.log
=== RUN   TestBackend
--- PASS: TestBackend (26.78s)
=== RUN   TestBackendLocked
--- PASS: TestBackendLocked (14.09s)
=== RUN   TestRemoteClient_impl
--- PASS: TestRemoteClient_impl (0.00s)
=== RUN   TestRemoteClient
--- PASS: TestRemoteClient (3.14s)
=== RUN   TestRemoteClientLocks
--- PASS: …
```
> backend/manta: Manta Backend was not dealing with a ResourceNotFound

- backend/local/backend_local.go
- command/format/diagnostic.go
- command/hook_module_install.go
- command/meta.go
- command/meta_config.go
- command/meta_new.go
- command/test-fixtures/validate-invalid/main.tf
- command/test-fixtures/validate-invalid/multiple_modules/main.tf
- command/validate.go
- command/validate_test.go
- main.go
> **Note:** The target of this PR is the `v0.12-dev` branch, because this change is not shippable in isolation.
This is the first of many more changes required to fully integrate the "HCL2" implementation of HCL into Terraform. As a mostly-isolated starting point this changes the `terraform validate` command to use the new parser.
As proposed in #15895, this reduces slightly the scope of the `terraform validate` command to just "safe" static validation, which will eventually include checking configuration values against provider validation rules but will not do any "dynamic" validation that requires per-run context, state, etc.
This changeset anticipates (but does not yet implement) a `terraform plan -validate-only` mode that does a slightly-deeper validation with the full context of a …
> "HCL2"-based validate command

- website/intro/getting-started/dependencies.html.md
Underscores are no longer allowed as of March 1, 2018. Reference: https://github.com/hashicorp/terraform-website/issues/180
> docs/getting-started: Replace underscores in aws_s3_bucket name in dependencies example

- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
I bumped into this when trying to resolve a bug in the K8S provider, where certain fields in the schema become immutable from a certain version of K8S.
The end-developer use-case follows:
```go
CustomizeDiff: func(diff *schema.ResourceDiff, meta interface{}) error {
// Mutation of PersistentVolumeSource after creation is no longer allowed in 1.9+
// See https://github.com/kubernetes/kubernetes/blob/v1.9.3/CHANGELOG-1.9.md#storage-3
conn := meta.(*kubernetes.Clientset)
serverVersion, err := conn.ServerVersion()
if err != nil {
return err
}
k8sVersion, err := gversion.NewVersion(serverVersion.String())
if err != nil {
return err
}
v1_9_0, _ := gversion.NewVersion("1.9.0")
if k8sVersion.Equal(v1_9_0) || k8sVersion.GreaterThan(v1_9_0) {
if diff.HasChange("spec.0.persistent_volume_source") { …
```
> helper/schema: Allow ResourceDiff.ForceNew on nested fields (avoid crash)

- helper/schema/field_reader.go
- helper/schema/field_reader_config.go
- helper/schema/field_reader_config_test.go
- helper/schema/field_reader_diff.go
- helper/schema/field_reader_diff_test.go
- helper/schema/field_reader_map.go
- helper/schema/field_reader_map_test.go
- helper/schema/field_reader_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
When specifying the type of a Map in a provider schema, we have two options which are (today) inconsistently applied - although Option 1 is more commonly used.
**Option 1: Provide a ValueType directly to the Elem**
```
"field": &schema.Schema{
Type:         schema.TypeMap,
Elem:         schema.TypeString,
}
```
**Option 2: Specify the Type using a nested Schema**
```
"field": &schema.Schema{
Type:         schema.TypeMap,
Elem:         &schema.Schema{Type:schema.TypeString},
}
```
Different parts of the helper/schema codebase make different assumptions about which approach will be used which can cause panics. I would like to move towards consistent use of one or the other.
Option 2 is my preferred approach, as it:
* Is consistent with how lists of scalar types are declared (big win!)
* …
> Move towards consistently specifying the type of a Map in a nested *Schema elemnt

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/habitat/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/salt-masterless/resource_provisioner.go
- communicator/communicator_mock.go
- communicator/remote/command.go
- communicator/ssh/communicator.go
- communicator/ssh/communicator_test.go
- communicator/winrm/communicator.go
- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/terraform_test.go
- vendor/github.com/masterzen/winrm/client.go
- vendor/vendor.json
The remote.Cmd struct could not convey any transport related error to
the caller, meaning that interrupted commands would show that they
succeeded.
Change Cmd.SetExited to accept an exit status, as well as an error to
store for the caller.  Make the status and error fields internal,
require serialized access through the getter methods.
Users of remote.Cmd should not check both Cmd.Err() and Cmd.ExitStatus()
until after Wait() returns.
Require communicators to call Cmd.Init before executing the command.
This will indicate incorrect usage of the remote.Cmd by causing a panic
in SetExitStatus.
The timeout for the remote command was taken from the wrong config
field, and the connection timeout was being used which is 5 min. Any
remote command taking more than 5 min would be terminated by …
> fix improper remote-exec timeout and communicator error handling

- helper/validation/validation.go
- helper/validation/validation_test.go
Helper function so providers can easily ensure an attribute parses as `time.RFC3339`. We could also introduce a `func TimeString(format string) schema.SchemaValidateFunc`. Let me know if you think that would be better or if we should have both. 😄
> validation: Add ValidateRFC3339TimeString

- tools/terraform-bundle/README.md
- tools/terraform-bundle/package.go
This commit allows for terraform-bundle to be able to package custom private plugins and addresses support ticket #7214. Now, terraform-bundle will attempt to look for a plugin on the public registry, and if that fails, it will look in a local plugins directory. If the plugin can be found in the local folder, that plugin will be included in the bundle. By default the local plugins directory is "./plugins", but this can be changed by setting the -plugins-dir argument. Ex: 
my test.hcl file with a custom plugin that does not exist on the public registry
```
providers {
aws = ["~> 1.0"]
google = ["~> 1.0"]
mycustomplugin = ["0.1"] # lives at ./my-plugins/terraform-provider-mycustomplugin
}
```
use case
```
$ terraform-bundle -os=linux -arch=amd64 -plugin-dir=./my-plugins test.hcl
```
> Allow terraform-bundle to include custom plugins

- state/local.go
- state/local_test.go
- terraform/state.go
Only open a new file descriptor for RefreshState if we haven't written a
state, and don't have the correct state open already. This prevents
windows from failing to refresh a locked state.
This also surfaces initial state read errors, which were previously assumed to be because of an empty state. On windows, this could mask the error return when file access is denied.
Fixes #17620
> Don't open a new file descriptor for a locked state.

- terraform/context_plan_test.go
- terraform/test-fixtures/plan-untargeted-resource-output/main.tf
- terraform/test-fixtures/plan-untargeted-resource-output/mod/main.tf
- terraform/transform_targets.go
filterPartialOutputs was not taking into account that some dependent
resources might yet be removed from the graph. Check that they are not
in the targeted set before declaring that the output remain.
fixes #17462
> remove more unneeded partial outputs

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner.go
- builtin/provisioners/habitat/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner_test.go
- builtin/provisioners/salt-masterless/resource_provisioner.go
- communicator/communicator_mock.go
The timeout for a provisioner is expected to only apply to the initial
connection. Keep the context for the `communicator.Retry` separate from
the global cancellation context.
fixes #17638
> use correct context for communicator.Retry

- website/docs/providers/type/community-index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
- website/docs/providers/type/misc-index.html.markdown
- website/docs/providers/type/network-index.html.markdown
I noticed some pages of the Terraform website have wrong descriptions in their meta headers...
> Fix providers categories descriptions in documentation

- command/console.go
- command/graph.go
- command/import.go
- command/import_test.go
- command/push.go
The state locking improvements for the regular commands had the side
effect of locking the state in the console, import, graph and push
commands. Those commands had been updated to get a state via the
Backend.Context method, which now locks the state whenever possible.
Add Unlock calls to all commands that call Context directly.
Fixes #17624
> unlock state in console, import, graph, and push

- helper/schema/resource.go
- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
- helper/schema/resource_test.go
Return the global default timeout if the ResourceData timeouts are nil.
Set the timeouts from the Resource when calling Resource.Data, so that
the provider-configured values are always available.
Fixes #17672
> make sure ResourceData timeouts are always set

- config_unix.go
For me, every ```eval``` in the code look like a potential security issue :-)
It's a small change to remove this.
> Use built-in method to get user homedir instead of eval on sh

- builtin/provisioners/chef/resource_provisioner.go
- builtin/provisioners/habitat/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/salt-masterless/resource_provisioner.go
- communicator/remote/command.go
- communicator/ssh/communicator.go
- communicator/ssh/communicator_test.go
This reduces the surface area for the `remote.Cmd` API, as mentioned in #17596.
Combine the `ExitStatus` and `Err` values from `remote.Cmd` into an error
returned by `Wait`, better matching the behavior of the `os/exec` package.
Non-zero exit codes are returned from Wait as a `remote.ExitError`.
Communicator related errors are returned directly.
Clean up all the error handling in the provisioners using a
communicator. Also remove the extra copyOutput synchronization that was
copied from package to package.
> clean up remote.Cmd api

- command/apply.go
Fixes #17671
This `auto-approve` flag was in `apply -help` on Terraform v0.11.3,
but it was deleted by mistake in #17218.
This fix restores it.
The order of the flags has changed from before deletion but it is the same as `destroy`.
```
$ terraform -v
Terraform v0.11.3
Your version of Terraform is out of date! The latest version
is 0.11.5. You can update by downloading from www.terraform.io/downloads.html
$ terraform apply -help
Usage: terraform apply [options] [DIR-OR-PLAN]
Builds or changes infrastructure according to Terraform configuration
files in DIR.
By default, apply scans the current directory for the configuration
and applies the changes appropriately. However, a path to another
configuration or an execution plan can be provided. Execution plans can be
used to only execute a …
```
> Restore `auto-approve` flag in the output of `apply -help` command

- backend/local/backend_apply_test.go
- backend/local/backend_plan_test.go
- backend/local/backend_refresh_test.go
- backend/local/testing.go
- command/apply_test.go
- command/command_test.go
- command/debug_json2dot_test.go
- command/fmt_test.go
- command/init_test.go
- command/output_test.go
- command/plan_test.go
- command/plugins_lock_test.go
- command/plugins_test.go
- command/refresh_test.go
- command/show_test.go
- config/module/get.go
Cleanup a bunch of the TempDir handling.
The number of temp files left by tests is large enough to create problems attempting to delete them from the command line on some systems. Some command tests also left files in the working directory.
Cleaning up the backend test was rather easy, but the command tests had hundreds of call sites creating temp files and directories, so rather than modify the helper signatures and clean up the files at each site, all temp files will now be created in a global testing directory which is cleaned up in `TestMain`.
> cleanup temp files

- tools/terraform-bundle/package.go
Fixed a bug in which an example custom provider would be saved as "terraform-provider-custom-v0.0.1" instead of "terraform-provider-custom_v0.0.1". Not an issue when running the bundle on TFE, but is annoying when trying to run a terraform bundle locally.
> Fix scrub mistake

- config/configschema/coerce_value.go
- config/configschema/coerce_value_test.go
- config/configschema/schema.go
- configs/configload/loader.go
- configs/module_merge.go
- configs/module_merge_body.go
- configs/synth_body.go
- configs/synth_body_test.go
- helper/schema/core_schema.go
- helper/schema/core_schema_test.go
This PR has four commits that are actually pretty orthogonal to one another but are all in the area of configuration-handling and so are presented together just in the interests of reducing paperwork. It is probably easiest to review each of the included commits separately rather than as a single diff.
These changes were all made in the course of implementing the new HCL2-powered handling of backends which will follow in a subsequent PR.
> configs: Various utilities needed for handling HCL2-based configuration

- helper/schema/schema.go
- helper/schema/schema_test.go
The error message displayed when a validating conflicting schema attributes includes the value of the conflicting attribute, regardless of whether or not it is marked as Sensitive. This can leak sensitive data.  
Since the attribute value is not really relevant to the purpose of the error message, this PR removes the value from the error message. 
(See also discussion at https://github.com/terraform-providers/terraform-provider-local/pull/9)
> Remove attribute value from ConflictsWith validation message (leaks sensitive data)

- communicator/ssh/communicator.go
Most of the time an ssh authentication failure would be non-recoverable,
but some host images can start the ssh service before it is properly
configured, or before user authentication data is available.
Log ssh authentication errors and allow the provisioner to retry until
the connection timeout.
Fixes #17733
> retry ssh authentication failures

- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
This adds a new method to `ResourceDiff`: `Computed`, which exposes the
computed read result field to `ResourceDiff`. In the context of
customizing the diff, this is important as interpolated and otherwise
computed values will show up in the diff as blank, with no way of
determining if the value is actually blank or if it's a computed value
not available at diff customization time. Currently assumptions need to
be made on this, but this does not help in validation scenarios where
one needs to differentiate between an actual blank value and a value
that will be available later.
This is exposed for the most part via `NewComputed` in the diff, but the
tests cover both the config reader as well (with no diff, even though
this should not come up in normal operation) and also the `newDiff` …
> helper/schema: Add Computed to ResourceDiff, expose GetOkExists

- terraform/context_apply_test.go
- terraform/interpolate.go
- terraform/test-fixtures/apply-resource-scale-in/main.tf
If an existing resources is scaled back to 0, locals and outputs will
still have a multi-variable reference to evaluate, which should return
an empty list. Due to how the resource is removed, the resource will
still exist in the state but with no primary instance, which needs to be
ignored in the instance count.
Fixes #17425
> detect scaled in resources when evaluating *s

- addrs/count_attr.go
- addrs/input_variable.go
- addrs/instance_key.go
- addrs/local_value.go
- addrs/module_call.go
- addrs/path_attr.go
- addrs/referenceable.go
- addrs/resource.go
- addrs/self.go
- addrs/terraform_attr.go
- lang/data.go
- lang/data_test.go
- lang/doc.go
- lang/eval.go
- lang/eval_test.go
- lang/functions.go
- lang/references.go
- lang/scope.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/README.md
- vendor/github.com/hashicorp/hcl2/ext/dynblock/expand_body.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/expand_spec.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/expr_wrap.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/iteration.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/public.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/schema.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/variables.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/variables_hcldec.go
- vendor/vendor.json
Whereas package `configs` deals with the static structure of the configuration language, this new package `lang` deals with the dynamic aspects such as expression evaluation.
So far this mainly consists of populating a `hcl.EvalContext` that contains the values necessary to evaluate a block or an expression. There is also special handling here for dynamic block generation using the HCL `dynblock` extension, which is exposed in the public interface (rather than hiding it as an implementation detail of `EvalBlock`) so that the caller can then extract proper source locations for any result values using the expanded body.
This also includes the beginnings of a replacement for the function table handling that currently lives in the old "config" package, but most of the functions are not yet …
> lang: new package for the runtime parts of the config language

- tools/terraform-bundle/package.go
Permissions were lost when building on linux. This fixes that bug..
> Keep permissions when copying file for Linux

- state/local.go
- state/local_lock_unix.go
This patch replaces the deprecated os.SEEK_SET with the instead recommended io.SeekStart.
https://github.com/golang/go/blob/39852bf4cce6927e01d0136c7843f65a801738cb/src/os/file.go#L81
> Use io.SeekStart instead of deprecated os.SEEK_SET

- website/docs/backends/types/s3.html.md
When setting up remote state locking with S3 and DynamoDB, I had to Google around to check which  IAM permissions Terraform requires for the DynamoDB table. The S3 bucket permissions are documented, so I thought it would be helpful to also document the DynamoDB table ones.
I also spotted a reference to the deprecated `lock_table` argument and updated it to `dynamodb_table`.
Relevant Terraform versions: 0.9+
> Add required DynamoDB IAM permissions for state locking to S3 backend docs

- website/docs/providers/type/cloud-index.html.markdown
Simple update to grammar on Cloud index description. It is __not__ critical and can be released with a future version of the website.
> fix grammar in description

- builtin/provisioners/habitat/resource_provisioner.go
- website/docs/provisioners/habitat.html.markdown
**This PR:**
* Fixes https://github.com/hashicorp/terraform/issues/17334 - On installation the channel and builder URL were not passed properly. This is no longer the case
* Updates the binding documentation as the example listed generates a slew of errors
Signed-off-by: Rob Campbell <rcampbell@chef.io>
> [provisioner-habitat] Fix package channel honoring and documentation

- builtin/provisioners/habitat/resource_provisioner.go
Signed-off-by: Arash Zandi <arash.zandi@smartb.eu>
Cherry picked from #17225
Fixes #17224
> `enable` habitat supervisor service before `start`

- website/docs/registry/api.html.md
In [Download the Latest Version of a Module](https://www.terraform.io/docs/registry/api.html#download-the-latest-version-of-a-module) API document for registry, `version` parameter isn't needed for that API.
> website: remove an unnecessary parameter for API

- communicator/winrm/communicator.go
- communicator/winrm/communicator_test.go
- communicator/winrm/provisioner.go
- communicator/winrm/provisioner_test.go
- terraform/eval_validate.go
- website/docs/provisioners/connection.html.markdown
Some customers prohibit *any* basic or digest authentication methods over WinRM.
This is a simple patch to add NTLM (kerberos) support for WinRM connections, modeled after packer's support for the same.
When testing functionality, I ran the following on the host to disable all insecure auth:
```
winrm set winrm/config/client/auth '@{Basic="false"}'
winrm set winrm/config/client/auth '@{Digest="false"}'
winrm set winrm/config/service/auth '@{Basic="false"}'
```
Then, I tested it with the unpatched Terraform to verify that it locked me out.  (It did)
Finally, I tested it with the patched Terraform to verify that it let me in.  (It did)
> Support NTLM for WinRM communicators.

- communicator/ssh/communicator.go
- communicator/winrm/communicator.go
- vendor/github.com/packer-community/winrmcp/winrmcp/cp.go
- vendor/vendor.json
While this may not completely solve the open issues around winrm failures, updating winrmcp and getting the remote errors may help troubleshoot the issues. 
The main goal here was to return possible errors from winrm commands. 
The command error field in not exported, and only returned from the client `Run*` methods. Replace our `runCommand` with the winrm equivalent `Client.Run`.
Update the `winrmcp` package.
Update the log format of both communicators.
> get errors from winrm commands

- website/docs/configuration/resources.html.md
I like to see in documentation what's non-expected behaviour and where to follow for updates.
#3116
> docs: no interpolations in `lifecycle` attribute (#3116)

- tools/terraform-bundle/package.go
It appears that the FileInfoHeader method does not compress files by default. Explicitly setting Deflate fixes the issue.
If you think it's useful, I can also add some e2e validation of the resulting zip file, but I don't see any of that at the moment.
> Ensure files are compressed in terraform-bundle

- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
- helper/schema/schema_test.go
A couple of bugs have been discovered in `ResourceDiff.ForceNew`:
* `NewRemoved` is not preserved when a diff for a key is already present.
This is because the second diff that happens after customization
performs a second `getChange` on not just state and config, but also on
the pre-existing diff. This results in `Exists == true`, meaning nil is
never returned as a new value.
* `ForceNew` was doing the work of adding the key to the list of changed
keys by doing a full `SetNew` on the existing value. This has a side
effect of fetching zero values from what were otherwise undefined values
and creating diffs for these values where there should not have been
(example: `"" => "0"`).
This update fixes these scenarios by:
* Adding a new private function to check the existing diff for …
> helper/schema: ResourceDiff ForceNew attribute correctness

- terraform/context_apply_test.go
- terraform/interpolate.go
- terraform/test-fixtures/plan-destroy-interpolated-count/main.tf
When computing the count value, make sure to include walkDestroy with
walkApply, as the former is only a special case of the latter.
When applying a saved plan, the computed count values are lost and we
can no longer query the state for those values. The apply walk was
already considered in the `resourceCountMax` function, but the destroy
walk was not.  This worked when destroying in a single operation
("terraform destroy"), since the state would still be updated with the
latest counts from the plan.
Fixes #17793
> walkDestroy is a form of "apply"

- addrs/module.go
- addrs/module_instance.go
- configs/config.go
We initially just mimicked our old practice of using `[]string` for module paths here, but the `addrs` package now gives us a pair of types that better capture the two different kinds of module addresses we are dealing with: static addresses (nodes in the configuration tree) and dynamic/instance addresses (which can represent the situation where multiple instances are created from a single module call).
This distinction still remains rather artificial since we don't yet have support for `count` or `for_each` on module calls (#953), but this is intended to lay the foundations for that to be added later, and in the meantime just gives us some handy helper functions for formatting these address types as strings.
> configs: Start using the new "addrs" package types for modules

- configs/module.go
- configs/module_merge.go
- configs/resource.go
- terraform/resource_address.go
- terraform/resource_address_test.go
Initially the intent here was to tease these apart a little more since they don't really share much actual behavior in common in core, but in practice it'll take a lot of refactoring to tease apart these assumptions in core right now and so we'll keep these things unified at the configuration layer in the interests of minimizing disruption at the core layer.
The two types are still kept in separate maps to help reinforce the fact that they are separate concepts with some behaviors in common, rather than the same concept.
> configs: Re-unify the ManagedResource and DataResource types

- configs/config.go
This is useful for creating a valid placeholder configuration, but not much else. Most callers should use `BuildConfig` to build a configuration that actually has something in it.
The motivation for writing this is that there are a few places in core where we stub out a configuration pointer to avoid crashes, and so having this allows a more direct port of those codepaths to use the new config types.
> configs: NewEmptyConfig function

- configs/config_build.go
This is a built-in implementation of `ModuleWalker` that just returns an error any time it's asked for a module. This is intended for simple unit tests where no child modules are needed anyway.
> configs: DisabledModuleWalker

- website/layouts/backend-types.erb
At the moment the documentation does not show which of the two "etcd" sidebar entries is the "v3" one:
This PR addresses exactly that. It makes the "v3" bit visible.
> Make "v3" in etcd visible in the backend types sidebar

- website/docs/modules/sources.html.markdown
This update is relevant for the current version, but is not urgent. It provides a clearer example of referencing private Bitbucket modules via SSH; it's similar to the Generic Git option, but it's more explicit to show it in the special BB section as well.
Also a small typo fix withs > with!
> Provide example of the SSH method for BB private modules

- website/docs/modules/usage.html.markdown
The example for parsing multiple providers to a module had quotationmarks arount the keys. This does not seem to be the correct format.
(note: I have not inspected the code, but the example did not work for me. When I removed the quotation marks it did work)
> Module multiple provider example typo

- command/meta_backend.go
> command: fix spelling in error - fixes #18065

- website/docs/commands/push.html.markdown
- website/docs/configuration/terraform-enterprise.html.md
We had a couple broken links pointing to the docs for the run API. This
updates them to the new location.
> Fix broken links to /docs/enterprise/run/api.html

- configs/configload/loader_snapshot.go
- configs/configload/loader_snapshot_test.go
- configs/parser_config_dir.go
Here we introduce a new idea of a "configuration snapshot", which is an in-memory copy of the source code of each of the files that make up the configuration. The primary intended purpose for this is as an
intermediate step before writing the configuration files into a plan file, and then reading them out when that plan file is later applied.
During earlier configs package development we expected to use an `afero` vfs implementation to read directly from the zip file, but that doesn't work in practice because we need to preserve module paths from the source file system that might include parent directory traversals (../) while retaining the original path for use in error messages.
The result, for now, is a bit of an abstraction inversion: we implement a specialized afero vfs …
> configload: Configuration snapshots

- backend/local/backend_apply.go
If the workspace name is not "default", include it in the confirmation
message for `terraform destroy`.
Fixes #15480
```
Plan: 0 to add, 0 to change, 1 to destroy.
Do you really want to destroy?
Terraform will destroy all your managed infrastructure in the worksapce "test" as shown above.
There is no undo. Only 'yes' will be accepted to confirm.
Enter a value: yes
```
> cli: show workspace name in destroy confirmation

- command/output.go
- command/output_test.go
- Fixes https://github.com/hashicorp/terraform/issues/11696
- This changes makes `terraform output -json` return '{}' instead of
throwing an error about "no outputs defined"
- If `-json` is not set, the user will receive an error as before
- This UX helps new users to understand how outputs are used
- Allows for easier automation of TF CLI as an empty set of outputs is
usually acceptable, but any other error from `output` would be
re-raised to the user.
> Remove error on empty outputs when `-json` is set

- helper/schema/data_source_resource_shim.go
- helper/schema/resource.go
- helper/schema/resource_test.go
We already had the functionality to make resources deprecated, which was
used when migrating resources to data sources, but the functionality was
unexported, so only the schema package could do it. Now it's exported,
meaning providers can mark entire resources as deprecated. I also added
a test in hopefully-the-right place?
> Export resource deprecation.

- configs/configload/getter.go
- configs/configload/loader_init_from_module.go
- configs/configload/loader_install.go
It is common for the same module source package to be referenced multiple times in the same configuration, either because there are literally multiple instances of the same module source or because a single package (or repository) contains multiple modules in sub-directories and many of them are referenced.
To optimize this, here we introduce a simple caching behavior where the module installer will detect if it's asked to install multiple times from the same source and produce the second and subsequent directories by copying the first, rather than by downloading again over the network.
This optimization is applied once all of the `go-getter` detection has completed and sub-directory portions have been trimmed, so it is also able to normalize differently-specified source addresses that …
> configload: Don't download the same module source multiple times

- website/docs/backends/config.html.md
- website/docs/backends/types/consul.html.md
- website/intro/examples/consul.html.markdown
- website/intro/getting-started/remote.html.markdown
- website/upgrade-guides/0-9.html.markdown
Following the examples as they are currently will cause Terraform
to error as demo.consul.io returns a 503 if you try to use it
over http. Consistently set the scheme to https for all examples
that use demo.consul.io.
> Using demo.consul.io requires `scheme = "https"`

- website/docs/state/purpose.html.md
- website/docs/state/remote.html.md
After some discussion with "iamakulov" on Twitter it seems that the use of the word "conflicts" and "merge conflicts" here was sounding like us implicitly condoning the use of version control as a mechanism for distributing local state files, which hasn't been recommended for quite some time since remote state now provides a much more robust solution.
While here, I also tweaked some other language on this page for style and for use of terminology we more commonly use in our more recent documentation.
> website: Tweak the language we use to describe remote state

- config/interpolate_funcs.go
rsadecrypt logs private key when cannot base64 decode input string
> Fix logging in rsadecrypt

- website/intro/getting-started/modules.html.md
The module now gets the region from the provider block. See https://github.com/hashicorp/terraform-aws-consul/pull/65 and https://github.com/hashicorp/terraform-aws-consul/issues/49 for context.
> Remove aws_region param from Consul example in docs

- command/012_config_upgrade.go
- configs/configupgrade/analysis.go
- configs/configupgrade/upgrade.go
- configs/configupgrade/upgrade_expr.go
- configs/configupgrade/upgrade_native.go
- configs/configupgrade/upgrade_test.go
- configs/configupgrade/upgrader.go
In order to properly migrate the contents of `resource`, `data`, `provider` and `provisioner` blocks we will need the provider's schema in order to understand what is expected, so we can resolve some ambiguities inherent in the legacy HCL AST.
This includes an initial prototype of migrating the contents of resource blocks (attributes only for now) just to verify that the information is being gathered correctly. As with the rest of the `upgrade_native.go` file, this will be reorganized significantly once the basic end-to-end flow is established and we can see how to organize this code better.
---
This minimal PoC of resource upgrading now takes care of the "attribute value expressed with block syntax" ambiguity, rewriting it to always use attribute syntax:
```diff
resource "null_resource" …
```
> configupgrade: Analysis of input configuration

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Adding Telefonica as a new Terraform provider. This links will allow navigations from terraform.io
> Adding TelefonicaOpenCloud Documentation Links

- tfdiags/contextual.go
- tfdiags/contextual_test.go
The only contextual information returned by the plugins in a diagnostic
is an attribute path. In order to test the conversions, we need to be
able to extract the cty.Path from a diagnostic if it exists.
> add tfdiags.GetAttribute

- README.md
I stumbled building terraform without stringer installed, and it was not obvious how to install it.  This should help others solve the problem more quickly.
Incidentally, I first tried with Go-1.9.7, and `make` gave errors about code not matching gofmt.  Is Go-1.9.x still supported?  If not, I can make another PR to change the minimum version in the README.
> README: install stringer before running make

- README.md
Go 1.9 seems not to work, and most development is done with 1.10 anyway.
Per #18344
> Require Go-1.10

- website/docs/backends/types/terraform-enterprise.html.md
Add links to important docs (like user tokens), and explain that this isn't part
of our recommended primary workflows anymore.
> website: Revise atlas backend page

- providers/provider.go
In order for providers to determine if a computed value was unset in the
configuration, the configuration must be passed along with the prior and
proposed states. Terraform core will still handle the creation of the
ProposedNewState to ensure correctness, but the raw configuration value
will also be supplied for comparison.
> add Config to the PlanResourceChangeRequest

- helper/schema/core_schema.go
- helper/schema/core_schema_test.go
The original code assumed a Resource was a top-level construct only, but it's overloaded to also represent nested blocks which don't require the "id" attribute. Rather than try to guess where a `Resource` is going to be located, make a separate `CoreConfigResourceSchema` method for the top level blocks.
Due to a typo not calling `t.Error` in the tests, refactoring the id insertion didn't fail when it should have, and the previous PR never really worked.
> only add "id" to top-level resources

- configs/configschema/coerce_value.go
- configs/configschema/coerce_value_test.go
- configs/configschema/decoder_spec.go
- configs/configschema/decoder_spec_test.go
Any value that is not set in the configuration should decode as a Null
value. Unknown should still be returned if a computed value expression
is unknown. `CoerceValue` should also match the decoder behavior.
> always use Null for unset configuration values

- website/docs/commands/taint.html.markdown
It looks like the output does not match the command, in fact.
This pull-request fixes this issue.
> Fix documentation on tainting resources within modules

- website/docs/registry/api.html.md
The example `curl` doesn't work when copy/pasted. Using proper http URL separators for query parameters fixes this and makes it uniform to all other examples.
> Fixes `curl` example call in API docs

- config/hcl2shim/flatmap.go
- config/hcl2shim/flatmap_test.go
When creating a flatmap from a cty.Value, there may be Null collections
which don't need to be added to the flatmap at all. Skip over these to
avoid panicking in ElementIterator with a Null value.
> handle Null collections in flatmaps

- website/docs/modules/create.html.markdown
Relevant to the current version, but not urgent.
Module version specification was described as upcoming in 0.11; I've changed it to describe version specification as existing functionality & link to the relevant docs section for syntax guidance.
> Link to info on constraining module versions

- config/hcl2shim/paths.go
- config/hcl2shim/paths_test.go
PathFromFlatmapKey is used to convert a flatmap key to a cty.Path, and
ensures it conforms to the type schema.
This is used when handling Diffs, where the ResourceAttrDiffs are
indexed by the flatmapped key values, and we need to convert those to
addresses to apply to a cty.Value.
> add PathFromFlatmapKey

- website/docs/modules/sources.html.markdown
It's been a while since we made any significant updates to this page. The main theme of this revamp is to ensure that we highlight how to provide "ambient credentials" for each of the module sources using the standard mechanisms for each source type.
While there, I also attempted a general cleanup to highlight the main cases and make this less like a detailed description of all of `go-getter`'s esoteric features, and did some general copy-editing to write
it in our usual documentation "voice".
> website: Revise the "Module Sources" page

- helper/resource/testing.go
- helper/resource/testing_config.go
- helper/resource/testing_test.go
This adds the `Taint` field to the acceptance testing framework, allowing
the ability to pre-taint resources at the beginning of a particular
`TestStep`. This can be useful for when an explicit `ForceNew` is required
for a specific resource for troubleshooting things like diff mismatches,
etc.
The field accepts resource addresses as a list of strings. To keep
things simple for the time being, only addresses in the root module are
accepted. If we ever want to expand this past that, I'd be almost
inclined to add some facilities to the core terraform package to help
translate actual module resource addresses (ie:
`module.foo.module.bar.some_resource.baz`) into the correct state, versus
the current convention in some acceptance testing facilities that take
the module address as a list of …
> helper/resource: Add ability to pre-taint resources

- helper/schema/resource.go
- helper/schema/resource_test.go
- helper/schema/schema.go
This is the provider-side UpgradeState imeplementation for a particular
resource. This new function will be called to upgrade a saved state with
an old schema version to the current schema.
UpgradeState also requires a record of the last schema and version that
could have been stored as a flatmapped state. If the stored state is in
the legacy flatmap format, this will allow the provider to properly
decode the flatmapped state into the expected structure for the new json
encoded state. If the stored state's version is below that of the
LegacySchema.Version value, it will first be processed by the legacy
MigrateState function.
> add UpgradeState to schema.Resource

- website/docs/providers/type/community-index.html.markdown
Corrected the naming of the 'Keboola' provider (https://github.com/plmwong/terraform-provider-keboola) and shifted it down to keep alphabetical ordering.
> Correcting terraform custom provider name in community-index.html.markdown

- website/docs/backends/types/terraform-enterprise.html.md
Just providing the hostname won't work. This commit adds an example and fixes
the explanation.
> website: atlas backend requires https protocol in address

- helper/schema/resource.go
- helper/schema/resource_test.go
It turns out that state upgrades need to be handled differently since
providers are going to be backwards compatible. This means that new
state upgrades may still be stored in the flatmap format when used wih
terraform 0.11. Because we can't account for the specific version which
could produce a legacy state, all future state upgrades need to record
the schema types for decoding.
Rather than defining a single Upgrade function for states, we now have a
list of functions, each of which handle upgrading a specific version to
the next. In practice this isn't much different from the way many
resources implement upgrades themselves, with a separate function for
each version dispatched from the MigrateState function. The only added
burden is the recording of the schema type, and we intend to …
> StateUpgrade redux

- backend/remote/backend.go
- backend/remote/backend_test.go
Using these default options prevents the need for checking this in the backend
code by just leveraging the default schema validation logic.
> backend/remote: use schema max/min items options

- backend/remote/backend.go
- website/docs/backends/types/remote.html.md
Instead promote the use of shared credentials using the CLI Config File
> backend/remote: do not use the TFE_TOKEN env variable

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Here our prior existing single template becomes the "Bug report" template, and we introduce a second "Feature request" template that is more appropriate for gathering context about a feature request.
> Separate issue templates for Bugs vs. Features

- helper/logging/transport.go
log messages in provider code get passed through this function: https://github.com/hashicorp/terraform/blob/35d47201ad24d89081d55ea3057c5f7144761b2c/vendor/github.com/hashicorp/go-plugin/client.go#L754-L790
If a line contains only JSON, it looks for specific entries in the JSON map to give it instructions on how it should be printed. In this particular case, since we're just printing JSON being sent to/from a server, we don't want it to contain those special messages, we want it to get printed directly.
By pretty-printing it, we end up with no one line that contains valid JSON (so they all get printed), and we have the benefit of easier-to-read logs. Win-win!
> pretty-print json in http requests/responses

- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provisioner.go
- plugin/grpc_provider.go
- plugin/grpc_provisioner.go
- plugin/resource_provider.go
- plugin/resource_provider_test.go
- plugin/resource_provisioner.go
- plugin/resource_provisioner_test.go
- plugin/serve.go
- vendor/github.com/hashicorp/go-plugin/client.go
- vendor/github.com/hashicorp/go-plugin/server.go
- vendor/github.com/hashicorp/go-plugin/testing.go
- vendor/vendor.json
Add wrappers to automatically shim `schema.Provider` and `schema.Provisioner` in the plugin package. The protocol negotiation will be handled directly by the new go-plugin version.
> new plugin shims

- providers/resolver.go
These new types are adaptations of `terraform.ProviderResolver` and `terraform.ResourceProviderFactory` respectively. In a later commit we will update users of the old types to use these new types, possibly in a "gradual repair" sort of fashion by initially using type aliases, though that won't 100% solve the problem because the types themselves have changed in this move to return `providers.Interface` instead of `terraform.ResourceProvider`.
> providers: Resolver and Factory types

- website/docs/providers/type/community-index.html.markdown
I also switched it around with the Kafka link to preserve the alphabetical ordering of the page.
> Correction of spelling for 'Keboola' provider

- backend/remote-state/manta/backend.go
- backend/remote-state/manta/backend_test.go
- backend/remote-state/manta/client_test.go
- builtin/providers/terraform/data_source_state.go
- builtin/providers/terraform/data_source_state_test.go
- helper/schema/resource_data.go
- website/docs/backends/types/manta.html.md
The `remote` backend config contains an attribute that is defined as a `*schema.Set`, but currently only `string` values are accepted as the `config` attribute is defined as a `schema.TypeMap`.
Additionally the `b.Validate()` method wasn’t called to prevent a possible panic in case of unexpected configurations being passed to `b.Configure()`.
This commit is a bit of a hack to be able to support this in the 0.11 series. The 0.12 series will have proper support, so when merging 0.12 this should be reverted again.
The additional change to the `manta` backend was needed to (next to making it consistent as its the only attribute name that uses camelcase) because passing that attribute `objectName` ended up giving me this error: 
https://github.com/hashicorp/terraform/blob/4d9a2841147fe3e613b8fe …
> terraform/terraform_remote_state: accept complex configs

- backend/backend.go
- command/meta_backend_migrate.go
- command/meta_backend_test.go
- command/test-fixtures/backend-change-multi-to-no-default-with-default/local-state.tfstate
Certain backends (currently only the `remote` backend) do not support using both the default and named workspaces at the same time.
To make the migration easier for users that currently use both types of workspaces, this commit adds logic to ask the user for a new workspace name during the migration process.
> backend/migrations: migrate the default state

- command/push.go
Issue: hashicorp/terraform#18775
`terraform push --help` shows `-no-color` description misaligned.
> Making spacing consistent everywhere

- command/hook_ui.go
- plans/changes.go
- terraform/eval_diff.go
- terraform/node_resource_apply.go
- terraform/node_resource_destroy.go
- terraform/resource.go
Since we do our deletes using a separate graph node from all of the other actions, and a "Replace" change implies both a delete _and_ a create, we need to pretend at apply time that a single replace change was actually two separate changes.
This will also early-exit eval if a destroy node finds a non-Delete change or if an apply node finds a Delete change. These should not happen in practice because we leave these nodes out of the graph when they are not needed for the given action, but we do this here for robustness so as not to have an invisible dependency between the graph builder and the eval phase.
---
This PR also includes a small set of fixes for other issues that were revealed by fixing this one.
> core: Split Replace changes into separate Delete/Create changes during apply walk

- website/docs/commands/state/mv.html.md
- website/docs/commands/state/push.html.md
The description for the `state mv` and `state push` had descriptions for the `state rm` command. It only shows up in places like Slack which renders link previews, so low impact.
> Fix description for state mv and push sub-commands

- backend/remote/backend_mock.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
- backend/remote/test-fixtures/plan-with-working-directory/terraform/main.tf
- backend/remote/test-fixtures/plan-with-working-directory/terraform/output.log
- backend/remote/testing.go
In TFE you can configure a workspace to use a custom working directory. When determining which directory that needs to be uploaded to TFE, this working directory should be taken into account to make sure we are uploading the correct root directory for the workspace.
> backend/remote: take working directories into account

- backend/remote/backend.go
- backend/remote/backend_mock.go
- backend/remote/backend_state.go
- backend/remote/backend_state_test.go
If a run ID is available, we need to make sure we pass that when creating a new state version so the state will be properly associated with the run.
>  backend/remote: add the run ID to associate state

- website/docs/internals/archiving.html.md
Explanatory page to link to from the READMEs of providers that are (reversibly) archived as a signal to users that they are not actively maintained.
> Add docs/internals/archiving.html to describe the archiving process.

- terraform/test_failure
Just ran into this file by chance. It seems to be a piece of a test log.
I presume it was never meant to be checked in.
@svanharmelen Can you please review?
> Remove a leftover test log file

- backend/remote/backend.go
- backend/remote/backend_mock.go
The pagination info of a list call that returns an empty list contains:
```go
CurrentPage: 1
TotalPages: 0
```
So checking if we have seen all pages using `CurrentPage == TotalPages` will not work and will result in an endless loop.
The tests are updated so they will fail (timeout after 1m) if this is handled incorreclty.
> backend/remote: handle empty results correctly

- .travis.yml
- README.md
- backend/remote-state/s3/backend_test.go
- builtin/provisioners/chef/linux_provisioner_test.go
- command/init.go
- command/meta_backend_test.go
- helper/schema/resource_timeout_test.go
- helper/schema/schema_test.go
- plugin/discovery/get_test.go
- vendor/github.com/xanzy/ssh-agent/pageant_windows.go
- vendor/vendor.json
A fresh checkout of `origin/master` does not build atm using the `dev` target because `master` has not been formatted using `gofmt` from Go 1.11 (this has been the case for a while if you've been running devel).
```
% pwd
$GOPATH/src/github.com/hashicorp/terraform
% git status | head -n 2
% git rev-parse HEAD
7cfeffe36b0be61ca812d33995e184e02a76c0dc
% make dev
gofmt needs running on the following files:
./plugin/discovery/get_test.go
./backend/remote-state/s3/backend_test.go
./command/meta_backend_test.go
./command/init.go
./helper/schema/schema_test.go
./helper/schema/resource_timeout_test.go
./builtin/provisioners/chef/linux_provisioner_test.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1 …
```
> Fix drift caused from gofmt when running make dev and go 1.11.

- command/taint.go
- command/untaint.go
Both the `taint` and `untaint` commands had a small logical error that caused them you first get the state and then lock it.
> Make sure the state is locked before it is used

- helper/pathorcontents/read_test.go
One of the tests in this package doesn't work when the tests are run as
root - like inside of a docker container. The test is still useful to
specify `pathorcontents` behavior when a file is not readable, so it's
better to skip than just delete it. See linked issue for further
disussion.
Closes #7707
> helper/pathorcontents: Skip one test when root

- terraform/graph_builder_plan_test.go
- terraform/schemas.go
- terraform/schemas_test.go
- terraform/transform_transitive_reduction_test.go
There does not appear to be any real reason that these Schemas fields are
not exported, and exporting them makes it possible to directly construct
Schemas for tests without pulling in an entire context.
> terraform.Schemas: export struct fields

- backend/local/backend_test.go
update the function names in the `testDelegateBackend` to match what was being
called in TestLocal_multiStateBackend (matching the test behavior in
master)
> backend/local: fix panic in tests

- tools/terraform-bundle/README.md
- website/docs/commands/init.html.markdown
- website/docs/configuration/providers.html.md
- website/docs/plugins/basics.html.md
- website/guides/running-terraform-in-automation.html.md
I'm attempting to keep things simple for normal users while making sure we've
got the full behavior written down somewhere for plugin developers.
This PR doesn't stand alone; it's paired with a PR in the
terraform-website repo, to deal with some related content in the "extend"
section: https://github.com/hashicorp/terraform-website/pull/497
> website: Reconcile docs about plugin discovery and downloading

- plugin/grpc_provider.go
While providers shouldn't return nil values, we need to protect against
them. Always assign valid Null cty values when the response contains a
nil.
> check responses for nil values

- command/workspace_command.go
Small update to the workspace command description to include available sub-commands, rather than similar looking but wrong ones.
resolves #18832 
resolves #18762
> Update wrong usage workspace command description

- backend/remote/backend.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan.go
Except when a lock-timeout has exceeded or auto-approve is set.
> backend/remote: ask to cancel a pending remote operation

- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/test-fixtures/apply-policy-passed/policy.log
If the policy passes, only show that instead of the full check output to prevent cluttering the output. So a passing policy will only show:
\----------------------------------------------
Organization policy check: passed
\----------------------------------------------
> backend/remote: only show the full policy output when it fails

- backend/remote/backend.go
- backend/remote/colorize.go
This is a bit of a hack to support the `-no-color` flag while we don’t have an option to set run variables.
That is also the reason why the orginal method is commented out instead of deleted. This will be reverted when the TFE starts supporting run variables.
> backend/remote: add support for `-no-color`

- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
We now first check the rights before we start to actually execute make remote calls.
> backend/remote:  prevent running plan or apply without permissions

- backend/backend.go
- backend/remote/backend.go
- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
- command/apply.go
- command/meta_backend.go
- command/plan.go
For Plan only:
-module-depth=n
For Plan & Apply
-parallelism=m
-refresh=false
-var “foo=bar” and -var-file=foo
> backend/remote: add checks for all flags we currently don’t support

- command/plugins.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
- helper/plugin/grpc_provisioner.go
- plugin/grpc_provider.go
- plugin/grpc_provisioner.go
PlanResourceChange isn't returning the diff, but rather it is returning
the destired state. If the propsed state results in a nil diff, then,
the propsed state is what should be returned.
Make sure Meta fields are not nil, as the schema package expects those
to be initialised.
> a plan with no diff should return proposed state

- backend/backend.go
- backend/remote/backend.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan_test.go
- backend/remote/test-fixtures/apply-with-error/main.tf
- backend/remote/test-fixtures/apply-with-error/plan.log
- backend/remote/test-fixtures/plan-with-error/main.tf
- backend/remote/test-fixtures/plan-with-error/plan.log
- command/apply.go
- command/plan.go
In some cases this is needed to keep the UX clean and to make sure any remote exit codes are passed through to the local process.
The most obvious example for this is when using the "remote" backend. This backend runs Terraform remotely and stream the output back to the local terminal.
When an error occurs during the remote execution, all the needed error information will already be in the streamed output. So if we then return an error ourselves, users will get the same errors twice.
By allowing the backend to specify the correct exit code, the UX remains the same while preserving the correct exit codes.
> backend/remote: allow enhanced backends to pass custom exit codes

- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan_test.go
This commit adds logic to check if a workspace is configured to auto apply changes. And if it does, we make sure we output all steps correctly.
> backend/remote: properly handle workspaces that auto apply changes

- backend/local/backend.go
- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
We previously asked to override a soft-failed policy, even wehn -auto-approve was set. That is now fixed by returning a policy failed error.
> backend/remote: don’t ask questions when -auto-approve is set

- builtin/provisioners/chef/linux_provisioner.go
- builtin/provisioners/chef/linux_provisioner_test.go
`chown user.group` appears to _work_ in linux but not documented (at least not in the `chown` man page). It also simply doesn't work at all in freebsd (at least on my pfsense machine based on freebsd 11). This changes the provisioner to use the more standard `chown user:group` syntax.
Please let me know if this introduces some obscure compatibility issue I'm not aware of.
> change chef linux provisioner to use user:group chown syntax

- backend/local/cli.go
- command/apply_test.go
- states/statemgr/filesystem.go
Set the backend cli options after configuration is applied. The old behavior was a mix of config and cli, and having cli override config consistently makes more sense.
Some minor fixes for command tests to get out of the way
> Backend config and command tests

- helper/validation/validation.go
- helper/validation/validation_test.go
`All()` combines the outputs of multiple `SchemaValidateFunc`, to reduce the usage of custom validation functions that implement standard validation functions.
Example provider usage:
```go
ValidateFunc: validation.All(
validation.StringLenBetween(5, 42),
validation.StringMatch(regexp.MustCompile(`[a-zA-Z0-9]+`), "value must be alphanumeric"),
),
```
`IntInSlice()` is the `int` equivalent of `StringInSlice()`
Example provider usage:
```go
ValidateFunc: validation.IntInSlice([]int{30, 60, 120})
```
Output from unit testing:
```
$ make test TEST=./helper/validation
2018/10/17 14:16:03 Generated command/internal_plugin_list.go
go list ./helper/validation | xargs -t -n4 go test  -timeout=2m -parallel=4
go test …
```
> helper/validation: Add All() and IntInSlice() SchemaValidateFunc

- go.mod
- go.sum
- plans/objchange/objchange.go
- plans/objchange/objchange_test.go
- vendor/github.com/zclconf/go-cty/cty/function/function.go
- vendor/github.com/zclconf/go-cty/cty/value_ops.go
- vendor/golang.org/x/net/html/parse.go
- vendor/golang.org/x/net/http2/write.go
- vendor/modules.txt
These two panics are actually not really connected at all but happened both be triggered by a "set of object type" value during the plan step, and therefore both cropped up at the same time.
The first is in Terraform itself, where it was failing to deal with the possibility of the "old" value being null/unknown (as it is for a `Create` action).
The second is in the underlying library `cty` where the `cty.Value.HasElement` method -- which tests if a particular element is present in a set -- was not comparing types correctly and was thus panicking when given a set whose element type is an object type. (This would also have been true for a set whose element type is a tuple type, since these are also not comparable using Go's `==` operator.)
> Fix two set-of-objects-related panics

- helper/plugin/grpc_provider.go
- plugin/grpc_provider.go
- plugin/grpc_provider_test.go
- plugin/mock_proto/mock.go
- plugin/proto/plugin.pb.go
- plugin/proto/plugin.proto
- providers/provider.go
- terraform/context_validate_test.go
- terraform/eval_validate.go
- terraform/provider_mock.go
This PR changes the method name and all call sites for PrepareProviderConfig.
This does not yet include the new logic for setting the defaults, but will allow for any parallel work to be done in core while the plugin work is finished.
> PrepareProviderConfig

- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
These may still have defaults set, even if they are not intended to be
used.
> don't set defaults for deprecated or removed

- .travis.yml
- Makefile
- go.mod
- go.sum
- plans/internal/planproto/generate.go
- plans/internal/planproto/generate.sh
- plugin/proto/generate.go
- plugin/proto/generate.sh
- plugin/proto/plugin.pb.go
- states/objectstatus_string.go
- vendor/github.com/golang/mock/gomock/matchers.go
- vendor/modules.txt
Since `protoc` is not go-gettable, and most development tasks in Terraform won't involve recompiling proto files anyway, we'll use a separate mechanism for these.
This way `go generate` only depends on things we can `go get` in the `make tools` target.
In a later commit we should also in some way specify a particular version of `protoc` to use so that we don't get "flapping" regenerations as developers work with different versions, but the priority here is just to make "make generate" minimally usable again to restore the dev workflow documented in the README.
This also includes some updates that resulted from running `make generate` and `make protobuf` after those `Makefile` changes were in place.
> build: Take protoc out of the "go generate" path

- helper/schema/resource.go
This was previously done in the RequiresNew code, which is skipped in
new style provider.
> add old values when computing the new InstanceDiff

- command/format/diagnostic.go
- tfdiags/diagnostic.go
- tfdiags/diagnostic_base.go
- tfdiags/error.go
- tfdiags/hcl.go
- tfdiags/rpc_friendly.go
- tfdiags/simple_warning.go
When an error occurs evaluating an expression, HCL annotates the diagnostic with information about what was being evaluated and in what context. Here we use that information to include additional contextual information in the diagnostics output.
This is particularly useful when the error relates to an expression that gets evaluated multiple times, and therefore the static source location information is not enough to fully understand what's going on. For example:
* Any expression within a block with `count` or `for_each` set.
* The sub-expressions of a `for` expression.
This is just a first pass at a rendering approach for this, with the expectation that we'll iterate on it further in later releases. I just wanted to get this in here now so that those experimenting with our early release …
> command/format: Include variable values as additional context in diagnostic messages

- backend/local/backend_refresh_test.go
- command/apply_test.go
Not sure if these checks still make sense, but without this change the test don’t compile for the related packages.
> Make the test compile again

- helper/validation/validation.go
- helper/validation/validation_test.go
`Any()` allows any single passing validation of multiple `SchemaValidateFunc` to pass validation to cover cases where a standard validation function does not cover the functionality or to make error messaging simpler.
Example provider usage:
```go
ValidateFunc: validation.Any(
validation.IntAtLeast(42),
validation.IntAtMost(5),
),
```
Output from unit testing:
```
$ make test TEST=./helper/validation
2018/10/18 20:57:55 Generated command/internal_plugin_list.go
go list ./helper/validation | xargs -t -n4 go test  -timeout=2m -parallel=4
go test -timeout=2m -parallel=4 github.com/hashicorp/terraform/helper/validation
ok  	github.com/hashicorp/terraform/helper/validation	0.750s
```
> helper/validation: Add Any() SchemaValidateFunc

- backend/backend.go
- backend/local/backend_apply_test.go
- backend/local/backend_local.go
- backend/local/backend_plan_test.go
- backend/local/test-fixtures/apply-vars/main.tf
- backend/local/test-fixtures/plan-vars/main.tf
Previously the `local` backend didn’t merge variables but completely replaced them when any backend operation variables were set.
Before [this change](https://github.com/hashicorp/terraform/commit/67db9da000#diff-a0d5ae04114a139f2356fb16fbac7581R174) this was essentially a dead codepath (that didn't have any tests) as the backend operation would never have a value for these variables and so the complete set of variables created while getting the `ContextOpts` would be used instead: https://github.com/hashicorp/terraform/blob/v0.11/command/meta.go#L312
But the variables were added to the backend operation because the `remote` backend needs access to these command line variables so they can be set as run variables. Run variables are not yet supported in this release, but this value is still …
> backend/local: do not use backend operation variables

- lang/funcs/collection.go
- lang/funcs/collection_test.go
Previously a config like this:
```hcl
locals {
terraform_versions = {
"terraform-provider-aws" = "0.10+"
}
}
provider "github" {
organization = var.organization_name
token = var.github_token
}
data "github_repositories" "providers" {
query = "org:${var.organization_name} archived:false aws OR azurerm OR google OR opc OR vsphere OR kubernetes"
}
data "github_repository" "provider" {
count = length(data.github_repositories.providers.full_names)
full_name = sort(data.github_repositories.providers.full_names)[count.index]
}
data "template_file" "readme" {
count = length(data.github_repository.provider.*.ssh_clone_url)
template = file("./templates/README.md")
vars = {
go_version = lookup(local.go_versions, data.github_repository.provider.*.name[count.index], local.default_go_version)
}
}
``` …
> lang: Fix crash in lookup function

- terraform/resource.go
- terraform/resource_test.go
Added some tests, since this function wasn't previously used outside of the terraform unit tests.
>  missed IsNull check in config shim

- svchost/svchost_test.go
When I try to use terraform module with a custom private registry, I found terraform doesn't handle correctly hostname started with a numeric character like `123.example.com` or `1example.com`
```
module "vpc" {
source = "123.example.com/namespace/name/provider"
}
```
So, I updated `idna` and added a new test case.
Previously, it throws an error like:
```
--- FAIL: TestForComparison (0.00s)
--- FAIL: TestForComparison/1example.com (0.00s)
svchost_test.go:173: unexpected error; want success
error: idna: invalid label "1example"
svchost_test.go:177: wrong result
input: 1example.com
got:
want:  1example.com
```
> Update golang.org/x/net/idna to handle hostname started with numeric

- website/docs/backends/operations.html.md
- website/layouts/docs.erb
Apparently we made a stub page for this ages ago, but now it doesn't have to be a stub anymore.
> website: Update and link the page about remote backend operations

- builtin/providers/test/provider.go
- builtin/providers/test/resource_timeout.go
- builtin/providers/test/resource_timeout_test.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
- helper/resource/testing_config.go
- helper/schema/core_schema.go
- terraform/resource.go
Resource timeouts were a separate config block, but did not exist in the
resource schema. Insert any defined timeouts when generating the
configshema.Block so that the fields can be accepted and validated by
core.
helper/schema will remove "timeouts" from the config, and stash them in
the diff.Meta map. Terraform sees "timeouts" as a regular config block,
so needs them to be present in the state in order to not show a diff.
Have the GRPCProviderServer shim copy all timeout values into any state
it returns to provide consistent diffs in core.
> provider timeouts

- builtin/providers/test/provider.go
- builtin/providers/test/resource_diff_suppress.go
- builtin/providers/test/resource_diff_suppress_test.go
- helper/plugin/grpc_provider.go
The prior state may contain customizations made by the provider. If
there is no prior state, then take the proposed state.
Fixes #19211
> prefer prior state when there is no plan diff

- builtin/providers/test/provider.go
- builtin/providers/test/resource_force_new.go
- builtin/providers/test/resource_force_new_test.go
- builtin/providers/test/resource_test.go
- config/hcl2shim/paths.go
- config/hcl2shim/paths_test.go
- helper/plugin/grpc_provider.go
- terraform/eval_diff.go
Fields that were in the RequiresNew list must only be for object attributes. Trim off any trailing index steps from the set of paths.
Create a new proposed value when replacing an instance, using the null state and the config. This ensures that all unknown values are properly set.
> fix instance replacement

- helper/resource/testing_import_state_test.go
- helper/resource/testing_test.go
These aren't going to be fixed in the immediate future, and are
preventing the CI tests from being helpful.
> skip resource tests for now

- builtin/providers/test/provider.go
- builtin/providers/test/resource_nested.go
- builtin/providers/test/resource_nested_test.go
- terraform/diff.go
If a legacy diff has equal old and new values, don't apply the diff.
These would show up in sets, because of the overall change in set key, or because the stored value can't be differentiated from nil.
Fixes #19215
>  don't apply unchanged attributes from legacy diffs

- state/remote/state.go
In the case when no state existed remotely and a new one was created locally, we don’t want to blow away the new local state when refreshing.
> Do not clear out a previous set state when refreshing

- plans/changes.go
- plans/changes_sync.go
- terraform/context_plan_test.go
- terraform/eval_diff.go
- terraform/eval_output.go
- terraform/evaluate.go
- terraform/test-fixtures/plan-required-output/main.tf
- terraform/test-fixtures/plan-required-output/mod/main.tf
- terraform/test-fixtures/plan-required-whole-mod/main.tf
- terraform/test-fixtures/plan-required-whole-mod/mod/main.tf
Failing minimal test for #19223
The issue is that the evaluation of the config (from `EvaluateBlock`) returns a `Null` value for the `required` field when referencing an attribute in a module output, rather than `Unknown`.
> null eval from output

- helper/schema/provider_test.go
- helper/schema/resource_test.go
- helper/schema/resource_timeout.go
- helper/schema/resource_timeout_test.go
- helper/schema/shims_test.go
I'm not sure when/where/why we decided to produce a simple map instead of slice (read as _I didn't go through all the refactoring commits_), but it makes more sense to me, so I'm assuming it was intentional.
Also I don't know why are we were not originally erroring out on invalid timeout types as I couldn't find a corresponding PR to this commit https://github.com/hashicorp/terraform/commit/aa3677cd896809718f26d066216ded14673a7961
cc @catsby ^
> helper/schema: Fix timeout parsing during Provider.Diff

- lang/funcs/collection.go
- lang/funcs/collection_test.go
These commits include some fixes and refinements to the built-in function implementations:
* Object types were not being accepted for `length`, as reported in #19278.
* There was an intermittent panic bug for the `values` function due to it not consistently ordering attribute names when building the result type for values over an object. (#19204)
* There was a failing test from an earlier change to the `lookup` function's handling of unknown object values.
* While I was in the neighborhood of `values` anyway, I made some refinements to the precision of its results in some edgier cases:
* `keys` on an unknown object type produces a known tuple result, since the attribute names are part of the type.
* `values` on an unknown object type produces an unknown tuple result of the appropriate …
> lang/funcs: Various fixes and refinements

- helper/schema/resource_timeout.go
This is to fix a bug I introduced in https://github.com/hashicorp/terraform/pull/19286
It also partially answers my question posed in that PR:
> I don't know why are we were not originally erroring out on invalid timeout types
I still believe we don't need to ignore any invalid types though.
```
$ make test TEST=./builtin/providers/test/...
```
```
2018/11/07 15:25:41 Generated command/internal_plugin_list.go
go list ./builtin/providers/test/... | xargs -t -n4 go test  -timeout=2m -parallel=4
go test -timeout=2m -parallel=4 github.com/hashicorp/terraform/builtin/providers/test
--- FAIL: TestResourceTimeout_read (0.01s)
testing.go:583: Step 0 error: Error planning: [ERR] Error decoding timeout: Invalid Timeout …
```
> helper/schema: Avoid erroring out on undefined timeouts

- website/docs/backends/types/swift.html.md
The docs contained an error telling people to use `expire_after` when they really wanted object versioning. This error is actually quite damaging because instead of not even retaining versions of the state, it is outright deleted after a given amount of time. Fixed up the examples and other bits to not use deprecated items. Fixed bad links to the OpenStack Swift project. Added more links to the OpenStack Swift project. fixes #19005
> Fix backend/swift docs

- command/meta_backend.go
- command/meta_backend_migrate.go
If the backend does not support workspaces, we don't have to try to
select a workspace and we should not return an error.
> backend/migrations: only select workspaces if supported

- helper/resource/testing_config.go
If a test config is invalid, there could still be previous state if the invalid config comes in a step after a valid config was applied. Currently, if that happens, resources are left dangling because the destroy step is skipped due to lack of state (see this [test log](https://ci-oss.hashicorp.engineering/repository/download/GoogleCloud_ProviderGoogleCloud/33605:id/debug-google-e5a6492-TestAccComputeFirewall_enableLogging.log) for an example). This fixes the bug.
> return state in tests even if cfg is invalid

- backend/atlas/state_client.go
- backend/atlas/state_client_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-retryablehttp/client.go
- vendor/github.com/hashicorp/go-retryablehttp/go.mod
- vendor/github.com/hashicorp/go-retryablehttp/go.sum
- vendor/github.com/hashicorp/go-tfe/go.mod
- vendor/github.com/hashicorp/go-tfe/go.sum
- vendor/github.com/hashicorp/go-tfe/policy_set.go
- vendor/modules.txt
Newer versions of the retryablehttp package use a context, so we need to
add that in our custom `CheckRetry` function.
In addition I removed the `return true, nil` to continue retrying in
case of an error, and instead directly call the `DefaultRetryPolicy`.
This is because the `DefaultRetryPolicy` will now also take the context
into consideration.
> Make the Atlas backend work after updating depencies

- builtin/providers/test/provider.go
- builtin/providers/test/resource_diff_suppress.go
- builtin/providers/test/resource_diff_suppress_test.go
- builtin/providers/test/resource_nested_set.go
- builtin/providers/test/resource_nested_set_test.go
- config/hcl2shim/flatmap.go
- config/hcl2shim/flatmap_test.go
- configs/configschema/coerce_value.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
- helper/resource/state_shim.go
- helper/schema/resource.go
- helper/schema/shims.go
- helper/schema/shims_test.go
- terraform/diff.go
This implements a couple a major changes to make the shimmed diffs work with the legacy provider code.
First, all handling of shimmed state now goes through the `ResourceData` struct, which rebuilds the flatmapped sets so that the keys match in the attributes and the diffs. Since this is what happens in the legacy Apply phase, the behavior should match.
The other major piece is `InstanceDiff.Apply`, which removes one unnecessary cycle of shimming, and applies the diff to the flatmapped attributes. The new application algorithm handles various types differently, based on the observed edge cases produced by the helper/schema package, and builds a new attribute map from scratch to prevent old mismatched set items from being preserved.
To clean up the diffs and attributes, all empty attribute …
> New Attribute and Diff handling in shims

- command/command_test.go
- e2e/e2e.go
In a couple places in tests we execute a child `go build` to make a helper program. Now that we're running in module mode, `go build` will normally default to downloading and caching dependencies, which we don't want because we're still using vendoring for the moment.
Therefore we need to instruct these child builds to use vendoring too, avoiding the need to download all of the dependencies and ensuring that we'll be building with the same dependencies that we'd use for a normal build.
(The main motivation of doing this now is actually to avoid wastefully re-downloading all of our dependencies when running tests in Travis-CI.)
> command: Use vendoring when building helper programs in tests

- helper/plugin/grpc_provider_test.go
- states/state_string.go
- terraform/context_plan_test.go
- terraform/diff.go
- terraform/provider_mock.go
It's possible that a computed collection could be handled by the
attribute name, rather than the index count value.
Use a new testDiffFn for some tests, which don't work with the old
function that can't determine `computed` without the schema.
add missing key-value from test
>  fixes for the remaining tests

- backend/init/init.go
- backend/init/init_test.go
- backend/local/backend.go
- backend/local/backend_apply_test.go
- backend/local/backend_plan.go
- backend/remote/backend.go
- backend/remote/backend_apply.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
- backend/remote/backend_test.go
- backend/remote/cli.go
- backend/remote/remote_test.go
- backend/remote/test-fixtures/apply-destroy/apply.log
- backend/remote/test-fixtures/apply-policy-passed/apply.log
- backend/remote/test-fixtures/apply-policy-soft-failed/apply.log
- backend/remote/test-fixtures/apply-variables/apply.log
- backend/remote/test-fixtures/apply/apply.log
- backend/remote/testing.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/modules.txt
In order to support free organizations, we need a way to load the `remote` backend and then, depending on the used offering/plan, enable or disable remote operations.
In other words, we should be able to dynamically fall back to the `local` backend if needed, after first configuring the `remote` backend.
To make this work we need to change the way this was done previously when the env var `TF_FORCE_LOCAL_BACKEND` was set. The clear difference of course being that the env var would be available on startup, while the used offering/plan is only known after being able to connect to TFE.
> backend/remote: change how to fall back to a local backend

- website/docs/commands/cli-config.html.markdown
- website/docs/commands/init.html.markdown
- website/docs/configuration/providers.html.md
- website/docs/plugins/basics.html.md
...and one other reference to the application data directory.
Companion PR to https://github.com/hashicorp/terraform-website/pull/565. 
Context:
https://docs.microsoft.com/en-us/windows/desktop/shell/knownfolderid#folderid_roamingappdata
In newer Windows versions, the folder accessible as `%APPDATA%` (and via various
APIs) is actually at something like "documents and settings\user\application
data\roaming", while earlier versions omit the "\roaming" part of the path. This
means you can confuse people by referring to the "application data" directory by
its human name, because "roaming" is the real application data directory, but it
looks like a subdirectory of "application data".
Thus, it's less confusing to just use the `%APPDATA%` variable, with the added
benefit that you can copy and …
> website: Fix plugin path on Windows

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/backend.go
- backend/remote-state/azure/backend_test.go
- backend/remote-state/azure/client_test.go
- backend/remote-state/azure/helpers_test.go
- website/docs/backends/types/azurerm.html.md
Requires a feature-toggled acceptance test, since this could only be run from within an Azure VM
Fixes #18425
> backend/azurerm: support for authenticating via msi

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/backend.go
- backend/remote-state/azure/backend_test.go
- backend/remote-state/azure/client_test.go
- backend/remote-state/azure/helpers_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-azure-helpers/storage/sas_token.go
- vendor/modules.txt
- website/docs/backends/types/azurerm.html.md
This PR adds support for authenticating using a SAS Token, which allows limited access permissions to be used to access a Storage Account.
Needs to be merged after #19433
> backend/azurerm: support for authenticating via SAS Tokens

- backend/remote-state/azure/backend.go
- backend/remote-state/azure/backend_test.go
- backend/remote-state/azure/client_test.go
- website/docs/backends/types/azurerm.html.md
This makes the Backend consistent with the AzureRM/Azure Stack Provider such that this is less confusing for users.
Rather than making this a breaking change I've added a compatibility path and removed references to the old names from the docs.
> backend/azurerm: removing the `arm_` prefix from keys

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/backend.go
- backend/remote-state/azure/backend_test.go
- backend/remote-state/azure/client_test.go
- backend/remote-state/azure/helpers_test.go
- website/docs/backends/types/azurerm.html.md
This allows the AzureRM Backend to be used with Azure Stack
Needs to be merged after #19448
> backend/azurerm: support for custom resource manager endpoints

- command/format/diagnostic.go
- command/validate_test.go
- configs/parser_config_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl2/gohcl/doc.go
- vendor/github.com/hashicorp/hcl2/gohcl/encode.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_ops.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_template.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/navigation.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/node.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/structure.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/variables.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/walk.go
- vendor/github.com/hashicorp/hcl2/hcled/navigation.go
- vendor/github.com/hashicorp/hcl2/hclwrite/ast.go
- vendor/github.com/hashicorp/hcl2/hclwrite/ast_attribute.go
- vendor/github.com/hashicorp/hcl2/hclwrite/ast_block.go
- vendor/github.com/hashicorp/hcl2/hclwrite/ast_body.go
- vendor/github.com/hashicorp/hcl2/hclwrite/ast_expression.go
- vendor/github.com/hashicorp/hcl2/hclwrite/doc.go
- vendor/github.com/hashicorp/hcl2/hclwrite/generate.go
- vendor/github.com/hashicorp/hcl2/hclwrite/node.go
- vendor/github.com/hashicorp/hcl2/hclwrite/parser.go
- vendor/github.com/hashicorp/hcl2/hclwrite/tokens.go
- vendor/modules.txt
Depends on https://github.com/hashicorp/hcl2/pull/58
----
I'm thinking maybe we should suppress the "context string" to avoid the duplication, i.e.
```
on /var/workspace/tf-test/repro-case/main.tf line 21:
21: resource "aws_instance" "web" {
```
but then we might need the context in the future, more complex cases when we figure out how to render snippets with interpolated `count.index`? I'm not sure.
----
It is worth mentioning that there is currently *no context* rendered for errors returned during refresh or import, because the relevant `EvalNode` implementations (e.g. `EvalRefresh`) don't have access to config at all, so there is no way to match it at this point.
If we want to avoid passing config to these `EvalNode`s we might need to consider adding context in the form of IDs or …
> command/format: Fix rendering of attribute-agnostic diagnostics

- helper/schema/core_schema.go
- helper/schema/core_schema_test.go
- helper/schema/schema.go
The commits in this PR are addressing some real-world situations where the schema generated by `CoreConfigSchema` didn't totally reflect the pre-v0.12 behavior where Terraform did not validate configuration at all.
Each of these commits is distinct from the others aside from them all being in the same package, so I expect it will be easiest to review these commit-by-commit.
This fixes both #19139 and #19422.
> helper/schema: CoreConfigSchema refinements

- builtin/providers/test/resource_diff_suppress.go
- builtin/providers/test/resource_nested_set.go
- builtin/providers/test/resource_test.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
- plans/objchange/compatible.go
When normalizing flatmapped containers, compare the attributes to the
prior state and preserve pre-existing zero-length or unknown values. A
zero-length value that was previously unknown is preserved as a
zero-length value, as that may have been computed as such by the
provider.
This also fixes a crash in  `plans/objchange` by returning early to prevent iterating on a null value.
Fixes #19469
> Shim computed containers

- backend/local/backend_plan.go
- terraform/eval_apply.go
- terraform/eval_diff.go
- terraform/eval_read_data.go
- terraform/eval_refresh.go
- terraform/eval_state.go
- terraform/eval_validate.go
- terraform/eval_validate_selfref.go
- terraform/evaluate.go
- terraform/evaluate_valid.go
- terraform/node_resource_abstract.go
- terraform/schemas.go
- terraform/transform_attach_schema.go
Previously we were fetching these from the provider but then immediately discarding the version numbers because the schema API had nowhere to put them.
To avoid a late-breaking change to the internal structure of `terraform.ProviderSchema` (which is constructed directly all over the tests) we're keeping the resource type schema versions in a new map alongside the existing one with the same keys, rather than just switching to using the `providers.Schema` struct directly there.
The methods that return resource type schemas now return two arguments, intentionally creating a little API friction here so each new caller can be reminded to think about whether they need to do something with the schema version, though it can be ignored by many callers.
Since this was a breaking change to the …
> core: Make resource type schema versions visible to callers

- backend/remote/backend_apply_test.go
- backend/remote/backend_common.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
- backend/remote/test-fixtures/apply-no-changes/policy.log
- backend/remote/test-fixtures/plan-no-changes/main.tf
- backend/remote/test-fixtures/plan-no-changes/plan.log
- backend/remote/test-fixtures/plan-no-changes/policy.log
This behavior was recently updated in the TFE UI, so lets follow that behavior here as well.
> backend/remote: also show policies when there are no changes

- plugin/discovery/get.go
- plugin/discovery/get_test.go
- registry/regsrc/terraform_provider.go
- registry/regsrc/terraform_provider_test.go
- registry/test/mock_registry.go
Uses the new registry namespace alias `-` to fetch providers from the registry. Registry returns with the appropriate provider source, if exists, and TF includes the returned namespace for user information on download. Currently, the registry only is configured to support the `terraform-providers` namespace for the `-` alias but may change in the future.
Prior to change
```
- Checking for available provider plugins...
- Downloading plugin for provider "null" (1.0.0)...
```
**Success**
**Provider Not Found**
No error change here when a provider is not found within `terraform.d/plugins` or the registry.
> Use registry alias to fetch providers

- repl/session_test.go
- terraform/context_validate_test.go
- terraform/evaluate.go
- terraform/evaluate_valid.go
Previously we were making an invalid assumption in evaluating module call references (like `module.foo`) that the module must exist, which is incorrect for that particular case because it's a reference to a child module, not to an object within the current module.
However, now that we have the mechanism for static validation of references, we'll deal with this one there so it can be caught sooner. That then makes the original assumption valid, though for a different reason.
This fixes #19483.
> core: Validate module references

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Changing the Terraform provider link from "selvpc' -> "selectel" and move link to cloud providers
> [Website] Provider name change "Selectel"

- backend/remote/backend.go
- backend/remote/backend_mock.go
- backend/remote/backend_state.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-slug/go.mod
- vendor/github.com/hashicorp/go-slug/slug.go
- vendor/github.com/hashicorp/go-tfe/configuration_version.go
- vendor/github.com/hashicorp/go-tfe/go.mod
- vendor/github.com/hashicorp/go-tfe/go.sum
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/modules.txt
Add support for the new `force-unlock` API and at the same time improve performance a bit by reducing the amount of API calls made when using the remote backend for state storage only.
Additionally also updated some dependencies which solve a couple of open issues.
> backend/remote: support the new force-unlock API

- backend/local/backend_local.go
Fixes #19147
Variables values are marshalled with an explicit type of
cty.DynamicPseudoType, but were being decoded using `Implied Type` to
try and guess the type. This was causing errors because `Implied Type`
does not expect to find a late-bound value.
(I take no credit for this, @apparentlymart figured out the bug and solution)
> backend/local: decode variables with cty.DynamicPseudoType

- builtin/providers/test/provider.go
- builtin/providers/test/resource_state_func.go
- builtin/providers/test/resource_state_func_test.go
- helper/plugin/grpc_provider.go
- plugin/grpc_provider.go
Any state modifying functions can only be run once during the plan-apply
cycle. When regenerating the Diff during ApplyResourceChange,
strip out all StateFunc and CustomizeDiff functions from the schema.
During PlanResourceChange, store any NewExtra data from the Diff in the
PlannedPrivate data, and re-insert the NewExtra data into the Diff
generated during ApplyResourceChange.
> Handle StateFunc in plugin shims

- vendor/github.com/kardianos/osext/README.md
- vendor/github.com/kardianos/osext/osext_go18.go
- vendor/github.com/kardianos/osext/osext_plan9.go
- vendor/github.com/kardianos/osext/osext_procfs.go
- vendor/github.com/kardianos/osext/osext_sysctl.go
- vendor/github.com/kardianos/osext/osext_windows.go
In order to get rid of ``Couldn't start Terraform: ExecPath not implemented for android``
> vendor: update kardianos/osext to support android

- command/format/state.go
I stumbled across some unpleasant formatting that I hadn't caught earlier: 
Before:
```
new = "hi dad"pets = [
"Pet: linus-closing-dove",
"Pet: linus-usable-reindeer",
"Pet: linus-united-shark",
]
```
After:
```
new = "hi dad"
pets = [
"Pet: linus-closing-dove",
"Pet: linus-usable-reindeer",
"Pet: linus-united-shark",
]
```
> format/state: added missing newline in the `outputs` output

- helper/schema/resource_diff_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
When the following conditions were met:
* Schema attribute with a primitive type (e.g. `Type: TypeString`) and `Computed: true`
* Old state of attribute set to zero value for type (e.g. `""`)
* Old state ID of resource set to non-empty (e.g. existing resource)
Attempting to use `CustomizeDiff` with `SetNewComputed()` would result in the difference  previously being discarded. This update ensures that previous zero values or resource existence does not influence the propagation of the computed update.
References:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6721
* https://github.com/terraform-providers/terraform-provider-aws/issues/6710
* https://github.com/hashicorp/terraform/pull/9618
Previously:
```
--- FAIL: TestSetNewComputed (0.00s)
--- FAIL: …
```
> helper/schema: Always propagate NewComputed for previously zero value primitive type attributes

- helper/resource/state_shim.go
- helper/resource/state_shim_test.go
Many provider tests rely on internal details of the legacy state, so we need to match it as closely as possible. Core would previously remove count indexes when the count was 0, so this matches that behavior in the shim.
> don't add numeric indexes to resources with a count of 0

- helper/resource/testing_config.go
- helper/resource/testing_import_state.go
- terraform/context.go
- terraform/context_import_test.go
- terraform/test-fixtures/import-provider-resource/main.tf
- terraform/transform_import_state.go
- Insert missing implied providers for imports when building the graph.
- Remove empty flatmapped containers from the import test states, so they can be more easily compared.
Fixes #19421
> Fix provider import tests

- states/statemgr/filesystem_test.go
This ensures that we test using the same source as we're using everywhere else, and more tactically also ensures that when running in Travis-CI we won't try to download all of the dependencies of Terraform during this test.
In the long run we will look for a more global solution to this, rather than adding this to all of our embedded `go` command calls directly, but this is intended as a low-risk solution to get the build working again in
the mean time.
> states/statemgr: use -mod=vendor to run the state locking helper

- backend/remote/backend.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan_test.go
- backend/remote/testing.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-tfe/organization.go
- vendor/modules.txt
Use the entitlements to a) determine if the organization exists, and b) as a means to select which backend to use (the local backend with remote state, or the remote backend).
> backend/remote: use entitlements to select backends

- helper/resource/testing.go
- helper/resource/testing_config.go
- helper/resource/testing_import_state.go
For better realism compared to normal Terraform runs, here we switch to calling through to the underlying factory function once for each call to our GRPC-mock-wrapping factory function.
Along with this, we can also avoid manually constructing a `terraform.Schemas` object in the test harness by using the one that was constructed during `terraform.NewContext`, avoiding the need to instantiate the provider one extra time before the tests begin.
This doesn't yet fix the apparent race we're seeing in some of the test provider tests, but by limiting the lifetime of the provider objects we can at least reduce the risk of unrealistic provider state bleeding between test steps.
> helper/resource: Don't share provider instances between test steps

- builtin/providers/terraform/data_source_state.go
Terraform 0.11.10 added schema validation to the `terraform_remote_state` data source. We're using an S3 backend provider with the `force_path_style = true` option configured and, when moving to 0.11.10, our templates started failing with an error stating `force_path_style` was an unrecognized option for the data source. A quick look into the source showed that option was left out of the schema list. This pull adds it back in so the same option set for the S3 backend is supported by the remote state data source.
> Adding missing S3 force_path_style option to schema check.

- configs/configupgrade/analysis.go
- configs/configupgrade/analysis_expr.go
- configs/configupgrade/test-fixtures/valid/redundant-list/input/redundant-list.tf
- configs/configupgrade/test-fixtures/valid/redundant-list/want/redundant-list.tf
- configs/configupgrade/test-fixtures/valid/redundant-list/want/versions.tf
- configs/configupgrade/upgrade_body.go
- configs/configupgrade/upgrade_expr.go
- configs/configupgrade/upgrade_test.go
- go.mod
- go.sum
- helper/resource/testing.go
- helper/resource/testing_config.go
- lang/eval.go
- plugin/grpc_provider.go
- terraform/node_resource_abstract.go
- terraform/transform_resource_count.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
- vendor/modules.txt
In early versions of Terraform where the interpolation language didn't have any real list support, list brackets around a single string was the signal to split the string on a special uuid separator to produce a list just in time for processing, giving expressions like this:
```hcl
foo = ["${test_instance.foo.*.id}"]
```
Logically this is weird because it looks like it should produce a list of lists of strings, but in practice the outer list was just a marker to enable the splitting behavior.
When we added real list support in Terraform 0.7 we retained support for this behavior by trimming off extra levels of list during evaluation, and inadvertently continued relying on this notation for correct type checking.
During the Terraform 0.10 line we fixed the type checker bugs (a few remaining …
> configs/configupgrade: Fix up legacy redundant list bracket usage

- helper/schema/field_writer_map.go
- helper/schema/resource_data_test.go
The added test in this commit, without the fix, will make d.Set return
the following error:
`Invalid address to set: []string{"ports", "0", "set"}`
This was due to the fact that setSet in feild_writer_map tried to
convert a slice into a set by creating a temp set schema and calling
writeField on that with the address(`[]string{"ports", "0", "set"}"` in
this case). However the temp schema was only for the set and not the
whole schema as seen in the address so, it should have been `[]string{"set"}"`
so it would align with the schema.
This commits adds another variable there(tempAddr) which will only
contain the last entry of the address that would be the set key, which
would match the created schema
This commit potentially fixes the problem described in #16331
> helper/schema: Fix setting a set in a list caused error

- backend/remote/backend.go
- backend/remote/backend_test.go
- registry/client.go
- registry/errors.go
- svchost/disco/disco.go
- svchost/disco/disco_test.go
- svchost/disco/host.go
- svchost/disco/host_test.go
This PR improves the error handling so we can provide better feedback about any service discovery errors that occured.
Additionally it adds logic to test if a version exists when discovering a service using `service.vN`. This is used to enable more informational errors that can indicate version incompatibilities.
> core: enhance service discovery

- helper/schema/field_reader_diff.go
- helper/schema/field_reader_map.go
There were a couple spots where argument slices weren't being copied
before `append` was called, which could possibly modify the caller's
slice data.
> don't modify argument slices

- communicator/winrm/provisioner.go
- communicator/winrm/provisioner_test.go
lost quite a bit of time here trying to get winrm provisioner working due to the wrong default port being selected when Https, so have create a fix so hopefully no one else bumps into this.  Never written a line of Go in my life so hope it passes muster, but it is relatively straight forward.
> Fix winrm default ssl port

- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser_template.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.rl
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/spec.md
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/token.go
- vendor/github.com/hashicorp/hcl2/hcl/json/structure.go
- vendor/github.com/hashicorp/hcl2/hcl/merged.go
- vendor/github.com/hashicorp/hcl2/hclwrite/format.go
- vendor/github.com/hashicorp/hcl2/hclwrite/tokens.go
- vendor/modules.txt
This includes a number of upstream bug fixes, which in turn fix a number of issues here in Terraform:
- New-style "full splat" operator now working correctly (#19181)
- The weird HCL1-ish single-line block syntax is now supported (#19153)
- Formatting of single-line blocks adds spaces around the braces (#19154)
This also includes a number of other upstream fixes that were not tracked as issues in the Terraform repository. The highlights of those are:
- A `for` expression with the `for` keyword wrapped onto a newline after its opening bracket now parses correctly.
- In JSON syntax, interpolation sequences in properties of objects that are representing expressions now have their variables properly detected.
- The "flush" heredoc variant is now functional again after being broken n some …
> vendor: upgrade github.com/hashicorp/hcl2

- go.mod
- go.sum
- lang/eval.go
- terraform/context_validate_test.go
- terraform/eval_validate.go
- vendor/github.com/hashicorp/hcl2/hcl/traversal_for_expr.go
- vendor/modules.txt
Both `depends_on` and `ignore_changes` contain references to objects that we can validate.
Historically Terraform has not validated these, instead just ignoring references to non-existent objects. Since there is no reason to refer to something that doesn't exist, we'll now verify this and return errors so
that users get explicit feedback on any typos they may have made, rather than just wondering why what they added seems to have no effect.
This is particularly important for `ignore_changes` because users have historically used strange values here to try to exploit the fact that Terraform was resolving `ignore_changes` against a flatmap. This will give them explicit feedback for any odd constructs that the configuration upgrade tool doesn't know how to detect and fix.
---
In the process …
> core: Validate depends_on and ignore_changes traversals

- builtin/providers/test/data_source.go
- builtin/providers/test/data_source_test.go
- builtin/providers/test/resource_test.go
- terraform/eval_context_builtin.go
- terraform/evaluate.go
One of these tests is fixed with a recent hcl2 update.
The other is fixed by not checking state to expand EachMode during validation.
> failing count refs

- backend/remote/backend.go
This is a back ported fix from v0.12. There is no need to cut a release for this fix, but lets fix it anyway just in case we want another v0.11 release in the future.
> backend/remote: fix an error that prevents checking constraints

- states/sync.go
- terraform/eval_state.go
- terraform/node_data_destroy.go
- terraform/node_data_refresh.go
- terraform/node_data_refresh_test.go
- terraform/node_resource_refresh.go
- terraform/transform_attach_state.go
First some fixed to make sure we're not mutating shared state and causing any extra races:
- ResourceInstanceObject needs to return a copy
- attach a deep copy of ResourceState
Then we need to make sure that NodeDestroyableDataResource has a ResolvedProvider to
call EvalWriteState. This entails setting the ResolvedProvider in
concreteResourceDestroyable, as well as calling EvalGetProvider in
NodeDestroyableDataResource to load the provider schema.
Even though writing the state for a data destroy node should just be
removing the instance, every instance written sets the Provider for the
entire resource. This means that when scaling back a counted data
source, if the removed instances are written last, the data source will
be missing the provider in the state.
> Ensure we have providers when scaling in counted data sources

- command/meta_backend.go
- terraform/state.go
- terraform/state_test.go
Older versions of terraform could save the backend hash number in a
value larger than an int.
While we could conditionally decode the state into an intermediary data
structure for upgrade, or detect the specific decode error and modify
the json, it seems simpler to just decode into the most flexible value
for now, which is a uint64.
Fixes #19146
> decode backend hash as uint64

- backend/remote/backend.go
- backend/remote/backend_test.go
The `go-version` package treads prereleases in a specific way, but in terms of compatibility any beta, or RC should be compatible with the final release. So we just test against the version only.
> backend/remote: compare versions without the prerelease

- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/eval_validate.go
- terraform/eval_validate_test.go
- terraform/node_resource_validate.go
- terraform/provisioner_mock.go
- terraform/test-fixtures/apply-provisioner-conninfo/main.tf
- terraform/test-fixtures/graph-provisioners/main.tf
Catch errors in provisioners connection blocks during Validate rather than Apply.
Make `host` a required field, to better alert users that the old automatic connection mechanism is no longer used.
> Validate provisioner connection blocks

- terraform/eval_local.go
- terraform/eval_local_test.go
We already catch indirect cycles through the normal cycle detector, but we never create self-edges in the graph so we need to handle a direct self-reference separately here.
The prior behavior was simply to produce an incorrect result (since the local value wasn't assigned a new value yet).
This fixes #18503.
> core: Detect and reject self-referencing local values

- command/meta.go
- terraform/evaluate.go
- terraform/evaluate_test.go
This PR includes two adjustments to how we normalize configuration paths.
The first is general and applies both to the paths we show in diagnostic messages and the paths we return from `path.root` and `path.module`: previously we were normalizing these to relative paths in some commands but not others, which is both cosmetically weird and potentially problematic since `path.module` might return something different depending on which Terraform command you are running. We will now normalize these to be relative paths in all cases.
The second applies only to the `path.` references in configuration, making them always use forward slashes even on Windows systems. This addresses #14986 by relying on the fact that Windows supports both slash types as long as they are used consistently within a …
> Normalization of configuration paths

- configs/test-fixtures/invalid-files/interp-in-data-label.tf
- configs/test-fixtures/invalid-files/interp-in-rsrc-label.tf
- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
- vendor/modules.txt
This fixes #19327, which turned out to be specifically related to the handling of invalid labels in the HCL parser.
> Don't crash if there's an invalid interpolation inside a block label

- plans/changes_src.go
- plans/dynamic_value.go
- plans/planfile/tfplan_test.go
An empty change value cannot be decoded, so return a `cty.NullVal` to indicate the absence of a state value in this case.
Fixes #19149
> Don't fail decoding null values from plan changes

- builtin/providers/test/data_source_test.go
- terraform/evaluate_valid.go
- terraform/evaluate_valid_test.go
- terraform/test-fixtures/static-validate-refs/static-validate-refs.tf
In prior versions of Terraform we permitted inconsistent use of indexes in resource references, but in as of 0.12 the index usage must correlate properly with whether `count` is set on the resource.
Since users are likely to have existing configurations with incorrect usage, here we introduce some specialized error messages for situations where we can detect such issues statically. This seems to cover all of the common patterns we've seen in practice.
Some usage patterns will fall back on a less-helpful dynamic error here, but no configurations coming from 0.11 can end up that way because 0.11 did not permit forms such as `aws_instance.no_count[count.index].bar` that this validation would not be able to "see".
Our configuration upgrade tool also contains a fix for this already, but it …
> core: Specialized errors for incorrect indexes in resource reference

- command/jsonplan/plan.go
- command/jsonplan/values.go
New Output:
```json
"resource_changes": [
{
"address": "module.all_the_pets.module.inception.random_pet.sub_module_pets[0]",
"module_address": "module.all_the_pets.module.inception",
"mode": "managed",
"type": "random_pet",
"name": "sub_module_pets",
"index": 0,
"deposed": true,
"change": {
"actions": [
"Create"
],
"after_unknown": true
}
},
],
"output_changes": {
"new": {
"actions": [
"Create"
],
"after": "hi dad",
"after_unknown": false
},
"pets": {
"actions": [
"Create"
],
"after_unknown": true
}
},
```
> jsonplan: remove "proposed_unknown" structure in favor of "after_unknown" field in "change"

- builtin/providers/terraform/data_source_state.go
- builtin/providers/terraform/data_source_state_test.go
Fetching a state requires a workspace name, which should default to
"default"
Fixes #19217
> there is always an implied workspace of "default"

- terraform/state.go
- terraform/state_filter.go
- terraform/state_test.go
Restore necessary code for `terraform.State.Remove`. There could be code that could be pruned from `state_filter.go` I didn't try and piecemeal it back together (just restored the whole file). I did not restore `state_filter_test.go` as I would have had to restore the text fixtures for it, I can totally restore those just wasn't sure how far to "pull on the thread".
> restore (via copypaste) terraform.State.Remove

- helper/schema/schema.go
- helper/schema/schema_test.go
With the introduction of explicit `null` in 0.12 it's possible for a value that is unknown during plan to become a known null during apply, so we need to slightly weaken our validation rules to accommodate that, in particular skipping the validation of conflicting attributes if the result could potentially be valid after the unknown values become known.
This change is in the codepath that is common to both 0.12 and 0.11 callers, but that's safe because 0.11 re-runs validation during the apply step and so will still catch problems here, albeit in the apply step
rather than in the plan step, thus matching the 0.12 behavior. This new behavior is a superset of the old in the sense that everything that was valid before is still valid.
The implementation here also causes us to skip all other …
> helper/schema: Skip validation of unknown values

- helper/resource/state_shim.go
- helper/resource/state_shim_test.go
We use a shim to convert from the new state model back to the old because the provider test API is still using the old API throughout. However, the shim was not preserving the schema version recorded in the new-style state and so a round-trip through this shim would cause the schema versions to all revert to zero.
This can cause trouble with the destroy phase of provider tests because (for API legacy reasons) we round-trip from old state back to new again before the destroy phase and thus causing the providers to try to upgrade from state version zero even though the data was already latest, which can cause errors because state upgrades are generally not idempotent.
This fixes #19753.
> helper/resource: Shim back to old state must preserve schema version

- lang/functions.go
- website/docs/configuration/functions/format.html.md
- website/docs/configuration/functions/formatdate.html.md
- website/docs/configuration/functions/timestamp.html.md
We missed this one on a previous pass of bringing in most of the cty stdlib functions.
This will resolve #17625 by allowing conversion from Terraform's conventional RFC 3339 timestamps into various other formats.
Since this is just a reference to the existing `formatdate` function from `cty`, we don't have any local tests for it -- there's no precedent for re-testing those in Terraform right now -- but this does introduce reference documentation for the Terraform website about it.
> lang: Add "formatdate" function

- helper/resource/testing.go
- helper/resource/testing_test.go
Due to incorrect use of a loop iterator variable inside a closure, all of the given providers were ending up with the same factory function. Now we copy the factory function to a local within the loop first so that
each iteration has its own variable.
This is the second round of similar bugs in this function, so we'll also add a test case for it to reduce the risk of future regressions given that most real callers don't exercise this with multiple providers in practice.
This fixes #19755.
> helper/resource: Allow multiple providers in a single TestCase

- builtin/providers/test/resource_nested_set.go
- builtin/providers/test/resource_nested_set_test.go
- builtin/providers/test/resource_nested_test.go
- builtin/providers/test/resource_test.go
- config/hcl2shim/flatmap.go
- config/hcl2shim/flatmap_test.go
- config/hcl2shim/values.go
- config/hcl2shim/values_test.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
- plugin/grpc_provider.go
This contains a few improvements in the shim functions and the shimmed grpc providers. The key spots are improvements to `HCL2ValueFromFlatmap`, `ConfigValueFromHCL2Block`, and the new  `copyMissingValues` used in the plugin.
- When converting to config values from HCL2 values, ensure that empty nested blocks correspond to empty objects in the config.
- If a flatmap value has a count of 1 and no other attributes, it
usually indicates the equivalent configuration of an empty (or default
value) set block. Treat this as containing a single zero value object
and insert that into the cty.Value set.
- `copyMissingValues` copies missing values from one cty.Object to another.
If we have known zero value containers and primitives in the source,
which appear as null values in the destination, we …
> Better handling for empty containers and zero values in provider shims

- backend/remote/backend_apply.go
- backend/remote/backend_plan.go
If you are uploading a large repo or if TFE is experiencing peak load, it can take some time before your configuration is uploaded and the run is created.
By displaying the first 2 lines of the header before starting to prepare the run, people will know that the command started successfully and that the remote operation is being prepared.
> backend/remote: log early to indicate execution started

- plugin/discovery/get_test.go
The `return` statement omitted had prevented tests after the first case from running. Additionally, I think the remaining test cases expects the installer to be initialized with plugin protocol 4 (fails without the changes)
> Fix plugin protocol test

- builtin/providers/test/resource_nested_test.go
- helper/resource/state_shim.go
- helper/resource/state_shim_test.go
- helper/resource/testing.go
- helper/resource/testing_config.go
- helper/resource/testing_import_state.go
Provider tests often rely on checking values contained within sets, by
directly accessing their flatmapped representation. In order to provider
the test harness with the expected set hashes, the sets must be
generated by the schema.Resource itself.
During the test we now build a fixed map of the providers, which should
only contain schema.Provider instances, and pass them into each
TestStep. The individual schema.Resource instances can then be pulled
from the providers, and used to recreate the state from the cty.Value
returned by the core operations.
> Resource test shims

- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
SetId needs to overwrite the newState as well, since the internal calls
to DataSource.Id() will override the set attribute.
> make sure id really gets set in SetId

- backend/remote-state/s3/backend.go
- backend/remote-state/s3/backend_state.go
- backend/remote-state/s3/client.go
- website/docs/backends/types/s3.html.md
References:
* https://github.com/terraform-providers/terraform-provider-aws/issues/4709
* https://github.com/hashicorp/terraform/issues/16611#issuecomment-452749479
The AWS Go SDK automatically provides a default request retryer with exponential backoff that is invoked via setting `MaxRetries` or leaving it `nil` will default to 3. The terraform-aws-provider `config.Client()` sets `MaxRetries` to 0 unless explicitly configured above 0. Previously, we were not overriding this behavior by setting the configuration and therefore not invoking the default request retryer.
The default retryer already handles HTTP error codes above 500, including S3's InternalError response, so the extraneous handling can be removed. This will also start automatically retrying many additional cases, such as …
> backend/s3: Configure AWS Client MaxRetries and provide enhanced S3 NoSuchBucket error message

- plugin/discovery/get.go
- plugin/discovery/get_test.go
The changes add a UI error during provider discovery with the registry to suggest to users to update constraints with the closest provider version with compatible plugin protocol.
Output of `init` on TF config with provider `null` version constraint `1.0.0` and plugin protocol `5`
```
provider "null" {
version = "1.0.0"
}
```
Output of `init` on TF config with provider `null` version constraint `3.0.0-pre` and plugin protocol `5`
```
provider "null" {
version = "3.0.0-pre"
}
```
Local registry test setup with provider null with versions and varying protocol ranges
```
{
"id": "terraform-providers/null",
"verified": true,
"versions": [
...
{
"version": "1.0.0",
"protocols": ["4"],
"platforms": [{"os": "darwin", "arch": "amd64"}]
},
{
"version": "2.0.0-alpha",
"protocols": ["4", "5.0"], …
```
> Add provider protocol compatibility UI err msg during registry discovery

- plugin/discovery/get.go
- plugin/discovery/get_test.go
- plugin/discovery/version.go
Previous PR https://github.com/hashicorp/terraform/pull/19976 added UI msg to suggest version for users to update their config, but also suggested pre-releases if it is the only one available.
Terraform should not suggest pre-releases, and if needed users can select a pre-release with the provider version constraint to the pre-release.
> Prerelease versions are filtered for plugin protocol mismatches

- command/jsonconfig/config.go
- command/jsonplan/plan.go
- command/jsonplan/values.go
- command/jsonstate/state.go
- command/show_test.go
- command/test-fixtures/show-json/basic-create/main.tf
- command/test-fixtures/show-json/basic-create/output.json
- command/test-fixtures/show-json/basic-delete/main.tf
- command/test-fixtures/show-json/basic-delete/output.json
- command/test-fixtures/show-json/basic-delete/terraform.tfstate
- command/test-fixtures/show-json/basic-update/main.tf
- command/test-fixtures/show-json/basic-update/output.json
- command/test-fixtures/show-json/basic-update/terraform.tfstate
* added a test framework for json output and a few starting tests (the directory layout might change with time, I've already thought about adding a folder for `delete` plans)
* added sorting to resource slices to simplify tests - as a bonus this matches behavior elsewhere in terraform
(will squash)
> command/show: test -json output

- builtin/providers/test/provider.go
- builtin/providers/test/resource_deprecated.go
- builtin/providers/test/resource_deprecated_test.go
- config/hcl2shim/values.go
- config/hcl2shim/values_test.go
- helper/plugin/grpc_provider.go
- helper/resource/state_shim.go
Later changes have removed the need to add empty blocks to the config. Remove the empty blocks so we don't need to filter them out when helper/schema isn't expecting them.
Make sure ReadResource shims the state in the same manner as ApplyResourceChange.
#19955
> Don't add empty blocks to config, and fix ReadResource

- command/format/diff.go
- command/format/diff_test.go
Example plan below gets reduced this way by 4 fields/lines.  🎉 🚿
> command/format: Ignore removal of empty strings

- command/init.go
- plugin/discovery/error.go
- plugin/discovery/get.go
UI error msg to suggest compatible plugin version (https://github.com/hashicorp/terraform/pull/19976) ends up as a big wall of red text. It displays the suggested version along with more information describing why there may not be any compatible versions among what is available from the registry.
~This PR adds color distinction to break up the red block. `ProviderInstaller` can be passed the context of `colorstring.Colorize` at instantiation or falls back to the default colorizer. This may seem a little hacky but it allows `ProviderInstaller` to display to the UI high context msgs without needing to return a bunch of values to the caller to then be logged with the error~
This PR combines the redundant msg into one dynamic message and shifts the responsibility of printing the output to the …
> Condense protocol mismatch error message

- builtin/providers/test/resource_nested.go
- builtin/providers/test/resource_nested_test.go
- helper/plugin/grpc_provider.go
Since ResourceData and schemaMap themselves don't always agree on what the state should look like, run the final applied state through a round trip in the shims to try and get a stable value. The output from `ApplyResourceChange` may not have been invalid, but it needs to agree with what the next `PlanResourceChange` produces. 
Fixes #19754 (that test will still fail due to an import error, but that will be addressed in a later PR)
> Fix shims with deeper nested containers

- plugin/discovery/get.go
During provider discovery, the provider is logged twice
1. https://github.com/hashicorp/terraform/blob/30eead2df5028805c980bbd0134a3fa28cc0262c/plugin/discovery/get.go#L193
2. https://github.com/hashicorp/terraform/blob/30eead2df5028805c980bbd0134a3fa28cc0262c/plugin/discovery/get.go#L209
Removes the first print since the second one includes more information (the expanded namespace/name)
> Remove duplicate discovery logging

- states/statemgr/locker.go
I assume the intention here was to escape "early" and prevent any potential leakage of HTML-unsafe characters to TFE (or any other UI of that type), but I believe that TFE should just not rely on Terraform, especially when it has the right context to know _when_ to escape.
> states/statemgr: Avoid HTML escaping when printing LockInfo

- command/import_test.go
- command/init.go
- plugin/discovery/requirements.go
- plugin/serve.go
- tools/terraform-bundle/package.go
Provider installer has been relying on the server protocol to resolve plugin protocol compatibility during discovery, which was protocol 4. This PR updates the installer to filter on protocol `5` instead
* Separates TF client protocol from referencing server protocol
* Bumps TF client protocol to 5
* Keeps default server protocol to 4
* Bumps `terraform-bundle` protocol to 5 for plugin discovery
**Note**: to target bundling an older terraform version, use the `terraform-bundle` of the same release or tag
> Bump protocol version to 5

- command/fmt.go
- command/fmt_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/spec.md
- vendor/github.com/hashicorp/hcl2/hcl/json/spec.md
- vendor/github.com/hashicorp/hcl2/hcl/spec.md
- vendor/github.com/hashicorp/hcl2/hclwrite/format.go
- vendor/modules.txt
This PR is a selection of fixes to `terraform fmt`:
* HCL formatter was adding additional space between interpolation sequences. (Fixes #19744)
* `terraform fmt` would try to format files that were not valid HCL syntax, which would usually result in it making a big mess of them by assuming valid quote/brace nesting, etc. This was not covered by a separate issue but I've encountered it several times while investigating others.
* We removed support for single-file formatting in the HCL2-based rewrite of this command, but that breaks various tools that expect to be able to format individual files. (Fixes #19852)
By upgrading HCL this also includes an unrelated fix to the handling of splat expressions on nulls. For good measure, I also "upgraded" cty to the latest master even though there …
> command: "terraform fmt" fixes

- builtin/providers/test/provider.go
- builtin/providers/test/resource_defaults.go
- builtin/providers/test/resource_defaults_test.go
- builtin/providers/test/resource_nested_set_test.go
- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
Some provisional fixes for the shims, and some added tests.
This change isn't complete, and the failing tests are disabled, but this unblocks some acceptance testing.
> Some fixes for the provider shims

- command/get.go
- command/get_test.go
We missed this on the initial update pass because this was calling directly into the module package API rather than going through the `Meta` methods that we updated for the new config loader.
`m.installModules` here is the same method that `terraform init` is using for this purpose, ensuring the two will behave the same way. This changes the output a little compared to the old installer, but it still includes
the important information about where each module is coming from.
This fixes #20024.
> command: Update "terraform get" to use the new module installer

- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/test-fixtures/apply-issue19908/issue19908.tf
In an ideal world, providers are supposed to respond to errors during apply by returning a partial new state alongside the error diagnostics. In practice though, our SDK leaves the new value set to nil for certain errors, which was causing Terraform to "forget" the object altogether by assuming that the provider intended to say "null".
We now adjust that assumption to apply only in the delete case. In all other cases (including updates) we retain the prior state if the new state is given as nil. Although we could potentially fix this in the SDK itself, I expect this is a likely bug in other future SDKs for other languages too, so this new assumption is a safer one to make to be resilient to data loss when providers don't behave perfectly.
Providers that return both nil new value and no …
> core: Retain prior state if update fails with no new state

- backend/unparsed_value.go
In Terraform 0.11 and earlier we just silently ignored undeclared variables in `-var-file` and the 
automatically-loaded `.tfvars` files. This was a bad user experience for anyone who made a typo in a variable name and got no feedback about it, so we made this an error for 0.12.
However, several users are now relying on the silent-ignore behavior for automation scenarios where they pass the same `.tfvars` file to all configurations in their organization and expect Terraform to ignore any settings that are not relevant to a specific configuration. We never intentionally supported that, but we don't want to immediately break that workflow during 0.12 upgrade.
As a compromise, then, we'll make this a warning for v0.12.0 that contains a deprecation notice suggesting to move to using …
> backend: Undeclared variables in -var-file is a warning, not an error

- config/hcl2shim/values_equiv.go
- config/hcl2shim/values_equiv_test.go
- helper/plugin/grpc_provider.go
Due to various inprecisions in the old SDK implementation, applying the generated diff can potentially make changes to the data structure that have no real effect, such as replacing an empty list with a null list or vice-versa.
Although we can't totally eliminate such diff noise, here we attempt to avoid it in situations where there are _only_ meaningless changes -- where the prior state and planned state are equivalent -- by just echoing back the prior state verbatim to ensure that Terraform will treat it as a no-op change.
If there _are_ some legitimate changes then the result may still contain meaningless changes alongside it, but that is just a cosmetic problem for the diff renderer, because the meaningless changes will be ignored altogether during a subsequent apply anyway. The …
> helper/plugin: Discard meaningless differences from provider planning

- config/hcl2shim/values_equiv.go
- config/hcl2shim/values_equiv_test.go
The SDK uses only the native `int` and `float64` types internally for values that are specified as being "number" in schema, so for SDK purposes only a `float64` level of precision is significant.
To avoid any weirdness introduced as we shim and un-shim numbers, we'll reduce floating point numbers to `float64` precision before comparing them to try to mimic the result the SDK itself would've gotten from comparing its own `float64` versions of these values using the Go `==` operator.
> config/hcl2shim: ValuesSDKEquivalent float64 comparison of numbers

- command/format/diff_test.go
This is a test case which would fail in `0.11` where we just simply rendered all sensitive fields as changed when any other field in the resource was being changed.
https://github.com/hashicorp/terraform/blob/ac4fff416318bf0915a0ab80e062a99ef3724334/command/format/plan.go#L316-L318
The behaviour seems to have been fixed at some point during the 0.12 overhaul I guess, so this will just ensure we won't reintroduce the same bug ever again.
> command/format: Add test to cover update of sensitive field

- tools/terraform-bundle/README.md
- tools/terraform-bundle/config.go
- tools/terraform-bundle/main.go
- tools/terraform-bundle/package.go
Since terraform-bundle is just a different frontend to Terraform's module installer, it is subject to the same installation constraints as Terraform itself.
Terraform 0.12 cannot install providers targeting Terraform 0.11 and earlier, and so therefore terraform-bundle built with Terraform 0.12 cannot either. A build of terraform-bundle from the v0.11 line must be used instead.
Without this change, the latest revisions of terraform-bundle would install plugins for Terraform 0.12 to bundle along with Terraform 0.10 or 0.11, which will not work at runtime due to the plugin protocol mismatch.
If asked to create a bundle for a version of Terraform v0.12 or greater, an error will now be returned instructing the user to use a build from the v0.11 branch or one of the v0.11.x tags in order to …
> tools/terraform-bundle: refuse to bundle versions <0.12.0

- backend/remote/backend.go
- svchost/disco/host.go
Previously we would show two errors when there was a version constraint
error. But of course one is enough.
> backend/remote: make sure we show the correct error

- helper/schema/core_schema.go
- helper/schema/core_schema_test.go
Historically `helper/schema` did not support non-primitive map attributes because they cannot be represented unambiguously in `flatmap`. When we initially implemented `CoreConfigSchema` here we mapped that situation to a nested block of mode `NestingMap`, even though that'd never worked until
now, assuming that it'd be harmless because providers wouldn't be using it.
It turns out that some providers are, in fact, incorrectly populating a `TypeMap` schema with `Elem: &schema.Resource{...}`, apparently under the false assumption that it would constrain the keys allowed in the map. In practice, `helper/schema` has just been ignoring this and treating such attributes as map of string. (#20076)
In order to preserve the behavior of these existing incorrectly-specified attribute definitions, …
> helper/schema: TypeMap of Resource is actually of TypeString

- helper/plugin/grpc_provider.go
- helper/schema/provider.go
Quick PR to plumb `terraform_version` from the protobuf on to the actual provider values prior to configure being called.
> Copy TF version to helper/schema provider

- command/jsonconfig/config.go
- command/jsonstate/state.go
- command/show.go
- command/show_test.go
* support `terraform show -json $STATEFILE`
* don't display empty `expression`s (specifically `count` and `for_each`).
> command/show: improvements to json output

- command/init_test.go
Somehow I keep running into this failure and I think the message is not making it immediately obvious where to look for the offending `terraform.tfstate`, so I think printing full path might help.
> command/test: Clarify failure (add full path)

- builtin/providers/test/provider.go
- builtin/providers/test/resource_import_other.go
- builtin/providers/test/resource_import_other_test.go
- helper/plugin/grpc_provider.go
- helper/resource/testing_import_state.go
One quirky aspect of our import feature is that we allow the importer to produce additional resources alongside the one that was imported, such as to create separate rules for each rule of an imported security group.
Providers need to be able to set the types of these other resources since they may not match the "main" resource type. They do this by calling `ResourceData.SetType`, which in turn sets `InstanceState.Ephemeral.Type`.
In our shims here we therefore need to copy that out into our new `TypeName` field so that the new core import code can see it and create the right type in the state.
Testing this required a minor change to the test harness to allow the `ImportStateCheck` function to see the resource type.
This fixes #20124 and #20125, but it will probably turn most of them into …
> helper/plugin: Honor resource type overrides in import

- command/format/state.go
- command/format/state_test.go
- command/state_show_test.go
fixes #19752
Here is a sample of the new output using the example state from #19752: https://gist.github.com/mildwonkey/e22885d1920d770ecf056b87c0369622
> command/format: include nested blocks in `terraform show` output

- builtin/providers/test/resource_list_test.go
- builtin/providers/test/resource_nested_set_test.go
- helper/plugin/grpc_provider.go
- terraform/diff.go
Values removed from a list are only sometimes present in the diff and marked as `NewRemoved`. When Applying the diff, any change to the list length needs to be taken into account to remove extra elements. 
We also need to remove all `RequiresNew` flags during apply. Terraform is now performing completely separate operations for replace/destroy/create, the diff doesn't need to track this, and if any value as `RequiresNew` set it will cause the resource to drop the pre-existing state.
Fixes #20141
(Should also help with issues like #19760, but those have a couple other blockers which need verifying as well)
> Improve list block handling in diff application

- helper/schema/provider_test.go
- helper/schema/resource_timeout.go
- helper/schema/resource_timeout_test.go
The new decoder is more precise, and unpacks the timeout block into a
single map, which ResourceTimeout.ConfigDecode was updated to handle.
We however still need to work with legacy versions of terraform, with
the old decoder.
Fixes #20156
> decode legacy timeouts

- go.mod
- go.sum
- vendor/modules.txt
Second attempt of https://github.com/hashicorp/terraform/pull/20144 as the previous one missed `go mod vendor`, or more precisely first part of it (just one dependency).
For the sake of transparency this is a result of:
```sh
go get github.com/hashicorp/terraform-config-inspect@latest
go mod tidy
go mod vendor
```
in the following environment:
```sh
docker run --rm -ti -e GO111MODULE=on \
-v "$PWD":/go/src/github.com/hashicorp/terraform \
-w /go/src/github.com/hashicorp/terraform \
golang:1.11.5 bash
```
It may look odd that bumping `terraform-config-inspect` to latest revision doesn't have any `vendor` changes. This is because there we in fact no changes except in `go.mod` as a result of `go mod tidy` here https://github.com/hashicorp/terraform-config-inspect/pull/13
> vendor: github.com/hashicorp/terraform-config-inspect@latest

- helper/resource/testing.go
- helper/resource/testing_test.go
This checking helper is frequently used in provider tests for data sources, as a shorthand to verify that an attribute of the data source matches with the corresponding attribute on a managed resource.
Since we now leave empty collections null in more cases, this function is sometimes effectively asked to verify that a given attribute is _unset_ in both the data source and the resource, so here we slightly adjust the definition of the check to consider two nulls to be equal to one another, which at this layer manifests as the keys not being present in the state attributes map at all.
This check function didn't previously have tests, so this commit also adds a basic suite of tests, including coverage for the new behavior.
This fixes #20194.
> helper/resource: TestCheckResourceAttrPair allow nonexist

- command/jsonconfig/config.go
- command/jsonplan/plan.go
- command/jsonstate/state.go
@vancluever - here's the current WIP if you want to test from this branch.
> command/show: continued work on `terraform show -json` output

- builtin/providers/test/resource_import_other.go
- builtin/providers/test/resource_import_other_test.go
- go.mod
- go.sum
- helper/plugin/grpc_provider.go
- plugin/grpc_provider.go
- vendor/github.com/zclconf/go-cty/cty/type_conform.go
- vendor/modules.txt
Previously we were using the type name requested in the import to select the schema, but a provider is free to return additional objects of other types as part of an import result, and so it's important that we perform schema selection separately for each returned object.
If we don't do this, we get confusing downstream errors where the resulting object decodes to the wrong type and breaks various invariants expected by Terraform Core.
The `testResourceImportOther` test in the test provider didn't catch this previously because it happened to have an identical schema to the other resource type being imported. Now the schema is changed and also there's a computed attribute we can set as part of the refresh phase to make sure we're completing the `Read` call properly during import. Refresh …
> plugin: Use correct schema when marshaling/unmarshaling imported resource objects

- scripts/gogetcookie.sh
Just as with 336b352d6fe4, this refreshes our rate limit bypass cookie for `go.googlesource.com` since the old one has apparently expired.
I did this by visiting https://go.googlesource.com/ and selecting "Generate Password" from the top navigation. This cookie belongs to a test account used by the Terraform team and should not be used by
non-Terraform codebases; please generate your own!
> build: Periodic refresh of our go.googlesource.com cookie

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
Previously we were just asserting that the number of elements didn't grow between planned and actual. We still can't precisely correlate elements in sets with unknown values, but here we adapt some logic we added earlier to `config/hcl2shim` to ensure that we can find a plausible correlation for each element in each set to at least one element in the other set, and thus catch more cases where set elements might vanish or appear between plan and apply, for improved safety.
This will still generate false negatives in some cases where unknown values are present due to having to assume correlation is intended wherever it is possible, but we'll catch situations where the actual value
is obviously contrary to what was planned.
As long as #20187 remains unresolved, this will serve to produce a …
> plans/objchange: Improve precision of AssertObjectCompatible with sets

- builtin/providers/test/provider.go
- builtin/providers/test/resource_computed_set.go
- builtin/providers/test/resource_computed_set_test.go
- builtin/providers/test/resource_list_set.go
- builtin/providers/test/resource_list_set_test.go
- builtin/providers/test/resource_nested_set_test.go
- helper/plugin/grpc_provider.go
- helper/schema/schema.go
- helper/schema/set.go
This is a few fixes all related to sets in the new shimmed providers. It also adds a feature flag to the helper/schema package to conditionally run code that is required for the new protocol. 
- don't normalizeNullValues in ReadResource
The required normalization now happens in PlanResourceChange, and this
function is no longer appropriate for ReadResource.
- DiffSuppressFunc should noop diffs in sets
Sets rely on diffs being complete for all elements, even when they are
unchanged. When encountering a DiffSuppressFunc inside a set the diffs
were being dropped entirely, possible causing set elements to be lost.
-  don't allow computed set elems to be equal
If set elements are computed, we can't be certain that they are actually
equal. Catch identical computed set hashes when they are added …
> SDK set fixes

- builtin/providers/test/provider.go
- builtin/providers/test/resource_nested_id.go
- builtin/providers/test/resource_nested_id_test.go
- terraform/diff.go
Nested structures may have "id" fields, which should be treated
normally.
Fixes #20181
> only force top-level id's back to unknown

- website/docs/providers/terraform/d/remote_state.html.md
In 0.12, the outputs for a data source of terraform_remote_state are nested under the 'outputs' attribute [1]. This updates the docs to make this change clearer.
Worked with @radeksimko at Terraform hackday, who has submitted a related upgrade guide [2]
[1] https://github.com/hashicorp/terraform/blob/1f4d2f4c5008cbf4e2da61b65f1cb98183bc4884/builtin/providers/terraform/data_source_state.go#L16-L43
[2] https://github.com/hashicorp/terraform/pull/20243/commits/d8e00191b7d8e9cd2dfad7c07e21aa0b86c887d4
> Update docs for 0.12 terraform_remote_state data source

- scripts/build.sh
This commit fixes a problem where `make bin` would strip of any prerelease info.
> build.sh: only set git commit info for dev builds

- Makefile
- plugin/mock_proto/generate.go
- plugin/mock_proto/generate.sh
It seems that all of the tools we run here are now sufficiently modules-aware to run without problems in modules mode, and indeed running _not_ in modules mode was causing problems with locating packages in `mockgen`.
> build: Run "go generate" in modules mode

- helper/plugin/grpc_provider.go
- internal/tfplugin5/tfplugin5.pb.go
- internal/tfplugin5/tfplugin5.proto
- plugin/grpc_provider.go
- providers/provider.go
- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/terraform_test.go
- terraform/test-fixtures/apply-inconsistent-with-plan/main.tf
Previously we would allow providers to change anything about the planned object value during apply, possibly returning an entirely-unrelated object of the same type. In practice this led to some subtle bugs where a single planned attribute value would change during apply and cause a downstream failure due to a dependent resource now seeing input other than what _it_ expected during plan.
Now we'll produce an explicit error message for this case which places the blame with the correct party: the upstream resource that changed. Without this, unexpected changes would often lead to the downstream resource implementation being blamed in error message even though it was just
reacting to the change from upstream.
As with most errors during apply, we'll still save the updated value in the state …
> core: Verify that objects don't change unexpectedly during apply

- config/module/storage.go
- configs/configload/module_manifest.go
Previously we used the default OS separator, but this caused issues when you are working on Windows and are trying to use remote operations with TFE.
> core: always use slashes in modules.json

- backend/remote/backend.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan_test.go
- backend/remote/backend_state_test.go
- backend/remote/backend_test.go
- backend/remote/testing.go
- svchost/disco/host.go
Do not special case the `dev` prerelease and cleanup test connection to prevent file descriptor issues when running the tests on a Mac.
> backend/remote: cleanup test connections

- backend/local/backend_apply_test.go
- backend/local/testing.go
- builtin/providers/test/resource_list_test.go
- builtin/providers/test/resource_nested_set_test.go
- command/show_test.go
- command/test-fixtures/show-json/basic-delete/output.json
- command/test-fixtures/show-json/basic-delete/terraform.tfstate
- command/test-fixtures/show-json/basic-update/output.json
- command/test-fixtures/show-json/basic-update/terraform.tfstate
- configs/configschema/coerce_value.go
- configs/configschema/coerce_value_test.go
- helper/plugin/grpc_provider.go
- helper/plugin/unknown.go
- helper/plugin/unknown_test.go
- lang/funcs/string.go
- plans/objchange/all_null.go
- plans/objchange/objchange.go
- plans/objchange/objchange_test.go
- terraform/context_plan_test.go
- terraform/eval_read_data.go
Previously we would construct a proposed new state with unknown values in place of any not-set-in-config computed attributes, trying to save the provider a little work in specifying that itself.
Unfortunately that turns out to be problematic because it conflates two concerns: attributes can be explicitly set in configuration to an unknown value, in which case the final result of that unknown overrides any default value the provider might normally populate.
In other words, this allows the provider to recognize in the proposed new state the difference between an Optional+Computed attribute being set to unknown in the config vs not being set in the config at all.
The provider now has the responsibility to replace these proposed null values with unknown values during PlanResourceChange if it …
> plans/objchange: Don't presume unknown for values unset in config

- configs/configupgrade/test-fixtures/valid/heredoc/input/heredoc.tf
- configs/configupgrade/test-fixtures/valid/heredoc/want/heredoc.tf
- configs/configupgrade/test-fixtures/valid/heredoc/want/versions.tf
- configs/configupgrade/upgrade_expr.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl/.travis.yml
- vendor/github.com/hashicorp/hcl/decoder.go
- vendor/github.com/hashicorp/hcl/go.mod
- vendor/github.com/hashicorp/hcl/go.sum
- vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
- vendor/github.com/hashicorp/hcl/hcl/printer/nodes.go
- vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go
- vendor/github.com/hashicorp/hcl/json/scanner/scanner.go
- vendor/modules.txt
Previously, configupgrade would panic if it encountered a HEREDOC. For
the time being, we will simply print out the HEREDOC as-is.
Unfortunately, we discovered that terraform 0.11's version of HCL
allowed for HEREDOCs with the termination delimiter inline (instead of
on a newline, which is technically correct). Since 0.12configupgrade
needs to be bug-compatible with terraform 0.11, we must roll back to the
same version of HCL used in terraform 0.11.
> configs/configupgrade: do not panic on HEREDOCs.

- builtin/providers/test/resource.go
- builtin/providers/test/resource_test.go
- helper/plugin/grpc_provider.go
Terraform core expects a sane state even when the provider returns an
error. Make sure at the prior state is always the default value to
return, and then alway attempt to process any state returned by
provider.Apply.
This should fix the bulk of the `Provider produced inconsistent result after apply` issues when there is a resource error.
> process state even after provider.Apply errors

- helper/resource/testing.go
- helper/resource/testing_test.go
This was changed in the single attribute test cases, but the AttrPair
test is used a lot for data source. As far as tests are concerned, 0 and
unset should be treated equally for flatmapped collections.
> allow 0 and unset to be equal in count tests

- builtin/providers/test/resource_test.go
- terraform/diff.go
The helper/schema handling of lists loses empty string values, but
retains the correct count. Only re-count the values if the count is
missing entirely, and allow our shims to re-populate the zero values.
> allow implicit empty strings in lists

- CODEOWNERS
First pass at adding CODEOWNERS to link remote-state backends with maintainers of the associated providers.
> First pass at adding CODEOWNERS for remote-state backends.

- go.mod
- go.sum
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/github.com/blang/semver/package.json
- vendor/github.com/hashicorp/logutils/go.mod
- vendor/github.com/mitchellh/copystructure/go.mod
- vendor/github.com/mitchellh/copystructure/go.sum
- vendor/github.com/mitchellh/hashstructure/README.md
- vendor/github.com/mitchellh/hashstructure/go.mod
- vendor/github.com/mitchellh/hashstructure/hashstructure.go
- vendor/github.com/mitchellh/reflectwalk/go.mod
- vendor/modules.txt
Related: https://github.com/hashicorp/terraform/pull/20287
AWS provider has already bumped these dependencies, and I'd like to avoid bringing all these updates through https://github.com/hashicorp/terraform/pull/20287 so I'm raising this separate, isolated PR.
> vendor: Bump more dependencies to go-mod-aware versions

- website/docs/backends/types/remote.html.md
This is only relevant to the last few 0.11 releases; we're considering it
a final release as of 0.12.
Ran this wording past @rkst before PRing.
> website: Change remote backend 'preview' callout to 'beta'

- command/jsonconfig/config.go
- command/show_test.go
- command/test-fixtures/show-json/basic-create/output.json
- command/test-fixtures/show-json/basic-delete/output.json
- command/test-fixtures/show-json/basic-update/output.json
The tests have been updated to reflect this.
Example output (truncated):
```json
"configuration": {
"root_module": {
"outputs": { },
"resources": [ ],
"variables": {
"test_var": {
"default": "bar"
}
}
}
}
```
> command/jsonconfig: display module variables in config output

- builtin/providers/test/resource_list.go
- builtin/providers/test/resource_list_test.go
- terraform/eval_diff.go
RequiresReplace paths with IndexSteps that have been added or removed will fail to apply against one or the other state values. We were previously ignoring the error from apply the path to the `priorVal`, but this can happen in either direction.
Only fail if both values produce an error. In the case of a single error, make sure the other value is a valid Null of the correct type.
Fixes #20294
> Requires replace should not error on missing index steps

- website/upgrade-guides/0-12.html.markdown
As we discovered during Terraform hackday w/ @surminus there are changes in how terraform remote state is referenced.
> docs/upgrade-guide: Document changes in remote state referencing

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-tfe/configuration_version.go
- vendor/github.com/hashicorp/go-tfe/team.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/modules.txt
Similar to https://github.com/hashicorp/terraform/pull/20310 and https://github.com/terraform-providers/terraform-provider-tfe/pull/59 this PR aligns versions of `go-tfe` in TFE provider and Terraform's `master` to make future upgrade path smoother.
> vendor: github.com/hashicorp/go-tfe@v0.3.8

- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
`cty.Value.AsValueMap` can return `nil` if called on an empty map or object. The logic above was dealing with that case for maps, but object types were falling through into this codepath and panicking when trying to assign a new key into the `nil` `dstMap`.
This also includes a bonus fix where we were calling `ty.ElementType` in a switch case that accepts object types. Object types don't have a single element type, so we can't call `ElementType` on those (that also panics) but we _can_ use the type of the value we selected from `src` to construct our placeholder null value.
> helper/plugin: fix panic with empty objects in normalizeNullValues

- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/structure.go
- vendor/modules.txt
This includes a fix to properly report the position of an errant block inside a body processed as `JustAttributes`, which fixes #20248.
> vendor: go get github.com/hashicorp/hcl2@master

- helper/validation/validation.go
- helper/validation/validation_test.go
My apologies, I was really trying to avoid this one. I am okay with it being rejected. 😅 
These two commits were merged into master right after the 0.12 cutover, with the hope that we could shortly thereafter update the provider SDK to have access to these for cleaning up the sprawling AWS provider custom validation functions. Since concurrent 0.11 SDK acceptance testing after updating to 0.12 SDK is a current goal which would further delay access to these, it would be wonderful to backport these now to avoid compilation issues and so we can open issues in the provider repository to help start the validation function cleanup process sooner rather than (potentially much) later.
> helper/validation: Backport All(), Any(), and IntInSlice() functions

- helper/schema/resource_data.go
This functionality is no longer supported in Terraform 0.12 and above.
> helper/schema: Add deprecation to ResourceData.UnsafeSetFieldRaw

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
Our usual "ground rules" for mapping `configschema` to `cty` call for the collection values representing nested block types to always be known and non-null, using an empty collection to represent the absence of any blocks of that type so that users can always safely use `length(...)` etc on them without worrying about them sometimes being null.
However, due to some different behaviors in the legacy SDK we've allowed it an exception to this rule which means that we can see unknown and null collections in these positions in object values returned from provider operations like `PlanResourceChange` and `ApplyResourceChange` when the legacy
SDK opt-out is activated.
As a consequence of this, we need to be mindful in our safety check functions, like `AssertObjectCompatible` here, of tolerating …
> plans/objchange: Fix panic in AssertObjectCompatible with set blocks

- builtin/providers/test/resource.go
- builtin/providers/test/resource_list.go
- builtin/providers/test/resource_list_test.go
- terraform/diff.go
Like was done for list blocks, simple lists of strings may be missing
empty string elements, and any list may be implicitly truncated.
> simple list diffs may also have missing elements

- builtin/provisioners/salt-masterless/resource_provisioner.go
Uses the defined constants for remote pillar and state tree locations as variable defaults. Then compares the retrieved variable values against those defaults.
Fixes #17150
> Ensure state and pillar remote locations are always defined

- command/jsonconfig/config.go
- command/jsonplan/values.go
- command/show_test.go
- command/test-fixtures/show-json/modules/foo/main.tf
- command/test-fixtures/show-json/modules/main.tf
- command/test-fixtures/show-json/modules/modules.json
- command/test-fixtures/show-json/modules/output.json
command/show: add "module_version" to "module_calls" in config portion  of `terraform show`.
Also extended the `terraform show -json` test to run `init` so we could
add examples with modules. This does _not_ test the "module_version"
yet, but it _did_ help expose a bug in `jsonplan` where modules were
duplicated. This is also fixed in this PR.
I'm open to renaming "module_version" (and any other feedback) - opening a PR seemed the most straightforward way to start that conversation.
> command/show: add "module_version" to "module_calls" in config 

- command/jsonplan/plan.go
- command/jsonplan/resource.go
- command/test-fixtures/show-json/basic-create/output.json
- command/test-fixtures/show-json/basic-delete/output.json
- command/test-fixtures/show-json/basic-update/output.json
🙄 No excuses, just user error on my part.
@vancluever you'll want to make note of this, I used the wrong type entirely for the "deposed" key in "resource_changes".
> command/jsonplan: "deposed" should be a string, not a bool.

- examples/README.md
- website/docs/providers/index.html.markdown
- website/docs/providers/type/major-index.html.markdown
The `google` provider supports GCP, not necessarily Google Cloud as a whole.
Update the naming on this index page to match [the provider README](https://github.com/terraform-providers/terraform-provider-google#terraform-provider-for-google-cloud-platform) and the [provider docs changes](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/index.html.markdown#google-cloud-platform-provider) coming in the next release.
> Fix Google Cloud Platform name across docs

- command/jsonconfig/config.go
- command/test-fixtures/show-json/modules/main.tf
- command/test-fixtures/show-json/modules/output.json
Display depends_on for resources and outputs, and description for
outputs.
I've added an example "depends_on" into a test as well. This also includes a bonus fix for a broken test I merged earlier today.
> command/jsonconfig: add missing fields from configuration output

- backend/remote-state/etcdv2/backend.go
- backend/remote/backend.go
- backend/remote/testing.go
The API surface area is much smaller when we use the remote backend for remote state only.
So in order to try and prevent any backwards incompatibilities when TF runs inside of TFE, we’ve split up the discovery services into `state.v2` (which can be used for remote state only configurations, so when running in TFE) and `tfe.v2.1` (which can be used for all remote configurations).
> backend/remote: use `state.v2` for remote state only

- tools/terraform-bundle/README.md
A hyphen is not successful, underscore is.
> Fix structure for provider names in terraform-bundle: an underscore is required before the version

- backend/local/backend.go
- terraform/context.go
- terraform/resource_provider.go
The init error was output deep in the backend by detecting a
special ResourceProviderError and formatted directly to the CLI.
Create some Diagnostics closer to where the problem is detected, and
passed that back through the normal diagnostic flow. While the output
isn't as nice yet, this restores the helpful error message and makes the
code easier to maintain. Better formatting can be handled later.
The new output would look like:
```
Error: Could not satisfy plugin requirements
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically …
```
> move provider init error to where it is generated
