hashicorp/terraform

- backend/remote-state/swift/backend.go
- backend/remote-state/swift/backend_state.go
- backend/remote-state/swift/backend_test.go
- backend/remote-state/swift/client.go
- backend/remote-state/swift/client_test.go
> Swift remote backend support for workspaces & locking

- go.mod
- go.sum
- vendor/github.com/antchfx/xpath/.travis.yml
- vendor/github.com/antchfx/xpath/README.md
- vendor/github.com/antchfx/xpath/build.go
- vendor/github.com/antchfx/xpath/func.go
- vendor/github.com/antchfx/xpath/func_go110.go
- vendor/github.com/antchfx/xpath/func_pre_go110.go
- vendor/github.com/antchfx/xpath/parse.go
- vendor/github.com/antchfx/xpath/query.go
- vendor/github.com/antchfx/xpath/xpath.go
- vendor/github.com/antchfx/xquery/xml/node.go
- vendor/github.com/dylanmei/winrmtest/go.mod
- vendor/github.com/dylanmei/winrmtest/go.sum
- vendor/github.com/satori/go.uuid/.travis.yml
- vendor/github.com/satori/go.uuid/LICENSE
- vendor/github.com/satori/go.uuid/README.md
- vendor/github.com/satori/go.uuid/codec.go
- vendor/github.com/satori/go.uuid/generator.go
- vendor/github.com/satori/go.uuid/sql.go
- vendor/github.com/satori/go.uuid/uuid.go
- vendor/modules.txt
This is a go mod aware version of `winrmtest`.
> vendor: github.com/dylanmei/winrmtest@99b7fe2fddf1

- website/docs/providers/type/community-index.html.markdown
Adding 2 new community providers to the Terraform docs
> [Website] Add two new community providers

- website/layouts/commands-providers.erb
> website: fix link

- go.mod
- go.sum
- vendor/golang.org/x/crypto/ssh/agent/server.go
- vendor/modules.txt
This is go modules aware version.
> vendor: go get golang.org/x/crypto@31a38585487a

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- command/format/diff.go
- command/format/diff_test.go
> command/plan: indicate if a resource is being replaced because it was tainted.

- command/import.go
- command/refresh.go
- website/docs/commands/apply.html.markdown
- website/docs/commands/import.html.md
- website/docs/commands/plan.html.markdown
- website/docs/commands/refresh.html.markdown
References:
* https://github.com/hashicorp/terraform/blob/b9d8e96e0c7c52487e45eaab1aa6dacc39997b47/command/command.go#L41
* https://github.com/hashicorp/terraform/blob/b9d8e96e0c7c52487e45eaab1aa6dacc39997b47/terraform/context.go#L149-L155
> command: Consistency implement and document parallelism default of 10

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Adding two lines in the provider documentation to the newly released, Ncloud provider for Terraform
> [Website] Add new provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Cherry-pick from https://github.com/hashicorp/terraform/pull/20605
> [Website] Cherry-pick 

- website/docs/configuration/functions/map.html.md
- website/docs/configuration/functions/toset.html.md
> Fixed typo in doc

- website/docs/configuration/locals.html.md
> Fix typo in locals.html

- website/docs/providers/type/community-index.html.markdown
Adding three new community providers
> [Website] New Community Providers

- builtin/providers/test/resource_test.go
- helper/plugin/grpc_provider.go
treat normalization during `ReadResource` like in `PlanResourceChange`.
This will allow resources to return an unexpected changes to set blocks
and attributes, otherwise we could mask these changes during
normalization.
Change the "plan" argument in normalizeNullValues to "preferDst" to more
accurately describe what the option is doing, since it no longer applies
only to `PlanResourceChange`.
This fixes some provider tests which are filing with:
`Expected a non-empty plan, but got an empty plan`, because the changes were being hidden by the normalization function.
> ReadResource normalization

- website/docs/configuration/functions/file.html.md
> Update file.html.md, "renders uses" => "renders using"

- website/intro/getting-started/destroy.html.md
// , Just noticed this while doing the Getting Started guide, figured I'd add a small improvement.
> Update the last output example

- website/docs/backends/types/s3.html.md
Added in
https://github.com/hashicorp/terraform/commit/fb6b349e580b1cbb9053c09f97f8424d63d0716f
Supersedes #20494 (couldn't add code suggestions).
Resolves #19672
> website: document s3 backend's force_path_style argument

- website/docs/configuration-0-11/interpolation.html.md
Supersedes #19049, also relevant to #20267, who knows, maybe I'll find more as I work back through the PRs. 😄
> website: resolve double-dollar confusion once and for all 😤

- website/docs/backends/types/s3.html.md
This was occasionally confusing readers, cf. https://github.com/hashicorp/terraform-website/issues/670
> website: Clarify that example S3 policy is for an IAM entity

- website/docs/commands/workspace/show.html.md
- website/layouts/commands-workspace.erb
> website: Add  command to sidebar nav

- website/docs/provisioners/null_resource.html.markdown
Fix typo in null_resource.html.markdown
> Fix typo in null_resource.html.markdown

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Adding JDcloud provider links to the terraform provider listings
> [Website] Add JDcloud provider

- configs/configupgrade/test-fixtures/valid/invalid-resource-name/want/resource.tf
> configupgrade: fix test

- backend/remote/backend_context.go
When using `terraform console` in combination with the remote backend, variables defined in Terraform Enterprise were load loaded correctly.
> backend/remote: correctly load remote variables

- main.go
- website/docs/commands/cli-config.html.markdown
- website/docs/commands/environment-variables.html.md
> Adding documentation for TF_CLI_CONFIG_FILE environment variable

- Dockerfile
- scripts/docker-release/Dockerfile-release
What all this really comes down to is smaller terraform containers.  Here are some containers that I built that are smaller than the official containers:
https://cloud.docker.com/u/aztek/repository/docker/aztek/terraform/tags
> Optimized build processes and image sizes by using build containers.

- command/graph.go
Fixes https://github.com/hashicorp/terraform/issues/16839
> Use user-supplied plugin path when running graph command

- website/upgrade-guides/0-12.html.markdown
> website: v0.12 upgrade guide about list variables and brackets

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Adding provider links for the newly certified Fortios provider
> [Website] Adding Fortios provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
> [Cherry-pick] website change from master

- CHANGELOG.md
Please, let's include the recent improvement to the Postgres backend.
> Update CHANGELOG for #20561

- website/docs/providers/type/community-index.html.markdown
Quick PR to add an additional community provider
> [Website] Adding community provider

- lang/functions.go
- website/docs/configuration/functions/reverse.html.md
- website/docs/configuration/functions/strrev.html.md
- website/layouts/functions.erb
Fixes #21075.
Replaces https://github.com/hashicorp/terraform/pull/21076.
> Add 'strrev' interpolation function

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Modifying FortiOS provider name
> [Website] Fix FortiOS typo

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
> [Website] Add Gridscale provider

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Cherry-picked from master branch
> [Cherry-pick] fix FortiOS caps

- website/guides/terraform-provider-development-program.html.md
Cherry-pick from master of https://github.com/hashicorp/terraform/pull/21126
> [Website]Cherry-pick from master

- configs/configupgrade/test-fixtures/valid/indexed-splat/input/indexed-splat.tf
- configs/configupgrade/test-fixtures/valid/indexed-splat/want/indexed-splat.tf
- configs/configupgrade/test-fixtures/valid/indexed-splat/want/versions.tf
- configs/configupgrade/upgrade_expr.go
- configs/configupgrade/upgrade_test.go
Depends on https://github.com/hashicorp/terraform/pull/21125
> configupgrade: Upgrade indexing of splat syntax

- website/docs/configuration/resources.html.md
Fixed typo: separtely/separately.
> Fixed Typo

- backend/remote/backend_state.go
When changes are made and we failed to upload the state, we should not
try to unlock the workspace. Leaving the workspace locked is a good
indication something went wrong and also prevents other changes from
being applied before the newest state is properly uploaded.
Additionally we now output the lock ID when a lock or force-unlock
action failed.
> backend/remote: do not unlock after a failed upload

- website/guides/terraform-provider-development-program.html.md
Remove unnecessary PR step and add licensing requirement set
> [Website] Terraform Provider Development Guide changes

- builtin/providers/terraform/data_source_state.go
- builtin/providers/terraform/data_source_state_test.go
- builtin/providers/terraform/provider.go
We were previously catching some errors at read time, but some type errors were panicking because the `cty.DynamicPseudoType` arguments have no automatic pre-type-checking done but this code was assuming they would be objects.
Here we add an explicit validation step that includes both the backend validation we were previously doing during read and some additional type checking to ensure the two dynamic arguments are suitably-typed. Having the separate validation step means that these problems can be detected by `terraform validate`, rather than only in `terraform plan` or `terraform apply`.
> providers/terraform: Explicit validate step

- website/docs/providers/index.html.markdown
- website/docs/providers/type/major-index.html.markdown
Adding links to provider documentation for the new release.
> [Website] Add VMware vRA7 provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/major-index.html.markdown
Cherry-pick from https://github.com/hashicorp/terraform/pull/21221
> [Cherry-pick] new provider

- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
Terraform core would previously ignore unexpected attributes found in
the state, but since we now need to encode/decode the state according
the schema, the attributes must match the schema.
On any state upgrade, remove attributes no longer present in the schema
from the state. The only change this requires from providers is that
going forward removal of attribute is considered a schema change, and
requires an increment of the SchemaVersion in order to trigger the
removal of the attributes from state.
> remove extra attributes from state during upgrade

- configs/configupgrade/analysis.go
```
Would you like to upgrade the module in the current directory?
Only 'yes' will be accepted to confirm.
Enter a value: yes
-----------------------------------------------------------------------------
Error: error resolving providers: [provider.packet: no suitable version installed
version requirements: "(any version)"
versions installed: none]
```
```
Would you like to upgrade the module in the current directory?
Only 'yes' will be accepted to confirm.
Enter a value: yes
-----------------------------------------------------------------------------
Error: error resolving providers:
- provider.packet: no suitable version installed
version requirements: "(any version)"
versions installed: none
```
> configupgrade: Improve error message formatting

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
Adding links to Rancher2 provider documentation
> [Website] Rancher2 provider doc links

- website/docs/configuration/terraform.html.md
Fixed typo: spceific/specific.
> docs: fixed typo

- go.mod
- go.sum
- vendor/github.com/golang/mock/gomock/controller.go
- vendor/github.com/golang/mock/gomock/matchers.go
- vendor/github.com/zclconf/go-cty/cty/function/stdlib/regexp.go
- vendor/modules.txt
This is go-mod-aware version of `golang/mock`.
> vendor: github.com/golang/mock@v1.3.1

- backend/remote-state/http/backend.go
- backend/remote-state/http/backend_test.go
- backend/remote-state/http/client.go
- backend/remote-state/http/client_test.go
- command/apply_test.go
- website/docs/backends/types/http.html.md
> backend/http: implement retries for the http backend

- website/docs/providers/type/community-index.html.markdown
This PR is a cherry pick from master branch PR --> https://github.com/hashicorp/terraform/pull/21578
> [Cherry-pick] new community links + update signalFX

- website/docs/configuration/types.html.md
There have been a few questions about this so far which indicated that the previous docs for this feature were very lacking. This is an attempt to describe more completely what `any` means, and in particular that it isn't actually a type at all but rather a placeholder for a type to be selected dynamically.
This closes #21384 by documenting the behavior I described in that issue.
> website: Further elaboration on the "any" type constraint

- website/docs/providers/type/community-index.html.markdown
Adding [AnsibleVault](https://github.com/MeilleursAgents/terraform-provider-ansiblevault) to the community provider listing.
> [Website] community provider

- website/docs/providers/type/community-index.html.markdown
Cherry-pick from master branch at https://github.com/hashicorp/terraform/pull/21637
> [cherry-pick] website changes

- go.mod
> udpate lost go.mod entry

- helper/plugin/grpc_provider.go
- helper/plugin/grpc_provider_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8828
Prior to Terraform 0.12, providers were not required to implement the `MigrateState` function when increasing the `SchemaVersion` above `0`. Effectively there is no flatmap state difference between version 0 and defined `SchemaVersion` or lowest `StateUpgrader` `Version` (whichever is lowest) when `MigrateState` is undefined, so here we remove the error and increase the schema version automatically.
> helper/plugin: Allow missing MigrateState for provider flatmap state upgrades

- states/statefile/testdata/roundtrip/v3-bigint.in.tfstate
- states/statefile/testdata/roundtrip/v3-bigint.out.tfstate
- states/statefile/version2.go
Fixes #21478
In #19688, `terraform.BackendState.Hash` was fixed.
We also need to fix `states/statefile.backendStateV2.Hash`
```
[terraform@fix-statev2-hash-decode|✔]$ go test -v ./states/statefile -run TestRoundtrip
=== RUN   TestRoundtrip
=== RUN   TestRoundtrip/v1-simple
2019/05/28 23:58:38 [TRACE] statefile.Read: upgrading format from v1 to v2
2019/05/28 23:58:38 [STATE UPGRADE] Detected the following collections in state: [triggers.]
2019/05/28 23:58:38 [STATE UPGRADE] Detected triggers as a map. Replaced count = 1
2019/05/28 23:58:38 [STATE UPGRADE] Detected the following collections in state: [triggers.]
2019/05/28 23:58:38 [STATE UPGRADE] Detected triggers as a map. Replaced count = 1
2019/05/28 23:58:38 [STATE UPGRADE] Detected the following collections in state: [triggers.] …
```
> states/statefile: decode backend hash as uint64

- website/docs/providers/type/community-index.html.markdown
Adding Foreman Terraform provider, build by Wayfair
> [Website] Foreman community provider

- website/docs/providers/type/community-index.html.markdown
Cherry-pick commit from https://github.com/hashicorp/terraform/pull/21692
> [Cherry-pick] Foreman community provider

- CHANGELOG.md
Fix broken markdown link in CHANGELOG.md
> Fix broken markdown link in CHANGELOG.md

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Adding two links for the Akamai provider documentation
> [Website] Akamai provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Cherry-pick from https://github.com/hashicorp/terraform/pull/21679
> [Cherry-pick] Akamai provider links

- website/docs/modules/composition.html.markdown
We previously had some notes about handling configuration variants just tacked on to the "dependency inversion" section as an afterthought, but this idea is a major use-case for dependency inversion so it deserves its own section and a specific example.
> website: Separate "Module Composition" section for variants

- website/docs/provisioners/puppet.html.markdown
First pass at some docs for the Puppet provisioner added in #18851
> Docs for the Puppet provisioner

- lang/funcs/collection.go
> Add missing bool case

- website/docs/backends/types/remote.html.md
Add instructions for backend cli input. 
PR created as part of the #21504
> Update remote.html.md with backend cli config in v0.12.0

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Cherry-pick from master branch https://github.com/hashicorp/terraform/pull/22003
> [Cherry-pick] SignalFX links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
> [Website] fix signalfx link name

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/csm/doc.go
- vendor/github.com/aws/aws-sdk-go/aws/csm/enable.go
- vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/request/request.go
- vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
- vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
- vendor/github.com/aws/aws-sdk-go/aws/session/session.go
- vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
- vendor/github.com/aws/aws-sdk-go/service/dynamodb/doc_custom.go
- vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go
- vendor/github.com/aws/aws-sdk-go/service/iam/api.go
- vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/modules.txt
dependency bump from github.com/aws/aws-sdk-go@v1.20.4 to github.com/aws/aws-sdk-go@v1.20.10
* new region endpoints
References:
https://github.com/aws/aws-sdk-go/releases/tag/v1.20.10
Updated via:
```
$ go get github.com/aws/aws-sdk-go@v1.20.10
$ go mod tidy
$ go mod vendor
```
> deps: github.com/aws/aws-sdk-go@v1.20.10

- website/docs/backends/types/azurerm.html.md
Using az login and then terraform init from the command line I got `Error: Either an Access Key / SAS Token or the Resource Group for the Storage Account must be specified`
> Updated docs for using az cli or service principle

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Adding new AVI Vantage provider documentation links
> [website] AVI Networks provider

- command/testing_eval.go
Martin has suggested this patch in
https://github.com/hashicorp/terraform/issues/21628. I have tested it
and it works.
> Add patch suggested by Martin

- builtin/providers/test/resource_map.go
- builtin/provisioners/chef/resource_provisioner_test.go
- builtin/provisioners/file/resource_provisioner_test.go
- config/interpolate_walk.go
- config/interpolate_walk_test.go
- config/raw_config.go
- config/raw_config_test.go
- helper/diff/resource_builder.go
- helper/diff/resource_builder_test.go
- helper/resource/testing_config.go
- helper/schema/field_reader_config_test.go
- helper/schema/resource_diff_test.go
- helper/schema/resource_timeout.go
- helper/schema/schema.go
- helper/schema/schema_test.go
- helper/schema/shims.go
- helper/schema/shims_test.go
- terraform/context_test.go
- terraform/diff.go
- terraform/eval_variable.go
- terraform/interpolate.go
- terraform/provider_mock.go
- terraform/resource_test.go
- terraform/state.go
- terraform/state_test.go
> Begin removing config package, starting with config.UnknownVariableValue

- website/docs/commands/init.html.markdown
> change from work to working directory

- command/init.go
- command/providers.go
- config/loader.go
- config/loader_test.go
- configs/parser_config_dir.go
- configs/parser_config_dir_test.go
- go.sum
> [SDK cleanup] Move IsEmptyDir to configs pkg

- config/config.go
- config/config_test.go
- config/providers.go
- terraform/util.go
> [SDK Cleanup] Prune ResourceProviderFullName and its callers

- command/meta.go
- command/meta_new.go
> [Cleanup] prune dead code from command/meta

- states/statefile/version3_upgrade.go
Some of our errors returned here were lacking context about what part of the file was problematic, which led to some useless error reporting for some real-world situations that this upgrade process doesn't seem to be catching.
Here we add additional context to those error cases, as a step towards tracking down exactly which upgrade cases are missing here so that we can potentially fix them in a subsequent release.
This is intended to gather some more information for #21435, so we can figure out which cases are still not being handled.
> states/statefile: additional context for some v3 upgrade error messages

- communicator/ssh/communicator.go
1) Mention the host and port in the "Connecting..." message.
2) Mention the username in the post-connection handshaking message.
3) If handshaking fails, mention the user, host, and port in the error
message that will eventually be returned to the user.
> Improve ssh connection debug messages

- plugin/discovery/get.go
> missing error check in discovery

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Add links for Cisco ACI provider
> [Website] Cisco ACI links

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/hcl2/ext/dynblock/README.md
- vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/spec.md
- vendor/github.com/hashicorp/hcl2/hcl/spec.md
- vendor/github.com/hashicorp/hcl2/hcl/structure.go
- vendor/github.com/hashicorp/hcl2/hclwrite/format.go
- vendor/modules.txt
Fixes #21434, thanks to work by @nozaq
> Upgrade HCL to include fmt fix

- website/upgrade-guides/0-12.html.markdown
> Docs about comparison behavior change from 0.11 to 0.12

- website/docs/configuration/functions/csvdecode.html.md
We added the `csvdecode` function originally with the intent of it being used with `for_each`, but because `csvdecode` was released first we had a section in its documentation warning about the downsides of using it with `count`, since that seemed like something people would be likely to try.
With resource `for_each` now merged, we can replace that scary section with a more positive example of using these two features together.
We still include a paragraph noting that `count` _could_ be used here, but with a caution against doing so. This is in the hope of helping readers understand the difference between these two patterns and why `for_each` is the superior choice for many situations.
> website: example of csvdecode with for_each

- terraform/eval_apply.go
> Ensure each references evaluated in provisioners block

- command/012_config_upgrade.go
bug fix for this(https://github.com/hashicorp/terraform/issues/21594) issue
from what seen, plan and apply command is not tested about this problem, i dont know how can i write test about this
> bug fix 0.12upgrade plugin-dir (#21594)

- website/docs/configuration-0-11/variables.html.md
the other variables have a type, i think this one might be missing
> added type to variable

- builtin/provisioners/habitat/resource_provisioner.go
- builtin/provisioners/habitat/resource_provisioner_test.go
- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
Reverts hashicorp/terraform#21345
Reverting in favor of reviewing #21776
> Revert "Habitat License Acceptance changes. "

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
This is a cherrypick from the master branch at https://github.com/hashicorp/terraform/pull/22417
> [Cherry-pick] Add Exoscale provider links

- website/docs/commands/import.html.md
- website/docs/commands/state/mv.html.md
- website/docs/commands/state/rm.html.md
- website/docs/commands/state/show.html.md
- website/docs/internals/resource-addressing.html.markdown
This documentation update increases the verbosity slightly in the examples to explain them, so please reach out with any changes!
> docs: Additional for_each commands and resource addressing documentation

- website/docs/provisioners/connection.html.markdown
> Missing punctuation mark

- website/docs/backends/types/remote.html.md
I tested that all state commands work with remote backend using Terraform 0.11.13.
> Add state commands

- lang/blocktoattr/variables.go
Fixes issue where attribute in nested is not of list type/is invalid and would panic
Fixes #21733
> Fix panic on double dynamic blocks

- lang/funcs/collection.go
- lang/funcs/string.go
- website/docs/commands/providers/schema.html.md
- website/docs/configuration-0-11/terraform.html.md
- website/docs/configuration/functions/setintersection.html.md
- website/docs/configuration/functions/setproduct.html.md
- website/docs/configuration/functions/setunion.html.md
- website/docs/configuration/functions/timestamp.html.md
- website/docs/configuration/functions/uuidv5.html.md
While working on another PR, I noticed a few minor typos.
> docs: Minor spelling and typo fixes

- website/docs/configuration/variables.html.md
> website: Add complex type example to variables.html

- lang/funcs/number.go
- lang/funcs/number_test.go
- lang/functions.go
- lang/functions_test.go
- website/docs/configuration/functions/parseint.html.md
- website/layouts/functions.erb
Added a function to parse a string to an integer for a specified base.
Closes #22584. Also see #22585.
> lang/funcs: added parseint function

- .github/CONTRIBUTING.md
- README.md
This PR seeks to remove outdated and incorrect information. There is
still work to be done updating the information that's left; this is
merely the first step.
> website/contributing: update contribution documentation

- website/docs/providers/index.html.markdown
- website/docs/providers/type/misc-index.html.markdown
Adding links to the Genymotion provider documentation.
> [Website] Add Genymotion doc links

- website/docs/commands/cli-config.html.markdown
Small documentation link update.
> website: update link to api token documentation for terraform cloud

- website/docs/providers/type/community-index.html.markdown
Add CDA as an new community provider
> [Website] Add CDA community provider

- website/docs/configuration/expressions.html.md
- website/docs/configuration/resources.html.md
Some additions to the expressions docs clarifying usage around `for_each` managed resources
> Update expression docs to clarify for_each usage

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Cherrypick from https://github.com/hashicorp/terraform/pull/23082
> [Cherry-pick] Okta

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Adding new provider links for Okta 
Moving the Venafi provider type
> [Website] Provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Create links to point to the newly certified LaunchDarkly TF provider
> [Website] LaunchDarkly provider links

- website/docs/configuration/resources.html.md
- website/docs/modules/composition.html.markdown
- website/docs/state/workspaces.html.md
replacing an outdated syntax for tags in multiple locations.
https://github.com/hashicorp/terraform/issues/21614
> Fix documentation for issue #21614, 

- website/docs/configuration/syntax.html.md
> Fix link in syntax docs

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Cherry-pick from https://github.com/hashicorp/terraform/pull/23183
> [Cherry-pick] from master

- website/docs/registry/providers/docs.html.md
- website/layouts/registry.erb
> website: Add Terraform Registry Provider Docs page

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
Cherry pick from master branch of https://github.com/hashicorp/terraform/pull/23212
> [Cherry-pick] Dome9 provider links

- website/docs/configuration/modules.html.md
- website/docs/configuration/providers.html.md
- website/docs/configuration/terraform.html.md
Addresses question 1 and 3 from #21699
> Document that Provider Proxy Configuration only supports `alias`

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Adding website links to the CherryServer provider documentation
> [Website] CherryServer doc links

- website/docs/commands/taint.html.markdown
Provide an explanation of how to taint a resource created with for_each
> Update taint docs - for_each

- backend/atlas/state_client_test.go
`testing.T.Fatal()` is a convenience function that calls `T.Log()` before `T.FailNow()`. From the godoc:
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
This PR changes the `doneCh` that passed an empty struct to mark goroutine completion into an `errCh` that exfiltrates any errors from the goroutine so that `t.Fatal()` can be called from the parent goroutine.
> backend/atlas: fix use of T.Fatal() inside goroutine

- website/docs/configuration/functions/base64sha256.html.md
- website/docs/configuration/functions/base64sha512.html.md
Fixed base64sha256 doc and updated base64sha512 doc in the same manner.
> Fix base64sha256/512 docs

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Adding links for the newly created vThunder provider
> [Website] vThunder links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Cherrypick from https://github.com/hashicorp/terraform/pull/23323
> [Cherrypick] vThunder links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Add links for the new HuaweiCloudStack provider
> [Website] Add huawei links

- configs/configupgrade/upgrade_expr.go
Terraform 0.12upgrade assumes that the configuration has passed 0.11
init, but did not explicitly check that the configuration was valid.
Certain issues would not get caught because the configuration was
syntactically valid. In this case, int or float values out of range
resulted in a panic.
Since running a 0.11 validate command is a breaking change, this PR
merely moves the `Value()` logic for ints and floats into configupgrade so
the error can be returned to the user, instead of causing a panic.
Fixes #23148
> configs/configupgrade: do not panic over int value out of range

- website/docs/configuration-0-11/interpolation.html.md
Replacement for a PR that went stale.
> website: placeholders in interpolation.html

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Add links to the new certified OpenNebula provider
> [Website] OpenNebula provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Cherry-pick from master branch from https://github.com/hashicorp/terraform/pull/23456
> [Cherrypick] Add opennebula links

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- configs/parser_config_dir.go
- terraform/node_resource_abstract.go
- tfdiags/contextual.go
Located all non-test paths where a Diagnostic type was assigned to an
error variable.
> fix diagnostics handling

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
cherrypick from master branch at https://github.com/hashicorp/terraform/pull/23584
> [Cherrypick] add stackpath links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Add two links to the newly certified StackPath provider
> [Website] add stackpath links

- backend/remote-state/s3/backend_test.go
S3 backend tests were failing on master
> Fix S3 test

- backend/remote-state/s3/backend_state.go
This resolves https://github.com/hashicorp/terraform/issues/15968
* backend/remote-state/s3/backend_state.go: Prior to this commit, the terraform s3 backend did
not paginate calls to s3 when finding workspaces, which resulted in workspaces 'disappearing'
once they are switched away from, even though the state file still exists. This is due to the
ListBucket operation defaulting MaxItems to 1000, so terraform s3 backends that contained
more then 1000 workspaces did not function as expected. This rectifies this situation by
paginating calls to s3 when finding workspaces.
Signed-off-by: Collin J. Doering <collin@rekahsoft.ca>
> Allow s3 backends to contain more then 1000 workspaces

- BUILDING.md
Split a sentence under the  "Versioning" section into two sentences to improve flow
> Edit BUILDING.md

- website/docs/configuration/outputs.html.md
Heya, this is my first contribution to terraform.
Happy to be able to help such and awesome product grow!
This PR adds a note to the official docs about the Output values behavior.
I've spend hours last Friday issuing changes to the output files alone and getting no outputs out of Terraform cloud (it didn't issue an apply because the state files and the code I was working on matched. And because of that I wasn't able to to test my changes properly.)
> Update Output values docs

- website/docs/state/sensitive-data.html.md
> website: Revise sensitive data in state page

- website/docs/providers/type/cloud-index.html.markdown
> Change Yandex.Cloud provider name in index

- website/docs/configuration/functions/range.html.md
Fixing a documentation issue with the pseudocode for the range function.
https://github.com/hashicorp/terraform/issues/23472
> Issue 23472 - Updated documentation for range function pseudocode

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Adding the two links to point to the checkpoint provider documentation
> [Website]add checkpoint links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
Cherrypick from master branch at https://github.com/hashicorp/terraform/pull/23856
> [cherry-pick]add checkpoint links

- website/docs/commands/0.12upgrade.html.markdown
- Added `uniq` making sure you get each directory once
- Added comment regarding OSX run
Sorry for the branch name in advance. Seems Github does not allow to edit the branch name when submitting from the web.
> Batch upgrade documentation

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
committing changes to stable-website branch
> [Cherypick] Add MetalCloud provider links

- website/docs/registry/modules/verified.html.md
Change the working around verified modules guarantee
> [Website] Verified module update

- website/docs/registry/modules/verified.html.md
cherrypick from https://github.com/hashicorp/terraform/pull/23971
> [Cherrypick] Verified module update

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Two links for the Auth0 provider docs
> [Website] Add Auth0 provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Cherrypick from https://github.com/hashicorp/terraform/pull/23974
> [Cherrypick] Add Auth0 provider links

- website/docs/provisioners/index.html.markdown
> VMware spelling update

- command/console.go
- command/import.go
[Follow-up from this review comment](https://github.com/hashicorp/terraform/pull/24120/files#r379639510).
> command: Comment to explain why unlock is required

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
Cherrypicked from master branch at https://github.com/hashicorp/terraform/pull/24267
> [Cherrypick] website docs

- website/docs/providers/index.html.markdown
- website/docs/providers/type/major-index.html.markdown
Cherrypick from https://github.com/hashicorp/terraform/pull/24335
> [Cherrypick] website links

- addrs/provider.go
- addrs/provider_test.go
- configs/config_test.go
- configs/module.go
- configs/module_merge.go
- configs/module_test.go
- configs/parser_test.go
- configs/provider_requirements.go
- configs/provider_requirements_test.go
- configs/provider_test.go
- configs/testdata/valid-modules/nested-providers-fqns/child/main.tf
- configs/testdata/valid-modules/nested-providers-fqns/main.tf
- configs/testdata/valid-modules/providers-fqns/main.tf
- terraform/testdata/transform-provider-fqns-module/child/main.tf
- terraform/testdata/transform-provider-fqns-module/main.tf
- terraform/testdata/transform-provider-fqns/main.tf
- terraform/transform_provider_test.go
This is the first test that shows that terraform understands (or at least, is starting to) the difference between a provider LocalName and FQN.
> terraform: provider source test

- command/cliconfig/credentials.go
Cherry-pick of #24397 onto v0.12 branch.
> command: Fix bug when using terraform login on Windows

- website/docs/providers/index.html.markdown
- website/docs/providers/type/misc-index.html.markdown
Removing the quorum provider listing
> [Website] Remove provider listing

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Adding two links to the newly certified SumoLogic Terraform provider.
> [Website] Add SumoLogic provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/monitor-index.html.markdown
Cherrypick from https://github.com/hashicorp/terraform/pull/24618
> [Cherrypick] from master branch

- website/docs/modules/sources.html.markdown
Related to https://github.com/hashicorp/terraform/issues/16442
> Keep s3 docs in line with functionality

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
This is a cherrypick from https://github.com/hashicorp/terraform/pull/24653
> [Cherrypick] provider links

- website/docs/configuration/functions/format.html.md
> Fix "additoinal" typo in web site

- command/login.go
- states/statemgr/filesystem_test.go
- terraform/eval_context_builtin.go
- terraform/hook_test.go
This is a proposed cherry-pick to 0.12 of the race condition fixes in https://github.com/hashicorp/terraform/pull/24599
> [Cherry-pick]  Fix races in GetVariableValue and login #24599 

- terraform/context_validate_test.go
- terraform/node_module_expand.go
Adds some basic validation on count and for_each arguments in `module` blocks. Prior to this change, invalid values were allowed (ex. an incorrect function in the tests).
> Add more validation to expanding modules

- website/docs/configuration/modules.html.md
Asana: https://app.asana.com/0/1128567758154570/1169245598025242
> Add link to new learn track in configuration/modules.html

- command/013_config_upgrade.go
- command/013_config_upgrade_test.go
The `0.13upgrade` command modifies the local configuration files, so we should warn the user that this is about to happen, advise them to ensure their version control is in a clean state, and add a confirmation prompt to continue.
The UI is similar to [the prompt in the `0.12upgrade` command](https://github.com/hashicorp/terraform/blob/acc48bf9ddc3a5e4165d46b63b09ee550fd561c8/command/012_config_upgrade.go#L122-L130). Feedback on the copy used is especially welcome! 🙏
> command: Add prompt & confirmation to 0.13upgrade

- website/docs/configuration/syntax-json.html.md
> website/docs: provider aliases in the JSON format

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
Adding KingsoftCloud provider links
> [Website] KingsoftCloud provider link

- website/docs/providers/index.html.markdown
- website/docs/providers/type/cloud-index.html.markdown
cherrypick from https://github.com/hashicorp/terraform/pull/24953
> [Cherrypick] Kingsoft cloud provider link

- website/docs/commands/environment-variables.html.md
Fixing one broken link, and tidying the sentences a bit.
> website: Edit text of new TF_IGNORE env var docs

- plans/changes_src.go
Just fix typo in changes_src.go.
I'm being helped by Terraform everyday, thanks 🙏
> fix typo ResourceInstancChange to ResourceInstanceChange

- website/docs/import/index.html.md
We fully intend to tackle this area of Terraform, but this vague statement is no longer helpful. Will update when we have something more concrete.
> Small modification to the website docs regarding import

- website/docs/configuration/resources.html.md
Provide example of using for_each with a set. There is no other example of this on entire internet at the moment, and key is to use toset method on the list provided.
> Example of for_each with list -> set using toset

- website/docs/backends/types/s3.html.md
There is no description for the type of `LockID` on this page. I want to improve it.
> improve s3.html.md

- website/docs/providers/terraform/d/remote_state.html.md
Example for local backend added.
> local backend example added

- website/docs/commands/state/mv.html.md
When I want to move an existing resource under a module, it doesn't work well with the current sample code, so I want to fix it.
> fix sample code

- command/e2etest/init_test.go
The e2etest `TestInitProviders_pluginCache` was failing on windows because a handful of paths and the null provider binary name needed to be converted for windows (slashes for the paths and adding `.exe` to the binary name of the plugin downloaded from the registry). This PR fixes that.
Confirmed on windows ( via `make-archive.sh` and a local VM); 
```
C:\Users\User\terraform-e2etest_windows_amd64>.\e2etest.exe -test.v -test.run TestInitProviders_pluginCache
=== RUN   TestInitProviders_pluginCache
=== PAUSE TestInitProviders_pluginCache
=== CONT  TestInitProviders_pluginCache
--- PASS: TestInitProviders_pluginCache (4.59s)
PASS
```
> update e2etests for windows compatibility

- website/docs/configuration/data-sources.html.md
- website/docs/configuration/modules.html.md
Update depends_on for modules and data sources.
> depends_on doc updates

- configs/named_values.go
- configs/named_values_test.go
> config/name_values: fix index out of range in looksLikeSentences

- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
- vendor/github.com/hashicorp/hcl/v2/diagnostic.go
- vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl/v2/hclwrite/parser.go
- vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
- vendor/github.com/zclconf/go-cty/cty/type.go
- vendor/github.com/zclconf/go-cty/cty/value.go
- vendor/github.com/zclconf/go-cty/cty/value_ops.go
- vendor/modules.txt
Upgrades:
- hcl v2.6.0: https://github.com/hashicorp/hcl/releases/tag/v2.6.0
- cty v1.5.0: https://github.com/zclconf/go-cty/releases/tag/v1.5.0
Issues:
- Fixes #22404
- Fixes #24377
- Fixes #24805 
- Fixes #25150
> Upgrade hcl and go-cty

- website/docs/backends/types/kubernetes.html.md
Spotted a few mistakes in the docs.
> Fix errors in kubernetes backend documentation

- backend/remote-state/oss/backend.go
This PR aims to support setting HTTPS_PROXY for OSS service. The test result as following:
```
TF_ACC=1 go test -v ./backend/remote-state/oss/ -run=TestBackend -timeout 120m
2020/06/05 10:18:11 [DEBUG] Instantiate OSS client using endpoint: "https://oss-cn-beijing.aliyuncs.com"
--- PASS: TestBackendConfig (0.26s)
backend_test.go:47: TestBackendConfig on *oss.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("terraform-backend-oss-test"), "key":cty.StringVal("first.tfstate"), "prefix":cty.StringVal("mystate"), "region":cty.StringVal("cn-beijing"), "tablestore_endpoint":cty.StringVal("https://terraformstate.cn-beijing.ots.aliyuncs.com"), …
```
> backend/oss: supports setting HTTPS_PROXY

- website/docs/providers/index.html.markdown
- website/docs/providers/type/network-index.html.markdown
> [Website] Cisco MSO provider links

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
Adding the links to the Rubrik provider docs
> [Website] Add Rubrik links

- website/upgrade-guides/0-11.html.markdown
> Typo fix to v11 upgrade guide

- website/docs/import/index.html.md
- website/docs/import/usage.html.md
Add a link to the Terraform Import guide on learn.
> Add link to new Terraform Import guide on learn platform

- .github/ISSUE_TEMPLATE/bug_report.md
Just a quick proposal for a patch (literally using GH UI for PR) to the issue template. If this is not desired, then that is cool.
> update hcl language markdown to terraform markdown

- website/docs/providers/type/community-index.html.markdown
Not sure if this is the correct approach to add a community provider entry in the index. Though I have submit the register form, but there is no reply.
> add community provider entry: terraform-provider-outlook

- website/docs/providers/index.html.markdown
- website/docs/providers/type/infra-index.html.markdown
Add provider links for CloudAMQP provider
> [Website] CloudAMQP links

- website/docs/registry/providers/docs.html.md
- website/docs/registry/providers/publishing.html.md
Links to https://registry.terraform.io/tools/doc-preview
> website: Add links to registry doc preview tool

- website/guides/terraform-provider-development-program.html.md
Updating Terraform Provider Development Program
> [Website] Provider Dev Program Guide

- command/hook_ui.go
This code was made to do nothing pre-0.12, and we have no plans to reintroduce a diff in the apply output, so it seems reasonable to now remove it altogether.
> command: Remove stubbed-out apply diff output code

- website/docs/configuration/modules.html.md
- website/docs/configuration/providers.html.md
- website/docs/internals/module-registry-protocol.html.md
OK, I think I got all of the ones that are currently appearing on builds. (There was another one listed in the current failure, but Petros already got it.)
> website: Fix several broken links

- terraform/graph_builder_apply.go
- terraform/graph_builder_apply_test.go
- terraform/graph_builder_plan.go
- terraform/graph_builder_plan_test.go
- terraform/graph_builder_refresh.go
@jbardin mentioned wanting to remove this so here we are 😝
> terraform: remove DisableReduce from refresh, plan and apply graphs

- CODEOWNERS
I also added myself as the maintainer for the PostgreSQL backend, I don't have a very large bandwidth at the moment but I know PostgreSQL a bit so I will try to help in my spare time.
CC @danieldreier
> Add remilapeyre to CODEOWNERS

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/backend.go
- backend/remote-state/azure/backend_test.go
- website/docs/backends/types/azurerm.html.md
fixes #24179
fixes #25765
supersedes #19606
dependent on #25769
> backend/azurerm: support for authenticating using a Client Certificate

- website/docs/provisioners/index.html.markdown
Adding cross links to Learn for new provisioner guides
> Updating links for cloud init guide in docs

- website/docs/configuration/modules.html.md
`foreach` on modules should be `for_each`
> Fix foreach to for_each

- website/docs/commands/providers/mirror.html.md
> chore: Update mirror.html.md

- website/docs/registry/providers/publishing.html.md
The GitHub Action passes this in already.
> website:  Omit unnecessary instruction fror Registry

- website/docs/configuration/variables.html.md
Wouldn't you know it, I saw this RIGHT after I clicked the merge button on #26085 😩
> website: Fix copy-paste error

- command/format/diff_test.go
Most of the functionality for rendering output changes is covered by the tests for `ResourceChanges`, as they both share the same diff renderer. This commit adds a few tests to cover some of the output specific code.
> command: Add tests for format.OutputChanges

- website/docs/configuration/expressions.html.md
`false` was missing a finishing "`"
> Correct annotation in expressions.html

- website/docs/registry/providers/publishing.html.md
Signed-off-by: shaowenchen <mail@chenshaowen.com>
> improvement github token

- states/remote/remote_test.go
- states/remote/state.go
- states/remote/state_test.go
Cherry-pick of https://github.com/hashicorp/terraform/pull/26190/ for 0.13
> Fix bug for force push for backends besides the remote backend

- website/docs/configuration/functions/timestamp.html.md
This utility Terraform Provider has resources designed to handle and store time information by participating normally in the graph.
> docs/function/timestamp: Mention Time Provider

- terraform/context_apply_test.go
- terraform/node_resource_destroy.go
> 0.13 backport of #26263

- terraform/context_apply_test.go
- terraform/evaluate.go
> 0.13 backport of #26264

- website/docs/registry/providers/publishing.html.md
> website: Add Registry email to publishing doc

- go.mod
- go.sum
- terraform/context_apply_test.go
Dependency upgrades for zclconf/go-cty#67 and hashicorp/hcl#406, along with a test for using complex values with the sensitive feature.
> Complex sensitive values

- terraform/context_plan_test.go
- terraform/eval_read_data_plan.go
A data source referencing another data source through depends_on should
not be forced to defer until apply. Data sources have no side effects,
so nothing should need to be applied. If the dependency has a
planned change due to a managed resource, the original data source will
also encounter that further down the list of dependencies.
This prevents a data source being read during plan for any reason from
causing other data sources to be deferred until apply. It does not
change the behavior noticeably in 0.14, but because 0.13 still had
separate refresh and plan phases which could read the data source, the
deferral could cause many things downstream to become unexpectedly
unknown until apply.
> data source depends_on

- .github/ISSUE_TEMPLATE/bug_report.md
- BUGPROCESS.md
- README.md
Add a written bug triage process and link to it in README.md.
This is a proposal, and the goals and norms are described here for the sake of discussion
> Add bug triage guide

- terraform/node_output.go
- terraform/node_output_test.go
Sensitive values may not be used in outputs which are not also marked as sensitive. This includes values nested within complex structures.
Note that sensitive values are unmarked before writing to state. This means that sensitive values used in module outputs will have the sensitive mark removed. At the moment, we have not implemented sensitivity propagation from module outputs back to value marks.
This commit also reworks the tests for `NodeApplyableOutput` to cover more existing behaviour, as well as this change.
> terraform: Check for sensitive values in outputs

- command/init.go
As we add and remove support for different target platforms over time, there will be transition periods where the available platforms for each provider will be different than the available platforms for Terraform CLI itself.
In recognition of that possibility, here we add a more specialized error message for that situation which tries to explain the problem a little more clearly than the generic error message that came before it.
In an ideal world we'd be able to detect situations where a newer or older version has support in a similar vein to what we do with provider protocol incompatibilities, but we don't currently have logic to fetch the data necessary to implement that, so this is instead a presentation-only change aimed at allowing some possible near-future changes to the supported …
> command/init: Better error message for provider unsupported platform

- configs/module_merge.go
- configs/module_merge_test.go
- configs/named_values.go
- configs/testdata/warning-modules/override-variable/a_override.tf
- configs/testdata/warning-modules/override-variable/b_override.tf
- configs/testdata/warning-modules/override-variable/primary.tf
Implements merging behavior for when `sensitive` is set on a variable.
> Implement module merge for sensitive variable config

- website/docs/commands/force-unlock.html.markdown
-Added code block for terraform force-unlock LOCK_ID
> Modified terraform force-unlock command

- website/docs/backends/types/s3.html.md
- website/docs/cli-index.html.md
- website/docs/commands/apply.html.markdown
- website/docs/commands/environment-variables.html.md
- website/docs/commands/import.html.md
- website/docs/commands/index.html.markdown
- website/docs/commands/init.html.markdown
- website/docs/commands/plan.html.markdown
- website/docs/configuration/index.html.md
- website/docs/configuration/modules.html.md
- website/docs/configuration/provider-requirements.html.md
- website/docs/configuration/resources.html.md
- website/docs/configuration/variables.html.md
- website/docs/import/index.html.md
- website/docs/import/usage.html.md
- website/docs/modules/index.html.markdown
- website/docs/plugins/basics.html.md
- website/docs/plugins/provider.html.md
- website/docs/provisioners/index.html.markdown
- website/docs/registry/providers/publishing.html.md
- website/guides/core-workflow.html.md
- website/intro/examples/consul.html.markdown
- website/intro/examples/index.html.markdown
- website/intro/index.html.markdown
- website/layouts/guides.erb
- website/upgrade-guides/0-11.html.markdown
The URL structure on Learn recently changed, so it's time to update some URLs.
> website: Update all Learn crosslinks

- website/guides/terraform-provider-development-program.html.md
> Fixed a typo

- backend/remote-state/azure/backend.go
Fix build by adding argument missing from #26463.
> add missing Context argument

- .hashibot.hcl
This is to test to see if migration is working again. Will label sample issue with `migrationtest/` to trigger
> Migration test

- .hashibot.hcl
Permissions were restored to this repo, POST/PATCH requests such as issue closing should be fixed.
> Restore issue migrator

- command/format/diff.go
- command/format/diff_test.go
When an attribute's sensitivity changes, but its value remains the same,  we consider this an update operation for the plan. This commit updates the diff renderer to match this, detecting and displaying the change in sensitivity.
Previously, the renderer would detect no changes to the value of the attribute, and consider it a no-op action. This resulted in suppression of the attribute when the plan is in concise mode.
This is achieved with a new helper function, `ctyEqualValueAndMarks`. We call this function whenever we want to check that two values are equal in order to determine whether the action is update or no-op.
Before:
After:
> command: Show diffs when only sensitivity changes

- .github/CONTRIBUTING.md
An update on the deprecated state of vendor provisioners for our contribution guide.
> Provisioner contribution guide updates

- backend/remote-state/pg/backend.go
- backend/remote-state/pg/backend_test.go
- website/docs/backends/types/pg.html.md
Closes https://github.com/hashicorp/terraform/issues/25708
> Add skip_table_creation and skip_index_creation options to the pg backend

- command/init.go
- command/meta.go
- terraform/context.go
This doesn't seem to be used anywhere.
> Remove unused env var TF_SKIP_PROVIDER_VERIFY

- plans/objchange/objchange.go
- plans/objchange/objchange_test.go
> 0.14 backport of #26606

- dag/dag.go
- helper/schema/field_writer_map.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_plan.go
- website/docs/registry/api.html.md
Fixes some comments in the source code that were bothering me (ableist language)
> Comment fixing

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/backend.go
- backend/remote-state/azure/helpers_test.go
> Backport Azure Backend changes from #26463 to 0.13

- terraform/context_apply_test.go
- terraform/context_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
Port of #26590 (mea culpa for not squashing the original PR into one commit)
> [0.14 port] Mark attributes providers mark as sensitive

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
> 0.14 backport 26638

- website/upgrade-guides/0-14.html.markdown
Cherry pick of https://github.com/hashicorp/terraform/pull/26643
> [0.14 cherry pick] 0.14 guide updates

- terraform/context_plan_test.go
- terraform/eval_diff.go
- terraform/testdata/plan-ignore-changes-sensitive/ignore-changes-sensitive.tf
Backport of #26644, which fixes an 0.14.0-beta1 bug.
> terraform: Fix sensitive values in ignore changes

- website/docs/commands/get.html.markdown
-Added PATH
-Added -no-color option
> Modified terraform get command

- website/docs/providers/terraform/index.html.markdown
Fixed config argument on datasource's configuration example
> website: Fixed config argument on example

- terraform/context_apply_test.go
- terraform/context_refresh_test.go
- terraform/graph_builder_plan.go
- terraform/node_resource_plan_instance.go
- terraform/node_resource_plan_orphan.go
- terraform/node_resource_plan_orphan_test.go
- terraform/provider_mock.go
> 0.14 backport of 26674

- website/docs/configuration/provider-requirements.html.md
> website: Fix for documentation around local-name conflicts

- lang/funcs/collection.go
- lang/funcs/collection_test.go
- lang/functions.go
- lang/functions_test.go
- website/docs/configuration/functions/anytrue.html.md
- website/layouts/functions.erb
This commit adds an `anytrue` function to Terraform configuration. It's
mostly a complement to the recently introduced `alltrue` function.
> lang/funcs: Add "anytrue" function

- experiments/experiment.go
- terraform/context_apply_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
- website/upgrade-guides/0-14.html.markdown
0.14 port of https://github.com/hashicorp/terraform/pull/26706
> [0.14 port] Add provider sensitivity propagation experiment

- command/jsonstate/state.go
- command/jsonstate/state_test.go
- command/testdata/show-json-state/sensitive-variables/output.json
- command/testdata/show-json-state/sensitive-variables/terraform.tfstate
backport https://github.com/hashicorp/terraform/pull/26739
> [backport] Show sensitive attributes in show -json

- command/format/state.go
- command/format/state_test.go
Backport https://github.com/hashicorp/terraform/pull/26740
> [backport] Hide sensitive outputs in terraform show

- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/context_validate_test.go
These weren't quite done, but got lost in the huge PR.
> fix the rpc diags tests

- website/docs/configuration/functions/element.html.md
and added instructions on how to get the last value in the list.
> website: The index must be non-negative integer

- website/docs/configuration/functions/lookup.html.md
Typo in introductory paragraph.
> Website: Update lookup.html.md

- website/guides/terraform-provider-development-program.html.md
Cherry picked changes from https://github.com/hashicorp/terraform/pull/26854
> [Cherrypick] Website changes

- website/docs/backends/types/azurerm.html.md
Ran into this while doing some major reorganization stuff, but it wasn't really related to any of it so I didn't want to clutter those PRs with it.
> website: Fix a random typo in azurerm backend

- main.go
Previously Terraform would react to an invalid top-level command the same way as for typing no command at all: just printing out the long top-level help directory.
If someone's tried to type a command, it's more helpful to respond to that request by explaining directly that the command is invalid, rather than leaving the user to puzzle that out themselves by referring to the help text.
As a bonus, this also allows us to use our `didyoumean` helper package to suggest a possible alternative if it seems like the user made a typo.
```shellsession
$ terraform blorp
Terraform has no command named "blorp".
To see all of Terraform's top-level commands, run:
terraform -help
$ terraform destory
Terraform has no command named "destory". Did you mean "destroy"?
To see all of Terraform's top-level …
```
> main: Special error message for invalid top-level command

- website/docs/configuration/functions/defaults.html.md
- website/docs/configuration/functions/textdecodebase64.html.md
- website/docs/configuration/functions/textencodebase64.html.md
Some configuration problems that could potentially break the site build.
> website: fix a few functional glitches

- website/docs/configuration/functions/defaults.html.md
- website/upgrade-guides/0-14.html.markdown
Fixing a number of failed automatic backports from the post-GA doc fixes.
> Website: Pk final docs fixes

- website/upgrade-guides/0-14.html.markdown
Link from the TOC to the new section is broken.
> Website: Upgrade guide link fix

- terraform/context_plan_test.go
- terraform/eval_diff.go
- terraform/eval_diff_test.go
> 0.14 backport of #27141

- website/docs/configuration/functions/setproduct.html.md
I found wrong syntax while I'm reading document of `setproduct`.
For someone confused by document, I open this PR.
> Fix wrong syntax in setproduct.html.md

- terraform/eval_for_each.go
- terraform/eval_for_each_test.go
> Backport 27247

- go.mod
- go.sum
> Update hcl and go-cty dependencies

- website/docs/configuration/locals.html.md
- website/docs/configuration/outputs.html.md
Link back to learn tutorials. I hope it's ok to combine both in one PR! lmk otherwise.
> Add links to outputs and locals tutorials

- internal/depsfile/locks_file.go
- internal/depsfile/locks_file_test.go
Signed-off-by: Anthony Sottile <asottile@umich.edu>
Resolves #27116
> fix file mode on lock file

- terraform/context_apply_test.go
- terraform/node_resource_abstract_instance.go
- terraform/testdata/apply-data-sensitive/main.tf
> core: Fix for sensitive data source arguments

- internal/depsfile/locks_file.go
- internal/depsfile/locks_file_test.go
0.14 backport of #27205
Closes #27435
> 0.14 backport of #27205

- terraform/context_apply_test.go
- terraform/node_resource_abstract_instance.go
If the provider returns an empty response during apply, we restore the
prior state for the resource, but the private data was not being
restored.
Fixes #27452
> preserve resource private data on error

- website/docs/cli/commands/workspace/list.html.md
- website/docs/cli/commands/workspace/new.html.md
- website/docs/cli/commands/workspace/select.html.md
Updating terraform workspace website list.html.md new.html.md select.html.md files thus it reflect the current version of Terraform CLI
> website: Updating terraform workspace docs

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
> Backport: Unmark before ElementIterator in couldHaveUnknownBlockPlaceholder

- command/apply_test.go
Make an old concurrent test more deterministic, and not rely on sleep for any synchronization.
> fix concurrent test relying on sleep

- command/jsonstate/state.go
- command/jsonstate/state_test.go
> 0.14 backport of 27352

- command/format/diff.go
When rendering a new, very large multi-line string output as part of `terraform plan` or `terraform apply`, we hit this code path: https://github.com/hashicorp/terraform/blob/14936e65504638b0b5430fbd41d8f3be365b9545/command/format/diff.go#L699-L711
The `writeValueDiff` multi-line string renderer calculates a longest common subsequence, which is an operation with quadratic time and space complexity. When the "two" strings are in fact the same value (as you can see from the call above), this results in a worst-case execution time. For very large strings, this can be several minutes:
```shellsession
$ time terraform-0.14.5 plan >/dev/null
real	4m3.381s
user	3m53.593s
sys	0m15.892s
```
This commit adds an early shortcut for this specific case, using simple string equality as the test, which …
> cli: Optimize for large multi-line string outputs

- backend/local/backend_refresh.go
- backend/local/backend_refresh_test.go
The warning diag added when refreshing an empty state file was never rendered, and instead a custom (and slightly incorrect) warning was output to the UI. This commit fixes the dropped diag and removes the custom warning.
This change is in service of moving custom UI rendering out of the backend code as much as possible before migrating to views.
> backend/local: Return diag for refresh empty state

- plugin/convert/diagnostics_test.go
Add a test for a diagnostic with no steps to make sure it still gets
associated with the resource in the config. Follow up to #27710 using
@alisdair's suggested testing.
I verified this by commenting out the fix in #27710, verifying it exhibited the behavior, and then adding it back in, and verifying the behavior in question was gone.
(Feel free to ignore this if the test isn't worth the merge, I just feel guilty for submitting a bugfix without a test associated.)
> Test empty diagnostics.

- website/upgrade-guides/0-14.html.markdown
Teeny tiny fix for a grammatical mistake in the v0.14 upgrade docs.
> Fix sentence in v0.14 upgrade guide

- internal/moduletest/provider.go
I held off merging my last PR so I could update this file, forgot about it, and merged my PR anyway. sorry!
If this is approved I'll close the revert PR https://github.com/hashicorp/terraform/pull/27902; I opened that first in case there was a major timing issue
> moduletest: update to match recent provider interface changes

- .circleci/config.yml
- .github/CONTRIBUTING.md
- README.md
- codecov.yml
- docs/plugin-protocol/README.md
- docs/plugin-protocol/tfplugin5.0.proto
- docs/plugin-protocol/tfplugin5.1.proto
- docs/plugin-protocol/tfplugin5.2.proto
- docs/plugin-protocol/tfplugin6.0.proto
- internal/tfplugin5/tfplugin5.pb.go
- internal/tfplugin6/tfplugin6.pb.go
- website/docs/language/settings/index.html.md
- website/docs/language/state/workspaces.html.md
- website/guides/core-workflow.html.md
- website/upgrade-guides/0-10.html.markdown
- website/upgrade-guides/0-11.html.markdown
- website/upgrade-guides/0-13.html.markdown
- website/upgrade-guides/0-7.html.markdown
- website/upgrade-guides/0-8.html.markdown
- website/upgrade-guides/0-9.html.markdown
Mostly a docs/links update, but there are some build-related renames in here too. 
The good news is if I missed anything, GitHub will provide a redirect anyway 🎉
> update to match new default branch name

- command/format/diff.go
- command/format/diff_test.go
Prior to this PR, NestedType attributes were treated like "norma" object-type attributes. The limitation being that if an inner attribute was sensitive, the entire attribute had to be marked sensitive. 
In the following before/after, `"conn_info"` is a NestedType attribute with an inner sensitive attribute, `"password"`:
Before:
```hcl
+ resource "test_instance" "example" {
+ conn_info = (sensitive value)
+ id        = (known after apply)
+ password  = (sensitive value)
}
```
After:
```hcl
+ resource "test_instance" "example" {
+ conn_info = {
+ password = (sensitive value)
+ user     = "not-secret"
}
+ id        = (known after apply)
+ password  = (sensitive value)
}
```
The majority of the code was copied and adapted from the NestedBlock printer, with minor tweaks for attribute-specific …
> Add formatting for attributes with nested types

- experiments/experiment.go
- terraform/context_apply_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
Conclude the provider sensitivity experiment and make this a default behavior.
> Make provider sensitivity default behavior

- website/docs/cli/commands/plan.html.md
Add a callout to our new resource targeting tutorial.
> Add callout to resource targeting tutorial

- terraform/context_apply2_test.go
- terraform/context_plan2_test.go
- terraform/node_resource_abstract_instance.go
> v0.15 backport of 28267

- backend/remote-state/kubernetes/backend.go
- backend/remote-state/kubernetes/client.go
- website/docs/language/settings/backends/kubernetes.html.md
This PR is to bring the backend configuration for Kubernetes in line with the Kubernetes provider.
Also fixes https://github.com/hashicorp/terraform/issues/26479
> Port kubernetes backend config changes from kubernetes provider 2.0.0

- go.mod
- go.sum
> deps: update go-plugin to v1.4.1

- go.mod
- go.sum
"backport" of https://github.com/hashicorp/terraform/pull/28465
> deps: update go-plugin dependency

- lang/funcs/collection_test.go
- lang/funcs/defaults.go
- lang/funcs/defaults_test.go
Two commits here, and I recommend reading (at least) the second commit message.
* `TransposeFunc`: This function was already handling marks, so this commit only adds tests to document the behavior.
* `DefaultFunc`: This is the trickier one! The majority of the behaviors after adding `AllowMarks: true` were pretty intuitive; I unmarked the input and default and re-marked whichever value was applied and the majority of my tests Just Passed. The last test case is the tricky one, where marks on the entire default `object` are applied to the individual elements. I'm happy to spend more time with this test case if this doesn't seem right; I don't think it really makes sense to mark the entire default object _anyway_, and if so it seems safe for each element to get those marks.
```
{
Input: …
```
> lang/funcs: tests for Transpose + mark handling for Defaults

- website/docs/internals/debugging.html.md
Contains a Learn link to the Troubleshooting tutorial. Links to the "best practices for bug reporting" section.
> Add Learn link to Debugging

- configs/configschema/decoder_spec.go
- configs/configschema/decoder_spec_test.go
- go.mod
- go.sum
- lang/blocktoattr/fixup.go
- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
- plans/objchange/objchange.go
- terraform/context_validate_test.go
> Backport of Better planing of unknown dynamic blocks into v0.15

- .circleci/config.yml
This leaves the cover profiles in place for now, we can remove them later if we don't want to make use of those.
> remove codedov

- lang/funcs/crypto.go
- lang/funcs/filesystem.go
Previously our file hashing functions were backed by the same "read file into memory" function we use for situations like `file` and `templatefile`, meaning that they'd read the entire file into memory first and then calculate the hash from that buffer.
All of the hash implementations we use here can calculate hashes from a sequence of smaller buffer writes though, so there's no actual need for us to create a file-sized temporary buffer here.
This, then, is a small refactoring of our underlying function into two parts, where one is responsible for deciding the actual filename to load opening it, and the other is responsible for buffering the file into memory. Our hashing functions can then use only the first function and skip the second.
This then allows us to use `io.Copy` to stream from …
> lang/funcs: File hashing functions stream data from disk

- terraform/node_resource_validate.go
When we detect that a module is trying to declare a resource type that doesn't exist in its corresponding provider, we have enough information to give some hints as to what might be wrong.
We give preference to the possibility of mixing up a managed resource type with a data resource type, but if not that then we'll use our usual [levenshtein-distance](https://en.wikipedia.org/wiki/Levenshtein_distance)-based similar name suggestion function.
We currently don't typically test exact error message text, and this is just a cosmetic change to the message output, so there are no new automated tests or modifications to existing ones here. However, some manual testing yielded the following output:
```
╷
│ Error: Invalid resource type
│ 
│   on null-things.tf line 2, in resource …
```
> core: "Did you mean" hints for unsupported resource types

- website/docs/language/functions/nonsensitive.html.md
- website/docs/language/functions/sensitive.html.md
A continuation of #28492 with more correct info.
> Updating sensitive/nonsensitive docs with v0.14 specifics.

- website/docs/language/settings/backends/pg.html.md
`CREATE SEQUENCE AS` was added in version 10, #28732
> pg backend requires PostgreSQL 10

- website/docs/language/settings/backends/pg.html.md
> pg requires PostgreSQL 10

- CODEOWNERS
Update paths from package renaming
> update CODEOWNERS paths

- internal/command/e2etest/unmanaged_test.go
- internal/command/meta_providers.go
- main.go
cherry picking commits from https://github.com/hashicorp/terraform/pull/28190
> unmanaged providers support w/ protocol v6 (cherry-pick to v0.15)

- website/docs/language/providers/configuration.html.md
This reverts commit 397494dacaab85fe8b2d9c52f4356978c9c76e8a.
> Revert "mclarify specifying provider versions"

- website/docs/cli/commands/plan.html.md
- website/docs/language/data-sources/index.html.md
- website/docs/language/expressions/conditionals.html.md
- website/docs/language/index.html.md
- website/docs/language/meta-arguments/for_each.html.md
- website/docs/language/modules/sources.html.md
- website/docs/language/providers/configuration.html.md
- website/docs/language/providers/index.html.md
- website/docs/language/providers/requirements.html.md
- website/docs/language/values/outputs.html.md
- website/docs/language/values/variables.html.md
- website/intro/index.html.markdown
This PR makes sure that the most popular docs pages open with explanations that make sense to users coming in from google rather than the docs nav.
> Gloss of top docs pages

- website/docs/language/settings/index.html.md
Add links to new tutorials for managing Terraform versions.
> Add links to terraform versions tutorials

- website/guides/core-workflow.html.md
- website/intro/index.html.markdown
- website/intro/use-cases.html.markdown
- website/intro/vs/boto.html.markdown
- website/intro/vs/chef-puppet.html.markdown
- website/intro/vs/cloudformation.html.markdown
- website/intro/vs/custom.html.markdown
- website/intro/vs/index.html.markdown
**Description**
Updating the page description metadata on Introduction to Terraform pages, as part of this effort to [update all of the doc pages' metadata](https://app.asana.com/0/1128567758154570/1199892904127584/f) on terraform.io.
I also adjusted the copy on the Introduction to Terraform page. In the future, I will do this kind of thing in a separate PR. I tried to make the copy more concise and readable. 
Requested review scope:
Review urgency:
I have:
> Add page metadata

- internal/command/format/diff.go
The logic behind this code took me a while to understand, so I wrote down what I understand to be the reasoning behind how it works. The trickiest part is rendering changing objects as updates. I think the other pieces are fairly common to LCS sequence diff rendering, so I didn't explain those in detail.
If my understanding is wrong, now would be a cool time to point that out! 😎
> Add comments explaining how ctySequenceDiff works

- website/docs/cli/commands/output.html.md
- website/docs/cli/config/config-file.html.md
- website/docs/internals/json-format.html.md
- website/docs/language/functions/fileset.html.md
grabbed a few very small documentation issues!
> various docs updates

- internal/backend/remote-state/pg/backend.go
- internal/backend/remote-state/pg/backend_test.go
- website/docs/language/settings/backends/pg.html.md
> Backport of #29157

- internal/terraform/context_apply2_test.go
- internal/terraform/context_plan_test.go
- internal/terraform/node_resource_abstract_instance.go
- internal/terraform/reduce_plan_test.go
> v1.0 backport of #29193

- README.md
<http://www.terraform.io/intro> and <https://www.terraform.io> are being redirected to HTTPS already, but this way skipping the redirect and making it a bit more secure 0:-)
> HTTP => HTTPS for two links in README.md

- website/docs/language/providers/configuration.html.md
Typo under Provider Configuration
> Update configuration.html.md (typo)

- website/docs/cli/install/apt.html.md
As discussed with Laura, submitting this PR.
> Conciseness and fixed some typos in apt.html.md

- website/docs/language/expressions/references.html.md
Closes #28881 by @abidmunirmalik
> terraform-workspace should be terraform.workspace

- internal/command/format/object_id.go
- internal/command/format/object_id_test.go
> unmark object ID or Name for formatting

- .circleci/config.yml
Ensure that go.mod and go.sum are correct
> run go mod tidy in CI

- internal/plans/objchange/objchange.go
- internal/plans/objchange/objchange_test.go
Null NestingSingle attributes were not being handled in ProposedNew.
Fixes #29388
> handle null NestingSingle values

- website/docs/cli/commands/refresh.html.md
The word 'the' is repeated in some lines, so I propose to remove them and get a better understanding of the text.
> Remove repeated word 'the' in some lines.

- internal/command/add.go
- internal/command/add_test.go
> command: Fix stale lock after running add

- website/docs/language/settings/backends/pg.html.md
the syntax is incorrect in postgres documentation for remote state
> fix syntax

- website/docs/configuration/expressions.html.md
Just correction of the link to operators.html.
> Update expressions.html link to operators.html

- internal/backend/unparsed_value_test.go
- internal/configs/configschema/decoder_spec.go
- internal/configs/configschema/implied_type.go
- internal/configs/configschema/implied_type_test.go
- internal/configs/experiments.go
- internal/configs/module_merge.go
- internal/configs/module_merge_test.go
- internal/configs/named_values.go
- internal/plans/objchange/objchange_test.go
- internal/terraform/evaluate.go
- internal/terraform/evaluate_test.go
- internal/terraform/node_module_variable.go
- internal/terraform/node_module_variable_test.go
- internal/terraform/node_root_variable_test.go
- internal/terraform/variables.go
Manual v1.0 backport of #29559
> v1.0 backport 29559

- internal/terraform/context_plan.go
- internal/terraform/context_plan2_test.go
Because `moved` blocks produce changes that span across more than one resource instance address at the same time, we need to take extra care with them during planning.
The `-target` option allows for restricting Terraform's attention only to a subset of resources when planning, as an escape hatch to recover from bugs and mistakes.
However, we need to avoid any situation where only one "side" of a move would be considered in a particular plan, because that'd create a new situation that would be otherwise unreachable and would be difficult to recover from.
As a compromise then, we'll reject an attempt to create a targeted plan if the plan involves resolving a pending move and if the source address of that move is not included in the targets.
Our error message offers the user two possible …
> core: Fail if a moved resource instance is excluded by -target

- internal/terraform/evaluate.go
A very quick typo I randomly stumbled upon, which hopefully many don't see at this point anyway! :D
> Correct terraform.env deprecation message typo

- internal/refactoring/move_execute.go
- internal/refactoring/move_execute_test.go
When checking dependencies between move statements, we need to check all combinations of `To` and `From` addresses. There are 8 possible combinations to assess when comparing move statements. The list of combinations is shown here, along with the statement which must be executed first when one address is nested within another:
```
A.From  IsNestedWithin  B.From => A
A.To    IsNestedWithin  B.From => A
A.From  IsNestedWithin  B.To   => B
A.To    IsNestedWithin  B.To   => B
B.From  IsNestedWithin  A.From => B
B.To    IsNestedWithin  A.From => B
B.From  IsNestedWithin  A.To   => A
B.To    IsNestedWithin  A.To   => A
```
When building the graph we are only interested in checking if `A` should depend on `B` to decide if we need to insert an edge, so we can reduce the above to only the …
> refactoring: exhaustive NestedWithin checks

- go.mod
- go.sum
- internal/command/command_test.go
- internal/command/get.go
- internal/command/get_test.go
- internal/command/init.go
- internal/command/init_test.go
- internal/command/meta_config.go
- internal/command/test.go
- internal/command/testdata/init-registry-module/main.tf
- internal/getmodules/getter.go
- internal/getmodules/installer.go
- internal/initwd/from_module.go
- internal/initwd/from_module_test.go
- internal/initwd/module_install.go
- internal/initwd/module_install_test.go
- internal/initwd/testing.go
- internal/refactoring/move_validate_test.go
- internal/registry/client.go
- internal/registry/client_test.go
- internal/terraform/terraform_test.go
> Backport of command: make module installation interruptible 

- internal/command/meta_backend.go
Manual backport of https://github.com/hashicorp/terraform/pull/29967
> v1.1 backport of #29967

- internal/command/meta_backend_migrate.go
When migrating from an explicit local backend to Terraform Cloud, we ask
if you want to migrate the state. If there is no state to migrate we
should not ask if they want to migrate the emptyness.
> Cloud: Do not ask to migrate empty default workspace

- website/docs/language/settings/backends/index.html.md
- website/docs/language/state/workspaces.html.md
Update broken links from the recent 1.1 docs PRs.
> Update broken links

- internal/command/meta_backend.go
Closes #30129
A regression introduced in d72a413ef833d4882fcb15d7436fba4a35d53741 (https://github.com/hashicorp/terraform/pull/29945)
The comment explains, but TLDR: The remote backend actually *depended* on being able to write it's backend state even though an 'error' occurred (no workspaces). This is expected behavior for the remote backend: 
With the improvements made in the changes mentioned above, an error now means that the backend config should _not_ be written to disk......except in this particular situation, sadly.
---
There are no tests for this, I know; we don't really have any sort of test harness for initializing this backend (all backend tests like this just use the local backend).
> command/meta_backend: Allow the remote backend to have no workspaces [again]

- internal/logging/panic.go
Because multiple goroutines may panic concurrently, we need a mutex to serialize the output. Emulating the runtime's own lock in this situation we also only want the first goroutine panic output, which is done vie a global mutex taken by the first panic handler to be triggered.
> Cleanup panic output

- Makefile
- website/README.md
This PR updates the `make website` workflow to account for the recent MDX/Next.js migration.
> Update make website workflow

- website/data/cli-nav-data.json
- website/data/configuration-nav-data.json
- website/data/guides-nav-data.json
- website/data/internals-nav-data.json
- website/data/intro-nav-data.json
- website/data/language-nav-data.json
This PR copies the Terraform core specific navigation files from `terraform-website` to this repo. This enables docs authors to adjust sidebar navigation within the same PR as their docs changes.
> Store website nav files (stable-website)

- Makefile
- website/README.md
This PR updates the `make website` workflow to account for the recent MDX/Next.js migration.
> Update make website workflow (stable-website)

- website/data/cli-nav-data.json
- website/data/configuration-nav-data.json
- website/data/guides-nav-data.json
- website/data/internals-nav-data.json
- website/data/intro-nav-data.json
- website/data/language-nav-data.json
This PR copies the Terraform core specific navigation files from `terraform-website` to this repo. This enables docs authors to adjust sidebar navigation within the same PR as their docs changes.
> Store website nav files (main)

- website/docs/language/values/variables.mdx
Remove extraneous word "from" in "...use a sensitive value from as part of an..."
> Update variables.mdx to fix typo

- go.mod
- go.sum
> Update aws-sdk-go dependency to support new region (Jakarta)

- website/intro/index.mdx
Oops :-) References them incorrectly and now they don't show up.
> fix image references on intro page

- internal/terraform/node_resource_plan_instance.go
Fixes a bug discovered while testing #30401, which could lead to a "Missing pending object in plan" error when concurrently planning multiple resource instances.
> core: Fix plan write/state write ordering bug

- website/intro/index.mdx
- website/intro/use-cases.mdx
Some final polish on the new intro docs :-)
> Fixing some final typos and nits

- website/docs/language/meta-arguments/depends_on.mdx
> delete comma from single entry list

- go.mod
- go.sum
- internal/cloud/backend_apply_test.go
Backport of #30126 and #29903
Closes #30530
> [backport] update go-tfe to v0.21.0

- CHANGELOG.md
Modifying the changelog to mention this new integration! 💅
> Add run tasks integration to the list of new features for 1.2

- internal/terraform/context_plan2_test.go
- internal/terraform/eval_conditions.go
- internal/terraform/eval_variable.go
- internal/terraform/eval_variable_test.go
Two related fixes in this PR:
- Preconditions and postconditions which refer to sensitive values in the `condition` expression would crash upon evaluation. We need to unmark the boolean condition result before checking if it's true, just like we do in the variable validation code.
- Variable validations, preconditions, and postconditions which refer to sensitive values in the `error_message` expression would also crash upon evaluation. In this case we must refuse to display the sensitive value, and we also generate an additional diagnostic explaining why and how to fix the problem.
(Targeting the branch from #30658 to avoid merge conflicts with the diagnostic severity changes in that PR.)
With this configuration, a failing variable validation will now display two error diagnostics: …
> core: Fix crashes when condition block expressions refer to sensitive values

- internal/terraform/transform_transitive_reduction.go
Remove extra word and add link to Wikipedia article
> Update comment for this transformer

- internal/cloud/backend_test.go
This test resolves an issue where certain variables were not being unset causing "leaks" into other test
cases and therefore resulting in failures. 
**The reason**: when we `defer` unsetting the variable, it was not initially scoped to the individual test case but the test overall.
**The solution**: Each test case is now scoped with `t.Run()` and any deferred methods can properly execute when the case exits. In this instance however, we are using `t.Cleanup()` rather than `defer`.
The culprit tests: `TestCloud_configWithEnvVars()` and `TestCloud_PrepareConfigWithEnvVars()`.
```sh
go test ./internal/cloud -run TestCloud_configWithEnvVars -count 20
go test ./internal/cloud -run TestCloud_PrepareConfigWithEnvVars() -count 20
```
> Fix a flaky test manipulating environment variables

- internal/command/views/plan.go
- internal/command/views/plan_test.go
The initial rough implementation contained a bug where it would
incorrectly return a NilVal in some cases.
Improve the heuristics here to insert null values more precisely when
parent objects change to or from null. We also check for dynamic types
changing, in which case the entire object must be taken when we can't
match the individual attribute values.
This new technique may be able to produce synthetic diffs which are
_too_ accurate for the current diff renderer, by being able to generate
deeply nested changes to display when it was actually an entire parent
object which was added or removed. I don't think this will be something
that we'll see in practice, since "contributing attributes" requires an
actual reference, which means that they can't refer to a deeply nested
attribute …
> improve the contributing attributes filter

- website/vercel.json
- related: https://github.com/hashicorp/terraform-cdk/pull/1611
> Add Vercel config to silence the comments on PRs, which is what we do across our other product repositories.
> chore: vercel config

- CHANGELOG.md
- internal/cloud/backend.go
- internal/cloud/backend_test.go
- internal/cloud/e2e/env_variables_test.go
- website/docs/cli/cloud/settings.mdx
Renamed `TF_ORGANIZATION` => `TF_CLOUD_ORGANIZATION`
Renamed `TF_HOSTNAME` => `TF_CLOUD_HOSTNAME`
> Rename cloud env vars to use `TF_CLOUD` prefix

- go.mod
- go.sum
> Bump mitchellh/cli from 1.1.2 to 1.1.3

- website/docs/language/functions/type.mdx
> chore: Typo fix

- website/docs/language/expressions/custom-conditions.mdx
This PR adds a link to the new learn tutorial related to custom conditions! This should help users who want to take a hands-on learning approach.
> Add learn tutorial link

- website/docs/language/resources/provisioners/local-exec.mdx
# Issue
https://github.com/hashicorp/terraform/issues/30953#issue-1218566474
> The documentation regarding local-exec lacks documentation regarding resource destruction.
I added a little bit about the destruction option for  local-exec because there was no mention about it.
> `local-exec` documentation lacks on-destroy documentation

- website/docs/language/settings/backends/artifactory.mdx
- website/docs/language/settings/backends/etcd.mdx
- website/docs/language/settings/backends/etcdv3.mdx
- website/docs/language/settings/backends/manta.mdx
- website/docs/language/settings/backends/swift.mdx
Add notices about the backend deprecations to the documentation.
> add deprecation notices to backends

- website/docs/language/state/remote-state-data.mdx
This is related to the following PR [#31458](https://github.com/hashicorp/terraform/pull/31458) to update the important section in the "update-important-section" branch.
> Update the important section to be more concise

- website/README.md
Changing the Deploy heading to an "ing" to match the others!
> Tiny README heading fix

- docs/destroying.md
_Behaviour_ noun is standard in British English.
> doc: use american english

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Adding a few quick fixes after reviewing the issue forms on the live site.
> Fixing placeholder values, adding usage note to bottom of the form.

- website/docs/language/expressions/custom-conditions.mdx
> docs: Fix condition example

- website/docs/cli/index.mdx
- website/docs/internals/index.mdx
- website/docs/language/index.mdx
Change the page frontmatter so to be a bit more concise :-)
> Update frontmatter for devdot

- website/data/internals-nav-data.json
Fix a nit found in the devdot VQA (thank you to design for the good suggestion!)
> Add internals overview page to navigation

- version/version.go
I thought this was an automated step after a minor release, but I guess it's manual.
> Update main branch version to 1.4.0

- .github/pull_request_template.md
This is intended to add some structure to pull request descriptions, and encourage peer review of changelog entries before merging a PR.
> Add initial pull request template

- website/docs/language/expressions/custom-conditions.mdx
Add continuous validation callout to preconditions and postconditions docs.
> Add callout to Continuous Validation

- website/docs/intro/index.mdx
This number has grown rapidly. [ref](https://registry.terraform.io)
> Update the # public providers estimate in the Terraform Intro

- website/docs/language/functions/timeadd.mdx
- website/docs/language/functions/timecmp.mdx
Fix Broken links identified in the latest devdot analysis
> fix broken links

- website/docs/language/state/import.mdx
> Grammar and syntax fixes in import.mdx

- website/docs/cli/commands/index.mdx
- website/docs/cli/commands/validate.mdx
- website/docs/cli/import/importability.mdx
- website/docs/cli/import/index.mdx
- website/docs/cli/install/apt.mdx
- website/docs/cli/install/yum.mdx
- website/docs/cli/plugins/index.mdx
- website/docs/cli/plugins/signing.mdx
- website/docs/internals/credentials-helpers.mdx
- website/docs/internals/json-format.mdx
- website/docs/internals/login-protocol.mdx
- website/docs/internals/machine-readable-ui.mdx
- website/docs/internals/module-registry-protocol.mdx
- website/docs/internals/provider-network-mirror-protocol.mdx
- website/docs/internals/provider-registry-protocol.mdx
- website/docs/language/data-sources/index.mdx
- website/docs/language/expressions/for.mdx
- website/docs/language/expressions/type-constraints.mdx
- website/docs/language/meta-arguments/lifecycle.mdx
- website/docs/language/modules/syntax.mdx
- website/docs/language/modules/testing-experiment.mdx
- website/docs/language/providers/configuration.mdx
- website/docs/language/providers/requirements.mdx
- website/docs/language/resources/provisioners/syntax.mdx
- website/docs/language/settings/backends/remote.mdx
Remove future-facing language from docs
> Remove future-facing language from docs (WIP)

- internal/command/unlock.go
Signed-off-by: Conor Evans <coevans@tcd.ie>
`may be still be` -> `may still be`
> fix(unlock): amend force-unlock description

- internal/backend/local/backend_local.go
For example openstack admin password
> Don't show symbols while input if variable marked as sensitive

- internal/command/format/diff.go
- internal/command/jsonformat/change/block.go
- internal/command/jsonformat/change/change.go
- internal/command/jsonformat/change/list.go
- internal/command/jsonformat/change/map.go
- internal/command/jsonformat/change/object.go
- internal/command/jsonformat/change/set.go
- internal/command/jsonformat/differ/attribute.go
- internal/command/jsonformat/differ/block.go
- internal/command/jsonformat/differ/list.go
- internal/command/jsonformat/differ/map.go
- internal/command/jsonformat/differ/object.go
- internal/command/jsonformat/differ/output.go
- internal/command/jsonformat/differ/set.go
- internal/command/jsonformat/differ/types.go
Address the 3 simplest comments from the previous round of PRs for the structured renderer:
- https://github.com/hashicorp/terraform/pull/32391#discussion_r1063682150
- https://github.com/hashicorp/terraform/pull/32391#discussion_r1063683195
- https://github.com/hashicorp/terraform/pull/32426#discussion_r1063784892
> Structured Plan Renderer: Address comments raised in previous PRs

- website/docs/cli/import/importability.mdx
removed double negation in importability documentation
> removed double negation

- website/docs/language/functions/templatefile.mdx
> Fix Examples ip_addrs

- internal/plans/objchange/objchange.go
Unify the ProposedNew paths for Blocks and Objects. Break out the individual case blocks into functions, then use a common interface to dispatch the object creation to the correct function based on schema type. I did not want to extend changes outside of the package at all, so it's not perfect, but it cuts the code in half, and prevents the block and object behavior from diverging again.
> refactor ProposedNew

- internal/backend/local/backend_local.go
- internal/states/remote/state.go
- internal/states/remote/state_test.go
> Manual v1.3 backport of 32614

- .github/workflows/equivalence-test.yml
The new version of equivalence tests will include the human rendered state in the outputs.
> Use the latest equivalence testing version when executing equivalence tests

- internal/modsdir/manifest.go
Fixes #26863
1.4.x
- make stable `modules.json` content so that it does not change with each update
> sort modules.json for stable order

- website/docs/language/upgrade-guides/index.mdx
Minor modification to the upgrade guide.
> 1.4 upgrade change

- website/docs/language/providers/index.mdx
New PR created under 1.4 instead of main.
Doc update.
> PR under 1.4 this time.

- internal/terraform/context_apply_test.go
This test was previously not taking into account the fact that the "Stopping" hook gets sent in the goroutine that calls `ctx.Stop`, whereas all of the others get called from inside `ctx.Apply`, and so there are no ordering guarantees for that event in relation to the others.
We now handle the stopping event as a special case that is allowed to appear anywhere in the sequence as long as it appears. The other events are still strongly ordered because their ordering is important for correctness of Terraform Core's own behavior.
As some extra insurance we also now check whether the provider's `ApplyResourceChange` and `Stop` functions both ran and reached a suitable point of execution related to the stop request, which help to ensure not only that something called `Stop` but that Terraform …
> core: Fix test flake in TestContext2Apply_stop

- go.mod
- go.sum
- internal/lang/funcs/collection_test.go
Like #32860 but targeting main.
1.5.x
> go.mod: Revert cty minor version v1.13 upgrade

- BUGPROCESS.md
non-material / trivial grammar fix
> trivial grammar fix in BUGPROCESS.md

- internal/terraform/transform_check.go
This is a small optimisation, but there is no need to search through all the nodes in the graph for a data resource when we know we have no data resource.
> checks: don't iterate through all the nodes when there is nothing to search for

- website/data/language-nav-data.json
Fixes #33069 - lingering documentation issue from that pull request.
1.4.x
n/a
-  Should allow CI to pass and docs to be generated for this new function.
> Adding additional entry necessary to generate docs.

- website/docs/language/providers/index.mdx
Link to plugin-framework tutorial updated.
> Link to plugin-framework tutorial

- internal/terraform/context_plan2_test.go
- internal/terraform/node_resource_plan_instance.go
The imported resource was being stored in the wrong state, and only ended up in the refresh state because ReadResource was being called a second time in the normal refresh path.
Make sure to only refresh the imported resource once. This is still done separately within importState so that we can handle the error slightly differently to let the user know if an imported instance does not exist.
> Import: only refresh an imported state once

- website/docs/language/functions/setsubtract.mdx
Fixes #31909
1.4.x
Update setsubtract examples to provide type annotations
> update setsubtract examples to include toset notation

- website/docs/language/syntax/style.mdx
> Change separating to grouping

- website/docs/cli/state/resource-addressing.mdx
An almost ridiculous contribution. Yet, it made things so much clearer for me, when I realized I could frame it with this finish.
(not even worth a CHANGELOG entry, so I've removed that here)
> tiny update to Resource Addressing: "value4"

- CHANGELOG.md
Changelog entry for plannable import in 1.5 beta.
> Changelog: plannable import

- internal/configs/module.go
Fixes #33220
1.5.x
- Fix an error message for import block with moved block
> Fix an error message for import block with moved block

- go.mod
- go.sum
cty: IndexStep.Apply will no longer panic if given a marked collection to traverse through.
Fixes #32956
> udpate go-cty

- internal/plans/objchange/plan_valid.go
- internal/plans/objchange/plan_valid_test.go
Update the planned set validation to use refinements
> validate planned set sizes using refinements

- go.sum
Quick checks [is failing on main](https://github.com/hashicorp/terraform/actions/runs/5348383486) because `go mod tidy` needs to be run
> [Chore] go mod tidy

- website/docs/language/functions/tostring.mdx
Per https://github.com/hashicorp/terraform/issues/33603, updating the documentation to accurately reflect the current implementation.
> Update tostring.mdx for null value conversion

- README.md
> Update licence link in README to BSL

- website/docs/intro/terraform-editions.mdx
- website/docs/intro/vs/custom.mdx
> Update website to reflect new license

- internal/terraform/test_context.go
- internal/terraform/test_context_test.go
> Add support for sensitive values in test assertions

- .github/workflows/build-terraform-cli.yml
- website/docs/internals/archiving.mdx
> Update file name

- .release/ci.hcl
> Enable Iron Bank updates

- website/docs/internals/debugging.mdx
> Update debugging.mdx to capitalize Terraform

- website/docs/language/import/index.mdx
I don't think this needs a lot of description, as this works pretty much how you'd expect it to work, except perhaps with unknown values.
> website: update docs for import block dynamic ids

- internal/plugin/grpc_provider.go
- internal/plugin/grpc_provider_test.go
- internal/plugin6/grpc_provider.go
- internal/plugin6/grpc_provider_test.go
> v1.6 backport of #33807

- website/docs/language/expressions/types.mdx
> v1.6 backport of 33821

- website/docs/language/expressions/types.mdx
> v1.5 backport of 33821

- internal/backend/remote-state/s3/backend.go
Adds logging for `aws-sdk-go-base`
1.6.0
-  backend/s3: Adds logging for AWS authentication
> backend/s3: Adds logging for `aws-sdk-go-base`

- internal/backend/remote-state/s3/backend.go
Adds logging for `aws-sdk-go-base`
1.6.0
> Adds logging for `aws-sdk-go-base`

- internal/backend/remote-state/s3/backend_state.go
- internal/backend/remote-state/s3/client.go
Adds context information to API error messages
Fixes #29154
Fixes #29008
1.6.0
> backend/s3: Improves bare error messages from API responses

- internal/addrs/parse_ref.go
This is something I should have a while back but I managed to forget. In the future we may want to introduce functions that reference metadata about the plan and state (eg. how many changes total, did the plan error, how many resources in the state, does a conditional resource exist, etc) and I want to preemptively reserver the `state` and `plan` keywords in case we need them.
Again, I should have done this long ago but just assumed I already had. Want to get this in before the main release at which point we can never do this in line with compatibility guidelines.
> Reserve state and plan keywords in test files

- .github/CONTRIBUTING.md
Updating `CONTRIBUTING.md` to better reflect current practices and give better guidance to new contributors.
> Small rewrite of Contrib to better reflect current practices.

- website/docs/cli/commands/test.mdx
> Fix typo in login link from test command doc page

- CHANGELOG.md
> Fix typo in the 1.6 changelog

- CHANGELOG.md
Alas, I don't have the YOLO powers. 🥲
> Update CHANGELOG for 34012

- website/docs/cli/commands/test.mdx
> Fix some typos in test cleanup doc 

- website/docs/language/tests/index.mdx
> Fix typo on testing docs page

- website/docs/language/functions/sum.mdx
Explain edge case with empty list
Fixes #
1.5.x
-
> Update sum.mdx docs

- website/docs/cli/commands/test.mdx
- website/docs/language/values/variables.mdx
> docs: add explicit instruction for windows filepaths

- internal/moduletest/mocking/fill.go
- internal/moduletest/mocking/generate.go
This PR fixes the flaky tests in moduletest/mocking by making the iteration order of maps and objects deterministic by sorting the map keys and object attribute names alphabetically before iterating through them.
```
~/hashicorp/terraform (liamcervante/flakes/moduletest) > go test ./internal/moduletest/mocking -count 100
ok      github.com/hashicorp/terraform/internal/moduletest/mocking      0.540s
```
> Fix flaky tests in moduletest/mocking by making iterations deterministic

- website/docs/language/resources/provisioners/syntax.mdx
[Small request from Oracle to update the links for the `oci_core_instance` provider.](https://hashicorp.slack.com/archives/C03BX0MJD27/p1700061298386359)
> Update oci_core_instance links

- internal/command/test_test.go
> Fix the compile error in command/test_test.go

- internal/backend/local/test.go
- internal/command/test_test.go
- internal/command/testdata/test/skip_destroy_on_empty/main.tf
- internal/command/testdata/test/skip_destroy_on_empty/main.tftest.hcl
- internal/command/testdata/test/skip_destroy_on_empty/verify/main.tf
Backport of https://github.com/hashicorp/terraform/pull/34331
> backport: terraform test: skip destroy step for empty run blocks

- CHANGELOG.md
> Update changelog for #34352

- go.mod
- go.sum
> deps: bump go-slug to v0.13.3

- website/docs/language/tests/mocking.mdx
Fixes to the test mock documentation
Fixes #
1.7.0
> Test mocks docs fixes

- website/docs/language/tests/mocking.mdx
> Backport "Test mocks docs fixes" to v1.7

- internal/stacks/tfstackdata1/convert.go
- internal/stacks/tfstackdata1/convert_test.go
This is just fixing a fixme that I postponed earlier in #34483.
> tfstackdata1: DynamicValueFromTFStackData1 decodes sensitive marks

- internal/stacks/stackruntime/internal/stackeval/component_instance.go
This makes the built-in `remote-exec` and `file` provisioners available for use in the modules that implement stack components. These are both relatively easy and low-risk to include because they are builtins and don't require anything from outside of Terraform itself.
For now this intentionally excludes `local-exec` because we'll want to think about what constraints we want to put on it, if any, to help ensure we can meet the goal of stack configurations being portable between different execution environments without significant modification, and our current stacks execution environment doesn't guarantee the availability of any external software _at all_.
The motivation for adding this _now_ is just to give some better feedback when someone uses a module using one of these provisioners, …
> stackeval: Make some provisioners available to stack components

- website/docs/language/settings/backends/azurerm.mdx
1.5.x
Minor fixups to azurerm backend documentation
- Markdown table bad columns break render
- Punctuation
- Styling (remove unnecessary bold text)
> docs: azurerm backend doc fixups

- website/docs/cli/commands/providers/lock.mdx
adding the CLI help output to the docs.
1.8.x
> document `-enable-plugin-cache` flag

- internal/stacks/stackruntime/internal/stackeval/component.go
- internal/stacks/stackruntime/internal/stackeval/component_test.go
- internal/stacks/stackruntime/internal/stackeval/for_each.go
- internal/stacks/stackruntime/internal/stackeval/for_each_test.go
- internal/stacks/stackruntime/internal/stackeval/provider.go
- internal/stacks/stackruntime/internal/stackeval/provider_test.go
- internal/stacks/stackruntime/internal/stackeval/stack_call.go
- internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
- internal/stacks/stackruntime/internal/stackeval/stack_call_test.go
This PR aims to bring the for_each handling in the stacks runtime closer to the core module runtime one.
> stacks: make component for_each more robust

- internal/terraform/context_plan2_test.go
- internal/terraform/node_resource_abstract_instance.go
Following up from #34567, it turns out that data source marks handling was also lacking, but not checked by any existing tests. 
Here we ensure that schema marks are always added when reading a data source. We also add marks to the values used when returning only the config value for deferred reads or check block errors so that marks are always propagated consistently.
> Insert schema marks when reading data sources

- internal/backend/local/backend_plan_test.go
- internal/backend/remote-state/s3/backend_test.go
- internal/checks/state.go
- internal/command/e2etest/automation_test.go
- internal/command/jsonplan/plan.go
- internal/command/meta_backend_migrate.go
- internal/getproviders/package_authentication.go
- internal/registry/test/mock_registry.go
- website/README.md
- website/docs/cli/commands/providers/lock.mdx
> remove repetitive words

- website/docs/language/settings/backends/s3.mdx
> double quote typo

- website/docs/language/style.mdx
1.8.x
This PR is aimed at fixing the validation condition specified in the style guide document. When using the [example](https://github.com/hashicorp/terraform/blob/main/website/docs/language/style.mdx#variables) from the style guide, these are the errors that are thrown:
> Error: Invalid reference in variable validation
on variables.tf line 6, in variable "web_instance_count":
6:     condition     = var.aws_instance_count > 1
The condition for variable "web_instance_count" can only refer to the variable itself, using var.web_instance_count.
> Error: Invalid variable validation condition
on variables.tf line 6, in variable "web_instance_count":
6:     condition     = var.aws_instance_count > 1
The condition for variable "web_instance_count" must refer to var.web_instance_count in order …
> Fix validation condition

- internal/terraform/node_resource_import.go
During `terraform import` there is no planfile where we could signal the deferral, therefore we should return diagnostics
1.8.x
-  stacks: return diagnostics if read during terraform import is deferred
> stacks: return diagnostics if read during terraform import is deferred

- website/docs/language/syntax/configuration.mdx
> Backport Config syntax docs update

- internal/backend/local/test.go
- internal/command/test_test.go
- internal/command/testdata/test/invalid-cleanup-warnings/main.tf
- internal/command/testdata/test/invalid-cleanup-warnings/main.tftest.hcl
> Backport of remove invalid warning during cleanup phase 

- internal/command/views/json/diagnostic.go
- internal/initwd/module_install.go
- internal/initwd/module_install_test.go
- internal/registry/response/module_versions.go
- internal/tfdiags/diagnostic.go
- website/docs/cli/commands/validate.mdx
Reverts hashicorp/terraform#35231
> Revert "Add Warning for Deprecated Modules in `Init` (Second Revision)"

- .github/workflows/main.yml
Updating to see if it resolves failed backport issues
> update backport-assistant to 0.4.3

- internal/terraform/context_apply_deferred_test.go
This is adding two new test cases around modules to the already existing `resource_in_module_for_each` one:
- `module_deferred_for_each_value` has an unknown value as the `for_each` value of a module
- `module_inner_resource_instance_deferred` has a resource within a module that is being deferred by the provider
Both worked just fine without further changes 👍 
[External Issue](https://hashicorp.atlassian.net/browse/TF-13952)
> stacks: deferred action tests for modules

- .github/ISSUE_TEMPLATE/bug_report.yml
Long-awaited public channel for registry bug reports has arrived! Huzzah!
> Adding new instructions for Terraform Registry bug reports

- internal/terraform/context_import_test.go
- internal/terraform/transform_config.go
Manual backport of #35330
---
When grouping imports by module for validation, imports with no associated module were left out and would silently fail. Change the config transformer to check all import targets together to make sure they are all valid within a configuration.
> backport #35330: Missing import target in module should error

- website/docs/cli/import/usage.mdx
- website/docs/internals/credentials-helpers.mdx
- website/docs/intro/core-workflow.mdx
- website/docs/language/expressions/conditionals.mdx
- website/docs/language/expressions/for.mdx
- website/docs/language/expressions/splat.mdx
- website/docs/language/expressions/type-constraints.mdx
- website/docs/language/functions/can.mdx
- website/docs/language/functions/list.mdx
- website/docs/language/functions/lookup.mdx
- website/docs/language/functions/map.mdx
- website/docs/language/functions/sensitive.mdx
- website/docs/language/functions/templatefile.mdx
- website/docs/language/import/generating-configuration.mdx
- website/docs/language/resources/syntax.mdx
- website/docs/language/settings/backends/oss.mdx
- website/docs/language/settings/backends/remote.mdx
- website/docs/language/style.mdx
- website/docs/language/tests/index.mdx
- website/docs/language/values/locals.mdx
This is a backport of https://github.com/hashicorp/terraform/pull/35354 to v1.9
> backport/1.9: Enable highlighting for HCL snippets

- website/data/language-nav-data.json
Update the side nav for the 1.8 upgrade guide to match the title of the doc
Closes #35359
> v1.8 upgrade guide side nav fix

- website/data/language-nav-data.json
Update the side nav for the 1.9 upgrade guide to match the title of the doc
> Update the nav for 1.9 upgrade guide

- website/data/language-nav-data.json
> Backport - Update the nav for 1.9 upgrade guide

- internal/moduletest/eval_context.go
This PR is a cherry pick of #35408 into the correct branch.
> skip check evaluation when context is not prepared successfully

- internal/moduletest/eval_context.go
Manual backport of https://github.com/hashicorp/terraform/pull/35411
> Manual backport of skip check evaluation when context is not prepared successfully

- internal/terraform/context_plan2_test.go
- internal/terraform/context_plan_import_test.go
- internal/terraform/eval_import.go
- internal/terraform/node_resource_plan.go
- internal/terraform/validate_selfref.go
- internal/terraform/validate_selfref_test.go
> backport of fix missing validation for count and for-each meta-arguments

- CHANGELOG.md
Closes https://github.com/hashicorp/terraform/issues/35445
> Fix CHANGELOG (v1.9)

- CHANGELOG.md
- internal/terraform/context_apply2_test.go
- internal/terraform/node_resource_destroy_deposed.go
- internal/terraform/node_resource_plan_orphan.go
> Manual backport of #35458 core: do not refresh when forgetting instances

- website/docs/cli/commands/destroy.mdx
I needed this, it's not clear in the docs currently; I had to find it from an old discussion.
> mention -target in destroy docs

- internal/command/init_test.go
- internal/command/testdata/init-with-duplicates/primary.tf
- internal/command/testdata/init-with-duplicates/secondary.tf
- internal/command/testdata/init-with-overrides-and-duplicates/primary.tf
- internal/command/testdata/init-with-overrides-and-duplicates/secondary.tf
- internal/command/testdata/init-with-overrides-and-duplicates/secondary_override.tf
- internal/configs/parser_config.go
> backport of init: fix invalid + duplicate required provider blocks crashing

- internal/checks/state_report.go
- internal/terraform/graph.go
- internal/terraform/node_module_variable.go
Manual backport of https://github.com/hashicorp/terraform/pull/35535
> backport of trace: add more logging around variable validations

- internal/stacks/stackruntime/apply_test.go
- internal/stacks/stackruntime/internal/stackeval/component_instance.go
This PR removes the validation that Stacks performs to make sure the input variables to components don't change between plan and apply.
Based on the comment [here](https://github.com/hashicorp/terraform/pull/35560#issuecomment-2286295525) - it turns out that values can totally change between the plan and apply phases due to the behaviour of the legacy SDK. This was breaking workflows for users, as Stacks was detecting these changes and refusing to process components as a result.
This is an alternative to #35560. Note, that Stacks still validates the inputs for the overall stack haven't changed, and Terraform internally still validates that resources are consistent with what was planned. Terraform has more information, and so can skip validations around legacy providers (this was how this …
> stacks: don't validate input variables during the apply phase

- website/docs/language/functions/contains.mdx
Fixes #35414
Martin already did adequate analysis in the linked issue and I used his suggestion verbatim
1.10.0
n/a
> docs: explicitly mention equality in contains docs

- website/docs/language/functions/timeadd.mdx
Follow guidance in [Google template](https://docs.google.com/document/d/1t2z3tFo1dJBac5M9gjNoL5Hjdu7VjenYOwUDowXErqU/edit?usp=sharing)
[Deploy preview](https://terraform-os0kbtq5g-hashicorp.vercel.app//terraform/language/functions/timeadd/)
> DocsDay: Reformat timeadd function 

- website/docs/cli/config/environment-variables.mdx
Fixes #34712
* removes the documentation around `TF_IGNORE`, which was removed as part of https://github.com/hashicorp/go-slug/pull/42.
> docs: remove `TF_IGNORE` documentation

- website/docs/language/functions/abs.mdx
- website/docs/language/functions/filesha1.mdx
- website/docs/language/functions/filesha256.mdx
- website/docs/language/functions/filesha512.mdx
What
Updates the abs, filesha1, filesha256, and filesha512 function documentation.
Why
This document didn't align with our writing standards.
[Deploy preview](https://terraform-git-fork-cjobermaier-abs-function-hashicorp.vercel.app/)
> docs: Update abs, filesha1, filesha256, and filesha512 functions

- website/docs/language/functions/setintersection.mdx
Reformat setintersection page to match the [template](https://docs.google.com/document/d/1t2z3tFo1dJBac5M9gjNoL5Hjdu7VjenYOwUDowXErqU/edit?usp=sharing).
[Deploy preview](https://terraform-ow69sap58-hashicorp.vercel.app/terraform/language/functions/setintersection)
> DocsDay: Reformat setintersection page

- website/docs/language/providers/requirements.mdx
> Fix typo in requirements.mdx

- .vscode/launch.json
This is to enable an easier debugging workflow inside of VS Code. See an example below.
https://github.com/user-attachments/assets/bd5dafbd-2c9a-4281-8020-cd572c1ade3d
> vscode: Add launch configuration for dlv debugger

- internal/backend/local/backend_apply.go
Variables sourced through interactive prompt were ignored when experiment was active.
--- 
I was tempted to write some tests but couldn't find any that involve the UI in this particular context. I also raised https://github.com/hashicorp/terraform/pull/35623 as part of my early attempts at writing some tests but then realised it would not be as easy as I thought.
> backend/local: Allow ephemeral values to be set via prompt during apply

- website/docs/cli/commands/apply.mdx
- website/docs/cli/commands/output.mdx
- website/docs/cli/config/environment-variables.mdx
- website/docs/language/expressions/types.mdx
- website/docs/language/functions/abs.mdx
- website/docs/language/functions/base64gzip.mdx
- website/docs/language/functions/filesha1.mdx
- website/docs/language/functions/filesha256.mdx
- website/docs/language/functions/filesha512.mdx
- website/docs/language/functions/indent.mdx
[These are all PRs from our last Docs day](https://github.com/hashicorp/terraform/issues?q=label%3Aevent%2Fterraform-docs-day+is%3Aclosed). Some folks didn't have the right permissions to make a PR directly and had to make forks—so this PR is for catching all of the stuff that didn't backported day of!
> Manually backporting all of the PRs from Docs Day that were on forks

- internal/terraform/context_apply_test.go
- internal/terraform/context_plan2_test.go
- internal/terraform/node_output.go
- internal/terraform/terraform_test.go
- internal/terraform/transform_orphan_output.go
There are tests attached which demonstrate before/after too but I'm attaching end-user effect below for added convenience of the reviewer.
https://github.com/user-attachments/assets/33d6b063-6175-4f80-8d06-59b27563a0e5
https://github.com/user-attachments/assets/d67c193d-eb23-4dba-bc70-24f6ac403756
> terraform: Ensure ephemeral outputs are removed from state

- internal/stacks/stackplan/planned_change.go
- internal/stacks/stackruntime/apply_destroy_test.go
- internal/stacks/stackruntime/internal/stackeval/input_variable.go
- internal/stacks/stackruntime/internal/stackeval/stack.go
This is a super quick follow up to https://github.com/hashicorp/terraform/pull/35724 that ensures inputs and outputs are properly removed from state during destroy plans.
The input variables are a bit quirky, as we both need to mark them for deletion and preserve their value in the plan. To achieve this we emit two raw events for input variables in this case, one each for this should be removed and here is the value this had during the plan.
> stacks: handle input and output state during delete plans

- website/docs/language/expressions/type-constraints.mdx
> docs: clarify map key quoting and formatting rules

- website/docs/language/stacks/index.mdx
> specify that stacks is hcp

- internal/terraform/context_plan_ephemeral_test.go
> ephemeral: add tests for locals

- website/docs/language/stacks/create/config.mdx
- website/docs/language/stacks/deploy/conditions.mdx
- website/docs/language/stacks/deploy/config.mdx
- website/docs/language/stacks/reference/tfdeploy.mdx
[Following up with stacks feedback from Keran](https://hashicorp.slack.com/archives/C04A1FQ1543/p1729288382128259) and feedback from [Daniel on good `auto_approve` catches](https://hashicorp.slack.com/archives/C04A1FQ1543/p1729079939253919) .
> Small stacks feedback

- website/docs/language/resources/ephemeral.mdx
- website/docs/language/resources/provisioners/connection.mdx
- website/docs/language/resources/provisioners/syntax.mdx
Reference: https://github.com/hashicorp/terraform/pull/35899#pullrequestreview-2399677700
> Ephemeral values in provisioner and connection blocks

- internal/lang/checks.go
- internal/moduletest/eval_context.go
- internal/terraform/eval_conditions.go
> lang: Add `Extra` to avoid duplicate diagnostic in `check` blocks

- internal/terraform/context_plan_ephemeral_test.go
This updates and enables test which tests that the _error message_ of a `check` does _not_ get persisted in the plan if it contains an ephemeral value. This is less drastic solution than the test originally assumed while still satisfying the core promises of ephemerality.
> terraform: Update test for check blocks w/ ephemeral values

- CODEOWNERS
> update codeowners so that each file at least assigns the core team

- .github/pull_request_template.md
> move default release target to 1.11.x

- website/docs/language/stacks/reference/tfstack.mdx
from should be a direct component reference, not a string
> fix incorrect syntax

- internal/backend/remote-state/cos/backend.go
- internal/backend/remote-state/cos/go.mod
- website/docs/language/backend/cos.mdx
> backport to v1.10: Add new auth for tencentcloud cos backend

- .github/actions/equivalence-test/action.yml
- .github/workflows/equivalence-test-update.yml
I think this will make the equivalence tests work once and for all.
> Complete equivalence test implementation

- .github/workflows/checks.yml
This should satisfy the definition of [TF-22390](https://hashicorp.atlassian.net/browse/TF-22390)
[TF-22390]: https://hashicorp.atlassian.net/browse/TF-22390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: Report test coverage

- docs/architecture.md
Fixes:
- Change text to reflect how Backends were changed in: https://github.com/hashicorp/terraform/pull/34818
- Update links to official documentation, either to fix a 404 or avoid the need for a redirect
- Formatting fix
Fixes #
N/A
N/A
> Update architecture.md docs

- CHANGELOG.md
> version: Prepare for 1.10.3 release

- internal/command/modules_test.go
This is to help understand the failures in CI: https://github.com/hashicorp/terraform/actions/runs/12581454453/job/35073933913#step:6:96
> command: Update test to aid debugging of failures

- scripts/changelog.sh
> fix dev release build to set VERSION correctly

- CHANGELOG.md
> add 1.10.4 release to changelog

- website/docs/language/expressions/references.mdx
> Remove typo (duplicated "an") in references.mdx

- .changes/1.10.3.md
- CHANGELOG.md
> add changelog entry for terraform modules -json

- .changes/experiments.md
> Remove all experiments, and EXPERIMENTS section

- .changes/unreleased/ENHANCEMENTS-20250108-113433.yaml
- .changes/unreleased/ENHANCEMENTS-20250116-101633.yaml
- CHANGELOG.md
- Add CHANGELOG entry for #36185.
- Fix dangling sentence in one of the other changelog entries.
> Update v1.11 changelog for additional enhancements

- .copywrite.hcl
> add backported changie entries to ignore list for copywrite letter

- internal/backend/local/test.go
- internal/command/testdata/test/shared_state_parallel/parallel.tftest.hcl
- internal/moduletest/config/config.go
- internal/moduletest/config/config_test.go
- internal/moduletest/graph/eval_context.go
- internal/moduletest/graph/eval_context_test.go
- internal/moduletest/graph/node_test_run.go
- internal/moduletest/graph/test_graph_builder.go
- internal/moduletest/graph/transform_providers.go
- internal/moduletest/hcl/variable_cache.go
> Transform providers

- docs/dependency-upgrades.md
> Typo and case consistensy in dependency-upgrades.md

- website/docs/language/expressions/version-constraints.mdx
I detected a typo while reading the `version-constraints` page. Not a big deal.
Fixes #
1.11.x
> Fix typo version-constraints.mdx

- website/docs/language/tests/index.mdx
Documentation for https://github.com/hashicorp/terraform/pull/36300
1.11.x
> Add docs for TF test parallel execution

- .changes/backported/ENHANCEMENTS-20250211-36471.yaml
- Dockerfile
Fixes https://github.com/hashicorp/terraform/issues/36431
See my rationale for inclusion in https://github.com/hashicorp/terraform/issues/36431#issuecomment-2650861955
1.11.x
> Dockerfile: Install `ca-certificates`

- internal/command/test_test.go
> skip flaky test

- internal/command/test_test.go
We can test the standard error and the standard out separately to stop the flakyness being introduced by merged streams when combining them.
> Fix flaky test in test_test.go

- .github/workflows/build.yml
Backport of https://github.com/hashicorp/terraform/pull/36433
> Update build action to build correct branch

- .github/workflows/build.yml
backport of https://github.com/hashicorp/terraform/pull/36591
> build: always build on successful pushes rather than waiting for unit tests

- website/docs/language/resources/ephemeral/index.mdx
- website/docs/language/resources/ephemeral/reference.mdx
- website/docs/language/resources/ephemeral/write-only.mdx
Feedback on https://github.com/hashicorp/terraform/pull/36605
> Add feedback for write-only changes

- website/docs/language/resources/ephemeral/index.mdx
- website/docs/language/resources/ephemeral/write-only.mdx
The chain goes on! Adding feedback from: https://github.com/hashicorp/terraform/pull/36634
> Add Brian feedback

- website/docs/language/meta-arguments/lifecycle.mdx
Per https://github.com/hashicorp/terraform/pull/36666, this link is more confusing than it is beneficial.
> Remove irrelevant link to github issue

- .changes/v1.11/BUG FIXES-20250310-093153.yaml
> Move changelog entry to v1.11

- .changes/v1.12/BUG FIXES-20250310-093153.yaml
> Remove changelog entry from v1.12

- .changes/v1.12/BUG FIXES-20250310-093153.yaml
> Remove 1.12 changelog entry

- internal/rpcapi/dynrpcserver/stacks.go
- internal/rpcapi/resource_identity.go
- internal/rpcapi/resource_identity_test.go
- internal/rpcapi/stacks.go
- internal/rpcapi/terraform1/stacks/stacks.pb.go
- internal/rpcapi/terraform1/stacks/stacks.proto
- internal/stacks/stackstate/state.go
> TF-23751: Add stacks RPC call for resource identities

- internal/stacks/stackruntime/apply_test.go
I didn't pull from main before merging https://github.com/hashicorp/terraform/pull/36673, and this has caused a compilation error in main due to another change. This fixes everything.
> Fix broken build due to merge conflicts

- internal/stacks/stackruntime/plan_test.go
- internal/stacks/stackruntime/testdata/mainbundle/test/resource-identity/resource-identity.tf
- internal/stacks/stackruntime/testdata/mainbundle/test/resource-identity/resource-identity.tfstack.hcl
- internal/stacks/stackruntime/testing/provider.go
- internal/stacks/stackruntime/testing/resource.go
Fixes [TF-24682](https://hashicorp.atlassian.net/browse/TF-24682)
1.12.x
[TF-24682]: https://hashicorp.atlassian.net/browse/TF-24682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> stacks: test resource identity

- .changes/v1.11/BUG FIXES-20250312-114637.yaml
- internal/backend/remote/backend_common.go
- internal/backend/remote/backend_plan.go
- internal/backend/remote/backend_taskStages.go
- internal/backend/remote/cloud_integration.go
Backporting [this fix](https://github.com/hashicorp/terraform/pull/36655) to 1.11
1.11.3
> Add polling to wait for post plan tasks to complete in remote backend

- internal/backend/local/test.go
- internal/command/test_test.go
- internal/moduletest/graph/manifest.go
> Prevent test run when leftover state data is present

- website/docs/language/moved.mdx
This PR makes minor updates to the format and text for alignment with the language block reference design doc.
> updated some of the boilerplate text

- docs/plugin-protocol/tfplugin5.10.proto
- internal/grpcwrap/provider.go
- internal/plugin/mock_proto/mock.go
- internal/tfplugin5/tfplugin5.pb.go
- internal/tfplugin5/tfplugin5.proto
> Add protocol 5 support in prototype branch

- internal/backend/local/backend_local.go
- internal/backend/local/test.go
- internal/backend/remote-state/kubernetes/client.go
- internal/command/cliconfig/cliconfig.go
- internal/command/format/diagnostic.go
- internal/command/jsonformat/state.go
- internal/command/jsonstate/state.go
- internal/command/junit/junit.go
- internal/command/junit/junit_internal_test.go
- internal/command/meta.go
- internal/configs/config.go
- internal/configs/config_build.go
- internal/configs/configload/loader_snapshot.go
- internal/dag/dot.go
- internal/dag/set.go
- internal/depsfile/locks.go
- internal/depsfile/locks_file.go
- internal/genconfig/generate_config.go
- internal/lang/eval.go
- internal/moduleref/resolver.go
- internal/moduletest/graph/eval_context.go
- internal/plans/planfile/config_snapshot.go
- internal/plans/planfile/tfplan.go
- internal/states/state_deepcopy.go
- internal/states/statefile/version3_upgrade.go
- internal/terraform/transform_ephemeral_resource_close.go
Backport #36818 into go 1.12
Fixes #
1.12.x
> Backport #36818 into go 1.12

- website/data/language-nav-data.json
- website/docs/language/upgrade-guides/index.mdx
> Update guide nav

- internal/command/test_test.go
- internal/command/testdata/test/skip_file_cleanup/main.tftest.hcl
- website/docs/cli/commands/test.mdx
- website/docs/language/tests/index.mdx
> More test documentation

- docs/plugin-protocol/tfplugin5.10.proto
- internal/grpcwrap/provider.go
- internal/plugin/mock_proto/mock.go
- internal/tfplugin5/tfplugin5.pb.go
Reverts https://github.com/hashicorp/terraform/pull/36815 for simplicity during prototyping
> Remove protocol 5 support

- website/docs/language/functions/regex.mdx
> Document `\.` for regex function

- internal/terraform/node_resource_abstract_instance.go
This is required for Stacks, where we use the pre and post diff hooks to emit updates for the TFC UI: https://github.com/hashicorp/terraform/blob/main/internal/stacks/stackruntime/internal/stackeval/terraform_hook.go#L59-L75.
The only other implementation for either of these hooks is in the [countHook](https://github.com/hashicorp/terraform/blob/main/internal/command/views/hook_count.go) implementation. My only conclusion looking at that implementation is that (a) it was wrong before as it wasn't actually counting all the remove operations and (b) this doesn't matter as the `ToAdd`, `ToChange` and `ToRemove` fields aren't actually being used anywhere. I think this PR will make those counts correct should they ever be needed anywhere in the future.
> Call the pre and post diff hooks from destroy plan nodes

- .github/pull_request_template.md
> github: Update PR template with required fields for PCI compliance

- internal/configs/query_file.go
- internal/configs/resource.go
- internal/configs/testdata/query-files/valid/simple/main.tfquery.hcl
> Add include_resource attr to list block

- website/docs/language/checks/index.mdx
> docs: update index.mdx

- internal/terraform/node_resource_apply_instance.go
internal ticket: https://hashicorp.atlassian.net/browse/TF-26334
> deferrals: add source info to deferred-during-apply diagnostic

- internal/command/init_test.go
- internal/command/testdata/init-with-state-store/main.tf
- internal/configs/module.go
- internal/configs/module_test.go
- internal/configs/parser_config.go
- internal/configs/parser_test.go
- internal/configs/state_store.go
- internal/configs/testdata/invalid-modules/conflict-cloud-backend-statestore/main.tf
- internal/configs/testdata/invalid-modules/conflict-cloud-statestore-separate-files/cloud.tf
- internal/configs/testdata/invalid-modules/conflict-cloud-statestore-separate-files/state-store.tf
- internal/configs/testdata/invalid-modules/conflict-cloud-statestore/main.tf
- internal/configs/testdata/invalid-modules/conflict-statestore-backend-separate-files/backend.tf
- internal/configs/testdata/invalid-modules/conflict-statestore-backend-separate-files/state-store.tf
- internal/configs/testdata/invalid-modules/conflict-statestore-backend/main.tf
- internal/configs/testdata/invalid-modules/multiple-state-store/a.tf
- internal/configs/testdata/invalid-modules/multiple-state-store/b.tf
- internal/configs/testdata/valid-modules/override-backend-with-state-store/main.tf
- internal/configs/testdata/valid-modules/override-backend-with-state-store/override.tf
- internal/configs/testdata/valid-modules/override-cloud-with-state-store/main.tf
- internal/configs/testdata/valid-modules/override-cloud-with-state-store/override.tf
- internal/configs/testdata/valid-modules/override-state-store-no-base/main.tf
- internal/configs/testdata/valid-modules/override-state-store-no-base/override.tf
- internal/configs/testdata/valid-modules/override-state-store/main.tf
- internal/configs/testdata/valid-modules/override-state-store/override.tf
> Add config parsing and validation for PSS

- internal/configs/configschema/internal_validate.go
- internal/configs/configschema/internal_validate_test.go
- internal/plugin/grpc_provider.go
- internal/plugin/grpc_provider_test.go
- internal/plugin6/grpc_provider.go
- internal/plugin6/grpc_provider_test.go
- internal/providers/provider.go
> Return list result that conforms to schema

- internal/plugin/grpc_provider.go
- internal/plugin/grpc_provider_test.go
- internal/plugin6/grpc_provider.go
- internal/plugin6/grpc_provider_test.go
> unwrap nested config

- internal/plugin/grpc_provider.go
- internal/plugin6/grpc_provider.go
We need the config encoding/decoding the resource changes
1.13.x
> Add config to List response

- internal/backend/remote-state/azure/backend.go
This fixes an issue in https://github.com/hashicorp/terraform/pull/37225 - I didn't want to push a commit and dismiss review from the Azure team. This fix can be approved by the core team as it doesn't require Azure-specific knowledge or to run tests.
1.13.x
> Add missing `return`s to azurerm backend

- internal/terraform/context_apply2_test.go
- internal/terraform/context_plan.go
- internal/terraform/context_plan2_test.go
- internal/terraform/graph_builder_apply.go
- internal/terraform/graph_builder_plan.go
- internal/terraform/transform_config.go
> Exclude list resources from normal plan runs

- internal/command/e2etest/terraform_query_test.go
- internal/command/e2etest/testdata/query-provider/main.tf
- internal/command/e2etest/testdata/query-provider/main.tfquery.hcl
- internal/command/e2etest/unmanaged_test.go
- internal/e2e/e2e.go
- internal/grpcwrap/provider.go
- internal/grpcwrap/provider6.go
- internal/provider-simple-v6/provider.go
- internal/provider-simple/provider.go
- internal/terraform/context_plan_query_test.go
> List implementation for simple provider and e2e tests

- internal/genconfig/generate_config.go
- internal/genconfig/generate_config_test.go
- internal/terraform/context_plan_query_test.go
- internal/terraform/node_resource_plan_instance.go
> Always generate provider address for list resource outputs

- internal/terraform/context_plan_actions_test.go
Very small PR that adds two test cases related to destroying to ensure destroying is no problem (it was no problem, but better safe than sorry)
Fixes [TF-27462](https://hashicorp.atlassian.net/browse/TF-27462)
1.14.x
[TF-27462]: https://hashicorp.atlassian.net/browse/TF-27462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> actions: add more test cases to ensure destroying is no issue

- internal/terraform/context_apply_action_test.go
> add more tests for failing actions

- docs/plugin-protocol/tfplugin5.proto
- docs/plugin-protocol/tfplugin6.proto
- internal/grpcwrap/provider.go
- internal/grpcwrap/provider6.go
- internal/plugin/grpc_provider.go
- internal/plugin6/grpc_provider.go
- internal/providers/provider.go
- internal/terraform/node_action_apply.go
- internal/tfplugin5/tfplugin5.pb.go
- internal/tfplugin6/tfplugin6.pb.go
> actions: add client capabilities across the board

- internal/command/jsonconfig/config.go
- internal/command/show_test.go
- internal/command/testdata/show-json-actions/main.tf
- internal/command/testdata/show-json-actions/output.json
> add actions to the planfile config

- internal/command/test_test.go
- internal/configs/parser_config_dir_test.go
- internal/configs/test_file.go
- internal/configs/testdata/invalid-test-files/skip_cleanup_after_backend.tftest.hcl
- internal/moduletest/graph/test_graph_builder.go
Improve error messaging and diagnostics around invalid backend and skip_cleanup combinations.
> Improve diagnostics around skip_cleanup conflicts

- internal/command/views/json/change.go
- internal/command/views/json/message_types.go
- internal/command/views/json_view.go
- internal/command/views/operation.go
- internal/command/views/operation_test.go
> add SRO message for planned action invocation

- internal/terraform/context_apply_action_test.go
This PR adds test cases that we cover during plan to the apply tests so we are sure what we can plan can also be applied.
Fixes #
1.14.x
> add more test cases for invoking actions during apply

- internal/command/jsonformat/plan_test.go
- internal/command/jsonprovider/provider.go
- internal/command/jsonprovider/provider_test.go
> include experimental schemas for displaying the plan

- internal/terraform/context_plan_actions_test.go
- internal/terraform/node_action_trigger_apply.go
> actions: detect cycle when before actions refer to the triggering resource

- internal/terraform/node_action_validate.go
Same PR as before, ensuring the CLA assistant passes this time. A couple of PRs merged at the same time (earlier today) and we ended up with some broken tests in main. 
Fixes #
1.14.x
> removing references to linked and lifecycle actions

- internal/backend/local/backend_apply.go
- internal/command/jsonformat/diff.go
- internal/command/jsonformat/plan.go
- internal/command/jsonformat/plan_test.go
Want to remerge https://github.com/hashicorp/terraform/pull/37522, this time will proper approvals.
> actions: render invoked actions

- internal/command/arguments/extended.go
- internal/terraform/context_apply_action_test.go
- internal/terraform/context_plan.go
- internal/terraform/context_plan_actions_test.go
Want to remerge https://github.com/hashicorp/terraform/pull/37523, this time will proper approvals.
> actions: allow skipping refresh when invoking actions

- internal/command/jsonformat/plan.go
- internal/command/jsonformat/plan_test.go
> actions: add number of invoked actions to plan summary

- internal/configs/action.go
- internal/configs/action_test.go
- internal/terraform/context_apply_action_test.go
- internal/terraform/context_plan_actions_test.go
- internal/terraform/node_action_trigger_instance_plan.go
- internal/terraform/node_action_trigger_partialexp.go
- internal/terraform/node_resource_plan_instance.go
> plan multiple actions invocations if multiple events are triggered in the same action trigger

- internal/moduletest/graph/eval_context.go
Fixed an incorrect error return that popped up in main
Fixes #
1.14.x
> modefuletest: fix error return

- docs/plugin-protocol/tfplugin6.proto
- internal/builtin/providers/terraform/provider.go
- internal/grpcwrap/provider6.go
- internal/plugin/grpc_provider.go
- internal/plugin6/grpc_provider.go
- internal/plugin6/mock_proto/mock.go
- internal/provider-simple-v6/provider.go
- internal/provider-simple/provider.go
- internal/providers/mock.go
- internal/providers/provider.go
- internal/providers/testing/provider_mock.go
- internal/refactoring/mock_provider.go
- internal/stacks/stackruntime/internal/stackeval/stubs/errored.go
- internal/stacks/stackruntime/internal/stackeval/stubs/offline.go
- internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
- internal/tfplugin6/tfplugin6.pb.go
- internal/tfplugin6/tfplugin6_grpc.pb.go
> PSS: Implement `LockState` & `UnlockState` provider methods
