communicator/ssh/provisioner.go
A mis-formatted private key may fail to parse correctly, but might still
contain sensitive data. Don't display the private key in any error
messages.
Fixes #19242
=> remove ssh private key contents from errors

configs/configupgrade/test-fixtures/valid/funcs-replaced/input/funcs-replaced.tf, configs/configupgrade/test-fixtures/valid/funcs-replaced/want/funcs-replaced.tf, configs/configupgrade/upgrade_expr.go
HIL implemented its type conversions by rewriting its AST to include calls to some undocumented builtin functions. Unfortunately those functions were still explicitly callable if you could figure out the name for them, and so they may have been used in the wild.
In particular, `__builtin_StringToFloat` was used as part of a workaround for a HIL design flaw (in #14967) where it would prefer to convert strings to integers rather than floats when performing arithmetic operations. This issue was, indeed, the main reason for unifying int and float into a single number type in HCL. Since we published that as a suggested workaround, the upgrade tool ought to fix it up.
The other cases have never been documented as a workaround, so they are less likely to appear in the wild, but we might as well …
=> configs/configupgrade: Fix up internal HIL conversion functions

configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/input/ignore-changes-flatmap-colls.tf, configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/want/ignore-changes-flatmap-colls.tf, configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/want/versions.tf, configs/configupgrade/upgrade_expr.go
Prior to Terraform 0.12, `ignore_changes` was implemented in a `flatmap`-oriented fashion and so users found that they could (and in fact, were often forced to) use the internal `.%` and `.#` suffixes that `flatmap` uses to ignore changes to the number of elements in a list or map.
Terraform 0.12 no longer uses that representation, so we'll interpret ignoring changes to the length as ignoring changes to the entire collection. While this is not a totally-equivalent change, in practice this pattern was most often used in conjunction with specific keys from a map in order to _effectively_ ignore the entire map, even though Terraform didn't really support that.
In the unlikely event that only the length was being ignored, that would've done nothing particularly useful in 0.11 and prior but …
=> configs/configupgrade: Silently ignore and trim .% and .# in ignore_changes

configs/configupgrade/test-fixtures/valid/argument-commas/input/argument-commas.tf, configs/configupgrade/test-fixtures/valid/argument-commas/want/argument-commas.tf, configs/configupgrade/test-fixtures/valid/argument-commas/want/versions.tf
The comma-separated syntax is now reserved only for object constructor expressions in attribute values, so the upgrade tool rewrites block arguments to be newline-separated instead.
This was already working but we didn't have an explicit test for it until now.
=> configs/configupgrade: Test for removing commas between block arguments

configs/configupgrade/test-fixtures/valid/element-of-set/input/element-of-set.tf, configs/configupgrade/test-fixtures/valid/element-of-set/want/element-of-set.tf, configs/configupgrade/test-fixtures/valid/element-of-set/want/versions.tf, configs/configupgrade/upgrade_expr.go, configs/configupgrade/upgrade_test.go
Although sets do not have indexed elements, in Terraform 0.11 and earlier `element(...)` would work with sets because we'd automatically convert them to lists before entry into HIL -- with an arbitrary-but-consistent ordering -- and thus return an arbitrary-but-consistent element from the list.
The `element(...)` function in Terraform 0.12 does not allow this because it is not safe in general, but there was an existing pattern relying on this in Terraform 0.11 configs which this upgrade rule is intended to preserve:
```hcl
resource "example" "example" {
count = "${length(any_set_attribute)}"
foo = "${element(any_set_attribute, count.index}"
}
```
The above works because the exact indices assigned in the conversion are irrelevant: we're just asking Terraform to create one resource for each …
=> configs/configupgrade: Detect and fix element(...) usage with sets

communicator/ssh/communicator.go
See if there is any additional stderr output before exiting, since it
can be helpful in addition to the error status.
=> print scp error before exiting on error code

state/state.go
This shouldn't really be an issue in normal usage, but some of the
backend tests will trigger a race here.
=> remove single rand source to prevent races

website/layouts/intro.erb
Companion PR to https://github.com/hashicorp/terraform-website/pull/677. Supersedes https://github.com/hashicorp/terraform/pull/19685.
Although /intro/getting-started includes docs content, those pages currently
redirect to the Learn platform, and so shouldn't be affected by the large unfurl
image.
=> website: Large, on-brand link preview image for marketing pages (/intro/*)

website/docs/modules/sources.html.markdown
The go-getter library that is used by the module loader validates S3 URLs in the parseURL function. That function assumes path-style URLs and fails on virtual-hosted-style URLs.
=> Only path-style S3 URLs are supported.

website/docs/backends/types/consul.html.md
The Terraform docs currently do not make it clear how state locks are acquired in Consul. The docs specify that the token must have session permissions with Consul if locking is enabled.
As it turns out, if Consul's ACL is enabled and you try to use a Consul token with session permissions but not at least `write` on `$path/.lock`, running any Terraform commands that touch state leads to non-obvious `403` errors whose resolution is digging into the source for the Consul backend.
This PR addresses https://github.com/hashicorp/terraform/issues/19963.
=> Add details about using lock=true when consul ACL is enabled

configs/configupgrade/analysis.go, configs/configupgrade/test-fixtures/valid/noop/input/resources.tf, configs/configupgrade/test-fixtures/valid/noop/want/resources.tf, configs/configupgrade/test-fixtures/valid/provisioner/input/provisioner.tf, configs/configupgrade/test-fixtures/valid/provisioner/want/provisioner.tf, configs/configupgrade/test-fixtures/valid/provisioner/want/versions.tf, configs/configupgrade/upgrade_body.go, configs/configupgrade/upgrade_native.go, configs/configupgrade/upgrade_test.go, terraform/eval_validate.go
This is mostly the same principle as for other schema-driven blocks, and is just a matter of wiring in a step to look up the appropriate schema and then run the normal migration steps based on it.
It has one additional function that we've not done anywhere else, though: it adds additional arguments to `connection` blocks to compensate for the fact that provider-supplied defaults are no longer supported in v0.12, under the principle of "explicit is better than implicit".
For compatibility, the upgrade tool will insert expressions that are as close as possible to the logic the provider formerly implemented, or in a few rare cases a `TF-UPGRADE-TODO` comment to prompt to fix it up manually.
---
Some of the existing resource type implementations have incredibly complicated implementations of …
=> configs/configupgrade: Upgrade of provisioner and connection blocks

configs/configupgrade/test-fixtures/valid/resource-count-ref/input/resource-count-ref.tf, configs/configupgrade/test-fixtures/valid/resource-count-ref/want/resource-count-ref.tf, configs/configupgrade/test-fixtures/valid/resource-count-ref/want/versions.tf, configs/configupgrade/upgrade_expr.go
Terraform 0.11 and prior had an odd special case where a resource attribute access for `.count` would be resolved as the count for the whole resource, rather than as an attribute of an individual instance as
for all other attributes.
Because Terraform 0.12 makes `test_instance.foo` appear as a list when the `count` argument is set (so it can be used in other expressions), it's no longer possible to have an attribute in that position: lists don't have attributes. Fortunately we don't really need that special case anymore since it doesn't do anything we can't now do with the `length(...)` function.
This upgrade rule, then, detects references like `test_instance.foo.count` and rewrites to `length(test_instance.foo)`. As a special case, if `test_instance.foo` doesn't have `count` set then it …
=> configs/configupgrade: Fix up uses of the .count pseudo-attribute

communicator/ssh/communicator.go, communicator/ssh/communicator_test.go
Long running remote-exec commands with no output may be cutoff during
execution. Enable ssh keepalives for all ssh connections.
Supersedes #19339
=> add ssh keepalive messages to communicator

configs/configschema/decoder_spec.go, configs/configupgrade/test-fixtures/valid/redundant-list/input/redundant-list.tf, configs/configupgrade/test-fixtures/valid/redundant-list/want/redundant-list.tf
This was already working but we had no tests to prove it.
This for #19140, showing that it's been fixed by some other change since I verified it on v0.12.0-alpha4.
=> config/configupgrade: Test to show that list unwrapping works for sets

backend/remote-state/s3/backend.go, backend/remote-state/s3/backend_state.go, backend/remote-state/s3/backend_test.go
The handling of slashes was broken around listing workspaces in
workspace_key_prefix. While it worked in most places by splitting an
extra time around the spurious slashes, it failed in the case that the
prefix ended with a slash of its own.
A test was temporarily added to verify that the backend now works with the
unusual keys, but rather than risking silent breakage around prefixes
with trailing slashes, we also add validation to prevent users from
entering keys with trailing slashes at all.
```
--- PASS: TestBackendConfig (1.08s)
--- PASS: TestBackendConfig_invalidKey (0.00s)
--- PASS: TestBackend (18.43s)
--- PASS: TestBackendLocked (27.05s)
--- PASS: TestBackendExtraPaths (16.82s)
--- PASS: TestBackendPrefixInWorkspace (6.02s)
--- PASS: TestKeyEnv …
```
=> s3 workspace_key_prefix

backend/remote/backend_apply.go, backend/remote/backend_mock.go, go.mod, go.sum, vendor/github.com/hashicorp/go-tfe/organization.go, vendor/github.com/hashicorp/go-tfe/run.go, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/github.com/hashicorp/go-tfe/workspace.go, vendor/modules.txt
Previously we checked can-update in order to determine if a user had the
required permissions to apply a run, but that wasn't sufficient. So we
added a new permission, can-queue-apply, that we now use instead.
=> backend/remote: use the can-queue-apply permission

command/jsonprovider/attribute.go, command/jsonprovider/attribute_test.go, command/jsonprovider/block.go, command/jsonprovider/block_test.go, command/jsonprovider/doc.go, command/jsonprovider/provider.go, command/jsonprovider/provider_test.go, command/jsonprovider/schema.go, command/jsonprovider/schema_test.go, command/providers_schema.go, command/providers_schema_test.go, command/test-fixtures/providers-schema/output.json, command/test-fixtures/providers-schema/provider.tf, commands.go
=> [WIP] command/jsonprovider: export providers schemas to json

command/validate.go
We brought forward a new implementation of `terraform validate` that was originally scheduled for a later release after finding that it would be simpler than reworking the old implementation for new v0.12 assumptions, but we didn't yet implement `terraform plan -validate-only` in spite of it being mentioned in the updated docs for `terraform validate`.
For now then, the documentation will make the weaker suggestion of running `terraform plan` to validate a particular _run_ rather than a particular _module_, which is the closest thing we have for now. At some point after v0.12.0 we will evaluate whether a validate-only mode for `terraform plan` (which would then run without configuring the providers at all) is needed.
This fixes #19259.
=> command: Remove promise of plan -validate-only from validate docs

website/docs/commands/0.12upgrade.html.markdown, website/layouts/docs.erb, website/upgrade-guides/0-12.html.markdown
This includes some revisions to the upgrade guide to give more guidance to beta testers, and also the formerly-missing documentation for the `terraform 0.12upgrade` command.
All of these docs will certainly be revised at least one more time before the final v0.12.0 release, so some parts of these docs intentionally discuss things from a prerelease perspective assuming that we'll update them as we prepare for final release, along with more step-by-step upgrade instructions once the full flow is finalized.
=> website: Documentation updates in preparation for v0.12.0-beta1

backend/atlas/backend.go, backend/backend.go, backend/init/deprecate_test.go, backend/init/init.go, backend/local/backend.go, backend/nil.go, backend/remote-state/s3/backend.go, backend/remote-state/s3/backend_test.go, backend/remote/backend.go, backend/remote/backend_test.go, backend/remote/testing.go, backend/testing.go, builtin/providers/terraform/data_source_state.go, command/init.go, command/meta_backend.go, helper/schema/backend.go, helper/schema/backend_test.go
- Change `backend.ValidateConfig` to `PrepareConfig`
This mirrors the change made for providers, so that default values can
be inserted into the config by the backend implementation. `PrepareConfig` 
looks up any defaults and insert them into the config value before
validating and returning the config. 
Fixes #19249
Related to #19256, but does not create a new `config.Body` for decoding. Currently, the `PrepareConfig` call (nee `ValidateConfig`) will fail its own validation at this point before we have the complete config to merge with the original body. 
Fixing how config bodies are merged and decoded could possibly deal with future backend implementations that don't fully validate, but for now we would only be gaining an extra diagnostic with  the line number of the backend block with …
=> backend init defaults and inputs

backend/remote-state/s3/backend.go
Porting over previous behavior from terraform-provider-aws.
Output from acceptance testing:
```
--- PASS: TestBackendConfig (0.37s)
--- PASS: TestBackendConfig_invalidKey (0.00s)
--- PASS: TestBackend (3.02s)
--- PASS: TestBackendLocked (9.69s)
--- PASS: TestBackendExtraPaths (3.15s)
--- PASS: TestBackendPrefixInWorkspace (1.85s)
--- PASS: TestKeyEnv (8.88s)
--- PASS: TestRemoteClient_impl (0.00s)
--- PASS: TestRemoteClient (2.22s)
--- PASS: TestRemoteClientLocks (12.14s)
--- PASS: TestForceUnlock (12.73s)
--- PASS: TestRemoteClient_clientMD5 (8.53s)
--- PASS: TestRemoteClient_stateChecksum (9.59s)
```
=> backend/s3: Add debug logging and user agent

command/format/diff.go, plans/objchange/normalize_obj.go, plans/objchange/normalize_obj_test.go, terraform/eval_apply.go, terraform/eval_diff.go
We are now allowing the legacy SDK to opt out of the safety checks we try to do after plan and apply, and so in such cases the before/after values in planned changes may be inconsistent with our usual rules.
To avoid adding lots of extra complexity to the diff renderer to deal with these situations, instead we'll normalize the handling of nested blocks prior to using these values.
In the long run it'd be better to do this normalization at the source, immediately after we receive an object from a provider using the opt-out, but we're doing this at the outermost layer for now to avoid risking
unintended impacts on other Terraform Core components when we're just about to enter the beta phase of the v0.12.0 release cycle.
=> command/format: Normalize before/after values before rendering

helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
1->0 set changes needs to be fixed during apply due to inconsistencies within `helper/schema`,
and this was carried over to Read as well. The new normalization should make preventing those changes unnecessary, and this will also prevent extra empty elements from being added when resources are refreshed.
Attributes with no change can only become computed during initial instance creation. There are cases where `helper/schema` will show a `NewComputed` field with no change in the configuration which needs to be filtered out of the diff.
Fixes #20506
=> Unexpected empty and computed values

website/docs/configuration/data-sources.html.md, website/docs/configuration/functions/jsondecode.html.md, website/docs/configuration/functions/jsonencode.html.md, website/docs/configuration/functions/timestamp.html.md, website/docs/configuration/functions/uuid.html.md
In all the shuffling of these docs for v0.12 some of the links ended up not lining up quite right.
=> website: Fix some broken links

website/upgrade-guides/0-12.html.markdown
The announcement post contains the information about the temporary situation where not all of the providers are compatible yet. Linking there rather than duplicating the information in the upgrade guide means we'll be able to update in one place as the situation changes.
=> website: Temporary link to the beta1 announcement from v0.12 guide

command/jsonconfig/config.go, command/jsonplan/values.go, command/test-fixtures/show-json/modules/bar/main.tf, command/test-fixtures/show-json/modules/foo/main.tf, command/test-fixtures/show-json/modules/main.tf, command/test-fixtures/show-json/modules/output.json
jsonconfig and jsonplan both had subtle bugs with the logic for
marshaling module calls that only showed up when multiple modules were
referenced. This PR fixes those bugs and extends the existing tests to
include multiple modules.
It turns out having a dozen variables with similar names (mc! cm! cc!) is terribly confusing. Splitting things out into smaller functions greatly helped.
=> command/show: fixing bugs in modulecalls

command/jsonplan/plan.go, command/show.go
When a planfile is supplied to the `terraform show -json` command, the
context that loads only included schemas for resources in the plan. We
found an edge case where removing a data source from the configuration
(though only if there are no managed resources from the same provider)
would cause jsonstate.Marshal to fail because the provider schema wasn't
in the plan context.
jsonplan.Marshal now takes two schemas, one for plan and one for state.
If the state schema is nil it will simply use the plan schemas.
=> command/show: differentiate between state schemas and plan schemas.

command/meta_backend.go, helper/schema/backend.go, helper/schema/backend_test.go
When the user aborts input, it may end up as an unknown value, which
needs to be converted to null for PrepareConfig.
Allow PrepareConfig to accept null config values in order to fill in
missing defaults.
Fixes #20503
=> don't panic of the users aborts backend input

helper/plugin/grpc_provider.go, plans/objchange/objchange.go, plans/objchange/objchange_test.go
It turns out the `timeouts` blocks were initially being added to the plan by `ProposedNewObject`, and the provider shims were maintaining the block as instructed. This means even if the provider made no changes to the proposed value, core would still report it as an error.
The other location the block was being added was in the `hcl2shim` package, since it is operating on only the flatmap data and the `cty.Type` it has to make some assumptions about the structure. Rather than change the `hcl2shim` behavior at this point, we just modify the `copyTimeoutValues` to drop the block entirely if it contains no values.
=> Prevent unexpected timeout blocks from being planned

command/show.go, command/state_show.go
Previously, these commands were not checking if the user specified a
`-plugin-dir` flag during `terraform init` and would therefore fail if
providers were not in one of the standard directories.
Fixes #20547
=> command/show and state show: honor user-specified plugin-dir

backend/remote-state/pg/client.go, backend/remote-state/pg/client_test.go, website/docs/backends/types/pg.html.md
…to avoid rollback of partial state updates.
Based on [discussion following merge of Postgres backend](https://github.com/hashicorp/terraform/pull/19070#issuecomment-469432575) with @jbardin 
Acceptance tests are once again passing locally ✅ (updated for commit 34fa67c)
```sh-session
$ TF_ACC=1 GO111MODULE=on go test -v -mod=vendor -timeout=2m -parallel=4 github.com/hashicorp/terraform/backend/remote-state/pg
--- PASS: TestBackendConfig (0.06s)
backend_test.go:50: TestBackendConfig on *pg.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"conn_str":cty.StringVal("postgres://localhost/terraform_backend_pg_test?sslmode=disable"), …
```
=> Switch pg backend to session-level advisory locking

plugin/discovery/get.go, plugin/discovery/get_test.go
If the user supplies a plugin cache dir, the provider installer was not
checking if target directory exists before linking the cached plugin.
Fixes #20532
=> plugin/discovery: create target plugin directory if it does not exist

builtin/providers/test/resource_list.go, builtin/providers/test/resource_list_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
Providers were not strict (and were not forced to be) about customizing
the diff when a computed attribute needed to be updated during apply.
The fix we have in place to prevent loss of information during the
helper/schema apply process would add in single missing value back in.
The first place this was caught was when we attempt to fix up the
flatmapped attribute. The 1->0 count error is now better handled by our
`cty.Value` normalization step, so we can remove the special apply
case here.
The next place is in `normalizeNullValues`, and since the intent was to
re-insert missing zero-value lists and sets, adding a check for a length
of 0 protects us from adding in extra elements.
The new test fixture emulates common provider behavior of re-computing
values without customizing the diff. …
=> don't re-add removed list values even when planned

builtin/providers/test/resource_computed_set.go, builtin/providers/test/resource_computed_set_test.go, helper/plugin/grpc_provider.go
The NewExtra values are stored outside the diff from plan, and the
original keys may not contain the ~ prefix. Adding the NewExtra back
into the diff with the mismatched key was causing an entire new set
element to be populated. Since this symbol isn't used to apply the diff in
helper/schema, we can simply strip them out.
Fixes #20486
=> remove the partially-known ~ set sigil in diffs

backend/unparsed_value.go, backend/unparsed_value_test.go
For users who in previous versions have relied on our lack of checking for whether variables are declared, they may previously have seen an overwhelming number of warnings when running Terraform v0.12.
Here we cap that number at three specific warnings and then one general warning, so we can still give a specific source location for the first couple (for users who have genuinely made a typo) but summarize away a large number for those who are seeing this because they've not yet migrated to using environment variables.
This fixes #20538. I took a slightly different approach to what I'd previously proposed there because when I tried it in practice the single consolidated warning message was not so helpful in the situation where the problem really _is_ a typo in a `.tfvars` file, because it …
=> backend: Cap number of "undeclared variable" warnings at four

website/docs/state/sensitive-data.html.md
To better align with the current status of PGP usage and remove any confusion for the missing functionality.
References:
* https://www.terraform.io/docs/providers/aws/r/iam_access_key.html
* https://www.terraform.io/docs/providers/aws/r/db_instance.html
=> docs/state: Adjust mention of PGP encryption from RDS to IAM

command/format/diff.go, helper/plugin/grpc_provider.go, terraform/eval_apply.go, terraform/eval_diff.go
Use `objchange.NormalizeObjectFromLegacySDK` to ensure that all objects
returned from the provider match what is expected based on the
configuration according to the schemas.
This is intended to provide additional warnings about blocks that are unexpectedly altered, most commonly blocks that are marked as "computed" in `helper/schema`, which we don't intend to support in the same manner going forward.
=> normalize all objects read from the provider

configs/configload/copy_dir.go, configs/configload/copy_dir_test.go, internal/initwd/copy_dir.go, internal/initwd/copy_dir_test.go
Take two! With tests!
configs/configload and internal/initwd both had a copyDir function that
would fail if the source directory contained a symlinked directory,
because the os.FileMode.IsDir() returns false for symlinks.
This PR adds a check for a symlink and recreates the symlink in the
target directory. It handles symlinks for both files and directories
(with included tests).
Fixes #20539
=> copyDir: detect if the module install path is a symlink to a directory

backend/remote/backend.go, go.mod, go.sum, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/modules.txt
Enably retrying on server errors in the updated `go-tfe` client and add a
retry log hook for writing retry messages to the CLI.
=> backend/remote: also retry on server errors

backend/local/cli.go, backend/remote/backend.go, backend/remote/cli.go, go.mod, go.sum, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/modules.txt
Enably retrying on server errors in the updated `go-tfe` client and add a retry log hook for writing retry messages to the CLI.
=>  backend/remote: also retry on server errors

backend/remote/backend_apply.go, backend/remote/backend_apply_test.go, backend/remote/backend_common.go, backend/remote/backend_mock.go, backend/remote/backend_plan.go
Check for external updates made to the current run using the UI or API while waiting for user input.
=> backend/remote: check for external updates

command/format/diff.go, helper/plugin/grpc_provider.go
Revert the functionality in #20595, since it turns out there is provider code that will not work with the normalized blocks.
This retains the removal of the eval* TODOs, since it was demonstrated that it's not feasible to store the normalized values while remaining compatibility with the legacy providers.
=> revert #20595

command/jsonplan/plan.go, command/jsonprovider/provider.go, command/jsonstate/state.go, command/providers_schema.go
The `-json` output was noticeably slow, and the file size noticeably large. As the output was designed for machine-readability and the indentation processing is a bottleneck, it makes sense to remove the indentation. 
Removing the indentation reduced the run time of `terraform providers schema -json` on a tf configuration with the AWS provider to 1.2 seconds, down from 7 seconds on my laptop. It also reduced the output file size from 1.1M to less than .5M. 
If there is demand later, we could add some variation on a `-pretty` flag for human-readable output.
=> remove indentation from json output of `show` and `providers schema`

website/docs/configuration/expressions.html.md
Since references to attributes of resources are by far the most common reference type, and the mapping of resource type config to the attributes is not always obvious, here we give some real examples of patterns for accessing different configuration constructs within resource blocks along with the resource type's exported attributes.
Since we don't have any real examples of labelled nested blocks yet (the current SDK doesn't support them) I've included a hypothetical example for now just to establish the patterns around them in preparation for beginning to introduce them as we roll out this feature in the SDK.
While I was in this file anyway, I also fixed up some `for` expression examples that were not following the way the whitespace gets set by `terraform fmt`. (The extra spaces …
=>  website: References to Resource Attributes

backend/init/init.go, backend/init/init_test.go, backend/local/cli.go, backend/remote/cli.go
The `init` bits in this PR were missed during the initial backport of the free remote state storage code back in Januari. The issue didn't surface until a recent change made last week and unfortunately local testing with the `TF_FORCE_LOCAL_BACKEND` flag didn't catch this either.
=> backend/remote: fix a backend init bug

builtin/providers/test/resource_computed_set.go, builtin/providers/test/resource_list.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
As we've improved the cty.Value normalization, we need to remove
normalization procedures from the flatmap handling. Keeping the empty
containers in the flatmap will prevent unexpected nils from being added
to some schema configurations
=> stop removing empty flatmap containers

builtin/providers/test/provider.go, builtin/providers/test/resource_config_mode.go, builtin/providers/test/resource_config_mode_test.go, helper/schema/core_schema.go, helper/schema/core_schema_test.go, helper/schema/schema.go, helper/schema/schema_test.go
This allows a provider developer slightly more control over how an SDK schema is mapped into the Terraform configuration language, overriding some default assumptions.
`ConfigMode` overrides the default assumption that a schema with an Elem of type `*Resource` is to be mapped to configuration as a nested block, allowing mapping as an attribute containing an object type instead.
This should rarely be needed, but it can be useful in situations where the provider was assuming attribute-like behaviors in 0.11 (such as ability to explicitly assign an empty list) which were possible because 0.11 didn't enforce the use of block syntax for nested resources. For some real examples, see #20505.
Since this uses the attribute syntax, this'll work best for SDK schema attributes that already had plural …
=> helper/schema: ConfigMode field in *Schema

lang/funcs/crypto.go, lang/funcs/crypto_test.go
Closes #20652
The implementation and testing were incorrectly referencing SHA-512 instead of SHA-256.
=> lang/funcs: Fix filebase64sha256 function hashing algorithm

command/meta_config.go, command/unlock_test.go
We can't dereference the config module if there were any errors loading
it.
Fixes #20635
=> check for errors when loading a backend config

builtin/providers/test/resource.go, builtin/providers/test/resource_dataproc_cluster_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go, terraform/diff.go
This shifts around some of the normalization to fix up more edge cases. In the process we are able to completely remove the `normalizeFlatmapContainers` function, which should simplify maintenance in general.
Aside from cleanup and tests, the 2 primary goals in this PR are:
- retain existing count values during `diff.Apply`, since zero values are often not represented in flatmapped state.
- Normalize null values in `ReadResource` to prevent drift when reading a resource doesn't produce consistent values. The old normalization in `PlanResourceChange` would try and anticipate these diffs so that providers could exert more control in `Read`, but there's no way to account for every combination of values that providers may unexpectedly create.
Fixes #20507
=> sdk shim normalization

website/docs/providers/terraform/d/remote_state.html.md
I don't want this PR to set precedence in how we version docs as this would be a tedious and manual, hence unscalable process. We have plans to address this in the long run and offer versioned docs in a more scalable way, but there are other things which have had higher priority on the roadmap.
Until then we'll have to accept some level of discomfort as a result of this unfortunately.
I think this one in particular is justified because `terraform_remote_state` data source has significant user base and we are introducing a change which is unfortunately breaking the user experience.
=> docs: Differentiate 0.11/0.12 in terraform_remote_state

command/012_config_upgrade.go, configs/configupgrade/analysis.go, configs/configupgrade/test-fixtures/valid/module-source/input/main.tf, configs/configupgrade/test-fixtures/valid/module-source/want/main.tf, configs/configupgrade/test-fixtures/valid/module-source/want/versions.tf, configs/configupgrade/test-fixtures/valid/relative-module-source/input/main.tf, configs/configupgrade/test-fixtures/valid/relative-module-source/input/module/main.tf, configs/configupgrade/test-fixtures/valid/relative-module-source/want/main.tf, configs/configupgrade/test-fixtures/valid/relative-module-source/want/module/main.tf, configs/configupgrade/test-fixtures/valid/relative-module-source/want/versions.tf, configs/configupgrade/upgrade.go, configs/configupgrade/upgrade_body.go, configs/configupgrade/upgrade_native.go, configs/configupgrade/upgrade_test.go, internal/initwd/getter.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go
If a module source appears to be a relative local path but does not have
a preceding ./, print a #TODO message for the user.
Together, this and PR #20639 fixes #19745 and #20573
=> configs/configupgrade: detect possible relative module sources

website/docs/configuration/syntax-json.html.md, website/docs/state/workspaces.html.md, website/layouts/backend-types.erb, website/layouts/commands-providers.erb, website/layouts/commands-state.erb, website/layouts/commands-workspace.erb, website/layouts/docs.erb, website/layouts/downloads.erb, website/layouts/functions.erb, website/layouts/guides.erb, website/layouts/intro.erb, website/layouts/registry.erb
Updating this got onerous almost immediately, so let's use a partial instead and only update these links in one place. 
This depends on https://github.com/hashicorp/terraform-website/pull/699, so I'm leaving it in draft state until it's OK to merge. 
This PR also includes two other tiny docs site fixes that didn't seem worth their own PRs, but if anyone has any reservations about that I'll go ahead and rebase them out into their own thing(s).
=> website: re-arrange how we include the "other docs" sidebar section

website/docs/commands/0.12upgrade.html.markdown, website/docs/configuration-0-11/environment-variables.html.md, website/docs/configuration-0-11/modules.html.md, website/docs/configuration-0-11/providers.html.md, website/docs/configuration/expressions.html.md, website/docs/configuration/modules.html.md, website/docs/configuration/providers.html.md, website/docs/modules/sources.html.markdown, website/docs/registry/modules/publish.html.md, website/docs/registry/modules/use.html.md, website/docs/registry/private.html.md, website/upgrade-guides/0-11.html.markdown
@apparentlymart, you're in the review hotseat for this because I think most of this was from pages you moved. 😄
Mostly straightforward except for the part about duplicating the 0.12 configuring modules page into the 0.11 docs, but it seemed like the lowest-impact way to deal with the moved content.
=> website: update several broken links

lang/funcs/filesystem.go
Closes #20664
Wording can be adjusted as appropriate. 😄
=> config: Mention other file hashing functions when file() detects unsupported contents

configs/test-fixtures/invalid-files/version-variable.tf, configs/version_constraint.go
In the current PR, I've added a check if the version attribute `IsWhollyKnown()` and return some diagnostics. This results in two error messages:
```
$ ./terraform init
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Variables not allowed
on pets.tf line 11, in module "pets":
11:   version = var.module_version
Variables may not be used here.
Error: Invalid version constraint
on pets.tf line 11, in module "pets":
11:   version = var.module_version
A string value is required for version.
```
I could choose to return from `decodeVersionConstraint` in this scenario without any additional diagnostics, which gives a much nicer …
=> configs: do not panic if module version is a variable

command/format/diff.go, command/format/diff_test.go
Trying to decode and write "null" as json will panic, since it decodes
to nil.
Fixes #20634
=> don't try to treat "null" as json in diff output

website/docs/configuration/functions/formatdate.html.md, website/layouts/functions.erb
The formatdate function wasn't shown in the function reference sidebar; I only discovered it by seeing a link at the bottom of the 'timestamp' page.
=> Added 'formatdate' to the function reference sidebar.

command/jsonplan/plan.go, command/jsonplan/resource.go, command/test-fixtures/show-json/basic-create/output.json, command/test-fixtures/show-json/basic-delete/output.json, command/test-fixtures/show-json/basic-update/output.json, command/test-fixtures/show-json/modules/output.json
`"provider_name"` currently appears in `planned_values.resources`, but not `"resource_changes"`.
=> command/show: add provider name to resource changes

plans/objchange/objchange.go, plans/objchange/plan_valid.go, plans/objchange/plan_valid_test.go
We were using the wrong cty operation to access map members, causing a panic whenever a prior value was present for a resource type with a nested block backed by a map value.
=> plans/objchange: Don't panic when prior state contains nested map blocks

terraform/context_refresh_test.go, terraform/eval_refresh.go, terraform/test-fixtures/refresh-dynamic/main.tf
Our post-refresh safety check had the constraint and real type inverted, so previously any refresh of a resource type with a dynamically-typed attribute would always fail this type check.
`TestConformance` is not commutative when `cty.DynamicPseudoType` is present because in the constraint argument it means "any type" but in the concrete type to be checked it means "unknown type". Having these inverted therefore led to a pretty confusing error message:
```
Error: Provider produced invalid object
Provider "test" planned an invalid value for test_instance.test:
.access.policy: object required, but received dynamic during refresh.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
This also includes a small tweak to the error message from this …
=> core: Don't fail on dynamic attribute values during refresh

command/init.go, command/init_test.go, command/plugins_test.go, plugin/discovery/get.go, plugin/discovery/get_test.go, registry/response/terraform_provider.go, tools/terraform-bundle/package.go
Terraform Registry (and other registry implementations) can now return an
array of warnings with the versions response. These warnings are now
displayed to the user during a `terraform init`.
=> plugin/discovery: Parse warnings from TF Registry

website/docs/commands/0.12upgrade.html.markdown, website/docs/commands/fmt.html.markdown, website/docs/commands/providers/schema.html.md, website/docs/commands/show.html.markdown, website/docs/commands/state/addressing.html.md, website/docs/internals/resource-addressing.html.markdown, website/docs/modules/composition.html.markdown
We have released the v0.12-oriented content to the website early in order to support the beta process, but in some places we neglected to explicitly mark features or content as being v0.12-only.
Here we add explicit markers to the main cases we've seen where readers have reported confusion, along with some other tweaks in similar vein.
=> website: Indicate v0.12-only content

website/docs/commands/destroy.html.markdown, website/docs/commands/plan.html.markdown
Updated Resource Targeting section of `terraform plan` docs to include targeting a specific index of a resource and added a reference to it in `terraform destroy` that mirrors the reference in `terraform apply`. This closes #18184
=> Docs: reference resource by index, fixes #18184

go.mod, go.sum, lang/eval.go, lang/references.go, terraform/graph_builder_plan_test.go, terraform/test-fixtures/graph-builder-plan-dynblock/dynblock.tf, vendor/github.com/hashicorp/hcl2/ext/dynblock/variables.go, vendor/github.com/hashicorp/hcl2/ext/dynblock/variables_hcldec.go, vendor/modules.txt
The `hcldec` package has no awareness of the dynamic block extension, so the `hcldec.Variables` function misses any variables declared inside `dynamic` blocks.
`dynblock.VariablesHCLDec` is a drop-in replacement for `hcldec.Variables` that _is_ aware of dynamic blocks, returning all of the same variables that `hcldec` would find naturally plus also any variables used inside the dynamic block `for_each` and `labels` arguments and inside the nested `content` block.
This fixes #20517.
=> lang: Consider "dynamic" blocks when resolving references

website/docs/backends/types/remote.html.md
This PR adds a few lines to the docs to indicate which commands are
supported by what version of the remote backend and it makes a
recommendation about which version to use.
=> docs: elaborate on supported remote backend versions

helper/resource/state_shim.go, helper/resource/state_shim_test.go
It's important to preserve the provider address because during the destroy phase of provider tests we'll use the references in the state to determine which providers are required, and so without this attempts to override the provider using the "provider" meta-argument can cause failures at destroy time when the wrong provider gets selected.
(This is particularly acute in the google-beta provider tests because that provider is _always_ used with `provider = "google-beta"` to override the default behavior of using the normal "google" provider. Fixes #20735.)
=> helper/resource: Preserve provider address when shimming to old state

command/format/diff.go, command/format/diff_test.go
Due to these tests happening in the wrong order, removing an object from the end of a sequence of objects would previously cause a bounds-check panic.
Rather than a more severe rework of the logic here, for now we'll just introduce an extra precondition to prevent the panic. The code that follows already handles the case where there _is_ no new object (i.e. the "old" object is being deleted) as long as we're able to pass through this type-checking logic.
The new "JSON list of objects - removing item" test covers this problem by rendering a diff for an object being removed from the end of a list of objects within a JSON value.
This fixes #20750.
=> command/format: Don't panic when item removed from list of objects

lang/funcs/filesystem.go, lang/funcs/filesystem_test.go
The `templatefile` function only has two arguments, so `ArgErrorf` can be called with only zero or one as the argument index. If we are out of bounds then HCL itself will panic trying to build the error message for this call when called as an HCL function.
Unfortunately there isn't really a great layer in Terraform to test for this class of bug systematically, because we are currently testing these functions directly rather than going through HCL to do it. For the moment we'll just live with that, but if we see this class of error arise again we might consider either reworking the tests in this package to work with HCL expression source code instead of direct calls or adding some additional tests elsewhere that do so.
This fixes #20762.
=> lang/funcs: Fix out-of-bounds ArgError in templatefile function

backend/remote-state/gcs/backend.go, backend/remote-state/gcs/backend_test.go, website/docs/backends/types/gcs.html.md
These two attributes are not used since https://github.com/hashicorp/terraform/commit/aec45e696701b4aa09958b5e683831b293d6a85e.
=> Mark the unused attributes project and region as removed.

config/interpolate_funcs.go, config/interpolate_funcs_test.go, lang/funcs/collection.go, lang/funcs/collection_test.go, lang/functions.go, website/docs/configuration/functions/reverse.html.md, website/layouts/functions.erb
=> config: new "reverse" interpolation function

website/intro/getting-started/modules.html.md
I think "a module" is better than "modules" in this case because it makes it clear that one module can have more than one output value.
=> website: add missing article

go.mod, go.sum, vendor/github.com/zclconf/go-cty/cty/convert/unify.go, vendor/github.com/zclconf/go-cty/cty/gocty/in.go, vendor/modules.txt
This includes a fix to prevent unintentional infinite recursion when trying to unify multiple object types to a single type for conversion to `list(any)`.
Sadly I wasn't able to reproduce the problem as reported (in #20728), so therefore I wasn't able to write a Terraform test for it, but I have confirmed that the cty behavior here was incorrect anyway (recursively
calling the same function we're already in with the same arguments is clearly not productive) and so this change will allow whatever situation that was to terminate with a type conversion error, rather than causing a stack overflow.
It's likely that there is another bug lurking under this, since the problematic code here was supposed to be unreachable, but avoiding the crash is the priority for now. If the problem re-surfaces …
=> vendor: go get github.com/zclconf/go-cty/cty@master

website/docs/commands/environment-variables.html.md
Blatantly copied from https://learn.hashicorp.com/terraform/development/running-terraform-in-automation since it is missing on the [env var page]( https://www.terraform.io/docs/configuration/environment-variables.html).
On a side note, the edit link on the page https://www.terraform.io/docs/configuration/environment-variables.html is broken. It looks like the page was moved via e5e3452ffacbc83658d92210a3547162c74ad730 but that change was made on the 5th of May. Have the docs not been deployed since then?
=> Adds TF_IN_AUTOMATION description

website/docs/backends/types/terraform-enterprise.html.md
Corrects documentation stating backend terraform-enterprise's access_token is required, when it can be collected at time of `terraform init`.
=> Corrects and clarifies that access_token is not a required

command/init.go, plugin/discovery/error.go, plugin/discovery/get.go, plugin/discovery/get_test.go, plugin/discovery/signature.go
* Forces immutability of providers between the Registry and the hosting location
* Improves the verification error messages during provider discovery.
Below are screenshots of checksum and signature error messages
=> plugin/discovery: verify registry checksum

website/docs/provisioners/null_resource.html.markdown
Fix a typo in null_resource provisioner title: `exiting` -> `existing` resource
=> Fix a typo in null_resource provisioner title

backend/remote-state/s3/client_test.go, command/meta_backend_test.go, communicator/communicator.go, config/raw_config_test.go, configs/config.go, helper/resource/state.go, helper/schema/resource_diff.go, internal/earlyconfig/config.go, plugin/discovery/meta_set.go, website/docs/commands/state/show.html.md
Hi! I noticed a misuse of `a` vs `an` in the documentation. So I did a quick search of similar mistakes and made the corrections here.
=> grammatical updates to comments and docs

builtin/providers/test/resource_config_mode.go, builtin/providers/test/resource_config_mode_test.go, helper/plugin/grpc_provider.go, helper/schema/core_schema.go, helper/schema/core_schema_test.go, helper/schema/schema.go, terraform/eval_state_upgrade.go
When running in v0.12-and-higher mode, this will cause the SDK to report the type of the attribute as `any`, effectively skipping type checking on the Core side altogether and checking only in the SDK and provider code.
The practical impact of this is to restore the v0.11-style checking behavior of allowing object values to be missing certain attributes as long as they are marked as optional in the schema. The SDK can do this
because it uses a unified schema model for both object values and nested blocks, while Terraform Core only supports the idea of "optional" when talking about attributes in nested blocks.
This is a continuation of the pile of workarounds that also includes the `ConfigMode` and `AsSingle` fields, allowing providers to selectively opt out of some new v0.12 behaviors in …
=> helper/schema: Schema.SkipCoreTypeCheck flag

website/docs/commands/graph.html.markdown
'legacy' doesn't seem to be a thing anymore, and we were missing some
of the other values for -type. Also -no-color doesn't seem to be
relevant to this command.
=> website: Update options for graph command

go.mod, go.sum, vendor/github.com/hashicorp/go-plugin/client.go, vendor/modules.txt
This fixes missing json output from plugin logs, as well as converts the `[LEVEL]` tags to hclog log levels.
Fixes: #20758
=> udpate go-plugin

website/docs/commands/workspace/show.html.md
The `terraform workspace show` command was not included in the workspace documentation. This PR aims to complete the documentation to include it.
=> Create show.html.md for workspace command

website/docs/configuration-0-11/outputs.html.md, website/docs/configuration/outputs.html.md, website/docs/configuration/resources.html.md
For 0.11 I just specified the naming rules; for 0.12, I added some info about
referencing values and tightened up the layout of the optional arguments.
=> website: Expand output values docs

website/docs/import/index.html.md
In the terraform state documentation the verb "map" is widely used to
describe the relationship between an item in the state and in the real world
whereas the verb "attach" is not used anywhere.
=> Make vocabulary more consistent

config/module/storage.go, config/module/storage_test.go, config/module/test-fixtures/manifest-load/linux-paths/modules.json, config/module/test-fixtures/manifest-load/windows-linux/modules.json, config/module/test-fixtures/manifest-load/windows-paths/modules.json
This commit fixes #20712 by properly filtering out any modules that are still using Windows path separators in the modules manifest.
=> core: fix crash loading manifests with Windows paths

config/hcl2shim/paths.go, config/hcl2shim/paths_test.go, helper/resource/testing_config.go
Add the (forces new resource) annotation to the diff output for provider
tests failures when we can. This helps providers narrow down what might
be triggering changes when encountering test failures with the new SDK.
Fixes #20755
=> add (forces new resource) to provider test diffs

website/docs/configuration-0-11/interpolation.html.md
The definition of split was referring the built-in function join. However, join is just one of the ways a string might have been created, and this could cause confusion.
=> website: Simplify wording for split built-in function

command/show.go
Reverting a change that slipped in #20557: the `refresh` step is required to `show` resources in remote state.
Fixes #20642
Any pointers on testing with remote state greatly appreciated - I'd like to avoid another regression.
=> command/show: refresh is required to show remote state

terraform/context_validate_test.go, terraform/eval_validate.go, terraform/eval_validate_test.go, terraform/node_resource_validate.go, terraform/test-fixtures/validate-bad-prov-connection/main.tf, terraform/test-fixtures/validate-bad-resource-connection/main.tf
The resource connection block was not being validated. Merge the two
bodies, with the provider as the override, before validation.
There's still another separate issue around error diagnostics for the connection block. An `*hcl.Diagnostic` is returned with for the missing host key, but when there's an empty snippet block from the missing attribute, `format.Diagnostic` returns the outer resource rather than the connection block. 
Fixes #20816
=> merge connection blocks for validation

website/docs/configuration/functions/cidrhost.html.md, website/docs/configuration/functions/cidrsubnet.html.md
Some users are not accustomed to thinking of IP addresses in a bitwise fashion, so the hope here is to give enough of an introduction to that way of thinking for the reader to understand what the `newbits` and `netnum` arguments represent.
This has been a frequent Q&A topic in the various community forums, so hopefully this will help users to understand what this function is doing (and the related `cidrhost` function, too) and how best to employ it.
=> website: Additional explanation for cidrsubnet function

backend/local/backend_apply.go, states/statemgr/filesystem.go, states/statemgr/migrate.go
When failing to write the state, the local backend writes the state to a local file called `errrored.tfstate`. Previously it would do so by creating a new state file which would use a new serial and lineage. By exorting the existing state file and directly assigning the new state, the serial and lineage are preserved.
=> backend/local: preserve serial and lineage on failure

command/init.go, plugin/discovery/error.go, plugin/discovery/get.go, registry/client.go, registry/errors.go
If the registry is unresponsive, you will now get an error specific to this, rather than a misleading "provider unavailable" type error. Also adds debug logging for when errors like this may occur.
=> Add friendly error for when registry unresponsive

builtin/providers/test/resource_config_mode_test.go, go.mod, go.sum, lang/blocktoattr/doc.go, lang/blocktoattr/fixup.go, lang/blocktoattr/fixup_test.go, lang/blocktoattr/schema.go, lang/blocktoattr/variables.go, lang/blocktoattr/variables_test.go, lang/eval.go, lang/references.go, terraform/graph_builder_plan_test.go, terraform/test-fixtures/graph-builder-plan-attr-as-blocks/attr-as-blocks.tf, vendor/github.com/hashicorp/hcl2/ext/dynblock/variables.go, vendor/modules.txt
For any block content we evaluate dynamically via this API, we'll make a special allowance for users to optionally write members of a list attribute instead as a sequence of nested blocks, thus allowing some
existing provider features that were assuming this capability to continue to support it after v0.12.
This should not be used for any new provider features, and subsequent work we will define a new pattern that allows the same or better expressiveness without relying on distinguishing between two configurations that appear logically equivalent.
---
This provides a path forward for the few cases in existing providers where a nested block type was declared as `Optional`+`Computed` in the schema and the provider logic then distinguished between unset (no blocks at all) vs. explicitly …
=> lang/eval: Apply attr-as-nested-block fixup in EvalBlock

configs/configupgrade/test-fixtures/valid/invalid-resource-name/input/resource.tf, configs/configupgrade/test-fixtures/valid/invalid-resource-name/want/resource.tf, configs/configupgrade/test-fixtures/valid/invalid-resource-name/want/versions.tf, configs/configupgrade/test-fixtures/valid/module-source/input/main.tf, configs/configupgrade/test-fixtures/valid/module-source/want/main.tf, configs/configupgrade/upgrade_native.go
message
In terraform 0.11 and prior it was possible to start a resource name
with a number. This is no longer valid, as the resource name would would
be ambiguous with number values in HCL expressions.
Fixes #19919
I've applied this check to outputs and resources.
=> configs/configupgrade: detect invalid resource names and print a TODO

builtin/providers/test/resource.go, builtin/providers/test/resource_list.go, builtin/providers/test/resource_list_test.go, builtin/providers/test/resource_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go, terraform/diff.go
There were a few holes in the handling of unknowns in the shims:
Because schema.ResourceDiff can't differentiate between unknown
values and new computed values, unknowns can be lost during an update.
If a planned value converted an unknown to a null, restore the unknown
so that it can be correctly replaced in the final plan.
The legacy diff process inserts unknown values into an optional+computed
map. Fix these up in post-plan normalization process, by looking for
known strings that were changed to unknown.
NewRemoved diff values were sometimes left in maps and lists. These are
no longer converted to unknown, but still need to be correctly removed.
Also fixes #20861
=> Better handling of unknowns in sdk shims

command/format/diff.go, command/format/diff_test.go
This PR includes a possible fix for issue #20381 
There was no check if a force new resource is needed when just adding the new value in the plan, this could solve that, but there might be better ways to do this
=> Add force new resource caption when just showing new value

go.mod, go.sum
There are two transitive dependencies present on the current three which
are hosted on `bzr`, which increases the tooling required to compile
Terraform, and fails to compile the new version on Windwos.  This
affects plugin providers as well, making it harder to compile plugins
on Winows.
If `bzr` is not installed, fetching dependencies will fail:
<details>
<summary> Error when Bazaar is not installed</summary>
```
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr
branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk
. in
C:\Users\bltav\go\pkg\mod\cache\vcs\f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339:
exec: "bzr": executable file not found in %PATH%
go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: bzr branch
--use-existing-dir …
```
=> Avoid requiring Bazaar to compile

website/docs/configuration/variables.html.md, website/intro/getting-started/variables.html.md
@nfagerlund let me know if there's a different education/documentation human I should request review from, please!
Terraform 0.12 introduces the ability to define complex variables on the command line or at the UI prompt. I've added a note to the getting started guide and a few examples to the input variable documentation. 
Fixes #18464
=> website: adding examples of complex variables on the command line

configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/input/list-of-obj-as-block.tf, configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/want/list-of-obj-as-block.tf, configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/want/versions.tf, configs/configupgrade/upgrade_body.go, configs/configupgrade/upgrade_test.go, lang/blocktoattr/fixup.go, lang/blocktoattr/schema.go, lang/blocktoattr/variables.go
In order to preserve pre-v0.12 idiom for list-of-object attributes, we'll prefer to use block syntax for them except for the special situation where the user explicitly assigns an empty list, where attribute syntax is
required in order to allow existing provider logic to differentiate from an implicit lack of blocks.
This is a continuation of #20837.
=> configs/configupgrade: Prefer block syntax for list-of-object attributes

config/hcl2shim/values.go, config/hcl2shim/values_test.go
Nulls can't exist in HCL, and the legacy sdk will panic when
encountering them. The map shim already did this, just copy the same
pattern in the list case.
Fixes #20889
=> filter nulls when shimming a config

plugin/grpc_provider.go, plugin/grpc_provider_test.go
Some providers may generate quite large schemas, and the internal
default grpc response size limit is 4MB. 64MB should cover most any use
case, and if we get providers nearing that we may want to consider a
finer-grained API to fetch individual resource schemas.
Fixes #20879
=> increase grpc recv limit

helper/schema/field_writer_map.go, helper/schema/field_writer_map_test.go
Closes #14418
When creating flatten functions in Terraform Providers that return `*schema.Set`, it is possible to return a typed `nil`, e.g.
```go
func flattenHeaders(h *cloudfront.Headers) *schema.Set {
if h.Items != nil {
return schema.NewSet(schema.HashString, flattenStringList(h.Items))
}
return nil
}
```
This previously could cause a panic, e.g.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1881911]
goroutine 1325 [running]:
github.com/hashicorp/terraform/helper/schema.(*MapFieldWriter).setSet(0xc00054bf00, 0xc00073efa0, 0x5, 0x5, 0x5828140, 0x0, 0xc0002cea50, 0xc000e996a8, 0xc001026e40)
/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.11.12/helper/schema/field_writer_map.go:343 …
```
=> helper/schema: Prevent setSet() panic with typed nil

command/format/diagnostic.go, go.mod, go.sum, tfdiags/contextual_test.go, vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/structure.go, vendor/modules.txt
Fixes #20829
HCL2 was originally returning the end of the block as the location for missing attributes. On it's own this wasn't terribly helpful, and terraform ended up looking up the start of the block for error messages. An unintended side effect of this was that attributes missing from nested blocks returned unclear error messages  pointed to the top-level resource, not the nested block.
HCL2 has been updated to return the _start_ of the block, which leads to more precise error messages:
```
Error: Missing required argument
on connection.tf line 5, in resource "null_resource" "foo":
5:   connection {
The argument "host" is required, but no definition was found.
Error: Missing required argument
on connection.tf line 11, in resource "random_id" "id":
11: resource "random_id" "id" {
The …
```
=> command/format: improve "source" of error messages regarding missing arguments

config/hcl2shim/values.go, config/hcl2shim/values_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
A list-like attribute containing null values will present a list to
helper/schema with nils, which can cause panics. Since null values were
not possible in configuration before HCL2 and not supported by the
legacy SDK, return an error to the user.
Revert the filtering of null values from lists, and validate the cty.Values before shimming.
This appears slightly repetitive here, but is far simpler than threading new errors through the shims and every call site, when it's only a single edge case we're trying to detect.
=> Validate configuration shims for nulls in lists

configs/configupgrade/upgrade_expr.go
Previously the `0.12configupgrade` tool would attempt to upgrade a string even after `hil.Parse()` returned an error, which caused much `panic`.
Fixes #20917
=> configs/configupgrade: return if hil.Parse() produces an error.

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/plugin/grpc_provider.go
Stripping out the unchanged NewComputed diffs was a patch for some provider behavior which was fixed in other ways, and is no longer needed.
Removing this behavior allows us to implement correct CusomizeDiffFuncs in
providers so that they can mark fields with empty values as computed
during a plan.
=> Allow all planned computed diff fields

lang/eval.go, lang/eval_test.go
Previously it was calling directly to hcldec.Variables, and thus missing the special fixups we do inside `ReferencesInBlock` to deal with Terraform-specific concerns such as our attribute-as-blocks preprocessing.
=> lang: EvalBlock should use ReferencesInBlock

website/docs/configuration/attr-as-blocks.html.md
The re-introduction of some of the ambiguity between argument and nested block syntax (for compatibility with existing provider patterns) unfortunately leads to some interesting consequences for attributes using this mode.
While the behavior is generally as before in straightforward cases, this page aims to spell out some of the different usage patterns explicitly for the benefit of those writing more complex configurations, such as generic re-usable modules where using argument vs. block syntax leads to some real differences. The ambiguity of the JSON syntax for the Terraform language also requires some special attention.
This page is intentionally not linked from anywhere in the part of the website maintained in the Terraform repository. Instead, it can be linked from the provider …
=> website: Documentation of the special "attributes as blocks" mode

configs/configupgrade/test-fixtures/valid/number-literals/input/number-literals.tf, configs/configupgrade/test-fixtures/valid/number-literals/want/number-literals.tf, configs/configupgrade/test-fixtures/valid/number-literals/want/versions.tf, configs/configupgrade/upgrade_expr.go
The v0.12 language supports numeric constants only in decimal notation, as a simplification of the language. For rare situations where a different base is more appropriate, such as unix-style file modes, we've found it better for providers to accept a string containing a representation in the appropriate base, since that way the interpretation can be validated and it will be displayed in the same way in the rendered plan diff, in outputs, etc.
We use `hcl1token.Token.Value()` here to mimick how HCL 1 itself would have interpreted these, and then format them back out in the canonical form, which implicitly converts any non-decimal constants to decimal on the way through.
This closes #20933 by addressing the v0.12.0-release-blocking part. That issue also raised a situation where the parse …
=> configs/configupgrade: Normalize number literals to decimal

website/docs/provisioners/index.html.markdown
Clarifying the behavior for destroy-time provisioners when a resource is tainted.
=> Clarifying behavior for destroy-time provisioners

lang/blocktoattr/fixup.go, lang/blocktoattr/fixup_test.go, lang/blocktoattr/variables_test.go
When a top-level list-of-object contains an attribute that is also list-of-object we need to do the fixup again inside the nested body (using our synthetic attributes-only schema) so that the attr-as-blocks mechanism can apply within the nested blocks too.
Fixes #20934.
=> lang/blocktoattr: Apply fixup within already-fixed-up blocks too

command/init.go, plugin/discovery/error.go, plugin/discovery/get.go
Updates to throw a specific error if using the defined public registry vs. another registry, so that we only display info to go to status.hashicorp.com if you're using the public registry.
cc @findkim
=> Only display status link if public registry used

builtin/providers/test/resource_state_func.go, builtin/providers/test/resource_state_func_test.go, helper/plugin/grpc_provider.go, helper/schema/shims.go, helper/schema/shims_test.go
The synthetic config value used to create the Apply diff should contain
no unknown config values. Any remaining UnknownConfigValues were due to
that being used as a placeholder for values yet to be computed, and
these should be marked NewComputed in the diff.
Fixes: #20958
=> Don't allow unknown values in the config when generating the apply Diff

website/layouts/functions.erb
Find-in-page is still supported with the 'expand/collapse all' control. And until you need cmd-F, this makes it much easier to tell where you are and what's nearby.
This uses new features that just went into terraform.io on Friday.
=> website: in functions sidebar, default lists to collapsed

command/output.go
Previously this command was setting the state path to the default state
file, instead of honoring the path set in the backend configuration.
Fixes #20983
=> command/output: get the state path from the workspace or CLI argument

lang/funcs/collection.go, lang/funcs/collection_test.go, lang/functions.go, website/docs/configuration/functions/coalesce.html.md
The go-cty coalesce function, which was originally used here, returns the
first non-null element from a sequence. Terraform 0.11's coalesce,
however, returns the first non-empty string from a list of strings.
This new coalesce function aims to preserve terraform's documented
functionality while adding support for additional argument types. The
tests include those in go-cty and adapted tests from the 0.11 version of
coalesce.
This uncovered two changes of note between 0.11 coalesce and 0.12 coalesce: `coalesce` now accepts a single argument, and `coalesce` no longer returns `""` if all arguments are empty strings. These are both changes based on the 0.11 test cases. I believe that, in practice, neither are cases that users are depending on, but I will revisit if needed if problems arise …
=> funcs/coalesce: return the first non-null, non-empty element from a sequence

command/output.go, command/state_list.go
If the user supplied a state path via the `-state` flag and terraform
was running in a workspace other than `default`, the state was not being
loaded properly. Fixes #19920
=> command/state_list.go: fix bug loading user-defined state

website/docs/provisioners/null_resource.html.markdown, website/layouts/docs.erb
This page is useful, but it's easier to tell what it's for if we
put it next to the page about connections.
=> website: null_resource isn't a type of provisioner

configs/module_merge_body.go, configs/module_merge_test.go, configs/test-fixtures/valid-modules/override-dynamic-block-base/a_override.tf, configs/test-fixtures/valid-modules/override-dynamic-block-base/base.tf, configs/test-fixtures/valid-modules/override-dynamic-block-override/a_override.tf, configs/test-fixtures/valid-modules/override-dynamic-block-override/base.tf, configs/util.go
Previously we were treating `dynamic` blocks in configuration the same as any other block type when merging config bodies, so that `dynamic` blocks in the override would override any `dynamic` blocks present in the base, without considering the `dynamic` block type specified in the first label.
It's more useful and intuitive for us to treat dynamic blocks as if they are instances of their given block type for the purpose of overriding. That means a `foo` block can be overridden by a `dynamic "foo"` block and vice-versa, while `dynamic` blocks of different types do not interact at all during overriding.
This requires us to recognize dynamic blocks and treat them specially during decoding of a merged body. We leave them unexpanded here because this package is not responsible for dynamic …
=> configs: Handle "dynamic" blocks as special during override merging

go.mod, go.sum, vendor/github.com/hashicorp/hcl2/hcl/ops.go, vendor/github.com/hashicorp/hcl2/hcl/pos.go, vendor/github.com/hashicorp/hcl2/hcl/pos_scanner.go, vendor/modules.txt, website/upgrade-guides/0-12.html.markdown
The division operator now always performs floating point division, whereas before it would choose between float and int division based on the types of its arguments.
This adds (via an HCL upgrade) a specific error message for when a fractional number is used as an index in HCL, and then we add additional upgrade guidance providing a specific solution to the problem: the `floor` function.
Sadly we don't have enough context in the current design of the upgrade tool to make this fix automatic. With some refactoring it may be possible to apply the fix automatically within list brackets, but since that is a relatively complex change we'll first try this manual solution prompted by an error message, because in practice so far we've seen this reported only in the context of list indexing and our …
=> Document division behavior change in v0.12 upgrade guide

builtin/providers/test/provider.go, builtin/providers/test/resource_import_removed.go, builtin/providers/test/resource_import_removed_test.go, helper/resource/testing_import_state.go, helper/schema/field_reader.go, helper/schema/resource.go
Due to the lossiness of our legacy models for diff and state, shimming a diff and then creating a state from it produces a different result than shimming a state directly. That means that `ImportStateVerify` no longer works as expected if there are any `Computed` attributes in the schema where `d.Set` isn't called during `Read`.
Fixing that for every case would require some risky changes to the shim behavior, so we're instead going to ask provider developers to address it by adding `d.Set` calls where needed, since that is the contract for `Computed` anyway -- a default value should be produced during `Create`, and thus by extension during `Import`.
However, a common situation where this occurs is attributes marked as `Removed`, since all of the code that deals with them has generally …
=> helper/resource: Ignore Removed attributes for ImportStateVerify

builtin/providers/test/provider.go, builtin/providers/test/resource_undeletable.go, terraform/context_apply_test.go, terraform/eval_apply.go
When an operation fails, providers may return a null new value rather than returning a partial state. In that case, we'd prefer to keep the old value so that we stand the best chance of being able to retry on a subsequent run.
Previously we were making an exception for the delete action, allowing the result of that to be null even when an error is returned. In practice that was a bad idea because it would cause Terraform to lose track of the object even though it might not actually have been deleted.
Now we'll retain the old object even in the delete case. Providers can still return partial new objects if they were able to partially complete a delete operation, in which case we'll discard what we had before, but if the result is null with errors then we'll assume the delete failed …
=> core: Keep old value on error even for delete

builtin/providers/test/diff_apply_test.go, builtin/providers/test/resource_config_mode.go, builtin/providers/test/resource_config_mode_test.go, helper/schema/shims.go, terraform/diff.go
We previously attempted to make the special diff apply behavior for nested sets of objects work with attribute mode by totally discarding attribute mode for all shims.
In practice, that is too broad a solution: there are lots of other shimming behaviors that we _don't_ want when attribute mode is enabled. In particular, we need to make sure that the difference between null and
empty can be seen in configuration.
As a compromise then, we will give all of the shims access to the real `ConfigMode` and then do a more specialized fixup within the diff-apply logic: we'll construct a synthetic nested block schema and then use that to run our existing logic to deal with nested sets of objects, while using the previous behavior in all other cases.
In effect, this means that the special new …
=> helper/schema: Use a more targeted shim for nested set diff applying

configs/configupgrade/test-fixtures/valid/noop/input/resources.tf, configs/configupgrade/test-fixtures/valid/noop/want/resources.tf, configs/configupgrade/upgrade_expr.go
The expression upgrade functionality mostly ignores comments because in the old language the syntax prevented comments from appearing in the middle of expressions, but there was one exception: object expressions.
Because HCL 1 used `ObjectType` both for blocks and for object expressions, that is the one situation where something we consider to be an expression could have inline attached comments in the old language.
We migrate these here so we don't lose these comments that don't appear anywhere else. Other comments get gathered up into a general comments set maintained inside the analysis object and so will be printed out as required _between_ expressions (or rather: between _attributes_), just as they did before.
This fixes #21005.
=> configs/configupgrade: Preserve comments on items in object exprs

configs/configupgrade/upgrade.go
Previously we were trying to access a field of the analysis object before checking if analysis produced errors. The analysis function usually returns a nil analysis on error, so this would result in a panic whenever
that happened.
Now we'll dereference the analysis object pointer only after checking for errors, so we'll get a chance to report the analysis error to the user.
We don't have a new test covering this here because I didn't actually have a repro for this situation: in this case, it's clear that the old code was incorrect in retrospect, so I just fixed it. The new codepath still fails, but it fails in a way that returns useful context to the user, rather than panicking.
This will fix #20908 by removing the panic and allowing the real analysis error to shine through. That may then …
=> configs/configupgrade: Don't panic if analyzer fails

terraform/context_validate_test.go, terraform/evaluate.go
Earlier on in the v0.12 development cycle we made the decision that the validation walk should consider input values to always be unknown so that validation is checking validity for all possible inputs rather than for a specific set of inputs; checking for a specific set of inputs is the responsibility of the plan walk.
However, we didn't implement that in the best way: we made the `terraform validate` command force all of the input variables to unknown but that was insufficient because it didn't also affect the implicit validation walk we do as part of `terraform plan` and `terraform apply`, causing those to produce confusingly-different results.
Instead, we'll address the problem directly in the reference resolver code, ensuring that all variable values will always be treated as an …
=> core: Input variables are always unknown during validate

helper/schema/schema.go
This change documents that `ValidateFunc` is also available for use on TypeMap attributes.
Support for map validation has been added through https://github.com/hashicorp/terraform/pull/3505
=> Document that ValidateFunc works on maps.

website/docs/modules/composition.html.markdown
The example above treats recordsets as a list, but the declaration was for a single object.
=> website: Fix incorrect example in Module Composition page

website/docs/configuration/terraform.html.md
Using Terraform `v0.12.0-beta2` assigning the map as described in the example results in the error below when running `init`.
```
Error: Unsupported argument
on terraform.tf line 12, in terraform:
12:   required_providers = {
An argument named "required_providers" is not expected here. Did you mean to
define a block of type "required_providers"?
```
Following the error's advice and defining a `required_providers` block rather than assigning a map resolves the issue. Tested that this is actually the new 0.12 behavior by setting aws version to 2.9 (currently does not yet exist) and I receive the proper error message: _No provider "aws" plugins meet the constraint ">= 2.9"._
I've also set the required AWS provider version to 2.7 for the purpose of this example, the [first version to support …
=> update required_providers block for terraform 0.12 compatibility

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/schema/shims.go, helper/schema/shims_test.go
`removeConfigUnknowns` need to remove the value completely from the config
map. Removing this value allows `GetOk` and `GetOkExists` to indicate if the
value was set in the config in the case of an Optional+Computed attribute.
Fixes #21007
=> delete unknown values from apply config altogether

builtin/providers/test/resource_map.go, builtin/providers/test/resource_map_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
Make sure values removed from a map during apply are not copied into the
new map when the plan didn't correctly mark a computed map as unknown.
Fixes #21070 as far as core is concerned. The provider will need a couple updates as well.
=> Fixes for maps in shims

plugin/discovery/get.go
```
$ terraform init
Initializing the backend...
- Checking for available provider plugins...
- Downloading plugin for provider "aws (terraform-providers/aws)" (2.7.0)...
```
```
$ terraform init
Initializing the backend...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (terraform-providers/aws) 2.7.0...
```
=> plugin/discovery: Fix quoting of provider name

go.mod, go.sum
By upgrading this to a version that supports Go Modules, we can avoid the redundant dependencies `labix.org/v2/mgo` and `launchpad.net/gocheck`.
These dependencies come via `hashicorp/consul`, which we have vendored for the Consul backend.
There are no changes to the go-msgpack code here; we're just adopting a newer version that has a go.mod present so that its dependencies can be determined more accurately.
This is an immediate-term fix for #21080. If we later add a new dependency that is either directly served from a Bazaar repository or depends on something that is then the requirement for a working `bzr` will return; permanently avoiding `bzr` is not a goal here, but to the extent that we don't currently have any reason to need these dependencies, this allows us hopefully to avoid …
=> vendor: go get github.com/hashicorp/go-msgpack@v0.5.4

go.mod, go.sum, plans/objchange/compatible_test.go, terraform/context_refresh_test.go, terraform/eval_count.go, terraform/node_data_refresh.go, terraform/test-fixtures/refresh-data-count/refresh-data-count.tf, vendor/github.com/zclconf/go-cty/cty/gocty/out.go, vendor/github.com/zclconf/go-cty/cty/path.go, vendor/github.com/zclconf/go-cty/cty/value_init.go, vendor/github.com/zclconf/go-cty/cty/value_ops.go, vendor/modules.txt
The count for a data resource can potentially depend on a managed resource that isn't recorded in the state yet, in which case references to it will always return unknown.
Ideally we'd do the data refreshes during the plan phase as discussed in #17034, which would avoid this problem by planning the managed resources in the same walk, but for now we'll just skip refreshing any data resources with an unknown count during refresh and defer that work to the apply phase, just as we'd do if there were unknown values in the main configuration for the data resource.
This fixes #21047, by deferring the data resources in its repro config to apply time, and thus allowing the plan/apply flow to complete.
Once #17034 is resolved in a later release, we should be able to get this done during the plan …
=> core: Allow data resource count to be unknown during refresh

command/format/diff.go, command/format/diff_test.go
When rendering the diff, the NoOp changes should come from the LCS
sequence, rather than the new sequence. The two indexes will not align
in many cases, adding the wrong new object or indexing out of bounds.
Fixes: #21073
=> command/format: take noop changes from lcs

command/ui_input.go, command/ui_input_test.go
Once you start reading from stdin, that is a blocking call that will
never finish. So when a context is canceled causing the input method to
return, the read will remain blocking in the running goroutine.
There isn't a real solution for it (e.g. its not possible to unblock the
read) so the only solution is to make the reader reusable.
=> Make sure UIInput keeps working after being canceled

go.mod, go.sum, vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go, vendor/modules.txt
This fixes a bug in the `formatlist` function where it would panic if given an unknown list as an argument.
(Closes #21119.)
=> vendor: go get github.com/zclconf/go-cty@master

helper/resource/grpc_test_provider.go, plugin/grpc_provider.go
The grpc server does not shutdown when the listener is closed. Since
tests aren't run through go-plugin, which has a separate RPC Shutdown
channel to stop the server, we need to track and stop the server
directly.
This should fix #21104, and prevent old server instances from accumulating after tests.
=> Stop grpc server when running ACC tests

states/statefile/testdata/roundtrip/v3-simple.in.tfstate, states/statefile/testdata/roundtrip/v3-simple.out.tfstate, states/statefile/version3_upgrade.go
We used to allow "foo.1" etc as a dependency reference, but now it's "foo[1]".
Fixes #20835
=> states/statefile: upgrade legacy dependency syntax

lang/funcs/collection.go, lang/funcs/collection_test.go, lang/functions_test.go
Allow for more precise type handling 
- `slice`
- Handle tuples, and return precise types for the result. 
- Return a slice even when individual elements are unknown
- `flatten`
- Flatten can still return tuples or lists even when individual element are unknown.
- Handle individual elements as well as series.
- `chunklist`
- Should be able to return chunks containing unknown values
- `coalescelist`
- Should accept lists and tuples, and return a dynamic types when the arguments are not homogeneous.
- `contains`
- Sets are no longer going to be automatically converted, so we need to handle those in contains.
=> lang/funcs: better type handling in interpolation funcs

builtin/providers/test/resource_list_test.go, go.mod, go.sum, helper/schema/field_reader_config.go, plans/objchange/compatible.go, plans/objchange/compatible_test.go, terraform/resource.go, terraform/resource_test.go, vendor/github.com/hashicorp/hcl2/ext/dynblock/expand_body.go, vendor/github.com/hashicorp/hcl2/ext/dynblock/unknown_body.go, vendor/github.com/hashicorp/hcl2/hcl/json/scanner.go, vendor/modules.txt
If a `dynamic` block (in the HCL dynamic block extension sense) has an unknown value for its `for_each` argument, it gets expanded to a single placeholder block with all of its attributes set to a unknown values.
We can use this as part of a heuristic to relax our object compatibility checks for situations where the plan included an object that appears to be (but isn't necessarily) such a placeholder, allowing for the fact that the one placeholder block could be replaced with zero or more real blocks once the `for_each` value is known.
Previously our heuristic was too strict: it would match only if the only block present was a `dynamic` placeholder. In practice, users may mix `dynamic` blocks with static blocks of the same type, so we need to be more liberal to avoid generating incorrect …
=> plans/objchange: Fix handling of dynamic block placeholders

backend/remote/backend.go, backend/remote/backend_test.go, command/meta_backend.go
The remote backend schema changed in terraform 0.12, causing a panic
when 0.11 tries to load it. While we do not support downgrading
configurations, we should prevent panics where possible.
We may consider some form of backend schema versioning in the future.
Fixes #21190
NOTE: The error message is not terribly accurate or informative:
```
Error loading previously configured backend:
Error configuring the backend "remote": the cached backend configuration is not valid for this version of terraform
Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".
```
I could add a specific return error type and add a new message that specifically states …
=> backend/remote: fix panic when loading a 0.12 cached backend

terraform/resource.go, terraform/resource_test.go
With the new ConfigModeAttr, we can now have complex structures come in
as attributes rather than blocks. Previously attributes were either
known, or unknown, and there was no reason to descend into them. We now
need to record the complete path to unknown values within complex
attributes to create a proper diff after shimming the config.
=> more precise handling of ComputedKeys in config

backend/remote-state/pg/backend.go
This change fixes an error I get:
Error: pq: too many connections for role "asdf"
because I can only have so many connections.
=> Don't leak so many connections in the pg backend

website/docs/configuration/attr-as-blocks.html.md
- Note that we intentionally omitted it from the sidebar, to reduce confusion.
- Write a summary up top so you can stop reading sooner if you don't actually need this.
=> (website) Adjust intro of attr-blocks page

helper/validation/validation.go, helper/validation/validation_test.go
This function provides schema validation for float values.
=> Added FloatBetween validation function.

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/schema/field_reader_config.go
Computed primitive values must see the UnknownConfigValue or they are
assumed to be unchanged. Restrict the usage of the protov5 ComputedKeys
to containers.
=> restrict the ComputedKeys usage to containers

command/012checklist.go, commands.go
(Please note that this PR is targeted at the `v0.11` maintenance branch, not at the `master` branch.)
There's a small set of tasks that are easier to do if handled _before_ upgrading to Terraform 0.12, while still on 0.11:
* Upgrading to compatible provider versions. Not doing this doesn't actually _hurt_ once upgraded to Terraform 0.12 (it will produce suitable error messages itself if not compatible) but doing it ahead of time will allow the user to deal with any provider-level upgrade steps separately from the core upgrade, thus reducing risk compared to doing everything at once.
* Fixing any resource names that v0.12 would consider invalid because they start with digits. Dealing with this in 0.11 is easier because the 0.11 `terraform state mv` command will accept these now-invalid …
=> command/0.12checklist: Terraform 0.11 command to help prep for 0.12

builtin/providers/terraform/data_source_state_test.go, builtin/providers/terraform/test-fixtures/version4.tfstate, terraform/state.go, terraform/state_test.go
Although Terraform v0.11 can't generate this format or use it as the basis for new operations, we will implement it enough that `terraform_remote_state` can read it, in order to give more flexibility when upgrading from 0.11 to 0.12 in complex environments where remote state is used for connectivity between subsystems. With this in place, users have more freedom in what order they upgrade their individual subsystems to Terraform 0.12.
(Note that this PR is targeting the v0.11 branch, not the master branch. This is intended to be included in one final 0.11 release in order to reduce upgrade friction.)
=> providers/terraform: support state format 4 in remote state

terraform/eval_diff.go
Similar to the line below in the same file, schema should be the parameter, and the planned value the receiver. 
https://github.com/hashicorp/terraform/blob/15f7f8049f4a16c030e1848f30a90992293794ae/terraform/eval_diff.go#L205
@apparentlymart this fixed the issue I was experiencing locally.
=> Fix incorrect direction of TestConformance

website/upgrade-guides/0-12.html.markdown
Our original upgrade guide was drafted while some things were still in flux and not all of our upgrade tooling was in place yet.
This redraft now attempts to be more specific and direct, showing exact commands to run and (where relevant) exact error messages that Terraform might return.
I also took this opportunity for some general copy-editing, though we'll probably want to do one more pass of that alone (without changing any content at the same time) before final release.
This new content presumes the existence of a Terraform v0.11.14 release, which isn't published yet at the time of writing but should be published before v0.12.0 final, once we've done final verification and review of the upgrade path including it.
=> website: v0.12 upgrade guide revisions preparing for final release

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/schema/schema.go
The new type system only has a Number type, but helper schema
differentiates between Int and Float values. Verify that a new config
value is an integer during Validate, because the existing WeakDecode
validation will decode a float value into an integer while the config
FieldReader will attempt to parse the float exactly.
Fixes #21272
=> validate integers when using protoV5

helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
When normalizing the state during read, if the resource was previously
imported, most nil-able values will be nil, and we need to prefer the
values returned by the latest Read operation. This didn't come up
before, because Read is usually working with a state create by plan and
Apply which has already shaped the state with the expected empty values.
Having the src value preferred only during Apply better follows the
intent of this function, which should allow Read to return whatever
values it deems necessary. Since Read and Plan use the same
normalization logic, the implied Read before plan should take care of any
perpetual diffs.
I made the logic easier to read, but the only functional change is the addition of `&& apply` to the outermost condition.
Fixes #21266
=> only hold back empty container changes in apply

configs/configupgrade/test-fixtures/valid/inline-comments/input/main.tf, configs/configupgrade/test-fixtures/valid/inline-comments/want/main.tf, configs/configupgrade/test-fixtures/valid/inline-comments/want/versions.tf, configs/configupgrade/upgrade_expr.go
The configupgrade tool was not writing `LineComments` for lists. Now it
is!
Fixes #21155
=> configs/configupgrade: preserve in-line comments for lists

terraform/node_resource_apply_instance.go
This is a "should never happen" case, because we shouldn't ever have resources in the plan that aren't in the configuration, but since we've got a report of a crash here (which went away before we got a chance to debug it) here's just an extra guard to ensure that we'll still exit gracefully in that case.
If we see this error crop up again in future, it'd be nice to gather a full trace log so we can see what `GraphNodeAttachResourceConfig` did and why it did not attach a configuration.
This closes #21258, but it does not fix it: instead, it hopefully arranges for us to get more information (the resource address, in particular) in a subsequent bug report if this manages to crop up again.
=> core: Don't panic if NodeApplyableResourceInstance has no config

configs/configupgrade/test-fixtures/valid/variable-type/input/variables.tf, configs/configupgrade/test-fixtures/valid/variable-type/want/variables.tf, configs/configupgrade/upgrade_expr.go, website/upgrade-guides/0-12.html.markdown
The upgrade tool is assuming that a type of `"list"` means `list(string)` and a type of `"map"` means `map(string)`, because that was what we documented those as meaning in prior versions.
In practice, Terraform 0.11 was lacking some validation which allowed more complex nested structures in some cases even though they were pretty inconvenient to use due to other language limitations.
The upgrade tool doesn't have enough context to make a reliable decision on this, so instead we'll rely on the upgrade guide for this. We don't need a `TF-UPGRADE-TODO` comment in this case because we reserve those for things where a subsequent operation might cause the configuration to be misinterpreted, rather than just causing an error. Instead, we'll show an example of the comment in the upgrade guide so …
=> website: 0.12 upgrade guide about variable type constraints

command/012checklist.go
(Please note that this is targeted at the `v0.11` branch, not the `master` branch)
Although it's not super important to deal with these before upgrading to 0.12, some prior warning of it during checklist will be helpful to those with complicated, decomposed environments so that they can avoid starting on the upgrade process and then finding out partway that they have some module somewhere that needs a breaking change to fix this.
Because it requires a breaking change to the module to resolve, this is something that may be better dealt with as a separate change before beginning the 0.12 upgrade, to avoid changing too much at once.
As with the previous work on this tool, I tested this manually rather than via automated tests, as an opportunity cost tradeoff for a "best effort" codepath that …
=> command/0.12checklist: Detect reserved variable names

builtin/providers/test/resource_config_mode.go, builtin/providers/test/resource_config_mode_test.go, go.mod, go.sum, vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go, vendor/github.com/zclconf/go-cty/cty/function/stdlib/sequence.go, vendor/modules.txt
Update go-cty to fix a bug when converting an empty tuple to a set.
Fixes #21314
=> Fix inconsistent element types with tuple literals

website/docs/configuration/providers.html.md
Ran a format on the example code blocks provided and added quotes around the provider alias example for `"aws.west"` to allow it to be formatted without errors and to bring it in line with the example found [here](https://www.terraform.io/docs/configuration-0-11/providers.html).
=> Terraform format and syntax correction

internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/test-fixtures/invalid-version-constraint/.gitignore, internal/initwd/test-fixtures/invalid-version-constraint/root.tf
Fixes #21328
If the `version` attribute is used on modules whose source will be retrieve with `go-getter` (not Registry or local relative file paths), then Terraform will panic and crash.
This PR fixes the panic by preventing the use of the `version` attribute for module sources that would be retrieved with go-getter. I'm not sure if there are any cases where the version constraint should be allowed in that scenario?
=> Fix panic on init for go-getter modules w version

website/upgrade-guides/0-12.html.markdown
A longer-form guide will follow in the Sentinel section of the Terraform Enterprise documentation, once it's ready. For now, this section isn't saying anything useful since it was always just a stub for a guide we planned to write later.
=> website: Remove the Sentinel section from 0.12 upgrade guide

website/docs/configuration/variables.html.md
=> docs: fixed typo

states/statefile/roundtrip_test.go, states/statefile/write.go
Any time a new state is written, the current terraform version should be
recorded.
Fixes #21379
=> always write the current state terraform_version

website/upgrade-guides/0-12.html.markdown
This adds details for using Sentinel in Terraform 0.12. It largely
links to the corresponding guide in the Terraform Enterprise
documentation.
=> website: add Sentinel 0.12 upgrade guide details

command/init.go, command/meta_backend.go
There are a number of use cases that can require a user to select a workspace after initializing Terraform.
To make sure we cover all these use cases, we will always call the selectWorkspace method to verify a valid workspace is already selected or (if needed) offer to select one before moving on.
Fixes #21224
=> Always try to select a workspace after initialization (v0.12)

backend/remote-state/gcs/client.go
Currently if bad lock ID is passed, terraform errors with:
Failed to unlock state: strconv.ParseInt: parsing foo: invalid syntax
We should give user better hint what is wrong.
Closes #21447
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
=> backend/remote-state/gcs/client.go: make Unlock error message more clear

terraform/node_resource_abstract.go
It is possible for s.Current to be nil. This was hard to reproduce, so
the root cause is still unknown, but we can guard against the symptom.
=> core: don't panic in NodeAbstractResourceInstance References()

website/docs/backends/types/s3.html.md
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request
***
**Changes proposed in this pull request:**
* Document AWS_SDK_LOAD_CONFIG requirement when setting the S3 Backend AWS profile through the AWS_PROFILE variable.
**Fixes:**
There are multiple (closed) issues about this with calls for documentation, such as:
* https://github.com/terraform-providers/terraform-provider-aws/issues/233
* https://github.com/terraform-providers/terraform-provider-aws/issues/1184
* …
=> Document AWS_SDK_LOAD_CONFIG on s3 backend

command/jsonplan/plan.go, command/jsonplan/plan_test.go, command/jsonplan/values_test.go, command/test-fixtures/show-json/basic-create/output.json, command/test-fixtures/show-json/modules/output.json
The `omitUnknowns` and `unknownAsBool` functions were previously trying hard to preserve the same collection types in the output as they had in the input, by attempting to keep everything matched up so that the results would be valid.
Unfortunately, this turns out to be a harder problem than we originally thought: it was possible for a collection value going in to produce inconsistent element types out (and thus a panic) in the following
situations:
- when a collection with mixed known and unknown values was passed in to `omitUnknowns`.
- when a collection of collections where the inner collections are a mixture of empty and not empty in `unknownAsNull`.
The results of these functions are only used to marshal to JSON anyway, and JSON serialization can't distinguish between the three …
=> command/jsonplan: Don't panic with mixtures of known/unknown/empty

builtin/providers/test/resource_map.go, builtin/providers/test/resource_map_test.go, helper/schema/schema.go
While there was already a check in the sdk to filter unknowns from
validation, it missed the case where those were in simple lists and maps.
Fixes #21419
=> filter unknowns from simple lists and maps in sdk

command/init.go, command/init_test.go, command/meta_backend.go, command/meta_backend_migrate.go
This was the same outcome, caused by 2 different issues.
The first was that `init` is supposed to be idempotent, and calling init with no `-backend-config` flags should accept the stored config if the hash matches.
Second was that when the config did need to be compared, the saved result had already been pre-processed by `PrepareConfig` and was no longer identical to the given config.
Fixes #21189
=> init always prompts for migration with most remote backend configurations

lang/blocktoattr/fixup_test.go, lang/blocktoattr/schema.go
If a dynamic block is evaluated zero times, the body content will
contain 0 blocks. Allow the probe for ConfigModeAttr to accept that no
blocks with a matching attribute should still be converted to a block if
they are called with dynamicExpand.
Fixes #21373
=> allow empty dynamic blocks with ConfigModeAttr

command/jsonplan/plan.go, command/jsonplan/values_test.go, command/show_test.go, command/test-fixtures/show-json/basic-delete/output.json, command/test-fixtures/show-json/basic-update/output.json
We were somewhat inconsistent with return values in "after_unknown". This commit fixes that by removing some redundant (and panicky) code.
Fixes #21415 (via #21448)
With bonus fixes: typo, embarrassing debug code.
=> command/show (plan -json): fix panic

configs/configload/loader_load.go, configs/configload/loader_load_test.go, configs/configload/test-fixtures/add-version-constraint/.terraform/modules/modules.json, configs/configload/test-fixtures/add-version-constraint/add-version-constraint.tf, internal/initwd/module_install_test.go, internal/initwd/test-fixtures/invalid-version-constraint-local/.gitignore, internal/initwd/test-fixtures/invalid-version-constraint-local/root.tf, internal/initwd/test-fixtures/invalid-version-constraint/root.tf
Previously, adding a version constraint to a module that was previously recorded without a version in the module manifest would cause a panic.
Instead, we now use a slight variant of the "dependencies have changed" error that doesn't try to print out a specific version number.
=> configs/configload: Don't panic when version constraint is added

command/jsonconfig/config.go, command/test-fixtures/show-json/nested-modules/main.tf, command/test-fixtures/show-json/nested-modules/modules/main.tf, command/test-fixtures/show-json/nested-modules/modules/more-modules/main.tf, command/test-fixtures/show-json/nested-modules/output.json
In the unlikely event that a moduleCall has a nil config - for example,
if a nested module call includes a variable with a typo in an
attribute - continue gracefully.
I am concerned that there are repercussions for sentinel users, so I've opened #21568 to capture the root cause. 
Fixes #21543
=> command/show (-json): fix panic if a moduleCall has a nil config

website/docs/providers/type/community-index.html.markdown
Adding additional links for new Terraform community providers;
- 1Password
- Cloud Foundry
- CodeClimate
- Kafka Connect
- SignalFX - Update to new SignalFX provider (currently in TPDP)
=> [Website] new community links + update signalFX

lang/funcs/collection.go, lang/funcs/collection_test.go, lang/functions_test.go
`matchkeys` was returning a (false) error if the searchset was a
variable, since then the type of the keylist and searchset parameters
would not match.
This does slightly change the behavior: previously matchkeys would
produce an error if the parameters were not of the same type, for e.g.
if searchset was a list of strings and keylist was a list of integers.
This no longer produces an error.
=> lang/funcs: fix error when `matchkeys` encountered a variable

backend/local/backend_plan.go, backend/local/backend_plan_test.go
This unusual situation isn't supposed to arise in normal use, but it can come up in practice in some edge-case scenarios where Terraform fails in a severe way during a `create_before_destroy`.
Some earlier versions of Terraform also had bugs in their handling of deposed objects, so this may also arise if upgrading from one of those older versions with some leftover deposed objects in the state.
This fixes #21396.
---
Some additional context:
In working on this I noticed that _in principle_ the specific situation I covered in the test here could be simplified to just a normal `create_before_destroy` in the UI, because that is effectively what's going to happen anyway.
However, the UI handling of deposed instances is generalized to deal with a bunch of other similar edge-cases around …
=> backend/local: don't panic when an instance has only a deposed object

lang/functions.go, lang/functions_test.go, website/docs/configuration/functions/range.html.md, website/layouts/functions.erb
This is similar to the function of the same name in Python, generating a sequence of numbers as a list that can then be used in other sequence-oriented operations.
The primary use-case for it is to turn a count expressed as a number into a list of that length, which can then be iterated over or passed to a collection function to produce that number of something else, as shown in the example at the end of its documentation page, which is also duplicated here for easier reference:
```hcl
variable "name_counts" {
type    = map(number)
default = {
"foo" = 2
"bar" = 4
}
}
locals {
expanded_names = {
for name, count in var.name_counts : name => [
for i in range(count) : format("%s%02d", name, i)
]
}
}
output "expanded_names" {
value = local.expanded_names
}
#
```
This has been hanging out in …
=> lang: "range" function

command/jsonplan/plan.go, command/show.go, command/show_test.go, command/test-fixtures/show-json/basic-create/output.json, command/test-fixtures/show-json/basic-delete/output.json, command/test-fixtures/show-json/basic-update/output.json, command/test-fixtures/show-json/modules/output.json
A terraform planfile contains a state snapshot with certain resources updated
(those which get refreshed before plan, such as outputs and datasources). 
Previously `terraform show -json $PLANFILE` was displaying the current state instead of the planfile's state.
This caused an issue when the state included a `terraform_remote_state`
datasource. The datasource's state gets refreshed - and therefore
upgraded to the current state version - during plan, but that won't
persist to state until apply. 
In most cases, the json state parser can handle resources in state that haven't been upgraded yet. This particular problem is specific to `terraform_remote_state` datasources due to their unusual and unique schemas, which include `cty.DynamicPseudoType` - the decoder could not translate the older …
=> command/show (json): marshal the state snapshot included with the plan file

website/docs/configuration/expressions.html.md
Based on some common questions and feedback since the v0.12.0 release, here we add some small additional content to the documentation for "dynamic" blocks, covering how to access the keys of the collection being iterated over and how to fold multiple collections into a single one to achieve the effect of a nested iteration.
These have each come up a couple times already, but the ones I have to hand are #21533 and terraform-providers/terraform-provider-aws#8830.
=> website: Additional information about "dynamic" blocks

builtin/providers/test/resource_timeout_test.go, command/apply_test.go, command/command_test.go, command/refresh_test.go, helper/plugin/grpc_provider.go, helper/resource/state_shim.go, internal/tfplugin5/tfplugin5.pb.go, internal/tfplugin5/tfplugin5.proto, plugin/grpc_provider.go, providers/provider.go, states/state_deepcopy.go, states/state_test.go, terraform/eval_diff.go, terraform/eval_refresh.go
The Private data was lost in a couple places, and not detected due to the Private data not being used heavily by the current SDK.
This also adds the Private data to the `ReadResource` call. While not currently used, it makes the use of the data more consistent, and would allow for more flexibility with future providers.
Fixes #21528
=> Make sure resource private data is carried through the entire resource lifecycle

terraform/eval_validate.go, terraform/eval_validate_test.go
Assume "ref" can be nil and report an invalid reference to
the user instead of crashing.
This is a regression from terraform 0.11 and now fails in 0.12.0.
Including test case.
=> Fix panic on invalid depends_on root.

config/module/versions.go, config/module/versions_test.go
When explicitly requesting a module with metadata information (ex. `1.0+abc`), go-version does not differentiate between versions based on build number. According to semver:
> Build metadata SHOULD be ignored when determining version precedence.
So when comparing versions (including on equality) go-version will not factor in build/metadata, since it generally follows this spec.
As such, this PR adds a bit of logic to make sure that Terraform matches versions exactly when exact matches are requested for a version with metadata.
Addresses #20814
=> Ensure matching modules with metadata when requested

website/docs/commands/push.html.markdown, website/docs/configuration-0-11/terraform-enterprise.html.md, website/docs/configuration/terraform-enterprise.html.md
These docs are due to be removed, so these links will shortly break. Removal is in hashicorp/terraform-website#812
=> Remove links to legacy Terraform Enterprise docs

builtin/providers/test/resource_list.go, builtin/providers/test/resource_list_test.go, terraform/context_plan_test.go, terraform/context_refresh_test.go, terraform/eval_diff.go, terraform/eval_read_data.go
The provider's validate methods are called along with the static config validation early on, but will contain many unknown values that can't be checked for content.
By re-running the provider validate functions before plan (and read for data sources), the provider gets a chance to see the complete config, and return diagnostics about any new values which may not be valid.
Fixes #21225.
Fixes #21436, which was partially fixed by an earlier commit that prevented unknown values from going through validation, but as a side effect prevented their validation altogether.
This also closes #21315, since it will allow the provider to reject unexpected null values that would have otherwise been skipped due to being unknown during Validate.
=> Allow providers to re-validate the final resource config

go.mod, go.sum, vendor/github.com/hashicorp/go-plugin/client.go, vendor/github.com/hashicorp/go-plugin/server.go, vendor/modules.txt
Fixes a minor issue where the plugin may be closed before the stderr
reader completes, resulting in a warning in the logs.
=> update go-plugin package

docs/README.md, docs/plugin-protocol/README.md
This is an initial partial description of the plugin protocol focused mainly on explaining the purpose of the .proto files. In subsequent updates we will also document the negotiation protocol, etc.
For this first pass the goal was just to publish some information that was already available in an internal design document so that it's visible to SDK implementers. It is focused on the .proto versioning strategy because that was the main topic of the internal design documentation this was based on.
It may be easier to read in [its rendered form](https://github.com/hashicorp/terraform/tree/881abd5c0ded6366989690250d9393ff466432ee/docs/plugin-protocol), rather than as a Markdown source diff.
=> docs: README for the plugin-protocol directory

backend/remote-state/swift/backend.go
For #18569
This commit updates the authentication configuration for the Swift
remote.
Support for cross-domain authentication has been added and mapping
environment variables to the correct domain settings has been
fixed.
In addition, support for clouds.yaml files has been added.
The bulk of the files are from a mass vendor update. Sorry about that.
Upgrade Notes:
We applied this fix to the OpenStack Provider back in April/May and noticed the following:
The majority of users will not see an issue, especially those who authenticate entirely via environment variables.
Users who have modified/altered their auth settings to account for the prior behavior might have to change their auth settings to what they should have been all along.
There's always the possibility that a user will run into …
=> backend/remote: Swift Authentication Update

backend/remote-state/swift/backend.go, website/docs/backends/types/swift.html.md
This PR adds an application credential auth support to the swift backend. Application credentials auth is already supported by an openstack provider. See https://github.com/terraform-providers/terraform-provider-openstack/pull/642
/cc @jtopjian , @jbardin
=> Swift backend: add application credential support

helper/acctest/random.go
Re-seeding the PRNG every time only serves to make the output an
obfuscated timestamp. On windows with a low clock resolution, this
manifests itself by outputting the same value on calls within the
minimum time delta of the clock.
Fixes #21550
=> only seed math/rand once

configs/configload/getter.go, internal/initwd/getter.go, website/docs/modules/sources.html.markdown
Adds support for GCS style source URL for modules, as implemented in https://github.com/hashicorp/go-getter/pull/170
eg:
```
module "my_module" {
source = "gcs::https://www.googleapis.com/storage/v1/my/path/module.tar.gz"
name  = "foo"
}
```
=> Add GCS source support for modules

website/docs/providers/type/community-index.html.markdown
We've folded Yelp's provider into an official provider!
We (SignalFx) have taken over Yelp's provider and made it our own. This updates that link!
=> Update link to official SignalFx provider

backend/remote/backend_common.go, backend/remote/backend_mock.go, backend/remote/backend_plan.go, backend/remote/backend_plan_test.go, backend/remote/testing.go
This feature's being restructured, and this has been dead code for a while now. It won't need to be in the remote backend until this feature sees a real release. We can safely remove references to this and, even if folks are running 0.12.0 when the feature is ultimately released, the remote backend won't break for them (although it won't support the newer version of the feature).
=> Remove pre-alpha cost estimation logic from remote backend

website/docs/providers/index.html.markdown
Per GitLab's website, it appears that they always spell the name with a capital L.
=> Fix GitLab title on providers index

command/format/state.go, command/format/state_test.go, command/state_show_test.go
The original goal was to reduce newlines between each output in `terraform show`, as demonstrated in one of the tests cases, but I also found one extra trailing whitespace printing for untainted (most) resources.
=> command/format: Reduce extra whitespaces & new lines

helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
When upgrading from a flatmap state, unset blocks would not exist in the
state, while they will be represented as empty in the new cty.Value. This
will cause an unexpected diff in the first plan after upgrade. This
situation may normally be applied with no impact, but some providers may
have unexpected behavior, and if the attributes force replacement it may
require manual alteration of the state to complete the upgrade.
Fixes #21684
=> Ensure all object attrs & empty blocks in upgrade

backend/remote/backend_apply.go
Previously, the remote apply CLI warnings said: ```...its still pending```, w/ this PR they'll now read ```...it's still pending``` so that they are grammatically correct! 
Docs update here: [#819](https://github.com/hashicorp/terraform-website/pull/819)
=> Update remote apply warnings to use correct its/it's

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/plugin/grpc_provider.go
When a Diff contains a NewRemoved attribute (which would have been null
in the planned state), the final value is often the "zero" value string
for the type, which the provider itself still applies to the state.
Rather than risking a change of behavior in helper/schema by fixing the
inconsistency, we'll remove the NewRemoved attributes after apply to
prevent further issues resulting from the change in planned value.
This prevents a common `Provider "foo" produced an unexpected new value` 
which providers themselves can't remedy, and could cascade through many 
resources in complex configurations.
=> Remove removed attribute from applied state

lang/funcs/collection.go, lang/funcs/collection_test.go
Addresses #21695
Previously, if you called `merge` and one of the values was null, it would panic. Instead, by removing this line, it will give the user an error so they can fix it.
=> Don't allow nulls in calls to merge

builtin/providers/test/resource_nested_set_test.go, helper/plugin/grpc_provider.go
Like Upgrade, Import is another case where we don't have the context of
the configuration and need to ensure missing blocks are normalized.
Fixes #21266
=> normalize empty blocks during import

website/docs/commands/fmt.html.markdown
With `-check=false` the exit status is always zero.
With `-check=true` the exit status is zero when all files are properly formatted and non-zero otherwise.
**Test case**
With terraform 0.11.13, run the commands below in a directory containing terraform .tf files.
`terraform fmt` - exit status is always zero
`terraform fmt -check=false` - exit status is always zero
`terraform fmt -check=true` - exit status is zero if no changes are required and non-zero otherwise.
=> Correct fmt -check

command/fmt_test.go
When running in CI, where the system puts the temp directory can be impacted by Terraform's desire to normalize paths, as such, in the TestFmt_check test, when it is comparing the actual and expected directories, the temp directory should be normalized for this check to succeed consistently across systems.
=> tests: Normalize in the fmt -check test

website/docs/providers/terraform/d/remote_state.html.md
There is a sight difference in the syntax between 0.11 and 0.12 in defining terraform_remote_state.
=> terraform_remote_state docs have incorrect example for "config" argument

command/validate_test.go, go.mod, go.sum, terraform/context_plan_test.go, terraform/test-fixtures/plan-ignore-changes-in-map/ignore-changes-in-map.tf, vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_template.go, vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go, vendor/github.com/hashicorp/hcl2/hcl/json/structure.go, vendor/github.com/hashicorp/hcl2/hcl/traversal_for_expr.go, vendor/modules.txt, website/docs/configuration/resources.html.md
For Terraform 0.12 we had intended to start supporting ignoring individual map keys such as individual tags in a tags map. Unfortunately some later changes to HCL's parser inadvertently broke that behavior, so at release referring to a map key in `ignore_changes` would lead to an error:
```
Error: Invalid expression
on example.tf line 12, in resource "null_resource" "example":
73:         tags["Name"],
A static variable reference is required.
```
The main fix here was in HCL itself, so this PR begins with a vendor update to include that fix, but then also includes a documentation update to explain how this works and the addition/removal caveat that applies to it, along with a test for this specific behavior to reduce the risk of this inadvertently regressing again in the future.
This …
=> core: Fix handling of individual map keys in ignore_changes

builtin/providers/test/resource_timeout_test.go, helper/plugin/grpc_provider.go, helper/schema/resource.go
Timeouts needs to always exist in the private data with the new protocol, since not all helper/schema operations load the combined config+defaults at the correct time. The private data was lost in PlanResourceChange when there was no diff, which means there was no `diff.Meta` to encode them into. The `read` timeouts were also not decoded during `ReadResource`, so make sure to insert them from the private data.
=> Private data and timeouts were lost in empty plans

state/remote/remote_test.go, state/remote/state.go, state/remote/state_test.go
Previously we would write to the backend for every call to `PersistState`, even if nothing changed since the last write, but update the serial only if the state had changed.
The Terraform Cloud & Enterprise state storage have a simple safety check that any future write with an already-used lineage and serial must be byte-for-byte identical. `StatesMarshalEqual` is intended to detect that, but it only actually detects changes the state itself, and not changes to the snapshot metadata.
Because we write the current Terraform version into the snapshot metadata during serialization, we'd previously have an issue where if the first state write after upgrading Terraform to a new version happened to change nothing about the state content then we'd write a new snapshot that differed only by …
=> state/remote: Don't persist snapshot for unchanged state

configs/parser_config.go, configs/test-fixtures/invalid-files/provider-syntax.tf, configs/version_constraint.go
The `configs` package was not checking the diagnostics for errors after loading files as HCL, which lead to panics in `init` and `validate` when terraform encountered invalid HCL.
The following config would produce an error out of `terraform fmt`, which explicitly validates the syntax first, but cause a panic in `init` or `validate`:
```hcl
provider "aws" {
region = var.aws_region
version =
}
```
I think a follow-up HCL issue to improve the output in this instance is warranted:
```
$ terraform validate
Error: Invalid expression
on main.tf line 3, in provider "aws":
3:
4:
Expected the start of an expression, but found an invalid expression token.
```
Fixes #21518
=> configs: check for errors after LoadHCLFile

builtin/providers/test/resource_defaults_test.go, helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
The helper/schema diff process loses empty strings, causing them to show
up as unset (null) during apply. Besides failing to show as set by
GetOk, the absence of the value also triggers the schema to insert a
default value again during apply.
It would also be be preferable if the defaults weren't re-evaluated
again during ApplyResourceChange, but that would require a more invasive
patch to the field readers, and ensuring the empty string is stored in
the plan should block the default.
Fixes #21760
=> prevent an empty string from being lost

builtin/providers/test/resource_list.go, builtin/providers/test/resource_list_test.go, helper/schema/field_reader_config.go, helper/schema/field_reader_diff.go
Fix 2 specific panics in the sdk when reading nil or computed maps from
various configurations. The legacy sdk code is too dependent on undefined
behavior to attempt to find and fix the root cause at this point.
Since the code is essentially frozen for future development, these
changes are specifically targeted to only prevent panics from within
providers.  Because any code effected by these changes would have
panicked, there cannot be anything depending on the behavior, and these
should be safe to fix.
Fixes #15442,#19978,#21866
=> prevent sdk panics in 2 specific cases

plans/objchange/compatible.go, plans/objchange/compatible_test.go
When checking AssertObjectCompatible, we need to allow for a possible
unknown nested list block, just as we did for a set in 0b2cc62.
Fixes #21849
=> actual value may be unknown in nested list

helper/plugin/grpc_provider.go, helper/plugin/grpc_provider_test.go
If a set element is nil in validateConfigNulls, we don't want to
append that element to the diagnostic path, since it doesn't offer any
useful info to the user.
Fixes #21480
=> don't append nil elements to a diagnostic cty.Path

website/docs/commands/cli-config.html.markdown
Team tokens never worked with the `atlas` backend, but the `remote` backend
uses them as intended; they can perform plans and applies on workspaces where
the associated team has at least plan or write permissions, respectively.
=> website: CLI config: Team tokens work with CLI actions

builtin/providers/test/resource.go, builtin/providers/test/resource_test.go, helper/plugin/grpc_provider.go
This reverts commit 2e2a3630528d00c9b6899145f34c9ed04a390300 from #21472 
While that commit improved the consistency of the state from core's perspective, and would remove many warnings from the logs, it turns out that a lot more provider code than anticipated will `Set` empty or `nil` values and expect them to remain in the state.
If we are going to disrupt providers at all, it would require a much larger net benefit, and the number of actual runtime bugs this would fix is low. The greater challenge is that providers currently don't filter out which optional values should be "unset", and often set them all unconditionally. 
Since  21721 disrupts providers, and also can't even normalize all non-computed zero values (which would have been more disruptive), we are going to revert to the …
=> Revert "Remove removed attribute from applied state"

website/docs/configuration/expressions.html.md
It looks like there was a typo in the **Arithmetic Operators** section, this PR just fixes that :)
=> Fix typo in Arithmetic Operators section

command/hook_ui.go
Fixes #20017 
Changes proposed:
* hook_ui: Change the "Import complete!" message to "Import prepared!" and then list resources as "prepared" instead of "imported".
=> Change import message to 'prepared'

lang/funcs/filesystem.go, lang/functions.go, lang/functions_test.go, website/docs/configuration/functions/abspath.html.md, website/layouts/functions.erb
Allows working around #21400, and covers a suggested function in #16697
=> lang/funcs: add "abspath" function

terraform/evaluate.go
Fix for a crash during terraform plan: If there is a multi-instance
resource (count > 1) where one of the instances was deleted in the
deployment but was still present in the terraform state,
getResourceInstancesAll crashed.
Check not only for rs.Instances[key] to exist, but also to have a
valid Current pointer.
=> Fix for crash #21896

website/docs/providers/index.html.markdown, website/docs/providers/type/monitor-index.html.markdown
SignalFX provider has complete the TPDP, this PR will add the links pointing to the SignalFX provider docs.
=> [Website] Add Signalfx provider links

backend/remote-state/swift/backend.go, backend/remote-state/swift/backend_state.go, backend/remote-state/swift/client.go, website/docs/backends/types/swift.html.md
Currently in the swift backend, the object state name is hardcoded to "tfstate.tf". This PR makes that configurable via a "state_name" option. The option is optional and  defaults to "tfstate.tf". This puts the backend more in line with the S3 backend and will allow users to have one container with multiple states.
I'm not 100% happy with the option name. I'd prefer to use "key" or something similar, but the backend already uses that internally for the Openstack key and I didn't want to have the option and internal struct members named differently. Any suggestions?
I, of course still need to update the documentation and test it a bit more, so this is very much a WIP.
=> Add support for user configured state object names in swift containers

builtin/providers/test/resource_test.go, go.mod, go.sum, terraform/eval_diff.go, vendor/github.com/zclconf/go-cty/cty/path.go, vendor/modules.txt
Remove reflect.DeepEqual from path comparisons to get reliable results.
Fixes #21972
=> Update cty and use Path.Equals in depends_on comparisons

website/docs/configuration/functions/format.html.md
The search "terraform leading zero" does not find the `format()`
function, which is perfectly capable of adding leading zeros.
Thus I have added this one word to help people find `format()`.
I tried using "%-03" and "%0-3" and found that '-' overrides '0',
always padding with trailing _spaces_. Therefore there is no
need to mention trailing zeros.
=> Add "leading zeros" for the sake of SEO

website/docs/providers/type/community-index.html.markdown
The previous oVirt provider project has been moved under oVirt community, with a new URL prefix.
=> Update the URL of oVirt provider in docs.

website/docs/configuration/functions/replace.html.md
Noted that the helpful details around regular expressions in `replace()` that are in the 0.11 documentation aren't present in the 0.12 documentation.
=> Added regex details to replace() docs

command/format/plan.go
Don't show no-ops in `terraform show`, since it's not something that will change any state.
=> Fixes #21907

website/docs/backends/types/consul.html.md
The correct environment variable corresponding to the `ca_file` variable is `CONSUL_CACERT` and not `CONSUL_CAFILE`.
See `backend/remote-state/consul/backend.go` line 77.
=> Fix typo in environment variable

website/docs/backends/types/oss.html.md, website/docs/configuration/attr-as-blocks.html.md, website/upgrade-guides/0-12.html.markdown
`docker run    -v $(pwd):/scripts    --workdir=/scripts    nickg/misspell:latest    misspell -w -source=text website/`
=> Minor spelling fixes

backend/remote-state/s3/client.go
This PR is a minor typo correction in a comment in the S3 backend. It is purely a documentation update and does not add or remove any additional functionality.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> s3 backend: minor typo in putMD5 comment

builtin/providers/test/resource_nested_set_test.go, plans/objchange/compatible.go, plans/objchange/compatible_test.go
`AssertObjectCompatible` needs to detect possible dynamic `NestingSet` blocks, and ignore changes in set length. This check was already present in the `NestingList` case.
Fixes #22048
=> dynamic set blocks produce inconsistent final plan

website/upgrade-guides/0-12.html.markdown
This seems to be a common mistake - saw it in StackOverflow
and in several issues.
=> clarify config block in terraform_remote_state

website/docs/backends/types/artifactory.html.md
Typo discovered while researching artifactory backend configuration
=> Simple typo in example artifactory backend subpath

communicator/ssh/communicator.go, communicator/ssh/communicator_test.go, go.mod, go.sum, vendor/golang.org/x/crypto/ed25519/ed25519.go, vendor/golang.org/x/crypto/ed25519/ed25519_go113.go, vendor/golang.org/x/crypto/internal/chacha20/asm_ppc64le.s, vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go, vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go, vendor/golang.org/x/crypto/openpgp/keys.go, vendor/golang.org/x/crypto/openpgp/packet/private_key.go, vendor/golang.org/x/crypto/poly1305/mac_noasm.go, vendor/golang.org/x/crypto/poly1305/sum_noasm.go, vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go, vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s, vendor/golang.org/x/crypto/ssh/client_auth.go, vendor/golang.org/x/crypto/ssh/common.go, vendor/golang.org/x/crypto/ssh/kex.go, vendor/golang.org/x/crypto/ssh/messages.go, vendor/golang.org/x/crypto/ssh/server.go, vendor/golang.org/x/crypto/ssh/ssh_gss.go, vendor/modules.txt
An unresponsive server or dead tcp connection can hang a provisioner indefinitely.
Monitor the ssh connection status, and abort if the server becomes unresponsive for more than 120s.
Unfortunately the connection `timeout` parameter is already taken to mean "retry timeout", and is often set to an inappropriate value to use for monitoring the connection status. Rather than providing another similarly named option for users, we'll set a conservative timeout of 120s (somewhat arbitrarily chosen to match the arbitrarily chosen default TCP MSL value).
Fixes #12139
=> monitor ssh connection live-ness

command/show_test.go, command/testdata/show-json/nested-module-error/main.tf, command/testdata/show-json/nested-module-error/modules/main.tf, command/testdata/show-json/nested-module-error/modules/more-modules/main.tf, command/testdata/show-json/nested-modules/modules/more-modules/main.tf, command/testdata/show-json/nested-modules/output.json, configs/config_build.go, configs/config_build_test.go, configs/testdata/nested-errors/child_a/child_a.tf, configs/testdata/nested-errors/child_c/child_c.tf, configs/testdata/nested-errors/root.tf
When loading nested modules, the child module diagnostics were dropped
in the recursive function. This mean that the config from the submodules
wasn't fully loaded, even though no errors were reported to the user.
This caused further problems if the plan was stored in a plan file, which
means only the partial configuration was stored for the subsequent apply
operation, which would result in unexplained "Resource node has no
configuration attached" errors later on.
Also due to the child module diagnostics being lost, any newly added
nested modules would be silently ignored until `init` was run again
manually.
Fixes #21757
Fixes #21624
Fixes #21515
Fixes #21771
=> ensure we record diagnostics from nested modules

backend/remote/backend_plan.go, backend/remote/backend_plan_test.go
We recently started normalizing the config path before all "command"
operations, which was necessary for consistency but had unexpected
consequences for remote backend operations, specifically when a vcs root
with a working directory are configured.
This PR de-normalizes the path back to an absolute path.
I am still contemplating tests - this issue only occurs when a TFC user has a workspace with both a VCS root and a working directory configured, not something we can cover in unit tests. Any suggestions are appreciated.
=> [WIP] backend/enhanced: start with absolute configuration path

website/docs/providers/type/community-index.html.markdown
Pingdom provider refers to https://bitbucket.org/devops_sysops/pingdom-provider, which no longer exists
I've updated the URL to refer to https://github.com/russellcardullo/terraform-provider-pingdom, which seems to be the most up-to-date pingdom provider
=> Update pingdom community provider url

lang/funcs/collection.go, lang/funcs/collection_test.go
The function would previously panic when one or more null values were among the arguments.
The new behavior treats nulls as empty strings, therefore, it removes them.
Closes https://github.com/hashicorp/terraform/issues/22026.
=> Allow null values in Compact function

website/docs/commands/output.html.markdown
This PR will update documentation for `terraform output` options (please also see #21799).
- Removing deprecated `-module=` option
```
$ terraform output -module=network
Error: Unsupported option
The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.
```
- Add documentation for missing `-no-color` option
```
$ terraform output -h
Options:
-state=path      Path to the state file to read. Defaults to
"terraform.tfstate".
-no-color        If specified, output won't contain any color.
-json            If specified, machine readable output will be
printed in JSON format
```
=> Update in terraform output documentation

backend/remote/backend_plan.go, backend/remote/backend_plan_test.go
When a TFC workspace is configured with a working directory (and not with a VCS root), and a user is running `terraform init` locally from that same directory, TFC uploads the
entire configuration directory, not only the user's cwd. This is not
obvious to the user, so we are adding a descriptive message explaining
what is being uploaded, and why.
No VCS root, WD configured, init from directory other than VCS root:
=> backend/remote: notify users when uploading something other than cwd

lang/funcs/collection.go, lang/funcs/collection_test.go
Fixes https://github.com/hashicorp/terraform/issues/22021
I wasn't sure at first whether to error out or just return empty list, so I just followed how other functions seem to handle similar situation.
=> lang/funcs: Pass through empty list in chunklist

backend/remote/backend.go, backend/remote/backend_mock.go, backend/remote/backend_plan_test.go
Previously, terraform was returning a potentially-misleading error
message in response to anything other than a 404 from the
b.client.Workspaces.Read operation. This PR simplifies Terraform's error
message with the intent of encouraging those who encounter it to focus
on the error message returned from the tfe client.
The added test is odd, and a bit hacky, and possibly overkill. I am
willing (and even eager) to remove it altogether.
=> backend/remote: remove milseading contents from error message

command/init.go, command/init_test.go
Terraform would silently accept - and swallow - `-backend-config` on the
CLI when there was no `backend` block. Since it is mostly expected to
override existing backend configuration, ~it is reasonable that terraform
should return an error if there is no backend configuration to
override.~ EDIT: on second thought, let's print a warning! 
If the user intended to override the default (local) backend
configuration, they can first add a `backend` block to the `terraform` block to silence the warning:
```hcl
terraform {
backend "local" {}
}
```
Fixes #21023
=> command/init: omit a warning if -backend-config is used with no backend

lang/blocktoattr/variables.go, lang/blocktoattr/variables_test.go
Mistakenly using dynamic on an attribute will lead to a panic when
attempting to resolve variable references with a partial body, because
the dynamic blocks have yet to be expanded and validated. Check that the
block element type is actually an object before generating a schema.
Fixes #22043
Fixes #21619
=> invlaid use of dynamic with attrs should not panic

.hashibot.hcl
We can tune the sleep between issues and the max amount to process per routine as desired. The cron schedule is just an arbitrary point in the day that is far from the other similar crons... that system in general needs some work.
=> [hashibot] configure issue locker

configs/configupgrade/upgrade_expr.go
In some cases (see #22020 for a specific example), the parsed `hilNode`
can be `nil`. This causes a series of panics. Instead, return an error and
move on.
This does not try to identify _why_ the returned `hilNode` is `nil`, it just returns an error.
Fixes #22020
=> configs/configupgrade: fix panic on nil hilNode

website/docs/providers/terraform/d/remote_state.html.md
The "remote" backend supersedes the "atlas" backend so this is the one we should use in the example.
=> docs: Update example remote_state to use remote backend

builtin/providers/test/provider.go, builtin/providers/test/resource_required_min.go, builtin/providers/test/resource_required_min_test.go, configs/configschema/coerce_value.go, configs/configschema/coerce_value_test.go, configs/configschema/decoder_spec.go, configs/configschema/decoder_spec_test.go, helper/schema/schema.go
`MinItems` > 1 can't be validated directly from the configuration is using dynamic blocks.
We need to skip the validation in a few places to let these through.
- Skip the check in CoerceValue if there are any unknowns, which may indicate a dynamic block
- Reduce the check to 0 or 1 for the decoder spec, since a dynamic block will only have 1 config value.
- Skip the check in the schema validation if there are any unknowns. We will eventually get to validate the entire config once the blocks have been expanded and are known during the final plan.
Fixes #22195
=> MinItems with dynamic blocks

helper/schema/schema.go, helper/schema/schema_test.go
Nil values were not previously expected during validation, but they can
appear in some situations with the new protocol. Add checks to prevent
using zero reflect.Values.
Fixes #22216
Fixes #22147
=> don't reflect nil in schema validation

command/format/state.go, command/format/state_test.go
Account for deposed instances in show command.
Prevent crash if the current instance is missing.
Besides preventing the panic, this will also add `(N deposed)` to the resource address line, similar to other state outputs.
Fixes #21770
=> account for deposed in terraform show

helper/schema/resource.go
You can signal the same information in `Read` with an empty ID if the object does not exist, Implementing `Exists` is not the only way to do so and in some providers is also not the preferred way.
=> Update copy for Exists

helper/schema/schema.go, helper/schema/schema_test.go
If an attribute was not wholly known, helper/schema was skipping the
`validateType` function which (among other things) returned deprecation
messages. This PR checks for deprecation before returning when skipping
validateType.
Fixes #22255
=> helper/schema: don't skip deprecation check during validation

.travis.yml, command/e2etest/init_test.go, command/e2etest/test-fixtures/empty/init-from-module/main.tf
Public modules aren't likely to stay compatible with 0.11 syntax. Keep
the init test rather than disable it, but change it to use a local
module.
Disable the website tests since this isn't on the master branch
=> make v0.11 tests green

terraform/eval_for_each.go
That condition would not diagnose [other iterables](https://github.com/zclconf/go-cty/blob/3ccef1ae92b0ac73b92d86f274f0ff781e2d9b3b/cty/element_iterator.go#L24-L39), such as `tuple` argument values, causing a [`panic: not a string`](https://github.com/zclconf/go-cty/blob/8c00057b05d70e7d4a4ab5c197ae8871d2b3ec69/cty/value_ops.go#L1026) later on.
=> make diagnose on for_each argument more precise

httpclient/useragent.go
Sometimes HTTP requests are buried inside third-party libraries where we can't otherwise access their request method/URL, so this ensures we'll more often have at least a record of the fact that a request happened, even if there's no other logging for why it did.
We only include the method and URL here under the assumption that secret keys and other particularly sensitive information will not appear there, in line with usual best-practices.
This covers anything in the main Terraform CLI process that makes HTTP requests through our `httpclient` package, which is not 100% comprehensive but has good coverage of a number of interesting requests Terraform does, such as calling to a module registry, etc. When we use third-party libraries that make HTTP requests we generally provide our own …
=> httpclient: Create trace logging for outgoing HTTP requests

backend/remote-state/azure/arm_client.go, go.mod, go.sum, vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_token.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_client_cert.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_client_secret.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_msi.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/azure_cli_profile.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/builder.go, vendor/github.com/hashicorp/go-azure-helpers/authentication/config.go, vendor/modules.txt
modules: update go-azure-helpers to v0.5.0
To help address the issues posed on #22087 and #22085.
Depends on #22247.
=> modules: update go-azure-helpers to v0.5.0

lang/funcs/collection.go, lang/funcs/collection_test.go
lookup() can already handle arbitrary objects of (whatever) and should
handle maps of (whatever) similarly.
[The documentation](https://www.terraform.io/docs/configuration/functions/lookup.html) does _not_ mention any limitation to the types returned, which was inconsistent with the error message when a map of objects, lists or maps was used.
Fixes #22267
=> lang/funcs: lookup() can work with maps of lists, maps and objects

command/state_mv.go, command/state_mv_test.go
Create the missing modules in the state when moving resources to a
module that doesn't yet exist. This allows for refactoring of
configuration into new modules, without having to create dummy resources
in the module before the "state mv" operations.
Fixes #22278
Fixes #21346
=> allow moving resource to new modules not in state

command/fmt.go
This option is a valid option for the fmt subcommand, but it isn't
listed in the help text.
=> Mention the -no-color option

BUILDING.md, README.md
* Remove references to vagrant file as it is no longer is used in building
=> readme : remove references to vagrant file

builtin/provisioners/habitat/resource_provisioner.go, builtin/provisioners/habitat/resource_provisioner_test.go, website/docs/provisioners/chef.html.markdown, website/docs/provisioners/habitat.html.markdown
Chef Software recently announced [Business Model Changes](https://blog.chef.io/2019/04/02/chef-software-announces-the-enterprise-automation-stack/) that are being incorporated in Chef software projects. Going forward Habitat installation will require users to accept [Chef EULA](https://www.chef.io/end-user-license-agreement/). To facilitate this change, this PR adds a new argument `accept_license` to provisioner argument list. The EULA will be automatically accepted when the user sets this argument properly. Code changes have been tested against latest and previous Habitat versions and automated tests have been verified to pass successfully. Documentation has been updated accordingly.
=> Habitat License Acceptance changes. 

command/hook_ui.go, command/hook_ui_test.go
Fixes #18822
The `tuncatedId` function had been introduced in #12261 and increased the `maxIdLen` to 80 in #13317.
Since the number of bytes itself seems to be unimportant, the ID should be truncated to 80 characters, not 80 bytes.
Please let me know if we need to truncate it to 80 bytes considering multibyte character boundaries. This will require more complex logic.
```
[terraform@fix-multibyte-trucate|✔]$ go test -v ./command -run TestTruncateId
=== RUN   TestTruncateId
=== RUN   TestTruncateId/0
=== RUN   TestTruncateId/1
=== RUN   TestTruncateId/2
=== RUN   TestTruncateId/3
=== RUN   TestTruncateId/4
=== RUN   TestTruncateId/5
=== RUN   TestTruncateId/6
=== RUN   TestTruncateId/7
=== RUN   TestTruncateId/8
=== RUN   TestTruncateId/9
=== RUN   TestTruncateId/10
=== RUN …
```
=> command/hook_ui: Truncate the ID considering multibyte characters

lang/functions.go, lang/functions_test.go, website/docs/configuration/functions/regex.html.md, website/docs/configuration/functions/regexall.html.md, website/docs/configuration/functions/replace.html.md, website/layouts/functions.erb
These existing upstream `cty` functions allow matching strings against regular expression patterns, which can be useful if you need to consume a non-standard string format that Terraform doesn't (and can't) have a built-in function for.
Similarly to `format` and `formatdate`, I wrote up our own set of reference documentation for the regular expression syntax here, so that it's more convenient to find for end-users, many of which will not care that we happen to use the RE2 regex syntax. With that written up, I also changed the `replace` docs to link there rather than to the external RE2 wiki guide. There's still a link to the full RE2 reference in the `regex` function page, but now presented as additional detail for those who are interested rather than as required reading.
---
I just …
=> lang: "regex" and "regexall" functions

website/docs/commands/untaint.html.markdown
There is no `-index` option, instead you need to set the index as additional describer to the resource.
=> Removed -index from README

communicator/ssh/communicator.go, communicator/ssh/communicator_test.go, communicator/ssh/provisioner.go, communicator/ssh/provisioner_test.go
Backport the communicator/ssh package to enable keepalives and terminate dead connections.
=> backport communicator/ssh from 0.12

go.mod, go.sum, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go, vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go, vendor/github.com/aws/aws-sdk-go/aws/session/doc.go, vendor/github.com/aws/aws-sdk-go/aws/session/session.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/sts/api.go, vendor/github.com/hashicorp/aws-sdk-go-base/CHANGELOG.md, vendor/github.com/hashicorp/aws-sdk-go-base/session.go, vendor/modules.txt
Update the aws-sdk-go-base and aws-sdk-go packages to ensure the same
client behavior as the aws provider.
=> update deps to match the aws provider

helper/resource/testing.go
ImportStateVerify does not respect DiffSuppressFunc or CustomizeDiff, which is worth documenting (and maybe, possibly, worth changing someday?  If you think so, reviewer, I'd love to write that patch).  ImportStateVerifyIgnore is a list of prefixes, rather than a list of fields.
=> helper/resource: Minor docs tweak on ImportStateVerify

helper/schema/schema.go
This comment seems to imply that you can put CRUD functions on nested schema.Resource objects.
The comment goes back to the first commit to this file, but AFAICT this functionality has never been implemented.
=> helper/schema: Remove comment about nested schema.Resources having their own lifecycle

helper/acctest/random.go, helper/acctest/random_test.go
Adds `RandIpAddress`, a function to return a random IP address in a specified CIDR block.
Useful for parallel acceptance tests that need randomized IPs.
```console
$ GO111MODULE=on go test -mod=vendor -timeout=2m -parallel=4 github.com/hashicorp/terraform/helper/acctest
ok  	github.com/hashicorp/terraform/helper/acctest	0.002s
```
=> helper/acctest: Add function to return random IP address

helper/schema/schema.go
Small update to include the "part" in the error message for people doing nested resources.
There didn't seem to be any change needed in the unittests.
=> helper/schema: Add "part" to ConflictsWith validation error

website/docs/providers/index.html.markdown, website/docs/providers/type/cloud-index.html.markdown
Exoscale has completed the TPDP and this PR will add two links that ill point to the providers documentation pages.
=> [Website] Add Exoscale provider links

httpclient/useragent.go, httpclient/useragent_test.go, terraform/user_agent.go, terraform/version.go
Providers need to know version of Terraform that is calling them, so they can report this via `User-Agent` header to upstream APIs. Currently providers do this basically by leveraging Terraform's `version` package as Terraform provides the SDK for interacting with core and is therefore imported to providers.
Such version is inaccurate and https://github.com/hashicorp/terraform/commit/bb9ae50279a8b27a8456b6952a674b34306747b4 already introduced a way for providers to source real version of Terraform (the binary that is talking to provider's gRPC server).
This new interface reflects recent changes to the protocol in 0.12 and proposes standard `User-Agent` format for providers to use. It will also allow providers to avoid depending on the `version` package which will not be available in the …
=> httpclient: Introduce composable UserAgent()

go.mod, go.sum, vendor/github.com/hashicorp/hcl2/hclwrite/format.go, vendor/modules.txt
Fixes https://github.com/hashicorp/terraform/issues/22356
Diff https://github.com/hashicorp/hcl2/compare/0c3fe388e4503d9717d39c315e8c7ee2433f752a...72d32879a5c5db881136f801b9efedf19813c081
The update includes a patch to fix the above formatting bugs.
=> Bump github.com/hashicorp/hcl2

website/upgrade-guides/0-12.html.markdown
The unterminated code block effectively breaks rendering in the latter half of this section https://www.terraform.io/upgrade-guides/0-12.html#equality-operations-must-be-valid-on-value-and-type
=> Properly end code block in upgrade docs

states/sync.go, terraform/transform_orphan_count.go, terraform/transform_orphan_count_test.go
In the scenario when a resource is orphaned by the addition of for_each, in the evaluation of orphans, it is possible for the EachMode of the resource to be set incorrectly, because the last evaluated resource sets the EachMode for the whole resource. As such, adding an edge when evaluating the movement between NoKey and StringKey resources will ensure order is maintained, and an instance with StringKey will "win".
Fixes #22407
=> Add edge when calculating for_each orphans

backend/remote-state/gcs/backend.go
Fixes hashicorp/terraform#22451.
See golang/oauth2#310 for more details.
=> Use new endpoints for Google authentication

website/docs/commands/providers/schema.html.md
This addresses the first part of #22308 (without closing the issue): missing documentation.
=> website/docs: document providers schema output format

communicator/ssh/communicator.go, communicator/ssh/provisioner.go, terraform/eval_validate.go, website/docs/provisioners/connection.html.markdown
In our company, we are using Hashicorp Vault together with a Terraform for granting temporary credentials for developers and services. For example, for reasons, when you need to run Terraform in a container as a service you will need to give SSH access (password or RSA keys) for a short time (for deploying or redeploying) and then withdraw access. In the best practices - secrets, token or keys never should leave a place where was created. Ideally, the solution, in this case, will generate RSA pair on the service and sign the public key with the Vault SSH Secrets Engine. Using SSH connection by certificate access already implemented in 0.12.x version of Terraform, but miss a certificate method for connections via Bastion. This PR adds missing functionality into Terraform by new parameter - …
=> Add SSH certificate authentication method for connection via Bastion

command/console.go, command/fmt.go, command/get.go, command/graph.go, command/meta.go, command/output.go, command/providers.go, command/providers_schema.go, command/show.go, command/state_list.go, command/state_mv.go, command/state_pull.go, command/state_push.go, command/state_rm.go, command/state_show.go, command/taint.go, command/unlock.go, command/untaint.go, command/validate.go, command/workspace_delete.go, command/workspace_list.go, command/workspace_new.go, command/workspace_select.go, command/workspace_show.go
Any command using meta.defaultFlagSet *might* occassionally exit before
the flag package's output got written. This caused flag error messages
to get lost. This PR discards the flag package output in favor of
directly returning the error to the end user.
This PR DIRECTLY CONFLICTS with https://github.com/hashicorp/terraform/pull/22372
I am equally happy to choose one over the other - if we are concerned about the implications of this change, starting with a single command is not a bad option.
=> command: discard output from flags package and return errs directly

configs/configschema/coerce_value.go, configs/configschema/coerce_value_test.go
A provider may not have the data to fill in required block values in all
cases during the resource Read operation. This is more common in import,
because there is no initial configuration or state, and it's possible
some values are only provided in the configuration.
The original intent of MinItems and MaxItems in the schema was to
enforce configuration constraints, not to enforce what the resource
could save in the state.  Since the configuration is already statically
validated, and the Schema is validated against the configuration in a
separate step, we can drop these extra validation constraints in
CoerceValue and relax it to only ensure the types conform to what is
expected.
Closes #22387
Issue 22387 is not an exhaustive list, but the representative that the issues are mostly …
=> don't validate Min/Max block vals in CoerceValue

website/docs/providers/index.html.markdown, website/docs/providers/type/database-index.html.markdown
Add two links that will point to the MongoDB Atlas provider documentation.
=> [Website] MongoDB Atlas provider links

README.md
I am trying to build terraform in docker but failed. Update docs to install tools first.
=> docs: install tools before building in docker environment

go.mod
This was just forgotten in recently merged https://github.com/hashicorp/terraform/pull/22524
=> go.mod: Remove unnecessary replace directive for autorest

configs/configschema/coerce_value.go, configs/configschema/coerce_value_test.go, configs/configschema/decoder_spec.go, configs/configschema/decoder_spec_test.go
This PR is reduced in scope from #22484, only removing the validation that we cannot reliably handle. The dedicated Validated method contained a lot of duplicated logic, and added minimal value in the validation process (types and structure should match at this point), only really being able to catch MaxItems validations at the last moment. 
We can evaluate if `Validate` has a use in this are later on, or if full validation should simply be under the purview of the value recipient which will have other constraint checks anyway. Making better use of `InternalValidate` can also be decided separately from this change.
-- 
Due to both the nature of dynamic blocks, and the need for resources to
sometimes communicate incomplete values, we cannot validate MinItems and
MaxItems in CoerceValue. …
=> MinItems and MaxItems validations

website/docs/commands/taint.html.markdown
I noticed the doc for `terraform taint` had a formatting issue with a bulleted list:
Turns out this was just a missing newline between the preceding paragraph and the list. Adding a line break fixes it. I ran `make website` to confirm it renders properly:
=> website: fix <ul> formatting in "taint" doc

svchost/disco/host.go, svchost/disco/host_test.go, svchost/disco/oauth_client.go
So far all of our Terraform-native services have been configured using a single entry-point URL, given as a string.
However, for the forthcoming `login.v1` service we need to express a full OAuth client configuration so that the forthcoming `terraform login` command can obtain an API token using OAuth 2 flows.
This is a new API for retrieving from a host's service discovery document an OAuth client configuration represented as a JSON objects, given a particular service identifier. Initially this will be used only for `login.v1`. I find it unlikely that any other service definitions will use it in future, but subsequent versions of `login` (`login.v2`, etc) might do so.
For the moment this is just dead code from the perspective of a full Terraform CLI build. Its caller will arrive later, …
=> svchost/disco: Allow service types that are OAuth clients

backend/remote-state/s3/backend.go, backend/remote-state/s3/backend_state.go, backend/remote-state/s3/backend_test.go, backend/remote-state/s3/client.go, website/docs/backends/types/s3.html.md
These changes add support for encrypting terraform remote-state in S3 using [customer-supplied encryption keys (SSE-C)](https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html). For resources where the contents of the state file may be particularly sensitive, this allows the user greater control over who is able to read the remote-state (only those who have the key).
This PR also includes acceptance tests and documentation updates. Acceptance tests have been run against an AWS instance, and new tests are passing. (FYI, TestBackendExtraPaths is failing, but this also appears to be failing on master. I cannot tell if this is a problem with my AWS configuration, or with this test, but it doesn't seem to be related to my changes.)
```
=== RUN …
```
=> Add support for SSE-C to S3 backend

backend/remote-state/oss/backend.go, backend/remote-state/oss/backend_test.go, website/docs/backends/types/oss.html.md, website/docs/providers/index.html.markdown, website/docs/providers/type/major-index.html.markdown
This PR aims to support profile config in the Alibaba Cloud backend. The profile will help users to get config from credential file. Currently, the terraform-provider-alicloud has supported it and the backend also need to do it.
=> backend/oss: added support for profile config

svchost/disco/oauth_client.go
A server is allowed to omit `AuthorizationURL` if it's using the "password" grant type, and other future grant type implementations may have similar accommodations.
Doing this conditionally is required because this would otherwise panic if either of these were `nil`.
=> svchost/disco: Tolerate unpopulated OAuth endpoints

command/cliconfig/credentials.go
A more convenient interface to get a throwaway empty credentials source for use in tests, which doesn't interact at all with the real CLI configuration directory.
(This is for the tests for `terraform login`, which we can't merge yet because the server behind it isn't present. For that reason, the caller of this function will follow in a later PR.)
=> command/cliconfig: EmptyCredentialsSourceForTests

svchost/disco/disco.go
Previously we allowed access to the credentials store only indirectly through the `Disco` object, and that's fine for callers that only need to _read_ credentials, but more specialized callers like `terraform login` and `terraform logout` need more information in order to be transparent to the user about what they are going to do and where the credentials are going to be stored.
=> svchost/disco: Disco.CredentialsSource

website/docs/providers/terraform/d/remote_state.html.md, website/docs/providers/terraform/index.html.markdown
I was testing this with 0.12 to pin down some related TFC behavior, and if my data source tried specifying `workspaces` as a nested block (the way the backend config requires it), it blows up with a syntax error. 
I'm actually not sure whether this is an intentional change!
=> website: In 0.12, terraform_remote_state syntax differs from backend config

plugin/grpc_provider.go
As I was reading through the code and trying to understand where does the testing framework get Terraform version from I found that there are two places which are sourcing version, one of which seems redundant.
https://github.com/hashicorp/terraform/blob/75d3f1e62ef0d607da3d85a3222ed24a42a3958d/terraform/eval_context_builtin.go#L179-L182
I believe that this is just oversight and not a safeguard against callers of `GRPCProvider.Configure` which wouldn't declare Terraform version, but I'm happy to be corrected! 😄 
A side effect of this change is that we'll now report pre-released versions too, i.e. custom built `0.12.7` from master will be reported as `0.12.7-dev`, rather than simple `0.12.7`.
=> plugin: Pass TerraformVersion from ConfigureRequest

builtin/providers/test/diff_apply_test.go, terraform/diff.go
While we can't change the behavior of helper/schema at this point, we
can protect against panics in the case of unexpected nils in the
instance diff.
Fixes the panic in #22196
It's likely caused by a combination of diff suppress funcs and/or customize diff, but given that helper/schema is frozen there's not much that can be done. The new 0.12 code here is in the diff.Apply method, which is the last piece that still needs to handle the instance diff.
=> prevent panics when encountering nil diffs

website/docs/provisioners/chef.html.markdown, website/docs/provisioners/connection.html.markdown, website/docs/provisioners/file.html.markdown, website/docs/provisioners/habitat.html.markdown, website/docs/provisioners/index.html.markdown, website/docs/provisioners/local-exec.html.markdown, website/docs/provisioners/puppet.html.markdown, website/docs/provisioners/remote-exec.html.markdown, website/docs/provisioners/salt-masterless.html.md
For a long time now we've been advising against the use of provisioners, but our documentation for them is pretty prominent on the website in comparision to the better alternatives, and so it's little surprise that many users end up making significant use of them.
Although in the longer term a change to our information architecture would probably address this even better, this is an attempt to be explicit about the downsides of using provisioners and to prominently describe the alternatives that are available for common use-cases, along with some reasons why we consider them to be better.
This also includes some other tweaks to update the documentation for changes in 0.12 or to avoid showing non-recommended patterns in our examples.
---
I took the unusual step here of directly linking to …
=> website: Warn against using provisioners, and suggest alternatives

Makefile, scripts/protobuf-check.sh
I originally thought I could document this but then I realized since the Makefile seems to be (realistically) the most likely entrypoint, this may be better than any documentation.
=> make: Add check for protobuf dependencies

Makefile
Properly exclude files under "./vendor/" path, and find "files" only.
The original method "might" found "directories" with the same naming,
or, might exclude occasionally exclude the go files with "vendor" string
in any part of its path.
=> Improve the method to find out go files in Makefile

website/docs/backends/types/oss.html.md
I tried with integer, it crashed.
```
Initializing the backend...
Successfully configured the backend "oss"! Terraform will automatically
use this backend unless the backend configuration changes.
panic: [tablestore] invalid input
goroutine 1 [running]:
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.NewPrimaryKeyColumn(0xc0001e0fb0, 0x2, 0x8, 0x19efe40, 0xc0001e0f30, 0x0, 0x0)
/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/util.go:279 +0x338
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.(*PrimaryKey).Build(0xc0001fabe0, 0xc00069f200, 0x0, 0x0, 0x200)
/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/util.go:388 +0x200 …
```
=> Clarification for type of primary key

command/console.go
Allows -var and -var-file flags as expected
Fixes https://github.com/hashicorp/terraform/issues/21483
Fixes #22682
=> fix, use extended flags for terraform console

.travis.yml
This gets us slightly faster test runtimes and also insulates us better from downtime of individual upstreams, in favor of being dependent only on one specific upstream (the Go module proxy itself, currently run by Google).
This affects only Travis-CI runs. While it's also a good idea for many developers working on Terraform to use the module proxy too, I didn't go so far as to _force_ that in the `Makefile` because some folks cannot reach the official module proxy from their development systems for one reason or another, and so we will allow everyone to make their own local policy decision about whether to use a proxy and which proxy to use.
=> build: Use the official Go module proxy for Travis-CI runs

command/e2etest/init_test.go
The canonical location of the `template` provider is now in the `hashicorp` namespace rather than the `terraform-providers` namespace, so the output has changed to reflect that.
=> command/e2etest: Fix TestInitProviders

.hashibot.hcl
This might false positive some PRs, but it should avoid any PRs "slipping through the cracks". It's imperative all SDK affecting PRs are cherry picked or duplicated to the SDK.
=> [hashibot] Apply special label for PRs affecting sdk paths

terraform/context_apply_test.go, terraform/eval_apply.go, terraform/testdata/apply-provisioner-each/main.tf
The config diagnostics weren't checked before sending to the
provisioner, and may have contained invalid values.
This also adds an interesting case of `for_each` with `when = "destroy"`, which currently will fail if the each value is referenced in the provisioner.
This fixes the crash in #22700, but does not fix the root cause of the unknown for_each values.
=> don't send an invalid config to a provisioner

builtin/provisioners/habitat/resource_provisioner.go, builtin/provisioners/habitat/resource_provisioner_test.go, website/docs/provisioners/chef.html.markdown, website/docs/provisioners/habitat.html.markdown
Chef Software recently announced Business Model Changes that are being incorporated in Chef software projects. Going forward Habitat installation will require users to accept Chef EULA. To facilitate this change, this PR adds a new argument accept_license to provisioner argument list. The EULA will be automatically accepted when the user sets this argument properly. Code changes have been tested against latest and previous Habitat versions and automated tests have been verified to pass successfully. Documentation has been updated accordingly.
=> Habitat License Acceptance changes

addrs/provider_type.go, command/init.go, command/plugins_test.go, plugin/discovery/get.go, plugin/discovery/get_test.go, tools/terraform-bundle/package.go
This is a relatively small change meant to lay the foundation for
future enhancements to providers' address.
=> discovery: use `addrs.ProviderConfig` in place of a `typeName` string

go.mod, go.sum, vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go, vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go, vendor/modules.txt
Fixes #22352
Diff https://github.com/apparentlymart/go-cidr/compare/v1.0.0...v1.0.1
This update includes bug fixes for the `cidrhost` function with IPv6. Thanks @apparentlymart for the quick release.
=> Bump github.com/apparentlymart/go-cidr

terraform/eval_for_each.go, terraform/graph_builder_plan_test.go, terraform/testdata/plan-for-each/main.tf
We should check earlier for empty lists -- having it after set-specific checking meant we were missing empty lists/empty sets, and users would get an error they shouldn't get.
Fixes #22281
=> Cover empty sets in for_each

terraform/eval_for_each.go
Very small change because this block is much more useful when it points to the source.
=> Add source addressing to make error more useful

command/show.go
Fix two dropped error variables from the `command` package.
=> command: Fix dropped errors

backend/local/backend_apply.go, terraform/context.go, terraform/context_apply_test.go, terraform/context_plan_test.go
The documentation for the `-target` option warns that it's intended for exceptional circumstances only and not for routine use, but that's not a very prominent location for that warning and so some users miss it.
Here we make the warning more prominent by including it directly in the Terraform output when `-target` is in use. We first warn during planning that the plan might be incomplete, and then warn again after apply concludes and direct the user to run `terraform plan` to make sure that there are no further changes outstanding. The latter message is intended to reinforce that `-target` should only be a one-off operation and that you should always run without it soon after to ensure that the workspace is left in a consistent, converged state.
---
During plan, the warning message is: …
=> core: Warn when creating and applying with -target

website/docs/providers/index.html.markdown, website/docs/providers/type/network-index.html.markdown
Adding links to the index and networking provider listing pointing to the newly certified Pureport provider. 
TESTS WILL FAIL - but this PR must be merged first, then the providers documentation can be synced into the terraform-website middleman
=> [Website] Add Pureport provider links

website/docs/commands/taint.html.markdown
Adds a string key example to the `taint` docs, as this is a gotcha when dealing with resources created with `for_each`
=> [docs] Add string key example to taint docs

lang/funcs/cidr.go, lang/funcs/cidr_test.go, lang/functions.go, lang/functions_test.go, website/docs/configuration/functions/cidrsubnet.html.md, website/docs/configuration/functions/cidrsubnets.html.md
This is a companion to cidrsubnet that allows bulk-allocation of multiple subnet addresses at once, with automatic numbering.
Unlike cidrsubnet, cidrsubnets allows each of the allocations to have a different prefix length, and will pack the networks consecutively into the given address space. cidrsubnets can potentially create more complicated addressing schemes than cidrsubnet alone can. It's not possible to achieve variable prefix lengths with `cidrsubnet` (singular) in the Terraform language because it has no [reduce](https://en.wikipedia.org/wiki/Reduce_(parallel_pattern))-equivalent operator to allow iteratively computing the next address from the previous address.
---
This is a function-oriented version of the core algorithm in …
=> lang/funcs: cidrsubnets function

website/docs/configuration/functions/cidrsubnets.html.md
The `cidrsubnets` function signature is intentionally very low-level and focused on the core requirement of generating addresses. This registry module then wraps it with some additional functionality to make it more convenient to generate and use subnet address ranges.
This module won't work until Terraform 0.12.10 is released, but this documentation change won't be released until then either so this link will become useful at approximately the time it is published.
=> website: Link to hashicorp/subnets/cidr for cidrsubnets docs

terraform/context_refresh_test.go, terraform/node_data_refresh.go, terraform/testdata/plan-data-depends-on/main.tf
The old logic for `depends_on` was to short-circuit evaluation of the
data source, but that prevented a plan and state from being recorded.
Use the (currently unused) ForcePlanRead to ensure that the plan is
recorded when the config contains `depends_on`.
This does not fix the fact that `depends_on` does not work with data
sources, and will still produce a perpetual diff. This is only to fix
evaluation errors when an indexed data source is evaluated during
refresh.
Fixes #21917
=> ensure data sources are always written to state

builtin/providers/test/resource_nested_set_test.go, builtin/providers/test/resource_timeout.go, helper/resource/state_shim.go
If the resource schema version is > 0, the metadata containing the
timeout values was overwritten during acceptance tests.
Closes #22810
=> don't lose track of private data in the ACC tests

website/docs/backends/types/remote.html.md
This seems like a remnant from when remote operations (with Terraform Cloud Free) only supported state storage
=> Clarify remote operations for new Terraform Cloud Free tier

backend/remote-state/etcdv3/backend_test.go, backend/remote-state/manta/backend.go, backend/remote-state/manta/backend_test.go, backend/remote-state/oss/backend_test.go, internal/initwd/from_module_test.go, internal/initwd/module_install_test.go, tools/terraform-bundle/e2etest/package_test.go, tools/terraform-bundle/e2etest/testdata/empty/terraform-bundle.hcl, tools/terraform-bundle/e2etest/testdata/many-providers/terraform-bundle.hcl
While working on a new feature I found that certain e2e tests had not been updated for 0.12. This sent me down a bit of a rabbit trail getting the e2e tests to either pass _or_ (in the case of backends) fail cleanly. (The first two commits represent tests I needed to get working for my feature while the latter two were fixed merely because the messiness of the failures annoyed me). 
Some of these backend failures might represent bugs in the backend themselves (such as [etcv3](https://github.com/hashicorp/terraform/issues/21181)] but overall it seemed that the tests were simply making assumptions about env vars being set, then failing in weird ways when that was not the case. 
I did find one clear bug in the `manta` backend: a bool attribute was defaulting to `""` and causing a panic, so I …
=> to e2e, or not e2e, that is the question

website/docs/commands/validate.html.markdown
`-check-variables` is not present in v0.12 of `terraform validate`.
```
$ terraform --version
Terraform v0.12.9
$ terraform validate --help
Usage: terraform validate [options] [dir]
Validate the configuration files in a directory, referring only to the
configuration and not accessing any remote services such as remote state,
provider APIs, etc.
Validate runs checks that verify whether a configuration is
internally-consistent, regardless of any provided variables or existing
state. It is thus primarily useful for general verification of reusable
modules, including correctness of attribute names and value types.
It is safe to run this command automatically, for example as a post-save
check in a text editor or as a test step for a re-usable module in a CI
system.
Validation requires an …
```
=> Remove -check-variables flag from the docs

communicator/ssh/communicator.go
If a connection fails and attempts to reconnect after the keep-alive
loop started, the client will be pulled out from under the keep-alive
requests. Close over a local copy of the client, so that reconnecting
doesn't race with the keepalive loop terminating.
Fixes #22943
=> copy client pointer for keep-alive loop

website/docs/configuration/expressions.html.md, website/docs/configuration/resources.html.md, website/docs/provisioners/connection.html.markdown, website/docs/provisioners/index.html.markdown, website/layouts/docs.erb
Tried to be comprehensive about this: 
- As far as we know, connection and provisioner are the only places `self` is valid. 
- Robin's problem came from trying to use `count.index` within a connection block, so I added notes next to the count and each objects too. 
- The thing about local variables also benefited from just listing what are probably the three most common local values, since at least some readers are gonna check the info about variable names first before delving down into the stuff about meta-arguments or provisioners. 
- While I was messing with this, I was reminded that connection defaults went away in 0.12, so some language needed to be updated there. 
- Here's the result of that sidebar fiddling, which wasn't strictly necessary but which made that section a little more …
=> website: Document behavior of `self` object for provisioners

command/validate.go, website/docs/commands/validate.html.markdown
Reported in https://github.com/hashicorp/terraform-website/issues/874.
Also, I checked the code and ran some checks; `-var` and `-var-file` are still accepted by the command, but it looks like they're dead code and can never have any affect. Was that on purpose, to avoid breaking peoples' CI? It looks like we did make it blow up if `-check-variables` is provided.
=> website / help: reconcile 'validate' command docs

terraform/context_apply_test.go, terraform/node_module_removed.go, terraform/testdata/apply-targeted-resource-orphan-module/child/main.tf, terraform/testdata/apply-targeted-resource-orphan-module/main.tf
Fixes issue #21313.
The purpose of this PR is to implement `RemovableIfNotTargeted` for `NodeModuleRemoved`. During `TargetsTransformer.Transform` graph vertices are checked for `RemovableIfNotTargeted`
If config diff exists between state and the targeted apply graph, receive following error: `leftover module module.child in state that should have been removed`.
Added a test that contains a commented out module which exists in state, with target existing against a separate resource.
=> bug: fix terraform trying to clean up orphan modules on target

addrs/parse_ref.go, addrs/parse_ref_test.go, configs/configupgrade/analysis_expr.go, lang/data.go, lang/data_test.go, lang/eval.go, lang/eval_test.go, terraform/context_apply_test.go, terraform/eval_apply.go, terraform/evaluate.go, terraform/testdata/apply-invalid-index/main.tf
The primary goal of this PR is to always return entire resources to be evaluated, rather than individual instances. This allows us to push the evaluation of resource indexes down into expression evaluation. 
Invalid indexed references to other resources were silently returning unknown values when the instance didn't exist. These were only caught by extra validation in data sources when the config still contained unknown values during `ReadDataSource`. This now will catch invalid indexes, and adds an `IsWhollyKnown` validation to the config during apply, preventing config values from being silently dropped.
Only data sources caught this previously, but returned a rather unhelpful error of
```
configuration for data.null_data_source.foo[0].id still contains unknown values during apply (this …
```
=> Always evaluate resources in their entirety

command/jsonstate/state.go, command/jsonstate/state_test.go
This PR addresses 2 issues: `show -json` would crash if there was not a
`Current` `states.ResourceInstance` for a given resource, and `deposed`
resource instances were not shown at all.
Fixes #22642
=> command/jsonstate: properly marshal deposed resources

website/docs/providers/index.html.markdown, website/docs/providers/type/monitor-index.html.markdown
Adding two links that will point to the provider documentation for the new certified Venafi provider
=> [Website] Add links to provider documentation

command/plan.go
This removes a duplicate statement, so `opReq.PlanRefresh` is set only once (as per `command/apply.go`)
=> remove duplicate statement

command/validate.go
This PR removes the unused flags in the `validate` command.
The `-var` and `-var-file` command line options are unused (and in the case of any `var`s given on the command line, overwritten).
#22938 was recently opened to reconcile the `validate` documentation with actual behavior.
=> command/validate: warn if unused flags are set on the command line

builtin/provisioners/puppet/resource_provisioner.go
Before this, the Terraform Puppet provisioner would error out in a
confusing way if the type attribute in a connection block was not given.
Apparently an omitted type leads to type having a value "" which must be
then assumed to mean "ssh".
=> Bugfix for #23004

backend/remote/backend_apply.go, backend/remote/backend_common.go, backend/remote/backend_context.go, backend/remote/backend_plan.go, backend/unparsed_value.go
The remote backend uses `backend.ParseVariableValues` locally only to decide if the user seems to be trying to use -var or -var-file options locally, since those are not supported for the remote backend.
Other than detecting those, we don't actually have any need to use the results of `backend.ParseVariableValues` locally, and so it's better for us to ignore any errors it produces itself and prefer to just send a potentially-invalid request to the remote system and let the remote system
be responsible for validating it.
This then avoids issues caused by the fact that when remote operations are in use the local system does not have all of the required context: it can't see which environment variables will be set in the remote execution context nor which variables the remote system will set …
=> backend/remote: Report invalid variables only remotely

website/docs/providers/index.html.markdown, website/docs/providers/type/infra-index.html.markdown
Okta has requested that we remove their recently certified provider.
=> [Website] remove okta link

terraform/context_apply_test.go, terraform/evaluate.go
Again, doesn't fix the root cause, but builds on https://github.com/hashicorp/terraform/pull/22729 to help a bit as far as improving the error context to show users that `each.value` is the source of their error, versus the ambiguous error otherwise.
Related to https://github.com/hashicorp/terraform/issues/22700
=> Add a special error when each.value is nil in for_each resources

website/docs/configuration/providers.html.md
The instructions don't currently specify which directory to run `terraform init` from. This PR assumes that it doesn't matter. If I'm wrong about that, please comment below and I'll change this PR or open another.
=> Clarify where you run the `terraform init` command

terraform/context_apply_test.go, terraform/graph_builder_apply_test.go, terraform/testdata/apply-destroy-data-cycle/main.tf, terraform/testdata/apply-module-replace-cycle-cbd/main.tf, terraform/testdata/apply-module-replace-cycle-cbd/mod1/main.tf, terraform/testdata/apply-module-replace-cycle-cbd/mod2/main.tf, terraform/testdata/apply-module-replace-cycle/main.tf, terraform/testdata/apply-module-replace-cycle/mod1/main.tf, terraform/testdata/apply-module-replace-cycle/mod2/main.tf, terraform/transform_destroy_edge.go, terraform/transform_diff.go
This PR removes extra connections from the graph which are unneeded, however only cause problems in certain destroy scenarios. This solves a number of common cycles issues, while simplifying the graph itself. It does not solve all cycles, as destroy nodes still need their references evaluated in order for destroy-provisioners to function. 
---
Destroy nodes do not need to be connected to the resource (prepare
state) node when adding them to the graph. Destroy nodes already have a
complete state in the graph (which is being destroyed), any references
will be added in the ReferenceTransformer, and the proper
connection to the create node will be added in the
DestroyEdgeTransformer.
Under normal circumstances this makes no difference, as create and
destroy nodes always have a direct …
=> Remove some destroy cycles

configs/configload/copy_dir.go
fixes #22844 
This is a question, really: do we need to exclude dotfiles in `copyDir`?
`copyDir` is used in `configload/getter.go` to copy previously downloaded modules instead of using the go-getter client every time. The go-getter client downloads dotfiles, but `copyDir` did not copy dotfiles, leading to inconsistent behaviour when reusing the same module source.
=> remove dotfile exclusion in copyDir

website/docs/configuration/expressions.html.md
Add a note near count vs. for_each about the splat operator.
Closes #22476, as it appears that issue is about clarification/docs versus a bug report.
=> Docs around splat and for_each

website/docs/providers/index.html.markdown, website/docs/providers/type/cloud-index.html.markdown
Adding the links to navigate to the Vultr provider docs
=> [Website] Vultr provider links

website/docs/commands/taint.html.markdown
https://www.terraform.io/docs/commands/taint.html#aws_instance-baz-quot-key-quot- has weird things happening on render. Separating the two causes the render to work correctly, at least when built locally (`make website`)
Related to https://github.com/hashicorp/terraform/pull/23185
=> Quote differently so render works on taint docs

lang/eval.go, terraform/context_apply_test.go, terraform/testdata/apply-provisioner-for-each-self/main.tf
The fallback type for `GetResource` from an `EachMap` is a `cty.Object`,
because resource schemas may contain dynamically typed attributes.
Check for an Object type in the evaluation of self, to use the proper
`GetAttr` method when extracting the value.
Fixes #23194
=> Resource value may be an object in self evaluation

website/docs/import/usage.html.md
As mentioned in  #17871 the current example can hide the fact that the module
path plays an important role. The example's explanation is expanded.
Moreover, the verb "attach" is replaced with "map" to make the vocabulary
consistent with the wording in the documentation of the terraform state.
=> Expand example explanation

go.mod, go.sum, vendor/github.com/mitchellh/panicwrap/go.mod, vendor/github.com/mitchellh/panicwrap/go.sum, vendor/github.com/mitchellh/panicwrap/panicwrap.go, vendor/modules.txt
panicwrap now unsets the cookie env variable it uses in Wrapped()
to check if we are in a panic wrapped context.
This correct a false positive when teraform execute itself recurcively.
Fixes #20293.
=> Bump panicwrap's version to fix issue 2093

helper/plugin/grpc_provisioner.go, helper/plugin/grpc_provisioner_test.go
The grpc protocol requires strings to be valid utf8, but because
provisioners often don't have control over the command output, invalid
utf8 sequences can make it into the response causing grpc transport
errors.
Replace all invalid utf sequences with the standard utf replacement
character in the provisioner output. The code is a direct copy from the
go1.13 std library, and can be replaced with strings.ToValidUTF8 once
it's available.
Replaces #22957
Fixes #23300
=> sanitize provisioner output strings

panic.go
Sensitive information can be accidentally uploaded to the issue tracker if the crash log file isn't redacted by the operator.
=> Add security warning to panicOutput

backend/remote-state/artifactory/backend.go
Added a minimal transport to the artifactory client so that it support proxy environment variables. This should fix this issue https://github.com/hashicorp/terraform/issues/9403 .
Upstream there's this issue opened https://github.com/lusis/go-artifactory/issues/9 but I think there might need to be some refactor on terraform's side to support the latest client.
=> Add support for HTTP proxy env vars.

command/output.go, command/output_test.go
This PR adds an `-ignore-empty-output` flag to the `terraform output` command.
With this flag, when `terraform output -ignore-empty-flag` is run against no state or empty state, the exit status is 0 and the output is not from Error().
Without this flag, when `terraform output` is run against no state or empty state, the exit status remains 1 and the output continues to be from Error().
When merged, resolves #18975
=> Add -ignore-empty-output flag

website/docs/backends/types/remote.html.md, website/docs/state/workspaces.html.md
This PR seeks to clarify distinctions between the TF OSS and Terraform Cloud workspace concepts in order to avoid confusion such as that shown in https://github.com/hashicorp/terraform/issues/22802 and https://github.com/hashicorp/terraform/issues/21507.
It also clarfies that the `prefix` key cannot be used when configuring the terraform-remote_state data source.
It also points out that the `${terraform.workspace}` interpolation should not be used in Terraform code used in remote runs on TFC workspaces.
=> Doc workspace concepts

website/docs/state/sensitive-data.html.md
Stop documenting the now-deprecated pgp_key pattern.
=> Remove pgp_key paragraph.

command/format/diff.go, command/format/diff_test.go
We have a special treatment for multi-line strings that are being updated in-place where we show them across multiple lines in the plan output, but we didn't use that same treatment for rendering multi-line strings in isolation such as when they are being added for the first time.
Here we detect when we're rendering a multi-line string in a no-change situation and render it using the diff renderer instead, using the same value for old and new and thus producing a multi-line result without any diff markers at all.
This improves consistency between the change and no-change cases, and makes multi-line strings (such as YAML in block mode) readable in all cases.
Before:
```
+ resource "null_resource" "foo" {
+ id       = (known after apply)
+ triggers = {
+ "a" = "foo\nbar\nbaz\n"
}
}
``` …
=> command/format: multi-line rendering for unchanged strings

terraform/context_apply_test.go, terraform/eval_apply.go, terraform/node_resource_apply_instance.go, terraform/testdata/apply-destroy-tainted/main.tf
If there are errors while deleting an instance, mark the instance as
tainted. This ensures the instance remains queued for deletion, as it
may have been tainted in the first place.
Fixes #22011
=> Make sure a failed destroy is marked as tainted

lang/funcs/collection.go, lang/funcs/collection_test.go
=> transpose function  - return empty list when value is empty #23299

command/format/diff.go, command/format/diff_test.go
Fixes #21473
The previous code incorrectly compared the old value of the object with
a new value at the same index, even if the value was common to both
lists but occurs in old later. This caused confusing and wrong diffs if
you deleted an object in the middle of a list.
=> Fix diff of list of objects

command/version.go
Adding a protocol segment to the download link discourages parsers from interpreting the link as a filesystem link. For example in a terminal this does not currently work,
```
~$ open www.terraform.io/downloads.html 
The file ~/www.terraform.io/downloads.html does not exist.
```
But this does:
```
~$ open https://www.terraform.io/downloads.html 
```
=> Enhance link click-ability

website/docs/commands/taint.html.markdown
I've seen folks ask about how to express this in resource address syntax a number of times now, so adding this example here to illustrate how it looks when there are multiple levels of module to traverse through.
This is redundant with other information further up the page, but having it as an entirely separate example gives an opportunity to include more introductory text to explain what the example is showing.
=> website: example of "terraform taint" with a grandchild module

states/statemgr/filesystem.go
Looks like `multierror.Append(idErr, err)` is assigned to the `err` variable which is not used/returned the so updated it to `idErr`.
=> Update filesystem unlock err

Dockerfile
This removes about 1.3mb of stuff in /var/cache/apk.
=> Don't keep stale apk index cache in docker image

configs/named_values.go
The error message when an identifier begins with a digit or other invalid first character says that identifiers must start with a letter. However, underscores are also acceptable, as stated in the docs:
https://github.com/hashicorp/terraform/blob/6eb40f846b5984ea64339c30e934f87952db1835/website/docs/configuration/resources.html.md#L49-L50
This PR fixes the error message.
=> Correct identifier validation error message

configs/compat_shim.go, configs/named_values.go, configs/provider.go, configs/resource.go, configs/testdata/valid-files/references.tf.json, configs/testdata/valid-files/variable-type-quoted.tf, configs/testdata/warning-files/redundant_interp.tf, configs/testdata/warning-files/variable_type_quoted.tf
Following on from #23329, this introduces deprecation warnings for when an attribute value expression is a template with only a single interpolation sequence, and for variable type constraints given in quotes.
As with the previous commit, we allowed these deprecated forms with no warning for a few releases after v0.12.0 to ensure that folks who need to write cross-compatible modules for a while during upgrading would be able to do so, but we're now marking these as explicitly deprecated to guide
users towards the new idiomatic forms.
The `terraform 0.12upgrade` tool would've already updated configurations to not hit these warnings for those who had pre-existing configurations written for Terraform 0.11.
The main target audience for these warnings are newcomers to Terraform who are …
=> configs: Warn for deprecated interpolation and quoted type constraints

backend/remote/backend_context.go, backend/remote/backend_context_test.go, backend/remote/backend_mock.go, backend/remote/testing.go
Following up on #23122, the remote system (Terraform Cloud or Enterprise) serves environment and Terraform variables using a single type of object. We only should load Terraform variables into the Terraform context.
Fixes https://github.com/hashicorp/terraform/issues/23283.
=> backend/remote: Filter environment variables when loading context

command/meta_backend.go
`Meta.backendConfig` was incorrectly treating the second return value from `loadBackendConfig` as if it were go `error` rather than `tfdiags.Diagnostics`, which in turn meant that it would treat warnings like
errors.
This had confusing results because it still returned that `tfdiags.Diagnostics` value in its own diagnostics return value, causing the caller to see warnings even though the `backendConfig` function had taken
the error codepath.
In particular, this fixes #23370.
=> command: Don't treat config warnings as errors

command/format/diff.go, command/format/diff_test.go
Fix for #23100 where `terraform plan` panics instead of decoding the string "null" with whitespace. Underlying cause is that `json.Decoder` tokenises "null" with any amount of whitespace around it as a `nil` value ([demonstration](https://gist.github.com/simonbrady/6e15f76faead23c58ee7abc60b2fcad7)), but the code only checks for literal `"null"`.
=> Fix #23100: Panic in plan output when string contains "null" with whitespace

go.mod, go.sum, vendor/github.com/hashicorp/go-slug/terraformignore.go, vendor/github.com/hashicorp/go-tfe/README.md, vendor/github.com/hashicorp/go-tfe/go.mod, vendor/github.com/hashicorp/go-tfe/go.sum, vendor/github.com/hashicorp/go-tfe/oauth_client.go, vendor/modules.txt
=> [deps] Update go-tfe

command/meta.go, tfdiags/consolidate_warnings.go, tfdiags/consolidate_warnings_test.go
Some of our warning messages are produced in response to the use of deprecated language constructs that might be used many times across a whole configuration, and so the resulting warnings can easily overwhelm the other parts of Terraform's output from commands like `terraform plan`.
As a compromise, we'll detect when the diagnostics includes more than two warnings with the same summary text and consolidate the third and any further warnings into a single count of additional warnings at the end of the second warning message, like this:
```
Warning: Interpolation-only expressions are deprecated
on cli-consolidate-warnings.tf line 7, in resource "null_resource" "b":
7:   triggers = "${map("a", "b")}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via …
```
=> Consolidate repetitive warning messages

terraform/testdata/transform-destroy-cbd-edge-multi/main.tf, terraform/transform_destroy_cbd.go, terraform/transform_destroy_cbd_test.go
An earlier change to eliminate the large amount of duplicate edges being
added by the original CreateBeforeDestroy dependency mapper mistakingly
prevented adding edges when there are multiple CBD dependencies.
This updates the algorithm to use a map to collect all possible edges
and de-deplucating them before processing.
Possible alternative to #23426
Also fixes #23422
=> fix CreateBeforeDestroy de-duplication

states/statefile/testdata/roundtrip/v3-invalid-depends.in.tfstate, states/statefile/testdata/roundtrip/v3-invalid-depends.out.tfstate, states/statefile/version3_upgrade.go, website/upgrade-guides/0-12.html.markdown
In #21435 we can see three different specific issues arising from the state format upgrade codepath moving between Terraform 0.11 and Terraform 0.12:
1. Terraform 0.11 had a habit of leaving behind old entries in `depends_on` in state snapshots after various operations, including the `terraform state mv` command we recommended for fixing invalid resource names (starting with digits) in `terraform 0.12checklist`. The state upgrade would then choke on these and refuse to proceed, even though in practice such invalid references are generally ignored completely by Terraform 0.11 after `terraform state mv` has orphaned them.
2. Terraform 0.11 treated the resource `provider` argument as a literal string always, and allowed it to include all sorts of weird and wonderful punctuation characters. …
=> Address some problems with state upgrade from 0.11 to 0.12

terraform/context_apply_test.go, terraform/graph_builder_apply_test.go, terraform/node_resource_destroy_deposed.go, terraform/terraform_test.go, terraform/transform_destroy_cbd_test.go, terraform/transform_destroy_edge.go
Pulls the most critical changes from #23426
- Node string format was missing deposed key
- The CBD transformation uses state information, but the tests didn't include any state.
- Dependencies connections were referencing the instance address when they should have been using the resource address.
- The dependency connection is correct (the CBD transformation is what needed to be fixed), so remove TODO about changing it.
=> Minor dependency handling fixups

website/docs/backends/types/remote.html.md
Example reference had a missing `=` sign on line 133; this causes the workspace reference not to parse properly
=> Fix example reference for remote backend

command/jsonplan/values.go, command/jsonplan/values_test.go, command/jsonstate/state.go, command/jsonstate/state_test.go
The code responsible for marshalling attribute values was checking for
nil values, but not null.
Fixes #23485, #23274
=> command/json{state,plan}: check for null values

website/docs/configuration/functions/cidrsubnets.html.md
Some sections of the documentation, including the title, have `cidrsubnet` instead of `cidrsubnets` written.
=> Corrects function name in `cidrsubnets` function documentation

addrs/provider_type.go, command/init.go, command/plugins_test.go, plugin/discovery/get.go, plugin/discovery/get_test.go, tools/terraform-bundle/package.go
`addrs.ProviderType{Name}` should have been `{Type}`. 
A `ProviderType` may have multiple names, and may end up with a field like `Name []string` (or some other associative mechanism). The existing `name` field was intended as `Type` 
As an example: the type should be `google`, while the name might be `google-beta` or `google.alias`.
=> addrs: rename Provider Name to more accurate Provider Type

.github/ISSUE_TEMPLATE/config.yml, .github/SECURITY.md
As I discovered, GitHub can prioritize link to a security policy, if that is defined under the right file - see https://github.com/hashicorp/terraform-plugin-sdk/pull/267 for example.
I'm therefore proposing replacement of a custom link with policy in this repo too as that will make the (critical) link much more visible.
=> github: Make link to vulnerability reports more visible

terraform/evaluate.go
NoEach and Each list both have this check, but it was missing in
EachMap. Refactor the EachList check to remove a level of indentation,
and make the check consistently near the start of the block.
This fixes #23522 by preventing the panic, but the mechanism that removes the Current instance is still not fully understood. It may be due to unexpected behavior of the provider, which we can better observe once the panic is caught.
=> check for missing Current instance in EachMap

website/intro/index.html.markdown
⚠️ this PR has a companion PR on the `terraform-website` repo that handles it's required CSS updates: https://github.com/hashicorp/terraform-website/pull/1036. It's important (although not entirely essential) that this PR be merged after it's companion is merged and deployed.
context: the impetus for adding this video comes from a request from Armon Dadgar...
> I do think it would be worth getting some of them onto the IO sites as well, like quick "what is TF" type videos - armon
=> website: add yt video to /intro

command/format/diff.go
On formatting plan result, prefixes (indicators) before resource name and prefixes before the description are generated by different code.
```
~ update in-place
...
~ resource "aws_security_group" "..." {
↑
them
```
This is so tiny point, but should deserve to be fixed.
By this change,
- whitespaces before sign go out of color codes (e.g.: `[green]__+[reset]` → `__[green]+[reset]`)
- unknown action shows `__?` rather than `???`
but these changes can be affordable.
=> make plan-diff format a bit more dry

command/internal_plugin.go, command/internal_plugin_test.go
This fixes #14847, #17094 
Hi,
This PR fixes the internal plugins breaking over the amount of `args` received. Though it might be a bit naïve.
My first approach was to add an exception to `mergeEnvArgs`, to simply skip the merge if the command was `internal-plugin`. Something something, separation of concerns, so I decided to let the internal plugin command handle this. I think the cli package guarantees that all command options/flags are prefixed with a dash, making it easy and reliable to filter these.
I added a unit test for the newly added function. I couldn't find any test that actually called the `Run` function, but I might have overlooked something.
=> Strip flags from internal_plugin args (fixes TF_CLI_ARGS usage)

command/state_mv.go, command/state_mv_test.go
If a state mv target happens to be a resource that doesn't exist, allow
the creation of the new resource inferring the EachMode from the target
address.
Fixes #22301
Fixes #23569
=> Allow moving instances to new resources

configs/provisioner.go, configs/resource.go, configs/testdata/warning-files/destroy-provisioners.tf
Add deprecation warning for references from destroy provisioners or
their connections to external resources or values. In order to ensure
resource destruction can be completed correctly, destroy nodes must be
able to evaluate with only their instance state.
We have sufficient information to validate destroy-time provisioners
early on during the config loading process. Later on these can be
converted to hard errors, and only allow self, count.index, and each.key
in destroy provisioners. Limiting the provisioner and block evaluation
scope later on is tricky, but if the references can never be loaded,
then they will never be encountered during evaluation.
Destroy provisioner were added way back in the 0.9.0 release. The initial concept was simple, but the implications of the added …
=> deprecation warning for destroy provisioner refs

command/format/diff.go, command/show_test.go
Don't inspect an empty set, return false
Fixes #23377
=> Fix panic on show plan

command/meta_config.go, configs/provisioner.go
This updates the text to be more user-oriented:
```
Warning: External references from destroy provisioners are deprecated
on main.tf line 12, in resource "null_resource" "new":
12:     command = local.command
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.
References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.
```
Suppress warnings from loading the backend config. 
These will be caught again later when the entire config is loaded, and would be duplicated in the output.
Cosmetic updates for #23559
=> Update destroy provisioner warnings

configs/experiments.go, configs/experiments_test.go, configs/module.go, configs/parser_config.go, configs/testdata/experiments/concluded/concluded_experiment.tf, configs/testdata/experiments/current/current_experiment.tf, configs/testdata/experiments/invalid/invalid_experiments.tf, configs/testdata/experiments/unknown/unknown_experiment.tf, experiments/doc.go, experiments/errors.go, experiments/experiment.go, experiments/set.go, experiments/testing.go
Traditionally we've preferred to release new language features in major releases only, because we can then use the beta cycle to gather feedback on the feature and learn about any usability challenges or other situations we didn't consider during our design in time to make those changes before inclusion in a stable release.
This "experiments" feature is intended to decouple the feedback cycle for new features from the major release rhythm, and thus allow us to release new features in minor releases by first releasing them as experimental for a minor release or two, adjust for any feedback gathered during that period, and then finally remove the experiment gate and enable the feature for everyone.
The intended model here is that anything behind an experiment gate is subject to breaking …
=> experiments: a mechanism for opt-in experimental language features

command/apply.go, command/format/diagnostic.go, command/format/diagnostic_test.go, command/meta.go, command/plan.go, command/refresh.go, tfdiags/consolidate_warnings.go, tfdiags/consolidate_warnings_test.go, website/docs/commands/apply.html.markdown, website/docs/commands/plan.html.markdown, website/docs/commands/refresh.html.markdown
When warnings appear in isolation (not accompanied by an error) it's reasonable to want to defer resolving them for a while because they are not actually blocking immediate work.
However, our warning messages tend to be long by default in order to include all of the necessary context to understand the implications of the warning, and that can make them overwhelming when combined with other output.
As a compromise, this adds a new CLI option `-compact-warnings` which is supported for all the main operation commands and which uses a more compact format to print out warnings as long as they aren't also accompanied by errors. This is mainly intended for use in automation scenarios where work is being sent to production, as opposed local development scenarios while working on changes to a …
=> command: New -compact-warnings option

website/docs/configuration/functions/templatefile.html.md
It's a common source of errors to try to produce JSON or YAML syntax using string concatenation via our template language but to miss some details like correct string escaping, quoting, required commas, etc.
The `jsonencode` and `yamlencode` functions are a better way to generate JSON and YAML, but it's not immediately obvious that both of these functions are available for use in external templates (via `templatefile`) too.
Given that questions related to this come up a lot in our community forum and elsewhere, it seems worth having a documentation section to show the pattern of having a template that consists only of a single function call.
=> website: Note about using jsonencode/yamlencode in templatefile

go.mod, go.sum, vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md, vendor/github.com/hashicorp/hcl/v2/README.md, vendor/github.com/hashicorp/hcl/v2/appveyor.yml, vendor/github.com/hashicorp/hcl/v2/go.mod, vendor/github.com/hashicorp/hcl/v2/go.sum, vendor/github.com/hashicorp/hcl/v2/gohcl/decode.go, vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go, vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go, vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go, vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_body.go, vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_expression.go, vendor/github.com/hashicorp/hcl/v2/hclwrite/generate.go, vendor/github.com/zclconf/go-cty/cty/convert/conversion_primitive.go, vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go, vendor/github.com/zclconf/go-cty/cty/gob.go, vendor/github.com/zclconf/go-cty/cty/set_internals.go, vendor/modules.txt
This also includes an upgrade to cty v1.1.1 because HCL calls for it.
The changes in these two libraries are mainly to codepaths that don't directly affect Terraform, but including this upgrade will cause some small improvements to Terraform's error messages for type conversion problems.
=> vendor: go get github.com/hashicorp/hcl/v2@v2.2.0

backend/remote-state/http/client_test.go
This fixes two dropped errors in `backend/remote-state/http`, and removes the unused test function `assertError()`.
=> Fix backend remote state dropped test errors

terraform/context_apply_test.go, terraform/node_resource_abstract.go, terraform/provisioner_mock.go, terraform/testdata/apply-plan-connection-refs/main.tf
References from a resource-level connection blocks were not returned from
`NodeAbstractResource.References`, causing the provisioner connection
attributes to sometimes be evaluated too early.
Fixes #23201
=> check resource-level connections block for references

Makefile, tools/terraform-bundle/package.go
We must use the `addrs.NewLegacyProvider()` func when creating a new `addrs.Provider`
Fixes #23652
=> terraform-bundle: fix panic with addrs.Provider

communicator/ssh/communicator.go
If there is an error when opening the session for agent forwarding in
the process ssh connention, there is a deadlock when recursively
calling Connect on an internal reattempt. Avoid that, and let the
connection be reattempted externally.
Fixes: #23662
=> ssh: Fix deadlock on agent forwarding error

website/docs/configuration/syntax-json.html.md
Fixes a little markup misuse.
[Here's how it was before](https://www.terraform.io/docs/configuration/syntax-json.html):
=> website: Fix inpage link in docs

backend/remote-state/gcs/backend.go, website/docs/backends/types/gcs.html.md
Right now, the only environment variable available is the same
environment variable that will be picked up by the GCP provider. Users
would like to be able to store state in separate projects or accounts or
otherwise authenticate to the provider with a service account that
doesn't have access to the state. This seems like a reasonable enough
practice to me, and the solution seems straightforward--offer an
environment variable that doesn't mean anything to the provider to
configure the backend credentials. I've added GOOGLE_BACKEND_CREDENTIALS
to manage just the backend credentials, and documented it appropriately.
Fixes terraform-providers/terraform-provider-google#4209.
=> Add a backend-specific env var for the GCS backend.

command/workspace_command.go
The help documentation for "docker workspace" shows New with camel case N which is wrong. This commit fixes the doc error for following commands:
~/C/terraform ❯❯❯ docker run -i -t terraform workspace New                        
Usage: terraform workspace
new, list, show, select and delete Terraform workspaces.
~/C/terraform ❯❯❯ docker run -i -t terraform workspace                                  
Usage: terraform workspace
new, list, show, select and delete Terraform workspaces.
~/C/terraform ❯❯❯ docker run -i -t terraform workspace --usage                          
Usage: terraform workspace
new, list, show, select and delete Terraform workspaces.
=> small fix with command usage 'terraform workspace New'

terraform/graph_builder_apply_test.go, terraform/node_resource_destroy.go, terraform/testdata/graph-builder-orphan-alias/main.tf
The resource cleanup node does not need a provider. We can't directly
remove the ProvidedBy method, but this node only needs to be eval-able so
we can remove all the NodeAbstractResource methods at once.
Fixes #23671
Fixes #22758
=> NodeDestroyResource does not need a provider

website/docs/cli-index.html.md
The .html suffix redirects correctly, but it's not the 'real' path and thus
can throw off analytics. Cf. https://github.com/hashicorp/terraform-website/pull/1062
=> website: Use canonical URLs for learn.hashicorp.com links

terraform/context_apply_test.go, terraform/eval_state.go, terraform/node_resource_apply_instance.go
This is a "should never happen" case, but we have reports of it actually happening. In order to try to collect a bit more data about what's going on here, we're changing what was previously a hard panic into a normal error message that can include the address of the instance we were working on and the action we were trying to do to it at the time.
The hope is to narrow down what situations can trigger this in order to find a reliable reproduction case in order to debug further. This also means that for those who _do_ encounter this problem in the meantime Terraform will have a chance to shut down cleanly and therefore be more likely to be able to recover on a subsequent plan/apply cycle.
Further investigation of this will follow once we see a report or two of this updated error message. …
=> core: Don't panic if EvalMaybeResourceDeposedObject has no DeposedKey

command/command_test.go, command/state_mv.go, command/state_mv_test.go
Clear any Dependencies if there is an entry matching a `state mv` from
address. While stale dependencies won't directly effect any current
operations, clearing the list will allow them to be recreated in their
entirety during refresh. This will help future releases that may rely
solely on the pre-calculated dependencies for destruction ordering.
Closes #23711
=> remove stale dependencies on `state mv`

website/docs/registry/modules/publish.html.md
This is a minor change on the [Publishing Modules](https://www.terraform.io/docs/registry/modules/publish.html) page of the Terraform documentation.
The **Force GitHub Sync** option of the dropdown menu has been renamed to **Resync Module**.
=> website: update publishing modules documentation

configs/configload/getter.go, internal/initwd/getter.go
In an earlier change we switched to defining our own sets of detectors, getters, etc for `go-getter` in order to insulate us from upstream changes to those sets that might otherwise change the user-visible behavior of Terraform's module installer. We want these to change only intentionally on our part so that we can be sure to also update the relevant documentation and mention it in the changelog, rather than inadvertently introducing new functionality as part of bringing in upstream bug fixes.
However, we apparently neglected to actually refer to our local set of detectors, and continued to refer to the upstream set. Here we catch up with the latest detectors from upstream (taken from the version of `go-getter` we currently have vendored) and start using that fixed set.
Currently we are …
=> configs: use local set of go-getter detectors

website/docs/commands/state/show.html.md
In earlier versions of Terraform the result of terraform state show was in the pre-0.12 "flatmap" structure that was unable to reflect nested data structures. That was fixed in Terraform 0.12, but as a consequence this statement about the output being machine-parseable (which was debateable even in older versions) is incorrect.
Fortunately, we now have `terraform show -json` to get output that is _explicitly_ machine-parseable, so we'll recommend to use that instead here. The JSON output of that command is a superset of what's produced by `terraform state show`, so should be usable to meet any use-case that might previously have been met by parsing the `terraform state show` output.
=> docs: terraform state show is not machine-readable

internal/initwd/module_install.go, internal/initwd/module_install_test.go
Closes #23544
Suggestions for tests that specifically exercise this feature appreciated - the ideas I had felt more complicated (and fragile) than was worthwhile so I'd love to hear better ones. 
Some relevant trace output (using the example from #23544 ):
```
2019/12/19 11:16:04 [DEBUG] Module installer: security-group-reg-1 installed at .terraform/modules/security-group-reg-1/terraform-aws-modules-terraform-aws-security-group-57856b3
2019/12/19 11:16:04 [DEBUG] Module installer: begin security-group-reg-2
2019/12/19 11:16:05 [TRACE] ModuleInstaller: security-group-reg-2 is not yet installed
2019/12/19 11:16:05 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/security-group-reg-2 prior to install of security-group-reg-2
- security-group-reg-1 in …
```
=> initwd: cache registry responses for module versions and download URL

command/init.go, command/meta_backend.go, command/meta_backend_test.go, command/testdata/backend-from-state/terraform.tfstate
When a user runs `terraform init --backend=false`, terraform should
inspect the state for a previously-configured backend, and use that
backend, ignoring any backend config in the current configuration. If no
backend is configured or there is no state, return a local backend.
Fixes #16593
=> command: use backend config from state when backend=false is used.

terraform/context_apply_test.go, terraform/graph_builder_apply.go, terraform/terraform_test.go, terraform/testdata/plan-destroy-interpolated-count/main.tf, terraform/testdata/plan-destroy-interpolated-count/mod/main.tf, terraform/transform_reference.go
Since a planned destroy can no longer indicate it is a full destroy,
unused values were being left in the apply graph for evaluation. If
these values contains interpolations that can fail, (for example, a
zipmap with mismatched list sizes), it will cause the apply to abort.
The PruneUnusedValuesTransformer was only previously run during destroy,
more out of conservatism than for any other particular reason. Adapt it
to always remove unused values from the graph, with the exception being
the root module outputs, which must be retained when we don't have a
clear indication that a full destroy is being executed.
=> Always prune unused values

plugin/client.go
When using the new provider binary acceptance testing framework, disabling AutoMTLS for Core-provider gRPC communication leads to test run speed improvements of between 10% (for a typical provider) and 70% (for an in-memory provider such as `random`).
This PR allows AutoMTLS to be disabled at runtime with the `TF_DISABLE_AUTOMTLS` env var. The binary testing framework would set this env var when running `terraform` commands.
@apparentlymart , requesting review as you have some context on this from previous discussion.
=> Allow disabling plugin AutoMTLS with TF_DISABLE_AUTOMTLS env var

command/graph.go, website/docs/commands/graph.html.markdown
Update docs to reflect that `-module-depth` won't change output in current versions of Terraform
Fixes https://github.com/hashicorp/terraform/issues/23750
=> (docs) Update docs to reflect current behavior for module-depth

terraform/node_resource_destroy.go, terraform/transform_provider.go
The change in #23696 removed the NodeAbstractResource methods from the
NodeDestroyResource type, in order to prevent other resource behaviors,
like requesting a provider.
While this node type is not directly referenced, it was implicitly
ordered against the module cleanup by virtue of being a resource node.
The ReferenceTransformer uses the GraphNodeReferenceable and
GraphNodeSubPath interfaces to add nodes to the reference map, so we
need to re-add the relevant methods.
Since there's no good entry point to test this ordering at the moment,
add static checks for the interfaces, and document where these
interfaces are required.
Fixes #23821
=> NodeDestroyResource needs to be referencable

configs/module.go, configs/module_merge.go, configs/module_merge_test.go, configs/parser_config.go, configs/provider_requirements.go, terraform/module_dependencies.go, terraform/module_dependencies_test.go, terraform/testdata/module-deps-required-providers/main.tf
Renamed `file.ProviderRequirements` to` file.RequiredProviders` to match the
name of the block in the configuration. `file.RequiredProviders` contains
the contents of the file(s); `module.ProviderRequirements` contains the
parsed and merged provider requirements.
Extended `decodeRequiredProvidersBlock` to parse the new provider source
syntax (version only, it will ignore any other attributes).
Added some tests; swapped `deep.Equal` with `cmp.Equal` in
`terraform/module_dependencies_test.go` because deep was not catching
incorrect constraints.
=> configs: extend module.ProviderRequirements to include an addrs.Provider instead of just version constraints.

command/format/state.go, command/init_test.go, command/plugins_test.go, command/show_test.go
The formatter in `command/format/state.go`, when formatting a resource
with an aliased provider, was looking for a schema with the alias (ie,
test.foo), but the schemas are only listed by provider type (test).
Update the state formatter to lookup schemas by provider type only.
Some of the show tests (and a couple others) were not properly cleaning
up the created tmpdirs, so I fixed those. Also, the show tests are using
a statefile named `state.tfstate`, but were not passing that path to the
show command, so we were getting some false positives (a `show` command
that returns `no state` exits 0).
Fixes #21462
=> command/show: fix issue with show and aliased provider

configs/provisioner.go, configs/testdata/warning-files/destroy-provisioners.tf
The path values are statically loaded, and do not create any
dependencies that could cause problems with destroy provisioners.
closes #23675
=> it's safe for destroy provisioners to access path

backend/unparsed_value.go
There have been several issues and a few PRs opened to address these warnings introduced in 0.12 and its pretty clear there is no intention of removing or silencing them.
However, it's extremely common that users are using tfvars for sensitive values, so treating these as hcl diags and exposing the source and thus, the value of the var is not ideal. Changing the feedback on the error should correct this.
This should fix #22782
=> Avoid leaking sensitive values in undeclared variable warnings

website/docs/providers/index.html.markdown, website/docs/providers/type/cloud-index.html.markdown
Adding two links to point to the new metalcloud provider docs
=> [Website] Add MetalCloud provider links

internal/getproviders/legacy_lookup.go, internal/getproviders/legacy_lookup_test.go, internal/getproviders/multi_source.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go
This is a temporary helper so that we can potentially ship the new provider installer without making a breaking change by relying on the old default namespace lookup API on the default registry to find a proper FQN for a legacy provider provider address during installation.
If it's given a non-legacy provider address then it just returns the given address verbatim, so any codepath using it will also correctly handle explicit full provider addresses. This also means it will automatically self-disable once we stop using `addrs.NewLegacyProvider` in the config loader, because there will therefore no longer be any legacy provider addresses in the config to resolve. (They'll then be "default" provider addresses instead, assumed to be under `registry.terraform.io/hashicorp/*` and not subject to …
=> internal/getproviders: LookupLegacyProvider

internal/modsdir/manifest.go
Fixes an issue related to #22234 
In order to maintain compatibility between Windows CLI and remote plan and apply, the remote system, Terraform Cloud in this case, needs to be able to properly utilize the module path in the module manifest within the .terraform directory.
Windows writes the module path with its standard file path separator `\` as provided by the `filepath.Separator` function. Terraform Cloud, being Linux based, requires a different path separator `/`.
To appease both platforms without causing issue to how the functions operate, I have written a condition to always write the Linux-style path structure in to the module manifest file. To ensure there are no issues in Windows, I have added a condition that while reading the module manifest, the path is read in to memory …
=> Fix compatibility issue between Windows CLI and remote plan and apply

website/docs/configuration/expressions.html.md
The current docs use `aws_security_group`, which is a resource where the referenced attribute in the example is in attributes-as-blocks mode, and thus, should not be used with dynamic blocks (because setting the `for_each` iterator to `[]` will result in "unset" versus "set to none" behavior).
This updates to use the `aws_elastic_beanstalk_environment` resource, whose `setting` attribute does not have the same issues (it is _not_ attributes as blocks mode)
=> Update dynamic block docs to use a better example

command/meta.go, commands.go, main.go
Following the same approach we use for other CLI-Config-able objects like the service discovery system, the main package is responsible for producing a suitable implementation of this interface which the command package can then use.
When unit testing in the command package we can then substitute mocks as necessary, following the dependency inversion principle.
For now this is hard-coded to use the `RegistrySource` implementation that knows how to find providers directly from their origin registries. In future we plan to make this configurable to also allow installing from local and network mirrors, but the `cliconfig` package will need some further work before that will be possible and we will likely defer that for now until we're ready to start introducing the real network/filesystem …
=> command: Accept a "provider source" from the main package

website/docs/configuration/resources.html.md
Document that `for_each` values on resources must have known keys, to reduce confusion surrounding passing "known" values to `for_each` and getting errors (such as the case of using imperfect functions, like `uuid`, in relation to creating `for_each` key values)
- Closes https://github.com/hashicorp/terraform/issues/22735
- Closes https://github.com/hashicorp/terraform/issues/23052
=> Document for_each key requirements

backend/local/backend_plan.go, command/format/state.go, command/format/state_test.go, command/jsonconfig/config.go, command/jsonplan/plan.go, command/jsonplan/values.go, command/jsonplan/values_test.go, command/jsonprovider/provider.go, command/jsonprovider/provider_test.go, command/jsonstate/state.go, command/jsonstate/state_test.go, configs/config.go, terraform/context_input.go, terraform/eval_context_builtin.go, terraform/evaluate.go, terraform/evaluate_valid.go, terraform/evaluate_valid_test.go, terraform/graph_builder_apply_test.go, terraform/graph_builder_plan_test.go, terraform/schemas.go, terraform/schemas_test.go, terraform/transform_attach_schema.go, terraform/transform_transitive_reduction_test.go
This is a stepping-stone PR for the provider source project. In this PR
"legcay-stype" FQNs are created from the provider name string. Future
work involves encoding the FQN directly in the AbsProviderConfig and
removing the calls to addrs.NewLegacyProvider().
=> terraform: use addrs.Provider as map keys for provider schemas

CODEOWNERS
This updates the CODEOWNERS file with real GitHub handles so that PRs would actually get targeted towards these groups for the backends.
I did not update `*` to be `@hashicorp/terraform-core` because that would auto-request review on all PRs to the core team, and so glob should wait until more ownership is established codebase-wide.
=> Update codeowners file with real handles

command/login.go, command/login_test.go, commands.go
_The token generated in the above screen capture has been invalidated_ 🤫
This is the first in a series of PRs implementing and improving the `terraform login` feature.
- Enable the stubbed-out `terraform login` sub-command
- Add fallback detection of the `tfe.v2` API (to ensure that we're trying to authenticate against compatible Terraform Cloud/Terraform Enterprise)
- If `login.v1` is supported, use whichever OAuth grant flow is available (note: none of these are supported by TFC/TFE yet)
- Otherwise, if `tfe.v2` is supported, open a browser to the user's token settings page, and wait for a token to be pasted back
=> Enable login subcommand, add manual token support

command/format/state.go, command/state_show.go, command/state_show_test.go
The `state show`  command was not checking if a given resource had a
configured provider, and instead was only using the default provider
config. This PR checks for a configured provider, using the default
provider if one is not set.
Fixes #22010
Test results _before_ this fix (I'm including this because more than once I've added a test only to notice that is was passing _before_ I fixed the problem and needed re-writing to 'successfully fail'):
```
--- FAIL: TestStateShow_configured_provider (0.00s)
state_show_test.go:242: Expected:
"# test_instance.foo:\n# missing schema for provider \"test\"\n"
To equal:
"# test_instance.foo:\nresource \"test_instance\" \"foo\" {\n    bar = \"value\"\n    foo = \"value\"\n    id  = \"bar\"\n}\n"
FAIL
FAIL	github.com/hashicorp/terraform/command	3.400s …
```
=> command/state show: use configured provider

command/login.go, command/login_test.go, command/testdata/login-tfe-server/tfeserver.go
When a token is pasted by the user, we make a request to the TFE API `/account/details` endpoint to verify its validity. If successful, we display the logged-in username as confirmation. If not, we refuse to store the invalid token and display an error message.
This commit also trims whitespace from around the pasted value, to reduce the likelihood of a copy & paste error.
If you hit <kbd>Enter</kbd> without pasting a token:
If you paste or type an invalid token:
If everything goes great and you're logged in as me:
=> Add token validation for manual terraform login

backend/remote/backend.go, backend/remote/backend_test.go
Prompt the user to run terraform login to generate and store a token for the configured remote backend.
When using Terraform Cloud:
```
$ terraform init
Initializing the backend...
Error: Required token could not be found
Run the following command to generate a token for app.terraform.io:
terraform login
```
When using another host (e.g. Terraform Enterprise):
```
$ terraform init
Initializing the backend...
Error: Required token could not be found
Run the following command to generate a token for tfe.acme.com:
terraform login tfe.acme.com
```
=> Improve remote backend missing token error

command/login.go, command/logout.go, command/logout_test.go, commands.go, website/docs/commands/logout.html.markdown, website/layouts/docs.erb
Use `terraform logout` to remove stored credentials for a remote service host. This is the corresponding command to `terraform login`.
Normal successful usage:
For a specific hostname (e.g. a TFE instance):
Using a credentials helper:
When attempting to remove credentials which were manually configured (e.g. in `~/.terraformrc`):
If the credentials helper fails:
When already logged out:
=> command/logout: Add terraform logout command

configs/module.go, configs/module_test.go, configs/provider_requirements.go, configs/provider_requirements_test.go
We will need to lookup any user-supplied local names for a given FQN.
This PR adds a map of `addrs.Provider` ->  `LocalName` to the `Module`, along with
adding tests for this and decodeRequiredProvidersBlock.
This also introduces the _appearance_ of support for a required_provider
"source" attribute, but ignores any user-supplied source and instead
continues to assume that addrs.NewLegacyProvider is the way to go. 
I'm labeling this a breaking change as support (even "fake" support) for the source attribute should not be included in a 0.12 release
=> configs: added map to configs.Module for provider local name lookup

terraform/context.go, terraform/util.go
Linked to #23470 
Actually, terraform crash when putting a negative parallelism value. With this we throw a proper error when it happen.
I also updated the `NewSemaphore` to throw an error with negative value
=> Fix negative parallelism and negative semaphore

command/workspace_delete.go
See: https://github.com/hashicorp/terraform/issues/24019
The locker is not released after workspace removal warning.
=> fixed locker not released after workspace removal warning

lang/funcs/collection.go, lang/funcs/collection_test.go, website/docs/configuration/functions/merge.html.md
This PR implements 2 changes to the merge function.
- Rather than always defining the merge return type as dynamic, return
a precise type when all argument types match, or all possible object
attributes are known.
- Always return a value containing all keys when the keys are known.
This allows the use of merge output in for_each, even when keys are yet
to be determined.
Fixes #24024
This also handles the bulk of the concerns from #23052 and comments in #22735. While those had other confounding factors that led us astray, the common thread is that users expect `merge` to return what known keys it has, which is what a for expression would be able to do.
=> make the merge function more precise

command/import_test.go, command/testdata/import-provider-datasource/main.tf, terraform/graph_builder_import.go
There was an order-of-operations bug where the import graph builder was
validating that the provider did not have any resource references before
references were actually being attached. This PR fixes the order of
operations and adds a test (in the command package).
Fixes #22804
=> command/import: attach references before validating provider

version/version.go
Update the building version to 0.13 to reflect `master` being the next major version.
=> Update to 0.13 version for master

configs/provider_requirements_test.go
=> configs/decodeRequiredProviders: sort before comparing slices

addrs/provider_config.go, addrs/provider_config_test.go, command/show_test.go, terraform/context_import_test.go, terraform/eval_provider_test.go, terraform/eval_state_test.go, terraform/transform_provider.go, terraform/transform_provider_test.go
* fix outdated syntax in comments
* test for non-strings in ParseAbsProviderConfig
* ProviderConfigDefault and ProviderConfigAliased now take Providers instead of strings
=> addrs: ProviderConfig fixups

command/console.go, command/graph.go, command/import.go, command/import_test.go, command/testdata/import-provider-invalid/main.tf, command/testdata/import-provider-mismatch/main.tf
If an error occurs on creating the context for console or import, we would fail to unlock the state. Fix this by unlocking slightly earlier. Affects console and import commands.
Fixes #23318.
Also, while I was making these changes:
- Remove the no-op unlock from the graph command, which followed the same code pattern. graph never actually acquires a lock, so rather than applying the same fix, I thought it best to remove the code.
- Remove a now-unused test fixture which was almost reusable for this change, but not quite.
=> command: Fix stale lock when exiting early

command/webbrowser/native.go
With the current implementation of `terraform login`, Windows Subsystem for Linux fails to open a browser due to lack of support for xdg-open. This commit reuses a fix from https://github.com/pkg/browser/pull/8 which detects a WSL environment and uses `cmd.exe` to open the URL instead.
I'm a little uncertain that this fix is the right thing to do, for the same reasons the above PR hasn't been merged, but I thought it was worth a discussion. Tested manually on WSL (and Mac OS X).
=> command/login: Fix browser launcher for WSL users

addrs/module_instance.go, instances/expander.go, instances/expander_test.go, instances/expansion_mode.go, instances/instance_key_data.go, terraform/context.go, terraform/eval_context.go, terraform/eval_context_builtin.go, terraform/eval_context_mock.go, terraform/eval_state.go, terraform/evaluate.go, terraform/graph_builder_apply.go, terraform/graph_builder_apply_test.go, terraform/graph_builder_plan.go, terraform/graph_builder_refresh.go, terraform/graph_walk_context.go, terraform/node_data_refresh.go, terraform/node_data_refresh_test.go, terraform/node_module_expand.go, terraform/node_resource_plan.go, terraform/node_resource_refresh.go, terraform/node_resource_refresh_test.go, terraform/transform_module_expansion.go, terraform/transform_orphan_count.go, terraform/transform_orphan_count_test.go, terraform/transform_resource_count.go
Our existing handling of `count` and `for_each` for resources is rather scattered across different parts of Terraform.
This PR represents some initial experimentation towards centralizing the expansion logic for resources and for modules (looking forward to future module `count` and `for_each`) to help the different parts of Terraform Core that deal with the repetition constructs to coordinate with each other in a more organized way.
The `Expander` type includes three different families of methods:
* `Set*` methods (`SetResourceSingle`, `SetResourceCount`, `SetResourceForEach`, `SetModuleCount`) are used to record the results of evaluating the `count` and `for_each` expressions in the configuration for later use by the `Expand*` family.
* `Expand*` methods (`ExpandResource` and …
=> instances.Expander: A utility for encapsulating "count" and "for_each" concerns

terraform/eval_for_each.go, terraform/eval_for_each_test.go
Previously, passing `[null, null]` to `for_each` caused a panic. This commit detects this invalid usage and returns an error instead.
Fixes #24047.
~I couldn't find anywhere useful to add test coverage for this. Do we have tests covering error cases for eval?~ Added test coverage for `eval_for_each` in 1b1a620.
=> terraform: detect null values in for_each sets

addrs/provider.go, addrs/provider_test.go, configs/config_test.go, configs/module_test.go, configs/testdata/providers-explicit-fqn/root.tf, internal/earlyconfig/config.go, terraform/module_dependencies.go
The provider FQN is becoming our primary identifier for a provider, so it's important that we are clear about the equality rules for these addresses and what characters are valid within them.
The hostname portion is already constrained and normalized by the "service host" mechanism, but we also need to take care of the namespace and type portions:
```
hostname/namespace/type
registry.terraform.io/hashicorp/random
```
We previously had a basic regex permitting ASCII letters and digits for validation and no normalization at all. We need to do at least case folding and UTF-8 encoding normalization because these names will appear in file and directory names in case-insensitive filesystems and in repository names such as on GitHub.
Since we're already using DNS-style normalization and …
=> addrs: Stronger validation and normalization of provider namespace/type

backend/local/backend_plan.go
Fixes #22541
This change will print warnings, such as deprecations,
even if plan has no changes.
=> Show warnings even if no changes

addrs/instance_key.go, terraform/context_apply_test.go, terraform/eval_apply.go, terraform/evaluate.go, terraform/testdata/apply-provisioner-destroy/main.tf
Destroy provisioners have access to the `each.key` value, but they cannot access it by evaluating the `for_each` expressions and must extract it from the instance address.
Fixes #24139
=> Destroy provisioner each.key

website/docs/backends/types/artifactory.html.md, website/docs/backends/types/azurerm.html.md, website/docs/backends/types/consul.html.md, website/docs/backends/types/cos.html.md, website/docs/backends/types/etcd.html.md, website/docs/backends/types/etcdv3.html.md, website/docs/backends/types/gcs.html.md, website/docs/backends/types/http.html.md, website/docs/backends/types/local.html.md, website/docs/backends/types/manta.html.md, website/docs/backends/types/oss.html.md, website/docs/backends/types/pg.html.md, website/docs/backends/types/remote.html.md, website/docs/backends/types/s3.html.md, website/docs/backends/types/swift.html.md, website/docs/backends/types/terraform-enterprise.html.md
"Example referencing" was ambiguous and confusing, especially since these
sections don't show how to reference an output in an expression.
=> website: Label backend data source examples as "data source configuration"

lang/funcs/filesystem.go, lang/funcs/filesystem_test.go, website/docs/configuration/functions/templatefile.html.md
Previously the `templatefile` function would permit any arbitrary string as a variable name, but due to the HCL template syntax it would be impossible to refer to one that isn't a valid HCL identifier without causing an HCL syntax error.
The HCL syntax errors are correct, but don't really point to the root cause of the problem. Instead, we'll pre-verify that the variable names are valid before we even try to render the template, and given a specialized error message that refers to the vars argument expression as the problematic part, which will hopefully make the resolution path clearer for a user encountering this situation.
```
invalid template variable name "<invalid>": must start with
a letter, followed by zero or more letters, digits, and
underscores.
```
The syntax error still …
=> lang/funcs: templatefile requires valid variable names

addrs/provider.go, internal/getproviders/filesystem_mirror_source.go, internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_source_test.go, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/-/legacy/1.0.0/linux_amd64/terraform-provider-legacy, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/2.0.0/darwin_amd64/terraform-provider-null, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/2.0.0/linux_amd64/terraform-provider-null, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/2.0.0/windows_amd64/terraform-provider-null.exe, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/invalid, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/terraform-provider-null_2.1.0_linux_amd64.zip, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/terraform-provider-null_invalid.zip, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/null/terraform-provider-null_invalid_invalid_invalid.zip, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/random/1.2.0/linux_amd64/terraform-provider-random, internal/getproviders/testdata/filesystem-mirror/tfe.example.com/AwesomeCorp/happycloud/0.1.0-alpha.2/darwin_amd64/extra-data.txt, internal/getproviders/testdata/filesystem-mirror/tfe.example.com/AwesomeCorp/happycloud/0.1.0-alpha.2/darwin_amd64/terraform-provider-happycloud, internal/getproviders/types.go
The end-goal of this `FilesystemMirrorSource` is to be configurable as an explicit alternate installation source for when Terraform is running in a location that can't reach upstream registries, but we have an interim milestone of shipping a version of Terraform that includes the new on-disk filesystem layouts (a breaking change) without the fully-generalized installer (a non-breaking change).
With that interim goal in mind, this implements enough of `FilesystemMirrorSource` that it can take on a temporary role as a replacement for the goals of package `plugin/discovery` as we lightly modify the existing plugin installer to use the new on-disk layout for the `.terraform` directory's cache of auto-installed providers.
This particular PR introduces the necessary filesystem scanning …
=> Ability to discover fully-qualified providers on local disk

command/init.go
Our initial Terraform 0.13.0 release is expected to continue to support only the hard-coded official HashiCorp signing key, with support for other keys to follow in a later release once the trust infrastructure is in place to support that.
This change is intended to (marginally) improve the UX for a possible future situation where a HashiCorp-distributed provider makes a released signed with a new key and a prior version of Terraform ends up trying to install it due to incorrect version constraints. With this new text we
hope to give the user a better prompt for onward troubleshooting, but in a sort of hedging way because we have not yet finalized the details of how new keys might roll out in practice.
```
Error: Untrusted signing key for provider "null"
This provider package is not …
```
=> command/init: new error message for signature verification failure

command/state_mv.go, command/state_mv_test.go
When doing a state mv of an instance, the resulting each mode should
always be taken from the target address. 
Fixes #23847
=> state mv should always use target address to determine each mode.

lang/funcs/collection.go, lang/funcs/collection_test.go
The map function assumed that the key arguments were strings, and would panic if they were not.
After this commit, calling `map(1, 2)` will result in a map `{"1" = 2}`, and calling `map(null, 1)` will result in a syntax error.
```
$ terraform console
> map(1, 2)
{
"1" = 2
}
> map(null, 1)
>
Error: Error in function call
on <console-input> line 1:
(source code not available)
Call to function "map" failed: argument 1 is a null key.
```
Fixes #23346, fixes #23043
=> lang: Fix non-string key panics in map function

command/jsonstate/state.go, command/jsonstate/state_test.go, command/show_test.go, command/testdata/show-json-state/basic/output.json, command/testdata/show-json-state/basic/terraform.tfstate, command/testdata/show-json-state/modules/bar/main.tf, command/testdata/show-json-state/modules/foo/main.tf, command/testdata/show-json-state/modules/main.tf, command/testdata/show-json-state/modules/output.json, command/testdata/show-json-state/modules/terraform.tfstate, command/testdata/show-json/multi-resource-update/main.tf, command/testdata/show-json/multi-resource-update/output.json, command/testdata/show-json/multi-resource-update/terraform.tfstate
Resource addresses in state output were not including index for
instances created with for_each or count, while the index was appearing
in the plan output. This PR fixes that inconsistency, adds tests, and
updates the existing tests.
Fixes #24110
=> command/jsonstate: fix inconsistency with resource address

internal/initwd/module_install.go, registry/client.go, registry/client_test.go, registry/test/mock_registry.go, website/docs/commands/environment-variables.html.md
Adds retry request wrapping to the remote registry client during discovery for modules and providers. The default retry is 1 additional attempt for 500-range responses (except 501), and is configurable with the environment variable `TF_REGISTRY_DISCOVERY_RETRY`.
This PR adds logging for the retried attempts and also improves the error message when the requests fail for module downloads.
**Current error**
> **Error: Invalid response from remote module registry**
>
> The remote registry at app.terraform.io failed to return a download URL for app.terraform.io/namespace/module/provider 0.1.0.
**New error** is now uniform between download and list versions requests
> **Error accessing remote module registry**
>
> Failed to retrieve a download URL for app.terraform.io/namespace/module/provider …
=> registry: retryable discovery requests

registry/client.go, registry/client_test.go, website/docs/commands/environment-variables.html.md
This PR introduces no breaking changes. It adds the option to configure the remote registry client timeout duration with the environment variable `TF_REGISTRY_CLIENT_TIMEOUT`. This may be useful during extraneous circumstances to mediate server issues with the remote registry.
=> registry: configurable client timeout

terraform/node_resource_abstract.go, terraform/transform_attach_schema.go, terraform/transform_import_state.go, terraform/transform_provider.go
This refactor allows terraform to indicate whether a specific provider
configuration was found for the resource or if it is instead returning
the assumed default.
With that additional information the provider transformer can check if
there is a specific (non-default) provider FQN.
----
Another option I considered is having `ProvidedBy()` to return `nil` instead of an `AbsProviderConfig` when a specific ProviderConfig was not found (instead of return an assumed default provider) and making the provider transformer responsible for determining the provider in that case. I think the biggest argument in favor of this change is readability; I find the current behavior non-intuitive. It would require adding a DefaultProvider() function to the `GraphNodeProviderConsumer`.
=> terraform: refactor ProvidedBy() to return an addrs.ProviderConfig interface

states/statemgr/filesystem_test.go
Something non-deterministic in the test suite is causing a coverage blip in a line in the filesystem state manager. This commit adds a test which specifically covers that line, which hopefully pleases the Codecov robot.
=> states: Fix coverage blips in statemgr/filesystem

states/instance_object.go, states/instance_object_src.go, states/state_deepcopy.go, terraform/graph_builder_apply_test.go, terraform/node_resource_destroy.go, terraform/transform_diff.go
Normally `CreateBeforeDestroy` is only used from the configuration, because it's primarily thought of in the operation ordering for instance replacement. It however also effects dependent resource operations by updating the dependent before destroying the CBD instance. We need to store `CreateBeforeDestroy` in the state, because that is the only way to record the proper ordering for dependent resource updates when a resource is removed from the config. 
Fixes: #23635, along with numerous issues that have misdiagnosed in providers, where updates are applied in the wrong order when removing dependent resources.
=> Add CreateBeforeDestroy to instance state

command/jsonstate/state.go, command/jsonstate/state_test.go, command/testdata/show-json-state/modules/output.json
inconsistent ordering of child modules in the json output from `terraform show` was causing flapping tests. HARRUMPH
=> jsonstate: sort child modules by address for consistency

website/docs/providers/index.html.markdown, website/docs/providers/type/major-index.html.markdown
Adding vmc provider link to documentation
Tests should fail because changes must be made to terraform-website after this PR is merged
=> [Website] vmc provider links

command/init_test.go
Fix `init` tests which were leaving behind a `.terraform` directory.
=> command: tests should not leave dirs behind thank you

terraform/context_apply_test.go, terraform/testdata/apply-module-replace-cycle/mod1/main.tf
A typo in the config caused it to disagree with the plan on whether a
resource should be CreateBeforeDestroy, preventing it from being ordered
properly. Add the new CreateBeforeDestroy field to the test fixture
state as well for completeness.
=> fix a flapping test involving CreateBeforeDestroy

backend/remote-state/oss/backend.go, backend/remote-state/oss/backend_state.go, backend/remote-state/oss/backend_test.go, backend/remote-state/oss/client.go, backend/remote-state/oss/client_test.go, website/docs/backends/types/oss.html.md
While using the OSS backend with Terragrunt, which can execute many Terraform modules in parallel, I found multiple bugs in the way the backend handles state locking via Tablestore.
Currently, the locking works as follows:
- User creates a Tablestore table with some arbitrary primary key
- The backend discovers this primary key and *always* writes the fixed string "terraform-remote-state-lock" to it
- The backend then tries to update/delete rows based on this primary key alone, ignoring any other attributes
| Something (PK) | Digest | Info |
|-------------|--------|-----|
| terraform-remote-state-lock | (empty) | {ID: ...} |
| terraform-remote-state-lock-md5 | \<hash\> | (empty) |
This won't work when having more than one lock in the table at a time. What the backend actually does is …
=> Fix & improve state locking of OSS backend

configs/module.go, tfdiags/hcl.go, tfdiags/hcl_test.go
This is a funny sort of thing to do that shouldn't come up often, but it can arise in the `configs` package in particular because of the convention there for its methods to return `hcl.Diagnostics`.
At a later time we might want to revisit that decision and have it return `tfdiags.Diagnostics` for consistency with everything else, but that's a more invasive change than I'd like to make right now so this is a compromise to help us deal with the situations where the `configs` package interacts with other packages, like the `addrs` package, that tend to produce `tfdiags.Diagnostics`.
The situation that motivated this is included in this PR as a second commit, in `configs/module.go`.
=> tfdiags: Support converting tfdiags.Diagnostics mechanically to hcl.Diagnostics

addrs/parse_target_test.go, addrs/resource.go, addrs/target_test.go, terraform/context_import_test.go, terraform/eval_context_builtin.go, terraform/eval_state.go, terraform/graph_builder_apply_test.go, terraform/node_data_refresh.go, terraform/node_data_refresh_test.go, terraform/node_module_expand.go, terraform/node_module_removed.go, terraform/node_provider_abstract.go, terraform/node_provider_disabled.go, terraform/node_resource_abstract.go, terraform/node_resource_apply.go, terraform/node_resource_plan.go, terraform/node_resource_refresh.go, terraform/node_resource_refresh_test.go, terraform/transform_attach_config_provider.go, terraform/transform_config.go
Core needs a way to address resources through unexpanded modules, as
they are present in the configuration. There are already some cases of
paring `addrs.Module` with `addrs.Resource` for this purpose, but it is
going to be helpful to have a single type to describe that pair, as
well as have the ability to use TargetContains.
=> implement addrs.ConfigResource

addrs/module.go, addrs/module_instance.go, addrs/resource.go, addrs/target_test.go, terraform/transform_targets_test.go
Implement `Targetable` for `Module`, because we will want to be able to target whole modules (as they may expand into multiple module instances), and this has not been possible before.
=> Make modules targetable

configs/config_test.go, configs/module.go, configs/module_merge.go, configs/module_merge_test.go, configs/module_test.go, configs/resource.go, configs/testdata/valid-modules/nested-providers-fqns/child/main.tf, configs/testdata/valid-modules/nested-providers-fqns/main.tf, configs/testdata/valid-modules/override-resource-provider/a_override.tf, configs/testdata/valid-modules/override-resource-provider/base.tf
This turned out to be much simpler than I feared: we can be certain of the provider FQN when loading the configuration, because it is either:
- a default hashicorp provider (with or without explicit provider source)
- mapped directly to a provider in required_providers (either by explicit provider config ref, or simple mapping of implied name to a name in required_providers)
This PR simplifies much of the work down the line and my next PR will be removing repetitive (and now redundant!) logic from the `terraform` package.
=> configs: attach provider fqn to Resource

go.sum
It seems that the checksum for v3.3.10+incompatible has changed at some point, causing `go mod vendor` to fail now.
We can see by the fact that no files within `vendor` have changed that the change in checksum is not the result of any material change in the module code, and therefore presumably resulted from some change in metadata or a change in the Go module hashing algorithm since Go 1.12.
This seems related to etcd-io/etcd#10665, but since that issue remains open at the time of writing and since (as mentioned above) there are no actual source file content changes implied by this change, we'll just adopt the new hash here to restore our ability to run `go mod vendor`.
=> vendor: Fix checksum for github.com/coreos/etcd

addrs/resource.go, configs/configupgrade/analysis.go, configs/module.go, configs/module_test.go, configs/resource.go, configs/testdata/valid-modules/nested-providers-fqns/main.tf, states/statefile/version3_upgrade.go, states/statemgr/testing.go, terraform/eval_state_upgrade.go, terraform/node_resource_abstract.go, terraform/transform_attach_schema.go, terraform/transform_import_state.go, terraform/transform_provider.go
configs.Resource.ImpliedProvider() now returns a string; it is the
callers' responsibility to turn that into an addrs.Provider if needed.
GraphNodeProviderConsumer ProvidedBy() no longer returns nil (reverting
to earlier, pre-provider-fqn behavior): it will return either the
provider set in config, provider set in state, or the default provider.
=> terraform: large refactor to use Provider from configs.Resource

command/013_config_upgrade.go, command/013_config_upgrade_test.go, command/testdata/013upgrade-explicit-providers/expected/providers.tf, command/testdata/013upgrade-explicit-providers/main.tf, command/testdata/013upgrade-file-exists/expected/providers.tf, command/testdata/013upgrade-file-exists/providers.tf, command/testdata/013upgrade-implicit-providers/expected/providers.tf, command/testdata/013upgrade-implicit-providers/main.tf, command/testdata/013upgrade-invalid/main.tf, command/testdata/013upgrade-no-providers/main.tf, command/testdata/013upgrade-subdir/expected/providers.tf, command/testdata/013upgrade-subdir/subdir/main.tf, commands.go
This PR is not intended to implement the fully functional 0.13upgrade command, only provide suitable scaffolding for the real version.
=> command: Add scaffold for 0.13upgrade command

command/cliconfig/credentials.go
Restructure the credentials storing code for compatibility with Windows system calls. Fixes #24388. Changes:
- We need to close the temporary file before moving it
- `file.Chmod` is not supported, so use `os.Chmod`
- `os.Chmod` also requires the file is closed, so move it to the end of the procedure
Note that the chmod doesn't actually do anything useful on Windows. To actually make this file user-only, we'd need to use something like [go-acl](https://github.com/hectane/go-acl). I'm open to doing that in this PR, but I thought the smallest change to fix the bug was worth looking at first.
Before:
After:
=> command: Fix bug when using terraform login on Windows

website/docs/configuration-0-11/outputs.html.md, website/docs/configuration-0-11/variables.html.md
Since these links were in the soon-to-be-deprecated 0.11 language section, I
think we can just remove them without needing to find an equivalent link.
=> website: Remove links to the getting started guide's old location

registry/client.go, registry/client_test.go, registry/test/mock_registry.go
Non-HTTP errors previously resulted in a panic due to dereferencing the `resp` pointer while it was `nil`, as part of rendering the error message. This commit changes the error message formatting to cope with a `nil` response, and extends test coverage.
Fixes #24384
=> registry: Fix panic when server is unreachable

command/init.go, command/init_test.go, command/plugins.go, command/testdata/init-get-providers/main.tf, moduledeps/module.go, moduledeps/module_test.go, terraform/context.go
I've renamed a couple of functions that had `plugin` in the name but were hard-coded to only work with providers for clarity.
If it isn't obvious from the branch name, this started as a project to convert maps that use provider type name strings to fqns or fqn strings, but I kept getting caught up on functions that were, or appeared to be, generic to all plugins (provisioners + providers). 
I am probably blocked on map key changes until the remaining provider installer work lands (which is a-ok) but I figured I'd take this opportunity to make these function names unambiguous.
=> rename provider-specific functions

.github/CONTRIBUTING.md
Nothing fancy (and suggestions welcome!) but I wanted to make sure we have something to point to when questions come up.
=> docs/contributing: add note about codecov

instances/expander.go, instances/expander_test.go, terraform/node_data_refresh.go, terraform/node_resource_plan.go, terraform/node_resource_refresh.go
It turns out that within terraform resource expansion will normally
happen with an absolute address. This is because in order to evaluate
the expansion expression, we need to already have the context within a
module instance.
This leaves the existing ExpandResource logic in place as
ExpandModuleResource since it's working, and in case we do find a
location where it's useful to get a full expansion (which may be needed
for instance dependency tracking)
Reword some of the resource related arguments and comments, as they were
copied from the module methods and not entirely accurate.
=> Expander.ExpandResource should use AbsResource

instances/expander.go
ExpandResource must only check the specific ModuleInstances in the
requested path, because the resource may not have been registered yet in
all module instances.
=> Expander.ExpandResource cannot expand all modules

internal/getproviders/filesystem_search.go, internal/providercache/dir.go, internal/providercache/dir_modify.go, internal/providercache/dir_modify_test.go, internal/providercache/testdata/cachedir/registry.terraform.io/hashicorp/null/2.0.0/windows_amd64/terraform-provider-null.exe
The main thing here is fixing a bug I didn't spot before merging #24447, where the cache linking behavior was incorrectly deleting the _source_ of the link, rather than the target path.
However, in the process of fixing that I also noticed that the `LinkFromOtherCache` test hadn't been running at all due to it being named incorrectly, and so that's why this didn't show up as a problem in the previous PR.
Along the way I added a little more `TRACE`-level logging to the overall process because it was helpful in understanding what the problem was here and also because we know from experience with the old installer that trace logging tends to be very helpful when responding to user questions about why certain plugins were not detected as they expected.
As with #24447, this is all still just …
=> Some fixes for internal/providercache and internal/getproviders

addrs/module_call.go, addrs/output_value.go, addrs/parse_ref.go, addrs/parse_ref_test.go, lang/data.go, lang/data_test.go, lang/eval.go, terraform/evaluate.go, terraform/evaluate_valid.go, terraform/node_output.go
Previously, `ModuleCallOutput` referenced a particular module _instance_ however, we now consider whole modules as a result of the expansion strategy, so `ModuleCallOutput` is updated to reference whole modules, while `AbsModuleCallOutput` is the type referring to an output in a particular module instance.
=> Update ModuleCallOutput and add AbsModuleCallOutput

command/format/diagnostic.go, command/format/diagnostic_test.go
Previously, if a diagnostic context spanned multiple lines, any lines which did not overlap with the highlight range would be displayed as blank. This commit fixes the bug.
The problem was caused by the unconditional use of `PartitionAround` to split the line into before/highlighted/after ranges. When two ranges don't overlap, this method returns empty ranges, which results in a blank line. Instead, we first check if the ranges do overlap, and if not we print the entire line from the context.
Fixes #21636
=> command/format: Fix multi-line diagnostic output

command/fmt.go, command/fmt_test.go
Previously, diagnostic errors would display the filename and line number, along with "(source code not available)". This is because the `fmt` command directly loads and parses the configuration, instead of using the config loader.
This commit registers the manually parsed source as a synthetic configuration file, so that the diagnostic formatter can look up the source for the range with the error and display it.
Fixes #20910
=> command/fmt: Include source snippets in errors

builtin/provisioners/habitat/linux_provisioner.go, builtin/provisioners/habitat/linux_provisioner_test.go
Resolves #24273
Signed-off-by: David McNeil <mcneil.david2@gmail.com>
=> Fix permissions of habitat provision's user.toml

configs/config.go, configs/config_test.go, configs/testdata/provider-reqs/child/provider-reqs-child.tf, configs/testdata/provider-reqs/provider-reqs-root.tf, internal/earlyconfig/config.go, internal/earlyconfig/config_test.go, internal/earlyconfig/testdata/provider-reqs/child/provider-reqs-child.tf, internal/earlyconfig/testdata/provider-reqs/provider-reqs-root.tf, internal/getproviders/types.go, internal/providercache/installer.go, states/state.go
We've been using the models from the `moduledeps` package to represent our provider dependencies everywhere since the idea of provider dependencies was introduced in Terraform 0.10, but that model is not very convenient to use for any use-case other than the `terraform providers` command that needs individual-module-level detail.
To make things easier for new codepaths working with the new-style provider installer, here we introduce a new model type `getproviders.Requirements` which is based on the type the new installer was already taking as its input. We have new methods in the `states`, `configs`, and `earlyconfig` packages to produce values of this type, and a helper to merge `Requirements` together so we can combine config-derived and state-derived requirements together during …
=> internal/getproviders: A new shared model for provider requirements

.circleci/config.yml
This is a sample CircleCI configuration to allow testing of CircleCI configuration on a branch without Circle's webhook complaining there is no configuration on every PR. This branch filter prevents Circle from running on every branch so it shouldn't even show up in the PR checks.
=> add sample circleci config

README.md
I added a few links to the bullets at the top and expanded the "Getting Started" section to include links to the Learn guides and product certifications.
=> Added links to Learn and certification exams to the README

addrs/provider.go, addrs/provider_test.go, backend/local/testing.go, command/apply_test.go, command/command_test.go, command/init.go, command/meta.go, command/meta_providers.go, command/plugins.go, command/state_show_test.go, command/version.go, helper/resource/testing.go, providers/factory.go, terraform/context.go, terraform/context_components.go, terraform/resource_provider.go, terraform/schemas.go
Back when we first introduced provider versioning in Terraform 0.10, we did the provider version resolution in `terraform.NewContext` because we weren't sure yet how exactly our versioning model was going to play out (whether different versions could be selected per provider configuration, for example) and because we were building around the limitations of our existing filesystem-based plugin discovery model.
However, the new installer codepath is new able to do all of the selections up front during installation, so we don't need such a heavy inversion of control abstraction to get this done: the command package can determine the exact provider versions previously selected during installation and pass their factories directly to `terraform.NewContext` as a simple static map.
The result of …
=> Remove terraform.ResourceProvider, use providercache.Installer instead

states/statefile/testdata/roundtrip/v3-bigint.out.tfstate, states/statefile/testdata/roundtrip/v3-grabbag.out.tfstate, states/statefile/testdata/roundtrip/v3-invalid-depends.out.tfstate, states/statefile/testdata/roundtrip/v3-simple.out.tfstate, states/statefile/testdata/roundtrip/v4-simple.in.tfstate, states/statefile/version3_upgrade.go
This commit reverts an earlier change which automatically converted
provider strings to legacy provider FQNs. It is now reverted back to legacy-style strings. 
It has become apparent that a state upgrade step will be required before upgrading to v0.13 and we should do that explicitly, instead of hidden assumptions like this one. 
This PR is targeting the f-init-new-installer branch and will cause many broken tests; I can hold off on merging and fix them here OR merge (pending review) and deal with the tests in the f-init-new-installer branch.  The reason I haven't started fixing tests is that we are debating a fairly substantial change to terraform.NewContext which (greatly) impacts all the same tests and I'd rather do it all at once if possible/reasonable.
=> states/version3 upgrade: revert provider FQN changes

configs/config.go, configs/config_test.go, configs/module.go, configs/module_merge.go, configs/module_merge_test.go, configs/module_test.go, terraform/context_apply_test.go, terraform/context_fixtures_test.go, terraform/context_import_test.go, terraform/context_input_test.go, terraform/context_plan_test.go, terraform/context_refresh_test.go, terraform/context_validate_test.go, terraform/eval_apply.go, terraform/eval_context_builtin.go, terraform/eval_context_mock.go, terraform/eval_diff.go, terraform/eval_read_data.go, terraform/eval_refresh.go, terraform/evaluate_valid.go, terraform/node_resource_abstract.go, terraform/terraform_test.go
`terraform` context tests passing: apply, plan, input, import
=> Mildwonkey/terraform tests (targeting integration branch)

.circleci/config.yml
This PR migrates Terraform from Travis over to CircleCI. I tried to copy most of the configuration and added in bits that I thought would be useful from some of the other projects I have worked on. 
A summary of the more notable changes:
1. I am bumping consul to 1.7.2 (latest) to run tests against.
2. There is a check to make sure `make generate` does not generate a dirty git directory. This should be a command that is run locally and committed back to the repo.
3. Go tests are [parallelized](https://app.circleci.com/pipelines/github/hashicorp/terraform/20/workflows/0a188038-4f96-4125-948d-15ac865072c4) across 4 executors based on package runtimes calculated by `go list ./... | circleci tests split --split-by=timings --timings-type=classname`. They run with the `-cover` flag and these …
=> CI: migrate travis to circle

backend/local/backend_apply_test.go, backend/local/backend_plan_test.go, backend/local/backend_refresh_test.go, backend/local/testing.go
I copied a couple of helper functions from `terraform`: there was little enough to copy and we don't expect to be writing tons of new backends so that seemed good enough for this purpose.
=> backend/local: refactor tests with modern state and default providers

addrs/provider.go, command/state_meta.go, command/state_replace_provider.go, command/state_replace_provider_test.go, commands.go
Terraform 0.13 will allow the installation of providers from various sources. If a user updates their configuration to change the source of an in-use provider (for example, if the provider namespace changes), they will also need to update the state file accordingly.
This commit introduces a new `state replace-provider` subcommand which supports this. All resources using the `from` provider will be updated to use the `to` provider.
=> command: Add state replace-provider subcommand

addrs/provider.go, command/init.go, command/init_test.go, command/meta_providers.go, command/testdata/init-internal-invalid/main.tf, configs/config.go, configs/config_test.go, configs/module.go, configs/module_merge.go, configs/module_test.go, configs/testdata/provider-reqs/provider-reqs-root.tf, configs/testdata/providers-explicit-fqn/root.tf, internal/earlyconfig/config.go, internal/providercache/installer.go, internal/providercache/installer_events.go, terraform/node_resource_abstract.go
An earlier changeset established the addressing scheme for "built-in" providers in the `addrs` package, which was intended to represent the special providers that are built in to Terraform itself, rather than separately installable, which we defined to live in the namespace `terraform.io/builtin/`. The `terraform` provider is currently the only built-in provider, and it was made available in the set of provider factories passed to `terraform.NewContext` already in an earlier change.
This PR introduces that concept into the provider installer too, both so that it knows not to try to install them the "normal" way and so it can verify that the requested built-in providers are valid and thus we retain the characteristic that `Installer.EnsureProviderVersions` will return without error only …
=> Finish up support for built-in providers

command/jsonconfig/config.go, command/jsonplan/plan.go, command/jsonstate/state.go
There was a remaining TODO in this package to find the true provider FQN when looking up the schema for a resource type. We now have that data available in the Provider field of configs.Resource, so we can now complete that change.
The tests for this functionality actually live in the parent "command" package as part of the tests for the "terraform show" command, so this fix is verified by all of the `TestShow...` tests now passing except one, and that remaining one is failing for some other reason which we'll address in a later commit.
```
$ go test ./command -run ^TestShow
/tmp/tf958142578/tf669733492 <nil>
--- FAIL: TestShow_json_output_state (0.07s)
--- FAIL: TestShow_json_output_state/basic (0.01s)
show_test.go:404: wrong result:
  command.state{
  	FormatVersion:    "0.1",
   …
```
=> command/jsonconfig: Use correct provider address to access schema

command/e2etest/init_test.go, go.mod, go.sum, main.go, provider_source.go, vendor/github.com/apparentlymart/go-userdirs/LICENSE, vendor/github.com/apparentlymart/go-userdirs/internal/unix/homedir.go, vendor/github.com/apparentlymart/go-userdirs/macosbase/doc.go, vendor/github.com/apparentlymart/go-userdirs/macosbase/home.go, vendor/github.com/apparentlymart/go-userdirs/macosbase/macosbase.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/app.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/app_darwin.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/app_stub.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/app_unix.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/app_windows.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/dirs.go, vendor/github.com/apparentlymart/go-userdirs/userdirs/doc.go, vendor/github.com/apparentlymart/go-userdirs/windowsbase/doc.go, vendor/github.com/apparentlymart/go-userdirs/windowsbase/impl.go, vendor/github.com/apparentlymart/go-userdirs/windowsbase/stub.go, vendor/github.com/apparentlymart/go-userdirs/windowsbase/windowsbase.go, vendor/github.com/apparentlymart/go-userdirs/xdgbase/doc.go, vendor/github.com/apparentlymart/go-userdirs/xdgbase/home.go, vendor/github.com/apparentlymart/go-userdirs/xdgbase/xdg.go, vendor/modules.txt
This restores some of the local search directories we used to include when searching for provider plugins in Terraform 0.12 and earlier. The directory structures we are expecting in these are different than before, so existing directory contents will not be compatible without restructuring, but we need to retain support for these local directories so that users can continue to sideload third-party provider plugins until the explicit, first-class provider mirrors configuration (in CLI config) is implemented, at which point users will be able to override these to whatever directories they want.
The equivalent functionality was previously implemented via `plugin/discovery`, but we're no longer using that for provider plugins so this is attempting to achieve a similar effect using our new …
=> main: Consult local directories as potential mirrors of providers

addrs/provider.go, addrs/provider_test.go, command/init.go
The provider fully-qualified name string used in configuration is very long, and since most providers are hosted in the public registry, most of that length is redundant. This commit adds and uses a `ForDisplay` method, which simplifies the presentation of provider FQNs.
If the hostname is the default hostname, we now display only the namespace and type. This is only used in UI, but should still be unambiguous, as it matches the FQN string parsing behaviour.
**Note:** I've probably have missed some places where we output provider strings intended for users to read. Suggestions on how to find them (or pointers to places I've missed) would be great 🙏 
Before:
After:
=> addrs: Simplify presentation of provider FQNs

command/init_test.go, internal/getproviders/mock_source.go
The fake installable package meta used a ZIP archive which gave different checksums between macOS and Linux targets. This commit removes the target from the contents of this archive, and updates the golden hash value in the test to match. This test should now pass on both platforms.
=> internal: Fix init provider lockfile test

helper/wrappedstreams/streams.go, helper/wrappedstreams/streams_other.go
os.NewFile was called on file descriptors 3, 4, and 5 during every init,
in case this process happened to be running inside panicwrap. If the
runtime has already chosen one of these file descriptors to use
internally, starting polling on them can cause the runtime to crash.
Initialize the file descriptors lazily, only if we know that they belong
to us, after Wrapped is checked.
Fixes #24287
=> don't call os.NewFile on unknown FDs

terraform/context_validate_test.go, terraform/graph_builder_plan.go, terraform/graph_builder_validate.go, terraform/node_module_expand.go, terraform/transform_module_expansion.go
We cannot evaluate expansion during validation, since the values may not
be known at that time.
Inject a `nodeValidateModule`, using the "Concrete" pattern used for other
node types during graph building. This node will always evaluates to a
single module instance, so that we have a valid context within which to
evaluate all sub resources.
=> Create module validation nodes

command/init.go, configs/parser_config.go, configs/testdata/error-files/required-providers-toplevel.tf
When a provider dependency is implicit rather than explicit, or otherwise when version constraints are lacking, we produce a warning recommending the addition of explicit version constraints in the configuration.
This restores the warning functionality from previous Terraform versions, adapting it slightly to account for the new provider FQN syntax and to recommend using a `required_providers` block rather than version constraints in `provider` blocks, because the latter is no longer recommended in the documentation.
Due to the constraints of how we're presenting this information the warning message might imply to a user new to Terraform that it's recommending putting a `required_providers` block at the toplevel of configuration, and so to help guide towards the right answer I also added …
=> command/init: Restore the unconstrained provider warnings

internal/getproviders/package_authentication.go, internal/getproviders/registry_client.go, internal/getproviders/registry_source_test.go, internal/getproviders/types.go, internal/providercache/dir_modify.go
Earlier on in the stubbing of this package we realized that it wasn't going to be possible to populate the authentication-related bits for all packages because the relevant metadata just isn't available for packages that are already local.
However, we just moved ahead with that awkward design at the time because we needed to get other work done, and so we've been mostly producing `PackageMeta` values with all-zeros hashes and just ignoring them entirely as a temporary workaround.
This is a first step towards what is hopefully a more intuitive model: authentication is an optional thing in a PackageMeta that is currently populated only for packages coming from a registry.
So far this still just models checking a SHA256 hash, which is not a sufficient set of checks for a real release but …
=> internal/getproviders: Tidy up some confusion about package hashes

terraform/eval_context_builtin.go, terraform/eval_variable.go, terraform/evaluate.go, terraform/node_module_variable.go, terraform/testdata/plan-modules-expand/main.tf
When evaluating ModuleCallArguments, we need to use the appropriate ModuleInstance as the scope of the evaluation, as that instance key data is what is used to evaluate `count.index` and `each.key`/`each.value` references appropriately.
Note: As of this PR, `count.index` etc usage will still fail when used in a config to plan, as it does not yet pass the validate step, but that will be fixed in a separate PR.
=> Enable count.index and each.key/value in module expansion

internal/getproviders/multi_source_test.go
Due to other pressures at the time this was implemented, it was tested only indirectly through integration tests in other packages. This now introduces tests for the two main entry points on `MultiSource`, along with its provider-address pattern matching logic.
This does not yet include thorough tests for `ParseMultiSourceMatchingPatterns`, because that function still needs some adjustments to do the same case folding as for normal provider address parsing, which will follow in a latter commit along with suitable tests.
With that said, the tests added here do _indirectly_ test the happy path of `ParseMultiSourceMatchingPatterns`, so we do have some incomplete testing of that function in the meantime.
=> internal/getproviders: Tests for MultiSource

internal/getproviders/memoize_source_test.go
Due to other pressures at the time this was implemented, it was tested only indirectly through integration tests in other packages. This now introduces tests for the two main entry points on `MemoizeSource`.
=> internal/getproviders: Tests for MemoizeSource

configs/module_call.go, configs/module_call_test.go
`count` and `for_each` cannot used be used in the same resource or module. This is validated during config loading for resources; validate this during the loading of modules too.
=> don't allow count && for_each in module calls

website/docs/import/usage.html.md
This pull request has no code change but only contains documentation update resulting from changes proposed to the terraform-provider-aws.
<h3>Reason for Change</h3>
[terraform-provider-aws pull request](https://github.com/terraform-providers/terraform-provider-aws/pull/12616) contains changes that alter behavior of AWS security group such that import of aws_security_group will no longer implicitly import aws_security_group_rule for associated rules.
<p>This change, therefore, removes mention of aws_security_group and replaces with example of aws_network_acl that exhibits such complex import behavior discussed in the doc.</p>
=> Updating import usage doc with accurate example of complex import with secondary resources

command/login.go, states/statemgr/filesystem_test.go, terraform/eval_context_builtin.go, terraform/hook_test.go
Fix a few races that had crept into the codebase. Now that we've moved to a new CI system, we can probably start testing for these automatically, but there will still be some test fixtures that need updating.
- `GetVariableValue` was missing the variable mutex calls.
- The `login` command had a race around a closed-over `err` value.
- The `testHook` mock wasn't synchronized in the tests.
- Missing call to `wg.Wait()` caused a race in the deferred cleanup function.
Fixes #24589
=> Fix races in GetVariableValue and login

terraform/context_validate_test.go, terraform/eval_apply.go, terraform/eval_count.go, terraform/eval_diff.go, terraform/eval_for_each.go, terraform/eval_for_each_test.go, terraform/eval_read_data.go, terraform/eval_state.go, terraform/eval_validate.go, terraform/eval_variable.go, terraform/node_data_refresh.go, terraform/node_module_expand.go, terraform/node_module_variable.go, terraform/node_module_variable_test.go, terraform/node_resource_refresh.go, terraform/node_root_variable.go, terraform/transform_module_variable.go
Validate module variables to the best of our ability during validation.
This challenge here is that modules are not expanded during validation, therefor variables that contain count or each references cannot be evaluated. An attempt at making the `Expander` handle unknown module expansions was started in #24586, but that was turning into too much of a re-write. After some testing, we may return to that with a simpler approach, but this allows terraform to work while missing some validations until plan time.
What is missing here, is that we cannot validate if an incorrect count/each reference was used in a variable, and we can't run variable validation functions with count/each references even if they are static. Each of these will be caught during plan, so there is no safety issue, just a …
=> Allow module variables to pass validation

website/docs/providers/type/community-index.html.markdown
Fix a typo in the provider name. Makes it easier to find the link on the page.
=> Fix a typo in the Graylog provider name

addrs/module_call.go, states/state_string.go, terraform/context_apply_test.go, terraform/transform_reference.go
Like resource references, we need to make instance references less
specific when they aren't expanded yet during plan. 
Add a method to get the `ModuleCallOutput` which will allow the
reference transformer to connect to the unexpanded node during plan.
=> Correctly connect module output references during plan

website/docs/configuration/syntax-json.html.md
is this the right place to fix the docs on the [website](https://www.terraform.io/docs/configuration/syntax-json.html)? Found a broken link and wanted to fix it
=> fix broken hcl json spec link

website/docs/configuration/modules.html.md, website/docs/internals/resource-addressing.html.markdown
This is the first pass of updating documentation to allow for `count` and `for_each` for modules. This also updates the resources addresses section to clarify referring to module paths with consideration for module instances.
=> Docs for count/for_each on modules

website/docs/providers/index.html.markdown, website/docs/providers/type/network-index.html.markdown
Adding two thinks for the Infoblox Terraform provider documentation
=> [Website] provider links

lang/funcs/collection.go, lang/funcs/collection_test.go, lang/functions.go, lang/functions_test.go, website/docs/configuration/functions/sum.html.md, website/layouts/functions.erb
@alisdair   
Continuation of closed PR -> https://github.com/hashicorp/terraform/pull/24356   
This feature adds an additional collection function, `sum`. `sum` takes a list, set, or tuple of numbers and returns the sum of all elements.
[X] Early validation of idea and implementation plan: Terraform's core is complicated enough that there are often several ways to implement something, each of which has different implications and tradeoffs. Working through a plan of attack with the team before you dive into implementation will help ensure that you're working in the right direction.
[X] Unit tests: Terraform's core is covered by hundreds of unit tests at several different layers of abstraction. Generally the best place to start is with a "Context Test". These are higher level test that …
=> Feature: Sum Function

backend/remote/backend_common.go, backend/remote/backend_plan.go
Fixes an issue in the `remote` backend, where a policy hard failure could cause the CLI to exit early without displaying the result of the policy check. This is because the run will end up in the `errored` state on policy hard failures. If the run enters the `errored` state before the cost-estimate and policy-check are rendered, the CLI would simply return early and never display the result.
This change ensures that we always query the cost-estimate and policy check when present, and render the results when available, resolving the race condition. This is largely just moving logic around.
=> backend/remote: display cost estimate and policy check whenever available

addrs/provider_test.go, command/init_test.go, command/testdata/init-required-providers/main.tf, internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/random-beta/1.2.0/linux_amd64/terraform-provider-random-beta, internal/providercache/dir_test.go, internal/providercache/testdata/cachedir/registry.terraform.io/hashicorp/random-beta/1.2.0/linux_amd64/terraform-provider-random-beta
This PR adds a number of tests in various packages to exercise use with hyphenated providers, for example `google-beta`. I started this work while tracking down an issue with terraform-bundle. It turns out that the issue was not unique to the hyphenated provider, that was a red herring, but these tests may prove useful during future refactoring.
=> tests: Added tests to exercise hyphenated providers

command/e2etest/init_test.go, command/e2etest/testdata/local-only-provider/main.tf, command/e2etest/testdata/local-only-provider/terraform.d/plugins/example.com/awesomecorp/happycloud/1.2.0/os_arch/terraform-provider-happycloud_v1.2.0, provider_source.go
This more closely replicates the 0.12-and-earlier behavior, where having at least one version of a provider installed locally would totally disable any attempt to look for newer versions remotely.
This is just for the implicit default behavior. Assumption is that later we'll have an explicit configuration mechanism that will allow the user to specify exactly where to look for what, and thus avoid tricky heuristics like this. The implicit exclusions added here are mimicking what might later appear in the explicit CLI config as something like this (final configuration design still TBD):
```hcl
direct {
exclude = ["example.com/awesomecorp/happycloud"]
}
```
Because this check lives inside `package main`, it's tested here with an e2etest.
=> main: skip direct provider installation for providers available locally

command/plan_test.go, terraform/context.go, terraform/resource_provider.go
A side effect of the various changes to the provider installer included losing the `initialization required` error message which would occur if a user removed or modified the `.terraform` directory.
Previously, plugin factories were created after the configuration was loaded, in `terraform.NewContext`.  Terraform would compare the required providers (from config and state) to the available providers and return the aforementioned error if a provider was missing.
Provider factories are now loaded at the beginning of any terraform command, before terraform even loads the configuration, and therefore before terraform has a list of required providers. 
This PR replaces the current error when a providers' schema cannot be found in the provider factories with the `init` error, and adds a command …
=> terraform: return `initialization required` error when provider schemas not found

addrs/parse_ref.go, addrs/parse_ref_test.go, lang/data.go, lang/data_test.go, lang/eval.go, lang/eval_test.go, plans/changes.go, plans/changes_sync.go, repl/session_test.go, states/module.go, states/output_value.go, states/state.go, states/state_deepcopy.go, states/state_test.go, states/statefile/version4.go, states/sync.go, terraform/context_plan_test.go, terraform/context_validate_test.go, terraform/evaluate.go
In order to be able to use module values, and handle operations like possibly invalid module indexes in conditional statements; whole, expanded modules must always be returned during evaluation. This is the same methodology applied to resources in #22846.
This also requires some new methods on the Changes and State, since the evaluation is happening from within a known `addrs.ModuleInstance` path, but we need to retrieve all instances of the child module being referenced. We need to collect all outputs from all possible module instances, as module outputs are handled individually (as opposed to resources which are stored as objects containing all their attributes), so this allows us to compile a data structure with all the outputs for each module in order to build the `cty.Object` values …
=> Always return all module instances during evaluation

command/init_test.go, internal/getproviders/memoize_source_test.go, internal/getproviders/mock_source.go, internal/getproviders/multi_source_test.go, internal/providercache/installer.go, internal/providercache/installer_test.go
The public registry includes a list of supported provider protocol
versions for each provider version. This change adds verification of
support and adds a specific error message pointing users to the closest
matching version.
=> internal/providercache: verify that the provider protocol version is compatible

internal/getproviders/multi_source.go, internal/getproviders/multi_source_test.go
This is a minor refactor which takes advantage of `addrs.ParseProviderPart` case normalization to normalize (non-wildcard) providers sources, which in turn ensures that the provider wildcards match the same way that we do exact matching on provider addresses.
=> internal/getproviders: apply case normalizations in ParseMultiSourceMatchingPatterns

command/state_replace_provider.go, website/docs/commands/state/replace-provider.html.md, website/layouts/commands-state.erb
[Rendered](https://github.com/hashicorp/terraform/blob/alisdair/terraform-state-replace-provider-docs/website/docs/commands/state/replace-provider.html.md). Documentation for `terraform state replace-provider`, added in #24523.
We should update this page to link to the docs on provider FQN when that's available.
=> website: Add docs for state replace-provider

configs/config.go, configs/module.go, configs/module_merge.go, configs/module_merge_test.go, configs/module_test.go, configs/parser_config.go, configs/provider_requirements.go, configs/provider_requirements_test.go, configs/testdata/invalid-modules/multiple-required-providers/a.tf, configs/testdata/invalid-modules/multiple-required-providers/b.tf, configs/testdata/valid-modules/required-providers-after-resource/main.tf, configs/testdata/valid-modules/required-providers-after-resource/providers.tf, configs/testdata/valid-modules/required-providers-overrides/bar_provider_override.tf, configs/testdata/valid-modules/required-providers-overrides/main.tf, configs/testdata/valid-modules/required-providers-overrides/providers.tf
We now permit at most one `required_providers` block per module (except for overrides). This prevents users (and Terraform) from struggling to understand how to merge multiple `required_providers` configurations, with `version` and `source` attributes split across multiple blocks.
Because only one `required_providers` block is permitted, there is no need to concatenate version constraints and resolve them. This allows us to simplify the structs used to represent provider requirements, aligning more closely with other structs in this package.
This commit also fixes a semantic use-before-initialize bug, where resources defined before a `required_providers` block would be unable to use its source attribute. We achieve this by processing the module's `required_providers` configuration (and …
=> configs: Simplify required_providers blocks

terraform/graph_builder_eval.go
Add the expansion transformer to the eval graph, which is used in rare scenarios which includes running `terraform console`. Prevents panic when running `terraform console` in contexts with module expansion.
Currently, tests for `terraform console` don't have any existing states where `init` is required before running that command, which would be necessary in order to fully test-through this case, which is why there isn't a test included in this changeset -- I could work on it, but it feels a bit separate from this current task.
=> Add expansion transformer to eval graph

website/docs/providers/index.html.markdown
Link to [terraform-provider-cloudinit](https://github.com/hashicorp/terraform-provider-cloudinit) documentation.
=> Cloud-init provider link

CHANGELOG.md
@kayrus and @jtopjian I wanted to get a quick review here from you. I read the docs updates in GH-23510 and it wasn't clear to me whether user will need to make changes to their configuration or if this is purely additive. If they do need to make changes I'd like to list it as a breaking change, otherwise I think it should be categorized as an enhancement.
=> Update CHANGELOG.md for swift authentication

configs/module.go, configs/module_test.go, configs/testdata/valid-modules/implied-providers/providers.tf, configs/testdata/valid-modules/implied-providers/resources.tf
Previously, resources without explicit provider configuration (i.e. a `provider =` attribute) would be assigned a default provider based upon the resource type. For example, a resource `foo_bar` would be assigned provider `hashicorp/foo`.
This behaviour did not work well with community or partner providers, with sources configured in `terraform.required_providers` blocks. With the following configuration:
```tf
terraform {
foo = {
source = "acme/foo"
}
}
}
resource foo_bar "a" { }
```
the resource would be configured with the `hashicorp/foo` provider.
This commit fixes this implied provider behaviour. First we look for a provider with local name matching the resource type in the module's required providers map. If one is found, this provider is assigned to the …
=> configs: Fix for resources with implied providers

terraform/evaluate.go
Since evaluation is driven only by the configuration (i.e. you can't
interpolate what's not in the config), the resource evaluation should
also follow configuration rather than state. Determining the each mode
solely from the config, and applying that to the state and changes
removes the need for EachMode in the resource state. This bypasses the
awkward dance around getting the correct EachMode set in and retrieved
from state during plan when it changes in the config.
Since objects and tuples have fixed numbers of elements, we can't return
an unknown version of those during validation. While we could return a
DynamicVal (which was used previously), that prevents the validation of
references to outputs and attributes in config. Instead, we can return a
synthetic type made from a List or …
=> Resource (and module) evaluate improvements

command/console_test.go, command/testdata/modules/.terraform/modules/modules.json, command/testdata/modules/child/main.tf, command/testdata/modules/main.tf, command/testdata/modules/terraform.tfstate, terraform/node_output.go
This allows outputs to be evaluated in `walkEval`, impacting `terraform console`.
Outputs are still not evaluated for `terraform console` in the root module, so this has no impact on writing to state (as child module outputs are not written to state). 
An open question I have is if this could have external effects I'm not seeing w.r.t. writing outputs to state, but all tests pass currently. I am concerned about this because the EvalNode is `EvalWriteOutput`. If someone has advice on how I might test this to ensure it's _not_ causing externalities, please share!
Also adds test coverage to the `console` command for evaluating module outputs generally, as well as locals.
=> Support reading module outputs in terraform console

command/init.go, internal/providercache/installer.go
There was a bug in the installer which was passing a nil error.
There is more work to be done here, but I wanted to get the simple bug fix in quickly. 
The registry source's `PackageMeta` function makes multiple GET requests to get the package metadata and shasums, which is more information than we need when searching for any provider versions with a protocol version supported by the current version of terraform (version). I am considering adding a `PartialPackageMetadata` function, but that seems like a lot of boilerplate for something unique to the registry installer, especially as there is some internal chatter about a new endpoint which could simplify this request (or reinforce the need for a second method; who knows just yet?).
=> internal/providercache: fix error message for protocol mismatch

.hashibot.hcl
The filter will lock all issues/PRs closed for over 30 days, and not comment on them if they are old (no activity for 60 days). This PR also removed the cherry pick labeler, the SDK will no longer cherry-pick from Core.
=> [hashibot] Skip lock comments on old issues

command/init.go
Fixed a bug where we were returning the wrong `diags` to the user during `init`.
Here's an example when the user has multiple `required_providers` settings:
=> init: return proper errors when config has an error and earlyconfig does not

command/login.go, command/testdata/login-oauth-server/oauthserver.go
Providers like Okta and AWS Cognito expect that the PKCE challenge
uses base64 URL Encoding without any padding (base64.RawURLEncoding)
Additionally, Okta strictly adheres to section 4.2 of RFC 7636 and
requires that the unencoded key for the PKCE data is at least 43
characters in length.
=> Fix PKCE Oauth2 exchange

backend/remote/backend_state.go, state/remote/remote.go, state/remote/remote_test.go, state/remote/state.go, state/remote/state_test.go
This PR adds support for the `-force` flag for `state push` with the remote backend. Per the documentation around manual state push / pull https://www.terraform.io/docs/backends/state.html#manual-state-pull-push both differing serials and lineage protections can be bypassed with the -force flag.
- The first change you'll notice is the addition of a `forcePush` property on the remoteClient struct. This allows the client to know if it is operating in the context of a force push.
- The second change is an optional interface `ClientForcePusher` for clients (like the `remoteClient`) that would need to know they are operating in the context of a force push. There was a force flag added to the Go TFE client that needs to be specified at persistence time.
- The last change is tracking the serial …
=> Add support for force pushing with the remote backend

backend/remote/backend_state.go, state/remote/remote.go, state/remote/remote_test.go, state/remote/state.go, state/remote/state_test.go
This is a copy of #24696 on the v0.12 tree.
Adds support for the `-force` flag for state push with the remote backend.
=> Backport remote backend force push to v0.12

builtin/providers/terraform/data_source_state.go, builtin/providers/terraform/data_source_state_test.go
This PR ensures that the `Configure` method for a backend object powering a `terraform_remote_state` data source is not called during `terraform validate`. This ensures that only the supplied configuration will be validated but the state itself will not be loaded.
I followed @apparentlymart's ever-helpful advice and slightly refactored `getBackend` to accomplish this. Rather than return a configured backend object, `getBackend` now returns an un-configured object and the validated configuration (plus diags). 
`dataSourceRemoteStateValidate` continues to ignore the backend, and now the config too, and just cares about diags. `dataSourceRemoteStateRead` can combine those two values into a `b.Configure(cfg)` call to actually configure the backend and invoke any remote API calls that may …
=> Avoid configuring backend when validating terraform_remote_state

website/docs/modules/index.html.markdown
This is a cherry-pick of #24445, to make sure it stays deployed after the next 0.12 release wipes stable-website.
=> Docs cherry-pick: Add reference to new modules track (#24445)

configs/configload/loader_load.go, configs/configload/loader_load_test.go, configs/configload/testdata/expand-modules/no-provider-passed/.terraform/modules/modules.json, configs/configload/testdata/expand-modules/no-provider-passed/child/main.tf, configs/configload/testdata/expand-modules/no-provider-passed/root.tf, configs/configload/testdata/expand-modules/provider-configured/.terraform/modules/modules.json, configs/configload/testdata/expand-modules/provider-configured/child/main.tf, configs/configload/testdata/expand-modules/provider-configured/root.tf, configs/configload/testdata/expand-modules/valid/.terraform/modules/modules.json, configs/configload/testdata/expand-modules/valid/child-with-alias/main.tf, configs/configload/testdata/expand-modules/valid/child/main.tf, configs/configload/testdata/expand-modules/valid/root.tf
Expanding modules cannot have providers configured in them as this can cause issues with removal of the module. This PR updates the `moduleWalkerLoad` method in the `configload` package, where we have information about the caller (where the `count` or `for_each` is declared) and the module being loaded (which may have 0 or more provider configurations in it).
*Edited* Updated error message (changes to `for_each` when referring to `for_each`):
```
Error: Module does not support count
on main.tf line 15, in module "child":
15:   count = 1
Module "child" cannot be used with count because it contains a nested provider
configuration for "aws", at child/main.tf:2,10-15.
This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling …
```
=> Disallow provider configuration in expanding modules

command/013_config_upgrade_test.go, internal/getproviders/legacy_lookup_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go
When looking up the namespace for a legacy provider source, we need to use the `/v1/providers/-/{name}/versions` endpoint. For non-HashiCorp providers, the `/v1/providers/-/{name}` endpoint returns a 404.
This commit updates the `LegacyProviderDefaultNamespace` method and the mock registry servers accordingly, and increases test coverage for `LookupLegacyProvider`.
I ran a manual test of the `0.13upgrade` command using the following config in `main.tf`:
```hcl
provider "datadog" {
api_key = var.datadog_api_key
app_key = var.datadog_app_key
}
resource "datadog_monitor" "default" {
}
```
The command executed successfully and output this `versions.tf`:
```hcl
terraform {
datadog = {
source = "terraform-providers/datadog"
}
}
required_version = ">= 0.13"
}
```
(Prior to …
=> internal: Fix LookupLegacyProvider

addrs/provider.go, command/init.go, internal/getproviders/errors.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/getproviders/registry_source_test.go, internal/getproviders/types.go, internal/providercache/installer.go, internal/providercache/installer_test.go
This PR moves the provider protocol compatibility verification + provider version suggestion functionality from `providercache` into `getproviders`, since it was unique to the registry client. 
I've also refactored the provider version suggestion so that it's using the `protocol` portion of the response from `registryClient.ProviderVersions` instead of pulling the metadata for every version of the provider available until it finds a compatible version.
The new functionality is tested in both packages. I copied the `testRegistrySource` from `getproviders` into `providercache`, so I could test the error messages from the _installer_ (instead of the registry client). It was copied instead of exported so we can feel free to modify each implementation to match that package's testing needs.
=> getproviders: move protocol compatibility functions into registry client

command/init.go, command/init_test.go, command/testdata/init-provider-source/main.tf, configs/provider_requirements.go
Up until now, terraform v0.12 would silently ignore any "source" attributes
found in a required_provider block. This adds a warning when "source" is
found informing users that the attribute is ignored in terraform v0.12.
We were previously throwing away any warnings from the config loader if
there were no errors, so as a side effect any other warnings out of the
config loader that had not been displayed previously are now shown.
Here's a slightly off-center example of the output from `init` (also displayed on `validate`):
NOTE FOR REVIEWERS: I am concerned that displaying previously-swallowed warnings may be a surprise for some users, though it also feels correct.  Thoughts?
=> command/init: add a warning that "source" is ignored in terraform v0.12

command/init.go
Previously the diagnostics from the config loaders (earlyconfig and
regular) were only appended to the overall diags if an error was found.
This adds all diagnostics from the regular config loader so that any
generated warnings will be displayed, even if there are no errors.
I did not add the `earlyconfig` warnings since they will be displayed if
there is an error and are likely to be duplicated by the config loader (it will be easy to add in if I'm mistaken).
=> command/init: include config loader diagnostics in output

builtin/provisioners/chef/resource_provisioner.go, communicator/winrm/communicator.go, website/docs/provisioners/chef.html.markdown
Allows exit code 35 and 37 which do not imply Chef failure.
https://github.com/chef/chef-rfc/blob/master/rfc062-exit-status.md
Should help with #15134 and #16551
=> Chef: Gracefully Handle RFC062 Exit Codes

internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source_test.go, internal/providercache/installer_events.go
This is a port of the retry/timeout logic added in #24260 and #24259, using the same environment variables to configure the retry and timeout settings. It uses [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) to wrap the `http.Client` instance.
In a separate commit, remove the unused retry events from the provider installer. I previously tried to use transient error values and retry event handlers to handle retries. This had much better UI than the basic logging in this PR, but at least [my implementation was much more fragile](https://github.com/hashicorp/terraform/compare/alisdair/getproviders-retries-bad-branch-do-not-use). I was unable to find an abstraction that made sense and felt robust.
I don't think this PR is the best possible approach, but it does work, and …
=> internal/getproviders: Add configurable HTTP retry & timeout support

internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/filesystem_search.go, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/2.0.0/darwin_amd64/terraform-provider-null, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/2.0.0/linux_amd64/terraform-provider-null, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/invalid, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/terraform-provider-null_2.1.0_linux_amd64.zip, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/terraform-provider-null_invalid.zip, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/null/terraform-provider-null_invalid_invalid_invalid.zip, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/random-beta/1.2.0/linux_amd64/terraform-provider-random-beta, internal/getproviders/testdata/filesystem-mirror-invalid/hashicorp/random/1.2.0/linux_amd64/terraform-provider-random
If the search path is missing a directory, the provider installer would
try to create an `addrs.Provider` with the wrong parts. For example if the
hostname was missing (as in the test case), it would call
`addrs.NewProvider(namespace, typename, version)` and panic (because the version contains `.`, which makes it an invalid type). 
This commit adds a validation step for each part before calling `addrs.NewProvider` to avoid
the panic. For consistency with the rest of the function, it does not return an error in this case and instead ignores the directory.
=> internal/getproviders: fix panic with invalid path parts

website/docs/backends/types/s3.html.md
Doc improvement by adding short info on a single dynamodb table being usable to lock multiple state files as requested per issue #15303.
=> Add info on dynamodb locking multiple state files as per issue #15303

.hashibot.hcl
HashiBot labels issues as "crash" and "bug" when they container "panic:". This causes issues to bypass human triage, which means that provider-specific panics are put in our issue list rather than being labeled correctly. This removes that rule to allow for human labeling.
=> Remove hashibot panic issue labeler

addrs/provider.go, addrs/provider_test.go, configs/provider.go, configs/provider_meta.go, configs/provider_requirements.go, configs/provider_requirements_test.go, configs/resource.go, configs/testdata/invalid-files/provider-localname-normalization.tf, terraform/testdata/transform-provider-fqns-module/child/main.tf, terraform/testdata/transform-provider-fqns-module/main.tf, terraform/testdata/transform-provider-fqns/main.tf
This PR addresses the issue reported in #24914 where a provider local name in all caps caused misleading and unhelpful errors. Because terraform normalizes the provider source string, and the registry is case-insensitive, it does not make sense to treat provider names as case-sensitive. 
With this PR, Terraform verifies each provider local name (in `required_providers`, `provider {}` blocks, provider metas, and resources) and returns an error if the local name is not normalized. This error includes directions for fixing the problem:
A couple of other issues cropped up while I was in the area, so it may make more sense to review one commit at a time. I found a remaining called to `addrs.NewLegacyProvider()` that I would have sworn I replaced already about four times, and once the …
=> configs: require normalized provider local names

go.mod, go.sum, vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md, vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go, vendor/github.com/hashicorp/hcl/v2/hclwrite/parser.go, vendor/modules.txt
Upgrade hcl for hclwrite bugfixes, which will make 0.13upgrade more reliable. [Upstream changelog](https://github.com/hashicorp/hcl/releases/tag/v2.5.1).
=> vendor: go get github.com/hashicorp/hcl/v2@v2.5.1

command/command_test.go, command/refresh_test.go, command/show_test.go, helper/resource/state_shim.go, helper/resource/state_shim_test.go, states/instance_object.go, states/instance_object_src.go, states/state_deepcopy.go, states/statefile/testdata/roundtrip/v4-cbd.in.tfstate, states/statefile/testdata/roundtrip/v4-cbd.out.tfstate, states/statefile/version3_upgrade.go, states/statefile/version4.go, terraform/context_apply_test.go, terraform/eval_apply.go, terraform/eval_refresh.go, terraform/eval_state.go, terraform/graph_builder_apply.go, terraform/node_resource_apply_instance.go
The serialization of create_before_destroy into state was never completed. Here we serialize the new state field, and in the process remove the deprecated DependsOn field from the serialized output. 
The resource apply nodes need to be GraphNodeDestroyerCBD in order to correctly inherit create_before_destroy. While the plan will have recorded this to create the correct deposed nodes, the edges still need to be transformed correctly. We also need create_before_destroy to be saved to state for nodes that inherited it, so that if they are removed from state the destroy will happen in the correct order.
=> CreateBeforeDestroy inheritence and state serializaton

backend/remote/backend_apply.go, backend/remote/backend_apply_test.go, backend/remote/backend_common.go, backend/remote/backend_context.go, backend/remote/backend_context_test.go, backend/remote/backend_mock.go, backend/remote/backend_plan.go, backend/remote/backend_plan_test.go, backend/remote/testing.go, go.mod, go.sum, vendor/github.com/hashicorp/go-tfe/README.md, vendor/github.com/hashicorp/go-tfe/go.mod, vendor/github.com/hashicorp/go-tfe/go.sum, vendor/github.com/hashicorp/go-tfe/oauth_client.go, vendor/github.com/hashicorp/go-tfe/organization_membership.go, vendor/github.com/hashicorp/go-tfe/policy_set.go, vendor/github.com/hashicorp/go-tfe/policy_set_parameter.go, vendor/github.com/hashicorp/go-tfe/run.go, vendor/github.com/hashicorp/go-tfe/run_trigger.go, vendor/github.com/hashicorp/go-tfe/team.go, vendor/github.com/hashicorp/go-tfe/team_member.go, vendor/github.com/hashicorp/go-tfe/testing.go, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/github.com/hashicorp/go-tfe/variable.go, vendor/modules.txt
This is the local-CLI portion of allowing `-target` to be used with remote operations. `-target` addresses given on local CLI are copied into the API request to create a run, which Terraform Cloud will then in turn pass back into `-target` options for the remote Terraform CLI process.
Old versions of Terraform Cloud/Enterprise that lack support for this new attribute would silently ignore the `target-addrs` attribute and run an untargeted plan, so this also includes some version-sniffing so we can continue to return an error for an older server. The design of `go-tfe`'s versioning API combined with the mocking approach of the remote backend makes it annoyingly messy to unit test the case where `-target` isn't available on the server yet, so as a pragmatic compromise we elected to just …
=> backend/remote: Support -target on plan and apply

backend/remote/backend_apply_test.go, backend/remote/backend_common.go, backend/remote/backend_plan_test.go, go.mod, go.sum, vendor/github.com/hashicorp/go-tfe/cost_estimate.go, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/modules.txt
This is a follow-up to https://github.com/hashicorp/terraform/pull/24834, to include a few more bits of targeted plan handling from a separate PR to [go-tfe](https://github.com/hashicorp/go-tfe/pull/121).
It:
- updates `go-tfe`
- replaces the temporary handling for cost estimate status `tfe.CostEstimateSkippedDueToTargeting`
- adds sad path tests for the version check which prevents remote backend users from initiating targeted plans if their version of the API doesn't support them
=> Replace temporary cost estimate status handling for targeted runs

command/cliconfig/cliconfig.go, command/cliconfig/cliconfig_test.go, internal/providercache/dir.go
This PR came about after I spent <a long time> tracking down an error that turned out to be caused by a weird broken symlink in my plugin cache dir. The `providercache` was swallowing the error. 
This PR adds logging for any error messages and adds a bonus validation check (in command/cliconfig) that the user-specified provider cache dir exists.
=> provider cache: log errors and validate dir exists

website/docs/configuration/modules.html.md
This PR includes the website-side docs corresponding to #24892, attempting to clarify limitations about modules using `count` and `for_each`.
=> Add docs for provider limitations when expanding modules

website/docs/configuration/types.html.md
The [v0.11- docs](https://www.terraform.io/docs/configuration-0-11/syntax.html) give a pretty extensive description of how values of `map` type can be defined. There isn't quite as detailed an accounting of `map` considerations in the v0.12+ docs.
This PR brings forward some of that documentation detail for the `map` type, adding info about how while both equals signs and colons are valid delimiters in maps, they are currently handled differently by `terraform fmt`.
This PR addresses (issue) https://github.com/hashicorp/terraform/issues/24198.
=> Update maps docs to reflect v0.12 colon behavior

website/docs/configuration/functions/timestamp.html.md
Adding clarification that `timestamp` returns date and time in UTC.
=> specify that `timestamp` returns UTC

command/hook_ui.go
Fixes an edge case where reading during apply would display "**(Unknown action Read for […])**" in the UI.
=> command: Add UI hooks for read actions

configs/experiments.go, configs/testdata/invalid-files/variable-validation-bad-msg.tf, configs/testdata/invalid-files/variable-validation-condition-badref.tf, configs/testdata/invalid-files/variable-validation-condition-noref.tf, configs/testdata/invalid-modules/variable-validation-without-optin/variable-validation-without-optin.tf, configs/testdata/valid-files/variable_validation.tf, experiments/experiment.go, terraform/context_validate_test.go, terraform/testdata/validate-variable-custom-validations-child/child/child.tf, website/docs/configuration/functions/can.html.md, website/docs/configuration/variables.html.md
All of the feedback from the experiment described enhancements that can potentially be added later without breaking changes, so this change simply removes the experiment gate from the feature as originally implemented with no changes to its functionality.
Further enhancements may follow in later releases, but the goal of this change is just to ship the feature exactly as it was under the experiment.
Most of the changes here are cleaning up the experiment opt-ins from our test cases. The most important parts are in `configs/experiments.go` and in `experiments/experiment.go`.
=> configs: Custom variable validation is no longer experimental

configs/module_call.go, configs/module_call_test.go, terraform/context_apply_test.go, terraform/node_module_expand.go, terraform/testdata/apply-module-depends-on/main.tf, terraform/testdata/apply-module-depends-on/moda/main.tf, terraform/testdata/apply-module-depends-on/modb/main.tf
Allow the use of `depends_on` for modules.
This PR stands on the existing work already done for module expansion, evaluation, and data source planning. See #24461, #24697, and #24904 for the majority of the work involved in making that happen. 
Now that modules can be ordered and referenced as a whole, and data sources will cleanly allow forced ordering  by `depends_on`; all that is left is to enable the feature in the config and add the graph connections for the `depends_on` references. 
Closes #10462
Closes #17101
=> Module depends_on

backend/local/backend_apply.go, backend/local/backend_plan.go, backend/local/backend_plan_test.go, backend/local/testdata/plan-outputs-changed/main.tf, command/format/diff.go, command/show.go, plans/objchange/action.go, website/docs/commands/apply.html.markdown, website/docs/commands/plan.html.markdown
This is a baby-step towards an intended future where all Terraform actions which have side-effects in either remote objects or the Terraform state can go through the plan+apply workflow.
This initial change is focused only on allowing plan+apply for changes to root module output values, so that these can be written into a new state snapshot (for consumption by `terraform_remote_state` elsewhere) without having to go outside of the primary workflow by running `terraform refresh`. This applies both to direct changes to `output` blocks and to indirect changes via other objects used in an output's `value` expression.
This is also better than `terraform refresh` because it gives an opportunity to review the proposed changes before applying them, as we're accustomed to with resource changes. …
=> backend/local: treat output changes as side-effects to be applied

command/013_config_upgrade_test.go, command/command_test.go, command/e2etest/init_test.go, command/init.go, command/init_test.go, command/testdata/init-get-provider-detected-legacy/main.tf
Fetching a default namespace provider from the public registry can result in 404 Not Found error. This might be caused by a previously-default provider moving to a new namespace, which means that the configuration needs to be upgraded to use an explicit provider source.
This commit adds a more detailed error for this situation. Terraform checks if a provider with the same type can be found in the registry alias table, and if so displays this information in the diagnostic output. The recommended course of action is to run the 0.13upgrade command to generate the correct required_providers configuration.
The diagnostic output looks like this:
```
Error: Failed to install providers
Could not find required providers, but found possible alternatives:
hashicorp/foo -> acme/foo
hashicorp/bar -> …
```
=> command/init: Better diagnostics for provider 404s

go.mod, go.sum, vendor/github.com/zclconf/go-cty/cty/function/stdlib/json.go, vendor/modules.txt
Upgrade go-cty to get `jsonencode` fix, closes #23062
```
$ go get -u github.com/zclconf/go-cty
$ go mod vendor
$ go mod tidy
```
=> [vendor] upgrade go-cty

website/docs/providers/type/network-index.html.markdown
Fixes a typo in the documentation for Network Providers.
=> Fix doc typo replacing "and" with "as"

command/e2etest/providers_mirror_test.go, command/e2etest/testdata/terraform-providers-mirror/terraform-providers-mirror.tf, command/providers_mirror.go, commands.go, internal/getproviders/filesystem_search.go, internal/getproviders/hash.go, internal/getproviders/types.go, internal/providercache/cached_provider.go, website/docs/commands/providers/mirror.html.md
This new command is intended to make it easy to create or update a mirror directory containing suitable providers for the current configuration, producing a layout that is appropriate both for a filesystem mirror or, if copied into the document root of an HTTP server, a network mirror. (Network mirrors are not yet supported by Terraform for installation, so _that_ part is more aspirational but the directory structures are compatible in any case.)
This initial version is not customizable aside from being able to select multiple platforms to install packages for.
Future iterations of this could include commands to turn the JSON index generation on and off, or to instruct it to produce the unpacked directory layout instead of the packed directory layout as it currently does. Both of those …
=> command: terraform providers mirror

terraform/context_validate_test.go, terraform/node_resource_abstract.go, terraform/testdata/validate-bad-resource-count/main.tf
Fixes a panic when a configuration had a non-existing resource *with* a dynamic block. The `References()` function was missing a necessary return if the resource schema was empty (because the resource did not exist), and would panic when it tried to use the nil schema to parse dynamic blocks.
Added a test that panicked before this change was made.
--- 
EDIT: Adding a `return` after `References()` found that there was no schema caused another test to fail. I changed it so it *just* skips evaluating references which require a schema. I'm leaving both commits in place for now: if the former commit seems more correct, I can change the test output to match the new output. Otherwise we can stick with my second commit (I will squash).
Fixes #24838
=> terraform: fix panic with non extant resource and dynamics

configs/config.go, configs/config_test.go
`addProviderRequirements()` was incorrectly using the map keys from the module
provider configs when looking up the provider FQN. The map keys include
alias, so this resulted in a panic. 
This commit updates `addProviderRequirements()` to use the provider's name (only) when looking up the FQN and includes a test which reproduced the panic.
Fixes https://github.com/hashicorp/terraform/issues/25089
=> configs: fix panic with provider aliases

lang/funcs/crypto.go, lang/funcs/crypto_test.go
Keys generated by recent versions of OpenSSH use a new OpenSSH PEM format which is incompatible with the `x509` package. We can work around this by using the `ParseRawPrivateKey` from `x/crypto/ssh` and type asserting that we get the expected RSA key type back.
- [`ParseRawPrivateKey` docs](https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKey)
- [`ParseRawPrivateKey` source](https://github.com/golang/crypto/blob/279210d13fedf5be6d476bad5df6a015042bb905/ssh/keys.go#L1120-L1145), where you can see that it delegates depending on key type
- [Code further down the path returning an `rsa.PrivateKey`](https://github.com/golang/crypto/blob/279210d13fedf5be6d476bad5df6a015042bb905/ssh/keys.go#L1329-L1365), which is what our `rsadecrypt` function needs to proceed
The new OpenSSH private key …
=> lang/funcs: Add support for OpenSSH RSA key format

command/013_config_upgrade.go
It seems to be implemented but not shown in help message.
FYI: A help message for 0.12upgrade command on the 0.12 branch.
https://github.com/hashicorp/terraform/blob/v0.12.26/command/012_config_upgrade.go#L235-L243
=> Add `-yes` flag to 0.13upgrade help message

command/refresh.go
This patch will fix `terraform refresh` command default state file path.
`refresh` command forcibly updates state path to `DefaultStateFilename` when state argument is not present.
DefaultStateFilename = terraform.tfstate, but when using workspace, it is a mistake.
So, I changed to refers correct state path.
\*) I refered output.go
Related Issue: #22842
=> fix default state file path for refresh command

internal/modsdir/manifest.go
This fixes a dropped error in the `internal/modsdir` package.
=> internal/modsdir: Fix Dropped Error

terraform/context_apply_test.go, terraform/eval_read_data.go, terraform/eval_read_data_plan.go, terraform/graph_builder_refresh.go, terraform/node_data_refresh.go, terraform/node_module_expand.go, terraform/node_resource_abstract.go, terraform/node_resource_plan_instance.go, terraform/testdata/apply-module-depends-on/moda/main.tf, terraform/testdata/apply-module-depends-on/modb/main.tf, terraform/transform_reference.go
This adds the ability for data source evaluation to be deferred within modules using `depends_on`.
We start by extending the lookup of `depends_on` resources from the data source to walk back through any modules found that return references from `DependsOn()`. This is adequate for plan, since the data source is going to check for changes to these dependencies, but during refresh not-yet-created nodes don't exist in the graph.
To handle refresh, we do the same lookup, but only record if there are _any_ parent modules that returned `depends_on` references. This allows us to prevent the first read of the data source during an initial refresh in the same way we do when the data source has `depends_on` in its own configuration. 
Fixes #25121
=> Data source within modules using depends_on

backend/remote/backend.go, backend/remote/backend_test.go
objects
If a user cancels (ctrl-c) terraform init while it is requesting missing
configuration options for the remote backend, the PrepareConfig and
Configure functions would receive a null cty.Value which would result in
panics. This PR adds a check for null objects to the two functions in
question.
Fixes #23992
I have no idea how to test this, so please enjoy a screenshot showing the fix:
=> backend/remote: do not panic if PrepareConfig or Configure receive null

website/docs/backends/types/consul.html.md
Currently the example config for the Consul backend uses a live Consul demo cluster at `demo.consul.io`. This results in TF state with sensitive information and all being stored on a public site when users just copy and paste the config. This PR changes it so that the config address isn't the public demo cluster.
=> use example.com address in consul backend config

Makefile
Most of the targets in the Makefile have not been used in either CI or the normal development workflow for some time. Removing them clarifies that the expected way to build Terraform locally is simple: `go install`.
Remaining targets:
- `fmtcheck`, `generate`: these are used in CI to verify that the code is correctly formatted and that generate has been run appropriately
- `protobuf`: [referenced in CONTRIBUTING.md](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#generated-code) as the simplest way to build the `proto` files
- `website`, `website-test`: used to compile and test the local website in isolation from [the terraform-website repo](https://github.com/hashicorp/terraform-website)
=> Makefile: remove unused targets

addrs/provider_config.go, addrs/provider_config_test.go, states/statefile/testdata/roundtrip/v4-legacy-simple.in.tfstate, states/statefile/testdata/roundtrip/v4-legacy-simple.out.tfstate, states/statefile/version4.go
The ParseLegacyAbsProviderConfig was not detecting builtin providers
("terraform"), which caused issues for all users with 0.12 state and
the "terraform_remote_state" data source. Since "terraform" is the only
built-in provider this adds a very simple check to the parser so it
properly returns the builtin FQN.
Fixes https://github.com/hashicorp/terraform/issues/25148
=> addrs: detect builtin provider when parsing legacy provider string

terraform/context_validate_test.go, terraform/node_module_variable.go, terraform/node_output.go, terraform/transform_module_expansion.go
The recursive transform call should only return immediately on error.
This was causing nested modules containing multiple modules to not
be properly expanded.
Fixes #25114
=> Incorrect early return in module expansion transformer

command/format/diagnostic.go, command/format/diagnostic_test.go
Diagnostics where the highlight range has an empty overlap with a line would skip lines of the output. This is because if two ranges abut each other, they can be considered to overlap, but that overlap is empty. This results in an edge case in the diagnostic printer which causes the line not to be printed.
Config:
```hcl
variable "x" {
default = {
"foo"
}
}
```
Before:
After:
=> command/format: Fix empty overlap diagnostics

command/013_config_upgrade.go, command/013_config_upgrade_test.go
I feel the current confirmation prompt for 0.13upgrade command is ambiguous what is expected. Actually, when I used it for the first time, I cancelled it by typing `y` instead of `yes`.
I believe it would be great if the 0.13upgrade command tell us the expected value for confirmation like 0.12upgrade.
https://github.com/hashicorp/terraform/blob/v0.12.26/command/012_config_upgrade.go#L137-L141
```
$ terraform 0.13upgrade
This command will update the configuration files in the given directory to use
the new provider source features from Terraform v0.13. It will also highlight
any providers for which the source cannot be detected, and advise how to
proceed.
We recommend using this command in a clean version control work tree, so that
you can easily see the proposed changes as a diff against …
```
=> Make 0.13upgrade confirmation more user-friendly

website/docs/state/workspaces.html.md
Documentation change.  Added Kubernetes backend to docs/state/workspaces, since the Kubernetes backend supports multiple workspaces.
https://github.com/hashicorp/terraform/blob/master/website/docs/backends/types/kubernetes.html.md
> The following configuration options are supported:
> secret_suffix - (Required) Suffix used when creating secrets. Secrets will be named in the format: tfstate-{workspace}-{secret_suffix}.
=> backend/kubernetes: Kubernetes supports multiple workspaces

provider_source.go
A very very small bug caused terraform _not_ to include the default local plugin dir!
Fixes #25172
=> init: fix issue loading local plugin directory

website/docs/internals/module-registry-protocol.html.md, website/docs/internals/provider-registry-protocol.html.md, website/docs/internals/remote-service-discovery.html.md, website/docs/registry/api.html.md, website/layouts/docs.erb
Terraform v0.13 will, for the first time, support third-party implementations of the provider registry protocol. To allow for that, this adds some documentation about the protocol Terraform CLI is expecting.
This documentation is aimed at third-party server implementers only, and is not intended as comprehensive documentation for the larger API surface offered by the _official_ implementations of this protocol on the public Terraform Registry and in Terraform Cloud and Terraform Enterprise. We'll leave the Terraform Registry teams to document the extended protocol separately.
---
Continuing in similar vein to the above, I also included here a separate doc about the module registry protocol as required by Terraform CLI, which is only a tiny subset of the larger API offered by Terraform …
=> website: Specification for the provider registry protocol

command/013_config_upgrade.go, command/testdata/013upgrade-explicit-providers/expected/main.tf, command/testdata/013upgrade-explicit-providers/input/main.tf, command/testdata/013upgrade-implicit-providers/expected/main.tf, command/testdata/013upgrade-implicit-providers/input/main.tf
I went with the admittedly-displeasing option of a string comparison each time we encountered a provider name since this is intended to run before any of the other provider-detecting logic (which already recognizes "terraform" as a builtin provider). 
Fixes https://github.com/hashicorp/terraform/issues/25210
=> command/013upgrade: detect builtin terraform provider

dag/dag.go, dag/graph.go, dag/graph_test.go, dag/set.go, dag/set_test.go, dag/tarjan.go, terraform/transform_output.go
The output destroy node only needs to connect to each of the output's up-edges in order to be connected transitively to all of the outputs dependencies. In large, highly-connected graphs, this may save considerable time for each output.
This exposed a flaw in the Graph UpEdges and DownEdges methods, which returned the internal Set for efficiency, but would allow callers to inadvertently change the internal graph structure. Make sure the public interface returns a copy of the set, while retaining the no-copy behavior for internal callers.
=> Do not walk all descendants for root outputs

command/testdata/init-get-providers/main.tf, configs/config.go, go.mod, go.sum, vendor/github.com/apparentlymart/go-versions/versions/constraints/ruby_style.go, vendor/modules.txt
The new provider install logic for 0.13 uses a different version constraint parser that makes an effort to produce user-actionable error messages when the user enters something invalid or non-sensical, but as of right now the `configs` package is still in an in-between state between old and new because we didn't change the other places where version constraints appear to use the new parser yet.
The new parser is intentionally a little stricter than the old one, because it's no longer just a regex match and aims to give feedback when it finds something weird, but it was inadvertently a little _too_ strict in that it was enforcing the space between the operator and the boundary like in `~> 1.0.0`, due to a mistaken impression on my part that this was required by rubygems (which our …
=> Don't panic if the new version constraint parser is stricter than the old one

command/init.go, command/init_test.go, command/testdata/init-get-provider-detected-legacy/.terraform/modules/dicerolls/terraform-random-bar-1.0.0/main.tf, command/testdata/init-get-provider-detected-legacy/.terraform/modules/modules.json, command/testdata/init-get-provider-detected-legacy/child/main.tf, command/testdata/init-get-provider-detected-legacy/main.tf, configs/config.go, configs/config_test.go
When initializing a configuration which refers to re-namespaced legacy providers, we attempt to detect this and display a diagnostic message. Previously this message would direct the user to run the `0.13upgrade` command, but without specifying in which directories.
This commit detects which modules are using the providers in question, and displays a list of upgrade commands which specify the source directories of these modules.
For remote modules, we display a separate list noting that they need to be upgraded elsewhere, providing both the local module call name and the module source address.
Addresses the root cause of #25153. 
With a module from the registry:
=> command/init: Improve diags for legacy providers

terraform/context_import_test.go, terraform/graph_builder_import.go, terraform/testdata/import-module/main.tf
In order to import into a module, we have to make sure that module has
registered the expansion data.
Fixes #25192
=> ensure modules are expanded during import

command/apply.go
The positional argument passed to apply was once used to specify a source for a Terraform module to fetch and initialize (#337). This functionality was removed from the `init` command later (#15032) but not completely removed from `apply`.
This code was non-functional but largely not harmful, except for a very specific case (#25068): when passing an absolute path to a plan file as the positional argument on Windows, the `getter.Detect` code would incorrectly interpret the path as a URL. This caused init to fail and the apply command would exit with code 1 but without diagnostics.
This commit removes this codepath, which fixes this bug, and should otherwise have no effect on the supported behaviour of apply.
Fixes #25068
Manual verification of the fix on Windows 10:
=> command/apply: Remove implicit init call

command/graph_test.go, dag/marshal.go, dag/marshal_test.go
Providers can contain quotes, so we need to ensure proper quoting in the
dot format.
While it would be nice to make some other changes to the dot format, like better layout and clustering of modules, the abstractions are not what we need to do. The existing code was left halfway between transitioning from the line-by-line dot writer, to a structured json output, but the json graph project was abandoned. We can get much better output leveraging dot, but we need to start with better base abstractions.
Fixes #25237
=> quote dot node names

configs/configload/loader_load.go, configs/configload/loader_load_test.go, configs/configload/testdata/expand-modules/more-nested-provider/.terraform/modules/modules.json, configs/configload/testdata/expand-modules/more-nested-provider/child/main.tf, configs/configload/testdata/expand-modules/more-nested-provider/child2/main.tf, configs/configload/testdata/expand-modules/more-nested-provider/child3/main.tf, configs/configload/testdata/expand-modules/more-nested-provider/root.tf, configs/configload/testdata/expand-modules/nested-provider/.terraform/modules/modules.json, configs/configload/testdata/expand-modules/nested-provider/child/main.tf, configs/configload/testdata/expand-modules/nested-provider/child2/main.tf, configs/configload/testdata/expand-modules/nested-provider/root.tf
When a module is loaded, rather than only checking the first parent, provider validation has been refactored into a separate function such that we look for `count` or `for_each` on module calls. 
This covers the case when a module has a `provider {}` block and is the child (or child of a child) of a module that has `count` or `for_each` declared. Two tests are included, to ensure parent, and parent-of-parent.
=> Validation for provider blocks in expanding modules (nested)

terraform/context_validate_test.go, terraform/eval_output.go, terraform/eval_output_test.go, terraform/eval_validate.go, terraform/node_module_expand.go, terraform/node_output.go
While output blocks allowed `depends_on`, the expressions were never validated. We can validate that during regular output evaluation, since outputs don't have a separate validation node.
Module block `depends_on` was also not be validated, which we can do using the same logic applied to resources.
Fixes #25260
=> Validate depends_on in modules and outputs

command/import_test.go
This test runs `init`, which causes some dangling `.terraform` state after running tests.
=> command: Fix test cleanup

command/version.go, command/version_test.go
This PR adds a `-json` flag for the `terraform version` command, whose output is otherwise intended for human consumption.
Typical output looks like this:
Tests have been added for `terraform version` (which had none before) and `terraform version -json`.
=> terraform version -json

communicator/communicator_test.go, communicator/ssh/communicator_test.go, communicator/ssh/provisioner.go, communicator/ssh/provisioner_test.go
Validate if the SSH host is empty in provisioner connection configuration.
This will avoid the behavior of terraform trying to connect to the provisioner remote-exec that has no connection configured.
Fixes #21690
=> ssh: return error if host is empty

terraform/context_plan_test.go, terraform/node_module_variable.go, terraform/transform_reference.go
Normally module outputs are referenced directly, but with the new addressing scheme we can reference modules as objects, or groups of objects containing their outputs. When building the initial graph however module are not yet expanded, so like resource instances, we need to de-specify the module instance to the entire module when connecting references.
Fixes #25246
=> Whole module references

internal/initwd/from_module.go, internal/initwd/from_module_test.go, internal/initwd/module_install_test.go
There were two related issues here:
1. panic with any local module with submodules
This was caused by the local installer looking up the root module with the (nonexistent) key `"root."`, instead of `""`. I've updated the logic that determines the lookup key.
1. panic with a relative directory that was above the workdir ("../")
This was caused by a call to `filepath.Rel(".", subDir)`. This was fixed by detecting when "." is the source path and instead using the absolute path.
Added (unit) test cases for both panics and updated the existing e2e tests with
the correct install paths. As a side note, the e2e tests in this package don't run automatically in circle, but that functionality is covered in the command package e2e tests. I decided not the remove the e2e tests from `initwd` because …
=> internal/initwd: fix panics with relative submodules in DirFromModule

go.mod, go.sum, lang/functions_test.go, vendor/github.com/zclconf/go-cty-yaml/CHANGELOG.md, vendor/github.com/zclconf/go-cty-yaml/resolve.go, vendor/modules.txt
Update go-cty-yaml for the YAML numeric literal parsing fix in zclconf/go-cty-yaml#6.
Fixes #23770, with a small test to verify that.
=> vendor: update go-cty-yaml

scripts/docker-release/Dockerfile-release
`TERRAFORM_VERSION` is used to set a label in the final docker stage for the light docker image but because it was only declared in the first stage, it never made it to the 2nd stage in the multistage build. This fixes that issue.
I have also bumped the base image from `alpine:3.9.2` to `alpine:3.12`
=> Pass ARG to second stage in light Dockerfile

scripts/build.sh
This removes updating dependencies of gox in the `full` image docker build and also uses `-mod=readonly` to prevent automatic updates of `go.mod`
=> don't update deps of gox in docker build and use -mod=readonly

command/version.go, command/version_test.go
We globally support a -`v`/`-version`/`--version` flag, which triggers the version subcommand: https://github.com/hashicorp/terraform/blob/d144c391fabbcdf9343c2524e9ce874301486b40/main.go#L246-L255
The recent introduction of JSON output support meant we started parsing the flags for the first time, but we didn't add flags for these global version arguments. The result is that for the Terraform 0.13.0-beta2 release, `terraform -v` no longer works.
This commit adds those flags (but doesn't check them, since they have no effect on the version command itself). Also adds usage information for terraform version.
```shellsession
$ terraform-0.13.0-beta2 version
Terraform v0.13.0-beta2
$ terraform-0.13.0-beta2 -v
Error parsing command-line flags: flag provided but not defined: -v
$ …
```
=> command: Fix bug with -v/-version/--version flags

website/docs/configuration/backend.html.md, website/docs/configuration/modules.html.md, website/docs/configuration/provider-requirements.html.md, website/docs/configuration/providers.html.md, website/docs/configuration/terraform.html.md, website/docs/configuration/version-constraints.html.md, website/docs/internals/provider-meta.html.md, website/layouts/docs.erb
We previously covered everything about using providers on a single page, but that was getting unwieldy already and we now have a lot more to discuss with v0.13 introducing a new source address syntax and some other concepts.
Here we split the provider-related content into two parts: "Provider Requirements" covers how to find and declare dependencies on providers, and then "Provider Configuration" (formerly just "Providers") then focuses primarily on how to write zero or more provider configurations for a particular provider.
Because "Provider Requirements" is now presented before "Provider Configuration" in the navigation, I've also moved some of the introductory content about providers in general onto the "Requirements" page. The first paragraph of that content is duplicated onto the …
=> website: "Provider Requirements" documentation

command/command_test.go, command/plan_test.go
Some of the tests in the command package were running directly on the fixture directories, and modifying or locking files within them. This could cause state to leak between tests.
This commit cleans up all such cases that I could find (using `chflags` to mark all of the `testdata` tree as immutable). Fixes #24547.
=> command: Fix command fixture modify-in-place bugs

builtin/providers/terraform/data_source_state.go, builtin/providers/terraform/data_source_state_test.go
The workspace attribute is not computed, and therefor cannot be changed
from the configuration.
If the configuration has no `workspace` defined, the existing code will write `default` to the state. This will cause the next plan to see a change in the config from `default` to `null`, and force it to be read again. 
Fixes #25296 (2)
=> don't set remote workspace in state

terraform/context_plan_test.go, terraform/eval_read_data_plan.go
If a data source is storing a value that doesn't comply precisely with
the schema, it will now show up as a perpetual diff during plan. We
don't have a strict check for this, as data sources do not have the
`LegacyTypeSystem` flag to allow this behavior, but we can use the
same verification we use for managed resources. 
Since we can easily detect if there is no resulting change from the
stored value, rather than presenting a planned read each time, we can
change the plan to a NoOp and log the incongruity as a warning.
Fixes #25179, at least from the core side. Any other unexplained plans
would need to be fixed in the provider.
=> Hide empty plans for misbehaving data resource

configs/config.go, configs/config_test.go, configs/parser_test.go, configs/testdata/provider-reqs/child/grandchild/provider-reqs-grandchild.tf, configs/testdata/provider-reqs/child/provider-reqs-child.tf
[In a recent PR](https://github.com/hashicorp/terraform/pull/25190), we changed the provider requirements code to permit per-module requirements gathering, to enhance the provider command output. This had an incorrect implementation of recursive requirements gathering for the normal case, which resulted in only depth-1 modules being inspected.
This commit fixes the broken recursion and adds a grandchild module to the unit tests as test coverage. This also demanded fixing the `testNestedModuleConfigFromDir` helper function to cope with nested modules in test configs.
Fixes #25312, #25310.
=> configs: Fix nested provider requirements bug

backend/remote/backend.go
Ensure that the *http.Response is not nil before checking the status.
This can happen when retrying transport errors multiple times.
=> prevent panic in remote backend retry

configs/configload/loader_load.go, configs/configload/loader_load_test.go, configs/configload/testdata/module-depends-on/.terraform/modules/modules.json, configs/configload/testdata/module-depends-on/child/main.tf, configs/configload/testdata/module-depends-on/child2/main.tf, configs/configload/testdata/module-depends-on/root.tf
Providers themselves don't support `depends_on`, and therefore a module
with providers also cannot use `depends_on`.
Fixes #25330
=> don't allow providers in modules using depends_on

website/docs/provisioners/connection.html.markdown
Terraform's provisioner SSH connection type does not validate SSH host keys by default (see use of ssh.InsecureIgnoreHosteKey at https://github.com/hashicorp/terraform/blob/master/communicator/ssh/provisioner.go#L217-L244), which is generally appropriate given Terraform's frequent use with newly-created remote resources that do not have a known-trusted or CA-signed host key deployed.
This adds a note to the documentation to explicitly highlight this behavior, and point to the `host_key` direct as a means by which SSH host key checking may be enabled.
=> add note re. SSH host key validation to provisioner connection doc

website/docs/configuration/functions/trimprefix.html.md
I was looking to find out what Terraform would return when the prefix isn't in the string(https://www.terraform.io/docs/configuration/functions/trimprefix.html). Needed to go look it up in the Terraform source, so I figured I'd help the next lost person figure it out faster.
https://github.com/hashicorp/terraform/blob/master/lang/functions.go#L126 shows that Terraform's Trimprefix comes directly from the standard go library. 
When prefix is absent in the go standard library, the original string is returned; https://golang.org/pkg/strings/#TrimPrefix.
=> Trimprefix: what happens when prefix is not in string?

command/init.go, command/init_test.go
When using `-flag=value` with Powershell, unquoted values are broken into separate arguments. This means that the following command:
terraform init -backend-config=./backend.conf
is interpreted by Terraform as:
terraform init -backend-config= ./backend.conf
This results in an empty backend-config setting (which is semantically valid!) followed by a custom configuration path (pointing at a file).
Due to a bug where we could exit without printing diagnostics, this would result in a silent failure that was very difficult to diagnose. See #25266.
=> command: Fix init flags silent exit bug

lang/funcs/filesystem.go, lang/funcs/filesystem_test.go
The functions that interact with the filesystem are, by design, restricted to reading files that are distributed as a static part of the configuration, and cannot be used to interact with files that are generated dynamically by resources in the configuration.
However, new users have often yet developed a correct mental model of how Terraform execution works and are confused by the terse error messages these functions return. As an interim step to help some of those users, this just adds some more commentary to the error message which gives a vague, generic directive to look to attributes of the resource that is generating the file, which should (if it's designed well) export attributes that allow the resulting file to be used effectively with common patterns, such as checksums of the …
=> lang/funcs: Filesystem functions hint about dynamically-generated files

command/import_test.go, terraform/context_import_test.go, terraform/transform_import_state.go
We previously intentionally removed support for the `allow-missing-config` option to terraform import, requiring that all imported resources have matching config. See #24412.
However, the option was not removed from the import command, and it is widely used. This commit reintroduces support for importing with a missing configuration by falling back to implying the provider FQN based on the resource type.
Fixes #25294
=> command/import: Fix allow-missing-config option

configs/provider_requirements.go, configs/provider_requirements_test.go
When parsing provider requirements we should check the type of the source and version attributes rather than assuming that they are strings. Otherwise an invalid attribute value will cause a panic.
(Probably best reviewed ignoring whitespace.)
Fixes #25366
=> configs: Fix provider requirements panics

website/docs/commands/0.12upgrade.html.markdown, website/docs/commands/0.13upgrade.html.markdown, website/layouts/docs.erb
Although this command is removed in Terraform 0.13, our documentation is for all versions of Terraform that remain in common use and keeping this documented will be helpful for folks who are still using Terraform 0.11 and planning their upgrades to Terraform 0.12.
Both of the upgrade commands now include notes that they are only available in their specific major version, along with a link to the relevant upgrade guide for other background information about the upgrade, in case the user finds the command documentation first. (The command docs are, I think, a little more discoverable than the upgrade guides.)
=> website: Restore the docs for "terraform 0.12upgrade"

backend/remote-state/azure/backend.go, backend/remote-state/azure/backend_state.go, backend/remote-state/azure/backend_test.go, backend/remote-state/azure/client.go, website/docs/backends/types/azurerm.html.md
Rebased PR with some small fixes. Originally by @pmarques ([2018](https://github.com/hashicorp/terraform/pull/18512)) and @rahdjoudj ([2019](https://github.com/hashicorp/terraform/pull/21888)).
Fixes #18284 
Closes #18512 
Closes #21888
=> Azure backend: support snapshots/versioning

command/e2etest/init_test.go, command/e2etest/testdata/provider-warnings/main.tf, command/init.go, command/init_test.go, command/providers_mirror.go, internal/getproviders/filesystem_mirror_source.go, internal/getproviders/filesystem_mirror_source_test.go, internal/getproviders/http_mirror_source.go, internal/getproviders/memoize_source.go, internal/getproviders/memoize_source_test.go, internal/getproviders/mock_source.go, internal/getproviders/multi_source.go, internal/getproviders/multi_source_test.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/getproviders/registry_source_test.go, internal/getproviders/source.go, internal/getproviders/types.go, internal/providercache/installer.go, internal/providercache/installer_events.go
The public registry may include a list of warnings in the "versions"
response for any given provider. This PR adds support for warnings from
the registry and an installer event to return those warnings to the
user.
Example output:
```
Warning:
The remote registry returned warnings for
registry.terraform.io/test/burrito:
- Not a real burrito, please do not eat.
```
I would like to add an e2e test for this before it gets merged; I will follow up with the registry folks and see if there's a test provider whose existence I can count on and that we can add warnings to.
=> internal/getproviders: decode and return any registry warnings
