- website/docs/configuration/provider-requirements.html.md
- website/layouts/guides.erb
- website/upgrade-guides/0-13.html.markdown
This is an initial draft of the v0.13 upgrade guide intended to accompany the v0.13-beta1 release. We will continue to improve this guide throughout the v0.13 prerelease period based on questions and feedback.
For better readability you can see [a rendered version of this page](https://github.com/hashicorp/terraform/blob/doc-v0.13-upgrade/website/upgrade-guides/0-13.html.markdown), but note that the links to other pages in this document are set up to work on the final published website and so will not function correctly in GitHub's own Markdown rendering of this page. The paragraphs starting with `->` and `~>` will be rendered as note (blue) and warning (yellow) callouts respectively on the final site, due to markdown extensions implemented in the website renderer.
> website: Terraform v0.13 upgrade guide

- command/013_config_upgrade.go
- command/testdata/013upgrade-preserves-comments/expected/main.tf
- command/testdata/013upgrade-preserves-comments/input/main.tf
Previously, any comments inside the required provider configuration for a given provider would be wiped out upon rerunning the `0.13upgrade` command. This commit attempts to preserve those comments if the existing entry is semantically equivalent to the entry we are about to write.
Fixes #24958.
> command: Fix 0.13upgrade to preserve more comments

- command/login.go
- command/login_test.go
- command/ui_input.go
- go.mod
- go.sum
- terraform/ui_input.go
- vendor/modules.txt
This is for consistency with other commands which use prompts, all of which require "yes" rather than "y" to confirm. Fixes #24514.
After review, this change also includes adding secret/password entry to the `UIInput` interface and implementation, using the same logic as in [mitchellh/cli](https://github.com/mitchellh/cli/blob/171fbb5c839de5402a78f6097cfa41cd1a7d18c4/ui.go#L79-L84): https://github.com/hashicorp/terraform/blob/5a744602e1fcb584a24e36f04ded33f96b08b38c/command/ui_input.go#L135-L140
Also includes an exciting new horizontal rule in the UI to fix some confusing spacing. Screenshot:
Password/secret prompt (iTerm uses the 🔑 icon to indicate that echo is off):
Login completed, without the token being displayed:
> command/login: Require "yes" to confirm

- terraform/transform_destroy_edge.go
- terraform/transform_destroy_edge_test.go
When the DestroyEdgeTransformer was updated to handle stored
dependencies the addrs.ConfigResource type did not yet exist. The lookup
map keys in the transformer needed to be updated to remove module
indexes.
Fixes #25391
> index destroy dependencies by addrs.ConfigResource

- website/docs/backends/types/swift.html.md
Support for locking merged as https://github.com/hashicorp/terraform/pull/20211 on Feb 25, 2019
> Document swift support for locks

- terraform/context_apply_test.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_plan.go
- terraform/node_local.go
- terraform/node_module_expand.go
- terraform/node_module_variable.go
- terraform/node_output.go
- terraform/node_provider_abstract.go
- terraform/node_provider_disabled.go
- terraform/testdata/destroy-targeted/child/main.tf
- terraform/testdata/destroy-targeted/main.tf
- terraform/transform_provider.go
- terraform/transform_targets.go
This simplifies the initial targeting logic, and removes the complex
algorithm for finding descendants that result in output changes, which
hid bugs that failed with modules.
The targeting is handled in 2 phases. First we find all individual
resource nodes that are targeted, then add all their dependencies to the
set of targets. This in essence is all we need for targeting, and is
straightforward to understand.
The next phase is to add any root module outputs that can be solely
derived from the set of targeted resources. There is currently no way to
target outputs themselves, so this is how we can allow these to be
updated as part of a target.
Rather than attempting to backtrack through the graph to find candidate
outputs, requiring each node on the chain to properly advertise if it
could …
> New target transformer

- go.mod
- go.sum
- vendor/github.com/zclconf/go-cty/cty/function/stdlib/collection.go
- vendor/github.com/zclconf/go-cty/cty/function/stdlib/set.go
- vendor/modules.txt
Upstream changelog:
- `function/stdlib`: The `merge` function will no longer panic if all given maps are empty. ([#58](https://github.com/zclconf/go-cty/pull/58))
- `function/stdlib`: The various set-manipulation functions, like `setunion`, will no longer panic if given an unknown set value. ([#59](https://github.com/zclconf/go-cty/pull/59))
Terraform bugs fixed:
- Fixes #25318 
- Fixes #25303
> Upgrade go-cty to v1.5.1

- draft-upgrade-guide.md
With in-house providers, the correct plugin path does not contain the `v` in the version directory.
Should fix https://github.com/mildred/terraform/pull/new/fix-guide-v0.13-beta
> Fix 0.13 upgrade guide

- configs/resource.go
- configs/testdata/invalid-files/data-invalid-provider-reference.tf
- configs/testdata/invalid-files/resource-invalid-provider-reference.tf
If a resource's "provider" reference is invalid and cannot be parsed, we should not store the reference as part of a `ProviderConfigRef`. Doing so creates an invalid data structure, which prevents us from using `MustParseProviderPart` with the name in later steps.
The invalid test files added in this commit will cause a panic without the code change.
Fixes #25311
> configs: Fail early for invalid resource provider

- scripts/build.sh
- scripts/generate-plugins.go
While trying to write a `SlackBuild` for [slackbuilds](https://slackbuilds.org) I found myself having to hack around with directory names to get `terraform` to build with the required template.
In `slackbuild` scripts, the build directories are usually named with the format `$PRGNAM-$VERSION` (so `terraform-0.13`, etc).
This PR makes `terraform` building process more agnostic about the build directory name, which can only be a good thing, right?
> Allow building on non-terraform named directory

- command/init.go
- command/init_test.go
- command/testdata/init-backend-config-file/backend.config
- website/docs/backends/config.html.md
The -backend-config flag expects a set of key-value pairs or a file
containing key-value pairs. If the file instead contains a full backend
configuration block, it was silently ignored. This commit adds a check
for blocks in the file and returns an error if they are encountered.
Fixes #24845
Please feel encouraged to nitpick the error message!
```
Error: Invalid backend configuration file
The backend configuration file "backend.config" given on the command line must
only contain key-value pairs, and not full configuration blocks
```
> command/init: return an error with invalid -backend-config files

- terraform/eval_for_each.go
- terraform/eval_for_each_test.go
The error message when `evaluateForEachExpression` encountered an unknown
value of `cty.DynamicPseudoType` was not clear to users:
```
The given "for_each" argument value is unsuitable: "for_each" supports maps
and sets of strings, but you have provided a set containing type dynamic.
```
By moving the check for unknowns before the validation of set element types,
the following error is returned instead:
```
The "for_each" value depends on resource attributes that cannot be
determined until apply (...)
```
Fixes #24012
> terraform: improve error message when for_each encounters `cty.DynamicPseudoTypes`

- terraform/context_apply_test.go
- terraform/evaluate.go
Orphaned instances that are create_before_destroy will still be in the
state when their references are evaluated. We need to skip instances
that are planned to be destroyed altogether, as they can't be part of an
evaluation.
Fixes #16473
Fixes #11716
> don't evaluate destroy instances

- backend/local/backend_local.go
- backend/local/backend_local_test.go
- backend/remote/backend_context_test.go
- command/console.go
The `remote` backend `Context` would exit without an active lock if there
was an error, while the `local` backend `Context` exited *with* a lock. This
caused a problem in `terraform console`, which would call unlock on the state manager
regardless of error status.
This commit makes the local and remote backend consistently unlock the
state in case of error, and updates terraform console to check for errors in `Context`
before trying to unlock the state.
The new output from `terraform console` with a (successfully) configured backend but some other issue (for ex, invalid config syntax) no longer contains the locking error and only includes whatever actual problems were encountered.
Fixes #24246
----
Update: I finally figured out tests in backend/local and backend/remote; I am not adding …
> backend context: do not hold lock if there is an error

- terraform/context_eval_test.go
- terraform/evaluate.go
- terraform/testdata/eval-context-basic/child/main.tf
- terraform/testdata/eval-context-basic/main.tf
- website/docs/commands/console.html.markdown
Allow impure funcs in `walkEval`, which is used by `terraform console`.
I wrote a bit of a unit test for this, but it was so very simplistic that it did not seem worth doing (the test seemed more likely to give a false sense of coverage). I will happily do it anyway, or take other suggestions! 
I am also considering what additional documentation might be useful here, if any.  I started writing a note about impure functions in the `console` documentation to warn users about impure functions, but it felt pretty awkward. I'm inclined to skip it for now unless we start getting questions, but I can go back to that if y'all think it's something we should add now.
> terraform console: enable use of impure functions

- website/docs/internals/json-format.html.md
This PR updates the [JSON output format](https://www.terraform.io/docs/internals/json-format.html) documentation page. In this page, the Plan representation is described as having a top level `"config"` key mapping to a config-representation object. But with the latest version of Terraform, the config-representation object is mapped under a top level `"configuration"` key.
Related code: [command/jsonplan/plan.go](https://github.com/hashicorp/terraform/blob/bc386234d528747ad244574f72f1fc30a486d5c2/command/jsonplan/plan.go#L39)
---
Examples to reproduce with terraform `v0.12.26`:
* `main.tf` file:
```tf
resource "null_resource" "test" {
provisioner "local-exec" {
command = "echo 'hello world'"
}
}
```
Run
```shell
terraform init
terraform plan -out=plan
terraform show -json plan
```
the …
> Fix JSON output format documentation

- scripts/docker-release/Dockerfile-release
This PR modifies the Dockerfile used for releases to use `alpine:latest`. Previously, our release process relied on a Dockerfile separate from this repo which used `alpine:latest` but when we switched CI providers, we relied on the one in this repo instead. This brings them in sync and future releases should use the Dockerfile in `scripts/docker-release/Dockerfile-release`
Closes #25397
> use alpine:latest as the base image for terraform docker containers

- tools/terraform-bundle/package.go
This fixes a dropped error variable and handles logging.
> tools/terraform-bundle: fix dropped error

- website/docs/configuration/functions/format.html.md
This addresses the documentation portion of #23189 but does not close it (we may go back and fix this behavior in a future major release, since it will be a breaking change)
EDIT: Closes #23189
> website/docs: document difference in formatting strings with width and precision

- terraform/context_apply_test.go
- terraform/graph_builder_apply.go
- terraform/testdata/apply-destroy-outputs/main.tf
- terraform/transform_destroy_edge.go
- terraform/transform_output.go
If we're adding a node to remove a root output from the state, the
output itself does not need to be re-evaluated. The exception for root
outputs caused them to be missed when we refactored resource destruction
to only use the existing state.
Fixes #25469
> Do not evaluate output when doing a full destroy

- addrs/provider.go
- addrs/provider_test.go
- command/init.go
- command/init_test.go
- command/testdata/init-sniff-version-error/init-sniff-version-error.tf
- configs/testdata/error-files/provider-source-prefix.tf
The main motivation here is to produce a helpful error if a user incorrectly uses the terraform-provider- prefix (which we see on provider VCS repositories and plugin executables) as part of the source address.
However, this also more broadly blocks "terraform-" as a prefix in anticipation of whatever instinct causes the phenomenon where e.g. Python's PyPI has thousands of packages whose names start with "python-", even though everything on PyPI is for Python by definition. This is definitely not _necessary_, but it's better to be restrictive at first and weaken later as needed.
---
While I was testing this in various ways I encountered two other somewhat-confusing situations which led to me making some other changes at the same time:
* We were still returning the special `terraform init` …
> Disallow provider source addresses starting with terraform-

- command/init.go
- command/init_test.go
- command/meta_providers.go
- command/testdata/init-get-provider-invalid-package/main.tf
- internal/getproviders/mock_source.go
- internal/providercache/cached_provider.go
- internal/providercache/cached_provider_test.go
- internal/providercache/dir.go
- internal/providercache/dir_modify_test.go
- internal/providercache/dir_test.go
- internal/providercache/installer.go
- internal/providercache/installer_test.go
- internal/providercache/testdata/cachedir/registry.terraform.io/missing/executable/2.0.0/linux_amd64/executable
When installing a provider which has an invalid package structure (e.g. a missing or misnamed executable), the previous error message was confusing:
This PR adds support for a post-install provider cache validation step, which allows separate reporting of this error case, and a more actionable error message:
Broken into several commits due to the size of the diff:
- **providercache: Lazily detect executable file** (8e87ccb)
Instead of searching the installed provider package directory for a binary as we install it, we can lazily detect the executable as it is required. Doing so allows us to separately report an invalid unpacked package, giving the user more actionable error messages.
- **getproviders: FakeInstallablePackageMeta filename** (a18b531)
Add an optional execFilename argument to …
> Add post-install provider cache validation and error reporting

- terraform/testdata/apply-destroy-outputs/main.tf
- terraform/transform_destroy_edge.go
The pruneUnusedNodes transformer was skipping root level locals and
variables, causing them to be left in the graph during a full destroy.
Use the return value from `temporaryValue` to indicate if the node is
truly temporary or not, rather than keeping the entire root module.
Fixes #25532
> ensure root module locals and vars are pruned

- configs/module.go
- configs/testdata/invalid-files/resource-name-invalid.tf
An invalid type name in a resource (or data source) could cause a panic
when determining the implied provider for the resource. This commit adds
verification that the type name is valid. It does not add a diagnostic,
since the invalid type name would have already been caught by the
parser.
Fixes #25560
> configs: prevent panic with invalid type name

- terraform/node_resource_abstract.go
- terraform/node_resource_destroy.go
- terraform/node_resource_refresh.go
The AbstractResourceInstance type was storing the entire Resource from
the state, when it only needs the actual instance state. This would
cause resources to consume memory on the order of n^2, where n is the
number of instances of the resource.
Rather than attaching the entire resource state, which includes copying
each individual instance, only attach the ResourceInstance state, and
extract out the provider address from the Resource.
> don't store an entire Resource's state in each ResourceInstance

- website/upgrade-guides/0-13.html.markdown
Part of the upgrade process happens in the first `terraform apply` after adding explicit source addresses in the configuration. Previously we just left that implied under the assumption that everyone would run `terraform apply` shortly after anyway, but there is a specific tricky situation where the first change after upgrading is to remove a resource from the configuration, leaving Terraform unable to complete the upgrade.
Because of that, we'll now explicitly direct users to run `terraform apply` after upgrading. Along with that, there's a reminder to
make sure that "terraform plan" indicates no changes before upgrading, so that completing the upgrade doesn't involve also applying changes to remote objects.
> website: v0.13 upgrade guide about "terraform apply" during upgrading

- command/jsonconfig/config.go
- command/show_test.go
- command/testdata/providers-schema/basic/output.json
- command/testdata/show-json/basic-create/main.tf
- command/testdata/show-json/basic-create/output.json
A lingering FIXME caused missing configuration from provider config
blocks in the json output of terraform plan. This fixes the regression
and adds a regression test. For the sake of testing, I added an optional attribute
to the show test provider, which resulted in the providers schema test
getting an update - not a bad addition, but we can always add a
test-specific provider schema as needed.
> command/show: fix bug displaying provider config in json output of tf plan

- terraform/node_resource_abstract.go
- terraform/testdata/transform-destroy-edge-module-only/main.tf
- terraform/transform_destroy_edge.go
- terraform/transform_destroy_edge_test.go
- terraform/transform_reference.go
- terraform/transform_reference_test.go
Our reference transformer analyses and our destroy transformer analyses are built around static (not-yet-expanded) addresses so that they can correctly handle mixtures of expanded and not-yet-expanded objects in the same graph.
However, this characteristic also makes them unnecessarily conservative in their handling of references between resources within different instances of the same module: we know they can never interact with each other in practice because the dependencies for all instances of a module are the same and so one instance cannot possibly depend on another, but ignoring the instance keys in the analyses causes resources in different instances of the same module to become interconnected.
As a compromise then, here we introduce a new helper function that can recognize when a …
> core: Skip edges between resource instances in different module instances

- website/docs/commands/state/show.html.md
issue: https://github.com/hashicorp/terraform/issues/25616
From v0.12 the output format of state show command seems to be changed
but the old format is used in the document.
https://www.terraform.io/docs/commands/state/show.html
```
$ terraform version
Terraform v0.12.28
+ provider.packet v2.10.1
$ terraform state show 'packet_device.worker'
resource "packet_device" "worker" {
billing_cycle = "hourly"
created       = "2015-12-17T00:06:56Z"
facility      = "ewr1"
hostname      = "prod-xyz01"
id            = "6015bg2b-b8c4-4925-aad2-f0671d5d3b13"
locked        = false
}
```
> docs: fix the output format of state show command

- terraform/context_apply_test.go
- terraform/evaluate.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_apply_test.go
- terraform/node_local.go
- terraform/node_module_expand.go
- terraform/node_output.go
- terraform/testdata/apply-provisioner-destroy/main.tf
- terraform/transform_reference.go
The operation carried out by `terraform destroy` has always posed a problem, because it requires evaluation of the configuration, while intending to act as if most of that configuration is not present. The case for providers is further complicated when the provider configuration refers to other resources in the config. This is the only time during apply that we must somehow evaluate resources before they are themselves evaluated, since they are scheduled to be destroyed.
In 0.13 the ability for the evaluator to return values from resources scheduled for destruction during apply was removed entirely (which matches how it works during planning), so the situations that do need to evaluate a resource in its entirety don't contain deposed instances. This change unfortunately breaks providers …
> Allow provider config evaluation during a full destroy

- terraform/node_resource_abstract.go
- terraform/node_resource_destroy.go
- terraform/node_resource_refresh.go
This backports #25544, but is not a direct cherry-pick of the commit due
to significant changes in the types between 0.12 and 0.13.
The AbstractResourceInstance type was storing the entire Resource from
the state, when it only needs the actual instance state. This would
cause resources to consume memory on the order of n^2, where n is the
number of instances of the resource.
Rather than attaching the entire resource state, which includes copying
each individual instance, only attach the ResourceInstance state, and
extract out the provider address from the Resource.
> backport gh 25544

- tools/terraform-bundle/README.md
It's easier to read inline monospace characters than quoted characters,
especially when the content itself refers to a file or directory name.
> Syntax updates

- internal/providercache/package_install.go
When installing a provider which is already cached, we attempt to create a symlink from the install directory targeting the cache. If symlinking fails due to missing OS/filesystem support, we instead want to copy the cached provider.
The fallback code to do this would always fail, due to a missing target directory. This commit fixes that. I was unable to find a way to add automated tests around this, but I have manually verified the fix on Windows 8.1.
Fixes #25652
Steps to reproduce:
1. On a Windows 7 or 8 host, create a simple configuration:
```hcl
provider "random" {}
```
1. Run `terraform init` to download the random provider
1. Copy the `.terraform\plugins` folder to `%APPDATA%\terraform.d`
1. Remove the `.terraform` folder
1. Rerun `terraform init`
With 0.13.0-rc1:
With this commit:
> internal/providercache: Fix bug when symlink fails

- website/docs/configuration/modules.html.md
As part of documenting the new module `for_each` capabilities we added a section noting that shared modules using the legacy pattern of declaring their own provider configurations would not be compatible with them. However, that also applies to the new module `depends_on` and several folks participating in the beta pointed out that the documentation wasn't discussing that at all.
In order to generalize the advice we were giving, I've moved the old content we had (since v0.11) recommending against provider configurations in shared modules out into its own section, now hopefully being _more_ explicit that it is a legacy pattern and not recommended, and then folded the content about `for_each` and `count` (now also including `depends_on`) into that expanded section.
As is often the case, …
> website: Generalized advice on modules with provider configs

- website/docs/commands/cli-config.html.markdown
- website/docs/configuration/data-sources.html.md
- website/docs/configuration/index.html.md
- website/docs/configuration/modules.html.md
- website/docs/configuration/provider-requirements.html.md
- website/docs/configuration/providers.html.md
- website/docs/configuration/resources.html.md
- website/docs/configuration/terraform.html.md
- website/docs/internals/provider-registry-protocol.html.md
- website/docs/modules/publish.html.markdown
- website/docs/providers/index.html.markdown
- website/docs/registry/providers/os-arch.md
- website/docs/registry/providers/publishing.html.md
- website/layouts/docs.erb
This is mostly an effort to smooth out some of the explanations, make sure
things are presented in a helpful order, make sure terminology lines up, draw
connections between related concepts, make default behavior more apparent, and
the like. It shouldn't include very much new information, but there might be one
or two things that came out of a conversation somewhere.
Spotter's guide:
- Trying to _usually_ refer to provider configs with an `alias` argument as
"alternate provider configurations," rather than "aliased" ones. (May have
missed a few of these.)
- Introducing the idea of a "preferred local name" for a provider. That's
a provider's consistent resource type prefix, which:
- Terraform uses to guess the default provider for a resource type name.
- Usually (but not always) matches …
> Website: 0.13 docs edits, mostly around provider requirements

- website/docs/commands/import.html.md
- website/docs/import/index.html.md
- website/docs/import/usage.html.md
- website/docs/state/index.html.md
- website/docs/state/purpose.html.md
Terraform's design assumes that each remote object in Terraform's care is bound to one resource instance and one alone. If the same object is bound to multiple instances then confusing behavior will often result, such as two resource configurations competing to update a single object, or objects being "left behind" when all existing Terraform deployments are destroyed.
This assumption was previously only implied, though. This change is an attempt to be more explicit about it, although these are additions to some older documentation sections that have not been revised for some time and so this is just a best effort to make this information discoverable without getting drawn into a full-on reorganization of these sections.
While revising this I saw some particular oddities that I decided to …
> website: Documentation about the one-to-one object binding assumption

- tools/terraform-bundle/config.go
- tools/terraform-bundle/e2etest/package_test.go
- tools/terraform-bundle/e2etest/testdata/local-providers/terraform-bundle.hcl
These e2e tests will fail until there is a 0.13.0 GA release. I am opening this PR in advance so it can get approved and merged as soon as 0.13.0 is released.
> tools/terraform-bundle: re-enable e2e tests

- website/docs/state/index.html.md
Small docs issue with a broken link to the outputs page in the CLI documentation.
> Small docs fix for broken link

- website/layouts/backend-types.erb
A small fix to include the sidebar link to the k8s state storage backend.
> Fix sidebar link for Terraform standard backends to include link to Kubernetes backend docs

- backend/local/backend.go
- backend/local/backend_apply.go
- backend/local/backend_apply_test.go
- backend/local/backend_local.go
- backend/local/backend_local_test.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- backend/local/backend_refresh.go
- backend/local/backend_refresh_test.go
- backend/local/testing.go
- backend/remote/backend.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_context_test.go
- backend/remote/backend_plan_test.go
- command/console.go
- command/import.go
There was a subtle (and confusing) difference between the local and remote backend state locking strategies:
* The local backend context returns with a locked state, even if Context() failed.
* The remote backend returns with an unlocked state when Context() failed.
This was only showing up as a problem in a few commands when one was using the remote backend but the command was (only) running locally, such as `terraform console`: `terraform console` would always unlock state after getting the context, but if there was an error from `Context()`, the remote state was already unlocked and would result in a "workspace already unlocked" error. 
This PR aims for parity between remote and local by making the following changes:
* `backend/local` will unlock the state if `Context()` has an error, …
> backend state locking

- configs/module_merge.go
- configs/module_merge_test.go
- configs/testdata/valid-modules/override-module/a_override.tf
- configs/testdata/valid-modules/override-module/b_override.tf
- configs/testdata/valid-modules/override-module/primary.tf
The module `merge` function was not overriding `providers` blocks inside module calls. This fixes that and adds a test.
Fixes #24291
> configs: include "providers" when overriding modules

- states/statefile/version4.go
- states/statefile/version4_test.go
If a statefile had resources with the same name in different modules,
the sort order could be inconsistent between state refreshes. This adds
the module to the Less() function used in sorting and a minimal test to
verify consistent ordering.
Fixes #21552
> states/statefile: consistently sort resources across modules

- go.mod
- go.sum
- lang/funcs/cidr.go
- lang/funcs/cidr_test.go
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/modules.txt
The `cidrsubnet` and `cidrhost` functions were limited to supporting 32-bit systems. This PR:
* updates the `"github.com/apparentlymart/go-cidr"` library, which was recently extended with SubnetBig and HostBig functions
* switches to the new go-cidr functions, including passing appropriate values as `big.Int`s
* modifies terraform's validation check in `cidrsubnet` to check for bits > 64 instead of 32
Fixes  #25360
There's a new test, but for good measure, have some `terraform console` output:
```
> cidrsubnet("fe08::/64", 63, 0)
fe08::/127
```
> lang/funcs: update cidrsubnet and cidrhost for 64-bit systems

- command/state_mv.go
- command/state_mv_test.go
When moving a resource block with multiple instances to a new address within the same module, we need to ensure that the target module is present as late as possible. Otherwise, deleting the resource from the original address triggers pruning, and the module is removed just before we try to add the resource to it, which causes a crash.
Includes regression test which panics without this code change.
Fixes #25520
> command: Fix state mv for only resource in module

- website/docs/configuration/functions/indent.html.md
We must use interpolation, using the %{} directive will trigger the following error  **"indent" is not a valid template control keyword**
> Fix documentation example for the indent function

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
The `couldHaveUnknownBlockPlaceholder` helper was added to detect when a
set block has a placeholder for an unknown number of values. This works
fine when the number increased from 1, but we were still attempting to
validate the unknown placeholder against the empty set when the final
count turned out to be 0.
Since we can't differentiate the unknown dynamic placeholder value from
an actual unknown number of set values, we have to skip that object's validation
altogether.
Fixes #25600 
Fixes #22409 (same case but slightly different cause)
> Unknown set blocks with dynamic may have 0 elements

- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/eval_read_data_plan.go
- terraform/evaluate.go
When looking up a resource during plan, we need to return an empty
container type when we're certain there are going to be no instances.
It's now more common to reference resources in a context that needs to
be known during plan (e.g. for_each), and always returning a DynamicVal
here blocks plan from succeeding when there are 0 instances.
> Return known empty containers from resource evaluation during plan

- terraform/context_plan_test.go
- terraform/graph_builder_plan.go
- terraform/graph_builder_refresh.go
- terraform/testdata/plan-targeted/main.tf
- terraform/testdata/plan-targeted/mod/main.tf
- terraform/transform_targets.go
Before expansion happens, we only have expansion resource nodes that
know their ConfigResource address. In order to properly compare these to
targets within a module instance, we need to generalize the target to
also be a ConfigResource.
We can also remove the IgnoreIndices field from the transformer, since
we have addresses that are properly scoped and can compare them in the
correct context.
Fixes #25748
> Generalize target addresses before expansion

- backend/local/backend_local.go
- command/console_test.go
- command/graph_test.go
- command/testdata/apply-vars/main.tf
- terraform/eval_state_upgrade.go
- terraform/eval_state_upgrade_test.go
While removal of attributes can be handled by providers through the
UpgradeResourceState call, data sources may need to be evaluated before
reading, and they have no upgrade path in the provider protocol.
Strip out extra attributes during state decoding when they are no longer
present in the schema, and there is no schema upgrade pending. If there 
is a pending schema upgrade, let the provider handle it since it may want to
check for the removed attribute values. 
Another option not explored here is declaring that providers must migrate
any attributes pending removal before they actually removed, which would
allow the possibility of making the decoder less strict and always strip out
unknown attributes (similar to `encoding/json`). Since we can
handle the case fully within core, it seems …
> Remove resource state attributes that are no longer in the schema

- website/layouts/docs.erb
This is an adjustment to the sidebar nav to demote provisioners from a top-level item to a subsection of the language docs. A few things worth noting: 
- This doesn't mess with the actual URL paths yet, so we don't need to do any redirecting or link updates yet. It just changes the sidebar. 
- Both the 0.12+ language docs and the 0.11 language docs get a "provisioners" nav item in the sidebar, but only the 0.12 one is complete. When viewing a page in the provisioners section, it looks like you're within the 0.12+ language docs, even if you clicked the link from the 0.11 section. This is a pretty degraded experience for 0.11 users, BUT, hopefully we're far enough along in getting the community onto the modern language that it isn't a huge problem. 
- I'm using some trickery to keep the …
> website: Move provisioners into language section of nav sidebar

- Makefile
Running `make website` would result in a missing image error from Docker, as a result of the `VERSION` variable missing from the Makefile. This value matches that in the Makefile of the terraform-website repository.
> [build] Fix missing VERSION for running make website

- website/layouts/commands-providers.erb
The `providers mirror` subcommand documentation is up, but missing from the sidebar:
> website: add providers mirror command to providers sidebar

- states/statemgr/statemgr_fake.go
I've frequently needed to coerce `Unlock()` errors for tests and it's been
awkward and fraught every time, so I decided to add a full state manger
that returns *mostly* errors. I intend to use this in conjunction with
the `clistate.Locker` interface, which first calls `statemgr.Lock()` (to block if the
mutex is in use) at the start of `clistate.Unlock()`, so `statemgr.Lock()` rather awkwardly needed to succeed.
> statemgr: add a NewUnlockErrorFull state manager for tests

- addrs/provider.go
- addrs/provider_test.go
- states/statefile/testdata/roundtrip/v3-builtin.in.tfstate
- states/statefile/testdata/roundtrip/v3-builtin.out.tfstate
Builtin provider addrs (i.e. `"terraform.io/builtin/terraform"`) should be able to convert to legacy string form (i.e. `"terraform"`). This ensures that we can safely round-trip through `ParseLegacyAbsProviderConfig`,
which can return either a legacy or a builtin provider addr.
Fixes #25803. The test in the second commit reproduces the panic without the first commit.
> addrs: Fix LegacyString for builtin providers

- command/version.go
- command/version_test.go
Running `terraform version` should output the version number, followed by the outdated message if any. This was broken in https://github.com/hashicorp/terraform/pull/25252 and the order was reversed. This PR fixes the order.
```
★ ./terraform version
Terraform v0.13.0-beta1
Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
```
```
★ ./terraform version
Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0-rc1
```
> terraform version: fix output order

- terraform/eval_read_data_plan.go
- terraform/eval_read_data_plan_test.go
In order to determine if we need to re-read a data source during plan,
we need to compare the newly evaluated configuration with the stored
state. To do that we create a ProposedNewVal, which if there
are no changes, should match the existing state.
A problem arises if the remote data source contains any blocks, and they
are not set in the configuration. Terraform always decodes configuration
blocks as empty containers, however the legacy SDK cannot correctly
handle empty blocks and may return a null value which is saved to the
state. In order to correctly make the comparison for planning, we need
to reify those null blocks as empty containers in the cty value.
The createEmptyBlocks helper converts any null NestingList or NestingSet
blocks to empty list or set cty values. We only need to …
> allow plan data state comparison with legacy SDK

- command/import_test.go
- command/testdata/import-module-input-variable/child/main.tf
- command/testdata/import-module-input-variable/main.tf
- command/testdata/import-module-input-variable/terraform.tfvars
- terraform/node_module_variable.go
Include the import walk in the list of operations for which we create an `EvalModuleCallArgument` node. This causes module call arguments to be evaluated even if the module variables have defaults, ensuring that invalid default values (such as the common `{}` for variables thought of as maps) do not cause failures specific to import.
This fixes a bug where a child module evaluates an input variable in its locals block, assuming that it is a nested object structure. The bug report includes a default value of `{}`, which is overridden by a root variable value. Without the eval node added in this commit, the default value is used and the local evaluation errors.
**Note:** I'm surprised that we weren't evaluating module call arguments for imports, as that seems like it would break import for …
> terraform: Eval module call arguments for import

- command/init_test.go
- command/testdata/init-check-required-version/main.tf
- terraform/version_required.go
If a module has multiple `terraform.required_version` constraints, any failures would point at the last constraint in the error diagnostics. If an earlier constraint was the actual problem, this leads to confusing errors like this:
```
Error: Unsupported Terraform Core version
on main.tf line 6, in terraform:
6:   required_version = ">= 0.13.0"
This configuration does not support Terraform version 0.13.0.
```
The error was due to storing the declaration range of the constraint as a pointer to the contents of a loop variable, which was later overwritten in later iterations of the loop.  Instead we now use HCL's handy `Range.Ptr` method to create a direct pointer to the range struct.
Fixes #25833
> terraform: Fix required version constraint diags

- terraform/context_apply_test.go
This fixes a dropped test `err` variable in the `terraform` package.
> terraform: fix dropped test error

- tools/terraform-bundle/CHANGELOG.md
This is something I'd meant to do during the 0.13 development cycle. It's purposefully small and simple: terraform-bundle isn't likely to change much (if at all) in the next release(s), but I said I'd do it, so here it is!
> terraform-bundle: initial changelog

- command/jsonconfig/config.go
- command/testdata/show-json/module-depends-on/foo/main.tf
- command/testdata/show-json/module-depends-on/main.tf
- command/testdata/show-json/module-depends-on/output.json
With the recent addition of the `depends_on` meta-argument, we also need to ensure that `depends_on` is being added to the module calls within the config. This PR adds the `depends_on` field as well as a test for validating it is output via `terraform show`.
Codecov is reporting the drop in test coverage due to the tests being in a different package to `jsonconfig`.
> Ensure depends_on is in module calls for config

- website/docs/commands/apply.html.markdown
There has been some confusion regarding use of the `-state` option on apply, and the upgrade from terraform v0.12 to v0.13 introduced an additional rough edge: `terraform init` has no knowledge of the alternative statefile path specified on the command line, and therefore ends up missing some important information about the providers required by the state. This could have been an issue for anyone with, for example, providers required by the state that aren't in the configuraiton, but it's especially noticeable in the v013 upgrade path because terraform init needs to know that the state still has "legacy" style providers. 
If a user wants to configure an alternate statefile path that can persist through all terraform commands (init being the interesting one today), they should configure a …
> website/docs: clarify behavior of -state flag  

- codecov.yml
The annotations are  distracting and make some PRs difficult (for me) to read.
> build: disable github pr annotations

- command/meta.go
- command/meta_test.go
Since `-no-color` is a global argument and not actually handled by terraform commands, it must be removed from the list of arguments sent to commands.  However the current code assumes only a single `-no-color` argument is ever added.  This can easily not be the case if someone has `TF_CLI_ARGS` set to include `-no-color`, e.g. in an automation system where color is not helpful, and a call to terraform also includes a `-no-color` argument.
This change removes all instances of `-no-color` from the argument list before sending it to the commands.
Fixes #25845
> Fix error when multiple -no-color arguments are used

- command/init.go
- command/init_test.go
- command/testdata/init-backend-config-file/backend.config
- command/testdata/init-backend-config-file/invalid.config
When loading a backend config override file, init was doing two things wrong:
- First, if the file failed to parse, we accidentally didn't return, which caused a panic due to the parsed body being nil;
- Secondly, we were overzealous with the validation of the file, allowing only attributes. While most backend configs are attributes only, the enhanced remote backend body also contains a `workspaces` block, which we need to support here.
This commit fixes the first bug with an early return and adds test cases for missing file and intentionally-blank filename (to clear the config).
We also add a schema validation for the backend block, based on the backend schema itself. This requires constructing an HCL body schema so that we can call `Content` and check for diagnostic errors.
The result …
> command: Fix backend config override validation

- addrs/resource.go
- terraform/node_resource_abstract.go
- terraform/node_resource_abstract_test.go
When we need to select a qualified provider address based on an implied provider name, we have a special case that the name "terraform" maps to `terraform.io/builtin/terraform`, instead of `registry.terraform.io/hashicorp/terraform` as would be the case for other prefixes.
However, in order for that to work properly we need to use `addrs.ImpliedProviderForUnqualifiedType` instead of `addrs.NewDefaultProvider`, because the latter just unconditionally always produces a "default" provider configuration (belonging to the "hashicorp" namespace on the public registry).
This fixes #25719.
> core: NodeAbstractResourceInstance.Provider correct implied provider

- internal/providercache/package_install.go
The `installFromHTTPURL` function downloads a package to a temporary file, then delegates to `installFromLocalArchive` to install it. We were previously not deleting the temporary file afterwards. This commit fixes that.
I can't see any reasonable way to write a unit test for this, but I've manually tested it.
Fixes #25977
> internal: Clean up package install temp file

- website/docs/configuration/modules.html.md
Add a note to the provider configuration section explaining that only config can be inherited by child modules, not source or version requirements.
Copy editing suggestions very welcome here!
Raised in #25984
> website: Provider requirements are not inherited

- website/docs/configuration/provider-requirements.html.md
On the https://www.terraform.io/docs/configuration/provider-requirements.html#requiring-providers page, the link to the `v0.12-Compatible Provider Requirements` section is broken:
* current link: https://www.terraform.io/docs/configuration/provider-requirements.html#v012-compatible-provider-requirements
* correct link: https://www.terraform.io/docs/configuration/provider-requirements.html#v0-12-compatible-provider-requirements
> Fix link to "v0.12-Compatible Provider Requirements" section

- website/docs/configuration/provider-requirements.html.md
The version constraint section could be read to suggest that terraform allows selection of multiple versions of a single provider. Suggestions _gleefully_ welcomed.
Fixes https://github.com/hashicorp/terraform/issues/25935
> website/docs: remove unclear provider version constraint description

- command/init.go
- command/init_test.go
When applying a backend config override file, we must not check for the presence of all required fields, as the override can be a partial configuration. It is only valid to check for required fields after all overrides have been merged, which init already does.
I can't find any way to add test coverage for this change. I've validated that this fixes the issue reported in #26002 manually, but the only backends which have required attributes in their schema also need to access remote services for `init` to succeed.
Fixes #26002
> command: Fix backend config schema validation

- internal/getproviders/errors.go
- internal/getproviders/hash.go
- internal/getproviders/http_mirror_source.go
- internal/getproviders/http_mirror_source_test.go
- internal/getproviders/package_authentication.go
- internal/getproviders/package_authentication_test.go
- internal/getproviders/registry_client_test.go
- provider_source.go
- website/docs/commands/cli-config.html.markdown
- website/docs/commands/providers/mirror.html.md
- website/docs/internals/provider-network-mirror-protocol.html.md
- website/layouts/docs.erb
Our initial v0.13.0 release included support for mirroring providers in the local filesystem, as an alternative to retrieving them from the registry host indicated in the provider source address. We had intended to also support mirrors implemented as HTTP servers, thus allowing a mirror to potentially be set up once and shared across a number of different calling hosts, but that was a stretch goal for v0.13.0 and ultimately wasn't completed in time.
This changeset implements the `network_mirror` installation method, using a newly-defined protocol that is designed to be relatively easy to implement using a static website system, particularly if you upload to it the result of running [`terraform providers mirror`](https://www.terraform.io/docs/commands/providers/mirror.html).
An important …
> Network-based Mirrors for Provider Installation

- internal/initwd/from_module_test.go
Fixes #26014
This PR contains a small change to the `from_module_test.go` unit test to canonicalize the directory path names in its "expected" values in the same way that the invoked code path does. Existing code is using the absolute path, but without the symlinks (if any) expanded.
Without this change, the unit test does not pass when run from a source tree whose `$PWD` contains symlinks because the "expected" values are constructed differently than the code being tested. Full details are described in issue #26014.
> build: allow tests to pass when $PWD contains symlinks

- terraform/resource_provisioner.go
Fix comment for `type ResourceProvisioner interface` as the `Apply` method is only returning an `error` and not the new resource state.
> provisioner comment fix.

- website/docs/modules/sources.html.markdown
The information on downloading archives (specifically the warning that an archive might be a directory) is all there, but it's not necessarily obvious that the information was relevant (and important) when looking at the http download section specifically. 
Closes #25873
> webside/docs: add note re: archive subdirectories to http download section

- terraform/eval_read_data_plan.go
- terraform/eval_read_data_plan_test.go
When calling `createEmptyBlocks`, we only intend to process legacy SDK blocks (`NestingList` or `NestingSet`), but the function also needs to pass through `NestingSingle` block types untouched. To do so we must only look up the container's element type after we've established that the block is backed by a container.
Fixes #26011
> terraform: Fix createEmptyBlocks NestingSingle bug

- configs/module.go
Changing "An module" to "A module" in an error message
> Tiny typo in an error message

- backend/local/backend_local.go
- command/plan_test.go
- terraform/context.go
- terraform/context_apply_test.go
This pull reverts a recent change to `backend/local` which created two context, one with and one without state. Instead I have removed the state entirely from the validate graph (by explicitly passing a `states.NewState()`).
This changed caused a test failure, which (ty so much for the help) @jbardin discovered was inaccurate all along: the test's call to  `Validate()` was actually what was removing the output from state, which should not have been happening during `Validate` anyway. The new expected test output matches terraform's actual behavior on the command line: if you use -target to destroy a resource, an output that references only that resource is _not_ removed from state. 
This includes two tests to cover the expected behavior:
- `TestPlan_varsUnset` has been updated so it will …
> terraform: remove state from `validate` graph walk

- website/docs/providers/type/community-index.html.markdown
Reported in https://github.com/hashicorp/terraform-website/issues/1418
> website: fix a broken community provider link

- command/013_config_upgrade.go
- command/013_config_upgrade_test.go
- command/command_test.go
- command/init.go
- command/testdata/013upgrade-provider-redirect-version-unavailable/expected/main.tf
- command/testdata/013upgrade-provider-redirect-version-unavailable/expected/versions.tf
- command/testdata/013upgrade-provider-redirect-version-unavailable/input/main.tf
- command/testdata/013upgrade-provider-redirect/expected/main.tf
- command/testdata/013upgrade-provider-redirect/expected/versions.tf
- command/testdata/013upgrade-provider-redirect/input/main.tf
- internal/getproviders/legacy_lookup.go
- internal/getproviders/legacy_lookup_test.go
- internal/getproviders/registry_client.go
- internal/getproviders/registry_client_test.go
- internal/getproviders/registry_source.go
If a provider changes namespace in the registry, we can detect this when running the `0.13upgrade` command. As long as there is a version matching the user's constraints, we now use the provider's new source address. Otherwise, warn the user that the provider has moved and a version upgrade is necessary to move to it.
Successful provider redirect, due to version constraint being met by the redirect target:
Cannot follow the redirect, as the version constraint cannot be met:
> command: Add redirect support to 0.13upgrade

- command/output.go
- command/output_test.go
When the output subcommand is called with no arguments, and there are no outputs to show, we previously rendered an error message but returned a non-error status code. This is confusing.
This commit changes the text UI to use a warning diagnostic, which makes it clearer that this is a non-error situation. We do not change the exit code or the text of the warning, so hopefully this is not considered a breaking change.
Fixes #25956
> command: Warn instead of error for empty output

- website/docs/registry/providers/publishing.html.md
The new preferred way to publish is the GitHub action + GoReleaser, this highlights that in the docs.
> Add GitHub action instructions to publishing

- docs/plugin-protocol/object-wire-format.md
Although we have in this same directory the protocol buffers schemas for the static parts of the provider wire protocol, many of the protocol messages include `DynamicValue` messages that are presented in a nested dynamic serialization format.
That format was previously not documented, and was thus defined only by the implementation. Terraform happens to use a third-party library to implement parts of this encoding, which means that the rules were even harder to track down from reading the code.
Regardless of how Terraform happens to implement its serialization and deserialization of `DynamicValue`, it's the wire format that is contractual and so this document is an implementation-agnostic description of the mapping rules for serializing any Terraform Language value by reference to a …
> docs: Provider protocol wire format for values

- command/format/diagnostic.go
- command/format/diagnostic_test.go
- command/init.go
- command/init_test.go
- command/testdata/init-get-provider-legacy-from-state/main.tf
- command/testdata/init-get-provider-legacy-from-state/terraform.tfstate
- website/upgrade-guides/0-13.html.markdown
When `init` attempts to install a legacy provider required by state and fails, but another provider with the same type is successfully installed, this almost definitely means that the user is migrating an in-house provider. The solution here is to use the `terraform state replace-provider` subcommand.
This commit makes that next step clearer, by detecting this specific case.
Before:
After:
> command: Better in-house provider install errors

- website/docs/commands/cli-config.html.markdown
Small link issue is fixed in our documentation.
> Small typo in the internals link to the provider network mirror protocol

- website/docs/configuration/locals.html.md
- website/docs/configuration/variables.html.md
An alternate approach to #25017 . 
The subtle difference in keywords when creating vs. accessing locals trips
people up, even more than the "variable" vs. "var" distinction. It deserves its
own subheader on the page, plus a nice noisy callout.
> Clarify `locals` vs. `local.thing` distinction

- command/clistate/state.go
- command/clistate/state_test.go
This attempts to fix [Issue 23017](https://github.com/hashicorp/terraform/issues/23017)
When the lock can't be released return the err even if there is no previous error with the current action. This allows faster failure in CI/CD systems. Without this failure to remove the lock would result in the failure happening on a subsequent plan or apply which slows down the feedback loop in automated systems.
> Return an error on unlock failure

- lang/functions_test.go
- website/docs/configuration/functions/jsonencode.html.md
The `jsonencode` function has some slightly unintuitive character escaping edge cases:
```shellsession
$ echo 'jsonencode("(>_<)")' | terraform console
"(\u003e_\u003c)"
```
This behaviour always been there, but was undocumented and not covered by tests. This PR adds a small note to the function documentation, and a test case. While it's unusual looking, this is valid JSON, and we don't intend to change how it works, as it would be disruptive to users.
I think this closes #26110, since we're not going to change the behaviour.
> Document jsonencode HTML escape behaviour

- terraform/execute.go
- terraform/graph.go
- terraform/graph_walk.go
- terraform/graph_walk_context.go
This introduces a new `GraphNode`, `GraphNodeExecutable`, which will
gradually replace` GraphNodeEvalable` as part of the overall removal of
terraform's `EvalNode`s. Terraform's `Graph.walk` function will now check if a node implements
`GraphNodeExecutable` and run `walker.Execute()`.
For the time being, terraform will panic if a node implements both
`GraphNodeExecutable` and `GraphNodeEvalable`. This will be removed when
we've finished removing all `GraphNodeEvalable` implementations.
The new` GraphWalker` function, `Execute()`, is meant to replace both
`EnterEvalTree` and `ExitEvalTree`, and wraps the call to the
`GraphNodeExecutable`'s `Execute` function.
This PR departs from my original (internal) proposal, which did not include the`walker.Execute()` wrapper around …
> terraform: add GraphNodeExecutable interface

- configs/config_test.go
- configs/configload/testdata/expand-modules/provider-configured/child/main.tf
- configs/parser_test.go
- configs/provider.go
- configs/provider_test.go
- configs/testdata/valid-files/provider-configs.tf
- website/docs/configuration/providers.html.md
The version argument is deprecated in Terraform v0.14 in favor of
required_providers and will be removed in a future version of terraform
(expected to be v0.15). The provider configuration documentation already
discourages use of 'version' inside provider configuration blocks, so it
only needed an extra note that it is actively deprecated.
I took advantage of an existing test, TestProviderReservedNames in provider_test.go, to verify the diagnostic, instead of writing a test just for this. That felt ok to do since we'll be removing it all in v0.15 (probably).
> configs: deprecate version argument inside provider configuration blocks

- internal/providercache/dir_modify_test.go
For reasons that are unclear, these two tests just started failing on macOS very recently. The failure looked like:
```
PackageDir: strings.Join({
"/",
+     "private/",
"var/folders/3h/foobar/T/terraform-test-p",
"rovidercache655312854/registry.terraform.io/hashicorp/null/2.0.0",
"/windows_amd64",
},
```
Speculating that the macOS temporary directory moved into the /private directory, I added a couple of EvalSymlinks calls and the tests pass again.
No other unit tests appear to be affected by this at the moment.
🤷‍♂️
> internal: Fix providercache test failures on macOS

- internal/depsfile/doc.go
- internal/depsfile/locks.go
- internal/depsfile/locks_file.go
- internal/depsfile/locks_file_test.go
- internal/depsfile/paths.go
- internal/depsfile/testdata/locks-files/empty.hcl
- internal/depsfile/testdata/locks-files/invalid-provider-addrs.hcl
- internal/depsfile/testdata/locks-files/invalid-versions.hcl
- internal/depsfile/testdata/locks-files/unsupported-block.hcl
- internal/depsfile/testdata/locks-files/valid-provider-locks.hcl
- internal/getproviders/types.go
This PR introduces a new package `internal/depsfile` which is intended to eventually be responsible for reading and writing both files containing dependency lock information _and_ separate files containing development override settings. However, this initial set of commits introduces only the dependency lock file handling, and only for provider locks.
This PR is largely new, dead code that is not yet called from anywhere. A later PR will connect this with the existing provider installation codepaths so that the installer can react to the recorded version selections and can generate _new_ lock entries after installation for any new providers that were not previously locked.
The first commit, though, is actually addressing an existing quirk of `internal/getproviders`'s …
> internal/depsfile: A new package for reading and writing dependency metadata files

- terraform/eval_provider.go
- terraform/execute.go
- terraform/graph_walk_context.go
- terraform/node_data_destroy.go
- terraform/node_data_destroy_test.go
- terraform/node_data_refresh.go
- terraform/node_resource_refresh.go
- terraform/node_resource_refresh_test.go
Two commits, three notable changes:
- refactor the `Execute()` signature to talk a _pointer_ to a `walkOperation` (easier test writing, most commonly not required)
- add a `GetProvider` function that will (eventually) replace all of the `EvalGetProvider` nodes
- refactor `NodeDestroyableDataResourceInstance` and `NodeRefreshableDataResourceInstance`
Note: The "refactor" of `NodeRefreshableDataResourceInstance` is intentionally using what I might call the "last resort" or perhaps "minimal effort" refactor, where each step in the eval tree is replaced with a bunch of direct `Eval()`s. This is in part necessary to keep individual changes minimal, but in this case, another current project's stretch goal may end up removing `NodeRefreshable`*s altogether so I don't want to spend too much time …
> eval node removal: data nodes refresh & destroy

- e2e/e2e.go
Due to a recent update to OS X, this is necessary so that the correct working directory is saved, so that methods like Path() on the e2e binary will return the correct value. This is the same fix as in https://github.com/hashicorp/terraform/pull/26136, but used to apply to the failing test `TestPrimaryChdirOption`
> Update workDir of e2e binary to eval symlinks

- terraform/context_apply_test.go
- terraform/transform_module_expansion.go
One of the tenants of the graph transformations is that resource destroy
nodes can only be ordered relative to other resources, and can't be
referenced directly. This was broken by the module close node which
naively connected to all nodes within the module, creating cycles in some
cases when edges are reversed from CreateBeforeDestroy.
Fixes #26166
> don't connect module closers to destroy nodes

- terraform/context_apply_test.go
- terraform/transform_module_expansion.go
> Backport 26186

- states/remote/remote_test.go
- states/remote/state.go
- states/remote/state_test.go
In refactoring the `state push -force` code when implementing force push for the Terraform remote backend, a bug was introduced that meant that backends that don't implement the `EnableForcePush` method would still have their state validated, despite having `-force` set.
This commit fixes that, and adds test coverage such that there is a separate mockRemoteClient that has this method implemented. I had trouble thinking of a way to simplify the tests that doesn't make it needlessly complicated. The tests fail without the change in state.go.
Closes #25761
I nominate this change to go to v0.13 as well, as it is a bug fix for existing versions worthy of cherry-picking.
> Fix bug for force push for backends besides the remote backend

- backend/local/backend_plan_test.go
- command/format/diff.go
- command/format/diff_test.go
- command/format/state.go
- helper/experiment/experiment.go
When rendering a diff between current state and projected state, we only show resources and outputs which have changes. However, we show a full structural diff for these values, which includes all attributes and blocks for a changed resource or output. The result can be a very long diff, which makes it difficult to verify what the changed fields are.
This commit adds an experimental concise diff renderer, which suppresses most unchanged fields, only displaying the most relevant changes and some identifying context. This means:
- Always show all identifying attributes, initially defined as `id`, `name`, and `tags`, even if unchanged;
- Only show changed, added, or removed primitive values: `string`, `number`, or `bool`;
- Only show added or removed elements in unordered collections and …
> command: Add experimental concise diff renderer

- website/docs/state/remote.html.md
Some of our key partners were conspicuously missing from our remote state summary page.
> website: Add Google and Microsoft products to the summary for supported remote backends

- configs/provider_requirements.go
- configs/provider_requirements_test.go
A few users have recently been confused about the purpose of the `required_providers` objects, adding provider configuration parameters in addition to `version` and `source`. This previously did not cause an error so would result in a confusingly distant failure.
This commit adds a single diagnostic for any `required_providers` object which includes attributes other than `version` or `source`. Very open to suggestions on the diagnostic text!
Fixes #26160
> configs: Error on invalid required_providers attrs

- command/state_replace_provider_test.go
- go.mod
- go.sum
- vendor/github.com/mitchellh/cli/.travis.yml
- vendor/github.com/mitchellh/cli/Makefile
- vendor/github.com/mitchellh/cli/cli.go
- vendor/github.com/mitchellh/cli/go.mod
- vendor/github.com/mitchellh/cli/ui_mock.go
- vendor/modules.txt
Update tests to match the fix in mitchellh/cli#71, which aligns `MockUi` with `BasicUi` and allows newlines in user input.
We are not using the new `ErrorWriter`, added in mitchellh/cli#81, as it does not appear to interact correctly with `panicwrap`. All error output from CLI parsing will continue to appear on stdout, not stderr.
I'm upgrading this dependency to split out these changes from the Consul upgrade in #23601, hopefully for easier review.
> vendor: Upgrade mitchellh/cli

- backend/remote-state/consul/backend_test.go
- backend/remote-state/consul/client.go
- backend/remote-state/consul/client_test.go
When the path ends with / (e.g. `path = "tfstate/"), the lock
path used will contain two consecutive slashes (e.g. `tfstate//.lock`) which
Consul does not accept.
This change the lock path so it is sanitized to `tfstate/.lock`.
If the user has two different Terraform project, one with `path = "tfstate"` and
the other with `path = "tfstate/"`, the paths for the locks will be the same
which will be confusing as locking one project will lock both. I wish it were
possible to forbid ending slashes altogether but doing so would require all
users currently having an ending slash in the path to manually move their
Terraform state and would be a poor user experience.
Closes https://github.com/hashicorp/terraform/issues/15747
> Sanitize lock path for the Consul backend when it ends with a /

- command/format/diagnostic.go
- command/format/diff.go
- command/format/diff_test.go
- configs/experiments.go
- configs/named_values.go
- configs/testdata/valid-files/variables.tf
- configs/testdata/warning-files/variables-sensitive.tf
- experiments/experiment.go
- go.mod
- go.sum
- plans/changes.go
- plans/changes_src.go
- plans/dynamic_value.go
- plans/objchange/compatible.go
- states/instance_object.go
- terraform/context.go
- terraform/context_plan_test.go
- terraform/eval_apply.go
- terraform/eval_diff.go
- terraform/eval_for_each.go
- terraform/evaluate.go
- terraform/testdata/plan-ignore-changes/main.tf
- terraform/testdata/plan-variable-sensitivity/main.tf
- vendor/github.com/zclconf/go-cty/cty/json/marshal.go
- vendor/github.com/zclconf/go-cty/cty/marks.go
- vendor/github.com/zclconf/go-cty/cty/msgpack/marshal.go
- vendor/modules.txt
This PR allows `sensitive` to be added to a variable declaration, after enabling the `sensitive_variables` experiment:
```terraform
terraform {
experiments = [sensitive_variables]
}
variable "foo" {
sensitive = true
}
resource "some_resource" "bar" {
some_val = var.foo
}
```
At this current stage of the project, this works on some very basic configurations. When sensitivity is defined, when Terraform outputs the plan to the CLI, attributes using this variable will not be displayed:
```
+ resource "some_resource" "bar" {
+ id          = (known after apply)
+ some_val    = (sensitive)
}
```
This PR depends on changes in https://github.com/zclconf/go-cty -- at the moment, go.mod points to `master`, while this feature is in progress. Once the methods have stabilized and there is a new release …
> Add sensitive attribute to variables

- .circleci/config.yml
Despite installing Consul as part of the build, we haven't actually been running the Consul remote state backend tests in CI. This commit sets the environment variable needed to do this.
[I verified that tests are running on this branch](https://github.com/hashicorp/terraform/compare/alisdair/are-consul-tests-running), where I pushed an intentionally failing test (which passed CI), then enabled the tests (which failed CI), and finally removed the failing test (and CI is green).
> build: Enable Consul remote backend tests

- terraform/context_apply_test.go
- terraform/eval_diff.go
- terraform/node_resource_apply_instance.go
If the planed action changes from CreateThenDelete to DeleteThenCreate,
terraform will present an error like:
```
Error: Provider produced inconsistent final plan
When expanding the plan for null_resource.a to include new values learned so
far during apply, provider "registry.terraform.io/hashicorp/null" changed the
planned action from CreateThenDelete to DeleteThenCreate.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
This was being reported to providers as the message indicated, so wasn't
immediately visible to core developers, e.g.
https://github.com/terraform-providers/terraform-provider-aws/issues/15044
https://github.com/terraform-providers/terraform-provider-aws/issues/15048 …
> Use saved plan to determine CreateBeforeDestroy status

- terraform/context_apply_test.go
- terraform/eval_diff.go
- terraform/node_resource_apply_instance.go
> Backport 26192

- website/docs/commands/cli-config.html.markdown
In addition to the directories previously listed, Terraform looks in the CLI config directory (`$HOME/.terraform.d/plugins` on macOS/Linux/UNIX, and `%APPDATA%/terraform.d/plugins` on Windows). List this in the documentation for clarity.
We also add a note about the working directory relative "vendor" location, `./terraform.d/plugins`.
Fixes #25985
> website: Fix docs for implied provider FS mirrors

- command/apply.go
- command/apply_test.go
- command/console_test.go
- command/output.go
- command/output_test.go
- repl/format.go
- repl/format_test.go
- repl/session.go
- repl/session_test.go
Use a slightly modified value renderer from terraform-provider-testing to display values in the console REPL, as well as outputs from the apply and outputs subcommands.
[Derived from code in this repository, MIT licensed](https://github.com/apparentlymart/terraform-provider-testing), as [suggested by Martin](https://github.com/hashicorp/terraform/issues/26099#issuecomment-686012115). Hope this is what he meant! 
Note that this is technically a breaking change for the console subcommand, which would previously error if the user attempted to render an unknown value (such as an unset variable). This was marked as an unintentional side effect, with the goal being the new behaviour of rendering "(unknown)", which is why I changed the behaviour in this commit.
Fixes #26099. Arguably fixes …
> repl: Improved value renderer for console outputs

- backend/remote-state/consul/backend_test.go
- backend/remote-state/consul/client.go
- backend/remote-state/consul/client_test.go
The Consul KV store limits the size of the values in the KV store to 524288
bytes. Once the state reaches this limit Consul will refuse to save it. It is
currently possible to try to bypass this limitation by enable Gzip but the issue
will manifest itself later. This is particularly inconvenient as it is possible
for the state to reach this limit without changing the Terraform configuration
as datasources or computed attributes can suddenly return more data than they
used to. Several users already had issues with this.
To fix the problem once and for all we now split the payload in chunks of 524288
bytes when they are to large and store them separatly in the KV store. A small
JSON payload that references all the chunks so we can retrieve them later and
concatenate them to reconstruct the …
> Split the state in chunks when they outgrow the limit of Consul KV store

- configs/provisioner.go
- configs/testdata/warning-files/vendor_provisioners.tf
- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
- website/docs/provisioners/puppet.html.markdown
- website/docs/provisioners/salt-masterless.html.md
This notice follows the [recent announcement](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-3/13997) that the Chef, Habitat, Puppet, and Salt-masterless provisioners are deprecated and will be removed in future version of Terraform.
> Deprecate vendor (3rd party) provisioners

- go.mod
- go.sum
- vendor/github.com/apparentlymart/go-userdirs/userdirs/app_stub.go
- vendor/github.com/apparentlymart/go-userdirs/userdirs/app_unix.go
- vendor/modules.txt
Fixes #26175, I will also backport this update to the v0.13 branch.
> vendor: upgrade go-userdirs library to fix openBSD crash

- terraform/context_apply_test.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/transform_destroy_cbd.go
- terraform/transform_destroy_edge.go
When destroying an instance which was forced to be `CreateBeforeDestroy` from downstream consumers, we were inadvertently preferring the config value over the state value for `CreateBeforeDestroy`. The `CreateBeforeDestroyOverride` was not useful in this case, because a destroy node does not have the same descendants as the plan node, and we cannot check for a forced `CreateBeforeDestroy` in the same manner, so we need to trust the value from state.
The last commit is extra cleanup of some unnecessary interfaces, and is not going to be part of the backport candidate.
This fixes the cycle in #26226, and converts it into a duplicate of #25631.
> always check the CreateBeforeDestroy value from state

- terraform/eval_variable.go
- terraform/node_module_variable.go
- terraform/node_root_variable.go
- terraform/node_root_variable_test.go
EvalModuleCallArguments is now a method on nodeModuleVariable, it's only
caller, and the other functions have been replaces with straight through
code (or in the case of evalVariableValidations, a standalone function).
I was unable to add tests for nodeModuleVariable.Execute, which requires
fixtures that aren't part of the MockEvalContext (a scope.evalContext is
one); it's not ideal but that function should be well covered by the
context tests so I chose to leave it as-is.
Finally, I removed the unused function hclTypeName. Deleting code is
fun!
> terraform: refactor nodeModuleVariable and NodeRootVariable EvalTree()s

- terraform/context_apply_test.go
- terraform/evaluate.go
While this was easier to spot during plan, it is also possible to
evaluate resources with 0 instances during apply as well.
This doesn't effect the failure when scaling CBD instances, it only
changes the fact that the inconsistent value is no longer unknown.
Fixes #26252
> allow evaluation of 0 instances during apply

- website/docs/internals/credentials-helpers.html.md
For a credentials helper plugin to be useful with Terraform 0.13+, we need to cope with the case of having no credentials for a host without this being an error. This is to allow the public Terraform Registry to be accessed without supplying a token.
The way to implement this is to respond to queries for credentials for a host which has no credentials stored with an empty object and a success exit code. This contradicts the previous documentation, which calls for an error response in this case.
See #25938.
> website: Credentials helper response for no creds

- command/login.go
- command/login_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/terraform-svchost/LICENSE
- vendor/github.com/hashicorp/terraform-svchost/disco/host.go
- vendor/github.com/hashicorp/terraform-svchost/disco/oauth_client.go
- vendor/modules.txt
Support was previously added in terraform_svchost (https://github.com/hashicorp/terraform-svchost/pull/5)
This PR pulls in that version of `terraform_svchost` and adds support to `terraform` to include the scope(s) in the URL generated by `terraform login [hostname]`
Fixes #25354
> Add support for scopes to terraform login

- configs/module_call.go
- configs/named_values.go
- configs/resource.go
- configs/testdata/warning-files/redundant_interp.tf
Extend the deprecation for interpolation-only expressions to include module calls, data sources, outputs, and locals.
This PR is targeting the 0.14.0 release. If merged, I'm not sure if it should be cherry-picked to 0.13.x or not. Thoughts?
Fixes #25430, fixes #25828, supersedes #25465.
> configs: More interpolation-only expr deprecations

- codecov.yml
While we like codecov, and the coverage goals, we've frequently ignored
the failures for various reasons. These have confused community members
submitting PRs and it can be confusing to look at a list of merged PRs
with the big X indicating failed checks ("confusing" isn't really a
problem, but if there were actually a bad merge, it could be hard to
find which in a list of commits actually had an important failure).
Fixes a mild inconvenience.
> build: put codecov in informational mode

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- command/e2etest/automation_test.go
- command/e2etest/primary_test.go
- command/plan_test.go
- command/testdata/show-json/basic-create/output.json
- command/testdata/show-json/basic-delete/terraform.tfstate
- command/testdata/show-json/basic-update/terraform.tfstate
- command/testdata/show-json/modules/output.json
- command/testdata/show-json/multi-resource-update/output.json
- helper/resource/testing_config.go
- plans/plan.go
- terraform/context.go
- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/context_test.go
- terraform/eval_context.go
- terraform/eval_context_builtin.go
- terraform/eval_context_mock.go
- terraform/eval_count.go
- terraform/eval_state.go
- terraform/evaluate.go
- terraform/graph_walk_context.go
- terraform/node_resource_plan_instance.go
- terraform/testdata/apply-destroy-module-with-attrs/child/main.tf
- terraform/testdata/apply-destroy-module-with-attrs/main.tf
This removes the separate `Refresh` operation that happens during planning, having each resource instance refresh "just in time" during the plan walk. The refresh walk has numerous problems, mostly stemming from the graph being generated by a mix of the state for managed resources, the configuration for temporary values, and a combination of configuration and state for data sources. This can lead to incongruities during refresh that cannot be resolved, often requiring the use of `plan -refresh=false` in order to apply some configurations. We also skip the problem of data sources reading "stale" state that will be updated during apply, by having data sources evaluated during plan where we have all the change information available.
Merging of refresh into planning is primarily accomplished …
> Move resource refreshing into plan

- terraform/context_plan_test.go
- terraform/testdata/plan-variable-sensitivity-module/child/main.tf
- terraform/testdata/plan-variable-sensitivity-module/main.tf
Two commits:
- 9e340ab: Extend the existing sensitive variable plan test, to verify that attributes using sensitive values have appropriate path value marks stored. This is the best way I can think of to test that sensitivity is being preserved for plan outputs, short of an end-to-end test.
- e1a41da: Add a test showing that sensitive variable values can be used as module input variables, while preserving sensitivity. Uses the same approach as above to verify this.
Note: the overall diff is really confusing. Thanks git! I'd recommend looking at each commit in turn for a clearer picture on what's changing.
> Extend sensitive variable plan tests

- terraform/context_plan_test.go
- terraform/eval_read_data_plan.go
- terraform/node_resource_plan_instance.go
This only changes the refreshed state stored in the plan file. Since the
change is stored in the plan, the applied result would be the same, but
we should still store the refreshed data in the plan file for tools that
consume the plan file.
This will also be needed in order to implement a new refresh command
based on the plan itself.
> save read data in the refresh state during plan

- terraform/context_plan_test.go
- terraform/transform_reference.go
Treat any reference from a data source to a managed resource as a
dependency on the entire resource. While a resource's
attribute may be statically resolvable from the configuration, if the
user added a reference to that resource, it stands to reason that the
user intended there to be a dependency which we need to wait on.
This is an extension of an implicit behavior that existed previously in
Terraform, but was lost in the 0.13 release. That behavior was emergent
from the fact that the Refresh walk did not process the configuration
for managed resources, so any new resources in the config would be
evaluated as entirely unknown during Refresh, even if some attributes
were statically resolvable at that point.
This new implementation restores the old behavior, and extends it to
updates and …
> delay data source reads with pending resource ref

- backend/local/backend_refresh_test.go
- backend/local/testdata/refresh-var-unset/main.tf
- command/command_test.go
- command/testdata/show-json/basic-create/output.json
- command/testdata/show-json/basic-delete/terraform.tfstate
- command/testdata/show-json/basic-update/terraform.tfstate
- command/testdata/show-json/modules/output.json
- command/testdata/show-json/multi-resource-update/output.json
- terraform/context.go
- terraform/context_apply_test.go
- terraform/context_refresh_test.go
- terraform/eval_state.go
- terraform/graph_builder_plan.go
- terraform/node_output.go
- terraform/node_resource_plan.go
- terraform/node_resource_plan_instance.go
- terraform/testdata/apply-output-depends-on/main.tf
- terraform/testdata/refresh-data-count/refresh-data-count.tf
- terraform/testdata/refresh-module-input-computed-output/child/main.tf
- terraform/testdata/refresh-module-input-computed-output/main.tf
- terraform/testdata/refresh-schema-upgrade/main.tf
Since all resources are refreshed during plan now, we can use the state generated by plan for the purpose of refreshing. The refresh step has been removed from the `plan` command, and this changes the refresh command to use the plan output rather than it's own unique graph.
The majority of this change set is fixing refresh tests that were incorrect, had incomplete fixtures, or no longer make sense. The removal of the old Refresh code will come in another PR to reduce the size of the diffs for review.
> Replace internal Refresh command with Plan

- command/testdata/providers-schema/required/output.json
- command/testdata/providers-schema/required/provider.tf
- configs/config.go
- configs/config_test.go
- configs/testdata/valid-files/providers-explicit-implied.tf
The providers schema command is using the `Config.ProviderTypes` method, which had not been kept up to date with the changes to provider requirements detection made in `Config.ProviderRequirements`. This resulted in any currently-unused providers being omitted from the output.
This commit changes the `ProviderTypes` method to use the same underlying logic as `ProviderRequirements`, which ensures that `required_providers` blocks are taken into account.
Includes an integration test case to verify that this fixes the provider schemas command bug.
Fixes #26306. Diff [best viewed ignoring whitespace](https://github.com/hashicorp/terraform/pull/26318/files?diff=unified&w=1), due to the new nil check if statement.
> command: Providers schema shows required_providers

- configs/compat_shim.go
- configs/testdata/warning-files/redundant_interp.tf
Previous deprecations only included direct assignment of template-only expressions to arguments. That is, this was not deprecated:
```hcl
locals {
foo = ["${var.foo}"]
}
```
This commit uses `hclsyntax.VisitAll` to detect and show deprecations for all template-only expressions, no matter how deep they are in a given expression.
Fixes #26331. Should be back-ported to 0.13 if merged, to go along with #26105.
> configs: Deprecate nested redundant interpolations

- configs/provisioner.go
- configs/testdata/warning-files/vendor_provisioners.tf
- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
- website/docs/provisioners/puppet.html.markdown
- website/docs/provisioners/salt-masterless.html.md
This cherry-picks https://github.com/hashicorp/terraform/pull/26203 to v0.13 -- which means that deprecation notice didn't actually get released in 0.13.3, so the docs here have been amended to 0.13.4. I'll also update master so that this deprecation notice doesn't get mangled in 0.14.
> Deprecate vendor provisioners in 0.13

- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
- website/docs/provisioners/puppet.html.markdown
- website/docs/provisioners/salt-masterless.html.md
This updates the provisioner docs to the (what will be) correct version the deprecation notice appears.
> docs: Vendor provisioner deprecation version

- terraform/evaluate_test.go
This adds a test for GetInputVariable, and includes a variable with a "sensitive" attribute in configuration, to test that that value is marked as sensitive.
> tests: Add test for GetInputVariable, with sensitive config

- terraform/context_refresh_test.go
- terraform/eval_state.go
- terraform/node_resource_plan_instance.go
This evaluation was required when refresh ran in a separate walk and
managed resources were only partly handled by configuration. Now that we
have the correct dependency information available when refreshing
configured resources, we can update their state accordingly. Since
orphaned resources are not refreshed, they can retain their stored
dependencies for correct ordering.
This also prevents users from introducing cycles with nodes they can't
"see", since only orphaned nodes will retain their stored dependencies,
and the remaining nodes will be updated according to the configuration.
Fixes #25611
> we no longer need EvalRefreshDependencies

- backend/local/backend_local.go
- backend/local/backend_plan_test.go
- backend/local/backend_refresh.go
- terraform/context.go
- terraform/context_plan_test.go
- terraform/graph_builder_plan.go
- terraform/node_resource_plan.go
- terraform/node_resource_plan_instance.go
Recreate the behavior of `-refresh=false` in plan. While this would previously skip some refreshing of data sources, this is now limited specifically to managed resources.
Since there is no longer a separate refresh walk, we need to thread the `-refresh=false` option all the way to the instance node for planning. We reverse the bool and use `skipRefresh` in core to prevent any unintended changes from the default behavior.
> Re-implement -refresh=false

- terraform/context_refresh_test.go
- terraform/eval_state.go
- terraform/node_resource_plan_instance.go
While `create_before_destroy` is stored in the instance state, the status would only be updated when a change to the resource was applied. This meant that if a resource was incorrectly created with the wrong option, it would require a change to the resource itself to fix, which may not be possible with all resources.
This change updates the stored `create_before_destroy` value while the resource is being refreshed.
Fixes #25473
> Update create_before_destroy in state during refresh

- terraform/context_refresh_test.go
- terraform/eval_state.go
- terraform/node_resource_refresh.go
This is a 0.13 backport of #26343
Update the `create_before_destroy` status in state during refresh, in order to reflect the current configuration.
It's not quite as complete as the 0.14 version, as we can't update the forced `create_before_destroy` behavior due to the refresh walk not having that information, but it still allows a misconfigured resource to be manually updated in state with a refresh.
> 0.13 backport 26343

- command/format/diff.go
- command/format/diff_test.go
- providers/provider.go
- states/instance_object.go
- states/instance_object_src.go
- states/state_deepcopy.go
- states/state_test.go
- states/statefile/version4.go
- states/statefile/version4_test.go
- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/eval_diff.go
- terraform/eval_refresh.go
When marking a variable value as sensitive, we want to be able to track that value's sensitivity when it changes, or when it is destroyed. Without having a sense of sensitivity of the "prior" value, this would mean that a `terraform plan` with a changed value to a non-sensitive value would expose the prior sensitive value, or any `terraform destroy` would expose the sensitive value.
The commits attached to this PR have a few commits dedicated to tests, but hopefully I've squashed down the commits into chunks that are more understandable.
The commit implementing the serialization strategy is https://github.com/hashicorp/terraform/pull/26338/commits/3049c29fcdcd3dd354c2cc42bf681506951a92e7, and the areas of interest are likely to be the states/instance_object.go, …
> Store sensitive attribute paths in state

- command/taint.go
- command/taint_test.go
- command/testdata/taint-check-required-version/main.tf
Despite not requiring the configuration for any other reason, the taint subcommand should not execute if the required_version constraints cannot be met. Doing so can result in an undesirable state file upgrade.
Fixes #26325. Fixes #23049.
Question for reviewers: it feels to me like there ought to be a neater way of loading the config to check the constraints are met. Can you think of one? 🙏
> command: Taint should respect required_version

- command/providers_mirror.go
- internal/depsfile/locks.go
- internal/depsfile/locks_file.go
- internal/depsfile/locks_file_test.go
- internal/depsfile/testdata/locks-files/invalid-versions.hcl
- internal/depsfile/testdata/locks-files/valid-provider-locks.hcl
- internal/getproviders/filesystem_mirror_source_test.go
- internal/getproviders/hash.go
- internal/getproviders/hash_test.go
- internal/getproviders/http_mirror_source.go
- internal/getproviders/http_mirror_source_test.go
- internal/getproviders/mock_source.go
- internal/getproviders/package_authentication.go
- internal/getproviders/package_authentication_test.go
- internal/getproviders/registry_client.go
- internal/getproviders/registry_client_test.go
- internal/getproviders/registry_source_test.go
- internal/getproviders/types.go
- internal/providercache/cached_provider.go
- internal/providercache/cached_provider_test.go
- internal/providercache/installer.go
There's a few different things going on here because I'm trying to quickly drive a thread all the way through to an MVP before going back to refine. Unfortunately that means this diff will be quite hard to read as a whole, and so I'd recommend going commit-by-commit for this one.
In earlier work I introduced the `internal/depsfile` package to represent the new lock file format. While investigating the next step I found that maintaining a separate set of locked hashes per platform isn't really practical because our different installation methods each have their own constraints that prevent us from reliably distinguishing which hash belongs to which platform.
As a compromise then, the lock file will now just record an undifferentiated set of hashes across all platforms, and will consider …
> Further work towards provider dependency pinning MVP

- command/format/diff.go
- command/format/diff_test.go
This PR adds a warning that will display in the diff output if a value is changing its sensitivity. It is conservative, in that if the sensitivity is changing (either to _or_ from sensitive) it will not display the value, but will show a `(sensitive)`.
Some examples of this in action:
Changing from one sensitive value to another sensitive value, the `(sensitive)` remains in place and no warning is displayed:
Changing from a sensitive value to a non sensitive value, a warning is displayed in the UI:
Same thing, but showing this appearing more than once in a plan:
When a value will no longer be sensitive, this warning displays:
This PR adds coverage for this specialized diff between all primitive types, as more work is needed (both in `diff.go` but also more widely in Terraform) on complex …
> Warnings and specialized diffs when switching between sensitive values

- command/format/diff.go
Changes sensitivity warning color output. Screenshot:
> Change sensitivity warning to be yellow only on 'Warning'

- command/format/diff_test.go
- plans/objchange/lcs.go
- plans/objchange/lcs_test.go
Adds support for specialized diffs with lists. Because indices aren't "special" in how they identify members of the list, no changes are made to suppress previously sensitive values/values becoming sensitive at a particular index (see the tests for output in various cases). A change was necessary to `LongestCommonSubsequence` to become mark-aware, and this chooses to say that values are not equal if they are equal on value, but not on whether they are marked.
> Support list diffs with sensitivity

- tools/terraform-bundle/e2etest/package_test.go
- tools/terraform-bundle/package.go
Hi,
We are using the Terraform bundle tool, and it seems broken with custom plugins (v0.13.3)
Command:
`terraform-bundle package -plugin-dir ./custom-plugins ./terraform-bundle.hcl`
Inspect:
```
Archive:  terraform_0.13.3-bundle2020092409_linux_amd64.zip
Length      Date    Time    Name
---------  ---------- -----   ----
36373356  09-24-2020 09:19   plugins/github.com/carlpett/sops/0.5.1/linux_amd64/terraform-provider-sops
26763888  09-24-2020 09:19   plugins/github.com/dihedron/jenkins/0.0.0-1abf850/linux_amd64/terraform-provider-jenkins
31781827  09-24-2020 09:19   plugins/github.com/mrparkers/keycloak/1.20.0/linux_amd64/terraform-provider-keycloak
158158848  09-24-2020 09:19   plugins/registry.terraform.io/hashicorp/aws/2.70.0/linux_amd64/terraform-provider-aws_v2.70.0_x4
20427104 …
```
> Fix terraform bundle broken with custom plugins

- command/fmt.go
- command/fmt_test.go
- command/testdata/fmt/general_in.tf
- command/testdata/fmt/general_out.tf
- command/testdata/fmt/variable_type_in.tf
- command/testdata/fmt/variable_type_out.tf
In Terraform 0.11 and earlier, the `terraform fmt` subcommand was very opinionated in the interests of consistency. While that remains its goal (similar to `go fmt` in the Go community), for pragmatic reasons Terraform 0.12 significantly reduced the number of formatting behaviors in the `fmt` sub command. We've held off on introducing 0.12-and-later-flavored cleanups out of concern it would make it harder to maintain modules that are cross-compatible with both Terraform 0.11 and 0.12, but with this aimed to land in 0.14 -- two major releases after 0.12 -- our new goal is to help those who find older Terraform language examples have them updated to the more modern idiom.
More rules may follow later, now that the implementation is set up to allow modifications to tokens as well as …
> command/fmt: Restore some more-opinionated behaviors

- command/command_test.go
- command/taint.go
- command/taint_test.go
- command/untaint.go
- command/untaint_test.go
Fixes #22157. Removes DefaultStateFilepath as the default for the
-state flag, allowing workspaces to be used properly.
> Fix taint and untaint commands when in a workspace

- website/docs/import/index.html.md
- website/docs/import/usage.html.md
In feedback for the [Terraform import tutorial](https://learn.hashicorp.com/tutorials/terraform/state-import) on HashiCorp Learn, @sudomateo [mentioned](https://github.com/hashicorp/learn/pull/1615#issuecomment-642151768) that the tutorial doesn't talk about the limitations of using Terraform import with a remote backend. The docs don't mention this limitation either.
This PR adds a note mentioning this limitation, and also updates the references to the import tutorial. A separate PR will update the tutorial on Learn.
> website: Terraform import and remote backends

- command/fmt_test.go
- command/plugins_lock.go
- command/plugins_lock_test.go
This PR removes some unused code. The new provider installer is responsible for writing the lockfile, so I've removed the older Write() method.
This has an unfortunate side effect: now that I've removed the `Write` portion, the test as written is pretty pointless, and the provider installer's lock file test coverage is also lacking. I won't be offended if we decide not to merge this as-is, but I don't have the time or spoons to add (needed) test coverage at this moment. 
Bonus commit: `fmt` tests were failing on OSX because it is haunted (and `/tmp` is a symlink)
> command: remove unused method on pluginSHA256LockFile

- CODEOWNERS
With `0.13.4` targeted for release this week, I thought it wise to be consistent with the status of built-in tool-specific code. This small change makes clear we are no longer looking for maintainers for the tool specific provisioners.
> Updating CODEOWNERS with our deprecated status for tool-specific provisioners

- terraform/context_plan_test.go
- terraform/context_validate_test.go
- terraform/eval_diff.go
- terraform/eval_validate.go
- terraform/provider_mock.go
Ignore changes was intended to only ignore changes happening within the configuration, and should not be applied to values set by the provider. We were previously re-applying this to the planned value for compatibility, but intended to remove the patch in a major release version.
It also turned out that we should have been applying `ignore_changes` directly to the configuration, rather than the proposed value created for the plan. Doing this ensures that the configuration used for comparison internally, the proposed value, and the configuration passed to the provider all show the same starting data minus the ignored changes. Without this change, because providers are required to create their plan based on the proposed value, `AssertPlanValid` would always show errors when comparing the …
> Fix handling of ignore_changes

- backend/remote/backend_mock.go
- builtin/provisioners/puppet/resource_provisioner.go
- command/e2etest/unmanaged_test.go
- terraform/context.go
- terraform/context_apply_test.go
- terraform/eval_context_builtin.go
`go test -race ./...` now passes
> Fix race conditions

- backend/remote-state/pg/backend_state.go
- backend/remote-state/pg/backend_test.go
- backend/testing.go
Closes https://github.com/hashicorp/terraform/issues/23121
> Always have the default workspace in the pg backend

- website/docs/configuration/functions/templatefile.html.md
Use of dynamic templates in Terraform configurations via the `template_file` data source is now doubly unsupported, in that `terraform-provider-template` is deprecated. We therefore remove this sentence in the docs linking to it.
> docs: remove link to deprecated provider

- terraform/node_resource_abstract.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_abstract_instance_test.go
- terraform/node_resource_apply.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/node_resource_plan.go
* Split node_resource_abstract.go into two files, putting
`NodeAbstractResourceInstance` methods in their own file - it was getting
large enough to be tricky for (my) human eyeballs.
* un-exported the functions that were created as part of the EvalTree()
refactor; they did not need to be public.
* removed `dottedInstanceAddr`, which was unused.
> terraform: minor cleanup from EvalTree() refactor

- configs/testdata/invalid-files/variable-bad-sensitive.tf
Adds a test file for an incorrectly typed (non-boolean) sensitive value to ensure it errors. This behavior is caught/diags are added when the config is loaded, so all this PR does is adds a test file.
> Add test file for bad sensitive value

- website/docs/configuration/variables.html.md
This adds documentation for the `sensitive` argument for variable blocks. This PR also re-organizes the variable page to have an index of the argument sections, to make the page more navigable.
> docs: Docs for sensitive variables

- command/e2etest/init_test.go
- command/init.go
Simple fix for https://github.com/hashicorp/terraform/issues/26411
> Fix bad string match that was causing TestInitProviderNotFound to fail

- terraform/context_plan_test.go
- terraform/node_resource_plan_instance.go
The loading of the initial instance state was inadvertently skipped when
-refresh=false, causing all resources to appear to be missing from the
state during plan.
> always load instance state when -refresh=false

- command/format/diff.go
- command/format/diff_test.go
Considers wholly marked maps as well as map keys when considering sensitivity.
> Add format/diff coverage for maps with sensitivity

- terraform/context_plan_test.go
- terraform/transform_reference.go
If a data source refers to a indexed managed resource instance, we need to
re-target that reference to the containing resource for planning.  Since
data sources use the same mechanism as depends_on for managed resource
references, they can only refer to resources as a whole.
> data sources with indexed references to managed resources

- command/format/diff.go
- command/format/diff_test.go
- plans/objchange/compatible.go
- states/instance_object.go
- terraform/context_apply_test.go
- terraform/context_test.go
- terraform/eval_diff.go
Before this PR, using a sensitive value in a nested block would result in a panic. This adjusts `Encode` to unmark a value before processing `UnknownAsNull` and calls `AssertPlanValid` with all unmarked values for value-validation. There is also additional testing added to test blocks through apply, and adjusts compatibility testing to drop marks for such testing (as it is testing whether values are compatible). As far as printing the diff, we have a special behavior to obfuscate the whole nested block when either the old or new value is sensitive (see note).
**Note** : When a member of a set is marked, the set itself is marked, so we must consider all members of the set as sensitive. This results in _highly_ conservative behavior when a sensitive value is used in a nested block, but at …
> Support sensitivity within nested blocks

- addrs/provider_config_test.go
- backend/testing.go
- command/command_test.go
- command/format/diff_test.go
- command/format/state_test.go
- command/graph_test.go
- command/init_test.go
- command/jsonprovider/provider_test.go
- command/meta_backend_test.go
- command/state_mv_test.go
- command/state_rm_test.go
- command/taint_test.go
- command/untaint_test.go
- command/workspace_command_test.go
- configs/config_test.go
- configs/module_test.go
- internal/earlyconfig/config.go
- moduledeps/module.go
- moduledeps/module_test.go
- plans/plan_test.go
- providers/addressed_types_test.go
- states/statefile/write.go
- states/statemgr/testing.go
This PR _mostly_  includes test updates but I will summarize (and then comment on) "real" changes below. I've removed as many calls to `addrs.NewLegacyProvider` as possibly, leaving (I hope) only the load-bearing ones.
I needed to update tests that were using the older `terraform.State`s in the command package (to avoid winding through some shims which default to legacy providers - that's a future project). This led me on a small sidequest to refactor the testStateFileDefault helper function in command_test.go to take a states.State instead of terraform.State (which let me simplify a couple of tests). None of the test functionally (should have) changed and using the modern states is More Correct anyhow.
The final bit of fallout from the above came in the init tests: one test set a future …
> remove LegacyProvider

- lang/funcs/collection.go
- lang/funcs/collection_test.go
Fix for issue #26320 - this allows us to derive known values from partially known maps where we can, and may prevent unnecessary destroy/rebuild cycles during apply in some cases.
Based on @apparentlymart 's suggestions in the issue thread.
Most of this PR is changes to `primary_test.go` and `automation_test.go` as I have added a very basic regression test to the primary workflow. Happy to change or adjust this if you feel it would be cleaner/preferable to have a separate HCL file and test set for this.
> Issue 26320 - lookup(): only treat map as unknown if it is wholly unknown

- terraform/eval_diff.go
- terraform/eval_diff_test.go
- website/docs/configuration/resources.html.md
This change will allow specifying a `map["key"]` path in `ignore_changes` that may not exist in the config or the prior value. This allows users to prevent a single map element from changing to or from being unset.
This didn't work previously because the transformation always started off with the configuration, and would never encounter a key if it was not present in the configuration. We also couldn't retain the absence of a value, since the lookup wouldn't find the key in the prior value.
The following configuration will now prevent the "unwanted" value from showing up in the plan if it is not originally present in the prior state. 
```
resource "test_resource" "a" {
map = {
wanted = "value"
unwanted = "added after initial apply"
}
lifecycle = {
ignore_changes = [map["unwanted"]]
}
} …
```
> allow ignore_changes to reference any map key

- command/console_test.go
- command/testdata/variables/main.tf
- repl/format.go
- repl/format_test.go
Updates `terraform console` to show `(sensitive)` when a value is marked as sensitive.
> Obfuscate sensitive vals in console

- website/docs/configuration/resources.html.md
Just re-read the docs the ignore_changes update and saw a few typos
> [Documentation] Typo fixes

- backend/remote-state/azure/arm_client.go
- backend/remote-state/azure/helpers_test.go
This should fix an issue when using the metadata host to lookup the environments from.
> AzureRM backend: correctly lookup environment from metadata host

- website/docs/configuration/variables.html.md
Add note to docs about nested block behavior for sensitive variables, https://github.com/hashicorp/terraform/pull/26379
> Add sensitive variable docs for nested blocks

- command/format/diff.go
- command/format/diff_test.go
Now, heredoc in `terraform plan` uses `<<~` as heredoc start symbol.
```hcl
~ filter          = <<~EOT
metric.type="agent.googleapis.com/memory/percent_used" resource.type="gce_instance" metadata.user_labels."name"="instancename""
EOT
```
Because [HCL spec](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#template-expressions) says that `<<` and `<<-` are heredoc start symbol, I think it may be better to use `<<-` instead of `<<~`.
```hcl
~ filter          = <<-EOT
metric.type="agent.googleapis.com/memory/percent_used" resource.type="gce_instance" metadata.user_labels."name"="instancename""
EOT
```
> Use valid heredoc begin symbol in diff output.

- terraform/context_import_test.go
- terraform/node_module_variable.go
We do not currently need to evaluate module variables in order to
import a resource.
This will likely change once we can select the import provider
automatically, and have a more dynamic method for dispatching providers
to module instances. In the meantime we can avoid the evaluation for now
and prevent a certain class of import errors.
Fixes #26258 by rolling back #25890. Note the test from 25890 is not removed,
because other evaluation improvements in the meantime now prevent the
need to evaluate the variables in the first place.
> do not evaluate module variables during import

- terraform/context_eval_test.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_destroy_plan.go
- terraform/graph_builder_eval.go
- terraform/graph_builder_import.go
- terraform/graph_builder_plan.go
- terraform/node_module_variable.go
- terraform/node_output.go
- terraform/node_resource_destroy.go
- terraform/node_resource_destroy_deposed.go
- terraform/transform_config.go
- terraform/transform_reference.go
While turning off evaluation of variable during import was a temporary step in #26490 to avoid errors, further improvements would need to get those working again. During some auditing of the GraphNodeExecutable actions and graph building steps, it was found where the missing evaluation was skipped for outputs. These evaluations are are now re-enabled for future work.
We remove as many unnecessary Execute op filters as possible so as to not continue to miss nodes that should be added to the less viewed used graphs like eval, import and plan-destroy.
We also go through the graph builders themselves and re-order all the transformations to use the same relative ordering. While many of the transformations are commutative, using the same order ensures the same behavior between operations if the …
> Audit some graph building and GraphNodeExecutable

- terraform/evaluate.go
- terraform/evaluate_test.go
- website/docs/configuration/outputs.html.md
This change "marks" values related to outputs that have Sensitive set to true. Sensitivity will follow outputs used elsewhere in configuration:
```terraform
module "foo" {
source = "./mod"
}
resource "test_instance" "x" {
some_attribute = module.mod.a
}
output "a" {
value = "secret"
sensitive = true"
}
```
Locations where the sensitive output is used will be redacted in CLI output:
```sh
Terraform will perform the following actions:
+ resource "test_instance" "x" {
+ some_attribute    = (sensitive)
}
```
> Consider sensitivity when evaluating module outputs

- command/format/diff.go
- command/format/diff_test.go
If a value rendered for the diff is sensitive and results in replacement of the resource, we should render the standard "forces replacement" text after the "(sensitive)" value display.
> command: Fix missing force new for sensitive vars and blocks

- states/module.go
- states/sync.go
- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/eval_diff.go
- terraform/eval_variable.go
When sensitivity changes (but values do not) we still want to show an "Update" informational to the user, so we should have the `action` be Update in this (otherwise NoOp) scenario. However, when this happens, we should _not_ follow through with communicating with the provider and the following scenarios, because it is a no-op change from the provider's (value-only) perspective.
There are a few commits in here where I updated comments to reflect current state of the world (no EachMode) or simple typos. They are extraneous to this PR, but maybe it'll prevent some future "Fixed a typo" PRs.
> Update state when sensitivity changes

- backend/local/backend_plan_test.go
- backend/local/backend_refresh_test.go
- command/apply_test.go
- command/import_test.go
- command/plan_test.go
- terraform/context_apply_test.go
- terraform/context_fixtures_test.go
- terraform/context_import_test.go
- terraform/context_input_test.go
- terraform/context_plan_test.go
- terraform/context_refresh_test.go
- terraform/context_test.go
- terraform/context_validate_test.go
- terraform/eval_diff.go
- terraform/provider_mock.go
- terraform/provisioner_mock.go
- terraform/terraform_test.go
- terraform/testdata/apply-multi-depose-create-before-destroy/main.tf
- terraform/testdata/apply-provider-computed/main.tf
- terraform/testdata/apply-unknown/main.tf
- terraform/testdata/validate-computed-var/main.tf
- terraform/testdata/validate-module-pc-vars/child/main.tf
- terraform/testdata/validate-module-pc-vars/main.tf
Test cleanup to remove legacy types and functions from the mock provider and provisioner. Fixes many tests to ensure that they are actually testing something. This moves us much closer to removing the legacy types altogether.
A lot of the churn here is because the mock provider's default behavior has been simplified and made consistent, so we need to make sure the schemas, state, and desired results all match. The most noticeable thing here was the mock resource `type` attribute, which was sometimes used, planned with a known computed value which isn't the typical provider behavior, and missing from many resulting states.
> Cleanup and remove legacy types from test mocks

- go.mod
- go.sum
closes #26516
refs https://github.com/apparentlymart/go-versions/pull/1
> fix: update go-versions with improved error handling

- configs/experiments.go
- configs/named_values.go
- configs/testdata/invalid-modules/object-optional-attrs-experiment/object-optional-attrs-experiment.tf
- configs/testdata/warning-files/object-optional-attrs-experiment.tf
- experiments/experiment.go
- internal/typeexpr/doc.go
- internal/typeexpr/get_type.go
- internal/typeexpr/public.go
- internal/typeexpr/type_type.go
- terraform/context_apply_test.go
- website/docs/configuration/types.html.md
This builds on an experimental feature in the underlying `cty` library which allows marking specific attribtues of an object type constraint as optional, which in turn modifies how the `cty` conversion package handles missing attributes in a source value: it will silently substitute a null value of the appropriate type rather than returning an error. This is similar to the ability to silently convert a bool `true` into the string `"true"`: rather than returning an error, `cty` will just silently insert a suitably-typed `null` value as the value of each optional attribute that isn't in the input object.
This new language feature aims to address the following two common situations:
* If a module author needs to extend an object type constraint with a new attribute in order to support a new …
> configs: Experimental support for optional object type attributes

- command/testdata/show-json/basic-update/output.json
- command/testdata/show-json/basic-update/terraform.tfstate
- command/testdata/show-json/multi-resource-update/output.json
- command/testdata/show-json/multi-resource-update/terraform.tfstate
- terraform/context.go
- terraform/context_apply_test.go
- terraform/graph_builder_apply.go
- terraform/graph_builder_apply_test.go
- terraform/graph_builder_destroy_plan.go
- terraform/graph_builder_plan_test.go
- terraform/node_output.go
- terraform/node_resource_apply.go
- terraform/transform_output.go
- terraform/transform_targets_test.go
We record output changes in the plan, but don't currently use them for anything other than display. If we have a wholly known output value stored in the plan, we should prefer that for apply in order to ensure consistency with the planned values. This also avoids cases where evaluation during apply cannot happen correctly, like when all resources are being removed or we are executing a destroy.
Recording all change in the state also lets us remove the need for the special destroy root output transformer. That was always a stop-gap until we could plan the outputs, since it was the last usage of the apply graph `Destroy` flag.
`Before` values are now stored correctly in the plan changes too, and the change `Action` is updated to use `NoOp` when there is no change,  and `Update` when the …
> Use recorded changes for outputs and plan root output removals

- website/layouts/guides.erb
- website/upgrade-guides/0-14.html.markdown
The upgrade requirements for this release are considerably more modest than for Terraform v0.13, so this time we just have some notes about a few changes in behavior that may be impactful to some users. The main focus is on how the dependency pinning behavior treats some different usage scenarios, but this also includes information on how to opt out of the concise diff behavior and some information on why Terraform v0.14 is now likely to hide more values as `(sensitive value)` in the new release.
This first pass is intended to be included as part of a forthcoming beta testers' guide as we begin the v0.14 beta testing period. We will make further changes to this upgrade guide based on feedback from those who participate in the beta process.
Note that this upgrade guide is not intended as …
> website: First draft of v0.14 upgrade guide

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- command/show.go
- helper/resource/testing_config.go
- plans/changes.go
With the output changes now recorded in the plan, we can drop the workaround for synthesizing the changes based on the plan and prior states. This also will show more possible changes in the outputs themselves, like output `Create` actions:
```
Changes to Outputs:
+ output_value = "new_value"
```
And changes to only the sensitivity in the configuration:
```
Changes to Outputs:
```
> Render output changes based on the plan

- Dockerfile
Removing this was a mistake! 
We use two dockerfiles; the one in this PR is used to create the "full" docker image, which includes the source code. The _other_ dockerfile which I removed in [an earlier PR](https://github.com/hashicorp/terraform/pull/26484) is being moved to terraform-releases in https://github.com/hashicorp/terraform-releases/pull/20.
> build: revert Dockerfile removal

- terraform/context_validate_test.go
- terraform/testdata/validate-required-provider-config/main.tf
- terraform/transform_provider.go
The ProviderConfigTransformer was using only the provider FQN to attach
a provider configuration to the provider, but what it needs to do is
find the local name for the given provider FQN (which may not match the
type name) and use that when searching for matching provider
configuration.
Fixes #26556
> terraform: fix ProviderConfigTransformer [v0.13 backport]

- terraform/context_validate_test.go
- terraform/testdata/validate-required-provider-config/main.tf
- terraform/transform_provider.go
The ProviderConfigTransformer was using only the provider FQN to attach
a provider configuration to the provider, but what it needs to do is
find the local name for the given provider FQN (which may not match the
type name) and use that when searching for matching provider
configuration.
Fixes #26556
This will also be backported to the v0.13 branch.
> terraform: fix ProviderConfigTransformer

- main.go
Spotted while reading source code, a small fix where there's an error check against an error that wasn't saved.
> Fix un-saved error on chdir

- website/docs/commands/plan.html.markdown
Ran into an issue requiring `-var=foo=bar` over `-var 'foo=bar'`.  
Without the `=` the generic response came back:
```
Usage: terraform plan [options] [DIR]
Generates an execution plan for Terraform.
This execution plan can be reviewed...
```
Terraform `0.12.2`
> Terraform Plan CLI Vars Format

- terraform/node_module_variable_test.go
A few tests were inadvertently renamed, causing them to be be skipped.
For some reason this is not caught by the `vet` pass that happens during
normal testing.
> re-enable and fix module variable tests

- command/e2etest/init_test.go
- command/init.go
- command/init_test.go
- command/meta_providers.go
- command/testdata/init-legacy-provider-cache/.terraform/plugins/example.com/test/b/1.1.0/os_arch/terraform-provider-b
- command/testdata/init-legacy-provider-cache/.terraform/plugins/registry.terraform.io/hashicorp/c/2.0.0/os_arch/terraform-provider-c
- command/testdata/init-legacy-provider-cache/versions.tf
- website/upgrade-guides/0-14.html.markdown
Terraform v0.10 introduced `.terraform/plugins` as a cache directory for plugins installed automatically over the network. Terraform v0.13 later reorganized the directory structure inside but retained its purpose as a cache for the provider plugins used by the current configuration.
The local cache used to also serve as an implicit record of specifically which packages were selected in a particular working directory, with the intent that a second run of `terraform init` would always select the same packages again. That meant that in some sense it behaved a bit like a local filesystem mirror directory, even though that wasn't its intended purpose.
Due to some unfortunate miscommunications, somewhere a long the line we published some documentation that _recommended_ using the cache …
> command: new cache directory .terraform/providers for providers

- command/cliconfig/config_unix.go
- command/cliconfig/config_windows.go
- command/cliconfig/credentials.go
- internal/depsfile/locks_file.go
- internal/replacefile/doc.go
- internal/replacefile/replacefile_unix.go
- internal/replacefile/replacefile_windows.go
- internal/replacefile/writefile.go
In this case, "atomic" means that there will be no situation where the file contains only part of the newContent data, and therefore other software monitoring the `.terraform.lock.hcl` file for changes (using a mechanism like inotify) won't risk encountering a truncated file.
It does _not_ mean that there can't be existing filehandles open against the old version of the file. On Windows systems the write will fail in that case, but on Unix systems the write will typically succeed but leave the existing filehandles still pointing at the old version of the file. They'll need to reopen the file in order to see the new content.
This atomic update was already documented as a guarantee in the `depsfile` package documentation, so this change is intended to make the implementation actually match …
> internal/depsfile: Update the dependency lock file atomically

- configs/configschema/decoder_spec.go
- lang/blocktoattr/fixup_bench_test.go
`DecoderSpec` is called many times throughout terraform, and in the process of checking for BlocktoAttr fixups, it may be called n^2 times recursively. While this is not normally a problem for most common resources, with deeply nested schemas this can cause serious performance issues. 
Because of the delicate nature of the BlockToAttr fixup code in dealing with legacy provider schemas, it would be preferable to leave that code as-is for he time being if at all possible. Rather than refactor the BlockToAttr code ((if that's possible at all without subtle breaking changes), we have an easy performance gain here by caching the `Block.DecoderSpec` calls.
The benchmark shown here produced the following results:
```
name               old time/op    new time/op    delta
FixUpBlockAttrs-4 …
```
> Memoize Block.DecoderSpec

- configs/configschema/decoder_spec.go
- lang/blocktoattr/fixup_bench_test.go
> 0.13 backport of 26577

- go.mod
- go.sum
Update hcl to v2.7.0 and go-cty to latest commit. These changes support the sensitive variable work in 0.14.
Fixes #25326
* json: There is a new function `ParseWithStartPos`, which allows overriding the starting position for parsing in case the given JSON bytes are a fragment of a larger document, such as might happen when decoding with `encoding/json` into a `json.RawMessage`. ([#389](https://github.com/hashicorp/hcl/pull/389))
* json: There is a new function `ParseExpression`, which allows parsing a JSON string directly in expression mode, whereas previously it was only possible to parse a JSON string in body mode. ([#381](https://github.com/hashicorp/hcl/pull/381))
* hclwrite: `Block` type now supports `SetType` and `SetLabels`, allowing surgical changes to the type and labels of an …
> Update hcl and go-cty dependencies

- plans/objchange/objchange.go
- plans/objchange/objchange_test.go
When generating set elements for comparison for a `ProposedNewObject`, we want to use the most accurate type possible for lists and maps within the sets. This ensures distinct values within lists and maps are compared correctly, while also still allowing nested lists and maps containing dynamic types in sets.
Based on #26133
> More precise handling of lists and maps within sets for ProposedNewObject

- command/apply.go
- command/cliconfig/provider_installation.go
- command/cliconfig/provider_installation_test.go
- command/cliconfig/testdata/provider-installation
- command/cliconfig/testdata/provider-installation.json
- command/e2etest/provider_dev_test.go
- command/e2etest/testdata/provider-dev-override/pkgdir/.exists
- command/e2etest/testdata/provider-dev-override/provider-dev-override.tf
- command/init.go
- command/meta.go
- command/meta_providers.go
- command/validate.go
- commands.go
- e2e/e2e.go
- main.go
- provider_source.go
- website/docs/commands/cli-config.html.markdown
For normal provider installation we want to associate each provider with a selected version number and find a suitable package for that version that conforms to the official hashes for that release. Those requirements are very onerous for a provider developer currently testing a not-yet-released build, though.
To allow for that case this new CLI configuration feature allows overriding specific providers to refer to give local filesystem directories. Any provider overridden in this way is not subject to the usual restrictions about selected versions or checksum conformance, and activating an override won't cause any changes to the selections recorded in the lock file because it's intended to be a temporary setting for one developer only. In the typical case of just working with a single …
> command/cliconfig: Allow development overrides for providers

- command/apply.go
- command/cliconfig/provider_installation.go
- command/cliconfig/provider_installation_test.go
- command/cliconfig/testdata/provider-installation
- command/cliconfig/testdata/provider-installation.json
- command/e2etest/provider_dev_test.go
- command/e2etest/testdata/provider-dev-override/pkgdir/.exists
- command/e2etest/testdata/provider-dev-override/provider-dev-override.tf
- command/init.go
- command/meta.go
- command/meta_providers.go
- command/validate.go
- commands.go
- e2e/e2e.go
- main.go
- provider_source.go
- website/docs/commands/cli-config.html.markdown
This is a v0.14 backport of #26605. That change was intentionally a "shallow" design in order to reduce the risk for this backport, which I'd like to make to avoid the lock file creating even more friction for provider developers.
> v0.14 backport: Allow development overrides for providers

- plugin/grpc_provider.go
- plugin/grpc_provider_test.go
Core was previously ignoring JSON-encoded dynamic values, but these are
technically supported, so we must either error or accept the value.
Since we already have the decoder for Json state, it's minimal effort to
support this on all plugin methods too.
This change also gives providers an easy way to implement the
UpgradeResourceState method. The obvious implementation of returning the same
JSON-encoded value has tripped up a few providers not using the legacy
SDK already, and we should have at least indicated that the value was
being lost.
> Accept JSON encoded dynamic values from providers

- go.mod
- go.sum
This includes some fixes for Windows console users, most notably adding support for underline, which is useful for HCL diagnostics. [Link to upstream diff since last version](https://github.com/mattn/go-colorable/compare/v0.1.1..v0.1.8).
> go get github.com/mattn/go-colorable@v0.1.8

- terraform/context_apply_test.go
- terraform/eval_apply.go
- terraform/terraform_test.go
- terraform/testdata/apply-provisioner-sensitive/main.tf
- website/docs/provisioners/index.html.markdown
Two separate commits in this pull request, which I'd suggest reviewing separately. The first is a bug fix which I'm pretty confident about, and the second is a UI change that I'd really appreciate feedback on.
If provisioner configuration or connection info includes sensitive values, we need to unmark them before calling the provisioner. Failing to do so causes serialization to error.
Unlike resources, we do not need to capture marked paths here, so we just discard the marks.
If the provisioner configuration includes sensitive values, it's a reasonable assumption that we should suppress its log output. Obvious examples where this makes sense include echoing a secret to a file using local-exec or remote-exec.
This commit adds tests for both logging output from provisioners with …
> Fixes for sensitive values used as input to provisioners

- terraform/context_apply_test.go
- terraform/context_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
This updates `GetResource` evaluation so that the value returned has marks where the provider's schema has marked an attribute as sensitive. In practice, this means that values will be marked inside a resource when that resource is referenced elsewhere in the config, so that "sensitivity" as defined by the provider on an attribute will follow that value when used elsewhere in Terraform.
Put another way, if we have one resource that has an attribute that is `Sensitive` according to that provider's schema, then referencing that attribute elsewhere will result in derived sensitivity:
```terraform
resource "test_resource" "foo" {
sensitive_value = "should get marked"
}
resource "test_resource" "bar" {
value  = test_resource.foo.sensitive_value
}
```
In this scenario, `value` in …
> Mark attributes providers mark as sensitive

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
The Legacy SDK cannot handle missing strings from objects in sets, and
will insert an empty string when planning the missing value. This
subverts the `couldHaveUnknownBlockPlaceholder` check, and causes
errors when `dynamic` is used with `NestingSet` blocks.
We don't have a separate codepath to handle the internals of
`AssertObjectCompatible` differently for the legacy SDK, but we can treat
empty strings as null strings within set objects to avoid the failed
assertions.
Fixes #25600
> Treat empty strings as null in NestingSet objs when looking for dynamic blocks in AssertObjectCompatible

- website/upgrade-guides/0-14.html.markdown
Now that sensitivity follows attributes providers mark as sensitive, add this note to the upgrade guide.
I couldn't think of other areas of the docs that would need this note (sensitivity for providers appears to be mentioned only in the Extend docs? and then only the comments in the Go code), so pointers are very helpful if there are other locations!
> Add note to upgrade guide about provider sensitivity

- codecov.yml
Only run codecov on master branches. This will have no effect on the current behavior of the master branch. That will also be true for opening this for the 0.14 branch, so more of a tidying task.
> [build] Only run codecov on master

- codecov.yml
0.14 sibling to the `master` branch PR
> [build][0.14] only run codecov on main branch

- terraform/context_plan_test.go
- terraform/eval_diff.go
- terraform/testdata/plan-ignore-changes-sensitive/ignore-changes-sensitive.tf
Because `ignore_changes` configuration can refer to resource arguments which are assigned sensitive values, we need to unmark the resource object before processing.
Fixes #26633
> terraform: Fix sensitive values in ignore changes

- backend/remote/backend_common.go
A cost estimation error does not actually stop a run, so the run was continuing in the background after the cli exits, causing confusion. This change matches the UI behavior.
> Allow runs to continue on tfce error

- internal/replacefile/writefile.go
`ioutil.TempFile` has a special case where an empty string for its `dir` argument is interpreted as a request to automatically look up the system temporary directory, which is commonly `/tmp` on Linux.
We don't want that behavior here because we're specifically trying to create the temporary file in the same directory as the file we're hoping to replace. If the file gets created in `/tmp` then it might be on a different device and thus the later atomic rename won't work.
Instead, we'll add our own special case to explicitly use `"."` when the given filename is in the current working directory. That overrides the special automatic behavior of `ioutil.TempFile` and thus forces the behavior we need.
This hadn't previously mattered for earlier callers of this code because they were creating …
> replacefile: don't create the temporary file in TMPDIR

- command/e2etest/init_test.go
If you run the e2e tests locally and use a configured plugin_cache_dir,
`TestInitProvidersLocalOnly` will leave a bad (incomplete) directory behind in your cache dir that causes
later `init`s to fail. To circumvent this, pass an explicitly-empty CLI
config file.
This is a nicety for local developers and not required, but
it happens to me often enough that I'd like to fix it. It's probably not
a *bad* idea to pass an explicit cli config to all e2e tests, honestly,
but this is the only one that causes active problems for the local workstation (that I have encountered, at least) so I limited this PR to that one test.
Here's the error which occurs on subsequent `init` if this test is run on a
machine that uses a plugin cache dir:
```
2020/10/13 10:41:05 [TRACE] providercache.fillMetaCache: …
```
> command/e2etest: do not leave incomplete provider installation directories behind

- Dockerfile
Two updates:
- we are going to stop publishing the full docker image , but we will leave the dockerfile and its supporting script in place for users who want to continue using that for development
- the main docker release is handled elsewhere, so drop (outdated) references to it
Closes #26629
> build: update comments in dockerfile

- internal/getproviders/filesystem_search.go
Previously this codepath was generating a confusing message in the absense of any symlinks, because `filepath.EvalSymlinks` returns a successful result if the target isn't a symlink.
Now we'll emit the log line only if `filepath.EvalSymlinks` returns a result that's different in a way that isn't purely syntactic (which
`filepath.Clean` would "fix").
The new message is a little more generic because technically we've not actually ensured that a difference here was caused by a symlink and so we shouldn't over-promise and generate something potentially misleading.
> getproviders: Don't log if EvalSymlinks changes nothing

- command/providers_test.go
- internal/depsfile/locks_file_test.go
- internal/getproviders/types.go
If a configuration requires a partial provider version (with some parts unspecified), Terraform considers this as a constrained-to-zero version. For example, a version constraint of `1.2` will result in an attempt to install version `1.2.0`, even if `1.2.1` is available.
When writing the dependency locks file, we previously would write `1.2.*`, as this is the in-memory representation of `1.2`. This would then cause an error on re-reading the locks file, as this is not a valid constraint format.
Instead, we now explicitly convert the constraint to its zero-filled representation before writing the locks file. This ensures that it correctly round-trips.
Because this change is made in `getproviders.`VersionConstraintsString, it also affects the output of the providers sub-command.
Fixes …
> internal: Fix lockfile constraint output for 1.2.*

- command/ui_input.go
- command/ui_input_test.go
**UPDATE**: adding `-input=false` seems to do the trick [as pointed out here](https://www.reddit.com/r/Terraform/comments/j6yk2l/terraform_plan_doesnt_error_out_if_required/g81m2zy?utm_source=share&utm_medium=web2x&context=3). It might still make sense to keep the error handling though?
------------
Fixes: https://github.com/hashicorp/terraform/issues/26508
Sample output:
```
Step 4/4 : RUN TF_LOG=DEBUG /terraform plan /tmp/
---> Running in f67cf0c83d8d
2020/10/07 20:12:22 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's internal logs.
----
2020/10/07 20:12:22 [INFO] Terraform version: 0.14.0 dev 
2020/10/07 20:12:22 [INFO] Go runtime version: go1.15.2
2020/10/07 20:12:22 [INFO] CLI args: …
```
> Exit with error if UI input scan fails

- command/providers_test.go
- internal/depsfile/locks_file_test.go
- internal/getproviders/types.go
If a configuration requires a partial provider version (with some parts unspecified), Terraform considers this as a constrained-to-zero version. For example, a version constraint of `1.2` will result in an attempt to install version `1.2.0`, even if `1.2.1` is available.
When writing the dependency locks file, we previously would write `1.2.*`, as this is the in-memory representation of `1.2`. This would then cause an error on re-reading the locks file, as this is not a valid constraint format.
Instead, we now explicitly convert the constraint to its zero-filled representation before writing the locks file. This ensures that it correctly round-trips.
Because this change is made in `getproviders.VersionConstraintsString`, it also affects the output of the providers sub-command.
Backport of …
> [v0.14] internal: Fix lockfile constraint output for 1.2.*

- command/e2etest/init_test.go
- command/e2etest/provider_dev_test.go
- command/meta_providers.go
- command/plugins.go
- go.mod
- go.sum
- internal/logging/logging.go
- internal/logging/panic.go
- main.go
Now that the output isn't being filtered by the panicwrap process, there was nothing being written to the log to generate the `crash.log` file in case of a panic.
Since the parent process needs to create the crash log, while the wrapped process need to write the temp log, we do this by passing a temp file name between the processes. The parent process creates the empty log file, and registers the filename with the panic handler, while the wrapped process re-opens the file for log writing. 
Now that the parent process is no longer responsible for writing any of the actual logs, we can remove the need for `prefixedio` along with the extra synchronization, buffering and copying of multiple streams it required.
There was a bug in the `hclog` package which prevented `StandardWriters` from …
> Restore "crash.log" behavior and remove prefixedio

- website/docs/backends/types/gcs.html.md
Experienced similar issue as https://github.com/hashicorp/terraform/issues/18417 this updates the documentation so that it's more clear a storage bucket must exist prior to configuring the backend.
> website: Clear wording that GCS backend bucket must pre-exist

- website/docs/registry/api.html.md
Hello maintainers 👋🏼 
This PR updates the `description` for https://www.terraform.io/docs/registry/api.html as it incorrectly referenced Consul and ACL tokens.
The sentence I chose is based on what is used in the [List Modules](https://www.terraform.io/docs/registry/api.html#list-modules) section.
> updates `description` to reflect endpoint usage

- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
- website/docs/provisioners/puppet.html.markdown
- website/docs/provisioners/salt-masterless.html.md
Making the deprecation of tool-specific provisioners even more visible (and following up on a commitment I made to do this exact thing).
> website: tool-specific provisioner docs change to red notice box

- terraform/context_apply_test.go
- terraform/context_refresh_test.go
- terraform/graph_builder_plan.go
- terraform/node_resource_plan_instance.go
- terraform/node_resource_plan_orphan.go
- terraform/node_resource_plan_orphan_test.go
- terraform/provider_mock.go
This forces orphaned resources to be re-read during planning, removing
them from the state if they no longer exist.
This needs to be done for a bare `refresh` execution, since Terraform
should remove instances that don't exist and are not in the
configuration from the state. They should also be removed from state so
there is no Delete change planned, as not all providers will gracefully
handle a delete operation on a resource that does not exist.
> Read orphaned instances during plan

- plugin/grpc_provider.go
- plugin/grpc_provider_test.go
Backport #26613 to 0.14
The added functionality does not effect existing providers, but adding it into 0.14 will broaden the compatible base for providers working with the prototype plugin SDK.
> 0.14 backport of 26613

- terraform/context_apply_test.go
- terraform/eval_apply.go
Warnings alone cannot be returned from eval nodes, since are still
treated as errors.
This is temporary, as we are close to being able to complete the
refactoring that allows diagnostics to be all the way from the plugin
method calls.
> do not return warnings as errors from eval

- terraform/context_apply_test.go
- terraform/eval_apply.go
Warnings alone cannot be returned from eval nodes, since are still
treated as errors.
0.14 backport of #26687
> 0.14 backport of #26687

- terraform/evaluate.go
- terraform/evaluate_test.go
When a resource is referenced by another one, `GetResource` fulfills this request. If a resource has a planned change, GetResource returns the planned value of the resource -- this means that that value could theoretically return without its marks (until this changeset!). 
I haven't been able to re-create this in an E2E situation (context2apply) -- the evaluation appears to happen within Plan, and each plan starts with a new Changes, so I can't inject one (as things are now). 
Submitting for review with the caveat of "I am unsure how to run into this situation, but this is the _right_ thing to do if you somehow can".
> Return marked After values in GetResource

- command/meta_providers.go
- command/plugins.go
- go.mod
- go.sum
- internal/logging/logging.go
- internal/logging/panic.go
- main.go
- website/docs/commands/environment-variables.html.md
- website/docs/internals/debugging.html.md
Both core and provider logs can be quite verbose, and it is often difficult to debug one or the other while sifting through the combination of their logs.
Here we introduce two new environment variables for more control over logging:
TF_LOG_CORE=level
TF_LOG_PROVIDER=level
The existing `TF_LOG` environment variable remains to set the global log level, but these new variables allow the viewing of the subsystem logs independently.
> Separate loggers

- codecov.yml
We have informational mode enabled for pull requests. This commit enables it for individual commits, too.
Informational mode registers the result of a Codecov check without ever failing due to low coverage. This is appropriate for Terraform because much of the test coverage comes from cross-package tests, which Codecov misses.
Here's a commit which does not match our target for diff coverage, and now shows a happy ✅ instead of an angry ❌ :
> build: Set Codecov to informational mode again

- lang/funcs/collection.go
- lang/funcs/collection_test.go
- lang/functions.go
- lang/functions_test.go
- website/docs/configuration/functions/anytrue.html.md
- website/layouts/functions.erb
This is a v0.14 backport of #26498, which was originally intended to go along with the `alltrue` we already merged into 0.14 and only ended up delayed to after the 0.14.0-beta1 release due to me being late to review it.
> lang/funcs: "anytrue" function

- internal/logging/logging.go
- internal/logging/panic.go
- internal/logging/panic_test.go
- main.go
- plugin/grpc_error.go
- plugin/grpc_provider.go
- plugin/grpc_provisioner.go
In prior versions of terraform, the combined stderr log stream would cause provider crashes to trigger `panicwrap`, and print a formidable message about terraform crashing, and how to report it. While the updated log handling now prevents the plugin stack traces from reaching `panicwrap`, they were also lost completely unless logging was enabled. This leaves the user with only a rather unhelpful grpc error from a crashing provider:
Error: rpc error: code = Unavailable desc = transport is closing
Since there is no direct way for core to handle a crash in a provider, we will catch the output by wrapping the plugin loggers to look for `panic: ` or `fatal error: ` and record the following output. This relies on the behavior of go-plugin, which sends any unstructured stderr output to a `Debug` …
> Handle panics in plugins

- internal/getproviders/types.go
- internal/getproviders/types_test.go
A set of version constraints can contain duplicates. This can happen if multiple identical constraints are specified throughout a configuration.
When rendering the set, it is confusing to display redundant constraints. This commit changes the string renderer to only show the first instance of a given constraint, and adds unit tests for this function to cover this change.
This also fixes a bug with the locks file generation: previously, a configuration with redundant constraints would result in this error on second init:
```
Error: Invalid provider version constraints
on .terraform.lock.hcl line 6:
(source code not available)
The recorded version constraints for provider
registry.terraform.io/hashicorp/random must be written in normalized form:
"3.0.0".
```
Fixes #26670.
> internal: Suppress duplicate version constraints

- experiments/experiment.go
- terraform/context_apply_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
- website/upgrade-guides/0-14.html.markdown
Rolls back marking attributes providers mark as sensitive to an `experiment` and adds associated docs and adjustments
to the upgrade guide. This is making https://github.com/hashicorp/terraform/pull/26590 experimental, rather than default, and I submitting this for a 0.14 backport.
To propagate sensitivity to attributes providers mark as sensitive, activate the experiment in the `terraform` block:
```
terraform {
experiments = [provider_sensitive_attrs]
}
```
> Add provider sensitivity propagation experiment

- website/docs/configuration/modules.html.md
It seems that the word `with` is redundant in the following sentence:
> For a module with without count or for_each, the address will not...
> Small spelling improvement

- internal/getproviders/types.go
- internal/getproviders/types_test.go
In #26678 we made this function skip duplicates, which set the precedent that this function is trying to canonically represent the _meaning_ of the version constraints rather than exactly how they were expressed in the configuration.
Continuing in that vein, now we'll also apply a consistent (though perhaps often rather arbitrary) ordering to the terms, so that it doesn't change due to irrelevant details like declarations being written in a different order in the configuration. This affects both the `terraform init` UI output and the provider constraint strings we write into dependency lock files.
The ordering here is intended to be reasonably intuitive for simple cases, but constraint strings with many different constraints are hard to interpret no matter how we order them so the main …
> getproviders: Consistent ordering of terms in VersionConstraintsString

- website/docs/internals/module-registry-protocol.html.md
1: There is a mismatch in the segment labels for the version query URL (system vs provider)
2: There is a discrepancy between the documentation and the actual generated request for retrieving module source code (URL segments 4 vs 3)
- There is no segment for "provider"
> website: Update module-registry-protocol.html.md

- internal/depsfile/locks_file.go
- internal/providercache/installer.go
- internal/providercache/installer_events_test.go
- internal/providercache/installer_test.go
- internal/providercache/package_install.go
- internal/providercache/testdata/beep-provider/terraform-provider-beep
This is a bit of an odd PR because my original goal was to improve the test coverage for the provider installer, but in the process of doing so I found a bug in it and so this PR is now primarily aimed at fixing that bug prior to the beta 2 release (so hopefully the new behavior will see some external testing before final) but most of the diff here is actually adding a bunch of largely-unrelated extra test coverage. :roll_eyes: 
Given that, reviewers might prefer to read this commit-by-commit.
---
Previously we were only verifying locked hashes for local archive zip files, but if we have non-ziphash hashes available then we can and should also verify that a local directory matches at least one of them.
This does mean that folks using filesystem mirrors but yet also running Terraform …
> providercache: verify locked hashes for local package dirs (and also various tests)

- command/format/state.go
- command/format/state_test.go
`terraform show -json` is intended to be the means to view _all_ values in state, but previously, `terraform show` would still show outputs that were designated as `sensitive`. This adjusts that behavior.
Before:
```
$ terraform show 
resource "random_pet" "bar" {
id        = "cat-quick-sunbird"
length    = 2
prefix    = (sensitive)
separator = "-"
}
Outputs:
out = "cat"
```
After:
```
$ terraform show 
resource "random_pet" "bar" {
id        = "cat-quick-sunbird"
length    = 2
prefix    = (sensitive)
separator = "-"
}
Outputs:
out = (sensitive value)
```
> Hide sensitive outputs in terraform show

- command/jsonstate/state.go
- command/jsonstate/state_test.go
- command/testdata/show-json-state/sensitive-variables/output.json
- command/testdata/show-json-state/sensitive-variables/terraform.tfstate
This prevents "sensitive" values from unintentionally showing as nil when running terraform show -json. Also adjusts the signature of a function to remove an unused argument.
Closes #26737
> Unmark values before showing in JSON

- backend/remote/backend_common.go
Reverts part of #26618
We'll just have the error continuation bug fix in for now. Improved error messaging will come later once it's refactored in our cost-estimation library.
> Stop printing tfce error message log

- command/format/diagnostic.go
- command/format/diagnostic_test.go
- lang/eval.go
- terraform/eval_for_each.go
- terraform/eval_for_each_test.go
- terraform/eval_validate.go
- terraform/node_module_expand.go
(This is another installment of "I had a little time to kill and this has been annoying me.")
When writing complex `for_each` expressions that collect values from various other places in the configuration, the error message about the value being invalid due to being unknown is particularly frustrating because it has historically not given any guidance as to what might be contributing to the value being unknown.
We typically annotate expression evaluation errors with information about the values that might have contributed to them, but we've not been doing that for the `for_each` expressions because our evaluation codepath was using a sort of "all in one" shortcut method to evaluate the expression and thus didn't have enough information (the `hcl.EvalContext`, to be specific) to properly …
> Show which input values are unknown when for_each fails due to being unknown

- command/init_test.go
- states/statefile/read.go
- states/statefile/testdata/roundtrip/v4-future.in.tfstate
- states/statefile/testdata/roundtrip/v4-future.out.tfstate
For this version of Terraform and forward, we no longer refuse to read compatible state files written by future versions of Terraform. This is a commitment that any changes to the semantics or format of the state file after this commit will require a new state file version 5.
The result of this is that users of this Terraform version will be able to share remote state with users of future versions, and all users will be able to read and write state. This will be true until the next major state file version is required.
This does not affect users of previous versions of Terraform, which will continue to refuse to read state written by later versions.
---
This commit is targeting the main branch, so will be released with 0.15. I'm tagging this for backport to v0.14 also, although I'd like …
> states: Disable Terraform version check

- website/docs/configuration/version-constraints.html.md
This PR updates the documentation of version constraint syntax to remove confusion of the users.
As per the suggestion from @alisdair, I have updated the document. 
Fixes #26574
> website: clarify version constraint syntax

- website/intro/examples/index.html.markdown
Reasoning for docs update:
Had an issue when completing the 2 tier aws example, and it looks like I wasn't the only one. 
The page mentions that the configuration is "intuitive", and it seems to list all the commands needed, and implies that Terraform will prompt you for any other required info. 
However, unless you have added the required private key to your ssh-agent using ssh-add, the example fails! Not a good start for newcomers! 
I know there's a comment in the main.tf file about it using a local SSH agent to connect, but i don't think that's explicit enough. 
It's an easy step to miss, and you'd be inclined to think it's an issue with your Terraform install, or your AWS settings etc... 
Relevant Terraform version:
Current version
> Added info re additional step re private key to the Example Config intro docs

- backend/local/backend_plan.go
- backend/local/testdata/plan-outputs-changed/main.tf
- backend/local/testdata/plan-outputs-changed/submodule/main.tf
When rendering planned output changes, we need to filter the plan's output changes to ensure that only root module outputs which have changed are rendered. Otherwise we will render changes for submodule outputs, and (with concise diff disabled) render unchanged outputs also.
Fixes #26776
> backend: Only show root module output changes

- lang/eval.go
- lang/eval_test.go
We can insert the terraform and path values into EvalSelfBlock, since
these are static and always known during evaluation.
Fixes #26779
> allow path and terraform in self-block eval

- internal/getproviders/types.go
- internal/getproviders/types_test.go
When rendering a set of version constraints to a string, we normalize partially-constrained versions. This means converting a version like `2.68.*` to `2.68.0`.
Prior to this commit, this normalization was done after deduplication. This could result in a version constraints string with duplicate entries, if multiple partially-constrained versions are equivalent. This commit fixes this by normalizing before deduplicating and sorting.
Fixes #26772
> getproviders: Normalize versions before dedupe

- command/apply_test.go
- providers/provider.go
- terraform/context_plan_test.go
- terraform/node_provider.go
- terraform/provider_mock.go
The provider was only given the static configuration to validate early on, but that would not contain any variable values that may have been referenced. Add a second call to `PrepareProviderConfig` immediately before `Configure` to allow the provider to validate the final config and not have to repeat its own validation within the `Configure` call. 
Core was also not using the `PreparedConfig` response from `PrepareProviderConfig`, which remains unchanged in this PR. We elect to continue ignoring the `PreparedConfig` here, since there is no useful reason for it at this point, and it would introduce a functional difference between terraform releases that can be avoided. A log warning is added here if the config was altered, as an extra hint to providers that returned value is unused.
The …
> Validate final provider configuration

- terraform/context_validate_test.go
- terraform/eval_refresh.go
- terraform/eval_validate.go
- terraform/eval_validate_test.go
The validation for ignore_changes was too broad, and makes it difficult
to ignore changes in an attribute that the user does not want to set.
While the goal of ignore_changes is to prevent changes in the
configuration alone, we don't intend to break the use-case of ignoring
drift from the provider. Since we cannot easily narrow the validation to
only detect computed attributes at the moment, we can drop this error
altogether for now.
Return diagnostics rather than an error, since the EvalNodes have been
removed and the caller has been updated.
IgnoreWarnings was no longer used.
> Allow null attributes to be referenced in ignore_changes

- internal/logging/panic.go
- internal/logging/panic_test.go
When logging is turned on, panicwrap will still see provider crashes and
falsely report them as core crashes, hiding the formatted provider error.
We can trick panicwrap by slightly obfuscating the error line.
> hide provider crashes from panicwrap when logging

- go.mod
- go.sum
Updates dependency to point to a version rather than a commit.
> Update zclconf/go-cty dependency

- terraform/context_validate_test.go
- terraform/evaluate.go
Ensure that variables are marked in the validate walk so that appropriate diags will surface at validate, rather than surprising users at plan/apply.
> Mark variables as sensitive (if relevant) in validate

- command/meta.go
- terraform/context.go
- terraform/context_test.go
When building a context, we read the dependency locks and ensure that the provider requirements from the configuration can be satisfied. If the configured requirements change such that the locks need to be updated, we explain this and recommend running "terraform init".
This check is ignored for any providers which are locally marked as in development. This includes unmanaged providers and those listed in the provider installation `dev_overrides` block.
Fixes #26565.
> terraform: Compare locks and provider requirements

- website/docs/commands/output.html.markdown
[View rendered](https://github.com/hashicorp/terraform/blob/alisdair/update-output-command-docs/website/docs/commands/output.html.markdown)
The example configuration now uses Terraform 0.12+ syntax, and the output examples are up to date with the current text UI. We also add an explicit recommendation to use the `-json` option for a consistent and stable output format, for use in automation.
Fixes #26831.
> website: Update output command docs

- backend/remote-state/gcs/backend.go
- backend/remote-state/gcs/backend_state.go
- backend/remote-state/gcs/backend_test.go
- website/docs/backends/types/gcs.html.md
Path was deprecated more than 3 years ago.
This removes it from the code.
Spotted while working on #26700
> backend/gcs: remove deprecated "path" config argument

- builtin/providers/terraform/data_source_state.go
These fields are well documented [in the docs](https://registry.terraform.io/providers/hashicorp/terraform/latest/docs/data-sources/remote_state), but this provides descriptions for the schema export (`terraform providers schema -json`) which is in turn used by the language server.
In other words this enhances the user experience of user editing configuration with the Terraform language server - we can display these descriptions e.g. in completion selectbox or on hover.
--- 
I have mostly copy-pasted these from the linked docs and it seems that we use dot at the end of every description. I'm assuming this is intended, even though in most cases it's not a full sentence? Someone with better english grammar knowledge please confirm or correct me if I'm wrong. cc @nfagerlund
> builtin/provider/terraform: Add field descriptions

- go.mod
- go.sum
Update hclog to a tagged version, and get a minor fix from go-plugin to stop logging an EOF as a warning.
> update go-plugin and go-hclog

- website/docs/configuration/variables.html.md
Update the link to HashiCorp learn to the new variables tutorial in the configuration language section, rather than the old variables tutorial in the AWS getting started section.
> website: update link to new varibles tutorial

- configs/resource.go
- terraform/evaluate_valid_test.go
- terraform/testdata/static-validate-refs/static-validate-refs.tf
When a resource has no `provider` argument specified, its provider is derived from the implied provider type based on the resource type. For example, a `boop_instance` resource has an implied provider local name of `boop`. Correspondingly, its provider configuration is specified with a `provider "boop"` block.
However, users can use the `required_providers` configuration to give a different local name to a given provider than its defined type. For example, a provider may be published at `foobar/beep`, but provide resources such as `boop_instance`. The most convenient way to use this provider is with a `required_providers` map:
```hcl
terraform {
boop = {
source = "foobar/beep"
}
}
}
```
Once that local name is defined, it is used for provider configuration (a …
> configs: Fix provider lookup local name mismatch

- website/docs/cli/install/apt.html.md
- website/docs/cli/install/yum.html.md
- website/layouts/downloads.erb
The HashiCorp engineering services team has set up APT and Yum repositories as alternative installation methods for various HashiCorp products, now including Terraform.
We don't really have a great place to talk about these in our current website structure. There is a longer-term plan to revamp the downloads page to include other options, but we are already getting lots of questions about how to use these repositories and so my goal here is to publish at least a first pass of documentation, linked from the Downloads page sidebar as a placeholder for now, so we'll have somewhere to refer to when answering such questions.
My intent is that even once we have a revamped Downloads page that mentions these options more clearly, we'll still need to link out to another page to talk about various …
> website: Initial docs about the APT/Yum repositories

- communicator/ssh/communicator.go
- communicator/ssh/provisioner.go
- communicator/ssh/provisioner_test.go
- terraform/eval_validate.go
- website/docs/provisioners/connection.html.markdown
EDIT: changed solution to use a target_platform property in the connection block
A small fix for #25634 where certain parts of the remote_exec (chmodding, inserting a shebang requesting a pty) are skipped when the target file is a windows path. This is determined by looking at the first 2 runes of the destination path, if the first rune in a range [a-z]:[A-Z] and the second rune is a colon the isWindows var is set to true.
```
resource "null_resource" "cmd" {  
connection {
type        = "ssh"
user        = "administrator"
password    = var.password
host        = var.host
script_path = "c:\\windows\\temp\\terraform_%RAND%.cmd"
target_platform = "windows"
}
provisioner "remote-exec" {
inline = [
"echo hello there",
"rmdir /s /q c:\\windows\\temp\\cmd",      
"mkdir …
```
> Support for remote_exec on Windows SSH

- go.mod
- go.sum
- website/docs/modules/sources.html.markdown
Aims to fix https://github.com/hashicorp/terraform/issues/24656 and related to https://github.com/hashicorp/go-getter/issues/263
> Update go-getter to v1.5.1 with support for vhost style S3 paths

- website/docs/configuration/expressions.html.md
The second Local Named Values has a subset of the information the first one has and adds nothing to the documentation other than confusion.
> Remove redundant Local Named Values section

- lang/funcs/defaults.go
- lang/funcs/defaults_test.go
- lang/functions.go
- lang/functions_test.go
- lang/scope.go
- terraform/eval_context_builtin.go
- website/docs/configuration/functions/defaults.html.md
- website/layouts/language.erb
This is a new part of the existing `module_variable_optional_attrs` experiment, because it's intended to complement the ability to declare an input variable whose type constraint is an object type with optional attributes. Module authors can use this to replace null values (that were either explicitly set or implied by attribute omission) with other non-null values of the same type.
This function is a bit more type-fussy than our functions typically are because it's intended for use primarily with input variables that have fully-specified type constraints, and thus it uses that type information to help inform how the defaults data structure should be interpreted.
Other uses of this function will probably be harder today because it takes a lot of extra annotation to build a value of a …
> lang/funcs: Experimental "defaults" function

- website/docs/commands/output.html.markdown
The missing new line doesn't permit the code block to show up in the generated documentation
> Add a missing new line

- website/docs/internals/module-registry-protocol.html.md
I was attempting to update implement the module registry protocol and ran into some issues with the documentation.
In the `Download Source Code for a Specific Module Version` a `:system` path variable is documented, but doesn't seem to actually exist. It doesn't appear to be present in the listed example URL (`https://registry.terraform.io/v1/modules/hashicorp/consul/aws/0.0.1/download`), and my provider was returning 404's until I removed that segment.
On a related note, `List Available Versions for a Specific Module` the `system` path variable looks like it should actually be referencing the `provider`.
This PR removes the extraneous path variable documentation and replaces remaining `system` references with `provider` references.
> Remove 'system' references from module registry protocol docs.

- terraform/node_provider.go
- terraform/node_provider_test.go
Before configuring a provider, we need to unmark the configuration object, in case it includes any sensitive values. This is required because configuration occurs over gRPC, which doesn't support sensitive marks.
Fixes #26922
> terraform: Unmark provider configuration arguments

- backend/local/backend_plan_test.go
- backend/local/testdata/plan-module-outputs-changed/main.tf
- backend/local/testdata/plan-module-outputs-changed/mod/main.tf
- plans/changes.go
- plans/plan_test.go
Module outputs should not trigger plan rendering. These are not shown in the plan output, however they were still causing `Changes.Empty()` to return `false`.
Fixes #26899
> Don't render a plan for module outputs

- configs/compat_shim.go
- configs/compat_shim_test.go
We have an existing warning message to encourage moving away from the old 0.11-and-earlier style of redundantly wrapping standalone expressions in templates, but due to the special rules for object keys the warning message was giving misleading advice in that context: a user following the advice as given would then encounter an error about the object key being ambiguous.
```hcl
locals {
foo = {
a = "b"
"${local.bar}" = "c"
}
}
```
```
Warning: Interpolation-only expressions are deprecated
on interp-map-keys.tf line 4, in locals:
4:     "${local.bar}" = "c"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the …
```
> configs: Specialized warning for single-interpolation object keys

- website/docs/configuration/functions/coalesce.html.md
In order to be able to predict a result type even if arguments are not yet known, `coalesce` requires all of its arguments to be of the same type. Our usual automatic conversion rules mean that in some cases the result is a silent type conversion rather than an explicit error, so we'll at least document that so that folks who encounter it can understand what is causing the likely-surprising behavior.
If we were building this function over again today I expect we'd make it always return an error under type mismatch, but to do so now would be a breaking change and the potential cost of that seems too high for something that doesn't seem to arise incredibly often in practice.
This closes #26219, by documenting the existing behavior as the intended behavior.
> website: "coalesce" function unifies its argument types

- website/docs/modules/sources.html.markdown
As written previously this seemed to suggest using `app.terraform.io` (the "hostname you use to access the Terraform Cloud application) to access a private registry in Terraform Enterprise, but that isn't true and I assume isn't what was intended.
Instead, the hostname for a Terraform Enterprise instance is the hostname where the Terraform Enterprise application is running, which is both the hostname where users would find its web UI and the hostname they'd use to configure the `remote` backend for remote operations and state storage.
This is motivated by and closes #26154.
> website: Reword confusing statement about module sources in TFE

- website/docs/provisioners/local-exec.html.markdown
The local-exec provisioner documentation includes an example which refers to an attribute of the current resource using its full traversal path, rather than using `self` as we typically expect.
Due to some coincidences in how Terraform builds the dependency graph, referring to the resource in this way happens to work when the resource has only a single instance (the graph builder just skips that self-referential dependency edge), but it fails if the user later tries to add `count` or `for_each` to the resource, because at that point all of the instances become dependent on one another, which creates a dependency cycle.
Using `self` to access the current instance attributes is the usual approach, so I've updated the documentation to show that.
This fixes #25548.
> website: Fix confusing example for local-exec provisioner

- configs/config_build.go
- configs/config_build_test.go
- configs/testdata/nested-backend-warning/child/child.tf
- configs/testdata/nested-backend-warning/root.tf
Terraform considers backend configurations only in the root module, so any declarations in child modules are entirely ignored.
To avoid users mistakenly thinking that a root module backend configuration has taken effect, we'll now emit a warning about it. This is a warning rather than an error because it's reasonable to call a module that would normally be a root module instead as a child module when writing a wrapper module to handle integration testing.
```
Warning: Backend configuration ignored
on child/nested-backend-config-child.tf line 2, in terraform:
2:   backend "ignored" {}
The selected backend applies to the entire configuration, so Terraform expects
provider configurations only in the root module.
This is a warning rather than an error because it's sometimes convenient to …
```
> configs: Emit a warning for backends in nested modules

- website/docs/commands/providers/lock.html.md
This was commit 04199a628, and it looks like it might have skipped main and gone straight to 0.14.
> website: Adopt a title typo fix from v0.14 branch

- command/testdata/fmt/general_in.tf
- command/testdata/fmt/general_out.tf
- go.mod
- go.sum
Fixes #26960 via https://github.com/hashicorp/hcl/pull/422. I'm planning on backporting this to 0.14.0.
> command: Fix fmt to preserve blank block labels

- backend/remote/backend_apply_test.go
- backend/remote/backend_common.go
- backend/remote/backend_mock.go
- backend/remote/backend_plan.go
- backend/remote/backend_plan_test.go
- backend/remote/remote_test.go
The remote backend tests spent most of their execution time sleeping in various polling and backoff waits. This is unnecessary when testing against a mock server, so reduce all of these delays when under test to much lower values.
Only one remaining test has an artificial delay: verifying the discovery of services against an unknown hostname. This times out at DNS resolution, which is more difficult to fix than seems worth it at this time.
The only change to production code is unifying the network backoff when waiting for the run and waiting for the cost estimate. The latter is now an exponential backoff between 1 and 3 seconds, instead of constant 1 second.
From my reading of these tests, I don't think this should cause flaky tests due to timing. I'm going to rerun the CircleCI job a few …
> backend: Faster remote backend tests

- command/version.go
- command/version_test.go
- commands.go
- version/version.go
Along with all of the other information we previously reported in the `terraform version` output, we'll now include the name of the current platform as our provider installation mechanisms represent it.
This is addressing a long-standing minor annoyance where we sometimes can't tell from an incomplete bug report which platform Terraform was running on, and incomplete bug reporters do tend to at least include the requested `terraform version` output even if they don't also include the requested full trace log.
However, what motivated doing this _now_ is that anyone building a provider registry or mirror needs to have some awareness of these platform identifiers which have been, until v0.13, mostly an implementation detail. This additional information is a small thing we can do to help …
> command/version: Report the current platform

- terraform/context_components_test.go
- terraform/context_validate_test.go
- terraform/eval_validate.go
- terraform/eval_validate_test.go
- terraform/provider_mock.go
Related PR: https://github.com/hashicorp/terraform/pull/26832
Unmark values before sending over to the provider's `ValidateResourceTypeConfig` function -- previously, sending this now (as of PR mentioned above) marked value would fail to be marshalled, and this wasn't covered by our test suite, because the mock provider does not marshall values in its `ValidateResourceTypeConfig`
This PR therefore updates some of the testing infrastructure, ranging from making `test_number` a number, to adding msgpack into the validate functions for the mock provider, to adding some internal methods `getResourceSchema` and `getDatasourceSchema` for that mock provider as well.
> Unmark values before provider validate call

- lang/eval.go
- terraform/context_validate_test.go
I found these while exploring some tests and found a few places across the project to fix. There is one remaining location, but changing it (https://github.com/hashicorp/terraform/blob/master/states/statefile/version4.go#L86) breaks 100+ tests, and I favor getting this fixed in these places here without blocking on that one.
This is a candidate for v0.14 backport, but not for merge to RC as while the tests pass, I don't want to cause mysterious bugs in GA, so I won't be requesting team review on the backport PR.
> Fix diags non-assignment bugs

- internal/providercache/installer_test.go
The temporary directory on some systems (most notably MacOS) contains
symlinks, which would not be recorded by the installer. In order to make
these paths comparable in the tests we need to eval the symlinks in
the paths before giving them to the installer.
> Fix providercache tests on MacOS

- website/docs/commands/fmt.html.markdown
We've historically made statements like this in response to requests for more customization to the `terraform fmt` behavior, but the documentation itself was somewhat vague about the intended goals of this command.
This is an attempt to be more explicit that consistency between codebases is the primary goal of this command, and that the examples in the Terraform documentation are our main guide for what is "idiomatic style" when adding additional rules over time.
Nothing here is intended to be new policy, but instead as codifying positions we've taken elsewhere in the past in the hope of allowing users to decide how (and whether) they wish to make use of this tool.
---
I've marked this for backport into the v0.14 branch because Terraform v0.14 includes some new rules to do things like …
> website: More words about "terraform fmt"

- repl/format.go
- repl/format_test.go
The console and output formatter previously displayed multi-line strings with escaped newlines, e.g. `"hello\nworld\n"`. While this is a valid way to write the HCL string, it is not as common or as readable as using [the heredoc syntax](https://www.terraform.io/docs/configuration/expressions.html#string-literals), e.g.
```hcl
<<EOF
hello
world
EOF
```
This commit adds heredoc detection and display to this formatter, including support for indented heredocs for nested multi-line strings. This change affects the apply, console, and output sub-commands.
Fixes #27039. Targeting an 0.14.0 backport because this is a fairly narrowly-scoped fix to a problem introduced by changes in the 0.14 release.
> repl: Display multi-line strings as heredocs

- go.mod
- go.sum
Fixes #27041, fixes #26746. Targeting backport to 0.14.0 because #27041 is a crash with sensitive values.
Upstream changelog:
* gohcl: Fix panic when decoding into type containing value slices. ([#335](https://github.com/hashicorp/hcl/pull/335))
* hclsyntax: The unusual expression `null[*]` was previously always returning an unknown value, even though the rules for `[*]` normally call for it to return an empty tuple when applied to a null. As well as being a surprising result, it was particularly problematic because it violated the rule that a calling application may assume that an expression result will always be known unless the application itself introduces unknown values via the evaluation context. `null[*]` will now produce an empty tuple. …
> Upgrade to hcl v2.7.2

- website/docs/configuration/blocks/providers/index.html.md
- website/docs/configuration/dependency-lock.html.md
- website/docs/configuration/expressions.html.md
- website/docs/configuration/expressions/conditionals.html.md
- website/docs/configuration/expressions/function-calls.html.md
- website/docs/configuration/expressions/index.html.md
- website/docs/configuration/expressions/references.html.md
- website/docs/configuration/expressions/splat.html.md
- website/docs/configuration/functions.html.md
- website/docs/configuration/modules.html.md
- website/docs/configuration/provider-requirements.html.md
- website/docs/configuration/resources.html.md
- website/docs/configuration/variables.html.md
A collection of really tiny docs fixes for the last little run-up to 0.14. 
The one about spacing out the landing pages makes it so that if you clicked an old deep link into the expressions page, the summary and link to the relevant _new_ page is the **only** thing you'll see in the initial page view. (You can, of course, scroll to see more if you really want to.)
> website: Add new learn links, improve legacy landing pages

- website/docs/configuration/expressions/references.html.md
This is under a heading "Sensitive Resource Attributes" on the assumption that if we later stabilize this feature then this heading will live on with some different content that describes the propagation of sensitive values from resource attributes, rather than describing the experiment.
If we do later stabilize this and thus make the propagation behavior common to all "sensitive" things in the configuration then I expect we'll probably want to write a page specifically about that behavior under the "Expressions" section, incorporating some of the stuff we currently have on the "Variables" page, but bigger reorganizing like that can wait until we're surer about what we're going to do with this.
> website: Initial docs for the provider_sensitive_attrs experiment

- plugin/ui_input.go
- plugin/ui_input_test.go
- plugin/ui_output.go
- plugin/ui_output_test.go
The import was switched for other types which have since been removed.
Point this at the correct package.
> don't use legacy import for the terraform.UIInput interface

- website/docs/backends/types/terraform-enterprise.html.md
- website/docs/configuration/functions/defaults.html.md
- website/docs/configuration/functions/textdecodebase64.html.md
- website/docs/configuration/functions/textencodebase64.html.md
This is the 0.14 version of https://github.com/hashicorp/terraform/pull/27089; it includes one additional fix (the old atlas backend page had a bad layout key).
> website: fix a few functional glitches (0.14 version) 

- website/docs/configuration/functions/alltrue.html.md
- website/docs/configuration/functions/anytrue.html.md
Fixing a little of the ambiguity due to lack of versioned docs. `anytrue` and `alltrue` functions are available in Terraform `0.14` and later.
Fixes #27098
> Anytrue alltrue docs clarification.

- website/docs/cli/install/apt.html.md
Apt install expects a `name=version` NOT `name==version`
> Fix apt install typo

- website/docs/commands/providers/lock.html.md
- website/docs/configuration/dependency-lock.html.md
I originally drafted these docs in a context where I was relying on GitHub's Markdown renderer, and carelessly imported them into the Terraform website without verifying that the website's Markdown renderer could process it. This particular quirk has bitten us before: the website Markdown parser expects follow-on paragraphs in a list item to be indented at least four spaces, and with less than that it ignores the leading whitespace altogether and just understands a normal paragraph.
This change will cause the follow-on paragraphs to now correctly render as part of the bullet points they are intended to be attached to.
If this is merged then I intend to also merge it into the v0.14 branch to publish along with the next release.
> website: Correct formatting for lists in dependency lock docs

- terraform/context_apply_test.go
- terraform/eval_apply.go
When applying, we return early if only sensitivity changed between the before and after values of the changeset. This avoids unnecessarily invoking the provider.
Previously, we did not write the new value for a resource to the state when this happened. The result was a permanent diff for resource updates which only change sensitivity, as the apply step is skipped and the state is unchanged.
This commit adds a state write to this shortcut return path, and fixes a test for this exact case which was accidentally relying on a value diff caused by an incorrect manual state value.
Fixes #26959. Targeting release in 0.14.1.
> terraform: Write state if sensitivity changes

- terraform/context_plan_test.go
- terraform/eval_diff.go
- terraform/eval_diff_test.go
This covers 3 separate, but related issues that are interacting badly with `ignore_changes` and legacy providers. 
The first is a more straightforward bug, where multiple entries for map keys in `ignore_changes` could cause `cty.Transform` to return early, leaving some values unchanged. Refactor the function to try and separate the fast-path a little better,
and hopefully make it easier to follow.
The second is a side effect of some incorrect provider behavior, but we need to work with it to remain compatible with the legacy SDK. Because we allow legacy providers to depart from the contract and return changes to non-computed values, the plan response may have altered values that were already suppressed with ignore_changes. A prime example of this is where providers attempt to obfuscate …
> Fixes for ignore_changes with unintended provider behavior

- terraform/context_plan_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
- terraform/testdata/plan-variable-sensitivity-module/child/main.tf
- terraform/testdata/plan-variable-sensitivity-module/main.tf
It is possible, say with multiple layers of sensitive variables, to "double-mark" a variable. Add a check to ensure this does not happen.
Fixes https://github.com/hashicorp/terraform/issues/27095
> Avoid double-marking variables

- command/init.go
- command/init_test.go
- tools/terraform-bundle/README.md
- website/docs/commands/init.html.markdown
As of Terraform 0.13+, the get-plugins command has been superseded by new provider installation mechanisms, and general philosophy (providers are always installed, but the sources may be customized). Update the init command to give users a warning if they are setting this flag, to encourage them to remove it from their workflow, and update relevant docs and docstrings as well.
Fixes https://github.com/hashicorp/terraform/issues/27092
Looking to backport to 0.14 (which would give 0.14.1+ users a warning when using this flag), and remove the flag completely in 0.15 after this.
Also looking for:
- Are the reccs here the preferred recommendations for people using this flag?
- Approval/Nay-saying on the "add a warning, then remove completely" plan
- Should this be backported to 0.13 as well?
> Update docs and add warning for -get-plugins

- terraform/eval_diff.go
- terraform/eval_diff_test.go
The logic for handling unknown equality was incorrect, and would miss
changes where the configuration is still not known during plan.
> ignore_changes can ignore unknowns too

- website/docs/configuration/expressions/conditionals.html.md
- website/docs/configuration/expressions/dynamic-blocks.html.md
- website/docs/configuration/expressions/for.html.md
- website/docs/configuration/expressions/function-calls.html.md
- website/docs/configuration/expressions/operators.html.md
- website/docs/configuration/expressions/references.html.md
- website/docs/configuration/expressions/splat.html.md
- website/docs/configuration/expressions/strings.html.md
When we did the earlier documentation rework for Terraform v0.12 we still had one big "Expressions" page talking about the various operators and constructs, and so we had to be a bit economical with the details about some more complicated constructs in order to avoid the page becoming even more overwhelming.
However, we've recently reorganized the language documentation again so that the expressions section is split across several separate pages, and that gives some freedom to go into some more detail about and show longer examples for certain features.
My changes here are not intended to be an exhaustive rewrite but I did try to focus on some areas I've commonly seen questions about when helping in the community forum and elsewhere, and also to create a little more connectivity between …
> website: Elaborate the "expressions" sub-pages in the language section

- go.mod
- go.sum
The result of:
`go get github.com/hashicorp/hcl/v2@2.8.0`
`go mod tidy`
Fixes https://github.com/hashicorp/terraform/issues/27107
Fixes https://github.com/hashicorp/terraform/issues/27040
> Update hcl2 dependency

- builtin/providers/terraform/data_source_state.go
The change recently introduced to ensure that remote backend users do not accidentally upgrade their state file (#26947) needs to be disabled for all read-only uses, including the builtin `terraform_remote_state` data source. Without doing this, the remote state data source fails to read state from `remote` backend sources which do not have an exactly matching Terraform version.
I don't see any reasonable way to add automated tests for this change. Here is an example of the manual verification I'm doing:
```hcl
data "terraform_remote_state" "sfv" {
backend = "remote"
config = {
workspaces = {
name = "sfv"
}
organization = "alisdair-v2"
}
}
output "foobar" {
value = data.terraform_remote_state.sfv.outputs.foobar
}
```
If approved, I intend to backport this change to 0.14, 0.13, and 0.12. …
> Fix terraform_remote_state backend version check

- backend/remote/backend.go
- backend/remote/backend_test.go
Terraform Cloud/Enterprise support a pseudo-version of "latest" for the configured workspace Terraform version. If this is chosen, we abandon the attempt to verify the versions are compatible, as the meaning of "latest" cannot be predicted.
If approved, this will be backported to 0.14, and for later release in 0.13 and 0.12.
> backend/remote: Fix for "latest" workspace version

- website/docs/provisioners/chef.html.markdown
- website/docs/provisioners/habitat.html.markdown
- website/docs/provisioners/puppet.html.markdown
- website/docs/provisioners/salt-masterless.html.md
Noticed that I'd accidentally put 0.14.0 instead of 0.15.0 for this docs change.
> Fix docs for 0.15 for vendor provisioners

- command/output.go
- command/output_test.go
- website/docs/commands/output.html.markdown
So far the output command has had a default output format intended for human consumption and a JSON output format intended for machine consumption.
However, until Terraform v0.14 the default output format for primitive types happened to be _almost_ a raw string representation of the value, and so users started using that as a more convenient way to access primitive-typed output values from shell scripts, avoiding the need to also use a tool like "jq" to decode the JSON. Terraform v0.14 improved the default `terraform output` formatting to be consistent with how we print values in other commands such as `terraform plan`, but consequently it's no longer suitable for direct consumption by shell scripts.
Recognizing that primitive-typed output values are common and that processing them with …
> command/output: Raw output mode

- website/upgrade-guides/0-9.html.markdown
I missed this earlier because my link checker was collapsing the two links from
this page to that page into a single report.
For posterity's sake, I'm linking directly to the markdown file in GitHub at an
appropriate tag version. I do not expect anyone to ever click this link again,
though.
> website: Fix a stray broken link to 0.8 -> 0.9 backend upgrade doc

- terraform/eval_provider.go
- terraform/execute.go
- terraform/node_module_variable.go
- terraform/node_output.go
- terraform/node_provider.go
- terraform/node_resource_abstract.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/node_resource_destroy_deposed.go
- terraform/node_resource_plan_instance.go
- terraform/node_resource_validate.go
- terraform/transform_import_state.go
- terraform/update_state_hook.go
- terraform/update_state_hook_test.go
- terraform/upgrade_resource_state.go
This is a purely mechanical refactor PR: I de-exported a few more
functions which did not need to be exported in the first place, and
fixed a few outdated log outputs.
> terraform: final eval-related cleanup

- backend/local/backend_apply_test.go
- backend/local/backend_local.go
The option is set in the same place for plan and apply.
Fixes #27228
> set SkipRefresh for plan and apply

- command/webbrowser/native.go
- go.mod
- go.sum
The upstream bug with opening a browser on Windows Subsystem for Linux has been fixed, so this reverts our local patch for this. [The approach upstream](https://github.com/pkg/browser/pull/26) adds fallback support for `x-www-browser` and `www-browser` if `xdg-open` fails, and this fixes the problem on WSL installations of common Linux distros.
This reverts commit 12e090ce48f17e970cd7ba5de129f638ae296303.
Tested (using `terraform login`) on Windows 10, both the windows/amd64 build with cmd.exe and Powershell and the linux/amd64 build on WSL with Ubuntu 18.04.
> command: Revert local patch for pkg/browser

- lang/funcs/collection.go
- lang/funcs/collection_test.go
The `alltrue`/`anytrue` functions did not correctly handle unknown values. This commit changes these functions so that the result is unknown if:
- The list argument is unknown
- For `alltrue`: any elements are unknown
- For `anytrue`: any elements are unknown and no known elements are true
The last change is a little subtle, so there are test cases to cover it specifically. Examples:
- `anytrue(unknown)` = `unknown`
- `anytrue(false, unknown)` = `unknown`
- `anytrue(false, unknown, true)` = `true`
Intended for backport to a future 0.14 patch release.
Fixes #27236
> lang/funcs: Fix alltrue/anytrue with unknowns

- command/init.go
- internal/getproviders/didyoumean.go
- internal/getproviders/didyoumean_test.go
- internal/providercache/installer.go
(This is part of #27129, though it won't close it immediately. See below for a follow-up PR I plan to do to add an extra hint for v0.14 in particular.)
If a user forgets to specify the source address for a provider, Terraform will assume they meant a provider in the `registry.terraform.io/hashicorp/` namespace. If that ultimately doesn't exist, we'll now try to see if there's some other provider source address recorded in the registry's legacy provider lookup table, and suggest it if so.
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
hashicorp/mysql: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/mysql
Did you intend to use terraform-providers/mysql? If so, you …
```
> command/init: Hint about providers in other namespaces

- terraform/eval_count.go
- terraform/eval_count_test.go
When evaluating count values, we need to unmark the cty value before passing the value for conversion into a go int value.
This PR adds a test file/some coverage for the `evaluateCountExpression` function, but selfishly limits this addition to the basic level pluss adding a test case specific to this marking.
> Unmark values in count before go conversion

- command/init.go
- internal/getproviders/didyoumean.go
- internal/getproviders/didyoumean_test.go
- internal/providercache/installer.go
This is a v0.14 backport of #27227, with the addition of an additional hint about how working through the v0.13 upgrade guide might help resolve this error for folks who tried to skip directly from v0.12 to v0.14.
As noted in the other PR, my intent is for this temporary hint about v0.13 upgrade guide to only live through the v0.14 series, but for the rest of this message to remain as a general hint aimed at folks who are writing new modules for the first time and just forgetting to specify provider source addresses, rather than those who are bulk-upgrading existing configurations from earlier versions.
The additional paragraph this adds is the following:
```
If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to v0.13 first and follow the …
```
> v0.14 backport: Hint about missing providers that were renamed into different namespaces for v0.13

- lang/funcs/collection.go
- lang/funcs/collection_test.go
Fixes error when calling sum with values not known until apply time. Also allows sum to cope with numbers too large to represent in float64, along with correctly handling errors when trying to sum opposing infinities.
Fixes #27216. See comment in linked issue for why this commit is larger than just the `IsKnown`/`IsWhollyKnown` change.
Targeting an 0.14 patch release.
> lang: Improved robustness of sum function

- terraform/eval_context_mock.go
- terraform/node_provider.go
- terraform/node_provider_test.go
If there is no "provider" block present in the configuration at all,
errors related to missing required arguments lack source information or
even a reference to the provider in question. This PR adds more specific
error messages in three of these situations:
- ValidateProvider
- ConfigureProvider: provider.PrepareProviderConfig
- ConfigureProvider: ctx.ConfigureProvider
To test the last case I added a ConfigureProviderFn to the MockContext.
Closes #20121, #26707, #23087
> terraform: improve provider config related error messages

- command/console.go
Expressions such as "path.root" were returning the cwd (or modulePath),
instead of the usual _relative_ path. This commit normalizes the path
before building the context.
Closes #26813
> console: normalize module path before building context

- command/testdata/validate-invalid/incorrectmodulename/output.json
- command/testdata/validate-invalid/interpolation/output.json
- command/testdata/validate-invalid/missing_defined_var/output.json
- command/testdata/validate-invalid/missing_quote/output.json
- command/testdata/validate-invalid/missing_var/output.json
- command/testdata/validate-invalid/multiple_modules/output.json
- command/testdata/validate-invalid/multiple_providers/output.json
- command/testdata/validate-invalid/multiple_resources/output.json
- command/testdata/validate-invalid/output.json
- command/testdata/validate-invalid/outputs/output.json
- command/testdata/validate-valid/output.json
- command/validate_test.go
Also uncomment and fix some tests which had been skipped for a couple of years. Those validate cases work now!
Note that these test cases and the JSON output are not especially minimized, making them snapshot/golden tests. The output looks correct at time of writing, and we don't expect to change validate significantly any time soon, but if we do there will be some churn here.
> command: Add tests for terraform validate -json

- website/docs/configuration/data-sources.html.md
Trying to find a way to better document the implied `depends_on` behavior with data resources, as seen in #27171. 
This behavior was re-introduced in order to satisfy #25961, and remain compatible with a large base of existing provider acceptance tests. The original behavior however only worked on the first apply, and could return incorrect results on subsequent changes. Making this work in all cases has the unfortunate side effect of causing data sources to be deferred until apply far more often, hence the workaround presented here.
> add implied data depends_on caveat

- command/state_list_test.go
- command/state_meta.go
- command/testdata/state-list-nested-modules/terraform.tfstate
- website/docs/commands/state/list.html.md
A few distinct bugs fixed in here:
There was a bug in the logic checking if a given module was the child of
the targetAddr, now fixed. That resolved the basic issue where resources
in nested submodules were not listed.
The logic around `allowMissing` needed some tweaking to allow for empty
modules, as long as those modules had submodules with resources. `state
list` is the only command using `allowMissing` with `false`, so this felt safe
to do.
Finally I extended the logic so `state list` would included expanded modules,
when given a module instance, so for e.g. `list module.foo` would result in resources from
`module.foo[1]`, `module.foo[0]`, etc.
Fixes #26191
> command/state list: list resources in nested and expanded modules

- terraform/evaluate.go
Add checks for double marking elsewhere in the evaluate code -- this is tough to test for, so submitting this as a cautionary patch, carrying the fix for https://github.com/hashicorp/terraform/pull/27131 over to output values without waiting for a bug report of "how" this can happen.
> Guard against double marking in other locations in evaluate

- website/docs/configuration/expressions/function-calls.html.md
When passing around sensitive data with the new 0.14 "sensitivity follows values" behavior, we don't have it documented that that behavior results in sensitive results when using many functions in Terraform, so add a note about this.
Closes #27239
Closes https://github.com/hashicorp/terraform/issues/27180
> (docs) Document sensitivity + function call behavior

- tools/terraform-bundle/README.md
- tools/terraform-bundle/package.go
Update the `terraform-bundle` tool documentation to use the [correct default location](https://github.com/hashicorp/terraform/blob/master/tools/terraform-bundle/package.go#L31) where the tool will find custom provider plugins.
Consider the following bundle HCL:
```
terraform {
version = "0.13.5"
}
providers {
aws = {
versions = ["~> 2.0"]
}
yaml = {
versions = ["2.1"]
source = "providers.local/myorg/yaml"
}
}
```
According to the current README, I should have a tree folder that looks as such:
```
$ tree -a
.
├── bundle.hcl
└── plugins
└── providers.local
└── myorg
└── yaml
└── 2.1
└── linux_amd64
└── terraform-provider-yaml_v2.1.0-linux-amd64
```
Attempting to build this bundle fails, as `terraform-bundle` does not look in `./plugins` by default:
```
$ terraform-bundle package …
```
> correct terraform-bundle default plugins dir docs

- terraform/context_plan_test.go
- terraform/node_resource_plan_orphan.go
- terraform/transform_provider.go
Because of the composition pattern used within core, we can't easily remove a behavior from an embedded type. Rather than trying to re-implement all necessary methods on the `NodePlannableResourceInstnaceOrphan` to exclude orphaned data resources from `GraphNodeProviderConsumer`, we can modify `ProvidedBy` to indicate when there is no provider required.
Overloading the meaning of the returned values of this method is definitely not optimal, but it already requires careful handling due to it being overloaded in this way. It also is only called in one location, and immediately checked for the new condition. This seems overall safer than the alternatives of yet another optional interface, or proxying all required methods which are not guaranteed to be statically checked and can be missed. …
> modify ProvidedBy to indicate no provider needed for orphaned data sources

- website/docs/configuration/meta-arguments/for_each.html.md
Move limitations from a note to their own section, to allow for expansion on disallowing sensitive values
in for_each. This is to try and help users who might run into unexpected errors when trying to use a sensitive value as an argument to for_each, or might be confused when they have run a sensitive value through a function but are still getting an error (this is expected, as functions with sensitive arguments return sensitive results, currently).
> [docs] Add limitations section to for_each 

- terraform/eval_for_each.go
- terraform/eval_for_each_test.go
This adjusts the previous behavior that would disallow _any_ value involving marks to `for_each` to be more nuanced, and allow maps and objects where the keys are unmarked strings to pass through this evaluation unscathed.
If the keys of an object are marked, a [cty] panic will occur when evaluating the expression, but there's an HCL PR to turn that into an error.
This is related to #27239, but does not fix it, a function call is used in the expression, and function calls always result in marked values when passed any marked arguments (docs PR that clarifies this: https://github.com/hashicorp/terraform/pull/27280) currently, since no functions are marks-aware at present.
Also related to #27180 but does not fix it, for the same reason (function calls).
> Allow for_each arguments containing sensitive values if they aren't keys

- terraform/context_plan_test.go
- terraform/marks.go
- terraform/marks_test.go
- terraform/node_resource_abstract_instance.go
When comparing marks for values during plan and apply, we need to ensure the order of the marked paths is consistent. Since the marks themselves were not ordered, we would occasionally turn `NoOp` plans to `Update` when there was no change to the values or sensitivity. This could then cascade through the plan causing numerous changes to appear with no clear cause.
Fixes #27287
> Correctly compare unordered sets of marks

- terraform/context_plan_test.go
- terraform/eval_apply.go
- terraform/eval_diff.go
- terraform/marks.go
- terraform/marks_test.go
> v0.14 backport of #27318

- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/context_test.go
Isolate the test schema expansion, because having NestingSet in the schema actually necessitates [] values in the AttrsJson.
While this didn't fail any tests on its addition, that is scary and so isolate this to the one test using it.
This block was added in https://github.com/hashicorp/terraform/pull/26379/, but the fact that it is actually more of a sweeping change than expected was discovered recently, which necessitated the change (that has been reverted) in `TestContext2Plan_noSensitivityChange` and `TestContext2Apply_variableSensitivityChange`
> [tests] Roll back test schema expansion and isolate

- backend/remote/backend.go
- backend/remote/backend_apply_test.go
Terraform remote version conflicts are not a concern for operations. We are in one of three states:
- Running remotely, in which case the local version is irrelevant;
- Workspace configured for local operations, in which case the remote version is meaningless;
- Forcing local operations with a remote backend, which should only happen in the Terraform Cloud worker, in which case the Terraform versions by definition match.
This commit therefore disables the version check for operations (plan and apply), which has the consequence of disabling it in Terraform Cloud and Enterprise runs. In turn this enables Terraform Enterprise runs with bundles which have a version that doesn't exactly match the bundled Terraform version.
Intended for back-port to 0.14 for an upcoming release.
> backend/remote: No version check for operations

- website/docs/configuration/expressions/index.html.md
not "references.html" but "operators.html".
> website: Fix wrong link of operators.

- backend/remote/backend.go
- backend/remote/backend_test.go
If the remote backend is connected to a Terraform Cloud workspace in local operations mode, we disable the version check, as the remote Terraform version is meaningless.
Fixes #27353.
> backend/remote: No version check for local ops

- terraform/node_resource_validate.go
- terraform/node_resource_validate_test.go
There was a special, duplicate function that could be replaced by calling evaluateCountExpressionValue, and removes duplicate code. The diff here may be confusing to read inline, but reading the raw file or splitting the diff makes the change fairly clear.
Fixes #27403.
> De-duplicate count validate code

- terraform/context_plan_test.go
- terraform/eval_variable.go
- terraform/testdata/validate-variable-custom-validations-child-sensitive/child/child.tf
- terraform/testdata/validate-variable-custom-validations-child-sensitive/validate-variable-custom-validations.tf
Binding a sensitive value to a variable with custom validation rules would cause a panic, as the validation expression carries the sensitive mark when it is evaluated for truthiness. This commit drops the marks before testing, which fixes the issue.
Fixes #27375
> core: Fix sensitive value variable validation

- website/docs/backends/types/remote.html.md
This variable mechanism was replaced long ago with a explicit `Allow destroy plans` setting on a Terraform Cloud workspace, and no longer does anything: https://www.terraform.io/docs/cloud/workspaces/settings.html#destruction-and-deletion
Rather than mention this new mechanism at all though, I've removed the requisite from here entirely - the reason being that a consideration like this is hardly different from other permission concerns (e.g. "You must have Apply permission on a workspace to `apply`"), and without enumerating _all_ of these here - which doesn't seem appropriate - we just remove this concern entirely.
> Remove documentation on 'CONFIRM_DESTROY'

- go.mod
- go.sum
Several bug fixes for operations with sensitive values. Fixes #27329. Fixes #27336.
* hclsyntax: Fix panic for marked collection splat. ([#436](https://github.com/hashicorp/hcl/pull/436))
* hclsyntax: Fix panic for marked template loops. ([#437](https://github.com/hashicorp/hcl/pull/437))
* hclsyntax: Fix `for` expression marked conditional.([#438](https://github.com/hashicorp/hcl/pull/438))
* hclsyntax: Mark objects with keys that are sensitive. ([#440](https://github.com/hashicorp/hcl/pull/440))
> Upgrade HCL to v2.8.2

- terraform/context_refresh_test.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/node_resource_destroy_deposed.go
- terraform/schemas.go
- terraform/transform_import_state.go
- terraform/transform_provider.go
- terraform/transform_vertex.go
Fixes within the terraform package to remove staticcheck errors from running `staticcheck github.com/hashicorp/terraform/terraform`. 
The following notices were fixed:
- Makes error last return
- Unused value
- Unnecessary type transformation
- Errors are lowercase and don't end in punctuation
On the last item, it means that some error appearances will change:
```
Plugin reinitialization required. Please run "terraform init".
[... cut for brevity...]
2 problems:
- failed to instantiate provider "registry.terraform.io/hashicorp/unknown" to obtain schema: unknown provider "registry.terraform.io/hashicorp/unknown"
```
(These bulleted items are now lowercase)
> Staticcheck fixes in terraform package

- website/docs/commands/cli-config.html.markdown
On Windows, the file must be named named terraform.rc => On Windows, the file must be named terraform.rc
> Corrected minor typo

- command/jsonstate/state.go
- command/jsonstate/state_test.go
This is a proposed fix for #27351
> command: Fix terraform show not outputting child_modules properly in certain circumstances

- builtin/provisioners/file/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner_test.go
- builtin/provisioners/local-exec/resource_provisioner.go
- builtin/provisioners/local-exec/resource_provisioner_test.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner_test.go
The context used for `Stop` is more appropriately tied to the lifetime of
the provisioner rather than a call to the `ProvisionResource` method. In
some cases `Stop` can be called before `ProvisionResource`, causing a panic
in the provisioner.  Rather than adding nil checks to the `CancelFunc` call
for `Stop`, create a base context to use for cancellation with both `Stop`
and `Close` methods.
Fixes #27449
> provisioners: ensure context cancel is never nil in builtin provisioners

- backend/local/backend_plan_test.go
- backend/local/testdata/destroy-with-ds/main.tf
- terraform/context.go
- terraform/context_apply_test.go
- terraform/graph_builder_destroy_plan.go
- terraform/node_resource_abstract_instance.go
- terraform/testdata/apply-destroy-data-cycle/main.tf
- terraform/testdata/apply-destroy-data-resource/main.tf
- terraform/testdata/plan-module-destroy-gh-1835/b/main.tf
Because the destroy plan only creates the necessary changes for apply to
remove all the resources, it does no reading of resources or data
sources, leading to stale data in the state. In most cases this is not a
problem, but when a provider configuration is using resource values, the
provider may not be able to run correctly during apply. In prior
versions of terraform, the implicit refresh that happened during
`terraform destroy` would update the data sources and remove missing
resources from state as required.
The destroy plan graph has a minimal amount of information, so it is not
feasible to work the reading of resources into the operation without
completely replicating the normal plan graph, and updating the plan
graph and all destroy node implementations is also a considerable …
> Refresh during destroy

- command/init.go
[these were flagged for removal in the command audit, I'm going to describe what I think the reasoning is]
The state lock flags are not relevant in the `init` flow, and are thus removed.
> Remove state lock flags from init

- command/init.go
The `-verify-plugins` flag does not do anything, and so remove the parsing of the flag variable and the mention in the CLI docs.
> Remove verify-plugins flag

- command/init.go
- website/docs/commands/init.html.markdown
Remove the no-op get-plugins flag, this follows through on a deprecation notice released in the 0.14 series.
> Remove get-plugins flag

- repl/format.go
- repl/format_test.go
Recent changes to the human-readable rendering of outputs and console values led to long integer values being presented in scientific notation (e.g. 1.2345678e+07). While technically correct, this is an unusual way to present integer values.
This commit checks if a number value is an integer, and if so renders it as a sequence of digits instead (e.g. 12345678).
Fixes #27438.
> cli: Fix rendering of long integers

- website/docs/configuration/functions/templatefile.html.md
Reference file in Maps example is named config.tmpl, example references non existent file called backend.tmpl,
likely a cut and paste error from the above example.
> Chage backend.tmpl to config.tmpl in Maps example,

- website/docs/configuration/variables.html.md
This PR updates the documentation of input variable of terraform. It's
mentioned that multiple `-var` is possible, but no example is given.
This PR adds an example of multiple `-var` option
> website: add example of multiple var cli

- .tfdev
- command/version.go
- command/version_test.go
- commands.go
- main.go
- scripts/build.sh
- version.go
The revision field is only populated on dev builds so this means most releases of Terraform have an empty "terraform_revision" field in the JSON output. Since we recommend developers use go tooling to `go build` this tool when developing, the revision is not useful data and so it is removed.
The `.tfdev` file is for people who use the [internal] terraform-devtool, and I checked to ensure this removal wouldn't break users who depend on that -- it appears not to (the value going into the devtool should be nil now).
> Remove revision from version command

- website/docs/cli/plugins/index.html.md
- website/docs/commands/version.html.markdown
- website/layouts/docs.erb
The version command, although not the mightiest of our commands, did not have a page among our docs. This means that it's not present on the site in the alphabetical listing of commands.
> Add documentation page for version

- terraform/context_apply_test.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/node_resource_destroy_deposed.go
The error handling here was very convoluted, passing multiple error values and error pointers around, which was a remnant of the old eval-node pattern. This caused diagnostics to be dropped in some cases, and made the code extremely fragile in general.
Get rid of the separate error parameters and return value in the apply methods, and reorganize the diagnostic handling to use a single set of diagnostics that flows through each Execute method.
> Fix error handling in instance apply methods

- command/state_mv.go
- command/state_mv_test.go
This updates the error when running `state mv resource.foo resource.foo[1]`, where the destination is not a whole resource, have a more helpful error to encourage the user to consider if they meant to use instance addresses throughout (or whole resource addresses throughout).
The addresses previously used in these errors were allocated from type checking that had previously proven that they couldn't be typecast to that type (`!ok`) so this changes all error locations to use `destAddr` throughout.
Before
```
Error: Invalid target address
Cannot move test_instance.foo to <invalid>..: the target must also be
a whole resource.
```
After:
```
Error: Invalid target address
Cannot move test_instance.foo to test_instance.bar[0]: the source is a whole
resource (not a resource instance) so the …
```
> Make errors in state mv more accurate

- backend/cli.go
- backend/local/backend.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- backend/local/cli.go
- command/e2etest/primary_test.go
- command/format/diagnostic.go
- command/format/diagnostic_test.go
- command/format/trivia.go
- command/meta.go
- command/meta_backend.go
- command/show.go
- command/state_mv_test.go
- commands.go
- go.mod
- go.sum
- internal/terminal/impl_others.go
- internal/terminal/impl_windows.go
- internal/terminal/panicwrap_ugh.go
- internal/terminal/stream.go
- internal/terminal/streams.go
- main.go
Since very early versions of Terraform we've been supporting colored output from our CLI in the Microsoft Windows console using [go-colorable](https://github.com/mattn/go-colorable), which aims to translate in-band virtual terminal sequences into out-of-band classic Windows Console API calls interspersed with calls to write literal characters to the terminal filehandle.
For several years now Windows 10 updates have supported xterm-style virtual terminal sequences in the Windows console, but only after opting in. Somewhat recently we updated `go-colorable` in #26588 to get a version which would make use of that mechanism if available, but we retained the existing translation layer for console windows where VT mode wasn't available, particularly on Windows 8. However, that effectively meant …
> Require xterm-style virtual terminal on all platforms, including Windows

- terraform/context_apply_test.go
- terraform/context_input_test.go
- terraform/context_plan_test.go
- terraform/context_refresh_test.go
- terraform/context_validate_test.go
- terraform/node_resource_abstract_instance.go
- terraform/terraform_test.go
Remove all calls to the old `testDiffFn` and `testApplyFn` functions in preference for the simpler default behavior, when the test does not specifically rely on the old behavior. 
One additional check check was added to the apply codepath, we now generate an error if the provider returns an invalid nil value during `ApplyResourceChange`. This check was not done previously due to extent it would break the old context tests, but the updated mocks are no longer affected.
> Context test updates

- command/taint.go
- command/taint_test.go
Show the resource name in the warning when allow-missing is used and no resource matches.
> Show resource name in taint -allow-missing warning

- command/untaint.go
- command/untaint_test.go
Ensure the name shows when running `untaint -allow-missing`
> Add name to untaint missing warning

- command/meta_backend.go
After verifying the remote backend workspace version is compatible with the local Terraform version, we need to record that this check was successful. Otherwise [the fallback error handling path will run a strict version check](https://github.com/hashicorp/terraform/blob/dcf49dc7dd8248cb75799279adbbd8654de3e8f5/backend/remote/backend.go#L638-L650), even if the versions are compatible, which will cause an unexpected failure.
The result of this bug was that compatible remote and local Terraform versions (e.g 0.14.2 and 0.14.4) were prevented from working with commands like `taint`, `import`, `state mv` and so on, unless you use the `-ignore-version-check` override. The same is true for incompatible remote and local versions (e.g. 0.13.5 and 0.14.4) for workspaces in "local" operations mode. …
> cli: Fix double check of remote workspace version

- terraform/context_plan_test.go
- terraform/node_output.go
The planning logic here was inspired by resources, but unlike resources
a null value is valid for an output and does not necessarily indicate it
is being removed. If both before and after are null, the change should
be NoOp. When an output is removed from the configuration, we have a
separate node to create a Delete action to remove it from the state.
Rather than using a prior value of null to indicate Create, which is
imprecise because null is a valid output value, only plan values that
didn't exist in the prior state as Create changes.
Fixes #27490
> Create and Delete actions for output plans

- command/e2etest/init_test.go
- command/format/diagnostic.go
- command/format/diagnostic_test.go
- command/meta.go
- command/state_mv_test.go
- command/taint_test.go
- command/untaint_test.go
I frequently see people attempting to ask questions (e.g. in the community forum) about Terraform's error and warning messages but either only copying part of the message or accidentally copying a surrounding paragraph that isn't part of the message.
While I'm sure some of these are just "careless" mistakes, I've also noticed that this has sometimes overlapped with someone asking a question whose answer is written directly in the part of the message they didn't include when copying, and so I have a theory that our current output doesn't create a good enough visual hierarchy for sighted users to understand where the diagnostic messages start and end when we show them in close proximity to other content, or to other diagnostic messages. As a result, some folks fail to notice the relevant …
> command: Better visual hierarchy for diagnostics

- .circleci/config.yml
- Makefile
This adds a CI job for running the new PR link checker for documentation.
[terraform-website PR 1574](hashicorp/terraform-website#1574)
added a new link checking CI job specifically for warning about broken links in
pull requests. This link checker is optimized for:
- Running (relatively) quickly.
- Only reporting on files that were changed in the current PR, to avoid spamming
you with problems you had nothing to do with.
- Being transparent and simple to maintain. (Note that this is in conflict with
minimizing false positives/negatives! We try to give very few of both, but
completely eliminating them would result in an unaffordable maintenance
burden. We expect that some PRs will be merged with this job red.)
The tool is somewhat specific to our Middleman site builder, and we expect it …
> CI: Add broken link checking job for website content

- command/meta_backend_migrate.go
Previously the state migration process was using the fallback strict error check when migrating to or from a Terraform Cloud workspace. This resulted in an error when running init if the local and remote Terraform versions did not exactly match.
This was excessively strict. When migrating from a remote Terraform Cloud workspace to local state, there is no need for a version check at all, as we cannot break the Terraform Cloud workspace. When migrating to Terraform Cloud, we should use the more forgiving check, rather than the strict equality.
This commit fixes both of these cases accordingly, and allows migrating state to and from Terraform Cloud remote workspaces without errors.
Fixes #27543
> cli: Fix state migration remote version check

- terraform/context_plan2_test.go
- terraform/eval_diff.go
fix null check for tainted state during plan
The tainted state was checked against `cty.NilVal`, however it was
always being set to a null value.
Backport of #27563
> 0.14 backport of 27563

- terraform/context_plan2_test.go
- terraform/node_resource_abstract_instance.go
When planning a data source change, the object compatibility verification step should be performed with unmarked values. This value is transient and preserving marks is not necessary, and the object change code is not fully marks-aware.
Fixes #27565
I intend to backport to 0.14, although I expect the cherry pick robot will fail due to changes in this package on the main branch.
> core: Fix crash for marked data source prior value

- CHANGELOG.md
- terraform/context_plan2_test.go
- terraform/eval_read_data_plan.go
When planning a data source change, the object compatibility verification step should be performed with unmarked values. This value is transient and preserving marks is not necessary, and the object change code is not fully marks-aware.
Fixes #27565, backport of #27567
> Backport of core: Fix crash for marked data source prior value into v0.14

- internal/getproviders/filesystem_search.go
Hello
Fixes https://github.com/hashicorp/terraform/issues/27445.
Instead of raising and error, it display a warning (TF_LOG=trace) and continue analyzing the next providers.
Cheers
Romain
> Providers: Fix init with broken link in plugin_cache_dir

- command/state_pull.go
- website/docs/cli/commands/state/pull.html.md
Some users expect the `state pull` subcommand to retrieve the state file directly from the remote backend and output it unchanged, allowing them to use `jq` to inspect the remote state's Terraform version. Since Terraform upgrades the state on load, this is not the case, which causes confusion.
Changing the behaviour of `state pull` is not a simple task, and is being tracked in enhancement request #25866. For now, I think we can be clearer in the documentation about what `state pull` does, which will hopefully avoid this confusion.
Fixes #27555
> docs: Note that state pull upgrades the state file to current version

- internal/providercache/installer.go
- internal/providercache/installer_test.go
In init, we can check to see if the target dir already has the provider we are seeking and skip further querying/installing of that provider.
This will help address concerns users are having where they've previously installed a provider (ex. that is in their `.terraform` directory after install) and subsequent installs keep re-fetching the package. While we've been telling users this installation is expected behavior, I think we can make a nicer flow by making things faster by re-using that same provider if it's already installed.
Closes #27534
> Reuse installed target dir providers in init

- command/untaint.go
- website/docs/cli/commands/untaint.html.md
This option is an error, and is removed from the docs for taint.
This does the same docs removal for untaint, without changing the current error behavior.
> Remove -module from docs for untaint

- command/taint.go
- command/untaint.go
- website/docs/cli/commands/untaint.html.md
This has been an error with help text, and can be removed. A "while I was here" to update the usage text for `-allow-missing` is here as well.
The `untaint` command currently has this option in its help string and its web docs, and I'll be opening a v0.14 specific PR for that.
> Remove -module option for taint and untaint

- command/state_mv.go
- command/state_mv_test.go
Update the state mv help docs, there were rogue tab characters causing non-preferred formatting.
Adds a test to make sure that this text doesn't accidentally get tabs added, without having a test that simply direct matches the whole strings (which would be brittle to adding a tab to the test validation)
Before:
After:
> Update state mv help docs to use spaces instead of tabs

- .github/CONTRIBUTING.md
- backend/local/backend_apply.go
- backend/local/backend_plan.go
- backend/local/testing.go
- backend/remote-state/http/client.go
- builtin/provisioners/local-exec/resource_provisioner.go
- command/cliconfig/config_unix.go
- command/command_test.go
- command/console.go
- command/init.go
- command/meta_backend.go
- command/meta_backend_migrate.go
- command/plan_test.go
- command/state_push_test.go
- communicator/communicator.go
- communicator/ssh/communicator.go
- communicator/ssh/ssh_test.go
- dag/walk.go
- internal/helper/wrappedstreams/streams.go
- internal/legacy/helper/schema/schema.go
- internal/logging/logging.go
- main.go
- main_test.go
While setting up terraform on a new computer, I ran into this verbiage:
> Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.
Which should be (emphasis added to show the change).
> Changes to backend configurations require reinitialization. This allows
Terraform to **set up** the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.
So while changing that, I also changed the other instances of "setup" when used as a verb, to be properly spelled as "set up".  Note this is purely a documentation change, except in the case of two error …
> Grammar nit: "setup" as a verb should be spelled "set up"

- command/e2etest/init_test.go
- command/e2etest/strip_ansi.go
- command/format/diagnostic.go
- command/format/diagnostic_test.go
- command/format/state_test.go
- command/meta.go
- command/state_mv_test.go
- command/taint_test.go
- command/untaint_test.go
Commit e865faf adds visual indentation for diagnostic messages using various vertical line characters. This PR disables this behaviour when running in automation, adding `format.DiagnosticPlain` to preserve the legacy behaviour.
While the contents of stderr are not intended to be part of the Terraform API, this is currently how terraform-exec detects certain error types in order to present them as well-known Go errors to the user. Such detection is complicated when vertical lines are added to the CLI output at unpredictable points.
I expect this change will also be helpful for screen reader users.
> Disable visual error hierarchy in -no-color mode

- command/state_mv_test.go
Missing import appeared due to base branch drift when merging https://github.com/hashicorp/terraform/pull/27536.
> Fix command/state_mv_test.go

- command/apply.go
- command/output.go
- command/output_test.go
- command/refresh.go
The `-module` flag to `terraform output` has been unimplemented since 0.12 (removed in 025540789). This commit removes some dead code and the specific error message for this flag.
[The website documentation for `output`](https://www.terraform.io/docs/cli/commands/output.html) does not mention this flag, so it is unchanged.
> cli: Remove dead code for output -module flag

- command/import.go
- command/meta.go
- command/state_mv.go
- command/state_replace_provider.go
- command/state_rm.go
- command/taint.go
- command/untaint.go
Update docstring for ignore-remote-version to be more accurate, as it's not whether the versions differ, but if they are incompatible
> Update docstring for ignore-remote-version

- terraform/context_plan2_test.go
- terraform/node_resource_plan_orphan.go
When removing data source instances via alterations to a `for_each` value, the orphaned instance must be removed from both the refresh state, and the working state.  While the `refreshState` represents what the data source is currently, plan-time evaluations will still happen against the working state.
Fixes #27617
This will require a manual backport for 0.14
> removed orphaned data sources from the working state

- terraform/context_plan2_test.go
- terraform/node_resource_plan_orphan.go
When evaluating orphaned data sources during plan, they need to be
removed from both the refresh state and the current working state.
0.14 backport of #27621
> removed orphaned data sources from the state

- terraform/context_plan_test.go
- terraform/node_output.go
Backport #27512.
This was not immediately queued for backport, but applies cleanly and addresses a 0.14 specific issue.
> 0.14 backport of 27512

- command/apply.go
- command/e2etest/provider_dev_test.go
- command/init.go
- command/meta_providers.go
- command/validate.go
Reference: https://github.com/hashicorp/terraform/issues/27459
Reference: https://github.com/hashicorp/terraform/pull/27507
This follows the change in the plan command to move the development overrides warning above other output from the command that may exhibit unexpected behavior.
> command: Use different warning messaging in init command and move above potentially confusing output

- go.mod
- go.sum
Changes:
```
* backend/s3: Support for AWS Single-Sign On (SSO) cached credentials
```
Updated via:
```
go get github.com/aws/aws-sdk-go@v1.37.0
go mod tidy
```
Please note that Terraform CLI will not initiate or perform the AWS SSO login flow. It is expected that you have already performed the SSO login flow using AWS CLI using the `aws sso login` command, or by some other mechanism before executing Terraform. More precisely, this credential handling must find a valid non-expired access token for the AWS SSO user portal URL in `~/.aws/sso/cache`. If a cached token is not found, is expired, or the file is malformed an error will be returned.
You can use configure AWS SSO credentials from the AWS shared configuration file by specifying the required keys in the profile:
```
sso_account_id …
```
> deps: Bump github.com/aws/aws-sdk-go@v1.37.0

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
This is needed for cases where a variable may be fetched and become a member of a set, and thus the whole set is marked, which means ElementIterator will panic on unmarked values.
Fixes https://github.com/hashicorp/terraform/issues/27596
> Unmark values in couldHaveUnknownBlockPlaceholder before iteration

- command/apply.go
- command/apply_test.go
- command/command.go
- command/console.go
- command/console_test.go
- command/get_test.go
- command/graph.go
- command/graph_test.go
- command/init.go
- command/init_test.go
- command/plan.go
- command/plan_test.go
- command/refresh.go
- command/refresh_test.go
- command/unlock.go
- command/unlock_test.go
- command/workspace_delete.go
- command/workspace_list.go
- command/workspace_new.go
- command/workspace_select.go
- website/docs/cli/commands/graph.html.md
Several commands continued to support the legacy positional path argument to specify a working directory. This functionality has been replaced with the global `-chdir` flag (#26087), which is specified before any other arguments, including the sub-command name.
This commit removes support for the trailing path parameter from most commands. The only command which still supports a path argument is `fmt`, which also supports "-" to indicate receiving configuration from standard input.
Any invocation of a command with an invalid trailing path parameter will result in a short error message, pointing at the `-chdir` alternative.
There are many test updates in this commit, almost all of which are migrations from using positional arguments to specify a working directory. Because of the layer at …
> cli: Remove legacy positional path arguments

- backend/backend.go
- backend/local/backend_apply.go
- backend/remote/backend_apply.go
- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
This dramatically simplifies the logic around auto-approve, which is nice.
Also add test coverage for the manual approve step, for both apply and destroy, answering both yes and no.
> cli: Remove deprecated destroy -force flag

- website/docs/language/data-sources/index.html.md
This adds a link to the new tutorial: [Query data sources](https://learn.hashicorp.com/tutorials/terraform/data-sources?in=terraform/configuration-language).
> Add crosslink to new Learn tutorial

- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
[The previous changes removing support for using the trailing positional argument as a working directory](https://github.com/hashicorp/terraform/pull/27664) missed a spot in the `apply`/`destroy` command implementation. We still support this argument for applying a saved plan:
terraform apply foo.tfplan
However, if you pass a positional path which doesn't "look like" a plan (for example, the path to a configuration directory), Terraform would silently ignore it and continue.
This commit fixes that by adding an error message if the user specifies a path which the plan loader rejects as not "looking like" a plan. This message includes a reference to the `-chdir` flag as a pointer about what to do next.
We also rearrange the error message when calling `terraform destroy` with a plan file …
> cli: Better diagnostics for apply positional args

- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
- command/flag_kv.go
- command/meta.go
- command/plan.go
- command/plan_test.go
- command/refresh.go
- command/refresh_test.go
- command/testdata/apply-destroy-targeted/main.tf
- command/testdata/apply-targeted/main.tf
- command/testdata/refresh-targeted/main.tf
Errors encountered when parsing flags for apply, plan, and refresh were being suppressed. This resulted in a generic usage error when using an invalid `-target` flag.
This commit makes several changes to address this. First, these commands now output the flag parse error before exiting, leaving at least some hint about the error. You can verify this manually with something like:
terraform apply -invalid-flag
We also change how target attributes are parsed, moving the responsibility from the flags instance to the command. This allows us to customize the diagnostic output to be more user friendly. The diagnostics now look like:
Finally, we add test coverage for both parsing of target flags, and at the command level for successful use of resource targeting. These tests focus on the UI output …
> cli: Improve error for invalid -target flags

- internal/providercache/installer.go
- internal/providercache/installer_test.go
Emit the ProviderAlreadyInstalled event when we successfully verify that we've already installed this provider and are skipping installation.
Before:
```
$ terraform init
Initializing the backend...
- Reusing previous version of providerland/foo from the dependency lock file
Terraform has been successfully initialized!
```
After:
```
$ terraform init
Initializing the backend...
- Reusing previous version of providerland/foo from the dependency lock file
- Using previously-installed providerland/foo v0.0.8
Terraform has been successfully initialized!
```
> Emit ProviderAlreadyInstalled when provider installed

- internal/terminal/testing.go
This is to allow convenient testing of functions that are designed to work directly with `*terminal.Streams` or the individual stream objects inside.
Because the `InputStream` and `OutputStream` APIs expose directly an `*os.File`, this does some extra work to set up OS-level pipes so we can capture the output into local buffers to make test assertions against. The idea here is to keep the tricky stuff we need for testing confined to the test codepaths, so that the "real" codepaths don't end up needing to work around abstractions that are otherwise unnecessary.
> terminal: StreamsForTesting helper

- backend/remote/backend_common.go
When an error occurs during `terraform apply`, the _"Cost Estimation"_ output  appears, even though it shouldn't.
**See Screenshot**
There is nothing wrong with the specific conditions in the remote backend for cost estimations. Rather, the `CLI.Output` should appear further below depending on the `Status` returned from the `api/v2/cost-estimation` endpoint in the remote backend.
> Cost Estimation CLI output unnecessary

- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
- command/arguments/default.go
- command/arguments/output.go
- command/arguments/output_test.go
- command/arguments/types.go
- command/arguments/view.go
- command/arguments/view_test.go
- command/command_test.go
- command/meta.go
- command/meta_config.go
- command/output.go
- command/output_test.go
- command/refresh.go
- command/refresh_test.go
- command/views/output.go
- command/views/output_test.go
- command/views/view.go
- commands.go
Terraform supports multiple output formats for several sub-commands. The default format is user-readable text, but many sub-commands support a `-json` flag to output a machine-readable format for the result. The output command also supports a `-raw` flag for a simpler, scripting- focused machine readable format.
This commit adds a "views" abstraction, intended to help ensure consistency between the various output formats. This extracts the render specific code from the command package, and moves it into a views package. Each command is expected to create an interface for its view, and one or more implementations of that interface.
By doing so, we separate the concerns of generating the sub-command result from rendering the result in the specified output format. This should make it easier …
> cli: Add initial command views abstraction

- internal/terminal/streams.go
- internal/terminal/streams_test.go
It's pretty common to want to apply the various `fmt.Fprint...` functions to our two output streams, and so to make that much less noisy at the callsite here we have a small number of very thin wrappers around the underlying `fmt` package functionality.
Although we're aiming to not have too much abstraction in this `terminal` package, this seems justified in that it is only a very thin wrapper around functionality that most Go programmers are already familiar with, and so the risk of this causing any surprises is low and the improvement to readability of callers seems worth it.
> terminal: Helpers for doing fmt-ish operations on the streams

- plugin/convert/diagnostics.go
Right now, there's a bug that if a diagnostic comes back from the
provider with an AttributePath set, but no steps in the AttributePath,
Terraform _thinks_ it's an attribute-specific diagnostic and not a
whole-resource diagnostic, but then doesn't associate it with any
specific attribute, meaning the diagnostic doesn't get associated with
the config at all.
This PR changes things to check if there are any steps in the
AttributePath before deciding this isn't a whole-resource diagnostic,
and if there aren't, treats it as a whole-resource diagnostic, instead.
See hashicorp/terraform-plugin-sdk#561 for more details on how this
surfaces in the wild.
> Fix empty diags not getting associated with source.

- command/views/output.go
- command/views/view.go
A small, no-impact update to use the new streams helper functions from #27759.
> views: Use new streams helper functions

- backend/backend.go
- backend/local/backend.go
- backend/local/backend_apply.go
- backend/local/backend_apply_test.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- backend/local/backend_refresh.go
- backend/local/backend_refresh_test.go
- backend/local/cli.go
- backend/local/testing.go
- backend/remote/backend.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_plan_test.go
- backend/remote/cli.go
- backend/remote/testing.go
- command/apply.go
- command/meta_backend.go
- command/plan.go
- command/refresh.go
The enhanced backends (local and remote) need to be able to render diagnostics during operations. Prior to this commit, this functionality was supported with a per-backend `ShowDiagnostics` function pointer.
In order to allow users of these backends to control how diagnostics are rendered, this commit moves that function pointer to the `Operation` type. This means that a diagnostic renderer is configured for each operation, rather than once per backend initialization.
Some secondary consequences of this change:
- The `ReportResult` method on the backend is now moved to the `Operation` type, as it needs to access the `ShowDiagnostics` callback (and nothing else from the backend);
- Tests which assumed that diagnostics would be written to the backend's `cli.Ui` instance are migrated to …
> backend: Add per-operation diagnostic rendering

- command/jsonconfig/config.go
- command/testdata/show-json/provider-version-no-config/main.tf
- command/testdata/show-json/provider-version-no-config/output.json
- command/testdata/show-json/provider-version/main.tf
- command/testdata/show-json/provider-version/output.json
- configs/config.go
- configs/config_test.go
The JSON plan output format includes a serialized, simplified version of the configuration. One component of this config is a map of provider configurations, which includes version constraints.
Until now, only version constraints specified in the provider config blocks were exposed in the JSON plan output. This is a deprecated method of specifying provider versions, and the recommended use of a `required_providers` block resulted in the version constraints being omitted.
This commit fixes this with two changes:
- When processing the provider configurations from a module, output the fully-merged version constraints for the entire module, instead of any constraints set in the provider configuration block itself;
- After all provider configurations are processed, iterate over the …
> cli: Fix for missing provider requirements in JSON plan

- command/output_test.go
- command/views/output.go
- command/views/output_test.go
Now that the view code is separated, we can increase test coverage in unit tests. This commit moves some tests from the command package which were testing only view code, and adds more new test cases.
> views: Expand test coverage for views.Output

- backend/backend.go
- backend/local/backend_apply.go
- backend/local/backend_local.go
- command/apply.go
- command/apply_test.go
- command/import.go
- command/import_test.go
- command/meta.go
- command/plan.go
- command/plan_test.go
- command/refresh.go
- command/refresh_test.go
- command/show_test.go
- command/views/hook_ui.go
- command/views/hook_ui_test.go
Move the code which renders Terraform hook callbacks as UI into the views package, backed by a `views.View` instead of a `cli.Ui`. Update test setup accordingly.
To allow commands to control this hook, we add a hooks member on the backend `Operation` struct. This supersedes the hooks in the Terraform context, which is not directly controlled by the command logic.
There is a little bit of refactoring of the UI hook in this change:
- Use an explicit initializer instead of the calls to `h.once.Do(h.init)`, and rename some fields so that they are unexported
- Inline the locking around calls to `output`, rather than wrapping the entire `views.View` as was done with `cli.Ui`
I intentionally did not fix the misuse of `Color` on the entire output string rather than the format string in order to …
> cli: Migrate Terraform UI hook to command views

- communicator/ssh/communicator.go
- communicator/ssh/provisioner.go
- communicator/ssh/provisioner_test.go
- terraform/eval_validate.go
- website/docs/language/resources/provisioners/connection.html.md
Backport of #26865. Targeting 0.14.1 because we just missed the RC.
Changelog line:
```markdown
* communicator/ssh: Add support for Windows targets. The `remote-exec` provisioner now works correctly when connecting to Windows servers using SSH. Specify the `target_platform` as `"windows"` in the `connection` block. [GH-26865]
```
> communicator/ssh: Add support for Windows targets

- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
The call to TestConformance needs to be reversed, since we want to
verify that the actual value returned conforms to the planned type.
While the inverse (checking that the planned value conforms to the
applied type) works for everything terraform has been exposed to up
until now, this fails when the planned type has dynamic attributes which
are allowed to become concrete types.
> reverse call to TestConformance in objchange

- command/views/hook_ui.go
- command/views/hook_ui_test.go
Due to calling the `Colorize` function with the full string instead of the format string, plan/apply logs which include resource instance keys or IDs which happen to match color formatting would be rendered incorrectly.
This commit fixes this by only colorizing the known-safe format string. We also add full test coverage for the UI hook, although only one of the hooks is tested for this color bugfix due to verbosity of the test.
We also add the bold coloring to the provisioner output prefix, which seems to have been an oversight.
There is one other small change in this commit: we drop the `(generation)` suffix from the `PreApply` hook, because this appears to be unused. We only ever pass `states.CurrentGen` as the generation argument to this hook.
```hcl
variable "names" {
type = …
```
> cli: Fix misapplied terminal colors on run logs

- terraform/context_apply2_test.go
- terraform/node_resource_abstract_instance.go
The `PreApply` hook was always being called with a `nil` generation argument, instead of the deposed key of the resource (if present). This commit passes the deposed key from the change to the `PreApply` hook, and adds a context test to cover this.
The resulting behavior of Terraform after this change makes sense to me, but I'm not completely confident that this is the right fix. Below is my understanding of what this changes.
Apply logs now display the generation of any resource which is destroyed as a result of a `create_before_destroy` setting. For example, with this configuration:
```hcl
resource "random_id" "foo" {
byte_length = 16
keepers = { uuid = uuid() }
lifecycle {
create_before_destroy = true
}
}
```
Repeated applies now look like:
```shellsession
$ terraform apply …
```
> terraform: Fix missing deposed key for PreApply

- website/docs/language/meta-arguments/module-providers.html.md
- website/docs/language/modules/develop/providers.html.md
- website/docs/language/providers/configuration.html.md
Remove references to the "proxy configuration block" concept, and add
examples showing the usage of `configuration_aliases`.
> update docs for configuration_aliases

- command/apply_test.go
Extra declaration, probably from a bad merge. Fixing!
> [tests] Remove duplicate declaration

- backend/remote-state/azure/client.go
Fix for bug desribed in #27511. Value of `blob.Response.Response` could be `nil` if error occurred on early stages of calling `c.giovanniBlobClient.Get(...)` method.
> Fix possible nil pointer dereference in azure sdk

- lang/functions_test.go
in the implementation of `abspath` func, the separator character in the results will be replaced with a slash ('/') character.
the test case in windows will fail
> fix test case on windows

- backend/remote-state/azure/backend_state.go
- backend/remote-state/azure/backend_test.go
- backend/testing.go
Refresh state outside of grabbing the lock; only grab the lock on provisioning if the state file doesn't exist; this is similar to the GCS backend.
This fixes the broken force-unlock command for the nominal case, where the backend state is locked and already exists.
This was previuosly done for the purpose of creating a new workspace, and simultaneously creating the resulting state file. This PR simply gets the state outside of the lock, but attempts to grab the lock when creating, so still avoids any potential race conditions.
> backend: Refresh azure state outside of grabbing the lock

- backend/unparsed_value.go
- backend/unparsed_value_test.go
- website/docs/language/values/variables.html.md
Remove deprecation and add docs specific to the behavior around undeclared variable values. While in the area, I also formatted the error so it'll (more likely, depending on variable names) be the preferred Terraform output width (78).
This also reduces the number of warnings to result in a summary (`In addition to the other similar warnings shown...`) from 3 full warnings to two full warnings. I like this better because then the third warning related to undeclared variables is the summary, rather than the fourth. The math on the `extras` doesn't change because it was off originally (off by 1 issue)
Before:
After:
> Remove deprecation on undeclared variable, docs, and summary adjustment

- terraform/context_validate_test.go
- terraform/node_resource_validate.go
- terraform/testdata/validate-sensitive-provisioner-config/main.tf
Sensitive values in provisioner configuration would cause errors in the validate phase. We need to unmark these value before serializing the config value for the provisioner plugin.
Reported in #27763. There will be a separate PR for the 0.14 branch as this won't backport cleanly.
> core: Unmark provisioner config before validation

- backend/backend.go
- backend/local/backend.go
- backend/local/backend_apply.go
- backend/local/backend_apply_test.go
- backend/local/backend_plan.go
- backend/local/backend_plan_test.go
- backend/local/backend_refresh.go
- backend/local/backend_refresh_test.go
- backend/local/cli.go
- backend/remote/backend_apply_test.go
- backend/remote/backend_plan_test.go
- backend/remote/testing.go
- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
- command/import.go
- command/plan.go
- command/plan_test.go
- command/refresh.go
- command/show.go
- command/show_test.go
- command/views/operation.go
- command/views/operation_test.go
- command/views/plan.go
- command/views/plan_test.go
- command/views/show.go
- command/views/view.go
This commit extracts the remaining UI logic from the local backend, and removes access to the direct CLI output. This is replaced with an instance of a `views.Operation` interface, which codifies the current requirements for the local backend to interact with the user. For now there is only one implementation of `views.Operation`, for the existing UI design.
The exception to this at present is interactivity: approving a plan still depends on the `UIIn` field for the backend. This is out of scope for this commit and can be revisited separately, at which time the `UIOut` field can also be removed.
Notes:
- Some instances of direct error output have been replaced with diagnostics, most notably in the emergency state backup handler. This requires reformatting the error messages to allow the …
> backend/local: Replace CLI with view instance

- backend/remote/backend_state.go
When using the `-lock-timeout` option with the remote backend configured in local operations mode, Terraform would fail to retry acquiring the lock. This was caused by the lock error message having a missing `Info` field, which the state manager requires to be present in order to attempt retries: https://github.com/hashicorp/terraform/blob/6871d0c991f760eead17dddff874427c8a03eecd/states/statemgr/locker.go#L81-L91
Other remote state storage backends attempt to fetch lock information to populate this field. Because the Terraform Cloud API doesn't really have any lock information exposed, we can't do that here, so we just round-trip the lock info we were passed in to make sure there's something non-nil in the `LockErr`.
While I can't find anywhere to add test coverage for this, I've manually …
> backend/remote: Fix broken state lock retry

- command/plan.go
This code does not appear to have any effect. The operation request has its `PlanOutBackend` field populated directly in the `Meta.Operation` method, by calling `m.backendForState.ForPlan()`.
I tested a trivial null-resource config with a Consul backend, and the saved plans with and without this code present were identical.
> cli: Remove no-op plan backend setup

- command/apply.go
- command/apply_destroy_test.go
- command/apply_test.go
- command/arguments/apply.go
- command/arguments/apply_test.go
- command/arguments/extended.go
- command/arguments/flags.go
- command/meta.go
- command/views/apply.go
- command/views/apply_test.go
- command/views/hook_count.go
- command/views/hook_count_test.go
- command/views/operation.go
This PR refactors the apply command to use the new command/arguments and command/views structure. There should be no effect on the functionality of apply.
As a result of this commit, the apply command no longer requires the cli.Ui struct in its tests, except for those dealing with user input (for approval or variable values). All output is now through views.
In a somewhat vain attempt to keep this diff reviewable, there are a significant number of FIXMEs to be addressed in follow-ups. See the self-review for highlights of these, along with some other notes.
I'd particularly appreciate thoughts from reviewers about the new arguments types in extended.go, and on the proposal to migrate variable loading to the arguments package. Also any manual testing would be great!
> cli: Migrate apply to command views

- command/arguments/refresh.go
- command/arguments/refresh_test.go
- command/refresh.go
- command/refresh_test.go
- command/views/refresh.go
- command/views/refresh_test.go
This PR refactors the refresh command to use the new command/arguments and command/views structure. There should be no effect on the functionality of refresh.
Follow-up to #27841. See also #27864.
> cli: Migrate refresh to command views

- command/apply.go
- command/arguments/apply.go
- command/arguments/apply_test.go
- command/arguments/extended.go
- command/arguments/plan.go
- command/arguments/plan_test.go
- command/plan.go
- command/plan_test.go
- command/views/plan.go
- command/views/plan_test.go
This PR refactors the plan command to use the new command/arguments and command/views structure. There should be no effect on the functionality of plan.
Follow-up to #27841. See also #27865.
> cli: Migrate plan to command views

- terraform/transform_provider.go
- terraform/transform_provider_test.go
There were a few parts of the provider transformation process which could be cleaned up, and this provided a good time to audit the behavior of these transformers.
Duplicate nodes were causing issues in prior releases, and while they would no longer be triggered due to new config validations, it should not be possible within the transformer anyway.
Remove the `ParentProviderTransformer` entirely. The concept behind a "parent provider" no longer applies to the provider handling, and the handling of the legacy inheritance algorithm is done within the general `ProviderTransformer`.
Finally we can remove the new block for handling `configuration_aliases`. These can be now be handled in the same manner as an implied "default" provider being passed in, relying on the parent module's `providers` …
> Provider transformer cleanup

- command/jsonstate/state.go
- command/jsonstate/state_test.go
- website/docs/cli/commands/show.html.md
In order to satisfy the json output requirements for instance state,
the `jsonstate` package decodes and re-encodes the state for
each instance. The problem here is that we may not have a schema
for the current state, and encoding will fail when the types have
incompatible changes. This was going to be addressed in #27836,
but due to the fact that we have existing supported resources using
dynamic types, we cannot change the encoding without a breaking
change.
Instead of returning an error with no context about unexpected
attributes or incorrect types, notify users that the schema stored in
the state does not match the current provider.
Users can only encounter this error if the providers have updated their
schemas since the state was stored. This would appears when running
`terraform …
> jsonstate: indicate schema version mismatch during encoding

- website/docs/language/resources/provisioners/remote-exec.html.md
> Document `inline` & `on_failure` behaviour

- docs/architecture.md
This document has been an invaluable source of knowledge for me to understand the general design of Terraform (_thanks @apparentlymart!_).
I found a few outdated bits here and here so I went ahead and fixed them:
* `godoc.org` was officially replaced by `pkg.go.dev` and all pages are now permanently redirected ([Go blog](https://blog.golang.org/godoc.org-redirect))
* A few pages from `terraform.io/docs` have been relocated since the time this doc was last updated
* `terraform.GraphNodeResource` was renamed to `terraform.GraphNodeConfigResource` in #24389
* Terminology: "vertexes" -> "vertices" (1 occurrence)
I also added a FIXME comment to follow up on the removal of `EvalNode` (_ping @mildwonkey_). I'm game for tackling it in a separate PR but couldn't find an umbrella issue explaining …
> Update "Terraform Core Architecture Summary" doc

- website/upgrade-guides/0-15.html.markdown
As usual, we'll continue to iterate on this based on feedback and questions during the beta period, but this is a first draft intended to help those who are trying out the first beta.
[GitHub-rendered Version](https://github.com/hashicorp/terraform/blob/doc-v0.15-upgrade/website/upgrade-guides/0-15.html.markdown) (which will become invalid once this is merged and thus I've deleted the PR branch.)
> website: Terraform v0.15 upgrade guide first draft

- command/validate.go
These flags are not used and have been deprecated since 0.12.11.
> cli: Remove -var/-var-file flags from validate

- plans/objchange/plan_valid.go
- plans/objchange/plan_valid_test.go
Catch attributes which are planed but not computed separately to provide
a clearer error to provider developers.
The error conditions were previously caught, however it was unclear from
the error text as to _why_ the change was an error. The statements about
value inequality would be incorrect when planning no changes for a value
which should not have been set in the first place.
Previous errors could have text like:
```
.length: planned value cty.NumberIntVal(2) does not match config value cty.NullVal(cty.Number) nor prior value cty.NumberIntVal(2)
```
Which is replaced by:
```
.length: planned value cty.NumberIntVal(2) for a non-computed attribute
```
> objchange: catch invalidly planned attributes earlier

- builtin/provisioners/file/resource_provisioner.go
- builtin/provisioners/file/resource_provisioner_test.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner_test.go
The new provisioner implementation did not validate that there was a connection configuration.
There should probably be a way to catch this ahead of time during static validation, but we need to prevent the communicator from panicking.
> remote provisioners require a connection config

- docs/architecture.md
I've removed references to EvalNode() / Eval() and replaced with a basic explanation of `GraphNodeExecutable.Execute` and a list of the "main" graph `Execution`s. 
I'm sure this section could be re-written better, and I'll happily take any suggestions, but the main goal of _this_ PR is accuracy.
> update arch docs; remove old EvalNode references

- backend/local/backend_local.go
configSnap may be nil if there are errors loading it from the plan file.
This does not address any potential regressions or errors when loading the config, it only adds a missing error check leading to a nil pointer dereference.
Fixes #27924
> check errors before using configSnap

- website/docs/language/modules/testing-experiment.html.md
This isn't incredibly important, but Kitchen-Terraform is written in and requires tests to be written in Ruby.
> Fix Kitchen-Terraform language in test experiment

- configs/named_values.go
Our previous message conflated the requirement for a full sentence with the suggestion to write in a style similar to Terraform's built-in error messages, which created a sense that the system would actively reject an error message written in another language.
There's no intent here to block writing error messages in other languages, but there is a practical consideration that Terraform's UI output is currently not localized and so consistency with Terraform's other output, if that's important to a module author, will typically mean writing the error message in English.
This is the new error message implemented here:
```
╷
│ Error: Invalid validation error message
│ 
│   on variable-validation.tf line 4, in variable "foo":
│    4:     error_message = "not valid"
│ 
│ The validation error …
```
> configs: A better error message for custom variable validation

- configs/experiments.go
- configs/parser_config.go
- configs/testdata/error-files/invalid_language_edition.tf
- configs/testdata/error-files/unsupported_language_edition.tf
- configs/testdata/valid-files/valid-language-edition.tf
We expect that in order to continue to evolve the language without breaking existing modules we will at some point need to have a way to mark when a particular module is expecting a newer interpretation of the language.
Although it's too early to do any deep preparation for that, this commit aims to proactively reserve an argument named "language" inside "terraform" blocks, which currently only accepts the keyword `TF2021` that is intended to represent "the edition of the Terraform language as defined in 2021".
Since `TF2021` represents the language as currently defined _without_ setting `language`, in practice there's no real reason to set this today, but this minimal validation is intended to give better feedback to users of older Terraform versions in the event that we introduce a new …
> configs: Accept and minimally validate a "language" argument

- command/plan.go
- command/plan_test.go
- command/refresh.go
- command/views/apply.go
- command/views/operation.go
- command/views/output.go
- command/views/plan.go
- command/views/refresh.go
- command/views/state_locker.go
The previous implementation of views was copying and embedding the base `View` struct in each individual view. While this allowed for easy access to the interface of that struct (both in the view and externally), it more importantly completely broke the ability of the diagnostic printer to output source code snippets.
This is because the `configSources` field on the base view is lazily set after the config loader is initialized. In the commands ported to use views, this happens after the base `View` struct is copied, so we are updating the wrong copy of the struct.
This commit fixes this with a simple mechanical refactor: keep a pointer to the base `View` struct instead, and update all of the individual views to explicitly refer to that struct to access its fields and methods.
This is not …
> views: Fix missing source in diagnostic output

- addrs/module.go
- addrs/module_instance.go
- addrs/module_instance_test.go
- addrs/module_test.go
- addrs/output_value.go
- addrs/output_value_test.go
- addrs/resource.go
- addrs/resource_test.go
- plans/changes.go
Generating strings and comparing them to implement Equal is a quick and easy solution. Unfortunately when this code is in the hot path, it becomes very expensive, so this commit changes some of those instances to compare the values directly.
Combined with using `addr.Equal` instead of checking for string equality, this makes Terraform dramatically faster for some operations, such as generating large JSON plans.
This optimization came from investigating very slow `terraform show -json <plan>` for plans with large numbers of resources (#27974). To reproduce this, I created a configuration with thousands of `null_resource` instances:
```hcl
resource "null_resource" "lots" {
count = 15000
triggers = {
count = count.index
}
}
```
I applied this configuration to generate some state, then …
> core: Reduce string allocations for addrs Equal

- lang/funcs/defaults.go
- lang/funcs/defaults_test.go
Two commits, addressing the two separate issues in #27385:
When applying default values to collection types, null collections in the input should result in empty collections in the output.
Fixes #27385 (original report)
We allow primitive fallback values which have mismatched types, but only if there is a conversion to the target type. Previously we would allow unsafe conversions (e.g. string to bool), but later had no capacity to return an error if the conversion failed due to the value of the fallback being unable to convert to the target type.
This commit makes the more conservative requirement that default fallback values must have a safe conversion.
Fixes #27385 (follow-up reports)
> functions: Fix panics in defaults

- plugin/convert/diagnostics.go
- plugin/convert/diagnostics_test.go
Backport of https://github.com/hashicorp/terraform/pull/27710
Fixes https://github.com/hashicorp/terraform/issues/27283
> [0.14 backport] Fix empty diags not getting associated with source.

- terraform/node_resource_destroy_deposed.go
- terraform/node_resource_destroy_deposed_test.go
NodeDestroyDeposedResourceInstanceObject should not panic if the deposed
state no longer exists.
While we have not confirmed if we can still get into this situation with the current codebase, Execute should not pass a nil state to a function that will panic. Returning an error here will let us better diagnose if this does happen again.
Fixes #27475
> do not panic if there is no deposed state

- addrs/provider.go
- command/e2etest/init_test.go
- command/e2etest/testdata/provider-not-found-non-default/main.tf
- command/init.go
- internal/getproviders/didyoumean.go
- internal/getproviders/didyoumean_test.go
When a user has any module, or child module, that has a `ErrRegistryProviderNotKnown` error, users are often confused why they don't get inheritance from other modules. 
Because Terraform explicitly loads modules as units with their own provider requirements (`required_providers`), and adds a suggestion of a provider "did you mean" if they have a provider of the same type (but not the default namespace) in their requirements.
This is what the new suggestion looks like in practice (with suggestion):
This is what the new suggestion looks like in practice (without suggestion/no existing provider requirements):
Open to comments on improving this suggestion to be more user-friendly (for lack of a better term)
My hope is that this can address the (very valid!) concerns and comments surrounding …
> Give suggestions & remind users to use required_providers when provider not in registry

- command/init.go
- command/init_test.go
- command/testdata/init-provider-lock-file-readonly-add/main.tf
- internal/depsfile/locks.go
- internal/depsfile/locks_test.go
- website/docs/cli/commands/init.html.md
Cherry-pick of @minamijoyo's #27630 commit onto v0.15. [Original proposal for this change here](https://github.com/hashicorp/terraform/issues/27264#issuecomment-754312194). Original PR description:
---
Fixes #27506
Add a new flag `-lockfile=readonly` to `terraform init`. It would be useful to allow us to suppress dependency lockfile changes explicitly. The type of the `-lockfile` flag is string rather than bool, leaving room for future extensions to other behavior variants.
The readonly mode suppresses lockfile changes, but should verify checksums against the information already recorded. It should conflict with the `-upgrade` flag.
Note: In the original use-case described in #27506, I would like to suppress adding zh hashes, but a test code here suppresses adding h1 hashes because it's …
> command/init: Add a new flag `-lockfile=readonly` (v0.15 backport of #27630)

- website/docs/language/syntax/configuration.html.md
- website/docs/language/syntax/json.html.md
The `hcl2` branch doesn't exist anymore, it was renamed to `main`.
> docs: Update link to HCL native syntax spec

- command/jsonprovider/attribute.go
- command/jsonprovider/block.go
- command/jsonprovider/provider_test.go
- command/providers_schema_test.go
- command/testdata/providers-schema/basic/output.json
- command/testdata/providers-schema/required/output.json
This PR extends jsonprovider to support attributes with NestedTypes and extends test coverage in jsonprovider and the providers schemas tests. I've also cleaned up some comments and extracted the logic to parse the nesting mode so it can be used in both marshaling blocks and attributes.
Fixes #28050
> add support for attributes with nested types in providers schema

- website/docs/cli/commands/validate.html.md
Apparently I missed documenting this the first time around, so we've had it implemented but not documented since Terraform v0.12.0. This is some retroactive documentation of my best recollection of the design intent for this format at the time we implemented it.
> website: docs for the terraform validate JSON output

- configs/provider_meta.go
- configs/testdata/invalid-modules/provider-meta/invalid-interpolation.tf
- configs/testdata/valid-modules/provider-meta/main.tf
The `provider_meta` specification does not allow interpolation, but we were not preventing it in the configuration. The `provider_meta` block does not have a defined lifecycle during evaluation, and cannot be correctly ordered to ensure any references have been evaluated. Since `provider_meta` must be an entirely static map, we can validate this early on while loading the configuration. 
Preventing interpolations could be a breaking change for existing modules that were successfully using this undefined behavior, but as demonstrated in #28061 success is not deterministic between releases.
Resolves #28061
> validate provider_meta contains no interpolations

- command/format/diagnostic.go
- command/testdata/validate-invalid/incorrectmodulename/output.json
- command/testdata/validate-invalid/interpolation/output.json
- command/testdata/validate-invalid/missing_quote/output.json
- command/testdata/validate-invalid/missing_var/output.json
- command/testdata/validate-invalid/multiple_modules/output.json
- command/testdata/validate-invalid/multiple_providers/output.json
- command/testdata/validate-invalid/multiple_resources/output.json
- command/testdata/validate-invalid/output.json
- command/testdata/validate-invalid/outputs/output.json
- command/validate.go
- command/views/json/diagnostic.go
- command/views/json/diagnostic_test.go
- command/views/json/testdata/diagnostic/error-with-empty-highlight-range-at-end-of-source-code.json
- command/views/json/testdata/diagnostic/error-with-multi-line-snippet.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-and-expression-referring-to-sensitive-value.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-and-known-expression.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-and-unknown-expression-of-unknown-type.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-and-unknown-string-expression.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-but-no-context.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject-with-multiple-expression-values.json
- command/views/json/testdata/diagnostic/error-with-source-code-subject.json
- command/views/json/testdata/diagnostic/error-with-source-code-unavailable.json
- command/views/json/testdata/diagnostic/sourceless-warning.json
- website/docs/cli/commands/validate.html.md
The motivation for this work is to unify the diagnostic rendering path, ensuring that there is one standard representation of a renderable diagnostic. This means that commands which emit JSON diagnostics are guaranteed to provide the same information in machine-readable format.
At present, only `terraform validate` emits JSON diagnostics, but this is likely to change in the future.
This rather large pull request is probably best reviewed one commit at a time:
This commit adds a comprehensive JSON format for diagnostics, which ensures that all current diagnostic output can be semantically represented in a machine-readable format. The diagnostic formatter interface remains unchanged, but it first transforms its input via the JSON format to ensure that there is only one code path for …
> cli: Add comprehensive JSON diagnostic structure

- lang/funcs/defaults.go
- lang/funcs/defaults_test.go
When using defaults with a value which contains null objects or tuples, we cannot continue to traverse the value and apply defaults. Instead, when we find an attribute which is null, we return early and stop processing this branch.
Previously this would panic. This behaviour is a little counter-intuitive to me, but I think it's consistent with how defaults work. The alternative I considered was replacing the `null` value with a copy of the given fallback object/tuple, but that wasn't obviously correct either.
Fixes #28046.
> functions: Fix defaults for null objects/tuples

- backend/remote/backend.go
- backend/remote/backend_test.go
When migrating state to a new workspace, the version check would error due to a 404 error on fetching the workspace record. This would result in failed state migration.
Instead we should look specifically for a 404 error, and allow migration to continue. If we're just about to create the workspace, there can't be a version incompatibility problem.
Fixes #28092, which was introduced in 0.14.5. Proposing backport to 0.14 and 0.15.
> backend/remote: Fix new workspace state migration

- backend/remote-state/pg/backend.go
- backend/remote-state/pg/backend_test.go
Until now the default workspace for every project would have the ID 1,
which would make it impossible to lock them at the same time since we
use the ID to identify the lock. With a global sequence to generate the
IDs, the default workspace will now have a different ID for each project
and it will be possible to lock multiple unrelated projects at the same
time.
If an old version of Terraform tries to get the lock on a project created
with this new version it will work as we continue to use the ID of the
workspace, we just change the way we generate them.
If this version tries to get a lock on a project created by an old
version of Terraform it will work as usual, but we may encounter a
conflict with another unrelated project. This is already the current
behavior so it's not an issue to …
> Use a global sequence to create the IDs for each workspace

- go.mod
- go.sum
Update hcl and go-cty packages to fix a number of issue around optional attributes and sensitive values, and improve type inference in conditional statements.
Closes #27269
Closes #27295
Closes #28049
Closes #27966
> update hcl and go-cty

- internal/logging/logging.go
- website/docs/internals/debugging.html.md
Add support for TF_LOG=json, which logs at the TRACE level but outputs
the contents in their JSON encoding.
This makes logs parsable after the fact.
> Support TF_LOG=json

- lang/funcs/sensitive.go
- lang/funcs/sensitive_test.go
- lang/functions.go
- lang/functions_test.go
- website/docs/language/functions/nonsensitive.html.md
- website/docs/language/functions/sensitive.html.md
- website/layouts/language.erb
These aim to allow hinting to Terraform about situations where it's not able to automatically infer value sensitivity.
`nonsensitive` is for situations where Terraform's behavior is too conservative, such as when a new value is derived from a sensitive value in such a way that all of the sensitive content is removed.
`sensitive`, on the other hand, is for situations where Terraform can't otherwise infer that a value is sensitive. These situations should be pretty rare in a module that's making effective use of sensitive input variables and output values, but the documentation shows one example of an uncommon situation where a more direct hint via this function would be needed.
---
I've marked this as a draft because we're still debating the practical tradeoffs of including these …
> lang/funcs: "sensitive" and "nonsensitive" functions

- command/testdata/validate-invalid/incorrectmodulename/output.json
- command/testdata/validate-invalid/interpolation/output.json
- command/testdata/validate-invalid/missing_defined_var/output.json
- command/testdata/validate-invalid/missing_quote/output.json
- command/testdata/validate-invalid/missing_var/output.json
- command/testdata/validate-invalid/multiple_modules/output.json
- command/testdata/validate-invalid/multiple_providers/output.json
- command/testdata/validate-invalid/multiple_resources/output.json
- command/testdata/validate-invalid/output.json
- command/testdata/validate-invalid/outputs/output.json
- command/testdata/validate-valid/output.json
- command/validate.go
- website/docs/cli/commands/validate.html.md
In line with the other complex JSON output formats for plan and provider schema, here we add an explicit `format_version` field to the JSON output of terraform validate.
While I don't think it's likely that we will change the validate format in a backwards-incompatible way, this gives us a way to safely indicate that and allow an integrating tool to safely parse both formats.
> cli: Add format version to validate -json output

- website/docs/cli/commands/validate.html.md
The traversal value is normally a valid HCL string, but can be simplified if a traversal step has a complex index value (e.g. an
object). This means it is not always parseable HCL, so this commit updates the documentation to clarify this and explicitly record that we do not guarantee its contents are stable. The purpose of these values is purely for building human-readable UI.
Here's the code which generates this value: https://github.com/hashicorp/terraform/blob/53739f0aacf6e8251a977f2038bb61b9f1a1a3c3/command/views/json/diagnostic.go#L373-L401
> documentation: Clarify JSON diagnostic values traversal semantics

- backend/remote-state/etcdv3/backend_test.go
- backend/remote-state/etcdv3/client_test.go
etcdv3 acceptance tests fail due to attempting to pass slices of strings
for the endpoints config to HCL2ValueFromConfigValue() which does not
handle that type.
Not a pretty solution but a helper function that converts the endpoints to a slice of
empty interfaces satisfies the requirements of the
HCL2ValueFromConfigValue function.
fixes https://github.com/hashicorp/terraform/issues/28096
> Fix type conversion panic

- backend/remote-state/etcdv3/backend_state.go
The default state is already explicitly added to the result slice. Added
a guard to prevent it being added a second time.
Fixes https://github.com/hashicorp/terraform/issues/28098
> Fix duplicate default state

- website/docs/language/expressions/references.html.md
- website/docs/language/meta-arguments/for_each.html.md
Update documentation to reference that this experiment is now default in 0.15+. My apologies that these docs updates should have been included in the PR upgrading this experiment.
> Update documentation for provider_sensitive_attrs experiment

- tools/terraform-bundle/config.go
terraform-bundle would happily install no providers if the "version" argument was omitted, so this PR adds an error in that situation. I'll backport this to 0.13 - 0.15, since we tell users to build terraform-bundle from the latest commit of a given version tag. ("backport" here is low-risk; terraform-bundle is not part of a terraform release so it's no impact, whether or not there is a terraform release from those branches)
Closes #28091
> terraform-bundle: return an error if "versions" argument is omitted

- command/jsonprovider/provider.go
- command/testdata/providers-schema/basic/output.json
- command/testdata/providers-schema/empty/output.json
- command/testdata/providers-schema/required/output.json
Support for attributes with NestedTypes was added in https://github.com/hashicorp/terraform/pull/28055, and that PR should have included a format version bump: this is a backwards-compatible change, but consumers will need to be updated in order to properly decode attributes (with NestedTypes) going forward.
Thanks @bflad for the nudge! 
@vancluever , I am sorry I did not include you on the last PR (#28055); if you have questions / see any problems / have any requests I'll get right on 'em.
> command/jsonprovider: bump format version

- command/plan_test.go
- configs/configschema/decoder_spec.go
- configs/configschema/internal_validate.go
- configs/configschema/internal_validate_test.go
- terraform/resource_provider.go
- terraform/schemas.go
Hello! This PR comes with a lead-in question before you look at the code: should we even do this? I think so, but if there's any controversy I can step back and RFC this. [updated with improved error message] ~If agreed, I will have at least one more commit to improve the error message; I didn't want to spend any more time on it before confirming if this is a good idea in the first place.~ 
----
The terraform-plugin-sdk has a lovely series of InternalValidate functions that verify the validity of the providers' schemas during `Configure` (entrypoint [here](https://github.com/hashicorp/terraform-plugin-sdk/blob/dcaac684c7fe179d35d2ff34f9f1de99ea129c6c/helper/schema/provider.go#L109)). Terraform _assumes_ that this is run for every provider. 
This is not a safe assumption, unfortunately: …
> terraform: validate providers' schemas during NewContext

- command/arguments/validate.go
- command/arguments/validate_test.go
- command/validate.go
- command/validate_test.go
- command/views/validate.go
- command/views/validate_test.go
Update `terraform validate` to use views and argument parsing. This is mostly moving code around as part of migration towards views for all commands.
There's only one change in behaviour here, which I think is a bug fix rather than a breaking change: extra positional arguments to validate would previously be ignored, and now an argument error is shown:
```shellsession
$ terraform-0.15.0-beta1 validate foo bar baz
Success! The configuration is valid.
$ terraform-main validate foo bar baz
╷
│ Error: Too many command line arguments
│
│ Expected at most one positional argument.
╵
For more help on using this command, run:
terraform validate -help
```
The positional argument for dir is mostly useless, and is likely to be deprecated in future. We're removing it from the help documentation here …
> cli: Migrate validate command to views

- terraform/evaluate.go
- terraform/evaluate_test.go
When we map schema sensitivity to resource values, there may be unknowns
when dealing with planned objects. Check for unknowns before iterating
over block values.
Fixes #28153
> check for unknowns when marking resource values

- dag/set.go
- dag/set_test.go
Intersection is faster for sets of different sizes if one iterates over the shorter set and checks the presence of an element in a larger one. For an edge case consider `s` having 1M entries and `other` no entries at all. In this case original code will iterate over 1M entries in `s` not finding anything and then returning an empty result set. In the patched code the iteration won't happen at all and result is returned immediately.
This change is inspired by profiling a relatively large terraform configuration, where the time to validate was sped up 4x with this change.
This should have no effect other than performance improvement.
> Set Intersection #performance

- dag/set.go
- dag/set_test.go
Backport of #28183 to v0.15. Fixes #28170, I think.
> Set Intersection #performance (#28183)

- command/apply.go
- command/console.go
- command/import.go
- command/plan.go
- command/refresh.go
- website/docs/cli/commands/apply.html.md
- website/docs/cli/commands/console.html.md
- website/docs/cli/commands/import.html.md
- website/docs/cli/commands/plan.html.md
- website/docs/cli/commands/refresh.html.md
- website/docs/language/settings/backends/local.html.md
We have these funny extra options that date back to before Terraform even had remote state, which we've preserved along the way by most recently incorporating them as special-case overrides for the local backend: `-state`, `-state-out`, and `-backend`.
The documentation we had for these has grown less accurate over time as the details have shifted, and was in many cases missing the requisite caveats that they are only for the local backend and that backend configuration is the modern, preferred way to deal with the use-cases they were intended for.
We always have a bit of a tension with this sort of legacy option because we want to keep them documented just enough to be useful to someone who finds an existing script/etc using them and wants to know what they do, but not to take up so much …
> command: Reorganize docs of the local backend's legacy CLI options

- command/fmt.go
- command/testdata/fmt/general_in.tf
- command/testdata/fmt/general_out.tf
The formatter for value expressions which use legacy interpolation syntax was previously behaving incorrectly with some multi-line expressions. Any HCL expression which requires parenthesis to be allowed to span multiple lines could skip those parens if already inside string interpolation (`"${}"`).
When removing string interpolation, we now check for a resulting multi-line expression, and conservatively ensure that it starts and ends with parenthesis. These may be redundant, as not all expressions require parens to permit spanning multiple lines, but at least it will be valid output.
Fixes #28199.
> cli: Fix fmt output for multi-line value exprs

- website/docs/cli/commands/state/pull.html.md
This PR clarifies the version that `terraform state pull` will upgrade the local version of the state file to, in reference to [this discussion](https://github.com/hashicorp/terraform/pull/27572/files#r600928348). One open question I had is what happens if the local terraform version is earlier than the remote version; will pull downgrade the local state file?
> Clarify that pull will match state file to locally installed terraform version

- command/init.go
- command/init_test.go
If the provider locks have not changed, there is no need to rewrite the locks file. Preventing this needless rewrite should allow Terraform to operate in a read-only directory, so long as the provider requirements don't change.
Slightly related to #27630, but serving a different use case. The goal here is to make a smaller change which can be back-ported to 0.14, and still allow being able to run Terraform in a read-only directory to allow upgrade from 0.13 to 0.14.
> cli: Only rewrite provider locks file if changed

- .circleci/config.yml
Cross-platform builds are running out of resources. Try using a little
more memory.
> provide more memory for builds

- .circleci/config.yml
Rather than increase resources for more cross-platform builds, opt to
remove platforms that are not officially supported.
> remove unsupported platforms from CI test builds

- terraform/evaluate.go
- terraform/evaluate_test.go
When applying sensitivity marks to resources, we previously would first mark any provider-denoted sensitive attributes, then apply the set of planned-change sensitive value marks. This would cause a panic if a provider marked an iterable value as sensitive, because it is invalid to call `MarkWithPaths` against a marked iterable value.
Instead, we now merge the marks from the provider schema and the planned change into a single set, and apply them with one call. The included test panics without this change.
Fixes #28244. See also https://github.com/hashicorp/terraform-provider-aws/issues/18485.
> core: Fix sensitive value/attribute conflict

- website/docs/language/expressions/dynamic-blocks.html.md
We previously added a hint to both resource `for_each` and `dynamic` blocks about using the `flatten` and `setproduct` situations to construct suitable collections to repeat over.
However, we used the same text in both places which ended up stating that `dynamic` blocks can only accept map or set values, which is a constraint that applies to resource `for_each` (because we need to assign a unique identifier to each instance) and not to `dynamic` blocks (which don't have any uniqueness enforced by Terraform Core itself).
To remove that contradiction, I've just generalized this to say "collection", because the primary point of this paragraph is the "one element per desired nested block" part, not specifically what sort of collections are permitted in this location. (Earlier text on the page …
> website: Dynamic blocks can for_each any collection type

- main.go
- main_test.go
The shell autocomplete command will use the binary name as the first
argument which does not show up under the list of subcommands.
> don't error when given autocomplete commands

- command/jsonplan/plan.go
- command/jsonplan/plan_test.go
When rendering the JSON plan sensitivity output, if the plan contained unknown collection or structural types, Terraform would crash. We need to detect unknown values before attempting to iterate them.
Unknown collection or structural values cannot have sensitive contents accidentally displayed, as those values are not known until after apply. As a result we return an empty value of the appropriate type for the sensitivity mapping.
This doesn't change the JSON output itself, just resolves a crash.
> command/jsonplan: Fix sensitive/unknown crash

- terraform/context_apply2_test.go
- terraform/context_plan2_test.go
- terraform/node_resource_abstract_instance.go
Dependencies are tracked via configuration addresses, but when dealing with depends_on references they can only apply to resources within the same module instance.
When determining if a data source can be read during planning, verify that the dependency change is coming from the same module instance.
Fixes #28084
> Don't force data reads from dependency changes in sibling modules

- terraform/context.go
- terraform/context_plan2_test.go
When refresh was skipped for a destroy plan, there was no state stored
in the plan.
Fixes #28271
> ensure plans always have a stored state

- addrs/module_instance.go
- addrs/module_instance_test.go
`bytes.Buffer` always allocates when converting to a string. `strings.Builder` does not.
Preallocating the memory is beneficial as well, note that the new code only does a single allocation per operation
Results, first this branch, then main:
```
$ go test -bench=String ./addrs -benchmem 
BenchmarkStringShort-12         18271692                56.52 ns/op           16 B/op          1 allocs/op
BenchmarkStringLong-12           8057071               158.5 ns/op            96 B/op          1 allocs/op
PASS
$ git checkout main addrs/module_instance.go
$ go test -bench=String ./addrs -benchmem 
BenchmarkStringShort-12          7690818               162.0 ns/op            80 B/op          2 allocs/op
BenchmarkStringLong-12           2922117               414.1 ns/op           288 B/op …
```
> Improve ModuleInstance String() performance

- go.mod
- go.sum
after a fresh terraform checkout, I got the following error trying to build:
```
verifying github.com/hashicorp/go-getter@v1.5.1: checksum mismatch
downloaded: h1:LZ49OxqBBtdKJymlpX7oTyqGBQRg4xxQDyPW4hzoZqM=
go.sum:     h1:lM9sM02nvEApQGFgkXxWbhfqtyN+AyhQmi+MaMdBDOI=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```
After some research, it appears that two versions of go-getter v1.5.1 were released (see related discussion in https://github.com/hashicorp/nomad/pull/9349#issuecomment-756281963). 
Bumping the go-getter version gets around this issue.
The changes in go-getter are minimal and …
> bump go-getter to 1.5.2

- website/docs/language/functions/yamldecode.html.md
The `yamldecode` example it's a little bit confusing because it's using a `json` instead of `yaml`. So for better suit I change it to a yaml.
> Fix yamldecode example from json to yaml

- backend/testing.go
- command/format/diagnostic.go
- command/meta_backend.go
- command/views/json/diagnostic.go
- plugin/convert/diagnostics_test.go
- plugin/grpc_error.go
- terraform/node_provider.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_validate.go
- tfdiags/contextual.go
- tfdiags/contextual_test.go
- tfdiags/diagnostic.go
- tfdiags/diagnostic_base.go
Diagnostics are most commonly associated with a particular addressable value in terraform, and it would be useful to have some sort of annotation to attribute a diagnostic with a runtime address. This is useful in addition to the configuration body, since the individual resource instance, or containing module instance may be critical to determining the reason for the error.
The result here is that formatted diagnostics will include an address before the configuration details pinpointing the instance:
```
╷
│ Error: something went horribly wrong
│
│   with module.mod["foo"].aws_vpc.a["bar"],
│   on mod/main.tf line 2, in resource "aws_vpc" "a":
```
-- 
We first add an address argument to `tfdiags.InConfigBody`, and store the address string the diagnostics details. Since nearly every place …
> Add addresses to diagnostics

- terraform/context_apply_test.go
- terraform/node_resource_abstract_instance.go
Is a resource delete action fails and the provider returned a new state,
we need to ensure the stored dependencies are retained.
Fixes #28315
> restore saved dependencies on delete error

- lang/funcs/sensitive.go
- lang/funcs/sensitive_test.go
- terraform/context_plan2_test.go
Calling the `nonsensitive` function with values which are not sensitive will result in an error. This restriction was added with the goal of preventing confusingly redundant use of this function.
Unfortunately, this breaks when using `nonsensitive` to reveal the value of sensitive resource attributes. This is because the validate walk does not (and cannot) mark attributes as sensitive based on the schema, because the resource value itself is unknown.
This commit therefore alters this restriction such that it permits nonsensitive unknown values, and adds a test case to cover this specific scenario.
Fixes #28321.
> lang/funcs: Make nonsensitive more permissive

- lang/funcs/collection.go
- lang/funcs/collection_test.go
- lang/functions.go
- lang/functions_test.go
- website/docs/language/functions/one.html.md
- website/layouts/language.erb
In the Terraform language we typically use lists of zero or one values in some sense interchangably with single values that might be null, because various Terraform language constructs are designed to work with collections rather than with nullable values.
In Terraform v0.12 we made the splat operator `[*]` have a "special power" of concisely converting from a possibly-null single value into a zero-or-one list as a way to make that common operation more concise.
In a sense this `one` function is the opposite operation to that variant of splat: it goes from a zero-or-one collection (list, set, or tuple) to a possibly-null single value.
This is a concise alternative to the following clunky conditional expression, with the additional benefit that the following expression is also not viable …
> lang/funcs: "one" function

- website/docs/language/expressions/references.html.md
- website/docs/language/values/outputs.html.md
- website/docs/language/values/variables.html.md
- website/upgrade-guides/0-15.html.markdown
Our earlier draft of this guide didn't include a section about the stabilization of the `provider_sensitive_attrs` language experiment. This new section aims to address the situation where a module might previously have been returning a sensitive value without having marked it as such, and thus that module will begin returning an error after upgrading to Terraform v0.15.
As part of that, I also reviewed the existing documentation about these features and made some edits aiming to make these four different sections hopefully work well together if users refer to them all at once, as they are likely to do if they follow the new links from the upgrade guide. I aimed to retain all of the content we had before, but some of it is now in a new location.
In particular, I've moved the discussion …
> website: v0.15 upgrade guide for sensitive resource attributes

- backend/local/backend_apply.go
This blank line delineating the plan and the query was accidentally dropped as part of the views migration.
Before:
After:
> command: Add a newline before confirming apply

- website/docs/language/expressions/references.html.md
- website/docs/language/values/outputs.html.md
- website/docs/language/values/variables.html.md
- website/upgrade-guides/0-15.html.markdown
Manual version of https://github.com/hashicorp/terraform/pull/28361
* website: v0.15 upgrade guide for sensitive resource attributes
Our earlier draft of this guide didn't include a section about the
stabilization of the "provider_sensitive_attrs" language experiment. This
new section aims to address the situation where a module might previously
have been returning a sensitive value without having marked it as such,
and thus that module will begin returning an error after upgrading to
Terraform v0.15.
As part of that, I also reviewed the existing documentation about these
features and made some edits aiming to make these four different sections
work well together if users refer to them all at once, as they are likely
to do if they follow the new links from the upgrade guide. I aimed to …
> website: v0.15 upgrade guide for sensitive resource attributes (#28355)

- dag/set.go
- dag/set_test.go
1. Use hint for map size in Set.Copy().
2. Use Set.Copy() if Set.Difference() argument is empty.
> tiny optimisations of dag.Set

- terraform/context_apply2_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
If a resource has a writeable attribute which is sensitive in the schema, which is bound to a marked sensitive value, reading the resource from state would previously crash due to double-marking the value. To fix this, we need to unmark the value from state, merge its marks with the schema-derived marks, and re-apply the merged marks.
Fixes #28370.
> core: Fix double-marked sensitive attributes

- website/layouts/language.erb
Unfortunately it seems that this link got lost in a merge conflict when we did the big nav refactor earlier in the v0.15 cycle, so here we'll retoractively add it to the new location for upgrade guide nav, in the language layout rather than the downloads layout.
If we merge this then in addition to backporting it into the v0.15 branch I'll also cherry-pick it for immediate deployment.
> website: Link to the v0.15 upgrade guide

- website/upgrade-guides/0-15.html.markdown
Terraform v0.15 includes the conclusion of the deprecation cycle for some renamed arguments in the "azure" backend.
We missed this on the first draft of the upgrade guide because this change arrived along with various other more innocuous updates in #28181 and so we didn't spot it during our change review.
This closes #28378.
> website: v0.15 Upgrade Guide entry for Azure Backend arguments

- command/apply.go
- command/plan.go
Fix two bugs which surface when using the remote backend:
- When migrating to views, we removed the call to `(*Meta).process` which initialized the color boolean. This resulted in the legacy UI calls in the remote backend stripping color codes. To fix this, we populate this boolean from the common arguments.
- Remote apply will output the resource summary and output changes, and these are rendered via the remote backend streaming. We need to special case this in the apply command and prevent displaying a zero-change summary line.
Neither of these are coverable by automated tests, as we don't have any command-package level testing for the remote backend. Manually verified.
Fixes #28408.
> cli: Fix remote backend UI issues

- backend/remote/backend.go
- command/apply.go
Disabling the resource count and outputs rendering when the remote backend is in use causes them to be omitted from Terraform Cloud runs. This PR changes the condition to render these values if either the remote backend is not in use, or it is in local operations mode. The latter is true both for Terraform Cloud workspaces which are for state storage, and when executing Terraform runs remotely on a Terraform Cloud worker.
PR review note: I'm not thrilled with this solution, but I'm at a loss as to how better to solve it. Open to ideas!
Follow-up to #28409.
Missing apply summary:
Apply summary present:
> cli: Fix missing apply summary for remote runs

- configs/config.go
- configs/config_build.go
- configs/provider.go
- configs/provider_validation.go
- configs/resource.go
- configs/testdata/valid-modules/nested-providers-fqns/child/main.tf
- configs/testdata/valid-modules/nested-providers-fqns/main.tf
All the information is available to resolve provider types when building
the configuration, but some provider references still had no FQN. This
caused validation to assume a default type, and incorrectly reject valid
module calls with non-default namespaced providers.
Resolve as much provider type information as possible when loading the
config. Only use this internally for now, but this should be useful
outside of the package to avoid re-resolving the providers later on. We
can come back and find where this might be useful elsewhere, but for now
keep the change as small as possible to avoid any changes in behavior.
Fixes #28407
> resolve provider types when building the config

- website/docs/cli/config/config-file.html.md
docs: add note that provider binaries need to be placed in appropriate subdirectories under the default locations
closes #28395 (with a similar PR to terraform-website)
Re-iterate that provider binaries need to be installed _in the proper subdirectory_ rather than just under `.plugins`.
> docs: small update for provider binary locations

- terraform/context.go
- terraform/context_plan2_test.go
The destroy plan walk was identifying itself as a normal plan, and
causing providers to be configured when they were not needed. Since the
provider configuration may not be complete during the minimal destroy
plan walk, validation or configuration may fail.
Fixes #28428
> wrong operation during destroy plan walk

- terraform/context.go
- terraform/context_plan2_test.go
Manual backport of #28444
Re-orders conflicting test changes in `context_plan2_test.go` to match `main`, which are causing automatic back ports to fail.
----
The destroy plan walk was identifying itself as a normal plan, and
causing providers to be configured when they were not needed. Since the
provider configuration may not be complete during the minimal destroy
plan walk, validation or configuration may fail.
> v0.15 backport: wrong operation during destroy plan walk

- lang/funcs/conversion.go
- lang/funcs/conversion_test.go
In order to avoid updating every one of our existing functions with explicit support for sensitive values, there's a default rule in the
functions system which makes the result of a function sensitive if any of its arguments contain sensitive values.
We were applying that default to the various type conversion functions, like `tomap` and `tolist`, which meant that converting a complex-typed value with a sensitive value anywhere inside it would result in a wholly-sensitive result.
That's unnecessarily conservative because the `cty` conversion layer (which these functions are wrapping) already knows how to handle sensitivity in a more precise way. Therefore we can opt in to handling marked values (which Terraform uses for sensitivity) here and the only special thing we need to do is handle …
> lang/funcs: Conversion functions can handle sensitive values

- builtin/provisioners/local-exec/resource_provisioner.go
- builtin/provisioners/local-exec/resource_provisioner_test.go
- builtin/provisioners/remote-exec/resource_provisioner.go
- builtin/provisioners/remote-exec/resource_provisioner_test.go
Now that provisioners work directly with the plugin API and cty data
types, we need to add a few null checks to catch invalid input that
would have otherwise been masked by the legacy SDK.
Try to follow the behavior of the legacy SDK as closely as possible,
silently skipping nulls where empty strings would have been ignored,
and returning an error when an empty string would also have errored. 
Fixes #28455
> additional null checks in provisioners

- go.mod
- go.sum
This includes the improvements to various collection-related functions to make them handle marks more precisely. For Terraform in particular that translates into handling sensitivity more precisely, so that non-sensitive collections that happen to contain sensitive elements won't get simplified into wholly-sensitive collections when using these functions.
The functions affected by this change are:
* `chunklist`
* `concat`
* `flatten`
* `keys`
* `length`
* `lookup`
* `merge`
* `setproduct`
* `values`
* `zipmap`
> dependencies: update cty from v1.8.1 to v1.8.2

- terraform/context_plan2_test.go
- terraform/context_validate_test.go
- terraform/evaluate.go
- terraform/node_output.go
Non-root module outputs no longer strip sensitivity marks from their values, allowing dynamically sensitive values to propagate through the configuration. We also remove the requirement for non-root module outputs to be defined as sensitive if the value is marked as sensitive.
This avoids a static/dynamic clash when using shared modules that might unknowingly receive sensitive values via input variables.
Fixes #28431.
> core: Loosen output value sensitivity requirement

- command/login.go
- command/login_test.go
- command/meta.go
- command/testdata/login-tfe-server/tfeserver.go
When logging in to Terraform Cloud or Terraform Enterprise, this changes the success output to be a bit more customized for the platform. For Terraform Cloud, fetch a dynamic welcome banner that intentionally fails open and defaults to a hardcoded message if it's not available for any reason.
Additionally, after some research to ensure that adding a code for 256 color terminals shouldn't be a problem, I've added a Terraform purple color code to the default list of colorstring codes.
_Logging in to Terraform Cloud:_
_Logging in to Terraform Cloud (a failure case with trace logging enabled):_
_Logging in to Terraform Enterprise:_
> New login success output for TFC/E

- command/console.go
- go.sum
- lang/funcs/conversion.go
- lang/funcs/conversion_test.go
- lang/functions.go
- lang/scope.go
- repl/format.go
- website/docs/configuration/functions/type.html.md
The `type() function`, which is only available for terraform console,
prints out a string representation of the type of a given value. This is mainly intended for
debugging - it's handy to be able to directly inspect terraform's understanding
of a complex variable. 
This introduces a new field for `lang.Scope`: `ConsoleMode`. When `ConsoleMode` is true, any additional functions intended for use in the console (only) may be added.
(with bonus `go mody tidy` cleanup)
> lang/funcs: add (console-only) TypeFunction

- configs/configschema/decoder_spec.go
- configs/configschema/decoder_spec_test.go
- go.mod
- go.sum
- lang/blocktoattr/fixup.go
- plans/objchange/compatible.go
- plans/objchange/compatible_test.go
- plans/objchange/objchange.go
- terraform/context_validate_test.go
Make use of the new `hcldec.UnknownBody` feature in HCL to allow unknown `dynamic` blocks to be decoded as entirely unknown values. A more complete description of this new feature is in https://github.com/hashicorp/hcl/pull/461
Now that the dynamic sentinel values are no longer a factor, the logic around `couldHaveUnknownBlockPlaceholder` is no longer needed, as `AssertObjectCompatible` can directly check of the entire block container is unknown.
The `hcldec` package will also now no longer need terraform to change `MinItems` and `MaxItems` to account for dynamic blocks, because they will no longer be compared at all when dealing with unknown dynamic blocks.
The end result here is that providers will now be able to correctly customize (within the constraints of the [Resource Instance …
> Better planing of unknown dynamic blocks

- terraform/context_plan2_test.go
- terraform/node_resource_abstract.go
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_abstract_test.go
- terraform/node_resource_apply_instance.go
- terraform/node_resource_destroy.go
- terraform/node_resource_destroy_deposed.go
- terraform/node_resource_plan_instance.go
- terraform/node_resource_plan_orphan.go
If the configuration is storing sensitive values in a data source which cannot be read at plan time, those values must be unmarked before creating a planned read value.
This also updates the `UpgradeResourceState` codepaths to use `Diagnostics`, and add configuration context when possible. 
Fixes #28535
> Unmark config values when planning a data source read

- command/jsonplan/plan.go
- command/show_test.go
- command/testdata/show-json-sensitive/main.tf
- command/testdata/show-json-sensitive/output.json
- configs/configschema/marks.go
- configs/configschema/marks_test.go
- terraform/evaluate.go
- terraform/evaluate_test.go
When rendering a stored plan file as JSON, we include a data structure representing the sensitivity of the changed resource values (#28201). Prior to this commit, this was a direct representation of the sensitivity marks applied to values via mechanisms such as sensitive variables, sensitive outputs, and the `sensitive` function.
This commit extends this to include sensitivity based on the provider schema. This is in line with the UI rendering of the plan, which considers these two different types of sensitivity to be equivalent.
Fixes #28522.
> core: Add sensitive provider attrs to JSON plan

- terraform/node_provider.go
- terraform/node_provider_test.go
- terraform/node_resource_abstract_instance.go
There were some remaining calls to providers where configuration could be
added to diagnostics, warnings would not get config annotations,
or the diagnostics were skipped entirely.
To ensure that real provider diagnostics with configuration information are
maintained, `ConfigureProvider` errors now append a separate message
about missing configuration instead of relying on the diagnostic `Err()`
string format.
> Add more diagnostic configuration context to provider methods

- website/docs/cli/commands/apply.html.md
- website/docs/cli/commands/init.html.md
- website/docs/cli/commands/plan.html.md
**Reasoning for docs update**: fix spelling of "normally" in the sentence which is found in `init`, `plan`, `apply` docs
**Relevant Terraform version**: current
> docs: correct spelling of normally

- command/format/diff.go
- command/format/diff_test.go
When rendering a plan diff, sensitive resource attributes would previously omit the "forces replacement" comment, which can lead to confusion when the only reason for a resource being replaced is a sensitive attribute.
Fixes #28540.
> cli: Show forces replacement for sensitive attrs

- command/views/json/change.go
- command/views/operation_test.go
Now that we have extra information about the reason for a given resource action, include that in the JSON log output for planned changes.
> command/views: Add reason to JSON planned change

- command/apply.go
- command/apply_test.go
- command/arguments/apply_test.go
- command/arguments/extended.go
- command/format/diff.go
- command/plan.go
- command/plan_test.go
- command/show_test.go
- command/testdata/apply-replace/main.tf
- command/testdata/plan-replace/main.tf
- terraform/node_resource_abstract_instance.go
- terraform/node_resource_plan.go
- website/docs/cli/commands/plan.html.md
- website/docs/cli/commands/taint.html.md
- website/docs/cli/commands/untaint.html.md
This allows a similar effect to pre-tainting an object but does the action within the context of a normal plan and apply, avoiding the need for an intermediate state where the old object still exists but is marked as tainted.
```
terraform plan -replace=null_resource.blah
terraform apply -replace=null_resource.blah
```
The core functionality for this was already present from #28560, so this commit is just the UI-level changes to make that option available for use and to explain how it contributed to the resulting plan in Terraform's output. It does include one little tweak to the core-level implementation to respond to some error reporting feedback I deferred in #28560.
As with instances that are marked as tainted in the prior state, an instance that is forced for replacement gets a …
> command: New -replace=... planning option

- backend/remote/backend_mock.go
- go.mod
- go.sum
The go-tfe client used in the remote backend is an aging version, so to ensure stability in the 0.15.x series and in anticipation of adding new things and avoiding potential unrelated regressions at that time, bump the client to latest.
> Update go-tfe client to v0.14.0

- go.mod
- go.sum
Upstream changelog:
* `function/stdlib`: Fix a panic in `SetproductFunc` in situations where one of the input collections is empty. ([#103](https://github.com/zclconf/go-cty/pull/103))
* `function/stdlib`: Improvements to `ElementFunc`, `ReverseListFunc`, and `SliceFunc` to handle marked values more precisely (individual element vs. whole-collection marks). ([#101](https://github.com/zclconf/go-cty/pull/101))
Fixes #28524
> Upgrade cty to 1.8.3

- configs/provider_validation.go
- configs/testdata/config-diagnostics/pass-inherited-provider/main.tf
- configs/testdata/config-diagnostics/pass-inherited-provider/mod/main.tf
- configs/testdata/config-diagnostics/pass-inherited-provider/mod2/main.tf
- configs/testdata/config-diagnostics/pass-inherited-provider/warnings
- configs/testdata/config-diagnostics/unknown-root-provider/main.tf
- configs/testdata/config-diagnostics/unknown-root-provider/mod/main.tf
- configs/testdata/config-diagnostics/unknown-root-provider/warnings
- terraform/context_validate_test.go
- terraform/transform_provider.go
Add validation for the local side of the providers map assignments in module calls. If these did not actually correspond to a configuration during runtime, the user would be presented with a `missing provider` error with the assumed address of the provider, but no indication how to configure that address. We can detect these during validation, and present a much more precise error
```
╷
│ Warning: No configuration passed in for provider aws in module.mod1
│
│   on mod1/main.tf line 15, in module "mod2":
│   15:     aws.local = aws
│
│ Provider aws is referenced within module.mod1, but no configuration has been supplied.
│ Add a provider named aws to the providers map for module.mod1 in the root module.
```
It was also assumed that inherited providers could be referenced within modules, …
> Validate passing default providers through modules

- command/apply_test.go
- command/init_test.go
- command/plan_test.go
- command/refresh_test.go
- command/show_test.go
Adding some tests for init and plan - working off our (internal) cli command audit spreadsheet.
I'm currently ignoring tests for statefile lock/lock-timeout: it is tested in backend/remote and backend/local. That's not to say it's not worth adding, just that I'm not worrying about those right this minute.
> command tests: plan and init

- command/jsonplan/plan.go
- command/jsonplan/plan_test.go
- command/testdata/show-json/requires-replace/output.json
- website/docs/internals/json-format.html.md
The set of paths which caused a resource update to require replacement has been stored in the plan since 0.15.0 (#28201). This commit adds a simple JSON representation of these paths, allowing consumers of this format to determine exactly which paths caused the resource to be replaced.
This representation is intentionally more loosely encoded than the JSON state serialization of paths used for sensitive attributes. Instead of a path step being represented by an object with type and value, we use a more-JavaScripty heterogenous array of numbers and strings. Any practical consumer of this format will likely traverse an object tree using the index operator, which should work more easily with this format. It also allows easy prefix comparison for consumers which are tracking paths.
While …
> jsonplan: Add replace_paths

- configs/configschema/marks.go
- configs/configschema/marks_test.go
When comparing values in a plan, the prior value can be null.
> null check in ValueMarks

- terraform/node_resource_abstract_instance.go
- terraform/node_resource_plan_orphan.go
- terraform/node_resource_plan_orphan_test.go
If we don't do this then we can create a situation where refresh detects that an object already doesn't exist but we plan to destroy it anyway, rather than returning "no changes" as expected. Often that's harmless because deleting is idempotent anyway, but there are also many APIs that treat deleting a non-existing object as special sort of error which would then cause a failure during apply.
By writing the unit test for this I also noticed that we were failing to generate a `NoOp` plan for the resource in that case. Again, that's not something that's a _major_ big deal, but for our JSON plan output we produce plans for every resource instance we considered during planning so that certain external consumers can distinguish "we've confirmed that this instance needs to changes" from "this …
> core: If we refresh during orphan processing, use the result for planning

- lang/funcs/collection.go
- lang/funcs/collection_test.go
We improved marks support for these two functions in https://github.com/zclconf/go-cty/pull/98, not realizing that Terraform has its own separate and incompatible implementations. These commits bring across essentially the same changes, re-applied to these local versions.
Similar to cty's implementation, we only need to preserve marks from the value itself, not any nested values it may contain. This means that taking the length of an umarked list with marked elements results in an unmarked number.
Several changes to `lookup` to improve how we handle marked values:
- If the entire collection is marked, preserve the marks on any result (whether successful or fallback)
- If a returned value from the collection is marked, preserve the marks from only that value, combined with any overall …
> Improve marks support for `length` and `lookup`

- plans/planfile/planfile_test.go
- plans/planfile/reader.go
Our model for `plans/planfile` has unfortunately grown inconsistent with changes to our modeling of `plans.Plan`.
Originally we considered the plan "header" and the planned changes as an entirely separate artifact from the prior state, but we later realized that carrying the prior state around with the plan is important to ensuring we always have enough context to faithfully render a plan to the user, and so we added the prior state as a field of `plans.Plan`. More recently we've also added the "previous run state" to `plans.Plan` for similar reasons.
Unfortunately as a result of that modeling drift our `ReadPlan` method was silently producing an incomplete `plans.Plan` object, causing use-cases like `terraform show` to produce slightly different results due to the plan object not …
> plans/planfile: Read state snapshots as part of reading a plan

- terraform/context_plan2_test.go
- terraform/node_resource_plan_instance.go
Previously in refresh-only mode we were skipping making any updates to the working state at all. That's not correct, though: if the state upgrade step detected changes then we need to at least commit _those_ to the working state, because those can then be detected by downstream objects like output values.
Although this incorrect code has been included in a release, it wasn't actually reachable because we haven't made any releases with `-refresh-only` available as an end-user planning mode yet. I found this while working on #28634, where I noticed that refresh-only mode made output values not update until the subsequent plan+apply.
> core: Update working state for resource instances in refresh-only mode

- backend/local/backend_apply.go
- backend/local/backend_plan.go
- command/show.go
- command/views/operation.go
- command/views/operation_test.go
- command/views/plan.go
- command/views/show.go
In practice the current implementation isn't actually using this, and if we need access to states in future we can access them in either the `plan.PriorState` or `plan.PrevRunState` fields, depending on which stage we want a state snapshot of.
(Technically these two plan fields aren't reliably available until we also merge #28653, but that's moot here because the current view code doesn't access either of them anyway. #28634 will eventually make use of this to produce the "Objects have changed outside of Terraform" bit, though.)
> command/views: Remove baseState argument from plan-rendering views

- command/apply.go
- command/import.go
- command/plan.go
- command/refresh.go
- command/state_mv.go
- command/state_push.go
- command/state_replace_provider.go
- command/state_rm.go
- command/taint.go
- command/untaint.go
- command/workspace_delete.go
- command/workspace_new.go
- website/docs/cli/commands/apply.html.md
- website/docs/cli/commands/import.html.md
- website/docs/cli/commands/plan.html.md
- website/docs/cli/commands/state/mv.html.md
- website/docs/cli/commands/state/push.html.md
- website/docs/cli/commands/state/replace-provider.html.md
- website/docs/cli/commands/state/rm.html.md
- website/docs/cli/commands/taint.html.md
- website/docs/cli/commands/untaint.html.md
- website/docs/cli/commands/workspace/delete.html.md
- website/docs/cli/commands/workspace/new.html.md
- website/docs/language/settings/backends/remote.html.md
We previously had only very short descriptions of what `-ignore-remote-version` does due to having the documentation for it inline on many different command pages and `-help` output.
Instead, we'll now centralize the documentation about this argument on the remote backend page, and link to it or refer to it from all other locations. This then allows us to spend more words on discussing what Terraform normally does _without_ this option and warning about the consequences of using it.
This continues earlier precedent for some local-backend-specific options which we also don't recommend for typical use. While this does make these options a little more "buried" than before, that feels justified given that they are all "exceptional use only" sort of options where users ought to learn about …
> cli+website: -ignore-remote-version doc elaboration and other cleanup

- backend/remote/backend.go
- backend/remote/backend_test.go
Currently, the error when we fail to read the organization entitlements while configuring the remote backend is a little cryptic:
It implies that the organization definitely does not exist, but in practice, there are any number of reasons why we might get an error there: the user may have misspelled the organization name, forgotten to specify the hostname (causing it to default to `app.terraform.io`), or be using an API token that's been revoked.
Surfacing more information and common debugging steps should help users resolve this problem more easily.
> backend/remote: clearer error when we fail to read the organization

- command/format/diff.go
- command/jsonplan/plan.go
- command/jsonplan/values.go
- plans/changes_src.go
- plans/changes_test.go
- plans/objchange/normalize_obj.go
- terraform/context_apply2_test.go
- terraform/context_plan_test.go
- terraform/evaluate.go
- terraform/node_output.go
When decoding change values, the stored marks should be applied to the decoded value, as this is the direct inverse of the `Encode` operation. The missing marks were not noticed in most cases because they would be correctly re-evaluated on demand, however some cases like module output values can rely on the change source alone, resulting in the marks being lost during apply.
Many call sites which were aware that the marks were missing would manually apply the marks after decoding. After removing the duplicate marking and verifying tests, `Decode` call sites were again statically located and checked for mark handling. Any locations found that were relying on the _absence_ of marks now must manually strip the marks before processing the values.
Fixes #28671
> Decode change values with marks

- terraform/evaluate_valid.go
- terraform/evaluate_valid_test.go
- terraform/testdata/static-validate-refs/static-validate-refs.tf
It's a relatively common mistake to try to refer to a data resource without including the data. prefix, making Terraform understand it as a reference to a managed resource.
To help with that case, we'll include an additional suggestion if we can see that there's a data resource declared with the same type and name as in the given address.
> core: "Did you mean" hint for missing data. prefix in references

- website/docs/cli/commands/apply.html.md
- I'm using distinct subheaders and smaller paragraphs to try and make the info
about apply's two modes more skimmable.
- I'm also adding a separate "Plan Options" subheader (and keeping the section
tiny so it stays snugged up right next to the "Apply Options" one) to make it
extra-clear that Hey, There's More Options, They're Over There.
> website: Make apply's usage of plan options harder to miss

- command/meta_providers.go
- command/plugins.go
- internal/logging/logging.go
Once a plugin process is started, go-plugin will redirect the stdout and
stderr stream through a grpc service and provide those streams to the
client. This is rarely used, as it is prone to failing with races
because those same file descriptors are needed for the initial handshake
and logging setup, but data may be accidentally sent to these
nonetheless.
The usual culprits are stray `fmt.Print` usage where logging was
intended, or the configuration of a logger after the os.Stderr file
descriptor was replaced by go-plugin. These situations are very hard for
provider developers to debug since the data is discarded entirely.
While there may be improvements to be made in the go-plugin package to
configure this behavior, in the meantime we can add a simple monitoring
io.Writer to the streams …
> monitor plugin std outputs for unexpected data

- addrs/parse_ref.go
- addrs/parse_ref_test.go
- configs/escaping_blocks_test.go
- configs/module_call.go
- configs/provider.go
- configs/provisioner.go
- configs/resource.go
- configs/testdata/escaping-blocks/data/data-escaping-block.tf
- configs/testdata/escaping-blocks/module/module-escaping-block.tf
- configs/testdata/escaping-blocks/provider/provider-escaping-block.tf
- configs/testdata/escaping-blocks/resource/resource-escaping-block.tf
- lang/eval.go
- lang/eval_test.go
The Terraform language has always had a number of situations where reserved words defined in the language can appear in the same location as externally-defined names provided by either providers or modules. These are:
* In `provider`, `resource`, and `data` blocks Terraform overlays reserved meta-arguments onto the relevant provider schema, effectively masking any provider-defined argument with a conflicting name.
* In `module` blocks Terraform overlays reserved meta-arguments onto the set of input variable names defined in the module. Currently we block modules from declaring such conflicting names, but that means that adding any new meta-arguments here is a breaking change for existing modules, as we previously saw when we reserved `count` in the v0.12 release.
* In `provisioner` blocks …
> Mechanisms to allow for future language extension

- command/init.go
- command/init_test.go
- command/meta.go
- command/meta_backend.go
- command/meta_backend_test.go
- command/state_rm_test.go
- website/docs/cli/commands/init.html.md
When terraform detects a change in the stored backend configuration, it will always attempt to setup a state migration. This often presents a problem for users when the stored configuration is no longer valid in some way, usually due to changes in authentication or accidental misconfiguration. The failure mode here can be quite confusing, as the error may show "Access Denied" or similar for what the user intends to be the current backend, though it is originating from the stored configuration.
Since init is a required part of the workflow, the majority of time that init is executed, migration is not expected. In the cases where it is desired, the user should already be aware of the change because there was a change in the configuration. This would also match the behavior of running …
> Prevent automatic backend migration during `terraform init`

- command/init.go
- command/init_test.go
- command/meta.go
- command/meta_backend.go
- command/meta_backend_test.go
- command/state_rm_test.go
- website/docs/cli/commands/init.html.md
> backport #28718: Prevent automatic backend migration during `terraform init`

- internal/backend/local/backend_apply.go
- internal/backend/local/backend_apply_test.go
Make sure to collect apply diagnostics before persisting the backend
state so runtime errors are not lost.
Closes #28708
> save apply diagnostics on backend failure

- internal/backend/local/backend_apply.go
- internal/backend/local/backend_apply_test.go
Make sure to collect apply diagnostics before persisting the backend
state so runtime errors are not lost.
> backport #28724: save apply diagnostics on backend failure

- internal/command/format/diff.go
- internal/command/format/diff_test.go
When an attribute value changes in sensitivity, we previously rendered this in the diff with a `~` update action and a note about the consequence of the sensitivity change. Since we also suppress the attribute value, this made it impossible to know if the underlying value was changing, too, which has significant consequences on the meaning of the plan.
This commit adds an equality check of the old/new underlying values. If these are unchanged, we add a note to the sensitivity warning to clarify that only sensitivity is changing.
Fixes #28593. This is a more conservative change that the one I originally proposed in that issue, but I think it's a reasonable step forward.
> cli: Improve sensitivity change warning output

- internal/command/e2etest/unmanaged_test.go
- internal/command/meta_providers.go
- main.go
This PR uses the 1.4.1 release if [go-plugin](https://github.com/hashicorp/go-plugin) which includes a providers' protocol version in the reattachConfig, so terraform can choose the proper `plugin.Client` when it's available. Terraform will still default to protocol v5 if the reported NegotiatedVersion is 0 so we don't break all of the existing sdkv2 providers' acceptance tests (you can confirm this at home by running the acc tests in terraform-provider-random. If we don't default to protocol v5, the tests fail).
I updated the e2etest test so we can see that terraform can handle both protov5 and protov6 plugins.
Depends on https://github.com/hashicorp/terraform/pull/28465
> terraform: use ProtocolVersion from unmanaged providers' reattachConfig to chose the correct PluginClient

- website/docs/cli/commands/plan.html.md
Fix some typos in the `Command: plan` docs site.
- speculative plan, which is a description of **a the** effect -> speculative plan, which is a descripiton of **the** effect
- This option is **particular** useful when running Terraform -> This option is **particularly** useful when running Terraform
- Limit the number of concurrent **operation** as Terraform -> Limit the number of concurrent **operations** as Terraform
> docs(plan): fix minor typos

- website/docs/language/functions/substr.html.md
Document that negative indexes are valid in `substr` 
Closed #28669
> negative substring indexes

- internal/builtin/provisioners/file/resource_provisioner.go
- internal/builtin/provisioners/file/resource_provisioner_test.go
- internal/builtin/provisioners/local-exec/resource_provisioner.go
- internal/builtin/provisioners/remote-exec/resource_provisioner.go
- internal/builtin/provisioners/remote-exec/resource_provisioner_test.go
- internal/terraform/node_resource_abstract_instance.go
The calls to resource provisioners were still converting diagnostics to error, which was losing any detail information. We also need to ensure that the builtin provisioners return diagnostics which can be annotated with config context.
Fixes #28707
> return diagnostics from provisioners

- internal/command/providers_lock.go
- internal/command/providers_lock_test.go
- internal/command/providers_mirror_test.go
- internal/command/testdata/providers-lock/basic/main.tf
- internal/getproviders/types.go
- internal/getproviders/types_test.go
There are a few small changes in this PR:
- Tests for providers lock, go me
- I replaced a clearly copy-pasta'd error message with a more appropriate "Invalid provider argument" error - please do nitpick my wording.
- Writing tests for providers lock unearthed a very tiny bug in `getproviders.ParsePlatform`, so a fix for that (including tests) is in here too. 
- Barely worth mentioning providers mirror "tests" (emphasis on the airquotes)
> providers lock tests

- internal/terraform/node_resource_abstract_instance.go
- internal/terraform/transform_orphan_resource.go
- internal/terraform/transform_orphan_resource_test.go
If an orphaned resource only consists of deposed instances, there will be no current state with which to plan, causing a panic when accessing the stored private data. There is no reason however to access this private field for a noop change in a destroyed instance, so avoid the field altogether since we accept that the state may be nil here anyway. 
We also should not have been planning to delete an orphan here in the first place, since there is no current instance state to plan. We can skip any instances with no current state when adding orphan nodes to the graph.
Fixes #28763
> Fix crash with deposed instances in orphaned resources

- internal/command/format/diff.go
- internal/command/views/operation_test.go
- internal/command/views/plan.go
We need to take into account that resources may not have a current instance, or not have semantically relevant changes to the current instance when rendering drift in the UI.
In the first case, the renderer can panic when attempting to decode a nil current instance. In the latter case, we print the `Objects have changed ...` header because the state has changes to the data, while the current instances may still be unchanged. 
Add checks for missing `Current` instance states, and skip printing empty diffs altogether.
Fixes #28789
Fixes #28776
> plan: handle deposed instances when rendering drift

- website/docs/cli/config/config-file.html.md
The current documention was unclear about the full path of local mirrors
when using the XDG Base Directory Specification.
Also removed the trailing slashes for the other paths in this section.
> website: Give example plugin location when using XDG Base Directory

- website/docs/cli/commands/console.html.md
These examples showcase come use cases for `terraform console`.
> website: add examples for `terraform console`

- internal/terraform/transform_import_state.go
- internal/terraform/transform_import_state_test.go
Most legacy provider resources do not implement any import functionality
other than returning an empty object with the given ID, relying on core
to later read that resource and obtain the complete state. Because of
this, we need to check the response from ReadResource for a null value,
and use that as an indication the import ID was invalid.
Fixes #28637
> return error for invalid resource import

- internal/command/views/json/message_types.go
- internal/command/views/json_view.go
This was dead code, and there is no clear way to retrieve this information, as we currently only derive the drift information as part of the plan rendering process.
> command/views: Remove unused drift summary message

- website/docs/cli/commands/apply.html.md
- website/docs/cli/commands/plan.html.md
- website/docs/internals/machine-readable-ui.html.md
Terraform 0.15.3 added support for a `-json` flag to the plan, apply, and refresh commands, which renders the Terraform UI output in a structured machine readable format. This commit adds documentation for this interface.
> website: Add documentation for machine readable UI

- internal/backend/local/backend_local.go
- internal/backend/local/backend_local_test.go
When returning from the context method, a deferred function call checked for error diagnostics in the `diags` variable, and unlocked the state if any exist. This means that we need to be extra careful to mutate that variable when returning errors, rather than returning a different set of diags in the same position.
Previously this would result in an invalid plan file causing a lock to become stuck. Fixes #28693.
The `defer` in question: https://github.com/hashicorp/terraform/blob/a3b1764fd7d8acf110a55bf0830d2b42696c0a51/internal/backend/local/backend_local.go#L47-L53
> backend/local: Fix lock when applying stale plan

- internal/backend/remote/backend.go
Adds a bit more information to the error message when remote backend users attempt to use `terraform refresh` so they know there's another option.
> backend/remote: point refresh users towards -refresh-only

- internal/initwd/module_install.go
- internal/initwd/module_install_test.go
- internal/initwd/testdata/load-module-package-escape/child/package-escape-child.tf
- internal/initwd/testdata/load-module-package-escape/grandchild/package-escape-grandchild.tf
- internal/initwd/testdata/load-module-package-escape/package-escape.tf
- internal/initwd/testdata/load-module-package-prefix/package-prefix.tf
- internal/initwd/testdata/load-module-package-prefix/package/child/package-prefix-child.tf
- internal/initwd/testdata/load-module-package-prefix/package/grandchild/package-prefix-grandchild.tf
- website/docs/language/modules/sources.html.md
Our module installer has a somewhat-informal idea of a "module package", which is some external thing we can go fetch in order to add one or more modules to the current configuration. Our documentation doesn't talk much about it because most users seem to have found the distinction between external and local modules pretty intuitive without us throwing a lot of special terminology at them, but there are some situations where the distinction between a module and a module package are material to the end-user.
One such situation is when using an absolute rather than relative filesystem path: we treat that as an external package in order to make the resulting working directory theoretically "portable" (although users can do various other things to defeat that), and so Terraform will copy the …
> initwd: Error message for local paths escaping module packages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
The issues tracker for this project is for Terraform CLI bugs and feature requests only; so let's be a little more preemptive about it!
The remote backend is indeed tracked and worked on here, but I didn't think that distinction would be useful to differentiate on generally. 🤷‍♂️
> Add support reference for TFC-related issues

- .github/ISSUE_TEMPLATE/config.yml
Interestingly, I just learned that the GitHub template config.yml `url` doesn't support `mailto` prefixes. Oops! Let's use the support form instead, which is probably better anyway.
Fixes #28865  😅
> Fix support link (mailto is not supported in GitHub template URLs)

- docs/README.md
- docs/unicode.md
Previously this is a task that I've just taken on using my own knowledge of how these parts fit together, but that's not at all a sustainable situation, and so here I've just documented the steps I've followed in for previous Unicode version upgrades, and thus which I'd expect to follow for future Unicode version upgrades too.
I hope this is also a somewhat-interesting overview of how Terraform makes use of Unicode, even for folks who are just working on the other relevant features of Terraform and not specifically trying to change Terraform's Unicode support.
Since I'm the primary maintainer of two of the external dependencies involved in this it seems likely that following this process will still involve interactions with me in _some_ capacity, but hopefully only necessarily in the form …
> docs: Some notes on adopting new Unicode versions

- internal/command/init.go
- internal/command/meta_backend_migrate.go
Two changes, both addressing the same underlying issue:
- Fix faulty state migration version check when using multiple workspaces
When migrating multiple local workspaces to a remote backend target using the `prefix` argument, we need to perform the version check against all existing workspaces returned by the `Workspaces` method. Failing to do so will result in a version check error.
- Add `-ignore-remote-version` flag for init as a fallback
When performing state migration to a remote backend target, Terraform may fail due to mismatched remote and local Terraform versions. Here we add the `-ignore-remote-version` flag to allow users to ignore this version check when necessary.
Unfortunately neither of these are easily unit tested. I've manually verified that this fixes #28858 when …
> Fix remote backend multi workspace state migration

- website/docs/language/v1-compatibility-promises.html.md
Seems like we lost a newline in some of the shuffling it took to get this into the live website, and so it's formatting oddly in the rendered website. This restores the intended formatting of this as the start of a bullet list, rather than as a continuation of the previous paragraph.
> website: Fix formatting of v1 compatibility promises

- internal/backend/remote/backend.go
Backporting this small change from https://github.com/hashicorp/terraform/pull/28820 into the 1.0 branch since I foolishly merged that PR into main without applying a backport label.
> backport changes to refresh error message to v1.0

- internal/backend/remote/backend_plan.go
- internal/backend/remote/backend_plan_test.go
Historically, we've used TFC's default run messages as a sort of dumping
ground for metadata about the run. We've recently decided to mostly stop
doing that, in favor of:
- Only specifying the run's source in the default message.
- Letting TFC itself handle the default messages.
Today, the remote backend explicitly sets a run message, overriding
any default that TFC might set. This commit removes that explicit message
so we can allow TFC to sort it out.
This shouldn't have any bad effect on TFE out in the wild, because it's
known how to set a default message for remote backend runs since late 2018.
> Remote backend: Stop setting message when creating runs

- internal/command/jsonconfig/expression.go
- internal/command/jsonconfig/expression_test.go
- internal/command/show_test.go
- internal/command/testdata/show-json/modules/output.json
- internal/command/testdata/show-json/sensitive-values/output.json
The "references" included in the expression representation now properly unwrap for each traversal step, to match what was documented.
This fixes https://github.com/hashicorp/terraform/issues/28860
[update: I made the version bump in a later PR] There isn't a format version specific to the configuration representation, and we're not changing the overall format of the plan representation, so I did not increase the plan's format version. I'm not confident about that, I will do so if anyone disagrees!
> jsonconfig: properly unwind and enumerate references

- internal/plans/objchange/plan_valid.go
- internal/plans/objchange/plan_valid_test.go
An unknown block represents a dynamic configuration block with an
unknown for_each value. We were not catching the case where a provider
modified this value unexpectedly, which would crash with block of type
NestingList blocks where the config value has no length for comparison.
Fixes #28929
> handle unexpected changes to unknown block

- internal/communicator/ssh/communicator.go
- internal/communicator/ssh/communicator_test.go
Terraform builds `scp` command used in the ssh communicator directly from user input, without any sort of sanitization or quoting. This allows for command injection via `destination` argument in the provisioner block. 
The security implications of this are minimal, because Terraform provisioners already allow code execution. Regardless, Terraform should quote the user input when constructing the `scp` command, so `destination` is not a vector for code exec. 
This change adds quotes around the user input in the `scp` command. This change is not friendly to filenames that contain a quote - any pre-existing quotes will be removed. In theory this change could break existing Terraform code, but this mechanism of concatenating things into an `scp` command already seems a bit brittle.
> Quoting filesystem path in scp command argument

- commands.go
- internal/command/add.go
- internal/command/add_test.go
- internal/command/arguments/add.go
- internal/command/arguments/add_test.go
- internal/command/command_test.go
- internal/command/testdata/add/basic/main.tf
- internal/command/testdata/add/module/main.tf
- internal/command/testdata/add/module/module/main.tf
- internal/command/views/add.go
- internal/command/views/add_test.go
- website/docs/cli/commands/add.html.md
- website/docs/cli/commands/index.html.md
- website/layouts/docs.erb
`terraform add` generates resource configuration templates which can be filled out and used to create resources. 
The template is output in stdout unless the `-out` flag is used. By default, only required attributes are included and the values all set to `null`, with a comment indicating the expect value type (`string`, `list of object`, etc). The `-optional` flag  tells `add` to include all optional attributes as well. 
When the `-from-state=ADDRESS` flag is used, `add` will copy the values from that resource's state into the template. For this initial release, terraform does not copy any values that are `sensitive` according to the provider schema; a future release may add a mechanism to overrides this behavior. (`-from-state` currently ignores the `-optional` flag and prints all …
> commands: `terraform add`

- internal/lang/blocktoattr/fixup.go
- internal/lang/blocktoattr/fixup_test.go
When `blocktoattr.fixupBody` returned its content, the value for
`MissingItemRange` was omitted, losing the diagnostic Subject.
Fixes #28976
> blocktoattr fixup dropping MissingItemRange

- internal/command/jsonplan/plan.go
- internal/command/show_test.go
- internal/command/testdata/show-json/drift/main.tf
- internal/command/testdata/show-json/drift/output.json
- internal/command/testdata/show-json/drift/terraform.tfstate
Previously, if any resources were found to have drifted, the JSON plan output would include a drift entry for every resource in state. This commit aligns the JSON plan output with the CLI UI, and only includes those resources where the old value does not equal the new value—i.e. drift has been detected.
Also fixes a bug where the "address" field was missing from the drift output, and adds some test coverage.
(I attempted to refactor the code which determines which resources have drifted into a single location, but got stuck with import cycles. We make the decision about drift very late, after decoding the state values using the provider schema, which means that the implementation needs to refer to the `states`, `plans`, and `terraform` packages, while being called from `command/views` and …
> json-output: Omit unchanged resource_drift entries

- website/docs/cli/config/config-file.html.md
- website/docs/language/functions/templatefile.html.md
- website/docs/language/settings/backends/configuration.html.md
- website/docs/language/settings/backends/remote.html.md
As discussed internally this will help us (and anyone else) with building better editor experience in the Terraform language server and in editors for these file types.
Related issues:
- https://github.com/hashicorp/vscode-terraform/issues/636
- https://github.com/hashicorp/terraform-ls/issues/521
- https://github.com/hashicorp/terraform-ls/issues/518
> docs: Document naming conventions for templates & backend configs

- internal/addrs/module.go
- internal/addrs/module_instance.go
- internal/addrs/resource.go
- internal/addrs/targetable.go
- internal/configs/module.go
- internal/configs/moved.go
- internal/configs/moved_test.go
- internal/configs/parser_config.go
- internal/configs/testdata/invalid-files/everything-is-a-plan.tf
- internal/experiments/experiment.go
This PR adds decoding for the upcoming "moved" blocks in configuration. This code is gated behind an experiment called `EverythingIsAPlan`, but the experiment is not registered as an active experiment, so it will never run (there is a test in `configs` which will fail if the experiment is registered, so we'll know exactly when we need to deal with that). 
There is some validation missing still: this does not validate if the actual resource types (when that's what we're moving) are the same (I've put this off in part because we will eventually need the provider schema to verify aliased resources, so I suspect this validation will have to happen later on). I also expect that not all validate targetable address types will be moveable (`addrs.ConfigResource` comes to mind), but I wasn't sure …
> configs: add decodeMovedBlock behind a locked gate.

- go.mod
- go.sum
Fixes #28984. @jbardin, does the `flatten` change have a corresponding Terraform issue?
* `function/stdlib`: The `flatten` function will now correctly return `cty.DynamicVal` if it encounters `cty.DynamicVal` anywhere in the given data structure, because it can't predict how many elements the result will have in that situation. ([#106](https://github.com/zclconf/go-cty/pull/106), [#107](https://github.com/zclconf/go-cty/pull/107))
* `function/stdlib`: The `setproduct` function will no longer panic when given a set containing unknown values, which would therefore be a set with an unknown length. ([#109](https://github.com/zclconf/go-cty/pull/109))
> Upgrade cty to v1.8.4

- website/docs/cli/commands/plan.html.md
- website/docs/language/values/variables.html.md
The `-var` command line option comes with the disadvantage that a user must contend both with Terraform's own parser and with the parser in whichever shell they've decided to use, and different shells on different platforms have different rules. That's why we typically recommend against using it except for very simple variable values.
Previously we've largely just assumed that folks know the appropriate syntax for the shell they chose, but it seems that command lines involving spaces and other special characters arise rarely enough in other commands that Terraform is often the first time someone needs to learn the appropriate syntax for their shell, and shells typically don't give good feedback about escaping.
We can't possibly capture all of the details of all shells in our docs, because …
> website: Explicit examples of -var escaping in various shells

- internal/command/format/diagnostic.go
- internal/command/views/json/diagnostic.go
- internal/command/views/json/diagnostic_test.go
- internal/command/views/json/testdata/diagnostic/error-whose-range-starts-at-a-newline.json
Because our snippet generator is trying to select whole lines to include in the snippet, it has some edge cases for odd situations where the relevant source range starts or ends directly at a newline, which were previously causing this logic to return out-of-bounds offsets into the code snippet string.
Newlines at the bounds of source ranges are inevitably a bit of an edge case when thinking about the line/column representation of positions rather than byte offsets, because newlines don't really exist as far as line/column representation is concerned: they are the boundary between the lines, not part of the lines themselves, and they therefore don't really have a real "column". Therefore we somewhat arbitrarily just decide to shift the range over to the start of the following line instead …
> command/views/json: Never generate invalid diagnostic snippet offsets

- internal/command/jsonstate/state.go
- internal/command/jsonstate/state_test.go
`ResourceInstanceObjectSrc.Decode` already handles marking the decoded values with any marks stored in `AttrSensitivePaths`, so re-applying those marks is not necessary and seems to be related to panics seen in the wild, as seen in #29042.
~I have yet to reproduce the reported panic in a test (or locally, for that matter), so I won't close the linked issue until we can get a reproduction/confirmation. The test case I added was not enough to cause a panic, even though the value was already marked.~
Update: @davidalger wrote a test for me, yay! @apparentlymart believes that an upstream fix he recently merged would fix this panic, but the code is still redundant (and yay, more test cases!) so I'd still like this reviewed.
> command/jsonstate: remove redundant remarking of resource instance

- main.go
Found a small typo in a comment in main.go
> Small comment typo

- internal/addrs/module.go
- internal/addrs/module_call.go
- internal/addrs/module_instance.go
- internal/addrs/move_endpoint.go
- internal/addrs/move_endpoint_test.go
- internal/addrs/moveable.go
- internal/addrs/output_value.go
- internal/addrs/parse_ref.go
- internal/addrs/parse_ref_test.go
- internal/addrs/parse_target.go
- internal/addrs/resource.go
- internal/command/jsonconfig/expression.go
- internal/configs/experiments.go
- internal/configs/module.go
- internal/configs/moved.go
- internal/configs/moved_test.go
- internal/configs/parser_config.go
- internal/configs/parser_config_dir_test.go
- internal/configs/testdata/invalid-modules/config-driven-move-experiment/config-driven-move-experiment.tf
- internal/configs/testdata/valid-modules/moved-blocks/moved-blocks-1.tf
- internal/configs/testdata/valid-modules/moved-blocks/moved-blocks-2.tf
- internal/experiments/experiment.go
- internal/lang/data_test.go
- internal/lang/eval.go
- internal/terraform/evaluate_valid.go
- internal/terraform/transform_reference.go
I had originally set out here to implement the more dynamic validation rules for config-driven move, but in the process of doing so I kept running into confusing situations where it wasn't clear whether a particular `addrs.AbsResourceInstance` or `addrs.ModuleInstance` was representing an absolute address as usual, or instead serving as our new kind of "relative address" that appears in the `moved` blocks.
After getting that messed up a few times I concluded that this was the sort of thing we'd intended the `addrs` package to encapsulate, so that the compiler can help us use addresses only in a consistent way. Therefore I've implemented some new types in the `addrs` package specifically for representing that sort of address, which I've called `MoveEndpoint`, `AbsMoveable`, and …
> Various preparation for Config-driven Move validation

- website/README.md
**Description**
Adding instructions describing how to preview documentation changes locally to the /website readme. Please note that CircleCI link check is failing, but it's just for the localhost address we give for previewing the website on the user's local machine. We can ignore this.
Requested review scope:
Review urgency:
I have:
> Add instructions to preview docs site locally to /website readme

- website/layouts/language.erb
**Description**
Adding the v1 Compatibility Promises Content to the documentation sidebar in response to this Asana ticket [capability promises isn' in the terraform.io nav](https://app.asana.com/0/1128567758154570/1200539294164951/f).
I think our upgrade guides section could use a larger restructuring, but for now, let's just make sure that this content shows up in the navigation. My thought is that the compatibility promises make the most sense just after the v1.0 upgrade guide (separating it from the v0.x releases that have come before, but please let me know if there are other thoughts!
Requested review scope:
Review urgency:
I have:
> Add compatibility promises to sidebar toc

- go.mod
- go.sum
Update the cty library to v1.9.0 with the following changes:
* `cty`: `cty.Walk`, `cty.Transform`, and `cty.TransformWithTransformer` now all correctly support marked values. Previously they would panic when encountering marked collections, because they would try to recurse into them without handling the markings.
* `function/stdlib`: The `floor` and `ceil` functions no longer lower the precision of arguments to what would fit inside a 64-bit float, instead preserving precision in a similar way as most other arithmetic functions. ([#111](https://github.com/zclconf/go-cty/pull/111))
* `function/stdlib`: The `flatten` function was incorrectly treating null values of an unknown type as if they were unknown values. Now it will treat them the same as any other non-list/non-tuple value, …
> update go-cty to v1.9.0

- internal/command/views/json/message_types.go
- internal/command/views/json_view.go
- internal/command/views/json_view_test.go
- internal/command/views/operation.go
- internal/command/views/operation_test.go
- website/docs/internals/machine-readable-ui.html.md
The new `resource_drift` message allows consumers of the `terraform plan -json` output to determine which resources Terraform found to have changed externally after the refresh phase.
Note to reviewers: this implementation is a _third_ copy of the logic for determining resource drift for a plan. I'm not happy about this, but I'm struggling to see a way to extract the logic to a single place, given the intertwingled dependencies. Any suggestions?
> json-output: Add resource drift to machine readable UI

- website/README.md
Adding this because there are some gotchas associated with deploying changes to docs that live in the terraform repo.
> Add deploy information to website folder readme

- internal/addrs/module_instance.go
- internal/addrs/module_instance_test.go
- internal/states/state.go
- internal/states/state_test.go
- internal/states/sync.go
This PR adds `Move` functions for `AbsResouce`s, `AbsResouceInstance`s, and `ModuleInstance`s. The code was loosely inspired by the functionality in `internal/command/state_mv.go`, though these functions are all limited to a single state.
It is the caller's responsibility to confirm the validity of the moves. The functions will panic if the `src` does not exist or the `dst` does exist; I've added a `MaybeMove` version of each function which will succeed if the opposite is true. The return value of the `MaybeMove` functions indicates whether or not a move actually occurred. (Having said that, I'm less convinced of the utility of the `MaybeMove` funcs and have no qualms about dropping them)
Finally, I've added `SyncState` wrappers for all of these functions for good measure.
These are …
> states: new `Move` funcs for Resource, ResourceInstance, and ModuleInstances

- website/docs/cli/config/environment-variables.html.md
Adds anchor to environment variables documentation, to be used by this [terraform-website](https://github.com/hashicorp/terraform-website/pull/1772) PR.
You could scroll down there, but this is more convenient.
> website: Adds anchor for TF_CLI_ARGS.

- internal/command/views/json_view_test.go
- internal/command/views/operation_test.go
This test would previously fail randomly due to the use of multiple resource instances. Instance keys are iterated over as a map for presentation, which has intentionally inconsistent ordering.
To fix this, I changed the test to use different resource addresses for the three drift cases. I also extracted them to a separate test, and tweaked the test helper functions to reduce the number of fatal exit points, to make failed test debugging easier.
Targeted for backport to v1.0 because this test is over there, too.
> Fix flapping JSON output test

- internal/getproviders/registry_client.go
- internal/getproviders/registry_client_test.go
Update the version constraints for what providers will be downloaded
from the registry, allowing protocol 6 providers to be downloaded from
the registry.
> Add support for protocol 6 providers during init.

- internal/configs/configschema/decoder_spec.go
- internal/configs/configschema/decoder_spec_test.go
- internal/configs/configschema/implied_type.go
- internal/configs/configschema/implied_type_test.go
- internal/plans/objchange/objchange_test.go
(#29172)
* configs/configschema: fix missing "computed" attributes from NestedObject's ImpliedType
listOptionalAttrsFromObject was not including "computed" attributes in the list of optional object attributes. This is now fixed. I've also added some tests and fixed some panics and otherwise bad behavior when bad input is given. One natable change is in ImpliedType, which was panicking on an invalid nesting mode. The comment expressly states that it will return a result even when the schema is inconsistent, so I removed the panic and instead return an empty object.
> [BACKPORT] configs/configschema: fix missing "computed" attributes from NestedObject's ImpliedType

- internal/getproviders/registry_client.go
- internal/getproviders/registry_client_test.go
Update the version constraints for what providers will be downloaded
from the registry, allowing protocol 6 providers to be downloaded from
the registry.
(backport)
> [backport] Add support for protocol 6 providers during init. (#29153)

- internal/command/views/operation.go
- internal/command/views/operation_test.go
#29175 didn't work. This commit makes the output order of the resource drift messages stable, by building a slice of changes and sorting it by address.
I've run these tests locally 30 times in a row with no failures, which surely ought to be enough to be certain that it's stable…? 🤞
> Fix flapping JSON output test properly

- internal/backend/remote-state/etcdv3/backend_state.go
The current usage of internal remote state backends requires that
`StateMgr` be able to return an instance of `statemgr.Full` even if the
state is currently locked.
Fixes #28100
> StateMgr must be able to return with locked state

- CODEOWNERS
There have been no responses from the codeowner for this backend, so
moving to Unmaintained status.
> etcdv3 backend is unmaintained

- internal/backend/remote-state/pg/backend.go
- internal/backend/remote-state/pg/backend_test.go
- website/docs/language/settings/backends/pg.html.md
While it should not be possible to create two workspaces with the same name as the index should be created by the database administrator when `skip_index_creation` is used, this additional constraint will make it impossible to do so even if the index is missing.
I also reworded the documentation for the `skip_...` options which was inaccurate.
Discussion at https://github.com/hashicorp/terraform/issues/29034
> Add uniqueness constraint on workspaces name for the pg backend

- internal/backend/remote-state/oss/backend.go
- internal/backend/remote-state/oss/backend_test.go
The API DescribeEndpoint does not support STS authorizing and using the DescribeEndpoints instead.
```
TF_ACC=1 go test -v ./internal/backend/remote-state/oss/ -run=TestBackend -timeout 120m
backend_test.go:48: TestBackendConfig on *oss.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("terraform-backend-oss-test"), "key":cty.StringVal("first.tfstate"), "prefix":cty.StringVal("mystate"), "region":cty.StringVal("cn-beijing"), "tablestore_endpoint":cty.StringVal("https://terraformstate.cn-beijing.ots.aliyuncs.com"), "tablestore_table":cty.StringVal("TableStore")}}
--- PASS: TestBackendConfig (0.58s)
=== RUN   TestBackendConfigWorkSpace …
```
> backend/oss: Changes the DescribeEndpoint to DescribeEndpoints to fixes the unsupported sts bug

- internal/command/format/diff.go
- internal/command/format/diff_test.go
`writeNestedAttrDiff` wasn't prepared to handle entirely null maps. This commit adds a test (which reproduced the panic before the fix) and the same map handling that's in the nested _block_ format printer, which treats null maps as empty maps. 
Fixes #29205
> format/diff: fix panic with null map in NestedType attrs

- internal/terraform/context_apply2_test.go
- internal/terraform/context_plan_test.go
- internal/terraform/node_resource_abstract_instance.go
- internal/terraform/reduce_plan_test.go
Up until now marks were not considered by `ignore_changes`, that however
means changes to sensitivity within a configuration cannot be ignored, even
though they are planned as changes.
Rather than separating the marks and tracking their paths, we can easily
update the processIgnoreChanges routine to handle the marked values
directly. Moving the `processIgnoreChanges` call also cleans up some of
the variable naming, making it more consistent through the body of the
function.
Fixes #29173 in conjunction with https://github.com/hashicorp/hcl/pull/478
> Handle marks on ignore_changes values

- website/docs/cli/commands/validate.html.md
error_count (number): A zero or positive whole number giving the count of errors Terraform detected. If valid is 'true' then error_count will always be zero, because it is the presence of errors that indicates that a configuration is invalid.
> error_count

- go.mod
- go.sum
- internal/configs/configschema/validate_traversal_test.go
Update HCL to v2.10.1
* dynblock: Decode unknown dynamic blocks in order to obtain any diagnostics even though the decoded value is not used ([#476](https://github.com/hashicorp/hcl/pull/476))
* hclsyntax: Calling functions is now more robust in the face of an incorrectly-implemented function which returns a `function.ArgError` whose argument index is out of range for the length of the arguments. Previously this would often lead to a panic, but now it'll return a less-precice error message instead. Functions that return out-of-bounds argument indices still ought to be fixed so that the resulting error diagnostics can be as precise as possible. ([#472](https://github.com/hashicorp/hcl/pull/472))
* hclsyntax: Ensure marks on unknown values are maintained when processing string templates. …
> update hcl v2.10.1

- internal/configs/configschema/path.go
- internal/configs/configschema/path_test.go
This commit adds a recursive Object.AttributeByPath function which will step through Attributes with NestedTypes. If an Attribute without a NestedType is encountered while there is still more to the path, it will return nil.
> configs/configschema: extend block.AttributeByPath to descend into Objects

- website/docs/cli/install/apt.html.md
As part of this PR, just wanted to have this typo fixed to have a better sense of the sentence.
> `apt-add-repository` usually automatically runs `apt update` as part of its work in order to fetch the new package indices, but if it does not, then you will need to do so manually before the packages will be available.
Also, I wanted to rephrase the sentence as below(less wording and more readable- let me know if this is okay and I can raise a new pull request):
> `apt-add-repository` usually automatically runs `apt update` as part of its work to fetch the new package indices, but if it does not, you will need to manually do so before the packages will be available.
Thanks,
susenj
> Minor typo in apt.html.md

- website/docs/language/providers/index.html.md
Tiny PR to update a link on the Providers overview page to reflect new plugin docs revamp. Link should point to "Plugin Development" not "Extending Terraform."
> Update extending link to "plugin development"

- internal/addrs/move_endpoint_module.go
- internal/addrs/move_endpoint_module_test.go
Since moving resources requires doing some non-trivial "address arithmetic" we previously stubbed out some methods for that in the `addrs` package, which is typically where we centralize all of the logic for parsing and wrangling our address types.
This partially fills in those stub methods with enough logic to support `moved` blocks whose `from`/`to` addresses refer to either module calls or module instances. This includes both moving the modules themselves and also moving resources contained within those modules.
Relevant pre-existing context: The `refactoring.ApplyMoves` function uses these `MoveDestination` methods to recognize when it needs to move something in the state, and to see where it should move it to. Separate logic in `states.State` methods then actually manipulates the …
> addrs: Address rewriting logic for moves of module calls and module instances

- .github/ISSUE_TEMPLATE/bug_report.md
Change generic provider link to the registry, since the majority of providers are no longer under the terraform-providers org.
Remove example link to an individual user's repo.
> update GH issue template

- internal/addrs/move_endpoint_module.go
- internal/addrs/move_endpoint_module_test.go
This is a continuation of #29247 which finishes up the rules for resolving `moved` blocks, now handling the situation where a `moved` block contains either resource or resource instance addresses.
The two resource cases are somewhat simpler because resources can only contain resource instances and resource instances can't contain anything, so we don't need to deal with the case of only a prefix match on the address like we did with module instances in the previous PR.
The two sets of logic here end up looking textually very similar to a human reader, but that's just because `addrs.AbsResource` and `addrs.AbsResourceInstance` both have some method names in common. The Go compiler still sees the two as distinct, and so it's not straightforward to reuse the same codepath for both situations. …
> addrs: Address rewriting logic for moves of resources and resource instances

- internal/addrs/module_instance.go
- internal/instances/expander.go
- internal/instances/set.go
- internal/instances/set_test.go
- internal/refactoring/move_validate.go
- internal/terraform/context.go
This PR aims to resolve a TODO we previously left in `Context.Plan` to somehow gather the set of all declared module and resource instances to pass into the `refactoring.ValidateMoves` function.
I got there by creating a small wrapper around `instances.Expander` that provides an API more tailored to what move validation needs, and then passing that through to `refactoring.ValidateMoves` once we've finished creating the plan.
Since the instance expander only exists inside the graph walker this took a small amount of refactoring compared to what we originally stubbed in `Context.Plan`, where now the finding, applying, and validating of `moved` blocks happens in each of the separate plan mode methods rather than in the overall `Plan` method that dispatches to them. That's a little …
> Gather the data needed to implement refactoring.ValidateMoves

- internal/addrs/module_call.go
- internal/addrs/move_endpoint_module.go
- internal/addrs/moveable.go
- internal/addrs/resource.go
- internal/instances/set.go
- internal/refactoring/move_validate.go
- internal/refactoring/move_validate_test.go
- internal/refactoring/testdata/move-validate-zoo/child/move-validate-child.tf
- internal/refactoring/testdata/move-validate-zoo/move-validate-root.tf
This is a first pass at implementing `refactoring.ValidateMoves`, covering the main validation rules.
This is not yet complete. A couple situations not yet covered are represented by commented test cases in `TestValidateMoves`, although that isn't necessarily comprehensive. We'll do a further pass of filling this out with any other subtleties before we ship this feature.
The subtext here is that I ran out of time today and reached a reasonable stopping point and so I'd like to land this working subset before iterating on it further.
> refactoring: First round of ValidateMoves rules

- internal/backend/remote-state/consul/client.go
- internal/backend/remote-state/consul/client_test.go
The logic in e680211bc07d7037a3c6fa5dd869b884ca5a1b3b to determine whether a given state is small enough to fit in a single KV entry in Consul is buggy: because we are using the Transaction API we are base64 encoding it so the payload sent is actually bigger than the raw state, and there is some JSON overhead. This fixes this issue by always trying to store the state in a single entry, and we split it if Consul tells us that is too large. Because we don't try to guess we don't fail anymore.
As far as I know no user as encountered this bug but this patch should be backported to the 0.14 branch as it was the first version to have this feature in the Consul backend.
> Fix handling large states in the Consul backend

- internal/command/views/json/output.go
- internal/command/views/json/output_test.go
- internal/command/views/operation.go
- internal/command/views/operation_test.go
- website/docs/internals/machine-readable-ui.html.md
Extend the outputs JSON log message to support an `action` field (and make the `type` and `value` fields optional). This allows us to emit a useful output change summary as part of the plan, bringing the JSON log output into parity with the text output.
While we do have access to the before/after values in the output changes, attempting to wedge those into a structured log message is not appropriate. That level of detail can be extracted from the JSON plan output from `terraform show -json`.
Proposed for backport to 1.0.x, as I consider this to be a bug of omission (this message should have been omitted for plans) and it has narrow scope.
> json-output: Add output changes to plan logs

- website/docs/language/expressions/type-constraints.html.md
Fixed one typo found on the type constraints page:
recieving -> receiving
> Fixed typo on type-constraints.html.md

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
This follows https://github.com/hashicorp/terraform/pull/29251 and makes the remaining wording around providers more generic by pointing users to the Registry, which is now the source of truth for all these things.
Secondly I noticed that Contributor docs still mention codecov, which is no longer in use AFAICT.
> docs: Update outdated info about terraform-providers org

- website/docs/language/values/variables.html.md
Previously the docs never mentioned that it's possible to declare multiple `validation` blocks.
The wording mostly reflects the implementation https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/terraform/eval_variable.go#L46-L111
> docs: Add note about multiple variable `validation` blocks

- internal/getproviders/registry_client.go
- internal/registry/client.go
Prior to this patch the user could receive a message like this from `init`:
```
Error: Failed to install provider
Error while installing 1password/onepassword v1.1.2: could not query provider
registry for registry.terraform.io/1password/onepassword: failed to retrieve
authentication checksums for provider: the request failed after 2 attempts,
please try again later: 500
```
While the status code is helpful, it would be far more helpful if the user knew what URL/hostname returned that error.
I mistakenly thought this would come from the Registry API, but @bethanyr helpfully pointed out to me that the checksums are in fact pulled from GitHub.
The new (proposed) error message would therefore indicate this:
```
Error: Failed to install provider
Error while installing 1password/onepassword …
```
> internal/registry: Add URL to error message for clarity

- internal/command/format/diff.go
- internal/command/format/diff_test.go
Better handling of null and empty containers when rendering a diff of nested attribute object types.
Empty containers can be rendered as single attributes to avoid the need to differentiate between empty and null in the element handling. Null containers were not handled at all, because the old block formatting would never nee null values.
Fixes #29382
Fixes #29385
> Empty nested attribute handling in diffs

- internal/command/format/object_id.go
- internal/command/format/object_id_test.go
It's possible that an "identifying" attribute could have marks. Make sure we don't return sensitive values as identifying attributes, and unmark the entire value when converting to a string.
Fixes #29374
> unmark object ID or Name for formatting

- internal/command/format/diff.go
- internal/command/format/diff_test.go
The code adopted from block diffs was not set to handle null and unknown
values, as those are not allowed for blocks. While there is much room for
improvement in the formatting code, this PR takes care to only update the
new code paths for formatting so as to not disturb the rather fragile existing
block formatting code.
We also revert the change to formatting nested object types as single
attributes, because the attribute formatter cannot handle sensitive
values from the schema. This presents some awkward syntax for diffs for
now, but should suffice until the entire formatter can be refactored to
better handle these new nested types.
Fixes #29392
> handle null and unknown values in attr diffs

- website/docs/language/functions/cidrhost.html.md
The return value of the cidrhost() function in the documentation examples does not match the logic described by the description and the way it actually works, due to a typo. The first two examples have "10.12.127.0/20" as the input CIDR to get an IP from, but they should really be "10.12.112.0/20".
Thanks!
> Fixed cidrhost() example 1 and 2 with correct function parameter

- website/docs/language/functions/element.html.md
The element function page previously linked to the index page for all functions where it meant to link to the index function page.
> Fix link to index function

- go.mod
- go.sum
AWS SSO is used in many organizations to authenticate users for access to their AWS accounts. It's the same scale organizations that would very likely also use Terraform to manage their infrastructure. However, proper support for using this authentication scheme landed in the CLI and SDKs only over time, with features like interactive re-authentication (as may be needed when temporary credentials expire) still not universally supported. It's because of this that **many people**, including myself, will **configure their profiles** in their local AWS config **such that in addition to the SSO configuration, there is a** `credential_process`, which provides backwards compatibility for applications not supporting SSO as well as helps trigger an interactive re-auth as needed (such as …
> Bumping AWS GO SDK to 1.38.42 to fix AWS SSO auth woes

- internal/command/add.go
- internal/command/add_test.go
- internal/command/views/add.go
- internal/command/views/add_test.go
- website/docs/cli/commands/add.html.md
We're aware of several quirks of this command's current design, which result from some existing architectural limitations that we can't address immediately.
However, we do still want to make this command available in its current capacity as an incremental improvement, so as a compromise we'll document it as experimental. Our intent here is to explicitly exclude it from the [Terraform 1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) so that we can have the space to continue to improve the design as other parts of the overall Terraform system gain new capabilities.
We don't currently have any concrete plan for this command to be stabilized and subject to compatibility promises. That decision will follow from ongoing discussions with other …
> command: "terraform add" is experimental

- internal/addrs/module_call.go
- internal/addrs/move_endpoint_module.go
- internal/addrs/move_endpoint_module_test.go
- internal/refactoring/move_execute.go
- internal/refactoring/move_execute_test.go
- internal/refactoring/move_statement.go
Implement `MoveEndpointInModule.CanChainFrom` and `MoveEndpointInModule.NestedWithin` for use in `refactoring.ApplyMoves`, while fixing a few bugs hidden in the mostly unused code.
The move results will need some more refactoring, as well as the tests fixtures, but this allows the basic functionality to be verified.
> refactoring: CanChainFrom and NestedWithin

- go.mod
- go.sum
TencentCloud deleted all their v3 tags, so any system that does not use the global Go proxy will fail to find the github.com/tencentcloud/tencentcloud-sdk-go module source.
Update go.mod to point to the specific commit rather than the incompatible and missing version tag. Manually verified the source files are identical, so no acceptance testing is necessary for this PR.
This unblocks anyone having issues attempting to build/analyze the project, and a reasonable v1 tag can be updated later by the backend maintainer.
> cleanup tencentcloud missing tag

- internal/command/meta_backend_migrate.go
The `-force-copy` flag to init should automatically migrate state. Previously this was not applied to one case: when migrating from a backend with multiple workspaces to another backend supporting multiple workspaces. I believe this was an oversight so this commit fixes that.
Fixes #29239
> command: Suppress prompt for init -force-copy

- internal/addrs/move_endpoint_module.go
- internal/addrs/move_endpoint_module_test.go
- internal/refactoring/move_execute_test.go
Add the `anyKey` `InstanceKey` value to the addrs package to simplify module path comparison. This allows all combinations of module path representation to be normalized into a `ModuleInstance` which can be compared directly, rather than dealing with multiple levels of different prefix types.
The new `anyKey` value and `anyKeyImpl` type are not exported, and only used within the package for comparing combinations of configuration, relative and absolute instance addresses. This value and type should not be used outside of the `addrs` package, and does not show up as an `InstanceKeyType`.
We can use this new type to reimplement `CanChainFrom` and `NestedWithin` using the new `ModuleInstance` path representation, simplifying the code significantly.
> refactoring: complete CanChainFrom and NestedWithin

- website/docs/language/functions/urlencode.html.md
Found typo in the examples of `urlencode`. This behavior is originated from the Go's function `url.QueryEscape`.
Confirmed by executing `echo '"http://example.com/search?q=${urlencode("terraform urlencode")}"' | terraform console` in the latest version.
> Fix a result in examples for urlencode.html.md

- website/docs/language/functions/jsonencode.html.md
The use of `jsonencode` to minify JSON values is useful, so note that in the docs explicitly. A data source or resource may produce a JSON string as an attribute that is not minified, and if needs to be used elsewhere minified, an expression like `jsonencode(jsondecode(data.some_data_source.json))` will do this.
> note that output of jsonencode is minified

- website/docs/language/functions/jsonencode.html.md
Update to the language agreed upon by technical writing. Specifically: Avoid starting sentences with a code construct. Instead, use "The X command....". This allows us to keep active voice and avoids awkward sentence construction.
> Update jsonencode minified note

- website/docs/language/functions/setsubtract.html.md
The explanation of the setsubtract function confuses the first and second sets when using the term "Relative Complement".  Fixing it.
> setsubtract doc: use "Relative Complement" correctly

- website/docs/language/functions/element.html.md
The link from the docs page for function `element` -> function `index` was linking to index.html, but this is the docs homepage.
It now links to index_function.html, the documentation for the related index function.
> docs: fix link to index

- website/docs/language/settings/backends/s3.html.md
There's a small gotcha in the S3 Backend docs that I just ran into, that's quite hard to debug: When using KMS encryption on S3 State Storage, terraform will output a `PermissionDenied` error if they don't have `kms:Encrypt`, `kms:Decrypt` and `kms:GenerateDataKey` permissions on the KMS key used to encrypt the state: 
```
╷
│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: AccessDenied: Access Denied
│ 	status code: 403, request id: <REDACTED>, host id: <REDACTED>
╵
╷
│ Error: Failed to persist state to backend
│ 
│ The error shown above has prevented Terraform from writing the updated state to the configured backend. To allow for recovery, the state has been written to the file "errored.tfstate" in the current working
│ directory.
│ 
│ Running "terraform …
```
> Add a note to the docs on the S3 backend around permissions needed for encrypted state storage

- website/docs/language/expressions/for.html.md
In the last paragraph, the word "generated" is in the wrong tense for the sentence. The correct word is "generate" (unless I misunderstand the sentence 🙂).
> generated -> generate

- website/docs/language/functions/tobool.html.md
- website/docs/language/functions/tonumber.html.md
- website/docs/language/functions/tostring.html.md
Noticed this while using `tobool`, it seems to apply to `tonumber` and `tostring` as well, confirmed in console in 0.14, but didn't try any other versions.
```shell
$ terraform console
> tonumber(null)
null
> tostring(null)
null
> tobool(null)
null
> exit
$ terraform version
Terraform v0.14.7
```
> Add null to type conversion docs

- .gitignore
The main purpose of this change is to avoid a problem where new golden files added to certain directories for test purposes (like .log) shouldn't be ignored.
Cleaning up a bit more and broadening the definition, this removes ignore rules for artifacts of Terraform itself (state files, plans). It's generally not recommended to be using this codebase as your Terraform working directory anyway; build here, test elsewhere.
> Clean up ignored files

- website/docs/language/meta-arguments/lifecycle.html.md
- website/docs/language/resources/provisioners/syntax.html.md
Documents issue https://github.com/hashicorp/terraform/issues/13549
Ran in this today again after first running into it a year ago and forgetting about it...
I think it's better to document this so people don't try to use this and then just end up disappointed because it doesn't work.
> document that destroy provisioners don't run with create_before_destroy

- website/docs/language/modules/sources.html.md
explicitly state that commit shas can be passed to module `ref=`
> documentation: commit sha can be passed to ref
