hashicorp/terraform

internal/configs/experiments.go
This package level variable can be overridden at link time to allow temporarily disabling the UI warning when experimental features are enabled. This makes it easier to understand how UI will render when the feature is no longer experimental.
This change is only for those developing Terraform.
=> configs: Disable experiment warnings at link time

internal/command/jsonconfig/expression.go, internal/command/jsonconfig/expression_test.go
In order to marshal config blocks using ConfigModeAttr, we need to insert the fixup body to map hcl blocks to the attribute in the schema.
Serializing the configuration of `dynamic` blocks is something that will need to be handled separately, if at all, as they require more context than is available at the time of serialization.
Fixes #29022
=> allow json output to marshal ConfigModeAttr blocks

internal/command/format/diff.go, internal/command/format/diff_test.go, internal/command/views/plan.go, internal/command/views/plan_test.go, internal/plans/changes.go, internal/plans/changes_src.go, internal/plans/changes_test.go
For resources which are planned to move, render the previous run address as additional information in the plan UI. For the case of a move-only resource (which otherwise is unchanged), we also render that as a planned change, but without any corresponding action symbol.
If all changes in the plan are moves without changes, the plan is no longer considered "empty". In this case, we skip rendering the action symbols in the UI.
Plan consisting of one move, without changes:
Adding another move, this time with changes which cause the resource to be replaced:
=> command: Render "moved" annotations in plan UI

website/docs/language/state/remote-state-data.html.md
Update the terraform_remote_state data source docs to include usage of the new `tfe_outputs` [data source in the tfe-provider](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/outputs). Also added a specific section for Terraform Cloud.
=> Update terraform_remote_state data source docs:

docs/plugin-protocol/releasing-new-version.md
Releasing a new major protocol version requires coordination between a
few different projects and codebases, and it's easy to forget a step.
This commit introduces a doc to keep track of these steps, making it
less likely one will be omitted or forgotten.
=> Add docs on how to release a new major protocol version.

website/docs/language/settings/backends/azurerm.html.md
Without `resource_group_name` I had
> │ Error: Either an Access Key / SAS Token or the Resource Group for the Storage Account must be specified - or Azure AD Authentication must be enabled
=> Added required paramter `resource_group_name` for MSI

website/docs/language/resources/provisioners/remote-exec.html.md
This is a secondary change to PR #28578 
Details:
According to the [Provisioner Connection](https://www.terraform.io/docs/language/resources/provisioners/connection.html) page, provisioners require the connection block.
This change of behavior is shown prominently within a note on the [Provisioner Connection](https://www.terraform.io/docs/language/resources/provisioners/connection.html) page:
> Note: In Terraform 0.11 and earlier, providers could set default values for some connection settings, so that connection blocks could sometimes be omitted. This feature was removed in 0.12 in order to make Terraform's behavior more predictable.
However, this behavioral change is omitted from the [remote-exec provisioner](https://www.terraform.io/docs/language/resources/provisioners/remote-exec.html) …
=> Added clarity: remote-exec connection requirement

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
The config is already validated, and does not need to be checked again in AssertPlanValid, so we can just remove the check which conflicts with the new optional nested attribute types.
Add some more coverage for plan validation.
Fixes #29561
=> remove incorrect computed check

internal/backend/unparsed_value_test.go, internal/configs/configschema/decoder_spec.go, internal/configs/configschema/implied_type.go, internal/configs/configschema/implied_type_test.go, internal/configs/experiments.go, internal/configs/module_merge.go, internal/configs/module_merge_test.go, internal/configs/named_values.go, internal/plans/objchange/objchange_test.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/node_module_variable.go, internal/terraform/node_module_variable_test.go, internal/terraform/node_root_variable_test.go, internal/terraform/variables.go
The use of the `ObjectWithOptionalAttrs` type should not escape into the type general population. It is only used for the decoding of configuration, and conversions between object values, and otherwise should never be seen in any value or type that could be used to instantiate a value.
Separate the external `ImpliedType` methods from the `cty.Type` generated internally for the decoder spec in configschema. Along with preventing optional attrs from escaping via `ImpliedType`, this separation allows the decoding codepaths to continue running without the overhead of `WithoutOptionalAttributesDeep`, which is verified by the benchmarks for extremely large schemas
This unfortunately does cause our `ImpliedType` method to possibly return a different type than the `hcldec.ImpliedType` function, …
=> Prevent `ObjectWithOptionalAttrs` from escaping

website/docs/language/settings/backends/s3.html.md
**Note:** this replaces https://github.com/hashicorp/terraform/pull/28561 - had deleted the fork/branch and was easier to onc again re-create.
Very minor update to the S3 backend documentation.
Refers to a DynamoDB "primary key" - when it should be "partition key".
=> S3 backend documentation update - DynamoDB uses Partition keys, not primary keys - redux

internal/backend/local/backend_local_test.go, internal/backend/local/backend_plan_test.go, internal/backend/local/testing.go, internal/command/command_test.go, internal/command/get_test.go, internal/command/meta_backend_test.go
Use `EvalSymlinks` with temp dir paths to help with MacOS errors from various terraform components. Same fixes as used in other PRs like #27005 and #23596. Update impacted test fixtures to use `t.TempDir` for more consistent handling.
This is not a comprehensive cleanup, just enough to get tests working again on darwin.
=> fix temp directory handling in some tests

internal/backend/backend.go, internal/backend/local/backend_plan_test.go, internal/backend/remote/backend_apply.go, internal/backend/remote/backend_apply_test.go, internal/backend/remote/backend_plan.go, internal/backend/remote/backend_plan_test.go, internal/command/meta_backend.go
The original intent of this test was to verify that we properly release the state lock if `terraform.NewContext` fails. This was in response to a bug in an earlier version of Terraform where that wasn't always true. (see #25454)
In the recent refactoring that made terraform.NewContext no longer responsible for provider constraint/checksum verification, this test began testing a failed plan operation instead, which left the error return path from `terraform.NewContext` untested.
An invalid parallelism value is the one remaining case where `terraform.NewContext` can return an error, so as a localized fix for this test I've switched it to just intentionally set an invalid parallelism value. This is still not ideal because it's still testing an
implementation detail, but I've at least left a …
=> backend/local: Restore original intent of TestLocal_plan_context_error test case

internal/configs/configschema/coerce_value.go, internal/configs/configschema/coerce_value_test.go, internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
Empty containers of NestedTypes were not handled in ProposedNew, causing plans to be submitted with null values where there was configuration present.
Fixes #29576
=> handle empty containers in ProposedNew NestedTypes

internal/configs/configschema/coerce_value.go, internal/configs/configschema/coerce_value_test.go
The CoerceValue code was not updated to handle NestedTypes, and while none of the newer codepaths make use of this method, there are still some internal uses.
Here we continue to leverage the go-cty `Convert` function to transform the attribute values, but instead read the attribute type from the `configschema.Block` spec type rather than recursing into the `NestedType` values.
=> handle NestedTypes in configschema CoerceValue

internal/refactoring/move_validate_test.go
When originally filling out these test cases we didn't yet have the logic in place to detect chained moves and so this test couldn't succeed in spite of being correct.
We now have chain-detection implemented and so consequently we can also detect cyclic chains. This commit largely just enables the original test unchanged, although it does include the text of the final error message for reporting cyclic move chains which wasn't yet finalized when we were stubbing out this test case originally.
=> refactoring: TestValidateMoves/cyclic_chain can now pass

website/docs/internals/machine-readable-ui.html.md, website/layouts/docs.erb
This PR adds the Machine-Readable UI page to the documentation sidebar, adds a hyphen (because machine-readable is modifying UI in this case, so it gets a hyphen), and reorganizes the internals sidebar so that topics appear in alphabetical order. 
I have:
=> Add Machine-Readable UI to sidebar

internal/command/add.go, internal/command/add_test.go, internal/command/views/add.go
This PR fixes #29220 about `terraform add` command used with `-out` option:
1. As the help message of this command indicated, the `-out` should append to the existing file. While current implementation truncated it. In reallity, since users are likely to repeatedly call the `terraform add` on different resources, and output to the same file. So this PR changes the implementation to make it align with indicated as the help message.
2. When users didn't specify `-out`, or the `-out` directs to some non-module-like directory, the in-module check on the target resource should be skipped.
=> `terraform add`: `-out` option append to existing config & optionally check resource existance

internal/command/views/operation_test.go, internal/command/views/plan.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
This PR fixes some edge cases with plans which include unexecuted config-driven moves on resources which are otherwise unchanged.
- Add move-only changes to the set of "drifted" resources in a plan. This allows us to show pending moves in refresh-only plans, which then more completely represents what will happen if they are applied.
- Correspondingly, ensure that for normal plans we do not double-render move-only changes
This PR is based on #29589, to be merged after it.
Refresh-only plan with a single unexecuted move operation:
Normal plan with the same situation:
Refresh-only plan including unexecuted move operation and detected drift:
Normal plan with the same situation:
=> cli: Improved plan UI for move-only changes

internal/command/jsonplan/plan.go, internal/command/jsonplan/resource.go, internal/command/testdata/show-json/moved-drift/main.tf, internal/command/testdata/show-json/moved-drift/output.json, internal/command/testdata/show-json/moved-drift/terraform.tfstate, internal/command/testdata/show-json/moved/main.tf, internal/command/testdata/show-json/moved/output.json, internal/command/testdata/show-json/moved/terraform.tfstate, internal/command/testdata/show-json/multi-resource-update/output.json, internal/command/views/json/change.go, internal/command/views/json_view_test.go, internal/command/views/operation.go, internal/command/views/operation_test.go, website/docs/internals/json-format.html.md, website/docs/internals/machine-readable-ui.html.md
Two commits:
Configuration-driven moves are represented in the plan file by setting the resource's `PrevRunAddr` to a different value than its `Addr`. For JSON plan output, we here add a new field to resource changes, `previous_address`, which is present and non-empty only if the resource is planned to be moved.
Like the CLI UI, refresh-only plans will include move-only changes in the resource drift JSON output. In normal plan mode, these are elided to avoid redundancy with planned changes.
Add previous address information to the `planned_change` and `resource_drift` messages for the streaming JSON UI output of plan and apply operations.
Here we also add a "move" action value to the `change` object of these messages, to represent a move-only operation.
As part of this work we also …
=> json-output: Add support for config-driven move to plan JSON and streaming JSON UI

internal/command/command_test.go, internal/command/init_test.go, internal/command/ui_input.go
Remove answers from testInputResponse as they are given, and raise an error during cleanup if any answers remain unused.
This enables tests to ensure that the expected mock answers are actually used in a test; previously, an entire branch of code including an input sequence could be omitted and the test(s) would not fail.
The only test that had unused answers in this map is one leftover from legacy state migrations; this particular prompt was removed in 7c93b2e5e637bdee37c5e505d13121d9bfee223d
=> command: Ensure all answers were used in command.testInputResponseMap

internal/addrs/resource.go, internal/addrs/resource_test.go, internal/refactoring/move_execute.go, internal/refactoring/move_execute_test.go, internal/refactoring/move_validate_test.go, internal/terraform/context_plan.go, internal/terraform/context_walk.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/graph_walk_context.go, internal/terraform/node_resource_abstract_instance.go
When we originally stubbed `ApplyMoves` we didn't know yet how exactly we'd be using the result, so we made it a double-indexed map allowing looking up moves in both directions.
However, in practice we only actually need to look up old addresses by new addresses, and so this commit first removes the double indexing so that each move is only represented by one element in the map.
We also need to describe situations where a move was blocked, because in a future commit we'll generate some warnings in those cases. Therefore `ApplyMoves` now returns a `MoveResults` object which contains both a map of changes and a map of blocks. The map of blocks isn't used yet as of this commit, but we'll use it in a later commit to produce warnings within the "terraform" package.
---
While working on this, I …
=> refactoring: ApplyMoves new return type and more accurate results

internal/terraform/context_plan2_test.go, internal/terraform/node_resource_plan.go
When planning in refresh-only mode, we must not remove orphaned resources due to changed `count` or `for_each` values from the planned state. This was previously happening because we failed to pass through the plan's skip-plan-changes flag to the instance orphan node.
This bug is present in the 1.0 series, and while not reported by anyone else as far as I can tell, it seems reasonable to me to backport it.
Fixes #29638
=> core: Fix refresh-only interaction with orphans

internal/backend/local/backend_apply_test.go, internal/backend/local/backend_local_test.go, internal/backend/local/backend_plan_test.go, internal/backend/local/backend_refresh_test.go, internal/backend/local/testing.go
Clean up some temp directory handling in tests. No functional changes here, only saving the commit from a PR which went unused.
=> temp path clean for some backend tests

internal/command/views/json/change.go, internal/command/views/json/hook.go, website/docs/internals/machine-readable-ui.html.md
The extra feedback information for why resource instance deletion is planned is now included in the streaming JSON UI output.
We also add an explicit case for no-op actions to switch statements in this package to ensure exhaustiveness, for future linting.
=> json-output: Add change reasons to explain deletes

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
Our current implementation of destroy planning includes secretly running a normal plan first, in order to get its effect of refreshing the state.
Previously our warning about colliding moves would betray that implementation detail because we'd return it from both of our planning operations here and thus show the message twice. That would also have happened in theory for any other warnings emitted by both plan operations, but it's the move collision warning that made it immediately visible.
We'll now only return warnings from the initial plan if we're also returning errors from that plan, and thus the warnings of both plans can never mix together into the same `diags` and thus we'll avoid duplicating any warnings.
This does mean that we'd lose any warnings which might hypothetically emerge …
=> core: Emit only one warning for move collisions in destroy-plan mode

internal/command/init.go, internal/command/init_test.go, internal/command/show_test.go, internal/command/testdata/init-check-required-version-first-module/main.tf, internal/command/testdata/init-check-required-version-first-module/mod/main.tf, internal/command/testdata/init-check-required-version-first/main.tf, internal/configs/configload/loader_load.go, internal/configs/configload/loader_load_test.go
Our current check of `required_version` happens after parsing the configuration, which may not be possible if new configuration constructs have been added to the language since the declared `required_version`. This can cause terraform to print rather unhelpful error messages about unknown identifiers in various modules, when the only pertinent information is that the CLI version is not compatible.
Restructure the init command to ensure that we check the core version constraints before handling any parsing diagnostics. We can remove the extra loading of the configuration, which is redundant when the config loader can return the same value along with its diagnostics.
Closes #29109
=> Check required_version as early as possible

internal/command/cliconfig/credentials.go
`helperType` is not set at the time of this log message and therefore the log will print.
```
[ERROR] Unable to find credentials helper ""; ignoring
```
=> Fix Credentials Helper error message

.circleci/config.yml, Makefile, go.mod, go.sum, scripts/exhaustive.sh, tools/tools.go
For now, only check the JSON views package, since this was the instance that most recently tripped us up. There are a few dozen failures elsewhere in Terraform which would need to be addressed before expanding this to other packages.
=> build: Add exhaustive switch statement lint

internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/testdata/provider-tampering-base/provider-tampering-base.tf, internal/command/meta.go, internal/command/meta_backend.go, internal/command/meta_providers.go
In the original incarnation of `Meta.providerFactories` we were returning into a `Meta.contextOpts` whose signature didn't allow it to return an error directly, and so we had compromised by making the provider factory functions themselves return errors once called.
Subsequent work made `Meta.contextOpts` need to return an error anyway, but at the time we neglected to update our handling of the `providerFactories` result, having it still defer the error handling until we finally instantiate a provider.
Although that did ultimately return these error messages anyway, the error ended up being reported from deep in the guts of a Terraform Core graph walk, in whichever concurrently-visited graph node happened to try to instantiate the plugin first. This meant that the exact phrasing of the …
=> command: Early error message for missing cache entries of locked providers

README.md
A change to an image path on the terraform website inadvertently caused the hotlinked logo image from the readme to break - this replaces it with a functional and more stable image path!
=> Fix broken logo in readme

internal/command/meta_backend.go, internal/command/meta_backend_migrate.go
This PR changes the variable naming in the backend state migration to be clearer to what it is doing. Variables that reference "One" now are "Source" and variables that reference "Two" are now "Destination".
=> Backend State Migration: Variable name change

.github/ISSUE_TEMPLATE/bug_report.md
Terraform is no longer going to silently capture all logs for a possible
crash report, and therefor won't create a crash.log file when a panic is
encountered.
The prompt to create a log file with TF_LOG from the Debug Output
section should suffice to get users to submit the logs when possible. In
the case of a crash specifically, the crash output also requests that
the stack trace be added to the issue for users who may not be aware of
what is necessary.
=> remove Crash section of issue template

internal/command/apply.go, internal/command/meta_backend.go
When using the Terraform Cloud integration - like the 'remote' backend - the resource count output should be suppressed if those counts are already being rendered remotely. This generalizes this to the shared interface, so the following duplicated output doesn't happen:
=> command: Adjust skipping of resource counts for any remote implementation

internal/cloud/backend.go, internal/cloud/backend_test.go
When a remote workspace specifies an exact version constraint against a prerelease version, we need to skip the looser version constraint checks. This is because a prerelease version cannot satisfy a constraint which uses any operator other than `=`.
Also modify the diagnostics to include the constraint which is not met, rather than the specific version. This ensures that if our logic expands the workspace's given constraint, we are clear that it is this that fails.
=> cloud: Fix prerelease version constraint checks

internal/command/testdata/show-json/moved-drift/main.tf, internal/command/testdata/show-json/moved/main.tf, internal/configs/experiments.go, internal/configs/testdata/invalid-modules/config-driven-move-experiment/config-driven-move-experiment.tf, internal/configs/testdata/valid-modules/moved-blocks/moved-blocks-1.tf, internal/experiments/experiment.go, internal/refactoring/move_statement_test.go, internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf, internal/terraform/context_plan2_test.go
Based on feedback during earlier alpha releases, we've decided to move forward with the current design for the first phase of config-driven refactoring.
Therefore here we've marked the experiment as concluded with no changes to the most recent incarnation of the functionality. The other changes here are all just updating test fixtures to no longer declare that they are using experimental features.
Shortly after we land this I also intend to merge the docs over in #29126, and so between those two PRs we should be in a code-complete state for this feature, ready for inclusion in a release.
=> experiments: config_driven_move has concluded

website/docs/language/modules/develop/index.html.md, website/docs/language/modules/develop/refactoring.html.md, website/docs/language/modules/syntax.html.md, website/layouts/language.erb
This is an early iteration of documentation about the refactoring features we're intending to introduce in a forthcoming release.
I've named the documentation section "refactoring" because in previous discussions with users that seems to be the term they use to describe the underlying need. `moved` blocks are our first language feature intended to meet that need, although it probably won't be the last as we consider other requirements in later releases. My intent here is that once we've published this it should eventually end up being the first result for a web search for the topic of Terraform refactoring.
=> website: First draft of "Refactoring" documentation, about "moved" blocks

internal/cloud/e2e/init_with_empty_tags_test.go, internal/command/meta_backend.go
Previously, `terraform init` was throwing an error if you configured the cloud
block with `tags` and there weren't any tagged workspaces yet. Confusing and
alienating, since that that's a fairly normal situation! Basically TFC was
handling an empty list of workspaces worse than other backends, because it
doesn't support an unnamed default workspace.
This commit catches that condition during `Meta.selectBackend()` and asks the
user to pick a name for their first tagged workspace. If they cancel out, we
still error, but if we know what name they want, we can handle it the same way
as a nonexistent workspace specified in `name` -- just pass it to
`Meta.SetWorkspace()`, and let the workspace get implicitly created when
`InitCommand.Run()` eventually calls `StateMgr()`.
=> Cloud: Init without erroring when no workspaces match the `tags`

website/docs/language/expressions/types.html.md, website/docs/language/values/variables.html.md
- Add `nullable` to the variable documentation.
- Remove "module" from the "null means omission" part of the null type documentation.
=> nullable variable docs

internal/backend/remote-state/oss/backend.go, website/docs/language/settings/backends/oss.html.md
This PR aims to add new attribute `sts_endpoint` to support setting custom Security Token Service endpoint.
=> backend/oss: Supports the new attribute sts_endpoint

internal/cloud/e2e/apply_auto_approve_test.go, internal/cloud/e2e/backend_apply_before_init_test.go, internal/cloud/e2e/init_with_empty_tags_test.go, internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go, internal/cloud/e2e/migrate_state_single_to_tfc_test.go, internal/cloud/e2e/migrate_state_tfc_to_other_test.go, internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go, internal/cloud/e2e/run_variables_test.go
Add the `-parallel N` switch to tell the tests to run in N processes:
```
TFE_TOKEN=$TFE_TOKEN TFE_HOSTNAME=$TFE_HOSTNAME TF_ACC=1 go test -v \
-tags=e2e ./internal/cloud/e2e/... -parallel 4
```
=> cloud: Allow cloud tests to be run in parallel

internal/configs/configschema/validate_traversal.go, internal/configs/module_merge.go, internal/configs/module_merge_test.go, internal/configs/testdata/valid-modules/override-ignore-changes/main.tf, internal/configs/testdata/valid-modules/override-ignore-changes/main_override.tf
Fixes https://github.com/hashicorp/terraform/issues/21474, in which `ignore_changes = all` does not survive a module merge.
=> configs: fix ignore_changes config override bug

internal/command/format/diff.go, internal/command/format/diff_test.go
This change contains two commits, the first addressing a bug and the second improving general rendering in the same area. I'm submitting them together, but would be happy to split them up or only submit the bug fix.
Diffs only rendered correctly if all changed elements appeared before all unchanged elements. Once an unchanged element was found, all remaining elements were skipped. This usually led to the output being an empty list with a weird amount of space between the brackets.
**Before:**
```
~ resource "nested_fields" "example" {
name   = "example"
~ values = [
~ {          },
]
}
```
**After:**
```
~ resource "nested_fields" "example" {
name   = "example"
~ values = [
~ {
name  = "b"
~ value = "2" -> "3"
},
]
}
```
I made several changes to make list diffs clearer and more …
=> command/format: improve list nested attribute rendering

internal/command/init_test.go, internal/command/meta_backend.go, internal/command/testdata/init-backend-config-file-change-migrate-existing/.terraform/terraform.tfstate, internal/command/testdata/init-backend-config-file-change-migrate-existing/input.config, internal/command/testdata/init-backend-config-file-change-migrate-existing/local-state.tfstate, internal/command/testdata/init-backend-config-file-change-migrate-existing/main.tf
Replaces #29856
Closes #26259
Closes #26260
The `Meta.backend_C_r_S_unchanged()` method was sadly pulling too many duties.
It seems to have originally been used as a method to be called when the backend is not changing, with an extra assumption that if the configured backend's hash doesn't match the one in state, surely the hash should just be updated as an option might have been moved to command line flags.
However, this function was used throughout this file as 'the method to load the initialized (but not necessarily configured) backend', regardless of whether or not it is the same (unchanged). This is in addition to `Meta.backendFromState()`, which is used to load the same thing except in the main codepath of 'init -backend=false'.
These changes separate the concerns of …
=> command: Update backend hash value only after a successful migration

internal/cloud/backend.go, internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/cloud/tfe_client_mock.go
Currently, when using the Tags strategy for the `cloud` integration, a workspace passed to the `StateMgr` doesn't handle new tags. This is evident during a migration, where new workspaces are created or existing ones retrieved. The workspaces in question should have the tags declared in the configuration. This change enables that.
=> Cloud: Update Workspace during Tags strategy

go.mod, go.sum
cty: The documented definition and comparison logic of cty.Number is now
refined to acknowledge that its true range is limited only to values
that have both a binary floating point and decimal representation,
because cty values are primarily designed to traverse JSON serialization
where numbers are always defined as decimal strings.
In particular, that means that two cty.Number values now always compare
as equal if their representation in JSON (under cty's own JSON encoder)
would be equal, even though the decimal approximation we use for that
conversion is slightly lossy. This pragmatic compromise avoids confusing
situations where a round-trip through JSON serialization (or other
serializations that use the same number format) may produce a value that
doesn't compare equal to the …
=> update go-cty to v1.10.0

internal/terraform/context_plan_test.go, internal/terraform/evaluate.go, internal/terraform/testdata/plan-self-ref-multi-all/main.tf
Allow `GetResource` to return correctly typed values during validation, rather than relying on `cty.DynamicVal` as a placeholder. This allows other dependent expressions to be more correctly evaluated.
There is no reason we must use the stored state to find the provider address for evaluation. We don't need the exact provider instance here, since we are only looking for the schema and the schema lookup is done with a simple provider type.
Once we have the resource type, we can return correctly shaped unknown values for validation based on the expansion mode of the resource configuration.
Fixes the specific case shown in #29809
=> generate precise resource types during validate

internal/backend/remote-state/oss/backend.go, website/docs/language/settings/backends/oss.html.md
This PR is the improvement of the PR #29307 aims to fix the useless conflict error. This PR will try to get new attribute assume_role_* value at first, if the value is not set, then to check whether is setting `assume_role` block. If both of them have been set, `assume_role` will be ingored.
=> backend/oss: Removes the ConflictWith tag which on the attributes assume_role* to fix the incompatible error

internal/command/meta_backend_migrate.go
Among a few copy changes for clarity, this changes the multi-to-multi workspace migration UX for Terraform Cloud to automatically select the newly-migrated current workspace on behalf of the user rather than force them to reselect the workspace they were already on. For awareness of how the migration changed their workspaces, as well as to signal how the current selected workspace's name changed, we also provide output at the end of the migration to display what the workspaces now look like.
**Before:**
**After:**
---
Note that these changes do break the E2E tests (`internal/cloud/e2e`), but those tests are in a bit of a state right now for other reasons and we don't want them to hold this change up. We'll address those separately.
=> cloud: Autoselect migrated current workspace + migrate UX adjustments

internal/backend/remote/backend.go, internal/command/meta_backend.go, internal/command/meta_backend_migrate.go
For Terraform Cloud users using the `remote` backend, the existing 'pattern' prompt should work just fine - but because their workspaces are already present in TFC, the 'migration' here is really just realigning their local workspaces with Terraform Cloud. Instead of forcing users to do the mental gymnastics of what it means to migrate from 'prefix' - and because their remote workspaces probably already exist and already conform to Terraform Cloud's naming concerns - streamline the process for them and calculate the necessary pattern to migrate as-is, without any user intervention necessary.
Given the previous remote backend configuration:
```hcl
terraform {
backend "remote" {
organization = "foo"
workspaces {
prefix = "lol-"
}
}
}
```
To a new `cloud` configuration:
```hcl
terraform { …
```
=> cloud: Add streamlined 'remote' backend state migration path

main.go, version/dependencies.go
We have a few dependencies that are such a significant part of Terraform's behavior that they will often be the root cause of or the solution to a bug reported against Terraform.
As a small quality-of-life improvement to help with diagnosing those, we'll now report the selected versions for each of these so-called "interesting" dependencies as part of our initial trace log output during Terraform startup.
The goal here is that when someone opens a bug report, and includes the trace log as our bug report template requests, we'll be able to see at a glance which versions of these dependencies were involved, instead of having to manually cross-reference in the go.mod file of the reported main Terraform CLI version.
This does slightly grow the general overhead of the logs, but as long as we …
=> main: Report version information for "interesting" dependencies

internal/cloud/backend.go, internal/cloud/backend_apply_test.go, internal/cloud/backend_test.go, internal/cloud/tfe_client_mock.go
The cloud package currently uses a deprecated API on workspaces to determine a workspace's execution mode. 
Deprecated:  Operations (boolean)
New hotness: Execution mode (string - "local", "remote", or "agent")
More details: https://www.terraform.io/docs/cloud/api/workspaces.html#request-body
All uses of Operations field coming from the client (within the cloud package) should be converted to the appropriate ExecutionMode equivalent.
Also, we need to update all acknowledgment of operations field on the tests that are testing the behavior of workspaces.
The usage of operations within `entilements` context is not being replaced because `type` entitlements does not have an ExecutionMode field.
Lastly, the usage of `Operations: *options.Operations` within `internal/cloud/tfe_client_mock.go` …
=> cloud: convert uses of worspaces.operations into workspaces.executionMode

internal/command/state_mv.go, internal/command/state_mv_test.go, internal/command/testdata/init-backend-http/main.tf, website/docs/cli/commands/state/mv.html.md
While [the documentation for the `state mv` command says](https://www.terraform.io/docs/cli/commands/state/mv.html#usage) that `-state`, `-state-out`, `-backup`, and `-backup-out` are only supported on the local backend, Terraform will accept these options and ignore the backup options silently when used with a non-local backend. This can put users into a state where they think they have backed up their state when modifying it but they actually haven't. This PR changes the `state mv` command to error when the `-backup` or `-backup-out` options are used without the `-state` option on non-local backends. 
Closes #27908
There were a few different options I explored while trying to figure out what behavior made the most sense here:
1. Don't allow the use of the options `-state`, `-state-out`, …
=> Command state mv: Error when backup or backup-out options are used without the state option on non-local backends

go.mod, go.sum, internal/command/command_test.go, internal/command/get.go, internal/command/get_test.go, internal/command/init.go, internal/command/init_test.go, internal/command/meta_config.go, internal/command/test.go, internal/command/testdata/init-registry-module/main.tf, internal/getmodules/getter.go, internal/getmodules/installer.go, internal/initwd/from_module.go, internal/initwd/from_module_test.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testing.go, internal/refactoring/move_validate_test.go, internal/registry/client.go, internal/registry/client_test.go, internal/terraform/terraform_test.go
This gets us a bit further towards https://github.com/hashicorp/terraform/issues/23647.
https://github.com/hashicorp/terraform/pull/26405 made the `getproviders` package context-aware in order to allow provider installation to be cancelled.
Here we make a similar change for module installation, which is now also cancellable with SIGINT. This involves plumbing context through `initwd` and `getmodules`. Functions which can make network requests now include a context parameter whose cancellation cancels those requests.
Since the module installation code is shared, this has the welcome side effect of making "terraform get" also interruptible during module installation.
This PR also bumps go-getter from v1.5.2 to v1.5.9 to include a v1.5.4 change that makes HTTP requests cancellable …
=> command: make module installation interruptible

go.mod, go.sum, internal/cloud/backend_apply_test.go
The current version of main branch for `go-tfe` has go mocks placed in a different directory:
https://github.com/hashicorp/go-tfe/pull/280
Terraform is using some of those mocks in `terraform/internal/cloud/backend_apply_test.go`
To avoid this kind of errors:
```
terraform/internal/cloud/backend_apply_test.go:579:15: undefined: tfe.NewMockApplies
terraform/internal/cloud/backend_apply_test.go:781:15: undefined: tfe.NewMockApplies
terraform/internal/cloud/backend_apply_test.go:1272:21: undefined: tfe.NewMockPolicyChecks
```
We need this test file to import the mocks from its new path.
At this point, this PR is failing due to a different compile error not address in this PR:
`terraform/internal/cloud/backend_plan.go:238: undefined: tfe.RunVariable`
This is because this type `RunVariable` …
=> Pull changes made to mocks in go-tfe

internal/cloud/backend_plan_test.go, internal/cloud/cloud_variables.go, internal/cloud/cloud_variables_test.go
All run variables remain encoded as strings in the TFC/E API requests but will now be expressed as an HCL string to be evaluated by the remote terraform. Previously, only string variables were supported but now you can express all types of cloud run variable values when using -var-file
Examples:
string: \`"quoted literal"\` (strings must be quoted)
map:  \`{ foo = "bar" }\`
list: \`["foo", "bar"]\`
bool: \`true\`
null: \`null\`
number: \`0.0001\`
This requires the API to anticipate that all run variables be HCL values.
=> fix(run variables): support all variable types (map, list, bool, number, null, string)

internal/terraform/node_resource_abstract_instance.go, internal/terraform/reduce_plan_test.go
When processing nested data structures for `ignore_changes`, a null map was sometimes converted to an empty map. 
When processing individual changes within a map, those changes could be lost when re-applying any marks set on the outer map.
Fixes #29921
=> `ignore_changes` converting null maps to empty maps, and applying marks.

go.mod, go.sum, internal/cloud/e2e/README.md, internal/cloud/e2e/apply_auto_approve_test.go, internal/cloud/e2e/backend_apply_before_init_test.go, internal/cloud/e2e/helper_test.go, internal/cloud/e2e/init_with_empty_tags_test.go, internal/cloud/e2e/main_test.go, internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go, internal/cloud/e2e/migrate_state_single_to_tfc_test.go, internal/cloud/e2e/migrate_state_tfc_to_other_test.go, internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go, internal/cloud/e2e/run_variables_test.go
This fixes the Cloud e2e tests.
**Changes**
* Run table tests as subtests (in parallel)
* Fix broken tests
* Remove `TF_LOG=INFO` in test cases
* Add a readme to show you to run tests.
* Add new `-tfoutput` flag to print the terraform to standard output.
* Change expect to not log to STDOUT
* Some commands were changed to use `-auto-approve` because it wasn't necessary for extra input steps.
_Note:_ I've removed some `t.Parallel()` bits because it started introducing some flakiness. I didn't do a full investigation because of time considerations. We will investigate this at a later point.
```
terraform % TF_ACC=1 go test ./internal/cloud/e2e/... -v -ldflags "-X \"github.com/hashicorp/terraform/version.Prerelease=alpha20211029\"" 
...
...
PASS
ok …
```
=> Cloud: Make e2e Tests Less Chatty, and More Stable

internal/lang/funcs/crypto.go, internal/lang/funcs/filesystem.go
Files opened by the filesha256 function were not being closed,
leaking file descriptors. Close files that were opened when the
function exist.
Even though I'm fairly certain that this is a fix, I'm asking for your review and opinion on this as I'm not that familiar with the codebase.
=> funcs: defer close file in filesha256

internal/addrs/move_endpoint.go, internal/addrs/move_endpoint_module.go, internal/addrs/move_endpoint_test.go, internal/addrs/moveable.go, internal/addrs/resource.go, internal/configs/moved_test.go, internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go, internal/refactoring/testdata/move-validate-zoo/move-validate-root.tf
Closes #29896
A move statement is invalid if the types of its resource(s) and resource instance(s) do not match.
The meat here is in the last three commits. The last commit introduces an `AbsMoveableResource` interface to make the code a bit tidier, but is optional. 
As described in the comments, we rely on the following invariant for each move statement supplied to `ValidateMoves()`:
- The "from" and "to" addresses are of the same `MoveEndpointKind`.
=> refactoring: error when changing resource type during move

internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/command/meta_backend_migrate.go
Given: You have multiple explicit local workspaces, and the `default`
workspace is empty.
When: You migrate the workspaces to Terraform Cloud.
Then: Terraform should _not_ ask for a workspace to migrate the
`default` workspace to in Terraform Cloud.
=> Cloud: Migrate empty default workspace prompt

internal/command/format/diff.go, internal/command/format/diff_test.go
Unchanged elements in nested attributes backed by sets were previously misrendered as empty objects. This PR removes the additional brackets and adds a count of unchanged elements, and secondarily fixes the indentation for these diffs.
Targeting 1.1 backport.
Before:
After:
=> cli: Fix diff for nested set unchanged elements

internal/command/format/diff.go, internal/command/format/diff_test.go
[As noted in this comment](https://github.com/hashicorp/terraform/pull/29983#issuecomment-974383383), the indentation for nested map rendering was out by two spaces. The same was true for a nested single object. As of this commit, these are now consistent with the other displays of object/map values.
Backporting to 1.1.
Before:
After:
=> cli: Fix nested single and map diff rendering

internal/command/init_test.go, internal/command/meta_backend_migrate.go
We cannot programmatically migrate workspaces to Terraform Cloud without
prompts, so `-input=false` should not be allowed in those cases.
There are 4 scenarios where we need input from a user to complete
migrating workspaces to Terraform Cloud.
1.) Migrate from a single local workspace to Terraform Cloud
* Terraform config for a local backend. Implicit local (no backend
specified) is fine.
* `terraform init` and `terraform apply`
* Change the Terraform config to use the cloud block
* `terraform init -input=false`
* You should now see an error message
2.) Migrate from a remote backend with a prefix to Terraform Cloud with
tags
* Create a workspace in Terraform Cloud manually. The name should
include a prefix, like "app-one"
* Have the terraform config use `backend "remote"` with a prefix …
=> Cloud integration requires input for migrations

internal/command/arguments/flags.go, internal/command/init.go
This fixes an issue where a user could not disable initialization of the `cloud` configuration block (As is possible with `-backend=false` for state backends), as well as add some syntactic sugar around `-backend` by adding a mutually
exclusive `-cloud` alias.
It also adjusts some help text in `init` to account for a backend to not necessarily be a constant in a _usage_ sense (e.g. you've configured TFC, etc).
=> command/init: Add -cloud alias to -backend, adjust `init` help output

internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_abstract_instance_test.go
Resource instances removed from the configuration would previously use the implied provider address. This is correct for default providers, but incorrect for those from other namespaces or hosts. The fix here is to use the stored provider config if it is present.
Fixes #30018
=> core: Fix schema loading for deleted resources

internal/configs/configschema/implied_type.go, internal/configs/configschema/implied_type_test.go, internal/configs/configschema/marks.go, internal/configs/configschema/marks_test.go
Object values returned from providers have their attributes marked as sensitive based on the provider schema. This was not fully implemented for nested attribute types, which is corrected in this commit.
This also fixes the JSON plan output for providers using nested attribute types to ensure that sensitive nested attribute values are marked accordingly.
=> configs: Add sensitive marks for nested attributes

internal/backend/remote-state/http/backend.go
Fixes #29978.
This retryablehttp client was missed when we introduced the `internal/logging` hclog logger.
=> backend/http: supply logging.LogOutput() to retryable client

internal/addrs/module_source.go, internal/addrs/module_source_test.go, internal/configs/module_call.go, internal/configs/testdata/error-files/module-invalid-registry-source-with-module.tf, internal/configs/testdata/error-files/module-local-source-with-version.tf, internal/earlyconfig/config_build.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go
Previously we ended up losing all of the error message detail produced by the registry address parser, because we treated any registry address failure as cause to parse the address as a go-getter-style remote address instead.
That led to terrible feedback in the situation where the user _was_ trying to write a module address but it was invalid in some way.
Although we can't really tighten this up in the default case due to our compatibility promises, it's never been valid to use the `version` argument with anything other than a registry address and so as a compromise here we'll use the presence of `version` as a heuristic for user intent to parse the source address as a registry address, and thus we can return a registry-address-specific error message in that case and thus give more …
=> addrs: Expose the registry address parser's error messages

internal/command/meta_backend.go
We recently added a prompt where, if no workspaces match the mapping in the configuration, we ask the user to create a new workspace instead of erroring with 'No workspaces found, so create a new workspace.', which is great.
The issue is, if that prompt is ignored and exited, the user is left in a very awkward state:
1. The saved backend config file (terraform.tfstate) shows now diff for the JSON attributes "serial", "tags" and "hash"
2. workspace list is completely empty if they run `terraform workspace list`
3.` terraform apply` still runs successfully and it's using the previous workspace, from the previous config and not the one from the current saved backend config
4. The cloud config is not reflective of how the working directory is set up at all
1. Change the workspace tag value …
=> Cloud: Update Terraform init -reconfigure prompt

internal/command/meta_backend.go
When going from a local backend to Terraform Cloud, if you skip the
`terraform init` and run `terraform apply` this will give the user more
clear instructions.
Closes https://github.com/hashicorp/terraform/issues/29969
=> Cloud: Apply without init error message

website/docs/internals/json-format.html.md
The `root_module.resources[].sensitive_values` key in the example output was incorrectly named and clashed with the regular `root_module.resources[].values` key.
=> Fix example for values-representation in docs for JSON Format internals

website/docs/language/settings/backends/remote.html.md
This helps to distinguish what is a `/` (as a directory separator)
from a "/" (as in "his/her").
=> Improve `.terraformignore` doc formatting

website/docs/cli/install/apt.html.md
The HashiCorp APT server supports several distro releases that were not in this list,
leading to a false impression that they aren't supported.
Note, Ubuntu has a new release twice a year, so periodic maintenance
is needed here.
=> Docs: Add newer Debian & Ubuntu versions to repo list

website/docs/cli/install/apt.html.md
Apologies for not creating an issue first but it seemed like a simple docs change. 
`apt install terraform` requires the  `apt update` before terraform can be installed.
=> Website/Docs: debian install - run apt update first

website/docs/language/modules/develop/refactoring.html.md
This PR adds a learn call out for `moved` blocks to the new page that @apparentlymart made for this feature! 🥳
=> Update note and add learn call out

website/layouts/language.erb, website/upgrade-guides/1-1.html.markdown
Since this is only a minor release there isn't any super-significant upgrade guide content this time, but I've used this page to elaborate on some of the upgrade notes already recorded in the Terraform changelog, to give additional context if needed to the hopefully-small number of users that these changes will directly effect during upgrading.
=> website: Terraform v1.1 upgrade guide

website/docs/language/settings/backends/remote.html.md, website/docs/language/values/variables.html.md, website/layouts/language.erb
We late-reorganized this into the "Module Development" subsection, but forgot to update the actual link in the navbar, so it was still linking to its old location.
=> website: Correct navbar link to the "Refactoring" page

go.mod, go.sum
This puts the go-tfe dependency back into the main branch and the latest official release. Previously, it was pointed at a pre-release branch to support run-specific variables.
=> Update go-tfe to v0.21.0

website/docs/language/settings/backends/s3.html.md
I'm guessing this document is just out of date, but I got an error when configuring `assume_role` as an argument and had to add an `assume_role` block
=> Update docs to use `assume_role` block

website/docs/language/values/variables.html.md
The variable example for `.tfvars` includes a spelling error making the `terraform` and `hcl` examples mismatch. (`moose` vs. `mosse`).
Live documentation with the typo: https://www.terraform.io/docs/language/values/variables.html#values-for-undeclared-variables
=> Docs: Change misspelling of variable in documentation

internal/command/format/diff.go, internal/instances/expander.go, internal/instances/expander_test.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_plan_orphan.go
Fixes #30110.
These commits are also on [a shared working branch](https://github.com/hashicorp/terraform/compare/f-implied-move-module-call), which I've rebased and squashed so that we don't have a broken commit on main if this is merged. From @apparentlymart's commit comment:
Previously we were treating it as a programming error to ask for the instances of a resource inside an instance of a module that is declared but whose declaration doesn't include the given instance key.
However, that's actually a valid situation which can arise if, for example, the user has changed the repetition/expansion mode for an existing module call and so now all of the resource instances addresses it previously contained are "orphaned".
To represent that, we'll instead say that an invalid instance key of a …
=> core: Fix crash with orphaned module instance

go.mod, internal/getmodules/getter.go, internal/getmodules/git_getter.go, internal/getmodules/git_getter_test.go
Earlier versions of this code allowed `ref` to take any value that would be accepted by `git checkout` as a valid target of a symbolic ref. We inadvertently accepted a breaking change to upstream `go-getter` that broke that as part of introducing a shallow clone optimization, because shallow clone requires selecting a single branch.
To restore the previous capabilities while retaining the `depth` argument, here we accept a compromise where `ref` has the stronger requirement of being a valid named ref in the remote repository if and only if `depth` is set to a value greater than zero. If `depth` isn't set or is less than one, we will do the old behavior of just cloning all of the refs in the remote repository in full and then switching to refer to the selected branch, tag, or naked commit …
=> getmodules: Re-allow git:: source with ref=COMMIT_ID

internal/terraform/context_plan_test.go, internal/terraform/context_validate_test.go, internal/terraform/evaluate.go, internal/terraform/testdata/plan-self-ref-multi-all/main.tf
Revert the evaluation change from #29862.
While returning a dynamic value for all expanded resources during validation is not optimal, trying to work around this using unknown maps and lists is causing other undesirable behaviors during evaluation.
Fixes #30127
=> use `cty.DynamicVal` for expanded resources during validation

internal/instances/expander.go, internal/instances/set.go, internal/instances/set_test.go, internal/terraform/context_apply2_test.go
After each plan, the entire set of known move blocks must be validated. Sometimes the individual addresses may lie outside of paths which are expanded during the plan, either through the use of `-target`, or later changes to the configuration that make the `moved` obsolete.
Since `instances.Set` is only used after all instances have been processed, it should only handle known instances and not panic when given an address that traverses an unexpanded module. This will allow for validation of `moved` block which no longer apply to the current set of address to skip over addresses which cannot be expanded.
Fixes #30196
Fixes #30184
=> Ignore unexpanded paths when validating move statements.

internal/backend/local/backend_apply.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go
This PR resolves 2 issues around failures during the core Apply step. 
- The first is that the graph building diagnostics were lost, and no error was being returned upon failure, allowing terraform to continue. 
- The second issue is that while an apply error normally means that there could be a partial state to store, in the event of an error before any apply operations have started we have no state, and should not overwrite the existing state. 
Fixes #30178
=> Apply graph failure handling

internal/backend/local/backend_apply.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go
Manual backport of #30199
----
This PR resolves 2 issues around failures during the core Apply step.
The first is that the graph building diagnostics were lost, and no error was being returned upon failure, allowing terraform to continue.
The second issue is that while an apply error normally means that there could be a partial state to store, in the event of an error before any apply operations have started we have no state, and should not overwrite the existing state.
Fixes #30178
=> Backport of Apply graph failure handling into v1.1

internal/command/init_test.go, internal/command/testdata/init-provider-now-unused/main.tf, internal/depsfile/locks.go, internal/depsfile/locks_test.go, internal/providercache/installer.go, internal/providercache/installer_test.go, website/docs/language/files/dependency-lock.mdx
Previously we would only ever add new lock entries or update existing ones. However, it's possible that over time a module may _cease_ using a particular provider, at which point we ought to remove it from the lock file so that operations won't fail when seeing that the provider cache directory is inconsistent with the lock file.
Now the provider installer (`EnsureProviderVersions`) will remove any lock file entries that relate to providers not included in the given requirements, which therefore makes the resulting lock file properly match the set of packages the installer wrote into the cache.
This does potentially mean that someone could inadvertently defeat the lock by removing a provider dependency, running `terraform init`, then undoing that removal, and finally running "terraform …
=> providercache: Discard lock entries for unused providers

website/docs/cli/commands/taint.mdx
A user recently submitted [this issue](https://github.com/hashicorp/terraform/issues/30194) where they were confused by the fact that the `-replace` flag is available on apply, but is not actually documented on the `apply` page or in the CLI output. It is documented in the `plan` page and CLI output, though and is indeed a valid flag for `apply`.
An investigation revealed that we do mention several times on the apply page that `apply` accepts all of the planning options and modes available on the `plan` page. Here's an example:
We also have a note in the CLI output for `apply -help` that says:
```
If you don't provide a saved plan file then this command will also accept
all of the plan-customization options accepted by the terraform plan command.
For more information on those options, …
```
=> Update taint command page to make alternative clearer

internal/configs/config_build.go, internal/configs/testdata/config-diagnostics/invalid-provider/errors, internal/configs/testdata/config-diagnostics/invalid-provider/main.tf, internal/configs/testdata/config-diagnostics/invalid-provider/mod/main.tf, internal/configs/testdata/config-diagnostics/invalid-provider/warnings
If there are errors loading the configuration, don't try to resolve the
provider names, as those names may not even be valid.
Fixes #30078
=> skip provider resolution when there are errors

internal/refactoring/move_execute.go, internal/refactoring/move_execute_test.go
When applying module `moved` statements by iterating through modules in state, we previously required an exact match from the `moved` statement's `from` field and the module address. This permitted moving resources directly inside a module, but did not recur into module calls within those moved modules.
This commit moves that exact match requirement so that it only applies to `moved` statements targeting resources. In turn this allows nested modules to be moved.
As of this commit, we are relying on the logic in `ModuleInstance.MoveDestination()` to control whether or not a given module instance is relevant to a moved statement. This method will return a `false` match result if the move statement doesn't apply: https://github.com/hashicorp/terraform/blob/cd7277128f5a3cf706307b4d11837b57b802 …
=> refactoring: Move nested modules

internal/cloud/e2e/apply_auto_approve_test.go, internal/cloud/e2e/backend_apply_before_init_test.go, internal/cloud/e2e/helper_test.go, internal/cloud/e2e/init_with_empty_tags_test.go, internal/cloud/e2e/main_test.go, internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go, internal/cloud/e2e/migrate_state_single_to_tfc_test.go, internal/cloud/e2e/migrate_state_tfc_to_other_test.go, internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go, internal/cloud/e2e/run_variables_test.go
As the cloud e2e tests evolved some common patters became apparent. This
standardizes and consolidates the patterns into a common test runner
that takes the table tests and runs them in parallel. Some tests also
needed to be converted to utilize table tests.
Running tests in parallel can help speed up overall test execution. Go
blocks parent tests while child tests run, so it does not fully fan out
as you might expect. It is noticeably faster, though. Running 4 or more
concurrent processes knocks over a minute off the total execution time.
=> Cloud: Add parallelism back into the tests

website/docs/language/functions/try.mdx
This paragraph is trying to say that try only works for dynamic errors and not for errors that are _not_ based on dynamic decision-making in expressions.
I'm not sure if this typo was always here or if it was mistakenly "corrected" at some point, but either way the word "probably" changes the meaning of this sentence entirely, making it seem like Terraform is hedging the likelihood of a problem rather than checking exactly for one.
(The text on this page could probably do with some more general editing and review too, but my goal here is only to correct this specific bug so that the paragraph is not misleading, and so I'd rather save more elaborate editing for a separate PR another day.)
=> website: Try function documentation "provably" vs "probably" typo

internal/addrs/module_instance_test.go, internal/addrs/move_endpoint_module.go, internal/addrs/move_endpoint_module_test.go, internal/refactoring/move_execute.go, internal/refactoring/move_statement.go, internal/refactoring/move_statement_test.go, internal/refactoring/move_validate_test.go, internal/refactoring/testdata/move-statement-implied/child/move-statement-implied.tf, internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf
When a move statement is only changing the index of a module, any moves within that module would result in cycles, because both the absolute `From` and `To` addresses would match both of the parent module's `From` and `To` address.
For example, changing the index of a module named `count` results in a a `from->to` of:
```
module.count->module.count[0]
```
And changing the count of a resource nested within `module.count` results in:
```
module.count[*].test.count->module.count[*].test.count[0]
```
Because `module.count[*]` matches both the `From` and `To` addresses of the parent, the edges would be added in both directions resulting in a cycle.
The graph we actually want in this case looks like 
```
module.count->module.count[0]
module.count[*].test.count->module.count[*].test.count[0] …
```
=> Handle move blocks within a module which is changing the index

internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go, internal/lang/funcs/encoding.go, internal/lang/funcs/encoding_test.go, internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go, internal/lang/funcs/number.go, internal/lang/funcs/number_test.go, internal/lang/funcs/redact.go, internal/lang/funcs/redact_test.go
Some function errors include values derived from arguments. This commit is the result of a manual audit of these errors, which resulted in:
- Adding a helper function to redact sensitive values;
- Applying that helper function where errors include values derived from possibly-sensitive arguments;
- Cleaning up other errors which need not include those values, or were otherwise incorrect.
Fixes #30033
```shellsession
$ echo 'base64decode("wheee")' | terraform console
╷
│ Error: Error in function call
│
│   on <console-input> line 1:
│   (source code not available)
│
│ Call to function "base64decode" failed: failed to decode base64 data "wheee".
╵
$ echo 'base64decode(sensitive("wheee"))' | terraform console
╷
│ Error: Error in function call
│
│   on <console-input> line 1:
│   (source code …
```
=> lang/funcs: Redact sensitive values from function errors

internal/addrs/module_instance_test.go, internal/addrs/move_endpoint_module.go, internal/addrs/move_endpoint_module_test.go, internal/refactoring/move_execute.go, internal/refactoring/move_statement.go, internal/refactoring/move_statement_test.go, internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go, internal/refactoring/testdata/move-statement-implied/child/move-statement-implied.tf, internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf
Create a separate `validateMoveStatementGraph` function so that
`ValidateMoves` and `ApplyMoves` both check the same conditions. Since
we're not using the builtin `graph.Validate` method, because we may have
multiple roots and want better cycle diagnostics, we need to add checks
for self references too. While multiple roots are an error enforced by
`Validate` for the concurrent walk, they are OK when using
`TransitiveReduction` and `ReverseDepthFirstWalk`, so we can skip that
check.
Apply moves must first use `TransitiveReduction` to reduce the graph,
otherwise nodes may be skipped if they are passed over by a transitive
edge.
=> cleanup some move graph handling

internal/dag/dag.go, internal/dag/dag_test.go
Remove two sorted walk functions which were left during a refactor to ensure the old behavior of a sorted walk was still accessible in some manner (this only refers to ordering of non-dependent nodes, different from a topological sort mentioned below). The package has since been removed from any public API, and the sorted versions are no longer called, so we can remove them.
Clarify the comments around the requirements for `TransitiveReduction`, `DepthFirstWalk`, and `ReverseDepthFirstWalk`. `TransitiveReduction` does not rely on having a single root, and only must be free of cycles. `DepthFirstWalk` and `ReverseDepthFirstWalk` do not do a topological sort, so if order matters `TransitiveReduction` must be called first.
=> dag: minor cleanup

internal/dag/edge.go
When creating a `Set` of `BasicEdge`s, the `Hashcode()` function is used to determine map keys for the underlying set data structure.
The string hex representation of the two vertices' pointers is unsafe to use as a map key, since these addresses may change between the time they are added to the set and the time the set is operated on.
Instead we modify the `Hashcode()` function to maintain the references to the underlying vertices so they cannot be garbage collected during the lifetime of the `Set`.
N.B. Testing of this PR is discussed elsewhere. I'm not sure if it is possible to create a unit test to demonstrate the undesirable behaviour.
=> dags: fix BasicEdge pointer issue

internal/cloud/backend_plan_test.go, internal/cloud/cloud_variables.go, internal/cloud/cloud_variables_test.go
All run variables remain encoded as strings in the API but will now be expressed as an HCL value to be evaluated correctly by the remote terraform. Previously, only strings were supported.
Examples:
string: `"quoted literal"` (strings must be quoted)
map:  `{ foo = "bar" }`
list: `["foo", "bar"]`
bool: `true`
null: `null`
number: `0.0001`
This requires the API to anticipate that all run variables will be HCL values
Backport of https://github.com/hashicorp/terraform/pull/29913
Fixes #30204
=> (backport) fix(run variables): support all variable types (map, list, bool, number, null, string)

.github/workflows/build-Dockerfile, .github/workflows/build.yml, internal/command/e2etest/main_test.go, internal/command/e2etest/make-archive.sh, internal/command/e2etest/primary_test.go, internal/command/e2etest/provider_dev_test.go, internal/command/e2etest/provider_plugin_test.go, internal/command/e2etest/providers_tamper_test.go, internal/command/e2etest/provisioner_plugin_test.go
This introduces a new process, based on GitHub Actions, for producing the various release artifacts for Terraform CLI.
The _ultimate_ goal here is for this workflow to build all of the artifacts needed to drive the Terraform CLI release process, so that the actual release process (maintained elsewhere) could consume these artifacts directly and no longer need to access the actual repository content, which in turn means that we can verify all of the artifacts before optionally launching the separate release process. The intended workflow then would be to first have this workflow build on the release branch, then once it's succeeded create a tag from the same commit to produce a releasable build. The branch build will have a synthetic version number including the commit ID, while the _tag_ …
=> A new build process, based on GitHub Actions

docs/plugin-protocol/releasing-new-version.md
I just read the docs with curiosity and found a typo.
=> docs: Fix typo in docs/plugin-protocol/releasing-new-version.md

website/docs/language/resources/provisioners/connection.mdx, website/docs/language/resources/provisioners/file.mdx, website/docs/language/upgrade-guides/1-1.mdx
We recently made a change to how provisioners upload files in order to address an unintended remote code execution vector when using SSH, which revealed that we had not previously documented well enough the expected contract for how provisioners upload files to remote systems, and so some users were depending on unintended consequences of the the bug now fixed.
We are retaining the fix on security-related grounds, but this is a good prompt to be clearer in the docs about what exactly Terraform is doing when asked to upload files over SSH and WinRM, so users can understand what is supported and write their configurations accordingly. The provisioners documentation hasn't had a comprehensive edit pass for a long time now, so while in the area I also took the opportunity to fix some …
=> website: Documentation of how provisioners upload files

.github/workflows/build.yml
Normally when we cross-compile we do so without CGo (the Go toolchain's default), because we don't have suitable C headers available for systems other than the host.
However, building for macOS on macOS is special because there are sufficient headers available on darwin_amd64 to build for both darwin_amd64 _and_ darwin_arm64. Also, we _must_ use CGo on macOS because the system resolver is only available via darwin's libc, and so building without CGo produces executables that don't resolve hostnames correctly. (golang/go#12524)
This is a conditional in bash to avoid having to duplicate the entire step. Perhaps later we'll find a more general version of this which can avoid the special case, but this is sufficient for the moment.
(Please note that this workflow is currently only used for …
=> build: CGO_ENABLED when building for macOS in our experimental new build workflow

website/docs/language/values/locals.mdx
The definition of local values used "it" many times, making the sentence not very clear.
=> Update local values definition

internal/states/instance_object.go, internal/states/instance_object_test.go
Resource dependencies are by nature an unordered collection, but they're
persisted to state as a JSON array (in random order). This makes a mess for
`terraform apply -refresh-only`, which sees the new random order as a change
that requires the user to approve a state update.
(As an additional problem on top of that, the user interface for refresh-only
runs doesn't expect to see that as a type of change, so it says "no changes!
would you like to update to reflect these detected changes?")
This commit changes `ResourceInstanceObject.Encode()` to sort the in-memory
slice of dependencies (lexically, by address) before passing it on to be
compared and persisted. This appears to fix the observed UI issues with a
minimum of logic changes.
- ~This change _does_ fix the UI issue, but oddly, it …
=> Sort dependencies when encoding `ResourceInstanceObject`

internal/terraform/eval_for_each.go, internal/terraform/eval_for_each_test.go
Our original messaging here was largely just lifted from the equivalent message for unknown values in "count", and it didn't really include any specific advice on how to update a configuration to make for_each valid, instead focusing only on the workaround of using the -target planning option.
It's tough to pack in a fully-actionable suggestion here since unknown values in for_each keys tends to be a gnarly architectural problem rather than a local quirk -- when data flows between modules it can sometimes be unclear whether it'll end up being used in a context which allows unknown values.
I did my best to summarize the advice we've been giving in community forum though, in the hope that more people will be able to address this for themselves without asking for help, until we're one day …
=> core: Invalid for_each argument messaging improvements

internal/terraform/context_validate_test.go, internal/terraform/node_module_variable.go, internal/terraform/transform_module_variable.go
Now that variable evaluation checks for a nil expression the graph
transformer does not need to generate a synthetic expression for
variable defaults. This means that all default handling is now located
in one place, and we are not surprised by a configuration expression
showing up which doesn't actually exist in the configuration.
Rename nodeModuleVariable.evalModuleCallArgument to evalModuleVariable.
This method is no longer handling only the module call argument, it is
also dealing with the variable declaration defaults and validation
statements.
Add an additional tests for validation with a non-nullable variable.
=> remove synthetic default expression for variables

website/docs/cli/state/index.mdx, website/docs/cli/state/move.mdx, website/docs/cli/state/taint.mdx
Previously the `terraform state ...` subcommands were the only way to perform various manipulations of the state, but in recent Terraform versions we have replaced these with better options.
Since these pages about `terraform state ...` seem to already have pretty good search engine optimization for the use-cases they are describing, we'll prioritize mentioning the new approaches and only mention the now-deprecated or de-emphasized features as a secondary approach.
Specifically:
- Describe the `-replace=...` planning option in preference to `terraform taint`, and present taint as primarily a mechanism for Terraform to use itself, as opposed to something end-users should typically use directly.
- Introduce the config-based refactoring features before describing `terraform state mv`.
The …
=> website: CLI state manipulation section de-emphasize old features

website/docs/language/resources/provisioners/salt-masterless.mdx
This PR fixes broken links that were found from a manual link check of the entire terraform.io site. Apparently SaltStack documentation has been relocated to a new URL. This PR fixes the broken links to point to the new URL paths.
=> Fix broken links to external docs

internal/terraform/context_validate_test.go, internal/terraform/node_module_variable.go
v1.1 targeted fix for #30307. The variable handling has been overhauled in v1.2 already, but we want to head off any possible incorrect use of null variables slipping into validation when `nullable=false` in the variable configuration. The given test is already fixed in v1.2 by #29959.
Default values are currently being handled in two places, the graph
transformation where a synthetic default expression is created if there
was no input expression, and in the evaluator when a reference to the
variable is evaluated. Unfortunately neither of these covers the case
where a non-nullable variable default needs to be checked within a
validation statement
Rather than try and fix the overall variable handling here, which runs
the risk of encountering more unexpected behavior, we are going to fixup …
=> Handle null variable input with nullable=false

internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go
Terraform uses "implied" move statements to represent the situation where it automatically handles a switch from `count` to no-`count` on a resource. Because that situation requires targeting only a specific resource instance inside a specific module instance, implied move statements are always presented as if they had been declared in the root module and then traversed through the exact module instance path to reach the target resource.
However, that means they can potentially cross a module package boundary, if the changed resource belongs to an external module. Normally we prohibit that to avoid the root module depending on implementation details of the called module, but Terraform generates these implied statements based only on information in the called module and so there's no need …
=> refactoring: Implied move statements can be cross-package

internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go
Previously we were just returning a string representation of the file mode, which spends more characters on the irrelevant permission bits that it does on the directory entry type, and is presented in a Unix-centric format that likely won't be familiar to the user of a Windows system.
Instead, we'll recognize a few specific directory entry types that seem worth mentioning by name, and then use a generic message for the rest.
The original motivation here was actually to deal with the fact that our tests for this function were previously not portable due to the error message leaking system-specific permission detail that are not relevant to the test. Rather than just directly addressing that portability problem, I took the opportunity to improve the error messages at the same time.
However, …
=> lang/funcs: fileexists slightly better "not a file" error message

internal/backend/backend.go, internal/backend/local/backend_local.go, internal/command/arguments/show.go, internal/command/arguments/show_test.go, internal/command/show.go, internal/command/show_test.go, internal/command/testdata/show-json-state/no-state/output.json, internal/command/views/show.go, internal/command/views/show_test.go, internal/command/views/testdata/show/main.tf
This PR refactors the `show` command by:
1. Removing its dependence on a local backend and local run to load necessary data
1. Only loading the backend when we need it
1. Migrating it to use the command arguments and views packages
1. Removing the now unnecessary `DisablePlanFileStateLineageChecks` flag added in #30205  to fix #30195 
The goal of this PR is to make the show command significantly simpler and easier to understand, without changing existing functionality. 
See https://github.com/hashicorp/terraform/pull/30205#issuecomment-997113175 for more context
main.tf used for relevant scenarios below
```
resource "null_resource" "test" {
count = 1
}
```
Build this branch locally and compare the following basic scenarios to the most recent version of Terraform to make sure the command …
=> cli: Refactor show command & migrate to command arguments and views

.github/workflows/build.yml
Hey all 👋  We need to update the github action linux packaging path instead of relying on the old redirect, which is no longer working. More info in this slack thread: https://hashicorp.slack.com/archives/C024ZDP4YGY/p1642701024072100
=> Update linux packaging action path

website/docs/language/functions/zipmap.mdx
zipmap does not produce a map with comma in terraform cli
tested with Terraform v1.1.3
=> Typo in zipmap documentation

internal/command/autocomplete.go, internal/command/workspace_delete.go, internal/command/workspace_new.go, internal/command/workspace_select.go
Fixes #30193 crash caused by nil pointer exception. It seems the autocomplete entry for the subcommand name itself was unnecessary and was crashing terraform. It has been removed.
=> Fix autocomplete for workspace subcommands

website/docs/language/values/outputs.mdx
References to child modules should use the resource name, not their path
=> Fix reference to child module in outputs docs

.github/workflows/merged-pr.yml
Untested (untestable?) GitHub actions workflow adding a comment to try to remind us to update the changelog when merging a PR.
=> Add merged pull request reminder 📎

help.go
Improve the help.go docs: typo and a more explicit comment.
=> Improve the help.go docs: typo and a more explicit comment.

website/docs/cli/commands/apply.mdx, website/docs/cli/commands/plan.mdx, website/docs/cli/commands/taint.mdx
Closes https://github.com/hashicorp/terraform/issues/30194
---------
This PR:
- Clarifies that you can replace multiple resources and once.
- Updates two of the callouts on the `apply` page so that they are more obvious. The callouts let users know they can also use all of the planning modes and options available to `terraform plan` when they run `terraform apply` without supplying a plan file.
=> Make -replace flag clearer

internal/configs/checks.go, internal/configs/experiments.go, internal/configs/named_values.go, internal/configs/parser_config.go, internal/configs/parser_config_test.go, internal/configs/resource.go, internal/configs/testdata/error-files/precondition-postcondition-constant.tf, internal/configs/testdata/invalid-files/data-reserved-lifecycle.tf, internal/configs/testdata/invalid-files/data-resource-lifecycle.tf, internal/configs/testdata/invalid-modules/preconditions-postconditions-experiment/preconditions-postconditions-experiment.tf, internal/configs/testdata/warning-files/preconditions-postconditions-experiment.tf, internal/experiments/experiment.go, internal/lang/eval.go, internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/eval_conditions.go, internal/terraform/evaluate_valid.go, internal/terraform/node_output.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_destroy.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_root_variable_test.go, website/docs/language/expressions/preconditions-postconditions.html.mdx
This PR introduces two new concepts to help document expectations and assumptions about resources, data sources, and outputs. By specifying `precondition` and `postcondition` blocks, module authors can define explicit checks which must be `true` for the configuration to be valid.
Preconditions are checked before creating a resource, reading a data source, or recording a module output value. These can be thought of as documented **assumptions** about the referenced data, which are checked by Terraform on every plan and apply. Preconditions can refer to values elsewhere in the configuration (which may cause Terraform to reorder the operations on those dependencies).
Postconditions are checked after creating a resource or reading a data source. As such, they may refer to values in the …
=> Preconditions and Postconditions

internal/configs/checks.go, internal/configs/resource.go, internal/configs/testdata/error-files/precondition-postcondition-selfref.tf
Preconditions and postconditions for resources and data sources may not refer to the address of the containing resource or data source. This commit adds a parse-time validation for this rule.
Config:
```terraform
terraform {
experiments = [preconditions_postconditions]
}
variable "length" {
type    = number
default = 2
}
resource "random_pet" "example" {
length  = var.length
keepers = {
uuid = uuid()
}
lifecycle {
precondition {
condition = random_pet.example.length > random_pet.example.length
error_message = "Pets cannot have single word names."
}
postcondition {
condition = length(regexall("[aeiou]", random_pet.example.id)) > 3
error_message = "Pet names must have at least three vowels."
}
}
}
```
Before:
After:
=> configs: Validate pre/postcondition self-refs

internal/terraform/context_plan.go, internal/terraform/context_validate.go, internal/terraform/graph_builder_plan.go
This vestigial field was written to but never read. I can't find when it was last used, but it appears to be useless now.
=> core: Remove unused PlanOpts.Validate

.github/CONTRIBUTING.md
During working on https://github.com/hashicorp/terraform/pull/30016 I have found out CONTRIBUTING.md is a little outdated on `go test` commands.
=> Update go test commands in .github/CONTRIBUTING.md.

website/docs/language/meta-arguments/depends_on.mdx
Closes https://github.com/hashicorp/terraform/issues/30252
___________________________
This PR:
-  Updates the documentation on the `depends_on` meta-argument page to help users better understand the potential consequences for Terraform operations and planning. 
- Explicitly tells users that Read actions and data sources are affected by `depends_on` and links to associated dependencies documentation on the resources and data sources pages, respectively. 
- Reorders the page to help with flow and to make sure that important points (like how `depends_on` should be used as a last resort) are more salient.  
More details about the motivation for these changes are available in the linked issue.
=> Update depends_on documentation

website/docs/cli/commands/console.mdx
This PR adds a line to the console command documentation that explains to users why they can't use the console during a run. This came from an internal conversation where users were surprised that they couldn't do this, as the console only performs read actions. But this is the intended behavior - we prevent any processes that read state while the state is actively being written.
=> Update Console Command Documentation

website/docs/language/settings/backends/remote.mdx, website/docs/language/state/workspaces.mdx
We recently surprised TFC/TFE users who were using the `remote` backend. There are two things of note here:
- First, workspaces that are set to have remote execution will no longer return default when you ask for `workspace.name`. They will return the name of the workspace with the prefix.
- Second, the behavior is different for the workspace depending on whether it is set to local or remote execution. For local, workspace.name returns only the name, no prefix. For remote execution, `workspace.name` will have the prefix on it. Previously, remote execution would always return `default`. 
Some users were using the fact that TFC/TFE workspaces with remote execution set up returned `default` to determine whether runs were taking place locally or remotely. Those users need an alternative way …
=> Clarify workspace.name expression

internal/command/state_mv.go, internal/command/state_mv_test.go
Manual backport of #29839 targeting v1.1. Fix `terraform state mv` to exit with code `1` when the specified resources are not found. Previously an error diagnostic would be displayed, but Terraform would exit successfully.
=> cli: Fix state mv exit code for missing resource (#29839)

website/docs/language/functions/substr.mdx
The `substr` function allows the `length` parameter to be longer than the remaining characters in the input after the offset. This is useful for when you want to truncate a string to a maximum number of characters. However, the documentation isn't clear on this so I had to do a test deployment to confirm the behaviour after finding the behaviour in an old issue https://github.com/hashicorp/terraform/issues/15751
=> Adds documentation to `substr` function to cover when `length` exceeds input length

internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_validate.go, internal/terraform/node_resource_validate_test.go
Adding a (non-Optional) Computed attribute to `ignore_changes` is a no-op, so we should warn users when they do this, as it is likely they intended something else.
Throwing an error here would be a breaking change.
Also adds test for the `StaticValidateTraversal()` check that verifies `ignore_changes` paths are present in the schema.
=> Warn when ignore_changes includes a Computed attribute

internal/command/jsonplan/plan.go, internal/command/jsonplan/plan_test.go
When calculating the unknown values for JSON plan output, we would previously recursively call the `unknownAsBool` function on the current sub-tree twice, if any values were unknown. This was wasteful, but not noticeable for normal Terraform resource shapes.
However for deeper nested object values, such as Kubernetes manifests, this was a severe performance problem, causing `terraform show -json` to take several hours to render a plan.
This commit reuses the already calculated unknown value for the subtree, and adds benchmark coverage to demonstrate the improvement.
Fixes #30548.
For these benchmarks, we construct a fairly narrow object value of variable depth, then compute its unknown value. The execution time difference for this change is:
| Object Depth | Speedup |
|---|---|
| 2 | 4x | …
=> jsonplan: Improve performance for deep objects

website/docs/language/modules/sources.mdx
Adding another example to make clear how to mix github.com inference as well as commit reference.
I came across this because I initially was using the github.com auto-magic reference AND it was inferring modules from subdirectories without the double slash. When it came time to pin my reference to a commit, I had trouble finding the proper format because I had to now add back in the double slash as well as the reference.
This example would have helped show me exactly what I needed in this instance.
=> [Docs] Added github.com commit reference example

website/docs/language/resources/provisioners/connection.mdx
One of the links was missing a slash before the path :-)
=> Fix broken link on provisioners connection page

go.mod, go.sum
Both `alibaba-cloud-sdk-go` and `winrmtest` depend on `satori/go.uuid`, which is unmaintained and has an associated CVE. This PR upgrades those dependencies to versions which do not directly depend on the vulnerable library.
Note that `satori/go.uuid` remains in `go.mod`, because transitive dependencies continue to depend on it. However, this no longer affects the Terraform binary, as the dependency is only used in tests of those dependencies.
Fixes #30570.
@xiaozhu36, are you able to test the OSS backend with these upgraded dependencies?
=> build: Upgrade `alibaba-cloud-sdk-go` and `winrmtest` dependencies

internal/terraform/context_apply_test.go, internal/terraform/node_resource_abstract_instance.go
The UI hooks for data source reads were missed during planning. Move the
hook calls to immediatley before and after the ReadDataSource calls to
ensure they are called during both plan and apply.
We also remove extra call sites for PreDiff and postDiff hooks.
PreDiff and PostDiff hooks were designed to be called immediately before
and after the PlanResourceChange calls to the provider. Probably due to
the confusing legacy naming of the hooks, these were scattered about the
nodes involved with planning, causing the hooks to be called in a number
of places where they weren't designed, including data sources and destroy
plans. Since these hooks are not used at all any longer anyway, we can
removed the extra calls with no effect.
If we choose in the future to call PlanResourceChange for …
=> ensure UI hooks are called for data sources

website/docs/language/expressions/operators.mdx
Including a note about logical operators not short-circuiting will make the documentation clearer and more useful. https://github.com/hashicorp/terraform/issues/24128 includes examples of people being caught out by this lack of clarity.
=> Document logical operators not short-circuiting

website/docs/language/modules/develop/providers.mdx
Documentation is wrong the `configuration_aliases` should be `[ aws.src, aws.dst ]` not `[ aws.src, aws.dest ]`.
=> Change aws.dest to aws.dst

internal/terraform/context_validate_test.go, internal/terraform/node_resource_validate.go, internal/terraform/node_resource_validate_test.go
The previous precondition/postcondition block validation implementation failed if the enclosing resource was expanded. This PR fixes this by generating appropriate placeholder instance data for the resource, depending on whether `count` or `for_each` is used.
=> core: Fix expanded condition block validation 

internal/terraform/context_apply.go, internal/terraform/graph_builder.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_destroy_plan.go, internal/terraform/graph_builder_eval.go, internal/terraform/graph_builder_import.go, internal/terraform/graph_builder_test.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_destroy_cbd_test.go
Complete the removal of the Validate option for graph building. There is
no case where we want to allow an invalid graph, as the primary reason
for validation is to ensure we have no cycles, and we can't walk a graph
with cycles. The only code which specifically relied on there being no
validation was a test to ensure the Validate flag prevented it.
Fixes #30647
=> Always validate the graph

internal/terraform/context_plan2_test.go, internal/terraform/eval_conditions.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_output.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/transform_output.go, internal/tfdiags/diagnostic.go, internal/tfdiags/hcl.go
Evaluate precondition and postcondition blocks in refresh-only mode, but report any failures as warnings instead of errors. This ensures that any deviation from the contract defined by condition blocks is reported as early as possible, without preventing the completion of a state refresh operation.
Prior to this commit, Terraform evaluated output preconditions and data source pre/postconditions as normal in refresh-only mode, while managed resource pre/postconditions were not evaluated at all. This omission could lead to confusing partial condition errors, or failure to detect undesired changes which would otherwise cause resources to become invalid.
Reporting the failures as errors also meant that changes retrieved during refresh could cause the refresh operation to fail. This is also …
=> core: Eval pre/postconditions in refresh-only mode

website/docs/cli/commands/import.mdx, website/docs/cli/import/usage.mdx
If any non(-regular) AWS user reads over the documentation for the import command, they might be confused when it just says 'AWS instance' as it could also refer to an account or datacenter.
So I added the resource type name to make it clear _which type of instance_ is meant.
=> Clearify which type of id is used in the documentation

website/docs/cli/commands/refresh.mdx
Provider is not misled into thinking. Terraform may be misled into thinking that all of the managed objects have been deleted . So, Terraform removes all of the tracked objects from the state file.
=> Terraform may be misled, not provider

internal/backend/remote/backend.go, internal/backend/remote/backend_apply_test.go, internal/backend/remote/backend_context.go, internal/backend/remote/backend_context_test.go, internal/backend/remote/backend_plan_test.go, internal/backend/remote/backend_test.go, internal/backend/remote/testdata/variables/main.tf, internal/cloud/backend.go, internal/cloud/backend_context.go, internal/cloud/backend_context_test.go, internal/cloud/testdata/variables/main.tf
This PR addresses this issue: https://github.com/hashicorp/terraform/issues/29966
The idea is that remote variables should not override local variables when executing a "Local Run"
In general, this should vastly improve the ergonomics of using `terraform import` with Terraform Cloud, especially when importing resources that require authentication.
Note: I'm very open to suggestions on how to improve the tests. I used the existing tests are a starting point, but I couldn't find a less-verbose way to implement the new tests.
=> fix: local variables should not be overridden by remote variables during `terraform import`

website/docs/cli/commands/import.mdx
There is always a configuration for import and using `-var` is always allowed.
=> Remove incorrect sentence

internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go
The `sum()` function accepts a collection of values which must all convert to numbers. It is valid for this to be a collection of string values representing numbers.
Previously the function would panic if the first element of a collection was a non-number type, as we didn't attempt to convert it to a number before calling the cty `Add` method.
=> functions: Fix sum() of all strings

internal/command/format/diff.go, internal/command/format/diff_test.go
When rendering a diff for an object value within a resource, Terraform should always display the value of attributes which may be identifying. At present, this is a simple rule: render attributes named "id", "name", or "tags".
Prior to this commit, Terraform would only apply this rule to top-level resource attributes and those inside nested blocks. Here we extend the implementation to include object values in other contexts as well.
Fixes #30641
=> cli: Fix missing identifying attributes in diff

website/docs/cli/commands/state/pull.mdx, website/docs/cli/commands/state/push.mdx
Closes https://github.com/hashicorp/terraform/issues/24986.
Users requested that we update the documentation to specify that terraform state files must be in UTF-8 format without a byte order mark. We also provide a solution to ensure that the state file is formatted properly using `Set-Content`.
=> Add note about powershell formatting

go.mod, go.sum, internal/backend/remote/backend.go, internal/backend/remote/backend_apply_test.go, internal/backend/remote/backend_common.go, internal/backend/remote/backend_context.go, internal/backend/remote/backend_state.go, internal/cloud/backend.go, internal/cloud/backend_apply_test.go, internal/cloud/backend_common.go, internal/cloud/backend_context.go, internal/cloud/backend_plan.go, internal/cloud/backend_runTasks.go, internal/cloud/backend_state.go, internal/cloud/e2e/apply_auto_approve_test.go, internal/cloud/e2e/helper_test.go, internal/cloud/e2e/migrate_state_multi_to_tfc_test.go, internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go, internal/cloud/e2e/migrate_state_single_to_tfc_test.go, internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go, internal/cloud/tfe_client_mock.go
This PR is updating terraform to use the latest major version for go-tfe.
1.0 version is not introducing new major features or functionality into the client, but mainly bringing consistency of practices into its codebase, like adding pointer type to optional fields and renaming interface methods. Because of this, the upgrade contains breaking changes.
More details about about 1.0 release: https://github.com/hashicorp/go-tfe/releases/tag/v1.0.0
=> Pull changes from go-tfe 1.0

internal/command/init.go
=> This removes the duplicate word "what" from terraform init -help message.

website/docs/language/resources/provisioners/file.mdx
Closes https://github.com/hashicorp/terraform/issues/30661#issuecomment-1067082006
This PR adds a note that when using `file` provisioner over SSH to a Windows system, you need to make sure that `cmd.exe` runs the commands and not PowerShell. Using PowerShell causes parsing errors that prevent the file from uploading properly. It also fixes the opening sentence to use active voice and also to avoid unnecessarily violent language, per our style guide.
=> Add PowerShell note to file provisioner page

website/docs/language/functions/format.mdx
The existing description for the '-' symbol as use in format() stated that the result would padded spaces to the left.  When tested in via 'terraform console' using `format("%-10.1f", 3)` the result was `"3.0       "`
Terraform v1.1.7
=> Description of '-' symbol as used in format()

website/docs/language/settings/backends/s3.mdx
This PR contains a small update to the docs to show an example of fine-grained access control to the dynamo state lock table.
=> Docs Update: Show example of state lock table access control

internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/errors.go, website/docs/cli/cloud/settings.mdx
`TF_ORGANIZATION` will serve as a fallback for configuring an organization in the `cloud`
block. This is the first step to make it easier for users wanting to configure Terraform
programmatically.
1. Pull this branch locally and run `go install .` which will install the binary in `$GOPATH/bin/terraform` 
1. Export `TF_ORGANIZATION` so Terraform can consume the var: 
```sh
export TF_ORGANIZATION="my-awesome-org"
```
3. Create a simple Terraform configuration, omitting `organization` from the `cloud` block. We'll use the `tfe` provider in this example. 
```hcl
terraform {
cloud {
hostname = "my-tfe.host.com"
workspaces {
name = "test"
}
}
}
provider "tfe" {
hostname = "my-tfe.host.com"
token = "my-tfe-token"
}
resource "tfe_workspace" "test" {
name = "my-awesome-workspace"
organization = …
```
=> Add TF_ORGANIZATION env var support

CHANGELOG.md, internal/cloud/backend.go, internal/cloud/backend_test.go, website/docs/cli/cloud/settings.mdx
This PR introduces the ability to configure `hostname` in the cloud configuration using the `TF_HOSTNAME` environment variable. `TF_HOSTNAME` is of course optional, as the cloud configuration will default to `app.terraform.io` if neither the env variable nor the hostname in the configuration are set. If both the `TF_HOSTNAME` and `hostname` in the configuration are set, Terraform will use `hostname`. 
1. Pull this branch locally and run `go install .` which will install the binary in `$GOPATH/bin/terraform` 
1. Export `TF_HOSTNAME` so Terraform can consume the var: 
```sh
export TF_HOSTNAME="my-awesome.tfe-host.io"
```
3. Create a simple Terraform configuration, omitting `hostname` from the `cloud` block. We'll use the `tfe` provider in this example. 
```hcl
terraform {
cloud { …
```
=> Add TF_HOSTNAME env var support

internal/command/meta_backend.go
Currently if an error occurs during client configuration, `b.Configure` it gets swallowed. This PR returns the error after it gets added to error diagnostics.
Errors occurring during client configuration gets swallowed.
Fixes [issue #30760](https://github.com/hashicorp/terraform/issues/30760)
Unit tests already exists
Paired with @uturunku1
=> command/meta_backend: fix for cloud integration panic

internal/backend/remote-state/oss/backend_state.go
This fixes a dropped `err` variable in `internal/backend/remote-state/oss`.
=> internal/backend/remote-state/oss: fix dropped error

internal/command/format/diff.go, internal/command/format/diff_test.go
This is a port of https://github.com/hashicorp/terraform/pull/25443 to the new diff renderer.
Fixes https://github.com/hashicorp/terraform/issues/21749
When rendering a diff, we should quote object attribute names if the string representation is not a valid identifier. While this is not
strictly necessary, it makes the diff output more closely resemble the configuration language, which is less confusing.
This commit applies to both top-level schema attributes and any object value attributes. We use a simplistic `"%q"` Go format string to quote the strings, which is not strictly identical to HCL's quoting requirements,but is the pattern used elsewhere in HCL and Terraform.
=> command/format: Correctly quote diff object keys

internal/command/meta_backend.go
Backport of [https://github.com/hashicorp/terraform/pull/30773](https://github.com/hashicorp/terraform/pull/30773)
Closes [https://github.com/hashicorp/terraform/issues/30646](https://github.com/hashicorp/terraform/issues/30646) and [https://github.com/hashicorp/terraform/issues/30760](https://github.com/hashicorp/terraform/issues/30760)
=> backport cloud integration panic fix

internal/command/format/diff.go, internal/command/format/diff_test.go
When rendering diffs for resources which use nested attribute types, we must cope with collections backing those attributes which are entirely sensitive. The most common way this will be seen is through sensitive values being present in sets, which will result in the entire set being marked sensitive.
This approach fixes the crash by entirely omitting sensitive collections from the diff output. For some situations this is reasonable—for example, a `list(string)` which is populated by a `sensitive` variable should be elided from user view. In other use cases, notably set-backed nested attributes, this is likely to be counter-intuitive. Unfortunately, given how cty copes with marks on sets, I don't see any alternative at this time.
Fixes #30824.
=> cli: Fix plan diff for sensitive nested attributes

internal/cloud/backend.go, internal/cloud/backend_test.go, website/docs/cli/cloud/settings.mdx
`TF_WORKSPACE` can now be used to configure your cloud block, effectively serving as an alternative to setting the `name` attribute in your workspaces configuration. In short, setting `TF_WORKSPACE="my-cool-wkspace"` is now akin to:
```hcl
terraform {
cloud {
workspaces {
name = "my-cool-workspace"
}
}
}
```
Given we've added support for `TF_ORGANIZATION` in #30719 and `TF_HOSTNAME` in #30748, we can now non-interactively configure the cloud block, leaving it empty in our configuration:
```hcl
terraform {
cloud {}
}
```
*^is now valid*
1. Pull this branch locally and run `go install .` which will install the binary in `$GOPATH/bin/terraform` 
1. Export `TF_WORKSPACE` so Terraform can consume the var: 
```sh
export TF_WORKSPACE="wkspace"
```
3. Create a simple Terraform configuration, …
=> Add cloud config support for TF_WORKSPACE

.release/release-metadata.hcl
This is a manual backport of https://github.com/hashicorp/terraform/pull/30717 for `v1.0`. 
👋  This PR adds a `.release/release-metadata.hcl` file to the repo. This contains static metadata that will be processed and sent as part of the payload in RelAPI POST requests, which will be sent when staging and production releases are triggered.  
This can be merged now, but will not have any effect until after the RelAPI launch. Similar additions are being added across all projects that publish to releases.hashicorp.com.
=> [v1.0 RelAPI Onboarding] Add release API metadata file

internal/command/format/diff.go, internal/command/format/diff_test.go
[A previous change](https://github.com/hashicorp/terraform/pull/30766) added missing quoting around object keys which do not parse as barewords. At the same time we introduced a bug where map keys could be double-quoted, due to calling the `displayAttributeName` helper function (to quote non-bareword keys) then using the `writeValue` method (which quotes all strings).
This commit fixes this and adds test coverage for map keys which require quoting.
Fixes #30854
=> cli: Fix double-quoted map keys in diff UI

internal/command/cliconfig/credentials.go, internal/command/cliconfig/credentials_test.go, website/docs/cli/config/config-file.mdx, website/docs/internals/remote-service-discovery.mdx
Introduces a new method of configuring token service credentials using a host-specific environment variable. This configuration was previously possible using the [terraform-credentials-env](https://github.com/apparentlymart/terraform-credentials-env) credentials helper.
This new method is now consulted first, as it is seen to be the most proximate source of credentials before CLI configuration. The configured credential helpers are consulted as a last resort.
The same naming methodology found in the helper is used for domains: periods (.) must be replaced by underscores, which is preferred because underscores are not allowed in DNS names and because periods are not allowed (or tricky to set) in variable names. The only gotcha I uncovered was that dashes are not valid characters in bash …
=> Allow remote service creds to be configured using env

internal/cloud/e2e/env_variables_test.go, internal/cloud/e2e/helper_test.go, internal/cloud/e2e/main_test.go
Cloud e2e tests for using environment variables: `TF_ORGANIZATION`, `TF_HOSTNAME`, `TF_WORKSPACE` to configure the `cloud` block. 
To run the tests:
```sh
go test ./internal/cloud/e2e -run Test_cloud_organization_env_var
go test ./internal/cloud/e2e -run Test_cloud_workspace_name_env_var
go test ./internal/cloud/e2e -run Test_cloud_workspace_tags_env_var
go test ./internal/cloud/e2e -run Test_cloud_null_config
```
=> Cloud e2e tests for configuring `cloud` with env vars

internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/upgrade_resource_state.go
Data sources do not have state migrations, so there may be no way to
decode the prior state when faced with incompatible type changes.
Because prior state is only informational to the plan, and its existence
should not effect the planning process, we can skip decoding when faced
with errors.
This PR intended for backporting avoids the error, however we probably don't need to deal with the prior state at all. I can follow-up with a more invasive PR to remove the extra state handling entirely for v1.2.
Fixes #30823
=> data schema changes may prevent state decoding

internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_plan_destroy.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/upgrade_resource_state.go
After data source handling was moved from a separate refresh phase into the planning phase, reading the existing state was only used for informational purposes. This had been reduced to reporting warnings when the provider returned an unexpected value to try and help locate legacy provider bugs, but any actual issues located from those warnings were very few and far between.
Because the prior state cannot be reliably decoded when faced with incompatible provider schema upgrades, and there is no longer any significant reason to try and get the prior state at all, we can skip the process entirely.
The only place where the prior state was functionally used was in the destroy path to create the change entry. Because a data source destroy is only for cleanup purposes to clean out the state …
=> remove the use of data source prior state from planning

internal/getproviders/registry_client.go
Occasionally `terraform init` on some providers may return the following error message:
```
Error while installing citrix/citrixadc v1.13.0: could not query provider
registry for registry.terraform.io/citrix/citrixadc: failed to retrieve
authentication checksums for provider: 403 Forbidden
```
That 403 is most often returned from GitHub (rather than Registry API) and this change makes it more obvious.
Similar to https://github.com/hashicorp/terraform/pull/29298
=> internal/getproviders: Add URL to error message for clarity

internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/testing.go
Ensure mocks are used for cloud backend configure tests and adds a few new tests for cloud configuration using environment variables.
Mocks were previously not used in these tests because Configure creates the tfe client but also makes several API calls using it. One minor functional change to highlight is that the cloud Backend Configure method only sets the client field if it's not already set. This prevents overwriting the mock client when the Configure method itself is under test.
=> test(cloud): ensure mocks are used for backend configure tests

internal/command/cliconfig/credentials.go, internal/command/cliconfig/credentials_test.go, website/docs/cli/config/config-file.mdx
After re-reviewing terraform-credentials-env, I made a mistake in not allowing period characters in `TF_TOKEN_...` variable names, nor allowing case-insensitive variable names. I now see that being liberal with variable names by using svchost.ForComparison on the variable name itself can allow for all these variations without a bunch of guessing code. I should have just lifted @apparentlymart 's code to begin with!
The only addition I made was to encode hyphens as double underscores. My reasoning about why this is OK is captured in the comment:
> We accept double underscores in place of hyphens because hyphens are not valid identifiers in most shells and are therefore hard to set. This is unambiguous with replacing single underscores below because hyphens are not allowed at the beginning …
=> fix(creds): allow periods in TF_TOKEN_... credentials vars

CHANGELOG.md
Removed the run task entry since the feature will be backported to v1.1. I've also added the missing
enhancement entry for using `TF_WORKSPACE` to configure your cloud block.
=> Minor changelog modifications

internal/backend/remote-state/azure/backend.go, internal/backend/testing.go, website/docs/language/settings/backends/azurerm.mdx
This PR changes the default value of `use_microsoft_graph` within the Azure Backend from `false` to `true` - [which was announced when this field was introduced in Terraform 1.1](https://www.terraform.io/language/settings/backends/azurerm#azurerm).
For end-users there should be no difference in obtaining a MSAL Token rather than an ADAL Token (although permissions changes may be needed for Microsoft Graph, rather than Azure Active Directory)
Fixes #30881
```
$ TF_ACC=1 envchain azurerm go test -v -timeout 900m ./internal/backend/remote-state/azure/...
--- PASS: TestBackendConfig (0.00s)
=== RUN   TestBackendAccessKeyBasic
--- PASS: TestBackendAccessKeyBasic (109.04s)
=== RUN …
```
=> backend/remote-state/azure: defaulting the Azure Backend to use MSAL

internal/lang/funcs/conversion.go, internal/lang/funcs/conversion_test.go
We had intended these functions to attempt to convert any given value, but there is a special behavior in the function system where functions must opt in to being able to handle dynamically-typed arguments so that we don't need to repeat the special case for that inside every function implementation.
In this case we _do_ want to specially handle dynamically-typed values, because the keyword `null` in HCL produces
`cty.NullVal(cty.DynamicPseudoType)` and we want the conversion function to convert it to a null of a more specific type.
These conversion functions are already just a thin wrapper around the underlying type conversion functionality anyway, and that already supports converting dynamic-typed values in the expected way, so we can just opt in to allowing dynamically-typed values and …
=> lang/funcs: type conversion functions can convert null values

.github/workflows/checks.yml, internal/command/views/hook_json_test.go, internal/communicator/communicator.go, internal/communicator/communicator_test.go, internal/plans/changes_sync.go, internal/terraform/node_output.go, internal/terraform/transform_output.go
The only non-test issue covered here was the use of stored changes from the plan in the output nodes, which instead should have been pulling the synchronized set directly from the context.
The additional race-enabled tests cover the bulk of terraform code via the `./internal/terraform` and `./internal/command` packages. They are much more time consuming to run however, and we can revisit the necessity of having the command package included in these if the race tests end up delaying results too much.
=> Fix known races and enable race detector in tests

internal/states/statefile/version4.go
typo found by [`revive`](https://github.com/mgechev/revive)
=> fix typo in struct tag

.github/workflows/build.yml
The `generate-metadata` action needs to be pulling from tags for better release management. We run the risk of disruption if we pushed changes to the `main` branch of the generate-metadata action thus disrupting release workflows for Terraform. 
Read more on [Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)
Feel free to add any labels (unsure if backporting is supported) -- LMK if I need to make this change for Terraform Enterprise.
=> change action to pull v1 instead of main

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
The plan graph does not contain all the information necessary to detect
cycles which may happen when building the apply graph. Once we have more
information from the plan we can build the complete apply graph with all
individual instances to verify that the apply can begin without errors.
This gives better feedback for users, allowing them to detect more problems
when running `plan` which would otherwise not be detected until `apply`.
Closes #30407
=> core: build a test apply graph during plan

go.mod, go.sum
This tagged release is a superset of the specific commit we had previously selected, adding in just an improved error message for inconsistent result types in a conditional expression.
The error message for #30562 would become the following after merging this:
```
╷
│ Error: Inconsistent conditional result types
│ 
│   on fun-with-tuples.tf line 20, in output "test":
│   20:   value = true ? { foo = { bar = 42 } } : { bar = 44 }
│ 
│ The true and false result expressions must have consistent types.
│ The 'true' value includes object attribute "foo", which is absent
│ in the 'false' value.
╵
```
This fixes #30562 and fixes #29226. (by improving the error message to be more specific, not by changing what is valid.)
=> build: go get github.com/hashicorp/hcl/v2@v2.12.0

CHANGELOG.md, internal/backend/remote/backend.go, internal/cloud/backend.go
This is re-opening #30663 with added support for the `cloud` backend as well. 
In short, the token read from your configuration, if it is set, should always be used over whatever token value is set in a `.terraformrc` file.
=> Give the configuration token higher precedence over the CLI config file

CHANGELOG.md, internal/cloud/backend.go, internal/cloud/backend_apply.go, internal/cloud/backend_cli.go, internal/cloud/backend_common.go, internal/cloud/e2e/apply_no_input_flag_test.go, internal/cloud/errors.go, internal/cloud/testing.go
For non-interactive contexts, Terraform is typically executed with the flag `-input=false`. However for runs that are not set to auto approve, the cloud integration will prompt a user for approval input even with the flag being set to false. This PR enables the cloud integration to know the value of the input flag and use it to determine whether or not to ask the user for input (i.e during run confirmation).
If `-input` is set to false and the run cannot be auto approved, the cloud integration will throw an error
stating run confirmation can no longer be handled in the CLI and that they must do so through the browser.
1) Create a Terraform configuration using the cloud integration.
2) Run `~/go/bin/terraform apply -input=false`
3) Expect an error.
=> Handle -input=false in cloud integration

website/docs/language/functions/urlencode.mdx
This PR fixes the result of `urlencode()`.
Also, I added a special character `!` into its example in order to the example show how urlencode works for ASCII special characters which should become percent-encoded.
The `urlencode()` is implemented by `url.QueryEncode()`.
https://github.com/hashicorp/terraform/blob/983e40bf4a27ce4a0c89a62a152bc8fec5476fa3/internal/lang/funcs/encoding.go#L183
`url.QueryEncode()` does not escapes ` ` to `%20` but `+`.
https://pkg.go.dev/net/url#QueryEscape
https://github.com/hashicorp/terraform/pull/29359
=> Fix an example for urlencode.mdx

internal/command/jsonplan/plan.go, internal/command/jsonplan/values.go, internal/command/jsonplan/values_test.go, internal/command/jsonstate/state.go, internal/command/jsonstate/state_test.go, internal/command/testdata/show-json-sensitive/output.json, internal/command/testdata/show-json-state/modules/output.json, internal/command/testdata/show-json/basic-create/output.json, internal/command/testdata/show-json/basic-delete/output.json, internal/command/testdata/show-json/basic-update/output.json, internal/command/testdata/show-json/conditions/output-refresh-only.json, internal/command/testdata/show-json/modules/output.json, internal/command/testdata/show-json/multi-resource-update/output.json, internal/command/testdata/show-json/provider-version-no-config/output.json, internal/command/testdata/show-json/provider-version/output.json, internal/command/testdata/show-json/sensitive-values/output.json, website/docs/internals/json-format.mdx
Previously the supported JSON plan and state formats included only serialized output values, which was a lossy serialization of the Terraform type system. This commit adds a `type` field in the usual `cty` JSON format, which allows reconstitution of the original value.
For example, previously a `list(string)` and a `set(string)` containing the same values were indistinguishable. This change serializes these as follows:
```json
{
"value": ["a","b","c"],
"type": ["list","string"]
}
```
and:
```json
{
"value": ["a","b","c"],
"type": ["set","string"]
}
```
=> json-output: Add output type to JSON format

internal/typeexpr/get_type.go, internal/typeexpr/get_type_test.go, internal/typeexpr/type_string_test.go, internal/typeexpr/type_type_test.go
The Terraform `internal/typeexpr` package is a fork of [the HCL `ext/typeexpr` package](https://github.com/hashicorp/hcl/blob/main/ext/typeexpr/README.md), but we dropped the tests when bringing it across. This PR imports those tests, then extends them to cover the `optional` extension made in this local fork.
=> typeexpr: Add test coverage

internal/communicator/shared/shared.go, internal/communicator/ssh/communicator.go, internal/communicator/ssh/http_proxy.go, internal/communicator/ssh/provisioner.go, internal/communicator/ssh/provisioner_test.go, internal/terraform/node_resource_validate.go, website/docs/language/resources/provisioners/connection.mdx
These commits support SSH over HTTP Proxy in the SSH provisioner without significantly changing the existing Pure Go SSH implementation.
I found that in #4523 #1709, the lack of support for SSH on HTTP Proxy has inconvenienced many people. I myself have to switch networks whenever I use terraform in a company network.
Therefore, I proposed this implementation.
- add `proxy_*` fields to `connection` which add configuration for a proxy host
- `proxy_host`: Setting this enables the SSH over HTTP connection. This host
will be connected to first, and then the `host` or `bastion_host` connection will be made from there.
- `proxy_port` - The port to use connect to the proxy host.
- `proxy_scheme` - http or https
- `proxy_user_name` - The username to use connect to the private proxy host.
- …
=> communicator/ssh: Add support SSH over HTTP Proxy

go.mod, go.sum
The existing ssh client was relying on legacy key algorithms and could not connect to recent versions of openssh, or servers with a limited set of fips approved algorithms.
Update `golang.org/x/crypto` to allow the ssh client to make use of newer key algorithms.
The server-side portion of this work is not yet completed, making a unit test difficult, but this was manually tested against an openssh server using the fedora35 fips configuration options
```
Ciphers aes256-gcm@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha2-512
KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256, …
```
=> udpate x/crypto/ssh

internal/cloud/backend_runTasks.go
Whoops! I have no idea how this was working before, but by looking at Go-TFE statuses for Run Tasks, I believe this string should be reading "pending".
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202212658537836
=> fix typo for task.Status

website/docs/language/files/dependency-lock.mdx
I was recently confused by the continued presence in the lock file of a provider on which I had (so I thought!) removed all dependencies from my config. With @alisdair's help, I determined that the provider was still being included in the lock file because there was still a data source from that provider in my state.
Adding a note about state to the lock file documentation to help others.
=> Add note about lockfile's relationship to state 

internal/backend/local/backend_apply.go, internal/backend/local/backend_apply_test.go
When executing an apply with no plan, it's possible for a cancellation
to arrive during the final batch of provider operations, resulting in no
errors in the plan. The run context was next checked during the
confirmation for apply, but in the case of -auto-approve that
confirmation is skipped, resulting in the canceled plan being applied.
Make sure we directly check for cancellation before confirming the plan.
Fixes #30918
=> check for cancellation before apply confirmation

internal/communicator/ssh/communicator.go
A mistake in the nested conditional logic led to us calling `o.Output` when `o` was `nil`, which is the case for the `file` provisioner's connection process.
Fixes #30982. Tested manually:
```
aws_instance.test: Creating...
aws_instance.test: Still creating... [10s elapsed]
aws_instance.test: Still creating... [20s elapsed]
aws_instance.test: Still creating... [30s elapsed]
aws_instance.test: Still creating... [40s elapsed]
aws_instance.test: Provisioning with 'file'...
aws_instance.test: Still creating... [50s elapsed]
aws_instance.test: Provisioning with 'remote-exec'...
aws_instance.test (remote-exec): Connecting to remote host via SSH...
aws_instance.test (remote-exec):   Host: 34.227.59.196
aws_instance.test (remote-exec):   User: ec2-user
aws_instance.test (remote-exec):   Password: …
```
=> communicator/ssh: Fix crash using SSH+HTTP proxy

internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/cloud/backend.go, internal/cloud/backend_test.go
Bump compatibility version from 1.2.0 to 1.3.0 for upcoming terraform core release.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202218836281989
=> Bump compatibility version to 1.3.0 for terraform core release

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go
We can no longer be assured that the particular instance of a provider we are using has had `GetProviderSchema` called, so the diagnostics may not have been previously checked. Always check the diagnostics, even if we're fetching a cached response, in order to provide a more meaningful error instead of a panic in the rare case where the rpc call failed.
Fixes #30655
=> plugin: diagnostics must be checked on all schema calls

website/docs/cli/commands/plan.mdx
Related to: https://github.com/hashicorp/terraform/issues/30600
This PR warns users that Terraform will error if they include spaces before or after variable declarations when using the `-var` flag. For example, users should not use `-var "length = 2". Instead, they should use `-var "length=2".
=> Add warning about spaces in variable value assignment

website/docs/language/expressions/custom-conditions.mdx
AWS always set private_dns to something, but public_dns is only set if it's enabled on the VPC. We needed to change our example from `self.private_dns` to `self.public_dns` so it works correctly.
Thanks to @robin-norwood for catching this!
=> Change private to public in custom conditions example

website/docs/cli/cloud/settings.mdx
Related to https://github.com/hashicorp/terraform-website/pull/2310
Add a warning about the potential of drift to the new section about non-interactive `cloud` block environment variables. Remote execution with the non-interactive component would require users to auto-approve plans. We provide more details about why this happens and suggest an alternative in the linked PR.
=> Add warning about drift to cloud block environment variables

internal/configs/provider_validation.go
This fixes a bug introduced in #30639 in which initialising a module will fail if that module contains both a provider block and a module call using `for_each`.
This bug was introduced in https://github.com/hashicorp/terraform/pull/30639/files#diff-95e614048e1ba4ba7621e22ba67cfe5c8acd386e5540b8c92c267d2fd1b3d31eR31-R55 by removing a variable scoped to a `for` loop (`var nope`) and instead overwriting `noProviderConfigRange`. This meant that the error at https://github.com/hashicorp/terraform/pull/30639/files#diff-95e614048e1ba4ba7621e22ba67cfe5c8acd386e5540b8c92c267d2fd1b3d31eR181 would be triggered if the _parent_ module contained a provider block, not the child.
Fixes #31081
There are no tests in code for this behaviour. Highly recommend adding them as follow up. I manually tested this …
=> configs: fix module for_each call bug

CHANGELOG.md
Changing a typo in the Big Fixes list: `inteerruptiong` to `interruption`.
=> Correct typo in 1.2.0's CHANGELOG.md

go.mod, go.sum
The version that was in use previously broke my runs using ssh-agent with a signed ed25519 key with a nice `ssh: handshake failed: agent unsupported algorithm "ssh-ed25519"` error.  I took a further look into this, and saw that the upstream change that broke it for me was fixed in https://github.com/golang/crypto/commit/46612604a -- therefore I just updated this dependency again to the (as the time of writing) latest version.
If possible this change needs a backport to terraform 1.2, as this is the version I tried to use ...
=> update golang.org/x/crypto again

internal/command/output.go
The official docs [suggest](https://www.terraform.io/docs/cli/commands/output.html#usage) the `-state` flag  for `terraform output` is ignored, when using remote state. This information is not present in the CLI help text. From my experience, it does seem the official docs are correct.
=> Fix CLI help text for output. 

internal/configs/configload/loader_load_test.go, internal/configs/configload/testdata/child-provider-child-count/.terraform/modules/modules.json, internal/configs/configload/testdata/child-provider-child-count/child-provider-child-count.tf, internal/configs/configload/testdata/child-provider-child-count/child/child-provider-child-count-child.tf, internal/configs/configload/testdata/child-provider-child-count/grandchild/child-provider-child-count-grandchild.tf, internal/configs/configload/testdata/child-provider-grandchild-count/.terraform/modules/modules.json, internal/configs/configload/testdata/child-provider-grandchild-count/child-provider-grandchild-count.tf, internal/configs/configload/testdata/child-provider-grandchild-count/child/child-provider-grandchild-count-child.tf, internal/configs/configload/testdata/child-provider-grandchild-count/grandchild/child-provider-grandchild-count-grandchild.tf
#31091 addressed a regression in the logic for catching when the newer module meta-arguments are used in conjunction with the legacy practice of including provider configurations inside modules, where the check started incorrectly catching situations where the legacy nested provider configuration was in the same module as the child call using one of those meta-arguments.
This is a regression test to catch if a similar bug arises in the future.
Since it's testing validation rules that apply to an entire configuration tree, it ended up in a rather idiosyncratic location under the `configload` package, rather than directly in `configs`. The `configs` package only knows how to load one module at a time, so it's harder to write a test like this in that context. Due to it being further removed …
=> configs: A test for the regression reported in #31081

internal/configs/configload/loader_load.go, internal/configs/configload/loader_snapshot_test.go, internal/configs/configload/loader_test.go, internal/configs/configload/testdata/already-installed-now-invalid/.terraform/modules/modules.json, internal/configs/configload/testdata/already-installed-now-invalid/foo/bar/main.tf, internal/configs/configload/testdata/already-installed-now-invalid/foo/main.tf, internal/configs/configload/testdata/already-installed-now-invalid/root.tf
In configurations which have already been initialized, updating the source of a non-root module call to an invalid value could cause a nil pointer panic. This commit fixes the bug and adds test coverage.
Fixes #31056.
=> configs: Fix module loader nil pointer panic

.github/workflows/build.yml, internal/command/e2etest/make-archive.sh
Back in #30283 we introduced a prototype new build process that for now just signals whether we were able to build working executables for various platforms, but is hopefully destined to one day become the first step in our routine release process, producing the artifacts that we'll ultimately publish.
We merged that PR early in order to get some experience with its behavior over several different kinds of releases, since this sort of thing is notoriously hard to test realistically in an artificial environment. Since then, we've learned about a couple of quirks that this PR aims to now address:
* #30864: Due to how the standard "checkout" GitHub Action tries to fetch as little as possible, it was not producing a fully-fledged-enough repository for us to analyze tags to automatically …
=> build: Further polishing of the prototype build workflow

website/docs/language/values/variables.mdx
This reverts commit 7756023564f006658a9bdef2a21a0005c4702b2b.
This is an intentional typo to highlight that a warning is produced if a variable is provided and not required.
=> Revert "Docs: Change misspelling of variable in documentation"

website/docs/language/meta-arguments/lifecycle.mdx
- Note that it was added in v1.2, so users know whether they can use it yet.
- Fix nested indentation formatting, so the parent list item stays together.
- Minor copy edits.
- List all of the available lifecycle block arguments before diving into the
docs for each argument, for ease of reading/scanning.
By the way, this new feature rules. 🤘 Our team ran across it while evaluating a PR to add a resource-specific replacement trigger to the tfe provider, and being able to just use this on anything is far nicer.
=> Edit docs for replace_triggered_by lifecycle argument

internal/command/meta_vars.go, internal/command/plan_test.go
When specifying variable values on the command line, name-value pairs must be joined with an equals sign, without surrounding spaces. Previously Terraform would interpret `-var "foo = bar"` as assigning the value `" bar"` to the variable named `foo `. This is never valid, as variable names may not include whitespace.
This commit looks for this specific error and returns a diagnostic with a suggestion for correcting it. We cannot simply trim whitespace, because it is valid to write `-var "foo= bar"` to assign the value `" bar"` to the variable `foo`, as unlikely as it seems.
Fixes #30600, see also documentation in #30969.
Before:
After:
=> cli: Improved error for invalid -var "foo = bar"

internal/cloud/backend_runTasks.go
Ryan Hall noticed that one important aspect of the run task result is not present in the run task result summary displayed by the CLI: The URL
In the platform, the run task result offers a link "details" which directs the user to the URL from the third party integration where the user can see more information about why a task failed or succeeded.
The URL was never part of the original implementation for how we display results in the CLI. So this is not a bug. However, by looking at some of the design images shared by Brian, there was clearly a desired to include the url in the output. We may have not noticed the url was there and that is why we skipped that implementation at the time.
Result after adding the URL:
When I squeeze my terminal, I have noticed that vertical line gets pushed. …
=> add url to run task summary

internal/terraform/context_apply2_test.go, internal/terraform/context_plan.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_destroy_plan.go, internal/terraform/graph_builder_plan.go, internal/terraform/transform_config.go, internal/terraform/transform_destroy_edge.go, internal/terraform/transform_destroy_edge_test.go, internal/terraform/transform_orphan_resource.go, internal/terraform/transform_output.go, internal/terraform/transform_reference.go
This PR aims to allow the same components used in `PlanGraphBuilder` to create the full destroy plan, and eliminate the special case of the `DestroyPlanGraph`.
The destroy plan was originally envisioned to be completely "offline", where we could generate a simple `Delete` action for every resource in the state. It turns out that this is not possible, since in order to read each resource from the state, we must call `UpgradeResourceState` to ensure the schema matches the encoded state, requiring interaction with the provider aside from fetching the schema. Provider developers have also expressed the desire to be able to plan or validate destroy actions, which would also require providers to be correctly configured. 
Because the simplistic `DestroyPlanGraphBuilder` was only intended to …
=> Use plan graph builder for destroy

docs/planning-behaviors.md
For a while now we've had information equivalent to this in various internal documents that we've referred to when designing features such as config-driven refactoring, the "replace" planning option, and so forth.
However, so far we've not put that information in any sort of durable public place that we can easily find and refer to when having design discussions on GitHub and similar.
This is therefore an attempt to capture a summary of the three main design patterns we've identified for planning-related behaviors, with a few motivating examples of each one, in the hope that this will be a good reference and some helpful inspiration for future design work.
It's intentionally not totally comprehensive of all planning behaviors both because that would duplicate the end-user-oriented …
=> development docs: Planning Behaviors

internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go
Closes #31047
Prevent potential panics and immediately return provider-defined errors diagnostics.
Previously in `internal/plugin6`:
```
--- FAIL: TestGRPCProvider_GetSchema_ResponseErrorDiagnostic (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x17fa752]
goroutine 13 [running]:
testing.tRunner.func1.2({0x191a100, 0x2236330})
/usr/local/Cellar/go/1.18.2/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
/usr/local/Cellar/go/1.18.2/libexec/src/testing/testing.go:1392 +0x39f
panic({0x191a100, 0x2236330})
/usr/local/Cellar/go/1.18.2/libexec/src/runtime/panic.go:838 +0x207 …
```
=> Return early on GetProviderSchema RPC responses with error diagnostics

website/docs/language/expressions/custom-conditions.mdx
Clarify for users how they can use the `format` function to translate `null` values and items from `list` and `map` into a formatted string. This lets them include these values in the error messages :) 
Closes https://github.com/hashicorp/terraform/issues/31165
=> Add guidance about using the format function

internal/backend/init/init.go, internal/backend/init/init_test.go
Add deprecation warnings to all unmaintained remote state backends. The following backends have remained without maintainers since before v1.0 of Terraform, and are planned to be removed in the next major release.
- artifactory
- etcd
- etcdv3
- manta
- swift
=> deprecate unmaintained remote state backends

website/docs/language/meta-arguments/depends_on.mdx
I was reading the docs and just notice some unnecesary words in the `depends_on` meta argument documentation
=> docs: update depends_on.mdx meta-argument

internal/terraform/context_apply2_test.go, internal/terraform/node_provider.go, internal/terraform/node_resource_abstract_test.go, internal/terraform/provider_mock.go
In order to correctly call `UpgradeResourceState` during a destroy plan, the provider provider must be configured. Now that the destroy plan can completely evaluate the provider configuration, enable the call to `ConfigureProvider` during that plan.
Fixes #30460
=> Configure providers during a destroy plan

website/docs/cli/install/apt.mdx
Currently `sudo` is applied to `echo` resulting in:
`/etc/apt/sources.list.d/terraform.list: Permission denied`
Using `echo "..." | sudo tee /etc/apt/sources.list.d/terraform.list` fix the problem
=> Fix a wrong usage of sudo in debian install doc

website/data/cli-nav-data.json, website/data/internals-nav-data.json, website/data/language-nav-data.json
Previously, the "Internals" section of our docs took you to a page that did not have a standard sidebar. This is a disorienting experience for users. It is also disorienting because currently, the Internals section appears to be a part of the CLI sidebar, but when users actually click a page, they are suddenly taken to a new sidebar.
This PR adds a header to the Internals sidebar to make it feel more standard and also provides links to and from the CLI and Language documentation so users can navigate back and forth. It uses a convention that we have leveraged in the Terraform Cloud Agents documentation to signify to users that they are about to be taken to a new sidebar. 
**Links in TFC Docs:**
=> Add internals to the sidebar

internal/backend/remote-state/cos/client.go
When running command `terraform force-unlock` , the remote state file will be removed as expect. However, the `tencentcloud-terraform-lock` tag will not removed at the same time in some unexpected program exit cases. Creating this PR is purpose to ensure the tag removed to get rid of impact of next terraform operation.
Here shows the unit test output:
```
$ TF_ACC=1 go test -v ./internal/backend/remote-state/cos
=== RUN   TestStateFile
=== PAUSE TestStateFile
=== RUN   TestRemoteClient
=== PAUSE TestRemoteClient
=== RUN   TestRemoteClientWithPrefix
=== PAUSE TestRemoteClientWithPrefix
=== RUN   TestRemoteClientWithEncryption
=== PAUSE TestRemoteClientWithEncryption
=== RUN   TestRemoteLocks
=== PAUSE TestRemoteLocks
=== RUN   TestBackend
=== PAUSE TestBackend
=== RUN …
```
=> Backend/COS: remove COS object lock tag either when unlock remote state

internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go
Expanded resource instances can initially share the same dependency
slice, so we must take care to not modify the array values when
checking the dependencies.
In the future we can convert these to a generic Set data type, as we
often need to compare for equality and take the union of multiple groups
of dependencies.
Fixes #31243
=> copy dependency values when sorting

internal/configs/config_test.go, internal/configs/provider_validation.go, internal/configs/testdata/duplicate-local-name/main.tf, internal/terraform/transform_provider.go, internal/terraform/transform_provider_test.go
Adding multiple local names for the same provider type in `required_providers` was not prevented, which can lead to ambiguous behavior in Terraform. Providers are always located via the provider's fully qualified name (even using the full name as a map key in many places), so duplicate local names cannot be differentiated. This can lead terraform to non-deterministically configure the incorrect provider in some cases.
Because it is currently possible that a configuration with providers which themselves do not need explicit configuration may have been working with duplicates, we cannot turn these into errors. Adding multiple entries for the same provider now results in a warning like so:
```
│ Warning: Duplicate required provider
...
│
│ Provider hashicorp/null with the local name "dupe" …
```
=> Validate duplicate provider local names in `required_providers`

internal/command/jsonplan/plan.go, internal/command/jsonplan/plan_test.go
The JSON output for sequences previously omitted unknown values for tuples and sets, which made it impossible to interpret the corresponding unknown marks. For example, consider this resource:
```hcl
resource "example_resource" "example" {
tags = toset(["alpha", timestamp(), "charlie"])
}
```
This would previously be encoded in JSON as:
```json
"after": {
"tags": ["alpha", "charlie"]
},
"after_unknown": {
"id": true,
"tags": [false, true, false]
},
```
That is, the timestamp value would be omitted from the output altogether, while the corresponding unknown marks would include a value for each of the set members.
This commit changes the behaviour to:
```json
"after": {
"tags": ["alpha", null, "charlie"]
},
"after_unknown": {
"id": true,
"tags": [false, true, false]
},
```
This aligns …
=> json-output: Fix unknowns for tuples and sets

internal/command/jsonplan/plan.go, internal/command/testdata/show-json/unknown-output/main.tf, internal/command/testdata/show-json/unknown-output/output.json
Planned output changes are represented in the JSON output format using the same change object as planned resource changes. This structure includes an `after` value and a parallel `after_unknown` value, which can be combined to determine which specific parts of a value are known only at apply time.
Previously, structured output values would be marked in the JSON plan as coarsely known or unknown, even if only some subset of the structure will be known only at apply time. This simplification was unnecessary, and this commit reuses the same logic for resource changes to give more information to consumers of this format.
For example, consider this output:
```hcl
output "bar" {
value = tolist([
"hello",
timestamp(),
"world",
])
}
```
The plan UI for this output would be:
```
+ bar = [
+ …
```
=> json-output: Extended detail for unknown outputs

internal/states/remote/testing.go
When attempting to lock a remote state backend, failure due to an existing lock should return an instance of `LockError`. This allows the wrapping code to retry until the specified timeout, instead of immediately exiting.
This commit adds a test for this in the `TestRemoteLocks` test helper, which is used in many of the remote state backend test suites.
This would have caught the bug fixed by #31256, for example, and the http backend tests fail without the commit in that PR.
=> states/remote: Check for LockError error type

internal/configs/experiments.go, internal/configs/testdata/invalid-modules/object-optional-attrs-experiment/object-optional-attrs-experiment.tf, internal/configs/testdata/valid-files/object-optional-attrs-experiment.tf, internal/experiments/experiment.go, internal/terraform/context_apply_test.go, website/docs/language/expressions/type-constraints.mdx
This PR concludes the optional attributes experiment, and revises the associated documentation for type constraints. It attempts to make the writing more concise and also use conventions like bullets to help make the content clearer.
It also:
- Adds a note at the top of the section that this functionality is only available in v.1.3 and later (following the convention we've used for this type of notice in other places in our docs).
- Removes a section about how this is experimental. My understanding is that the goal is to end the experiment when 1.3 is launched, and thus this section will not be necessary. Please let me know if I'm mistaken!
**ADD REDIRECT:** When we remove pages, we need to add a redirect. I created a companion PR in `terraform-website` that adds a redirect for the …
=> Edit type constraints docs for style and flow

internal/addrs/module.go, internal/addrs/module_test.go
After the change:
```
terraform/internal/addrs$ go test -bench=Module . -benchmem
BenchmarkModuleStringShort-12           15489140                77.80 ns/op           24 B/op          1 allocs/op          
BenchmarkModuleStringLong-12            10807070               111.8 ns/op            80 B/op          1 allocs/op   
```
before the change:
```
BenchmarkModuleStringShort-12            3290968               384.2 ns/op           120 B/op          3 allocs/op          
BenchmarkModuleStringLong-12             1859038               668.4 ns/op           304 B/op          4 allocs/op  
```
About 5x speedup for time, and only single allocation.
Inspiration for this change is perf profiling on a particularly large config which points to memory churn:
```
29.34%  terraform  terraform …
```
=> Performance: string builder speedup for Module.String()

website/docs/language/providers/requirements.mdx
The [Best Practices](https://www.terraform.io/language/providers/requirements#best-practices-for-provider-versions) section of the Provider Requirements page incorrectly describes how a provider version operator works. Specifically this sentence:
> The ~> operator is a convenient shorthand for allowing only patch releases within a specific minor release:
It suggests the operator is only concerned with the patch portion of a version, but that's not correct. According to the [Version Constraint docs](https://www.terraform.io/language/expressions/version-constraints) it:
> Allows only the rightmost version component to increment. For example, to allow new patch releases within a specific minor release, use the full version number: ~> 1.0.4 will allow installation of 1.0.5 and 1.0.10 but not …
=> Clarify how the ~> version constraint operator works

website/docs/cli/commands/apply.mdx, website/docs/cli/commands/plan.mdx
Closes https://github.com/hashicorp/terraform/issues/30839
This PR updates the `apply` command page to streamline language and also give more context about what planning modes and options are. This should help users who are new to Terraform understand why they may want to include some additional flags on the apply command and helps solve the continual issue of how all the `plan` flags are available for `apply`..but we don't list them on that page :) 
This PR also clarifies the destroy mode is essentially the same as running `terraform destroy`. On `terraform destroy` we say it's a convenience way to run `terraform apply -destroy`, so this PR adds this information to the `plan` page as well.
=> Update apply page for style, concision, and clarity

website/docs/language/functions/merge.mdx
Even if the expansion with three dots is explicity mentioned in https://www.terraform.io/language/expressions/function-calls#expanding-function-arguments the additional example would have helped me a lot as it is a common use case to "flatten" a list of maps.
=> Added example with function argument expansion

go.mod, go.sum, internal/terraform/context_test.go, internal/terraform/version_required.go
Closes https://github.com/hashicorp/terraform/issues/28148
Any `required_version` that contains a prerelease field will fail the later constraint check anyway. This change ensures the reported error message makes clear that prerelease versions are not supported in the `required_version` constraint.
=> Fail global required_version check if it contains any prerelease fields

website/docs/language/functions/format.mdx
Closes https://github.com/hashicorp/terraform/issues/31175
User requested that we specifically call out that you can use the `format` function to convert items of `null`, `list`, and `map` types into a formatted string.
=> Update format function to mention list, map, and null types

go.mod, go.sum
There doesn't appear to be any reason we pinned `github.com/golang/mock` on an old version.
=> remove go.mod replacement of `github.com/golang/mock`

docs/planning-behaviors.md, docs/resource-instance-change-lifecycle.md, website/README.md
There are small typos in:
- docs/planning-behaviors.md
- docs/resource-instance-change-lifecycle.md
- website/README.md
Fixes:
- Should read `exhaustive` rather than `exhastive`.
- Should read `representation` rather than `repesentation`.
- Should read `preferably` rather than `preferrably`.
- Should read `absence` rather than `absense`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

internal/addrs/instance_key.go, internal/addrs/instance_key_test.go
So far we've only ever needed to re-parse address strings that happen not to contain instance keys and so we've gotten away with our serialization of these not being quite right, but given how liberally we've expected to be able to use address strings from this package for wire format interchange it seems likely that this is going to surprise us eventually.
Now we'll use an escaping scheme compatible with HCL's parser rather than Go's parser, and so we can safely rely on hclsyntax.ParseTraversal as part of reversing this operation to transform an address string back into an address equivalent to the value it was created from.
This will cause string keys containing certain control characters to appear a little differently in the UI, but the difference is consistent with our usual …
=> addrs: Format string instance keys in an HCL-compatible way

website/docs/language/settings/terraform-cloud.mdx
There should be a link to the argument being referenced for clarity and completeness.
=> Added link to "hostname" argument

internal/command/init.go, internal/providercache/installer.go, internal/providercache/installer_events.go, internal/providercache/installer_events_test.go, internal/providercache/installer_test.go
This is an attempt to implement @apparentlymart's suggestion in https://github.com/hashicorp/terraform/pull/31399.
I can merge this back into the original PR if we like it.
I also noticed `HashPackageFailure` was not in use so removed it.
=> create installer event for tracking provider lock hashes

internal/backend/remote-state/azure/arm_client.go, internal/backend/remote-state/azure/backend.go, internal/backend/remote-state/azure/backend_test.go, internal/backend/remote-state/azure/client.go, internal/backend/remote-state/azure/helpers_test.go, internal/httpclient/useragent.go, website/docs/language/settings/backends/azurerm.mdx
This PR finishes the migration from ADAL to MSAL for the AzureRM Backend - meaning that Microsoft Graph (and MSAL) are now used by default and Azure Active Directory Graph (and ADAL) are no longer available.
Whilst this is _technically_ a breaking change to the config, this has been called out in the v1.1 and v1.2 releases (and is marked as deprecated in v1.2) - we believe that this shouldn't be impactful to users - and ADAL is scheduled for removal in the near future: https://docs.microsoft.com/graph/migrate-azure-ad-graph-faq
```
$ TF_ACC=1 go test -v ./internal/backend/remote-state/azure/ -timeout=60m
--- PASS: TestBackendConfig (0.00s)
=== RUN   TestAccBackendAccessKeyBasic
--- PASS: …
```
=> backend/azurerm: exclusively using Microsoft Graph/MSAL and removing Azure Active Directory Graph/ADAL

internal/command/show.go, internal/command/show_test.go, internal/command/testdata/show-corrupt-statefile/terraform.tfstate
Fixes https://github.com/hashicorp/terraform/issues/31430.
This fixes a panic caused by passing a `string` to `diags.Append()`.
=> command: fix panic on show when state file is invalid or unavailable

.github/workflows/checks.yml, Makefile, scripts/goimportscheck.sh
A couple of assumptions made here:
- `goimports` is actually the right tool to be using for this.
- We only check the files that were modified in the last commit, this is because a lot of the files in this repository are not valid with our imports schema (they only sometimes separate out github.com/hashicorp/terraform from other third party imports).
- Instead, we could run against against all the files that have diffed from `main`: `git diff --name-only main` (this would mean this check would never work when against the main branch as it will always report no difference).
- Or, we could run against all the files in the repo, and do a single merge that fixes all the current broken files.
Thoughts?
=> Add goimports as a check to the Github commit actions

internal/providercache/installer_test.go
I merged the following three PRs without merging from main between merges:
- https://github.com/hashicorp/terraform/pull/31389
- https://github.com/hashicorp/terraform/pull/31399
- https://github.com/hashicorp/terraform/pull/31408
One of them added a new event type, that then wasn't included in a test from an earlier one.
=> Fix tests failing on main

internal/states/remote/state_test.go
These tests were originally written long before Go supported subtests explicitly, but now that we have t.Run we can avoid the prior problem that one test failing would mask all of the others that followed it.
Now we'll always run all of them, potentially collecting more errors in a single run so we can have more context to debug with and potentially fix them all in a single step rather than one by one.
---
This is just a small papercut I encountered while I was working on #31268. I'm pulling it out into a separate PR because it's independent of what I was working on over there and that PR is already quite cross-cutting so I want to reduce the noise as much as possible.
=> states/remote: use t.Run in table-based tests

internal/dag/dag.go, internal/dag/dag_test.go, internal/refactoring/move_execute.go, internal/refactoring/move_execute_test.go, internal/refactoring/move_statement_test.go, internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go
In order to traverse a graph in "dependency order", meaning all dependencies of a node have been visited before the node itself is visited, you need to first create a topological sort of the graph nodes. Terraform core has always done this,  accomplishing the sort through a parallel walk of all nodes, with each node becoming unblocked as soon as dependencies are satisfied, naturally creating a topological order for the visits. There however was no simple synchronous walk function which provided the same ordering of nodes. This led the refactoring package to erroneously use the only type of synchronous walk available, `ReverseDepthFirstWalk`. Since the majority of move graphs reduce into a simple tree, the depth-first walk appears to be correct at first glance, however if you take a simple …
=> topological sorting for refactoring

internal/dag/dag.go, internal/dag/dag_test.go, internal/refactoring/move_execute.go, internal/refactoring/move_execute_test.go
Manual backport of #31499
The new generics types used in v1.3 preventing directly backporting the refactoring changes, though only the test code had to be manually re-written to match.
=> manual backport of #31499

internal/plans/changes.go, internal/plans/changes_sync.go, internal/terraform/context_apply_test.go, internal/terraform/graph_builder_plan_test.go, internal/terraform/node_output.go, internal/terraform/transform_destroy_edge.go, internal/terraform/transform_destroy_edge_test.go, internal/terraform/transform_output.go, internal/terraform/transform_targets_test.go
We previously had a special case in the graph transformer for output values where it would directly create an individual output value node instead of an "expand" node as we would do for output values in nested modules.
While it's true that we do always know that expanding a root module output value will always produce exactly one instance, treating this case as special creates the risk of those two codepaths diverging in other ways.
Instead, we'll let the expand node also deal with root modules and minimize the special case only to how we look up any changes for the output values, since the design of plans.Changes is a bit awkward and requires us to ask the question differently for root module output values. Otherwise, the behavior will now be consistent across all output values …
=> core: Use DynamicExpand even for root module outputs

internal/command/views/hook_json.go, internal/command/views/hook_ui.go, internal/terraform/context_apply2_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/transform_diff.go, internal/terraform/transform_diff_test.go
Preconditions and postconditions results can change due to changes to other upstream resources, even if the resource they are directly attached to doesn't have a change pending.
Therefore we need to still visit "no-op" resources during the apply walk and deal with the ancillary side-effects, skipping only the actual call to the provider to run `ApplyResourceChange`. If we don't, there can potentially be failures we won't catch until the next plan, which might be run by someone who has no context about whatever change broke the conditions.
This also makes the UI "see" no-op changes being applied via the hooks API. Rather than making another special case in Terraform Core for that, I concluded it's a UI-level concern to decide whether it's interesting to report a particular resource being …
=> Evaluate resource preconditions and postconditions during apply even if they have no planned change

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
Allow the provider to plan any compatible value for computed-only attributes. We currently fail here if there's an apparent config value at this point and the provider set a new computed value. 
We don't need to check the config for null here, because under normal circumstances there should never be a config value for a computed-only attribute in the first place. There however could be 2 reasons we find one at this point:
- A user set `ignore_changes` on a computed attribute and ignored the warning, causing us to insert the prior state value into the plan-time config. This unfortunately is only a warning to prevent breaking configs which are currently working with legacy providers.
- Core currently fails to validate if config attributes are computed, and a provider not using one of the …
=> always allow computed-only changes in the plan

go.mod, go.sum, internal/backend/local/backend_local_test.go, internal/cloud/backend.go, internal/cloud/backend_state_test.go, internal/cloud/state.go, internal/cloud/state_test.go, internal/cloud/testing.go, internal/cloud/tfe_client_mock.go, internal/command/output.go, internal/states/remote/state.go, internal/states/remote/state_test.go, internal/states/state.go, internal/states/statemgr/filesystem.go, internal/states/statemgr/filesystem_test.go, internal/states/statemgr/lock.go, internal/states/statemgr/persistent.go, internal/states/statemgr/statemgr_fake.go, internal/states/statemgr/testing.go
Normally, `terraform output` refreshes and reads the entire state in the command package before pulling output values out of it. This doesn't give Terraform Cloud the opportunity to apply the "read state outputs" org permission and instead requires the elevated "read state versions" permission.
I decided to expand the state manager interface to provide a separate GetRootOutputValues function in order to give the cloud backend a more nuanced opportunity to fetch just the outputs. This required moving state Refresh/Read code that was previously in the command into the shared backend state as well as the filesystem state packages.
Since terraform is now consuming outputs from the API, the API supports a new "detailed-type" output attribute (depending on feature flags) which contains the …
=> `terraform output` should adhere to Terraform Cloud authorization

internal/getproviders/registry_client.go
This is a follow-up PR to https://github.com/hashicorp/terraform/pull/30810 and https://github.com/hashicorp/terraform/pull/29298
They each aimed to add more context to the following error messages:
```
Error while installing citrix/citrixadc v1.13.0: could not query provider
registry for registry.terraform.io/citrix/citrixadc: failed to retrieve
authentication checksums for provider: 403 Forbidden
Error: Failed to install provider
Error while installing 1password/onepassword v1.1.2: could not query provider
registry for registry.terraform.io/1password/onepassword: failed to retrieve
authentication checksums for provider: the request failed after 2 attempts,
please try again later: 500
```
Based on some recent CI runs, it became clear that `Request.Host` may sometimes be empty, which …
=> getproviders: account for occasionally missing `Host` header in errors

internal/providercache/package_install.go
This is motivated by issues of the nature described in https://github.com/hashicorp/terraform/issues/31516 which we also noticed as part of our regular CI runs recently which runs `terraform init` for all ~250 official+verified providers.
https://github.com/hashicorp/terraform-ls/runs/7467545895?check_suite_focus=true#step:6:43
It aims to turn the following error:
> Error while installing bluecatlabs/bluecat v1.0.0: local error: tls: bad record MAC
into 
> Error while installing bluecatlabs/bluecat v1.0.0: github.com: local error: tls: bad record MAC
The aim here is to communicate the fact that (often) such networking issues are between the user and GitHub, rather than the Terraform Registry - and if it is in fact the Registry then should allow us (and the user) to tell the errors apart. …
=> providercache: include host in provider installation error

website/docs/cli/commands/fmt.mdx, website/docs/cli/commands/import.mdx, website/docs/cli/commands/output.mdx, website/docs/cli/commands/providers/schema.mdx, website/docs/cli/commands/state/list.mdx, website/docs/cli/commands/state/show.mdx
`The list of available flags are` does not conform to [subject-verb agreement](https://www.grammarbook.com/grammar/subjectVerbAgree.asp) rules. We may either write: _The list of available flags is_ or _The available flags are_, but not both.
=> fix grammar: subject-verb agreement

website/docs/cli/config/config-file.mdx
Fixes Bug reported in https://github.com/hashicorp/terraform/issues/31442
This PR is a 4th alternate implementation - documentation change to match code behavior.
Use instead if the following PRs are not workable:
* https://github.com/hashicorp/terraform/pull/31456 
* https://github.com/hashicorp/terraform/pull/31452 
* https://github.com/hashicorp/terraform/pull/31443
=> Detailing `-chdir` behavior with `terraform.d/plugin` folders

website/docs/language/expressions/references.mdx
Closes https://github.com/hashicorp/terraform/issues/31441
User has requested that we update [this page](https://www.terraform.io/language/expressions/references#filesystem-and-workspace-info) to call out the "the race conditions and inconsistent behavior that can result from using path.module and local module source for write operations" that Martin described in [this thread](https://github.com/hashicorp/terraform/issues/29503).
This PR adds a few sentences after the `path.module` value to explain this. It also changes * to - for bullets, per our style guide.
=> Add note about module.path and local module sources

scripts/goimportscheck.sh
It's not easy to configure `goimports` with the flags in certain editors, so we can make it easier by keeping the CI check simple.
=> Remove -local flag from goimports check

website/README.md
This Pull Request updates the documentation README to support versioned documentation. Specifically, it explicitly explains how the website generates versioned docs from release branches, and describes the backporting workflow that contributors should follow if they need to edit the latest/past documentation versions. 
This is aligned with our project plan for supporting versioned docs, and we have done similar README updates in other repositories in advance of rolling out versioned docs for that product.
=> Update Docs README to support versioned documentation

website/docs/internals/json-format.mdx
Add `"resource_drift"` and `"relevant_attributes"` to the json plan documentation.
Since a "change-representation" is used for both drift and planned changes, I altered the wording there slightly to make it more generic.
Fixes #31537
=> update json plan docs with drift output

internal/configs/configload/loader_load_test.go, internal/configs/configload/testdata/invalid-names-in-submodules/.terraform/modules/modules.json, internal/configs/configload/testdata/invalid-names-in-submodules/main.tf, internal/configs/configload/testdata/invalid-names-in-submodules/sub/main.tf, internal/configs/provider_validation.go
Fixes #31572
(which triggers the bug)
**`./main.tf`**
```hcl
module "test" {
source = "./sub"
}
```
**`./sub/main.tf`**
```hcl
resource "-test_test" "name" {
}
```
There are also cases which may produce an extra error - assuming that the provider name is also invalid for HCL:
I didn't spend much time on deduplicating it though as I'd expect/hope this is generally an error people will see quite rarely.
I chose to quote the original provider name in the error message, although the other existing diagnostic doesn't do that (uses `%s` instead of `%q`) - let me know if you prefer either. My preference for `%q` was primarily driven by making empty name and other short names with just special characters more visible and obvious.
=> fix: validate implied provider names in submodules

internal/configs/configschema/empty_value.go, internal/configs/configschema/implied_type.go, internal/configs/configschema/internal_validate.go, internal/configs/configschema/validate_traversal.go, internal/configs/configschema/validate_traversal_test.go, internal/plans/objchange/objchange.go
There were a couple locations left which assumed that a schema `Attribute` type was only defined by the `Type` field, which would end up using an invalid `cty.NilType` when `NestedType` was defined. Add `ImpliedType()` to the `Attribute` type which checks for both `Type` and `NestedType` and use it in place of direct `Type` field references.
Leave the `Object.ImpliedType` method for now, since `objchange` does specifically split out the `NestedType` for validation of optional attributes.
Fixes #31527
=> Account for `NestedType` in static traversal validation

internal/configs/configschema/validate_traversal.go, internal/configs/configschema/validate_traversal_test.go
We can't validate if data from deprecated nested attributes is not used in the configuration, but we can at least catch the simple case where a deprecated attribute is referenced directly.
Partial fix for #7569
=> validate deprecated attributes from static traversals

internal/configs/configschema/validate_traversal.go, internal/configs/configschema/validate_traversal_test.go
manual backport of #31576
----
validate deprecated attrs from static traversals
We can't validate that data from deprecated nested attributes is used in
the configuration, but we can at least catch the simple case where a
deprecated attribute is referenced directly.
=> v1.2 backport of 31576

internal/lang/eval.go, internal/terraform/context_validate_test.go
Warnings were dropped from static reference validation if there weren't
also errors in the configuration.
=> don't lose warnings from static validation

internal/command/fmt.go, internal/command/fmt_test.go, website/docs/cli/commands/fmt.mdx
All the code infrastructure was there to support formatting multiple
files already.
This makes `terraform fmt` more flexible and also compliant with the
[treefmt formatted spec](https://numtide.github.io/treefmt/docs/formatters-spec.html)
Fixes https://github.com/numtide/treefmt/issues/97
=> command/fmt: support formatting multiple files

internal/addrs/move_endpoint_module.go, internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go, website/docs/language/modules/develop/refactoring.mdx
Remove validation errors on cross-package move statements.
=> refactoring: allow cross-package move statements

internal/typeexpr/defaults.go, internal/typeexpr/defaults_test.go, website/docs/language/expressions/type-constraints.mdx
Previously, when applying defaults to an input variable's given value before type conversion, we would permit `null` attribute values to override a specified default. This behaviour is inconsistent with the intent of the type system underlying Terraform, and represented a divergence from the treatment of `null` as equivalent to unset which exists in resources. The same behaviour exists in top-level variable definitions with `nullable = false`, and we consider this to be the preferred behaviour here too.
This commit slightly changes default value application such that an explicit `null` attribute value is treated as equivalent to the attribute being missing. Default values for attributes will now replace explicit nulls.
Rendered copy of the docs, which hopefully illustrates why this change …
=> typeexpr: Replace null attr values with defaults

internal/command/e2etest/module_archive_test.go, internal/command/e2etest/testdata/module-archive/main.tf, internal/initwd/module_install.go
At some point Terraform lost the ability to handle the go-getter subdirectory wildcard syntax of `//*`. While the registry no longer uses this type of path to locate module archives, it's still technically valid, and should be possible to use within terraform.
=> Expand module subdirectory globs

CHANGELOG.md, go.mod, go.sum, internal/cloud/backend_common.go, internal/cloud/backend_plan.go, internal/cloud/backend_runTasks.go
Prevously the cloud backend would only render post-plan run tasks. Now
that pre-plan tasks are in beta, this commit updates the plan phase to
render pre-plan run tasks.  This commit also moves some common code to
the common backend as it will be used by other task stages in the
future.
=> Add Pre-Plan Run Tasks to Terraform CLI

website/docs/internals/module-registry-protocol.mdx
Hello ☀️ 
my pull request contains small changes in Module Registry Protocol documentation. I noticed that some places use `provider` and some `system`.
I used `system` to make things more consistent.
=> docs: Use more consistent naming in Module Registry Protocol documentation

.github/workflows/build-Dockerfile
In `actions-docker-build` we [pass](https://github.com/hashicorp/actions-docker-build/blob/05c370a26e61b06be46c5095d6e914c9f0ea4f3d/scripts/docker_build#L49) `PRODUCT_VERSION` to the docker build command. This fixes it to set the label properly with the build-arg which is used in a comparison to determine the `minor-latest` and `latest` docker image tags.
=> set PRODUCT_VERSION for default docker build

website/docs/cli/commands/force-unlock.mdx
The `force-unlock` command does not accept an optional `[DIR]` argument.
=> docs: remove [DIR] from force-unlock docs

website/docs/cli/import/usage.mdx
A user recently pointed out that we make a vague statement about improving a workflow "in the future" on this docs page. Best practices and our style guide dictate that we do not include statements like this in documentation. This PR removes that statement and fixes a few style nits in the surrounding sentences.
=> Remove future-facing statement from import page

internal/lang/funcs/datetime.go, internal/lang/funcs/datetime_test.go, internal/lang/functions.go, internal/lang/functions_test.go, website/data/language-nav-data.json, website/docs/language/functions/timeadd.mdx, website/docs/language/functions/timecmp.mdx
This is a complement to `timestamp` and `timeadd` which allows establishing the ordering of two different timestamps while taking into account their timezone offsets, which isn't otherwise possible using the existing primitives in the Terraform language.
[Documentation Preview](https://terraform-wx68wir4j-hashicorp.vercel.app/language/functions/timecmp)
=> lang/funcs: "timecmp" function

.github/workflows/checks.yml, Makefile, scripts/goimportscheck.sh
The original prompt to start working on this was that the `goimports` check script was generating confusing errors if there were too many files changed in a particular PR.
But while there I also made some other small tweaks in the hope of making these "quick checks" easier to follow in the GitHub Actions logs, since in the common case that's the main place we make use of them.
There are more details about the motivations for these changes in the commit messages of the individual commits, in case you're interested.
=> build: Some small tweaks to the "goimports" check and to how we run these checks in general

internal/command/apply.go
Noticed this was missing when reviewing https://github.com/hashicorp/terraform-exec/pull/292.
=> command: add destroy option to terraform apply help text

internal/addrs/module_source.go, internal/addrs/module_source_test.go
This fixes an issue in the String() for ModuleSourceRemote in which it does not consider query strings (if present). Before this fix, any subdirectory would simply be appended to the ModuleSourceRemote.Package instead of inserting it between the root package and any query parameters.
Related: https://github.com/hashicorp/terraform/issues/31250
=> ModuleSourceRemote String now considers query string (#31250)

website/data/cli-nav-data.json, website/data/internals-nav-data.json, website/data/language-nav-data.json
The Dev Portal UI is showing weird behavior where the divider between the last section in the layout file and the next section is duplicated. I believe that is because the devdot platform automatically adds dividers between sections --> no need to add them manually anymore. This PR removes the duplicate dividers from these  navigation sidebar layout files:
- Language 
- CLI
- Internals
=> Remove Duplicate Divider for DevDot

internal/cloud/state.go, internal/command/command_test.go
Addresses the outstanding comments from my last PR: https://github.com/hashicorp/terraform/pull/31698
I'm not sure if there are any repercussions to removing `EnableForcePush`, but we won't be using it anywhere within State anymore so I removed it, let me know if that needs to be added back in.
=> removes EnableForcePush and other unrelated code

website/docs/language/settings/backends/configuration.mdx
Closes https://github.com/hashicorp/terraform/issues/24510
Users are wondering if we can differentiate between the "state" that gets stored on your local machine for remote backends and the actual state of your real-world infrastructure. This PR clarifies that when you set up a remote backend, Terraform stores the backend configuration in a local directory called `.terraform/terraform.tfstate`. The only content included in this file is the backend configuration, including any credentials you passed to the CLI for the backend. 
We clarify that we do not recommend checking this file into Git, as it may contain sensitive credentials. We also do a couple of fixes for this subsection of the page to better align with our style guide and to make the note about backing up your state before …
=> Add more context about local backend configuration state file

website/docs/language/settings/backends/remote.mdx, website/docs/language/settings/terraform-cloud.mdx
Recently, a customer got confused by this page in the Language documentation: https://www.terraform.io/language/settings/terraform-cloud
They believed it was our only documentation about the new `cloud` block, and reached out to support for help and additional details. They did not know that this documentation existed: https://www.terraform.io/cli/cloud
This PR updates the Terraform Cloud page in the Language docs to hopefully make it clear that it's just a pointer and that the real information is in CLI docs. It also updates a link in the `remote` backends page to point to the CLI docs. I think this will be more helpful for users who want to learn to use the `cloud` block and potentially migrate to it.
=> Update Cloud Block Docs

website/data/language-nav-data.json, website/docs/language/upgrade-guides/1-1.mdx, website/docs/language/upgrade-guides/index.mdx, website/docs/language/v1-compatibility-promises.mdx
See hashicorp/terraform-website#2414 for the bigger picture on what this is all about!
---
Before our website allowed selecting from older versions of Terraform to see older documentation we needed to preserve all of the historical upgrade guides in the latest release branch so that they'd stay available on the website.
However, our new strategy is for each release to have its own separate set of documentation selectable using a global version selector. We should therefore now have only the upgrade guide for the each minor release on its release branch, with the upgrade guides for earlier releases instead maintained on their own branches.
However, our v1.1 branch is, as a matter of pragmatism, serving as the home for the "v1.1 and earlier" documentation, and so there will continue to be …
=> website: Version-specific upgrade guides (v1.1 branch)

internal/configs/named_values.go, internal/configs/testdata/valid-files/object-optional-attrs.tf, internal/terraform/context_apply_test.go, internal/terraform/eval_variable.go
Applying object type defaults to `null` values can convert `null` to an `object` with partial attributes. This means that even a specified default value of `null` will not remain `null` after variable evaluation.
In turn, the result can then be invalid, if not all attributes in an object type have defaults specified.
This commit skips the type default application step during config load and variable evaluation if the default or given value is `null` of any type. We still perform type conversion.
We also add back the configs package test data for the `optional(…)` type modifiers, which were accidentally deleted in a previous PR.
Fixes #31795.
=> Do not apply type defaults to null values

website/docs/language/upgrade-guides/index.mdx
[Rendered Version](https://github.com/hashicorp/terraform/blob/upgrade-guide-v1.3/website/docs/language/upgrade-guides/index.mdx) (see also the Vercel-generated preview below, once it's complete.)
(Note: This PR is intentionally targeting the v1.3 branch directly, because upgrade guides are now release-branch-specific. The equivalent of this page on the `main` branch is a placeholder for the v1.4 upgrade guide which is not yet written.)
=> website: Terraform v1.3 upgrade guide

website/docs/language/settings/backends/configuration.mdx
We've removed the main documentation pages for the backends that are removed in Terraform v1.3, but we'll leave a small callout note so that the backend names are still reachable through our search index once the v1.3 docs are the active version.
The primary goal here is to help folks who have inherited configurations using older versions of Terraform to learn about features they see in those configurations, so the main thing here is the link to the older release docs which include those. However, this is also a good opportunity to link to the upgrade guide content which describes some possible migration paths away from these removed backends.
(This goes along with hashicorp/terraform-website#2342, which puts redirects at the URLs where these backend pages used to be, sending the reader …
=> website: Tombstone callout for the v1.3 removed backends

website/docs/language/expressions/type-constraints.mdx
We have versioned docs now, so we don't need this 🥳
=> Remove unnecessary version note

go.mod, go.sum, internal/terraform/context_apply_test.go
Include the changes to HCL proposed in hashicorp/hcl#555. Includes a context test which crashes before this HCL upgrade.
Fixes #31844
1.3.1
-  Fixed a crash when using objects with optional attributes and default values in collections, most visible with nested modules.
=> Upgrade hcl to fix crash with optional attributes

internal/command/views/apply_test.go, internal/command/views/json/output.go, internal/command/views/json/output_test.go, internal/command/views/json_view.go, internal/command/views/refresh_test.go
1.3.1
* Previously, logs generated from running `terraform apply -json` contained plaintext value of sensitive outputs. With this fix, all sensitive output values will be omitted in the json logs when `terraform apply -json` is run.  To retrieve machine-readable output values, including those which are sensitive use `terraform output -json` instead. ([#31813](https://github.com/hashicorp/terraform/issues/31813))
Currently, sensitive output values are displayed as plain text in the run logs. This PR omits sensitive output values when logging. 
The fix targets both CLI and TFC workflows. In CLI, when running `terraform plan -json` and `terraform apply -json`, sensitive values should be omitted. Similarly, when downloading `raw log` for both plan and apply in TFC, sensitive values should be …
=> redact sensitive output values in run logs

website/docs/cli/workspaces/index.mdx, website/docs/language/state/workspaces.mdx
Update the workspaces documentation in the Language and CLI documentation sets. Specifically this PR makes the following changes:
- Pulls out the majority of the "How workspaces work" content from the language docs and puts it all together in the CLI documentation. I have added links on the language page to the CLI docs where users can find more information. 
- Removes version information about very old Terraform versions from the language documentation. We have versioned docs now, so this seems unnecessary. We're also on Terraform v1.3, which is very far removed from v0.9 that the note is referring to.
- Adds headers to help break up long blocks of content and help users better find useful information. 
- Clarifies when users should and should not use workspaces to manage multiple groups …
=> Update workspace documentation

internal/terraform/context_apply2_test.go, internal/terraform/transform_destroy_edge.go
When adding destroy edges between resources from different providers, and a provider itself depends on the other provider's resources, we can get cycles in the final dependency graph.
The problem is a little deeper than simply not connecting these nodes, since the edges are still needed when doing a full destroy operation. For now we can get by assuming the edges are required, and reverting them only if they result in a cycle. This works because destroy edges are the last edges added to managed resources during graph building.
This was rarely a problem before v1.3, because noop nodes were not added to the apply graph at all, and unused values were aggressively pruned. In v1.3 however all nodes are kept in the graph so that postcondition blocks are always evaluated during apply, increasing …
=> prevent cycles when connecting destroy nodes

internal/terraform/context_plan2_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_destroy_edge.go
We may need to prune nodes from a full destroy plan graph which cannot be evaluated if there is no current state. This is the same method used during apply, however for planning we are only going to encounter evaluation problems during a full destroy, so we can skip the pruning process for normal plans.
Add missing `expandsInstances()` method to `nodeExpandPlannableResource` to ensure planned resources are handled correctly when pruning nodes.
Fixes #31838
=> prune unused nodes from a destroy plan graph

CODEOWNERS
Updates codeowners of the `gcs` backend to @hashicorp/terraform-ecosystem-strategic team because we maintain the Google provider.
The existing code owner @hashicorp/terraform-google is an empty group. We could add everyone to that group, but it made more sense to just change the code owner.
N/A
N/A - not a user-facing change
=> Update codeowner of `gcs` backend to include Strategic Integrations team

internal/providercache/package_install.go
1.4.x
-  providercache: show why a provider couldn't be installed (e.g. lack of permissions)
--- 
On Windows, when Terraform doesn't have `TMP` or other environment variable which would hint where to create temporary files, the stdlib `ioutil.TempDir()` chooses `C:\Windows`. This directory in turn typically requires elevated privileges for writing which common user does not have.
See also https://github.com/hashicorp/terraform-exec/issues/337
```
Error: Failed to install provider
Error while installing hashicorp/local v2.2.3: failed to open temporary file
to download from
https://releases.hashicorp.com/terraform-provider-local/2.2.3/terraform-provider-local_2.2.3_windows_amd64.zip
```
```
Error: Failed to install provider
Error while installing hashicorp/local v2.2.3: failed to open …
```
=> providercache: Improve installation error message

website/docs/language/functions/yamlencode.mdx
We originally included this warning because the go-cty-yaml module wasn't yet stable and it was also not extensively tested so it wasn't yet clear if its behavior would need to change in some less common cases we hadn't tested so far.
However, go-cty-yaml had its v1.0.0 release some time ago and is now committed to preserving its current Marshal output unless it is found to be non-compliant with the YAML 1.2 specification. This doc change means that Terraform's yamlencode is now adopting a similar posture:
- The exact style details produced by the function for a particular input are now frozen. It'll change only if we find that the function is producing output that isn't valid per the YAML spec.
- If someone finds a YAML parser that cannot parse what yamlencode produces but what it …
=> website: Remove warning that yamlencode is experimental

internal/terraform/context_plan2_test.go, internal/terraform/transform_diff.go
If a previously deposed object is deleted outside of Terraform, the next plan will result in a NoOp change for the deposed object.
If that NoOp change was flagged as an update to run any associated condition checks, it would fail the following test to ensure a deposed change is only ever participating in a delete operation. Fix the check to verify that the deposed object has an acceptable action rather than use the `update` flag.
Fixes #31896
=> Prevent errors from NoOp deposed changes

internal/terraform/context_plan_test.go, internal/terraform/node_resource_abstract_instance.go
Legacy providers expect Terraform to be able to clean up invalid plans and altered computed attributes. Add a special case for the LegacyTypeSystem to revert `ignore_changes = all` to the complete prior state, rather than the config value generated by #31747.
Fixes #31912
=> special handling for legacy `ignore_changes = all`

internal/terraform/context_plan2_test.go, internal/terraform/transform_destroy_edge.go
When we checked for cycles with destroy edges around providers, it was only for providers of a different type, but one can do the same thing with the same provider under different local aliases. Check to see if the provider also contains an alias, or is defined absolutely in some other way. The absolute accuracy here isn't critical, since in most cases these edges are not required for correct results, but finding a correct and consistent method for determining when these edges are needed is going to take more research.
There was also an oversight fixed here where the basic creator->destroyer edges were added _after_ the cycle checks, limiting their utility. The ordering of the additions was swapped to make sure all cycles are noticed.
Fixes #31843
=> Extract more exact provider name when checking for destroy cycles

internal/terraform/context_import_test.go, internal/terraform/evaluate.go, internal/terraform/testdata/import-provider-resources/main.tf
Because import does not yet plan new instances as part of the import process, we can end up evaluating references to resources which have no state at all, and the fallback for this situation could result in slightly better values. The count and for_each values were technically incorrect, since the length is not known to be zero, so we return a `DynamicVal` instead. The single instance case does have a concrete type which we can return as an unknown.
This whole process was meant as a step towards a complete import plan, but unfortunately is still contains a few similar edge cases which plagued the original import graph. While these new values will allow more expressions to evaluate correctly (mostly in count/for_each where known-ness is important), there are going to be situations which …
=> evaluation of missing instances during import

.github/workflows/equivalence-test.yml
For more information, see this pull request: https://github.com/hashicorp/terraform/pull/31928
In particular [this comment](https://github.com/hashicorp/terraform/pull/31928#issuecomment-1268135664) discusses moving the equivalence tests into their own action. This PR creates a skeleton of this action that adds the workflow dispatch event. Having this skeleton in place makes it easier to test the new action in development, as Github only registers the workflow dispatch event for an action if it is in the default branch.
More PRs will follow making this action do something interesting.
=> Add skeleton action for executing the new equivalence tests

internal/dag/dag.go, internal/dag/graph.go
When reading this code to check Terraform's graph sorting behavior, I got very confused about the direction of traversal for several methods. Although some of these methods would also probably benefit from renames, this commit only updates their doc comments to use the same directional terminology that we use in the `Edge` interface (source/target).
1.4.x
N/A (only modifies internal comments)
=> Clarify some comments in internal/dag

go.mod, go.sum, internal/cloud/backend_apply.go, internal/cloud/backend_plan.go, internal/cloud/backend_taskStages.go, internal/cloud/backend_taskStages_test.go
This PR:
* Updates the go-tfe library to the latest version (1.10.0). This is needed by later commits for the pre-apply task stage.
* Moves the task stage logic to the backend_taskStages.go file.
* Replaces using an array to a map indexed by the Task Stage's stage. This makes it easier to find the relevant stage in the list and means the getTaskStageIDByName function is no longer required.
* Adds support to display the output of the new pre-apply task stage.
=> Add support for pre-apply task results in the cloud backend

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_apply_instance.go
An orphaned resource which plans as a NoOp change will have no config available during apply. This is not an error, but there is nothing to do since there are also no checks to validate. We still leave the change in the plan to keep the plan as complete as possible, noting all possible changes.
Preventing the node from being added to the graph is awkward, because the config is attached separately from the diff transformer. This should not pose any problems however, because there is no longer any state or config linking the instance to any dependencies in the graph.
Fixes #31850
=> core: A NoOp orphan change has nothing to apply

docs/plugin-protocol/tfplugin5.3.proto, docs/plugin-protocol/tfplugin6.3.proto, internal/tfplugin5/tfplugin5.pb.go, internal/tfplugin6/tfplugin6.pb.go
This opts to inline document these intentional design decisions in the protocol definition as a catch-all for it not being documented elsewhere.
If there is a better place for this documentation, please let me know.
Partially relates to https://github.com/hashicorp/terraform/issues/29568 although I'm not actively working on that particular issue, just trying to capture some recent discussions that occurred out-of-band with GitHub.
None (main branch for additional protocol definition file comments)
None
=> docs/plugin-protocol: Add notes about missing configuration in ReadResource and UpgradeResourceState request messages

internal/terraform/graph.go, internal/terraform/node_local.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_root.go, internal/terraform/transform_root_test.go
The graph walking mechanism is specified as requiring a graph with a single root, which in practice means there's exactly one node in the graph which doesn't have any dependencies.
However, we previously weren't verifying that invariant is true for subgraphs returned from `DynamicExpand`. It was working anyway, but it's not ideal to be relying on a behavior that isn't guaranteed by our underlying infrastructure.
We also previously had the `RootTransformer` being a bit clever and trying to avoid adding a new node if there is already only a single graph with no dependencies. That special case isn't particularly valuable since there's no harm in turning a one-node graph into a two-node graph with an explicit separate root node, and doing that allows us to assume that the root node is always …
=> core: Simplify our idea of "root node" and require it for DynamicExpand

.github/ISSUE_TEMPLATE/documentation_issue.yml
Closes https://github.com/hashicorp/terraform/issues/31552. 
Adds a new issue form type for documentation issues. Format discussed with docs team.
=> Add Documentation Issue form template

go.mod, go.sum
This updates to a newer golang.org/x/net version, addressing CVE-2022-27664 (https://groups.google.com/g/golang-announce/c/x49AQzIVX-s, https://go.dev/issue/54658). This vulnerability is unlikely exposed in Terraform itself (is associated with HTTP/2 server functionality) but will cause vulnerability scan noise.
1.4.x, 1.3.x
-  Updated to newer golang.org/x/net version, which addressed CVE-2022-27664.
=> go get -u golang.org/x/net

go.mod, go.sum
Fixes #31924
1.3.3
-  Fixed setting empty collections into variables with collections of nested objects with default values.
=> Update go-cty to latest version

internal/plans/changes_sync.go, internal/plans/plan.go, internal/terraform/context.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/context_eval_test.go, internal/terraform/context_plan.go, internal/terraform/evaluate.go, internal/terraform/graph.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_eval.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_output.go, internal/terraform/transform_destroy_edge.go, internal/terraform/transform_destroy_edge_test.go, internal/terraform/transform_output.go
This covers a number of various loosely related issues all stemming from the condition checks handling in outputs and NoOp resource nodes:
- Optimally the apply graph operation should not need extra knowledge from how the plan was created, as normal, refresh, or destroy plan. The serialized plan however does not have the information necessary to make this a reality. With the addition of conditions on outputs, output nodes need to be aware of the current phase of operation to know whether to register, evaluate, or ignore the conditions in the config. Resource evaluation also requires knowing if a full destroy in effect to determine how to evaluate resources pending removal in a full destroy when a provider required them for configuration. The existing workaround of checking for only …
=> Clean up handling of check-related graph nodes

website/docs/language/expressions/references.mdx
In Terraform plans, unknown values are displayed as `(known after apply)`. This PR updates the docs to reflect this.
=> docs: fix typo regarding unknown values

website/docs/language/expressions/custom-conditions.mdx
Example was missing a closing bracket
=> Fix can function example

website/docs/language/settings/backends/s3.mdx
The website documentation was missing a permission causing the example to not work. 
This PR aims in fixing that documentation issue.
=> Modifies permissions needed to use s3 with dynamoDb locks

go.mod, go.sum, internal/backend/remote-state/azure/arm_client.go, internal/backend/remote-state/azure/backend.go, website/docs/language/settings/backends/azurerm.mdx
Support for generic OIDC authentication (eg. for Gitlab or Kubernetes) has been added to azurerm provider as well as in the go-azure-helpers already:
https://github.com/hashicorp/terraform-provider-azurerm/issues/16901
https://github.com/hashicorp/go-azure-helpers/blob/main/authentication/auth_method_oidc.go#L41
Currently the remote state backend only supports Github Actions. This pull requests added the support for generic OIDC as in the provider. Also, the documentation has been updated to reflect the usage.
Info: This pull request upgrades the dependency of go-azure-helpers to the latest available version.
Fixes #31802
1.4.x
-  Added support for generic OIDC authentication in azurerm remote state backend (eg. Gitlab or Kubernetes)
=> backend/azurerm: add support for generic OIDC authentication

internal/states/statefile/version4.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_destroy.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/transform_diff.go, internal/terraform/transform_diff_test.go, internal/terraform/transform_reference.go
The handling of conditions during apply can have adverse affects on very large configs, due to the handling of all existing instances even when there are no changes. With extremely large configurations, the execution time can go from a few minutes to many hours only for minor changes.
The first step is to ensure empty `CheckResults` in the state are normalized to prevent the state from being re-written when there are no semantic differences. Empty and nil slices are not handled consistently overall, but we will use an empty slice in the state zero value to match the other top-level structures.
Next we can skip adding NoOp changes to the apply graph when there are no conditions at all to evaluate from the configuration. The nodes themselves can have significant processing overhead when …
=> Apply optimizations for handling of condition checks

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go
This PR closes #23385 [S3 Backend allows key ending with '/'](https://github.com/hashicorp/terraform/issues/23385).
Currently, the core issue is that a bucket 'key' with a trailing slash will be treated as an S3 folder, and while no error is displayed to the user, no `.tfstate` files are uploaded.
The proposed fix is quite simple fix; when instantiating an s3 `Backend` using `New()`, a new check is added, this time for trailing slashes. A relevant testcase has been added as well.
I'm not very familiar with Terraform, so I apologize if I've missed anything obvious.    
If any more actions would be required or recommended, let me know so I can fix it. 😄
=> S3 Backend : Bucket key should not contain trailing slash

go.mod, go.sum, internal/terraform/context_apply_test.go, internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go
Fixes #31978
Currently Terraform attempts to apply defaults in variables before calling go-cty to convert the variables into their actual concrete types. This can lead to a situation where HCL cannot apply the defaults because of a type incompatibility and then panics and crashes Terraform (#31978). It's kind of impossible to recover from or predict this situation without modifying the HCL public functions (eg. make the panic return an error, or add a new function like `CheckCanApplyDefaults`). We can't do this check with go-cty because as far as go-cty is concerned these are perfectly valid conversions. Note, that HCL and go-cty disagree here about what is or what isn't a valid type conversion.
This PR switches the order of these operations. We now go through go-cty to convert to the …
=> Convert variable types before applying defaults

internal/terraform/context_refresh_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
When executing a refresh-only plan, it is not valid to plan a data source read. If the data source config is not known during planning, the only valid update would be the prior state, if there is any.
Fixes #29070
=> don't plan data source reads during refresh-only

internal/terraform/context_apply.go
If there are no changes in a given plan, then there is no reason to create and walk a full apply graph since all objects are known. This means that an apply operation of a refresh plan should only entail returning the planned state. 
We however do still need the walk to apply output changes which are recorded in the plan, and some vestigial cleanup is done during the apply walk. In the future, copying the planned output values and cleaning up the state could be done outside the walk, but we will leave that for later pending investigation into any other unexpected side effects it may cause.
For now to ensure refreshed checks are stored correctly, copy the planned checks into the final state after the apply walk.
=> don't lose checks from refresh-only plan

internal/command/console_test.go, internal/command/format/diff.go, internal/command/format/diff_test.go, internal/repl/format.go, internal/repl/format_test.go, website/docs/language/expressions/function-calls.mdx, website/docs/language/expressions/references.mdx, website/docs/language/functions/nonsensitive.mdx, website/docs/language/functions/sensitive.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Fixes several bugs in the plan diff rendering of nested attributes 
- When a schema attribute is sensitive, but also contains nested attributes, terraform reveals the nested attributes. The renderer checks for sensitive _values_ at this nesting level, but ignores sensitive _schema_.
- There is a mixture of "(sensitive)" and "(sensitive value)" output in the plan diff and I changed them all to "(sensitive value)"
- Certain nested attribute modes don't output consistent new values for delete plans or unknown values
I also added a lot more test coverage for single nested attribute mode and sensitive schema nested attributes
<details>
<summary>Sample Config</summary>
```hcl
terraform {
nested = {
source = "alisdair/nested"
}
}
}
resource "nested_single" "example" {
name = …
```
=> fix: don't reveal nested attributes with sensitive schema

internal/command/e2etest/testdata/plugin-cache/.terraform.lock.hcl, internal/providercache/installer.go, internal/providercache/installer_test.go, internal/providercache/package_install.go, internal/providercache/testdata/beep-provider-other-platform/terraform-provider-beep
When we originally introduced the trust-on-first-use checksum locking mechanism in v0.14, we had to make some tricky decisions about how it should interact with the pre-existing optional read-through global cache of provider packages:
The global cache conflicts with the checksum locking because if the needed provider is already in the cache then Terraform skips installing the provider from upstream and therefore misses the opportunity to capture the signed checksums published by the provider developer. We can't use the signed checksums to verify a cache entry because the origin registry protocol is still using the legacy ziphash scheme and that is only usable for the original zipped provider packages and not for the unpacked-layout cache directory. Therefore we decided to prioritize the …
=> providercache: Ignore lock-mismatching global cache entries

website/docs/internals/provider-registry-protocol.mdx
Add a short summary of the `shasum` property in the Provider Registry Protocol's distribution package response documentation. The Response Properties section of the provider registry protocol does not mention the `shasum` property, but it is required and shown in the example.
1.4.x
-  Added a description of the `shasum` object property to the registry protocol's documentation. This property is a required part of the response, but it was previously shown in the example response only without a corresponding reference.
=> Document provider registry response property shasum

website/docs/cli/commands/state/show.mdx
The `terraform state show` command doesn't normally need quotes around the resource name to return information. But when querying resources that have been created by the use of `for_each` - which creates resource identifiers such as ` module.thing[\"item\"]` - the command fails to find the the resource. The documentation does show the use of single quotes but this can be easily missed when reading the documentation. 
I would be nice to have this highlighted a bit more as this is very subtle and can be missed when you are used to the command working without wrapping single quotes. 
Also, I haven't found a way to show these resources with the `terraform console` yet either.
=> Additional note on usage of single quotes for for_each resources

go.mod, go.sum, internal/terraform/eval_variable_test.go
- Updates HCL
- Updates go-cty 
- Add test cases that verify all the below issues are fixed
- Fixes https://github.com/hashicorp/terraform/issues/32157 (Fixed by https://github.com/hashicorp/hcl/pull/567)
- Fixes https://github.com/hashicorp/terraform/issues/32152  (Fixed by https://github.com/zclconf/go-cty/pull/143)
- Fixes https://github.com/hashicorp/terraform/issues/32160 (Fixed by https://github.com/hashicorp/hcl/pull/567)
- Fixes https://github.com/hashicorp/terraform/issues/32109 (Fixed by https://github.com/zclconf/go-cty/pull/144)
1.3.5
- Fix Terraform creating objects that should not exist in variables that specify default attributes in optional objects.
- Fix several Terraform crashes that are caused by HCL creating objects that should not exist in variables that specify …
=> Update HCL and go-cty to fix optional and default attributes 

docs/unicode.md
I missed this on my first attempt to write this document. Consequently we're currently depending on a version of HCL which uses Unicode 9, and that's significantly lagging behind everything else which is currently on Unicode 13.
My goal of adding these docs then is to remind us to update HCL to Unicode 15 once we're updating everything else to Unicode 15 with the Go 1.20 release, assuming that the Go team completes that Unicode upgrade as currently planned (golang/go#55079).
=> docs: "How Terraform Uses Unicode" should mention HCL too

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go
In order to complete the terraform destroy command, a refresh must first be done to update state and remove any instances which have already been deleted externally. This was being done with a refresh plan, which will avoid any condition evaluations and avoid planning new instances. That however can fail due to invalid references from resources that are already missing from the state.
A new plan type to handle the concept of the pre-destroy-refresh is needed here, which should probably be incorporated directly into the destroy plan, just like the original refresh walk was incorporated into the normal planning process. That however is major refactoring that is not appropriate for a patch release.
Instead we make two discrete changes here to prevent blocking a destroy plan. The first is to …
=> Make the pre-destroy refresh a full plan

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
Some prior refactors left the `destroyPlan` method a bit confusing, and ran into a case where the previous run state could be returned as `nil`. Get rid of the no longer used `pendingPlan` value, and track the prior and prev states directly, making sure we always have a value for both.
Fixes #32186
=> Ensure destroy plan contains valid state values

website/docs/language/state/backends.mdx
=> Added a missing comma on backends.mdx

website/docs/cli/install/apt.mdx, website/docs/cli/install/yum.mdx
Distro lists were out-of-date, just bringing them into sync with:
https://github.com/hashicorp/linux-packaging#current-support
=> Updating distro lists to be current as of 2022-11

CHANGELOG.md, go.mod, go.sum, internal/backend/backend.go, internal/backend/local/backend.go, internal/backend/local/backend_local_test.go, internal/backend/local/backend_test.go, internal/backend/local/testing.go, internal/backend/remote-state/azure/backend_state.go, internal/backend/remote-state/consul/backend_state.go, internal/backend/remote-state/cos/backend_state.go, internal/backend/remote-state/gcs/backend_state.go, internal/backend/remote-state/http/backend.go, internal/backend/remote-state/inmem/backend.go, internal/backend/remote-state/kubernetes/backend_state.go, internal/backend/remote-state/oss/backend_state.go, internal/backend/remote-state/pg/backend_state.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/backend/testing.go, internal/builtin/providers/terraform/data_source_state_test.go, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/state.go, internal/cloud/state_test.go, internal/cloud/tfe_client_mock.go, internal/command/workspace_delete.go
Updates the cloud backend to call either workspace safe-delete or workspace force-delete 
These are new concepts to the Terraform Cloud workspace deletion APIs ([proposed documentation here](https://github.com/hashicorp/terraform-docs-common/pull/146)). Workspace safe delete will only remove a workspace if it does not have resources under management, to help prevent users from accidentally leaving managed resources orphaned from Terraform.
If a CLI user does not pass the `-force` option to `terraform workspace delete`, the cloud backend will attempt to use the new workspace safe-delete API (if we can detect that the TFC/E version contains this API). Otherwise it will continue using the existing API, which functions as a force delete.
The CLI [already has this …
=> Use safe or force workspace delete for cloud backend

internal/backend/remote-state/gcs/backend.go, internal/cloud/backend_plan.go, internal/e2e/e2e.go, internal/plugin6/convert/schema.go
Fixes #
1.3.x
-  BUG FIXES: fix pre allocate for composite literal
=> fix: pre allocate for composite literal

internal/terraform/node_resource_plan_orphan.go, internal/terraform/node_resource_plan_orphan_test.go
If when refreshing an orphaned instance the provider indicates it has already been deleted, there is no reason to create a change for that instance. A NoOp change should only represent an object that exists and is not changing.
This was likely left in before to try and provide a record of the change for external consumers of the plan, but newer plans also contain all changes made outside of Terraform which better accounts for the difference. The NoOp change now can cause problems if the change is from null to null, because it may represent an instance with conditions to check even though that instance does not exist.
Fixes #32235
=> A deleted orphan should have no planned change

internal/terraform/graph_builder_apply.go, internal/terraform/transform_destroy_edge.go
In a heavily-connected graph with lots of inter-dependent providers, the cycle checks for destroy edges across providers can seriously impact performance. Since the specific cases we need to avoid will involve create/update nodes, skip the extra checks during a full destroy operation. Once we find a way to better handle these dependencies*, the transformer will not need to do the complete cycle checks in the first place.
While probably not a complete solution to the increased plan+apply overhead, this should help recover some of the performance loss seen in #32234
\* tracking the dependencies may not be reasonable, and a simple "reachability" method for the graph may be all we need.
=> check walkDestroy to help DestroyEdgeTransformer

internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_abstract_instance_test.go, internal/terraform/node_resource_abstract_test.go
Once the ProviderTransformer has resolved and set the exact provider, the ProvidedBy method should return that exact provider again. This was not affecting the actual execution of the nodes because the `ResolvedProvider` field was being accessed directly, but could cause graph processing to proceed incorrectly when a `GraphNodeProviderConsumer` reported an incorrect provider address.
On top of checking `ResolvedProvider` first, we can also hoist the stored provider addr into the `AbstractInstance` and avoid the method duplication and slight differences between the implementations.
=> ProvidedBy should return the resolved provider

internal/command/workspace_delete.go, website/docs/cli/commands/workspace/delete.mdx
In terraform cloud we are adding some guardrails to help prevent users from accidentally deleting workspaces with resources under management (RUM).
The Terraform CLI already attempts to prevent the user from deleting workspaces with RUM, and requires the `-force` flag to remove a workspace with RUM. The docs + help text around this refer to workspaces which are dangerous to delete as "workspaces with non-empty state".
In order to bring the CLI experience up to date with the TFC/E experience, and standardize on an industry term rather than something terraform specific, this updates the docs/help to refer to "resources under management" instead.
Proposed doc change [here](https://github.com/hashicorp/terraform-docs-common/pull/146) and some changes to the CLI to utilize the Terraform Cloud …
=> Update workspace delete command docs to reference RUM vs empty state

go.mod, go.sum, internal/lang/functions_test.go
This includes the fix for a bug in what Terraform calls the "yamldecode" function, where it was not correctly handling any situation where the decode result is a null value. It was previously returning an unknown value in that case, whereas now it returns a null value as expected.
Fixes #31188.
=> go get github.com/zclconf/go-cty-yaml@v1.0.3

internal/terraform/node_output.go
When output values are updated in the refreshed state, we don't need to re-set the changes which were already set in conjunction with the current state. 
This is just a small change pulled for backport from the larger #32251 change set addressing output evaluation overall.
Helps address #32251 by not overwriting the change entry for every single output.
=> don't re-set changes for refreshed outputs

.github/workflows/equivalence-test.yml
*No changes to Terraform proper*
This does a small refactoring of the Terraform Equivalence Tests. They retrieve the metadata.json file from the Build job and use that to deduce the version and correct branch, instead of requiring this information as an input.
Also: 
- update the Terraform Equivalence Testing Framework version so it removes some more unwanted fields.
- remove and update deprecated set-output approach
=> Update Terraform equivalence tests to remove unneeded input.

internal/backend/remote-state/oss/backend.go, internal/backend/remote-state/oss/client.go
This PR aims to fix getting oss endpoint error caused by network connection failed and other reasons. This error will break oss backend process. Considering all of oss endpoints have followed up pattern `oss-<RegionId>.aliyuncs.com`, above error can be ignored.
Fixes #
1.4.x
-  backend/oss: Ignore the getting oss endpoint error and using string concat instead; Improves the error message level
=> backend/oss: Ignore the getting oss endpoint error and using string concat instead; Improves the error message level

internal/builtin/providers/terraform/provider.go, internal/builtin/providers/terraform/resource_data.go, internal/builtin/providers/terraform/resource_data_test.go, internal/command/e2etest/terraform_test.go, internal/command/e2etest/testdata/terraform-managed-data/main.tf
Add a new managed resource, `terraform_data`, which incorporates and enhances the functionality of `null_resource`, making use of features not available through the legacy SDK.
This new resource has 4 attributes:
- `id`: A unique computed string.
- `triggers_replace`: A value of any type which will trigger replacement when changed.
- `input`: A value of any type, which will be reflected in `output` after apply.
- `output`:  Computed from the `input` value, which during plan will be unknown of the same type as `input`, and identical to `input` after apply.
This gives us a built-in replacement for `null_resource`, while adding some key new features; the ability to store and reference data of any arbitrary type, and create unknown values during plan via the input and output attributes. …
=> New `terraform_data` managed resource to replace `null_resource`

internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/prerelease-version-constraint-match/root.tf, internal/initwd/testdata/prerelease-version-constraint/root.tf
Update the module constraint checking logic to use the apparentlymart/go-versions library instead of the hashicorp/go-versions library. This copies the logic of the provider installer which relies entirely on the apparentlymart implementation.
A further PR could look into completely stripping out the old version with the new version for all version processing (not just constraint checking). This is a lot of work though, so this PR could be viewed as a first step in that direction, or maybe we should decide that we should fix this only with a bigger migration and I can close this PR?
Fixes #32356 
1.3.6
-  Fix exact version constraint parsing for modules using prerelease versions.
=> Use the apparentlymart/go-versions library to parse module constraints

internal/command/workspace_command.go
The Terraform workspace command will return a 0 return code even when invalid arguments are passed to the command.
For example, `terraform workspace seleect` will return a 0 (non-error) return code even though it's an invalid command. This PR updates the Run method to fall in line with other terraform commands and returns a proper non-zero return code when an invalid argument is passed to `terraform workspace`.
```bash
➜  linux_amd64 git:(twittyc/terraformWorkspaceInvalidArgsReturnsNon0) terraform workspace seleect
Usage: terraform [global options] workspace
new, list, show, select and delete Terraform workspaces.
➜  linux_amd64 git:(twittyc/terraformWorkspaceInvalidArgsReturnsNon0) echo $?
0
```
This fix updates the return code to properly give an error
``` bash
➜  linux_amd64 …
```
=> Bug fix: Terraform workspace command returns zero exit code when given an invalid argument.

internal/command/workspace_command.go, internal/command/workspace_command_test.go, internal/command/workspace_select.go
This adds the new terraform workspace select flag `-or-create`. This flag is intended to make managing workspaces easier in CI environments where auto creating or selecting a workspace is useful (especially when using remote backend). This flag will first attempt to select the provided workspace name. If this workspace is not found, it will then create and select it. 
Traditionally this functionality has been achieved through some sort of scripting. We currently get this behavior using the following script: `terraform workspace select test || terraform workspace new test`; however, this does not work well when attempting to use the official terraform docker image as it does not handle shell scripts by design. Having this functionality in the terraform cli itself would be very useful. We …
=> New Terraform Workspace select flag: `-or-create`

website/docs/cli/install/apt.mdx
I tested both jammy and kinetic in docker and both of them have terraform packages. It's pretty bad that the list isn't updated because I almost did a bunch of unnecessary work because of it. And the person in #31826 was given bad advice since the packages were already published at that time (judging by #30974 which was opened earlier). You folks don't know what packages you publish yourselves?
Fixes #31826
Related: #30974
N/A
N/A
=> website: add missing Ubuntu apt repositories jammy and kinetic to the list

internal/command/plan_test.go, internal/terraform/context_refresh_test.go, internal/terraform/node_resource_abstract_instance.go
Legacy providers may return null values for nested blocks during refresh. Because the ReadResource call needs to accept any value to allow the provider to report external changes, we allowed all changes to the value as long as the underlying cty.Type was correct, allowing null block values to be inserted into the state.
While technically invalid, we needed to accept these null values for compatibility, and they were mostly seen as a nuisance, causing noise in external changes and plan output. These null block values however can be inserted into the effective configuration with the use of `ignore_changes`, which can cause problems where the configuration is assumed to be completely valid.
Rather than accept the null values, we can insert empty container values for these blocks when …
=> fix invalid null blocks during refresh

website/docs/language/modules/develop/composition.mdx
Tiny documentation fix: A block of HCL was missing syntax highlighting on the "Best Practices: Module Composition" page.
=> Add missing HCL syntax highlighting in `composition.mdx`

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
Using ignore_changes with a list block, where the provider returned an invalid null value for that block, can result in a panic when validating the plan.
Future releases may prevent providers from storing a null block in state, however we can avoid the panic for now. Only the NestingList case needs to be handled, because legacy providers only have list and set blocks, and the set case does not use the config value.
The null case should be avoided entirely by #32424, but this is a minimal backport to patch a crash in the current minor release, and handle pre-existing state with null values.
Fixes #31536
=> don't panic with a null list block value in config

internal/backend/remote-state/oss/backend.go
This should fix the code consistency check on the v1.3 branch.
We still need to tweak goimportscheck.sh so that it correctly sets the base branch when run on a non-main branch.
=> ci: goimports fix

internal/terraform/context_apply2_test.go, internal/terraform/node_output.go
Output references from `error_message` were not being tracked. Also fix the early return in `referencesForOutput`, which could skip preconditions altogether. The small slice allocation optimization is not really needed here, since this is not a hot path at all.
Fixes #32447
=> Ensure we have all references for output preconditions

internal/command/jsonformat/README.md, internal/command/jsonformat/change/change.go, internal/command/jsonformat/change/renderer.go, internal/command/jsonformat/differ/attribute.go, internal/command/jsonformat/differ/block.go, internal/command/jsonformat/differ/output.go, internal/command/jsonformat/differ/value.go, internal/command/jsonformat/renderer.go, internal/command/jsonplan/plan.go, internal/command/jsonplan/resource.go, internal/command/jsonprovider/attribute.go, internal/command/jsonprovider/attribute_test.go, internal/command/jsonprovider/block.go, internal/command/jsonprovider/block_test.go, internal/command/jsonprovider/provider.go, internal/command/jsonprovider/provider_test.go, internal/command/jsonprovider/schema.go, internal/command/jsonprovider/schema_test.go
This change is part of a series of changes that will create a new plan renderer that consumes the JSON structured output produced by the `-json` flag.
This change adds a basic outline of the new approach by creating structs and empty functions. 
The changes are broken up into a series of PRs that each focus on one part of the renderer to make reviewing easy. This does mean that the order matters, so you should review the PRs in the order listed below. If you prefer to view all the changes in a single (very) big PR, then skip to the last one and change it so it diffs against the main branch instead of the last PR in the chain.
The new renderer has a single entry class: `jsonformat/renderer.go`. It then makes use of two inner packages: `differ` and `change`. The `differ` package converts a …
=> Add skeleton functions and API for refactored renderer

internal/command/jsonformat/change/block.go, internal/command/jsonformat/change/change.go, internal/command/jsonformat/change/object.go, internal/command/jsonformat/change/renderer_test.go, internal/command/jsonformat/differ/tuple.go
This PR adds functionality so that keys of objects and blocks that fail the HCL syntax check will be rendered within quotation marks.
This matches the checks and behaviour of the old renderer.
=> Structured Plan Renderer: Escape object and block keys that don't match HCL syntax

internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
NestingSingle blocks removed from from the config were causing a plan to error out with "... planned for existence but config wants absence". Terraform core was proposing an incorrect value in this case, taking the prior instead as a fallback because a null value was not expected.
Unlike other collection nesting modes, a NestingSingle block not present in the configuration is a null value, and should be allowed when planning a new value rather than building an empty object or falling back to the prior value.
Fixes #32460
=> NestingSingle blocks can be null

internal/command/jsonformat/computed/diff.go, internal/command/jsonformat/computed/renderers/block.go, internal/command/jsonformat/computed/renderers/list.go, internal/command/jsonformat/computed/renderers/map.go, internal/command/jsonformat/computed/renderers/object.go, internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/sensitive.go, internal/command/jsonformat/computed/renderers/sensitive_block.go, internal/command/jsonformat/computed/renderers/set.go, internal/command/jsonformat/computed/renderers/string.go, internal/command/jsonformat/computed/renderers/type_change.go, internal/command/jsonformat/computed/renderers/util.go
Refactor the human renderer functions to require a colorize object as part of their options.
This means that we now perform the colorize operation on localized strings instead of a single mass colorize once at the end of the rendering process.
=> Structured Plan Renderer: Push the colorize actions as locally as possible

internal/command/jsonplan/plan.go, internal/command/jsonplan/plan_test.go
These outputs are already removed from the internal plan when it is saved to disk, but now we are starting to read from the jsonplan in memory so we just need to another check of this directly in the marshaller.
=> Remove outputs from the jsonplan that are not from the root module

internal/builtin/providers/terraform/resource_data.go, internal/builtin/providers/terraform/resource_data_test.go
The configuration may be supplying a typed null value to the terraform_data.input attribute, which must be reflected in the output to have a valid plan. This wouldn't fail on an initial plan, but if an earlier plan contains an unknown input, then we need to match the resulting type of that prior plan.
=> typed null input should be reflected in output

internal/lang/funcs/descriptions.go, internal/lang/functions.go, internal/lang/functions_descriptions_test.go
This PR adds descriptions for all Terraform functions and is the first step in enabling machine-readable function signatures (more: [TF-508: Machine-readable function signatures](https://docs.google.com/document/d/10H00gyk__iKaxRLquHHLpg7Cg5Tx9IfEZ2tV9rfO_ac/edit)).
It is planned to export the descriptions via a new `terraform metadata functions --json` command. The first consumer of the JSON output will be the Terraform language server, to provide function signature information inside the editor. After that, the docs website might be another potential consumer, making the description list the single source of truth.
Instead of iterating over the functions list and using `WithDescription` for each one, I've [another approach](https://github.com/hashicorp/terraform/compare/main...dbanck:ter …
=> Add function descriptions

internal/command/jsonformat/computed/renderers/map.go, internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/diff.go, internal/command/jsonformat/renderer.go
This adds some more minor fixes to the structured plan renderer to keep changes to a minimum.
- fixes rendering large numbers by formatting them with the correct precision
- nested maps do not align their keys
- add missing new lines when rendering drift changes explanation
- only print the resource changes header if we have actual changes (ie. not just things being moved in the state)
- fix the ordering of resources within the plan, sort by module and mode before simple address
=> Structured Plan Renderer: another round of fixes after more equivalence testing

testing/equivalence-tests/outputs/data_read/plan, testing/equivalence-tests/outputs/drift_relevant_attributes/plan, testing/equivalence-tests/outputs/drift_relevant_attributes/plan.json, testing/equivalence-tests/outputs/drift_relevant_attributes/state.json, testing/equivalence-tests/tests/drift_relevant_attributes/terraform.resource/f6f74ca6-e8ef-e51f-522c-433b9ed5038f.json
the data read and drift plans have outputs that were produced by an incomplete renderer version, I didn't notice this until after I merged so this PR brings them up to speed.
=> fix the outputs of equivalence tests that were executed with the wrong version

internal/configs/configschema/marks.go
Go's `append()` reserves the right to mutate its primary argument in-place, and expects the caller to assign its return value to the same variable that was passed as the primary argument. Due to what was almost definitely a typo (followed by copy-paste mishap), the configschema `Block.ValueMarks` and `Object.ValueMarks` functions were treating it like an immutable function that returns a new slice.
In rare and hard-to-reproduce cases, this was causing bizarre malfunctions when marking sensitive schema attributes in deeply-nested block structures -- omitting the marks for some sensitive values (🚨), and marking other entire blocks as sensitive (which is supposed to be impossible). The chaotic and unreliable nature of the bugs is likely related to `append()`'s automatic slice reallocation …
=> Fix accidental mutation of shared `cty.Path`s in ValueMarks funcs

internal/configs/configschema/marks.go
This is a backport of #32543. (A manual one — forgot to add the label before merging.) 
----
Go's `append()` reserves the right to mutate its primary argument in-place, and expects the caller to assign its return value to the same variable that was passed as the primary argument. Due to what was almost definitely a typo (followed by copy-paste mishap), the configschema `Block.ValueMarks` and `Object.ValueMarks` functions were treating it like an immutable function that returns a new slice.
In rare and hard-to-reproduce cases, this was causing bizarre malfunctions when marking sensitive schema attributes in deeply-nested block structures -- omitting the marks for some sensitive values (🚨), and marking other entire blocks as sensitive (which is supposed to be impossible). The chaotic and …
=> [backport] Fix accidental mutation of shared `cty.Path`s in ValueMarks funcs

internal/cloud/backend_test.go
This was clearly wrong, but it was also harmless -- in the event of a failing test due to missing tags, they would get double-reported as both missing and unexpected. This commit separates out the reporting as intended.
1.4.x
-  none; it's a test-only fix.
=> Fix typo in cloud backend's `TestCloud_setConfigurationFields`

website/docs/language/functions/setproduct.mdx
This changes fixes a spelling error found on the `setproduct` function documentation page.
In `website/docs/language/functions/setproduct.mdx`, a misspelled word `nework_subnets` has been corrected to `network_subnets`, following a similar spelling within the same file and [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/network).
Below is a screenshot showing the location of the misspelled word within the project's documentation:
=> Fix the spelling of network within the setproducts function documentation.

website/docs/cli/install/apt.mdx
All instructions are available at https://www.hashicorp.com/official-packaging-guide. To avoid needing to update the key fingerprint in a million places, we are removing these static references and instead pointing users to the official guide which will always be kept up-to-date.
Relates to https://status.hashicorp.com/incidents/fgkyvr1kwpdh, https://status.hashicorp.com/incidents/k8jphcczkdkn and will close [#32565](https://github.com/hashicorp/terraform/issues/32565) (as all other docs sites have been updated)
=> Remove references to old linux signing key

commands.go, internal/command/cliconfig/cliconfig.go, internal/command/meta.go, internal/command/meta_providers.go, internal/providercache/installer.go, internal/providercache/installer_test.go, website/docs/cli/config/config-file.mdx
Currently Terraform will use an entry from the global plugin cache only if it matches a checksum already recorded in the dependency lock file. This allows Terraform to produce a complete lock file entry on the first encounter with a new provider, whereas using the cache in that case would cause the lock file to only cover the single package in the cache and thereefore be unusable on any other operating system or CPU architecture.
This temporary CLI config option is a pragmatic exception to support those who cannot currently correctly use the dependency lock file but who still want to benefit from the plugin cache. With this setting enabled, Terraform has permission to produce a dependency lock file that is only suitable for the current system if that would allow use of an existing entry …
=> cliconfig: Allow forcing use of the plugin cache despite the lock file

internal/builtin/provisioners/local-exec/resource_provisioner.go
Added Quiet value in order to quiet the output from local-exec
Fixes #32097 
1.4.x
-
=> Added Quiet value

internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
When structural attributes were added, optional+computed attributes were not correctly handled when they contain nested values which could themselves be computed. This would cause terraform to ignore previously computed values from state when generating the proposed plan. The special case for optional+computed was incorrect, but isn't needed in the context of planning new values anyway -- attributes are either computed, or not computed depending on the existence of a configuration value. It is up to the provider to determine how and when to deal with any changes to that computed value.
We can also combine and simplify the set comparison functions for NestingSet blocks and attribute types. The set handling was not recursing into nested values, and once a simplified method for comparing set …
=> Plan correct optional and computed attributes in nested objects and sets

internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
In the common cases we cannot determine if a null optional+computed value in the configuration was previously set when the value also exists in the state. There is however one situation where we can determine if there was previously a configuration value, we can check if a complex object in state must have at least partially come from configuration by seeing if the prior value has any non-null attributes which are not computed in the schema.
=> better determine when to plan optional+computed

internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
We could panic in many situations when nulls crop up in `NestingBlock`values. Fix the test cases and start refactoring best we can. This probably won't go so far as making all the objchange functions generic over Block and Object, but we can simplify a lot and verify parity in implementations, and avoid other problems with `cty.NilVal` and empty maps.
=> Fix crashes with NestingMap values

internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go
The existing `ProposedNew` set comparison method uses the prior elements with the computed portions nulled out to find candidates to match the configuration. This has the shortcoming of always removing optional+computed attributes, because we have not yet found the configuration to know if attribute was set or not.
Rather than having to take the most pessimistic value before comparison to precompute the nulled values, we can compare each candidate config and prior pair directly, walking the values in tandem. Each prior value is compared against the config and checked to see if it could have been derived from that configuration value, which allows us to treat optional+computed as optional if there is config and computed if there is not.
This removes the ambiguity from having …
=> a new method of `ProposedNew` set comparison

website/docs/language/settings/backends/http.mdx
Update the HTTP backend docs page with the new attributes added in https://github.com/hashicorp/terraform/pull/31699.
=> docs: add HTTP backend mTLS attributes

internal/terraform/context_apply2_test.go, internal/terraform/node_output.go
Although they are not serialized to the final stored state, all module outputs must be saved in the state for evaluation. There is no defined schema which is used to identify the overall type of module outputs, so all outputs must exist in the state to build the correct type for proper evaluation.
A corresponding change will be backported to v1.3 manually, since this commit overlaps with conflicting changes in `main`.
=> save null module outputs in state

internal/terraform/context_apply2_test.go, internal/terraform/node_output.go
Although they are not serialized to the final stored state, all module outputs must be saved in the state for evaluation. There is no defined schema which is used to identify the overall type of module outputs, so all outputs must exist in the state to build the correct type for proper evaluation.
Manual backport of #32583
=> v1.3 backport: save null module outputs in state

go.mod, go.sum, internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go
- Update to latest version of HCL, with flexible defaults package.
- Add test case that demonstrates failure of conversion before defaults with `any` type constraint.
- Apply defaults before conversion, in line with new HCL version.
Fixes #32396 
1.3.8 / 1.3.9 / 1.4.0
-  Fix terraform crash when applying defaults into a collection with dynamic type constraint.
=> Reverse the order of conversion/defaults, and update HCL with more flexible defaults package

go.mod, go.sum, internal/cloud/backend.go, internal/command/init.go, internal/command/meta_config.go
For a while, [Terraform Enterprise has supported](https://developer.hashicorp.com/terraform/cloud-docs/registry/using#generic-hostname-terraform-enterprise) `localterraform.com` as a generic alias for "whatever the platform hostname is" in order to allow developers to omit specific module source URLs when utilizing multiple Terraform Enterprise deployments.
This change extends support to Terraform CLI by aliasing `localterraform.com` during cloud configuration to be whatever the cloud hostname is, utilizing aliasing within service discovery. This allows module developers in particular to use the CLI to reference module sources in the same way the platform will without modifying hosts files or adding undocumented CLI config workarounds like `host{}` and `credentials{}` blocks.
To simplify …
=> Add support for Terraform Enterprise generic hostname localterraform.com

CHANGELOG.md, internal/backend/remote/backend.go, internal/cloud/backend.go
Duplicates generic hostname enhancement to backend/remote. We don't have a history of sharing code between the cloud and remote backends and this was a very small change so I basically duplicated #32571 
My thinking is that this enhancement falls close to being a bug fix so it might not be worthwhile to insist on a migration to cloud backend to get it. I'm open to either a different implementation that shares code or not backporting it at all.
1.4.0
=> Backport support for generic hostname to backend/remote

internal/backend/local/backend_local.go, internal/states/remote/state.go, internal/states/remote/state_test.go
This fixes #30670, which is due to how the remote state functionality previously had slightly different logic for the initial serial number of state. The local backend always generated initial state with a serial of `> 0`, whereas remote state would generate it with a serial of `0`. When combined with certain conditions (such as the one laid out in the referenced issue), this could result in Terraform over-writing remote state with stale state from a `plan` file and not throwing the expected `The given plan file can no longer be applied because the state was changed` error.
To support this change I also had to refactor the way in which the tests for the affected method were written, since previously the tests assumed one request per test case. I think I did this in a fairly idiomatic way …
=> make remote state initial behavior the same as local state

internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go
I made a PR to add rendering the state to the equivalence tests (https://github.com/hashicorp/terraform-equivalence-testing/pull/17), and in doing so spotted that the closing json bracket when rendering json strings was indented improperly when rendering without symbols.
This PR fixes that by rendering the indents on the final line for JSON strings properly, that is considering that the symbol width and the indent length are not necessarily the same and now rendering the empty symbol instead of just increasing the indent by one.
=> structured renderer: fix closing json bracket when rendering with no symbols

internal/backend/remote-state/gcs/backend.go, website/docs/language/settings/backends/gcs.mdx
Fixes https://github.com/hashicorp/terraform/issues/32556
1.4.x
-  Added support for `GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT` env var to allow impersonating a different service account when `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT` is configured for the GCP provider.
=> Add a GCS backend specific env var for impersonation

internal/backend/remote-state/gcs/backend.go, website/docs/language/settings/backends/gcs.mdx
Manual backport of #32557 into v1.4: Add a GCS backend specific env var for impersonation
=> Manual backport of #32557 into v1.4

internal/cloud/state.go, internal/cloud/state_test.go
Duplicates the remote state bug fix in #32614 
State versions created by the cloud integration should begin with serial 1, which matches the local state serial. This can prevent certain types of state/plan mismatches as described in #30670 
Remote backend is not subject to this same bug because it uses the remote state package.
1.4.0, 1.3.8
=> Begin cloud remote state with serial > 0

internal/addrs/resource.go, internal/command/jsonformat/diff.go, internal/command/jsonformat/state.go, internal/command/jsonplan/plan.go, internal/command/jsonstate/state.go, internal/command/testdata/show-json/provider-aliasing-conflict/output.json, internal/command/testdata/show-json/provider-aliasing-default/output.json, internal/command/testdata/show-json/provider-aliasing/output.json
This is a follow up from a comment left by @apparentlymart on an earlier PR: https://github.com/hashicorp/terraform/pull/32629#discussion_r1097901296
This PR imposes the "canonical" ordering of addresses on the jsonplan and jsonstate generation packages, so the produced JSON will be ordered according to the `Less` functions in the `addrs` package. With this change, the jsonformat package that produces the human readable output from the JSON state and plan outputs does not need to worry about ordering at all as they can simply trust the ordering in the json structures.
I'd be quite happy to close this PR without merging if we don't want to change the public API of the JSON outputs, or I could update the 1.4 changelog with something about the ordering being fixed. I just think if we want to …
=> structured run output: impose canonical ordering on jsonstate and jsonplan packages

internal/terraform/node_resource_plan_orphan.go, internal/terraform/node_resource_plan_orphan_test.go
This is a highly local fix for a panic which seems to arise when planning orphaned deposed instances. There are two other things to investigate in response to this issue, likely addressing each in follow-up PRs:
- Fix the graph transformers so that we don't add orphan processing nodes when the instance is deposed;
- Investigate why `readResourceInstanceState` needs to return `nil, nil` in the first place, and redesign it if possible so that we don't have this class of bug elsewhere.
(I may have misunderstood an out-of-band discussion about this, and if we might not want to use this approach at all, in which case we'll probably just fix the graph transformers instead.)
Fixes #32645 (probably; we don't have a full reproduction to validate this)
1.3.x
This is a panic and a narrowly-scoped …
=> Fix panic when planning orphaned deposed instances

internal/terraform/transform_orphan_count.go, internal/terraform/transform_orphan_count_test.go, internal/terraform/transform_orphan_resource.go
Resource instances with no current object in state should not have orphan nodes added to the graph, as deposed objects are handled separately. This was previously handled correctly for the non-expanded case, but expanded resources were missing the appropriate check for a current object.
Also update the comment in the non-expanded case to hopefully clarify that we're checking for the presence of a current object, not the absence of any deposed objects. An instance may have both a current object and zero or more deposed objects in some circumstances, and if so, we still want an orphan node to be added if the instance is not in configuration.
Fixes #32645 (probably; we don't have a full reproduction to validate this)
See also #32663, for another approach to a fix for the same reported issue. …
=> Do not add orphan nodes for deposed instances

commands.go, internal/command/jsonfunction/function.go, internal/command/jsonfunction/function_test.go, internal/command/jsonfunction/parameter.go, internal/command/jsonfunction/parameter_test.go, internal/command/jsonfunction/return_type.go, internal/command/metadata_command.go, internal/command/metadata_functions.go, internal/command/metadata_functions_test.go, website/docs/cli/commands/index.mdx
* Depends on #32453 
---
This PR builds upon the function descriptions added in #32453 and adds a new CLI command to export those as JSON. The new command enables machine-readable function signatures (more: [TF-508: Machine-readable function signatures](https://docs.google.com/document/d/10H00gyk__iKaxRLquHHLpg7Cg5Tx9IfEZ2tV9rfO_ac/edit)), which can be consumed by the language server and others (CDK, website docs, ...). The first consumer will be the Terraform language server, to provide function signature information inside the editor.
Metadata command:
```
$ terraform metadata
Usage: terraform [global options] metadata <subcommand> [options] [args]
This command has subcommands for metadata related purposes.
Subcommands:
functions    Show signatures and descriptions for the available …
```
=> Introduce `metadata functions` command

website/data/language-nav-data.json, website/docs/language/meta-arguments/lifecycle.mdx, website/docs/language/resources/provisioners/local-exec.mdx, website/docs/language/resources/provisioners/null_resource.mdx, website/docs/language/resources/terraform-data.mdx, website/layouts/language.erb
There is no great place for these in the current structure right now, since managed resources have only existed within external providers so far. For the time being I added a link from the main `Resourced` navigation section, and we can work out a better structure from there.
=> initial terraform_data docs

docs/resource-instance-change-lifecycle.md
Reference: https://github.com/hashicorp/terraform/blob/21bb677db706111d634d1b49ea0845ace67651b3/internal/plans/objchange/objchange.go#L289-L292
Previously, the resource lifecycle documentation for Proposed New State only mentioned special behavior for Optional and Computed attributes. This minor documentation update mentions that Terraform also imposes special behavior on Computed-only attributes (preserving any Prior State value).
N/A (main)
=> docs: Explicitly mention Computed-only attribute behavior for Proposed New State

internal/backend/local/backend_apply.go, internal/backend/local/hook_state.go, internal/backend/local/hook_state_test.go, internal/terraform/context.go, internal/terraform/context_apply_test.go, internal/terraform/hook.go, internal/terraform/hook_mock.go, internal/terraform/hook_stop.go, internal/terraform/hook_test.go, internal/terraform/testdata/apply-stop/apply-stop.tf
Terraform Core emits a hook event every time it writes a change into the in-memory state. Previously the local backend would just copy that into the transient storage of the state manager, but for most state storage implementations that doesn't really do anything useful because it just makes another copy of the state in memory.
We originally added this hook mechanism with the intent of making Terraform _persist_ the state each time, but we backed that out after finding that it was a bit too aggressive and was making the state snapshot history much harder to use in storage systems that can preserve historical snapshots. It was also hitting rate limits in some cases, because state changes can arrive in quick succession when making lots of small changes.
However, sometimes Terraform gets …
=> backend/local: Periodically persist intermediate state snapshots

internal/builtin/providers/terraform/provider.go, internal/builtin/providers/terraform/resource_data.go
The terraform provider was panicking on import, because it didn't previously have a resource type which could be imported at all. Add a stub import function for `terraform_data` as a placeholder to allow the call to complete successfully. While there's no need to actually import a `terraform_data` resource, users will inevitably use this to construct examples of import actions for learning purposes or bug reports.
This still isn't very useful even for examples however, because the state-only nature of the `terraform_data` resource type means that we can't fill in the state from only the import ID. This means that any value in `trigger_replace` or `input` will cause a change in the next plan. Once configuration data is available during import we can extend this to create a logical final …
=> allow terraform_data to import

internal/lang/funcs/descriptions.go
This PR replaces all `&#34;` (`"`) and `&#39;` (`'`) in the function descriptions. The escaping of any characters should be up to the consumer of the function signatures.
I didn't catch those entities while adding the descriptions in https://github.com/hashicorp/terraform/pull/32453.
1.4.x
=> Replace HTML entities in function descriptions

website/data/internals-nav-data.json, website/docs/internals/functions-meta.mdx, website/docs/internals/metadata-functions.mdx
This PR is a follow up to https://github.com/hashicorp/terraform/pull/32487 and adds documentation for the new command.
Fixes https://github.com/hashicorp/terraform/issues/32682
1.4.x
=> Add website docs for `metadata functions -json` command

internal/command/cliconfig/provider_installation.go
Fixes #32716.
Error output beforehand:
```
$   terraform plan
There are some problems with the CLI configuration:
╷
│ Error: Invalid provider installation dev overrides
│
│ The entry "registry.terraform.io/joneshf/terraform-provider-foo" in 1:1 is
│ not a valid provider source string.
╵
As a result of the above problems, Terraform may not behave as intended.
```
Error output afterward:
```
$  terraform plan
There are some problems with the CLI configuration:
╷
│ Error: Invalid provider installation dev overrides
│
│ The entry "registry.terraform.io/joneshf/terraform-provider-foo" in 1:1 is
│ not a valid provider source string.
│ Invalid provider type: Provider source "joneshf/terraform-provider-foo" has
│ a type with the prefix "terraform-provider-", which isn't valid. Although
│ that …
```
=> cliconfig: more err detail when provider_installation has invalid provider source

.github/workflows/build.yml
It turns out we don't actually need this step in our build workflow since docs publishing is handled separately! 🎉 Seems just as well to remove it to avoid confusion.
=> Remove docs bundle from build workflow

internal/cloud/backend.go, internal/cloud/backend_plan.go
An authorization bug was reported: #32665 
In the cloud backend, we instantiate a new http client in order to fetch the redacted plan and generate the plan output. The auth token for this client was configured by calling `b.token()` which only sources the token from your CLI configuration, ignoring any token that was set in the cloud config itself. 
In order to make use of the token returned by the cloud config, I've added a new `token` field to the cloud backend, since the `Configure()` receiver is the only place we have access to the config. I've also renamed `b.token()` to be more descriptive about where the token is being fetched to avoid any further confusion. 
1.4.x
-
=> Fix SRO authorization bug when token is fetched from cloud config

internal/cloud/backend_taskStages.go, internal/cloud/backend_taskStages_test.go
Fixes an issue where the CLI exits early after a policy evaluation due to a race condition.
The CLI checks whether the run is [confirmable](https://github.com/hashicorp/terraform/blob/main/internal/cloud/backend_apply.go#L100) or not after a policy evaluation. Due to latency issues, the run is still in task_stage_running state since the status has not been updated yet and the CLI exits. This change allows the policy evaluation to keep polling until a final status has been reached. 
It continues to poll if the taskStage status is `running` or `awaiting_override` until the taskStage reaches a terminal status (either passed, failed, cancelled, errored or unreachable)
This PR also adds a missing CHANGELOG entry.
Fixes #
1.4.0
* When showing the progress of a remote operation running in …
=> Bug Fix where CLI exits if run is not confirmable.

internal/command/cliconfig/cliconfig.go, internal/command/cliconfig/cliconfig_test.go
Since it's already possible to activate the dependency lock file using an environment variable, we should allow opting in to it having broken behavior using the environment too.
It's kinda odd in retrospect that `TF_PLUGIN_CACHE_DIR` is the only setting we allow to be configured both in the environment and the CLI configuration. That means that the infrastructure for dealing with that situation was relatively immature here and so I did some light refactoring to make it unit-testable without actually modifying the test program's environment. To reduce the risk of that I wrote what might be considered an excessive amount of tests for such a small change.
Closes #32656.
=> cliconfig: Allow breaking the dependency lock file using the environment

internal/command/e2etest/providers_mirror_test.go, internal/command/e2etest/testdata/terraform-providers-mirror-with-lock-file/.terraform.lock.hcl, internal/command/e2etest/testdata/terraform-providers-mirror-with-lock-file/terraform-providers-mirror.tf, internal/command/providers_mirror.go
When mirroring providers using `terraform providers mirror` command, AND, if dependency lock file exists, selected provider version might not match the dependency lock file.
So, this PR addresses this issue by honouring the lock file if present.
A new e2e test case has been added to cover this new case.
Fixes https://github.com/hashicorp/terraform/issues/28274
1.3.x
- `terraform providers mirror`: support dependency lock file
=> bugfix: terraform providers mirror command should honor terraform lock file

website/docs/language/providers/index.mdx
[Originally communicated here,](https://developer.hashicorp.com/terraform/language/v1.1.x/configuration-0-11/providers?ajs_aid=3cf1bdca-a598-4dc5-b074-6064b276abb6&_gl=1*xuizrx*_ga*MTM1ODg4NTcyMi4xNjY2MTA5NjI1*_ga_P7S46ZYEKW*MTY3NjU2OTMzNS4zMi4wLjE2NzY1Njk0MDMuMC4wLjA.&product_intent=terraform#provider-versions) this statement is missing in newer docs.
> Providers are released on a separate rhythm from Terraform itself, and thus have their own version numbers. For production use, it is recommended to constrain the acceptable provider versions by pinning it via configuration, to ensure that new versions with breaking changes will not be automatically installed by `terraform init` in the future.
=> Adding provider constraint best practice statement

website/docs/language/functions/compact.mdx
Update the documentation for `compact` to indicate that it also accepts and filters out `null` values.
(previously #28285)
=> Update documentation for compact function

internal/cloud/backend_taskStage_policyEvaluation_test.go, internal/cloud/backend_taskStage_taskResults_test.go, internal/cloud/backend_test.go, internal/cloud/testing.go
The cloud package tests were taking over 40s to execute, due to a couple of minor issues:
* Run tasks tests were using the real polling intervals between requests. This seems unimportant to test, and setting it to 0 saves 30s.
* Config tests were making a request to `nonexisting.local`, which was intended to fail. This also didn't seem like a specifically important error. I replaced it with a request to a mocked non-TFE host, which still executes the error handling path, but doesn't spin for 5–10s on a DNS failure.
Before:
```shellsession
$ go test -count=1 ./internal/cloud/
ok  	github.com/hashicorp/terraform/internal/cloud	41.957s
```
After:
```shellsession
$ go test -count=1 ./internal/cloud/
ok  	github.com/hashicorp/terraform/internal/cloud	4.690s
```
1.4.1
Backporting to 1.4 as it's …
=> 10x faster cloud tests

website/docs/cli/config/config-file.mdx, website/docs/cli/config/environment-variables.mdx
This is an alternative way to set the CLI configuration setting plugin_cache_may_break_dependency_lock_file to activate the transitional compatibility behavior that prefers to break the dependency lock file if that would create an additional opportunity to use the plugin cache.
This has been supported since #32726 but I forgot to update this particular doc section when I implemented it, despite @alisdair's attempt to prompt me which apparently I was too absent-minded to think about that day. :confounded: 
While here I also fixed a minor bug from #32494 (where this doc section originated) where the heading was at the wrong nesting level and so would've messed up the navigation tree as previously defined. The heading is now nested under "Provider Installation" as originally intended.
=> website: Document TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE env var

CHANGELOG.md
Adds some missing CHANGELOG to the v1.4 terraform release.
The new release has OPA support in the CLI and fixes a bug where the CLI exits early
=> Add missing changelog entries for OPA support and bug fix on the CLI

internal/configs/module_merge.go, internal/configs/module_merge_test.go, internal/configs/testdata/valid-modules/override-module/primary.tf
Fixes #32795
1.4.x
BUG FIXES
- Enables overriding modules that have `depends_on` attribute set (although still doesn't allow to override `depends_on` , which is the intended behaviour)
=> Fixes overriding modules which have depends_on attribute set

internal/configs/container.go, internal/configs/resource.go, internal/lang/data.go, internal/lang/data_test.go, internal/lang/eval.go, internal/lang/scope.go, internal/terraform/context_eval.go, internal/terraform/eval_conditions.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/eval_for_each.go, internal/terraform/eval_variable.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/evaluate_valid.go, internal/terraform/evaluate_valid_test.go, internal/terraform/node_module_variable.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_validate.go
This PR adds support for scoped resources into the Terraform configuration language.
- It creates a new `Container` interface within the `configs` package.
- It embeds an optional container with the `configs.Resource` structure.
- It adds a new address as an argument to the static analysis flow, `source`.
- The static analysis will now validate that the container is accessible from the given source.
As of this PR, this new functionality is not used. As such all `source` references are set to `nil`, indicating they have only the default level of access and cannot access anything within a container. 
In the longer term, only items that know they might need to access containerised resources will need to set the `source` argument which at the moment will only be the new `Check` blocks.
As …
=> Checks: Add support for scoped resources.

internal/command/jsonformat/plan.go, internal/command/jsonformat/plan_test.go
Currently, we are checking whether the output changes are empty before deciding to print the "no changes" message in the renderer. But, no-op changes do not print anything so any plan with no-op changes will make the renderer consider the output changes to be not empty so it won't print the nice message but then it also won't print any outputs.
This PR fixes this by computing the concrete output diffs earlier and then using them to decide whether to print the "no changes" message.
Fixes #32815 
1.4.1
- Fix the plan renderer skipping the "no changes" messages when there are no-op outputs within the plan.
=> Fix no-op outputs causing the plan renderer to skip the 'no changes' message

website/docs/language/state/index.mdx
Add TFC to state docs page. 
Fixes #
1.4.x
-
=> Add TFC to state doc

internal/command/jsonformat/renderer.go, internal/command/show_test.go
When rendering nested `nil` output values from state, the Colorize options could be set to `nil`. Ensure the `RenderHumanOpts` are always instantiated via their constructor. If a constructor is required, it would probably be safer to have no exported fields for the type, but that level of refactoring will have to be review separately.
Fixes #32833
v1.4.1
=> Prevent nil Colorize options when rendering state outputs

internal/command/cliconfig/cliconfig.go, internal/command/cliconfig/cliconfig_test.go, internal/command/e2etest/init_test.go
Fix-up and rebase of #32793
This Pull Request is about noticing people when `TF_CLI_CONFIG_FILE` environment variable points to a non existing file.
In such case, a warning message will be printed out like below;
```sh
There are some problems with the CLI configuration:
╷
│ Warning: Unable to open CLI configuration file
│
│ The CLI configuration file at
│ "/private/var/folders/7b/q4m7dd2x4fl8ltp731djsw940000gn/T/tmp.5TVZNsJu/.terraform.rcr"
│ specified does not exist.
╵
```
Fixes #32646
=> emit a warning msg if invalid CLI configuration file location

website/docs/language/providers/index.mdx
New PR for pinning providers
Using this new PR with backport label 1.4-backport since I made a mistake before
Old PR https://github.com/hashicorp/terraform/pull/32697.
=> Update index.mdx New PR for pinning providers

go.mod, go.sum, internal/lang/funcs/collection_test.go
We inadvertently incorporated the new minor release of cty into the 1.4 branch, and that's introduced some more refined handling of unknown values that is too much of a change to introduce in a patch release.
Therefore this reverts back to the previous minor release for the v1.4 series, and then we'll separately get the `main` branch ready to work correctly with the new `cty` before Terraform v1.5.
This reverts just the upgrade and the corresponding test changes from #32775, while retaining the HCL upgrade and the new test case it introduced for that bug it was trying to fix. That new test is still passing so it seems that the cty upgrade is not crucial to that fix.
=> Revert cty minor version v1.13 upgrade

website/docs/cli/commands/init.mdx
The option was removed in v0.15 and so is no-longer "plan[ed]" https://newreleases.io/project/github/hashicorp/terraform/release/v0.15.0
=> Correct docs on Configuration Directory

internal/terraform/context_apply2_test.go, internal/terraform/node_output.go
The outputs from non-root modules which contained nested sensitive values were being treated as entirely sensitive when evaluating them from state during apply. In order to have detailed information about sensitivity from non-root module outputs, we need to store the value along with all sensitive marks. This aligns with the usage of state being the in-memory store for other temporary values like locals and variables. Also like locals and variables, these outputs are not serialized to state storage, so will not be be affected by the inclusion of the marks.
Fixes #32880
=> Store all sensitive marks for non-root module outputs in state

website/docs/language/resources/provisioners/null_resource.mdx
Reference: https://github.com/hashicorp/terraform/pull/32624
Reference: https://github.com/hashicorp/terraform/pull/32898
Reference: https://github.com/hashicorp/terraform/pull/32914
Manual backport due to inconsistency between main and v1.4.
1.4.x
N/A
=> v1.4: website: Minor fixes to Provisioners Without a Resource page

internal/terraform/transform_check.go
Might fix #32924 
I haven't been able to reproduce the flake locally so can't confirm this is definitely the cause. But I think it's likely triggered by a check block that doesn't have an embedded data source which means the graph isn't aware of any ordering between the expand and report check.
=> checks: ensure checks are reported before executed

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
When creating a plan under the following conditions: 
- A provider has been upgraded with changes to the schema
- There are external changes to resources outside of terraform
- The `-target` flag is being used
- Resources which are not targeted require a schema migration
The un-targeted resources will not have been migrated to a new schema and cannot be decoded from the prior state for the external changes report.
Since there is no way to decode these resources which have been excluded via `-target`, we can only skip over them when inspecting `driftedResources`. Return warnings for now to indicate that these resources could not be decoded and users will need to eventually apply these changes.
Fixes #31052
=> External changes report can fail with schema migrations and `-target`

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/testdata/data-source-read-with-plan-error/main.tf
When planning encounters an error we were returning early without cleaning out any planed data sources which cannot be serialized. Move the cleanup to the common `walkPlan` method where the `PriorState` is assigned so that it cannot be missed.
Fixes #32865
=> Remove planned data source objects from state on error

internal/terraform/context_plan2_test.go, internal/terraform/marks.go, internal/terraform/node_resource_abstract_instance.go
Backport of #32892
The below text is copied from the body of the original PR.
If a resource has a change in marks from the prior state, we need to notify the user that an update is going to be necessary to at least store that new value in the state. If the provider however returns a prior state value in lieu of a new config value, we need to be sure to filter any new marks for comparison as well. The comparison of the prior marks and new marks must take into account whether those new marks could even be applied, and if the value is unchanged, the new marks may be completely irrelevant.
Fixes https://github.com/hashicorp/terraform/issues/32864
=> Backport of don't compare plan marks for missing values into v1.4

.release/ci.hcl
Pipeline is unable to run past `trigger-staging` because the `promote-staging` is missing a `depends` line - pipeline is hung after trigger staging: https://github.com/hashicorp/crt-workflows-common/actions/runs/4557006479. 
1.4.x
-  Add `depends` statement to `promote-staging`
-  Add `promote-staging-packaging` to opt in to linux packaging staging buckets
-  Remove `releng/` branch from pipeline triggers
=> Add depends block for promote-staging + add promote-staging-packaging

website/docs/cli/install/apt.mdx
1.4.3 included a packaging change that means that the previously accepted `apt install terraform=1.4.0` pattern no longer works, as reported in https://github.com/hashicorp/terraform/issues/32964. This PR updates the documentation to clarify the change and point towards more context.
1.4.x
=> update apt install instructions

internal/terraform/context_apply_checks_test.go, internal/terraform/node_check.go
When a nested data source within a check block fails to load data, the check block should not execute any of the embedded check rules. Currently, if none of the check rules reference the check block the check rules can execute before the embedded data source resulting in confusing check results if the data source does then fail.
This PR adds an explicit reference to the embedded data source from the check expand node, so even if it is not referenced by the individual check rules it will still execute before them.
=> checks: always reference the nested data source from the check graph node

website/docs/language/functions/templatefile.mdx
Although maps and objects are similar, maps require that all values be of the same type while objects can allow different values to have their own type.
This function does not restrict itself to maps- the examples themselves include cases where both strings and lists are passed through, making this an object and not a map.
=> Fix templatefile argument type

internal/backend/remote-state/pg/backend.go, internal/backend/remote-state/pg/backend_test.go, website/docs/language/settings/backends/pg.mdx
Describe in detail the changes you are proposing, and the rationale.
Somwhat Fixes #32525 , but only the easy way, by supporting the whole `conn_str` as environment variable. Theoretically being able to build this using `DB_NAME`, `DB_USER`, `DB_PASSWORD` and `DB_HOSTANAME` (or so) would be even more interesting.
(not important, just convenient)
1.4.x
A user can now (eg by the pipeline, which is running `terraform`) set the `conn_str` as environment variable, instead of having the requirement to set it inside the `backend` block. This mainly prevents the `backend` block from containing a secret (mostly the database password). 
In the [`backend_test.go`](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/pg/backend_test.go#L29-L31) this is basically done by …
=> Add support for PG_CONN_STR ENV var

internal/terraform/node_resource_abstract_instance.go, internal/terraform/provider_mock.go
When we plan to destroy an instance, the change recorded should use the correct type for the resource rather than `DynamicPseudoType`. Most of the time this is hidden when the change is encoded in the plan, because any `null` is always encoded to the same value, and when decoded it will be converted to the schema type. However when apply requires creating a second plan for an instance's replacement that value is not going to be encoded, and remains a dynamic value which is sent to the provider.
Most providers won't see that either, as the grpc request also encodes and decodes the value to conform with the correct schema. The builtin terraform provider does get the raw cty value though, and when that dynamic value is returned validation fails when the type does not match.
Fixes #32985
=> the destroy plan should use correct type

.github/scripts/verify_docker, .github/workflows/build.yml
This adds a test to catch the glibc build issue that caused #32947. We check both the container executes and the version is correct.
1.5.x
1.4.x
=> ci: Smoke test docker builds

website/docs/language/settings/backends/azurerm.mdx
Fixes #
1.4.x or later
Updated azurerm backend configuration:
* 'metadata_host' - (Optional) The Hostname of the Azure Metadata Service (for example management.azure.com), used to obtain the Cloud Environment when using a Custom Azure Environment. This can also be sourced from the ARM_METADATA_HOSTNAME Environment Variable.
- Documentation update for **'azurerm'** backend configuration doc. The **metadata_host** parameter is not included in the list of available / optional parameters for the backend configuration. This parameter is required when using the azurerm backend in certain custom Azure environments.
-
=> metadata_host param for AzureRM backend documentation

internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/string.go, internal/command/jsonformat/differ/change_test.go, internal/command/jsonformat/differ/map.go
This PR fixes 2 issues in the new renderer:
1. Unknown values are removed from the set of after values by the json plan package for attributes. This affects maps as they are unaware of the values they are supposed to contain. This PR makes the renderer look at the planned unknown values and merge them back into the main after set before computing the diff.
2. Null strings were being rendered with the `%q` format which meant they were being encapsulated by quotation marks and the color encodings were being rendered as a string.
This PR fixes both of these issues. 
Fixes #33016 
1.4.6
- Fix bug when rendering plans that include null strings
- Fix bug when rendering plans that include unknown values in maps
=> Fix rendering unknown values in map and null string primitives

go.mod, go.sum, internal/backend/remote/testing.go, internal/cloud/backend_plan.go, internal/cloud/backend_run_warning.go, internal/cloud/backend_run_warning_test.go, internal/cloud/testing.go, internal/cloud/tfe_client_mock.go
The cloud backend, which communicates with TFC like APIs, can create
runs which may have one or more configuration parameters altered. These
alterations are emitted as run-events on the run so that API clients
can consume and display them to users. This commit adds a step in
plan operation to query the run-events once a run is created and then
emit specific run-event descriptions to the console as warnings for
the user.
[Jira](https://hashicorp.atlassian.net/browse/TF-5641)
[RFC](https://hashidocs.hashicorp.services/document/18gCqJdevTjMfbOfqosO8hTI90_1_WFbWIlcu32GWfVw)
1.4.x
- Shows warnings generated when creating a run in the cloud backend
=> Emit warnings for certain run events in cloud backend

internal/backend/remote-state/pg/backend.go, internal/backend/remote-state/pg/backend_test.go, website/docs/language/settings/backends/pg.mdx
This patch does two things:
- it adds environment variable support to the parameters that did not have it (and uses `PG_CONN_STR` instead of `PGDATABASE` which is actually more appropriate to match the behavior of other PostgreSQL utilities)
- better documents how to give the connection parameters as environment variables for the ones that were already supported based on the recommendation of @bsouth00
I will prepare a backport of the documentation part of this once it is merged.
Closes https://github.com/hashicorp/terraform/issues/33024
1.5.0
The `pg` backend now supports the `PG_CONN_STR`, `PG_SCHEMA_NAME`, `PG_SKIP_SCHEMA_CREATION`, `PG_SKIP_TABLE_CREATION` and `PG_SKIP_INDEX_CREATION` environment variables.
=> Improve environment variable support for the pg backend

internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/unknown.go
This PR updates the unknown renderer to include the `# force replacement` suffix when necessary. I think that was missed initially as I couldn't think of any cases where a computed attribute would cause the replacement as something else would have to have triggered the attribute to be recomputed. As the issue demonstrates I think there is something happening within `import` commands that makes this assumption incorrect.
I've added tests into the renderer package to validate this, not much else needed as the data is already being made available it just wasn't being used.
Fixes #33041 
1.4.6
-  Fixes bug where computed attributes were not being rendered with the `# forces replacement` suffix.
=> Make the unknown attribute renderer consider the force replacement metadata

internal/terraform/graph_builder_plan.go, internal/terraform/transform_destroy_edge.go
Just like when applying a destroy plan, we can skip the inter-provider cycle check when creating the destroy plan, which can be expensive when there are a lot of resource instances with dependencies from another provider.
Existing test coverage is sufficient, and multiple test cases hit this new condition.
Closes #33071
=> skip inter-provider cycle check in destroy plan

internal/command/jsonformat/renderer.go
Fixes #
1.4.x
-  Add new `resource_drift` JSONLogType and format output
=> [TF-5829]add resource_drift JSONLogType

internal/configs/import.go, internal/configs/import_test.go, internal/configs/module.go, internal/configs/parser_config.go
Needs https://github.com/hashicorp/terraform/pull/33080.
This PR adds an `import` block type with the following shape:
```hcl
import {
id = "123"
to = my_resource.foo
}
```
The implementation is very similar to `moved` blocks at this point.
The following two features will be added in future PRs:
- `provider` field in import block
- validation: import blocks cannot appear in child modules
- validation: only one import block per addr
| # | Description | Package(s) | Pull Request |
|---|---| --- | ---|
| 0 | Add plannable import types | `configs`,`plans` | #33080   |
| 1 | Add import block | `configs` | #33081   |
| 2 | Render import changes | `command/views`,`command/jsonformat` | WIP #33082   |
| 3 | Make import plannable | `terraform` | WIP #33085  |
| 4 | Make import changes applyable | …
=> Plannable import 1: Add import block (configs)

.copywrite.hcl
Trying to unblock #33003 by ignoring all files under `testdata`, as automated copyright headers on those files result in unwanted changes to test results.
n/a
=> Configure copywrite to ignore testdata

internal/backend/remote/backend_context_test.go, internal/registry/regsrc/friendly_host.go
Once again trying to unblock #33003. This time we have [failing goimports consistency checks](https://github.com/hashicorp/terraform/actions/runs/4811956825/jobs/8566600883) triggered because copywrite modified some files we haven't touched in a while.
=> Fix goimports discrepancies

.copywrite.hcl
Yet another attempt to unblock #33003, this time ignoring all `*.pb.go` generated code, along with other `go generate` output from `stringer` and `mockgen`.
=> Configure copywrite to ignore protobuf, stringer, mockgen output

internal/plans/changes.go, internal/plans/changes_src.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/graph_walk_context.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go
Needs https://github.com/hashicorp/terraform/pull/33080.
During a plan, Terraform now checks for the presence of import blocks. 
For each resource in config, if an import block is present with a matching address, planning that node will now trigger an ImportResourceState and ReadResource. The resulting state is treated as the node's "refresh state", and planning proceeds as normal from there.
=> Plannable import 3: Make import plannable

internal/command/jsonformat/plan.go, internal/command/jsonformat/plan_test.go
Fixes the ordering of import and add within the change summaries printed by the plan renderer.
1.5.0-alpha
-  N/A, plannable imports will have their own CHANGELOG entry
=> Imports should come before Adds in change summaries

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
When running terraform plan with `-target` but also using terraform move blocks, an error of 
```
│ Error: Moved resource instances excluded by targeting
│ 
│ Resource instances in your current state have moved to new addresses in the latest configuration. Terraform must include those resource
│ instances while planning in order to ensure a correct result, but your -target=... options to not fully cover all of those resource
│ instances.
```
Pops up, which includes a minor typo.
This PR updates to fix the typo
Fixes minor typo in error message in terraform cli tool
1.4.x
Minor typo fix in `Error: Moved resource instances excluded by targeting` error message.
-
=> Fix small typo in tf plan error

website/docs/language/functions/regex.mdx
During refactoring, there was a backslash added to `|` character in terraform regex. That doesn't actually work.
Fix that and return just `x|y` - that's the correct usage, that works.
Fixes #
1.1-backport
1.2-backport
1.3-backport
1.4.x
- Terraform regex documentation of `x|y` included an extra backslash. Removed.
=> Fix regex pattern for more alternatives

website/docs/cli/cloud/migrating.mdx
This adds a warning about the consequences of switching to the `cloud` block, in terms of losing `prefix` support, and the impact that has on CLI usage. Specifically, after switching from the `remote` backend to the `cloud` block, CLI users lose the ability to run e.g. `terraform workspace select prod`, and must instead run e.g. `terraform workspace select my-app-prod`. This has the potential to impact previously written scripts, as well, but was until now not actually noted in the migration documentation.
=> [docs] Add warning about prefix loss when migrating

website/docs/language/settings/backends/s3.mdx
There was a syntax error on the example.  
`assume_role = {}` doesn't work, it should be `assume_role {}`
Fixes #
1.4.x
=> Fixing s3.mdx on Delegating Access

website/docs/cli/state/taint.mdx
Update documentation to match the documentation on the deprecated taint command in /cli/commands/taint.
DOCS: Update `-replace=...` command on the replace command page.
-Updates the website documentation so that the `-replace=...` command matches between:
website/docs/cli/commands/taint.mdx 
website/docs/cli/state/taint.mdx
=> docs: Update command to match /cli/commands/taint -replace cmd

internal/command/import.go, internal/command/meta.go, internal/command/views/apply.go, internal/command/views/hook_ui.go, internal/command/views/hook_ui_test.go, internal/command/views/plan.go, internal/command/views/refresh.go
Currently, the UI hooks print the same messages for importing statements during a direct import command and during a plan with plannable imports. This means the output for the UI doesn't entirely make sense during a plan and the produced logs are rendered inconsistently. 
This is quick PR that just updates the hooks to print different messages during a plan and an import. 
I wonder if an argument could be made that there should be no import streamed logs during a plan? Given that it already prints the message for the refresh? Maybe that is enough, if so I'd be happy to change this to just go and delete where those hooks are called.
Before:
```
tfcoremock_simple_resource.generated: Importing from ID "k-9"...
tfcoremock_simple_resource.generated: Import prepared!
Prepared …
```
=> Plannable import: Make the streamed logs more consistent during planning

internal/terraform/context_apply2_test.go, internal/terraform/transform_destroy_edge.go
The logic used to prune unused providers was only taking into account the common case of providers in the root module. The quick check of looking for up edges doesn't work within a module, because the module structures will create non-resource nodes connected to the providers. Use a deeper check of looking for any dependent resources which may require that provider to be configured.
=> prune unused providers within modules

website/docs/cli/commands/fmt.mdx
=> Update fmt.mdx to include missing period / full stop

internal/command/import.go, internal/command/meta.go, internal/command/views/apply.go, internal/command/views/hook_ui.go, internal/command/views/hook_ui_test.go, internal/command/views/plan.go, internal/command/views/refresh.go
Reverts hashicorp/terraform#33155
We're leaning into creating dedicated hooks for this instead. Watch #33160 for this.
=> Revert "Plannable import: Make the streamed logs more consistent during planning"

website/docs/language/expressions/type-constraints.mdx
From helping folks in community forums I've noticed that many people misunderstand "type = any" as being a shorthand to avoid writing out a proper type constraint, rather than as a way to handle the very rare case where a module truly does not care what type of value it's accepting.
This is understandable because the previous documentation only described how this feature behaved, and not what this feature was for. This new content instead leads by describing the single rare situation where this feature is appropriate to use, and only then explains some details of how it works. Hopefully this will help avoid misleading people into using this placeholder in inappropriate situations, and thus allow Terraform to give them better feedback about errors elsewhere in their configurations.
=> website: Clarify what the "any" type constraint placeholder is for

internal/command/jsonchecks/checks.go, internal/command/jsonchecks/checks_test.go
In preparation for 1.5, we're no longer marking the JSON output for checks as experimental. The new check blocks are fully supported and shouldn't be marked as experimental, so the rest of the checks get carried forward as well.
=> Don't mark check results as experimental in JSON outputs.

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
There is a difference between an empty collection and a null collection. The config generation was just treating null nested collections as empty collections, which meant the plan was reporting imported resources as being updated. This should never be the case for generated config.
=> plannable import: fix config gen printing empty collections in place of nulls

website/docs/language/resources/provisioners/syntax.mdx
The destroy-time provisioner note was formatted as a code block instead of an actual note.
=> docs: provisioners: fix formatting on a note

internal/command/views/apply.go, internal/command/views/apply_test.go, internal/command/views/hook_count.go, internal/command/views/hook_ui.go, internal/command/views/json/change_summary.go, internal/command/views/json_view_test.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/hook.go, internal/terraform/hook_mock.go, internal/terraform/hook_stop.go, internal/terraform/hook_test.go, internal/terraform/node_resource_plan_instance.go
There's no actual action that happens when applying an import, so in order to populate a count of imported objects and include some helpful output about what's happening, we'll use the slightly awkward method of iterating over the planned resource changes during an apply and manually calling a hook (similar to the approach discussed in #33155). 
This PR also establishes new `PrePlanImport`, `PostPlanImport`, `PreApplyImport`, and `PostApplyImport` hooks for the new configuration-driven import mechanism, so we'll no longer need to reuse the import-related hooks called during the legacy import command.
Output (import only):
```
tfe_organization.name: Preparing import... [id=boring-test-org]
tfe_organization.name: Refreshing state... [id=boring-test-org]
Terraform will perform the following …
```
=> Populate import counts during applies and clean up output

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_plan_instance.go
A change is only considered "importing" if it is adding a new resource instance to the state.
This means that subsequent plans in the presence of an already-applied import block will not create extra "importing" changes.
As in https://github.com/hashicorp/terraform/pull/33160 this PR illustrates some of the subtleties in the meaning of "import" now. From the provider's point of view, "import" (i.e. the `ImportResourceState` RPC) happens during planning. From the user's point of view, "import" (i.e. adding a new resource to the state) happens only once a _planned_ import change is also _applied_. I therefore think it's correct to say that if a resource has already been "imported" into the state, subsequent no-op changes are not "importing" that resource, despite the plan node calling …
=> terraform: config-driven import is idempotent

internal/backend/backend.go, internal/backend/local/backend_local.go, internal/backend/local/backend_plan.go, internal/command/arguments/plan.go, internal/command/command_test.go, internal/command/plan.go, internal/command/plan_test.go, internal/command/testdata/plan-import-config-gen/generated.tf.expected, internal/command/testdata/plan-import-config-gen/main.tf, internal/genconfig/generate_config_write.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/transform_config.go
- Adds a flag to the plan command: `gen-config-out`
- Uses the flag to decide whether generated config will be produced at all, and the location it will go to.
- If the location already exists, we fail and tell the user to choose a new one to avoid problems with concurrent writes or accidental deletions.
- Adds nice error messages detailing why an import fails if the target doesn't exist, and how to make it generate config for you.
- Refactor so the transform_config.go file decides when a node is created whether or not it will generate config instead of letting the node make the decision itself later. This makes it easier to tie it all back to presence of the new flag.
=> plannable import: write generated config to out flag

internal/command/testdata/validate-invalid/duplicate_import_ids/main.tf, internal/command/testdata/validate-invalid/duplicate_import_ids/output.json, internal/command/testdata/validate-invalid/duplicate_import_targets/main.tf, internal/command/testdata/validate-invalid/duplicate_import_targets/output.json, internal/command/validate_test.go, internal/configs/module.go
Importing to the same target address twice or attempting to import the same ID to two different resources of the same type will lead only to sadness and shouldn't be possible.
1.5.x
=> validate duplicate import blocks

internal/configs/module.go, internal/configs/testdata/invalid-modules/import-to-moved-from/main.tf
It is invalid for any import block to have a "to" argument matching any moved block's "from" argument.
=> plannable import: error if importing to a move source

internal/configs/config_build.go, internal/configs/testdata/config-diagnostics/import-in-child-module/child/main.tf, internal/configs/testdata/config-diagnostics/import-in-child-module/errors, internal/configs/testdata/config-diagnostics/import-in-child-module/root.tf
We currently only allow `import` blocks in the root module. If a child module contains an import block, we error.
1.5.x
=> plannable import: disallow import blocks in child modules

internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
Import addresses targeting expanded resource instances must target instances that already exist in configuration.
For example, an import block targeting `aws_instance.example["foo"]` is not valid if there is not already a configuration block for `aws_instance.example` with `for_each` and the key `"foo"`.
=> plannable import: error if importing to invalid keyed address

internal/backend/local/backend_plan.go, internal/command/jsonformat/plan.go, internal/command/jsonformat/plan_test.go, internal/command/views/operation.go, internal/command/views/operation_test.go, internal/genconfig/generate_config_write.go
The config generation file path is now dynamic, so remove mentions of `generated_config.tf` from the human renderer. We may want to plumb the actual file name through, but not without a little more thought into whether we're going to truncate it in the resource change comment.
Also add a note to the plan next steps when the config is generated. This should only print if a file is actually written.
=> plannable import: improve gen config human plan output

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
A `NestingSingle` nested block that is null in state should not be present in generated config at all.
This PR also fixes a panic when attempting to generate config for a state with a null value for a `NestingSingle` block.
=> genconfig: do not generate null NestingSingle blocks

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
It is not valid for a provider to return an unknown value for a configured nested collection, but we need to guard against invalid unknowns before comparing the number of values in the collection.
Fixes #32957
=> validate unknown nested attribute collections

internal/plans/planfile/tfplan.go, internal/plans/planfile/tfplan_test.go
We missed a bit of plumbing to allow importing info and generated config to be persisted correctly in the plan output file when using `terraform plan -out <planfile>` so that it can be read back later by `terraform apply` or `terraform show`.
1.5.x
=> plannable import: correct plumbing when using a plan output file

go.mod, go.sum, internal/backend/local/hook_state.go, internal/backend/local/hook_state_test.go, internal/backend/remote/backend.go, internal/cloud/state.go, internal/cloud/state_test.go, internal/states/remote/state.go
**NOTE:** The scope of this PR changed during discussion; see the commentary below to learn about the expanded scope.
The remaining text is the original PR writeup from before the scope increase.
---
We've seen some concern about the additional storage usage in Terraform Enterprise implied by creating intermediate state snapshots for particularly long apply phases that can arise when managing a large number of resource instances together in a single workspace.
This is an initial coarse approach to solving that concern, just restoring the original behavior when running inside Terraform Cloud or Enterprise for now and not creating intermediate snapshots at all.
This is here as a solution of last resort in case we do not find a better compromise before the v1.5.0 final release. Hopefully a …
=> cloud: Allow Terraform Cloud/Enterprise to apply backpressure to intermediate state snapshots

internal/command/testdata/plan-import-config-gen/generated.tf.expected, internal/configs/configschema/filter.go, internal/configs/configschema/filter_test.go, internal/genconfig/generate_config_test.go, internal/genconfig/generate_config_write.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
This PR fixes a number of issues with config generation during the plan.
- Config generated during the plan may fail validation due to helper/schema behaviours such as `ConflictsWith`, which are not visible to Terraform. Do not fail planning due to this.
- Detect the case where there could be an apparent `"id"` attribute in the schema added by helper/schema. In this case it is not safe to add `"id"` to generated config.
- Fix a bug in which configschema filters were not applied to nested object types.
- Fix a bug in which null NestingSingle blocks were written to generated config.
- Add tests for configschema filters.
Please see individual commits for more details.
=> plannable import: safer config generation and schema filters

internal/terraform/context_plan2_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_output.go, internal/terraform/transform_output.go
When planning a destroy operations, locals only referenced by root outputs do not need to be kept in the graph, because the root output does not get evaluated. Rather than try and prune the local based on this condition, we prevent the connection from being created by ensuring that a root output destroy node has no references.
When completing the pseudo-expansion of root outputs, the particular case where a plan expansion node which intends to only destroy root outputs should not have references was missed. This could cause locals which should not be kept in the graph due to a partial destroy to remain, even though they may have expressions that are no longer valid. This worked previously because root output destroy nodes were inserted directly, rather than via expansion.
The separate …
=> Remove destroy-plan locals only referenced by root outputs

docs/plugin-protocol/object-wire-format.md, go.mod, go.sum, internal/builtin/providers/terraform/resource_data.go, internal/builtin/providers/terraform/resource_data_test.go, internal/command/views/json/diagnostic.go, internal/lang/funcs/cidr.go, internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go, internal/lang/funcs/crypto.go, internal/lang/funcs/datetime.go, internal/lang/funcs/datetime_test.go, internal/lang/funcs/encoding.go, internal/lang/funcs/encoding_test.go, internal/lang/funcs/filesystem.go, internal/lang/funcs/number.go, internal/lang/funcs/refinements.go, internal/lang/funcs/string.go, internal/lang/funcs/string_test.go, internal/plans/objchange/compatible.go, internal/plans/objchange/compatible_test.go, internal/plans/objchange/objchange.go, internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
This introduces a new concept called [Refinements](https://github.com/zclconf/go-cty/blob/7dcbae46a6f247e983efb1fa774d2bb68781a333/docs/refinements.md) from upstream `cty`, which is the foundation of the Terraform language type system.
For example, this allows an known value to be refined as "not null", which means that `v != null` and `v == null` can return a known true or false even if the actual value isn't yet known. There are also various other refinements to help with some other common situations, such as testing whether the length of a collection is greater than zero, whether the length of a string is greater than zero, etc.
The individual commits have more detailed commit messages, so it might help to review this on a per-commit basis rather than as a large flat diff.
I'm …
=> Refined Unknown Values, allowing some operations with unknown values to produce known results

.github/actions/go-version/action.yml
This removes usage of the soon-to-be deprecated set-output command in github actions.
Per: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> remove deprecated set-output call in gha

internal/cloud/backend.go, internal/cloud/state.go, internal/cloud/state_test.go, internal/cloud/testing.go
Adding a null check for `x-terraform-snapshot-interval`, which if not present, disables intermediate snapshots in the cloud backend's state manager. The first check will occur when we read the current state version in the workspace,  Any TFC/E instance that does not emit this header in the State Version API does not support handling state snapshots. 
1.5.0
-
=> [cloud] Add interval header check to enable snapshots

go.mod, go.sum
This introduces HCL's own updates to generate refinements for unknown results from some operations.
Fixes #33237
Does not address #32651 completely, but provides additional information that we could consider in the plan UI.
Does not address https://github.com/hashicorp/terraform/issues/26755 completely, but provides some building blocks for it.
=> go.mod: go get github.com/hashicorp/hcl/v2@v2.17.0

internal/terraform/context_plan2_test.go, internal/terraform/transform_config.go
Fixes https://github.com/hashicorp/terraform/issues/33271.
This turns the https://github.com/hashicorp/terraform/issues/33271 panic cases into errors, though without the full diagnostic treatment that we'd get by erroring during the plan.
A better long-term approach is to follow @liamcervante's comment and do this during validate.
We can remove this error when we add support for generating configuration for expanded resources.
=> terraform: expanded resources cannot genconfig

internal/command/plan.go
Add help text for `terraform plan -generate-config-out=path`. Reflow the Other Options section to make it fit.
=> command: help text for generate-config-out

internal/cloud/backend_plan.go, internal/command/init.go
The intention here is to error generously in cases where the configured backend or TFC agent might not be ready for plannable import.
When
- The cloud backend is configured and the TFC_RUN_ID env var is populated (key indicators that we are running in a remote execution environment in Terraform Cloud), and
- At least one import block is present
Check the following:
- the TFC_AGENT_VERSION environment variable should be present and have a value of 1.10 or greater
- the API version (should already be available in the backend’s go-tfe client) should be 2.6 or greater
If either of these conditions fails, show an error saying that import functionality is not compatible with this version. The user can choose whether to remove the import blocks and run the plan as normal, or upgrade.
I'm not …
=> cloud: assert import block compatibility

internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_apply_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_check.go, internal/terraform/testdata/apply-with-checks/main.tf, internal/terraform/transform_check.go, internal/terraform/transform_check_starter.go
We have documented that checks should execute last, but due to nested data sources getting treated as regular data sources this was being missed for data sources that had no references. These could just execute whenever Terraform decided to let them.
This PR adds a new no-op node to the terraform graph, and ensures all resources execute before it with nested data sources executing after.
=> Ensure nested data blocks execute last of all Terraform resources

internal/command/views/operation.go
The plan next step text can vary in length depending on passed in path values. Word wrapping for this line must take place at the highest level.
Before:
After:
=> views: fix wordwrap bug

website/data/language-nav-data.json, website/docs/language/checks/index.mdx, website/docs/language/expressions/custom-conditions.mdx
Manual backport in place of #33317 as the automated process didn't work properly.
=> Manual backport of "Add documentation page for checks and assertions" into v1.5

website/docs/language/checks/index.mdx, website/docs/language/expressions/custom-conditions.mdx
Howdy! Small PR adding links to the Checks articles for the Checks tutorial. 
I also fixed my own small mistake from reviewing, I thought the style guide specified title case headers, which it does not, it requires sentence case headers. So I added those fixes in this PR as well!
@liamcervante Does this need a special backport tag as well?
=> Adding links to the Checks tutorial and fixing headers.

website/docs/language/modules/develop/composition.mdx
Fixes #
Grammar mistake in the documentation.
1.5.x
-  May the Good Lord above forgive my pedantry.
=> Add missing preposition to sentence

internal/backend/remote-state/oss/backend.go
Terraform State OSS Backend has a deprecated configuration variable `assume_role`, and it has been marked as `Deprecated`, and there always throws a warning when using oss backend. This is uncomfortable for customers. This PR aims to remove the warning.
1.4.x
=> backend/oss: Removes the deprecated warning for configuration variable assume_role

website/docs/language/settings/backends/cos.mdx
Give a list of permissions required for the COS state backend. This can be a reference if users want to define stricter policies.
1.4.x or next available document release
=> docs/backends/cos: add necessary permission list for using the backend

internal/command/jsonplan/plan.go, internal/command/show_test.go, internal/command/testdata/show-json/plan-error/main.tf, internal/command/testdata/show-json/plan-error/output.json, website/docs/internals/json-format.mdx
Closes #33368
1.5.x
- `terraform show -json`: Added `errored` field to indicate whether a plan succeeded.
=> `terraform show -json`: Add Errored field to output for plan

go.mod, go.sum, internal/getproviders/package_authentication.go, internal/getproviders/package_authentication_test.go
This PR updates Terraform's openpgp support away from the deprecated golang.org package to the maintained ProtonMail package.
This is the package recommended by the Go development team in https://github.com/hashicorp/terraform/pull/33131.
This PR is a combination of https://github.com/hashicorp/terraform/pull/33131 and https://github.com/hashicorp/terraform/pull/32056 as both have desirable features I think we should capture. I've merged them into this PR that I can merge and update easily.
=> Upgrade golang.org/x/crypto/openpgp to github.com/ProtonMail/go-crypto

website/data/language-nav-data.json, website/docs/language/modules/testing-experiment.mdx
I think this was accidentally deleted in https://github.com/hashicorp/terraform/pull/32771 and has left some dangling references. Once backported this PR should fix that for the 1.5 documentation.
=> Reinstate the accidentally deleted experimental testing page

go.mod, go.sum, internal/backend/remote/backend_state.go, internal/backend/remote/backend_state_test.go, internal/cloud/errored.tfstate, internal/cloud/state.go, internal/cloud/state_test.go, internal/cloud/testing.go, internal/cloud/tfe_client_mock.go
When using a cloud block and saving state, terraform cloud will no longer close the connection and fail to save with a gateway timeout response due to exceedingly large state or slow network operations. This utilizes a new platform feature to create a pending state version followed by uploading state content directly to the object store which has no gateway timeout. If the new feature is unavailable (during pre-release, or when using Terraform Enterprise) the legacy fallback is used.
1.5.1
Depends on the release of https://github.com/hashicorp/go-tfe/pull/717
When using a cloud block and saving state, terraform cloud will no longer close the connection and fail to save with a gateway timeout response due to exceedingly large or slow network operations.
=> cloud: when saving state, utilize new 'pending' state version

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
Several parts of the objchange logic incorrectly use cty.Value.RawEquals for value comparison, instead of more appropriate comparison methods like cty.Value.Equals or c.Value.Range().Includes. That makes them incorrectly consider two unknown values with the same type but different refinements as always non-equal, rather than evaluating based on the overlap between the refinements (if any).
As a short-term fix for that we previously added this unrefinedValue shim that just strips away the refinements for comparison, thus allowing callers to continue using RawEquals as long as they've already taken care of all of the other things that can make that go wrong, such as value marks. (Unfortunately the callers typically today handle that via a similar coarse technique: stripping out all of the …
=> plans/objchange: Support nested unknowns in our unrefinedValue shim

internal/command/test.go
My recent PRs managed to break the build when merging as they had dependencies I didn't realise. Sorry!
=> Fix the Terraform build after recent merges

internal/terraform/context_apply_test.go, internal/terraform/graph_builder_apply_test.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_apply_test.go, internal/terraform/transform_destroy_cbd_test.go, internal/terraform/validate_selfref.go
In order to ensure that transitive dependencies are connected even when there are no instances for a resource, we need to route the references through the config ("expand") node. This happens naturally by having the expand node report its config references, however legacy configs can contain self-references without the "self" identifier, so those need to be filtered out.
We can also remove the old `NodeApplyableResource` type, which was only there to call `writeResourceState` and can be done by `nodeExpandApplyableResource` without the expansion (the "Expand" node name in this context refers to the setting of the `instances.Expander`, not `DynamicExpand`)
Fixes #33370
=> connect references from config nodes during apply

website/docs/language/expressions/custom-conditions.mdx
This PR updates the custom conditions documentation to dissociate the use of pre- and post-conditions from Continuous Validation in Terraform Cloud.
1.5.2
=> docs: dissociate CV from preconditions and postconditions

internal/backend/remote-state/consul/client.go
Ran into this error while running terraform inside a container, after it applied my plans, terraform failed saving state to Consul. I suspect my policy needs tweaking, but it's near impossible to tell with an error like this:
```
╷
│ Error: Failed to save state
│ 
│ Error saving state: consul CAS failed with transaction errors:
│ [0xc0006e93c8]
╵
```
This PR changes the the rendering of the error instance to actually print the message, instead of the memory address of said error instance.
1.15.x
- When using consul as a state backend and failing to save state, `consul CAS failed with transaction errors` no longer shows an error instance memory address but an actual error message.
=> Return debuggable CAS errors on consul state put

internal/backend/remote-state/consul/client.go
1.5 backport of #33108. Original PR description:
---
Ran into this error while running terraform inside a container, after it applied my plans, terraform failed saving state to Consul. I suspect my policy needs tweaking, but it's near impossible to tell with an error like this:
```
╷
│ Error: Failed to save state
│ 
│ Error saving state: consul CAS failed with transaction errors:
│ [0xc0006e93c8]
╵
```
This PR changes the the rendering of the error instance to actually print the message, instead of the memory address of said error instance.
1.5.x
- When using consul as a state backend and failing to save state, `consul CAS failed with transaction errors` no longer shows an error instance memory address but an actual error message.
=> use multierror.Append instead of `append`

internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/structured/attribute_path/matcher.go
Terraform allows users to specify indexes as strings as long as the string can be converted into a number. For example, the following are equivalent:
- `test_resource.resource.list[0].attribute`
- `test_resource.resource.list["0"].attribute`
- `test_resource.resource.list["0.0"].attribute`
While the following would all raise validation errors.
- `test_resource.resource.list[0.5].attribute`
- `test_resource.resource.list["not a number"].attribute`
- `test_resource.resource.list["0.5"].attribute`
The plan renderer currently makes an assumption that the indices will be the appropriate type. This causes a panic when attributes like those listed above are included in the relevant attributes data, as the renderer will attempt to cast them into the wrong type.
This PR updates the logic for …
=> Plan renderer: Support users indexing integer paths with stringified numbers

internal/command/plan_test.go, internal/command/testdata/plan-existing-state/main.tf, internal/command/testdata/plan-existing-state/terraform.tfstate, main_test.go
A consumer relies on the fact that running `terraform plan -refresh=false -refresh=true` gives the same result as `terraform plan -refresh=true`. This depends on stdlib `flags` behaviour, handling of `TF_CLI_ARGS` in `main()`, and anything extra we do in `command`. Testing at `PlanCommand` seems appropriate to catch future regressions.
While adding this test I discovered the `TestPlan_refreshFalse` was non-functional: with the existing fixture, `ReadResource` would never be called, even with `-refresh=true`. Fixed this and also made the `main()` arg test more robust.
=> command: test plan -refresh= arg ordering

go.mod, go.sum, internal/cloud/backend_plan.go, internal/cloud/backend_plan_test.go, internal/cloud/cloudplan/saved_plan.go
This is it! We can use `terraform plan -out my.tfplan` in cloud mode to create an arbitrary number of saved plan runs, and then `terraform apply my.tfplan` one of the resulting plans to make it the workspace's next apply. 
Because `save-plan` is a new attribute in the runs API, it requires an update to go-tfe — https://github.com/hashicorp/go-tfe/pull/724
**To smoke test this:** Make sure your TFC org has been added to the saved-cloud-plans feature flag.
=> Implement `plan -out` with cloud integration

internal/terraform/context_apply_test.go, internal/terraform/node_output.go, internal/terraform/testdata/apply-destroy-provisider-refs/main.tf, internal/terraform/testdata/apply-destroy-provisider-refs/mod/main.tf
A module output is generally not used during destroy, however it must be evaluated when its value is used by a provider for configuration, because that configuration is not stored between walks.
There was an oversight in the output expansion node where the output node was not created because the operation was destroy, and module outputs have nothing to destroy. This however skipped evaluation when the output is needed by a provider as mentioned above. Because of the way an implied plan is stored internally when executing `terraform destroy`, this went unnoticed by the test.
Allowing the output to be evaluated during destroy fixes the issue, and should be acceptable because an output is classified as temporary in the graph, and will be pruned when not actually needed.
Update the existing …
=> always evaluate module outputs during destroy

internal/command/init.go
=> fix typo in terraform/internal/command /init.go

internal/command/test_test.go
This test is attempting to check the interrupt behaviour works as expected.
It has failed on at least one execution in `main`: https://github.com/hashicorp/terraform/actions/runs/5511524526/jobs/10047189970
I think there's a race condition in there in which the order of execution might affect the output. I've modified the piece of text the test is looking into something that is rendered by the framework before the cancellation process is started so it is something that should be displayed every time.
I do have some more work to do on the interrupts so I'll look at the tests again as part of that. This should be an acceptable short term fix in the mean time.
=> Make flaky 'TestTest_DoubleInterrupt' test more robust

website/docs/language/resources/provisioners/syntax.mdx
1.4.x
- Doc update: provide an example for using cloudinit and yamlencode in place of file provisioners.
=> [docs] Add example for using cloud-config in place of file provisioners

internal/command/get.go, website/docs/cli/commands/get.mdx
GetCommand uses [`ModulePath()`](https://github.com/hashicorp/terraform/blob/3732bffe1397dd8c482a6515383d009fe2d6ec44/internal/command/command.go#L61-L74) to determine the path to configuration files, but `ModulePath()` doesn't accept any arguments.
When a user specifies a `PATH` per the documentation they will receive a ["Too many command line arguments. Did you mean to use -chdir?" error](https://github.com/hashicorp/terraform/blob/3732bffe1397dd8c482a6515383d009fe2d6ec44/internal/command/command.go#L64-L66)
Fixes #29513
1.5.2
- The `get` command help text now specifies the correct usage syntax
=> Remove PATH from GetCommand helpText

website/docs/language/expressions/strings.mdx
Updates the `Expressions > Strings and Templates` docs to use the recommend [splat expression](https://developer.hashicorp.com/terraform/language/expressions/splat) syntax, with square brackets. While Terraform continues to support the `.*` syntax for resources with `count`, the docs describe them as "legacy 'attribute-only' splat expressions."
For good measure, I tested to confirm this works:
```tf
output "ips" {
value = <<-EOF
%{ for ip in aws_instance.example[*].private_ip }
server ${ip}
%{ endfor }
EOF
}
resource "aws_instance" "example" {
count = 2
instance_type = "t3.nano"
ami = "ami-0d593311db5abb72b"
}
```
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Outputs:
ips = <<EOT
server 172.31.52.27
server 172.31.53.123
EOT
```
=> docs: update splat expressions in directives

internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/expect_failures_resources/main.tftest, internal/moduletest/run.go, internal/moduletest/run_test.go, internal/terraform/eval_variable.go
This PR finishes up the `expect_failures` functionality for the new testing framework.
I previously did most of the work in #33443, and onboarded input variables into the checkable objects framework in #33481. With those 2 PRs merged, and any queued PRs modifying the test command also merged I can finish the functionality now.
This PR:
1. Removes check block warnings from the set of diagnostics produced by the plan when the testing framework is performing an apply command. This matches the behaviour in the main Terraform program, and keeps the outputs simpler for users.
2. Updates the diagnostics produced by input validation to attach the `CheckRuleDiagnosticExtra` structure, this is only possible now as input validation matches the behaviour of other checkable objects.
3. Updates the …
=> testing framework: finalise 'expected_failures' functionality

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go
The logic for skipping the cache was incorrect, causing core to spin up non-GetProviderSchemaOptional providers too often. 
Rather than conditionally setting the cache based on `GetProviderSchemaOptional`, we can conditionally _use_ the cache in the client to work around providers without `GetProviderSchemaOptional`, which allows core to still access the schema from the global cache and prevent repeatedly spinning up providers which don't have `GetProviderSchemaOptional` set. The client for these providers will have the schema also stored in the client instance to prevent additional `GetProviderSchema` calls, and act as a flag to ensure that `GetProviderSchema` has been called at least once.
=> always set schema caches from provider clients

internal/command/test_test.go, internal/command/views/test.go, internal/command/views/test_test.go
This PR simply adds the `format.WordWrap` function around long lines of text produced by the `TestHuman` view struct used the test command.
=> Implement word wrapping in the terraform test view functions

internal/command/views/test.go, internal/command/views/test_test.go
This PR makes the test output deterministic by printing the existing states in the order their run blocks are defined within the test file, instead of the order they are in the go map.
The test is failing in main but doesn't fail for me locally: https://github.com/hashicorp/terraform/actions/runs/5612594195/jobs/10271183062
=> Fix flaky test in views package

internal/backend/backend.go, internal/backend/local/backend.go, internal/backend/remote/backend.go, internal/backend/remote/backend_test.go, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/command/meta_backend.go
Previously, remote and cloud backends would automatically alias localterraform.com as the configured hostname during configuration. This turned out to be an issue with how backends could potentially be used within the builtin terraform_remote_state data source. Those data sources each configure the same service discovery with different targets for localterraform.com, and do so simultaneously, creating an occasional concurrent map read & write panic when multiple data sources are defined.
localterraform.com is obviously not useful for every backend configuration. Therefore, I relocated the alias configuration to the callers, so they may specify when to use it. The modified design adds a new method to backend.Enhanced to allow configurators to ask which aliases should be defined.
Fixes …
=> Relocate localterraform.com aliasing to backend configurators 

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/testing.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go
Convert S3 Backend implementation from `legacy/helper/schema` to `configschema` as part of modernization effort.
Relates #30443
This change should be invisible to practitioners
This change should be invisible to practitioners
=> S3 Backend: Converts from `legacy/helper/schema` to `configschema`

website/docs/language/meta-arguments/lifecycle.mdx
I've spent quite a lot of time to figure out the fact `create_before_destroy` meta-attribute propagates to all dependencies. Seems like I was not the only one who found this non-intuitive ([GitHub issue](https://github.com/hashicorp/terraform/issues/21610)). I think it's worth noting this behaviour in the documentation explicitly. I don't mind changing the text by maintainers if there is a better English variant.
Explains: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1906
- Document `create_before_destroy` meta-attribute propagation behaviour
=> docs: create_before_destroy meta-attribute propagation

internal/terraform/context_import_test.go, internal/terraform/testdata/issue-33572/main.tf, internal/terraform/transform_check.go
This PR fixes a crash that occurs when the `terraform import` command is used against configuration that has a nested data block defined within a check block.
Essentially, the nested data block still tries to report its checkable status during an import operation. This results in the checks system panicking as it is not expecting that kind of check to be reported. 
The fix in this case is just to make the full check block also execute during an import operation. Note, that this behaviour matches the behaviour of other checkable objects. Resource pre and post conditions still execute during the validate operation, they just report warnings instead of errors. As check blocks already only report warnings, making all checkable objects consistent in this case is as simple as turning on check …
=> Fix crash when nested data blocks are mixed with the import command

internal/command/fmt.go, internal/command/fmt_test.go, internal/command/testdata/tftest-fmt/main_in.tftest.hcl, internal/command/testdata/tftest-fmt/main_out.tftest.hcl
This PR just makes the `terraform fmt` command also load and process test files.
=> test framework: add support for testing files to fmt command

go.mod, go.sum
Upgrade go-getter to pull in the fix for #28968.
Full diff between v1.7.0 and v1.7.2: https://github.com/hashicorp/go-getter/compare/v1.7.0...v1.7.2
1.6.x
- Terraform will no longer override SSH settings in local git configuration when installing modules.
=> update go-getter to v1.7.2

CHANGELOG.md, internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/testing.go, internal/cloud/tfe_client_mock.go, website/docs/cli/cloud/settings.mdx
Adds project configuration to the workspaces section of the cloud block. Also configurable via the `TF_CLOUD_PROJECT` environment variable. When a project is configured, the following behaviors will occur:
- `terraform init` with workspaces.name configured will create the workspace in the given project
- `terraform workspace new <name>` with workspaces.tags configured will create workspaces in the given project
- `terraform workspace list` will list workspaces only from the given project
The following behaviors are NOT affected by project configuration
- `terraform workspace delete <name>` does not validate the workspace's inclusion in the given project
- When initializing a workspace that already exists in Terraform Cloud, the workspace's parent project is NOT validated against the given …
=> Add ability to specify Terraform Cloud Project in cloud block

internal/command/testdata/test/no_providers_in_main/main.tf
There's a race condition in the testing provider I built for the testing framework. where it can do concurrent reads/writes on the underlying data store. I've tried to fix it within the provider a couple of times but it's not been easy and I don't have time to spend ages on it right now. I will come back and revisit. However, a simple enough workaround is to just update the tests that use this provider so that they don't ever have a need for concurrent read/writes and so far this is not something the testing framework needs to worry about.
See here for an example failed test: https://github.com/hashicorp/terraform/actions/runs/5724121115/job/15509985171
=> Fix race condition in no_providers_in_main test

internal/command/import.go, internal/configs/import.go, internal/configs/import_test.go, internal/terraform/context_import.go, internal/terraform/context_import_test.go, internal/terraform/context_plan2_test.go, internal/terraform/eval_import.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/testdata/import-id-data-source/main.tf, internal/terraform/testdata/import-id-func/main.tf, internal/terraform/testdata/import-id-invalid-null/main.tf, internal/terraform/testdata/import-id-invalid-unknown/main.tf, internal/terraform/testdata/import-id-module/child/main.tf, internal/terraform/testdata/import-id-module/main.tf, internal/terraform/testdata/import-id-variable/main.tf
A simple approach permitting the import block id field to reference variables, attributes, and module outputs, as long as the result is a known non-empty string at plan time. A null or unknown value will result in an error.
This PR slightly modifies the legacy CLI terraform import code path to construct a synthetic `hcl.Expression` from the import id passed in from the command line, with no intended change of functionality. I thought this was a little better than maintaining two separate versions of the `configs.Import` and `terraform.ImportTarget` structs.
=> allow interpolation in import block id

internal/checks/state_test.go, internal/command/command_test.go, internal/command/get.go, internal/command/init.go, internal/command/meta_config.go, internal/initwd/from_module.go, internal/initwd/from_module_test.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/local-module-missing-provider/main.tf, internal/initwd/testing.go, internal/lang/globalref/analyzer_test.go, internal/refactoring/move_validate_test.go, internal/terraform/terraform_test.go
Some use cases like `cdktf` were using the Terraform CLI to fetch module sources to ensure consistent behavior with all source types, but are now blocked when retrieving a module which requires a provider configuration that they cannot provide during `init`. A new interface needs to be designed at some level to allow the `cdktf` use case without depending on internal implementation details, but in the meantime we can override the behavior from the CLI.
To revert the behavior, we allow the special cases of `init -from-module` and `get` to fetch the source, but any errors only returned by the validation of the config structure will be converted to warnings in the CLI. This won't allow the use of any invalid configuration, as the config will be fully validated by every other command, but …
=> Allow `get` and `init -from-module` to complete when there are configuration validation errors

internal/command/init.go, internal/command/init_test.go, internal/command/meta_backend.go, internal/command/testdata/init-syntax-invalid-backend-attribute-invalid/main.tf
This PR updates the backend initialisation logic so that if the value returned by parsing the configuration isn't wholly known it returns an error diagnostic instead of crashing. This happens because we try to delay returning diagnostics until we can validate the `required_versions` conditions.
This PR also tweaks the ordering of which diagnostics are returned first. Previously if the backend initialisation returned diagnostics those diagnostics would be reported instead of the config parsing diagnostics. I can see the logic in that, but there is no way to differentiate between there is an error in the backend initialisation and there was an error in the backend initialisation caused by an error in the configuration. Therefore, I think it's better to simply return the configuration errors …
=> Make config errors more important during init operations

internal/command/views/json_view.go
We updated the JSON outputs for the test framework in https://github.com/hashicorp/terraform/pull/33400 and forgot to bump the version number.
=> Update JSON_UI_VERSION after test framework changes

go.mod, internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/expect_failures_inputs/main.tftest.hcl, internal/command/testdata/test/expect_failures_outputs/main.tftest.hcl, internal/command/testdata/test/expect_failures_resources/main.tftest.hcl, internal/command/testdata/test/invalid_default_state/main.tftest.hcl, internal/command/testdata/test/only_modules/example/main.tf, internal/command/testdata/test/only_modules/main.tf, internal/command/testdata/test/only_modules/main.tftest.hcl, internal/command/testdata/test/partial_updates/main.tf, internal/command/testdata/test/partial_updates/main.tftest.hcl, internal/command/testdata/test/state_propagation/example/main.tf, internal/command/testdata/test/state_propagation/main.tf, internal/command/testdata/test/state_propagation/main.tftest.hcl, internal/command/testdata/test/state_propagation/second_example/main.tf
There are two pieces of feedback we've received from users during the testing alpha:
1. The requirement to have all variables defined at the file level has caused lots of confusion.
2. We have found a use case for having run blocks that call out to alternate modules share states.
This PR refactors the logic within the test command functionality to address both of the above pieces of feedback.
The requirement for this was that the final destroy operation needed values for the variables, and we didn't have a way of getting them otherwise. We now keep track of the last successful run block, this run block will have passed validation and will have defined values for all the variables. This means we can use the configuration and values for that run block to execute our destroy operation and we …
=> Implement updates to testing framework based on recent feedback

go.mod, go.sum, internal/cloud/backend_plan.go, internal/cloud/backend_plan_test.go, internal/cloud/tfe_client_mock.go
When creating cloud configuration versions, mark them as `provisional` when the plan is being saved locally. This means they do not become the workspace current configuration version unless they are later applied as well as the latest.
1.6.0
n/a
=> Create provisional configuration version when saving plan using cloud backend

internal/terraform/test_context.go
We've had lots of users getting confused with this error message, and I agree it's pretty bad. This should make it a lot more clear.
eg. https://gist.github.com/alexharv074/addc4d3dd369d28378d519774a260ce4
=> Update error message from an unknown Terraform Test condition

internal/command/test.go, internal/terraform/test_context.go, internal/terraform/test_context_test.go
I've recently discovered that the `apply` operation removes changes from the plan as it executes. This means that we don't need the duplicate `EvaluateAgainstState` and `EvaluateAgainstPlan` functions. We can just have a single `Evaluate` function that accepts both the state and the plan safe in the knowledge the plan will have been updated if it was applied.
=> Removing alternate functions for state and plan from `test_context.go`

internal/addrs/parse_ref.go, internal/addrs/parse_ref_test.go, internal/addrs/run.go, internal/command/meta_vars.go, internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/shared_state/main.tf, internal/command/testdata/test/shared_state/main.tftest.hcl, internal/command/testdata/test/shared_state/setup/main.tf, internal/command/testdata/test/shared_state_object/main.tf, internal/command/testdata/test/shared_state_object/main.tftest.hcl, internal/command/testdata/test/shared_state_object/setup/main.tf, internal/lang/data.go, internal/lang/data_test.go, internal/lang/eval.go, internal/lang/eval_test.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/evaluate_valid.go, internal/terraform/evaluate_valid_test.go, internal/terraform/test_context.go, internal/terraform/test_context_test.go
This PR updates the evaluation context for Terraform so that assertions and variable blocks within testing files can access the outputs of earlier run blocks.
The following example demonstrates how this is helpful to users who want to create temporary infrastructure to be used within their tests, but that infrastructure isn't something the module they are writing wants to manage themselves.
```hcl
run "setup" {
module {
source = "./create_vpc"
}
}
run "test" {
variables {
vpc_id = run.setup.vpc_id
}
assert {
condition = aws_security_group.primary.vpc_id == run.setup.vpc_id
error_message = "security group was assigned to the wrong VPC"
}
}
```
A big part of this change is the need to make "alternate state files" available to the evaluation context. As part of this, the …
=> Introduce 'run' keyword for referencing outputs from earlier run blocks

.copywrite.hcl, .github/workflows/build-terraform-oss.yml
This updates the linux package license to BUSL-1.1.
This PR should be merged to main so that the change is included in the next minor release that is cut from main.
License changes are not required on release branches (ongoing patch releases of current minor releases).
=> Update linux package license to BUSL-1.1

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, website/docs/language/settings/backends/s3.mdx
Adds support for the standard environment variables `AWS_ENDPOINT_URL_IAM`, `AWS_ENDPOINT_URL_S3`, `AWS_ENDPOINT_URL_STS`, and `AWS_ENDPOINT_URL_DYNAMODB` defined in https://docs.aws.amazon.com/sdkref/latest/guide/ss-endpoints-table.html
Deprecates the environment variables defined by the backend: `AWS_IAM_ENDPOINT`, `AWS_S3_ENDPOINT`, `AWS_STS_ENDPOINT`, and `AWS_DYNAMODB_ENDPOINT`.
Fixes #30479
1.6.0
S3 Backend: Adds support for standard environment variables for overriding AWS API endpoints `AWS_ENDPOINT_URL_IAM`, `AWS_ENDPOINT_URL_S3`, `AWS_ENDPOINT_URL_STS`, and `AWS_ENDPOINT_URL_DYNAMODB` . Deprecates `AWS_IAM_ENDPOINT`, `AWS_S3_ENDPOINT`, `AWS_STS_ENDPOINT`, and `AWS_DYNAMODB_ENDPOINT`.
=> backend/s3: Adds support for standard AWS endpoint environment variables and deprecates backend-specific envvars

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, website/docs/language/settings/backends/s3.mdx
Adds the `shared_config_files` and `shared_credentials_files` parameters and adds support for default AWS environment variables for credentials and configuration files, `AWS_CONFIG_FILE ` and `AWS_SHARED_CREDENTIALS_FILE`. This deprecates the `shared_credentials_file` parameter.
```console
% TF_ACC=1 go test -count=1 ./internal/backend/remote-state/s3/...
ok      github.com/hashicorp/terraform/internal/backend/remote-state/s3 102.007s
```
Relates #30493
1.6.0
-  Supports the default AWS environment variables for credentials and configuration files: `AWS_CONFIG_FILE ` and `AWS_SHARED_CREDENTIALS_FILE`. [GH-30493]
- Adds `shared_config_files` and `shared_credentials_files` parameters. This deprecates the `shared_credentials_file` parameter. [GH-30493]
=> backend/s3: support multiple shared config/credentials files

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/validate.go, website/docs/language/settings/backends/s3.mdx
This pull request implements the feature requested in https://github.com/hashicorp/terraform/issues/31244.
Currently the [S3 Backend](https://www.terraform.io/language/settings/backends/s3) does not support assuming a role with web identity. As we already support assuming a different role as part of the S3 backend this seems like a valid request.
Next to that I think that it's also right to have feature parity with the [Terraform AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume_role_with_web_identity-configuration-block) as they added the OpenID Connect (OIDC) support too recently.
OIDC allows GitHub Actions and other CI/CD pipelines to access resources in Amazon Web Services (AWS), without needing to store the AWS credentials as long-lived GitHub …
=> Add assume role with web identity support for the S3 backend

internal/command/test.go, internal/command/test_test.go, internal/command/testdata/test/bad-references/main.tf, internal/command/testdata/test/bad-references/main.tftest.hcl, internal/command/testdata/test/variable_references/main.tf, internal/command/testdata/test/variable_references/main.tftest.hcl, internal/command/testdata/test/variables_types/main.tf, internal/command/testdata/test/variables_types/main.tftest.hcl
This PR updates the testing framework to support variable references from inside run variable blocks. For example:
```hcl
variables {
shared_resource_id = "... some value ..."
}
run "setup_resources" {
module = {
source = "./setup
}
variables {
id_for_resource_to_be_created = var.shared_resource_id
}
}
run "actual_test" {
variables {
is_for_resource_that_is_supposed_to_exist = var.shared_resource_id
}
}
```
This allows users to share variable values between run blocks even if the modules they are referencing don't share variables with the same name.
In addition, this PR adds some validation into the `EvalCtx` and variable functions so the errors and diagnostics they produce are customised to the testing framework. For example now they will reference the actual run block where the error …
=> Allow referencing higher level variables from run blocks

internal/grpcwrap/provider.go
Reference: https://github.com/hashicorp/terraform/blob/7094517089e9a01d9aa94838f583898549e5a6de/internal/grpcwrap/provider6.go#L72
The server capability is passed through with version 6, but not version 5. (Sorry missed this with last change.)
1.6.x
N/A
=> internal/grpcwrap: Ensure GetProviderSchemaOptional server capability is passed through

go.mod, go.sum
Fixes https://github.com/hashicorp/terraform/issues/33464 a little closer to the root.
https://github.com/hashicorp/hcl/issues/616 fixes the effect of this in HCL templates (there is no HCL release as yet).
Changelog for cty 1.13.3:
* `msgpack`: As a compromise to avoid unbounded memory usage for a situation that some callers won't take advantage of anyway, the MessagePack decoder has a maximum length limit on encoded unknown value refinements. For consistency, the encoder will now truncate string prefix refinements if necessary to avoid making the encoded refinements too long. ([#167](https://github.com/zclconf/go-cty/pull/167))
This is consistent with the documented conventions for serializing refinements -- that we can potentially lose detail through serialization -- but in this case …
=> upgrade go-cty to v1.13.3

internal/command/jsonformat/plan.go, internal/command/jsonformat/state.go, internal/command/jsonplan/module.go, internal/command/jsonplan/plan.go, internal/command/jsonplan/resource.go, internal/command/jsonplan/values.go, internal/command/jsonplan/values_test.go, internal/command/jsonstate/state.go, internal/command/views/test.go, internal/command/views/test_test.go
This is going to be used when we integrate with TFC. We will consume JSON outputs and turn them back into human-readable output. Now, the verbose outputs are already in the format accepted by the renderer, whereas previously we would've had to load the schemas separately.
This PR also reverses the changes that made our JSON implementation more public in #33504. We don't need this anymore as we are just using the already public fields that our renderer requires.
=> Embed the schemas directly in the testing framework JSON verbose outputs

internal/command/test.go, internal/command/test_test.go
This is to ensure that during TFC executions Terraform won't try and load / read from directories outside of the uploaded configuration directory.
=> Terraform test directory must be local to the config directory

internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/invalid-module-name/child/main.tf, internal/initwd/testdata/invalid-module-name/main.tf
We install remote modules prior to showing any validation errors during init so that we can show errors about the core version requirement before we do anything else. Unfortunately, this means that we don't validate module _names_ until after remote modules have been installed, which may cause unexpected problems later if the module name is not a valid path.
1.6.x + 1.5.x
- Terraform will no longer allow downloading remote modules to invalid paths.
=> initwd: require valid module name

CHANGELOG.md, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/invalid-module-name/child/main.tf, internal/initwd/testdata/invalid-module-name/main.tf
Manual backport of https://github.com/hashicorp/terraform/pull/33745
=> v1.5 backport of initwd: require valid module name

website/docs/language/settings/backends/s3.mdx
Small documentation enhancement to include the corresponding s3 backend configurations for the IAM policies provided in the "Protecting Access to Workspace State" section.
Closes #30445
Relates #33687
1.6.x
=> backend/s3(docs): expand access control examples

CHANGELOG.md, internal/command/unlock.go
`terraform force-unlock` should allow backends to ignore version conflicts since it does not write state.
Fixes #28853 
1.6.0
=> Ignore remote version conflict for force-unlock

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/null-outputs/main.tf, internal/command/testdata/test/null-outputs/main.tftest.hcl, internal/terraform/evaluate.go
This PR updates the test framework so it doesn't assume all outputs defined in the config are populated in the state. If an output returns null during a Terraform execution it is simply skipped and not added to the state instead of added as a null value. This was causing a panic as the test framework was assuming all outputs would be present in the state.
Fixes #33780 
1.6.0-beta2
=> Handle null outputs in Terraform test files

website/docs/language/expressions/types.mdx
- Add `set` to the types list on the `types.mdx` page.
- Clarify relationship between complex types.
- Link to Type Constraints page for more detailed information on types.
_Note: this definition of `set` is copied from the Type Constraints page, though that language may not be clear in this context. Rather than risk making a technical error, I opted to stay with the same text._
1.4.x
N/A
=> clarify types and link to Type Constraints pagedit types

internal/states/statefile/version4.go
Terraform 1.5 introduced a new check result kind, which causes a decode failure when read by Terraform 1.3 and 1.4. This means that a 1.5+ state file cannot be read by the `terraform_remote_state` data source in 1.3 or 1.4 series.
Aborting state decode at this point isn't strictly necessary, as we don't stand to lose important data by failing to round-trip these check results. Instead we can ignore those check results, allowing decode to elide them from the state.
This has no negative effect on the remote state data source, which only exposes root module outputs anyway.
- 1.7.0
- 1.6.0
- 1.5.7
- `terraform_remote_state`: prevent future possible incompatibility with states which include unknown `check` block result kinds.
=> statefile: Ignore unknown check results on decode

website/docs/language/expressions/types.mdx
The backport in #33789 went to v1.5 instead of v1.6.
This ensures v1.6 tracks main correctly.
=> v1.6 backport of #33132

website/docs/language/expressions/types.mdx
Revert the incorrect wording from #33132, but keep the addition of `set` and the extra documentation link.
=> re-clarify types documentation

internal/cloud/state.go, internal/cloud/state_test.go
1.7.0, 1.6.0, 1.5.7
cloud: state snapshots could not be disabled when header x-terraform-snapshot-interval is absent
=> cloud: state snapshots always enabled despite missing header x-terraform-snapshot-interval

go.mod, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go, website/docs/language/settings/backends/s3.mdx
Adds acceptance tests for API endpoint overrides. Adds validation to endpoint parameters, since the endpoints must be specified as URLs.
1.6.0
-  backend/s3: Adds validation to ensure AWS API endpoint overrides are specified as URLs
=> backend/s3: Adds tests for endpoint overrides and adds validation for parameters

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/destroy_fail/main.tf, internal/command/testdata/test/destroy_fail/main.tftest.hcl, internal/command/testing/test_provider.go
This PR fixes an oversight in the testing framework. Previously, if the testing framework failed to clean up created resources it would still report the overall operation as a success. This means that CI pipelines and TFC could fail to sufficiently warn the user that the resources were not cleaned up. This PR marks a test file has having errored if it cannot clean up the resources, this is in turn ensures the overall command will return an error code of 1 if a test cleanup fails.
=> Make the test command fail if resources could not be cleaned up

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client.go, internal/backend/remote-state/s3/logging.go
Restores HTTP request/response logging for the S3 backend.
1.6.0
=> backend/s3: Restore HTTP request/response logging

internal/cloud/state.go, internal/cloud/testing.go
Some go-tfe methods perform multiple requests, some of which are not expected to contain a `x-terraform-snapshot-interval` header. This leads to the interval becoming unset after it is set. I decided to use the response content-type header to signal that the absence of the header is intended to unset the interval.
1.5.x, 1.6.0, 1.70
I will manually backport this as I already have two relevant backport PRs: #33835 #33834
```
2023-09-07T20:29:19.316Z [TRACE]  Intermediate state interval is set by header to 20s
2023-09-07T20:29:19.461Z [TRACE]  Skipping intermediate state interval because Content-Type was ""
2023-09-07T20:29:19.462Z [TRACE]  Skipping intermediate state interval because Content-Type was ""
2023-09-07T20:29:20.452Z [TRACE]  Intermediate state interval is set by header to 20s …
```
=> cloud: don't update snapshot interval unless response is from tfe.v2

website/docs/language/settings/backends/s3.mdx
Our S3 backend documentation previously asserted that DynamoDB doesn't support precise enough IAM policies to write per-environment access policies for S3 backend locking.
In the meantime the DynamoDB team added new capabilities for matching with various DynamoDB-specific condition keys, so we can now show an example of an environment-specific locking permission and also link to the relevant DynamoDB documentation for more details.
While working on this I noticed that this "Multi-account AWS Architecture" section would probably more at home on HashiCorp Learn in our modern documentation architecture, since it's much more like a tutorial than the typical content on these pages, but for the moment I've just updated it in-place and we can consider relocating it to Learn, or writing some new …
=> website: DynamoDB now supports fine-grain IAM policies

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go
With the AWS Go SDK V2, URI cleaning of S3 object URLs is no longer done by default. As such, `key` values containing double slashes (`//`) could introduce situations where an existing statefile cannot be read. This additional validation step disallows keys containing double slashes to prevent this.
Prevention of leading and trailing slashes (also potential failure points with AWS Go SDK v2) is already done via the `validateStringS3Path` validator.
```console
% TF_ACC=1 go test ./internal/backend/remote-state/s3/...
ok      github.com/hashicorp/terraform/internal/backend/remote-state/s3 122.148
```
Relates #33687
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33358 (changes to URI cleaning discovered during SDK upgrade of this resource in the AWS Provider)
1.6.x
N/A - …
=> backend/s3: prevent keys containing double slashes

internal/backend/remote-state/s3/client.go, internal/backend/remote-state/s3/client_test.go
Fixes https://github.com/hashicorp/terraform/issues/28496
**The Problem:** Currently, if S3 checksums don't match up with what terraform expects when running a plan/apply, it prints out only what it calculated the digest to be for the state in question. This can lead to difficulty debugging as in the issue linked above. In my case, one remote state call of many failed with this error, and it was really difficult to figure out which state was actually failing, or even that it was a remote state (rather than the state for my project) that was failing.
**Solution:** This PR adds more detail to the error message emitted when S3 states don't have the expected checksum, letting the user know exactly which state failed, and what it was expected to be. As a (slightly redacted) example:
```
│ …
```
=> Improve error message when S3 state checksums don't line up

internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client_test.go
The AWS SDK for Go v1 had a special case error when a bucket is requested from the wrong region. The SDK v2 does not, and does not include the region information in the error even though the text references it.
Relates #29254
1.6.0
Not user facing
=> backend/s3: Handles case when bucket is requested from wrong region

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go
Updates internal schema to include `singleNestedAttribute` type and updates backend schema to use it for nested attributes.
1.6.0
No user facing change
=> backend/s3: Adds `singleNestedAttribute` to internal schema

website/docs/cli/commands/test.mdx
Add quick documentation for the new `cloud-run` option introduced in #33710.
=> Add cloud-run documentation for testing framework

website/docs/cli/commands/test.mdx
This is a manual backport of #33875 in v1.6
The automated backport went a bit crazy: #33888.
=> Manual backport of Add cloud-run documentation for testing framework in v1.6

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/default_optional_values/main.tf, internal/command/testdata/test/default_optional_values/main.tftest.hcl
This PR makes the testing framework apply the defaults for input variables before using them in assertions.
Fixes #33864 
`v1.6.0-beta2`
=> Apply defaults when processing variables for assertions

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/expected_failures_during_planning/check.tftest.hcl, internal/command/testdata/test/expected_failures_during_planning/input.tftest.hcl, internal/command/testdata/test/expected_failures_during_planning/main.tf, internal/command/testdata/test/expected_failures_during_planning/output.tftest.hcl, internal/command/testdata/test/expected_failures_during_planning/resource.tftest.hcl, internal/moduletest/run.go
Currently if you mix `expect_failures` and `command = apply` you can get some confusing behaviour. Essentially the expected failure might happen during the planning stage, in which case Terraform doesn't produce a valid plan and the apply stage can't happen. This means the test fails, as the user asked for an apply operation, but the diagnostics can only really report the reason the test failed is because the thing the user expected to fail actually did fail. This is confusing as the user only really sees that the test failed even though they told it to expect the failure, while the test really failed because it could not execute the apply operation.
This PR adds a warning diagnostic that triggers in the described case. It adds a warning to the returned set of diagnostics that …
=> Add warning when testing and combining expect_failures with apply operations

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/middleware.go
Uses a middleware handler to return `bucketRegionError` for all S3 operations.
Works around https://github.com/aws/aws-sdk-go-v2/issues/2282
1.6.0
Not user facing
=> backend/s3: Add wrong bucket region handling to all of S3 client

internal/terraform/eval_import.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan.go, internal/terraform/testdata/import-id-variable/main.tf, internal/terraform/testdata/import-id-variable/mod/main.tf, internal/terraform/transform_reference.go
Even though import block evaluation is done in conjunction with their target resource block, their evaluation scope must always be the containing module of the import block. Since import blocks currently are only valid in the root module, that means the context must always always be the root module.
The references for the import evaluation must also be scoped to the root module where the block was written. In order to accomplish that without adding a new import node type to the graph, we instead can opt to add a new method (and associated `GraphNodeImportReferencer` interface) which separates the import references from the config references. The `ReferenceTransformer` can then use the correct root module path to lookup the referenced subjects when they come from `ImportReferences` as …
=> import blocks are evaluated in the root module

internal/configs/configschema/coerce_value.go, internal/configs/configschema/coerce_value_test.go
Adds a new error case to the `configschema.CoerceValue` function which provides improved messaging in cases where an attribute has none of `Required`, `Optional`, or `Computed` set to `true`. Previously this condition resulted in an error message like:
```
attribute "foo" is required
```
With this proposed change the messaging would change to:
```
attribute "foo" has none of required, optional, or computed set
```
Relates #33884 - The S3 backend had misconfigured nested attributes which _should_ have been optional, but instead omitted requirements entirely. When referenced by the `terraform_remote_state` data source, this resulted in a failed value coercion and an error message stating these attributes were required. With this change the error message would have instead stated the real …
=> configschema: CoerceValue error for omitted attribute requirements

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go
Adjusts the `singleNestedAttribute` struct such that one of `Required` or `Optional` is always set to `true` on the underlying schema. Defaults to optional. Previously the single nested attribute type arguments (`assume_role`, `assume_role_with_web_identity`, and `endpoints`) did not set either `Required` or `Optional` to `true`. This resulted in failures coercing the `terraform_remote_state` data sources `config` argument to the updated backend schema in 1.6.0. See the linked issue for additional context.
Before:
```console
% go test ./internal/backend/remote-state/s3/... -run="^TestBackend_CoerceValue/basic$"
--- FAIL: TestBackend_CoerceValue (0.00s)
--- FAIL: TestBackend_CoerceValue/basic (0.00s)
backend_test.go:2129: wrong error
got:  attribute "assume_role_with_web_identity" is …
```
=> backend/s3: set required or optional for single nested attributes

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/middleware.go
Backport of #33885
---
Uses a middleware handler to return `bucketRegionError` for all S3 operations.
Works around https://github.com/aws/aws-sdk-go-v2/issues/2282
1.6.0
Not user facing
=> Backport of backend/s3: Add wrong bucket region handling to all of S3 client into v1.6

.github/workflows/main.yml
Update the backport-assistant tool that helps us with backporting to release branches.
=> use latest backport-assistant

website/docs/language/tests/index.mdx
I took the existing run blocks list and converted it into a table for better readability. 
1.6 Beta or GA
=> [Docs Fix] Add table for run block in testing docs and remove doubled notes

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, website/docs/language/settings/backends/s3.mdx
Adds `source_identity` to `assume_role` block
1.6.0
=> backend/s3: Adds `source_identity` to `assume_role` block

internal/cloud/test.go, internal/cloud/tfe_client_mock.go
In some cases, for example a cancellation before the tests start executing because the test run is still in the queue or because of an error in atlas or the agent of some kind, we don't set the `TestStatus` on run object returned by TFC.
Previously, we were only looking at this when trying to work out the overall status of the run. This was causing a panic as an empty status was entering an unknown default branch of a switch statement. Now we look at the overall status of the Terraform Cloud run, and only look at the specific test status if overall run has been marked as finished.
I've updated our local mocks to reflect this behaviour, and was able to replicate. So the mocks have been updated and we don't need to add a new test just for this.
=> Fix panic when tests on TFC exit early

internal/cloud/test.go, internal/cloud/test_test.go, internal/cloud/tfe_client_mock.go
This PR updates the cancellation logic so that it continues listen for signals even while it is reading the logs from a cloud run.
Previously, we only listened for interrupt signal while we were waiting for the tests to start. Now, we are intercepting the signal at all times during the process. I've added a test that triggers the cancel signal during the log reading process, and then validates it still correctly marks the test run as being cancelled.
=> Refactor cloud test run cancellation logic to always intercept signals

internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client.go, internal/backend/remote-state/s3/client_test.go
Enables checksum in `PutObject` and `UploadPart` requests to support S3 buckets with Object Lock enabled.
Fixes #23127
1.6.0
-  S3 Backend: Fixes error when storing state in S3 buckets with Object Locks enabled
=> backend/s3: Supports S3 buckets with Object Lock

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/with_interrupt_and_additional_file/main.tf, internal/command/testdata/test/with_interrupt_and_additional_file/main.tftest.hcl, internal/command/testdata/test/with_interrupt_and_additional_file/skip_me.tftest.hcl
This change will also explicitly mark test files that are fatally interrupted as having errored.
=> Test files should be marked as skipped if all their run blocks were skipped

internal/cloud/test.go, internal/cloud/test_test.go, internal/cloud/tfe_client_mock.go
This PR changes the cancellation signal to send a second `Cancel` request instead of a `ForceCancel` request.
This should make the TFC API send a second SIGINT signal instead of a SIGTERM signal which will Terraform to still handle the cancel properly within the agent.
As part of this, the cloud implementation no longer allows skipping the stopped signal to trigger the cancel signal directly (otherwise, we'd never allow two cancel signals to be triggered). I also tweaked the tests so the test runs for the cancel tests won't ever finish naturally, but must be cancelled. This makes them more robust against any potential race conditions.
=> Implement double cancel instead of force cancel for test cloud runs

internal/command/test.go
It takes longer than 10 seconds for the interrupt signal to make it's way to the agent for cloud runs. So we'll wait longer in the CLI.
=> Increase timeout length after fatal interrupts for test cloud runs

internal/configs/config.go, internal/terraform/graph.go, internal/terraform/node_check.go, internal/terraform/node_local.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_expand.go
Continuing the tidy-up in https://github.com/hashicorp/terraform/pull/33932. 
One of the FIXMEs is in a code block that appears to be redundant. @liamcervante perhaps you agree 06b65907c2ecd6d4f8c961b0dcd73efd8c6b41f3
Also plumbed diags through DynamicExpand to resolve the FIXME in `resourceInstanceSubgraph`.
=> configs/terraform: refactor expansion code, add diags

internal/cloud/backend.go, website/docs/cli/cloud/settings.mdx
This fixes a typo in the markdown docs and aligns the description in code with the description in markdown. AFAICT the description in code isn't currently used anywhere.
1.6.x
=> cloud: Fix typo & align `project` field description

go.mod, go.sum
These each fix some different bugs related to handling of "refined" unknown values, both of which were causing panics with some input.
Fixes #33977, along with another separate bug reported in a comment on that issue.
=> go.mod: cty v1.14.1 and HCL v2.18.1

internal/getproviders/package_authentication.go, internal/getproviders/package_authentication_test.go, internal/getproviders/registry_client_test.go
The community fork of the `openpgp` package chosen by Terraform added unconditional verification of key expiration when validating signatures, which under normal circumstances is a welcome hardening of the API. This impact of this change however was overlooked when migrating to the new package, and it interfered with the current workflow set by the Terraform Registry.
Provider developers are not currently required to keep the signing keys stored in the Registry up to date, and older releases may be signed with a key which has since expired. For our purposes here however, we are validating the key and signature used at the time of publishing, and given that the Registry has previously vouched for the validity of the key used, we can continue to trust that key returned by the Registry for …
=> cli: ignore expired provider signing keys from registry during init

internal/backend/remote-state/s3/backend.go, website/docs/language/settings/backends/s3.mdx
As recent (1.6) changes to the s3 backend are breaking for anyone using an s3 api without STS API (like minio), this PR introduces a `skip_requesting_account_id` param analogously to the [aws provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id).
Fixes #33983
1.6.1
-  Add `skip_requesting_account_id` param to s3 backend for use with S3 APIs without STS.
=> Add skip_requesting_account_id Parameter to S3 Backend

internal/cloud/backend.go, internal/cloud/backend_test.go, internal/cloud/errors.go
Fixes #33976 
This bug was introduced in https://github.com/hashicorp/terraform/pull/33489 (adding `project` to the cloud config). Analyzing the flow of logic around config handling for the cloud backend took, a long time, which convinced me that a bug like this was honestly pretty inevitable — this code was too complex to safely edit. 
So, this PR refactors that whole zone to draw some sharper divisions of responsibility:
- `PrepareConfig` does almost nothing, as per the interface contract (which we were previously ignoring).
- Combining env vars with the received config block is now isolated in an immutable helper function, and the logic is now a bit more pedantic and obvious, hopefully making it harder to misunderstand in the future.
- `Configure` no longer delegates to the intensely …
=> Fix cloud integration's handling of TF_WORKSPACE environment variable

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go
Relaxes endpoint URL validation for S3, DynamoDB, IAM, and STS to emit a warning rather than an error for incomplete URLs. The IMDS endpoint requires a complete URL, because [`url.Parse`](https://pkg.go.dev/net/url#Parse) places bare hostnames in the `Path` field of `url.URL` and the IMDS client overwrites the `Path`.
According to the [AWS documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html), the endpoint parameters should be full URLs.
Fixes #33981
1.6.1
- Relaxes validation for S3, DynamoDB, IAM, and STS endpoint parameters
=> backend/s3: Relax endpoint validation rule

internal/backend/remote-state/s3/validate.go, internal/backend/remote-state/s3/validate_test.go
Release 1.6.0 broke the ability to use s3 key aliases in the s3 backend. This change adjusts the tests, and validation of kms key arn's to look for aliases
Fixes #33979
Fixes #34005 
1.6.1
- Fixes the ability to use KMS key aliases in the S3 backend
=> fix(s3): allow aliases for kms key

CHANGELOG.md
Aggregating S3 backend changelog entries for the `v1.6.1` release.
Relates #34031
Relates #34037
Relates #34038
1.6.1
- backend/s3: S3, DynamoDB, IAM, and STS endpoint parameters will no longer fail validation if the parsed scheme or hostname is empty. ([#34017](https://github.com/hashicorp/terraform/pull/34017))
- backend/s3: Providing a key alias to the `kms_key_id` argument will no longer fail validation. ([#33993](https://github.com/hashicorp/terraform/pull/33993))
- backend/s3: The `skip_requesting_account_id` argument supports AWS API implementations that do not have the IAM, STS, or metadata API. ([#34002](https://github.com/hashicorp/terraform/pull/34002))
=> backend/s3: v1.6.1 changelog entries

go.mod, go.sum
Fixes regression in v1.7.2 where GIT_SSH_COMMAND would always be overwritten.
Fixes #33985
Fixes #33986
=> update go-getter v1.7.3

website/docs/language/settings/backends/s3.mdx
Updates the S3 backend documentation examples for the `assume_role` and `assume_role_with_web_identity` arguments to use the correct syntax for single nested objects.
Fixes #33994 
1.6.x
N/a - docs
=> backend/s3(doc): fix assume_role example syntax

internal/states/statefile/version4.go
This PR skips variable validations when it comes time to write variables into the state file for the v1.6 series. This ensures that we won't see errors when earlier series try to read remote state from the v1.6 releases, and users can switch between Terraform versions.
This is intended to be a temporary workaround only, when v1.7 releases we will see the same errors again but we will have given users more time to update to either the 1.6 series or later, or to the latest patch release in their minor series.
Fixes #34014 
1.6.2
-  Fix interoperability issues between v1.6 series and earlier series by removing variable validations from the state file.
=> Skip writing variable validations into the state file

scripts/staticcheck.sh, staticcheck.conf
Turns out go-staticcheck will respect a config file and merge configs across subtrees of packages.
- [Staticcheck configuration methods](https://staticcheck.io/docs/configuration)
- [List of config options](https://staticcheck.io/docs/configuration/options/)
Since we already specify a list of staticcheck rules to ignore in the scripts/staticcheck.sh wrapper script, this hoists those preferences up to the top of the package tree, so they also affect the staticcheck integration in editors like VSCode. This avoids unnecessary yellow-squiggles for capitalized error messages, and makes integrated linting much more useful.
1.7.x
N/A; this has no runtime effect on Terraform.
=> Add staticcheck.conf to reduce unactionable noise in IDEs

CHANGELOG.md, go.mod, go.sum
When state version creation fails in terraform 1.6 (for instance, due to staleness), go-tfe was neglecting to return that error and crashing terraform with a nil pointer dereference panic. (See https://github.com/hashicorp/go-tfe/issues/791)
1.6.2
cloud: Fixes panic when saving state after Terraform Cloud returns certain types of API errors
=> Bump go-tfe, fix panic for certain kinds of state create errors

internal/terraform/context_apply_checks_test.go, internal/terraform/node_check.go, internal/terraform/transform_destroy_edge.go
The `nodeExpandCheck` node in the Terraform graph wasn't correctly marked as a `graphNodeExpandsInstances` object, which meant that when it was nested within a module that required expansion, and that module had no other changes to apply, we'd see the crash in the linked issue as the module would not apply its expansion logic.
This PR marks the `nodeExpandCheck` as `graphNodeExpandsInstances` so the graph will still expand modules that have check blocks in them. In addition, we need to then tell the `pruneUnusedNodesTransformer` to never prune check block nodes as we always want them to execute. Since they are now marked as `graphNodeExpandsInstances`, they would always be pruned as they have no references.
Fixes #34062 
1.6.2
-  `checks`: Fix a crash that occurs when checks blocks are …
=> Fix crash on check blocks in modules with no other changes

website/docs/language/functions/uuid.mdx
Documentation fix: the uuid function is not RFC compatible.
I copied over the relevant description and clarification from [go-uuid](https://github.com/hashicorp/go-uuid) which the uuid function is using.
=> fix uuid documentation: it is not RFC compatible

internal/backend/local/backend_local.go, internal/backend/local/test.go, internal/command/test_test.go, internal/terraform/test_context.go
This PR adds in the concept of "relevant variables" to the testing framework. Previously, each run block would process every available variable and attempt to parse even those they had no need for. This resulted in some edge case behaviour as seen in the linked issue. Now, each run block first calculates the variables it needs, and then exclusively processes the subset of required variables.
In addition, this PR does some refactoring of the variables processing. Previously, the variables were processed in their entirety twice: once for the test itself, and then once again for the assertions after the test has finished. Now, we only process the variables once at the beginning of each run and use mutator functions `FilterVariablesToConfig` and `AddVariablesToConfig` to achieve the required …
=> Process only relevant variables in the testing framework

website/docs/language/import/generating-configuration.mdx
This PR fixes a broken syntax example in the `import/generating-configuration` documentation.
1.5.x/1.6.x
N/A. This change is a documentation fix only.
=> Fix generated configuration example syntax in docs

internal/configs/config.go
Just dealing with another FIXME.
This block of code iterated through `import` blocks, adding to reqs the implied provider for each import target.
This is redundant, because for any `import` block, either there exists a corresponding `resource` block in config, or there does not and config will be generated.
If the `resource` block already exists, the provider requirement will be added by code earlier in `addProviderRequirements`. If the `resource` block does not exist, the provider requirement will be added by the code block directly following this one.
The above applies whether or not the target of the `import` block is in a child module. If a child module has a different local name for a provider, that provider must be in `required_providers`, so again it will be added to the provider …
=> configs: remove redundant provider reqs

go.mod, go.sum
HCL v2.19.0 
Enhancements
- ext/dynblock: dynblock.Expand now supports an optional hook for calling applications to check and potentially veto (by returning error diagnostics) particular for_each values. The behavior is unchanged for callers that don't set the new option. (https://github.com/hashicorp/hcl/pull/634)
Bugs Fixed
- hclsyntax: Further fixes for treatment of "marked" values in the conditional expression, and better tracking of refined values into the conditional expression results, building on the fixes from v2.18.1. (https://github.com/hashicorp/hcl/pull/633)
-----
Fixes #34060
=> update hcl v2.19.0

internal/terraform/context_apply2_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_module_variable.go, internal/terraform/node_root_variable.go, internal/terraform/transform_module_variable.go, internal/terraform/transform_variable.go
This PR makes Terraform skip variable validations during destroy plans and applys. This makes variable validations match the behaviour of other custom conditions which also do not execute during destroy operations.
This has the side effect of fixing the crash in the linked issue, as the variable validations will no longer attempt to sometimes execute during destroy-apply operations after having been skipped during the equivalent plan operation.
Fixes #34052
1.6.2
-  Fix occasional crash when destroying configurations with variables containing validations.
=> Skip variable validations during destroy plans

go.mod, go.sum, internal/command/jsonconfig/config.go, internal/configs/configschema/decoder_spec.go, internal/configs/configschema/decoder_spec_test.go
Update hcl to v2.19.1, which fixes an issue where the decoder can return null or unknown values which still contain optional attribute type constraints.
Remove invalid configschema tests. Schema attributes must have a type to be valid. These would have panicked anyway when used in other cases, but were passing within the limited test case. The update to hcl makes these panic earlier, so add our own panics to prevent invalid attribute schemas entirely.
We can be fairly certain these panics didn't affect actual functionality outside of the synthetic tests, because `hcldec` was returning an invalid `cty.NilVal` with no error, which itself would have panicked later if used.
=> update hcl v2.19.1

internal/configs/import.go, internal/configs/import_test.go
A data source should not be importable, and will crash if config generation is attempted. Validate the target type early to prevent errors during the plan.
=> data sources cannot be imported

website/docs/language/functions/flatten.mdx
Add a sensible default value for `networks` variable for `flatten` function
Fixes #33017 
1.4.x
- Affects https://github.com/hashicorp/terraform/blob/main/website/docs/language/functions/flatten.mdx
- Expands [Flattening nested structures for `for_each`](https://developer.hashicorp.com/terraform/language/functions/flatten#flattening-nested-structures-for-for_each) section by adding a default value for `networks` variable example
- CIDR ranges are dummy
=> Add a default value for networks variable for flatten example

website/docs/cli/commands/fmt.mdx
1.5.x
Specify the action of `terraform fmt` without any flags
-  
Hi,
This trivial commit only specifies (again) what the default action of `terraform fmt` does as some coworkers didn't know how to use it.
Cheers
=> website: doc: fmt: specify "no flag" action

website/docs/language/settings/backends/s3.mdx
Explicitly documents the `s3` backend support model for "S3 compatible" storage providers. This has always been "best effort" with no guaranteed support, but has not been formally stated in the backend documentation.
Relates #34086 
Relates #34053 
Relates #33847
Relates #19733
Relates #34099
1.6.x
N/a docs
=> backend/s3(doc): s3 comptible storage support model

website/docs/language/expressions/version-constraints.mdx
Add another example to `~>` operator, following https://thoughtbot.com/blog/rubys-pessimistic-operator 
1.5.x
-  Improve "Version Constraints" doc.
=> website: doc: Add another example to `~>` operator

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client.go, internal/backend/remote-state/s3/client_test.go, website/docs/language/settings/backends/s3.mdx
Some "S3-compatible" APIs do not support the header `x-amz-sdk-checksum-algorithm`. In the S3 API, a checksum is recommended and is required when Object Lock is enabled.
Allow users to disable the header.
Fixes #34099
Fixes #34086
Relates https://github.com/hashicorp/terraform/issues/34053#issuecomment-1767392693
1.6.2
- backend/s3: Allows users to disable checksum on S3 uploads for compatibility with "S3-compatible" APIs
=> backend/s3: Adds parameter `skip_s3_checksum` to skip checksum on upload

website/docs/language/resources/syntax.mdx
New to Terraform, I was reading the docs to learn about the syntax.
My changes do not remove any information and include:
- minor text changes.
- some changes to the order of information to create a more logical flow.
- moving links to the sentence to which they refer.
I hope this makes the docs more readable and easier to understand.
I have read the [contributing guide](https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md). I guess and hope that I have not changed or removed something crucial.
=> Improve syntax docs

scripts/build.sh
`cd` can fail for a variety of reasons: misspelled paths, missing directories, missing permissions, broken symlinks and more.
If/when it does, the script will keep going and do all its operations in the wrong directory. This can be messy, especially if the operations involve creating or deleting a lot of files. To avoid this, make sure you handle the cases when cd fails. Ways to do this include:
`cd foo || exit` as suggested to abort immediately, using exit code from failed cd command
=> Exit CD when fail for a variety of reasons

website/docs/language/settings/backends/s3.mdx, website/docs/language/upgrade-guides/index.mdx
Because of changes to the S3 Backend schema, some users are reporting that they need to reconfigure their backend when updating to Terraform 1.6, even if they have made no changes. Add this to the Upgrade Guide and S3 Backend documentation.
Relates #34022
1.6.2
Documentation change
=> backend/s3: Document need to reconfigure backend when updating Terraform

internal/moduletest/mocking/values.go, internal/moduletest/mocking/values_test.go
This PR introduces the core logic for generating values inside the testing framework.
The functionality accepts a target cty.Value and a replacement cty.Value. It then iterates through the target value and finds attributes that should be replaced (in this case values that we are expecting the provider to compute), and either replaces them with an equivalent attribute from the replacement value or generates a value for them if they are not specified in the replacement value.
Eventually this will be called from providers and the Terraform graph to mock out calls that would normally go to a real provider and create infrastructure. Instead, the call will come into this function and the computed values returned this way.
1.7.0
=> terraform test: add functionality for generating mock data

internal/addrs/module.go, internal/addrs/targetable.go, internal/configs/mock_provider.go, internal/configs/parser_config_dir_test.go, internal/configs/provider.go, internal/configs/test_file.go, internal/configs/testdata/invalid-test-files/duplicate_data_overrides.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_mixed_providers.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_mock_data_sources.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_mock_providers.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_mock_resources.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_module_overrides.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_providers.tftest.hcl, internal/configs/testdata/invalid-test-files/duplicate_resource_overrides.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_data_override.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_data_override_target.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_mock_data_sources.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_mock_resources.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_module_override.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_module_override_target.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_resource_override.tftest.hcl, internal/configs/testdata/invalid-test-files/invalid_resource_override_target.tftest.hcl, internal/configs/testdata/valid-modules/with-mocks/child/main.tf, internal/configs/testdata/valid-modules/with-mocks/main.tf, internal/configs/testdata/valid-modules/with-mocks/test_case_one.tftest.hcl, internal/configs/testdata/valid-modules/with-mocks/test_case_two.tftest.hcl
This PR adds support for the new mocking HCL blocks into the configs package. It also updates the test files so they will load the mocking data when they are loaded for terraform test commands.
I've left out the `source` attribute from `mock_provider` blocks from the time being. I want to have `terraform init` load any dedicated mock data files alongside the modules and providers. So I'll come back and add support for this in both `init` and `test` at the same time. This PR unlocks all the required functionality for mocking without doing too many things.
1.7.0
=> terraform test: parse mock and override blocks within test files

internal/providers/mock.go, internal/terraform/context_apply2_test.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_builtin_test.go, internal/terraform/eval_context_mock.go, internal/terraform/node_provider.go, internal/terraform/node_provider_eval.go
This PR implements a mock provider in the `providers` package, and updates the Terraform graph to use if when initialising providers if the config for the provider declares it as a mocked provider.
1.7.0
=> terraform test: implement mock providers in terraform graph

website/docs/language/resources/provisioners/local-exec.mdx
While direct injection of Terraform variables in the `local-exec` provisioner's `command` parameter is _possible_, it should be avoided due to its possibility of creating shell injection vulnerabilities. This PR adds mention of this to the documentation, and suggests the alternative of passing Terraform variables to a command as environment variables.
I can add a "do this/not that" example to the documentation as well, if that is desired.
1.5.x
=> Mention shell injection in local provisioner documentation

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/bad-references/providers.tftest.hcl, internal/command/testdata/test/provider_runs/main.tf, internal/command/testdata/test/provider_runs/main.tftest.hcl, internal/command/testdata/test/provider_runs/setup/main.tf, internal/command/testdata/test/provider_runs_invalid/main.tf, internal/command/testdata/test/provider_runs_invalid/missing_run_block.tftest.hcl, internal/command/testdata/test/provider_runs_invalid/unavailable_run_block.tftest.hcl, internal/command/testdata/test/provider_runs_invalid/unused_provider.tftest.hcl, internal/moduletest/config/config.go, internal/moduletest/config/config_test.go, internal/moduletest/hcl/context.go, internal/moduletest/hcl/provider.go, internal/moduletest/hcl/provider_test.go
This PR allows provider configurations to reference run blocks inside testing files.
To make this possible, I've introduced a field in the `TestSuiteRunner` that tracks the providers required for each configuration that a test suite might require. This is so that we can now selectively hand providers over to each run block as required, instead of the previous approach which simply copied all the provider configurations across for every run block. 
I also fixed a bug in the provider configuration logic that meant it wasn't properly raising diagnostics and giving bad error messages for problems within the provider configurations.
Fixes #34100 
Fixes #34007 
1.7.0
-  `terraform test`: Allow referencing run blocks from provider configurations in test files.
=> testing framework: allow providers to reference run blocks

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/sensitive_input_values/main.tf, internal/command/testdata/test/sensitive_input_values/main.tftest.hcl, internal/command/testdata/test/sensitive_input_values/setup/main.tf
This PR removes the sensitive marks from variables before passing them as input variables into run blocks. This only affects situations where users are passing outputs from previous run blocks that are marked as sensitive.
In addition, we add a warning if the receiving variable configuration isn't also marked as sensitive, as the sensitive metadata is being lost if the config isn't also marked as sensitive. It might be we want to actually completely disallow this, so add this diagnostic as an error instead of a warning. I'm happy to make that change if we think it's necessary.
Fixes #34185 
1.6.4
-  `terraform test`: Fix bug preventing passing sensitive output values from previous run blocks as inputs to future run blocks.
=> terraform test: remove marks before passing variables as inputs to a plan

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/sensitive_input_values/main.tf, internal/command/testdata/test/sensitive_input_values/main.tftest.hcl, internal/command/testdata/test/sensitive_input_values/setup/main.tf
Manual backport of #34190
Failed backport is in #34201
=> backport of terraform test: remove marks before passing variables as inputs to a plan

internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go, website/docs/language/functions/nonsensitive.mdx
https://github.com/hashicorp/terraform/issues/28222 and https://github.com/hashicorp/terraform/issues/31693 and other issues describe a set of situations where users are effectively locked into a situation where they can't use derivations of collections of objects where some fields are marked as sensitive into for_each, and are also unable to use nonsensitive because some of the values are indeed nonsensitive already. It also applies to arrays of elements where some are marked as sensitive while others are not. 
In these hybrid situations, there doesn't seem to be an way to mark everything as nonsensitive.
The behaviour in 1.5.x causes an error if nonsensitive is called on a value that is not marked as "sensitive". 
The documentation at …
=> nonsensitive: no longer produces error when applied to nonsensitive values

internal/addrs/module_instance.go, internal/addrs/module_instance_test.go, internal/moduletest/mocking/overrides.go, internal/moduletest/mocking/overrides_test.go, internal/moduletest/mocking/testing.go, internal/plans/plan.go, internal/terraform/context_apply.go, internal/terraform/context_apply_overrides_test.go, internal/terraform/context_plan.go, internal/terraform/context_walk.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/graph.go, internal/terraform/graph_walk_context.go, internal/terraform/node_output.go, internal/terraform/node_overridable.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/terraform_test.go
This PR implements the `override_resource`, `override_data`, and `override_module` blocks from the testing framework within the Terraform graph.
The implementation is relatively simple for `override_resource` and `override_data`. We simply check if the resource has an override set right before it makes any calls to the provider, and then uses the data in the override instead of talking to the provider.
The `override_module` is a bit more complex. We check all the nodes before they execute, and if they are within a module instance that has been overridden (either directly or indirectly because a parent module has been overridden) then we just don't execute the node. This works because we blanket intercept all nodes within the overridden module and because of Terraform's encapsulation logic …
=> testing framework: implement overrides in terraform graph

internal/command/test_test.go, internal/command/testdata/test/functions_available/main.tf, internal/command/testdata/test/functions_available/main.tftest.hcl, internal/lang/functions.go, internal/moduletest/hcl/context.go
This PR adds the base Terraform functions into the testing framework, so that users can access them when defining providers and variables within the testing framework.
1.7.0
-  `terraform test`: Terraform functions are now available within `variables` and `provider` blocks within test files.
=> testing framework: add support for functions in variables and providers

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/invalid-overrides/main.tf, internal/command/testdata/test/invalid-overrides/main.tftest.hcl, internal/command/testdata/test/invalid-overrides/setup/main.tf, internal/command/validate.go, internal/command/validate_test.go, internal/configs/config.go, internal/configs/mock_provider.go, internal/configs/test_file.go, internal/configs/test_file_test.go
I think it would be a source of frustration to a user who thinks they have set up an override but have a small typo in their target address, or something similar. This PR adds an explicit warning to the validate command, and during tests, if we discover any targets that point to addresses that can never exist. We validate this outside the graph, so we don't consider instance expansion but just look at the raw config.
We plan on adding source files for terraform mocks soon. I've pre-emptively added a source attribute to the override structures so we can differentiate between override blocks defined inside an actual file (which means we can reasonably say a user meant to target a resource available to this testing file) vs override blocks in the soon to be implemented data files. Override …
=> testing framework: add warnings for override blocks with invalid targets

internal/moduletest/mocking/fill.go, internal/moduletest/mocking/fill_test.go, internal/moduletest/mocking/generate.go, internal/moduletest/mocking/values.go, internal/moduletest/mocking/values_test.go, internal/providers/mock.go, internal/terraform/context_apply_overrides_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
This PR adds support for importing overridden resources during `terraform test` execution.
We parse the config early when importing into an overridden resource, and use the config to generate a complete value in the same we would if we were creating the resource from scratch. Then we pass that imported resource forward as normal.
The main use case for this is to allow users to test configs like those described in #34150.
In addition, this PR tweaks the behaviour of the mocking framework when generating mock data so that it more uniformly behaves as expected. Previously, it wasn't always following the guidelines around repeated blocks and nested attributes. The introduction of the `Fill` functions that behave in the same way as the `Generate` functions helps to address this, and makes sure …
=> terraform test: add support for importing overridden resources

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/mocking/child/main.tf, internal/command/testdata/test/mocking/main.tf, internal/command/testdata/test/mocking/tests/module_mocked.tftest.hcl, internal/command/testdata/test/mocking/tests/module_mocked_overridden.tftest.hcl, internal/command/testdata/test/mocking/tests/no_mocks.tftest.hcl, internal/command/testdata/test/mocking/tests/primary_mocked.tftest.hcl, internal/command/testdata/test/mocking/tests/primary_mocked_overridden.tftest.hcl, internal/configs/mock_provider.go, internal/moduletest/config/config.go, internal/providers/mock.go, internal/terraform/node_module_expand.go
Pass the overrides and mock providers from the test files into the Terraform graph during the `terraform test` command.
There's two bugs fixed as well that were exposed by the new integration tests added into the `command` package:
- Stopped removing overridden modules from the returned state as they never contain resources and data sources so would normally be removed.
- Updated the mock provider to clarify which functions it passes through to the underlying provider and which it doesn't. Fixed the `UpgradeResourceState` call which shouldn't be called without configuring the underlying provider first which we don't do for mocked providers.
1.7.0
=> terraform test: connect mock behaviour to test framework

internal/configs/config_build.go, internal/configs/config_build_test.go, internal/configs/configload/loader_load.go, internal/configs/configload/loader_snapshot.go, internal/configs/mock_provider.go, internal/configs/mock_provider_test.go, internal/configs/parser_config.go, internal/configs/parser_config_dir.go, internal/configs/parser_test.go, internal/configs/provider.go, internal/configs/testdata/valid-modules/with-mock-sources-inline/main.tf, internal/configs/testdata/valid-modules/with-mock-sources-inline/main.tftest.hcl, internal/configs/testdata/valid-modules/with-mock-sources-inline/testing/aws/.ignored.tfmock.hcl, internal/configs/testdata/valid-modules/with-mock-sources-inline/testing/aws/data.tfmock.hcl, internal/configs/testdata/valid-modules/with-mock-sources-inline/testing/aws/resource.tfmock.hcl, internal/configs/testdata/valid-modules/with-mock-sources/main.tf, internal/configs/testdata/valid-modules/with-mock-sources/main.tftest.hcl, internal/configs/testdata/valid-modules/with-mock-sources/testing/aws/.ignored.tfmock.hcl, internal/configs/testdata/valid-modules/with-mock-sources/testing/aws/data.tfmock.hcl, internal/configs/testdata/valid-modules/with-mock-sources/testing/aws/resource.tfmock.hcl, internal/initwd/module_install.go
This PR implements the `source` attribute in `mock_provider` blocks.
This will allow users to share implementation of mocks between different test files. We load the data sources during the `BuildConfig` function, which is the same time we load the modules. This should make a future extension in which mock data sources could be loaded from an external source (like the registry or a repository) easier.
1.7.0
=> terraform test: implement the source attribute for mock providers

internal/addrs/provider_config.go, internal/addrs/unique_key.go, internal/backend/local/backend_apply.go, internal/backend/local/test.go, internal/configs/config.go, internal/configs/provider_validation.go, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/providers/schema_cache.go, internal/terraform/context.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/context_apply_checks_test.go, internal/terraform/context_apply_overrides_test.go, internal/terraform/context_apply_test.go, internal/terraform/context_input_test.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/context_plugins.go, internal/terraform/context_test.go, internal/terraform/context_walk.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_builtin_test.go, internal/terraform/graph_builder_apply_test.go, internal/terraform/graph_builder_plan_test.go, internal/terraform/graph_walk_context.go, internal/terraform/providers.go, internal/terraform/schemas_test.go
Calling into `terraform.Context.Plan` or `terraform.Context.Apply` is conceptually similar to a module call (a `module` block), but written in Go instead of in the Terraform language. The caller passes in values for input variables, and in return receives the results of the output values, meaning that in _most_ ways we can use root and shared modules in the same way as far as Terraform Core itself is concerned. (That's less true once Terraform CLI is involved, but that's not relevant to this PR.)
One notable gap in that analogy is that modules can be written to expect provider configurations to be passed in by or automatically inherited from their calling module, but Terraform Core previously had no way to offer that possibility to its callers written in Go.
This PR aims to fill that gap …
=> core: Allow Go callers to provide their own already-instantiated-and-configured provider instances

internal/terraform/context_plan_import_test.go, internal/terraform/eval_for_each.go, internal/terraform/node_resource_plan.go
The expansion process has to assume that there will eventually be a configuration for instances to allow for config generation, but if the import block expands to no instances, we don't want to add that instance node to the graph with no import or configuration data.
=> import: don't panic if expanded import returns no instances with config generation

website/docs/internals/machine-readable-ui.mdx
Added "import" under values of "action" for "planned_change". This is my first PR, let me know if I missed anything!
There are other lists of actions under in the same page; I _assume_ that they need to be updated too, but I'm not familiar enough with them.
Fixes #
1.5.x
- Adds missing possible values of `action` for the documentation of the machine readable UI.
=> Update machine-readable-ui.mdx - missing "action" value "import"

website/docs/internals/json-format.mdx
Closes https://github.com/hashicorp/terraform/issues/34246
Add documentation of the `"importing"` field which is sometimes present in the change representation. Also correct a typo.
=> website: add "importing" to json plan format docs
