hashicorp/terraform

internal/rpcapi/terraform1/conversion.go, internal/stacks/stackplan/planned_change_test.go
This PR updates the stacks RPC API logic to specify the actions for a no-op change as a single item list with the no-op action. Given we include the `ChangeType_NOOP` enum value it feels like we should use it.
Meta-note: I had assumed this was going to be a bug but it looks very deliberate. I think the nil list is a change from how this works anywhere else in the Terraform ecosystem? The TFC agents and the UI are assuming no-op changes are formatted in this way, so we could go and change things at that point to interpret things in this way.
=> stacks: actions for a no-op change are a concrete list

website/docs/language/import/index.mdx
Update docs to make it more explicit that expressions, not just literal strings, can be used in the `import` block `id` field.
=> docs: more detail on import IDs

website/data/internals-nav-data.json
The Terraform Internals page (https://developer.hashicorp.com/terraform/internals) sidebar is missing a link to the Machine Readable UI docs page.
The initial migration of the docs nav files (https://github.com/hashicorp/terraform/pull/30237) lists the page as hidden. I'm not sure why, as the page is still in use and should be discoverable.
=> website: restore link to machine readable ui doc

LICENSE
Manual backport of https://github.com/hashicorp/terraform/pull/34304 to v1.6.
=> Manual backport of #34304 to v1.6

internal/cloud/tfe_client_mock.go, internal/terraform/provider_mock.go
This PR fixes some race conditions within our testing TFC client and testing provider. See here for an example failure: https://github.com/hashicorp/terraform/actions/runs/6961590415/job/18943516900
I ran this with `go test -race ./...`and everything passed with no deadlocks so seems safe.
=> Fix race conditions in mock provider and mock tfc client

internal/addrs/instance_key.go, internal/addrs/partial_expanded.go, internal/instances/expander.go, internal/instances/expander_test.go, internal/instances/expansion_mode.go, internal/instances/instance_key_data.go
This is some preparation work for eventually (in later PRs) solving #30937.
Our `instances.Expander` abstraction is intended to encapsulate the problem of keeping track of the dynamic expansion of multiple levels of nested `module` calls and of `resource` and `data` blocks that might belong to those nested modules and also have their own dynamic expansion.
This set of commits extends that abstraction to support explicitly tracking that the expansion of a particular object is unknown.
That in turn allows callers to ask both for the known instance keys of an object and separately for a set of patterns representing _potential_ instance keys that might appear later once more information is known. A particular configuration object can have a mixture of both known and unknown instance keys if …
=> instances: Expander can now track partially-unknown expansions

internal/addrs/graph.go, internal/addrs/graph_test.go, internal/command/graph.go, internal/command/graph_test.go, internal/command/testdata/graph-interesting/child/graph-interesting-child.tf, internal/command/testdata/graph-interesting/graph-interesting.tf, internal/terraform/graph.go, internal/terraform/graph_builder_plan_test.go, website/docs/cli/commands/graph.mdx
This fixes #14511.
I actually wrote the first two commits here as part of a new round of work on #30937, but after implementing `Graph.ResourceGraph` I remembered that a graph just of the relationships between resources -- without all of the other intermediaries -- was the main idea I heard about when researching #14511 many years ago.
Given that the `terraform graph` command is an ancillary debugging/learning tool rather than part of the main Terraform workflow, I find it pretty unlikely that we'd prioritize any work directly on it in the near future, but since my work here already got most of the way there I figured I might as well make a small effort to close that old issue at the same time, while I'm working in this area anyway.
The effect of this PR, then, is to change the default …
=> terraform graph: By default, produce a compact graph with only resources in it

internal/command/test_test.go
Using `output.All()` from the test streams was sometimes interleaving the stdout and stderr streams, which led to the test failing when looking for the expected outputs.
This PR just makes the troublesome test assess the output and error streams separately, and this fixes the flake as the error diagnostic is not being printed in the middle of where the expected output would go which happens sometimes when the streams were merged in the single call.
=> Fix flaky test in command/test_test.go

internal/addrs/partial_expanded.go, internal/namedvals/doc.go, internal/namedvals/state.go, internal/namedvals/values.go, internal/namedvals/values_test.go
Currently we have a slightly different treatment for each of the different kinds of named values, which makes it hard to generalize the implementations of their very similar behaviors.
This package should over time take ownership of the problem of tracking all three kinds of named value during a graph walk, with the main modules runtime copying the relevant subset of values out into the plan and state data structures as needed, while letting `namedvals.State` be the authority on all of their values for evaluation purposes.
Nothing is using this yet, though. In future PRs I'm planning to carefully swap out our existing mechanisms for tracking these in the `terraform` package to use `namedvals.State` instead. That will initially use only the "exact" value tracking, because that's all the …
=> namedvals: A new package for tracking the results of "named values"

internal/rpcapi/dynrpcserver/packages.go, internal/rpcapi/packages.go, internal/rpcapi/packages_test.go, internal/rpcapi/plugin.go, internal/rpcapi/terraform1/terraform1.pb.go, internal/rpcapi/terraform1/terraform1.proto, internal/rpcapi/testdata/providers/hashes.json, internal/rpcapi/testdata/providers/terraform_provider_bar/terraform-provider-bar, internal/rpcapi/testdata/providers/terraform_provider_foo/terraform-provider-foo
This PR adds the packages service to the new stacks RPC API.
We'll use this in the new `tfstacks` CLI to help with downloading providers and modules for verifying dependencies and creating lock files.
=> stacks: add the packages service to the rpc api

website/docs/language/tests/index.mdx
This is a new feature in v1.7.
=> docs: update terraform test docs with provider to run block reference examples

internal/command/console.go, internal/command/console_test.go, website/docs/cli/commands/console.mdx
Previously `terraform console` always evaluated in a kinda strange context where resource instance data comes from the prior state, but other derived of values end up being calculated dynamically based on the current configuration, which is okay for simple cases but can be confusing if the configuration has changed significantly since the most recent apply, or if there haven't yet been any applied changes.
Now we'll allow an optional new mode where Terraform runs the normal plan phase (as if running `terraform plan`) and then uses the resulting _planned state_ as the basis for evaluation, allowing evaluation against a partial approximation of what the world ought to look like if these changes were applied, without having to actually apply them first.
As with the previous use of the eval …
=> terraform console: Option to evaluate in a planned state

internal/rpcapi/dynrpcserver/stacks.go, internal/rpcapi/stacks.go, internal/rpcapi/terraform1/terraform1.pb.go, internal/rpcapi/terraform1/terraform1.proto
This can be used by the `tfstacks` CLI as part of the `tfstacks validate` command.
I haven't added any tests for this - the actual implementation is so simple that it seems unnecessary. I'd really just be adding a test that checks the validate function is called. The validate function itself should have unit testing around it to check the actual validations.
=> stacks: Add ValidateStackConfiguration RPC to stacks API service

website/docs/language/expressions/custom-conditions.mdx
This is a simple correction in the Expressions docs related to the custom condition examples. The EC2 instance encryption example mentions "precondition" when the example uses a `postcondition`.
-  Fixed explanation for EC2 instance encryption example in custom condition expression docs
=> Correct EC2 instance encryption condition example in custom-conditions.mdx

website/docs/language/functions/cidrhost.mdx
This feature was introduced (and documented) in https://github.com/hashicorp/terraform/pull/13765, but it seems that its documentation was not carried over when the docs were reorganized.
1.6.x
- Document negative host numbers for `cidrhost()` function
=> Document negative host numbers for `cidrhost()` function

internal/terraform/context_apply2_test.go, internal/terraform/context_plan.go
`PlanOpts` should contain only static options which are known before planning. Previous to this commit, `ctx.plan` was modifying the `opts` object, which, since it is passed via pointer, could be shared by other `ctx.plan` calls happening concurrently, producing weird behaviour.
Such weird behaviour was only noticeable during tests, in which it is common to pass a pointer to `DefaultPlanOpts`. When one test that modified `opts.forgetResources` was run at the same time as another test, `DefaultPlanOpts.forgetResources` would be populated when it shouldn't be. The real Terraform binary does not do this and `ctx.plan` is only called once per run.
One fix for the race condition would be to have `ctx.plan` take a deep copy of the entire `PlanOpts` object which it can modify without touching …
=> core: remove import,forget targets from PlanOpts

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, website/docs/language/settings/backends/s3.mdx, website/docs/language/upgrade-guides/index.mdx
In Terraform 1.7 we'll begin phasing out the legacy credential chain evaluation order by defaulting `use_legacy_workflow` to `false` and deprecating the argument. This will bring the default behavior into alignment with the AWS SDKs and CLI. Practitioners can still preserve the legacy behavior by setting this argument to `true`. In Terraform 1.8 this argument will be removed, and the S3 backend will always use the default credential chain evaluation order from the AWS SDK for Go.
```console
% TF_ACC=1 go test -count=1 ./internal/backend/remote-state/s3/...
ok      github.com/hashicorp/terraform/internal/backend/remote-state/s3 140.736s
```
Relates #30443
1.7.x
* backend/s3: The `use_legacy_workflow` argument now defaults to `false`. The backend will now search for credentials in the same …
=> backend/s3: default `use_legacy_workflow` to false, deprecate

internal/cloudplugin/binary.go, internal/cloudplugin/binary_test.go, internal/cloudplugin/testdata/cloudplugin-dev, internal/command/cliconfig/provider_installation.go, internal/command/cloud.go
Currently, Terraform will only run properly signed versions of the experimental
cloud plugin that were downloaded from a TFC instance that provides the
appropriate service. That obstructs development on new cloud plugin features!
Our internal teams will need a "dev override" capability, like what we offer
provider authors.
However, unlike with providers, we don't have to integrate this into a
heterogeneous mix of sources for mirroring and caching a wide range of binaries.
There's only one cloud plugin, HashiCorp controls it, and end users should never
need to override the location of the binary for non-development reasons.
Thus, we have the luxury of being quite a bit stupider in how we handle the
override signal. Instead of adding it to the CLI config file schema, we'll just
use a single …
=> Add TF_CLOUD_PLUGIN_DEV_OVERRIDE to enable cloudplugin dev

internal/cloud/backend_plan.go, internal/cloud/backend_plan_test.go
By convention, Terraform Cloud workspaces connected to a VCS repo should should only apply configs that come from the designated branch, to ensure that version control remains the source of truth for that infrastructure.
The cloud version of `terraform apply` already includes a guardrail for that, but we forgot to include an equivalent one for `terraform plan` when performing saved plans (which can be applied later, unlike a purely speculative plan).
We suspect that TFC actually needs some additional formal access controls around assigning configuration versions to workspaces, as everyone tends to be surprised to learn that the API doesn't actually prevent this. But in the meantime, what's good for the goose (apply command) is good for the gander (plan command), so I'm copying over the …
=> Disallow saved cloud plans in VCS workspaces

internal/command/meta_vars.go, internal/command/test_test.go, internal/command/testdata/test/tfvars_in_test_dir/alternate/main.tftest.hcl, internal/command/testdata/test/tfvars_in_test_dir/alternate/vars.auto.tfvars, internal/command/testdata/test/tfvars_in_test_dir/alternate/vars.auto.tfvars.json, website/docs/language/tests/index.mdx
Update the testing docs to reflect the new functionality added in https://github.com/hashicorp/terraform/pull/34341. Now, automatic variable files defined within specific test directories will load and apply their contents to tests also defined in the same test directory.
This PR also contains a quick fix for a small piece of missing functionality that was forgotten in the previous PR.
1.7.0
N/A - we already have a CHANGELOG entry from https://github.com/hashicorp/terraform/pull/34341.
=> Add docs for automatic var files in test directories

website/docs/cli/commands/state/rm.mdx, website/docs/language/modules/syntax.mdx, website/docs/language/resources/syntax.mdx
Config-driven remove via the `removed` block has two main applications: removing modules and removing resources. Add a section on the appropriate page for each.
Also link to the config-driven alternative on the `terraform state rm` page.
Questions:
1. Should I add something on the `removed` block to the [Language -> Modules -> Refactoring](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring) page? Refactoring a module is one use case for the `removed` block, but not all use cases (in particular some future ones) can be considered refactoring. We've also used "refactoring" as synonymous with "using `moved` blocks" in some places, so this page would need some reorganisation.
2. Should there be a single page describing the syntax for the `removed` block somewhere? …
=> website: removed block docs

.github/workflows/lock.yml
This is my first contribution to Terraform, so if I'm doing something wrong, please let me know.
- It seems like that `Lock Threads` is not working properly on GitHub Actions because of mismatch of inputs. (https://github.com/hashicorp/terraform/actions/runs/7095197463)
- Actually for example, [this PR closed over 30 days ago](https://github.com/hashicorp/terraform/issues/33919) is not locked. 
- According to their [CHANGELOG](https://github.com/dessant/lock-threads/blob/1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771/CHANGELOG.md?plain=1#L65-L74), some inputs are changed after `v3.0.0`.
- I changed some inputs following the [CHANGELOG](https://github.com/dessant/lock-threads/blob/1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771/CHANGELOG.md?plain=1#L65-L74).
- Bump to latest version.
=> chore(GitHub Actions): fix inputs of Lock Threads, and bump version

.github/workflows/lock.yml
Currently, discussions are not a feature we use on GitHub. However, we did not want to enable an automated behavior that would be difficult and confusing to track down for a future enabler of GitHub Discussions.
=> Limiting lock behavior to issues and PRs; ignoring discussions.

internal/plans/planfile/tfplan.go, internal/stacks/stackstate/from_proto.go
Currently, sensitive values cause a permadiff because they aren't being round-tripped through state correctly - they lose their sensitivity each time they're read from state, and then Terraform plans a change to mark them as sensitive again. This change preserves sensitive marks when deserializing stack state.
I tried to write a test for this and wasn't very successful due to the fact that we don't have much integration-y testing for stacks just yet. I'd be very open to other ideas on how/where to test this change, though!
=> stackstate: sensitive values are preserved when deserializing stack state

internal/command/jsonformat/plan_test.go, internal/command/jsonformat/structured/change.go, internal/command/jsonplan/plan.go
Previous to this change, forget-only actions (i.e. "forget", not "create then forget") would be rendered using the forget action symbol for the top-level resource, and the delete action symbol for each resource attribute, with a new value of "null". For example:
```
Terraform will perform the following actions:
. resource "aws_ecr_repository" "this" {
- arn                  = "arn:aws:ecr:us-east-1:634211456147:repository/delete-test" -> null
- id                   = "delete-test" -> null
- image_tag_mutability = "MUTABLE" -> null
- name                 = "delete-test" -> null
- registry_id          = "634211456147" -> null
- repository_url       = "634211456147.dkr.ecr.us-east-1.amazonaws.com/delete-test" -> null
- tags                 = {} -> null
- tags_all             = {} -> null
- …
```
=> jsonformat: render forget-only attr changes as no-op

website/docs/language/state/purpose.mdx
Fixes #34389
1.7.x
- Removed ambiguous reference from purpose of terraform state.
=> refact: removed ambiguous reference from purpose of terraform state

go.mod, go.sum, internal/command/jsonfunction/function.go, internal/command/metadata_functions.go, internal/lang/funcs/descriptions.go, internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go, internal/lang/funcs/testdata/recursive_namespaced.tmpl, internal/lang/functions.go, internal/lang/functions_descriptions_test.go, internal/lang/functions_test.go, internal/lang/scope.go, internal/provider-simple-v6/provider.go, internal/terraform/context_functions_test.go, internal/terraform/context_validate_test.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/graph_walk_context.go, internal/terraform/node_module_expand.go, internal/terraform/provider_mock.go
Enable the use of provider-defined functions within the `provider::` scope.
Providers can now implement functions which can be used from within the Terraform configuration language. The schema for each function is defined via the provider schema, using a layout similar to that of `cty` function definitions already in use internally. All provider functions found via their schemas are added to the `provider::` namespace, using the provider's local name as defined in the module's `required_providers`. This means that a `noop` function declared by the `aws` provider would be access as `provider::aws::noop()`. The use of the `::` delimiter as a function scoping mechanism was already added to the updated `hcl` package.
While providers must be trusted to ensure their functions only operate …
=> enable use of provider functions in the Terraform language

internal/dag/tarjan.go
Min built-in functions have been added since go1.21, so unnecessary parts have been removed.
1.8.x
removed min function and adopted go standard min
-
=> refactor: removed min function and adopted go standard min

.copywrite.hcl, LICENSE, docs/plugin-protocol/.copywrite.hcl, internal/tfplugin5/.copywrite.hcl, internal/tfplugin6/.copywrite.hcl
DO NOT MERGE UNTIL EOY
Updates LICENSE and copywrite tool files to 2024.
Backport to 1.6.x
=> [DO NOT MERGE UNTIL EOY] EOY license updates

internal/configs/test_file.go, internal/configs/testdata/config-diagnostics/tests-provider-mismatch/main.tftest.hcl, internal/configs/testdata/invalid-modules/tests-invalid-run-blocks/main.tf, internal/configs/testdata/invalid-modules/tests-invalid-run-blocks/main.tftest.hcl
Validate that run block names are valid HCL identifiers when they are parsed instead of failing with obscure error messages later.
Fixes #34372 
1.7.0
-  `terraform test`: Improve error message for invalid run block names.
=> terraform test: run block names should be valid HCL identifiers

internal/command/test_test.go, internal/command/testdata/test/empty_module_with_output/empty/main.tf, internal/command/testdata/test/empty_module_with_output/main.tf, internal/command/testdata/test/empty_module_with_output/main.tftest.hcl, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_module_expand.go, internal/terraform/node_module_expand_test.go, internal/terraform/transform_root.go
This PR updates the v1.7 branch such that it won't remove "empty" modules from state if they have external references pointing to their outputs.
This does potentially increase the size of the state files, but currently it will only affect the `terraform test` framework as the external references are only set by the testing framework. This has been fixed "properly" in main, so it also means that slight hack implemented here will only be present in the v1.7 branch. Overall, I think that makes the approach here acceptable given the temporary nature of the fix. I had attempted to port over the real fix in #34477, but it was rightly pointed out that it's a bit overkill and potentially risky so close to an upcoming release. Hopefully, this is an acceptable middle ground.
Fixes #34476 
1.7.0-rc2 …
=> terraform test: Keep modules in state if they are required by the external references

internal/providers/mock.go, internal/terraform/context_apply2_test.go
This PR updates the mocked providers so they override the provider configuration schemas returned by calls to GetProviderSchema. Currently, a provider with required blocks or attributes (such as the `azurerm` provider) will always fail to initialise as mocked providers should not include the usual configuration from the underlying providers, but the validation was still checking against the original schema.
After this PR lands, the mock provider will override the configuration schema so that it matches the schema provided by the configs package.
1.7.0-rc2
1.7.0
-  N/A, covered by the CHANGELOG entry for mocking generally.
=> Override provider schemas for mocked providers

internal/command/test_test.go, internal/command/testdata/test/empty_module_with_output/empty/main.tf, internal/command/testdata/test/empty_module_with_output/main.tf, internal/command/testdata/test/empty_module_with_output/main.tftest.hcl
This PR adds a test verifying the linked issue has already been fixed on main. A seperate PR added this test alongside the fix into `v1.7`: https://github.com/hashicorp/terraform/pull/34482.
Relates to #34476 
N/A
N/A
=> Add test verifying issue #34476 has been fixed

internal/configs/configschema/filter.go, internal/configs/configschema/filter_test.go
Make sure that we only dereference an attribute if it was set in the filter. While not extremely useful, a provider could technically have a nested object with no attributes.
Fixes #34463
=> `Block.Filter` can panic with a nested object which has no attributes

internal/cloud/backend.go, internal/cloud/backend_apply.go, internal/cloud/backend_apply_test.go, internal/cloud/backend_common.go, internal/cloud/backend_context.go, internal/cloud/backend_plan.go, internal/cloud/backend_plan_test.go, internal/cloud/backend_show.go, internal/cloud/backend_taskStage_taskResults_test.go, internal/cloud/backend_taskStages.go, internal/cloud/backend_test.go, internal/cloud/state_test.go, internal/cloud/test.go, internal/cloud/testing.go, internal/cloudplugin/cloudplugin1/grpc_plugin.go, internal/command/cloud.go, internal/command/cloud_test.go
- The cloud plugin wants a go-tfe client to get stuff from TFC.
- Terraform knows how to find all the info you need in order to configure a
go-tfe client, but it's sometimes scattered across configs and env vars and
credentials helpers, and trying to re-implement the resolution logic identically
in another codebase would be error-prone.
- Therefore, it'd be best if Terraform did that resolution and just passed the
plugin all the config info it needs.
There are two options for that handoff:
1. Adding it as an additional argument to the primary Execute RPC interface.
2. Passing it as gRPC metadata, which is a pile of arbitrary key => list-of-strings
pairs transmitted via HTTP/2 headers.
The crux of the decision here is whether a proliferation of plugin protocol
versions whenever we need to …
=> Cloudplugin: Pass configuration via gRPC metadata

internal/terraform/context_plan2_test.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_plan_orphan.go
Previously, we were checking if a resources module matched a removed module exactly when deciding whether it should be deleted or forgotten. This meant deeply nested resources were being destroyed even though a parent module was marked as removed.
After this PR we use `TargetContains` function instead of an equality check, so that deeply nested resources will respect the removed status of parent modules.
Fixes #34475
1.7.0-rc2
N/A - covered by the removed block entry more generally.
=> removed: child modules should be removed if they are within a removed module

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/terraform-sources.json, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/modules_with_provider_configs/module-a/modules-with-provider-configs-a.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/modules_with_provider_configs/module-b/modules-with-provider-configs-b.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/modules_with_provider_configs/modules-with-provider-configs.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/validating_test.go, internal/stacks/stackruntime/internal/stackeval/walk_static.go
When running in Stacks, it's the stack configuration that's responsible for configuring providers, and so the modules used to implement components should be written to expect provider configurations passed in from their caller.
Previously we didn't have any special checks for this and so it would fail with a useless error message saying that the relevant provider isn't available. (It's correct to say that it isn't available _in the modules runtime_, but the error message doesn't include that context, and we don't want to be discussing implementation details like "the modules runtime" in our error messages anyway.)
This introduces some more specialized error messages for that situation. I expect we'll revisit this and tweak these error messages over time based on feedback, but the main …
=> stacks: Return a better error if a component module tries to use an inline provider

internal/plans/plan.go, internal/stacks/stackplan/planned_change.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/sensitive-output-as-input/sensitive-output-as-input.tf, internal/stacks/stackruntime/testdata/mainbundle/test/sensitive-output-as-input/sensitive-output-as-input.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/sensitive-output-nested/sensitive-output-nested.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/sensitive-output/sensitive-output.tf, internal/stacks/stackruntime/testdata/mainbundle/test/sensitive-output/sensitive-output.tfstack.hcl, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
This PR is in two parts: modifying the modules runtime to support marked input variable values, and updating the stacks runtime to use this new functionality.
The stacks runtime interacts directly with the modules runtime's planning operations, rather than through the usual CLI paths. As a result, root module input variable values can be marked as sensitive upon entry.
This PR adds support for such marked values to the modules runtime and the `plans.Plan` type. This is sufficient for stacks, which does not use the planfile serialization, but we may in future choose to serialize these decoded marks also.
Stack components can emit sensitive values as outputs, which can be consumed as inputs to other components. This PR also ensures that such values are correctly processed in order to pass …
=> stacks: Support sensitive component outputs

internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_state.go, internal/backend/remote-state/s3/backend_test.go, website/docs/language/settings/backends/s3.mdx
In versions prior to v1.6, the S3 backend ignored all errors other than `NoSuchBucket` when listing workspaces. This allowed cases where the user did not have access to the default workspace prefix `env:` to succeed.
In order to preserve this behaviour, now ignore `AccessDenied` errors when the user does not have access to the default workspace prefix. If `workspace_key_prefix` is specified, `AccessDenied` errors will cause a failure.
Updates documentation to list permissions needed when using workspaces.
Fixes #34223
1.7.0
-  backend/s3: No longer returns error when IAM user or role does not have access to the default workspace prefix `env:`
=> backend/s3: Ignore default workspace prefix errors

internal/command/jsonfunction/function.go, internal/command/jsonfunction/function_test.go, internal/command/jsonfunction/parameter.go, internal/command/jsonprovider/provider.go, internal/command/jsonprovider/provider_test.go, internal/plugin/convert/functions.go, internal/plugin6/convert/functions.go, internal/providers/functions.go
Add function definitions to the json schema CLI output.  While the protocol names may not exactly match the json keys, this matches the existing `metadata functions` output for easier integration with tooling already using that interface. We use the `jsonfunction` package from the `metadata` command to serialize the new provider functions, and ensure they stay synchronized. This makes the integration a little clumsy, and it may be a good idea to combine the cli json definitions into a single package, but the separate serialization works well enough for now.
An example of the `"functions"` portion of the schema would look like:
```
"functions": {
"format_version": "1.0",
"function_signatures": {
"noop": {
"description": "noop takes any single argument and returns the same value", …
```
=> Add functions definitions to the `providers schema -json` output

website/docs/language/upgrade-guides/index.mdx
- Update `1.6` to `1.7`.
- Remove `terraform test`, there's not breaking changes for it in `v1.7`.
- Add callout for state interoperability issues.
=> Complete upgrade guide for v1.7

internal/refactoring/cross_provider_move.go, internal/refactoring/mock_provider.go, internal/refactoring/move_execute.go, internal/refactoring/move_execute_test.go, internal/refactoring/move_statement.go, internal/refactoring/move_statement_test.go, internal/refactoring/move_validate.go, internal/refactoring/move_validate_test.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go
This PR adds support for cross-provider moves. We modify the `refactoring` package so the state for each `moved` resource is updated before the move operation happens.
1. Update the `refactoring.ApplyMoves` method so it accepts the set of available providers.
2. Update the `MoveStatement` struct so it includes the provider for the target `to` resource.
3. Update the `refactoring.ApplyMoves` function so it retrieves the provider for cross-type moves, and updates the state with the updated value before it executes the move.
4. Remove the verification that ensured `from` and `to` types had to be the same.
1.8.0
N/A, will do a big CHANGELOG entry for the entire cross-provider move functionality.
=> Extend refactoring package to support cross-provider moves

internal/command/jsonfunction/function.go, internal/plugin/convert/functions.go, internal/plugin6/convert/functions.go, internal/providers/functions.go, website/docs/cli/commands/providers/schema.mdx
Reference: https://github.com/hashicorp/terraform/pull/34450
I didn't see any exhaustive unit testing covering this implementation, but please let me know if there should be.
1.8.x
-
=> Add missing function deprecation_message to JSON output and website documentation

internal/command/arguments/test.go, internal/command/test.go, internal/command/views/test.go
This adds an experimental new option `-junit-xml=FILENAME` for the `terraform test` command. When specified, it writes a JUnit XML report to the specified filename once the test run is complete, while continuing to report test progress in the UI in the usual way.
I had a little extra time and energy at the end of the day today, just before a long weekend, and so I took a stab at a quick implementation of one possible answer to #34264.
This is only experimental for now because it remains to be seen if this particular mapping to the JUnit XML schema is actually useful in real software -- this format is woefully underdocumented and implemented slightly differently by each consumer -- and so we might change this significantly before stabilizing it, or remove it altogether if it turns out that …
=> terraform test: Experimental JUnit XML reporting

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/modules_with_provider_configs/module-a/modules-with-provider-configs-a.tf
Should fix https://hashicorp.atlassian.net/browse/TF-11905. I note that Martin mentioned a better fix would be to implement config and module loading from a source bundle properly but that's a lot of work. I think this should work in the mean time until we can revisit a proper refactor.
I think this fix should work since the parent module was definitely successfully loaded, so the cached source directory of the parent should be valid from the current working directory, and therefore any relative sources from the parent should be able to be joined with the parents directory. The source bundle implementation either returns absolute paths pointing to external dependencies or paths relative to the parent. I think we do have all the information we need to correctly deduce the target path of …
=> stacks: on module load convert relative paths to absolute

internal/refactoring/cross_provider_move.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/upgrade_resource_state.go
Add error diagnostics to catch when we find an unknown value from `ReadResource` or `UpgradeResourceState`. An unknown value is not valid in either of these cases, but the current error is not helpful and only returns a generic error about failed state serialization.
Fixes #34502
Fixes #34503
=> Add error diagnostics when receiving an unknown value from `ReadResource` or `UpgradeResourceState`

internal/stacks/stackruntime/internal/stackeval/applying_test.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/component_instance_results.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/applying/component_dependencies/applying_component_dependencies.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/applying/component_dependencies/applying_component_dependencies.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/terraform-sources.json, internal/stacks/stackruntime/internal/stackeval/testing_test.go, internal/stacks/stackstate/from_proto.go
This builds on https://github.com/hashicorp/terraform/pull/34483 to actually make use of the computed dependency relationships during the apply phase.
When a component's plan is in normal or refresh-only mode, that component waits until its dependencies have completed applying.
For a destroy-mode plan the opposite is true, with the component waiting until its _dependents_ have finished applying. That therefore ensures that dependencies outlive their dependents as expected. Although there's no single place in the code that enforces this, it's not possible in practice for an upstream component to have a destroy-mode plan while a downstream has a non-destroy plan, because that would imply that the downstream still exists in the configuration but refers to something that's been removed, which …
=> Respect the dependency relationships between components when applying

internal/backend/remote/backend_common.go, internal/backend/remote/backend_plan.go, internal/cloud/backend_common.go, internal/cloud/backend_plan.go, internal/cloud/backend_taskStages.go
Fixes #
We should not call colorize on strings that are returned as error messages. 
1.5.x
- Fix terminal error by removing colorized text
=> [TF-11813] do not colorize runHeader when returned as err

internal/command/jsonfunction/function.go, internal/command/jsonfunction/function_test.go, internal/command/jsonprovider/provider.go, website/docs/cli/commands/providers/schema.mdx
Previously, the `providers schema -json` output would include the root object from `metadata functions -json`. This object had its own `format_version` property, which would be confusing with the root `format_version` property already present.
This change still uses the `jsonfunction` package for consistency between cty and provider function JSON handling, but removes that extra object, instead making `functions` directly a mapping of names to signatures/definitions. This also adds a code comment to hint maintainers that jsonprovider format versioning is tied to jsonfunction format versioning.
There are no compatibility concerns from this change as there have been no releases (even alphas) with the prior output.
Example output prior to change:
```jsonc
{
"format_version": "1.0", …
```
=> internal/command/jsonprovider: Remove root jsonfunction object from function output

internal/addrs/module_call.go, internal/addrs/module_instance.go, internal/instances/expander.go, internal/instances/expander_test.go, internal/namedvals/state.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/graph_walk_context.go
We've been gradually working to factor out fiddly details of how we do instance expansion and how we handle named values over many previous PRs over the last few years, so that we can build Terraform's features more in terms of well-tested internal abstractions rather than sprawled inline business logic.
Now we'll make use of that effort to simplify how the modules runtime's expression evaluator decides the value to use when referring to a module call, using a reference like `module.foo`. Whereas before this had to deal with various fiddly cases such as values in the plan overriding values in the state, we can now rely entirely on our `instances.Expander` and `namedvals.State` APIs to simplify the inline logic considerably.
My goal here was to have this logic focused primarily on the …
=> Expression evaluator decides module call values using instances.Expander and namedvals.State

internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/no_workspace_name_ref/no-workspace-name-ref.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/no_workspace_name_ref/no-workspace-name-ref.tfstack.hcl, internal/terraform/evaluate.go
The `terraform.workspace` attribute is a rare example of a CLI- and Cloud- specific concern bleeding into the Terraform modules language, and it can only really have meaning when used in the traditional Terraform workflow because otherwise there's no workspace to return the name of.
In Stacks any variations between instances of a module must be created through input variables. Within Terraform Cloud in particular it's also possible to use stack-level input variables that are assigned different values from different stack deployments, and thus an author can recreate the effect of `terraform.workspace` using a stack-level input variable that has a different value for each deployment.
This is one of the few cases where the Terraform module language differs in stacks compared to traditional …
=> stacks: The terraform.workspace attr is not available in Stacks

internal/backend/local/backend_local.go, internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/functions_available/alternate.tftest.hcl, internal/command/testdata/test/global_var_refs/environment_variable.tftest.hcl, internal/command/testdata/test/global_var_refs/main.tf, internal/command/testdata/test/global_var_refs/run_block_output.tftest.hcl
Fixes #34529 
This PR also allows users to reference functions at test-file level global variables, which is something we published within the CHANGELOG for v1.7.
1.7.1
-  `terraform test: Fix crash when referencing variables within the file level `variables` block.
=> terraform test: Fix crash when file level variables reference variables.

website/data/language-nav-data.json
[Someone on slack pointed out](https://hashicorp.slack.com/archives/CFCJ63SRL/p1705773259517479) we forgot to update the navbar to match upgrading to TF 1.7 (no longer 1.6)
=> docs: Fix upgrading version in docs Navbar

internal/command/test_test.go, internal/command/testdata/test/mocking-invalid/child/main.tf, internal/command/testdata/test/mocking-invalid/main.tf, internal/command/testdata/test/mocking-invalid/tests/module_mocked_invalid_type.tftest.hcl, internal/command/testdata/test/mocking/tests/module_empty_outputs.tftest.hcl, internal/configs/mock_provider.go, internal/terraform/graph.go
When the `values` or `outputs` attribute was missing from the `override_*` blocks in the new mocking framework, we were setting the value to be `cty.NilVal`. This was then causing a crash later in the processing when Terraform was assuming the values in these attributes was an object.
From the perspective of the mocking framework a nil or empty value is the same, in both cases it should just generate the values required. This PR updates the config parsing so that it just sets the value to be an object always using `cty.EmptyObjectValue` if the attribute isn't specified. It also updates the Terraform graph where this is read so that it can safely handle a `cty.NilVal` anyway.
We also add in a quick bit of validation, that makes sure the config specifies the attributes as an object, if it …
=> mocking overrides: default to concrete empty object when values are missing

internal/command/testdata/show-json-sensitive/output.json, internal/command/testdata/show-json/conditions/for-refresh.tfstate, internal/command/testdata/show-json/conditions/output-refresh-only.json, internal/terraform/context_apply_test.go, internal/terraform/context_plan2_test.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/marks.go, internal/terraform/node_resource_abstract_instance.go
The original sensitivity handling implementation applied the marks from a resource schema only when decoding values for evaluation. This appeared to work in most cases, since the resource value could only be used elsewhere in the configuration by references that would be returned from the evaluator. However, this approach left holes in the handling of the instance values where some marks may have been inserted from its own references to sensitive value, but the instance's own sensitive attributes were left unmarked. This was most noticeable in the state storage, where only sensitive references were listed in `sensitive_attributes`, leaving the actual sensitive attributes unmarked.
The same problems would arise in the plan artifacts too, with the change `After` values missing attributes …
=> apply schema marks to returned instance values

internal/experiments/experiment.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/eval_count.go, internal/terraform/eval_count_test.go, internal/terraform/eval_for_each.go, internal/terraform/eval_for_each_test.go, internal/terraform/instance_expanders.go, internal/terraform/node_check.go, internal/terraform/node_local.go, internal/terraform/node_module_expand.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_validate.go
This set of changes aims to finally expose some of the previously-unreachable codepaths dealing with modules or resources that have unknown values as their `count` or `for_each`.
The work here is _far_ from done, but I've reached the point where I can no longer continue just adding dead code that isn't actually exercisable, and so this PR introduces a new language experiment named `unknown_instances` which, if enabled, will cause the expansion logic to tolerate unknown values in the relevant arguments and register the unknown-ness with the instance expander.
As usual with experiments, this is available only in dev and alpha builds. Even in alpha builds, it's enabled only when explicitly enabled for the modules that would rely on it. If the next minor release comes before the remaining …
=> A "unknown_instances" language experiment, allowing unknown values in count and for_each

docs/resource-instance-change-lifecycle.md
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/262
This is a quick documentation update to the Resource Instance Change Lifecycle page to explicitly call out that unknown values are never permitted in any resource instance state.
Only `main` is fine.
N/A
=> docs: Explicitly mention states should not contain unknown values

website/package-lock.json, website/package.json
Dev Portal was recently updated to use [Next V14](https://github.com/hashicorp/dev-portal/blob/main/package.json#L177). The package.json in the Terraform website repo has been updated to use updated versions of next, node, npm, and the two other HashiCorp packages. This is to prevent any errors during the deploy preview process and local development, which has been an issue for other product teams when deploying changes to Dev Portal.
=> [website] Update npm, next & node versions to be in sync with Dev Portal

internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/eval_context_scope.go, internal/terraform/evaluate.go, internal/terraform/evaluate_placeholder.go, internal/terraform/evaluate_valid.go, internal/terraform/evaluate_valid_test.go, internal/terraform/graph.go, internal/terraform/graph_interface_subgraph.go, internal/terraform/graph_walk.go, internal/terraform/graph_walk_context.go, internal/terraform/node_local.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go
This is a further iteration towards #30937, and follows on from yesterday's #34561.
This particular PR deals with plumbing in the evaluation nuts-and-bolts for graph nodes that are representing unbounded sets of as-yet-unknown instances of objects that are declared beneath a module call that has an insufficiently-known `count` or `for_each` argument.
This has a few different parts:
- A new implementation of `lang.Data` that's designed to return placeholder values that should represent what all instances of a given object have in common, while using unknown values for the parts where they differ.
In this initial round it's quite meagre and returns `cty.DynamicVal` in some situations where it could technically be more precise than that, but we can improve the precision later to give earlier …
=> core: Plumbing for graph nodes that belong to partially-expanded module prefixes

internal/terraform/node_local.go, internal/terraform/node_local_test.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go
This is a further iteration towards #30937, and follows on from yesterday's [#34561](https://github.com/hashicorp/terraform/pull/34571) (which needs to land first).
These commits implement the `Execute` method for the three graph node types representing input variables, local values, and output values under partially-expanded module prefixes. In all three cases the goal is twofold:
- Raise any errors where can be confident that they will _definitely_ happen once the expansion becomes fully-known, to shorten the iterative journey as much as we can.
- Produce a placeholder value that represents what all instances of the relevant object have in common.
For example, if the expression that defines the value is one that will always return a string but the exact string might vary between …
=> core: Generate placeholder results for named values under partially-expanded module prefixes

website/docs/language/settings/backends/azurerm.mdx
This PR refactors the documentation for the `azurerm` backend to provide clarity for users on the various authentication options. The existing documentation was missing clarity on the Access Key vs Entra ID option to access the storage account. This change is designed to provide that clarity and make it clear that the `use_azuread_auth` variable is not mutually exclusive with the other authentication options, it is additive.
Fixes N/A
1.7.1
-
=> docs: update azurerm backend docs

internal/terraform/node_provider.go, internal/terraform/node_provider_test.go
Currently, when the `ValidateProviderConfig` RPC fails as part of schema validation for a generated provider configuration block, we add an additional sourceless diagnostic that adds some context around the provider that failed saying the user should add an explicit configuration block.
We do not currently do this if the **schema** validation itself fails (such as missing a required attribute). This PR adds the same error message we generate for the failed provider validation call to the earlier schema validation. The logic is exactly the same: if a generated configuration block fails validation it means the user must write it themselves.
Fixes #34594 
Fixes #28482 
1.7.2
-  Add additional diagnostics when a generated provider block that fails schema validation requires explicit …
=> Add 'explicit configuration required' message when provider schema validation fails

internal/command/views/test.go
Annoyingly, I seem to have flubbed this slightly while I was adapting to use `enc.EncodeToken` instead of (as originally written) just writing the literal processing instruction bytes onto the front of the buffer directly. :confounded: 
This made the output invalid and therefore unreadable for any XML processor that interprets the special `xml` processing instruction. It'll now be valid again.
This JUnit XML output is currently behind an experiment guard and so only available in alpha releases. Merging this will not have any impact on on-alpha release behavior.
=> terraform test: Fix invalid XML processing instruction in experimental JUnit XML output

internal/moduletest/mocking/generate.go, internal/moduletest/mocking/values_test.go
Some data sources actually specify dynamic types as computed attributes, such as `tfe_outputs`. This PR adds support for dynamic attributes to the mock value generation. For a dynamic type, mock providers will now return a null value. This is different from the other types, which return usable concrete values. But, we cannot do this for dynamic types as we don't know which value to return. And an error saying the types are mismatched is more confusing than error saying the value is null.
An alternative here would be to try and add diagnostics telling the user they must provide concrete values for dynamic types, but this goes against the philosophy of the mocking framework which is to let users only worry about the data they actually need instead of expecting them to try and build a …
=> terraform test: prevent crash when mocking dynamic types

internal/builtin/provisioners/file/resource_provisioner.go, internal/builtin/provisioners/file/resource_provisioner_test.go
Instead of a panic return an error
Fixes #34454
1.7.x
- don't panic when file provisioner source is null
=> if file provisioners source is null throw error instead of panic

internal/terraform/context_eval.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_builtin_test.go, internal/terraform/eval_context_mock.go, internal/terraform/eval_context_scope.go, internal/terraform/eval_import.go, internal/terraform/graph.go, internal/terraform/graph_interface_subgraph.go, internal/terraform/graph_walk.go, internal/terraform/graph_walk_context.go, internal/terraform/node_module_expand.go, internal/terraform/node_resource_abstract_instance_test.go, internal/terraform/node_resource_abstract_test.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_destroy_deposed_test.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_import_state_test.go
This is a continuation of some restructuring started in #34571.
In those earlier commits my goal was to minimize breaking changes to the `EvalContext` API to churn existing code as little as possible.
However, the way I achieved that was to handle fully-expanded modules and partial-expanded modules as two completely separate codepaths, which means that all other code must statically decide which of the two cases it's dealing with even though there's not really any reason the `EvalContext` implementation couldn't support that being decided dynamically.
For the "deferred actions" work, in a future commit we'll need to introduce a new graph node type representing partial-expanded resources which must decide dynamically whether it's in a fully-expanded module scope or a partial-expanded …
=> terraform: Further generalization of the EvalContext scope handling

internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go
We can only detect this during evaluation since the import id is an hcl expression
Fixes #33505
1.7.x
- throw helpful error message if import block is configured with id ""
=> fix panic when import id is empty string

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
This makes the value easier to read and is mostly an aesthetic change.
Fixes #34444
1.8.x
-  In import-generated code represent JSON values in HCL instead of as strings
=> In import-generated code represent JSON values in HCL instead of as strings

internal/command/providers_lock.go, internal/providercache/dir.go
This is only possible for the architecture of the system since the cache is only for one architecture.
Fixes #33837
1.8.x
-  improve provider lock speed by using cache
=> improve provider lock speed by using cache

go.mod, go.sum
We use this utility library only in our tests. It was previously causing panics when comparing deeply-nested `cty.Value` structures due to a false-positive on `go-cmp`'s cyclic transformer check, but now (as of this new commit) handles nested values itself by doing its own recursion so that `go-cmp` believes it's only transforming one level of value.
=> go.mod: Upgrade github.com/zclconf/go-cty-debug

internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/provider_config_test.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go
When validating or applying a provider configuration, we must unmark the value before attempting to use plugin RPC, as we cannot serialize marks.
1.8.0
=> stackeval: Unmark provider config for plugin RPC

internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/plan-undeclared-variable-in-component/undeclared-variable.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/plan-undeclared-variable-in-component/with-single-input.tf
This PR fixes a null pointer exception that originates here: https://github.com/hashicorp/terraform/blob/main/internal/stacks/stackruntime/internal/stackeval/expression_refs.go#L142
The lines in question are:
```go
target, _ := m.ResolveAbsExpressionReference(ctx, ref, phase)
if target == nil {
continue
}
```
`target` is null, but makes it through the null check because of a quirk in the go type system. A golang value is made up of two elements, the type and the value. `nil` is a keyword that maps to `(type=nil,value=nil)`. In this case the logic in the modified function was essentially calling `Referenceable(nil)` (as it returns an `*InputValue` as a `Referenceable`). This means the value returned by that function was actually `(type=Referenceable,value=nil)` and not something equivalent …
=> Fix nil pointer exception when planning stacks with undeclared variables

website/docs/cli/commands/providers/schema.mdx
The ["Block Representation" in `terraform providers schema -json` documentation](https://developer.hashicorp.com/terraform/cli/commands/providers/schema#block-representation) seems to have wrong indentation and matching curly braces in the `"block types"` object.
=> website docs: fix "Block Representation" for `provider schema -json`

internal/logging/panic.go
Our goal with this panic-interception was to largely mimic how the Go runtime would normally report panics except for two intentional exceptions: an extra prompt explaining to the user that Terraform crashed, and exiting with status code 11 instead of 2.
Unfortunately we accidentally deviated in a different way: we're reporting to whatever `os.Stderr` happens to refer to, instead of to the real process stderr. It seems like that shouldn't really matter, but unfortunately go-plugin intentionally changes `os.Stderr` to refer to a totally separate stream that it manages, causing the captured panic messages from a `terraform rpcapi` process to be routed over a grpc-based channel to the plugin client, instead of into the real stderr pipe directly.
This deviation makes the panic messages not …
=> logging: Send captured panics to real stderr

internal/backend/local/test.go
This PR updates the testing framework to use the platform independent `filepath` package instead of the linux-only `path` package. This fixes loading and processing variable values loaded from automated variable files in the testing directory.
Fixes #34664
1.7.x
-  `terraform test`: Fix automatic loading of variable files within the test directory on `windows` platforms.
=> terraform test: use platform independent path functions

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/terraform/node_resource_plan_partialexp.go
"ProviderMeta" is a niche protocol feature that's used by only two providers on an experimental basis, but this code was written under the assumption that the caller would always provide it for any provider that has a schema for it, and unfortunately the Terraform SDK seems to always provide a meta schema even for providers that don't use it, and thus it's empty.
The current phase of the "unknown_instances" language experiment is not fully wired in to the main logic as a way to reduce the risk of it impacting behavior for those not participating in the experiment, but that means that right now it doesn't actually have a resolved ProviderMeta value to present, and so was just omitting it on the assumption that it is always optional to provide anyway.
As a pragmatic stopgap to resolve that …
=> plugin+plugin6: Don't panic if ProviderMeta not populated

.github/workflows/checks.yml, Makefile, copyright_headers.go, docs/plugin-protocol/copyright_headers.go, internal/tfplugin5/copyright_headers.go, internal/tfplugin6/copyright_headers.go, scripts/copyright.sh
This is a follow-up to https://github.com/hashicorp/terraform/pull/34617
In other words the aim here is to ensure we do not forget to add copyright/license headers for any future incoming code.
Here is a test run to verify this actually works: https://github.com/hashicorp/terraform/actions/runs/7799797486/job/21271331690?pr=34624#step:4:21
1.8.x
=> ci: Add test for license headers

internal/logging/panic.go
Programs that monitor Terraform's output to report panics often make the reasonable assumption that the string "panic:" is always included and is therefore safe to monitor for. Our custom handling that outputs the `!! TERRAFORM CRASH !!` banner unfortunately breaks these assumptions at the moment.
Instead of asking consumers to add their own handling to deal with this problem, let's add that greppable string to our custom panic output.
1.8.x
=> standardize panic output

.gitignore
The workspace files (`go.work` + `go.work.sum`) can be used when working on upstream dependencies (such as `hashicorp/hcl` in our case) and enable testing downstream here without having to touch `go.mod` or `go.sum`, i.e. delay the need to bump dependencies until the point of a PR.
Example of such a file:
```go
go 1.21.5
use .
replace (
github.com/hashicorp/hcl/v2 => ../hcl
)
```
Relevant docs for multi-module workspaces which enable the above: https://go.dev/doc/tutorial/workspaces
The (relative) paths included in those files are typically machine specific and so unlikely to work on other systems.
=> gitignore: Add `go.work{.sum}`

go.mod, go.sum, internal/lang/eval.go, internal/terraform/context_functions_test.go, internal/terraform/context_validate_test.go
The context of how to use provider functions is very specific to Terraform, and the generic diagnostics from HCL are very helpful to a user who is unfamiliar with how the functions are handled internally. This is more important here, because there are new concepts for even experienced users, and many are likely to encounter these errors when trying the new feature. 
For example, if a user forgot to add the provider to the module `required_providers`, HCL can only see that there is no function by the name and returns something like `There are no functions in namespace "provider::test::"`. Now we can make use of a new `FunctionCallUnknownDiagExtra` sentinel error type from HCL to detect any unknown function call, and replace the diagnostic messages with ones more suitable for Terraform. …
=> Better diagnostics for unknown provider functions

internal/stacks/stackruntime/apply.go
This was originally part of 7dad938fdb6bfeaf7cc082ce50bcf99f7889a2a9 but unfortunately seems to have got lost during some rebasing, or some other similar sort of annoying reason.
This now allows the "experiments allowed" flag to propagate into the stackeval package when we're running the apply phase, for consistency with all of the other phases. Without this, it's possible to plan a configuration that's participating in experiments, but then it fails in a strange way during the apply step due to Terraform suddenly thinking it's a stable release where experiments are disabled.
---
Unfortunately experimental features remain a bit of a testing hazard because we test them by enabling the "experiments are allowed" flag inline in the test, close to the code being tested, but in a real build …
=> stackruntime: Pass ExperimentsAllowed into stackeval for apply

internal/collections/set.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/sensitive-input-nested/sensitive-input-nested.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/sensitive-input/sensitive-input.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/single-input.tf, internal/stacks/stackruntime/testing/provider.go, internal/stacks/stackruntime/testing/store.go
This PR fixes 2 bugs in stacks' processing of sensitive values from outputs.
During planning, the `sensitive` attribute on output configuration blocks is essentially ignored. The value must be marked as `sensitive` by another source (like, the `sensitive(...)` function) for the sensitivity to be applied within stacks references. This PR fixes this by explicitly checking the configuration of the output blocks for the sensitive attribute, and applying the relevant marks.
During apply, because of [this](https://github.com/hashicorp/terraform/blob/main/internal/terraform/node_output.go#L702) line, the output values themselves do not have sensitive marks applied to them from the state ever. So, the only way the sensitive marks would be applied would be if we were checking the config attributes …
=> stacks: apply sensitive marks to outputs from components

internal/command/jsonformat/collections/slice.go, internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/plan_test.go
Fixes #33779
1.8.x
-  Improve plan UI for lists to display item-level diffs on lists with unchanged length
=> compare individual elements if list is same length and not reordered

internal/stacks/stackruntime/internal/stackeval/terraform_hook.go, internal/stacks/stackruntime/internal/stackeval/terraform_hook_test.go
The `terraform.Hook` implementation in `stackeval` is used to track the operations performed during stack runtime operations, for later reporting to the caller. This hook did not correctly support the replace actions (create-then-destroy, destroy-then-create), resulting in a loss of data between plan and apply. This exhibited as a plan with a replace reporting 1 add and 1 remove operation, which when applied would report only 1 add operation.
Previously, we stored the action performed for each apply operation on a given resource instance in the `PreApply` hook, then allowed access to it via the `ResourceInstanceObjectAppliedAction` method. Here we extend the `PostApply` hook to look for a previous action performed on this instance, and use that to reconstruct the planned replace action. …
=> stackeval: Add support for replace actions to hook

internal/command/jsonformat/computed/renderers/primitive.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/string.go, internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/jsondiff/types.go, internal/command/jsonformat/structured/change.go
When unmarshalling the JSON plan, the renderer now uses `json.Number` to represent numbers instead of `float64`.  This means that very large numbers (> 2^63) will no longer be truncated down to 2^63.
Fixes #34686
1.7.4 or whatever the next 1.7 release is.
-  plan renderer: Numbers larger than 2^63 will now be accurately rendered.
=> plan rendering: fix truncation of very large numbers

internal/backend/local/backend_local.go, internal/backend/local/test.go, internal/command/validate.go, internal/terraform/context_apply_test.go, internal/terraform/context_functions_test.go, internal/terraform/context_plan_test.go, internal/terraform/context_refresh_test.go, internal/terraform/context_test.go, internal/terraform/context_validate.go, internal/terraform/context_validate_test.go
This PR adds the `ExternalProviders` argument into the `Validate` function on the `terraform.Context` object.
This will allow us to call Validate over Stack components from the `stackeval.Validate` function. A follow-up PR will make use of this new functionality. For now, nothing is using the new `opts` argument.
=> stacks: add support for external providers to validate context

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/invalid-provider/invalid-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/missing-provider/missing-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/provider-name-clash/provider-name-clash.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/undeclared-provider/undeclared-provider.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
This PR explicitly checks the diagnostics produced by the `CheckProvider` function added in the last PR (#34705) as part of the stacks validate functionality. This means we get error messages if there are missing or undeclared providers in the `providers` block for components.
I've also added two additional test cases that are currently skipped during tests that describe assigning providers with the same underlying types but different local names (or the reverse in the error case). This isn't currently support but probably should be. I've expanded a TODO calling this out. I'll revisit this in a future PR.
=> stacks: check providers blocks in components during validatation

CHANGELOG.md
Fixes #
Add changelog entry for #34473 
1.8.x
-
=> add changelog entry for removing call to colorize on CLI-driven runs #34473

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/global_var_ref_in_suite_var/main.tf, internal/command/testdata/test/global_var_ref_in_suite_var/run_block_output.tftest.hcl, internal/command/testdata/test/global_var_ref_in_suite_var/terraform.tfvars, internal/moduletest/config/config.go, internal/moduletest/hcl/context.go, internal/moduletest/hcl/provider.go, internal/moduletest/hcl/provider_test.go, internal/terraform/context_apply.go, website/docs/language/tests/index.mdx
This allows practitioners to define variables in `.tfvar` files, environment variables, CLI flags and use them in the definition of suit-level variables in the top-level variables block.
Fixes #34534
Fixes #34538
1.8.x
-  test: allow using global variables in suite-level variable definitions
=> test: allow using global variables in suite-level variable definitions

.github/workflows/checks.yml
It is helpful to see the result of the checks workflow prior to opening a PR, to avoid wasting time fixing unexpectedly failing checks while the PR is open and awaiting review. This commit configures GitHub Actions to run checks on all pushed branches.
See https://github.com/hashicorp/terraform/commit/5b615882e228e0654aa0b2067205bb1a84452bc2 for the previous commit introducing the push filtering behaviour.
=> build: Run checks on all pushed branches

internal/stacks/stackruntime/internal/stackeval/main_plan.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/validate_test.go
Currently, we are reporting duplicate diagnostics during the planning stage. This is because we always execute the static evaluation and the dynamic evaluation, whether or not there were errors during the static evaluation. The dynamic evaluation then finds the same errors in the static evaluation, and then both sets are reported.
I think we should return early if the static evaluation finds problems. There's a comment in the `main_plan.go` file that indicates this was the original intent: [main_plan.go:106-109](https://github.com/hashicorp/terraform/blob/8fd29e943983473b44339bc7b05b7f45e6c208ce/internal/stacks/stackruntime/internal/stackeval/main_plan.go#L106-L109). However, this doesn't actually happen. The `reportDiags` function that sets the `seenAnyErrors` boolean is never actually …
=> stacks: the plan function should stop on validation errors

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/stack_call_config.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go
This PR extends the scope of the static evaluations so that we can follow references to providers, foreach, count, and self during static walks of a Stacks configuration.
We add the relevant references to `stack_config.go`, update `component_config.go` so it implements `ExpressionScope`, update the remaining static nodes so they handle the returned references properly.
This will be used to validate input variables and providers statically in later PRs. There's no behaviour changes here, as nothing uses the new behaviour yet.
=> stacks: expand reference scope of static validations

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/expressions.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/input-from-component-list/input-from-component-list.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/input-from-component/input-from-component.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/input-from-missing-component/input-from-missing-component.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/input-from-provider/input-from-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/missing-variable/missing-variable.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/undeclared-variable/undeclared-variable.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-output/single-output.tf, internal/stacks/stackruntime/validate_test.go
This PR adds variable validation into the static walk of the Stacks configuration. This means that missing variables, or badly typed variables, will be picked up by the Validate RPC command.
I've made the `ComponentConfig` an `ExpressionScope` so we can evaluate the input variable expressions, we don't use the returned value anywhere we just care about the diagnostics. The `ComponentConfig` and `ComponentInstance` now share the implementation for `CheckInputVariableValues`, so this has been extracted into a common location.
=> stacks: validate the types of input variables during validation

internal/stacks/stackplan/planned_change.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/remove_data_resource/step1/remove-data-resource-step1.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/remove_data_resource/step1/remove-data-resource-step1.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/remove_data_resource/step2/remove-data-resource-step2.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/remove_data_resource/step2/remove-data-resource-step2.tfstack.hcl
Due to an oversight in our handling of resource instance objects that are neither in configuration nor plan -- which is true for data resources that have since been removed from the configuration -- we were generating plan change objects that were lacking a provider configuration address, which made them syntactically invalid and thus not reloadable using the raw plan parser.
This is a bit of a strange situation since we don't technically _need_ a provider configuration address for these; all we're going to do is just unceremoniously delete them from the state during apply anyway. However, we always have the provider configuration address available anyway, so adding this in here is overall simpler than changing the parser, the models it populates, and all of the downstream users of those …
=> stackeval: Don't fail when data resource is removed

internal/configs/parser_config.go, internal/configs/source_bundle_parser.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid/invalid.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_child/.terraform/modules/modules.json, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_child/child/invalid_child.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_child/invalid.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_grandchildren/first/child/invalid_child.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_grandchildren/first/first.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_grandchildren/root.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_grandchildren/second/child/invalid_child.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/invalid_grandchildren/second/second.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/terraform-sources.json, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/invalid/invalid.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/invalid_child/.terraform/modules/modules.json, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/invalid_child/child/invalid_child.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/invalid_child/invalid.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/invalid_nested_remote/invalid_nested_remote.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/validating/nested_module_diagnostics/nested_module_diagnostics.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/validating_test.go, internal/stacks/stackruntime/validate_test.go
Stacks uses go-slug's source bundles in order to compile a full configuration. Until now, we've been loading Terraform modules within these source bundles with the standard configuration parser, which worked as a stop-gap.
However, configuration diagnostics were reported with module-relative paths as the source filename, which made it tricky to correctly load the configuration file in order to later display a snippet of related code. This PR replaces these paths with source addresses, allowing consumers of diagnostics to query the source bundle to reliably find the target file.
This change will require an update in the diagnostic handling code for consumers of stack diagnostics, which will come in separate PRs.
1.8.0
=> Add and use a source bundle aware configuration parser for stacks

internal/builtin/providers/terraform/functions.go, internal/builtin/providers/terraform/functions_test.go, internal/builtin/providers/terraform/provider.go, internal/command/e2etest/terraform_provider_funcs_test.go, internal/command/e2etest/testdata/terraform-provider-funcs/terraform-provider-funcs.tf, website/data/language-nav-data.json, website/docs/language/functions/terraform-exprencode.mdx, website/docs/language/functions/terraform-tfvarsdecode.mdx, website/docs/language/functions/terraform-tfvarsencode.mdx
Using the new possibility of provider-contributed functions, this introduces three new functions which live in the
`terraform.io/builtin/terraform` provider, rather than being language builtins, due to their Terraform-domain-specific nature and the fact that they should not be needed by most Terraform module authors.
The three new functions are:
- `tfvarsencode`: takes a mapping value and tries to transform it into Terraform CLI's "tfvars" syntax, which is a small subset of HCL that only supports key/value pairs with constant values.
- `tfvarsdecode`: takes a string containing content that could potentially appear in a "tfvars" file and returns an object representing the raw variable values defined inside.
- `exprencode`: takes an arbitrary Terraform value and produces a string that would …
=> provider/terraform: Terraform-specific encoding functions `tfvarsencode`, `tfvarsdecode`, and `exprencode`

internal/configs/config.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/valid/valid.tfstack.hcl, internal/stacks/stackruntime/validate_test.go, internal/terraform/providers.go
Currently, stacks resolves provider types entirely by doing reverse look ups against the local name of the provider within the stack configuration. It then tries to resolve the provider map within components by looking up the provider entries by that local name. There is no guarantee that the local names between the component configs and the stack configs will match up.
This PR makes the `RequiredProviderInstances` lookup function also return the `LocalProviderConfig` address. This means we can look up the local name for the required provider in the stack configuration separately to resolving the local name within the component configuration.
We also expand the static analysis so that it checks the type of the returned references (to make sure they are referencing providers). The dynamic …
=> stacks: validate providers based on types instead of local names

website/docs/cli/state/resource-addressing.mdx, website/docs/language/functions/csvdecode.mdx, website/docs/language/functions/flatten.mdx, website/docs/language/functions/setproduct.mdx, website/docs/language/meta-arguments/for_each.mdx
While objects in `for_each` do not strictly yield _invalid_ configuration, we explicitly document that `for_each` expects maps or sets.
In most places I am proposing to fix, the wording near those snippets even explicitly mentions _map_ while providing a snippet which has (although implied) _object_.
I think this contributes to confusion of users about types.
=> website: ensure `for_each` examples take maps

internal/command/jsonformat/differ/attribute.go, internal/command/jsonformat/differ/block.go, internal/command/jsonformat/plan_test.go, internal/command/jsonformat/structured/change.go, internal/command/jsonformat/structured/map.go
Changes between empty strings and `null` were hidden in the CLI output, because the SDK could not reliably detect the difference and may return either value depending on the situation.
This legacy behavior can be confusing for authors of new providers which can correctly handle `null`, and it would be preferable to be able to render those changes in the CLI.
While we don't have enough information to detect when the legacy behavior is required, we can detect a number of cases where it's certain that we are not dealing with a legacy schema and should output the full diff:
- Anything with nested structural attributes
- Blocks of type NestingMap and NestingGroup
- Dynamic types
While this cannot solve all issues when the resource only uses primitive types, like with `random_password` in …
=> try to render some changes between `""` and `null`

go.mod, go.sum
Update hcl to the latest release in preparation for v1.8
---
- Support for namespaced functions (https://github.com/hashicorp/hcl/pull/639)
- ext/dynblock: if iterator is invalid return this error instead of consequential errors (https://github.com/hashicorp/hcl/pull/656)
---
Also contains a recent fix for a core issue:
Closes #34132
=> update hcl v2.20.0

internal/configs/experiments.go
Due to some specific circumstances around how this experiment reached stabilization we made a planned-temporary exception to make it valid to specify even in non-alpha builds of Terraform, just to be able to return a more precise error message.
The comment added at the time suggested that we remove this "a release or two after v1.3", and v1.8 is the actively-developed release at the time I'm writing this so we've kept this around far longer than we originally felt we needed to. It's time for it to go.
This particular experiment will now get the same treatment as all others when used in a non-alpha release: Terraform will return the general error about experiments only being available in alpha releases. Since this experiment has concluded, it will also return an error in alpha releases, …
=> configs: Don't treat module_variable_optional_attrs as special

internal/rpcapi/terraform1/terraform1.pb.go, internal/rpcapi/terraform1/terraform1.proto, internal/stacks/stackplan/planned_change.go, internal/stacks/stackplan/planned_change_test.go
Sends the [replace path](https://developer.hashicorp.com/terraform/internals/json-format#change-representation) through the JSON API.
Co-authored-by: Katy Moe <katy@katy.moe>
Fixes #
1.8.x
-  Stacks: Terraform Core now exposes  replace paths in change descriptions in the RPC API
=> stacks: expose replace paths in grpc api

internal/command/apply.go, internal/command/meta_providers.go, internal/command/plan.go, internal/command/validate.go
[JIRA Ticket](https://hashicorp.atlassian.net/browse/TF-3325)
Adds a remote specific line to the warning associated with plan and apply operations using provider overrides in the CLI config when a remote backend is being used. 
also how it was previously in either case
-  Modified provider developer override warning to include remote specific warning when a remote backend is being used
=> Modify provider dev override warning to include a remote backend specific line

internal/backend/local/backend_plan_test.go, internal/backend/remote-state/s3/backend_test.go, internal/checks/state.go, internal/command/e2etest/automation_test.go, internal/command/jsonplan/plan.go, internal/command/meta_backend_migrate.go, internal/getproviders/package_authentication.go, internal/registry/test/mock_registry.go, website/README.md
Manual backport of https://github.com/hashicorp/terraform/pull/34776 into v1.7 after failure of https://github.com/hashicorp/terraform/pull/34778.
=> manual backport of remove repetitive words into v1.7

website/docs/language/modules/sources.mdx
Manual backport of https://github.com/hashicorp/terraform/pull/34692 into v1.8 after failure of https://github.com/hashicorp/terraform/pull/34788.
Note that the final commit https://github.com/hashicorp/terraform/pull/34790/commits/8f6ddfa4cb32ac0be9aa11a61ad65136bc297074 replaces https://github.com/hashicorp/terraform/pull/34692/commits/b496edd1d30275d5016e63ac2c39b88a52cf0b00, which is a merge commit.
=> manual backport of docs update into v1.8

website/docs/language/modules/sources.mdx
Manual backport of https://github.com/hashicorp/terraform/pull/34692 into v1.7 after failure of https://github.com/hashicorp/terraform/pull/34787.
Note that the final commit https://github.com/hashicorp/terraform/pull/34790/commits/8f6ddfa4cb32ac0be9aa11a61ad65136bc297074 replaces https://github.com/hashicorp/terraform/pull/34692/commits/b496edd1d30275d5016e63ac2c39b88a52cf0b00, which is a merge commit.
=> manual backport of docs update into v1.7

internal/terraform/context_validate.go, internal/terraform/context_validate_test.go
Schema errors are normally handled when the schema is retrieved at the point it's used. This however fails for functions, which are loaded in a context that cannot easily handle errors. Most code paths will end up loading schemas before calling a function, but in the case that a provider is used for one of its functions without any resources, the validate walk could end up skipping the error checks.
Force the loading of provider schemas as early as possible during validation, to ensure we can handle any diagnostics we receive. This won't add any extra overhead to `validate` which aims to be as efficient as possible, since we're caching the schemas for all future calls during the operation.
Fixes #34777
=> load provider schemas early during validation

go.mod, internal/backend/remote-state/azure/client.go, internal/backend/remote-state/consul/client.go, internal/backend/remote-state/cos/client.go, internal/backend/remote-state/gcs/client.go, internal/backend/remote-state/oss/client.go, internal/backend/remote-state/s3/client.go, internal/cloud/backend_taskStages.go, internal/command/clistate/local_state.go, internal/configs/configschema/internal_validate.go, internal/configs/configschema/internal_validate_test.go, internal/dag/dag.go, internal/states/statemgr/filesystem.go, internal/tfdiags/diagnostics.go, internal/tfdiags/diagnostics_test.go
In the early days the Go standard library lacked various useful helpers for wrapping and combining errors and so various parties, including HashiCorp itself, wrote separate libraries to fill those gaps.
However, recent improvements to the standard library have made those all redundant. There's now sufficient functionality in the standard library to support all of Terraform's error wrapping and combining needs.
This therefore removes all of the uses of the following three modules from our non-legacy packages:
- `github.com/pkg/errors`
- `github.com/hashicorp/go-multierror`
- `github.com/hashicorp/errwrap`
The latter two still have callers in the packages under our `legacy` directory, but we'll hopefully eventually take care of those with a combination of …
=> Remove three redundant error-related dependencies

internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/plan-no-value-for-required-variable/unset-variable.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/plan-variable-defaults/child/child.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/plan-variable-defaults/deployments.tfdeploy.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/plan-variable-defaults/plan-variable-default.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
When evaluating a stack's root input variables, supplied by the caller, we must apply any default values specified in the variable configuration for variables with no specified value. This commit adds this default fallback case, using NilVal as a marker indicating the lack of a specified value.
If no default value exists for a variable, it is therefore required to be supplied by the caller. This commit also reports a diagnostic error in this case.
1.8.x
=> stackruntime: Apply defaults to root variables

go.mod, internal/backend/local/test.go, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client_test.go
This module was a temporary home for what are now the standard library "slices" and "maps" packages. We're building Terraform with a sufficiently new version of Go that we can use the standard library equivalents, so we no longer need this dependency.
It lives on as an indirect dependency for now because hashicorp/aws-sdk-go-base is also using it, but hopefully it'll vanish altogether in future if that library is updated to also use stdlib instead.
=> dependencies: No more golang.org/x/exp

internal/cloud/tfe_client_mock.go, internal/copy/copy_value.go, internal/copy/copy_value_test.go, internal/states/statefile/upgrade_helper.go, internal/states/statefile/version1_upgrade.go, internal/states/statefile/version2_upgrade.go
This is part of an ongoing effort to shed as many legacy dependencies as possible so that we can eventually reduce our dependency surface area.
Terraform used to make extensive use of the various reflection-based utility helpers that mitchellh published, but they tended to make maintenance very difficult by obscuring what was really going on and so we've _mostly_ moved away from using them in modern Terraform. They are also, as far as I'm aware, no longer actively maintained.
Aside from the packages under `legacy` that are just snapshots of bits of Terraform v0.11 we retain as technical debt (see https://github.com/hashicorp/terraform/pull/34793 and https://github.com/hashicorp/terraform/pull/34772), all of the remaining uses were very simplistic situations where copystructure's …
=> dependencies: Remove our few remaining (unnecessary) uses of mitchellh/copystructure and mitchellh/reflectwalk

internal/cloud/migration.go, internal/cloud/migration_test.go, internal/command/clistate/local_state.go, internal/command/command_test.go, internal/command/meta.go, internal/command/meta_backend.go, internal/command/unlock_test.go, internal/command/workdir/backend_state.go, internal/command/workdir/backend_state_test.go, internal/command/workspace_command_test.go
As a leftover of the Terraform v0.12 work back in 2019, we continued using a snapshot of the Terraform v0.11 version of `package terraform` for two main purposes:
1. To support the nearby snapshot of the legacy Terraform SDK that most of the remote state backends use.
2. To use a tiny subset of the state snapshot loading and saving code and models to represent Terraform CLI's "backend state" format, which tracks the active backend configuration for each working directory.
This PR eliminates the second case. Most of the changes here are in migrating the tiny sliver of legacy `package terraform` functionality that was related to Terraform CLI backend state into `command/workdir`, which is the package we use to deal with working-directory-related concerns.
Ideally we'd access the backend …
=> Eliminate all non-legacy uses of the "legacy/terraform" package

internal/command/jsonconfig/expression.go, internal/configs/checks.go, internal/configs/resource.go, internal/lang/eval.go, internal/lang/eval_test.go, internal/lang/globalref/analyzer_meta_references.go, internal/lang/globalref/analyzer_meta_references_shortcuts.go, internal/lang/langrefs/references.go, internal/lang/scope.go, internal/legacy/go.mod, internal/legacy/go.sum, internal/moduletest/eval_context.go, internal/moduletest/hcl/context.go, internal/moduletest/hcl/provider.go, internal/terraform/eval_conditions.go, internal/terraform/eval_for_each.go, internal/terraform/evaluate_valid_test.go, internal/terraform/node_check.go, internal/terraform/node_local.go, internal/terraform/node_module_expand.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_validate.go, internal/terraform/transform_reference.go, internal/terraform/validate_selfref.go
Finding references in an expression is a static analysis operation, but we previously had it grouped in with "package lang" that primarily deals with dynamic evaluation of expressions.
We need to do static analysis in far more locations than we do full expression evaluation, the static-analysis-only callers don't need anything else from package lang, and the reference-analysis functions are self-contained little wrappers around the address parsing logic in package addrs anyway.
Splitting these into a separate package therefore minimizes which packages depend indirectly on package lang, and thus which packages depend indirectly on the implementations of the built-in functions. Some of the built-in functions rely on dependencies we don't use anywhere else, so cutting these out shrinks how …
=> langrefs: Separate package for expression reference analysis

internal/builtin/providers/terraform/functions.go, internal/builtin/providers/terraform/functions_test.go, internal/builtin/providers/terraform/provider.go, internal/command/e2etest/testdata/terraform-provider-funcs/terraform-provider-funcs.tf, website/data/language-nav-data.json, website/docs/language/functions/terraform-decode_tfvars.mdx, website/docs/language/functions/terraform-encode_expr.mdx, website/docs/language/functions/terraform-encode_tfvars.mdx
When we added these functions we hadn't yet settled on a single convention for how provider-contributed functions ought to be named, and so these followed the convention previously used for Terraform's own built-in functions.
We've now decided to use the new provider namespace as an opportunity to partially fix the historical design error of naming functions as all lowercase without any separation between words. [The documented convention for providers is underscore-separated words](https://developer.hashicorp.com/terraform/plugin/best-practices/naming#function-names). This makes the provider functions inconsistent with the built-in functions, but should at least hopefully encourage the provider functions to be consistent with one another, so that the rule for which to use is relatively …
=> provider/terraform: Use new convention for function names

.github/workflows/checks.yml
A few of the packages in this repository are separated into their own Go modules to reflect boundaries of code ownership and/or boundaries with significantly different external Go module dependencies.
However, that means that the `./...` pattern in a Go command run at the root doesn't include those packages. The tests in the remote backends are mostly disabled in our unit test context because they require credentials for external network services, but nonetheless it's still useful to visit them and check if their packages can even compile.
Therefore we'll now visit each of the modules and run tests for all packages in each one. This restores the coverage we had before the module split, with the only slight difference being that the remote backend tests now run only after all of the main …
=> workflows/checks: Run tests for all modules in this repository

CODEOWNERS
We were using the CODEOWNERS file prior to GitHub having special support for it just as human documentation. GitHub has since claimed this file format as belonging to them, and declared our use of it invalid.
This PR therefore:
- Clears out some obsolete entries that refer to directories we already deleted long ago.
- Uses commented-out entries to retain the information that's useful to humans but not to GitHub, because some of our code owners are not HashiCorp employees and so cannot be requested as PR reviewers in this repository.
- Removes an obsolete HashiCorp team `hashicorp/terraform-ecosystem-strategic`, since ~it doesn't exist anymore and so cannot be requested as a reviewer.~
On further investigation I see that it _does_ exist as a team but that the team doesn't have any access …
=> CODEOWNERS: Make it valid, and exclude go.sum updates

website/docs/language/expressions/custom-conditions.mdx
It was pointed out that the example in the Custom Conditions docs that shows how to use a data source to validate conditions on resources, `root_block_device` is exposed as a list containing an object, so you must include an index when referencing it.
Running the example as-is fails validation with the below error:
```
│ Error: Invalid operation
│
│   on main.tf line 35, in data "aws_ebs_volume" "example":
│   35:     values = [aws_instance.example.root_block_device.volume_id]
│
│ Block type "root_block_device" is represented by a list of objects, so it must be indexed using a numeric key, like
│ .root_block_device[0].
```
=> Update custom conditions doc: root_block_device requires an index

internal/command/cliconfig/provider_installation.go
This pull request adds environment variable interpolation to the `dev_overrides` configuration block, specifically for the local filesystem path being mapped to the provider source address.
Before the proposed change:
```hcl
provider_installation {
dev_overrides {
"craigsloggett/github" = "/Users/craig.sloggett/.cache/go/bin"
}
direct {}
}
```
After the proposed change:
```hcl
provider_installation {
dev_overrides {
"craigsloggett/github" = "${GOPATH}/bin"
}
direct {}
}
```
Fixes #28602
1.8.x
-  Maintaining a `terraform.rc` file that's portable across systems, platforms, or users.
=> Interpolate environment variables when configuring dev_overrides

internal/providers/testing/provider_mock.go, internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/marks.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_partialexp.go
Rather than try to collect marks from configuration and the provider schema for direct comparison in a plan, we can opt to compare the marks as they were applied to the given values. This is important because a schema may declare a sensitive mark path which will not be stored in the final value if that path crosses a set type. Within the object, the marks are adopted by the set, and no longer tracked on individual set elements.
We also need to re-add any schema marks during apply, since complex computed values may have nested marks which could not be saved within the unknown plan values.
Finally we can remove the `dedupePathValueMarks` function, which was only really there to ensure that arbitrary sets of `PathValueMarks` could be compared directly, but we no longer have a need for that …
=> Always add all marks to plan and apply values, then compare marks from the values

internal/backend/backendrun/operation.go, internal/backend/local/backend_local.go, internal/command/apply.go, internal/command/arguments/extended.go, internal/command/plan.go, internal/command/refresh.go, internal/experiments/experiment.go, internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/planning.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/deferred_changes_propagation/deferred-changes-propagation.tf, internal/terraform/context_apply_deferred_test.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/context_walk.go, internal/terraform/evaluate.go, internal/terraform/node_module_expand.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan.go, internal/terraform/transform_config.go
This PR adds a top-level per-plan option to enable deferred actions (i.e., automatically de-targeting objects that cannot be planned until after this full plan/apply cycle), so that callers initiating a plan can opt into it based on their own criteria. 
Deferred actions is an experimental feature, and is not enabled by default for any current planning flow. 
This PR **replaces** an existing language experiment called `unknown_instances`, which was @apparentlymart's research spike on the first chunk of this design problem; experimental builds of Terraform can no longer opt into that behavior via the `experiments` attribute of the `terraform` config block. Instead, you can enable deferred actions for a given run by passing the new `-allow-deferral` command line option. This option is only …
=> Allow enabling deferred actions in PlanOpts

website/docs/language/state/sensitive-data.mdx
Updates this page (https://developer.hashicorp.com/terraform/language/state/sensitive-data) of the documentation to reflect gcs backend features added in the past. See: https://developer.hashicorp.com/terraform/language/settings/backends/gcs
1.8.1
Do docs changes need a release target? 
-
=> docs: Update 'Sensitive Data in State' page to describe encryption features of gcs backend

website/docs/language/modules/develop/refactoring.mdx
I'm not updating the docs for `terraform state mv` as that command does not support cross-type moves. Only the `moved` blocks do.
The providers declare which cross-type moves are available to them, so we can only say here that "some" resources support this, and ask the readers to look at the provider docs for clarification on "some".
=> Update docs to clarify cross-type moves

internal/plans/deferring.go, internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/plans/planfile/tfplan.go, internal/plans/planfile/tfplan_test.go, internal/plugin/convert/deferred.go, internal/plugin/convert/deferred_test.go, internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/convert/deferred.go, internal/plugin6/convert/deferred_test.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go, internal/providers/provider.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_abstract_instance_test.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_orphan.go
Co-authored-by: Matej Risek <matej.risek@hashicorp.com>
1.8.x
-  stacks: handle deferred actions in refresh
=> stacks: handle deferred actions in refresh

internal/addrs/partial_expanded.go, internal/addrs/partial_expanded_test.go, internal/terraform/context_apply.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_apply_deferred.go, internal/terraform/node_resource_partial_plan.go, internal/terraform/transform_deferred.go, internal/terraform/transform_targets.go
This PR completes the implementation of targeting deferred resources.
We've added a new type of node to the apply graph, which holds the deferred resources. The deferred resources do not implement an `Execute` function, so they make no changes to the state or the underlying cloud providers. They do implement the `GraphNodeReferencer` and `GraphNodeReferenceable` interfaces, that ensure the apply graph now contains a representation for deferred resources that allow the `TargetsTransformer` to correctly include any dependencies of deferred changes that have been targeted. We will also use these new deferred nodes in an upcoming PR for calculating the correct outputs.
In addition, the `DeferredTransformer` updates the node expanders to skip expansion for partial resources. This saves us …
=> Complete implementation of targeting with deferred resources

internal/backend/local/test.go, internal/command/views/test.go, internal/moduletest/run.go
In https://github.com/hashicorp/terraform/pull/34291 we introduced an experimental option for `terraform test` to produce JUnit XML output, in the hope of collecting feedback to eventually resolve https://github.com/hashicorp/terraform/issues/34264.
The first round of experiment yielded some good information about how different JUnit XML-consuming software expects the data to be structured. As expected, because this format was designed for Java there are various different ways to map non-object-oriented language concepts onto it, and thus we didn't quite nail it on the first round.
This second round makes two changes in response to the feedback:
- The test scenario filename also gets populated into the `classname` attribute of each test case, in addition to its previous placement as the …
=> terraform test: Another round of the JUnit XML output experiment

internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/string.go, internal/command/jsonformat/structured/change.go
*Don't merge (or at least backport) this until after the release of 1.8.0 has been completed this week.*
In https://github.com/hashicorp/terraform/pull/34702 we modified the JSON parsing of the plan renderer to support large (> 2^64) numbers. In doing so we changed the parsing to use the json.Decoder. The Decoder accepts partial JSON strings, so this means that a string that starts with a valid JSON object and then ends with a non-JSON piece of text is interpreted as valid JSON.
This PR updates the renderer so it checks the decoder has consumed the complete string before trusting that the returned object can be rendered as JSON. 
In Martin's comments, he details how the `ctyjson` package supports this and the large number parsing by default. Unfortunately, we can't use the `ctyjson` …
=> plan renderer: ensure JSON strings are completely JSON

website/docs/language/functions/filemd5.mdx, website/docs/language/functions/filesha1.mdx, website/docs/language/functions/md5.mdx
Just a simple doc update to add/improve security notices for `filemd5`, `md5`, and `filesha1` functions.
=> doc: Add and Improve Security Notices for `filemd5`, `md5`, and `filesha1` functions

website/docs/cli/config/environment-variables.mdx
Per the description, a user was confused about the usage and lack of documentation around TERRAFORM_CONFIG. It would help newer users update old configs if this was documented in some fashion.
Fixes #34898, #15849
=> Add a note about TERRAFORM_CONFIG to help with migration old configs.

internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/node_module_expand.go, internal/terraform/transform_reference.go
This PR fixes two crashes within Terraform v1.8.0. In both cases a module expansion was being missed, and then crashing when something tried to reference the missed module.
The first occurs when referencing an output that doesn't exist within the `try()` function. In this case the executing node was not getting connected to the module expansion node because the output node to connect doesn't exist. Now, the `transform_reference` transformer will unfold module call output references into simple module call references if the target node for a module call output does not exist.
The second occurs when referencing a module block directly (ie. not a module output), on a module that has no changes during the apply. The module expansion node was being removed as it had no direct references (as no …
=> Fix panics due to missing graph edges on empty modules or invalid refs

internal/refactoring/move_statement.go, internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf, internal/terraform/context_plan2_test.go
A `moved` block may target an address which does not exist, either due to error, or because subsequent refactoring has removed that resource entirely. There was already a check in place to guard when the target resource config did not exist, but a check for a missing module containing that resource address was overlooked and would cause a panic.
Fixes #34995
1.8.1
- `moved`: Fix crash when move targets a module which no longer exists
=> Move target may be in a module which does not exist

internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/providers/provider.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_abstract_instance.go
Co-authored-by: Mark DeCrane <mark.decrane@hashicorp.com>
1.8.x
-  stacks: adding deferred action to datasource reads
=> stacks: adding deferred action to datasource reads

website/docs/language/style.mdx
Change spelling from 'flat' to 'flag' to fix typo
Fixes: Typo in docs
=> docs: fix typo in spelling of 'flag'

website/docs/language/style.mdx
Correct spelling from 'Sential' to 'Sentinel'
=> docs: fix typo in spelling of 'Sentinel'

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/providers/provider.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_plan_destroy.go, internal/terraform/node_resource_plan_orphan.go
I would recommend reviewing this on a commit-by-commit basis since I included a refactoring.
Co-authored-by: Mutahhir Hayat <mutahhir.hayat@hashicorp.com>
1.8.x
-  stacks: add deferrals to PlanResourceChange
=> stacks: add deferrals to PlanResourceChange 

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go, internal/terraform/context_plan_import_test.go
This PR fixes a crash that occurs when generating configuration for a resource with "complex" sensitive attributes. Complex in this case means a list, set, map or object. Basically anything not a primitive type.
This bug was exposed by an earlier fix in which we started properly marking sensitive attributes within the plan, instead of waiting for the plan renderer to handle these directly (#34567). Now that sensitive marks will appear on values returned by the provider the config generation logic crashes as it is not checking for sensitive marks in the correct places.
The linked stack trace indicates this is happening during the `omitUnknowns` function. The fix in this case is to simply remove that function. As of #34525, it is impossible for us to encounter unknowns at this point anyway …
=> Fix crash when generating config for a resource with complex sensitive attributes

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/sensitive_input_values/main.tf
Previously, the Terraform plan functionality forbade input values with sensitive marks. The testing framework avoided this by removing the sensitive marks from inputs, and printing a warning if the input variable was not marked as sensitive. As of https://github.com/hashicorp/terraform/pull/34414 the terraform plan can now handle sensitive marks on input values. This means the testing framework no longer needs to remove sensitive marks, and warn users about the sensitive metadata being lost.
There's also a flyby refactoring of the tests in test_test.go to remove the init output from the expected/actual comparisons introduced as part of the recent `init` command refactoring. We don't care about validating the init output for theses tests.
Fixes #35011
1.9.0
-  `terraform test`: The test …
=> terraform test: don't remove sensitive marks from inputs

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_abstract_instance.go
This PR updates the order of validations that happen after an `ApplyResourceChange` operation. Previously, we restored the sensitive marks on the new value before validating that is was wholly known. If the value was not wholly known, then a panic might occur during the `UnknownAsNull` fix up call that ensures there are no unknown values present. 
Now, we restore the sensitive marks only after this validation has been completed. This ensures there are no sensitive marks during the `UnknownAsNull` function call.
This change should be safe as only validations occur between the old point and new point of mark reapplication. The attributes within the value are not exposed by these validations.
Fixes #35039 
1.8.2
-  `terraform apply`: Prevent panic when a provider erroneously provides
=> terraform apply: restore marks after unknown validation

internal/terraform/node_resource_plan.go, internal/terraform/validate_selfref.go, internal/terraform/validate_selfref_test.go
Manual backport of #35047. Replaces failed automatic backport in #35053.
Relates to #35038
=> Backport of Validate self-references within resource count and foreach arguments

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_abstract_instance.go
Manual backport of #35048. Replaces the failed automatic backport in #35054.
Relates to #35039.
=> Backport of terraform apply: restore marks after unknown validation

go.mod, go.sum, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.sum, internal/legacy/go.sum
This adopts the recent 1.7.4 release of the HashiCorp-maintained `go-getter` library, which includes a fix for CVE-2024-3817.
Terraform is not affected by this vulnerability, due to checks implemented around the usage of the vulnerable function, but we're upgrading to stay current and avoid scan noise.
The change within the library is relatively minor in nature, per https://github.com/hashicorp/go-getter/compare/v1.7.3...v1.7.4.
1.8.x
- Updated to new github.com/hashicorp/go-getter release, which addressed CVE-2024-3817. (Terraform was not exposed to this vulnerability due to checks implemented around its usage of the vulnerable function.)
=> go get github.com/hashicorp/go-getter && go mod tidy

internal/terraform/context_walk.go, internal/terraform/graph.go
The main goal here is to temporarily disable the `ResourceGraph` creation during normal plans, to avoid the overhead when deferrals are not being used. The `*deferring.Deferred` value is referenced in many places now throughout core, so we make sure to replace it with a valid empty value.
While we're in here, the `reducePreservingRelationships` gets an optimization that was ready anyway. The algorithm to remove nodes can be done in a single pass when removing the nodes immediately. As each node is removed and replaced with the product of all edges, those edges will already be in place for the next steps if those new edges connect to more nodes which will be removed.
=> Optimize, then disable ResourceGraph during normal plans

internal/terraform/context_plan2_test.go, internal/terraform/context_walk.go, internal/terraform/graph.go
Manual backport of #35066. Automatic backport failed in #35072.
=> Backport of optimize and disable resource graph

internal/command/jsonplan/plan.go, internal/command/jsonplan/resource.go
This PR adds support for rendering the deferred actions within the JSON plan output produced by `terraform show -json <planfile>`.
This is needed for providers to test their implementation of the deferred actions within the plugin protocol.
=> deferred actions: include deferred resources within JSON plan output

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
* `msgpack`: Now uses string encoding instead of float encoding for a whole number that is too large to fit in any of MessagePack's integer types.
* `function/stdlib`: Type conversion functions (constructed with `MakeToFunc`) can now convert null values of unknown type into null values of the target type, rather than returning an unknown value in that case.
* `json`: Will now correctly reject attempts to encode `cty.DynamicVal`, whereas before it would just produce an invalid JSON document without any error. (This is invalid because JSON encoding cannot support unknown values at all; `cty.DynamicVal` is a special case of unknown value where even the _type_ isn't known.)
Closes #34866
=> update go-cty v1.14.4

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.sum, internal/logging/logging.go
We were importing this to resolve an init-time conflict with this library when it was indirectly loaded by the etcd libraries.
We removed the etcd backends a while back and so we no longer use any of the etcd modules in Terraform, and so this tricky import was our only remaining reference to github.com/coreos/pkg/capnslog.
Dropping this eliminates two unnecessary dependencies.
This is only in the dependency chain for the backends because they refer directly or indirectly to the `logging` package, so this will not affect backend behavior.
=> logging: Remove import github.com/coreos/pkg/capnslog

internal/backend/backendbase/base.go, internal/backend/backendbase/sdklike.go, internal/backend/backendbase/sdklike_test.go, internal/backend/remote-state/gcs/backend.go, internal/backend/remote-state/gcs/backend_test.go
This is a follow-on from #34989, since that change caused the backend's validation to be slightly less strict.
Although the slight decrease in strictness is not a huge problem, it's desirable to retain at least the same level of validation correctness we had before because the SDK's liberal treatment of values is _already_ likely to be a challenge once we eventually move these backend implementions into providers and try to rework them to use the modern plugin framework, and so we'd rather introduce as little _new_ validation-sloppiness as possible in this interim step of using `backendbase` instead of the legacy SDK.
---
Previously we tried a simplification where any attribute with an "SDK-like default" was guaranteed to never be null, because that seemed like a plausible mimic of the …
=> backendbase: Preserve unset arguments as null when not set by env

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/providers/provider.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/context_import_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_abstract_instance_test.go, internal/terraform/node_resource_apply_instance.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_orphan.go
Fixes #
1.8.x
-  stacks: allow deferring import calls (through CLI or import blocks)
=> stacks: handle deferred import

internal/terraform/transform_attach_config_resource.go
The current implementation of `AttachResourceConfigTransformer` has performance of `O(N^2)` to the number of vertices in the graph, and this leads to significant performance degradation on huge graphs.
The given implementation decreases the complexity to `O(N)` by performing direct lookup of a resource in the `ManagedResources` or `DataResources` depending on the object type.
Fixes #35087
1.8.x
-
=> Improve performance of AttachResourceConfigTransformer on big graphs

internal/terraform/transform_attach_config_resource.go
The format of the resource keys in a `configs.Module` is an internal implementation detail, and should not be compared outside of the configs package. A module config already has a `ResourceByAddr` method we can use here which looks up a resource config by address.
=> AttachResourceConfigTransformer : use `ResourceByAddr` to lookup resource config

internal/terraform/context_apply_overrides_test.go, internal/terraform/graph.go
While we don't normally encounter providers within modules, they are technically still supported, and could exist within a module which has been overridden for testing. Since the module is not being evaluated overall, we cannot safely evaluate the provider config.
The override is handled similarly to the resource overrides during the graph walk. We can more easily handle the override logic in the same location, without having to pipe the information through multiple graph builders and transformers to store in the provider nodes themselves.
Fixes #35097
=> Don't evaluate providers within overridden modules

internal/terraform/context_apply_overrides_test.go, internal/terraform/graph.go
Manual backport of #35110
----
While we don't normally encounter providers within modules, they are technically still supported, and could exist within a module which has been overridden for testing. Since the module is not being evaluated, we cannot safely evaluate the provider config as variables will not exist within that module.
=> Backport #35110: Don't evaluate providers within overridden modules

website/data/language-nav-data.json, website/docs/language/moved.mdx
This PR adds proper configuration reference for the `moved` block in the Terraform language docs.
Fixes https://github.com/hashicorp/terraform/issues/35036 and https://github.com/hashicorp/terraform/issues/33613
Backport to 1.3.x
- Users were unable to find the `moved` block documentation. This is the first step toward refactoring the language docs according to content type
=> added reference page for  block

internal/plans/objchange/plan_valid.go, internal/plans/objchange/plan_valid_test.go
Manual backport of #35090
----
When descending into nested structural attributes, don't try to extract attributes from null objects. Unlike with blocks, nested attributes allow the possibility of assigning null values. While these technically aren't allowed to be altered, we need to accept these for compatibility.
=> prevent panics with null objects in nested attrs

internal/plans/deferring/deferred.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
Fixes #
1.8.x
-  stacks: if a provider uses deferred actions while terraform does not support this we will emit a diagnostic
=> stacks: error if provider emits deferred action when it's not supported

website/docs/language/syntax/configuration.mdx
UPGRADE NOTES
- Added information about labels "aws_instance" and "example" in `resource`  type block.
=> Config syntax docs update

internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_test.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/deferred-embedded-stack-and-component-for-each/deferred-embedded-stack-and-component-for-each.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/deferred-embedded-stack-for-each/deferred-embedded-stack-for-each.tfstack.hcl
Fixes #
1.8.x
-  stacks: support unknown for_each values on embedded stacks
=> stacks: support unknown for_each on embedded stacks

.github/dependabot.yml, .github/workflows/build-terraform-cli.yml, .github/workflows/build.yml
This sets up Dependabot to manage version updates for HashiCorp-owned GitHub Actions; all other (third-party) version updates will be handled by HashiCorp's internal TSCCR tooling. TSCCR does not/cannot manage HashiCorp-owned Actions versioning which is why we need to bring in Dependabot to handle this component; see [this memo](https://hermes.hashicorp.services/document/151w0ldYS3Z3arAiSTRuFImV73VabC0rhZJPCv6fzl4Q) (internal HashiCorp link) for details.
This PR also pins all HashiCorp-owned Actions used in this repo to using SHA hashes which is considered a security best-practice these days. This will force Dependabot to continue with this convention, and it is smart enough to update the comment on each of these lines to let us know which is the actual version that's being used.
N/A
N/A
=> build: Set up Dependabot to manage HashiCorp-owned GitHub Actions versioning

.github/workflows/main.yml
Possibly due to recent changes in GitHub Actions, backport-assistant started failing. Hoping that by bumping to latest, it will fix this issue.
=> Bump to latest version of backport-assistant

website/docs/language/resources/provisioners/syntax.mdx
I think line 249 is meaning to reference to the "when" functionality, not the "on_failure" functionality.
Fixes #
1.8.x
-
=> Wrong reference

.github/workflows/build.yml
Update build workflows to use linux runners for the darwin builds.
Native host name resolution works with current Go versions on MacOS without CGO enabled, so can be cross-compiled.
=> remove macos runners from buildworkflow

internal/backend/local/backend_local.go, internal/configs/configload/loader.go, internal/configs/parser.go
If a saved plan is being applied using a Terraform CLI/Core build that allows use of language experiments then that should be allowed when the configuration is being loaded from the snapshot saved in a plan file, in the same way as it would've been handled when preparing to generate that plan file.
The local backend doesn't get told directly whether it should allow experiments, and instead its operation comes with a pre-configured configuration loader that may have the experiment flag set internally.
When we load from snapshot we can't use the operation's own config loader because that loads from the real filesystem, and so we'll copy over the experiments-allowed flag from the operation's config loader to achieve consistency while still loading the configuration from the snapshot in the …
=> backend/local: Allow experiments when loading config from snapshot

internal/plans/deferring/deferred.go, internal/terraform/context_apply.go, internal/terraform/context_apply2_test.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/context_walk.go
This PR adds tests for deferring data sources due to unknown count/for_each values, and makes the necessary behavior changes to get those tests passing. 
For reviewers: here's the main things to validate about this PR.
- Is it logically and practically sound to _always_ set `deferralAllowed = true` in applies? If not, can we think of a safer way to re-process data sources that should be deferred (preferably without significantly changing the semantics of the plan)?
- Does it make sense for `Deferred`'s informational methods to do early negative returns if `deferralAllowed == false`?
- Can we think of any additional ways to directly or indirectly observe the effect of deferring a data source? I had a brief thought about spying on data source read requests in the mock provider, but in …
=> Finish implementation of unknown count/for_each in data sources

internal/backend/local/backend_local_test.go, internal/cloud/retry.go, internal/cloud/retry_test.go, internal/cloud/state.go, internal/cloud/state_test.go, internal/command/output.go, internal/states/remote/state.go, internal/states/remote/state_test.go, internal/states/statemgr/filesystem.go, internal/states/statemgr/filesystem_test.go, internal/states/statemgr/lock.go, internal/states/statemgr/persistent.go, internal/states/statemgr/statemgr_fake.go
Fixes #35105
When outputs are not available while using cloud backend, terraform will now silently retry while logging attempts. If retries are canceled or time out after one minute, an error is displayed (See below for screenshots)
1.9.x
- `terraform output` with cloud block: terraform no longer suggests that data loss could occur when outputs are not available
Before:
After (With TF_LOG, canceled):
After (With TF_LOG, deadline exceeded):
Please note the actual message says "within the deadline" not actually "within the timeout"
=> cloud: `terraform output` should gracefully handle 503 errors

internal/dag/dag.go, internal/terraform/transform_reference.go
The use of `depends_on` in modules can cause large numbers of nodes to become connected to all of the same dependencies. When using `Ancestors` to walk the graph and find all of these dependencies, there can be a lot of redundant ancestors shared between each of the original nodes, causing an exponential increase in processing time and memory use. 
Instead of traversing the graph from each dependency individually, which can frequently end up duplicating results, we can start a walk from all nodes at once, reducing the redundant graph traversals and automatically removing duplicates.
Fixes #35154
v1.8.4
=> Reduce redundant walks when resolving module `depends_on`

internal/dag/dag.go, internal/terraform/transform_reference.go
manual backport of #35157
---
The use of `depends_on` in modules can cause large numbers of nodes to become connected to all of the same dependencies. When using `Ancestors` to walk the graph and find all of these dependencies, there can be a lot of redundant ancestors shared between each of the original nodes, causing an exponential increase in processing time and memory use. 
Instead of traversing the graph from each dependency individually, which can frequently end up duplicating results, we can start a walk from all nodes at once, reducing the redundant graph traversals and automatically removing duplicates.
Fixes #35154
=> v1.8 Backport of #35157

internal/command/init_test.go, internal/command/providers_test.go, internal/command/testdata/init-with-tests-external-providers/main.tf, internal/command/testdata/init-with-tests-external-providers/main.tftest.hcl, internal/command/testdata/init-with-tests-external-providers/setup/main.tf, internal/command/testdata/providers/tests/main.tftest.hcl, internal/configs/config.go, internal/configs/config_test.go, internal/configs/parser_config.go, internal/configs/provider.go, internal/configs/test_file.go, internal/configs/testdata/provider-reqs-with-tests/provider-reqs-root.tftest.hcl, internal/configs/testdata/provider-reqs-with-tests/setup/setup.tf, internal/moduletest/config/config.go
This PR fixes a bug in which non-hashicorp providers defined within test files and referenced within alternate testing modules were wrongly being assumed as hashicorp providers and were failing to install.
We do this by no longer actually looking at test files for provider information. Since test files don't actually use providers directly and just hand them off to the main files, we don't need to consider the provider blocks in test files when calculating provider address and version constraints. This simplifies the provider constraint gathering and solves the underlying bug since the provider types don't need to be assumed within the test file at all now. It does mean that version constraints within provider blocks within test files will no longer be consulted. As such, I've updated the …
=> terraform test: Disallow version constraints within test files

internal/terraform/hook.go, internal/terraform/update_state_hook.go
All state implementations copy the given state when storing it to temporary or permanent storage[^1][^2][^3][^4], either explicitly with DeepCopy, or implicitly by serializing the state. Since `updateStateHook` is called with every resource instance state change, a second call to `DeepCopy` with that hook doubles the overhead of `PostStateUpdate` which may be a significant portion of the running time.
Since all Hook implementations which handle `PostStateUpdate` (which is exactly 1 in non-test code[^5]) only call state methods that eventually copy the state, we can remove the extra copy from the `updateStateHook` itself. The state was already locked for the duration of the `PostStateUpdate` call previously, so no additional delay should result.
For consistency this also updates the …
=> remove extra state.DeepCopy from updateStateHook

internal/builtin/providers/terraform/provider.go, internal/builtin/providers/terraform/provider_test.go, internal/builtin/providers/terraform/resource_data.go, internal/builtin/providers/terraform/resource_data_test.go
This change enables the built-in provider's `terraform_data` managed resource to work with the `moved` configuration block where the `from` address is a `null_resource` managed resource type from the official `hashicorp/null` provider. It produces no plan differences for typical configurations and specifically helps practitioners from re-running provisioners while moving resource types.
In addition to the unit testing, this was manually tested with the following configurations and outputs:
Initial configuration (no `triggers`):
```terraform
terraform {
null = {
source  = "hashicorp/null"
version = "3.2.2"
}
}
}
resource "null_resource" "example" {
provisioner "local-exec" {
command = "echo 'Hello, World!'"
}
}
```
Moved configuration (no `triggers`):
```terraform …
```
=> Support moving from null_resource to terraform_data

CHANGELOG.md
=> Update CHANGELOG for #35163

internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/diagnostics_test.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/output_value.go, internal/stacks/stackruntime/internal/stackeval/provider.go, internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_type.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/child/named_promises_child.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/named_promises.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/named_promises.tfstack.hcl
The `namedPromiseReporter` interface is a helper we use to collect user-friendly names for promises when we need to report a promise self-reference error to the user.
We collect names for promises reactively on error, rather than proactively in the normal course of work, because proactively maintaining a suitable data structure for this cross-cutting concern would be both expensive and complicated.
This compromise therefore allows us to pay the cost of walking over all of the promise-owning objects only in the exceptional case where we need to report a self-reference error, but it does come at the expense of it being possible for us to forget to implement this interface for certain types and thus be unable to name a subset of the affected promises.
(Those who are familiar with the …
=> stackeval: Improve coverage of namedPromiseReporter impls

internal/backend/backendrun/operation.go, internal/backend/local/backend_apply.go, internal/command/apply.go, internal/command/command.go, internal/command/meta.go, internal/command/meta_test.go, website/docs/cli/config/environment-variables.mdx
This PR stems from the initial work done by @alexott (#35116), which fixes #35115. These changes are a simple refactor to delegate handling this env var to `command.Meta`. This allows us to pass the user specified persist interval to `backendrun.Operation` and keep env var handling (with existing vars such as `TF_WORKSPACE`, `TF_INPUT`) centralized within `command.Meta`.
The default interval remains 20 seconds and serves as a global minimum interval. Remote backends such as `cloud` may override the default using the `X-Terraform-Snapshot-Interval` header. If the default interval value is greater than the user-specified value, the default will be used. 
1.9.x
-  Added TF_STATE_PERSIST_INTERVAL environment variable to control persist interval in the remote state backend.
=> Add `TF_STATE_PERSIST_INTERVAL` environment variable. 

internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go
Previously we were partially propagating any marks from the path, but not going all the way so we still ran into trouble when trying to use the string containing the file contents.
Now we'll have `loadTmpl` also return the marks it had to read through to actually parse the template, and then we'll use those (instead of the original path marks) to mark the result. In practice the `pathMarks` and the `tmplMarks` should always match today, but this is intentionally structured to make the data flow clearer -- the marks always travel along with whatever they related to -- so we're less likely to break this accidentally under future maintenance.
This fixes https://github.com/hashicorp/terraform/issues/31119.
=> funcs: Don't panic if templatefile path is sensitive

internal/configs/configschema/filter.go, internal/terraform/context_plan_import_test.go
The legacy SDK introduces an `id` attribute at the root level of resources. This caused invalid config to be generated for the legacy SDK. To avoid this we introduced a filter that removed this attribute from the generated config. This workaround is discussed here: https://github.com/hashicorp/terraform/blob/main/internal/terraform/node_resource_plan_instance.go#L751-L761.
The linked issue highlights we were also removing computed and optional `id` attributes from within nested attributes and blocks. These `id` attributes are not introduced by the SDK, so I've changed the filter functionality to accept a path instead of an attribute name and it now only removes attributes at the root level instead of across the whole schema.
Fixes #35178 
1.8.4
-  `import` blocks: Fix bug where resources …
=> import: only filter id attribute at root level when generating config

internal/configs/configschema/filter.go, internal/terraform/context_plan_import_test.go
=> backport of import: only filter id attribute at root level when generating config

docs/architecture.md
Description
The link goes to a broken package in pkg, this PR resolves the bug by updating the spelling of the link to appropriately go to the correct location within the `architecture.md` . This PR fixes issue #35184.
**Fix proposal**
The link in question that is broken is:
`https://pkg.go.dev/github.com/hashicorp/terraform/internal/erraform#Execute`
this is fixed with
`https://pkg.go.dev/github.com/hashicorp/terraform/internal/terraform#Execute`
**Version**
Fixes documentation in the current version # 1.8.3
```
terraform.exe --version
Terraform v1.8.3
on windows_amd64
```
**Change log entry**
BUG FIX
* broken link within `architecture.md` updated to correct location
=> broken link in architecture.md #35184

internal/configs/experiments.go, internal/configs/named_values.go, internal/configs/testdata/valid-files/variable-validation-condition-crossref.tf, internal/experiments/experiment.go, internal/terraform/context_plan_test.go, internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go, internal/terraform/evaluate_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/graph_builder_eval.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_root_variable_test.go, internal/terraform/node_variable_validation.go, internal/terraform/transform_variable_validation.go, website/docs/language/expressions/custom-conditions.mdx
In https://github.com/hashicorp/terraform/pull/34947 we introduced a language experiment that would permit variable validation rules to refer to other objects declared in the same module as the variable.
Now that experiment is concluded and its behavior is available for all modules.
This closes https://github.com/hashicorp/terraform/issues/25609.
---
This final version deviates slightly from the experiment: we learned from the experimental implementation that we accidentally made the `terraform validate` command able to validate constant-valued input variables in child modules
despite the usual rule that input variables are unknown during validation, because the previous compromise bypassed the main expression evaluator and built its own evaluation context directly.
Even though that …
=> terraform: Stabilize the variable_validation_crossref experiment

website/docs/language/moved.mdx
The two code snippets on the docs page for `moved` were different. This patch makes them the same.
This is purely a docs fix.
- Fix inconsistent `moved` snippets in docs
=> Fix inconsistent `moved` snippets in docs

internal/command/views/json/diagnostic.go, internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/registry/response/module_versions.go, internal/tfdiags/diagnostic.go, website/docs/cli/commands/validate.mdx
[Jira Ticket](https://hashicorp.atlassian.net/browse/TF-12601?atlOrigin=eyJpIjoiZGJlMWU1MzZiMWQ1NGRjNjkzNTQzOTY1MjI4NjA4YTQiLCJwIjoiaiJ9)
1.9.x
- `terraform init`:  Displays warnings when modules marked as deprecated are in use.
Module deprecations warnings are surfaced upon running `terraform init`. This includes both cases of where the module does, or does not, need installation. Furthermore, the warning can be raised for both modules that are directly used in configuration, as well as any external dependencies they depend on.
=> Add Warning for Deprecated Modules in `Init` (Second Revision)

internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/terraform/context_walk.go, internal/terraform/node_resource_abstract_instance_test.go, internal/terraform/node_resource_plan_instance.go
Currently, the deferred actions data structure maintains an internal `ResourceGraph` that it uses to track dependencies of resources. It uses this to work out if a resource should be deferred because it depends on a resource that has been deferred. This led to significant performance degradation within Terraform as we are now creating, holding, and searching two (potentially) large graphs within Terraform.
This PR deletes the internal resource graph from the deferred actions data structure. Instead, we now expect the callers to pass in addresses to their dependencies to be looked at directly instead of relying on the deferred actions data structure to handle this look up internally.
Terraform already computes the dependencies and provides them to where we need them in the …
=> deferred actions: remove resource graph

internal/configs/source_bundle_parser.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/path_values/module/child/main.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/path_values/module/main.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/path_values/path_values.tfstack.hcl
This PR updates the stacks `source_bundle_parser` so the `SourceDir` field of the configuration is still set to a local path instead of the source bundle path. AFAICT the `SourceDir` field is only used to compute the `path.root` and `path.module` variables, so this PR should restore the functionality of those attributes within stacks.
With this PR `path.root` resolves to the directory of the root Terraform module of the current component, and `path.module` resolves to the directory of the current module. `path.cwd` is behaving normally.
I wondered if this is the right behaviour for `path.root` in stacks. Possibly it should resolve to the current component directory instead of the root module of that component? Maybe we need to look into how this is being used more before making that …
=> stacks: convert sourcebundle source into directory for config SourceDir field

internal/command/jsonfunction/function.go, internal/experiments/experiment.go, internal/lang/funcs/descriptions.go, internal/lang/functions.go, internal/lang/functions_test.go, website/data/language-nav-data.json, website/docs/language/functions/templatefile.mdx, website/docs/language/functions/templatestring.mdx
A `templatestring` function was introduced as a language experiment in https://github.com/hashicorp/terraform/pull/34968. Based on feedback the function seems to do the job, so this PR concludes the experiment by making the function available in all configurations.
Closes https://github.com/hashicorp/terraform/issues/30616, closes https://github.com/hashicorp/terraform/issues/26838
=> lang: stabilise templatestring func experiment

website/data/intro-nav-data.json, website/docs/intro/phases/adopt.mdx, website/docs/intro/phases/collaborate.mdx, website/docs/intro/phases/govern.mdx, website/docs/intro/phases/index.mdx, website/docs/intro/phases/scale.mdx, website/docs/language/style.mdx
Currently the "[Phases of Terraform Adoption](https://developer.hashicorp.com/well-architected-framework/operational-excellence/operational-excellence-terraform-maturity)" content lives in the tutorials as part of the Well-Architected Framework. We are currently in the process of migrating this content to the respective documentation.
=> [Docs] Migrate "Phases of Terraform Adoption" from tutorials to docs

website/docs/cli/cloud/settings.mdx
The docs for HCP Terraform settings suggest that the `project` argument is mutually exclusive with both "tags" and "name" arguments.
1.9.x
- Fixed documentation bug that suggested the cloud block `project` argument is mutually exclusive with both "tags" and "name" arguments.
=> Fix cloud block documentation bug

internal/terraform/context_plan_import_test.go, internal/terraform/node_resource_plan_instance.go
A full destroy requires Terraform to refresh everything beforehand, but if an instance is missing from the state and has an `import` block, Terraform was attempting to re-import that resource before destroy. The most common reason this could happen would be when resuming a partially completed destroy, where some of the state has already been deleted. In that case the import will fail with an error because the resource no longer exists, and end up blocking the rest of the operation.
Fixes #35151
=> Don't attempt to import during a destroy operation

internal/terraform/context_plan_import_test.go, internal/terraform/node_resource_plan_instance.go
Manual backport of #35262 
---
Don't attempt to import during a destroy operation
A full destroy requires Terraform to refresh everything beforehand, but if an instance is missing from the state and has an `import` block, Terraform was attempting to re-import that resource before destroy. The most common reason this could happen would be when resuming a partially completed destroy, where some of the state has already been deleted. In that case the import will fail with an error because the resource no longer exists, and end up blocking the rest of the operation.
=> backport 35262

internal/command/jsonformat/differ/block.go, internal/command/jsonformat/differ/differ_test.go
Manual backport of #35271
---
An unknown block can happen when using an unknown for_each value in a dynamic block assignment. The plan renderer was missing a check for entirely unknown blocks, causing them to be omitted from the human readable output.
=> Backport #35271

internal/lang/funcs/string.go, internal/lang/funcs/string_test.go, website/docs/language/functions/templatestring.mdx
The `templatestring` function has some special constraints on its first argument that are included to add some intentional friction for those who are new to Terraform, want to do some simple template rendering, but have only found the `templatestring` function so far.
We know from previous experience with the `hashicorp/template` provider that this sort of functionality tends to attract those who haven't yet learned that the Terraform language has built-in support for string templates (without calling any function), who would then get confused by the need for an extra level of escaping to render a template string only indirectly through this function and waste time trying to get that to work, rather than looking for the better alternatives.
However, this rule is not intended to be onerous …
=> lang/funcs: Allow some more expression types in templatestring

internal/lang/funcs/string.go, internal/lang/funcs/string_test.go, website/docs/language/functions/templatestring.mdx
This is a backport of https://github.com/hashicorp/terraform/pull/35285 to the `v1.9` branch, created manually since the backport automation is currently broken.
=> lang/funcs: Allow some more expression types in templatestring (v1.9 Backport)

internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_test.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input-and-output/deferred-component-for-each/deferred-component-for-each.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input-and-output/deferred-component-references/deferred-component-references.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input-and-output/single-input-and-output.tf
This PR makes the stacks runtime explicitly return unknown values when referencing another component that has an unknown `for_each`.
We mark components with unknown as having the wildcard instance: `component.name[*]`. This introduced the bug that when a known variable attempts to reference the unknown component, we get an "reference doesn't exist" error. This is not the correct behaviour with deferred components, instead we should get an unknown value back.
=> stacks: return dynamic types when referencing partial components

internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/provider.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_test.go, internal/stacks/stackruntime/internal/stackeval/stubs/configured.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/deferred-provider-for-each/deferred-provider-for-each.tfstack.hcl
This PR adds support for unknown providers to the stacks runtime.
The provider instance functionality now returns an instanced addressed by the wildcard key to represent an unknown but otherwise valid provider configuration. We still return nil to represent an invalid provider configuration.
The components will now load a unknown provider stub when they encounter the requirement for an unknown provider. The unknown provider stub wraps an unconfigured provider so we can still function completely for offline functionality. For online functionality the unknown provider either errors if deferred responses are not supported, or returns a deferred response if deferrals are supported.
There's a small refactor where I've pushed the other stub provider into a separate package to live alongside the …
=> stacks: add support for unknown for_each expressions in providers

internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/component_test.go, internal/stacks/stackruntime/internal/stackeval/for_each.go, internal/stacks/stackruntime/internal/stackeval/for_each_test.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/provider.go, internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go, internal/stacks/stackruntime/internal/stackeval/provider_test.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_test.go, internal/stacks/stackruntime/internal/stackeval/testing_test.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
This PR refactors the handling of unknown components, providers, and stack calls from the stacks runtime.
Previously, we were just including the unknown instance as part of the set of returned instances with the Wildcard key eg. `["*"]`. This meant the rest of the runtime just handled this by looking up the unknown instance whenever matching variables via a HCL context. However, this was broken in the case of referencing a known value into an unknown instance (for example referencing `component.name["known"]` when `component.name` has an unknown set of instances should return an unknown value but would instead return "instance not found"), and also was only working at all because we haven't yet fixed the wildcard key to render properly (eg. `[*]` and not `["*"]`.
With this PR we turn the …
=> stacks: remove wildcard key from computed instances

internal/configs/named_values.go, internal/configs/testdata/invalid-files/variable-validation-condition-noself.tf
While variable validation rules can now include other references, they also still need to reference the variable itself. If the containing variable wasn't referenced, then the resulting `Invalid value for variable` error would not make sense.
Having no self-references will also cause a panic when trying to reinsert the variable name into the evaluation context, because the context variables map could be nil. A check for a nil map does not need to be added however, because ensuring that a self-reference exists means there will always be at least 1 variable in scope.
This will currently panic:
```
locals {
else = "?"
}
variable "validated" {
type    = string
default = ""
validation {
condition     = "something" == local.else
error_message = "Error message"
}
}
```
But should return a …
=> Variable validation rules must still reference the containing variable.

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/transform_destroy_cbd.go
The ordering for `CreateBeforeDestroy` is determined by the value stored in the resource instance state. If the destroy plan was created with `-refresh=false`, _and_ the configuration changed the value of `create_before_destroy`, then there was no chance for the state to be updated, and we now have a mismatch between the configuration and the state. This disagreement causes the plan to record the resource replacement as destroy-then-create, but later order the apply actions as create-before-destroy, and since the create is expected to be last, the destroy operation ends up showing a noop and is skipped.
The fix is relatively small, just ensure that we re-write the state when there is no refresh but there was a change in `CreateBeforeDestroy`.
The replacement ordering optimally should be …
=> store CreateBeforeDestroy even when not refreshing

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/transform_destroy_cbd.go
Manual backport of #35261
---
The ordering for `CreateBeforeDestroy` is determined by the value stored in the resource instance state. If the destroy plan was created with `-refresh=false`, _and_ the configuration changed the value of `create_before_destroy`, then there was no chance for the state to be updated, and we now have a mismatch between the configuration and the state. This disagreement causes the plan to record the resource replacement as destroy-then-create, but later order the apply actions as create-before-destroy, and since the create is expected to be last, the destroy operation ends up showing a noop and is skipped.
The fix is relatively small, just ensure that we re-write the state when there is no refresh but there was a change in `CreateBeforeDestroy`.
The replacement …
=> Backport of #35261

internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/terraform/context_apply2_test.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/evaluate.go, internal/terraform/evaluate_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/node_output.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_apply_deferred.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_partialexp.go, internal/terraform/transform_deferred.go, internal/terraform/transform_destroy_edge.go
This PR has two authors and two goals — @liamcervante was already working on wiring deferred values into outputs, and I needed to build on some of what he'd already done in order to finish implementing deferral for data sources. 
Previously, we weren't copying any information about deferred data sources into the plan; the theory was that data sources are handled during plan, and any resource that refers to them will already be listed as deferred, so we can just reconstruct things during the apply as needed. 
This turned out to be not quite coherent, mostly because data sources CAN in fact produce planned changes that get processed during an apply! To observe this, just make a data source reference a computed attribute from a resource that hasn't been applied yet; the data source will plan …
=> Copy deferred data sources into the plan, and use deferred values in references/outputs

website/docs/language/providers/requirements.mdx
Fixes #35317 
Remove callout to deprecated tutorial in provider requirements doc
=> Remove link to deprecated tutorial

website/docs/language/providers/requirements.mdx
Backport of #35326 to 1.9
Manual backport as an error was encountered with the backport action.
=> 1.9 Backport - Remove link to deprecated tutorial (#35326)

internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/for_each.go, internal/stacks/stackruntime/internal/stackeval/for_each_test.go, internal/stacks/stackruntime/internal/stackeval/planning.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/provider.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/plan.go, internal/stacks/stackruntime/plan_test.go
This PR turns on deferred actions for all Stacks operations. Currently, it was only enabled within the specific tests that required it. Now that implementation is (nearly) complete, we'll enable this for everything. This means that in the next release of Terraform Core, stacks will start to see deferred actions in everything.
=> deferred actions: always enable deferred actions in stacks

internal/addrs/partial_expanded.go, internal/addrs/partial_expanded_test.go, internal/states/sync.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/eval_for_each.go, internal/terraform/eval_import.go, internal/terraform/node_resource_partial_plan.go, internal/terraform/node_resource_plan.go
This PR adds support for unknown `for_each` values within `import` blocks when deferred actions is enabled.
This can result in the `to` argument being essentially unknown. To combat this we parse the `to` argument as a partial resource, and defer all resources that it **might** refer to once the unknown values are resolved.
Any resources that are already in state and might be targeted by a partial `to` address are not deferred. The behaviour of the import block when targeting a resource already in state is simply a no-op. So, when the unknown `to` is eventually resolved and would point to a resource already in state it doesn't matter.
This builds on the work in the previous PR allowing unknown `id` values: #35300. The way we mark a resource as being deferred due to an import block is to …
=> deferred actions: allow unknown foreach attributes within import blocks

internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_plan_instance.go
This PR fixes config generation when importing a resource with an unknown ID.
Previously, we would return an error and then crash when generating config for a resource with an unknown import ID. This PR updates the planning process so it exits early with a dummy value instead of attempting to validate configuration that doesn't exist.
The config will be properly generated in a follow up plan when the import ID is known.
=> deferred actions: fix config generation when importing an unknown resource

internal/terraform/context_import_test.go, internal/terraform/transform_config.go
When grouping imports by module for validation, imports with no associated module were left out and would silently fail. Change the config transformer to check all import targets together to make sure they are all valid within a configuration.
Fixes #35303
=> Missing import target in module should error

internal/addrs/move_endpoint_module_test.go, internal/addrs/parse_target.go, internal/addrs/parse_target_test.go
This is a manual backport of #35333.
=> Manual backport of Add support for partial addresses and targets that start with 'resource.'

internal/rpcapi/stacks_test.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/plan.go, internal/stacks/stackruntime/plan_test.go
This PR updates the logic for deciding whether an overall stack is "applyable" so that it takes into account the applyable status of all component instances.
Previously, a stack was "applyable" as long as it had no error diagnostics. Now, a stack is applyable if it (a) has no error diagnostics and (b) at least one component is "applyable".
Finally, stack outputs are not currently stored as part of the state of a stack anywhere. This means that there is no need for the applyable status of a stack to depend on outputs. I've updated a TODO within the code that is calling for outputs to be added to state so that it also calls out that if/when this happens the applyable status of a stack should be updated to reflect that status of any outputs.
=> stacks: applyable status should be dependent on applyable components

website/docs/cli/import/usage.mdx, website/docs/internals/credentials-helpers.mdx, website/docs/intro/core-workflow.mdx, website/docs/language/expressions/conditionals.mdx, website/docs/language/expressions/for.mdx, website/docs/language/expressions/splat.mdx, website/docs/language/expressions/type-constraints.mdx, website/docs/language/functions/can.mdx, website/docs/language/functions/list.mdx, website/docs/language/functions/lookup.mdx, website/docs/language/functions/map.mdx, website/docs/language/functions/sensitive.mdx, website/docs/language/functions/templatefile.mdx, website/docs/language/import/generating-configuration.mdx, website/docs/language/resources/syntax.mdx, website/docs/language/settings/backends/oss.mdx, website/docs/language/settings/backends/remote.mdx, website/docs/language/style.mdx, website/docs/language/tests/index.mdx, website/docs/language/values/locals.mdx
I noticed this originally when reading https://developer.hashicorp.com/terraform/language/v1.9.x/resources/syntax#removing-resources and decided to look up places where we were missing the HCL language ID in the snippets that contain HCL using an imperfect regex `\n\n```\n`.
=> website: Enable highlighting for HCL snippets

internal/command/e2etest/providers_mirror_test.go, internal/command/e2etest/testdata/terraform-providers-mirror-with-broken-lock-file/.terraform.lock.hcl, internal/command/e2etest/testdata/terraform-providers-mirror-with-broken-lock-file/terraform-providers-mirror.tf, internal/command/providers_mirror.go, website/docs/cli/commands/providers/mirror.mdx
The lock file diagnostic were not being checked in the mirror command, so an incomplete or broken lock file might cause the cli to crash.
Fixes #35318
=> Check lock file diagnostics in `mirror` command

internal/stacks/stackruntime/apply.go
This seems to have got lost while resolving some conflicts in https://github.com/hashicorp/terraform/pull/35346.
Without this, apply-time input variable values just get ignored entirely and if any are required the plan is not applyable at all. Now we'll pass through what the caller provided so stackeval can validate and use it properly.
=> stackruntime: Pass the apply-time variable values to stackeval

internal/stacks/stackruntime/internal/stackeval/local_value.go, internal/stacks/stackruntime/internal/stackeval/local_value_config.go, internal/stacks/stackruntime/internal/stackeval/local_value_test.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/local_value/basics/child/local-value-basics-child.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/local_value/basics/local-value-basics.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/local_value/custom_provider/child/child.tf, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/local_value/custom_provider/custom-provider-local.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/terraform-sources.json, internal/stacks/stackruntime/internal/stackeval/walk_static.go
Local Values are made available in the .tfstack.hcl language. The existing codebase already had support for local values, it was incomplete was missing the machinery required to reference local values within the `tfstacks.hcl` files. 
1.8.x
=> stackruntime: Support referencing Local Values within the `tfstacks.hcl` language

internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract_instance.go
This PR fixes a panic that occurs during a plan when a sensitive value update forces a resource to be replaced. We refactored the logic for gathering the required replace paths into a separate function in https://github.com/hashicorp/terraform/commit/ddabb6a2eebcdb0141a803bcd99b68f8b52cf86e. This refactor missed that previously it was the `unmarkedPriorVal` that was being used for comparison rather than the basic `priorVal`. When the values are then compared for equality, one of the values was marked which meant the overall returned boolean value was also marked, and then the panic occurs at line 2857.
This PR simply passes in the unmarked values for both the planned and prior values, instead of recomputing the unmarked values internally. This should be acceptable as nothing about the …
=> fix panic when updating a sensitive field that requires replacement

internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract_instance.go
This is a backport of #35372 to the 1.9 branch. It fixes a panic introduced in the 1.9 series, caught during the RCs.
=> Backport: fix panic when updating a sensitive field that requires replacement

internal/command/init.go
1.8.x
* Fixed and improved error message when `-plugin-dir` is used with `terraform init` and the values can't be saved into the workspace directory.
* The error message would say `-plugin-path` when the option is actually `-plugin-dir`.
* Improved said error message a bit to clarify where that value was going to be saved to.
=> Fix and clarify error message when -plugin-dir can't be saved to working directory

website/docs/language/upgrade-guides/index.mdx
The s3 backend block schema has changed, so it appears to need a re-init. This is a website-only change.
Fixes #34974
1.8.x
This PR is targeted directly at the v1.8 branch, because the affected upgrade guide page does not exist in future branches or in main.
=> 1.8 upgrade guide: clarify necessary upgrade actions for S3 backend

website/docs/language/expressions/operators.mdx
The example given to illustrate the behaviour of logical operators is incorrect. `var.foo || var.foo.bar` would also produce an error if the operator  was short-circuiting. The example should be with `var.foo && var.foo.bar`, that produces an error in terraform, but wouldn't if `&&` was short-circuiting.
=> Fix incorrect example in the docs

website/docs/language/functions/textencodebase64.mdx
`substr` → `textencodebase64`
https://developer.hashicorp.com/terraform/language/functions/textencodebase64
=> docs: correct function name in `textencodebase64` documentation

internal/collections/map.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go
This PR updates the stacks runtime to include counts for the state management actions (import, forget, move) in the apply-time summaries.
Essentially, these actions don't actually map to real actions during an apply. They're actually already "applied" during the plan, as the state is just modified to reflect the state management before the graph starts. This means they don't get emitted as successful changes during the apply, and as such aren't included in the counts.
After this PR, we look at the set of "affected resources" and validate that each of them is either included in the applied list or counted if they were imported, moved, or forgotten.
=> stacks: include move, forget, import counts in apply summaries

internal/moduletest/eval_context.go
This PR fixes the `terraform test` cmd logging additional errorenous error message while referencing invalid attributes. While evaluating a check, a HCL evaluation context is created for the test command. Some validation is done during the creation of the context, failing which an empty context is returned with the expected diagnostic. This PR stops the evaluation of a check as soon as a diagnostic is returned with an error.
Fixes #35265 
1.9.1
-  The `terraform test` command is expected to not show confusing message when context does not contain variables due to validation error
- The expected behaviour is shown for the case mentioned in the issue description:
=> fix: skip check evaluation when context is not prepared successfully

internal/moduletest/eval_context.go
Reverts hashicorp/terraform#35408
=> Revert "fix: skip check evaluation when context is not prepared successfully"

go.mod, go.sum, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.sum, internal/legacy/go.sum
=> deps: Bump go-getter to v1.7.5

internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go, internal/terraform/node_resource_plan.go, internal/terraform/validate_selfref.go
This PR validates import `id` attributes to ensure they do not reference to be imported resource.
Fixes #35416 
1.9.2
-  `import` blocks: Fix crash that occurs when incorrectly referencing the `to` resource from the `id` attribute.
=> import: fix crash when referencing the imported resource from the 'id' field

internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go, internal/terraform/node_resource_plan.go, internal/terraform/validate_selfref.go
=> backport of import: fix crash when referencing the imported resource from the 'id' field

internal/rpcapi/stacks.go, internal/rpcapi/stacks_test.go, internal/stacks/stackruntime/apply.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/applying.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/diagnostics_test.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/planning.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/provider_config_test.go, internal/stacks/stackruntime/internal/stackeval/validating.go, internal/stacks/stackruntime/plan.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/validate.go, internal/stacks/stackruntime/validate_test.go
If the providers are not in the lockfile fetching the schema fails.
This leads to follow up diagnostics that send an unclear message.
Now we validate the lockfile and if something is missing we skip further validation that relies on
the provider schema being present.
[Jira](https://hashicorp.atlassian.net/browse/TF-17949)
1.10.x
-  stacks: improve validation of lockfiles
=> stacks: validate lockfile containing all providers

internal/configs/config.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/testdata/mainbundle/test/legacy-module/README.md, internal/stacks/stackruntime/testdata/mainbundle/test/legacy-module/main.tf, internal/stacks/stackruntime/testdata/mainbundle/test/legacy-module/with-hashicorp-provider/with-hashicorp-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/legacy-module/with-non-hashicorp-provider/with-non-hashicorp-provider.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
This PR updates the stacks provider-checking logic to automatically deduce if one of the provider types has been implied. If so, we can probably guess the user is trying to use a non-hashicorp provider and Terraform has assumed the wrong type. We can then provide a more helpful error message, this will tell the user that they should add the non-hashicorp provider to a `required_providers` block to set the right type.
=> stacks: provide more helpful diagnostics when providers types are mismatched

internal/stacks/stackruntime/internal/stackeval/component_instance.go
This PR just extends the error message for this error case. I'm unable to replicate this particular issue so I can't really investigate the underlying cause. I'm adding the internal error so that if it happens again we might have more information from the outset.
=> stacks: extend diagnostic message to capture error from unscheduled component

internal/terraform/context_plan2_test.go, internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go, internal/terraform/node_resource_plan.go, internal/terraform/validate_selfref.go, internal/terraform/validate_selfref_test.go
This PR fixes a crash that occurs when self-referencing direct instances from the count and for_each meta arguments. The same behaviour was also happening within the `import` blocks. These have been updated to share the same code path, and more extensive test cases have been added to cover the missing edge cases.
This had been partially fixed previously in #35407, but some edge-cases had been missed allowing certain conditions (direct instance references) to still trigger the panic.
Fixes #35427
1.9.2
-  Fix panic when self-referencing direct instances from `count` and `for_each` meta arguments.
=> Fix missing validation for count and for-each meta-arguments

internal/command/init.go, internal/command/init_test.go
On a default provider install failure we can always suggest running `terraform providers` to help in cases where it's not apparent to the user how to proceed. This would most commonly be encountered by conflicting provider requirements, but if we find there are other common situations we may want to generate a more precise error type for better diagnostics.
Closes #35435
=> add suggestion to run `terraform providers` on provider installation failure

internal/stacks/stackplan/planned_change.go, internal/stacks/stackplan/planned_change_test.go
This PR updates the stacks runtime so that it includes moved and imported metadata in the planned change descriptions.
The moved and imported metadata were already included within the event stream which means this information was already published through to the Atlas UI. This just closes the last part of this and would allow other consumers (such as the tfstacks CLI) to eventually render this information as well.
=> stacks: include moved and imported metadata in change descriptions

internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go
In cases where the `condition` is known but the `error_message` is not, we were previously returning the generic error about the error message not being evaluable.
This is an interim change to give better feedback for the unfortunate situation described in https://github.com/hashicorp/terraform/issues/35397, so we can give authors better guidance in the meantime while we're designing a better solution.
In the long run we'll want to do something better here to minimize the chances of this situation arising -- reporting an error that we don't know how to describe is a poor user experience. But for now this at least acknowledges that an unknown value is the problem, and annotates the error message with the "caused by unknown" marking so that the UI will specify which of the contributing …
=> terraform: Error message for unknown error_message in variable validation

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/deferred/deferred.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/deferred/deferred/deferred.tf, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/deferred/ok/ok.tf
The apply also needs to know how many resources have been deferred so that orchestration rules might react to it.
=> stacks: track resource deferrals in apply

internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go
This is a backport of https://github.com/hashicorp/terraform/pull/35400 to the v1.9 branch.
I had intended to use the normal backport process but I forgot to add the label before I merged, so here we are. :man_shrugging: 
This was just a direct cherry-pick with no conflicts.
=> terraform: Error message for unknown error_message in variable validation [v1.9 backport]

internal/backend/remote-state/gcs/backend_internal_test.go, internal/backend/remote-state/gcs/backend_test.go
Historically the `gcs` backend hasn't been touched much. In the past I've added a few features but largely left the existing codebase as it was previously. Recently the `gcs` backend was refactored in https://github.com/hashicorp/terraform/pull/34989 to avoid using the old SDK.
As part of reviewing that PR I started adding a few acceptance tests in this PR. **There's a lot more work to be done** but I want to avoid this PR getting too big.
This PR:
- Separates acceptance tests and 'internal' tests into separate _test.go files
- Implements some pre-check functions to test for TF_ACC being set and credentials being supplied by the test environment
- When this info is missing the tests are skipped, to enable checks passing in this repo. This repo has no automated testing of the `gcs` backend …
=> Add acceptance and internal tests for `gcs` backend, add some test helper functions

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/component_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/failed-component/failed-component.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/failed-component-to-provider/failed-component-to-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/failed-parent/failed-parent.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go
This PR updates the stack runtime to insert unknown values for outputs that are missing after a components apply operation. A missing component output generally implies the operation failed, and the output was never written to state.
The success status of a component is tracked elsewhere, so while this does insert unknown values where they shouldn't be (ie. during an apply operation at all), this should be okay as anything that depends on the failed component will not execute anyway.
Separately to actual execution, these missing values were causing problems as we validate the component outputs separately (in the `CheckApply` functions) and these missing outputs were causing "missing output" errors to be thrown leading to confusion about the real source of an error.
This is an alternate …
=> stacks: insert unknown values for missing outputs during applies

internal/terraform/context_apply2_test.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_plan_orphan.go
Fixes #35436 
When destroying a resource instance, we always refresh first, to give the provider a chance to tell us that the instance no longer exists. This prevents issues with providers that cannot handle delete requests for already deleted resources.
When forgetting, however, this is unnecessary, since no further requests to the provider will be made for this instance. Indeed, since a main use case for the forget functionality is removing instances from state for which there is no longer a configurable provider, attempting to refresh is both unnecessary and often problematic.
=> core: do not refresh when forgetting instances

internal/rpcapi/stacks.go, internal/rpcapi/stacks_test.go
This PR fixes a flaky test in the stacks package. We can now set the plan timestamp override on the stacks server itself during tests, ensuring that we have a consistent set time for the whole test.
=> stacks: fix flaky TestStacksPlanStackChanges test

internal/configs/named_values.go, internal/configs/named_values_test.go
Previously this error message was including only the main error message and ignoring any context about what part of a potential nested data structure it arose from.
Now we'll use our usual path formatting utility to introduce additional context whenever a problem arises with a nested value.
This fixes #27773 by making its error message now include the problematic attribute path:
```
╷
│ Error: Invalid default value for variable
│ 
│   on variable-default-validation-context.tf line 6, in variable "foo":
│    6:   default = {
│    7:     "memap" = {
│    8:        abc = "i am a string"
│    9:        iamme = "one two three"
│   10:     }
│   11:   }
│ 
│ This default value is not compatible with the variable's type constraint:
│ ["memap"].abc: a bool is required.
╵
```
=> configs: Include context when variable default has nested problem

internal/configs/configschema/copy.go, internal/configs/configschema/filter.go, internal/configs/configschema/filter_test.go
This PR updates the schema filtering functions so they don't side-effect edit the original schema with the changes made while filtering. This was causing strange behaviour when generating config, as the value that had already been imported to state started disagreeing with the schema after the config had been generated.
Fixes #35478 
1.9.3
-  config generation: fix validation error when using nested computed and/or deprecated attributes
=> config generation: stop editing the original schema when filtering

internal/configs/configschema/copy.go, internal/configs/configschema/filter.go, internal/configs/configschema/filter_test.go
=> Manual backport of config generation: stop editing the original schema when filtering

internal/promising/errors.go, internal/promising/public_test.go, internal/promising/task.go, internal/stacks/stackruntime/internal/stackeval/diagnostics.go, internal/stacks/stackruntime/internal/stackeval/diagnostics_test.go
We were previously just treating `promising.ErrUnresolved` as a singleton that doesn't carry any context along with it. This particular error always represents a bug in the stack runtime rather than a problem with the input, because resolving all of the promises is a key part of the contract for package promising, but it's still helpful to know a little more about what exactly has failed when debugging it.
Therefore `promising.ErrUnresolved` is now a type rather than a value, and its carries with it a set of promise ids that were left unresolved. `stackeval` then recognizes this error type and uses its own records of what each promise was supposed to produce to hopefully return a useful error message that would narrow down what part of the system is buggy.
Since this message always …
=> stacks+promising: Better error messages for promise resolution failure

internal/rpcapi/stacks_test.go, internal/stacks/stackruntime/plan.go, internal/stacks/stackruntime/plan_test.go
This PR updates stack plans to be applyable even if they will make no changes to the infrastructure. This is because applying a stack plan with no changes will still perform any necessary state migrations, and allows users to upgrade state without making infrastructure changes.
We should revisit this in more detail to decide exactly what it means for something to `errored` and/or `applyable`. See the internal ticket for more detail: https://hashicorp.atlassian.net/browse/TF-18859
=> stack: stacks should be applyable even if no components are

internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/aliased-provider/aliased-provider.tf, internal/stacks/stackruntime/testdata/mainbundle/test/aliased-provider/aliased-provider.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
This PR adds new validation and plan tests that test an old error case where we weren't properly assigning the provider type when an alias provider was in use. We actually fixed this by accident while fixing something else in https://github.com/hashicorp/terraform/pull/35422. I'm coming back and adding these test cases in to prevent any regressions in the future.
Internal ticket: https://hashicorp.atlassian.net/browse/TF-18463
=> stacks: add additional provider validation tests

internal/plans/deferring/deferred.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
This PR fixes two crashes that would occur when a data source that does not get deferred depends on a resource (or data source) that is being deferred.
Essentially, we have the fact that the `planDataSource` function that only returns a change if it is either (a) deferring the data source to a future plan or (b) reloading it during the apply. In addition, during refresh only plans the function does not return a change even if the above conditions are true. 
This leads to the two crashes. One is where the neither of the two conditions are true, and the function returns a `nil` change. The second is during a refresh plan, when Terraform decides not to even attempts to refresh the data source it would always return a `nil` change.
In both cases, if the data source itself was not being …
=> deferred resources: fix crash when a non-deferred data source depends on deferred resources

website/docs/cli/commands/import.mdx
I'd  been using the `terraform import` CLI tool for far too long because I was unaware of this existing in the language for a long time. I believe lot of people aren't aware of this either.
I'm not putting  a ton of effort into the text till a reviewer has a chance to provide feedback for this in the off-chance there's already some other place in documentation I wasn't aware of. However a small pointer to additional resource may be helpful for search engines and LLMs to answer future queries :) 
Not a code change, so I don't think a lot of the titles apply
=> Add a note in import cli command that there's an import block in the language

internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/node_variable_validation.go
manual backport of #35511
---
Arbitrary expressions cannot be evaluated during destroy, because the "state" of the state is unknown. Missing resources or invalid data will cause evaluations to fail, preventing any progress in the destroy operations.
The way we handle this with providers and temporary values that need to be re-evaluated during destroy, is that they are selectively pruned out of the graph during the destroy process. Now that variable validations can reference other values in the configuration (#34947), which added another evaluation node type to the graph, that new node type must also act like it's a temporary value akin to variables, locals, and outputs.
This has some implications for validations in general, since they were always run during a destroy (#34101). Now that …
=> Backport #35511

internal/plans/objchange/compatible.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral-default/ephemeral-default.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral/ephemeral.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/for-each-component/for-each-component.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go
This PR ensures that any automatic conversions that are applied to root input values are applied *before* we compare the plan and apply input values for consistency. This fixes a bug that occurred when using collections as inputs. The agent would parse these as objects or tuples, and Terraform would then automatically convert them to the correct types. This behaviour is totally valid, and matches the behaviour of Terraform proper. We were then checking the plan values against the apply values at apply time before the apply operation had been given the chance to apply the automatic conversion and naturally the types were different and so it was failing.
I've pushed the evaluation of plan and apply time input variables into the `input_variable.go` file, after the automatic conversion. In …
=> stacks: apply automatic type conversion before comparing inputs

internal/command/init_test.go, internal/command/testdata/init-with-duplicates/primary.tf, internal/command/testdata/init-with-duplicates/secondary.tf, internal/command/testdata/init-with-overrides-and-duplicates/primary.tf, internal/command/testdata/init-with-overrides-and-duplicates/secondary.tf, internal/command/testdata/init-with-overrides-and-duplicates/secondary_override.tf, internal/configs/parser_config.go
This PR prevents a crash that was occurring whenever Terraform discovers duplicate `required_providers` blocks in which at least one was not syntactically correct.
Fixes #35532 
1.9.4
-  `init`: Stop crashing when discovering invalid syntax in a duplicate `required_providers` block.
=> init: fix invalid + duplicate required provider blocks crashing

internal/checks/state_report.go, internal/terraform/graph.go, internal/terraform/node_module_variable.go
Relates to #35477 
I haven't been able to replicate or work out exactly what's happening in the crashes here. I'm adding some logging around the variable validations here to see if this might reveal more about what's happening after the next release.
=> trace: add more logging around variable validations

internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_variable_validation.go, internal/terraform/transform_variable_validation.go
When evaluating variable validation, we may have valid `error_message` values which are unknown due to all other referenced input variables being unknown during the validate walk. In the rare case where the variable validation is known but the `error_message` is not, we need to be able to proceed to the plan phase in order to check the validation more thoroughly.
Fixes #35397
1.10
- Allow unknown `error_message` values to pass the core validate step, so variable validation can be completed later during plan.
=> Allow unknown `error_message` values during validate walk

.github/workflows/build-terraform-cli.yml
The RelEng team has been working on adding some validation to ensure that the work we did in #34977 to include a copy of the license file in all distributed packages is done correctly. While it's working correctly in the build .zips and Docker images, it wasn't being copied over into Linux debs/rpms because of what I'm guessing was a copypasta on my end. Thankfully, this is easily fixed.
I assume this doesn't have to be called out in the changelog, but if anyone disagrees, let me know.
=> build: Ensure license is actually copied into linux packages

internal/terraform/context_apply_deferred_test.go, internal/terraform/context_plan_import_test.go, internal/terraform/context_validate.go, internal/terraform/eval_for_each.go, internal/terraform/eval_import.go, internal/terraform/graph_builder_plan.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_validate.go, internal/terraform/transform_attach_config_resource.go, internal/terraform/transform_config.go
When import blocks were first introduced they had to be fully static, which allowed them to be validated during the configuration loading process. This early static validation was carried forward as more features were introduced, but that led to some validation in awkward places like the graph builder, and some validation which could not be done like validating the `to` expression.
Moving the import validation into the validate graph allows us to more fully validate the block contents, in the same way as normal resource configuration and mostly unifies where validation happens. We still have a couple outliers due to the possibility of config generation, which requires some checks in the config transformer for entirely missing modules when the resource has no config, and the plan node to …
=> core: move import validation into the validate graph

internal/command/jsonformat/diff.go, internal/command/jsonformat/plan.go, internal/command/jsonformat/plan_test.go, internal/command/jsonplan/plan.go
Adds support to the plan renderer for rendering deferred actions.
[Jira: TF-19059](https://hashicorp.atlassian.net/browse/TF-19059)
Example output from a completely deferred component:
Example output from a partially deferred component
1.10.x
-  plan: can render deferred actions
=> jsonformat: render deferred actions

.github/workflows/main.yml
A number of recent changes in the backport assistant and in our GitHub org settings make it now possible to use the ephemeral token instead of the bot PAT, which makes it considerably safer and reduces maintenance effort.
This PR aims to re-enable our backport workflows.
=> github: Use ephemeral token for backport-assistant

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/plan_test.go
This fixes flaky tests by making sure the diagnostics are in a consistent order before we compare them. In all cases here, the order of the diags doesn't matter to us, just that the right ones were included.
=> stacks: sort diags in test before comparison

internal/configs/depends_on.go, internal/configs/module_call.go, internal/configs/named_values.go, internal/configs/resource.go, internal/configs/test_file.go, internal/stacks/stackconfig/component.go, internal/stacks/stackconfig/embedded_stack.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/expression_refs.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_config.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/depends-on-invalid/depends-on-invalid.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/depends-on/depends-on.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
This PR adds `depends_on` attributes to the `component` and `stack` blocks within `.tfstack.hcl` files.
Components actually depend on other components, so a component depending on an embedded stack is actually just adding dependencies against all the components within the embedded stack. This was actually missing from the current implementation for other references. For example a normal reference to the output of an embedded stack should result in a dependency to the component within the embedded stack that generated that output. This was not happening. I fixed this, with the change to the `requiredComponentsForReferrer`. This fix accounts for the additional changes you can see in some of the other unrelated tests.
With the above bug fixed, connecting the new dependencies to the …
=> stacks: add depends_on for embedded stacks and components

internal/command/hook_module_install.go, internal/getmodules/moduleaddrs/detect_git.go, internal/getmodules/moduleaddrs/detect_git_test.go
Git URL refs often contain slashes, and while it's technically not correct to have unencoded slashes in the query, they were being split off and incorrectly appended to the path as a go-getter subdir. (This was likely part of the PR which pulled a lot of the behavior into the Terraform repo #34847) The behavior was definitely incorrect, and since Terraform apparently accepted unencoded slashes in query parameters in the past, we can just restore the prior behavior rather than rejecting unencoded slashes entirely.
Fixes #34554
=> allow slashes in git url parameters

website/docs/language/functions/templatestring.mdx
This PR reformats the content to the standardized function reference page type developed by the Education team.
=> re reformated the templatestring function ref

.github/workflows/main.yml
While #35554 helped in re-enabling the backport assistant, it came with a caveat that was unknown until after merging that PR - Checks on PRs opened by `github-actions` bot are not triggered due to GitHub's own limitation to avoid cycles in dependent workflows.
This PR changes the default behaviour of the BA in that it will create _draft PRs_ and then let human users mark it ready for review. As a result, the human will be the triggering user (rather than bot), which bypasses the limitation.
=> github: Bump BA to 0.4.7 & let it create draft PRs

.github/workflows/checks.yml
This is a PR complimenting https://github.com/hashicorp/terraform/pull/35574 by updating the triggers such that whenever a PR is opened against any _release branch_ and it is marked as ready for review (`ready_for_review`), the checks are triggered.
To my knowledge, the current default for `pull_request:` does _not_ include `ready_for_review` but I couldn't find conclusive docs to confirm this, I just could not make it work in a private fork.
=> github: Update checks triggers for BA workflow

website/docs/language/resources/provisioners/local-exec.mdx
=> Fix typo in local-exec.mdx

website/docs/cli/commands/output.mdx
Fixes #32861
* correct example for redacting an output value by name.
=> docs: correct example for redacting an output value by name

website/docs/language/expressions/types.mdx
Update Set data type description
Fixes #32601
1.8.x
-
=> Fix #32601 Update Set data type description

website/docs/language/functions/indent.mdx
This was a Docs Day project as listed in the task spreadsheet.
I updated the existing topic to be in the new format of the templatestring function reference [document](https://terraform-rmt1u78ff-hashicorp.vercel.app/terraform/language/functions/templatestring). Added the following new sections:
- Introduction
- Syntax
I worked with Tu and Brian, and we couldn't think of an Example use case. If anyone has an idea, it might be nice to add to this topic :) I deleted the existing example b/c I thought it was difficult to understand, but you could also bring that back.
Please let me know if you have any questions or if there's anything that I can do to help finish this up.
[Deploy Preview](https://terraform-git-fork-dan-heath-patch-2-hashicorp.vercel.app/terraform/language/functions/indent)
=> Docs Day: Update `indent` function reference

website/docs/language/functions/base64gzip.mdx
This was a Docs Day project as listed in the task spreadsheet. Google draft with some comments from Brian is here:
https://docs.google.com/document/d/1Nk9yAQxK1yMQeDPvIKHHh1t2_lDdC1Kh9MmhAgX50YQ/edit?usp=sharing 
I updated the existing topic to be in the new format of the `templatestring function reference` [document](https://terraform-rmt1u78ff-hashicorp.vercel.app/terraform/language/functions/templatestring). Added the following new sections:
- Introduction
- Syntax
- Example use case
[Deploy Preview](https://terraform-git-fork-dan-heath-patch-1-hashicorp.vercel.app/terraform/language/functions/base64gzip)
=> Docs Day: Update `base64gzip` reference doc

website/docs/cli/commands/apply.mdx
Fixes #29268 
We link to the planning options from the apply page (since apply runs an "automatic plan") but don't make it easy to find common planning options that are mentioned using ctrl-f
1.10.0
=> Make it easier to find literal planning options from apply page

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/import-failed-dep/import.tf, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/import-failed-dep/import.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/moved-failed-dep/moved.tf, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/moved-failed-dep/moved.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/removed-failed-dep/removed.tf, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/removed-failed-dep/removed.tfstack.hcl
This PR adds extra tests around the state manipulation functions. The new states verify the correct state and counts are still emitted by the API when an error occurs during applying but after the state manipulation operations have already happened.
Everything worked as expected so there's only changes to the tests in here.
=> stacks: add tests for state manipulation failure cases

website/docs/language/resources/provisioners/null_resource.mdx
=> Fix typo in null_resource.mdx

internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/validate_test.go
Quick fix on the error message we print when recommending users to run `tfstacks providers lock`.
=> stacks: fix suggested command when lock file is out of date

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/cross-type-moved/cross-type-moved.tf, internal/stacks/stackruntime/testdata/mainbundle/test/state-manipulation/cross-type-moved/cross-type-moved.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-provider-functions/with-provider-functions.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-provider-functions/with-provider-functions.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go
This PR updates the stacks runtime so that cross-provider moves and provider functions start working.
Within Stacks we initialise the providers externally to Terraform Core using the provider configurations from the `.tfstack.hcl` files. These are then provided to Terraform Core in the form of overrides, ensuring that it never attempts to initialise it's own providers internally, instead using the providers controlled by the stacks runtime. 
However, there are some operations within Terraform Core that explicitly require unconfigured clients. These are provider functions and cross-provider move refactorings. This PR updates stacks so that in addition to the configured provider overrides that are provided, we still provide options for Terraform to access unconfigured clients for these …
=> stacks: fix bug preventing unconfigured clients within Terraform

docs/architecture.md
Links to pkg.go.dev no longer work: see https://github.com/hashicorp/terraform/issues/35184. Instead, recommend that contributors reading architecture.md run `pkgsite` to render the Terraform Go docs locally.
This is a quick fix for https://github.com/hashicorp/terraform/issues/35394.
=> Update Go doc links in architecture.md

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_factory.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/stubs/errored.go, internal/stacks/stackruntime/internal/stackeval/stubs/offline.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
This PR adds additional protections around the providers created by the stacks runtime and used within Terraform Core. Essentially, Terraform Core should not be calling configure on any of the providers that it has access to during a stacks operation. Either a provider should never be configured as it only used for offline operations, or it should already have been configured by Stacks before being passed into Terraform Core.
We essentially do two things:
- First, the `providerClose` provider that is returned by the stacks factory now intercepts and prevents the configure function being called on the underlying provider returning an error if this is attempted. Any providers that should be configured are configured by stacks before they are wrapped into the `providerClose` implementation. …
=> stacks: ensure providers that should not be configured cannot be

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/component_instance_results.go, internal/stacks/stackruntime/testdata/mainbundle/test/failed-dependency/failed-dependency.tf, internal/stacks/stackruntime/testdata/mainbundle/test/failed-dependency/failed-dependency.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-data-source/with-data-source.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-data-source/with-data-source.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go
This PR fixes a bug in Terraform Stacks whereby "stale" state was not being cleaned up during normal apply operations and, in some cases, destroy operations.
[This comment](https://github.com/hashicorp/terraform/blob/main/internal/stacks/stackruntime/internal/stackeval/component_instance.go#L1517-L1523) sums up what we're trying to do. This isn't working though. We're preserving the previous run state inside the prior state when we write things into the stack plan format. But, when we write the stack plan format back into core format we don't recreate or preserve the objects in the previous run state through a combination of [this](https://github.com/hashicorp/terraform/blob/main/internal/stacks/stackplan/component.go#L145) and [this](https://github.com/hashicorp/terraform/blob/main/intern …
=> stacks: remove stale state during Stack apply operations

internal/command/metadata_functions.go
In the context of ephemeral values [no longer being an experiment](https://github.com/hashicorp/terraform/pull/35636) there is no point in ignoring the function when printing out machine-readable signatures.
```
$ terraform metadata functions -json | jq '.function_signatures | keys' | grep -c ephemeral
0
```
```
$ terraform metadata functions -json | jq '.function_signatures | keys' | grep ephemeral
"core::ephemeralasnull",
"ephemeralasnull",
```
=> internal/command: Avoid ignoring `ephemeralasnull` function

internal/lang/functions_test.go
Just adding tests where there were previously missing - I can't think of a reason for them missing - probably just because testing experiments was/is difficult.
I couldn't figure out a way of testing unknown values - or to put it differently - I couldn't find any existing tests for unknown values. We can always add those later.
=> lang/functions: Add test for `ephemeralasnull`

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/local_value/custom_provider/child/child.tf, internal/stacks/stackruntime/testing/provider.go, internal/stacks/stackruntime/testing/resource.go
This PR refactors the mock provider used by most of the Terraform Stacks integration tests.
The main drive behind the refactor is to break out the implementation of the various resources from the main provider functions. At the beginning all the resources behaved in roughly the same way and there wasn't many of them, but they've slowly become more complex and more of them have been added.
This PR also adds a new one that isn't used yet, but will be used in some upcoming tests for the removed blocks.
In addition, this PR tweaks the behaviour a little bit to make it more realistic. Now you can't create resources with the same ID which means one existing test needed to be modified. Also, I changed the error messages a bit so they point to the resource type that produced them, hopefully …
=> stacks: refactor the mock provider for realism

internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_destroy_deposed_test.go, internal/terraform/node_resource_plan_destroy.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_orphan.go, internal/terraform/node_resource_plan_orphan_test.go
The deferred actions deletion story was a bit inconsistent. This PR updates the destroy paths so they follow the same logic as the create and destroy operations. Namely: 
- They complete the full operation even if an early call defers. This means if a refresh defers, we'll still do the plan and work out a proper diff and then defer with that change instead of a partial change.
- We always set the provider address, where previously we were only setting it some of the time which was causing problems later when trying to read/render the plan.
- Finally, we respect the "defer all changes" part of the plan options. Previously, destroy operations would still apply even when the entire plan was supposed to be deferred.
=> deferred actions: fix missing features in deletions

internal/stacks/stackaddrs/removed.go, internal/stacks/stackaddrs/removed_test.go, internal/stacks/stackconfig/component.go, internal/stacks/stackconfig/config.go, internal/stacks/stackconfig/config_test.go, internal/stacks/stackconfig/declarations.go, internal/stacks/stackconfig/file.go, internal/stacks/stackconfig/removed.go, internal/stacks/stackconfig/testdata/basics-bundle/errored/main.tf, internal/stacks/stackconfig/testdata/basics-bundle/errored/main.tfstack.hcl, internal/stacks/stackconfig/testdata/basics-bundle/nested/subdir/main.tfstack.hcl, internal/stacks/stackconfig/testdata/basics-bundle/terraform-sources.json
This PR adds support for removed blocks within the Terraform Stacks configuration language.
For now, we just accept the removed blocks in the configuration but don't do anything with them yet.
=> stacks: add support for the removed block to .tfstacks.hcl

internal/stacks/stackplan/from_plan.go, internal/stacks/stackplan/from_proto.go, internal/stacks/stackruntime/internal/stackeval/applying.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/planning.go, internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/provider_expressions.go, internal/stacks/stackruntime/validate_test.go, internal/stacks/stackstate/from_state.go, internal/stacks/tfstackdata1/convert.go
This PR is a pure refactor of logic that will eventually be shared between the components and removed blocks. Essentially, the components and the removed blocks both plan and execute changes to the configuration. This PR moves the bridges between stacks and terraform core into shared functions that can be reused between any elements of stacks that wants to execute plan and apply commands.
=> stacks: refactor shared functionality in prep for removed blocks

internal/terraform/node_output.go
This enforces a more explicit configuration where ephemeral values have to be marked as such unless they are already ephemeral before being used in ephemeral context.
For example, the original prototype allowed this:
```hcl
variable "ephemeral" {
ephemeral = true
default   = 12
}
locals {
not-ephemeral = 42
}
output "foo" {
ephemeral = true
value     = var.ephemeral + local.not-ephemeral
}
```
This PR disallows that.
[A new `ephemeral()` function](https://github.com/hashicorp/terraform/pull/35653) may introduce an escape hatch though, to account for cases where ephemerality cannot be directly declared, such as in local values.
```hcl
output "foo" {
ephemeral = true
value     = var.ephemeral + ephemeral(local.not-ephemeral) # ALLOWED
}
```
The **downside** is that it also enables some use …
=> internal/terraform: Accept only ephemeral values in ephemeral outputs

internal/terraform/upgrade_resource_state.go, internal/terraform/upgrade_resource_state_test.go
During the state upgrade process we may have attributes which are no longer part of the schema type. Because cty requires the data to strictly match the schema we can't ignore these extra attributes and must actively filter them. In order to do that we use `encoding/json` to decode the state in a generic manner, but we need to account for large `cty.Number` values which may exceed `float64` precision.
=> core: use `json.Number` for decoding state

internal/backend/backendrun/operation.go, internal/backend/local/backend_apply.go, internal/backend/local/backend_local_test.go, internal/cloud/state.go, internal/command/jsonformat/state.go, internal/command/jsonstate/state.go, internal/command/output.go, internal/command/output_test.go, internal/command/refresh_test.go, internal/command/views/output.go, internal/command/views/output_test.go, internal/states/output_value.go, internal/states/remote/state.go, internal/states/state.go, internal/states/state_deepcopy.go, internal/states/statefile/version4.go, internal/states/statemgr/filesystem.go, internal/states/statemgr/lock.go, internal/states/statemgr/persistent.go, internal/states/statemgr/statemgr_fake.go, internal/states/sync.go, internal/terraform/context_apply_test.go, internal/terraform/evaluate.go, internal/terraform/node_output.go
Ephemeral root output values must be kept in the in-memory state representation, but not written to the state file. To achieve this, we store ephemeral root outputs separately from non-ephemeral root outputs, so Terraform can access them during a single plan or apply phase.
Ephemeral root outputs always have a value of null in the state file. 
This PR makes ephemeral outputs render correctly in `terraform output -json` (the machine-readable representation) but not `terraform output` (human-readable): the latter requires some more work on the renderer. The human-readable output currently shows the value of ephemeral outputs as null, but does not annotate them as "ephemeral".
=> states: store ephemeral output values in memory

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/plan_test.go
This PR adds a check to the root Stack object such that it will add diagnostics if it discovers any components within state that are not referenced by a component or a removed block. This ensures that users don't think they are deleting resources by removing a component block and forgetting to add a removed block.
=> stacks: ensure that all components in state are referenced in configuration

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/walk_static.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/invalid-provider-type/invalid-provider-type.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/missing-provider/missing-provider.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/undeclared-provider/undeclared-provider.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
This PR updates the validate command (and other static walks) within Stacks to include the new removed blocks. It also extends some of the tests to make sure we are catching the same kind of provider validations for both components and removed blocks.
=> stacks: include removed blocks during validate command

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-embedded-component/removed-embedded-component.tfstack.hcl
Just adding a quick test to verify the functionality, no additional implementation needed to make it work.
=> stacks: add a test for removed blocks in embedded stacks

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go, internal/stacks/stackruntime/plan_test.go
This PR adds an error message if a removed block within stacks targets a component that is still defined within the configuration.
=> stacks: error when removing a component still in config

internal/backend/local/backend_local.go
This is to ensure users are aware of any side effects when entering value of a variable.
One alternative I considered was to extend `InputOpts` by introducing `Ephemeral bool`, just to ensure that the "(ephemeral)" note is not formatted as bold.
```hcl
variable "test" {
ephemeral = true
description = "test description"
}
```
We could also consider different wording to make the side effects more obvious but I can't think of anything more obvious that also happens to be short.
=> backend/local: Indicate ephemerality in variable prompts

internal/command/jsonformat/computed/diff.go, internal/command/jsonformat/computed/renderers/block.go, internal/command/jsonformat/computed/renderers/blocks.go, internal/command/jsonformat/computed/renderers/map.go, internal/command/jsonformat/computed/renderers/set.go, internal/command/jsonformat/computed/renderers/unknown.go, internal/command/jsonformat/computed/renderers/util.go, internal/command/jsonformat/differ/block.go, internal/command/jsonformat/plan_test.go
This PR updates the rendering logic so that it properly renders the contents of a nested block that is becoming unknown. Previously, we'd only render a single item for the whole nested block. Now we should a single item being created that is unknown, and all existing entries being marked as deleted.
In addition, this change fixes a crash that would occur when nested blocks were becoming unknown and contained attributes that were forcing the resource to be replaced. We weren't properly accounting for the nested indices within the replacement list, and now since we are properly computing the diffs we are.
Fixes #35556 
v1.9.7
- Plan renderer: Fix crash that occurs when attempting to render unknown nested blocks that contain attributes forcing replacement.
- Plan renderer: Render complete …
=> plan renderer: render unknown nested blocks properly

internal/command/jsonformat/computed/renderers/block.go, internal/command/jsonformat/computed/renderers/renderer_test.go, internal/command/jsonformat/computed/renderers/unknown.go, internal/command/jsonformat/plan_test.go
This PR fixes a crash in the plan renderer that occurs when a plan marks an attribute that was null as becoming unknown.
The renderer had assumed that all computed attributes would have a value if the resource was being updated, so was only checking for `plans.Create` actions before deciding whether to render the "before" part of an unknown change. Now, we explicitly check whether the before part has a renderer at all when deciding whether to render the before part rather than simply relying on a logical consistency based on the false assumption it would only ever be create actions doing this.
There's also a flyby fix of the block renderers which can now successfully render blocks becoming unknown as update actions instead of create since that does not crash anymore.
Note, we could render …
=> plan renderer: fix crash when updating a null attribute to unknown

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/validate_test.go
Basically all of our stacks integration tests follow the same exact pattern in how they execute tests. This has led to a lot of duplicate code, and makes writing new tests quite onerous as you have to copy and paste all the required set up from an existing test into your new test when it is actually exactly the same.
My proposal is to introduce dedicate helper functions that actually handle all the boiler plate code, and then we can easily write new tests based on here's the input and here's the expected output without needing to do all the configuration.
This PR creates new helper functions that can validate, plan, and apply stack configurations in sequence while sharing common code across all tests. I've migrated the validate and apply_destroy tests over to using the shared code. I …
=> stacks: introduce shared functions for common tests

internal/plans/planproto/convert.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/forgotten-component/forgotten-component.tfstack.hcl, internal/states/module.go, internal/states/sync.go, internal/terraform/context_apply2_test.go, internal/terraform/context_plan.go, internal/terraform/context_walk.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/graph_walk_context.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_forget.go
[Jira](https://hashicorp.atlassian.net/browse/TF-18437)
1.10.x
-  stacks: removed block supports forgetting components
=> stacks: support forgetting components

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/stack.go
This is a super quick follow up to #35724, which makes sure we set the action as Update and NoOp appropriately based on if the value in the input or outputs has actually changed or not.
=> stacks: mark input and output changes as no-ops when no changes

website/docs/language/state/workspaces.mdx
Documentation link goes in 404 due to the missing `language` prefix in the URL.
=> fix(workspaces): URL for Kubernetes secret backend

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/testdata/mainbundle/test/forget_with_dependency/forget_with_dependency.tf, internal/stacks/stackruntime/testdata/mainbundle/test/forget_with_dependency/forget_with_dependency.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/forget_with_dependency_to_forget/forget_with_dependency_to_forget.tf, internal/stacks/stackruntime/testdata/mainbundle/test/forget_with_dependency_to_forget/forget_with_dependency_to_forget.tfstack.hcl
=> stacks: fix dependency handling in component forget

internal/stacks/stackplan/planned_change.go, internal/stacks/stackplan/planned_change_test.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackstate/applied_change.go, internal/stacks/tfstackdata1/convert.go, internal/stacks/tfstackdata1/convert_test.go
This PR stops the stacks runtime encoding values into the msgpack representation twice. We write the dynamic value into the raw data and planned / applied changes in different wrappers. Previously, we were encoding the value into msgpack independently for both representations. This PR updates the `tfstackdata1` package so that it accepts the `stacks` representation of a dynamic value and reuses the already encoded data instead of encoding it again.
=> stacks: stop encoding values into msgpack twice

internal/addrs/parse_ref.go, internal/addrs/parse_ref_test.go, internal/addrs/parse_target.go, internal/addrs/parse_target_test.go, internal/addrs/resource.go, internal/addrs/resourcemode_string.go, internal/builtin/providers/terraform/provider.go, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/provider-simple-v6/provider.go, internal/provider-simple/provider.go, internal/providers/ephemeral.go, internal/providers/functions_test.go, internal/providers/mock.go, internal/providers/provider.go, internal/providers/schemas.go, internal/providers/testing/provider_mock.go, internal/refactoring/mock_provider.go, internal/stacks/stackruntime/internal/stackeval/stubs/errored.go, internal/stacks/stackruntime/internal/stackeval/stubs/offline.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
Implement some foundation required to start work on the ephemeral resource type. Nothing here is actually functional yet, but the scope of changes is pretty large so I'm splitting this up into smaller segments while keeping everything working.
- Add a new resource mode in the `addrs` package to differentiate the new resources, but still allow the same language semantics as references to other resource types.
- Add the internal interface definition for the ephemeral actions. This also requires updating all implementations of the interface, though none of those methods can be called yet.
=> ephemeral resource addresses and interface definitions

internal/configs/config.go, internal/configs/config_test.go, internal/configs/module.go, internal/configs/parser_config.go, internal/configs/resource.go, internal/configs/testdata/invalid-files/ephemeral-invalid-lifecycle.tf, internal/configs/testdata/invalid-files/ephemeral-invalid-name.tf, internal/configs/testdata/valid-files/resources.tf, internal/lang/eval.go, internal/lang/eval_test.go
This add ephemeral resources to the configuration language. Terraform can now parse ephemeral resource configuration and references.
=> Add ephemeral resources to the Terraform language

internal/providers/ephemeral.go, internal/resources/ephemeral/ephemeral_resource_instance.go, internal/resources/ephemeral/ephemeral_resource_test.go, internal/resources/ephemeral/ephemeral_resources.go
The `resources/ephemeral` package manages ephemeral resources and and the lifecycle.
Ephemeral resources have a very different lifecycle from managed resources, and need to be managed more similarly to named values than resources. The `resources/ephemeral` package is a separate database for tracking ephemeral resource values, refreshing those resources as required, and closing down the resources when they are no longer needed.
=> New `resources/ephemeral` package for tracking ephemeral resource lifecycle

internal/command/test.go
Fixes a tiny typo.
1.8.x
-  `terraform test -help`: Fixed a tiny typo ("Enterpise" -> "Enterprise").
=> Fix typo in test.go

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go
This PR modifies the order of the dependency graph of components in Stacks to match the ordering applied to resources within Terraform Core.
When the dependency graph was originally written, I thought the "reversed ordering" applied during the destroy graph of Terraform was also applied on normal destroy operations in the regular graph. This isn't the case because it introduces cycles into the graph whenever providers require outputs from previous resources and are required to destroy a resource. It is clear that the resource being destroyed cannot become a dependency of the earlier resource, otherwise we'd definitely have a cycle.
The current implementation of Stacks, however, does this. And we have discovered the cycles with providers being a natural consequence. This PR modifies the …
=> stacks: stacks destroy ordering should match Terraform

website/docs/language/backend/s3.mdx
This PR fixes the documentation for the S3 backend.
The current DynamoDB IAM policy states that the lock key path should be prefixed with the DynamoDB table name. This is incorrect. As indicated by the source code below, the lock key path is prefixed by the S3 bucket name, not the DynamoDB table name.
- https://github.com/hashicorp/terraform/blob/a73e4e658648e0d507e89c4cd389a2af5edf9395/internal/backend/remote-state/s3/client.go#L495-L497
I've also updated the bucket's name to `BucketName` to match the DynamoDB table name, `TableName.`
=> Fix IAM Policy Documentation for S3 Backend

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
This PR updates the config generation package so map keys with whitespace are escaped with quotes. This is already handled automatically for the normal attribute generation, and nested blocks are also escaped by default. This PR updates the nested attributes so the keys of nested maps are validated and escaped if necessary. It is only maps that have this problem, attributes in objects cannot contain whitespace and other types (lists, sets, tuples) do not render keys anyway.
The rendering package has this same problem, and so far we've not handled it perfectly but just well enough. We'll continue to do so here, but the code calls out we could modify the HCL library so it exposes the internal functions it uses to detect when escaping is necessary and share those between HCL and Terraform. …
=> config generation: escape map keys with whitespace

internal/resources/ephemeral/ephemeral_resources.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/node_module_expand.go, internal/terraform/node_resource_ephemeral.go
This turned out to be a very simple change to get the correct cancellation context into ephemeral resources. The internal terraform `EvalContext` has a very old `Stopped` method which returned a channel instead of a `Context`, and was never used.
Replace the `Stopped` method with `StopCtx` which returns the full `context.Context` so we can forward that into the ephemeral resource calls.
=> core: get a cancelation context to the ephemeral resources

.github/dependabot.yml
This sets up Dependabot to automatically create PRs for Go dependencies with security vulnerabilities. The trick here is the `open-pull-requests-limit: 0` [setting](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit), which is essentially the part that says "don't have Dependabot create PRs for regular dependency upgrades, only for security issues". The `schedule.interval: daily` ensures that once a security vulnerability is flagged and a dependency upgrade is available that solves the issue, Dependabot will create a new PR within 24 hours. That seems appropriate for security issues.
Eventually we'd like to see if we can scale up to more regular (non-security) dependency upgrades using …
=> build: Set up Dependabot for go security updates

internal/terraform/context_plan_ephemeral_test.go, internal/terraform/context_validate_test.go, internal/terraform/node_output.go
This is an alternative to https://github.com/hashicorp/terraform/pull/35719 as discussed at length in Slack.
The assumptions are that we know of no valid use cases for _root_ ephemeral outputs and conversely know of negative consequences, such as those being exposed in logs etc. and leading to unintentional persistence - which would effectively violate the original promise of "ephemerality".
1.10.x
-  Ephemeral root outputs are now rejected to avoid values in such outputs to be mistakenly persisted
=> terraform: Reject root ephemeral outputs

internal/command/jsonprovider/provider.go, internal/command/jsonprovider/provider_test.go, internal/schemarepo/loadschemas/plugins.go
I tested this successfully manually with a `hashicorp/random` provider built from [this branch](https://github.com/hashicorp/terraform-provider-random/compare/main...av/ephemeral-password) (which has `random_password` resource available). I'm not sure if there is any good place where I can/should be adding tests for this as it's a basic data serialisation problem (i.e. there is relatively little to go wrong with the particular field, unless the serialisation as whole fails).
- https://github.com/hashicorp/terraform-json/pull/138
1.10.x
- Expose ephemeral resource schemas as part of `terraform providers schema -json` output
=> jsonprovider: Expose ephemeral resource schemas

internal/backend/backendrun/operation.go, internal/backend/local/backend_apply.go, internal/backend/local/backend_local_test.go, internal/backend/local/test.go, internal/cloud/state.go, internal/command/jsonstate/state.go, internal/command/output.go, internal/command/output_test.go, internal/command/views/output.go, internal/command/views/output_test.go, internal/states/output_value.go, internal/states/remote/state.go, internal/states/state.go, internal/states/state_deepcopy.go, internal/states/statefile/version4.go, internal/states/statemgr/filesystem.go, internal/states/statemgr/lock.go, internal/states/statemgr/persistent.go, internal/states/statemgr/statemgr_fake.go, internal/states/sync.go, internal/terraform/context_apply_test.go, internal/terraform/context_plan2_test.go, internal/terraform/evaluate.go, internal/terraform/node_output.go, internal/terraform/transform_orphan_output.go
This is effectively reverting ~99% of https://github.com/hashicorp/terraform/pull/35676 The only changes not being reverted are some formatting and deprecation fixes which remain relevant.
The code being removed is basically dead code now in the context of root ephemeral outputs being rejected per https://github.com/hashicorp/terraform/pull/35791
=> Remove handling of ephemeral root outputs

go.mod, go.sum
Fixes #34615
Bumped go-cty-yaml to v1.1.0. Yaml number parsing is now fully according to [YAML spec](https://yaml.org/spec/1.2-old/spec.html#id2805071). See [go-cty-yaml v1.1.0 CHANGELOG](https://github.com/zclconf/go-cty-yaml/blob/master/CHANGELOG.md#110-october-2-2024) for details.
Yaml number parsing is now fully according to [YAML spec](https://yaml.org/spec/1.2-old/spec.html#id2805071).
Related go-cty-yaml PR: https://github.com/zclconf/go-cty-yaml/pull/14
=> Bumped go-cty-yaml to v1.1.0

internal/backend/local/backend_apply.go, internal/collections/cmp.go, internal/collections/map.go, internal/collections/set.go, internal/plans/planfile/tfplan.go, internal/stacks/stackplan/from_proto.go, internal/stacks/stackplan/from_proto_test.go, internal/stacks/stackplan/plan.go, internal/stacks/stackplan/planned_change.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/change_exec.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackstate/applied_change.go, internal/stacks/stackstate/state.go, internal/stacks/stackstate/state_builder.go, internal/terraform/context_apply.go
This is an updated version of the changes tested out in #35426. We can mostly hide the internal details of the data types now, however the `MapElem` and it's `K` `V` fields are still exported in order to allow the creation of a populated map with a single expression, which is used in a number of tests already. The `MapElem` type is only exposed to provide a structure for the pairs of inputs to the constructor, and no longer needed for any external manipulation of the data. 
I also evaluated the use of `addrs.Map` and `addrs.Set`, which uses some similar ideas but the structure is different enough that there is no straightforward way to translate the code and unify the use of these types. All the types in the `addrs` package already have their own `UniqueKey` methods tied to the package …
=> Use go1.23 iterators for internal collection types

internal/stacks/stackplan/from_proto.go, internal/stacks/stackplan/planned_change.go, internal/stacks/stackplan/planned_change_test.go, internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/output_value.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral-default/ephemeral-default.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral/ephemeral.tfstack.hcl, internal/stacks/stackstate/applied_change.go, internal/stacks/stackstate/from_proto.go, internal/stacks/stackstate/state.go
This PR updates the behaviour of ephemeral inputs and outputs within stacks to match equivalent behaviour within core.
Previously, Stacks was removing all ephemeral values by encoding them as cty.NilVal or an empty pointer within the protocol buffer definitions.
Now, we use an unmarked null value to represent ephemeral values in line with the principles being implemented in Terraform Core.
Tapping @Uk1288 as an FYI, though I don't think this will change any of the required integrations.
There's a small refactor here where the processing of output values is pulled from the stack level into the individual output nodes. This matches the behaviour of the input variables, and makes discovering ephemeral values easier which is what led to the given approach for input variable as well.
=> stacks: represent ephemeral inputs and outputs as null

CHANGELOG.md, internal/backend/remote-state/s3/backend.go, internal/backend/remote-state/s3/backend_complete_test.go, internal/backend/remote-state/s3/backend_test.go
The PR #35720 introduced a breaking change to the S3 backend
IAM role chaining will be re-introduced at a later date
Fixes #35816
No CHANGELOG entry: reverts feature only present in alpha build
=> backend/s3: Revert IAM role chaining support

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/auth-provider-w-data/auth-provider-w-data.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/auth-provider-w-data/removed/removed.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/component-chain/component-chain.tf, internal/stacks/stackruntime/testdata/mainbundle/test/component-chain/component-chain.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-data-source/dependent/dependent.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-data-source/dependent/dependent.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go
This PR updates the component instance plan and apply operations so that if there is no state during the plan, or no changes during the apply, we no longer actually execute a full plan or apply operation.
This was causing issues during the refresh with modules that return null or unknown values for non-existent resources. These values were then being used as inputs into the delete and refresh operations for other empty components. Since data sources are still loaded during the refresh we would then see errors as a result of null or unknown values during the apply operation.
After this PR if the whole component is not in state (so it's already been deleted or was never created) then we skip the actual operation and return pre-built values for the plan and state that don't require …
=> stacks: skip full plan/apply cycles when deleting empty state

internal/stacks/stackruntime/internal/stackeval/output_value.go, internal/stacks/stackruntime/internal/stackeval/output_value_test.go, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/output_value/ephemeral_child/child/ephemeral-child-child.tfstack.hcl, internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/output_value/ephemeral_child/ephemeral-child.tfstack.hcl
[Jira: TF-18610](https://hashicorp.atlassian.net/browse/TF-18610)
1.10.x
-
=> stacks: root level outputs should not allow ephemeral values

internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral-default/ephemeral-default.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/ephemeral/ephemeral.tfstack.hcl
I merged https://github.com/hashicorp/terraform/pull/35831 updating ephemeral values within stacks to be represented as null values when exposed to the plan and state files. This PR affected both inputs and outputs, so both were updated.
Simultaneously, @DanielMSchmidt merged https://github.com/hashicorp/terraform/pull/35826 which actually prevent ephemeral values being used as outputs at all.
The combination of these two PRs broke the test pipeline on main without interacting with each other as I introduced tests untouched by Daniel's change that were incompatible. This PR removes the broken parts of the tests (namely the ephemeral outputs) and fixes the build (hopefully).
=> stacks: fix tests broken now that ephemeral outputs aren't allowed

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
This PR updates the config generation so that any invalid HCL syntax in generated map keys is escaped and not just whitespace.
Fixes #35752 
1.9.x
-  config generation: Escape all invalid syntax in generate map keys with quotes.
=> configgen: escape any invalid HCL syntax in map keys

internal/initwd/module_install.go, internal/initwd/module_install_test.go, internal/initwd/testdata/invalid-registry-modules/.gitignore, internal/initwd/testdata/invalid-registry-modules/root.tf
This PR updates `terraform init` so that if a module source is requesting a subdirectory within a registry module, where the registry module itself does exist and is successfully downloaded but the subdirectory is missing, Terraform correctly highlights the missing subdirectory as the problem rather than a generic "This is a bug in Terraform" message.
```
╷
│ Error: Unreadable module directory
│ 
│ The directory .terraform/modules/karpenter_fg_profile/modules/fargate_profile could not be read. This is a bug in Terraform and should be reported.
╵
```
```
╷
│ Error: Unreadable module subdirectory
│ 
│ The directory .terraform/modules/karpenter_fg_profile/modules/fargate_profile does not exist. The target submodule modules/fargate_profile does not exist within the target module.
╵
```
Fixes …
=> init: detect and report invalid submodules

internal/configs/provider_meta.go
This PR updates the parsing of the `provider_meta` blocks so that providers with invalid names aren't returned. This prevents a crash that occurs later when the names are parsed, and doesn't affect behaviour otherwise as the diagnostic explaining the error is still returned.
Fixes #35835 
1.9.x
-  Prevent crash when loading `provider_meta` blocks with invalid names.
=> provider meta: don't return providers with invalid names

internal/plans/deferring/deferred.go, internal/plans/deferring/deferred_test.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/evaluate.go, internal/terraform/node_resource_ephemeral.go, internal/terraform/node_resource_partial_plan.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_partialexp.go
1.10.x
- Ephemeral Resources: Support providers deferring ephemeral resource open calls
=> ephemeral resource deferrals

CHANGELOG.md
Relates #35661
Adds a changelog entry documenting support for S3 native state locking in the S3 backend. 
Once the upgrade guide is updated for 1.10 (currently still includes 1.9 upgrade notes) I will follow up with a more detailed description of the behavior when using the DynamoDB and S3 locking mechanisms together and plans for future deprecations and removals of DynamoDB configuration options.
1.10.0
- backend/s3: The s3 backend now supports S3 native state locking. When used with DynamoDB-based locking, locks will be acquired from both sources. In a future minor release of Terraform the DynamoDB locking mechanism and associated arguments will be deprecated. ([#35661](https://github.com/hashicorp/terraform/issues/35661))
=> backend/s3: s3 native locking changelog entry

internal/terraform/context_plan_ephemeral_test.go, internal/terraform/context_test.go, internal/terraform/eval_count.go, internal/terraform/eval_for_each.go
This PR ensures we check for ephemeral values for all possible expansions (for_each / count on resource / module / import).
It also refactors the plan tests and adds a lot of new tests for everything I could find in the RFC, some are skipped to leave the implementation to future PRs.
1.10.x
-  Ephemeral Values: Error if ephemeral values are used in the context of count or for_each
=> Ephemeral expansion and add tests for ephemeral values

internal/addrs/graph.go, internal/builtin/providers/terraform/provider.go, internal/dag/dag.go, internal/dag/dag_test.go, internal/terraform/context_apply_ephemeral_test.go, internal/terraform/context_plan.go, internal/terraform/graph_builder_plan.go, internal/terraform/graph_test.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_apply_test.go, internal/terraform/transform_config.go, internal/terraform/transform_destroy_edge.go, internal/terraform/transform_provider.go, internal/terraform/transform_reference.go, internal/terraform/transform_targets.go
Make sure ephemeral resources are inserted into the graph and evaluated during both apply and destroy operations. We make sure we insert ephemeral `nodeExpandApplyableResource` from the configuration during destroy, and that it can always correctly call the ephemeral planning path in both situations.
`CloseProviderTransformer` was fixed to use the `GraphNodeProviderConsumer` to connect the close nodes, so that ephemeral resource close nodes can be inserted into the graph without special casing them.
Some minor refactor from various experiment was left in here too, like change `AcyclicGraph.Ancestors` to not return an error which matches the `Descendants` behavior. 
This does not yet fix the hard problem of pruning unused/unusable ephemeral resource nodes from the graph when executing a …
=> Apply and destroy evaluation of ephemeral resources (partial)

internal/configs/config.go, internal/terraform/context.go, internal/terraform/context_apply_checks_test.go, internal/terraform/context_plan.go, internal/terraform/context_test.go
This PR updates the validation of required providers so that it also makes sure any providers required by the state are included. This improves the error message returned when a resource is in state but not in config and has no included provider.
Before
```
╷
│ Error: failed to read schema for null_resource.resource in registry.terraform.io/hashicorp/null: failed to instantiate provider "registry.terraform.io/hashicorp/null" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/null"
│ 
│ 
╵
```
After
```
╷
│ Error: Missing required provider
│ 
│ This state requires provider registry.terraform.io/hashicorp/null, but that provider isn't available. You may be able to install it automatically by
│ running:
│   terraform init
╵
```
Fixes #35860 
1.9.x
-  Improve error …
=> plan: also validate provider requirements from state

internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/ephemeral_input/main.tf, internal/command/testdata/test/ephemeral_input/main.tftest.hcl, internal/command/testdata/test/ephemeral_input_with_error/main.tf, internal/command/testdata/test/ephemeral_input_with_error/main.tftest.hcl, internal/command/testdata/test/ephemeral_resource/main.tf, internal/command/testdata/test/ephemeral_resource/main.tftest.hcl, internal/command/testing/test_provider.go, internal/command/views/json/diagnostic.go, internal/lang/checks.go, internal/moduletest/eval_context.go, internal/terraform/diagnostics.go, internal/terraform/eval_count.go, internal/terraform/eval_for_each.go
Adds support for ephemeral values and an error for ephemeral resources to terraform test
1.10.x
- terraform test: Adding support for ephemeral values and an error for ephemeral resources
=> test: Add support for ephemeral values and an error for ephemeral resources

internal/addrs/parse_target.go, internal/addrs/parse_target_test.go, website/docs/language/moved.mdx
This PR updates the parsing of targets (such as within import and moved blocks) so that they respect the keywords reserved by the top level references within Terraform.
These keywords include things like `local`, `each`, `count`, `self`, and `terraform`. Previously it was possible to reference these from within `moved` as resource types without prefixing them with the normally required `resource.` identifier to differentiate between a resource with the type name `local` and just referencing a `local` variable.
I'm not backporting this change, as it is technically a breaking change though I doubt anyone will be affected. Anyone who uses a resource that is simple called `local` (or any other reserved keyword) would previously have been able to reference it directly from a `moved` block. …
=> moved: error if not targeting a resource address

internal/dag/dag.go, internal/dag/dag_test.go, internal/terraform/context_apply2_test.go, internal/terraform/transform_reference.go
Add ancestor equivalents of FirstDescendantsWith and MatchDescendant.
In configurations with long chains of dependencies, we spend a lot of time recording redundant dependency edges, and writing all those dependencies in the state.
Rather than record every possible dependency edge, we can use the new methods above to only record the first managed resource in any lineage, such that the resulting graph is topologically equivalent having removed many transitive edges. For some configurations this can save considerable time and space when handling the state.
While this can remove the bulk of transitive dependencies in a lot of cases, this does not reduce the subgraph of direct dependencies. Take for example a resource `X`, and a graph with edges `X->A` `X->B` `A->B`. We will still currently …
=> core: use more efficient methods for finding ancestors

internal/terraform/context_apply.go, internal/terraform/context_plan.go, internal/terraform/context_plan2_test.go, internal/terraform/providers.go
This PR updates the external provider validation within Terraform Core such that it now includes the plan and/or state files when checking for "required providers". This means that when a user deletes all usages of a given provider they don't need to explicitly add that provider to the required providers block.
This improves the UX for users, since adding providers to the required providers block isn't required, making them do it only after they have removed resources is counter intuitive.
=> stacks: include plan and state providers when validating external providers

internal/terraform/context_apply2_test.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_destroy_deposed.go, internal/terraform/node_resource_forget.go, internal/terraform/node_resource_plan_destroy.go, internal/terraform/transform_destroy_edge.go
Ephemeral resources were the straw that broke the `pruneUnusedNodesTransformer`'s back. This transformer has always been in a tough spot, trying to maintain legacy behaviors around destroy, while keeping destroy operations from failing entirely from configuration evaluation errors. As we've tidied up graph creation over many prior versions, there were just a few node types which were incorrectly classified that were preventing us from inverting the `pruneUnusedNodesTransformer` logic to the more reasonable task of finding what to keep, rather than finding what to exclude.
With the missing destroy node types sorted out, the `pruneUnusedNodesTransformer` no longer needs to keep up with the whack-a-mole game of detecting nodes which might need to be skipped. When executing a destroy …
=> core: update destroy graph pruning to handle ephemeral resources

internal/lang/funcs/datetime.go, internal/lang/functions_test.go
Before a timestamp is assigned during plan, the `time.Time` value will be the zero value for that type. This represents a case where the timestamp is not yet known, but the handling of that timestamp isn't using our usual cty value system for representing unknowns. Rather than refactor the use of the timestamp itself throughout the code, we can simply have the function return an unknown if it encounters a zero value.
Fixes #35898
=> `plantimestamp` can be unknown during validation

internal/terraform/context_eval_test.go, internal/terraform/evaluate.go
The console eval walk is a special case where only state is evaluated, however since ephemeral resources will never have stored state we need to make sure that their evaluation always returns an unknown value.
Fixes #35912
=> fix ephemeral evaluation during with console

internal/checks/state_init.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/node_module_variable.go, internal/terraform/node_resource_ephemeral.go
Complete custom condition checks for ephemeral resources. These essentially work the same as they do for managed resources, however an ephemeral resource will continue "run" after a failed postcondition, to give the provider a chance to eventually call `Close` if needed.
=> core: check preconditions and postconditions for ephemeral resources

internal/command/jsonformat/renderer.go, internal/command/views/hook_json.go, internal/command/views/hook_json_test.go, internal/command/views/hook_ui.go, internal/command/views/hook_ui_test.go, internal/command/views/json/change.go, internal/command/views/json/hook.go, internal/command/views/json/message_types.go, internal/plans/action.go, internal/plans/action_string.go, internal/terraform/eval_context.go, internal/terraform/hook.go, internal/terraform/hook_mock.go, internal/terraform/hook_stop.go, internal/terraform/hook_test.go, internal/terraform/node_resource_ephemeral.go, website/docs/internals/machine-readable-ui.mdx
```sh
$ terraform plan
```
```
data.local_file.foo: Reading...
ephemeral.random_password.example: Opening...
data.local_file.foo: Read complete after 0s [id=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3]
ephemeral.random_password.example: Opening complete after 0s
ephemeral.random_password.example: Closing...
ephemeral.random_password.example: Closing complete after 0s
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
```sh
$ terraform apply
```
```
ephemeral.random_password.example: Opening...
data.local_file.foo: Reading...
data.local_file.foo: Read complete after 0s [id=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3]
ephemeral.random_password.example: Opening …
```
=> terraform: Emit lifecycle phases of ephemeral resources to the UI

website/docs/language/functions/ephemeralasnull.mdx, website/docs/language/functions/terraform-applying.mdx, website/docs/language/resources/ephemeral.mdx, website/docs/language/resources/provisioners/connection.mdx, website/docs/language/resources/provisioners/syntax.mdx, website/docs/language/stacks/reference/tfstacks-cli.mdx, website/docs/language/state/sensitive-data.mdx, website/docs/language/values/locals.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Remove the notes and fix the build!
=> Remove note components

internal/command/views/hook_ui_test.go
It's not ideal to be using `time.Sleep` in tests but this should at least reduce the chances of that test failing, since the space for a possible delay caused by CPU contention is increased to 995ms.
=> command/views: Attempt to fix flaky hook test

internal/providers/testing/provider_mock.go, internal/resources/ephemeral/ephemeral_resources.go, internal/terraform/context_apply_ephemeral_test.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_apply_instance.go
It turns out the reuse of the plan nodes for ephemerals during apply was interfering with how checks are handled in the plan. Since checks already have an established pattern of use, we can avoid the whole issue by using only the resource apply nodes to kick of ephemeral values.
This copies the subset of expansion logic needed from the resource plan node into the apply node. Since the apply time evaluation is much simpler, duplicated code is not overly complex, but we may want to revisit this for refactoring in the future.
Fixes #35924
=> add discrete codepaths for ephemeral apply nodes

CHANGELOG.md
This appears to pre-date some changes and decisions we have made about rejecting root ephemeral values entirely, so the output command does not ever get to touch ephemeral values.
See https://github.com/hashicorp/terraform/pull/35791
=> Changelog: Correct mention about ephemeral values in `output` command

internal/command/views/hook_json_test.go
This is in reaction to a failure indicated in the CI:
https://github.com/hashicorp/terraform/actions/runs/11628307687/job/32383225309#step:6:91
Again - not ideal to use `time.Sleep` in general but the fix of the other test appears to have addressed the flakiness for now in https://github.com/hashicorp/terraform/pull/35927
=> command/views: Attempt to fix flaky JSON hook test

internal/command/views/hook_json.go, internal/command/views/hook_ui.go, internal/resources/ephemeral/ephemeral_resources.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/node_resource_ephemeral.go
If an ephemeral resource configuration contains any unknown values, that resource cannot be opened with the provider. This works in the same was as a data source, in that a placeholder is created by Terraform for evaluation, taking the configuration values and inserting unknown values for any computed attributes.
We also add a UI hook for ephemeral resources which can't be read due to unknown values:
```
ephemeral.random_password.example: Configuration unknown, deferring...
```
This is a stopgap to give users some feedback when an ephemeral resource can't be opened, since there is no artifact in the plan which could otherwise be inspected. While the results could generally be inferred, hopefully this helps users more easily figure out what may be happening if they are seeing unexpected …
=> Handle unknown values in ephemeral resource config

internal/terraform/context_plan_ephemeral_test.go, internal/terraform/eval_variable.go
Backport of https://github.com/hashicorp/terraform/pull/35962
1.10.x
-
=> backport: ephemeral: deal with ephemeral masking in variable validation

internal/terraform/context_apply2_test.go, internal/terraform/graph_builder_apply.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_apply_instance.go
If an instance was forced to be CreateBeforeDestroy due to a dependent, and that dependent had no changes to apply, the dependent would not be in the graph to force the CBD status on the change, and the result would be lost from the state.
This rarely made any difference, because the status would be restored during the next plan, which is why it was not noticed until now. However if the resource was immediately removed from the configuration, the incorrect state would be the only source of the destroy order, which could result in a cycle during the next apply.
While it would be better to use the destroy order calculated during plan, when there is a newly created object its plan state is not stored because the instance has a null state value. This means we still need to recompute the CBD …
=> make sure all resource apply nodes implement `GraphNodeDestroyerCBD`

internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go, internal/lang/funcs/conversion.go, internal/lang/funcs/conversion_test.go, internal/lang/funcs/encoding.go, internal/lang/funcs/encoding_test.go, internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go, internal/lang/funcs/funcs_test.go, internal/lang/funcs/number.go, internal/lang/funcs/number_test.go, internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/node_resource_validate.go
You can't deal with marks in a function without also dealing with unknowns. If `AllowMarked` is true, but `AllowKnown` is not, the caller will short-circuit evaluation with an unknown, without being able to deal with marks from all arguments. The cty package can't guarantee that an unknown value contains all possible marks (some functions could alter marks based on the value), but it definitely helps to catch unexpected marks as early as possible during evaluation.
=> Functions that allow marks must also deal with unknown values

CODEOWNERS
Make the Education team (shared) codeowners of the docs on the website so that they can approve docs-only PRs as well. We don't need to be gatekeepers for those kinds of changes.
=> github: Update CODEOWNERS

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum, internal/terraform/context_plan_ephemeral_test.go
The go-cty `main` branch contains improved handling of marks when combined with unknown arguments in function calls.
This allows us to enable the remaining ephemeral tests in the terraform package.
=> update go-cty to improve support for marks with unknown function arguments

README.md
The logo displayed in the README is outdated, with an older color scheme and an earlier version of HashiCorp Sans. This PR updates it to the current version of the Terraform logo.
See https://github.com/bschaatsbergen/terraform/tree/r/fix-logo for an example of the new render.
=> logo: update to new design

.github/workflows/main.yml
The primary backporting workflow involves us labeling a PR _prior_ to merging it, which then triggers the backport assistant.
Sometimes we can forget to add the label and backporting then becomes more manual and tedious process.
This PR intends to allow us to run the BA whenever a PR is labeled - typically an already closed/merged PR.
I originally thought this would bring a conflict where PRs are created _before_ the PR is merged and perhaps even duplicated but after some brief testing in a private fork I believe the BA can handle this just fine.
=> github: Enable backporting closed PRs

internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go
Fixes #35983
1.9.9
-  Simplify config generation (`plan -generate-config-out`) for string attributes that contain primitive types (e.g. numbers or booleans)
=> Fix overly-eager jsonencode

website/docs/language/stacks/reference/tfstack.mdx
Quick fix to address the fact that [Stacks can support private registry modules.](https://hashicorp.slack.com/archives/C04A1FQ1543/p1731064167010569)
=> Fix to include private registry modules

internal/lang/funcs/sensitive.go, internal/lang/funcs/sensitive_test.go
Terraform attempts to track marks as accurately as possible, but unknown values may not always have the same marks as they will when they become known. This is most easily seen with functions, which are allowed to return an unknown value when faced with any unknown arguments, while they are also allowed to manipulate the marks on the values as they see fit. This results in situations where the marks simply cannot be known.
Terraform generally takes the stance that if an unknown has a mark, it will remain in the final value, but the absence of a mark is not indicative of the absence of any marks in the final value. That appears to be something we can continue to maintain throughout the codebase, so given that axiom I'm going to codify it here by only changing the `issensitive` results for …
=> `issensitive` must return unknown for unknown args without `sensitive`

website/docs/language/upgrade-guides/index.mdx
There isn't much to mention give that we aren't introducing any major breaking changes. I opted to mention the one core-related change and omitted backend changes as we usually do (AFAICT).
=> docs: Add upgrade guide for 1.10

.github/actions/equivalence-test/action.yml, .github/workflows/equivalence-test-diff.yml, .github/workflows/equivalence-test-manual-update.yml, .github/workflows/equivalence-test-update.yml
This PR fixes all the syntax errors in my first attempt at this.
=> Fix equivalence test actions

website/docs/cli/commands/providers/schema.mdx
This is a follow-up docs addition to https://github.com/hashicorp/terraform/pull/35800
=> docs/cli/providers: Document ephemeral resource schemas

website/docs/language/backend/index.mdx
This PR addresses a minor typo in the documentation. The word "infrastruture" has been corrected to "infrastructure" to ensure clarity and accuracy.
=> Fix typo: correct "infrastruture" to "infrastructure"

website/docs/language/functions/trimprefix.mdx, website/docs/language/functions/trimsuffix.mdx
The doc was not so clear if the suffix was removed multiple times. There is a difference in behavior to `trim`. The documentation is clarified with this MR.
1.10.x
- Clarify single-removal behavior in `trimsuffix` and `trimprefix` docs
=> Clarify single-removal behavior in `trimsuffix` and `trimprefix` docs

website/docs/language/expressions/version-constraints.mdx
Our docs platform automatically adds links to words at the beginning of a list item when the words are formatted with code backticks.  And because links are automatically style with an underline, the < character becomes underlined, which changes the meaning. This PR changes the list of operators you can use to constrain versions into a table, which omits the  autogenerated links. 
I also made some content updates for compliance with our writing style guidelines. 
Fixes #32423
Backports for all versions going back to 1.1.
=> Fix for incorrect rendering of > as ≥ in version constraints

website/docs/language/upgrade-guides/index.mdx
This includes sections on the introduction of S3 native state locking and the removal of deprecated root level attributes related to role assumption which have been replaced by the `assume_role` block.
Relates #35721
Relates #35661
1.10.0
=> backend/s3: upgrade guide notes for Terraform 1.10

website/docs/cli/install/yum.mdx, website/docs/language/stacks/reference/tfstacks-cli.mdx
Closes #35979 
In Fedora Linux 41 which uses DNF5, backward compatibility with DNF4 was intentionally broken. The `dnf config-manager` now uses new sub-commands, like `addrepo`, for adding repositories.
Since F41 is the latest supported Fedora Linux release, this PR proposes updating the instructions to reflect DNF5 installation.
* See https://github.com/rpm-software-management/dnf5/issues/405 which states the maintainers broke DNF4 backwards compatibility intentionally in DNF5.
* See for a cross-reference documentation fix in the Fedora docs: https://pagure.io/fedora-docs/quick-docs/pull-request/783
=> docs: update `dnf config-manager` usage

website/docs/language/tests/mocking.mdx
It's been 3 minor versions since we introduced mocking and we haven't received feedback that it missed the mark dramatically. It's time to move it out of beta.
I should have done this earlier in the release cycle, but since it's just a docs change hopefully that is okay.
=> Move mocking framework out of beta for 1.10

internal/providercache/package_install.go
An [interim solution](https://github.com/hashicorp/terraform/issues/29349#issuecomment-899881338) to lack of credential while downloading provider archives.
Fixes #29349 
1.10.x
-  Provider installation now support NetRC and utilises the credentials configured in `.netrc` file. Similar to module downloads.
=> feat: add NetRC support to the provider installer

internal/command/jsonplan/plan.go
This PR updates the ordering of the relevant attribute field in the `jsonplan` output so that is deterministic. This helps with some of our testing, but also just ensures stable outputs going forward.
=> jsonplan: deterministic relevant attribute order

internal/command/jsonplan/plan.go
Fixes a typo that meant the wrong list was being sorted.
=> jsonplan: sort the relevant attributes in the correct plan

website/docs/language/expressions/types.mdx
This PR adds a section to the Types list of the terraform docs. On this page, it wasn't explained on how lists and tuples differ. As seen in the documentation of the [`tolist`](https://developer.hashicorp.com/terraform/language/functions/tolist) function, they do clearly have a difference.
1.10.x
- Added the differences between tuples and lists to the [Types](https://developer.hashicorp.com/terraform/language/expressions/types#lists-tuples) documentation
=> feat(types.mdx): add hint for difference of tuples and lists

website/docs/language/stacks/use-cases.mdx
The PR updates the region references for the deployments in the stacks in the Use cases section of stacks.
=> docs: stacks region references in cross region/account deployments

internal/getmodules/getter.go, website/docs/language/modules/sources.mdx
Closes #36080
Our documentation suggests that file with the `tar.bz2`, `tar.tbz2` and `tbz2` extension can be fetched, unpacked and used as modules—however `tbz2` is currently not supported.
In [go-getter](https://github.com/hashicorp/go-getter) there is a decompressor for tar archives compressed with bzip2 that can handle both  `tar.bz2`, `tar.tbz2` and `tbz2` files. See https://github.com/hashicorp/go-getter/blob/main/decompress_tbz2.go#L28-L48
This PR adds
- Support for decompressing `tbz2` files, enabling the unpacking of `tbz2` module archives
- Improves the ordering of defined go-getter getter sets.
- Updates the documentation to reflect all possible go-getter getters and decompressors we have implemented.
=> getmodules: support `tbz2` module archives

scripts/changelog.sh, scripts/version-bump.sh
This PR adds two new scripts. One updates the first line of the CHANGELOG.md file to the required version number and date. The second bumps the version number in version/VERSION.
Both of these will be called by the new release tooling when it is ready.
=> Add changelog and version scripts to automate releases

website/docs/language/functions/ephemeralasnull.mdx, website/docs/language/functions/terraform-applying.mdx, website/docs/language/resources/ephemeral.mdx, website/docs/language/resources/provisioners/connection.mdx, website/docs/language/resources/provisioners/syntax.mdx, website/docs/language/state/sensitive-data.mdx, website/docs/language/values/locals.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Removing all the beta tags from ephemeral values. Just getting this set up early so we are all ready to go when 1.10 GAs!
=> [Do not merge] Remove the beta notice on all ephemeral values

internal/lang/funcs/filesystem.go, internal/lang/funcs/filesystem_test.go
manual backport of #36118
-----
While the evaluator can deal with unknown template variables, if the entire map of variables is unknown, we can't create the map and need to short-circuit the call.
Fixes https://github.com/hashicorp/terraform/issues/36110
=> v1.10 backport of #36118

internal/terraform/context_apply_deferred_test.go, internal/terraform/node_resource_validate.go
Import blocks with for_each were intended to require resource blocks with a matching expansion. This validation however did not take place in prior releases, and configurations with this mismatch currently exist in production.
That simple validation also does not take into account a single resource instance inside of an expanded module, which is a valid use case and harder to check for at the point of validation. That will still fail correctly during plan if the targets are not available.
We can skip this validation for now, and work on generating static validation errors later on if possible, taking into account the expanded module case.
Fixes #36111
=> relax import for_each validation

website/docs/language/backend/s3.mdx
Follow up to #35661
It is believed that authorization to the [`*.tflock`](https://github.com/hashicorp/terraform/blob/v1.10.0/internal/backend/remote-state/s3/backend_state.go#L30-L31) is required to use [`use_lockfile`](https://developer.hashicorp.com/terraform/language/backend/s3#use_lockfile)
But it was not mentioned in the documentation, so I added it.
=> Docs: Added necessary permission for `use_lockfile` at s3 backend

website/data/language-nav-data.json, website/docs/language/upgrade-guides/index.mdx
This PR updates the sidebar in the docs to correctly say 1.10.
Also, users with an S3 backend must run `terraform init -reconfigure` due to the removal of deprecated fields. The upgrade guide now says this.
Fixes #36150
1.10.x
=> 1.10 upgrade guide: sidebar update and -reconfigure callout

internal/terraform/node_resource_abstract_instance.go
These logs were added to help diagnose issues with providers transitioning to post-0.12 terraform. Now that all providers have been using the new protocol for considerable time, we no longer see questions about behavior that the logs help explain. Since legitimate external updates also show up in these warnings, the logs are only extra noise or at least redundant with the actual legacy SDK warnings.
=> remove old warnings about changes from refresh

docs/architecture.md
Fixes a link in the docs/architecture.md file that otherwise would link to http://localhost:8080/github.com/hashicorp/terraform/internal/configs/configload%5D
_"Saving the world, one character at a time"_
N/A
N/A
=> Remove square bracket from end of hyperlink in docs/architecture.md

internal/backend/local/backend.go, internal/backend/remote/backend.go, internal/cloud/backend.go
While working through the docs at [docs/architecture.md
](https://github.com/hashicorp/terraform/blob/main/docs/architecture.md) I realised that the backend package has some old comments that predate when the backend.Enhanced interface was replaced in https://github.com/hashicorp/terraform/pull/34818.
This PR:
- Updates old comments
- Adds a missing check that the Local backend implements the new interface `backendrun.OperationsBackend`
N/A
N/A
=> Update comments about Backend interface implementation, add implementation assertion

internal/command/views/hook_json_test.go, internal/command/views/hook_ui_test.go
This aims to eliminate the failures of a handful of tests I've seen failing lately just because `time.Sleep` takes longer to "wake up" than the declared _minimum_ time period.
As per [official docs](https://pkg.go.dev/time#Sleep):
> Sleep pauses the current goroutine for **_at least_** the duration d.
=> command/views: Fix flaky hook tests

internal/addrs/module_call.go, internal/addrs/module_call_test.go
The end-goal is to retrieve ConfigOutputValues for References. This ties in with the work on deprecated outputs.
Fixes #
1.11.x
-
=> addrs: ModuleCallOutput to ConfigOutputValue translation

CODEOWNERS
I'm trying to standardize who has permission to merge docs PRs across all our code repos. Please let me know if you have feedback; Thank you! 
Fixes #
1.11.x
-
=> Let the web presence team approve PRs to the website directory

.github/ISSUE_TEMPLATE/bug_report.yml
As LLM tools are increasingly used as a code development assistance tool, it will be helpful to have the information of how configurations are generated. This can be used to give feedback to the toolmakers regarding hallucinations.
=> Add LLM info request to the bug report form

website/docs/language/values/variables.mdx
The allowed use cases for ephemeral variables was left out of the ephemeral variables page. Copied the corresponding lines from ephemeral resources.
=> missing ephemeral variable docs

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
This just updates the go-cty dependency to a tagged release. There were no functional changes from the sha which was previously pinned, only additional unit tests were added.
=> update go-cty to a tagged release

internal/terraform/transform_destroy_edge.go
The design of Terraform inherently can create cycles for replacement across providers, and the interim solution was to simply check for any cycles and skip these dependencies. Checking the entire graph for cycles after each edge is added was bit silly, but doesn't pose any problems for most configurations. This is quadratic though, so extremely large numbers of interdependent replacement ops may slow down to the point of making a plan impossible.
While we don't have a solution for configuring the provider out of band, or quickly checking the provider dependencies as noted in the FIXME, we can do nearly the same thing just by making sure our `from` node isn't already an ancestor of the `to` node, essentially preemptively checking for the cycle.
See #31857 for an explanation of the cycle …
=> core: simplify cycle check for inter-provider deps

internal/plans/changes.go, internal/plans/changes_test.go
Terraform always attempts to generate a plan even when encountering an error, so we need to ensure that all plan elements have valid values to store and inspect later. Ensuring that `Changes.Encode` always returns a valid value avoids the need for nil checks elsewhere while returning an error to the user.
Fixes #36209
=> encoding of changes should always return a value

website/docs/language/backend/s3.mdx
Bucket and key were inconsistent with the doc content
Fixes #
1.11.x
-
=> Update sample bucket names on s3.mdx

internal/plugin6/convert/diagnostics_test.go, internal/plugin6/convert/schema.go, internal/plugin6/convert/schema_test.go
Nested structural attributes were missing write-only flags when converted to and from the wire protocol. Nested objects like this are only supported in proto v6.
=> convert write-only structural attrs to and from protobuf

.github/workflows/build.yml
This PR updates the `build` action so that on pushes to branches, it only triggers after the `Quick Checks` action. We then check that if the event type was `workflow_run`, we'll only trigger if the quick checks were successful.
This should ensure that we only build on pushes where the unit tests are passing. Pushes to tags, or direct builds via workflow_dispatch should continue working as before.
Closes hashicorp/terraform-releases#133
=> releases: trigger the build action only after the unit tests

internal/backend/local/backend_apply.go, internal/command/views/json/diagnostic.go, internal/terraform/eval_context_builtin.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_validate.go, internal/terraform/reduce_plan_test.go, internal/tfdiags/format.go
This is a change requested by the Hashicorp Support team.
=> logging: add trace statements when changes are ignored

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
Update go-cty to include latest type conversion bug fixes.
Fixes #36247
1.10.4
-  type conversion: Fix bug where empty map conversions were returning incomplete type information.
=> Update go-cty to 1.16.0

CODEOWNERS
I can't merge this [backport PR](https://github.com/hashicorp/terraform/pull/36264) because the codeowners of this branch isn't up to date with the codeowners of our main branch.
This PR pulls the following changes into our v1.10:
- https://github.com/hashicorp/terraform/pull/36000
- https://github.com/hashicorp/terraform/pull/35988
- https://github.com/hashicorp/terraform/pull/35971
=> backport all latest changes to the codeowners into v1.10

internal/command/views/modules.go, internal/moduleref/record.go, internal/moduleref/resolver.go, internal/moduleref/resolver_test.go
This should avoid the flakiness of underlying tests as exhibited recently in https://github.com/hashicorp/terraform/actions/runs/12633442691/job/35199838982?pr=36267#step:6:81
=> cmd/modules: Ensure modules are sorted by reference key

internal/repl/format.go, internal/repl/format_test.go
We now check if a value has an ephemeral mark before trying to format it. The check prevents us from passing a marked value to go-cty's AsString function, which leads to a crash.
Fixes #36261
1.10.x
I believe this could be backported?
-  Fix Terraform Console crash when printing ephemeral values
=> Fix `terraform console` crash for ephemeral values

internal/command/jsonformat/computed/renderers/write_only.go, internal/command/jsonformat/differ/attribute.go, internal/command/jsonformat/differ/block.go, internal/command/jsonformat/differ/differ_test.go, internal/command/jsonformat/differ/object.go, internal/command/jsonformat/plan_test.go
Fixes [TF-18619](https://hashicorp.atlassian.net/browse/TF-18619)
1.11.x
-  
[TF-18619]: https://hashicorp.atlassian.net/browse/TF-18619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ephemeral: render write-only attributes in plan UI

internal/grpcwrap/provider.go, internal/stacks/stackruntime/internal/stackeval/client_capabilities.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_validate.go
=> refactoring: standardize client capabilities

.changes/unreleased/NEW FEATURES-20250107-125354.yaml
I noticed that we missed adding a changelog entry for this in the past.
Fixes #
1.11.x
=> add changelog entry for write-only attributes

.changes/unreleased/ENHANCEMENTS-20250108-113433.yaml, CHANGELOG.md, internal/command/test_test.go, internal/command/testdata/test/mocking-error/child/main.tf, internal/command/testdata/test/mocking-error/main.tf, internal/command/testdata/test/mocking-error/tests/plan_mocked_overridden.tftest.hcl, internal/command/testdata/test/mocking-error/tests/plan_mocked_provider.tftest.hcl, internal/command/testdata/test/mocking-invalid/tests/override_computed_invalid_boolean.tftest.hcl, internal/command/testdata/test/mocking/tests/plan_mocked_overridden.tftest.hcl, internal/command/testdata/test/mocking/tests/plan_mocked_provider.tftest.hcl, internal/command/testdata/test/mocking/tests/plan_mocked_provider_overridden.tftest.hcl, internal/command/testdata/test/mocking/tests/primary_mocked_overridden.tftest.hcl, internal/configs/mock_provider.go, internal/moduletest/eval_context.go, internal/moduletest/mocking/values.go, internal/moduletest/mocking/values_test.go, internal/providers/mock.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
Fixes https://github.com/hashicorp/terraform/issues/35851
This PR enables users to use mocked or overridden values when running a plan command. The attribute `override_during` can be set to plan or apply. This attribute can be set in the blocks for `override_*`, and `mock_provider`.
1.11.0
-
=> terraform test: allow computed/mocked values override during planning

.changes/unreleased/ENHANCEMENTS-20250108-104335.yaml, internal/lang/ephemeral/validate.go, internal/refactoring/cross_provider_move.go, internal/terraform/context_apply_ephemeral_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_import.go, internal/terraform/node_resource_plan_instance.go
Responding to internal feedback about how the error messages don't indicate which RPC type is triggering the error
TODO:
1.11.x
=> Use different summaries and details when reporting errors about non-null write-only attribute values

CHANGELOG.md, go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
Dependency update from go-slug to upstream latest adjustments.
1.11.x
- Upstream latest adjustments in go-slug into terraform
=> Upgraded github.com/hashicorp/go-slug v0.16.0 => v0.16.3

internal/tfdiags/format.go, internal/tfdiags/format_test.go
While working on https://github.com/hashicorp/terraform/pull/36267 we discussed that ephemeral values are currently implemented as _hidden_ in other places in the codebase.
This PR aligns the behaviour in `CompactValueStr` with the rest of the codebase and also adds a test case for the function.
1.11.x
=> Hide ephemeral values in diagnostics output

.changes/unreleased/BUG FIXES-20250108-173554.yaml
Changes how the changelog is affected by the linked PR #36273
Including a change file because it addresses a CVE, and we've historically included CVE fixes in changelogs, e.g. : https://github.com/hashicorp/terraform/blob/v1.9/CHANGELOG.md
1.11.x
=> Add change file for #36273

.changes/unreleased/ENHANCEMENTS-20250110-134832.yaml, internal/providers/testing/provider_mock.go, internal/terraform/context_apply_ephemeral_test.go, internal/terraform/context_plan2_test.go, internal/terraform/upgrade_resource_state.go
This PR add validation to ensure providers don't return values for write-only attributes during UpgradeResourceState. Terraform core doesn't know if a provider has been updated since the last time the state was updated, and this RPC allows providers to upgrade state to match any schema changes for a particular resource.
The relevant changes for WO attributes are:
1) A field has been changed to become write-only
2) A field has changed to stop being write-only
In case number 2 there is no concern. The state will contain `null` from when the field was write-only, and then the provider may return a new non-null value on state upgrade.
For case number 1 we don't want a value to be returned to TF core. That is what this PR's changes protects against.
1.11.x
This change is for a feature that is …
=> Validate write-only attributes returned from providers during the UpgradeResourceState RPC 

internal/command/test_test.go, internal/command/testdata/test/mocking/tests/mocks/data.tfmock.hcl, internal/command/testdata/test/mocking/tests/primary_mocked_external.tftest.hcl, internal/configs/config_build_test.go, internal/configs/configload/loader_load.go, internal/configs/mock_provider.go, internal/configs/parser_config.go, internal/configs/parser_config_dir.go, internal/configs/provider.go, internal/configs/test_file.go, internal/providers/mock.go, internal/terraform/node_resource_abstract_instance.go
This is a quick follow up to #36227. We're extending the same functionality to the `mock_resource` and `mock_data` blocks that wasn't included in the last PR.
There's a small refactor to compute the `override_during` value at the provider level instead of at the mock_data level. This means we can also use the value defined on the provider if we're loading mock data from external sources. In addition, the refactor lets us get rid of the boolean pointer fields that I found confusing. Now, the functions all require a default value that can be provided by the source value at the provider level.
=> test: also allow mock_data and mock_resource blocks to generate data during planning

.changes/unreleased/NEW FEATURES-20250115-110818.yaml, internal/command/arguments/test.go, internal/command/arguments/test_test.go, internal/command/test.go
This PR promotes the `-junit-xml` flag and JUnit output from `terraform test` out of experimental status.
Documentation changes for this are in another PR: https://github.com/hashicorp/terraform/pull/36307
1.11.x
=> Promote JUnit output 'terraform test' feature from experimental status, make incompatibility with remote test execution explicit via flag validation

internal/configs/configschema/implied_type.go, internal/configs/configschema/implied_type_test.go, internal/configs/configschema/write_only.go, internal/configs/configschema/write_only_test.go, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_abstract_instance.go
1.11.x
WriteOnly attributes are still pre-release.
=> fix: Allow WriteOnly attributes to require replacement

.changes/unreleased/ENHANCEMENTS-20250108-104335.yaml
This change log entry isn't needed, and instead of deleting it from the generated changelog content we're removing the file. This will allow the changelog to be re-generated correctly.
Addresses https://github.com/hashicorp/terraform/pull/36328#discussion_r1916672632
=> Remove unneeded change file from v1.11 release branch

.changes/experiments.md
Cherrypicking 24583e7f9575f407b1c3f5ea44872fea2260709e from main into the release branch
=> Remove all experiments, and EXPERIMENTS section

.changes/experiments.md
Reverts hashicorp/terraform#36329 while also ensuring JUnit-related work is removed from experiments
=> Revert "Remove all experiments, and EXPERIMENTS section"

website/data/language-nav-data.json, website/docs/language/functions/terraform-applying.mdx, website/docs/language/resources/ephemeral/index.mdx, website/docs/language/resources/ephemeral/reference.mdx, website/docs/language/resources/ephemeral/write-only.mdx, website/docs/language/values/outputs.mdx, website/docs/language/values/variables.mdx
Rough outline for the TF 1.11 beta release - I don't have a working code snippet, so this is pretty vague based off what I gleaned from the PRDs. I would absolutely **love any feedback** on making this more concrete!
1.11.x (Beta)
=> Beta outline for write-only fields

.changes/unreleased/ENHANCEMENTS-20250115-084326.yaml, website/docs/language/tests/index.mdx
This just does the meta/adminy parts of the community PR #36185. I think it's easier for me to liaise with the internal docs team than it is for the community, and this is quite a complicated concept being introduced.
This should only be merged after the linked community PR.
=> docs: add docs and changelog for new terraform test state key attribute

CHANGELOG.md
Adds a missing change log entry to upstream/v1.11 to indicate that S3 native state locking is moving out of experimental to GA.
=> changelog: mark S3-native state locking as GA

internal/command/test_test.go
This change protects against the JUnit `terraform test` feature accidentally becoming experimental again.
1.11.x
=> Make test fail if the JUnit `terraform test` feature is experimental

CHANGELOG.md
Last update to the CHANGELOG before releasing 1.11-beta1.
These changes include running `./scripts/changelog.sh generate beta` which pulled in new change files from .changie/unreleased. We also needed to stop the automation from deleting a direct edit that was made to the CHANGELOG file and didn't have a matching change file.
We need to discuss processes around this, but we're likely to want change files to be the only source of truth in future.
=> Update CHANGELOG.md using new Changie automation

website/docs/language/stacks/reference/tfstack.mdx
The docs for the variant of the `output` block available in tfstack configurations were wrong — here's the fix.
To verify the schema for yourself, check its definition at the bottom of `internal/stacks/stackconfig/output_value.go` in this repo. (I also ran an experiment to make sure, and yep: sensitive is supported as optional, and type is mandatory.)
Q for education team reviewers: which branch is the [web version of these docs](https://developer.hashicorp.com/terraform/language/stacks/reference/tfstack#output-block-configuration) sourced from? Does it come straight out of main? 
1.11.x
=> Update the docs for tfstack config output blocks

.github/workflows/changelog.yml
This PR warns the user if they a) miss a changelog entry, b) miscategorize a changelog entry, c) the changelog has been manually edited outside a release.
It creates / updates / deletes a comment on the PR.
Fixes #
1.11.x
=> build github action to verify changelog entries have been added

CHANGELOG.md
Fixes the changelog for v1.11
This has already been added to the changelog for v1.10
I've also removed this from the v1.11.0-beta1 release notes
1.11.x
=> Remove `modules -json` entry from v1.11 changelog

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/testdata/mainbundle/test/removed-offline/child/child.tf, internal/stacks/stackruntime/testdata/mainbundle/test/removed-offline/parent/parent.tf, internal/stacks/stackruntime/testdata/mainbundle/test/removed-offline/removed-offline.tfstack.hcl
An assumption was made in Stacks that unknown variables should not be available at all during apply operations. This assumption was not true - we can have unknown values during refresh, destroy and deferred operations.
This PR removes the part of Stacks that was skipping components that found unknown variables - this was causing endless loops of undestroyable configuration in practice. 
This PR also updates the part where variables are loaded for components to allow a specific error to result in a completely unapplyable component. This is the case where a variable has changed between the plan and apply operations. Previously, this was resulting in an unknown value that was just leaving the component to be skipped. Now, we aren't skipping that component anymore so we need to find a way to …
=> stacks: allow unknown variables during apply operations

docs/debugging.md
fixed a typo and changed all lower case delve to Delve since thats how delve them selfs write it
Fixes #
1.11.x
=> Small docu typo fixes in debugging.md

.changes/backported/BUG FIXES-20250108-173554.yaml, CHANGELOG.md
We want the security fix to be released in v1.10 instead of v1.11. This has all been made to happen in https://github.com/hashicorp/terraform/pull/36375 and https://github.com/hashicorp/terraform/pull/36377. The last thing is that because the CHANGELOG entry is going into v1.10 we should remove it from v1.11 as well.
=> remove go-slug upgrade from v1.11 changelog

.changes/backported/BUG FIXES-20250122-082755.yaml, .changes/backported/BUG FIXES-20250122-110052.yaml, go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
Update to the latest patch release of go-cty. As this is a patch release that contains only bug fixes we should be safe to backport to 1.10 to fix the underlying issue there as well.
Fixes #36369 
Fixes #36351 
1.10.x
=> update go-cty to latest patch release

.changes/backported/BUG FIXES-20250122-082755.yaml, .changes/backported/BUG FIXES-20250122-110052.yaml, go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
This is a manual backport of #36376.
Failed automated backport: #36380
=> backport of update go-cty to latest patch release

internal/command/junit/junit.go, internal/command/junit/junit_internal_test.go, internal/command/testdata/test/junit-output/1pass-1fail/expected-output.xml, internal/command/testdata/test/junit-output/1pass-1fail/main.tftest.hcl
This PR
- 1) Updates the `message` attribute on a `<failure>` element to summarise how many assertions are failing out of a given total, and includes the first failed assertion's error message.
- This is a remaining piece of feedback on the JUnit test report shared in the Discuss forum: https://discuss.hashicorp.com/t/request-for-feedback-on-terraform-test-junit-xml-output/62307/16?u=sarah.french
- 2) Moves the rendering of the failured message diag into the <failure> element's body
- This matches [the docs for Azure Devops's use of JUnit XML format](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=junit%2Ctrxattachments%2Cyaml)
- This also matches feedback in [this message from the Discuss forum …
=> Change JUnit `terraform test` output to include test failure details inside `<failure>` elements, use the error message as the `message` attribute

website/docs/cli/commands/test.mdx
This PR updated docs for the `-junit-xml` flag and JUnit output from `terraform test, accompanying that feature leaving experimental status.
See: https://github.com/hashicorp/terraform/pull/36324
1.11.x
Changelog not needed/falls under the changelog entry for https://github.com/hashicorp/terraform/pull/36324
=> Add documentation for JUnit output from 'terraform test'

internal/command/junit/junit.go, internal/command/junit/junit_internal_test.go, internal/tfdiags/diagnostics.go, internal/tfdiags/diagnostics_test.go
Closes #36387
This change adds a new method to the `tfdiags` API: `Warnings` returns a new [Diagnostics](https://pkg.go.dev/github.com/hashicorp/terraform/tfdiags#Diagnostics) list containing only diagnostics with a severity of Warning.
This simplifies iterating over a list of diagnostics by a Warning severity:
```
if diags.HasWarnings() {
for _, v := range diags.Warnings() {
}
}
```
Instead of
```
if diags.HasWarnings() {
for _, diag := range diags {
if diag.Severity() == Warning {
}
}
}
```
It also replaces the existing `getWarnings` function in the `junit` package, which served as a reference for this implementation. Nice work on the `DiagnosticComparer` @SarahFrench!
=> tfdiags: Add Warnings method to filter by severity

.changes/unreleased/BUG FIXES-20250123-150746.yaml, internal/terraform/context_plan2_test.go, internal/terraform/node_resource_plan_orphan.go
The order of operations was incorrect here, with the refresh happening after the plan was already created. Invert the calls so the updated state is reflected in the plan output.
We don't need to carry forward the defer response from refresh, since in the rare case that a read does need to be deferred, the PlanResourceChange call will return the same response.
Fixes #35568
1.11.x
=> orphaned resources must be refreshed before plan

scripts/changelog.sh
Small adjustment to make sure we habe the `## 1.X.X (Unreleased)` line even if patch releases already exist on the branch.
Fixes #
1.11.x
=> changelog: handle dev releases without changes on non-empty changelogs

.github/workflows/changelog.yml
Currently the GHA that prompts for users to add a change file or label a PR as not user-facing will fail on PRs raised from forked repos, due to 403 errors when trying to post a comment to the PR. This is because [the GITHUB_TOKEN made in that context](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) will not include write permissions to pull requests.
Examples of 403 errors resulting from this:
- https://github.com/hashicorp/terraform/actions/runs/13140859146/job/36711885284
- https://github.com/hashicorp/terraform/actions/runs/13151146235/job/36698675615
We cannot save a token as a secret in this repo to be used by PRs from forked repos, as secrets (and variables) are not not passed to the …
=> Update changelog.yml so there are necessary permissions to run on PRs from forked repos

.changes/backported/BUG FIXES-20250205-36435.yaml, internal/backend/local/backend_apply.go, internal/command/apply_test.go, internal/command/testdata/apply-output-only/main.tf
Fixes #36410
It turns out the ordering of variable source evaluation is correct, it's just the diagnostic message that is wrong due to mixed ordering of arguments to `fmt.Sprintf`.
While the original report in #36410 suggests overriding variables via environment variables to be silently ignored, I think we cannot just make the same argument as was made in https://github.com/hashicorp/terraform/pull/36180
Specifically - We cannot expect users to be deleting autoloadable tfvars files. I do think it's reasonable to expect them to unset environment variables between plan and apply. Also, more importantly we only raise the diagnostic when values differ anyway.
That said after some consideration I chose to propose a warning that is still somewhat ignorable, just possibly noisy. I believe that …
=> Fix diagnostic & avoid variable override via environment

.github/workflows/build.yml
We haven't been building the correct branches recently because we've just been checking out whatever `main` is for all the `build` actions.
This updates the build action to work out the correct branch based on the method the build action was triggered.
=> Update build action to build correct branch

internal/command/arguments/test.go, internal/command/arguments/test_test.go
Don't set default parallelism for cloud runs. This would just cause the API to upload a parallelism value of `DefaultParallelism`. The cloud run will eventually trigger a local run that would use the default if unset.
1.11.x
=> Don't set default parallelism for cloud runs

CODEOWNERS
Adjusting codeowner permissions to get the terraform education team access to:
- website/
- data/
- docs/
- img/docs
- README.md
=> Add terraform education to the docs and README

.changes/backported/BUG FIXES-20250206-145217.yaml, internal/backend/backendbase/base.go, internal/backend/backendbase/base_test.go
This PR fixes a crash that affects all remote state backends that implement the `backendbase.Base`. When interrupting (Ctrl+c) during Terraform's interactive value prompt, we convert the resulting unknown value to a null value. 
Our generic `PrepareConfig` wasn't prepared to handle nulls and crashed when applying the sdk-like defaults.
Fixes #36420
1.11.x
=> backends: Fix crash when interrupting during interactive prompt for values'

.changes/unreleased/BUG FIXES-20250210-163038.yaml, internal/lang/format/format.go, internal/lang/marks/paths.go, internal/moduletest/mocking/values.go, internal/moduletest/mocking/values_test.go, internal/states/instance_object.go, internal/states/instance_object_test.go, internal/terraform/node_resource_abstract_instance.go, internal/tfdiags/config_traversals.go
Sensitive paths in a resource instance value were not serialized in a consistent order, which could cause comparison of the state to erroneously indicate a change. While the UI would not report any changes to the user because the states were functionally the same, the machine readable outputs, like the plan `applyable' field and the detailed exitcode would indicate that the plan was not empty.
The canonical user-readable version of a cty.Path is was created by the tfdiags package, but in order to reuse this everywhere we need, the formatting function needs to be split out to it's own package. This PR creates the `lang/format` package, delegates the `tfgdiags` format functions to the new package, then replaces any other `fmt.Sprintf` formatting of `cty.Path` I could find with the new more …
=> Serialize `AttrSensitivePaths` in a consistent order

website/docs/language/functions/format.mdx
PR adds one more example to the [format function examples](https://developer.hashicorp.com/terraform/language/functions/format#examples).
It aims to clarify [Specification Syntax](https://developer.hashicorp.com/terraform/language/functions/format#specification-syntax) and how to use argument position number.
<details>
<summary>screenshot</summary>
</details>
Fixes #24469
=> Update format function docs examples

internal/moduletest/graph/transform_state_cleanup.go
Fixes flakiness for the `TestTest_LongRunningTestJSON ` test as seen in https://github.com/hashicorp/terraform/actions/runs/13268393627/job/37041624584
You can test this locally by setting count to a large number and running the test many times
```
go test -timeout 600s -run ^TestTest_LongRunningTestJSON$ github.com/hashicorp/terraform/internal/command -count 30
```
1.11.x
=> Ensure that the file teardown summary is displayed before the run's teardown summary

internal/backend/remote/backend_common.go, internal/cloud/backend_common.go, internal/command/jsonformat/plan_test.go, internal/command/views/operation.go, internal/lang/funcs/collection.go, internal/lang/funcs/crypto.go, internal/legacy/helper/schema/shims_test.go, internal/plans/objchange/compatible.go, internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go, internal/rpcapi/dependencies.go
This is in preparation for https://github.com/hashicorp/terraform/pull/36478
I'm making it a separate PR to ease review and also to make it easier to back-port (without having to backport Go upgrade) as it highlighted some valid issues that aren't 1.24 specific.
1.11.x
=> Address `go vet` 1.24 failures

CODEOWNERS
Inspired by #36458, that PR made me realize that we currently have a situation where a PR that updates a state backend and its corresponding docs page, it would require an approved review from someone other than the backend maintainer team because the docs pages are currently co-owned only by the Terraform Core team and Education. It seems appropriate to me to make the backend maintainer teams co-owners as well, so that they have the ability to merge these PRs independently.
n/a
=> Make backend maintainers co-owners of their docs pages

.github/workflows/changelog.yml
This is to prevent issues such as https://github.com/hashicorp/terraform/pull/36496 or rather surface them as part of the PR before they reach a point of release.
I also think that changie installation in CI should be handled by the official GHA and updated on demand but that's a separate concern for another PR.
1.11.x
=> github/changelog: Dry-run `changie merge` & mention `changie new`

.changes/unreleased/ENHANCEMENTS-20250207-164803.yaml, go.mod, go.sum, internal/backend/remote-state/azure/backend.go, internal/backend/remote-state/azure/backend_test.go, internal/backend/remote-state/azure/client_test.go, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/azure/helpers_test.go, website/docs/language/backend/azurerm.mdx
This PR updates the `hashicorp/go-azure-sdk` to version `v0.20250131.1134653`, for the azure backend. The main reason for this update is to support ADO Pipelines OIDC auth via OIDC Request Token + URL + Service Connection ID, which will refresh the OIDC token if expired.
More context can be found at:
- https://github.com/hashicorp/terraform/issues/35664#issuecomment-2639122595
- https://github.com/hashicorp/terraform/issues/34322#issuecomment-2564937829
Fixes #35664
1.11.x
```yml
name: Backend unit test
on: [workflow_dispatch]
permissions:
id-token: write
contents: read
jobs:
setup-and-test:
runs-on: ubuntu-latest
steps:
- name: 'Checkout terraform repo'
uses: actions/checkout@v4
with:
repository: 'magodo/terraform'
ref: 'backend/azure/update_sdk_v0.20250131.1134653'
- name: 'Setup Go' …
```
=> Backend/azure: Update go-azure-sdk version to v0.20250131.1134653

website/docs/language/stacks/deploy/conditions.mdx, website/docs/language/stacks/deploy/config.mdx, website/docs/language/stacks/reference/tfdeploy.mdx
* Updated `auto_approve` example which referenced a plan condition check, but had `no component changes` details.
* Ran tfstacks fmt on config examples.
* Updated the providers variable to reference the var name defined.
* `development`  to `deployment` in a location.
1.11.x
=> docs: fixed orchestration example, variables

internal/configs/configschema/marks.go, internal/configs/configschema/write_only.go, internal/configs/configschema/write_only_test.go, internal/lang/ephemeral/validate.go, internal/lang/ephemeral/validate_test.go, internal/refactoring/cross_provider_move.go, internal/refactoring/mock_provider.go, internal/terraform/context_plan2_test.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/context_test.go, internal/terraform/node_resource_validate.go
This cleans up some validation problems with write-only attributes, which would produce confusing errors, or allow write-only attributes to be stored in the state.
The first validation which failed was if an ephemeral value ended up in a nested object which cannot be directly declared as write-only. The diagnostic would only state `Could not find schema for attribute`, so we can rewrite that to better indicate that an ephemeral value was inappropriately assigned, and where it was assigned to.
`ValidateWriteOnlyAttributes` did not properly descent through nested blocks and structural attributes, and would allow invalid values to be returned from the provider. The schema already contains code to walk a value in conjunction with its schema,`WriteOnlyPaths`, which should allow us to directly …
=> Fix validation of values against schemas with write-only attributes

.github/workflows/changelog.yml
This is to address the failure shown in https://github.com/hashicorp/terraform/actions/runs/13308340454/job/37164401027
1.11.x
=> fix: ensure changie config is available for dry-run

.github/workflows/changelog.yml
This is an attempt to fix failure reported in https://github.com/hashicorp/terraform/actions/runs/13333888743/job/37244515892?pr=36496#step:4:56
1.11.x
=> github: fix ref variable in configuration

.github/workflows/changelog.yml
For some reason the merging doesn't actually seem to do anything - or at least does not trigger the failure unless we also attempt to update the changelog via `-u`. It looks like a changie bug to me but this is a simple enough work around.
Hopefully this is the last commit to make the check finally work 🙈 
1.11.x
=> github: Ensure changie merge actually fails

.github/workflows/changelog.yml
This is how I feel about GitHub Actions and the PR based debugging experience by now:
Worth noting I did test this inside our private fork, so 🤞🏻 there should be no more PRs needed.
1.11.x
=> github: Ensure the `.changes` dir is included for checking

.changes/unreleased/ENHANCEMENTS-20250206-162053.yaml, .changes/unreleased/ENHANCEMENTS-20250206-34969.yaml
This prevents a problem we came across in the last alpha release:
```
Error: unmarshaling change file '.changes/unreleased/ENHANCEMENTS-20250206-162053.yaml': yaml: line 2: mapping values are not allowed in this context
```
As far as I can tell, `changie new` does actually do the escaping, which implies the file was not generated by changie or some version of it that didn't do the escaping? 🤔 
I will also propose some updates to our release automation to try to highlight this problem earlier.
1.11.x
=> changes: Fix escaping in changelog entry

.github/pull_request_template.md
Given that we've released release candidates for 1.11 and made an alpha release for 1.12 I figured that updating this template to default to 1.12 makes sense.
N/A
=> Update pull_request_template.md to default to 1.12.x

internal/command/test_test.go, internal/command/testdata/test/no_state/main.tf, internal/command/testdata/test/no_state/main.tftest.hcl, internal/moduletest/graph/node_state_cleanup.go
If the state is empty, it may be nil, and we need to check that before cleanup
1.11.0
=> No state to cleaup when it is empty

.github/CONTRIBUTING.md
A follow up to https://github.com/hashicorp/terraform/pull/36463
N/A
=> Add details about changelog processes to the contributing guide

.changes/v1.11/ENHANCEMENTS-20250219-094101.yaml, internal/backend/remote-state/oss/backend.go, website/docs/language/backend/oss.mdx
Terraform State OSS Backend uses Alibaba Cloud Tablestore to store state lock. There needs setting an instance name when putting lock data. Before, the instance name defaults to parsing from argument `tablestore_endpoint`, but it will not work when it is a VPC endpoint. This PR provides a new argument tablestore_instance_name explicitly the instance name to meet 
VPC access scenario.
1.11.x
- `backend/oss`: Adds new arguement tablestore_instance_name used to VPC scenario
=> backend/oss: Add new argument `tablestore_instance_name` used in VPC context

.changes/v1.11/BUG FIXES-20250206-155025.yaml, internal/cloud/backend_apply.go, internal/cloud/backend_apply_test.go
This PR does a manual backport of https://github.com/hashicorp/terraform/pull/36453 since the backport assistant failed
It seems a bit unusual that https://github.com/hashicorp/terraform/commit/166434811e797299a320c4c679c72287fe70fc2b is a merge commit, and I hope that backporting it will not cause any problems. I picked 857d18830828888f545e253804d34187a4bb9692 as the parent during cherry picking
1.11.x
=> Backport of "Fix: Saved plan apply hangs with `-auto-approve` flag using cloud backend"

internal/configs/configschema/marks.go, internal/configs/configschema/marks_test.go, internal/configs/configschema/write_only.go, internal/configs/configschema/write_only_test.go, internal/terraform/context_apply2_test.go
There were 2 remaining incorrect tests for `WriteOnlyPaths` which traversed a null value (and of course, the code to make those tests pass ;) ). While we can _return_ a path to a null value, we cannot return a path which traverses a null value, because that path cannot be applied.
Fixes #36538
=> `WriteOnlyPaths` cannot traverse null values

website/package-lock.json
This PR updates these dependencies to resolve some flagged security issues:
* cross-spawn 7.0.3 => 7.0.6, [contains more changes](https://github.com/moxystudio/node-cross-spawn/compare/v7.0.3...v7.0.6) as the jump is more patches, but looks ok
* ws: 7.5.9 => 7.5.10, [contains only the fix](https://github.com/websockets/ws/compare/7.5.9...7.5.10) for the issue
* nanoid : 3.3.7 => 3.3.8, [contains only the fix ](https://github.com/ai/nanoid/compare/3.3.7...3.3.8) for the issue
`npm audit` before: 
> 52 vulnerabilities (37 moderate, 14 high, 1 critical)
`npm audit` after: 
> 49 vulnerabilities (36 moderate, 12 high, 1 critical)
To try and make review easier I've updated these dependencies directly, instead of running a mass `npm audit fix`. If there's a better or preferable approach please …
=> Update website dependencies: ws, cross-spawn, nanoid

website/package-lock.json
Addresses a security issue: https://nvd.nist.gov/vuln/detail/cve-2023-45133
`npm audit` before:
> 52 vulnerabilities (37 moderate, 14 high, 1 critical)
`npm audit` after:
> 51 vulnerabilities (37 moderate, 14 high)
To try and keep the footprint of this PR low, I attempted to only update the affected package via `npm update @babel/traverse` but there are lots of interrelated dependencies that are affected; I'd like a review from the Web Presence team!
---
Used:
- Node v20.13.0
- npm v10.5.2
N/A
=> Update babel-related dependencies in website/ directory

.github/workflows/checks.yml
Fixes the errors we see in GHAs like this:
It looks like [v4 of the actions/go-setup GHA](https://github.com/actions/setup-go?tab=readme-ov-file#v4) enables caching by default, so when the action was updated to use a v4+ version of that action it started clashing with actions/cache.
This PR removes use of actions/cache and instead uses the caching features of go-setup. Internally this uses the same logic ([actions/cache is used](https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs)) but requires fewer inputs.
This matches what's already done in the equivalence test workflows, so a cache will be shared between more GHA workflows after this PR.
N/A
=> Remove use of `actions/cache`, which conflicts with caching done by `actions/setup-go`

.changes/v1.11/BUG FIXES-20250225-083056.yaml, go.mod
EvalSymlinks and Readlink on Windows used to return incorrect information for windows junctions which were specifically not symlinks prior to go1.23. Unfortunately Terraform uses `EvalSymlinks` in situations where Windows users had come to expect their configuration to work as if it were symlinked even though it used a different filesystem structure. Set `winsymlink=0` to restore the existing behavior until we can determine the best course of action for Windows users.
Fixes #36545
Fixes #36357
=> temporarily disable updated Go Windows symlink behavior

website/package-lock.json, website/package.json
This PR updates `next` from 14.0.4 => 14.2.24.
`next` is outdated:
```
% npm outdated   
Package                  Current   Wanted  Latest  Location                              Depended by
@hashicorp/platform-cli    2.7.3    2.8.0   2.8.0  node_modules/@hashicorp/platform-cli  website
next                      14.0.4  14.2.24  15.1.7  node_modules/next                     website
```
...and it's also getting flagged in audit:
```
% npm audit
...
next  9.5.5 - 14.2.20
Severity: high
Next.js Server-Side Request Forgery in Server Actions - https://github.com/advisories/GHSA-fr5h-rqp8-mj6g
Next.js Cache Poisoning - https://github.com/advisories/GHSA-gp8f-8m3g-qvj9
Denial of Service condition in Next.js image optimization - https://github.com/advisories/GHSA-g77x-44xx-532m
Next.js …
```
=> Update `next` dependency in website/

docs/plugin-protocol/README.md
Documenting the process for updating the protocol - thanks to @dbanck for help with the process around symlinks!
N/A
=> Add documentation describing how to update the plugin protocol

.changes/v1.11/BUG FIXES-20250226-181429.yaml, go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.sum, internal/legacy/go.sum
Pulls in the CVE fix introduced in v0.27.0: https://github.com/golang/oauth2/releases/tag/v0.27.0
When [comparing v0.23.0 to v0.27.0](https://github.com/golang/oauth2/compare/v0.23.0...v0.27.0) the only [functional change is this CVE fix](https://github.com/golang/oauth2/commit/681b4d8edca1bcfea5bce685d77ea7b82ed3e7b3); all other changes are to docs or code comments.
1.11.1
=> Bump golang.org/x/oauth2 from v0.23.0 to v0.27.0

go.mod, go.sum
Pulling in this vulnerability fix:
- https://github.com/hashicorp/cli/pull/6
1.11.1
=> Update `hashicorp/cli` dependency

.changes/v1.11/BUG FIXES-20250303-125722.yaml, internal/lang/funcs/collection.go, internal/lang/funcs/collection_test.go
=> lang/funcs/transpose: Avoid crash due to map with `null` values

.github/workflows/build.yml
Stop trying to get the build action to execute only if the unit tests pass.
Chaining actions together isn't as straightforward as it feels like it should be, and getting it to trigger at the right time and to build the right branch isn't coming together in a nice way. The relatively minor gains we get from this don't make up for risking releasing the wrong build or missing a failing build because it didn't execute.
=> build: always build on successful pushes rather than waiting for tests

.changes/v1.11/BUG FIXES-20250226-140931.yaml, internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/unapplyable-plan/main.tf, internal/command/testdata/test/unapplyable-plan/main.tftest.hcl
This fixes a crash in 1.11 branch that occurs when a run block in a test file fails due to a non-applyable plan. It later tries to deference the null state and crashes. This was already fixed in `main` during a larger refactor in which the actual crash wasn't detected, so I'm pushing directly to 1.11.
We shouldn't merge this until after the 1.11.0 release happens later this week, with the target release for this PR being 1.11.1 next week.
I will forward port the test that was added here so we don't accidentally cause a regression in main.
Fixes #
1.11.1
=> terraform test: fix crash when non-applyable plans are applied

internal/command/test_test.go, internal/command/testdata/test/unapplyable-plan/main.tf, internal/command/testdata/test/unapplyable-plan/main.tftest.hcl
Add a test for an already fixed crash to avoid regressions in the future. See also: https://github.com/hashicorp/terraform/pull/36582
Fixes #
1.12.x
=> Add test case to ensure no regression of already fixed crash

.changes/v1.12/ENHANCEMENTS-20250303-151031.yaml, internal/command/views/hook_ui.go, internal/command/views/hook_ui_test.go
This PR improves the elapsed time display in the UI Hook by changing it from seconds-only to a more readable mm:ss format.
Previously, elapsed time was displayed in seconds only, making it hard to interpret for longer durations. Now, it follows the 00m00s format, making it more user-friendly.
This improvement directly addresses [Issue #36368](https://github.com/hashicorp/terraform/issues/36368), which requests better readability for elapsed time display.
Main Changes:
Added separate calculations for minutes and seconds.
Updated the display string format to include mm:ss.
Kept the existing rounding logic for time calculations.
now:
before:
Fixes #36368
1.12.x
=> Enhance elapsed time display in UI Hook with minutes and seconds

.changes/v1.12/BUG FIXES-20250226-171815.yaml, internal/backend/local/backend_plan.go, internal/backend/remote-state/s3/backend_test.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/node_resource_plan_partialexp.go, internal/terraform/node_resource_validate.go, internal/terraform/terraform_test.go, internal/tfdiags/compare.go, internal/tfdiags/compare_test.go, internal/tfdiags/contextual.go, internal/tfdiags/diagnostic.go, internal/tfdiags/diagnostic_base.go, internal/tfdiags/diagnostics.go, internal/tfdiags/hcl.go, internal/tfdiags/rpc_friendly.go
Currently, some warning diagnostics, such as the following are being duplicated during `terraform plan`
```
Plan: 2 to add, 0 to change, 0 to destroy.
╷
│ Warning: Available Write-only Attribute Alternative
│
│   with aws_db_instance.test,
│   on main.tf line 30, in resource "aws_db_instance" "test":
│   30:   password            = random_password.password.result
│
│ The attribute password has a write-only alternative password_wo available. Use the write-only alternative of the attribute when possible.
│
│ (and one more similar warning elsewhere)
╵
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take …
```
=> fix: Avoid duplicated warnings

.changes/v1.12/BUG FIXES-20250310-093153.yaml, internal/lang/funcs/string.go, internal/lang/funcs/string_test.go
Fixes #36652 
When a string interpolation contains only one expression sequence, HCL optimizes by wrapping and directly delegating evaluation to that expression. The `templatestring` function tries to refine the expression value as non-null, and if null, this refinement leads to a panic. For compatibility reasons, HCL has to continue to support this unwrapping logic ([See attempted PR](https://github.com/hashicorp/hcl/pull/736)), thus we will simply return an error in `templatestring` when the single evaluated expression is null
1.12.x
=> Return error when the template's single interpolation results in null value

.changes/v1.12/BUG FIXES-20250310-100230.yaml, internal/plans/objchange/objchange.go, internal/plans/objchange/objchange_test.go, internal/terraform/context_plan2_test.go
While the proposed plan value for managed resource is only a suggestion for providers, deferred data sources must be completely planed by core, and hence set appropriate unknown values. We do this by creating an entirely unknown prior value to plan against, which will be used to fill in any `null` `computed` attributes when generating the proposed new value. There were a couple combinations of nested types where we need to specifically check for and handle unknown in the prior value to translate that "unknown-ness" to what would be an unknown value extracted from an unknown container.
Fixes #36653
=> Check for nested computed values in all structural types when planning data sources

website/docs/language/resources/provisioners/syntax.mdx
The docs link to https://github.com/hashicorp/terraform/issues/13549 which was closed. Gathering anything relevant or of use from that ~100 comment long issue thread is not a particularly useful endeavor, so given that the information is true and not likely to be changed, simply removing the issue link and leaving the warning.
=> Remove irrelevant link to issue.

internal/command/jsonprovider/attribute.go, internal/command/jsonprovider/attribute_test.go, internal/command/jsonprovider/provider.go, internal/command/jsonprovider/provider_test.go, internal/command/jsonprovider/schema.go
This PR updates the `terraform providers schema --json` command to include the resource identity schemas.
1.12.x
=> Marshall resource identity schemas in `jsonprovider` (TF-23824)

internal/stacks/stackconfig/config_test.go, internal/stacks/stackconfig/removed.go, internal/stacks/stackconfig/testdata/basics-bundle/errored/main.tfstack.hcl, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/removed.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-component-instance-direct/removed-component-instance-direct.tfstack.hcl
This is part of the work addressing feedback for the `removed` block in Stacks.
Currently, we were assuming that the `for_each` attribute was always being copied directly into the key of the `from` attribute. This isn't necessarily true - there's a test case that has been added that demonstrates this.
This PR updates the Stacks internals to differentiate between the "instance key" of a removed block (which is the output of the for_each evaluation) and the instance key of the address in the from attribute. The each attribute needs to be mentioned in the from attribute, but it doesn't have to be a 1:1 mapping. Previously, we would just check the instance key for direct matches between instances in state, components and removed blocks. Now, we actively check the from attribute of the removed …
=> stacks: fix errors processing index keys of removed blocks

.changes/v1.11/BUG FIXES-20250311-104640.yaml, internal/backend/remote-state/azure/api_client.go, internal/backend/remote-state/azure/backend.go, internal/backend/remote-state/azure/backend_test.go, internal/backend/remote-state/azure/storage_client_helpers.go
This is a manual backport of https://github.com/hashicorp/terraform/pull/36623, since the automatic one failed (in https://github.com/hashicorp/terraform/pull/36676)
1.11.2
=> Backport of Backend/azure: subscription_id infer from Azure CLI & a way to skip *unnecessary* management plane API call into v1.11

.changes/v1.12/BUG FIXES-20250310-100230.yaml
We haven't actually released deferred changes yet, so we don't need to do a CHANGELOG entry for bug fixes affecting only them.
@jbardin - did this affect any behaviour outside of deferred changes? If so, we should reword the changelog instead of deleting it. But, if it's only deferred changes then we don't need this at all.
=> Delete .changes/v1.12/BUG FIXES-20250310-100230.yaml

go.mod, go.sum, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/go.sum, internal/backend/remote-state/consul/go.mod, internal/backend/remote-state/consul/go.sum, internal/backend/remote-state/cos/go.mod, internal/backend/remote-state/cos/go.sum, internal/backend/remote-state/gcs/go.mod, internal/backend/remote-state/gcs/go.sum, internal/backend/remote-state/kubernetes/go.mod, internal/backend/remote-state/kubernetes/go.sum, internal/backend/remote-state/oss/go.mod, internal/backend/remote-state/oss/go.sum, internal/backend/remote-state/pg/go.mod, internal/backend/remote-state/pg/go.sum, internal/backend/remote-state/s3/go.mod, internal/backend/remote-state/s3/go.sum, internal/legacy/go.mod, internal/legacy/go.sum
Replaces https://github.com/hashicorp/terraform/pull/36690
Replaces https://github.com/hashicorp/terraform/pull/36689
/x/crypto also is updated from 0.33.0 to 0.35.0 : https://github.com/golang/crypto/compare/v0.33.0...v0.35.0
1.11.x
=> Bump `golang.org/x/net` to v0.36.0

website/docs/language/resources/ephemeral/write-only.mdx
Add Azure examples to write-only arguments!
[Updated to store and retrieve the wo-arg now!]
=> Add Azure example

website/docs/language/backend/azurerm.mdx
This is a manual backport of https://github.com/hashicorp/terraform/pull/36641 into v1.11, since the auto-generated one (https://github.com/hashicorp/terraform/pull/36699) failed.
=> Backport of docs: azurerm backend updates for 1.11 release into v1.11

commands.go, internal/command/command_test.go, internal/command/state_identities.go, internal/command/state_identities_test.go, internal/command/testdata/state-identities-backend-default/.terraform/terraform.tfstate, internal/command/testdata/state-identities-backend-default/main.tf, internal/command/testdata/state-identities-backend-default/terraform.tfstate, internal/command/testdata/state-identities-nested-modules/terraform.tfstate
This allows listing the identities in state via `terraform state identities`. All options that apply to `terraform state list` also apply here.
Example output:
1.12.x
=> CLI command for listing state identities

internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/local_value_config.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/output_value_config.go, internal/stacks/stackruntime/internal/stackeval/stack_call_config.go, internal/stacks/stackruntime/testdata/mainbundle/test/validate-cyclic-dependency/validate-cyclic-dependency.tfstack.hcl, internal/stacks/stackruntime/validate_test.go
Before this PR, circular references between components were never caught during validation, but during plan/apply. In plan/apply, the promises resolving some of those tasks are un-named, thus resulting in a lot of generic reference error messages in the diagnostics. e.g  `The following items in your configuration form a circular dependency chain through their references: │ - (...) │ - (...) │ - (...)`.
This PR detects the cycles when validating the component configuration itself, allowing us to display better error messages, and also not proceed to planning of invalid configuration
1.12.x
=> Detect circular references during Validation

website/docs/language/functions/issensitive.mdx
Example with variable as argument was using `sensitive()` instead of `issensitive()`.
1.12.x
1.8.x-backport
=> Update issensitive.mdx - Fixed function name typo

internal/communicator/ssh/http_proxy.go
Incase of error, the response from net/HTTP ReadResponse is always nil and no need to close the Body.
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x103e5bf00]
goroutine 1847 [running]:
github.com/hashicorp/terraform/internal/communicator/ssh.(*proxyDialer).Dial(0x140017fddc0, {0x103f1cf9a?, 0x1060351c0?}, {0x14000709600, 0xf})
github.com/hashicorp/terraform/internal/communicator/ssh/http_proxy.go:103 +0x520
github.com/hashicorp/terraform/internal/communicator/ssh.newHttpProxyConn(0x14000ef30b0, {0x14000709600, 0xf})
github.com/hashicorp/terraform/internal/communicator/ssh/http_proxy.go:148 +0xd0
github.com/hashicorp/terraform/internal/communicator/ssh.prepareSSHConfig.ConnectFunc.func1() …
```
=> Fix panic in proxyDialer

website/docs/language/functions/element.mdx
element function support negative index starting in version 1.10.0, but documentation still says that it doesn't support it.
1.12.x
=> fix element function documentation

.changes/v1.12/ENHANCEMENTS-20250318-001121.yaml, internal/cloud/backend_plan.go
I've updated the legacy term `Terraform Cloud agent` to `HCP Terraform Agent`, which was used in error messages.
1.12.x
=> update legacy term: Terraform Cloud agent => HCP Terraform Agent

internal/command/test_test.go
Replaces new test state get/set helpers with preexisting ones
1.12.x
=> Replace state get/set functions with existing helpers

.github/workflows/checks.yml
Updating GHAs on the v1.9 branch, as once they get too out of date the GHAs no longer run when you backport changes to that release branch:
=> Update .github/workflows/checks.yml on v1.9 to roughly match main branch

.github/workflows/checks.yml, Makefile
Updating GHAs on the v1.8 branch, as once they get too out of date the GHAs no longer run when you backport changes to that release branch:
=> Update .github/workflows/checks.yml on v1.8 to roughly match main branch

internal/configs/configload/loader_load_test.go, internal/initwd/from_module_test.go, internal/initwd/module_install_test.go, internal/terraform/context_apply2_test.go, internal/terraform/context_apply_checks_test.go, internal/terraform/context_apply_deferred_test.go, internal/terraform/context_apply_ephemeral_test.go, internal/terraform/context_apply_identity_test.go, internal/terraform/context_apply_test.go, internal/terraform/context_eval_test.go, internal/terraform/context_functions_test.go, internal/terraform/context_input_test.go, internal/terraform/context_plan2_test.go, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/context_plan_identity_test.go, internal/terraform/context_plan_test.go, internal/terraform/context_refresh_test.go, internal/terraform/context_test.go, internal/terraform/context_validate_test.go, internal/terraform/eval_for_each_test.go, internal/terraform/transform_destroy_edge_test.go, internal/terraform/transform_reference_test.go, internal/tfdiags/testing.go
Moves these functions into testing.go in the tfdiags package:
* AssertNoDiagnostics
* AssertDiagnosticCount
* AssertNoErrors 
* LogDiagnostics
Removes implementations of these functions from other packages
Refactors existing tests to use the new helpers in tfdiags
N/A
=> Migrate more testing helpers into tfdiags package

internal/backend/local/backend_test.go
This PR adds some more test coverage to the local backend's backend.Backend methods and behaviours storing state.
These tests are being pulled out of https://github.com/hashicorp/terraform/pull/36718
1.12.x
=> Add test coverage for `local` backend's backend.Backend methods and behaviours

internal/backend/local/backend.go, internal/backend/local/backend_test.go
Related to https://github.com/hashicorp/terraform/pull/36750
This PR:
* Increases testing of the local backend's PathsConflictWith method
* Increases testing of the related StatePaths method
---
[PathsConflictWith](https://github.com/hashicorp/terraform/blob/052646c3d207619dc8005f81c32b097280743e8a/internal/backend/local/backend.go#L436-L463) is used to detect if two local backends use state in the same file locations.
It is used to help avoid a situation where migration from one local backend configuration to another results in clashes and possible data loss. I.e. a situation where Terraform wants to move State from location A to location A, instead of from location A to B.
**CLI overrides like `-state`, `-state-out` and `-state-backup` aren't relevant to migrations, as those flags …
=> Increase test coverage for local backend's PathsConflictWith and StatePaths methods

website/package-lock.json, website/package.json
Addresses https://nvd.nist.gov/vuln/detail/CVE-2025-29927
I updated to this new version based on guidance in https://github.com/hashicorp/terraform/security/code-scanning/927
Before and after for npm audit:
48 vulnerabilities (36 moderate, 11 high, 1 critical)
47 vulnerabilities (36 moderate, 11 high)
1.12.x
=> Update Next.js dependency

internal/terraform/instance_expanders.go, internal/terraform/node_check.go, internal/terraform/node_local.go, internal/terraform/node_module_expand.go, internal/terraform/node_module_variable.go, internal/terraform/node_output.go, internal/terraform/node_resource_apply.go, internal/terraform/node_resource_plan.go
Forgot to remove `graphNodeTemporaryValue` when the `pruneUnusedNodesTransformer` was simplified to no longer make use of it.
=> remove unused interface

internal/plugin/grpc_provider.go, internal/plugin6/grpc_provider.go
> cc @dbanck 
This PR fixes a panic in the most recent `v1.12.0-alpha20250319` release with resource identity when using a protocol v6 provider (protocol v5 seems to be working fine, which was what I was testing on until recently 😆).
My repro-case isn't readily available, but basically any plan/apply cycle with a resource that returns identity will give you this panic on the following refresh.
<details>
<summary><b>Crash output</b></summary>
```bash
--- FAIL: TestExpectIdentityValue_CheckState_String (0.42s)
/Users/austin.valle/code/terraform-plugin-testing/statecheck/expect_identity_value_test.go:56: Step 1/1 error: Error running post-apply refresh plan: exit status 11
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of …
```
=> Fix protov6 crash when refreshing resource with identity

.changes/v1.11/BUG FIXES-20250327-094612.yaml, go.mod
Disable kyber globally in core. This primarily affects the S3 backend, since the only reported incompatible system was the AWS firewall, and the AWS provider has chosen to disable this option as well. https://github.com/hashicorp/terraform-provider-aws/pull/41740. 
There could be other incompatible networks out there still however, and since the X25519Kyber768Draft00 was removed in go1.24, we can just disable it for v1.11 and move on.
v1.11
=> disable tls kyber KEX

internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_config.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/expression_refs.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/input_variable_config.go, internal/stacks/stackruntime/internal/stackeval/local_value.go, internal/stacks/stackruntime/internal/stackeval/local_value_config.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/output_value.go, internal/stacks/stackruntime/internal/stackeval/output_value_config.go, internal/stacks/stackruntime/internal/stackeval/output_value_test.go, internal/stacks/stackruntime/internal/stackeval/provider.go, internal/stacks/stackruntime/internal/stackeval/provider_config.go, internal/stacks/stackruntime/internal/stackeval/provider_config_test.go, internal/stacks/stackruntime/internal/stackeval/provider_expressions.go, internal/stacks/stackruntime/internal/stackeval/provider_instance.go, internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go, internal/stacks/stackruntime/internal/stackeval/removed.go, internal/stacks/stackruntime/internal/stackeval/removed_config.go, internal/stacks/stackruntime/internal/stackeval/removed_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_config.go, internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
This PR is a refactoring of the Stacks runtime. No expected behaviour change as a result of these changes.
Previously, nodes in the stacks runtime were created with a single link back to the `main` object. From the main object they could then search for the stack instance the nodes were linked to. However, the nodes are all created from inside the stack they want to link back to. I found this reverse look up very confusing.
After this PR, nodes in the runtime accept both the stack and the configuration they are linked to directly in their constructor. This information is simply always available to them, removing the need for the lookups. I think it is easier to reason about each node and where it lives in the stack with this information made available up front. In addition, we can now …
=> stacks: provide stack and config on component creation

website/docs/cli/config/config-file.mdx
=> docs: Correct wording in CLI configuration page

internal/providers/testing/provider_mock.go
As far as I can tell, all the impacted methods need to basically enable mocking of _all_ type names, so the field doesn't seem relevant and it appears it was never used.
Introduced initially as part of a bigger PR https://github.com/hashicorp/terraform/pull/27805 and then accidentally copy pasted in other PRs for other purposes.
1.12.x
=> providers/testing: Remove unused `*TypeName` fields

internal/command/import.go, internal/command/views/hook_ui.go, internal/configs/import.go, internal/configs/import_test.go, internal/plans/changes.go, internal/plans/changes_src.go, internal/states/instance_object.go, internal/states/state_deepcopy.go, internal/terraform/context_apply2_test.go, internal/terraform/context_import.go, internal/terraform/context_import_test.go, internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go, internal/terraform/hook.go, internal/terraform/hook_mock.go, internal/terraform/hook_stop.go, internal/terraform/hook_test.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_validate.go, internal/terraform/testdata/import-identity-module/child/main.tf, internal/terraform/testdata/import-identity-module/main.tf, internal/tfdiags/object.go, internal/tfdiags/object_test.go
This PR adds support for importing resources via their identity
1.12.x
I'm planning to add changelog entries for the whole feature in a separate PR
=> Config-driven importing through identity (TF-23179)

.changes/v1.11/BUG FIXES-20250402-143931.yaml, internal/command/test_test.go, internal/command/testdata/test/write-only-attributes-mocked/main.tf, internal/command/testdata/test/write-only-attributes-mocked/main.tftest.hcl, internal/command/testdata/test/write-only-attributes-overridden/main.tf, internal/command/testdata/test/write-only-attributes-overridden/main.tftest.hcl, internal/command/testdata/test/write-only-attributes/main.tf, internal/command/testdata/test/write-only-attributes/main.tftest.hcl, internal/command/testing/test_provider.go, internal/lang/ephemeral/strip.go, internal/lang/ephemeral/strip_test.go, internal/lang/ephemeral/validate.go, internal/lang/ephemeral/validate_test.go, internal/providers/mock.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go, internal/stacks/stackruntime/testing/resource.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
We have several internal providers that wrap external providers and override functionality. These providers must handle setting write-only attributes to null automatically as Terraform expects this.
The mock provider in the testing framework, the unknown provider in stacks, and the override_resource functionality in the testing framework are all fixed in this PR.
Fixes #36819 
Target release: v1.11.4
=>  write-only attributes: internal providers should set write-only attributes to null

internal/builtin/providers/terraform/provider.go
These 'bugs' are not user facing, as any invalid managed resource/data resource/ephemeral resource are caught due to that resource type not being present in the provider schema ([for example, here](https://github.com/hashicorp/terraform/blob/87cdcc350e9ba1e764898d9f0ec29644775bbe9b/internal/terraform/node_resource_ephemeral.go#L43-L52)).
However this code is wrong- the Append method doesn't mutate the Diagnostics collection. The returned value always needs to be assigned back to where the collection is stored.
1.13.x
=> Fix non-user facing bugs where appended diags are not returned in `terraform` provider

internal/command/test_test.go, internal/command/testdata/test/skip_cleanup/main.tf, internal/command/testdata/test/skip_cleanup/main.tftest.hcl, internal/command/testdata/test/skip_file_cleanup/main.tf, internal/command/testdata/test/skip_file_cleanup/main.tftest.hcl, internal/command/views/test.go, internal/command/views/test_test.go, internal/configs/test_file.go, internal/moduletest/graph/node_state_cleanup.go, internal/moduletest/graph/transform_state_cleanup.go, internal/moduletest/graph/transform_test_run.go, internal/moduletest/graph/wait.go
Implements `skip_cleanup`, which allows skipping the cleanup of individual run blocks or the entire test file. This simply ensures that the cleanup stage for the state is an apply of the run requesting the skip, instead of the normal destroy
1.12.x
=> Terraform Test: Allow skipping cleanup of entire test file or individual run blocks

internal/stacks/stackaddrs/in_stack.go, internal/stacks/stackplan/plan.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/removed_component.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/deferred-embedded-stack-for-each/deferred-embedded-stack-for-each.tfstack.hcl, internal/stacks/stackstate/state.go
Currently, components in nested stacks are just ignored during the plan when the nested stack call is deferred.
This PR updates the stacks runtime so a deferred stack call still triggers deferred updates of any components in the nested stack that already exist.
=> stacks: include existing components when deferring nested stacks

.changes/v1.11/BUG FIXES-20250402-143931.yaml, internal/command/test_test.go, internal/command/testdata/test/write-only-attributes-mocked/main.tf, internal/command/testdata/test/write-only-attributes-mocked/main.tftest.hcl, internal/command/testdata/test/write-only-attributes-overridden/main.tf, internal/command/testdata/test/write-only-attributes-overridden/main.tftest.hcl, internal/command/testdata/test/write-only-attributes/main.tf, internal/command/testdata/test/write-only-attributes/main.tftest.hcl, internal/command/testing/test_provider.go, internal/lang/ephemeral/strip.go, internal/lang/ephemeral/strip_test.go, internal/lang/ephemeral/validate.go, internal/lang/ephemeral/validate_test.go, internal/providers/mock.go, internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tf, internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tfstack.hcl, internal/stacks/stackruntime/testing/provider.go, internal/stacks/stackruntime/testing/resource.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go
Manual backport of https://github.com/hashicorp/terraform/pull/36824
Automatic backport failed in https://github.com/hashicorp/terraform/pull/36826
=> backport of write-only attributes: internal providers should set write-only attributes to null

website/docs/language/expressions/operators.mdx
I was reading the changelog for the beta1 of 1.12 and noticed this entry:
> Logical binary operators can now short-circuit
This PR removes the callout in our docs that state that this is not supported
Related to #36224
1.12.0
=> Remove paragraph that logical operators do not short-circuit for 1.12

internal/command/testdata/push-backend-new/main.tf
Removes a test fixture that's not referenced in any test. I found this while investigating usage of the `inmem` backend
Also, the `atlas` block suggests it's been outdated for a while!
1.13.x
=> Remove unused test fixture "push-backend-new"

internal/rpcapi/stacks.go, internal/stacks/stackaddrs/removed.go, internal/stacks/stackaddrs/removed_test.go, internal/stacks/stackconfig/config.go, internal/stacks/stackconfig/declarations.go, internal/stacks/stackconfig/embedded_stack.go, internal/stacks/stackconfig/removed.go, internal/stacks/stackplan/plan.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/removed.go, internal/stacks/stackruntime/internal/stackeval/removed_component.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call_config.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_config.go, internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackruntime/internal/stackeval/walk_static.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-instance-dynamic/removed-stack-instance-dynamic.tfstack.hcl, internal/stacks/stackstate/state.go
This PR adds the concept of a `RemovedStackCall` into the stacks runtime. Essentially, a removed block can now target an entire embedded stack and mark everything inside as being removed.
To enable this, `Stack` objects now accept a `plans.Mode` as part of their constructor which the removed stack call sets to be `plans.Destroy` while regular stack calls inherit from their stack. The behaviour of the removed stack call within the stack is otherwise fairly similar.
This PR also refactors the dynamic walk logic to extract the now fairly complicated logic for handling components and embedded stacks into dedicated functions to tidy everything up a bit.
=> stacks: update removed blocks to allow targeting of embedded stacks

website/docs/language/tests/mocking.mdx
=> Fix for  #36859 in mocking.mdx

internal/command/testing/test_provider.go
I was wrestling with a test failing and I didn't realise it was because my test assumed a remote-object already existed and was readable by this test provider. Eventually I realised that using a ResourceStore would solve my problem.
The existing comments didn't call out that those resources represent pre-existing remote objects, so figured I'd add some to help discovery. 
1.13.x
=> Add comments about use of ResourceStores with TestProviders

website/docs/cli/commands/state/pull.mdx, website/docs/cli/commands/state/push.mdx
To avoid conflicts with sc.exe ([service control manager](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create)), full `Set-Content` command should be used instead of short alias `sc`.
=> Replace sc with Set-Content

internal/command/e2etest/providers_schema_test.go, internal/grpcwrap/provider.go, internal/provider-simple/provider.go
This is a change split away from a larger PR in https://github.com/hashicorp/terraform/pull/36834#discussion_r2031279359 with added tests.
TL;DR ephemeral resource schemas in v5 protocol weren't tested as thoroughly as in v6, so this PR changes that. I believe there is no end-user impact.
1.13.x
=> grpcwrap+provider-simple: Test ephemeral resource schemas in v5 protocol

internal/command/test_test.go
The `done` method reads data from stderr and stdout and can be used for assertions or logging. Here, the code was previously collecting data from stderr&stdout before the init commands were run.
Looks like this was being propagated through copy-pasting tests to make new ones, and the impact wasn't obvious as the tests were not asserting about the output from the init command.
1.13.x
=> Fix defects where `done` is called before the command's `Run` method is invoked

internal/command/test_test.go, internal/command/testdata/test/backend-with-skip-cleanup/false/main.tf, internal/command/testdata/test/backend-with-skip-cleanup/false/main.tftest.hcl, internal/command/testdata/test/backend-with-skip-cleanup/true/main.tf, internal/command/testdata/test/backend-with-skip-cleanup/true/main.tftest.hcl, internal/configs/test_file.go
(Work split out of https://github.com/hashicorp/terraform/pull/36848)
This PR:
* Adds validation to stop users setting `skip_cleanup=false` in a run block with a `backend` block
* This is because using a backend block implies  `skip_cleanup=true`
* _We could pivot to making `backend` and `skip_cleanup` mutually exclusive?_
* Adds tests for that validation, and also to show it's ok to set `skip_cleanup=true` in a run block with a `backend` block
=> Add validation to enforce skip_cleanup=false cannot be used with backends

CODEOWNERS
I believe this mostly just reflects existing practice/reality. Please do correct me if I'm wrong.
Context: I came across [a few older PRs](https://github.com/hashicorp/terraform/pulls?q=is%3Aopen+is%3Apr+label%3Abackend%2Fremote) which touched the Cloud backend in one way or another and thought that auto-assignment of reviewers would reduce the chance of such stale PRs in the future and reduce the need for manual triage.
=> CODEOWNERS: Set tf-core-cloud as owner of Cloud backend

internal/configs/configschema/implied_type.go, internal/terraform/context_plan_import_test.go, internal/terraform/eval_import.go, internal/terraform/node_resource_plan_instance.go, internal/tfdiags/object.go, internal/tfdiags/object_test.go
This PR addresses two issues when using optional attributes in an identity. We now correctly use the fully populated identity from the provider instead of the one from config.
1.12.x
=> Fix import with optional identity attributes

.changes/v1.11/BUG FIXES-20250310-093153.yaml, website/docs/language/upgrade-guides/index.mdx
=> Upgrade guide for v1.11

website/docs/language/tests/index.mdx
This PR adds documentation about the `backend` block in the context of `test` to our feature branch for the 'controlling destroys' work.
Later these diffs will be merged into main, and before then additional changes may be added, e.g. https://github.com/hashicorp/terraform/pull/36832#discussion_r2025213221
=> Add documentation for using a `backend` block during `test`

internal/rpcapi/resource_identity.go, internal/stacks/stackaddrs/stack.go, internal/stacks/stackconfig/declarations.go, internal/stacks/stackplan/from_proto.go, internal/stacks/stackplan/from_proto_test.go, internal/stacks/stackplan/plan.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/applying.go, internal/stacks/stackruntime/internal/stackeval/applying_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/main_apply.go, internal/stacks/stackruntime/internal/stackeval/planning_test.go, internal/stacks/stackruntime/internal/stackeval/removed.go, internal/stacks/stackruntime/internal/stackeval/removed_component.go, internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call_config.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackstate/state.go
This PR updates the stack plan, stack state, and removed tracking structures to store components within a nested tree structure instead of a single flat map entry.
This means we can now retrieve components by embedded stack address efficiently instead of having to iterate over the entire collection of components every time. Lookups to individual components now have to traverse the tree, but the address is still precise giving a direct map look up at every stage of the address which is still acceptable.
The removed tracking changes are similar, where instead of four flat maps of various removed blocks, the embedded blocks are now stored in a nested removed structure. This means we write the removed structure once when everything is discovered the first time, and then it can be reused in …
=> stacks: refactor plan, state, and removed tracking for efficient lookups

internal/stacks/stackplan/plan.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackstate/state.go
This PR updates the removed_stack_call functionality so a removed block that targets a stack that has already been removed from the state does not create a new stack just to claim it is being removed.
=> stacks: removing embedded stacks should ignore stacks not in state

internal/stacks/stackconfig/config.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/internal/stackeval/component.go, internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/removed.go, internal/stacks/stackruntime/internal/stackeval/removed_component.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack.go, internal/stacks/stackruntime/internal/stackeval/stack_call.go, internal/stacks/stackruntime/internal/stackeval/stack_config.go, internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/multiple-components/multiple-components.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/multiple-components/removed/removed.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/orphaned-component/orphaned-component.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-from-embedded-stack/removed-stack-from-embedded-stack.tfstack.hcl, internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-instance-dynamic/removed-stack-instance-dynamic.tfstack.hcl
This PR adds a lot of tests focusing on the removed blocks to expand test coverage. It also fixes a set of bugs found as part of the testing.
1. Updates the configuration loading to place deeply nested removed blocks into the correct part of the config tree.
2. Caches created instances of stacks and components that are created against unknown blocks instead of duplicating them leading to inconsistent results.
3. Improve the error message when a component in state is targeted by an orphaned removed block to return an error detailing what it means for a removed block to be orphaned.
=> stacks: improve test coverage for removed blocks

internal/stacks/stackconfig/config.go, internal/stacks/stackconfig/config_test.go, internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/main.tf, internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/main.tfstack.hcl, internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/subdir/main.tfstack.hcl, internal/stacks/stackconfig/testdata/basics-bundle/terraform-sources.json
This PR updates the Stack configuration loading so that it validates the source attributes of component, stack and removed blocks that target the same component or stack are the same.
=> stacks: ensure consistent sources between removed blocks

internal/stacks/stackruntime/internal/stackeval/input_variable.go, internal/stacks/stackruntime/internal/stackeval/main.go, internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go, internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go, internal/stacks/stackruntime/plan_refresh_test.go
This PR updates removed blocks in Stacks to perform refresh plans when a general refresh-only plan has been requested instead of still trying to destroy everything.
=> stacks: removed blocks should refresh during refresh plans

internal/terraform/context_apply2_test.go, internal/terraform/context_apply_identity_test.go, internal/terraform/context_plan_identity_test.go, internal/terraform/node_resource_abstract_instance.go
This PR adds a new validation that an provider-returned identity conforms to the identity schema.
1.12.x
=> Validate identity to match identity schema

internal/terraform/context_plan_import_test.go, internal/terraform/node_resource_plan_instance.go
This PR adds a check to ensure that the import RPC returns an identity when Terraform is doing an import by identity.
1.12.x
=> Validate identity in import response

.changes/v1.12/ENHANCEMENTS-20250417-182036.yaml, .changes/v1.12/ENHANCEMENTS-20250417-182215.yaml
This PR adds some basic changelog entries for the resource identity work
1.12.x
=> Add changelog entries for resource identities

CODEOWNERS
Fixes the path to the backend - the original value didn't match an existing directory.
But of course this doesn't matter as it's not an active line in the CODEOWNERS file anyway
N/A
=> Fix remote-state backend name in CODEOWNERS

internal/terraform/node_resource_abstract_instance.go
This PR fixes a crash that occurs during destroy introduced by https://github.com/hashicorp/terraform/pull/36904
1.12.x
=> Fix resource identity schema on destroy

website/docs/language/stacks/use-cases.mdx
Fix grammar: change "remains" to "remain" to match plural subject
Fixes #
v1.13
=> Fix grammar: change "remains" to "remain" to match plural subject

internal/terraform/context_plan_identity_test.go, internal/terraform/node_resource_abstract_instance.go
This PR removes two resource identity validations:
1. That an identity hasn't changed. Some resources have mutable identities, and the provider SDK can provide better safeguards and opt-out behaviour than enforcing this for every resource type in Terraform.
2. That an identity can't contain null values. Some identities need some sort of "optional" attribute, so we won't enforce that values must be non-null. This shifts some responsibility to provider authors that a resource identity is still uniquely identifiable even with null values.
1.12.x
=> Relax resource identity validation

internal/terraform/context_plan_identity_test.go, internal/terraform/node_resource_abstract_instance.go
This is a manual backport of https://github.com/hashicorp/terraform/pull/36989, because the automated one seems broken https://github.com/hashicorp/terraform/pull/36991.
=> Backport: Relax resource identity validation

website/docs/language/functions/index_function.mdx
From the documentation, I could not make up of only the index of the first occurrence is returned. By some local testing, I've verified this.
=> Emphasise "first".

website/docs/cli/commands/index.mdx, website/docs/cli/commands/plan.mdx
This PR changes mistakes in index.mdx and plan.mdx terraform docs.
Changes in the index.mdx
- Removed unnecessary comma in a compound object. Because a compound object with only two items requires no punctuation to separate them.
- Corrected the spelling of "into" as it should be one word.
- Eliminated redundant preposition "for" from the documentation.
Changes in the plan.mdx
- Removed incorrect preposition "for".
- Corrected the spelling of "configuratation" as it should be "configuration".
- Corrected the pronoun "which match" as it should be "that match".
- Added necessary commas.
- Corrected the use of incorrect form of verb "write" as it should be "writing"
=> Fix punctuation and spelling errors in Basic CLI Features and Command: plan documentation

internal/command/test_test.go
Fixing a test failure that comes from the machine running TestTest_JUnitOutput so fast that the test duration is under a second. The regex currently expects a number with a decimal in it, not scientific notation like "7.1e-05".
It's not valid to force integer values for `time` ([see use of non-integer values here](https://github.com/testmoapp/junitxml?tab=readme-ov-file#complete-junit-xml-example)), so we don't want to convert the `time` value to integers to solve the scientific notation problem.
Instead, this is a case where the test needs to be updated, not the code under test. We use a trivial test for `TestTest_JUnitOutput`, which can take less than a second to run, so triggering the test failure is due to how contrived the test scenario is.
N/A
=> Update JUnit output test to tolerate scientific notation

website/docs/language/upgrade-guides/index.mdx
I cannot think of anything note-worthy in the upgrade guide - anything that would "surprise" users because of some new behaviours. Any new stuff appears to be opt-in or the bug fixes are fixing something without any side effects as far as I can tell.
So I'm keeping just the bare minimum stuff in the guide. We can always add to it later as the website content is updated independently of releases.
1.12.x
=> Update 1.12 upgrade guide

internal/command/apply.go, website/docs/cli/commands/apply.mdx
=> include help entry for -replace

internal/stacks/stackruntime/apply_destroy_test.go, internal/stacks/stackruntime/helper_hooks_test.go, internal/stacks/stackruntime/helper_test.go, internal/stacks/stackruntime/internal/stackeval/component_instance.go, internal/stacks/stackruntime/internal/stackeval/planning.go, internal/stacks/stackruntime/internal/stackeval/refresh_instance.go, internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go
During Stacks destroy operations each component does a refresh operation before calling destroy. This was actually causing the number of resources to be double-counted by the stacks progress events as the refresh operation was triggering the pre- and post- diff hooks to be counted by Stacks.
This PR updates the stacks component planning so the hook implementations are taken out of the code shared by the refresh and planning operations, and are instead called directly by the stack graph nodes where they are needed. This ensures the destroy-refresh operation doesn't emit status updates for resources anymore.
I've added a big testing helper function to help test the stacks hooks implementation, and added a test that uses it to expose the problem fixed here. Because most of the tests share …
=> stacks: skip resource instance hooks during refresh plans

.changes/v1.13/update-cidrblock.yaml
=> update cidr in variable networks 

internal/rpcapi/stacks_test.go, internal/rpcapi/terraform1/stacks/stacks.pb.go, internal/rpcapi/terraform1/stacks/stacks.proto, internal/stacks/stackmigrate/components.go, internal/stacks/stackmigrate/migrate_test.go, internal/stacks/stackmigrate/resources.go, internal/stacks/stackplan/from_proto_test.go, internal/stacks/stackruntime/apply_test.go, internal/stacks/stackruntime/plan_test.go, internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/multiple-components/multiple-components.tf, internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/multiple-components/multiple-components.tfcomponent.hcl
This PR modifies the `resource_address_map` element of the Stacks migration RPC so that exact absolute resource addresses can be specified. Previously, only root resources could be included and they could only be mapped into components. Now, full addresses can be included on both sides of the mapping to specify exact locations.
This is based on feedback from the Migration team.
I also refactored the test file so that it reuses code with a test cases approach instead of lots of duplicated code across test cases. The existing test cases are unchanged, with one new test case added.
=> stacks migrate: allow resource mapping to include nested resources

.changes/v1.12/BUG FIXES-20250516-114251.yaml, internal/command/format/diagnostic_test.go, internal/command/views/json/diagnostic.go
=> fix: Avoid crash on test failure in BinaryOpExpr in function call

.changes/v1.12/BUG FIXES-20250514-184357.yaml, internal/providercache/package_install.go
Avoiding the new HEAD request that happens before GET request to get provider binary.
Fixes #36987
1.11.x
1.12.x
1.13.x
- `terraform init` - avoid sending a HEAD request when fetching providers
=> fix: avoid sending HEAD request on provider download

internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go
This PR adds a check if `GetResourceIdentitySchemas` returned diagnostics and returns early if there are any
1.12.1
=> Check `GetResourceIdentitySchemas` diagnostics and return early

.changes/v1.12/BUG FIXES-20250514-112152.yaml, internal/command/views/hook_ui.go, internal/command/views/hook_ui_test.go
This PR fixes the UI output during import. It now prints the identity in the pre and post apply hooks.
**Before**
**After**
1.12.1
=> Include identity in import apply UI output

website/docs/language/expressions/strings.mdx
Closes https://github.com/hashicorp/terraform/pull/35029
https://terraform-et2f4hct7-hashicorp.vercel.app/terraform/language/expressions/strings#heredoc-strings
1.13.x
=> docs: Warn about use of heredoc for JSON/YAML

internal/command/stacks.go, internal/rpcapi/stacks_grpc_client.go, internal/stacksplugin/stacksplugin1/stacks_grpc_plugin.go
Fixes #
This PR provides the ability for command interrupts to be propagated to the Stacks Plugin
This functional goes along with [this Stacks Plugin PR](https://github.com/hashicorp/terraform-stacks-cli/pull/186), and should be used for smoke testing.
1.13.x
=> Handle stacks plugin interrupts

website/docs/language/block/resource.mdx
=> fixes a few mistakes in the resource block ref

.changes/v1.13/ENHANCEMENTS-20250520-155148.yaml, internal/getproviders/package_authentication.go, internal/getproviders/registry_client.go, internal/getproviders/registry_client_test.go, internal/getproviders/registry_source.go, internal/getproviders/registry_source_test.go, internal/providercache/installer_test.go, internal/providercache/installer_test_helper.go
This makes s slight change to the `init` command, so that any version from the registry that does not conform to terraform's semver constraints is skipped, allowing the command to use other versions if present. If there is no version deemed valid, the command still appropriately gets an error, but the error would likely tell the user that the registry has no very matching the requested constraint.
1.13.x
=> Allow successful init when constraint matches at least one valid version

.github/workflows/build-terraform-cli.yml
This is a somewhat dangerous default - we didn't get alerted when cgo inputs were not being passed successfully. Let's make sure the build errors if `cgo` is not explicitly set for each matrix target.
1.4.x
=> make sure the build fails if cgo isn't being set correctly

docs/plugin-protocol/tfplugin5.proto, internal/tfplugin5/tfplugin5.pb.go
This is a no-op change that moves two definitions in `tfplugin5.proto` to match their relative location in `tfplugin6.proto`. The effect is to remove an incidental part of the text diff between the two files for easier comparison.
1.13.x
None
=> Minimize text diff between `tfplugin{5,6}.proto`

internal/moduletest/graph/apply.go, internal/moduletest/graph/plan.go, internal/moduletest/graph/variables.go
We haven't actually needed to do this since we added the extra eval context for the test framework with the "extra vars" logic: https://github.com/hashicorp/terraform/blob/d8d890f3b26cd61ec523a3cdbb58645b972be697/internal/moduletest/graph/eval_context.go#L407
When `terraform test` was launched, we were reusing the existing eval context which required any variables to be registered in the configuration. This is no longer needed as the extra test only variables are handled separately.
No changelog needed as their is no external facing change.
=> terraform test: stop transforming the config under test with new variables

.changes/v1.13/ENHANCEMENTS-20250522-093102.yaml, internal/terraform/evaluate.go
Expanded resources always require fetching all instances for evaluation, but the changes data structure requires iterating over all instances for each call to GetResourceInstanceChange, so it turns out to be an n^2 operation. This wasn't very visible in most configs with relatively few numbers of instances, but when you have a resource with a large number of instances referencing another resource with a large number of instances (e.g. the second resource uses the first as the for_each argument), you end up with (n^2)^2 lookups. Because the instance changes are in a global structure, this single point of lock contention would hold up the entire plan.
I'm going to call #26355 closed on this one. It was the last major bottleneck, and gets the performance more inline with individual instance …
=> reduce instance change lookups in GetResource

internal/logging/logging.go, internal/terraform/graph_builder.go
Graph transformations are really only interesting for developers directly working on graph transformers. Otherwise the complete graph can be printed once in the trace log for general debugging purposes. Removing the intermediate graph steps can reduce log output for large configs by many megabytes per run. On top of the volume of output, the graph string generation can cause a noticeable impact on performance with large graphs.
Developers working on terraform can set `TF_GRAPH_TRACE` to see all intermediate graph transformer steps.
=> add TF_GRAPH_TRACE to turn off graph trace output

internal/terraform/eval_for_each.go
Calling LengthInt does not require unmarking all nested values. The UnmarkDeep call causes an unnecessary deep copy, and generate lots of garbage every time a for_each collection was evaluated, which is at least once for each instance.
=> UnmarkDeep is not needed here

internal/configs/module_test.go, internal/configs/testdata/invalid-modules/conflict-cloud-backend-separate-files/backend.tf, internal/configs/testdata/invalid-modules/conflict-cloud-backend-separate-files/cloud.tf, internal/configs/testdata/invalid-modules/conflict-cloud-backend/main.tf, internal/configs/testdata/invalid-modules/multiple-backends/a.tf, internal/configs/testdata/invalid-modules/multiple-backends/b.tf, internal/configs/testdata/invalid-modules/multiple-cloud/a.tf, internal/configs/testdata/invalid-modules/multiple-cloud/b.tf, internal/configs/testdata/valid-modules/override-cloud-with-backend/main.tf, internal/configs/testdata/valid-modules/override-cloud-with-backend/override.tf
This PR adds some missing test coverage in the `configs` package (coverage goes from 76.4%  to 76.6% , lol)
This PR also includes renaming some existing tests, reordering them for consistency in the file, and adding test names.
The new tests are:
* `TestModule_backend_overrides_cloud`  - you can override a cloud block with a backend block in an override file.
* `TestModule_backend_multiple` - validation stops multiple backend blocks being present in a module.
* `TestModule_cloud_multiple`  - validation stops multiple cloud blocks being present in a module.
* `TestModule_conflicting_backend_cloud`  - validation stops a combination of cloud and backend blocks being present in a module.
N/A
Are there any changes to security controls (access controls, encryption, logging) in this pull …
=> Update and add new tests for module-parsing logic

docs/plugin-protocol/tfplugin5.proto, docs/plugin-protocol/tfplugin6.proto, internal/tfplugin5/tfplugin5.pb.go, internal/tfplugin6/tfplugin6.pb.go
This is to clarify the current reality of the `GetMetadata` method which isn't really "optional" in the way the original comment suggests.
Core does not implement this at all currently and while terraform-plugin-mux [does technically call that method](https://github.com/hashicorp/terraform-plugin-mux/blob/101e9dfd0787e782fc4d0869931716180da5df09/tf6muxserver/mux_server.go#L225), it only calls (generated) Go code within the provider which uses mux. **There is no known _RPC_ use of this at all today.**
Further/future context: We may re-assess the need for this method in the protocol in the context of a more granular access to provider schemas. Currently, it is far from ideal that schemas are received as one big blob for everything (all resources, all data sources, etc.).
1.13.x
Are there …
=> docs/plugin-protocol: Clarify use of GetMetadata

.changes/v1.13/ENHANCEMENTS-20250602-152211.yaml, .changes/v1.13/UPGRADE NOTES-20250602-152009.yaml, internal/backend/local/test.go, internal/command/test_test.go, internal/command/testdata/test/with-default-variables/main.tf, internal/command/testdata/test/with-default-variables/main.tftest.hcl, internal/configs/test_file.go, internal/moduletest/graph/eval_context.go, internal/moduletest/graph/transform_config.go, internal/moduletest/graph/variables.go, internal/moduletest/hcl/provider.go, internal/moduletest/hcl/provider_test.go, internal/moduletest/hcl/variable_cache.go, internal/moduletest/hcl/variable_cache_test.go, internal/terraform/eval_variable.go, internal/terraform/eval_variable_test.go, internal/terraform/node_module_variable.go, internal/terraform/node_root_variable.go
Currently, `terraform test` attempts to work out the type of any external variables by delaying evaluation until each run block executes so it can use the definitions within the run blocks's module. This means that the values of variables can technically change between run blocks which isn't ideal.
This commit is the first in a chain which will move the evaluation of variables into the terraform test graph. We need to give the users the option of specifying the type for external variables within the file as these variables are now going to be assessed outside of the context of a run block. To do this, we introduce the optional variable blocks that are added by this commit. The optional variable block means that users can specify the intended type of variables that should be provided …
=> terraform test: add variable definitions to test files

.changes/v1.12/BUG FIXES-20250604-131240.yaml, internal/terraform/context_plan_ephemeral_test.go, internal/terraform/node_output.go
There is currently no way to construct an output value which does not come directly from an ephemeral resource or input. Even if the constructed value is entirely composed of ephemeral attributes or elements, because there is no action to manually mark something as ephemeral (other than a variable block), the resulting value itself is not marked as ephemeral, and fails validation.
Instead of strictly checking for an ephemeral mark on the output value, we can accept any value because the result will always be entirely ephemeral anyway. This mirrors the variable block behavior, which can accept any type of value as input, but is evaluated as ephemeral.
=> allow output values without top-level ephemeral marks

.changes/v1.13/BUG FIXES-20250604-144021.yaml, internal/terraform/context_plan2_test.go, internal/terraform/evaluate.go
Sensitive marks were lost from module outputs during the namedvals rewrite. Ensure output are evaluated with sensitive marks in accordance with their configuration.
Interestingly I found that the old access point of `lang.Data.GetOutput` was not removed long ago when we fixed module evaluation overall to always access the module objects. This method however was recent [re-captured by the moduletest package](https://github.com/hashicorp/terraform/blob/f80762d3d539eeaf4c8894c3edd0d5f33aeefe60/internal/moduletest/graph/eval_context.go#L305). That code can probably be refactored to use `GetModule` and we can remove the `GetOutput` call to ensure uniformity of evaluation.
=> ensure outputs carry sensitive marks forward

internal/command/test_test.go, internal/command/testdata/test/parallel-errors/main.tf, internal/command/testdata/test/parallel-errors/main.tftest.hcl, internal/moduletest/graph/apply.go, internal/moduletest/graph/eval_context.go, internal/moduletest/graph/eval_context_test.go, internal/moduletest/graph/node_test_run.go, internal/moduletest/graph/plan.go, internal/moduletest/graph/transform_context.go, internal/moduletest/graph/transform_test_run.go, internal/moduletest/run.go
When we first launched the test command, every run block executed in order so one run block erroring meant all others should be skipped. We can now execute run blocks in parallel, which means that sometimes one run block erroring doesn't mean that all others should be skipped. Only those that rely on an errored block should be skipped.
This PR updates the logic for skipping run blocks on failures so they check prior nodes in the graph rather than the overall status of the test file. This will be helpful later when we add variable and providers to the graph as well.
We now track outputs directly in the `moduletest.Run` struct alongside the status instead of separately in the evaluation context. This means we can access the outputs and the status together when deciding on references and …
=> terraform test: check specific dependencies before skipping run blocks

internal/backend/remote-state/azure/backend.go, internal/backend/remote-state/azure/go.mod, internal/backend/remote-state/azure/helpers.go
A rebased* version of https://github.com/hashicorp/terraform/pull/34990 :
>As part of our efforts to remove the large snapshot of the legacy SDK that we've been using, this replaces the uses of that package with our new lightweight backendbase package, which is a collection of helpers that can substitute for most of the parts of the legacy SDK that backends tend to use.
>
>In the long run we're still planning to move all of the state storage backends out to provider plugins, at which point they'll presumably use the modern plugin framework, but in the meantime the legacy SDK is quite a liability because few people know how to maintain it while hopefully this interim backendbase package is easier to maintain (if needed) due to its relative simplicity.
>
>I don't have any test environment …
=> backend/azure: Remove legacy helper/schema dependency [rebased]

internal/plans/planfile/tfplan_test.go
This PR refactors and adds some tests to code relating to plan files, in anticipation of a future PR that adds new features to plan files. By pulling this work out early I'm trying to make my next PR smaller.
N/A
=> Add and refactor test in the `planfile` package

.changes/v1.13/BUG FIXES-20250626-140248.yaml, internal/command/workspace_command_test.go, internal/command/workspace_delete.go
This follows https://github.com/hashicorp/terraform/pull/37267, which makes Terraform stop users from creating or switching to workspaces called `""`.
That PR didn't touch the `workspace delete` command, as that command doesn't check the workspace name for validity. This is on purpose; we want to allow users to delete invalid workspaces if they exist.
Currently most if not all backend implementations block deletion of `""` workspaces, as it's conflated with the default workspace. For example: [s3 backend](https://github.com/hashicorp/terraform/blob/a9b67a6cdc9502949d38670a3b1187799cf2a70d/internal/backend/remote-state/s3/backend_state.go#L137-L139), [kubernetes backend](https://github.com/hashicorp/terraform/blob/a9b67a6cdc9502949d38670a3b1187799cf2a70d/internal/backend/remote-state/kubern …
=> Make `workspace delete` command reject empty string arguments

internal/command/workdir/backend_state.go, internal/command/workdir/backend_state_test.go
This PR fixes an issue related to https://github.com/hashicorp/terraform/pull/37179. That previous PR did not update the (*BackendStateFile) DeepCopy method to invoke the new (*StateStoreConfigState) DeepCopy method, resulting in the bug fixed here.
1.13.x
=> Fix bug in DeepCopy of backend state data that causes loss of StateStore data

.changes/v1.13/ENHANCEMENTS-20250627-094638.yaml, internal/plans/objchange/compatible.go
If both elements of the set have already been matched, there is no need to compare them again.
Verified the coverage using existing tests, so no need for another duplicate test case.
Closes #32940
=> skip set elem comparison when already matched

internal/command/meta_backend.go, internal/command/workdir/backend_config_state.go, internal/command/workdir/statestore_config_state.go
For context, the `SetConfig` method on `BackendConfigState` is only used in the context of tests currently. Whenever a BackendConfigState is assembled the config is set directly by assigning a value to ConfigRaw:
https://github.com/hashicorp/terraform/blob/a9b67a6cdc9502949d38670a3b1187799cf2a70d/internal/command/meta_backend.go#L1055-L1064
That `configJSON` value is constructed in the code immediately preceding the above snippet:
https://github.com/hashicorp/terraform/blob/a9b67a6cdc9502949d38670a3b1187799cf2a70d/internal/command/meta_backend.go#L1049-L1053
This PR refactors that code to instead use [the SetConfig method](https://github.com/hashicorp/terraform/blob/9fb6d02cb3e6c65705f77721b87df41b2795f80f/internal/command/workdir/backend_config_state.go#L54). This method includes the …
=> Refactor code to use backend config state's `SetConfig` method, protect against nil receiver

internal/command/meta_backend.go, internal/command/workdir/backend_config_state.go, internal/command/workdir/config_state.go, internal/command/workdir/statestore_config_state.go, internal/plans/plan.go, internal/plans/plan_test.go, internal/plans/planfile/tfplan.go, internal/plans/planfile/tfplan_test.go, internal/plans/planproto/planfile.pb.go, internal/plans/planproto/planfile.proto
Some prototyping/implementation for the PSS project that's only relevant to the apply command.
These changes enable saving PSS config in a plan, similar to how a planfile can store backend config and be used to configure a `backend.Backend` during an apply command that is supplied with a pre-existing plan file.
N/A
=> Update data stored in plan files to enable using PSS with saved plans

internal/command/stacks.go, internal/pluginshared/stacksbinary.go
This PR moves the cached stacksplugin binary location to `.terraform.d` by default, with the option to override this location with the argument `-plugin-cache-dir`.  
If this location is overriden, then the path provided is stored in `.terraform/.stackspluginpath` of the current working directory for future reference by the subcommand. The thought behind this was to be proactive with providing a workaround in the event any user specific issues made the default behavior a problem.
I figure no changelog entry is needed as this change wraps up into the existing entry for the `terraform stacks` subcommand.
As it stands, when you run `terraform stacks ...` the stacks plugin binary is downloaded to the `.terraform/tfstacks` directory in current working directory. This is a pattern that came …
=> Move `stacksplugin` cache to `.terraform.d`

internal/backend/local/backend_plan.go, internal/command/views/hook_json.go, internal/command/views/json/query.go, internal/genconfig/generate_config.go, internal/genconfig/generate_config_test.go, internal/genconfig/generate_config_write.go, internal/plans/changes.go, internal/plans/changes_src.go, internal/terraform/context_plan_query_test.go, internal/terraform/node_resource_abstract_instance.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/node_resource_plan_instance_query.go, internal/terraform/transform_config.go
=> Generate config for list results

internal/terraform/transform_config.go
The config transformer has a resource matcher to control which nodes are added to the graph. The PR extends the check to the import targets, so we don't add resource nodes during a query run.
1.14.x
=> Only add import target nodes when they match

internal/pluginshared/testing.go
Fixes a CodeQL alert https://github.com/hashicorp/terraform/security/code-scanning/939
While listed as "High" in severity, in practice the impact is negligible since the "user-input" in question is in fact hard-coded HTTP client with pre-defined request shapes/URLs and overall the entire codepath is only used in tests.
This is also the reason why I believe this does not need any Changelog mention.
1.13.x
=> pluginshared: Cleanup request path in tests

.github/workflows/changelog.yml
This is to allow cleanly merging PRs we raise every new minor version, such as https://github.com/hashicorp/terraform/pull/37312
The existing mechanism along with `no-changelog-needed` works for the common cases of regular functional PRs but not for these PRs where we are intentionally changing Changelog related files and at the same time changing nothing functionally.
This would be unexpected situation under any other circumstance - and should continue to be raised by the checks outside of these PRs.
1.14.x
=> github: Allow changelog check to be skipped on label

internal/command/apply_test.go, internal/command/command_test.go, internal/command/console_test.go, internal/command/graph_test.go, internal/command/plan_test.go, internal/command/show_test.go, internal/command/state_identities_test.go, internal/command/state_list_test.go, internal/command/state_mv_test.go, internal/command/state_pull_test.go, internal/command/state_rm_test.go, internal/command/state_show_test.go, internal/command/state_test.go, internal/command/taint_test.go, internal/command/untaint_test.go
Replaces old custom code:
```go
func testCwd(t *testing.T) string {
t.Helper()
tmp := t.TempDir()
cwd, err := os.Getwd()
if err != nil {
t.Fatalf("err: %v", err)
}
if err := os.Chdir(tmp); err != nil {
t.Fatalf("err: %v", err)
}
t.Cleanup(func() {
if err := os.Chdir(cwd); err != nil {
t.Fatalf("err: %v", err)
}
})
return tmp
}
```
with the standard library:
```go
tmp := t.TempDir()
t.Chdir(tmp)
```
We don't need a function to make a temp dir and temporarily change directory into it - this is 2 lines with the testing library.
1.14.x
=> Replace custom `testCwd` function with standard `testing` library

internal/actions/actions.go, internal/configs/action.go, internal/configs/module_merge_test.go, internal/configs/testdata/valid-modules/override-action-and-trigger/main_override.tf, internal/experiments/experiment.go, internal/instances/expander.go, internal/lang/eval.go, internal/moduletest/graph/transform_references.go, internal/schemarepo/loadschemas/plugins.go, internal/terraform/context_plan_actions_test.go, internal/terraform/context_walk.go, internal/terraform/eval_context.go, internal/terraform/eval_context_builtin.go, internal/terraform/eval_context_mock.go, internal/terraform/graph_walk_context.go, internal/terraform/node_action.go, internal/terraform/node_action_instance.go, internal/terraform/node_resource_abstract.go, internal/terraform/node_resource_plan_instance.go, internal/terraform/transform_action_count.go, internal/terraform/transform_attach_schema.go, internal/terraform/transform_config.go, internal/terraform/transform_reference.go
This implementation is very barebones, but builds the skelleton for all upcoming features in actions. It includes the graph implementation for planning actions including the expansion of actions and dealing with multiple action triggers.
We plan all actions as part of their triggering resource for now.
All action_triggers depend on the triggering resources plan to determine if an action should run or not, therefore we can plan the actions as part of the triggering resource.
This implementation ignores conditions, deferrals, provider arguments and it does not add the actions to the planfile; mostly to enable more people to work on these issues in parallel.
Fixes [TF-25936](https://hashicorp.atlassian.net/browse/TF-25936)
1.14.x
Are there any changes to security controls (access controls, …
=> actions: implement expansion and planning actions

internal/plans/action_invocation.go, internal/plans/changes.go, internal/plans/changes_src.go, internal/terraform/context_plan_actions_test.go, internal/terraform/node_resource_plan_instance.go
Small PR to integrate the work of https://github.com/hashicorp/terraform/pull/37320 and https://github.com/hashicorp/terraform/pull/37316
Closes [TF-27456](https://hashicorp.atlassian.net/browse/TF-27456)
1.14.x
[TF-27456]: https://hashicorp.atlassian.net/browse/TF-27456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add planned actions to planfile

internal/command/arguments/flags.go, internal/command/init.go, internal/command/views/init.go
Context: https://github.com/hashicorp/terraform/pull/37321#issuecomment-3069989127
(I figured that the commit in this PR made sense to introduce into main on its own, separate to implementing further logic for PSS in the init command.)
This PR connects the code that can parse `state_store` configuration with new logic introduced in https://github.com/hashicorp/terraform/pull/37321 that allows Terraform to create an operations backend that uses PSS. Prior to this PR the logic in that PR couldn't be invoked, as BackendOpts.StateStoreConfig and BackendOpts.ProviderFactory are never set based on what's in the config.
Now the logic prepares different  `BackendOpts` depending on the situation:
* If PSS is in use: include `state_store` config and the provider factory needed for PSS in the …
=> PSS: Allow backend or state_store config to be passed via BackendOpts into method for initialising the operations backend for a command

internal/command/stacks.go
We'll want to ignore cmd argument parsing errors here, otherwise global arguments passed-to/handled-in the stacks cli plugin will cause a failure here.
1.13.x
=> `stacks` subcommand: Ignore cmd arg parsing errors

internal/backend/remote-state/azure/backend.go
Correct typo in error message:
"One of `access_key`, `sas_token`, `use_azuread_auth` and `resource_group_name` must be specifieid"
to
"One of `access_key`, `sas_token`, `use_azuread_auth` and `resource_group_name` must be specified"
Fixes #
1.14.x
=> Update backend.go to correct typo in error message

internal/command/query_test.go, internal/command/testdata/query/empty-result/main.tf, internal/command/testdata/query/empty-result/query.tfquery.hcl, internal/command/views/hook_json.go, internal/command/views/hook_ui.go, internal/command/views/json/message_types.go, internal/command/views/query_operation.go
=> Append warning in CLI output when query result is empty

.github/workflows/backport.yml
This PR renames the backport workflow file from `main` to a more specific name and bumps the backport assistants version, which hasn't been updated in over a year
1.14.x
=> Bump backport assistant to 0.5.8

internal/plugin/grpc_provider.go, internal/plugin/grpc_provider_test.go, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go
This PR updates the logic for processing list events. Terraform now allows error and warning diagnostics for list events where all other fields are set to null. It is still possible to have a warning alongside a valid result. Terraform stops processing events and returns early whenever it encounters an error.
1.14.x
=> Allow list resource RPC events with only warnings

internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go
This PR cherry-picks commit https://github.com/hashicorp/terraform/commit/c0c3c7e1d568a77df0263add22616b379a869ed7 out of our prototyping branch and gets it into main.
These changes allow Terraform to use PSS-related methods when interacting with a separate provider binary using gRPC. Previous to these changes we were using the builtin provider to test PSS, so gRPC was not in use and the original panics in this code were not triggered.
N/A
=> PSS: Implement first gRPC methods: config validation and usage, listing and deleting workspaces

internal/terraform/context_apply_action_test.go, internal/terraform/context_plan_actions_test.go, internal/terraform/node_action_trigger_apply.go, internal/terraform/node_action_trigger_instance_plan.go, internal/terraform/transform_action_diff.go
We disabled a few tests around error handling for actions when we refactored the way actions work in #37444. This PR re-enables them albeit differently: Instead of adding context for how to proceed (undo changes, retry failing / not-yet-run actions) we show the invocation of the action. This gives the user more context. We will wait for user feedback if the next steps would be useful as well even with this context already in place. It is a bit more difficult to add this info in the current system therefore we postpone it for now until the work is more stable.
Fixes #
1.14.x
=> actions: improve error messages and reenable error related tests

internal/command/workdir/backend_state_test.go
=> Un-hardcode TF version in test

internal/stacks/stackmigrate/migrate_test.go, internal/stacks/stackmigrate/resources.go, internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/child/child.tf, internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/child/grandchild/main.tf, internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/single-component.tfcomponent.hcl
Some feedback from the Stacks migrate team is that the diagnostic returned by Terraform were a bit confusing. This PR goes through some of the diagnostics returned when Terraform migrates state and makes the wording more relevant to the actual operation being carried out.
Generally, Terraform was being a bit too specific about it's internal workings such as returning "provider not found" errors when the root cause was the a mapping was trying to point a resource to an address that didn't exist in the stack configuration. The diagnostics now try and relate things back to what the caller is actually trying to do instead of what Terraform is trying to do at the current point in time.
=> stacks migrate: make diagnostics more relevant to operation

internal/command/meta.go
Related to: https://github.com/hashicorp/terraform/issues/37439
I received some feedback that it'd be good to update the code with a comment to highlight the migration that has been started but not finished. This will help people understand why both are present in the `Meta` and aids discovery of the linked GH issue.
N/A
=> Add code comment to make in-progress migration from Ui to View more obvious

internal/command/jsonformat/plan_test.go, internal/command/jsonprovider/provider.go, internal/command/jsonprovider/provider_test.go
This PR removes the nested `config` block from the list resource schema JSON output of `terraform providers schema -json`. It makes the schema easier to consume and hides the nested block implementation detail.
It also moves the actions schemas behind the experimental flag.
**Before**
**After**
1.14.x
=> Exclude nested config block from list resource schemas

internal/command/e2etest/init_test.go
I just had to wrestle with this test for a while:
https://github.com/hashicorp/terraform/blob/62b3ba590aa2f0f4c5d412833f5317754f556c0c/internal/command/e2etest/init_test.go#L135C6-L143
The log at the end suggests checking [implied local mirror directories](https://developer.hashicorp.com/terraform/cli/config/config-file#implied-local-mirror-directories) but the test can fail earlier if a CLI configuration file is present on your machine and it causes Terraform to start making network calls.
N/A
=> Update info for debugging why `TestInitProvidersLocalOnly` may fail

internal/backend/remote-state/s3/backend_test.go
Fixes an issue with how a test is constructed following https://github.com/hashicorp/terraform/pull/37430
After that PR, the returned `error` is now the result of calling `[tfdiags.Diagnostics].Err()` to get an error representation of a diagnostic. This meant the types had changed and interfered with the error comparison code in the test.
At the time I made changes in the Workspaces method this issue was lost amongst the diags comparison issues that are affecting the S3 backends' tests. I'm currently addressing those in a [separate PR](https://github.com/hashicorp/terraform/pull/37509).
N/A
=> Fix S3 backend test affected by making the Workspaces method return errors via diagnostics

internal/terraform/context_plan_actions_test.go
Addressing some flapping behavior in a test - the DeferredActionInvocations aren't in any specific order, so this sorts them first for consistent testing.
Fixes #
1.14.x
=> test fix: sort DeferredActionInvocations before making assertions

docs/plugin-protocol/tfplugin6.proto, internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go, internal/plugin6/mock_proto/mock.go, internal/tfplugin6/tfplugin6.pb.go
Updates the base branch to include proto changes introduced in https://github.com/hashicorp/terraform-plugin-go/pull/531
N/A
=> Update proto file definition of Read/WriteStateBytes RPCs

internal/command/meta_backend_test.go, internal/command/testdata/backend-to-state-store/main.tf, internal/command/testdata/state-store-changed/.terraform/terraform.tfstate, internal/command/testdata/state-store-changed/main.tf, internal/command/testdata/state-store-new-vars-in-provider/main.tf, internal/command/testdata/state-store-new-vars-in-store/main.tf, internal/command/testdata/state-store-new/main.tf, internal/command/testdata/state-store-reconfigure/.terraform/terraform.tfstate, internal/command/testdata/state-store-reconfigure/main.tf, internal/command/testdata/state-store-to-backend/.terraform/terraform.tfstate, internal/command/testdata/state-store-unset/.terraform/terraform.tfstate, internal/configs/testdata/invalid-modules/conflict-cloud-backend-statestore/main.tf, internal/configs/testdata/invalid-modules/conflict-cloud-statestore-separate-files/state-store.tf, internal/configs/testdata/invalid-modules/conflict-cloud-statestore/main.tf, internal/configs/testdata/invalid-modules/conflict-statestore-backend-separate-files/state-store.tf, internal/configs/testdata/invalid-modules/conflict-statestore-backend/main.tf, internal/configs/testdata/invalid-modules/multiple-state-store/a.tf, internal/configs/testdata/valid-modules/override-state-store-no-base/override.tf, internal/configs/testdata/valid-modules/override-state-store/main.tf
This reduces repetitive code in these tests, but requires the test fixtures to be updated to use the correct provider and state store names
N/A
=> Add test helper to create mock provider that contains a state store

internal/backend/remote-state/azure/client.go, internal/backend/remote-state/azure/client_test.go, internal/backend/remote-state/consul/client.go, internal/backend/remote-state/consul/client_test.go, internal/backend/remote-state/cos/client.go, internal/backend/remote-state/gcs/client.go, internal/backend/remote-state/http/client.go, internal/backend/remote-state/inmem/client.go, internal/backend/remote-state/kubernetes/client.go, internal/backend/remote-state/oci/client.go, internal/backend/remote-state/oss/client.go, internal/backend/remote-state/oss/client_test.go, internal/backend/remote-state/pg/client.go, internal/backend/remote-state/s3/backend_test.go, internal/backend/remote-state/s3/client.go, internal/backend/remote-state/s3/client_test.go, internal/backend/remote/backend_state.go, internal/backend/remote/backend_state_test.go, internal/states/remote/remote.go, internal/states/remote/remote_grpc.go, internal/states/remote/remote_grpc_test.go, internal/states/remote/remote_test.go, internal/states/remote/state.go, internal/states/remote/testing.go
This PR is stacked on https://github.com/hashicorp/terraform/pull/37496
This PR updates the interfaces that are used for reading and saving state to/from remote locations. The changed code is used in all backends in the `remote-state` folder.
By making these interfaces return diagnostics we allow backends to return warnings to users, instead of just errors.
N/A
=> Update `remote.Client` interface's methods to return diagnostics instead of primitive errors

internal/terraform/context_plan_actions_test.go, internal/terraform/transform_config.go
I misconfigured a test and had the sudden realization that certain validations had gotten lost - crucially, we were no longer validating that the action referenced inside a resource's ActionTriggers existed inside the config. Very early on, that happened during configload, but it was based on flawed implementation (my mistake! what is a terraform, even?) and the validation was removed when I fixed my improper handling. 
I tried a few options but decided that this particular validation fit best in the configuration transformation process, as it is a matter of connecting the resource's action to the action configuration. I took some inspiration from validateImportTargets code, mostly in how I crafted the error, and in deciding to return after validating the actions if an error is …
=> actions: validate that action referenced in action_trigger exists in config during transform

internal/configs/parser_config_dir_test.go, internal/configs/query_file.go, internal/configs/testdata/query-files/valid/mixed/main.tfquery.hcl
This fixes a bug that prevented the definition of list resources of different types, but same name. e.g `list.foo.test` and `list.bar.test` within a query file.
1.14.x
=> Allow duplicate list names for different types

internal/terraform/context_apply_action_test.go, internal/terraform/node_action_trigger_apply.go
=> actions: ensure config is known during apply

CODEOWNERS
As discussed internally this adds additional protections to ensure we do not make any changes in `go.mod` during the temporary dependency freeze around Hashiconf. 
As written now this uses my github user directly. If anyone feels strongly about avoiding that we could create a new group that I am the only member of and go that route. 
This also references the file directly. If someone has a better / preferred pattern I'm happy to change it as well. 
1.14.x
=> temporarily require manager approval for go.mod changes

internal/command/jsonformat/plan_test.go, internal/command/jsonformat/structured/change.go, internal/command/jsonplan/action_invocations.go, internal/command/jsonplan/action_invocations_test.go
This PR updates the JSON plan to include unknown metadata.
Also, tweaks the representation of the config value to match the simple `json.RawMessage` used by other changes. It is true that it must be an object, so will always be a map, but being more specific for this field compared to other fields led to confusion in consumers, and also needed extra complexity in consuming everything later. This isn't needed anymore.
Also (2), I've updated the sensitive metadata so that it also reads from the schema for sensitive metadata. This matches the behaviour for other changes, and is just another check to make sure sensitive metadata is being included where appropriate.
1.14.x
=> actions: preserve unknown metadata in the json plan

internal/backend/local/backend.go, internal/backend/local/testing.go, internal/backend/remote-state/cos/backend_test.go, internal/backend/remote-state/gcs/backend_test.go, internal/backend/remote-state/kubernetes/client_test.go, internal/backend/remote-state/oss/client_test.go, internal/backend/remote-state/s3/client_test.go, internal/command/meta_backend.go, internal/command/meta_backend_migrate.go, internal/moduletest/graph/eval_context.go, internal/moduletest/states/manifest.go
Follow up to https://github.com/hashicorp/terraform/pull/37589. In that case, the interface defining the StateMgr method was updated to return diagnostics instead of errors, and something went wrong when that change was pulled into a long-lived feature branch.
This PR changes that code _and_ other examples of calling code to handle diagnostics more conventionally:
* Instead of checking for non-`nil` values, inspect for errors
* Retrieve an `error` representation of the diagnostics where calling code previously used errors to make test failure messages or return errors to users.
N/A
=> Update calls to StateMgr method to use diagnostics more conventionally

internal/command/query_test.go, internal/command/views/hook_json.go, internal/command/views/hook_ui.go, internal/command/views/json/query.go, internal/terraform/hook.go, internal/terraform/hook_mock.go, internal/terraform/hook_stop.go, internal/terraform/hook_test.go, internal/terraform/node_resource_plan_instance_query.go
This PR adds an `identity_version` attribute to the `list_resource_found` json output, to be used in the cloud implementation in comparing resource. I needed to update the `PostListQuery` method in the Hook interface, hence the reason for most of the edited files.
I also added a test to verify the raw output when running a query test in json mode.
1.14.x
=> query: add identity_version to list_resource_found json output

internal/configs/parser_config_dir_test.go, internal/configs/query_file.go, internal/configs/testdata/query-files/invalid/with-depends-on/main.tfquery.hcl
This disables the `depends_on` attribute for list blocks. Before this change, the attribute was accepted, but nothing was being done with it.
1.14.x
=> tf query: disable depends_on for list blocks

internal/command/jsonformat/plan_test.go, internal/command/jsonprovider/provider_test.go, internal/command/show_test.go, internal/command/views/operation_test.go, internal/configs/action.go, internal/configs/action_test.go, internal/configs/module_merge.go, internal/lang/eval.go, internal/plans/changes_src.go, internal/plans/planfile/tfplan_test.go, internal/plans/planproto/planfile.pb.go, internal/plans/planproto/planfile.proto, internal/plugin/grpc_provider_test.go, internal/plugin6/grpc_provider_test.go, internal/terraform/context_apply_action_test.go, internal/terraform/context_plan_actions_test.go, internal/terraform/resource_provider_mock_test.go
This PR removes remaining references to action types and linked_resources. Most of the changes are either minor test naming changes, or removing code that was only partially implemented (or implemented but gated and not working - anything referring to linked_resources, for example). I also tweaked a diagnostic with some grammatical issues and fixed some comments while I was in the area.
The impactful proto changes are in a single commit:  
[actions: remove references to linked_resources or action types from the plan proto](https://github.com/hashicorp/terraform/pull/37616/commits/02db4de5ce75b36ab36830f93119b27984d4a932)
Fixes #
1.14.x
=> actions: remove references to action types, linked resources

.changes/v1.14/NEW FEATURES-20250903-131921.yaml, internal/command/apply.go, internal/command/plan.go, internal/command/testdata/show-json-actions/main.tf, internal/configs/parser_config.go, internal/configs/resource.go, internal/configs/testdata/valid-files/actions.tf.json
This PR removes the feature flags around Terraform Actions. 
The implementation of actions happened in these PRs:
- https://github.com/hashicorp/terraform/pull/37003
- https://github.com/hashicorp/terraform/pull/37006
- https://github.com/hashicorp/terraform/pull/37030
- https://github.com/hashicorp/terraform/pull/37287
- https://github.com/hashicorp/terraform/pull/37313
- https://github.com/hashicorp/terraform/pull/37316
- https://github.com/hashicorp/terraform/pull/37320
- https://github.com/hashicorp/terraform/pull/37339
- https://github.com/hashicorp/terraform/pull/37340
- https://github.com/hashicorp/terraform/pull/37345
- https://github.com/hashicorp/terraform/pull/37349
- https://github.com/hashicorp/terraform/pull/37355
- https://github.com/hashicorp/terraform/pull/37375
- …
=> enable actions outside of experiments

.changes/v1.14/NEW FEATURES-20250829-183404.yaml, .changes/v1.14/NEW FEATURES-20250829-184206.yaml
This PR adds changelog entries for the upcoming Terraform 1.14 beta
Only merge close to the beta release date
1.14.x
=> Add changelog entries for Terraform Search (TF-28525)

internal/command/meta.go, internal/command/meta_config.go, internal/command/plan_test.go, internal/command/query.go, internal/command/query_test.go, internal/configs/config_build_test.go, internal/configs/configload/loader.go, internal/configs/configload/loader_load.go, internal/configs/configload/loader_snapshot.go, internal/configs/configload/testing.go, internal/configs/parser_config_dir.go, internal/configs/parser_config_dir_test.go, internal/configs/parser_file_matcher.go, internal/initwd/testing.go, internal/terraform/terraform_test.go
This constricts the parsing of query files to only commands related to terraform query. This implies that `init` would not parse query files, and we would not catch invalid config until running the `terraform query` command.
I had to edit this many files so that we could configure the loader to optional parse query files.
1.15.x
=> query: constrict query files parsing to tf query command only

internal/plugin6/grpc_provider.go, internal/plugin6/grpc_provider_test.go
This PR moves some fixes to the radek/pss-read-write branch out of https://github.com/hashicorp/terraform/pull/37323
I tested the process of initialising a working directory end to end using the `pss` provider and our changes to the terraform-plugin-go repo, and in the process made these changes to the Core-side of `ReadStateBytes`.
The main changes in this PR are:
* Being clear that the io.EOF sentinel error is not expected to be accompanied with _any_ chunk information, i.e. no bytes and no diagnostics.
* Adding a call to CloseSend to close the stream, if reading the state didn't encounter any grpc errors or custom error diagnostics from the provider.
N/A
=> Sarah's updates to radek/pss-read-write

internal/command/plan.go
This PR just returns an error early if a user tries to invoke actions with a cloud backend. TFC hasn't been updated yet, and Terraform crashes if this is attempted. With this we just get an error message instead of a crash, and we can remove this once TFC is up to date.
1.14.x
=> actions: allow invoke only on local execution while TFC adds support

.changes/v1.14/ENHANCEMENTS-20250919-115253.yaml, internal/command/stacks.go
This PR provide the raw args to the `StacksCommand`'s `Help()` which allows for the more typical `-help` usage rather than strictly requiring the `-usage` flag for command usage information.
We previously ran into trouble with the handling of the `-help` flag in regards to the the stacks CLI plugin. Notably since the cli runner strips the `-help` flag from the args passed to the command's `Run` implementation. At the time we encountered this we opted for a stop gap solution of using the `-usage` flag for help texts. This PR at adds the ability to properly handle the help flag.
1.14.x
=> Handle `-help` usage in stacks plugin

.changes/v1.14/BUG FIXES-20250924-110416.yaml, internal/command/test_test.go, internal/command/testdata/test/invalid-reference-with-target/main.tf, internal/command/testdata/test/invalid-reference-with-target/main.tftest.hcl, internal/terraform/context_plan_actions_test.go, internal/terraform/evaluate.go
…
This PR updates the behaviour for resources and locals, so that when referenced out of order they return explicit diagnostics stating this instead of simple unknown values.
Fixes #
1.14.x
=> evaluate: return diagnostics instead of unknown for uninitialised locals and resources

internal/terraform/node_action_trigger_instance_plan.go
This is a manual "backport", I selected the wrong label on the original PR 🙄 
Fixes #
1.15.x
=> backport of actions: don't panic when resource change is nil - it might be a refresh (37687)

.changes/v1.15/NEW FEATURES-20250926-164134.yaml, .github/workflows/build.yml
I'm not familiar enough with platform-specific differences to know whether our ability to produce a build is enough confidence that this will work, or whether we need to do manual testing to verify. We did unfortunately figure out that our existing E2E tests won't work for this platform, so any verification will need to be manual.
Fixes #32719
1.15.x, or we could backport to 1.14.x, this is relatively flexible
n/a
=> build: Produce a Windows arm64 binary

internal/states/resource_test.go, internal/states/state_test.go
=> Improve tests in internal/states (ProviderAddrs, HasCurrent, Unlock)

internal/states/remote/remote_grpc.go, internal/states/remote/remote_grpc_test.go
This PR allows any backend.Backend that represents a pluggable state store to return a state manager that's capable of reading and writing state via the ReadStateBytes and WriteStateBytes RPCs.
A remaining question is what to do about the MD5 hash returned from the Get method. This is not used downstream at all, so I've decided to leave it empty intentionally. I think calculating an MD5 hash on the Core/client side would be misleading, as readers would assume the value is used.
N/A
=> PSS: Implement `Get` and `Put` methods on remote grpc state, using Read/WriteStateBytes RPCs

.changes/v1.14/BUG FIXES-20250927-184134.yaml
The changie CI workflow [is currently failing](https://github.com/hashicorp/terraform/actions/runs/18277907604/job/52044452921#step:5:14) on the v1.14 branch due to a misformated changelog entry that was introduced in https://github.com/hashicorp/terraform/pull/37692.
This PR fixes the entry. I'm skipping the changelog check on this PR since the workflow checks out the target branch (v1.14) and will fail until this PR is merged.
1.14.x
=> Fix 1.14 changelog entry

internal/states/instance_object_src.go, internal/states/instance_object_test.go, internal/terraform/context_plan_identity_test.go
This PR is manual backport of https://github.com/hashicorp/terraform/pull/37709, because the automatic one failed
1.14.x
=> Backport: search: Drop identity from state if no identity schema is present

internal/terraform/context_apply_action_test.go, internal/terraform/context_plan_actions_test.go, internal/terraform/node_action_instance.go, internal/terraform/node_action_validate.go
~This just adds two tests that validate the behaviour of ephemeral inputs into actions, and codifies it so we can make sure we don't accidentally regress this in the future (only deliberately regress).~
Edited. I've changed this PR so that we are actually enforcing the ephemeral into write-only attributes behaviour. This matches the behaviour of resources, and means we won't accidentally leak ephemeral values into the plan file or introduce weird behaviour with ephemeral values changing between plan and apply.
=> actions: enforce ephemeral into write-only attributes behaviour
