builtin/providers/aws/resource_aws_internet_gateway.go, builtin/providers/aws/resource_aws_internet_gateway_test.go
Remove unreachable code when deleting internet gateway ([L119-133]).
When DeleteInternetGateway is successful it returns a nil error value.
However, for a nil error value, the RetryFunc returns an error ([L116]) yielding a
unnecessary second call to DeleteInternetGateway in the retry logic.
The logic works because DeleteInternetGateway eventually returns an ec2.Error
with error code ```InvalidInternetGatewayID.NotFound``` since the internet gateway
has been deleted in the previous call. The return value of nil breaks the
retry logic and the deletion is deemed successful ([L107-108]).
Fix the unnecessary second call to DeleteInternetGateway by short circuiting
with a nil error value when deletion of the internet gateway is successful on
the first try.
Added an acceptance test for internet …
=> builtin/providers/aws: remove unreachable code and skip unnecessary remote call

builtin/providers/aws/resource_aws_route_table.go
=> Vgw routes

builtin/providers/aws/resource_aws_route_table.go
=> Route diff fix

builtin/providers/aws/resource_aws_instance_test.go
Acceptance tests for issue #687. Depends on the fix in PR mitchellh/goamz#188.
=> builtin/providers/aws: acceptance tests for assigning private IPs on AWS instance

builtin/providers/consul/config.go, builtin/providers/consul/resource_consul_keys.go, builtin/providers/consul/resource_consul_keys_test.go, builtin/providers/consul/resource_provider_test.go, remote/consul.go, remote/consul_test.go
Depends on hashicorp/consul#581
=> Switch to github.com/hashicorp/consul/api

website/source/intro/vs/cloudformation.html.markdown
This is a reword of #760 at @mitchellh 's request.
=> Clarify re: Openstack support

builtin/providers/aws/resource_aws_internet_gateway.go, builtin/providers/aws/resource_aws_internet_gateway_test.go
Closes https://github.com/hashicorp/terraform/issues/658
=> Adding tags support to Internet Gateway resource

helper/schema/field_reader.go, helper/schema/field_reader_config.go, helper/schema/field_reader_config_test.go, helper/schema/field_reader_diff.go, helper/schema/field_reader_diff_test.go, helper/schema/field_reader_map.go, helper/schema/field_reader_map_test.go, helper/schema/field_reader_test.go, helper/schema/schema.go, helper/schema/schema_test.go, helper/schema/valuetype_string.go
Fixes #594 
Self explanatory...
=> helper/schema: Add TypeFloat

builtin/providers/cloudstack/config.go, builtin/providers/cloudstack/provider.go
Seems some platforms need more time, so make it configurable with a sane default…
Thanks Johan Welsch for the pseudo code :wink:
=> provider/cloudstack: make timeout configurable

builtin/providers/cloudstack/provider.go
This causes a crash of the provider
=> Fix conversion error

helper/schema/schema_test.go
=> failing schema diff test for TypeFloat

website/source/docs/configuration/syntax.html.md, website/source/docs/providers/mailgun/r/domain.html.markdown
=> website: use lists throughout the docs instead of array

README.md
Command `go generate` appeared in Go 1.4
=> Now Go version must be at least 1.4

helper/schema/resource_data.go, helper/schema/resource_data_test.go
Fixes GH-805 maybe.
@svanharmelen What do you think of this change? This just reverts the "zero value in state" thing. I added a test. I modified a few others but I think the logic I modified them to makes sense. Thoughts?
=> helper/schema: don't put things into the state that don't exist or are computed

helper/schema/field_reader_map.go, helper/schema/field_reader_map_test.go, helper/schema/field_writer_map.go, helper/schema/field_writer_map_test.go, helper/schema/resource_data_test.go, helper/schema/resource_test.go
@svanharmelen This fixes the computed map issue. I honestly don't think this ever worked... or if it did it just happened to work. None of our tests covered it. Take a look.
=> helper/schema: map counts in state

helper/schema/field_writer_map.go
Sorry, can't help myself... :wink:
=> core: ocd fixups, cosmetic only

contrib/zsh-completion/README.md, contrib/zsh-completion/_terraform, contrib/zsh-completion/install.sh
=> Add zsh completion support

Makefile
Add a vet target in order to catch suspicious constructs
reported by go vet.
Vet has successfully detected problems in the past.
For example, see
482460c4c8a663ec2882bbddbb32da8e990de080
fc36b1cd9490233a3d220365fac3bc65679fe6de
68a41035a92606b6943c517fd874b54e8237485f
7b704fb77d6430cde07703f7cc8574484630d85c
4f3f85b1651d0c34c27c79cdbb772ecc07d6665a
95fa353ee928a42de1923d0f961e40d4ce201443
4bfe18b40d0749c073b3c4ba23f5c908436815d0
Some vet flags are noisy. In particular, the following flags
reports a large amount of generally unharmful constructs:
```
-assign: check for useless assignments
-composites: check that composite literals used field-keyed
elements
-shadow: check for shadowed variables
-shadowstrict: whether to be strict about shadowing
-unreachable: check for unreachable code
``` …
=> Makefile: add vet target

Makefile, README.md
No need to have an extra dev bootstrapping step when we can automate it!
=> Makefile: roll gox into updatedeps

website/source/docs/configuration/resources.html.md
=> docs: add example of using variables with count

command/apply_test.go, config/module/detect.go, config/module/url_helper.go
=> command: fix test failures on OpenBSD, Windows

helper/schema/field_reader.go, helper/schema/field_reader_diff.go, helper/schema/field_reader_map.go, helper/schema/field_writer_map.go, helper/schema/resource_data_test.go, helper/schema/schema.go
I ran into some errors when removing the TODO from #588 
re: resolution of #594 
These are all the missing cases I could find, and the TODO in #588 can now be removed.
=> Add some missing Float cases

.gitignore, builtin/providers/google/provider.go, builtin/providers/google/resource_compute_address.go, builtin/providers/google/resource_compute_forwarding_rule.go, builtin/providers/google/resource_compute_forwarding_rule_test.go, builtin/providers/google/resource_compute_http_health_check.go, builtin/providers/google/resource_compute_http_health_check_test.go, builtin/providers/google/resource_compute_instance.go, builtin/providers/google/resource_compute_target_pool.go, builtin/providers/google/resource_compute_target_pool_test.go, website/source/docs/providers/google/r/compute_address.html.markdown, website/source/docs/providers/google/r/compute_forwarding_rule.html.markdown, website/source/docs/providers/google/r/compute_http_health_check.html.markdown, website/source/docs/providers/google/r/compute_instance.html.markdown, website/source/docs/providers/google/r/compute_target_pool.html.markdown
This is #588 rebased, squashed, and verified acceptance tests were passing.
Great work by @sparkprime!
=> [repack] Multiple gcp improvements and new resources

builtin/providers/google/resource_compute_http_health_check.go, builtin/providers/google/resource_compute_http_health_check_test.go
Some typos and missing code filled in here.  This also cast light on a bug in the test, also fixed.
=> Fix a number of healthcheck bugs

builtin/providers/google/provider.go, builtin/providers/google/resource_compute_instance_template.go, builtin/providers/google/resource_compute_instance_template_test.go, website/source/docs/providers/google/r/compute_instance_template.html.markdown
This adds instance template support including tests and docs.
=> GCE instance template support

website/source/docs/providers/aws/r/elb.html.markdown
Address confusion regarding ELB in VPC or EC2-classic. See #958.
=> Clarify usage of `aws_elb`

terraform/context_test.go
The attributes in the diff are %#v-formatted. This means that all `\`
characters in the Windows paths are escaped with a `\`. We need to
escape the `\` characters in cwd, module, and root before doing any
comparison work.
Fixes the following test failure on Windows:
```
--- FAIL: TestContextPlan_pathVar (0.00s)
context_test.go:3833: bad:
DIFF:
CREATE: aws_instance.foo
cwd:    "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform/barpath"
module: "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform\\test-fixtures\\plan-path-var/foopath"
root:   "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform\\test-fixtures\\plan-path-var/barpath"
type:   "" => "aws_instance"
STATE:
<no state>
expected:
DIFF:
CREATE: aws_instance.foo
cwd:    "" => …
```
=> terraform: fix ContextPlan test failure on Windows

helper/schema/schema.go, helper/schema/schema_test.go
Fixes #968 
The title explains it all, along with #968.
=> helper/schema: empty map values should show up in diff [GH-968]

builtin/providers/aws/resource_aws_autoscaling_group.go, builtin/providers/aws/resource_aws_autoscaling_group_test.go, helper/resource/testing.go, helper/schema/resource_data.go
Fixes GH-904
I found some weird bugs here with other things due to other changes we made. Going to go through and fix those now.
=> providers/aws: allow in-place update of launch configuration

builtin/providers/aws/resource_aws_instance.go
The value to set must not contain invalid fields. Additionally, we make sure to set the empty root block device if there isn't one.
=> providers/aws: root block device not being set properly

website/source/layouts/google.erb
Recent PRs adding new resources have added docs but not linked them from the sidebar
=> Add google resources to sidebar

terraform/state.go, terraform/state_test.go
This introduces a `*State.Equal` method that tests whether two states are equal. This is with the goal of working towards #380 eventually. I just want to check sanity:
* I don't need to compare `RemoteState` right? (the field)
* I try to treat `nil` as equal still (doesn't matter if there are spurious nils) because `prune()` will prune them out anyways.
=> terraform: State.Equal to check for state equality

builtin/providers/heroku/resource_heroku_addon.go
Reverts hashicorp/terraform#1006
=> Revert "Heroku returns config_vars for addon as string array."

builtin/providers/digitalocean/resource_digitalocean_droplet.go
Fixes #792
Depends on https://github.com/pearkes/digitalocean/pull/5
=> providers/digitalocean: use real bools for droplet creation

builtin/providers/aws/resource_aws_db_parameter_group_test.go
forgot to convert the test in #1060
=> provider/aws: convert db param group test to use aws-sdk-go

builtin/providers/digitalocean/resource_digitalocean_droplet.go, helper/resource/state.go
=> providers/digitalocean: Configure wait checks

website/source/docs/providers/aws/r/security_group.html.markdown
If it is all traffic instead of all tcp traffic , protocol should be equal -1 , otherwise indicate all tcp not all traffic
=> protocol value for all traffic should be -1

helper/schema/schema_test.go
a process also known as 'paulification' :)
=> helper/schema: [tests] add names to Validate tests

command/cli_ui.go, command/command.go, command/meta.go
also properly colorize error/warnings
depends on https://github.com/mitchellh/cli/pull/15
=> command: warnings should not exit

.travis.yml
should help us catch go vet issues quickly
=> run `go vet` on Travis

builtin/providers/aws/resource_aws_security_group.go, builtin/providers/aws/resource_aws_security_group_test.go, builtin/providers/aws/structure.go, builtin/providers/aws/structure_test.go
Converts AWS Security Group resource to use aws-sdk-go
=> provider/aws: Convert AWS Security Groups to aws-sdk-go

website/source/docs/providers/aws/r/security_group.html.markdown
align indentation with the rest of the code.
=> fix indent

builtin/providers/aws/resource_aws_instance.go
Some attributes are only valid inside of a VPC
=> provider/aws: Add additional guards for Tenancy, SourceDestCheck 

builtin/providers/aws/resource_aws_instance.go, builtin/providers/aws/resource_aws_instance_test.go
=>  providers/aws: fix bug w/ empty block dev mapping 

website/source/intro/getting-started/install.html.markdown
Hi! Noticed that this usage doc was a little out of date, so I brought it up to the output of `$ terraform` on master.
=> Bring usage docs up to date

builtin/providers/cloudstack/resource_cloudstack_disk.go, builtin/providers/cloudstack/resource_cloudstack_vpn_customer_gateway.go
This PR has to be merged at the same time as https://github.com/xanzy/go-cloudstack/pull/18, so I will do these in a minute right after each other.
Executed all CloudStack acceptance tests successfully just now, so the code is fully tested and without any issues.
=> provider/cloudstack: some small fixes, needed to work with bigger templates

builtin/providers/aws/resource_aws_route_table.go, builtin/providers/aws/resource_aws_vpc.go, builtin/providers/aws/resource_aws_vpc_test.go
Fixes sundry errors related to VPC in the AWS provider. See the commit messages for details.
=> Fix error handling in AWS VPC provider

builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/s3_tags.go, builtin/providers/aws/s3_tags_test.go
Adds tag support to AWS S3 buckets
Missing `read` functionality ATM
=> provider/aws: Add tags to S3

CHANGELOG.md
When through the PRs list and added changes / fixes that weren't themselves introduced post 0.3.7
=> Update CHANGELOG with post 0.3.7 changes

builtin/providers/aws/resource_aws_security_group_test.go
=> provider/aws: Fix acceptance test checks for AWS Security Group

builtin/providers/digitalocean/resource_digitalocean_ssh_key_test.go
there's now validation on the public key field
=> providers/digitalocean: fix ssh key test

builtin/providers/aws/resource_aws_launch_configuration.go, builtin/providers/aws/resource_aws_launch_configuration_test.go, website/source/docs/providers/aws/r/launch_config.html.markdown
=> block device support for launch configurations

builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go
d.Set has a pointer nil check we can lean on
/cc @fanhaf
=> providers/aws: pass pointers directly to d.Set in RDS

builtin/providers/aws/resource_aws_launch_configuration.go
These changes should fix #1367:
* `ebs_optimized` gets `Computed: true` and set from `Read`
* `ephemeral_block_device` loses `Computed: true`
* explicitly set `root_block_device` to empty from `Read`
While I was in there (tm):
* Send pointers to `d.Set` so we can use its internal nil check.
=> providers/aws: don't force update for existing launch configs

website/source/docs/providers/aws/r/db_instance.html.markdown, website/source/docs/providers/aws/r/db_parameter_group.html.markdown
=> Fix docs inconsistencies in AWS DB Provider

website/source/intro/vs/cloudformation.html.markdown
=> docs: remove note about openstack

helper/ssh/communicator_test.go
It turned out the tests didn’t work as expected due to some missing config in the `newMockLineServer` and a defer located in the wrong location. All is good again now…
=> Fixing up the communicator tests

website/source/docs/providers/aws/r/security_group.html.markdown
=> docs: move aws SG tags from rules to resource

builtin/providers/aws/config.go, builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go, builtin/providers/aws/resource_aws_db_parameter_group.go, builtin/providers/aws/resource_aws_db_parameter_group_test.go, builtin/providers/aws/resource_aws_db_security_group.go, builtin/providers/aws/resource_aws_db_security_group_test.go, builtin/providers/aws/resource_aws_db_subnet_group.go, builtin/providers/aws/resource_aws_db_subnet_group_test.go, builtin/providers/aws/structure_sdk.go, builtin/providers/aws/structure_sdk_test.go, builtin/providers/aws/tagsRDS.go, builtin/providers/aws/tagsRDS_test.go
Converts RDS to use github.com/awslabs/aws-sdk-go
=> provider/aws: Convert AWS RDS to use upstream aws-sdk-go

builtin/providers/aws/config.go, builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/resource_aws_s3_bucket_test.go, builtin/providers/aws/s3_tags.go, builtin/providers/aws/s3_tags_test.go
Converts the S3 resource to the new upstream sdk library
=> provider/aws: Conver AWS S3 to upstream sdk

website/source/docs/configuration/interpolation.html.md
Follow up to https://github.com/hashicorp/terraform/pull/1495
=> Add docs for length func

builtin/providers/docker/resource_docker_container.go, builtin/providers/docker/resource_docker_container_funcs.go, website/source/docs/providers/docker/r/container.html.markdown
Allow docker containers to use the linking system for connectivity. Docker links are explained here: https://docs.docker.com/userguide/dockerlinks/
=> Added Docker links support to the docker_container resource.

builtin/providers/docker/resource_docker_container.go, builtin/providers/docker/resource_docker_container_funcs.go, website/source/docs/providers/docker/r/container.html.markdown
Rebased, added a nil guard, and documented new attributes.
=> [repack] "Add docker container network settings to output attribute #1554"

website/source/docs/providers/atlas/r/artifact.html.markdown
=> Website: Minor improvements to artifact docs

builtin/providers/aws/resource_aws_network_acl.go
Fixes #1549 
I wasn't able to reproduce this but I can see how its technically possible. I just guard this with some sanity.
=> provider/aws: fix potential panic when finding network ACL

builtin/providers/aws/resource_aws_route_table.go, builtin/providers/cloudstack/resource_cloudstack_egress_firewall.go, builtin/providers/cloudstack/resource_cloudstack_firewall.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule.go, builtin/providers/cloudstack/resource_cloudstack_port_forward.go
This just fixes a few typos I noticed when reading through some of the Terraform source.
=> Fix comment typos.

builtin/providers/cloudstack/resource_cloudstack_network_acl_rule.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule_test.go
The protocol "all" was configurable but not implemented yet. Also fixed the hash to lower case the configs so the hash will match when nothing changed.
=> Provider/Cloudstack: Fixed the acl rules to support protocol all and icmp

website/source/intro/getting-started/modules.html.md
=> docs: Clarify provider config in modules intro

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_ebs_volume.go, builtin/providers/aws/resource_aws_ebs_volume_test.go
This resource allows the management of EBS volumes not associated with
any EC2 instance.
=> Implement aws_ebs_volume

builtin/providers/google/config.go, builtin/providers/google/dns_change.go, builtin/providers/google/provider.go, builtin/providers/google/resource_dns_managed_zone.go, builtin/providers/google/resource_dns_managed_zone_test.go, builtin/providers/google/resource_dns_record_set.go, builtin/providers/google/resource_dns_record_set_test.go, website/source/docs/providers/google/r/dns_managed_zone.markdown, website/source/docs/providers/google/r/dns_record_set.markdown, website/source/layouts/google.erb
Adds 2 new resources:
google_dns_managed_zone
google_dns_record_set
=> Support Google Cloud DNS, Fix #1148

website/source/docs/plugins/provider.html.md
Font was different from rest of the page and very weird lookin'
=> docs: Fix styling in provider code block

builtin/providers/openstack/resource_openstack_networking_subnet_v2.go
Fixes #1741 
I'm not sure why this was ever a string, but this fixes weird diff issues.
=> provider/openstack: enable_dhcp should be bool [GH-1741]

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_vpc.go, builtin/providers/aws/resource_aws_vpc_dhcp_options.go, builtin/providers/aws/resource_aws_vpc_dhcp_options_association.go, builtin/providers/aws/resource_aws_vpc_dhcp_options_association_test.go, builtin/providers/aws/resource_aws_vpc_dhcp_options_test.go, website/source/docs/providers/aws/r/vpc_dhcp_options.html.markdown, website/source/docs/providers/aws/r/vpc_dhcp_options_association.html.markdown, website/source/layouts/aws.erb
Contributes to #28. Sponsored by ManagedByQ - https://managedbyq.com
Acceptance tests are included. I also did extensive manual testing.
=> providers/aws: Implements DHCP Options Set support.

helper/resource/testing.go, helper/resource/testing_test.go
Also clarified that final return value of testStep is now only for the
happy path.
=> helper/resource/testing: unit tests to cover #1770

command/graph.go, command/meta.go, command/meta_test.go, command/plan.go, command/show.go
Another convienence env var here with TF_MODULE_DEPTH.
Works like you'd expect it to!
=> command: allow module depth to be set via env var

helper/schema/schema_test.go
=> helper/schema: add test for statefunc with nested sets

website/source/docs/providers/aws/r/customer_gateway.html.markdown
noticed a glitch by chance, fixed it
=> Fix indentation, which was causing a rendering error in middleman

helper/schema/resource_data_test.go
Wrote this test to verify behavior, committing and commenting to help me
get the answer faster in the future.
=> helper/schema: add clarifying GetOk test

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_elb.go, builtin/providers/aws/resource_aws_proxy_protocol_policy.go, builtin/providers/aws/resource_aws_proxy_protocol_policy_test.go, builtin/providers/aws/structure.go, website/source/docs/providers/aws/r/proxy_protocol_policy.html.markdown, website/source/layouts/aws.erb
This PR tries to fix #948 and I was inspired by #1685.
If you are okay with this, I'll work on the documentation, thanks.
=> provider/aws: Add proxy protocol support in ELB

builtin/providers/aws/resource_aws_route53_record_test.go
Regression Acceptance Test for #1122 cc @radeksimko
=> provider/aws: Add a regression check for Route 53 records

builtin/providers/aws/resource_aws_vpc_peering_connection.go, website/source/docs/providers/aws/r/vpc_peering.html.markdown
A superset of #1161, rebased on `master`
=> F aws auto vpc peer julienba

builtin/providers/aws/resource_aws_route_table.go, website/source/docs/providers/aws/r/route_table.html.markdown
=> Add Elastic Network Interfaces as route destination

builtin/providers/aws/resource_aws_route_table.go, builtin/providers/aws/resource_aws_route_table_test.go
Should I maybe rebase this on top of #1489?
=> provider/aws: add propagating_vgws to route tables

builtin/providers/docker/resource_docker_image_funcs.go
Added support for more complexly named image repos.
Specifically, images named in the following way did not work the current implementation: private.repo.org:5000/namespace/name:1.0.0
The pull request version supports an optional host with optional port, repo of unbounded numbers of slashes, as well as a an optional tag.
=> Support for more complexly named image repos

builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/resource_aws_s3_bucket_test.go
=> update tests so go vet is happy

builtin/providers/aws/resource_aws_elasticache_cluster.go, website/source/docs/providers/aws/r/elasticache_cluster.html.markdown, website/source/docs/providers/aws/r/elasticache_security_group.html.markdown, website/source/docs/providers/aws/r/elasticache_subnet_group.html.markdown, website/source/layouts/aws.erb
Documenting recent ElastiCache additions
=> provider/aws: Document AWS ElastiCache cluster

CHANGELOG.md
refs: b145ce88b73d2744ddffae8fe1ce01ccf20acbdc
=> [Doc] Added doc about provider/aws/security-group BC break

builtin/providers/aws/resource_aws_db_instance.go
Based on: https://github.com/hashicorp/terraform/pull/1803/files#diff-047ff2782c4a593ae27a5b9bd8ad998fR289
=> Closes #1908. Parse AccountId from User ARN for RDS tags

contrib/api-coverage/aws_api_coverage.rb
quick 'n' dirty - might have some bugs, but it'll get us started
=> contrib: aws api coverage report script

terraform/transform_output.go
Hit the "unflattenable node" error again with these.
This fixes it.
=> core: flatten orphan outputs

website/source/docs/providers/aws/r/iam_access_key.html.markdown, website/source/docs/providers/aws/r/iam_group_policy.html.markdown, website/source/docs/providers/aws/r/iam_instance_profile.html.markdown, website/source/docs/providers/aws/r/iam_role.html.markdown, website/source/docs/providers/aws/r/iam_role_policy.html.markdown, website/source/docs/providers/aws/r/iam_user_policy.html.markdown, website/source/layouts/aws.erb
Closing #1882 + little bit of cleanup.
=> Add docs for aws_iam_role + clean up examples in IAM docs

terraform/transform_expand.go, terraform/transform_provider.go
Same drill as usual - fixes unflattenable module error.
=> core: flatten orphan modules

builtin/providers/aws/resource_aws_s3_bucket.go, terraform/graph_dot.go
These things were annoying the $*!# out of me when running `make test` :-).
=> Fix three trivial errors 'go vet' discovered.

builtin/providers/aws/resource_aws_instance.go, builtin/providers/aws/resource_aws_instance_test.go, website/source/docs/providers/aws/r/instance.html.markdown
=> provider/aws: support ec2 termination protection

builtin/providers/aws/resource_aws_elb.go, builtin/providers/cloudflare/resource_cloudflare_record.go, builtin/providers/dnsimple/resource_dnsimple_record.go
Add some verbosity to error/warnings
=> providers/aws+cloudflare+dnsimple: Increase some verbosity

builtin/providers/aws/resource_aws_route53_zone.go, builtin/providers/aws/resource_aws_route53_zone_test.go, website/source/docs/providers/aws/r/route53_zone.html.markdown
My first piece of golang contribution. Please be gentle :-)
=> Added support for 'comment' field for an AWS route53 zone resource.

builtin/providers/aws/resource_aws_elasticache_subnet_group.go
=> Fix typo, use awslabs/aws-sdk-go

website/source/docs/configuration/interpolation.html.md
This example is derived from @phinze's [work seen here](https://github.com/hashicorp/terraform/issues/1893#issuecomment-100945306).
=> Update interpolation.md, doc pattern combining template_file and count

website/source/docs/providers/aws/r/iam_role_policy.html.markdown
This is a simple one.. Docs were missing a closing }
=> missing a closing } in the example

website/source/docs/providers/aws/r/lb_cookie_stickiness_policy.html.markdown
=> Correct lb_cookie_stickiness_policy example config

website/source/docs/modules/sources.html.markdown
=> docs: clarify ssh git module source syntax

website/source/docs/providers/aws/r/iam_instance_profile.html.markdown, website/source/docs/providers/aws/r/iam_role_policy.html.markdown
The original examples don't work.
=> docs: Fix IAM assume_role_policy examples

examples/aws-count/README.md, examples/aws-two-tier/README.md
Enhanced the README files for the examples to explain how to configure provider specific information how to be able to run the examples
=> Examples readme update

builtin/providers/cloudstack/resource_cloudstack_template.go
=> Cloudstack - allow OVA template upload

helper/schema/set.go
Name of function is Difference, not Differences.
=> Use name of function in comment string

builtin/providers/aws/resource_aws_elb.go, builtin/providers/aws/resource_aws_elb_test.go
=> provider/aws: fix case in ELB listener protocols

website/source/docs/providers/aws/r/s3_bucket.html.markdown
I believe this is a fat finger?
=> Minor correction to aws_s3_bucket docs

builtin/providers/aws/resource_aws_instance.go, builtin/providers/aws/resource_aws_instance_test.go
=> provider/aws: Fix issue with associating KeyPairs with Instances

builtin/providers/aws/resource_aws_instance.go
=> provider/aws: ignore empty vpc_security_group_ids

builtin/providers/docker/resource_docker_image_funcs.go
The regex solution is extremely complex, which makes it hard to debug and understand; the original switches and commenting lay out the various cases in a straightforward fashion. Plus, implementing username/repo support in the original code only needed converting a slice reference into a simple strings.Join call.
=> Put the image parsing code (mostly) back to how it was before

website/source/layouts/aws.erb
[![screen shot 2015-06-13 at 21 13 35](https://cloud.githubusercontent.com/assets/287584/8145839/20b8924e-1211-11e5-84c1-e93f634b7918.png)](https://www.youtube.com/watch?v=_UR-l3QI2nE)
=> aws docs: Sort resources alphabetically

website/source/docs/providers/aws/r/db_instance.html.markdown
=> provider/aws: grammar fix in the db_instance docs.

main.go
Seems to be a refactoring leftover of some kind as on lines 146-148 these calls are done again…
=> core: remove duplicate code

builtin/providers/azure/config.go, builtin/providers/azure/provider.go, builtin/providers/azure/resource_azure_sql_database_server.go, builtin/providers/azure/resource_azure_sql_database_server_test.go, builtin/providers/azure/resource_azure_sql_database_service.go, builtin/providers/azure/resource_azure_sql_database_service_test.go, website/source/docs/providers/azure/r/sql_database_server.html.markdown, website/source/docs/providers/azure/r/sql_database_service.html.markdown, website/source/layouts/azure.erb
Added support, tests and docs for:
* Azure SQL servers
* Azure SQL database services that run on those servers
Any and all reviews are very much appreciated.
=> provider/azure: added Azure SQL server and service support.

builtin/providers/azure/config.go, builtin/providers/azure/provider.go, builtin/providers/azure/resource_azure_affinity_group.go, builtin/providers/azure/resource_azure_affinity_group_test.go, website/source/docs/providers/azure/r/affinity_group.html.markdown, website/source/layouts/azure.erb
Added support, tests and docs for Azure affinity groups.
=> provider/azure: Added affinity group resource.

command/show.go, command/show_test.go
=> core: fix `terraform show` with remote state

builtin/providers/aws/resource_aws_instance.go
=> provider/aws: detect instance_type drift on aws_instance

builtin/providers/aws/resource_aws_security_group_rule.go
Fixes crash in #2431
Decided that `findResourceSecurityGroup` should return an error when
the SG is not found, since the callers cannot happily continue with a
`nil` SG
Also passes through a few error cases that were being swallowed.
/cc @catsby
=> provider/aws: fix sg rule crash

builtin/providers/aws/resource_aws_security_group_rule.go
Fixes #2308 
I think this was already fixed, but this adds another guard to it.
=> providers/aws: more guards against crashy cases [GH-2308]

builtin/providers/openstack/resource_openstack_compute_instance_v2.go
Fixes #2323 
I'm not sure how anything can ever be nil in that array, but let's just guard against it and call it a day. I looked through how the function is called and I don't think this will cause any problems.
=> providers/openstack: fix crash case if network is nil [GH-2323]

examples/aws-elb/README.md, examples/aws-elb/main.tf, examples/aws-elb/outputs.tf, examples/aws-elb/userdata.sh, examples/aws-elb/variables.tf
This example shows creation of ELB, Stickiness policy and related security group. The EC2 instance gets installed with nginx for demonstration.
=> Example of AWS ELB

examples/aws-eip/README.md, examples/aws-eip/main.tf, examples/aws-eip/outputs.tf, examples/aws-eip/userdata.sh, examples/aws-eip/variables.tf
This example creates an EC2 instance, installs nginx and assigns an Elastic IP.
=> AWS Terraform Example for eip

examples/aws-asg/README.md, examples/aws-asg/main.tf, examples/aws-asg/outputs.tf, examples/aws-asg/userdata.sh, examples/aws-asg/variables.tf
Addition to examples - Creation of ASG. The example leverages nginx and ELB to demonstrate the ASG
=> Examples add aws asg

examples/aws-rds/README.md, examples/aws-rds/main.tf, examples/aws-rds/outputs.tf, examples/aws-rds/sg-variables.tf, examples/aws-rds/sg.tf, examples/aws-rds/subnet-variables.tf, examples/aws-rds/subnets.tf, examples/aws-rds/variables.tf
Check README for more details on user/password and options are exposed in variables for postgres / mysql.
=> Terraform example for RDS 

builtin/providers/cloudstack/resource_cloudstack_instance.go
This makes sure we check the right thing.
=> provider/cloudstack: update userdata size check

builtin/providers/aws/resource_aws_autoscaling_group.go
Implements https://github.com/hashicorp/terraform/issues/2324 , allowing users to update Elastic Load Balancers for an AutoScaling Group without re-creating the group
=> provider/aws: Update ASGs to support in-place updates for Load Balancers

rpc/mux_broker.go
As discussed with @mitchellh and @phinze we don’t need to randomize in order to get infinite ID’s. When we hit the highest possible number and add `1` it will just wrap back to `0`, which is just fine with regards to how Terraform works and uses these ID’s.
Tested by setting the initial value of `m.nextId` to `4294967293` where the maximum is `4294967295 ` and then witnessed it wrapping to `0` with some additional logging.
=> core: reverting a few lines from PR #2406

builtin/providers/aws/resource_aws_vpc.go
=> provider/aws: Add validation for aws_vpc.cidr_block

builtin/providers/aws/resource_aws_autoscaling_group.go
Fixes https://github.com/hashicorp/terraform/issues/2509
Credit to @phinze and @mzupan for https://github.com/hashicorp/terraform/pull/2147
=> default_cooldown change shouldnt force new resource

builtin/providers/aws/network_acl_entry.go
=> provider/aws: add ah and esp protocol integers for network acls and sg

builtin/providers/aws/resource_aws_elb.go
http://docs.aws.amazon.com/cli/latest/reference/elb/create-load-balancer.html
=> provider/aws: Add validation for aws_elb.name

builtin/providers/aws/resource_aws_iam_role.go
=> provider/aws: Add validation for aws_iam_role.name

builtin/providers/aws/resource_aws_autoscaling_group.go
=> provider/aws: Add validation for aws_autoscaling_group.name

builtin/providers/aws/resource_aws_launch_configuration.go
=> provider/aws: Add validation for aws_launch_configuration

builtin/providers/aws/resource_aws_db_instance.go
cc @catsby 
https://github.com/hashicorp/terraform/pull/2516/files#r33371338
=> aws: Fix validation for aws_db_instance.identifier

builtin/providers/aws/resource_aws_instance.go
Fixes #1571 
Set the AMI on read.
=> providers/aws: set AMI on read for instance [GH-1571]

builtin/providers/aws/resource_aws_vpc.go
Fixes #1628 
This adds a retry for DependencyViolation on deleting a VPC. A lot of VPC deleting is eventually consistent, so this just makes it wait.
=> provider/aws: vpc delete retry on dependency violation [GH-1628]

website/source/docs/providers/docker/r/container.html.markdown, website/source/docs/providers/docker/r/image.html.markdown
to be set
See https://github.com/hashicorp/terraform/blob/master/builtin/providers/docker/resource_docker_image.go
=> The docker-image resource expects name, not image

builtin/providers/aws/resource_aws_iam_instance_profile.go
https://github.com/boto/botocore/blob/2485f5c/botocore/data/iam/2010-05-08/service-2.json#L8196-L8201
=> provider/aws: Add validation for aws_iam_instance_profile.name

command/push.go, command/push_test.go, website/source/docs/commands/push.html.markdown
Fixes #2373 
This adds the behavior outlined in #2373.
=> command/push: new UX (prefer Atlas over local vars) [GH-2373]

website/source/docs/providers/aws/r/iam_group_membership.html.markdown
Fixed page title and description of IAM Group Membership website Front-matter.
=> website: Fix page title and description of IAM Group Membership website

website/source/docs/providers/aws/r/ecs_service.html.markdown
Fix variable name for aws_iam_role, as per your examples.
cc @radeksimko
=> Fix aws_ecs_service iam_role docs

command/hook_count.go, command/hook_count_test.go
Fix for #2590 
FYI @phinze 
I'm not sure if there's any better way of testing this.
=> core: Return correct number of planned updates

website/source/docs/providers/aws/r/launch_configuration.html.markdown
Fixes https://github.com/hashicorp/terraform/issues/2633
=> provider/aws: Update Launch Configuration docs to reflect required device name

builtin/providers/aws/resource_aws_elasticache_cluster.go, website/source/docs/providers/aws/r/elasticache_cluster.html.markdown
=> provider/aws: Add maintenance window to ElastiCache cluster

website/source/docs/providers/aws/r/db_subnet_group.html.markdown
=> Minor correction to AWS RDS provider docs

builtin/provisioners/chef/linux_provisioner_test.go, builtin/provisioners/chef/resource_provisioner.go, builtin/provisioners/chef/resource_provisioner_test.go, builtin/provisioners/chef/windows_provisioner_test.go, command/counthookaction_string.go, helper/schema/valuetype_string.go, terraform/graphnodeconfigtype_string.go, terraform/instancetype_string.go, terraform/walkoperation_string.go
We should only test the uploaded file, and make sure we also test cases were we do not specify a secrets file
=> provisioner/chef: tweaking the tests

examples/aws-asg/README.md, examples/aws-elb/README.md, examples/aws-rds/README.md
I noticed a few of the docs for the examples had some typos.  I just wanted to fix them.
=> Fixed a few typos

builtin/provisioners/chef/linux_provisioner.go, builtin/provisioners/chef/linux_provisioner_test.go
=> provisioner/chef: fix error when uploading `hints` when using `sudo`

builtin/providers/aws/config.go
@catsby Less if-s, less indentations, less code => happier programmer. :wink:
=> aws: Simplify ValidateCredentials func

builtin/providers/aws/resource_aws_route53_record_test.go, builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/website_endpoint_url_test.go, website/source/docs/providers/aws/r/s3_bucket.html.markdown
Solution for https://github.com/hashicorp/terraform/issues/2208
=> Add website_domain for S3 buckets.

RELEASING.md
Some adjustments after releasing v0.6.1
=> updates for RELEASING

website/source/docs/providers/aws/r/launch_configuration.html.markdown
Hopefully this will help clear up this type of confusion https://github.com/hashicorp/terraform/issues/2958
=> Updating Launch Config Docs for Name attribute

CHANGELOG.md, website/source/docs/configuration/interpolation.html.md
=> More details about math in interpolation

terraform/context_plan_test.go, terraform/eval_check_prevent_destroy.go
per recommendations by @nathanielks
closes #2473
=> update prevent_destroy error message

builtin/providers/aws/resource_aws_elb.go
makes debugging these validation errors much more straightforward
=> provider/aws: add value into ELB name validation message

website/source/docs/providers/aws/r/autoscaling_group.html.markdown
- launch configs use the name and not ID
@catsby
=> use name instead of id

website/source/docs/providers/aws/r/sqs_queue.html.markdown
* Added undocumented `redrive_policy`
* Added link to AWS docs for `visibility_timeout_seconds`
=> Updated AWS_SQS_QUEUE docs

builtin/providers/google/resource_container_cluster.go
related to issue https://github.com/hashicorp/terraform/issues/2901
=> Convert int to int64 when building the cluster.NodeConfig struct

builtin/providers/cloudstack/resource_cloudstack_disk.go, builtin/providers/cloudstack/resource_cloudstack_ipaddress.go, builtin/providers/cloudstack/resource_cloudstack_network.go, builtin/providers/cloudstack/resource_cloudstack_port_forward.go, builtin/providers/cloudstack/resource_cloudstack_vpc.go, website/source/docs/providers/cloudstack/r/disk.html.markdown, website/source/docs/providers/cloudstack/r/ipaddress.html.markdown, website/source/docs/providers/cloudstack/r/network.html.markdown, website/source/docs/providers/cloudstack/r/vpc.html.markdown
- Added a retry loop for attaching disks as this something was tried to fast when the VM was still booting
- Fix issue #3033
- Update docs for latest updates and done some minor refactoring (styling)
=> provider/cloudstack: fix issue #3033 and update tweak several cloudstack resources

builtin/provisioners/chef/resource_provisioner.go
Still not a 100% fix, but that would require some more hacking in core TF. If time permits I’ll have a look at that later on… But for now this is a good fix to be able to close #2872
=> provisioner/chef: fixes issue #2872

builtin/providers/google/provider.go, builtin/providers/google/resource_compute_project_metadata.go, builtin/providers/google/resource_compute_project_metadata_test.go, website/source/docs/providers/google/r/compute_project_metadata.html.markdown, website/source/layouts/google.erb
Hi,
I've implemented the API call for https://cloud.google.com/compute/docs/reference/latest/projects/setCommonInstanceMetadata, as well as written tests and documentation.
Lars
=> GCE project metadata

builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go, builtin/providers/aws/resource_aws_db_subnet_group.go
Bundling some updates for RDS
- d793c6d fixes https://github.com/hashicorp/terraform/issues/3017 
- 22e73d7b fixes #2719
- fc0ccb9 fixes #2392
~~Not ready for merge yet, I think another 3 minor fixes will fit in here~~
=> provider/aws: Updates for RDS

builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/resource_aws_s3_bucket_test.go, website/source/docs/providers/aws/r/s3_bucket.html.markdown
This commit is allows to versioning configuration to S3 bucket resource.
```
resource "aws_s3_bucket" "bucket" {
bucket = "bucket"
acl = "private"
versioning = true
}
```
=> provider/aws: Add versioning option to S3 bucket

builtin/providers/cloudstack/resource_cloudstack_loadbalancer_test.go
This makes the code a little more generic and inline with the other
code. Functionally the same things are tested.
=> provider/cloudstack: small refactor of the CloudStack load balancer tests

builtin/providers/google/resource_compute_project_metadata.go
Fixes a runtime error due to a type mismatch
=> Brought GCE projecte metadata code up to spec with GCE API change

builtin/providers/azure/resource_azure_instance.go, website/source/docs/providers/azure/r/instance.html.markdown
Added support for joining Azure Windows instances to a domain
=> Added join_domain feature to Azure Instance resource

website/source/docs/providers/aws/r/network_interface.markdown
Just a minor typo on docs in website
=> List of security groups should be ID/s not name/s

website/source/404.html.erb
The existing 404 page didn't quite fit in with the style of the rest of the site.
Fixes this by adding a layout value for use during rendering, and adds some nicer markup.
Feel free to suggest modifications and make comments. I didn't include links to the intro,
the docs or the community page since they're already visible in the "inner" layout, and
because I find them sometimes a touch annoying.
=> Update 404 page

builtin/providers/google/resource_compute_instance_template.go
=> provider/gce: Instance Template Network Interface Should be URL

builtin/providers/cloudstack/resource_cloudstack_vpc.go, builtin/providers/cloudstack/resource_cloudstack_vpc_test.go
=> provider/cloudstack: add support for network domains

website/source/docs/providers/aws/r/launch_configuration.html.markdown
These changes were copy/pasted from the aws_instance page
=> fix documentation for aws_launch_configuration block devices

builtin/providers/openstack/resource_openstack_networking_floatingip_v2.go
A couple of notes:
* I didn't write any tests, because I apparently can't even *break* any tests. Whenever I change random test values in `_test.go` files, and run `go test ./...`, all tests still pass. As soon as I manage to get a test-workflow going, I will try my hand at the tests.
* I tested this on my own OpenStack environment, and things work as expected.
* The possibility to actually manage ports is introduced here: #1789
=> OpenStack: add functionality to attach FloatingIP to Port

command/apply.go, command/apply_test.go, command/command_test.go, command/meta.go, command/plan.go, command/refresh.go, command/test-fixtures/parallelism/main.tf
=> add parallelism to ui

builtin/providers/cloudstack/provider_test.go, builtin/providers/cloudstack/resource_cloudstack_disk.go, builtin/providers/cloudstack/resource_cloudstack_egress_firewall.go, builtin/providers/cloudstack/resource_cloudstack_egress_firewall_test.go, builtin/providers/cloudstack/resource_cloudstack_firewall.go, builtin/providers/cloudstack/resource_cloudstack_firewall_test.go, builtin/providers/cloudstack/resource_cloudstack_instance.go, builtin/providers/cloudstack/resource_cloudstack_ipaddress.go, builtin/providers/cloudstack/resource_cloudstack_loadbalancer.go, builtin/providers/cloudstack/resource_cloudstack_loadbalancer_test.go, builtin/providers/cloudstack/resource_cloudstack_network.go, builtin/providers/cloudstack/resource_cloudstack_network_acl.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule_test.go, builtin/providers/cloudstack/resource_cloudstack_nic.go, builtin/providers/cloudstack/resource_cloudstack_port_forward.go, builtin/providers/cloudstack/resource_cloudstack_port_forward_test.go, builtin/providers/cloudstack/resource_cloudstack_secondary_ipaddress.go, builtin/providers/cloudstack/resource_cloudstack_secondary_ipaddress_test.go, builtin/providers/cloudstack/resource_cloudstack_ssh_keypair.go, builtin/providers/cloudstack/resource_cloudstack_template.go, builtin/providers/cloudstack/resource_cloudstack_vpc.go, builtin/providers/cloudstack/resource_cloudstack_vpn_connection.go, builtin/providers/cloudstack/resource_cloudstack_vpn_customer_gateway.go, builtin/providers/cloudstack/resource_cloudstack_vpn_gateway.go, builtin/providers/cloudstack/resources.go
This makes things a little more generic and robust.
=> provider/cloudstack: refactor of the UUID/UnlimitedResourceID logic

builtin/providers/docker/resource_docker_image_test.go
This was continually changing in my environment. Was changes in PR #2619
=> provider/docker: Gofmt change for resource docker_image test

scripts/website_push.sh
Differences on OSX and Linux :frowning: 
/cc @catsby @phinze
=> Apply shopt options to include hidden files

builtin/providers/kubernetes/provider.go, builtin/providers/kubernetes/resource_namespace.go, builtin/providers/kubernetes/resource_persistent_volume.go, builtin/providers/kubernetes/resource_pod.go, builtin/providers/kubernetes/resource_replication_controller.go, builtin/providers/kubernetes/resource_resource_quota.go, builtin/providers/kubernetes/resource_service.go
=> provider/kubernetes: Fixed `no buildable source files` error

website/source/docs/providers/atlas/r/artifact.html.markdown
=> Update docs to show correct launching of atlas artifact in AWS.

builtin/providers/aws/resource_aws_security_group_rule_migrate_test.go
Updates migration test for security group rules introduced in https://github.com/hashicorp/terraform/pull/3019
=> update migration test

builtin/providers/aws/config.go, builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_glacier_vault.go, builtin/providers/aws/resource_aws_glacier_vault_test.go, website/source/docs/providers/aws/r/glacier_vault.html.markdown, website/source/layouts/aws.erb
@radeksimko This is the clean PR of #3169 
This has the rebased commits
Thanks to @mat-mcloughlin for the git help here :)
From the old PR description:
---------------------------------------------------------------
Started to build the resource to create an AWS Glacier Vault
**Please note that I am pretty new to Go and this will take a little while to complete while I learn more about it**
I have added a few basic acceptance tests:
```
terraform [aws-glacier-resource●●] % make testacc TEST=./builtin/providers/aws TESTARGS='-run=GlacierVault' 2>~/tf.log
TF_ACC=1 go test ./builtin/providers/aws -v -run=GlacierVault -timeout 90m
=== RUN TestAccAWSGlacierVault_basic
--- PASS: TestAccAWSGlacierVault_basic (3.31s)
=== RUN TestAccAWSGlacierVault_full
--- PASS: …
```
=> Aws glacier resource merge

website/source/docs/modules/sources.html.markdown
=> doc: module sources from private github repos

builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/resource_aws_s3_bucket_test.go, builtin/providers/aws/resource_aws_vpc_peering_connection_test.go
Small fixes to get our AWS acceptance tests updated and passing
=> Small fixes for acceptance tests

builtin/providers/google/resource_compute_instance.go
In #3501 @lwander got us almost all the way there, but we still had
tests failing. This seemed to be because GCE sets
`metadata.startup-script` to a blank string on instance creation, and if
a user specifies any `metadata` in their config this is seen as the
desired full contents of metadata, so we get a diff trying to remove
`startup-script`.
Here, to address this, we just proactively remove the "startup-script"
key from `Read`, and then we enforce that "metadata_startup_script"
is the only way to configure startup scripts on instances.
=> provider/google: one more fix to GCE metadata

website/source/docs/providers/vsphere/index.html.markdown
Since we merged this so that the community could collaborate on
improvements, I thought it would be prudent to inform potential users of
the status of the provider so they know what to expect.
=> vsphere docs: add warning about possible changes

builtin/providers/google/resource_compute_instance_group_manager.go
Addresses issue here: #3591 
If the delete request fails due a timeout, the code waits again as a long as the number of live instances in the instance group is shrinking. 
@sparkprime
=> provider/google: Fixed timeout bug on large instance groups

builtin/providers/google/config.go
UserAgent shows Terraform Version number for GCP requests.
=> provider/google: Accurate Terraform Version

scripts/dist.sh
=> Use hc-releases

.travis.yml
See also: https://github.com/hashicorp/terraform/commit/af04321723200d4cb4158e7e9a6b1f8b9f6aaf1b
=> travis: build with go 1.5 now

website/source/docs/providers/vsphere/index.html.markdown
=> website: document vsphere acctest instructions

command/apply_test.go, command/test-fixtures/parallelism/main.tf, terraform/graph_walk_context.go, terraform/resource_provider_mock.go
Thanks to @mitchellh for helping sort out concurrency stuff here.
=> command: fix flaky parallelism tests

builtin/providers/digitalocean/resource_digitalocean_droplet.go
fix issue #3628 by accepting SSH fingerprints
=> provider/digitalocean: fix issue #3628 by accepting SSH fingerprints

website/source/docs/providers/aws/r/autoscaling_group.html.markdown
=> docs: Updating the ASG docs to suggest health_check_grace_period is a required field under certain circumstances

builtin/providers/google/provider.go, builtin/providers/google/resource_compute_global_forwarding_rule.go, builtin/providers/google/resource_compute_global_forwarding_rule_test.go, website/source/docs/providers/google/r/compute_global_forwarding_rule.html.markdown, website/source/layouts/google.erb
Implements global forwarding rule resource
*Do not merge until HTTP(s) target proxies are in!*
=> provider/google: global forwarding rule tests & documentation

builtin/providers/vsphere/resource_vsphere_virtual_machine.go
Hi, 
This PR fix #3559 and #3560, when a template is cloned we deleted all the interfaces so the createNetworkInterfaces will work correctly. 
Regards.
=> Vsphere_virtual_machine: Network interfaces

website/source/docs/providers/vsphere/index.html.markdown, website/source/docs/providers/vsphere/r/virtual_machine.html.markdown, website/source/layouts/docs.erb, website/source/layouts/vsphere.erb
To help with Googling (e.g. _terraform vmware_), change all occurrences of 'vSphere' to 'VMware vSphere'.
=> docs: Change vSphere to VMware vSphere

website/source/docs/providers/aws/r/rds_cluster_instance.html.markdown
I'm bringing in the big pull requests now...
=> Typo in docs - AWS RDS config

config/loader.go, config/loader_hcl.go
**DO NOT MERGE YET: Upstream HCL isn't updated yet, this is just staging the changes.**
This updates the HCL parsers to the new API. The tests are unchanged and verify the functionality.
=> Use new HCL API

website/source/docs/providers/aws/index.html.markdown
This tripped me up today when I was trying to connect using MFA. I had a look at the source and found the token property, tested it out and low and behold it worked! 
Hopefully this saves someone else going through the same pain
=> Change the docs as the token can be explicitly set

command/plan.go, command/plan_test.go
Also adds a regression test using Mock UI. Fixes #3767.
=> Prompt for input variables before context validate

builtin/providers/aws/resource_aws_iam_saml_provider.go
fixes https://github.com/hashicorp/terraform/issues/3820
=> provider/aws: Set previously missing ARN in iam_saml_provider

website/source/docs/providers/aws/r/db_instance.html.markdown
=> Document `license_model` as supported argument

builtin/providers/aws/resource_aws_sns_topic.go
Builds of of #3751, thanks @bobtfish ! 
- removes `ForceNew: false`
- return `""` if `v` is nil in StateFunc
=> provider/aws: fix panic with SNS topic policy if omitted

builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook.go
This is a brute force way of fixing #3648, trapping a very specific error condition. We could loosen the error condition, and just retry on `ValidationError`, if we felt that better.
=> provider/aws: Add a retry function to rescue an error in creating Lifecycle Hooks

builtin/providers/aws/resource_aws_ecs_service.go
fixes https://github.com/hashicorp/terraform/issues/3582
=> provider/aws: Treat ecs_service w/ Status==INACTIVE as deleted

builtin/providers/google/provider.go, builtin/providers/google/resource_compute_https_health_check.go, builtin/providers/google/resource_compute_https_health_check_test.go, website/source/docs/providers/google/r/compute_https_health_check.html.markdown, website/source/layouts/google.erb
=> provider/google: HTTPS Health Checks Resource + Tests & Documentation

builtin/providers/aws/resource_aws_s3_bucket_object.go
=> provider/aws: homedir expand in s3 object source

builtin/providers/aws/resource_aws_db_subnet_group.go, builtin/providers/aws/resource_aws_db_subnet_group_test.go
=> allow spaces in db subnet name

website/source/docs/providers/template/r/file.html.md
Fixes https://github.com/hashicorp/terraform/pull/3909#discussion_r45133843
=> docs: fix template_file syntax error

builtin/providers/aws/resource_aws_elasticache_cluster.go, builtin/providers/aws/resource_aws_flow_log_test.go
Fixes to some of our failing tests
=> AWS Test fixtures updates

website/source/assets/stylesheets/_footer.scss
fix for https://github.com/hashicorp/terraform/issues/4026
=> fix edit this page stacking

website/source/docs/providers/aws/r/instance.html.markdown, website/source/docs/providers/aws/r/spot_instance_request.html.markdown
Add docs to Spot Instance, update Instances to be more verbose
=> provider/aws: Update Instance/Spot docs for IP information

scripts/dist.sh
Create and sign a signature file. Lifted from [Vault][1]
[1]: https://github.com/hashicorp/vault/blob/master/scripts/dist.sh
=> Update scripts/dest.sh to create a sig file

website/source/docs/providers/atlas/r/artifact.html.markdown
This will be uniform across Packer, Terraform, and Atlas.
=> Change amazon.ami to amazon.image

builtin/providers/digitalocean/resource_digitalocean_floating_ip.go
Build was broken, needed to use %d instead of %s :smile:
=> updating printf formating to correct syntax with int

builtin/providers/cloudstack/resource_cloudstack_egress_firewall.go, builtin/providers/cloudstack/resource_cloudstack_firewall.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule.go
All test still pass, but the updated logic makes a whole lot less API calls.
=> provider/cloudstack: improve performance for all firewall related resources

command/flag_kv_test.go, terraform/context_apply_test.go, terraform/test-fixtures/apply-map-var-override/main.tf
tests to cover the HCL-level issue fixed in
https://github.com/hashicorp/hcl/pull/65
=> core: test coverage around map key regression

builtin/providers/aws/resource_aws_db_instance.go
=> Issue #3894 RDS publicly_accessible param shouldn't force new resource

builtin/bins/provider-statuscake/main.go, builtin/providers/statuscake/provider.go, builtin/providers/statuscake/provider_test.go, builtin/providers/statuscake/resource_statuscaketest.go, builtin/providers/statuscake/resource_statuscaketest_test.go
Provider for [statuscake](https://www.statuscake.com/)
This provider will allow the addition / modification and deletion of tests via the statuscake API. This has *very* limited functionality for the first release. but it will continue to be enhanced
=> StatusCake Provider

website/source/docs/providers/aws/r/route53_health_check.html.markdown
Correct mistype for route53_health_check
=> docs: Correct mistype route53_health_check

config/loader_test.go, config/test-fixtures/heredoc.tf
This should be fixed upstream by hashicorp/hcl#66
=> Add failing test replicating #4065

website/source/layouts/aws.erb
=> provider/aws: Documentation layout update for aws_route

builtin/providers/aws/resource_aws_iam_role.go
Changing the IAM Role resource to allow update of Assume Policy Document
Fixes #3106 - tests all still pass:
```hcl
make testacc TEST=./builtin/providers/aws TESTARGS='-run=AWSRole_' 2>~/tf.log
TF_ACC=1 go test ./builtin/providers/aws -v -run=AWSRole_ -timeout 90m
=== RUN   TestAccAWSRole_basic
--- PASS: TestAccAWSRole_basic (5.14s)
=== RUN   TestAccAWSRole_testNameChange
--- PASS: TestAccAWSRole_testNameChange (11.58s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	16.735s
```
=> provider/aws: IAM Role now Allows Update Assume Policy Document

website/source/docs/modules/usage.html.markdown
get -u does not work the name is -update.
=> change get -u option get -update

config/loader_test.go, config/test-fixtures/heredoc.tf
Should help cover terraform against regression once
https://github.com/hashicorp/hcl/pull/70 lands.
=> config: test replicating #4079

builtin/providers/vsphere/config.go, builtin/providers/vsphere/provider.go, builtin/providers/vsphere/provider_test.go, website/source/docs/providers/vsphere/index.html.markdown
This fixes https://github.com/hashicorp/terraform/issues/3522.
=> provider/vsphere: rename vcenter_server config parameter to something clearer

website/source/docs/providers/google/r/pubsub_subscription.html.markdown
=> provider/google: Added missing pubsub documentation

website/source/docs/providers/aws/r/db_instance.html.markdown
fixes: #4205
Documenting the version upgrade flags on db_instance
=> provider/aws: DB_Instance Documentation update

website/source/docs/providers/vsphere/index.html.markdown, website/source/docs/providers/vsphere/r/virtual_machine.html.markdown
I think most users of VMware vSphere creates a new virtual machine by deploying a template. So, I'd like to update the default example.
=> provider/vsphere: Update a default example in VMware vSphere provider

builtin/providers/openstack/resource_openstack_blockstorage_volume_v1.go
This commit prevents Terraform from erroring when an attempt is made
to delete a volume already in a "deleting" state. This can happen when
the volume is the root disk of an instance and the instance was
terminated.
Fixes #4195 
Fixes #4110
=> provider/openstack: Handle volumes in "deleting" state

builtin/providers/aws/resource_aws_instance.go
=> provider/aws: Handle empty Instances response from RunInstances

builtin/providers/aws/hosted_zones.go
=> providers/aws: Update Hosted Zones to fix issue with eu-central

builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook_test.go, builtin/providers/aws/resource_aws_autoscaling_notification_test.go, builtin/providers/aws/resource_aws_autoscaling_policy_test.go, builtin/providers/aws/resource_aws_cloudformation_stack_test.go, builtin/providers/aws/resource_aws_instance_migrate.go, builtin/providers/aws/resource_aws_instance_test.go, builtin/providers/aws/resource_aws_key_pair_migrate.go, builtin/providers/aws/resource_aws_launch_configuration_test.go, builtin/providers/aws/resource_aws_route.go, builtin/providers/aws/resource_aws_security_group_rule_migrate.go, builtin/providers/aws/resource_aws_vpc_dhcp_options.go
This PR includes minor updates to make `go vet` happy. I've ran the relevant acceptance tests, but would like to hold of for 0.6.9/0.7.0 release (don't merge right away)
=> Small updates to AWS provider to make go vet happy

config/loader_hcl.go, config/loader_test.go, config/test-fixtures/resource-arity-mistake.tf
=> config: friendlier error message on resource arity mismatch

helper/resource/testing.go
In the acceptance testing framework, it is neccessary to provide a copy of the state _before_ the destroy is applied to the check in order that it can loop over resources to verify their destruction. This patch makes a deep copy of the state prior to applying test steps which have the Destroy option set and then passes that to the destroy check.
=> testing: Use a copy of pre-destroy state in destroy check

builtin/providers/aws/resource_aws_elasticache_cluster.go, builtin/providers/aws/resource_aws_elasticache_cluster_test.go
Fixes #3604 
Assuptions:
*We always remove the higher numbered nodes from the cache cluster*
I.e. If we are changing from a 2 node cluster to a 1 node cluster then we remove node_id 0002
If we are changing from a 5 node cluster to a 3 node cluster then we remove node_ids 0005 and 0004
=> provider/aws: Ability to reduce nodes in an ElastiCache cluster

website/source/docs/providers/aws/r/elasticache_cluster.html.markdown
Adds a note to the documentation about the feature implemented in #3809.
=> provider/aws: Add note about cluster size reduction

website/source/docs/providers/google/index.html.markdown
Updating documentation to reflect new Google Developers Console UI. Addresses issue in #4177
=> provider/google: Update docs for acquiring service account credentials

builtin/providers/google/resource_pubsub_subscription.go, builtin/providers/google/resource_pubsub_topic.go
Sorry but these keep showing up on my development branch so I need to fix them
=> Fixing gofmt errors

website/source/docs/providers/google/r/container_cluster.html.markdown
Addresses concerns found in #3681
=> provider/google: Improve Container Scope Example Documentation

builtin/providers/aws/resource_aws_s3_bucket.go
Reference #4103 for errors and background, this fix uses current pattern. Retry `MalformedPolicy` errors on S3 bucket policy apply for 1 minute to ensure that errors are not due to newly created IAM resources.
=> aws_s3_bucket: Retry MalformedPolicy errors due to newly created principals

builtin/providers/openstack/devstack/deploy.sh, website/source/docs/providers/openstack/index.html.markdown
This commit includes a script to deploy a standardized devstack environment
for use with development and testing.
=> provider/openstack: DevStack Deploy Script

builtin/providers/openstack/resource_openstack_compute_instance_v2.go, builtin/providers/openstack/resource_openstack_compute_instance_v2_test.go
This change better reflects how block devices are passed to the Nova API
and allows for future enablement of block_device features. It also resolves
an interpolation bug.
Fixes #4090
=> provider/openstack: Convert block_device from TypeSet to TypeList

examples/aws-rds/main.tf
I was getting "unknown slice type: *ast.LiteralType" before making this change.
=> Use [] around depends_on value.

Makefile, builtin/providers/aws/resource_aws_db_instance_test.go, builtin/providers/aws/resource_aws_dynamodb_table.go, builtin/providers/aws/resource_aws_security_group.go, builtin/providers/aws/resource_aws_security_group_test.go, builtin/providers/digitalocean/resource_digitalocean_record.go, builtin/providers/vsphere/resource_vsphere_folder.go, builtin/providers/vsphere/resource_vsphere_folder_test.go, builtin/providers/vsphere/resource_vsphere_virtual_machine.go, builtin/providers/vsphere/resource_vsphere_virtual_machine_test.go, scripts/build.sh, scripts/gofmtcheck.sh
Also adds a Makefile target `fmt` to run `gofmt` with the required options.
=> Fail builds if gofmt reports non-compliance

builtin/providers/aws/resource_aws_vpc_endpoint.go
vpc_endpoint bug fix.
https://github.com/hashicorp/terraform/issues/4137
=> providers_aws_vpce issue #4137

builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream.go, builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream_test.go
As I was fixing up the AccTests to not depend on a single existing IAM
role (which this commit does), I noticed that without some sleeping that
the kinesis_firehose_delivery_stream would often come back with:
```
msg: Firehose is unable to assume role {{arn}}. Please check the role provided.
code: InvalidArgumentException
```
Similar to the strategy taken in aws_instance with IAM Instance Profile errors,
I dropped in a simple retry loop which seemed to take care of the issue. Seems
that the same permission propagation delays apply here too.
=> provider/aws: kinesis firehose stream: retry through IAM propagation

builtin/providers/aws/resource_aws_spot_instance_request_test.go
Fixes failing Spot Instance request tests by making sure the request is in the cancelled state
=> provider/aws: Update tests destroy checks

builtin/providers/aws/resource_aws_vpc_endpoint_test.go, builtin/providers/aws/resource_aws_vpc_peering_connection_test.go, builtin/providers/aws/resource_aws_vpn_connection_test.go
still more to come, just starting the PR early..
=> VPC Endpoint test updates

website/source/intro/getting-started/install.html.markdown
Added example commands for setting environment paths in Linux/Unix and Windows.
=> Update install.html.markdown to include examples for $PATH

website/source/assets/stylesheets/_docs.scss, website/source/docs/providers/terraform/index.html.markdown, website/source/docs/providers/terraform/r/remote_state.html.md, website/source/docs/state/remote.html.md, website/source/layouts/docs.erb, website/source/layouts/terraform.erb
=> Add Terraform/Remote State documentation to provider/resource section.

website/source/docs/providers/openstack/r/lb_pool_v1.html.markdown
updating docs to match behavior of the code for admin_state_up
=> provider/openstack: Update lb_pool_v1.html.markdown

website/source/intro/getting-started/build.html.md
This just helps it stay consistent across the doc.
=> Update Build documentation to use t2.micro

website/source/docs/providers/aws/r/sns_topic.html.markdown
=> provider/aws: Document `display_name` on SNS Topic

website/source/docs/providers/do/r/droplet.html.markdown
=> provider/digitalocean: Document defaults

builtin/providers/aws/resource_aws_directory_service_directory.go, builtin/providers/aws/resource_aws_directory_service_directory_test.go, builtin/providers/aws/resource_aws_dynamodb_table.go, builtin/providers/aws/resource_aws_dynamodb_table_test.go
Updates for acceptance tests, mostly around the `CheckDestroy` acceptance test methods
=> provider/aws:Updating AWS Acceptance tests

builtin/providers/aws/resource_aws_vpn_gateway_test.go
Update `testAccCheckVpnGatewayDestroy` method to correctly check if the gateway is destroyed
=> providers/aws: Update VPN Gateway test

builtin/providers/google/resource_compute_firewall_test.go, builtin/providers/google/resource_compute_global_forwarding_rule_test.go, builtin/providers/google/resource_compute_instance_group_manager_test.go, builtin/providers/google/resource_compute_instance_test.go, builtin/providers/google/resource_compute_target_http_proxy_test.go, builtin/providers/google/resource_dns_record_set_test.go, builtin/providers/google/resource_sql_database_test.go
Fix tests that failed as a result of #4516 
@phinze, I got all tests to work locally after making changes that failed in the last Travis run, with the exception of [this one](https://travis-ci.org/hashicorp/terraform/jobs/100462877#L498), which I was never able to make fail in the first place. Maybe it was a transient error?
=> provider/google: Limit hardcoded test resource names

builtin/providers/heroku/resource_heroku_app.go, builtin/providers/heroku/resource_heroku_app_test.go
This is a rebase of #668 with an acceptance test and updates to make it conform to modern standards.
=> Heroku Organization App Improvements

builtin/providers/azurerm/config.go
=> provider/azurerm: Set user agent

builtin/providers/azurerm/provider.go, builtin/providers/azurerm/resource_arm_security_group.go, builtin/providers/azurerm/resource_arm_security_group_test.go, website/source/docs/providers/azurerm/r/security_group.html.markdown, website/source/layouts/azurerm.erb
@jen20: Adds [Network Security Group](https://msdn.microsoft.com/en-us/library/mt163615.aspx)
```
make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=AzureRMSecurityGroup' 2>~/tf.log
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=AzureRMSecurityGroup -timeout 90m
=== RUN   TestResourceAzureRMSecurityGroupProtocol_validation
--- PASS: TestResourceAzureRMSecurityGroupProtocol_validation (0.00s)
=== RUN   TestResourceAzureRMSecurityGroupAccess_validation
--- PASS: TestResourceAzureRMSecurityGroupAccess_validation (0.00s)
=== RUN   TestResourceAzureRMSecurityGroupDirection_validation
--- PASS: TestResourceAzureRMSecurityGroupDirection_validation (0.00s)
=== RUN   TestAccAzureRMSecurityGroup_basic
--- …
```
=> provider/azurerm: add security group

builtin/providers/aws/resource_aws_kinesis_stream.go
Each call to the Kinesis DescribeStream API returns a limited number of shards. When interrogating AWS for the state of a Kinesis stream, the client needs to page through the API's responses to get the true number of shards.
The default account limit in Kinesis is 10 shards per region, so it's difficult to write a useful acceptance test for this, but I have an (production) account with a limit set much higher, and I've confirmed that this code correctly collects all shards.
=> provider/aws: Kinesis DescribeStream pagination

builtin/providers/aws/resource_aws_opsworks_stack_test.go, builtin/providers/aws/resource_aws_vpc_peering_connection_test.go
- `TestAccAWSVPCPeeringConnection_basic` will now pass
- `TestAccAWSOpsworksStackNoVpc` willl now pass
- `TestAccAWSOpsworksStackVpc` willl now pass
- https://travis-ci.org/hashicorp/terraform/builds/100697426
=> provider/aws: Update acceptance tests

website/source/layouts/chef.erb
=> fix typo in chef docs sidebar

builtin/providers/azurerm/resource_arm_availability_set_test.go, builtin/providers/azurerm/resource_arm_network_security_group.go, builtin/providers/azurerm/resource_arm_network_security_group_test.go, builtin/providers/azurerm/resource_arm_public_ip.go, builtin/providers/azurerm/resource_arm_public_ip_test.go, builtin/providers/azurerm/resource_arm_virtual_network.go, builtin/providers/azurerm/resource_arm_virtual_network_test.go
More fixes for breaking changes introduced in:
https://github.com/Azure/azure-sdk-for-go/pull/258
=> provider/azurerm: Additional fixes for upstream breaking changes

builtin/provisioners/chef/linux_provisioner.go, builtin/provisioners/chef/linux_provisioner_test.go
This small tweak fixes #4262 by making sure files can be uploaded
correctly.
=> provisioner/chef: fixes #4262

builtin/providers/openstack/resource_openstack_networking_port_v2.go
Addresses [Issue 4541](https://github.com/hashicorp/terraform/issues/4541)
=> Fix to not put fixed_ip in request if not defined

builtin/providers/aws/resource_aws_security_group_rule.go
This addresses the case where `compact` has not been used on a list passed into security group as cidr_block. See #3786 for an actual example.
Compact is still the correct answer there, but we should prefer returning an error to a panic - so fixes #3786.
I'm not sure of a good way to test this change using the provider framework - if anyone has any good ideas on that please share!
=> provider/aws: error with empty list item on security group

examples/aws-asg/main.tf
Lost a little while figuring out why this example wouldn't work, seems you need to use id, not name :)
=> Fix auto scaling example to use ID rather than name

website/source/docs/providers/vcd/index.html.markdown
Took me a little bit to work out what I was supposed to use.
=> Specify an example url for vCloud Director provider

builtin/providers/aws/resource_aws_ecs_service.go, builtin/providers/azurerm/resource_arm_availability_set.go
Fixes `make dev` / `make test`
=> Go fmt updates

website/source/intro/getting-started/dependencies.html.md, website/source/intro/getting-started/provision.html.md, website/source/intro/getting-started/variables.html.md
Supersedes #4626 (had to fix some merge conflicts)
=> Changes AMI to be non-hvm, matching the one used in earlier pages

builtin/providers/google/resource_compute_instance.go, website/source/docs/providers/google/r/compute_instance.html.markdown, website/source/docs/providers/google/r/dns_record_set.markdown
=> provider/google: provide assigned_nat_ip as well as nat_ip

builtin/providers/google/provider.go, builtin/providers/google/resource_sql_user.go, builtin/providers/google/resource_sql_user_test.go, website/source/docs/providers/google/r/sql_user.html.markdown, website/source/layouts/google.erb
=> provider/google: SQL user resource, documentation & tests

builtin/providers/docker/provider.go, builtin/providers/docker/resource_docker_container.go, builtin/providers/docker/resource_docker_container_funcs.go, builtin/providers/docker/resource_docker_network.go, builtin/providers/docker/resource_docker_network_funcs.go, builtin/providers/docker/resource_docker_network_test.go, website/source/docs/providers/docker/r/container.html.markdown, website/source/docs/providers/docker/r/network.html.markdown, website/source/layouts/docker.erb
=> provider/docker: Add support of custom networks

dag/graph.go, dag/graph_test.go
This adds HasVertex and HasEdge as quick checks for the presence of an edge or vertex. Tests present.
I need this for Otto and this doesn't affect any other TF behavior so I'll merge ASAP, but happy to get a review.
=> dag: add HasVertex, HasEdge

builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook.go, builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook_test.go, website/source/docs/providers/aws/r/autoscaling_lifecycle_hooks.html.markdown
Fixes: #4572
Change ASG Lifecycle Default Result to be computed and added a test to record what the default value is
=> provider/aws: ASG Lifecycle Hook Default Result

builtin/providers/template/resource_cloudinit_config.go, builtin/providers/template/resource_cloudinit_config_test.go
=> provider/template: Allow update in `template_cloudinit_config`

examples/aws-eip/README.md
Seems like a typo in the example code.
=> Removed the extra Braces

examples/aws-eip/README.md, examples/aws-rds/README.md
Corrected a typo and make another readme a bit more github friendly.
=> Typo correction and readability

builtin/providers/cloudstack/resource_cloudstack_egress_firewall.go, builtin/providers/cloudstack/resource_cloudstack_firewall.go, builtin/providers/cloudstack/resource_cloudstack_network_acl_rule.go, builtin/providers/cloudstack/resources.go
Without this additional check it could happen that one of the firewall resources would panic if given an unexpected port value.
=> provider/cloudstack: add a check to see if the port value is valid

builtin/providers/aws/resource_aws_elastic_beanstalk_application.go, builtin/providers/aws/resource_aws_elastic_beanstalk_configuration_template.go, builtin/providers/aws/resource_aws_elastic_beanstalk_configuration_template_test.go, builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
@catsby after the most recent merge from master for #3157 the tests have been failing with the following
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=Beanstalk -timeout 120m
=== RUN   TestAccAWSBeanstalkApp_basic
--- FAIL: TestAccAWSBeanstalkApp_basic (5.14s)
testing.go:169: Error destroying resource! WARNING: Dangling resources
Error: Check failed: Elastic Beanstalk Application still exists.
State: <no state>
=== RUN   TestAccAWSBeanstalkConfigurationTemplate_basic
--- FAIL: TestAccAWSBeanstalkConfigurationTemplate_basic (7.73s)
testing.go:169: Error destroying resource! WARNING: Dangling resources
Error: Check failed: Elastic Beanstalk Application still exists.
State: <no …
```
=> provider/aws: Elastic Beanstalk tests failing.

builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go
In the default configuration (ie. `aws:elb:loadbalancer:ManagedSecurityGroup` is left unset), Elastic Beanstalk automatically creates one security group per environment to allow ingress (port 80 & 22 by default). This causes terraform to detect a change in security groups every time, even though the configuration didn't change.
This looks up the names of the security groups returned by Elastic Beanstalk and excludes the automatically generated security group.
Adds to https://github.com/hashicorp/terraform/pull/3157
@catsby @dharrisio
=> Fix security group problem

builtin/providers/cloudstack/resource_cloudstack_network.go, builtin/providers/cloudstack/resource_cloudstack_network_test.go, builtin/providers/cloudstack/tags.go, builtin/providers/cloudstack/tags_test.go
Just some cosmetics and some cleaning up to make the code fit in a little better with the existing code. Functionally no changes are made and the existing tests still pass.
=> provider/cloudstack: policing up the new `tags` code from @Carles-Figuerola

builtin/providers/aws/resource_aws_elb.go
From https://travis-ci.org/hashicorp/terraform/jobs/104548434 .
Should fix flappiness of `TestAccAWSELB_iam_server_cert` test. I was able to reproduce this error, though only about 1 out of 7 times.
=> provider/aws: Retry Listener Creation for ELBs

builtin/providers/aws/resource_aws_efs_file_system_test.go, builtin/providers/aws/resource_aws_efs_mount_target_test.go
Updates EFS tests to correctly check in the destroy method
=> provider/aws: Update EFS test destroy methods

builtin/providers/azurerm/provider.go
Using EnvDefaultFunc with a default of empty string causes the validation which would ordinarily be performed by `Required: true` in the schema to not have any effect. Instead validate the configuration used to produce the ARM client before attempting to use it during provider configuration.
=> provider/azurerm: Fix panic if no creds supplied

builtin/providers/docker/resource_docker_container_funcs.go
Missed a potential error in the network management in docker.
=> provider/docker: Catch potential custom network errors in docker

website/source/docs/providers/docker/r/container.html.markdown, website/source/docs/providers/docker/r/image.html.markdown, website/source/docs/providers/docker/r/network.html.markdown, website/source/docs/providers/docker/r/volume.html.markdown
- Use a consistent format
- Remove typos
- Specify the expected parameter type for each entry
- Change importance of block documentation
=> provider/docker: Update documentation

builtin/providers/openstack/resource_openstack_networking_port_v2.go, website/source/docs/providers/openstack/r/networking_port_v2.html.markdown
IMO, ResourceData can't handle list of native structure.
=> provider/openstack Convert FixedIPS from struct to map for ResourceData

Godeps/Godeps.json, builtin/providers/azurerm/config.go, builtin/providers/azurerm/provider.go, builtin/providers/azurerm/resource_arm_dns_zone.go, builtin/providers/azurerm/resource_arm_dns_zone_test.go, vendor/github.com/jen20/riviera/LICENSE.md, vendor/github.com/jen20/riviera/azure/api.go, vendor/github.com/jen20/riviera/azure/apicall.go, vendor/github.com/jen20/riviera/azure/azureerror.go, vendor/github.com/jen20/riviera/azure/client.go, vendor/github.com/jen20/riviera/azure/create_resource_group.go, vendor/github.com/jen20/riviera/azure/credentials.go, vendor/github.com/jen20/riviera/azure/delete_resource_group.go, vendor/github.com/jen20/riviera/azure/locations.go, vendor/github.com/jen20/riviera/azure/register_resource_provider.go, vendor/github.com/jen20/riviera/azure/request.go, vendor/github.com/jen20/riviera/azure/response.go, vendor/github.com/jen20/riviera/azure/token.go, vendor/github.com/jen20/riviera/azure/utils.go, vendor/github.com/jen20/riviera/dns/api.go, vendor/github.com/jen20/riviera/dns/create_dns_zone.go, vendor/github.com/jen20/riviera/dns/delete_dns_zone.go, vendor/github.com/jen20/riviera/dns/get_dns_zone.go, website/source/docs/providers/azurerm/r/dns_zone.html.markdown, website/source/layouts/azurerm.erb
This resource is the first which makes use of the new Riviera library (at https://github.com/jen20/riviera), so there is some additional set up work to add the provider to the client which gets passed among resources.
=> provider/azurerm: Add `azurerm_dns_zone` resource

Godeps/Godeps.json, builtin/providers/azurerm/provider.go, builtin/providers/azurerm/resource_arm_sql_database.go, builtin/providers/azurerm/resource_arm_sql_database_test.go, vendor/github.com/jen20/riviera/azure/apicall.go, vendor/github.com/jen20/riviera/azure/client.go, vendor/github.com/jen20/riviera/azure/create_resource_group.go, vendor/github.com/jen20/riviera/azure/delete_resource_group.go, vendor/github.com/jen20/riviera/azure/register_resource_provider.go, vendor/github.com/jen20/riviera/azure/request.go, vendor/github.com/jen20/riviera/dns/create_dns_zone.go, vendor/github.com/jen20/riviera/dns/delete_dns_zone.go, vendor/github.com/jen20/riviera/dns/get_dns_zone.go, vendor/github.com/jen20/riviera/sql/create_elastic_database_pool.go, vendor/github.com/jen20/riviera/sql/create_or_update_database.go, vendor/github.com/jen20/riviera/sql/create_or_update_firewall_rule.go, vendor/github.com/jen20/riviera/sql/create_or_update_server.go, vendor/github.com/jen20/riviera/sql/delete_database.go, vendor/github.com/jen20/riviera/sql/delete_elastic_database_pool.go, vendor/github.com/jen20/riviera/sql/delete_firewall_rule.go, vendor/github.com/jen20/riviera/sql/delete_server.go, vendor/github.com/jen20/riviera/sql/get_database.go, vendor/github.com/jen20/riviera/sql/get_firewall_rule.go, vendor/github.com/jen20/riviera/sql/get_server.go, website/source/docs/providers/azurerm/r/sql_database.html.markdown, website/source/docs/providers/azurerm/r/sql_server.html.markdown, website/source/layouts/azurerm.erb
Test Results:
```
make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=AzureRMSqlDatabase' 2>~/tf.log
/Users/stacko/Code/go/bin/stringer
GO15VENDOREXPERIMENT=1 go generate $(GO15VENDOREXPERIMENT=1 go list ./... | grep -v /vendor/)
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/azurerm -v -run=AzureRMSqlDatabase -timeout 120m
=== RUN   TestResourceAzureRMSqlDatabaseEdition_validation
--- PASS: TestResourceAzureRMSqlDatabaseEdition_validation (0.00s)
=== RUN   TestAccAzureRMSqlDatabase_basic
--- PASS: TestAccAzureRMSqlDatabase_basic (335.56s)
=== RUN   TestAccAzureRMSqlDatabase_withTags
--- PASS: TestAccAzureRMSqlDatabase_withTags (466.84s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm …
```
=> provider/azurerm: Adding azurerm_sql_database resource

website/source/intro/hashicorp-ecosystem.html.markdown
Was leading to a 404. Love this page!
=> Fix trailing slash in Atlas Mindset URL

Godeps/Godeps.json, vendor/github.com/hashicorp/hil/lang.y, vendor/github.com/hashicorp/hil/parse.go, vendor/github.com/hashicorp/hil/y.go, vendor/github.com/hashicorp/hil/y.output
Related to https://github.com/hashicorp/terraform/pull/5038
=> Update vendored hashicorp/hil

command/validate.go, command/validate_test.go
=> Fixing some golint issues on the new validate command

website/source/docs/providers/aws/r/launch_configuration.html.markdown
=> Fix a typo: "encryption" to "encrypted"

website/source/docs/providers/aws/r/instance.html.markdown
missing explicit mentioning of the value type.
=> aws_instance docs

website/source/docs/providers/google/r/compute_route.html.markdown
=> provider/google: Route doc zone update

website/source/docs/providers/google/r/compute_instance_template.html.markdown
=> provider/google: Fix documentation around GCE Disk Type

website/source/docs/providers/vcd/r/vapp.html.markdown
This is updated documentation for changed behaviour in the downstream vcd provider.
https://github.com/hmrc/vmware-govcd/pull/3
=> provider/vcd - Update doco for ip enhancements in vmware-govcd

builtin/providers/aws/resource_aws_db_instance_test.go, builtin/providers/aws/resource_aws_directory_service_directory.go, builtin/providers/aws/resource_aws_iam_group_membership_test.go, builtin/providers/aws/resource_aws_rds_cluster_instance_test.go
Should help alleviate any name conflicts in the nightly tests
=> provider/aws: Update some tests to introduce more randomization

website/source/docs/providers/azurerm/r/network_interface.html.markdown
=> provider/azurerm: Documentation update for `azurerm_network_interface`

Godeps/Godeps.json, Makefile, builtin/providers/aws/resource_aws_cloudtrail_test.go, builtin/providers/aws/resource_aws_iam_group_membership_test.go, builtin/providers/azure/resource_azure_sql_database_server_test.go, builtin/providers/azure/resource_azure_sql_database_service_test.go, builtin/providers/digitalocean/resource_digitalocean_floating_ip_test.go, builtin/providers/digitalocean/resource_digitalocean_ssh_key_test.go, builtin/providers/google/resource_pubsub_subscription_test.go, builtin/providers/google/resource_pubsub_topic_test.go, builtin/providers/heroku/resource_heroku_domain.go, builtin/providers/heroku/resource_heroku_drain.go, builtin/providers/openstack/resource_openstack_compute_instance_v2.go, builtin/providers/statuscake/resource_statuscaketest_test.go, builtin/providers/tls/resource_cert_request.go, builtin/providers/tls/resource_certificate.go, builtin/providers/vsphere/resource_vsphere_virtual_machine.go, state/remote/atlas.go, state/remote/consul.go, terraform/state_test.go, terraform/state_v1_test.go, terraform/terraform_test.go, vendor/github.com/mitchellh/hashstructure/LICENSE, vendor/github.com/mitchellh/hashstructure/README.md, vendor/github.com/mitchellh/hashstructure/hashstructure.go, vendor/github.com/mitchellh/hashstructure/include.go
=> Fix go vet warnings

website/source/docs/configuration/interpolation.html.md
=> website: clarify `file()` base location

Makefile
=> Run `vet` target on `default` target

terraform/interpolate.go, terraform/interpolate_test.go
=> core: error instead of panic on self var in wrong scope

config/interpolate_funcs.go, config/interpolate_funcs_test.go, website/source/docs/configuration/interpolation.html.md
This will allow fixing https://github.com/hashicorp/terraform/issues/3068
which in turn should allow finishing https://github.com/hashicorp/terraform/pull/5239
=> config: Add new interpolation function - md5

builtin/providers/openstack/resource_openstack_compute_instance_v2.go
This commit protects against unsafe typecasting when an instance is
updating its network configuration.
Fixes #5344
=> provider/openstack: Safely typecast network during instance update

Godeps/Godeps.json, vendor/github.com/hashicorp/hcl/README.md, vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
=> deps: update hcl to latest

Godeps/Godeps.json, builtin/providers/openstack/resource_openstack_compute_secgroup_v2_test.go, vendor/github.com/rackspace/gophercloud/.travis.yml, vendor/github.com/rackspace/gophercloud/CONTRIBUTING.md, vendor/github.com/rackspace/gophercloud/README.md, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/secgroups/fixtures.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/secgroups/requests.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/servers/fixtures.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/servers/requests.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/servers/results.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/servers/urls.go
=> provider/openstack: Allow ICMP Security Groups with values of zero

website/source/docs/commands/apply.html.markdown, website/source/docs/commands/plan.html.markdown, website/source/docs/commands/push.html.markdown, website/source/docs/commands/refresh.html.markdown, website/source/docs/configuration/variables.html.md
[Per Paul's request](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/terraform-tool/iMXaSwmbfyg/P1XHnclaBAAJ)
@phinze FYI
=> Updates to docs per request on mailer 

website/source/docs/providers/aws/r/route.html.markdown
=> Make aws_route and aws_route_table docs consistent

builtin/providers/aws/resource_aws_instance.go
With this pull request, `security_groups` can now be updated without forcing a new instance.
API reference for Modify Instance Attribute:
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html
[description]
First apply the following sample config:
```
resource "aws_instance" "web" {
ami = "ami-383c1956"
instance_type = "t2.micro"
security_groups = [
"${aws_security_group.tf_test_foo.name}"
]
}
resource "aws_security_group" "tf_test_foo" {
name = "tf_test_foo"
description = "foo"
ingress {
protocol = "icmp"
from_port = -1
to_port = -1
cidr_blocks = ["0.0.0.0/0"]
}
}
resource "aws_security_group" "tf_test_bar" {
name = "tf_test_bar"
description = "bar"
ingress {
protocol = "icmp"
from_port = -1
to_port = -1
cidr_blocks = ["0.0.0.0/0"]
}
}
```
Next change the …
=> provider/aws: Support additional changes to security groups of instance without forcing new

state/remote/http.go
Saw the discussion on https://groups.google.com/forum/#!searchin/terraform-tool/http$20remote/terraform-tool/Uy1EDGQTiGg/ckGy0wUMCwAJ.
=> Moving octet-stream to json for remote http backend

website/source/docs/providers/aws/r/autoscaling_group.html.markdown
- Fixes https://github.com/hashicorp/terraform/issues/5457
=> Fix contradictory aws_autoscaling_group doc

website/source/docs/providers/aws/r/autoscaling_schedule.html.markdown
I noticed a typo ,and then fixed it!
=> Fix typo: "messag" to "message."

website/source/docs/providers/aws/r/db_instance.html.markdown
aws_db_instance documentation missing the tags params
=> Added the missing tags params to the aws_db_instance doc

website/source/docs/providers/aws/r/ecs_service.html.markdown
=> docs/aws: Fixed aws_ecs_service example

Godeps/Godeps.json, vendor/github.com/hashicorp/hcl/.gitignore, vendor/github.com/hashicorp/hcl/README.md, vendor/github.com/hashicorp/hcl/appveyor.yml, vendor/github.com/hashicorp/hcl/decoder.go, vendor/github.com/hashicorp/hcl/hcl/parser/parser.go, vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go, vendor/github.com/hashicorp/hcl/hcl/token/token.go, vendor/github.com/hashicorp/hcl/lex.go, vendor/github.com/hashicorp/hcl/parse.go
=> deps: Update github.com/hashicorp/hcl

helper/resource/error.go
Reasons & relevant discussion in https://github.com/hashicorp/terraform/pull/5634
=> helper/resource: Remove NewNotFoundError function

website/source/docs/providers/aws/r/ecr_repository.html.markdown
Same as just changed in https://github.com/hashicorp/terraform/commit/e46d06bd814404fea4442cd42866a11c5216351d ;)
Realized it's here, too.
=> region available is growing

builtin/providers/aws/resource_aws_route53_record.go
=> Fix route53 set_identifier logic

examples/consul/README.md
=> documentation: Change the consul provider link on the consul example README

website/source/docs/providers/aws/r/dynamodb_table.html.markdown
There's a typo on this page: https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#stream_arm
=> Change stream_arm to stream_arn in docs

Godeps/Godeps.json, command/meta.go, command/state_command.go, command/state_list.go, commands.go, help.go, main.go, terraform/resource_address.go, terraform/resource_address_test.go, terraform/state_filter.go, terraform/state_filter_test.go, terraform/test-fixtures/state-filter/complete.tfstate, terraform/test-fixtures/state-filter/small.tfstate, vendor/github.com/mitchellh/cli/cli.go, website/source/assets/stylesheets/_docs.scss, website/source/docs/commands/index.html.markdown, website/source/docs/commands/state/addressing.html.md, website/source/docs/commands/state/index.html.md, website/source/docs/commands/state/list.html.md, website/source/docs/state/index.html.md, website/source/layouts/commands-state.erb, website/source/layouts/docs.erb
=> Add `terraform state list`

website/Gemfile.lock
=> website: Update hashicorp-middleman

website/source/docs/providers/aws/r/api_gateway_api_key.html.markdown, website/source/docs/providers/aws/r/api_gateway_deployment.html.markdown, website/source/docs/providers/aws/r/api_gateway_integration.html.markdown, website/source/docs/providers/aws/r/api_gateway_integration_response.html.markdown, website/source/docs/providers/aws/r/api_gateway_method.html.markdown, website/source/docs/providers/aws/r/api_gateway_method_response.html.markdown, website/source/docs/providers/aws/r/api_gateway_model.html.markdown, website/source/docs/providers/aws/r/api_gateway_resource.html.markdown, website/source/docs/providers/aws/r/api_gateway_rest_api.html.markdown
- documented some fields that were not mentioned in docs at all
- removed fields that are not actually supported yet and were mentioned in docs
- fixed `Optional`/`Required` docs per real implementation
- document exported `id`s where these can be useful
- some grammar nitpicks
=> docs: Fix API Gateway documentation

website/source/docs/providers/aws/r/instance.html.markdown, website/source/docs/providers/aws/r/volume_attachment.html.markdown
=> provider/aws: doc EBS block device mix-match caveats

website/source/docs/providers/aws/r/kinesis_firehose_delivery_stream.html.markdown
Silly fix, but should be updated.
=> Fix typo in kinesis_firehose_delivery_stream.html.markdown

website/source/docs/providers/aws/r/api_gateway_integration.html.markdown, website/source/docs/providers/aws/r/api_gateway_method.html.markdown
Adding some lessons learnt from the trenches...
Some things were really tough to find, the documentation for API Gateway isn't great, neither are the error messages.
Hopefully this will save others some time!
=> docs: Add some details about API Gateway resources

website/source/docs/providers/terraform/r/remote_state.html.md
Sorry, don't know the requirements for other possible config types as I only work with Atlas, but feel they can be expanded on from this base.
=> docs: correct remote state documentation and add config sub-arguments for atlas.

website/source/docs/providers/google/r/compute_address.html.markdown, website/source/docs/providers/google/r/compute_autoscaler.html.markdown, website/source/docs/providers/google/r/compute_instance.html.markdown, website/source/docs/providers/google/r/compute_instance_group.html.markdown, website/source/docs/providers/google/r/compute_instance_group_manager.html.markdown, website/source/docs/providers/google/r/compute_instance_template.html.markdown, website/source/docs/providers/google/r/compute_network.html.markdown, website/source/docs/providers/google/r/compute_route.html.markdown, website/source/docs/providers/google/r/compute_ssl_certificate.html.markdown, website/source/docs/providers/google/r/compute_subnetwork.html.markdown, website/source/docs/providers/google/r/compute_url_map.html.markdown, website/source/docs/providers/google/r/compute_vpn_gateway.html.markdown, website/source/docs/providers/google/r/compute_vpn_tunnel.html.markdown, website/source/docs/providers/google/r/sql_database.html.markdown, website/source/docs/providers/google/r/sql_database_instance.html.markdown, website/source/docs/providers/google/r/sql_user.html.markdown, website/source/docs/providers/google/r/storage_bucket.html.markdown, website/source/docs/providers/google/r/storage_bucket_acl.html.markdown, website/source/docs/providers/google/r/storage_bucket_object.html.markdown
Hello,
Just a little PR in order to fix markdown syntax
Cheers,
=> docs/google: Update links, fix syntax errors and remove whitespaces

website/source/docs/providers/aws/r/api_gateway_integration.html.markdown
Fork of #5990 to update and close the PR
=> update docs on required parameter for api_gateway_integration

builtin/providers/openstack/resource_openstack_compute_instance_v2.go
Previously, resizing would only work if the flavor_id changed and
would create an error if the flavor_name changes. This commit fixes
this behavior.
It also quickly refactors the getFlavorID function to use
Gophercloud's IDFromName function. getFlavorID was the basis of
IDFromName so the exact same code is used.
Fixes #5780 
Side note: the standard devstack environment does not enable resizing out of the box, so an acceptance test is not possible at this time. I need to update the [deploy](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/devstack/deploy.sh) script to account for vendoring deps and will try to roll-in resize support while I'm at it.
=> provider/openstack: Allow resizing when Flavor Name changes

website/source/docs/providers/triton/index.html.markdown
=> provider/triton: Change triton docs to reflect key_material not key_path

command/apply.go
Wording borrowed from the website docs.
=> Document saved plan use in `terraform apply -help`

README.md
Fixes #6125 after it was merged to the .github folder
=> Fix the README file with the correct link to the CONTRBUTING.md

website/packer.json, website/scripts/deploy.sh
=> Fix website metadata script

Godeps/Godeps.json
=> Update joyent/gosdc/cloudapi to master

builtin/providers/aws/resource_aws_cloudtrail_test.go
Introduce better randomization to our CloudTrail tests. This should help avoid some collisions I believe we are hitting in our night acceptance tests
=> provider/aws: Better randomize the CloudTrail tests

builtin/providers/aws/resource_aws_opsworks_stack.go
This should address the issue @stack72 encountered when running the acceptance test in #4276
=> Handle race condition with IAM role permissions & Opsworks

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_opsworks_instance.go, builtin/providers/aws/resource_aws_opsworks_instance_test.go, website/source/docs/providers/aws/r/opsworks_instance.html.markdown, website/source/layouts/aws.erb
This is a work in progress to support issue #3459.
There's still a lot of work to be done.
TODO:
=> provider/aws: Opsworks instance

website/source/docs/providers/openstack/index.html.markdown
=> provider/openstack: Notes for using OpenStack with Rackspace

builtin/providers/vsphere/README.md
Start on a README for developers.
=> vSphere provider developer docs

.github/ISSUE_TEMPLATE.md
Small change to the template used in every issue report.
=> Correct grammar in ISSUE_TEMPLATE.md

website/source/docs/providers/aws/r/ebs_volume.html.md
=> documentation: Add a note to ebs_volume for snapshot_id & size

builtin/providers/openstack/devstack/deploy.sh, builtin/providers/openstack/resource_openstack_fw_firewall_v1_test.go, builtin/providers/openstack/resource_openstack_lb_member_v1_test.go, builtin/providers/openstack/resource_openstack_lb_pool_v1_test.go, builtin/providers/openstack/resource_openstack_lb_vip_v1_test.go
This commit patches a few acceptance tests in order to get them to
pass under OpenStack Mitaka.
The devstack dev environment script has also been updated to reflect
OpenStack Mitaka as well as the new Terraform dependency vendoring.
=> provider/openstack: OpenStack Mitaka Patches

website/source/docs/providers/openstack/index.html.markdown
=> provider/openstack: Add documentation for cacert_file

builtin/providers/vsphere/resource_vsphere_virtual_machine.go
Fixes https://github.com/hashicorp/terraform/issues/3966
=> Vsphere - Checking for powered off state before deletion

builtin/providers/aws/resource_aws_opsworks_stack.go
=> Fix issue with with Opsworks and empty Custom Cook Book sources

builtin/providers/azurerm/config.go, builtin/providers/azurerm/provider.go
This commit uses Riviera to register the Microsoft.Compute provider as a canary for whether or not the Azure account credentials are set up. It used to use the MS client, but that appeared to panic internally if the credentials were bad. It's possible that we were using it wrong, but there are no docs so `¯\_(ツ)_/¯`.
As part of this, we parellelise the registration of the other providers. This shaves the latency of each provider request times the number of providers minus 1 off the "startup" time of the AzureRM provider. The result is quite noticeable.
=> provider/azurerm: Error on bad creds and speed++

website/source/downloads.html.erb
http://mathiasbynens.github.io/rel-noopener/
=> Do not send referrer

website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown
adding the price classes from the AWS cloud formation docs
=> adding the price classes from the AWS cloud formation docs

Godeps/Godeps.json, vendor/github.com/hashicorp/hcl/hcl/printer/nodes.go, vendor/github.com/hashicorp/hcl/hcl/printer/printer.go
Updates to HCL have provided the referenced format, just need to update with latest 
Fixes #6346
=> Update of HCL dependency

builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go
This addresses issue brought up in #6242 where the `wait_for_ready_timeout` option is ignored, originally done in #6342
Tests
```
=== RUN   TestAccAWSBeanstalkEnv_basic
--- PASS: TestAccAWSBeanstalkEnv_basic (376.01s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    376.019s
```
=> provider/aws: Fixes issue where an update for an `aws_elastic_beanstalk_environment ` resource would ignore the `wait_for_ready_timeout` option.

builtin/providers/aws/resource_aws_sqs_queue.go
Fixes #5578 
When an SQS queue was deleted from the AWS Console, an error was thrown
to say that the Queue could not be found. This is now fixed to remove
the queue from the state on a specific not found exception
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSQSQueue' 2>~/tf.log
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSQSQueue -timeout 120m
=== RUN   TestAccAWSSQSQueue_basic
--- PASS: TestAccAWSSQSQueue_basic (20.52s)
=== RUN   TestAccAWSSQSQueue_redrivePolicy
--- PASS: TestAccAWSSQSQueue_redrivePolicy (18.80s)
=== RUN   TestAccAWSSQSQueue_Policybasic
--- PASS: TestAccAWSSQSQueue_Policybasic (24.17s)
PASS
ok …
```
=> provider/aws: refresh state on SQS Queue not found

builtin/providers/aws/resource_aws_cloudwatch_log_group.go
As per comments https://github.com/hashicorp/terraform/pull/6384/files/bdcdf8a3482aaa41f10a04ea3e12f3351364ce07#r61374612 :)
=> provider/aws: Removal of duplicate error handling code in cloudwatch_log_group

website/source/docs/providers/openstack/r/compute_instance_v2.html.markdown
This commit adds several example uses of the
openstack_compute_instance_v2 resource. It also makes a clarification
about booting from volumes and image ids/names.
=> provider/openstack: Instance Doc Examples

website/source/docs/configuration/variables.html.md
As reported and described in hashicorp/terraform#3292
=> Tweak docs to properly document .tfvars format

website/source/docs/providers/vsphere/index.html.markdown
Hi, 
This is the doc for the customization problems in Vsphere. 
Thanks
=> Fix #3562 provider/vsphere Added doc for customizations problems.

builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
Looks like the master branch is broken due to a bad test implementation.
=> Fixing the broken Test with Master branch

builtin/providers/vsphere/provider.go, builtin/providers/vsphere/resource_vsphere_file.go, builtin/providers/vsphere/resource_vsphere_file_test.go, website/source/docs/providers/vsphere/index.html.markdown, website/source/docs/providers/vsphere/r/file.html.markdown
Allows for file upload to vSphere at specified location.  This also
includes update for moving or renaming of file resources (in vSphere).
Ref issue #6366.
=> Adding File Resource for vSphere provider

builtin/providers/vsphere/README.md
Just read the Doc and found obvious typos...
=> Fixed obvious typos

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go, builtin/providers/aws/resource_aws_db_option_group.go, builtin/providers/aws/resource_aws_db_option_group_test.go, builtin/providers/aws/structure.go, website/source/docs/providers/aws/r/db_option_group.html.markdown, website/source/layouts/aws.erb
Scaffold the AWS DB Option Group resource
=> provider/aws: aws_db_option_group

examples/digitalocean/README.md, examples/digitalocean/main.tf, examples/digitalocean/outputs.tf, examples/digitalocean/variable.tf
I did not see an example for Digital Ocean. So I worked on one today for myself today and thought I would share.
=> Digital Ocean Example.

builtin/providers/azurerm/resource_arm_virtual_machine.go, website/source/docs/providers/azurerm/r/virtual_machine.html.markdown
Fix #6372
Partial fix of #6526
=> [azurerm] Add os_type and image_uri in azurerm_virtual_machine

builtin/providers/fastly/resource_fastly_service_v1.go, builtin/providers/fastly/resource_fastly_service_v1_conditionals_test.go, vendor/github.com/sethvargo/go-fastly/s3.go, vendor/github.com/sethvargo/go-fastly/version.go, website/source/docs/providers/fastly/r/service_v1.html.markdown
Add support for working with Conditions in Fastly Services. Many of the other objects (backends, gzips, etc) will be able to reference these conditions by adding/exposing `_condition` attributes to them, but I'll do that in a future patch to minimize what's changing in this PR
Docs here:
- https://docs.fastly.com/guides/conditions/
=>     provider/fastly: Add support for Conditions for Fastly Services

Makefile
=> fix(Makefile): remove 'updatedeps' from .PHONY

website/source/docs/providers/google/r/compute_instance.html.markdown
=> Fix address docs in gce instance

builtin/providers/fastly/resource_fastly_service_v1.go, builtin/providers/fastly/resource_fastly_service_v1_request_setting_test.go, website/source/docs/providers/fastly/r/service_v1.html.markdown
Supports request settings, which low you to conditionally respond or modify the request based on a met condition 
- https://docs.fastly.com/api/config#request_settings
=> provider/fastly: Add support for Service Request Settings

website/source/docs/providers/vsphere/r/file.html.markdown, website/source/layouts/vsphere.erb
Hi
Small word tweaks and sidebar fix for the recently added vsphere_file resource
=> Docs: fix sidebar + small rewordings for recently added vsphere file resource

builtin/providers/google/resource_compute_disk.go, builtin/providers/google/resource_compute_instance_test.go
=> providers/google: Don't fail deleting disks that don't exist.

Godeps/Godeps.json, builtin/providers/openstack/config.go, builtin/providers/openstack/provider.go, builtin/providers/openstack/resource_openstack_blockstorage_volume_v2.go, builtin/providers/openstack/resource_openstack_blockstorage_volume_v2_test.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/doc.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/fixtures.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/requests.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/results.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/urls.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/util.go, vendor/github.com/rackspace/gophercloud/openstack/client.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/images/results.go, vendor/github.com/rackspace/gophercloud/pagination/pager.go, website/source/docs/providers/openstack/r/blockstorage_volume_v2.html.markdown, website/source/layouts/openstack.erb
This commit adds an openstack_blockstorage_volume_v2 resource. This
resource is able to create volumes using the OpenStack Block Storage
v2 API.
Fixes #2817
=> provider/openstack: openstack_blockstorage_volume_v2 resource

helper/resource/testing_config.go
When testing destroy, the test harness calls Refresh followed by Plan, with the expectation that the resulting diff will be empty.
Data resources challenge this expectation, because they will always be instantiated during refresh if their configuration isn't computed, and so the subsequent diff will want to destroy what was instantiated.
To work around this, we make an exception that data resource destroy diffs may appear in the plan but nothing else.
This fixes #6713.
=> helper/resource: ignore data resource diffs during destroy

terraform/context_input_test.go, terraform/context_validate_test.go, terraform/eval_context_builtin.go, terraform/eval_interpolate.go, terraform/graph_config_node_output.go, terraform/interpolate.go, terraform/test-fixtures/input-interpolate-var/child/main.tf, terraform/test-fixtures/input-interpolate-var/main.tf, terraform/test-fixtures/input-interpolate-var/source/main.tf, terraform/test-fixtures/validate-computed-module-var-ref/dest/main.tf, terraform/test-fixtures/validate-computed-module-var-ref/main.tf, terraform/test-fixtures/validate-computed-module-var-ref/source/main.tf
=> Interpolate variable during Input and Validate

builtin/providers/openstack/devstack/deploy.sh, builtin/providers/openstack/resource_openstack_networking_floatingip_v2_test.go
This commit adds the newly required OS_EXT_GW environment variable to
the devstack acceptance environment build suite. It also fixes some
space formatting in a test.
=> provider/openstack: Devstack and fmt fixes

builtin/providers/vsphere/resource_vsphere_virtual_machine.go
If a scsi or ide controller does not exist at the time a new disk
or cdrom needs it, we need to add that controller to the vm.
Also adding logic to handle reading either a flat or sparse
disk from vSphere.
=> Adding controller creation logic

command/format_state.go
=> core: Update `terraform show` to deal with lists

website/source/docs/providers/aws/r/security_group_rule.html.markdown
=> update docs to reflect attribute conflict

website/source/docs/providers/aws/r/opsworks_instance.html.markdown
fixes #6885 
/cc @catsby @stack72
=> Fix errata Opsworks Documentation

builtin/providers/aws/resource_aws_elb.go
=> set cross_zone_load_balancing default to true

builtin/providers/aws/resource_aws_rds_cluster_instance.go
=> support aurora instance's parameter group and modifyinstance

website/source/layouts/aws.erb
=> add sidebar link for elb_attachment

vendor/github.com/hashicorp/hcl/.gitignore, vendor/github.com/hashicorp/hcl/.travis.yml, vendor/github.com/hashicorp/hcl/hcl/strconv/quote.go, vendor/vendor.json
Pulls in https://github.com/hashicorp/hcl/pull/125
Which fixes #6359
=> Update HCL to latest version

builtin/providers/aws/resource_aws_customer_gateway_test.go, builtin/providers/aws/resource_aws_vpn_connection_test.go, builtin/providers/aws/resource_vpn_connection_route_test.go, website/source/docs/providers/aws/r/customer_gateway.html.markdown, website/source/docs/providers/aws/r/vpn_connection.html.markdown, website/source/docs/providers/aws/r/vpn_connection_route.html.markdown
AS65000 is reserved for private use. 
https://en.wikipedia.org/wiki/Autonomous_system_\(Internet\)
=> BGP AS 60000 is assigned to EQUINIX-CLOUD-EXCHANGE-AMSTERDAM-ASN.

scripts/build.sh
=> make linux amd64 binaries static again.

helper/resource/testing.go
This commit adds a flag to acceptance tests in order to make appropriately named tests work during `make test` irrespective of the TF_ACC environment variable. This should only be used on tests which are known to be fast.
The actual use case here is for the remote state tests (to follow) which use the framework but have never actually been running on a regular basis (quelle horreur), which led to #6989 (and a ton of core work!)
=> testing: Allow acceptance test to run as unit test

builtin/providers/aws/resource_aws_route_table.go, builtin/providers/aws/resource_aws_route_table_association.go
Retry the creation of a Route Table Association. _Eventual Consistency Bandaid_ for #7104
=> provider/aws: Retry RouteTable Route/Assocation creation

builtin/providers/aws/resource_aws_eip.go
Bandaid #6970 by retrying the EIP address association
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEIP_ -timeout 120m
=== RUN   TestAccAWSEIP_basic
--- PASS: TestAccAWSEIP_basic (9.48s)
=== RUN   TestAccAWSEIP_instance
--- PASS: TestAccAWSEIP_instance (165.45s)
=== RUN   TestAccAWSEIP_network_interface
--- PASS: TestAccAWSEIP_network_interface (33.07s)
=== RUN   TestAccAWSEIP_twoEIPsOneNetworkInterface
--- PASS: TestAccAWSEIP_twoEIPsOneNetworkInterface (33.01s)
=== RUN   TestAccAWSEIP_associated_user_private_ip
--- PASS: TestAccAWSEIP_associated_user_private_ip (136.22s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	377.255s
Test:
```
=> provider/aws: Retry EIP association

website/source/docs/providers/vsphere/r/virtual_disk.html.markdown
Resolves https://github.com/hashicorp/terraform/issues/7165
=> vSphere Provider - Updating Virtual Disk doc

website/source/docs/modules/usage.html.markdown
1. For me it was surprising, that the string after the `module` keyword is a name of the instance of the module, not a module name.
2. Lot of people see modules as a vehicle to reduce repetition (DRY) and some ask, e.g. in google groups, if is is possible, to instantiate a module multiple times
So I thought, it would be a good idea to document such a use case for modules
=> docs: explain instantiating terraform module multiple times

website/source/docs/state/remote/index.html.md
Added example usage for remote config subcommand, showing how to move from remote state to local state.
=> website/remote: added example usage for -disable

config/loader_test.go, vendor/github.com/hashicorp/hcl/hcl/strconv/quote.go, vendor/vendor.json
Catches https://github.com/hashicorp/hcl/pull/132
Fixes #5550
=> vendor: Update hashicorp/hcl to latest version

builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go
Fixes #3760 by bundling the `allocated_storage` and `iops` updates. 
~~Marked as WIP until Travis shows passing on new Acc test~~
Custom TravisCI test running of `TestAccAWSDBInstance_basic` and new `TestAccAWSDBInstance_iops_update`:
- https://travis-ci.org/hashicorp/terraform/builds/138214603
=> provider/aws: Bundle IOPs and Allocated Storage update for DB Instances

website/source/docs/configuration/syntax.html.md
=> docs: Mention map keys which start with a number

README.md
The markdown wasn't being rendered as expected because there was a lack of indentation
=> Fix readme numbered indentation

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_spot_fleet_request.go, builtin/providers/aws/resource_aws_spot_fleet_request_test.go, website/source/docs/providers/aws/r/spot_fleet_request.html.markdown, website/source/layouts/aws.erb
This adds a Spot fleet resource to AWS, docs and some acceptance tests. We've been using this for a bit in our own environment without any issues.
Fixes #4070
=> AWS Spot fleet resource

vendor/github.com/rackspace/gophercloud/openstack/auth_env.go, vendor/github.com/rackspace/gophercloud/openstack/client.go, vendor/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go, vendor/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/errors.go, vendor/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/requests.go, vendor/vendor.json
Updating Gophercloud dependencies. Includes an update for Keystone to fix Keystone v3 token authentication.
Fixes #6458
=> vendor: Updating Gophercloud Deps

website/source/docs/providers/azurerm/r/network_security_group.html.markdown
Docs referred to availability set name, not NSG name,
=> Slight doc correction

website/source/docs/providers/azurerm/r/virtual_machine.html.markdown
=> provider/azurerm: Add documentation for `azurerm_virtual_machine` with another data_disk attached

builtin/providers/vsphere/resource_vsphere_virtual_machine.go
Without refreshing the devices list, we can't find the controller we just created.
=> Refreshing devices list after adding a disk or cdrom controller

builtin/providers/aws/resource_aws_db_security_group.go
Fixes https://github.com/hashicorp/terraform/issues/7178
=> provider/aws: Add inplace edit/update DB Security Group Rule Ingress

builtin/providers/aws/structure.go, builtin/providers/aws/structure_test.go
fix : https://github.com/hashicorp/terraform/issues/6767
=> Handled case when instanceId is absent in network interfaces

builtin/providers/aws/resource_aws_customer_gateway.go
Fixes #7136 
the nodes on what the fix does are added to the issue
=> provider/aws: `aws_customer_gateway` refreshing from state on deleted state

builtin/providers/aws/resource_aws_security_group_rule.go
Previously, any old HTTP error would be treated as the security_group_rule being deleted. In reality there are only a few cases where this is the right assumption.
Fixes #5396 and fixes #2449.
=> provider/aws: Handle spurious failures in resourceAwsSecurityGroupRuleRead

builtin/providers/digitalocean/provider.go, builtin/providers/digitalocean/resource_digitalocean_droplet.go, builtin/providers/digitalocean/resource_digitalocean_droplet_test.go, builtin/providers/digitalocean/resource_digitalocean_tag.go, builtin/providers/digitalocean/resource_digitalocean_tag_test.go, builtin/providers/digitalocean/tags.go, builtin/providers/digitalocean/tags_test.go, vendor/github.com/digitalocean/godo/.travis.yml, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_actions.go, vendor/github.com/digitalocean/godo/tags.go, vendor/vendor.json, website/source/docs/providers/do/r/droplet.html.markdown, website/source/docs/providers/do/r/tag.html.markdown
Adds support for a `digitalocean_tag` resource and to apply tags on a `digitalocean_droplet` resource.
reference: https://developers.digitalocean.com/documentation/v2/#tags
=> digitalocean tag support

builtin/providers/vsphere/resource_vsphere_virtual_machine.go, builtin/providers/vsphere/resource_vsphere_virtual_machine_test.go
Reverts hashicorp/terraform#7572
=> Revert the "Revert "Adding disk keep_on_remove support on delete case""

vendor/github.com/hashicorp/hcl/README.md, vendor/github.com/hashicorp/hcl/hcl/parser/parser.go, vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go, vendor/vendor.json
Catches https://github.com/hashicorp/hcl/pull/137
Fixes #7142
=> vendor: Update to lastest hashicorp/hcl

builtin/providers/triton/resource_machine_test.go
Should fix failing Triton tests
- https://travis-ci.org/hashicorp/terraform/builds/143814431
There are still a few fixes need but most of the tests should run now and fail with actual error messages
=> Triton test updates

builtin/providers/aws/resource_aws_db_instance.go, builtin/providers/aws/resource_aws_db_instance_test.go
Fixes #2439
Port used to ForceNew, it has now been changed to allow it to be
updated. 2 changes were needed:
1. Setting the port back to state
2. Adding the wait for state function to the Update func
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBInstance_portUpdate'
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSDBInstance_portUpdate -timeout 120m
=== RUN   TestAccAWSDBInstance_portUpdate
--- PASS: TestAccAWSDBInstance_portUpdate (699.84s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    699.861s
```
=> provider/aws: Allow `port` on `aws_db_instance` to be updated

command/hook_count.go, command/hook_count_test.go
=> command: Do not count data sources in plan totals

builtin/providers/aws/resource_aws_db_option_group.go, builtin/providers/aws/resource_aws_db_option_group_test.go
=> aws: Adding in additional retry logic due to latency with delete of db_option_group

website/source/docs/providers/azurerm/r/virtual_machine.html.markdown
I forgot to update the documentation with my previous PR: #7584
=> providers/azurerm: document delete_os_disk_on_termination flag

builtin/providers/azurerm/resource_arm_virtual_machine_test.go
The tests were removed due to a nil pointer panic in
testCheckAzureRMVirtualMachineOSDiskVHDExistance when the storage account itself
had been deleted in the destroy stage
Added a test to cover opting out of VHD delete rather than polluting the basic
linux VM test.
```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMVirtualMachine_deleteVHDOpt -timeout 120m
=== RUN   TestAccAzureRMVirtualMachine_deleteVHDOptOut
--- PASS: TestAccAzureRMVirtualMachine_deleteVHDOptOut (731.54s)
=== RUN   TestAccAzureRMVirtualMachine_deleteVHDOptIn
--- PASS: TestAccAzureRMVirtualMachine_deleteVHDOptIn (590.87s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	1322.529s
```
```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run …
```
=> provider/azurerm: fix tests removed in c1410509290507d77dab7b07932062e6f995802e

builtin/providers/openstack/import_openstack_networking_floatingip_v2_test.go, builtin/providers/openstack/import_openstack_networking_network_v2_test.go, builtin/providers/openstack/import_openstack_networking_port_v2_test.go, builtin/providers/openstack/import_openstack_networking_secgroup_rule_v2_test.go, builtin/providers/openstack/import_openstack_networking_secgroup_v2_test.go, builtin/providers/openstack/import_openstack_networking_subnet_v2_test.go, builtin/providers/openstack/resource_openstack_networking_floatingip_v2.go, builtin/providers/openstack/resource_openstack_networking_network_v2.go, builtin/providers/openstack/resource_openstack_networking_port_v2.go, builtin/providers/openstack/resource_openstack_networking_port_v2_test.go, builtin/providers/openstack/resource_openstack_networking_secgroup_rule_v2.go, builtin/providers/openstack/resource_openstack_networking_secgroup_v2.go, builtin/providers/openstack/resource_openstack_networking_subnet_v2.go
Router-based resources are not included. They will be added later.
=> provider/openstack: Support Import of OpenStack Networking Resources

Vagrantfile
Small change to set memory and CPU resources for the [Parallels Vagrant provider](https://parallels.github.io/vagrant-parallels/docs/configuration.html).
=> [Vagrantfile] set resources for the provider 'parallels'

builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
This fixes the `TestAccAWSBeanstalkEnv_tier` test. The instance profile
needs access to send and receive messages from its sqs queue. Without
these permissions Beanstalk returns an error event, causing the test to
fail.
AWS Documentation for what IAM policy access is needed worker tier environments: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html. For this test, it appears that only the SQS permissions are needed.
Test from current master:
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSBeanstalkEnv_tier -timeout 120m
=== RUN   TestAccAWSBeanstalkEnv_tier
--- FAIL: TestAccAWSBeanstalkEnv_tier (575.99s)
testing.go:264: Step 0 error: Error applying: 1 error(s) occurred:
* aws_elastic_beanstalk_environment.tfenvtest: 
2016-07-15 18:24:48.656 …
```
=> provider/aws: Fix Elastic Beanstalk test

builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go, builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
Fix Elastic Beanstalk recurring plans when additional security groups
are supplied. In the previous version, only non-default vpc security
groups would be handled by dropGeneratedSecurityGroup.
Fixes #6257 
If there's a way to write tests for this I'd like to add those as well. Currently not sure how to verify that subsequent plans return an empty diff.
=> provider/aws: Support ec2-classic and vpc in beanstalk recurring plans.

website/source/docs/providers/openstack/r/blockstorage_volume_v1.html.markdown, website/source/docs/providers/openstack/r/blockstorage_volume_v2.html.markdown, website/source/docs/providers/openstack/r/compute_floatingip_v2.html.markdown, website/source/docs/providers/openstack/r/compute_keypair_v2.html.markdown, website/source/docs/providers/openstack/r/compute_secgroup_v2.html.markdown, website/source/docs/providers/openstack/r/compute_servergroup_v2.html.markdown, website/source/docs/providers/openstack/r/fw_firewall_v1.html.markdown, website/source/docs/providers/openstack/r/fw_policy_v1.html.markdown, website/source/docs/providers/openstack/r/fw_rule_v1.html.markdown, website/source/docs/providers/openstack/r/lb_member_v1.html.markdown, website/source/docs/providers/openstack/r/lb_monitor_v1.html.markdown, website/source/docs/providers/openstack/r/lb_pool_v1.html.markdown, website/source/docs/providers/openstack/r/lb_vip_v1.html.markdown, website/source/docs/providers/openstack/r/networking_floatingip_v2.html.markdown, website/source/docs/providers/openstack/r/networking_network_v2.html.markdown, website/source/docs/providers/openstack/r/networking_port_v2.html.markdown, website/source/docs/providers/openstack/r/networking_router_interface_v2.html.markdown, website/source/docs/providers/openstack/r/networking_router_v2.html.markdown, website/source/docs/providers/openstack/r/networking_secgroup_rule_v2.html.markdown, website/source/docs/providers/openstack/r/networking_secgroup_v2.html.markdown, website/source/docs/providers/openstack/r/networking_subnet_v2.html.markdown
Also removing some unneeded region arguments in the examples.
=> provider/openstack: Documenting resources that support importing

builtin/providers/aws/resource_aws_redshift_cluster.go
```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSRedshiftCluster_importBasic'
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSRedshiftCluster_importBasic -timeout 120m
=== RUN   TestAccAWSRedshiftCluster_importBasic
--- PASS: TestAccAWSRedshiftCluster_importBasic (641.87s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    641.888s
```
=> provider/aws: Fix the import of `aws_redshift_cluster` breaking `skip_final_snapshot`

builtin/providers/azurerm/config.go
Before
```
2016/07/20 16:00:06 [DEBUG] plugin: terraform: azurerm-provider (internal) 2016/07/20 16:00:06 [DEBUG] Sending Azure RM Request "PUT" to "https://management.azure.com/subscriptions/res-id-here/resourceGroups/acctestrg-1234/providers/Microsoft.Network/trafficmanagerprofiles/acctesttmp-1234?api-version=2015-11-01"
2016/07/20 16:00:06 [DEBUG] plugin: terraform: azurerm-provider (internal) 2016/07/20 16:00:06 [DEBUG] Received Azure RM Request status code 409 Conflict for https://management.azure.com/subscriptions/res-id-here/resourceGroups/acctestrg-1234/providers/Microsoft.Network/trafficmanagerprofiles/acctesttmp-1234?api-version=2015-11-01
```
After:
```
2016/07/20 16:28:06 [DEBUG] plugin: terraform: azurerm-provider (internal) 2016/07/20 16:28:06 [DEBUG] AzureRM Request: PUT …
```
=> provider/azurerm: dump entire Request/Response in autorest Decorator

builtin/providers/aws/config.go
Fixes problem introduced in re-arrangement of config
Refs #7672
=> provider/aws: pull iamconn setup earlier

builtin/providers/aws/resource_aws_api_gateway_integration.go, builtin/providers/aws/resource_aws_api_gateway_integration_test.go, builtin/providers/aws/validators.go, website/source/docs/providers/aws/r/api_gateway_integration.html.markdown
Should address https://github.com/hashicorp/terraform/issues/7475 and https://github.com/hashicorp/terraform/issues/7141
=> Adding passthrough behavior for API Gateway integration

website/source/docs/providers/docker/d/registry_image.html.markdown, website/source/docs/providers/docker/index.html.markdown, website/source/docs/providers/docker/r/image.html.markdown, website/source/layouts/docker.erb
Related to #7000 
FYI @kyhavlov
=> docker/docs: Document new data source + limitations

builtin/providers/consul/config.go, builtin/providers/consul/resource_consul_agent_service.go, builtin/providers/consul/resource_consul_agent_service_test.go, builtin/providers/consul/resource_consul_catalog_entry.go, builtin/providers/consul/resource_consul_catalog_entry_test.go, builtin/providers/consul/resource_consul_node.go, builtin/providers/consul/resource_consul_node_test.go, builtin/providers/consul/resource_consul_service.go, builtin/providers/consul/resource_consul_service_test.go, builtin/providers/consul/resource_provider.go, website/source/docs/providers/consul/r/agent_service.html.markdown, website/source/docs/providers/consul/r/catalog_entry.html.markdown, website/source/docs/providers/consul/r/node.html.markdown, website/source/docs/providers/consul/r/service.html.markdown
I accidentally deleted PR #3687 - this is (very nearly) the same PR, re-opened.
=> Gh 2087 consul service resource

website/source/intro/getting-started/remote.html.markdown
=> docs/intro: Change the location of Atlas User Tokens in Intro docs

builtin/providers/cloudstack/resource_cloudstack_loadbalancer_rule.go, builtin/providers/cloudstack/resource_cloudstack_static_nat.go, website/source/docs/providers/cloudstack/r/loadbalancer_rule.html.markdown, website/source/docs/providers/cloudstack/r/static_nat.html.markdown
=> Add project parameter to additional resources

builtin/providers/aws/resource_aws_appautoscaling_policy.go, builtin/providers/aws/structure_test.go, builtin/providers/template/datasource_template_file_test.go, plugin/resource_provider_test.go, terraform/context.go
Builds off of https://github.com/hashicorp/terraform/pull/7868 and fixes other things found by running `make`
=> fix make issues (supersedes #7868)

website/source/community.html.erb
As the page says:
> Over time, faces may appear from this list as contributors come and
> go.
Let's reflect the list of peoople working on Terraform nowadays! :)
=> website: update community people section

website/source/docs/providers/terraform/index.html.markdown
Fixing minor typo to match documentation on https://www.terraform.io/docs/providers/terraform/d/remote_state.html
=> Fix terraform_remote_state documentation

website/source/docs/state/remote/index.html.md
=> Fix link to the remote state link post 0.7.x.

builtin/providers/google/resource_compute_backend_service.go, builtin/providers/google/resource_compute_backend_service_test.go, vendor/google.golang.org/api/compute/v1/compute-api.json, vendor/google.golang.org/api/compute/v1/compute-gen.go, vendor/google.golang.org/api/gensupport/buffer.go, vendor/google.golang.org/api/gensupport/media.go, vendor/google.golang.org/api/gensupport/resumable.go, vendor/google.golang.org/api/gensupport/send.go, vendor/google.golang.org/api/storage/v1/storage-api.json, vendor/google.golang.org/api/storage/v1/storage-gen.go, vendor/vendor.json, website/source/docs/providers/google/r/compute_backend_service.html.markdown
Adds the "enable_cdn" option to ``google_compute_backend_service``
=> google_compute_backend_service "enable_cdn"

website/source/docs/providers/aws/r/ses_receipt_rule.html.markdown
https://www.terraform.io/docs/providers/aws/r/ses_receipt_rule.html
=> remove duplicate 'recipients' argument on ses_receipt_rule docs

builtin/providers/aws/resource_aws_cloudformation_stack.go
Fixes #7996
The Create func was using the timeout that we were passing to the
resource. Update func was not.
```
% make testacc TEST=./builtin/providers/aws
% TESTARGS='-run=TestAccAWSCloudFormation_'
TF_ACC=1 go test ./builtin/providers/aws -v
-run=TestAccAWSCloudFormation_ -timeout 120m
=== RUN   TestAccAWSCloudFormation_basic
--- PASS: TestAccAWSCloudFormation_basic (120.61s)
=== RUN   TestAccAWSCloudFormation_defaultParams
--- PASS: TestAccAWSCloudFormation_defaultParams (121.40s)
=== RUN   TestAccAWSCloudFormation_allAttributes
--- PASS: TestAccAWSCloudFormation_allAttributes (263.29s)
=== RUN   TestAccAWSCloudFormation_withParams
--- PASS: …
```
=> provider/aws: Updates `aws_cloudformation_stack` Update timeout

.github/CONTRIBUTING.md
=> Corrected AWS env variable in docs

builtin/providers/aws/resource_aws_s3_bucket.go
The S3 API has two parameters that can be passed to it (HostName
and Protocol) for the RedirectAllRequestsTo functionality.
HostName is somewhat poorly named because it need not be only a
hostname (it can contain a path too.)
The terraform code for this was treating the API as the parameter
name suggests and was truncating out any paths that were passed.
=> Fix S3 provider redirect_all_requests_to behavior. #5142

builtin/providers/aws/resource_aws_rds_cluster_instance.go, builtin/providers/aws/resource_aws_rds_cluster_instance_test.go, website/source/docs/providers/aws/r/rds_cluster_instance.html.markdown
Add Enable Enhanced Monitoring feature to Aurora instance
=> Aurora Enhanced monitoring support

website/source/docs/providers/aws/r/kinesis_firehose_delivery_stream.html.markdown
=> provider/aws: Update docs for s3 compression_formation for Kinesis Firehose

website/source/docs/providers/openstack/index.html.markdown
=> doc: openstack fix minor typo

vendor/github.com/aws/aws-sdk-go/aws/config.go, vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/session/session.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/private/endpoints/endpoints.go, vendor/github.com/aws/aws-sdk-go/private/endpoints/endpoints.json, vendor/github.com/aws/aws-sdk-go/private/endpoints/endpoints_map.go, vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudfront/service.go, vendor/github.com/aws/aws-sdk-go/service/ec2/customizations.go, vendor/github.com/aws/aws-sdk-go/service/ecr/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/elb/api.go, vendor/github.com/aws/aws-sdk-go/service/elb/service.go, vendor/github.com/aws/aws-sdk-go/service/kms/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/waiters.go, vendor/github.com/aws/aws-sdk-go/service/s3/host_style_bucket.go, vendor/vendor.json
Update the AWS SDK to the latest version.
=> deps: github.com/aws/aws-sdk-go/... to v1.4.1

builtin/providers/aws/auth_helpers.go, builtin/providers/aws/config.go, builtin/providers/aws/provider.go, website/source/docs/providers/aws/index.html.markdown
Follow up to https://github.com/hashicorp/terraform/pull/7874
cc @renier any feedback appreciated
=> aws: Change names of new skip_* fields + document those

builtin/providers/azurerm/config.go, builtin/providers/azurerm/import_arm_virtual_network_peering_test.go, builtin/providers/azurerm/provider.go, builtin/providers/azurerm/resource_arm_virtual_network_peering.go, builtin/providers/azurerm/resource_arm_virtual_network_peering_test.go, website/source/docs/providers/azurerm/r/virtual_network_peering.html.markdown, website/source/layouts/azurerm.erb
```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMVirtualNetworkPeering -timeout 120m
=== RUN   TestAccAzureRMVirtualNetworkPeering_importBasic
--- PASS: TestAccAzureRMVirtualNetworkPeering_importBasic (225.50s)
=== RUN   TestAccAzureRMVirtualNetworkPeering_basic
--- PASS: TestAccAzureRMVirtualNetworkPeering_basic (216.95s)
=== RUN   TestAccAzureRMVirtualNetworkPeering_update
--- PASS: TestAccAzureRMVirtualNetworkPeering_update (266.97s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	709.545s
```
=> provider/azurerm: create virtual_network_peering resource

website/source/upgrade-guides/0-7.html.markdown
I'm pretty sure "with" was intended here.
=> fix small typo

builtin/providers/aws/resource_aws_iam_group_membership_test.go, builtin/providers/aws/resource_aws_iam_policy_attachment.go, builtin/providers/aws/resource_aws_iam_policy_attachment_test.go, builtin/providers/aws/resource_aws_iam_role_policy_attachment.go
This includes a cherry-picked https://github.com/hashicorp/terraform/pull/6726. Instead of merging, you probably want to merge @miquella's and cherry-pick this.
=> provider/aws: Paginate roles

helper/resource/testing.go, helper/resource/testing_test.go
This commit adds a function which composes a series of TestFuncs, but will run all tests before returning an error, unlike ComposeTestFunc. This is useful when verifying contents of state in acceptance tests and it is desirable to see all the failing cases in one run for slow resources.
=> testing: Add ComposeAggregateTestFunc

website/source/docs/plugins/basics.html.md
- Minor update to remove some possibly confusing discussion about
pre 0.7 separate binaries for plugins, and link to internal
plugins section for more clarification of how plugins are
handled in 0.7+.
=> Updated Plugins section

builtin/providers/aws/resource_aws_efs_mount_target.go
The current real limitation is 1 mount target per AZ, Terraform does not enforce that in any way - ain't saying it should - it just relies on API returning errors. However if the user happens to create 2 mount targets in two different subnets, both in the same AZ, the API simply returns the exact same mount target ID which causes Terraform to manage the same mount target as two resources.
See snippet from a debug log:
https://gist.github.com/radeksimko/f1e3dd1077f18495726528b175b0bb47
and full repro case:
https://gist.github.com/radeksimko/f09b8d8db2764d908b9a009d4df802e0
Acceptance tests:
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=AWSEFSMountTarget'
```
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=AWSEFSMountTarget -timeout 120m
=== RUN …
```
=> aws: Make EFS Mount Target creation fail for 2+ targets per AZ

builtin/providers/aws/resource_aws_iam_role.go
As discussed in https://github.com/hashicorp/terraform/pull/7733#issuecomment-240759666
cc @dtolnay
=> provider/aws: Explain better why we retry IAM role creation

website/source/docs/providers/terraform/d/remote_state.html.md
=> docs: Remove output from `terraform_remote_state`

website/source/docs/providers/aws/r/alb_target_group.html.markdown
=> aws/docs: Add example of aws_alb_target_group

website/source/docs/providers/aws/r/elb.html.markdown
explaining the pattern for health_check's target
=> health_check's target explained

builtin/providers/aws/provider.go, builtin/providers/aws/resource_aws_alb_target_group_attachment.go, builtin/providers/aws/resource_aws_alb_target_group_attachment_test.go, website/source/docs/providers/aws/r/alb_target_group_attachment.html.markdown, website/source/layouts/aws.erb
=> provider/aws: Add aws_alb_target_group_attachment

terraform/context_import_test.go, terraform/transform_import_state.go
Fixes #7691 
A pretty silly change, we were just straight up ignoring the index on import. This fixes that.
=> terraform: import specific index works [GH-7691]

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/service.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go, vendor/github.com/aws/aws-sdk-go/service/kms/api.go, vendor/vendor.json
I'd like to leave this until after 0.7.1 is released so we can get a few sets of nightly acceptance tests out of it!
=> provider/aws: Bump the AWS SDK version to 1.4.2

website/source/assets/stylesheets/_docs.scss, website/source/layouts/archive.erb, website/source/layouts/docs.erb
=> docs: Fix archive provider documentation

helper/resource/state.go
=> Do not sleep between first attempt or between successful attempts

vendor/github.com/hashicorp/hcl/decoder.go, vendor/vendor.json
Will merge once tests pass since review was done in HCL
=> vendor: update HCL for GH-8295

builtin/providers/openstack/resource_openstack_networking_port_v2.go
=> provider/openstack: Add allowed_address_pairs

website/source/docs/providers/aws/r/elastic_beanstalk_environment.html.markdown
It took me some googling to find this and thought it would be good to have an example of how that structure is meant to be right in the docs.
=> Added example of how the Option settings works

builtin/providers/aws/data_source_aws_ecs_container_definition.go, builtin/providers/aws/data_source_aws_ecs_container_definition_test.go
=> Add MemoryReservation To ECS Container Definition

website/source/docs/providers/aws/d/ip_ranges.html.markdown
* **Reasoning for docs update**: typo
* **Relevant Terraform version**: next release(v0.7.3)
=> Fix doc for provider/aws_ip_ranges

builtin/providers/aws/resource_aws_api_gateway_account.go
As we know the AWS IAM service is eventually consistent and although we already have the retry logic in place for this resource it seems there is another (new?) error message returned in case the IAM Role has not been propagated yet.
I discovered this when running API Gateway acceptance tests:
```
=== RUN   TestAccAWSAPIGatewayAccount_basic
--- FAIL: TestAccAWSAPIGatewayAccount_basic (41.95s)
testing.go:265: Step 1 error: Error applying: 1 error(s) occurred:
* aws_api_gateway_account.test: Updating API Gateway Account failed: BadRequestException: API Gateway could not successfully write to CloudWatch Logs using the ARN specified. This account may have reached a limit in CloudWatch Logs.
status code: 400, request id: 3eedb1df-6def-12e6-b761-f503a5eda22b
```
=> provider/aws: Add AWS error message to retry APIGateway acc update on

vendor/github.com/bgentry/go-netrc/LICENSE, vendor/github.com/bgentry/go-netrc/netrc/netrc.go, vendor/github.com/hashicorp/go-getter/get.go, vendor/github.com/hashicorp/go-getter/get_http.go, vendor/github.com/hashicorp/go-getter/netrc.go, vendor/vendor.json
This introduces netrc support for HTTP URLs for module sources.
Getter changed reviewed already. Will merge when tests are green.
=> vendor: update go-getter

builtin/providers/triton/resource_key.go
```
Before
=== RUN   TestAccTritonKey_basic
--- FAIL: TestAccTritonKey_basic (1.60s)
testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
* triton_key.test: failed to get key with name:
caused by: failed unmarshaling/decoding the response body: [{"name":"phinze","fingerprint":"ee:5e:f8:bb:67:a6:60:21:36:5c:73:ce:c6:8b:4d:69","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/zeXD4lIgk7Pm5r8qIM+U9qBHQE8a9aUXCsQd++SlA/hnBXeOLUpSm9vtuGFkknA1A4oQBvp07ngTFUw4y2ZD8GAIimmKywEetc/f2nnAkzxhbQ9C1OX5U1FbGUv+p8u60nB8ZZ/a4SgKA3IloVQ7HXjQmZKOsutE+IrT5FTviHrp6f7bwIhMkZXAuHWmkHlaIYub0TIgvbXujk6bqTGQq+G1yAeOLm2KSv6oU0v1A0aFYKBmcMVdj587fR0D91+DwsUBpmGeGyMBlA7x7eKFCS7Xme9sb9TC4VvkDg1xNIwZHo1ybkFih+l9DBMR7sbgfzeE6AwDxwY3/do7Uqwv phinze"},{"name":"jen20","fingerprint":"1b:bc:29:48:89:af:72:63:f0:83:b …
```
=> provider/triton: Id trying to be used before being set

builtin/providers/mysql/provider.go, builtin/providers/mysql/resource_user.go
Apologies. I've replaced the GH-8251 logic with `hashicorp/go-version`. Fixes GH-8570.
=> Fix breakage caused by MySQL version string parsing introduced in GH-8251

CHANGELOG.md, builtin/providers/fastly/resource_fastly_service_v1.go, website/source/intro/getting-started/build.html.md
=> Minor typos

website/source/docs/providers/aws/r/kinesis_firehose_delivery_stream.html.markdown
0.7.2 - kinesis firehose delivery stream docs
=> Fix multiple typos in current docs

builtin/providers/template/datasource_template_file.go, builtin/providers/template/datasource_template_file_test.go
Reverts hashicorp/terraform#8590
See comments on that thread.
=> Revert "providers/template: template_file supports floating point math"

builtin/providers/aws/resource_aws_efs_file_system.go, builtin/providers/aws/resource_aws_efs_file_system_test.go
This commit is purely a maintenance and clean-up of the resource.
=> provider/aws: Maintenance and clean-up for aws_efs_file_system.

communicator/shared/shared.go, communicator/shared/shared_test.go, communicator/ssh/provisioner.go, communicator/ssh/provisioner_test.go, communicator/winrm/provisioner.go, communicator/winrm/provisioner_test.go
Now you can provision machines over IPv6.
=> IPv6 support for the communicator.

builtin/providers/aws/resource_aws_autoscaling_group.go, builtin/providers/aws/resource_aws_autoscaling_group_test.go, builtin/providers/aws/resource_aws_autoscaling_group_waiting.go, builtin/providers/aws/resource_aws_autoscaling_group_waiting_test.go, builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook.go, builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook_test.go
Closes hashicorp/terraform#5619.
=> providers/aws: support for lifecycle hooks at ASG creation

builtin/providers/postgresql/config.go, builtin/providers/postgresql/provider.go, builtin/providers/postgresql/provider_test.go, builtin/providers/postgresql/resource_postgresql_database.go, builtin/providers/postgresql/resource_postgresql_database_test.go, builtin/providers/postgresql/resource_postgresql_role.go, builtin/providers/postgresql/resource_postgresql_role_test.go
This commit brings the Postgres provider up to "new" standards for error wrapping and nested structure definitions.
=> provider/postgres: Clean up definitions and errors

terraform/state.go
Minor cleanup of some inaccurate comments I noticed regarding state file structure and version.
=> Cleanup inaccurate state structure comments.

builtin/providers/aws/resource_aws_nat_gateway.go, builtin/providers/aws/resource_aws_nat_gateway_test.go
Should resolve hashicorp/terraform/issues/8687
=> adding missing failed states for the NAT Gateways

website/source/docs/configuration/providers.html.md
=> Reword "Multiple Provider Instances" documentation

website/source/docs/providers/vsphere/r/file.html.markdown
the render in the webpage did not show the code blocks for `Upload file to vSphere` section correctly.
=> Updated new lines

config/loader_test.go, vendor/github.com/hashicorp/hcl/Makefile, vendor/github.com/hashicorp/hcl/appveyor.yml, vendor/github.com/hashicorp/hcl/decoder.go, vendor/vendor.json
Add a failing test case. This will be fixed by https://github.com/hashicorp/hcl/pull/152
=> Fix #8820 Regression in loading variables.tf.json from module

website/source/docs/import/usage.html.md
Fixes #8880.
Note that other modifications other than renames can be done with state management commands.
=> Slight tweak to import docs to clarify state management commands

website/source/docs/provisioners/chef.html.markdown
=> Fix typo in chef provisioner

website/source/docs/state/remote/azure.html.md
=> state/remote/azure: Correct documentation

builtin/bins/provider-bitbucket/main.go, builtin/providers/bitbucket/client.go, builtin/providers/bitbucket/provider.go, builtin/providers/bitbucket/provider_test.go, builtin/providers/bitbucket/resource_default_reviewers.go, builtin/providers/bitbucket/resource_default_reviewers_test.go, builtin/providers/bitbucket/resource_hook.go, builtin/providers/bitbucket/resource_hook_test.go, builtin/providers/bitbucket/resource_repository.go, builtin/providers/bitbucket/resource_repository_test.go, command/internal_plugin_list.go, website/source/docs/providers/bitbucket/index.html.markdown, website/source/docs/providers/bitbucket/r/default_reviewers.html.markdown, website/source/docs/providers/bitbucket/r/hook.html.markdown, website/source/docs/providers/bitbucket/r/repository.html.markdown
This is some work I did to make a terraform provider for bitbucket. Not sure what the guides are to add a new provider and setup docs. So I would love some feedback and how to get this into contrib.
=> Initial work on a bitbucket provider for terraform

builtin/providers/bitbucket/resource_hook.go, builtin/providers/bitbucket/resource_repository.go
Implement critique in #7405. 
/cc @stack72 / @cwood
=> provider/bitbucket: Remove unnecessary casts.

builtin/providers/aws/resource_aws_cloudwatch_event_rule.go
=> provider/aws: Handle JSON parsing error in the ReadFunc for the event pattern document.

builtin/providers/aws/resource_aws_glacier_vault.go
=> provider/aws: Handle JSON parsing error in the ReadFunc for the access policy document.

builtin/providers/aws/data_source_aws_cloudformation_stack.go
This commit adds support for new helper function which is used to
normalise JSON string.
=> provider/aws: Update aws_cloudformation_stack data source with new helper function.

builtin/providers/aws/resource_aws_cloudwatch_event_rule.go
This commits allows for the helper function to return an error which
would bubble up from e.g. JSON parsing, etc.
=> provider/aws: Allow buildPutRuleInputStruct helper function to return an error.

builtin/providers/aws/resource_aws_cloudformation_stack.go
=> provider/aws: Handle JSON parsing error in the ReadFunc for various JSON documents.

website/source/docs/providers/aws/r/redshift_cluster.html.markdown
=> Minor spelling correction in AWS Redshift Cluster resource documentation

website/source/docs/providers/aws/r/flow_log.html.markdown
Update aws_flow_log docs with aws_cloudwatch_log_group resource example.
=> provider/aws: Update docs for aws_flow_log

builtin/providers/aws/resource_aws_s3_bucket.go, builtin/providers/aws/website_endpoint_url_test.go
The tests were incorrect. Updated tests and code. See #2259 for initial implementation.
=> Corrected Seoul S3 Website Endpoint

builtin/providers/google/resource_storage_bucket.go, builtin/providers/google/resource_storage_bucket_test.go, website/source/docs/providers/google/r/storage_bucket.html.markdown
Fixes: #7417
https://cloud.google.com/storage/docs/storage-classes
=> provider/google: Add support for GCS StorageClass

website/source/docs/providers/aws/r/rds_cluster_instance.html.markdown
I just realised the docs need changing too.
I really should've submitted this in https://github.com/hashicorp/terraform/pull/9060 😱  Sorry for the extra roundtrip.
=> aws: Fix docs after changing Aurora instance schema

website/source/docs/providers/aws/r/instance.html.markdown
=> Fix docs aws_instance

builtin/providers/openstack/config.go
Correction of the Issue #8735 to use openstack provider trought a proxy.
=> Correct Proxy setting for openstack provider: issue 8735

builtin/providers/aws/resource_aws_vpc_peering_connection.go, builtin/providers/aws/resource_aws_vpc_peering_connection_test.go
This commit adds simple logic which allows for a VPC Peering Connection
that is in a failed state (e.g. due to an overlapping IP address ranges,
etc.), to report such failed state as an error, rather then waiting for
the time out to occur.
=> provider/aws: Make sure that VPC Peering Connection in a failed state returns an error.

builtin/providers/google/resource_sql_database_instance.go
remove some debugging statements
=> provider/google: remove debug spew statement

website/source/docs/modules/create.html.markdown
Updated some style, grammar and formatting.
=> Update of the module creation page

website/source/docs/providers/bitbucket/r/hook.html.markdown, website/source/layouts/bitbucket.erb
=> provider/bitbucket: Add the bitbucket documentation

website/source/docs/modules/usage.html.markdown
Tidied up the page and fixed some formatting, style and naming issues.
=> Rewrite of the module usage page

website/source/docs/modules/sources.html.markdown
A quick rewrite of the page to make it clearer. Fixed some styling, grammar and formatting issues too.
=> Cleanup Module Source page

builtin/providers/aws/resource_aws_ssm_document.go
As noticed in the acceptance tests, we were expecting the document to be
deleted but it was still found
```
=== RUN   TestAccAWSSSMDocument_permission
--- FAIL: TestAccAWSSSMDocument_permission (5.60s)
testing.go:329: Error destroying resource! WARNING: Dangling
resources
Error: Check failed: Expected AWS SSM
Document to be gone, but was still found
State: <no state>
```
=> provider/aws: Add retry to the `aws_ssm_document` delete func

helper/schema/field_reader_diff.go, helper/schema/field_reader_diff_test.go
Given a schema such as:
```
schema := map[string]*Schema{
"list_of_sets_1": &Schema{
Type: TypeList,
Elem: &Resource{
Schema: map[string]*Schema{
"nested_set": &Schema{
Type: TypeSet,
Elem: &Resource{
Schema: map[string]*Schema{
"val": &Schema{
Type: TypeInt,
},
},
},
Set: func(a interface{}) int {
m := a.(map[string]interface{})
return m["val"].(int)
},
},
},
},
},
"list_of_sets_2": &Schema{
Type: TypeList,
Elem: &Resource{
Schema: map[string]*Schema{
"nested_set": &Schema{
Type: TypeSet,
Elem: &Resource{
Schema: map[string]*Schema{
"val": &Schema{
Type: TypeInt,
},
},
},
Set: func(a interface{}) int {
m := a.(map[string]interface{})
return m["val"].(int)
},
},
},
},
},
}
```
And a configuration such as:
```
resource "provider_name_resource_name" "test" {
list_of_sets_1 {
nested_set { …
```
=> Unchanged NestedSets are not returned by DiffFieldReader.

builtin/providers/azurerm/config.go, builtin/providers/azurerm/import_arm_servicebus_subscription_test.go, builtin/providers/azurerm/provider.go, builtin/providers/azurerm/resource_arm_servicebus_subscription.go, builtin/providers/azurerm/resource_arm_servicebus_subscription_test.go, website/source/docs/providers/azurerm/r/servicebus_subscription.html.markdown, website/source/layouts/azurerm.erb
```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMServiceBusSubscription -timeout 120m
=== RUN   TestAccAzureRMServiceBusSubscription_importBasic
--- PASS: TestAccAzureRMServiceBusSubscription_importBasic (339.00s)
=== RUN   TestAccAzureRMServiceBusSubscription_basic
--- PASS: TestAccAzureRMServiceBusSubscription_basic (328.47s)
=== RUN   TestAccAzureRMServiceBusSubscription_update
--- PASS: TestAccAzureRMServiceBusSubscription_update (368.95s)
=== RUN   TestAccAzureRMServiceBusSubscription_updateRequiresSession
--- PASS: TestAccAzureRMServiceBusSubscription_updateRequiresSession (348.47s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	1384.966s
```
=> provider/azurerm: add servicebus_subscription resource

vendor/github.com/mitchellh/copystructure/copystructure.go, vendor/github.com/mitchellh/reflectwalk/reflectwalk.go, vendor/vendor.json
Update to the latest reflectwalk and copystructure packages.
=> Update reflectwalk and copystructure

website/source/docs/providers/azurerm/r/sql_database.html.markdown
* Parameter is Objective, not Object
* Clarify what resource group needs to be used
* Name parameter is the database name
* Link to Azure docs for SQL Database Tiers/Editions/Size limits
=> Fixup some SQL DB docs

helper/schema/schema.go, helper/schema/schema_test.go
This is required for the times when the configuration cannot have an
empty configuration. An example would be in AzureRM, when you create a
LoadBalancer with a configuration, you can delete *all* but 1 of these
configurations
=> helper/schema: Adding of MinItems as a validation to Lists and Maps

website/source/docs/state/remote/gcs.html.md, website/source/docs/state/remote/manta.html.md
Fixes #9245.
Couple documentation fixes for GCS Remote State.
=> Fix documentation for GCS Remote State

Vagrantfile
Added vagrant box with docker support: https://atlas.hashicorp.com/tknerr/boxes/baseimage-ubuntu-14.04
=> Addded docker support to Vagrantfile

vendor/github.com/aws/aws-sdk-go/CHANGELOG.md, vendor/github.com/aws/aws-sdk-go/Makefile, vendor/github.com/aws/aws-sdk-go/aws/client/client.go, vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go, vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go, vendor/github.com/aws/aws-sdk-go/aws/request/offset_reader.go, vendor/github.com/aws/aws-sdk-go/aws/request/request.go, vendor/github.com/aws/aws-sdk-go/aws/session/session.go, vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/service.go, vendor/github.com/aws/aws-sdk-go/service/efs/service.go, vendor/github.com/aws/aws-sdk-go/service/kms/api.go, vendor/github.com/aws/aws-sdk-go/service/opsworks/api.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/github.com/aws/aws-sdk-go/service/waf/api.go, vendor/vendor.json
This will include the fix for the error:
```
Request body type has been overwritten. May cause race conditions
```
=> provider/aws: Bump version of AWS SDK to 1.4.15

vendor/github.com/hashicorp/hcl/hcl/ast/ast.go, vendor/github.com/hashicorp/hcl/hcl/parser/parser.go, vendor/github.com/hashicorp/hcl/hcl/printer/nodes.go, vendor/github.com/hashicorp/hcl/json/parser/parser.go, vendor/vendor.json
This fixes primarily printer issues with JSON, list comments, and bare
comments not attached to anything in particular.
=> update HCL vendor

website/source/intro/examples/aws.html.markdown, website/source/intro/examples/consul.html.markdown, website/source/intro/examples/count.markdown, website/source/intro/examples/cross-provider.markdown
1. Changed the `Example Contents` header to something more descriptive.
2. Minor edits for grammar and formatting.
=> Updated the examples

website/source/docs/provisioners/file.html.markdown
Fixed link and some minor formatting.
=> Fixed 404'ed link

builtin/providers/aws/config.go
This pull request is intended to add a temporary control to Terraform to output more verbose logging in the case of an AuthFailure error being returned by the AWS API.
cc @phinze, @sean-
=> provider/aws: Add extra logging on AuthFailure

website/source/docs/provisioners/chef.html.markdown
1. Fixed some formatting issues.
2. Fixed some grammar and structure issues.
=> Some edits to the Chef provisioner page

website/source/docs/provisioners/connection.html.markdown
1. Updated formatting.
2. Updated some grammar and structure.
=> Updates to the Connection docs

website/source/intro/getting-started/provision.html.md
1. Updated some formatting.
2. Tidied the example a little to make it less clunky.
3. Rewrote some text to make things clearer.
=> Updated provisioning getting started

builtin/providers/aws/resource_aws_s3_bucket_object.go
=> Remove If-Match check and update ETag in state based on HeadObject
