hashicorp/terraform

builtin/providers/github/provider.go
builtin/providers/github/resource_github_repository.go
builtin/providers/github/resource_github_repository_test.go
website/source/docs/providers/github/r/repository.html.markdown
website/source/docs/providers/github/r/team_repository.html.markdown
website/source/layouts/github.erb

Allows creation of repositories within the organization configured on the provider.

provider/github: github_repository resource

---

builtin/providers/aws/ec2_filters.go
builtin/providers/aws/ec2_filters_test.go

Makes the output deterministic, and fixes a failing test.

Make buildEC2AttributeFilterList output sorted

---

website/source/docs/configuration/variables.html.md
website/source/intro/getting-started/variables.html.md

1. Fixes a duplicate word.
2. Fixes a variety of formatting.
3. Re-structures variable assignment section.
4. Sets Notes to consistent style.

Some edits to the variables sections

---

command/apply_test.go

Wait for our expected number of goroutines to be staged and ready, then
allow Run() to complete. Use a high-water-mark counter to ensure we
never exceeded the max expected concurrent goroutines at any point
during the run.

Make TestApply_parallelism more reliable

---

builtin/providers/rabbitmq/resource_vhost_test.go
command/init.go
command/push_test.go
command/remote_config.go
state/testing.go

None were critical, but these will fail with the next version of vet.

Fix vet issues

---

website/source/docs/providers/azurerm/index.html.markdown

Added updated instructions for creating app registration in the new ARM portal.  Updated instructions for granting permissions to the app registration as well.

Update to new portal experience

---

website/source/docs/configuration/resources.html.md
website/source/docs/configuration/variables.html.md

1. Added a heredoc example to the variables page.
2. Tidied up and added headers.
3. Some minor whitespace and grammar edits.

Cleanup of the resources and variables pages

---

website/source/docs/providers/aws/r/cloudformation_stack.html.markdown

**Reasoning for doc update**
Usage of parameters wasn't very obvious in the docs, and referred to a list of `Parameter structures` without describing what those were. After looking into the code, this is what I determined to be be how to use parameters. I felt adding an example into the documentation would help others in the future.

Added a Parameter example

---

website/source/docs/configuration/resources.html.md

I am not sure `provider` IS a meta-param but it looks like one...

Added provider to meta-param resource docs

---

builtin/providers/aws/data_source_aws_ami.go
builtin/providers/aws/data_source_aws_ami_test.go

This commit adds a simple ValidateFunc to check whether the regular
expression that was passed down via the `name_regex` attribute is valid.

provider/aws: Validate regular expression passed via the `name_regex` attribute.

---

config/interpolate_funcs.go
config/interpolate_funcs_test.go
website/source/docs/configuration/interpolation.html.md

The title function returns a copy of the string with the first characters of all the words capitalized.

Adds ‘title’ built-in function.

---

builtin/providers/openstack/resource_openstack_fw_rule_v1.go
builtin/providers/openstack/resource_openstack_fw_rule_v1_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/fwaas/rules/requests.go
vendor/vendor.json
website/source/docs/providers/openstack/r/fw_rule_v1.html.markdown

This commit allows a protocol of "any" to be used in the firewall
rule resource, which will allow any protocol.
Fixes #7507 
/cc @carlpett

provider/openstack: Allow any protocol in openstack_fw_rule_v1

---

website/source/docs/configuration/interpolation.html.md

This little note should help users until the issue #9169 is addressed.

Add a note about operator precedence. #9169

---

vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
vendor/github.com/hashicorp/hcl/json/parser/flatten.go
vendor/github.com/hashicorp/hcl/json/parser/parser.go
vendor/vendor.json

A couple commits from HCL, approved there. Will wait for Travis to pass then merge.

vendor: update HCL

---

website/source/docs/configuration/interpolation.html.md
website/source/docs/configuration/variables.html.md
website/source/intro/getting-started/variables.html.md

Fixes some grammar, typos and structure. Updated some headings and fixed
a couple of spelling mistakes.

Pass over the Interpolation page

---

website/source/docs/state/remote/s3.html.md

In response to comments in #1964.

Cleanup and expansion of the S3 remote state documentation

---

vendor/github.com/cloudflare/cloudflare-go/LICENSE
vendor/github.com/cloudflare/cloudflare-go/README.md
vendor/github.com/cloudflare/cloudflare-go/cloudflare.go
vendor/github.com/cloudflare/cloudflare-go/cpage.go
vendor/github.com/cloudflare/cloudflare-go/dns.go
vendor/github.com/cloudflare/cloudflare-go/ips.go
vendor/github.com/cloudflare/cloudflare-go/keyless.go
vendor/github.com/cloudflare/cloudflare-go/railgun.go
vendor/github.com/cloudflare/cloudflare-go/user.go
vendor/github.com/cloudflare/cloudflare-go/waf.go
vendor/github.com/cloudflare/cloudflare-go/zone.go
vendor/vendor.json

To avoid the issue #8011 I have updated the used client library, with
this update I don't get the mentioned issues like `unexpected EOF`
anymore.
Fixes #8011

provider/cloudflare: Updated github.com/cloudflare/cloudflare-go

---

builtin/providers/aws/resource_aws_iam_user_policy_attachment_test.go

Was failing due to using IAM user `test-name` as it was being used in
more than 1 place - this has been replaced by a random user and random
policy names now
```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSUserPolicyAttachment_basic'                                                                               2 ↵ ✹
2016/10/31 08:39:08 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSUserPolicyAttachment_basic -timeout 120m
=== RUN   TestAccAWSUserPolicyAttachment_basic
--- PASS: TestAccAWSUserPolicyAttachment_basic (32.04s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	32.053s
```

provider/aws: Make iam_user_policy_attachment_test work as expected:

---

website/source/intro/getting-started/build.html.md

Very minor fix in the docs

---

website/source/docs/providers/do/r/domain.html.markdown
website/source/docs/providers/do/r/droplet.html.markdown
website/source/docs/providers/do/r/record.html.markdown

Specifically:
- User data is available in all regions, so remove the sentence saying to check for supported features in each region.
- Clarify domain vs. DNS record resources.
- Explain which DNS record types the `weight`, `port`, and `priority` arguments are applicable for.

provider/digitalocean: Update resource docs for website

---

builtin/providers/openstack/config.go
builtin/providers/openstack/provider.go
website/source/docs/providers/openstack/index.html.markdown

This series of commits makes the following changes to the OpenStack Provider configuration:
- Updates provider environment variables
- Makes the password field sensitive
- Adds Descriptions for all provider options
- Cleans up the Provider documentation
- Cleans up the EndpointType check
Fixes #8757
Fixes #8756
Fixes #7041

provider/openstack: Openstack Provider Updates

---

builtin/providers/postgresql/provider.go
builtin/providers/postgresql/resource_postgresql_extension.go
builtin/providers/postgresql/resource_postgresql_extension_test.go
website/source/docs/providers/postgresql/r/postgresql_extension.html.markdown
website/source/layouts/postgresql.erb

This change adds support for installing postgresql extensions on a
postgresql server.

provider/postgresql: Create provider for postgresql extensions

---

website/source/docs/configuration/interpolation.html.md

Fixed typo on interpolation docs

---

vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
vendor/vendor.json

Fix issue with double base64 encoding userdata value.
Fixes #9965

vendor: Update github.com/gophercloud/gophercloud

---

builtin/providers/aws/resource_aws_iam_role.go
builtin/providers/aws/resource_aws_iam_role_test.go
website/source/docs/providers/aws/r/iam_role.html.markdown

provider/aws: Exposed aws_iam_role create_date attribute

---

builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream.go
builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream_test.go

provider/aws: kinesis_firehose_delivery_stream: Fixed ES buffering_interval option

---

terraform/eval_diff.go

Reverts hashicorp/terraform#9118

Revert "[WIP] core: Log diff mismatch using spew instead of %#v"

---

vendor/github.com/hashicorp/hil/parser/binary_op.go
vendor/github.com/hashicorp/hil/parser/parser.go
vendor/vendor.json
website/source/docs/configuration/interpolation.html.md

vendor: update HIL

---

website/source/docs/providers/aws/r/elb.html.markdown

- Doc update to explicitly call out ELB defaults (so I don't have to look
at the source again :)

Doc Update for ELB defaults

---

vendor/github.com/hashicorp/hil/parser/parser.go
vendor/vendor.json

vendir: update HIL

---

CHANGELOG.md

It wasn't clear to me what this change meant.

Make template_file change more explicit

---

CHANGELOG.md

Typo'ed duh

---

builtin/providers/aws/import_aws_cloudwatch_log_group_test.go
builtin/providers/aws/resource_aws_cloudwatch_log_group_test.go
builtin/providers/aws/resource_aws_codecommit_repository_test.go

failures
* codecommit
* cloudwatch_logs

provider/aws: Fixing up acceptance tests after seeing concurrent

---

builtin/providers/aws/import_aws_rds_cluster_parameter_group_test.go
builtin/providers/aws/resource_aws_rds_cluster_parameter_group_test.go

This should allow tests to run concurrently.

provider/aws: Randomize names for Parameter Group tests

---

website/source/docs/providers/google/d/google_iam_policy.html.markdown

Small typo

---

builtin/providers/aws/cloudfront_distribution_configuration_structure.go
builtin/providers/aws/resource_aws_cloudfront_distribution.go
builtin/providers/aws/resource_aws_cloudfront_distribution_test.go
website/source/docs/providers/aws/r/cloudfront_distribution.html.markdown

/cc @paddyforan @stack72 
Fixes #9276 
Fixes #10327

IPv6 Support To Cloudfront

---

.travis.yml
Vagrantfile

go 1.7.4 came out today (security release)

Update Travis and Vagrant to go 1.7.4

---

website/source/intro/getting-started/variables.html.md

also include a Note regarding restrictions on the types environment variables can set.
+line length cleanup

Explain list-type variables, and their use

---

builtin/providers/aws/resource_aws_opsworks_application.go
builtin/providers/aws/resource_aws_opsworks_application_test.go

provider/aws resource_aws_opsworks_application does not accept document_root parameter

---

builtin/providers/azurerm/loadbalancer.go
builtin/providers/azurerm/resource_arm_availability_set.go
builtin/providers/azurerm/resource_arm_cdn_endpoint.go
builtin/providers/azurerm/resource_arm_cdn_profile.go
builtin/providers/azurerm/resource_arm_loadbalancer.go
builtin/providers/azurerm/resource_arm_loadbalancer_backend_address_pool.go
builtin/providers/azurerm/resource_arm_loadbalancer_nat_pool.go
builtin/providers/azurerm/resource_arm_loadbalancer_nat_rule.go
builtin/providers/azurerm/resource_arm_loadbalancer_probe.go
builtin/providers/azurerm/resource_arm_loadbalancer_rule.go
builtin/providers/azurerm/resource_arm_loadbalancer_test.go
builtin/providers/azurerm/resource_arm_local_network_gateway.go
builtin/providers/azurerm/resource_arm_network_interface_card.go
builtin/providers/azurerm/resource_arm_network_security_group.go
builtin/providers/azurerm/resource_arm_network_security_rule.go
builtin/providers/azurerm/resource_arm_public_ip.go
builtin/providers/azurerm/resource_arm_route.go
builtin/providers/azurerm/resource_arm_route_table.go
builtin/providers/azurerm/resource_arm_servicebus_subscription.go
builtin/providers/azurerm/resource_arm_servicebus_topic.go
builtin/providers/azurerm/resource_arm_storage_account.go
builtin/providers/azurerm/resource_arm_storage_share.go
builtin/providers/azurerm/resource_arm_subnet.go
builtin/providers/azurerm/resource_arm_traffic_manager_endpoint.go
builtin/providers/azurerm/resource_arm_traffic_manager_profile.go
builtin/providers/azurerm/resource_arm_virtual_machine.go
builtin/providers/azurerm/resource_arm_virtual_machine_extension.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go
builtin/providers/azurerm/resource_arm_virtual_network.go
builtin/providers/azurerm/resource_arm_virtual_network_peering.go

Updating a *ton* of property names and a couple of constructor signatures to make the build pass under Azure SDK for Go v7.0.1 - hold onto your hats!

provider/azurerm: fixing the build for SDK 7.0.1

---

builtin/providers/azurerm/resource_arm_availability_set_test.go
builtin/providers/azurerm/resource_arm_cdn_endpoint_test.go
builtin/providers/azurerm/resource_arm_cdn_profile_test.go
builtin/providers/azurerm/resource_arm_eventhub_namespace_test.go
builtin/providers/azurerm/resource_arm_local_network_gateway_test.go
builtin/providers/azurerm/resource_arm_network_interface_card_test.go
builtin/providers/azurerm/resource_arm_network_security_group_test.go
builtin/providers/azurerm/resource_arm_network_security_rule_test.go
builtin/providers/azurerm/resource_arm_public_ip_test.go
builtin/providers/azurerm/resource_arm_route_table_test.go
builtin/providers/azurerm/resource_arm_route_test.go
builtin/providers/azurerm/resource_arm_servicebus_namespace_test.go
builtin/providers/azurerm/resource_arm_servicebus_subscription_test.go
builtin/providers/azurerm/resource_arm_servicebus_topic_test.go
builtin/providers/azurerm/resource_arm_storage_account_test.go
builtin/providers/azurerm/resource_arm_subnet_test.go
builtin/providers/azurerm/resource_arm_template_deployment_test.go
builtin/providers/azurerm/resource_arm_traffic_manager_endpoint_test.go
builtin/providers/azurerm/resource_arm_traffic_manager_profile_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_extension_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_test.go
builtin/providers/azurerm/resource_arm_virtual_network_peering_test.go
builtin/providers/azurerm/resource_arm_virtual_network_test.go

cc @stack72 fixed the tests so they build (so we can run them)

provider/azurerm: fixing the acceptance test build under sdk 7.0.1

---

vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/vendor.json

vendor: update homedir

---

builtin/providers/azurerm/resource_arm_availability_set.go

This PR is a proposed fix to handle [Issue 10544](https://github.com/hashicorp/terraform/issues/10544).
An update to either the fault domain count or the update domain count should force a recreate of the resource.

Force a recreate if the numbers for the AS are changed.

---

website/source/docs/providers/aws/r/emr_cluster.html.md

docs/aws: Fix the discrepencies of the emr_cluster documentation

---

website/source/docs/configuration/resources.html.md

Note is formatted wrong and is hence not rendering.

Fixed note formatting

---

website/source/docs/providers/aws/r/elasticache_replication_group.html.markdown

A work in progress PR to address the documentation issues in #10127

[WIP] provider/aws: Update Elasticache docs for corrections, clarity

---

builtin/providers/aws/resource_aws_db_instance.go

Closes https://github.com/hashicorp/terraform/issues/9988
Not sure if we want to add a test for that (since it can be verrrrrrry long).

provider/aws: Set the DBName when restoring from a snapshot

---

builtin/providers/aws/resource_aws_lambda_function.go
builtin/providers/aws/resource_aws_lambda_function_test.go

Closes https://github.com/hashicorp/terraform/issues/10270

provider/aws: Added Lambda function guard when needed attributes are not set

---

builtin/providers/aws/resource_aws_s3_bucket.go
website/source/docs/providers/aws/r/s3_bucket.html.markdown

provider/aws: Support MFA delete for s3 bucket versioning

---

builtin/providers/rundeck/resource_job.go
builtin/providers/rundeck/resource_job_test.go
vendor/github.com/apparentlymart/go-rundeck-api/README.md
vendor/github.com/apparentlymart/go-rundeck-api/rundeck/job.go
vendor/github.com/apparentlymart/go-rundeck-api/rundeck/job_test.go
vendor/vendor.json

Hi guys,
Rundeck provider cannot create scheduled jobs (understand cronjobs).
This PR make it possible ;-)
Also upgraded go-rundeck library.

Improving Rundeck provider: scheduler

---

vendor/vendor.json

This previously referenced `github.com/lrsmith/terraform`
Fixes issue #10699

correct `rootPath`

---

website/source/layouts/aws.erb

* aws_vpc_endpoint_service data service
* aws_vpc_endpoint_route_table_association resource

Fix a couple of missing links

---

.travis.yml

Go 1.8beta2 is here. Adding to Travis :)

build: Update Travis to Go 1.8beta2

---

builtin/providers/aws/import_aws_efs_mount_target_test.go
builtin/providers/aws/import_aws_flow_log_test.go
builtin/providers/aws/resource_aws_efs_mount_target_test.go
builtin/providers/aws/resource_aws_flow_log_test.go

Should fix at lest ~2 of the failing tests we have due to our test being ran in parallel

provider/aws: More randomization so our tests can run in parallel

---

website/source/docs/providers/aws/r/opsworks_rds_db_instance.html.markdown

- Fix broken document ... [aws/opsworks_rds_db_instance](https://www.terraform.io/docs/providers/aws/r/opsworks_rds_db_instance.html)

provider/aws: Fix broken documentat

---

builtin/providers/aws/import_aws_lambda_function_test.go
builtin/providers/aws/resource_aws_lambda_function_test.go

Randomize the IAM things in our Lambda tests so they can be ran in parallel. Running tests locally, will share results and merge if they all pass

provider/aws: More randomiztion for lambda tests 💕

---

website/source/layouts/aws.erb

docs/aws: Add aws_autoscaling_attachment to the nav bar

---

.github/CONTRIBUTING.md

Fix a few typos in contributing guidelines

---

builtin/providers/openstack/resource_openstack_compute_instance_v2_test.go
website/source/docs/providers/openstack/r/compute_instance_v2.html.markdown

This commit adds some basic tests for block device functionality. It also
expands the existing block device documentation as well references the
new "volume attach" resources for further block storage functionality.

provider/openstack: Block Device Tests and Docs

---

builtin/providers/aws/resource_aws_db_instance.go

Update rds password if provided while creating from snapshot

---

website/source/docs/providers/google/r/container_cluster.html.markdown

Adapts docs to the change made in PR #10817.

GKE: Fix docs for node_version

---

state/remote/swift.go
website/source/docs/state/remote/swift.html.md

Just a small change, adding token authentication for Swift, just like elsewhere in OpenStack related stuff.

Swift token auth

---

builtin/providers/aws/resource_aws_spot_fleet_request.go

provider/aws: Fix typo in error code for aws_spot_fleet

---

builtin/providers/openstack/resource_openstack_lb_member_v2.go

This commit accounts for a 409 response when a LBaaS v2 member is
being created. Rather than error out, this should be considered a
pending state.
Fixes #10852

provider/openstack: 409 Response on Member Create

---

builtin/providers/aws/resource_aws_opsworks_instance.go
builtin/providers/aws/resource_aws_opsworks_instance_test.go
vendor/github.com/aws/aws-sdk-go/service/opsworks/api.go
website/source/docs/providers/aws/r/opsworks_instance.html.markdown

Add support for instance tenancy in `aws_opsworks_instance`

---

builtin/providers/azurerm/config.go
builtin/providers/azurerm/import_arm_eventhub_consumer_group_test.go
builtin/providers/azurerm/provider.go
builtin/providers/azurerm/resource_arm_eventhub_consumer_group.go
builtin/providers/azurerm/resource_arm_eventhub_consumer_group_test.go
website/source/docs/providers/azurerm/r/eventhub.html.markdown
website/source/docs/providers/azurerm/r/eventhub_consumer_group.html.markdown
website/source/layouts/azurerm.erb

provider/azurerm: Event Hubs Consumer Groups

---

builtin/providers/openstack/import_openstack_fw_firewall_v1_test.go
builtin/providers/openstack/import_openstack_fw_policy_v1_test.go
builtin/providers/openstack/import_openstack_fw_rule_v1_test.go
builtin/providers/openstack/resource_openstack_fw_firewall_v1_test.go
builtin/providers/openstack/resource_openstack_fw_policy_v1_test.go
builtin/providers/openstack/resource_openstack_fw_rule_v1_test.go
builtin/providers/openstack/resource_openstack_lb_listener_v2_test.go
builtin/providers/openstack/resource_openstack_lb_loadbalancer_v2_test.go
builtin/providers/openstack/resource_openstack_lb_member_v2_test.go
builtin/providers/openstack/resource_openstack_lb_monitor_v2_test.go
builtin/providers/openstack/resource_openstack_lb_pool_v2_test.go

Part 3 of 5. I'd submit all, but I'm rebasing and retesting them as I go just to make sure everything is good.

provider/openstack: Updating FWaaS and LBaaS v2 Acceptance Tests

---

builtin/providers/openstack/resource_openstack_lb_pool_v1_test.go
builtin/providers/openstack/resource_openstack_networking_floatingip_v2_test.go
builtin/providers/openstack/resource_openstack_networking_network_v2_test.go
builtin/providers/openstack/resource_openstack_networking_port_v2_test.go
builtin/providers/openstack/resource_openstack_networking_router_interface_v2_test.go
builtin/providers/openstack/resource_openstack_networking_router_route_v2_test.go
builtin/providers/openstack/resource_openstack_networking_router_v2_test.go
builtin/providers/openstack/resource_openstack_networking_secgroup_rule_v2_test.go
builtin/providers/openstack/resource_openstack_networking_secgroup_v2_test.go
builtin/providers/openstack/resource_openstack_networking_subnet_v2_test.go
builtin/providers/openstack/resource_openstack_objectstorage_container_v1_test.go

provider/openstack: Network and Object Storage Acceptance Test Cleanup

---

builtin/providers/openstack/resource_openstack_lb_member_v1_test.go
builtin/providers/openstack/resource_openstack_lb_monitor_v1_test.go
builtin/providers/openstack/resource_openstack_lb_pool_v1_test.go
builtin/providers/openstack/resource_openstack_lb_vip_v1_test.go

provider/openstack: Updating LBaaSV1 acceptance tests

---

builtin/providers/azurerm/import_arm_eventhub_authorization_rule_test.go
builtin/providers/azurerm/provider.go
builtin/providers/azurerm/resource_arm_eventhub_authorization_rule.go
builtin/providers/azurerm/resource_arm_eventhub_authorization_rule_test.go
website/source/docs/providers/azurerm/r/eventhub_authorization_rule.html.markdown
website/source/docs/providers/azurerm/r/eventhub_consumer_group.html.markdown
website/source/layouts/azurerm.erb

provider/azurerm: EventHub Authorization Rules

---

builtin/providers/aws/resource_aws_elasticache_replication_group.go

provider/aws: Add snapshotting to the list of pending state for elasticache

---

examples/google-internal-load-balancing/.gitignore
examples/google-internal-load-balancing/README.md
examples/google-internal-load-balancing/main.tf
examples/google-internal-load-balancing/output.tf
examples/google-internal-load-balancing/startup.sh
examples/google-internal-load-balancing/terraform.tfvars.example
examples/google-internal-load-balancing/variables.tf

google: Add example for Internal Load Balancing

---

README.md

Minor update to formatting for a specific directory name.

Minor formatting change

---

.travis.yml

Testing Travis compile for Windows platform

Build for Windows in Travis

---

CHANGELOG.md

BC note on the Arukas provider

Update CHANGELOG.md with BC for v0.8.4

---

builtin/providers/scaleway/helpers.go

the CI sees many failing Scaleway tests due to request quotas being exceeded.
this PR aims to address this issue by switching from `resource.Retry`, which
waits 100ms between retries, to `resource.StateChangeConf` with a configured
delay of 5s between retries.
this should help us fixing the quota issue…

provider/scaleway: improve test reliability

---

website/source/docs/providers/google/d/google_iam_policy.html.markdown

For #10650.
@devth how does this sound?

providers/google: Add link to setIamPolicy restrictions in iam docs

---

website/source/community.html.erb

Adds myself to the list of TF employees

website/docs: Add Grubernaut

---

Makefile
builtin/providers/aws/resource_aws_opsworks_application_test.go
builtin/providers/aws/resource_aws_opsworks_custom_layer_test.go
builtin/providers/aws/resource_aws_opsworks_permission_test.go
builtin/providers/aws/resource_aws_opsworks_stack_test.go
builtin/providers/aws/resource_aws_opsworks_user_profile_test.go
builtin/providers/ignition/resource_ignition_filesystem_test.go
builtin/providers/ignition/resource_ignition_raid_test.go
builtin/providers/ignition/resource_ignition_systemd_unit_test.go
builtin/providers/ignition/resource_ignition_user_test.go

Fix the Makefile to vet all subdirectories except vendor/.
Fix vet errors in providers.

vet all packages

---

builtin/providers/ignition/provider.go
builtin/providers/ignition/provider_test.go
builtin/providers/ignition/resource_ignition_networkd_unit.go
builtin/providers/ignition/resource_ignition_systemd_unit.go
builtin/providers/ignition/resource_ignition_systemd_unit_test.go
website/source/docs/providers/ignition/r/systemd_unit.html.md

Fixes: https://github.com/hashicorp/terraform/issues/11133

provider/ignition: allowing empty systemd.content when a dropin is provided

---

builtin/providers/scaleway/provider.go
builtin/providers/scaleway/provider_test.go

properly fetch configuration from env - leftover from #10874

provider/scaleway: fix provider configuration

---

terraform/state.go
terraform/state_test.go

When a InstanceState is merged with an InstanceDiff, any maps arrays or
sets that no longer exist are shown as empty with a count of 0. If these
are left in the flatmap structure, they will cause errors during
expansion because their existing in the map affects the counts for
parent structures.
Fixes #11170

Remove 0 counts from flatmap during MergeDiff

---

builtin/providers/openstack/resource_openstack_networking_router_interface_v2.go

provider/openstack: Increase deletion timeout for router interfaces

---

website/source/docs/providers/google/r/sql_database_instance.html.markdown

Additionnal information for machine type, which is the new name of "tiers".

Additionnal information for machine type

---

.travis.yml

go1.8 should be just around the corner :)

build: Update travis for go1.8rc2

---

builtin/provisioners/remote-exec/resource_provisioner.go
builtin/provisioners/remote-exec/resource_provisioner_test.go

Fixes #11145.
The provisioner collected all inline commands into a single script which meant
only the exit code of the last command was actually checked for an error.

provisioner/remote-exec: fail on first inline script with bad exit code

---

website/source/intro/getting-started/variables.html.md

Fix doc typo

---

builtin/providers/aws/resource_aws_s3_bucket.go

Looks like I missed this one in #9273--sorry about that!
cc @joelittlejohn
[Resolves #10061]

Set correct aws partition on s3 resource.

---

vendor/github.com/gophercloud/gophercloud/FAQ.md
vendor/github.com/gophercloud/gophercloud/README.md
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/floatingips/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
vendor/vendor.json

This update fixes two upstream bugs:
* Instance Personality was broke
* Instance Floating IPs could not be unmarshaled in certain situations

vendor: Updates to Gophercloud

---

builtin/providers/ns1/provider.go
builtin/providers/ns1/resource_record.go
builtin/providers/ns1/resource_record_test.go
builtin/providers/ns1/resource_team_test.go
builtin/providers/ns1/resource_zone.go
terraform/state.go
terraform/state_test.go
vendor/gopkg.in/ns1/ns1-go.v2/LICENSE.txt
vendor/gopkg.in/ns1/ns1-go.v2/Makefile
vendor/gopkg.in/ns1/ns1-go.v2/README.md
vendor/vendor.json
website/source/docs/providers/ns1/index.html.markdown
website/source/docs/providers/ns1/r/apikey.html.markdown
website/source/docs/providers/ns1/r/datafeed.html.markdown
website/source/docs/providers/ns1/r/datasource.html.markdown
website/source/docs/providers/ns1/r/monitoringjob.html.markdown
website/source/docs/providers/ns1/r/record.html.markdown
website/source/docs/providers/ns1/r/team.html.markdown
website/source/docs/providers/ns1/r/user.html.markdown
website/source/docs/providers/ns1/r/zone.html.markdown
website/source/layouts/ns1.erb

- Includes merge from master that fixed failing acctest.
- Adds ns1-go rest client via govendor
- Adds docs around some more resources
- `go vet` is green on provider

Ns1 provider

---

vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
vendor/github.com/hashicorp/hcl/hcl/printer/nodes.go
vendor/vendor.json

Fixes #11209 
Fixes #11208
This contains lots of awesome formatting fixes in addition to the above. See the diff for more info!

vendor update HCL

---

builtin/providers/aws/resource_aws_spot_fleet_request.go

Fixes https://github.com/hashicorp/terraform/issues/10828
Currently if you have `terminate_instances_with_expiration = false` in a `aws_spot_fleet_request` then the plan will error when updating (destroying then creating) the resource with the following:
```
aws_spot_fleet_request.fleet: Still destroying... (5m0s elapsed)
Error applying plan:
aws_spot_fleet_request.fleet: fleet still has (1) running instances
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hashicorp/terraform/10953)

only wait for spot fleet instance termination if requested

---

vendor/github.com/hashicorp/go-getter/README.md
vendor/github.com/hashicorp/go-getter/client.go
vendor/github.com/hashicorp/go-getter/get.go
vendor/github.com/hashicorp/go-getter/get_file.go
vendor/github.com/hashicorp/go-getter/get_file_unix.go
vendor/github.com/hashicorp/go-getter/get_git.go
vendor/github.com/hashicorp/go-getter/get_hg.go
vendor/github.com/hashicorp/go-getter/get_http.go
vendor/github.com/hashicorp/go-getter/get_mock.go
vendor/github.com/hashicorp/go-getter/get_s3.go
vendor/vendor.json

Update `go-getter` to include the latest updates from everyone's favorite @ryanuber

dependency: update go-getter

---

builtin/providers/aws/resource_aws_api_gateway_resource.go
builtin/providers/aws/resource_aws_api_gateway_resource_test.go

Fix: path not updated when modifying AWS API Gateway Resource

---

website/source/docs/providers/google/r/google_project.html.markdown

Signed-off-by: Kevin Kelani <kkelani@pivotal.io>

Remove duplicate google_project.project_id argument reference.

---

builtin/providers/ignition/resource_ignition_user.go
builtin/providers/ignition/resource_ignition_user_test.go

provider/ignition: Allow to add authorized keys without user creation

---

website/source/docs/providers/aws/r/iam_role.html.markdown

landed on https://github.com/hashicorp/terraform/issues/5541 and wanted to take a shot at adding the appropriate details to the iam role page.

Adding details around using a data source

---

website/source/docs/providers/do/r/tag.html.markdown

Fix do doc small typo

---

website/source/docs/providers/google/r/sql_database_instance.html.markdown

Fixes #9088.
Original PR is stale since Sept.

ip_address is an array and requires the instance number

---

builtin/providers/aws/resource_aws_kms_key.go

fixes https://github.com/hashicorp/terraform/issues/6576

provider/aws: retry CreateKey if arn in policy not yet seen

---

builtin/providers/aws/import_aws_db_subnet_group_test.go
builtin/providers/aws/resource_aws_db_instance_test.go
builtin/providers/aws/resource_aws_db_subnet_group_test.go
builtin/providers/aws/resource_aws_elastic_beanstalk_configuration_template_test.go

provider/aws: Handful of Acc configuration tests

---

builtin/providers/cloudstack/resource_cloudstack_port_forward.go

The existing hash function for set items cannot generate consistent hashes when using both `Optional` and `Computed` on a schema field.
I tried to add this use case to the existing code base, but came to the conclusion this would be quite an endeavor.
That together with the fact this is the only field in all sets used in all builtin providers/resources that would be using both options at the same time, made me decide to change this single resource instead.

provider/cloudstack: make the hash consistent again

---

builtin/providers/aws/data_source_aws_instance_test.go

Fixes 2 acceptance tests for the `aws_instance` data source
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSInstanceDataSource_SecurityGroups'
2017/01/31 12:12:15 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSInstanceDataSource_SecurityGroups -timeout 120m
=== RUN   TestAccAWSInstanceDataSource_SecurityGroups
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (119.14s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    119.172s
```
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSInstanceDataSource_tags'
==> Checking that code complies with gofmt …
```

provider/aws: Fix aws instance data source acceptance tests

---

builtin/providers/aws/data_source_aws_ecs_cluster.go
builtin/providers/aws/data_source_aws_ecs_cluster_test.go
website/source/docs/providers/aws/d/ecs_cluster.html.markdown
website/source/layouts/aws.erb

Adds documentation for the ECS Cluster Data Source. Also removes duplicate struct declarations from the data source and test.

documentation: Add documentation for the ECS Cluster Data Source

---

builtin/providers/aws/resource_aws_volume_attachment.go

If an `aws_volume_attachment` is identical to one that already exists in the API, don't attempt to re-create it (which fails), simply act as though the creation command had already been run and continue.
This allows Terraform to cleanly recover from a situation where a volume attachment action hangs indefinitely, possibly due to a bad instance state, requiring manual intervention such as an instance reboot. In such a situation, Terraform believes the attachment has failed, when in fact
it succeeded after the timeout had expired. On the subsequent retry run, attempting to re-create the attachment will fail outright, due to the `AttachVolume` API call being non-idempotent. This patch implements the idempotency client-side by matching the `(name, vID, iID)` tuple.
Note that volume …

provider/aws: Succeed creating aws_volume_attachment if identical attachment exists

---

builtin/providers/aws/resource_aws_lambda_event_source_mapping_test.go
builtin/providers/aws/resource_aws_lambda_function_test.go

Working on more, but I have these to fix some name collisions we have in our tests, so I'm merging them now

provider/aws: Some Lambda test fixes

---

builtin/providers/google/resource_compute_instance.go
builtin/providers/google/resource_compute_instance_test.go

This adds a test to the existing PR #9320. Kudos to @bjorand for finding this issue and submitting the fix!

Add test to PR 9320

---

builtin/providers/aws/resource_aws_db_instance_test.go
builtin/providers/aws/resource_aws_elastic_transcoder_pipeline_test.go

```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSElasticTranscoderPipeline -timeout 120m
=== RUN   TestAccAWSElasticTranscoderPipeline_basic
--- PASS: TestAccAWSElasticTranscoderPipeline_basic (21.11s)
=== RUN   TestAccAWSElasticTranscoderPipeline_kmsKey
--- PASS: TestAccAWSElasticTranscoderPipeline_kmsKey (42.33s)
=== RUN   TestAccAWSElasticTranscoderPipeline_notifications
--- PASS: TestAccAWSElasticTranscoderPipeline_notifications (35.21s)
=== RUN   TestAccAWSElasticTranscoderPipeline_withContentConfig
--- PASS: TestAccAWSElasticTranscoderPipeline_withContentConfig (40.81s)
=== RUN   TestAccAWSElasticTranscoderPipeline_withPermissions
--- PASS: TestAccAWSElasticTranscoderPipeline_withPermissions (20.17s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws …
```

provider/aws: More test fixing 

---

website/source/docs/providers/aws/d/instance.html.markdown

Minor grammar fixes to AWS Instance data source.

Minor grammar fixes to AWS Instance data source

---

website/source/docs/providers/aws/d/autoscaling_groups.html.markdown

Some minor fixes to make this data source's function clearer.

Minor fixes to AWS ASG data source docs

---

builtin/providers/rancher/config.go
builtin/providers/rancher/provider.go
builtin/providers/rancher/resource_rancher_environment.go
builtin/providers/rancher/resource_rancher_environment_test.go
builtin/providers/rancher/resource_rancher_registration_token.go
builtin/providers/rancher/resource_rancher_registration_token_test.go
builtin/providers/rancher/resource_rancher_registry.go
builtin/providers/rancher/resource_rancher_registry_credential.go
builtin/providers/rancher/resource_rancher_registry_credential_test.go
builtin/providers/rancher/resource_rancher_registry_test.go
builtin/providers/rancher/resource_rancher_stack.go
builtin/providers/rancher/resource_rancher_stack_test.go
builtin/providers/rancher/util.go
builtin/providers/rancher/util_test.go
website/source/docs/providers/rancher/r/registration_token.html.markdown
website/source/docs/providers/rancher/r/registry.html.markdown
website/source/docs/providers/rancher/r/registry_credential.html.markdown
website/source/docs/providers/rancher/r/stack.html.markdown

/cc @raphink @mcanevet 
This is the follow-up to https://github.com/hashicorp/terraform/pull/11594 to allow for specify additional metadata about Rancher resources on import.

[Rancher] - allow for importing resources using environment ID to target

---

website/source/layouts/docs.erb

Ignition wasn't in A-Z order, fixed identation, removed duplicated NoMad provider:

Docs: Remove duplicate NoMad provider, fix sorting

---

backend/local/backend_local.go

Fixes #11628
This is a simple fix to output warnings. I originally forgot to do this
since the local backend didn't have a CLI UI at the time. It does now so
this is an easy fix.

backend/local: output warnings

---

builtin/providers/aws/resource_aws_ssm_association_test.go
builtin/providers/aws/resource_aws_ssm_document.go
builtin/providers/aws/resource_aws_ssm_document_test.go
website/source/docs/providers/aws/r/ssm_document.html.markdown

A parameter `document_type` and a few more attributes returned based
upon the new API.

Latest updates to aws_ssm_document resource.

---

builtin/providers/aws/provider.go

This is first part - intended to be cherry-picked to `0-8-stable` as it's just introducing deprecation.
The second part - which will remove deprecated fields will come in a separate PR - and it will only stay in `master`.
Related: https://github.com/hashicorp/terraform/issues/6535

provider/aws: Unify custom endpoint fields in provider schema

---

builtin/providers/aws/resource_aws_ecs_task_definition_test.go

When ran in parallel the tests `TestAccAwsEcsTaskDefinition_withNetwork` and `TestAccAwsEcsTaskDefinition_withTask` will overlap with each other due to the shared naming of the `iam_role` resource.
This fixes these tests to allow running in parallel on TeamCity.
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAwsEcsTaskDefinition_withTask'
2017/02/09 09:20:03 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAwsEcsTaskDefinition_withTask -timeout 120m
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    0.022s
```
```
$ make testacc TEST=./builtin/providers/aws …
```

provider/aws: Fix ECS Task Definition tests

---

builtin/providers/aws/resource_aws_load_balancer_policy_test.go

Updates the aws_elb acceptance tests to better handle parallel test runs
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLoadBalancerPolicy_'
2017/02/09 10:04:58 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSLoadBalancerPolicy_ -timeout 120m
=== RUN   TestAccAWSLoadBalancerPolicy_basic
--- PASS: TestAccAWSLoadBalancerPolicy_basic (24.50s)
=== RUN   TestAccAWSLoadBalancerPolicy_updateWhileAssigned
--- PASS: TestAccAWSLoadBalancerPolicy_updateWhileAssigned (42.34s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    66.866s
```

provider/aws: Update aws_elb policy acctests

---

builtin/providers/aws/resource_aws_redshift_cluster_test.go

Allows failing redshift_cluster acceptance tests to pass when ran in parallel
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSRedshiftCluster_'
2017/02/09 11:15:49 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSRedshiftCluster_ -timeout 120m
=== RUN   TestAccAWSRedshiftCluster_importBasic
--- PASS: TestAccAWSRedshiftCluster_importBasic (593.87s)
=== RUN   TestAccAWSRedshiftCluster_basic
--- PASS: TestAccAWSRedshiftCluster_basic (663.11s)
=== RUN   TestAccAWSRedshiftCluster_kmsKey
--- PASS: TestAccAWSRedshiftCluster_kmsKey (684.31s)
=== RUN   TestAccAWSRedshiftCluster_enhancedVpcRoutingEnabled
--- …
```

provider/aws: Update redshift_cluster acceptance tests

---

vendor/github.com/aws/aws-sdk-go/CHANGELOG.md
vendor/github.com/aws/aws-sdk-go/CONTRIBUTING.md
vendor/github.com/aws/aws-sdk-go/aws/client/client.go
vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
vendor/github.com/aws/aws-sdk-go/aws/session/session.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
vendor/vendor.json

This allows to use the latest `AssociateIamInstanceProfile`, to add AWS role to existing instances! 🍾 
AWS SDK 1.6.20: https://github.com/aws/aws-sdk-go/pull/1078
Command: `govendor fetch github.com/aws/aws-sdk-go/...@=v1.6.20`

Bumped AWS SDK to 1.6.20

---

website/source/docs/providers/aws/r/lambda_permission.html.markdown

provider/aws: Update aws_lambda_permission documentation

---

vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
vendor/vendor.json

Updates go-cleanhttp vendored dependency
cc: @jefferai

core: Update go-cleanhttp vendored dependency

---

builtin/providers/consul/resource_consul_catalog_entry.go

provider/consul: catalog entry service id should default to service name

provider/consul: catalog entry service id should default to service name

---

CHANGELOG.md
website/source/docs/commands/force-unlock.html.markdown
website/source/docs/commands/index.html.markdown
website/source/docs/state/remote/s3.html.md
website/source/intro/getting-started/install.html.markdown
website/source/layouts/docs.erb

Also updates some stale command output.

Add force-unlock command to the docs

---

website/source/assets/stylesheets/_docs.scss
website/source/assets/stylesheets/_global.scss
website/source/assets/stylesheets/_header.scss
website/source/assets/stylesheets/_variables.scss

Hot fixes for a FOUC (flash of unstyled content) and the stack issues related to yesterday's typography update. 
cc/ @captainill

Website type update fixes

---

website/source/docs/import/importability.html.md

Is this a typo?
That worked fine!

Modification of document.

---

builtin/providers/openstack/resource_openstack_blockstorage_volume_v1.go
builtin/providers/openstack/resource_openstack_blockstorage_volume_v1_test.go
vendor/github.com/gophercloud/gophercloud/STYLEGUIDE.md
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/volumes/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
vendor/github.com/gophercloud/gophercloud/util.go
vendor/vendor.json

provider/openstack BlockStorage v1 availability_zone Fix

---

builtin/providers/rancher/provider.go

This doesn't really work yet, because the URL is required in the provider parameters. I see several options, not sure which one is the best:
* make the URL optional, fail in providerConfigure if it's not set
* use our own method instead of `schema.EnvDefaultFunc` to return default values, but then that means we can't provide `config` as a parameter as it needs to be known beforehand.
@stack72 @johnrengelman any idea?

rancher: parse Rancher client cli.json config file

---

website/source/docs/providers/aws/r/autoscaling_group.html.markdown

provider/aws: Add default_cooldown to the autoscaling_group docs

---

vendor/github.com/aws/aws-sdk-go/CHANGELOG.md
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
vendor/vendor.json

Adds support for EBS Elastic Volumes

provider/aws: Bump SDK version to 1.6.22

---

builtin/providers/azurerm/resource_arm_container_service.go

schema.Set contains a sync structure which can't be copied.

Fix copied schema.Set values

---

builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go

This was pointed out at the HUG in London tonight that we save the plain
text password in state
I don't think this will be ported back to 0-8-stable

provider/azurerm: Mark the azurerm_scale_set machine password as sensitive

---

builtin/providers/aws/data_source_aws_security_group_test.go

Fixes the `data_source_aws_security_group` acceptance tests
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccDataSourceAwsSecurityGroup'
2017/02/15 22:19:51 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccDataSourceAwsSecurityGroup -timeout 120m
=== RUN   TestAccDataSourceAwsSecurityGroup
--- PASS: TestAccDataSourceAwsSecurityGroup (45.67s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    45.676s
```

provider/aws: Fix sg data source acctests

---

website/source/docs/providers/aws/r/s3_bucket.html.markdown

I guess that needs to be true for everything to make sense.

Fix typo in s3_bucket resource

---

Vagrantfile

Same as #12022, but for Vagrantfile 🎉

build: Bump Vagrant to go1.8

---

builtin/providers/fastly/resource_fastly_service_v1.go
builtin/providers/fastly/resource_fastly_service_v1_response_object_test.go
website/source/docs/providers/fastly/r/service_v1.html.markdown

Allows the user to set up response objects for fastly
[Fastly API](https://docs.fastly.com/api/config#response_object)

provider/fastly Adds fastly response object

---

vendor/github.com/hashicorp/go-plugin/client.go
vendor/github.com/hashicorp/go-plugin/rpc_server.go
vendor/vendor.json

This fixes some hanging issues seen by TF users, see the relevant
commits in go-plugin.

vendor: update go-plugin

---

Makefile

Fixes #12064 
A hammer solution but I don't think parallelism gives any gain to Terraform at all.

Disallow parallelism in Makefile

---

website/source/docs/providers/azurerm/r/container_service.html.markdown

Noticed a duplicated description in the Container Service documentation - updated to match the Azure docs

provider/azurerm: Updating the Container Service Documentation

---

builtin/providers/aws/resource_aws_redshift_cluster.go
website/source/docs/providers/aws/r/redshift_cluster.html.markdown

See OwnerAccount in http://docs.aws.amazon.com/redshift/latest/APIReference/API_RestoreFromClusterSnapshot.html
I'm very new to terraform's code base, so it's unclear to me whether an acceptance test is needed and how to approach adding one (or updating an existing test).

Add owner_account option to aws_redshift_cluster

---

builtin/providers/google/resource_compute_instance.go

This should fix the `TestAccComputeInstance_diskEncryption` test that's been failing.

provider/google: Write the raw disk encryption key in the state file to avoid diffs on plan

---

dag/walk_test.go

There were some race and bookkeeping issues in a few dag tests causing them to fail on loaded systems.
This updates the tests to run complete the graph in a deterministic order, removing the need for the for-loops to try and induce failure.

Fix some intermittent dag test failures

---

builtin/providers/aws/resource_aws_db_instance_test.go
builtin/providers/aws/resource_aws_rds_cluster_test.go

provider/aws: Refactor snapshot tests to always delete the snapshot first

---

builtin/providers/azurerm/provider.go
builtin/providers/azurerm/resource_arm_loadbalancer.go
builtin/providers/azurerm/resource_arm_loadbalancer_nat_pool.go
builtin/providers/azurerm/resource_arm_loadbalancer_nat_rule.go
builtin/providers/azurerm/resource_arm_loadbalancer_probe.go
builtin/providers/azurerm/resource_arm_loadbalancer_rule.go
builtin/providers/azurerm/resource_arm_network_interface_card.go
builtin/providers/azurerm/resource_arm_public_ip.go

Fixes https://github.com/hashicorp/terraform/issues/12175

Ignore case on protocol and allocation types

---

website/source/docs/providers/azurerm/r/network_interface.html.markdown

Minor fix for doc issue #12184

update azure_network_interface documentation to say required for ip_configuration

---

website/source/docs/providers/aws/r/emr_cluster.html.md

List of applications was broken. Also added Apache Flink as valid application.

Fix emr_cluster docs

---

command/env_command.go
command/env_delete.go
command/env_new.go
command/env_select.go

Really minor whitespace changes here, will merge when/if tests are green.

command: color changes, trimming newlines

---

builtin/providers/aws/data_source_aws_s3_bucket_object.go

Before:
* data.aws_s3_bucket_object.redshift_reader: Failed getting S3 object: NotFound: Not Found
status code: 404, request id: B7B4BBDFBB9EE1FA
After:
* data.aws_s3_bucket_object.redshift_reader: Failed getting S3 object: NotFound: Not Found
status code: 404, request id: B7B4BBDFBB9EE1FA "s3://mybucket/lambda.zip"

provider/aws: more details on which s3 bucket had an error

---

builtin/providers/profitbricks/resource_profitbricks_firewall_test.go
builtin/providers/profitbricks/resource_profitbricks_loadbalancer_test.go
builtin/providers/profitbricks/resource_profitbricks_nic_test.go
builtin/providers/profitbricks/resource_profitbricks_server_test.go
builtin/providers/profitbricks/resource_profitbricks_volume_test.go

@stack72 I'm just changing password on acceptance tests.

Acceptance tests volume password change

---

command/meta_backend.go
command/meta_backend_test.go
command/test-fixtures/backend-new-interp/main.tf

The validation itself was added a couple weeks ago but I forgot to
actually call it. 😢

command: validate backend config

---

terraform/context.go

Make the UI output consistent
fixes #10434

Sort Validation warning and errors

---

main.tf
vendor/github.com/aws/aws-sdk-go/CHANGELOG.md
vendor/github.com/aws/aws-sdk-go/README.md
vendor/github.com/aws/aws-sdk-go/aws/config.go
vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
vendor/github.com/aws/aws-sdk-go/aws/session/session.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
vendor/github.com/aws/aws-sdk-go/service/elasticbeanstalk/api.go
vendor/github.com/aws/aws-sdk-go/service/elasticbeanstalk/errors.go
vendor/github.com/aws/aws-sdk-go/service/elasticsearchservice/api.go
vendor/github.com/aws/aws-sdk-go/service/iam/api.go
vendor/github.com/aws/aws-sdk-go/service/route53/api.go
vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
vendor/github.com/aws/aws-sdk-go/service/waf/api.go
vendor/vendor.json

**MERGE AFTER 0.8.8 RELEASE**
This allows the creation of Organisations

provider/aws: Bump AWS SDK to 1.7.3

---

website/source/docs/providers/azurerm/r/virtual_network.html.markdown

These attributes are exposed but missing in the docs.

[azurerm/doc] - Adds exposed attributes to the docs. 

---

website/source/docs/providers/aws/d/ip_ranges.html.markdown

http://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html#aws-ip-download
> Valid values: AMAZON | EC2 | CLOUDFRONT | ROUTE53 | ROUTE53_HEALTHCHECKS | S3

Updated list of available services

---

builtin/providers/google/resource_storage_bucket.go

Our GCP storage tests are really flaky right now due to rate limiting.
In theory, this could also impact Terraform users that are
deleting/creating large numbers of Google Cloud Storage buckets at once.
To fix, I'm detecting the specific error code that GCP returns when it's
a rate limit error, and using that with resource.Retry to try the
request again.

provider/google: retry storage creation/deletion on rate limiting

---

builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go

In the event that an unexpected state is returned from
`environmentStateRefreshFunc`, errors in the Elastic Beanstalk console
will now be returned to the user.
As an example the error returned for an issue like #10667 is now
```
Error applying plan:
1 error(s) occurred:
* aws_elastic_beanstalk_environment.test-eb-staging: 1 error(s) occurred:
* aws_elastic_beanstalk_environment.test-eb-staging: Error waiting for Elastic Beanstalk Environment (e-bhn3m2qfrb) to become ready: 2 error(s) occurred:
* 2017-03-03 18:24:50.158 +0000 UTC (e-bhn3m2qfrb) : Environment must have instance profile associated with it.
* 2017-03-03 18:24:50.256 +0000 UTC (e-bhn3m2qfrb) : Failed to launch environment.
```
`template_change` test fails due to not having solution stack in my account. Otherwise everything …

provider/aws: Return errors from Elastic Beanstalk

---

builtin/providers/cobbler/resource_cobbler_profile.go
builtin/providers/cobbler/resource_cobbler_profile_test.go
builtin/providers/cobbler/resource_cobbler_system_test.go
vendor/github.com/jtopjian/cobblerclient/profile.go
vendor/github.com/jtopjian/cobblerclient/system.go
vendor/vendor.json

This PR includes two fixes:
* Profile repos
* System interface management parameter
For #12300

provider/cobbler: Profile and System Fixes

---

builtin/providers/aws/resource_aws_iam_instance_profile.go

provider/aws: Populate the iam_instance_profile uniqueId

---

builtin/providers/aws/resource_aws_lb_ssl_negotiation_policy.go
builtin/providers/aws/resource_aws_lb_ssl_negotiation_policy_test.go

aws/provider: Fixes issue for aws_lb_ssl_negotiation_policy of already deleted ELB

---

builtin/providers/google/container_operation.go
builtin/providers/google/provider.go
builtin/providers/google/resource_container_cluster.go
builtin/providers/google/resource_container_node_pool.go
builtin/providers/google/resource_container_node_pool_test.go

Purposely kept to just required fields for now to keep the PR small.
Will enable further development in this resource, such as is necessary for #8605.

provider/google: initial commit for node pool resource

---

website/source/docs/providers/aws/r/iam_role.html.markdown

missing but a valid exported attribute

add "name" to exported attributes

---

builtin/providers/aws/resource_aws_volume_attachment.go

Currently, given the following manifest snippet:
```
resource "aws_spot_instance_request" "spot" {
...
ebs_block_device {
encrypted = true
...
}
}
```
According to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html the Amazon API does not honour the encryption setting on additional volumes. This could be worked around with something like:
```
resource "aws_spot_instance_request" "spot" {
wait_for_fulfillment = true
...
}
resource "aws_ebs_volume" "volume" {
encrypted = true
...
}
resource "aws_volume_attachment" "attach" {
volume_id   = "${aws_ebs_volume.volume.id}"
instance_id = "${aws_spot_instance_request.spot.spot_instance_id}"
...
}
```
However waiting for the spot request to be fulfilled does not guarantee that the instance is running; quite often it's pending …

Check spot instance is running before trying to attach volumes

---

builtin/providers/aws/resource_aws_instance.go
command/internal_plugin_list.go

`go fmt` is throwing an error and `make dev` is failing, so let's patch that up

Fix up command and some go fmt issues

---

builtin/providers/aws/data_source_aws_vpc_test.go
builtin/providers/aws/resource_aws_autoscaling_group_test.go

Most of these fixes are for running the tests in parallel. I'm going to merge right away as they only touch the test files

more aws acc test fixes

---

vendor/github.com/aws/aws-sdk-go/CHANGELOG.md
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go
vendor/vendor.json

Required for ACM and API Gateway integration

provider/aws: Bump SDK to 1.7.7

---

README.md

Use HTTPS in terraform website url.

README: update terraform website url with https

---

command/hook_ui.go
command/hook_ui_test.go

Here's a few tests to make sure we don't reintroduce bugs like these:
- https://github.com/hashicorp/terraform/pull/12370
- https://github.com/hashicorp/terraform/pull/12381

command: Add tests for UiHook

---

builtin/providers/openstack/resource_openstack_lb_member_v2.go

If LBaaSV2 member creation/deletion is attempted while LB resource is
busy (for example it's in PENDING_UPDATE state), Neutron will return 500
error. Currently This being caught by type assertion to
ErrUnexpectedResponseCode, however error 500 has a dedicated type
ErrDefault500, which makes the current type assertion to miss it and
eventually the error slips out through the check. This patch
changes the type assertion to explicitly check for ErrDefault500.
Also similar check has been added when member is deleted.

Check for ErrDefault500 when creating/deleting pool member

---

vendor/github.com/aws/aws-sdk-go/CHANGELOG.md
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
vendor/github.com/aws/aws-sdk-go/aws/session/session.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/api.go
vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/errors.go
vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/service.go
vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go
vendor/github.com/aws/aws-sdk-go/service/emr/api.go
vendor/github.com/aws/aws-sdk-go/service/emr/waiters.go
vendor/github.com/aws/aws-sdk-go/service/rds/customizations.go
vendor/vendor.json

Specifically fixes https://github.com/hashicorp/terraform/issues/11797 . I'm running the `TestAccAWSDBInstanceReplica` test to confirm, as well as ECS tests as ECS seemed to have some additions.

provider/aws: Bump aws/sdk to 1.7.9. Fixes at least 1 RDS bug

---

backend/remote-state/consul/backend_test.go
backend/remote-state/consul/client_test.go

just making sure to cover the gzip codepath in tests

add gzip to consul backend tests

---

builtin/providers/google/provider.go
builtin/providers/google/resource_container_cluster_test.go

@paddyforan, I'd love your thoughts on this approach. One the one hand, yay checking more stuff! On the other hand, it's a long function that itself could be buggy, and requires that people actually keep it up-to-date.

provider/google: Check all fields in GKE tests instead of just that the resource exists

---

builtin/providers/circonus/resource_circonus_contact.go
builtin/providers/circonus/resource_circonus_contact_test.go
website/source/docs/providers/circonus/r/contact_group.html.markdown

* Spell `webhook_url` like `webhook_url` and not like `webook_url`.
* Expect `pagerduty` not `pager_duty` from the API.

Fix PagerDuty support for `circonus_contact_group`.

---

website/source/index.html.erb

website: Replace 0.8 release w/ 0.9 on the HP

---

builtin/providers/aws/resource_aws_ami.go

Fixes the two failing aws_ami acceptance tests, by polling until the AMI is deleted before exiting.
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAMI_basic'
2017/03/14 16:03:26 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAMI_basic -timeout 120m
=== RUN   TestAccAWSAMI_basic
--- PASS: TestAccAWSAMI_basic (43.98s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    43.989s
```
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAMI_snapshotSize'
go generate $(go list ./... | grep -v …
```

Add waitForDestroy for aws ami resource

---

builtin/providers/scaleway/resource_scaleway_server.go

Exposing public IPv6 for scaleway provider based on #9217

Added schema to expose public IPv6

---

builtin/providers/profitbricks/resource_profitbricks_server.go

As requested by @stack72  I patched up volume resource on ProfitBricks provider
```
$ make testacc TEST=./builtin/providers/profitbricks/ TESTARGS='-run=TestAccProfitBricksVolume_Basic'
2017/03/17 18:52:38 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/profitbricks/ -v -run=TestAccProfitBricksVolume_Basic -timeout 120m
=== RUN   TestAccProfitBricksVolume_Basic
--- FAIL: TestAccProfitBricksVolume_Basic (240.05s)
testing.go:268: Step 1 error: Check failed: Check 1/2 error: Bad name: webserver
FAIL
exit status 1
FAIL    github.com/hashicorp/terraform/builtin/providers/profitbricks   240.069s
make: *** [testacc] Error 1
```

panic_prevention

---

builtin/providers/mysql/resource_grant.go
builtin/providers/mysql/resource_user.go

MySQL Provider does not recreate user/grant if user/grant got deleted manually

---

website/source/docs/providers/google/r/compute_disk.html.markdown

Hi
this version was not found anymore.
Thanks.

[DOCUMENTATION] Change version of Debian image

---

builtin/providers/aws/resource_aws_autoscaling_attachment_test.go
config/interpolate_funcs_test.go
terraform/state.go
website/source/docs/providers/external/data_source.html.md

Just fixes some misspellings of receive.

Fix receive typo

---

helper/acctest/random.go

Many cloud services prevent duplicate key pairs with different names. Among them are Digital Ocean, Joyent Triton and Packet. Consequently, if tests leave dangling resources it is not enough to simply randomise the name, the entire key material must be regenerated.
This commit adds a helper method that returns a new randomly generated key pair, where the public key material is formatted in OpenSSH "authorized keys" format, and the private key material is PEM encoded.
cc @stack72

helper/acctest: Add NewSSHKeyPair function

---

builtin/providers/aws/resource_aws_vpc.go

Fixes: #12895
The AWS API returns both dissociated and associated IPv6 CIDRs. The UI
only returns the associated. Therefore, the assumption was made that we
would always take the 1st association in the set to use for state
We now loop over the set and look for the associated IPv6 CIDR before
using that in state
```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSVpc_'
2017/03/20 21:21:02 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSVpc_ -timeout 120m
=== RUN   TestAccAWSVpc_importBasic
--- PASS: TestAccAWSVpc_importBasic (65.91s)
=== RUN   TestAccAWSVpc_basic
--- PASS: TestAccAWSVpc_basic (50.88s) …
```

provider/aws: Set aws_vpc ipv6 for associated only

---

builtin/providers/ignition/resource_ignition_config_test.go
builtin/providers/ignition/resource_ignition_filesystem.go
builtin/providers/ignition/resource_ignition_filesystem_test.go
website/source/docs/providers/ignition/d/filesystem.html.md

provider/ignition: ignition_filesystem, explicit option to create the filesystem

---

builtin/providers/azurerm/resource_arm_template_deployment_test.go

Currently the `TestAccAzureRMTemplateDeployment_disappears` test fails often because of issues deleting the Deployment - this PR switches to using a simpler ARM Template for cleanup, to allow it to succeed. Given Terraform is only managing the Template Deployment, and not the resources within the Template - the contents of the ARM Template shouldn't matter, providing it's valid.
Previously the `TestAccAzureRMTemplateDeployment_disappears` test was failing fairly often for me, but after repeated runs I'm not seeing that behaviour anymore:
```
$ TF_ACC=1 envchain azurerm go test ./builtin/providers/azurerm/ -v -run=TestAccAzureRMTemplateDeployment_disappears -timeout 120m
=== RUN   TestAccAzureRMTemplateDeployment_disappears
--- PASS: TestAccAzureRMTemplateDeployment_disappears (274.66s) …
```

provider/azurerm: Fixing the Template Deployment Deletion test

---

builtin/providers/openstack/resource_openstack_lb_pool_v1.go
builtin/providers/openstack/resource_openstack_lb_pool_v1_test.go

provider/openstack: Fix monitor_id typo in LBaaS v1 Pool

---

builtin/providers/profitbricks/config.go
builtin/providers/profitbricks/provider.go
builtin/providers/profitbricks/resource_profitbricks_datacenter.go
builtin/providers/profitbricks/resource_profitbricks_datacenter_test.go
builtin/providers/profitbricks/resource_profitbricks_firewall.go
builtin/providers/profitbricks/resource_profitbricks_ipblock.go
builtin/providers/profitbricks/resource_profitbricks_lan.go
builtin/providers/profitbricks/resource_profitbricks_loadbalancer.go
builtin/providers/profitbricks/resource_profitbricks_nic.go
builtin/providers/profitbricks/resource_profitbricks_server.go
builtin/providers/profitbricks/resource_profitbricks_volume.go

Implemented handling of status code 404

Handling missing resources

---

builtin/providers/openstack/resource_openstack_lb_pool_v2.go

This commit accounts for a 409 or 500 response when a LBaaS v2 pool is
being created. Rather than error out, this should be considered a
pending state.
Just hit this by random chance. The acceptance test would fail once every 10 times or so. Pretty much the exact same as #10875.

provider/openstack: 409/500 Response on Pool Create

---

website/source/docs/state/environments.html.md

List backends supporting environments.
Note character restrictions for environment names.

environment docs

---

website/source/docs/state/sensitive-data.html.md
website/source/layouts/docs.erb

To be linked from https://github.com/hashicorp/terraform/pull/12960 and few other pages in the docs.

docs/state: Sensitive data in state file

---

website/source/docs/providers/aws/r/api_gateway_domain_name.html.markdown
website/source/docs/providers/aws/r/db_instance.html.markdown
website/source/docs/providers/aws/r/directory_service_directory.html.markdown
website/source/docs/providers/aws/r/dms_certificate.html.markdown
website/source/docs/providers/aws/r/dms_endpoint.html.markdown
website/source/docs/providers/aws/r/iam_server_certificate.html.markdown
website/source/docs/providers/aws/r/opsworks_mysql_layer.html.markdown
website/source/docs/providers/aws/r/opsworks_rds_db_instance.html.markdown
website/source/docs/providers/aws/r/rds_cluster.html.markdown
website/source/docs/providers/aws/r/redshift_cluster.html.markdown
website/source/docs/providers/azurerm/r/container_registry.html.markdown
website/source/docs/providers/azurerm/r/container_service.html.markdown
website/source/docs/providers/azurerm/r/sql_server.html.markdown
website/source/docs/providers/azurerm/r/virtual_machine_scale_sets.html.markdown
website/source/docs/providers/google/r/compute_disk.html.markdown
website/source/docs/providers/google/r/container_cluster.html.markdown
website/source/docs/providers/google/r/sql_user.html.markdown
website/source/docs/providers/mysql/r/user.html.markdown
website/source/docs/providers/postgresql/r/postgresql_role.html.markdown
website/source/docs/providers/rabbitmq/r/user.html.markdown

In the spirit of transparency and to avoid any misunderstandings.
I will send a separate PR to add `Sensitive: true` to fields which are still missing it (and are involved in this PR).

Add links to details about sensitive data in state

---

builtin/providers/google/resource_container_cluster.go

Related to https://github.com/hashicorp/terraform/pull/13132 and https://github.com/hashicorp/terraform/pull/13145

provider/google: Mark GKE pass as sensitive

---

website/source/community.html.erb

Missed I hadn't done this - thanks for the reminder @stack72

Adding @tombuildsstuff to the community page

---

builtin/providers/oracleopc/config.go
builtin/providers/oracleopc/provider.go
builtin/providers/oracleopc/provider_test.go
builtin/providers/oracleopc/resource_instance.go
builtin/providers/oracleopc/resource_instance_test.go
builtin/providers/oracleopc/resource_ip_association.go
builtin/providers/oracleopc/resource_ip_association_test.go
builtin/providers/oracleopc/resource_ip_reservation.go
builtin/providers/oracleopc/resource_security_application.go
builtin/providers/oracleopc/resource_security_association.go
builtin/providers/oracleopc/resource_security_association_test.go
builtin/providers/oracleopc/resource_security_ip_list.go
builtin/providers/oracleopc/resource_security_list.go
builtin/providers/oracleopc/resource_security_rule.go
builtin/providers/oracleopc/resource_security_rule_test.go
builtin/providers/oracleopc/resource_ssh_key.go
builtin/providers/oracleopc/resource_storage_volume.go
builtin/providers/oracleopc/resource_storage_volume_test.go
website/source/docs/providers/oracleopc/r/opc_compute_instance.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_ip_association.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_ip_reservation.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_security_application.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_security_association.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_security_ip_list.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_security_list.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_security_rule.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_ssh_key.html.markdown
website/source/docs/providers/oracleopc/r/opc_compute_storage_volume.html.markdown

This is initial code submission for the Oracle Compute Cloud provider based on https://github.com/oracle/terraform-provider-compute

Provider opc

---

website/source/assets/stylesheets/_community.scss
website/source/community.html.erb

Also, as a separate commit, a quick tweak to the CSS for this page to fix an inconsistency of the layout that was bothering me. :grinning:

Add myself to the community page

---

builtin/providers/aws/data_source_aws_route53_zone.go

Simple misspelling in error message

provider/aws: fix error message in route53 data source

---

website/source/docs/providers/aws/r/alb.html.markdown

provi:er/aws: Documentation changes on ALB to remove ELB refs

---

website/source/docs/providers/aws/r/api_gateway_method.html.markdown

provider/aws: Document the AWS_IAM authorizer type for api_gateway_method

---

website/source/docs/providers/aws/r/kinesis_firehose_delivery_stream.html.markdown

provider/aws: change kinesis_firehose_delivery_stream to point to correct destination

---

command/meta_backend.go
command/meta_backend_test.go

Don't erase local state during backend migration if the new and old
paths are the same. Skipping the confirmation and copy are handled in
another patch, but the local state was always erased by default, even
when it was our new state.
fixes #13240

don't delete local state on a local backend

---

builtin/providers/aws/data_source_aws_subnet_ids.go
builtin/providers/aws/data_source_aws_subnet_ids_test.go
builtin/providers/aws/provider.go
website/source/docs/providers/aws/d/subnet_ids.html.markdown
website/source/layouts/aws.erb

provider/aws Add support for aws_subnet_ids as a data source

---

vendor/github.com/mitchellh/mapstructure/decode_hooks.go
vendor/github.com/mitchellh/mapstructure/mapstructure.go
vendor/vendor.json

Updating mapstructure vendor for opc provider

---

command/hook_ui.go
command/hook_ui_test.go

Fixes https://github.com/hashicorp/terraform/issues/13292

command/hook_ui: Increase max length of state IDs

---

builtin/providers/openstack/resource_openstack_compute_volume_attach_v2.go

https://github.com/hashicorp/terraform/issues/13334

Do not error if compute volume attachment is missing

---

website/source/docs/providers/terraform/d/remote_state.html.md

The existence of the attribute is mentioned here already: https://www.terraform.io/docs/state/environments.html

Document the `environment` attribute on `terraform_remote_state`

---

builtin/providers/opc/config.go
builtin/providers/opc/provider.go
builtin/providers/opc/resource_instance_test.go
vendor/github.com/hashicorp/go-oracle-terraform/compute/client.go
vendor/github.com/hashicorp/go-oracle-terraform/compute/logging.go
vendor/github.com/hashicorp/go-oracle-terraform/compute/storage_volumes.go
vendor/vendor.json

Adds debug logging, fixes a failing instance acceptance test, and updates vendored dep

provider/opc: Add debug logging

---

backend/remote-state/consul/client.go
backend/remote-state/consul/client_test.go

This matches the consul cli behavior, where locks are cleaned up after
use.
Return an error from re-locking the state. This isn't required by the
Locker interface, but it's an added sanity check for state operations.
What was incorrect here was returning an empty ID and error, which would
indicate that Lock/Unlock isn't supported.

cleanup consul lock entries

---

website/source/docs/providers/aws/index.html.markdown

provider/aws: Remove deprecated endpoints from Provider introduction

---

website/source/docs/configuration/data-sources.html.md

Hi
I just added a link to "Multiple Provider Instances" on ressources's page.
Thanks.

Add a link to "Multiple Provider Instances"

---

builtin/providers/fastly/resource_fastly_service_v1.go
builtin/providers/fastly/resource_fastly_service_v1_sumologic_test.go
builtin/providers/fastly/validators.go
builtin/providers/fastly/validators_test.go
vendor/github.com/sethvargo/go-fastly/request.go
vendor/github.com/sethvargo/go-fastly/sumologic.go
vendor/github.com/sethvargo/go-fastly/syslog.go
vendor/vendor.json
website/source/docs/providers/fastly/r/service_v1.html.markdown

This PR adds support for sumologic logging to Fastly's provider.

provider/fastly: Sumologic

---

builtin/providers/aws/resource_aws_ecs_service_test.go

Fixes TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression
```
make testacc TEST=./builtin/providers/aws/ TESTARGS='-run=TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression'
2017/04/10 10:10:57 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws/ -v -run=TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression -timeout 120m
=== RUN   TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression
--- PASS: TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression (107.01s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	107.046s
```

TestAccAWSEcsServiceWithPlacementConstraints_emptyExpression

---

builtin/providers/aws/resource_aws_appautoscaling_target.go
builtin/providers/aws/resource_aws_appautoscaling_target_test.go
builtin/providers/aws/validators.go
website/source/docs/providers/aws/r/appautoscaling_target.html.markdown

provider/aws: Add support for EMR clusters to aws_appautoscaling_target

---

builtin/providers/scaleway/data_source_scaleway_bootscript.go
builtin/providers/scaleway/data_source_scaleway_image.go
builtin/providers/scaleway/resource_scaleway_ip.go
builtin/providers/scaleway/resource_scaleway_security_group.go
builtin/providers/scaleway/resource_scaleway_security_group_rule.go
builtin/providers/scaleway/resource_scaleway_server.go
builtin/providers/scaleway/resource_scaleway_volume.go
builtin/providers/scaleway/resource_scaleway_volume_attachment.go

improve readability by removing unnecessary schema type declarations
this changeset does not include any semantic changes

provider/scaleway: improve schema resources

---

website/source/docs/providers/aws/d/instance.html.markdown
website/source/docs/providers/aws/r/instance.html.markdown

Updates instance documentation.
Fixes: #13514

provider/aws: Update instance documentation

---

website/source/docs/providers/vsphere/r/virtual_machine.html.markdown

provider/vsphere: Add keep_on_remove to docs

---

terraform/graph_builder_apply.go
terraform/graph_builder_apply_test.go
terraform/graph_builder_import.go
terraform/graph_builder_plan.go
terraform/graph_builder_plan_test.go
terraform/graph_builder_refresh.go

@mitchellh can you check and confirm I added them back to all applicable locations? Thx!

core: add the close provider/provisioner transformers back

---

website/source/layouts/enterprise.erb

include bitbucket & gitlab links in TFE docs sidebar.

add bitbucket & gitlab to docs sidebar

---

builtin/providers/google/import_compute_address_test.go
builtin/providers/google/import_compute_global_address_test.go
builtin/providers/google/resource_compute_address.go
builtin/providers/google/resource_compute_global_address.go
website/source/docs/import/importability.html.md

I wanted this at work last week so I figured I'd take a stab at adding it in. :)

Google address importability

---

builtin/providers/openstack/resource_openstack_networking_port_v2.go
builtin/providers/openstack/resource_openstack_networking_port_v2_test.go
builtin/providers/openstack/resource_openstack_networking_secgroup_v2.go

Openstack port update fixes

---

website/source/docs/providers/google/r/google_project.html.markdown

Fix billing_acount into billing_account in google_project.html.markdown

---

website/source/docs/providers/aws/r/api_gateway_usage_plan.html.markdown
website/source/docs/providers/aws/r/api_gateway_usage_plan_key.html.markdown

provider/aws: Documentation fixes for aws_api_gateway_*

---

builtin/providers/alicloud/resource_alicloud_instance.go

Fix creating PrePaid instance error
Use different IoOptimized value for PrePaid instance and PostPaid instance
Fixes: #13661

provider/alicloud: Fix create PrePaid instance (#13661)

---

website/source/docs/providers/aws/r/inspector_resource_group.html.markdown

provider/aws: Documentation fixes for aws_inspector_resource_group

---

website/source/docs/providers/aws/r/ami.html.markdown

provider/aws: Documentation fixes for aws_ami

---

builtin/providers/aws/resource_aws_network_acl_rule.go
builtin/providers/aws/resource_aws_network_acl_rule_test.go

Fixes the first part of https://github.com/hashicorp/terraform/issues/13489.
If a NACL rule can't be found during the Read pass remove it.
Acceptance test:
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSNetworkAclRule_deleteRule'
```

Remove aws_network_acl_rule if not found

---

builtin/providers/newrelic/resource_newrelic_alert_condition.go
builtin/providers/newrelic/resource_newrelic_alert_condition_test.go
vendor/github.com/paultyng/go-newrelic/api/alert_channels.go
vendor/github.com/paultyng/go-newrelic/api/alert_conditions.go
vendor/github.com/paultyng/go-newrelic/api/alert_policy_channels.go
vendor/github.com/paultyng/go-newrelic/api/applications.go
vendor/github.com/paultyng/go-newrelic/api/client.go
vendor/github.com/paultyng/go-newrelic/api/component_metric_data.go
vendor/github.com/paultyng/go-newrelic/api/component_metrics.go
vendor/github.com/paultyng/go-newrelic/api/components.go
vendor/github.com/paultyng/go-newrelic/api/labels.go
vendor/github.com/paultyng/go-newrelic/api/plugins.go
vendor/github.com/paultyng/go-newrelic/api/types.go
vendor/vendor.json
website/source/docs/providers/newrelic/r/alert_condition.html.markdown

Update go-newrelic vendor and use new field

---

website/source/docs/providers/aws/r/elasticsearch_domain.html.markdown

provider/aws: Documentation fixed for elasticsearch_domain

---

contrib/fish-completion/README.md
contrib/fish-completion/terraform.fish

Please note that this has been already merged to fish-shell and should be included in the upcoming release, but it might be still useful in `contrib` for people on older versions:
https://github.com/fish-shell/fish-shell/pull/3960

Shell completions for fish

---

builtin/providers/digitalocean/resource_digitalocean_droplet.go
builtin/providers/digitalocean/resource_digitalocean_droplet_test.go
website/source/docs/providers/do/r/droplet.html.markdown

Note: In DO, Droplets are about the only thing you pay. DNS/Float IP are
free.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

DigitalOcean: Export droplet prices

---

vendor/github.com/Azure/go-autorest/autorest/autorest.go
vendor/github.com/Azure/go-autorest/autorest/azure/async.go
vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
vendor/github.com/Azure/go-autorest/autorest/azure/token.go
vendor/github.com/Azure/go-autorest/autorest/client.go
vendor/github.com/Azure/go-autorest/autorest/error.go
vendor/github.com/Azure/go-autorest/autorest/preparer.go
vendor/github.com/Azure/go-autorest/autorest/responder.go
vendor/github.com/Azure/go-autorest/autorest/sender.go
vendor/github.com/Azure/go-autorest/autorest/version.go
vendor/vendor.json

Bumps autorest dependency for Azure providers.
Fixes: #11131

core: Bump AutoRest Dep

---

builtin/providers/ultradns/common_test.go
builtin/providers/ultradns/provider.go
builtin/providers/ultradns/resource_ultradns_rdpool.go
builtin/providers/ultradns/resource_ultradns_rdpool_test.go
website/source/docs/providers/ultradns/r/rdpool.html.markdown

Add the ultradns_rdpool resource to the builtin provider ultradns.
rebase and try again.

provider/ultradns: add ultradns_rdpool resource

---

website/source/docs/enterprise/vcs/bitbucket.html.md

Bitbucket branding is incorrect in the docs. Currently is BitBucket needs to be Bitbucket. 
context: https://twitter.com/rajsarkar/status/854804309669584897

Change BitBucket to Bitbucket

---

builtin/providers/google/config.go
builtin/providers/google/import_bigquery_dataset_test.go
builtin/providers/google/provider.go
builtin/providers/google/resource_bigquery_dataset.go
builtin/providers/google/resource_bigquery_dataset_test.go
vendor/google.golang.org/api/bigquery/v2/bigquery-api.json
vendor/google.golang.org/api/bigquery/v2/bigquery-gen.go
vendor/vendor.json
website/source/docs/providers/google/r/bigquery_dataset.html.markdown
website/source/layouts/google.erb

This PR adds support for BigQuery datasets.
Heavily inspired by (https://github.com/hashicorp/terraform/pull/3764) https://github.com/22Acacia/terraform-provider-googlebigquery.
Big thanks to @coffeepac :star: for submitting the initial PR. This PR might also lack some of the functionality in the initial PR and I'm quite new to GCP so any feedback is more than welcome 😺

provider/google: BigQuery Dataset

---

website/source/docs/providers/aws/r/s3_bucket.html.markdown

provider/aws: Change s3_bucket documentation example to work

---

builtin/providers/google/resource_compute_address.go
builtin/providers/google/resource_compute_global_address.go

Following up on https://github.com/hashicorp/terraform/pull/13270#discussion_r111216801.

provider/google: Set name field when reading addresses

---

website/source/layouts/_sidebar.erb

Was pointing to Consul before :)

website: Fix mobile link to correct project

---

builtin/providers/aws/resource_aws_s3_bucket.go
builtin/providers/aws/resource_aws_s3_bucket_test.go
website/source/docs/providers/aws/r/s3_bucket.html.markdown

Adds a `bucket_prefix` parameter to the `aws_s3_bucket` resource.

Add `bucket_prefix` to `aws_s3_bucket`

---

vendor/github.com/hashicorp/go-oracle-terraform/compute/instances.go
vendor/vendor.json

This adds error handling to unqualifying nats

Fixes panic from occuring with unqualifying nats

---

builtin/providers/ns1/resource_record_test.go
website/source/docs/providers/ns1/r/record.html.markdown

References:
- https://github.com/hashicorp/terraform/issues/13744
- https://github.com/hashicorp/terraform/issues/12485

provider/ns1: record documentation improvements

---

builtin/providers/google/import_compute_network_test.go
builtin/providers/google/resource_compute_network.go

Adding import for the compute network.

Adding Import to the Google network resource

---

builtin/providers/aws/data_source_aws_db_instance.go
website/source/docs/providers/aws/d/db_instance.html.markdown

provider/aws: Add replica_source_db to the aws_db_instance datasource

---

website/source/docs/providers/oneandone/index.html.markdown
website/source/docs/providers/oneandone/r/firewall_policy.html.markdown
website/source/docs/providers/oneandone/r/loadbalancer.html.markdown
website/source/docs/providers/oneandone/r/monitoring_policy.html.markdown
website/source/docs/providers/oneandone/r/private_network.html.markdown
website/source/docs/providers/oneandone/r/public_ip.html.markdown
website/source/docs/providers/oneandone/r/server.html.markdown
website/source/docs/providers/oneandone/r/shared_storage.html.markdown
website/source/docs/providers/oneandone/r/vpn.html.markdown
website/source/layouts/docs.erb
website/source/layouts/oneandone.erb

Also renaming the files and adding the hcl syntax highlighting

provider/oneandone: Adding the documentation to the sidebar

---

builtin/providers/rabbitmq/acceptance_env/deploy.sh
builtin/providers/rabbitmq/resource_binding_test.go

Pending confirmation of #12782
cc @jbardin

provider/rabbitmq: Add test for binding properties_key

---

builtin/providers/digitalocean/resource_digitalocean_droplet_test.go

Implement much better testing for GH-13720.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

provider/digitalocean: Improve test coverage for droplet pricing

---

website/source/docs/providers/azurerm/r/redis_cache.html.markdown

Whilst reviewing #13884, I noticed the documentation for Azure Redis Cache wasn't so clear - so I've updated it to better match the Azure docs

provider/azurerm: Updating the Redis Documentation

---

builtin/providers/github/resource_github_branch_protection.go

It was a bit aggressive to clear an item from state due to _any_ error. In reality, we should only clear things from state and hide the error if a 404 HTTP status is returned.

provider/github: Clears branch protection from state only if error is an HTTP 404

---

builtin/providers/digitalocean/resource_digitalocean_droplet_test.go

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

provider/digitalocean: Test that droplets are indempotent

---

website/source/docs/import/importability.html.md
website/source/docs/providers/opc/d/opc_compute_network_interface.html.markdown
website/source/docs/providers/opc/d/opc_compute_vnic.html.markdown
website/source/docs/providers/opc/index.html.markdown
website/source/docs/providers/opc/r/opc_compute_acl.html.markdown
website/source/docs/providers/opc/r/opc_compute_image_list.html.markdown
website/source/docs/providers/opc/r/opc_compute_image_list_entry.html.markdown
website/source/docs/providers/opc/r/opc_compute_instance.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_address_association.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_address_prefix_set.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_address_reservation.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_association.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_network.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_network_exchange.html.markdown
website/source/docs/providers/opc/r/opc_compute_ip_reservation.html.markdown
website/source/docs/providers/opc/r/opc_compute_route.html.markdown
website/source/docs/providers/opc/r/opc_compute_sec_rule.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_application.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_association.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_ip_list.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_list.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_protocol.html.markdown
website/source/docs/providers/opc/r/opc_compute_security_rule.html.markdown
website/source/docs/providers/opc/r/opc_compute_ssh_key.html.markdown
website/source/docs/providers/opc/r/opc_compute_storage_volume.html.markdown
website/source/docs/providers/opc/r/opc_compute_storage_volume_snapshot.html.markdown
website/source/docs/providers/opc/r/opc_compute_vnic_set.html.markdown

Updates documentation to add code-block tags, and populate the importability documentation page.

provider/opc: Update documentation

---

website/source/docs/providers/aws/r/cloudformation_stack.html.markdown

provider/aws: Improve documentation for  cloudformation_stack 

---

builtin/providers/ultradns/resource_ultradns_rdpool.go
website/source/docs/providers/ultradns/r/rdpool.html.markdown

Minor improvements.
Thanks for the quick merge for https://github.com/hashicorp/terraform/pull/13745.

provider/ultradns: ultradns_rdpool resource minor improvements

---

website/source/docs/providers/aws/r/alb_listener_rule.html.markdown

docs: Fix parameter name of aws_listener_rule

---

builtin/providers/opc/resource_ip_address_association.go

This modifies the creation of the GetIPAddressAssociation struct to correctly input the name

Refactor IPAddressAssociationRead

---

website/source/layouts/docs.erb

Making the switch from OPC to Oracle Public Cloud for clarity

Update OPC to Oracle Public Cloud

---

website/source/layouts/digitalocean.erb

docs/digitalocean: Add image data source to sidebar

---

builtin/providers/aws/resource_aws_kms_key.go

```
=== RUN   TestAccAWSKmsKey_isEnabled
--- FAIL: TestAccAWSKmsKey_isEnabled (229.51s)
testing.go:280: Step 2 error: Error applying: 1 error(s) occurred:
* aws_kms_key.bar: 1 error(s) occurred:
* aws_kms_key.bar: Failed to set key rotation for "c98e0539-7d2a-4bdf-9380-0a5258a69b44" to true: "DisabledException: arn:aws:kms:us-west-2:*******:key/c98e0539-7d2a-4bdf-9380-0a5258a69b44 is disabled.\n\tstatus code: 400, request id: 6a240630-2b16-11e7-b764-abbc11cb3f70"
FAIL
```
```
=== RUN   TestAccAWSKmsKey_disappears
--- PASS: TestAccAWSKmsKey_disappears (8.09s)
=== RUN   TestAccAWSKmsKey_policy
--- PASS: TestAccAWSKmsKey_policy (24.96s)
=== RUN   TestAccAWSKmsKey_tags
--- PASS: TestAccAWSKmsKey_tags (25.47s)
=== RUN …
```

provider/aws: Retry setting KMS key rotation on DisabledException

---

builtin/providers/nomad/provider.go
website/source/docs/providers/nomad/index.html.markdown

I don't know how to write a test for this functionality.

provider/nomad: Add TLS options

---

builtin/providers/digitalocean/config.go

This is to help us reduce the flakiness of DigitalOcean acceptance tests and find out what exactly is behind these test failures:
```
=== RUN   TestAccDigitalOceanFloatingIP_Droplet
--- FAIL: TestAccDigitalOceanFloatingIP_Droplet (103.27s)
testing.go:337: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* digitalocean_droplet.foobar (destroy): 1 error(s) occurred:
* digitalocean_droplet.foobar: Error waiting for droplet to be unlocked for destroy (44154402): Error retrieving droplet: invalid character '<' looking for beginning of value
=== RUN   TestAccDigitalOceanDroplet_UpdateTags
--- FAIL: TestAccDigitalOceanDroplet_UpdateTags (44.11s)
testing.go:280: Step 0 error: Error applying: 1 …
```

provider/digitalocean: Log HTTP requests & responses in DEBUG+ level

---

builtin/providers/heroku/resource_heroku_space.go

Mostly cribbed from AWS NAT gateway waiting.

providers/heroku: wait for spaces to be allocated

---

builtin/providers/aws/data_source_aws_efs_file_system.go
builtin/providers/aws/data_source_aws_efs_file_system_test.go
builtin/providers/aws/provider.go

heavily based off of resource_aws_efs_file_systems read method.

Added data source for aws_efs_file_system

---

website/source/docs/providers/aws/r/waf_byte_match_set.html.markdown
website/source/docs/providers/aws/r/waf_ipset.html.markdown
website/source/docs/providers/aws/r/waf_rule.html.markdown
website/source/docs/providers/aws/r/waf_size_constraint_set.html.markdown
website/source/docs/providers/aws/r/waf_sql_injection_match_set.html.markdown
website/source/docs/providers/aws/r/waf_web_acl.html.markdown
website/source/docs/providers/aws/r/waf_xss_match_set.html.markdown
website/source/layouts/aws.erb

docs/aws: Add undocumented fields to all WAF resources

---

builtin/providers/google/resource_compute_instance_template.go
builtin/providers/google/resource_compute_instance_template_test.go

provider/google: add support for networkIP in compute instance templates

---

website/source/docs/configuration/data-sources.html.md
website/source/docs/providers/aws/d/subnet_ids.html.markdown

Also fix the bad interpolation in the subnet_ids example.
Closes https://github.com/hashicorp/terraform/issues/14061

Document that data sources support meta parameters such as count

---

builtin/providers/profitbricks/data_source_image_test.go
builtin/providers/profitbricks/resource_profitbricks_server.go
builtin/providers/profitbricks/resource_profitbricks_volume.go
vendor/github.com/profitbricks/profitbricks-sdk-go/nic.go
vendor/github.com/profitbricks/profitbricks-sdk-go/request.go
vendor/vendor.json

This is related to an issue we had from a user https://github.com/profitbricks/terraform-provider-profitbricks/issues/43
I also fixed `data_source_image_test.go`

Private images Fix

---

builtin/providers/google/resource_google_project_services_test.go

This will make the test green again.

provider/google: update list of services in ignoreUnenablableServices test

---

builtin/providers/google/resource_compute_instance.go

Fixes #13897.
The crash was occurring because the user specified a disk source as well as an attribute that is part of `initializeParams`, which is mutually exclusive with `source`. This PR enforces this mutual exclusivity and prevents a crash.

provider/google: fix compute instance panic with bad disk config

---

builtin/providers/google/import_compute_route_test.go
builtin/providers/google/resource_compute_route.go

Chipping away at the resource imports.

Adding import for the compute_route resource

---

CHANGELOG.md
builtin/providers/aws/config.go
builtin/providers/aws/provider.go
website/source/docs/providers/aws/index.html.markdown

* Add option for custom CloudFormation, KMS, RDS, SNS, SQS endpoints
* Minor formatting to arrange internal endpoint variables alphabetically and with consistent naming
* Update CHANGELOG
* Update docs accordingly

provider/aws: add additional custom service endpoint options

---

website/source/assets/stylesheets/_global.scss
website/source/guides/index.html.md
website/source/guides/writing-custom-terraform-providers.html.md
website/source/layouts/guides.erb
website/source/layouts/layout.erb

This adds the guides framework as well as an initial "authoring providers" guide.
/cc @stack72 @grubernaut @catsby @paddycarver @randomcamel @burzinpatel

Add Provider Guide

---

builtin/providers/google/resource_compute_backend_service.go
website/source/docs/providers/google/r/compute_backend_service.html.markdown

provider/google: better visibility for compute_region_backend_service

---

builtin/providers/aws/resource_aws_route_table.go
builtin/providers/aws/resource_aws_route_table_association.go
builtin/providers/aws/tags.go

Closes https://github.com/hashicorp/terraform/issues/13407
cc @vancluever

provider/aws: Increase timeouts for Route Table retries

---

builtin/providers/aws/resource_aws_instance.go
builtin/providers/aws/resource_aws_instance_test.go

Fixes: #14032
When you are using an IPv6 address directly to an instance, it was
causing the ipv6_address_count to try and ForceNew resource. It wasn't
marked as computed
I was able to reproduce this:
```
-/+ aws_instance.test
ami:                          "ami-c5eabbf5" => "ami-c5eabbf5"
associate_public_ip_address:  "false" => "<computed>"
availability_zone:            "us-west-2a" => "<computed>"
ebs_block_device.#:           "0" => "<computed>"
ephemeral_block_device.#:     "0" => "<computed>"
instance_state:               "running" => "<computed>"
instance_type:                "t2.micro" => "t2.micro"
ipv6_address_count:           "1" => "0" (forces new resource)
ipv6_addresses.#:             "1" => "1"
ipv6_addresses.0:             "2600:1f14:bb2:e501::10" => …
```

provider/aws: Adding IPv6 address to instance causes perpetual diff

---

website/source/docs/providers/azurerm/r/virtual_machine.html.markdown

Changed data to os in the storage_os_disk description

Update for storage_os_disk description

---

builtin/providers/aws/resource_aws_eip.go

As mentioned in https://github.com/hashicorp/terraform/issues/13407#issuecomment-300540075 the current timeout seems to be too low.
cc @zzzuzik

provider/aws: Increase EIP update timeout

---

website/source/docs/providers/heroku/r/pipeline_coupling.html.markdown
website/source/layouts/google.erb

Fixing some broken links in the website

Website: fixing broken links

---

builtin/providers/aws/resource_aws_rds_cluster.go
builtin/providers/aws/resource_aws_rds_cluster_instance.go

Should resolve https://github.com/hashicorp/terraform/issues/9328

Using the new time schema helper for RDS Instance lifecycle mgmt

---

website/source/docs/providers/azurerm/r/loadbalancer_probe.html.markdown

Spaces are not allowed in name for `azurerm_lb_probe`

Spaces are not allowed in name

---

website/source/docs/providers/openstack/r/compute_instance_v2.html.markdown

provider/openstack: Add documentation about user_data

---

builtin/providers/azurerm/import_arm_virtual_machine_scale_set_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_test.go
website/source/docs/providers/azurerm/r/virtual_machine_scale_sets.html.markdown

* Adds support for VMSS with managed disks
* Adds support for adding load balancer inbound nat rules in network profile
* Changed storage references to align with new VM storage references

[MS] provider/azurerm: Virtual Machine Scale Sets with managed disk support

---

builtin/providers/datadog/resource_datadog_monitor.go
builtin/providers/datadog/resource_datadog_monitor_test.go
website/source/docs/providers/datadog/r/monitor.html.markdown

Added new evaluation_delay parameter to datadog_monitor

Added new evaluation_delay parameter

---

builtin/providers/aws/resource_aws_autoscaling_group_waiting.go

Closes #9074
Config to reproduce the error: https://gist.github.com/radeksimko/c2418796a87d8458d85abb2767c5e9a6
```
Error applying plan:
1 error(s) occurred:
* aws_autoscaling_group.bar: 1 error(s) occurred:
* aws_autoscaling_group.bar: "radeksimko-terraform-test": Waiting up to 20s: Need at least 4 healthy instances in ASG, have 0
```
```
Error applying plan:
1 error(s) occurred:
* aws_autoscaling_group.bar: 1 error(s) occurred:
* aws_autoscaling_group.bar: "radeksimko-terraform-test": Waiting up to 20s: Need at least 4 healthy instances in ASG, have 0 Most recent activity: {
ActivityId: "f9b6fb3b-4996-4f2e-86fa-cea062ae7730",
AutoScalingGroupName: "radeksimko-terraform-test",
Cause: "At 2017-05-15T06:35:52Z a user request created an AutoScalingGroup changing the desired capacity from 0 …
```

provider/aws: Show last scaling activity when ASG creation/update fails

---

vendor/github.com/ukcloud/govcloudair/Makefile
vendor/github.com/ukcloud/govcloudair/api_vcd.go
vendor/github.com/ukcloud/govcloudair/edgegateway.go
vendor/github.com/ukcloud/govcloudair/types/v56/types.go
vendor/github.com/ukcloud/govcloudair/vapp.go
vendor/github.com/ukcloud/govcloudair/vdc.go
vendor/vendor.json

Hello,
In reference to this issue : https://github.com/hashicorp/terraform/issues/13331 
**govcloudair** accepted the pull request https://github.com/UKCloud/govcloudair/pull/4 , so I propose here to **bump the govcloudair vendor** used for the **vcd provider**.
(tests in vCloud director 5.5 are ok).
Regards.

bump govcloudair vendor

---

examples/google-content-based-load-balancing/.gitignore
examples/google-content-based-load-balancing/README.md
examples/google-content-based-load-balancing/main.tf
examples/google-content-based-load-balancing/output.tf
examples/google-content-based-load-balancing/scripts/install-video.sh
examples/google-content-based-load-balancing/scripts/install-www.sh
examples/google-content-based-load-balancing/terraform.tfvars.example
examples/google-content-based-load-balancing/variables.tf

Add a new Google Cloud example based on the  [content-based load balancing tutorial](https://cloud.google.com/compute/docs/load-balancing/http/content-based-example).

provider/google: Google Cloud content-based load balancing example.

---

builtin/providers/heroku/import_heroku_pipeline_coupling_test.go
builtin/providers/heroku/resource_heroku_pipeline_coupling.go

Adds support for importing pipelines with the heroku_pipeline_coupling resource.
Resolves #14491

[WIP] providers/heroku: import heroku_pipeline_coupling resource

---

builtin/providers/aws/data_source_aws_instance_test.go
builtin/providers/aws/data_source_aws_route53_zone_test.go
builtin/providers/aws/resource_aws_alb_target_group_attachment_test.go
builtin/providers/aws/resource_aws_alb_target_group_test.go
builtin/providers/aws/resource_aws_ami_copy_test.go
builtin/providers/aws/resource_aws_db_instance_test.go
builtin/providers/aws/resource_aws_db_subnet_group_test.go
builtin/providers/aws/resource_aws_default_security_group_test.go
builtin/providers/aws/resource_aws_directory_service_directory_test.go
builtin/providers/aws/resource_aws_efs_mount_target_test.go
builtin/providers/aws/resource_aws_egress_only_internet_gateway_test.go
builtin/providers/aws/resource_aws_eip_association_test.go
builtin/providers/aws/resource_aws_eip_test.go
builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go
builtin/providers/aws/resource_aws_instance_test.go
builtin/providers/aws/resource_aws_internet_gateway_test.go
builtin/providers/aws/resource_aws_lambda_function_test.go
builtin/providers/aws/resource_aws_launch_configuration_test.go
builtin/providers/aws/resource_aws_main_route_table_association_test.go
builtin/providers/aws/resource_aws_nat_gateway_test.go
builtin/providers/aws/resource_aws_network_acl_rule_test.go
builtin/providers/aws/resource_aws_network_acl_test.go
builtin/providers/aws/resource_aws_network_interface_attacment_test.go
builtin/providers/aws/resource_aws_network_interface_test.go
builtin/providers/aws/resource_aws_opsworks_stack_test.go
builtin/providers/aws/resource_aws_rds_cluster_instance_test.go
builtin/providers/aws/resource_aws_rds_cluster_test.go
builtin/providers/aws/resource_aws_redshift_cluster_test.go
builtin/providers/aws/resource_aws_redshift_subnet_group_test.go

provider/aws: Tag VPCs created in our tests to help track down leaks

---

website/source/docs/providers/alicloud/r/db_instance.html.markdown

Delete an unnecessary option `commodity_code `.

Update Example Usage

---

vendor/github.com/ukcloud/govcloudair/vapp.go
vendor/github.com/ukcloud/govcloudair/vdc.go
vendor/vendor.json

Since #13585 didn't include the latest changes here yet another pull request. :)
@bobbydeveaux can you test against this changes as well? Thank you in advance.

Bumped github.com/ukcloud/govcloudair vendor version

---

config/interpolate_funcs.go
config/interpolate_funcs_test.go
website/source/docs/configuration/interpolation.html.md

Add power function

---

website/source/docs/configuration/interpolation.html.md

Add note to mention `pow` function accepts float values.
I missed commit in #14598

Add note in documentation for pow function

---

builtin/providers/aws/resource_aws_ssm_maintenance_window.go

Fixes: #14653
I was originally calling the wrong API method and only some of the
values were being persisted to state. By changing the API method, we can
now get all of the values and therefore can detech manual drift
```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSSMMaintenanceWindow_'
2017/05/19 16:56:27 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSSMMaintenanceWindow_ -timeout 120m
=== RUN   TestAccAWSSSMMaintenanceWindow_basic
--- PASS: TestAccAWSSSMMaintenanceWindow_basic (41.39s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	41.419s
```

provider/aws: Change AWS ssm_maintenance_window Read func

---

builtin/providers/aws/resource_aws_elasticache_cluster.go

```
=== RUN   TestAccAWSElasticacheCluster_snapshotsWithUpdates
--- FAIL: TestAccAWSElasticacheCluster_snapshotsWithUpdates (260.18s)
testing.go:280: Step 1 error: Error applying: 1 error(s) occurred:
* aws_elasticache_cluster.bar (destroy): 1 error(s) occurred:
* aws_elasticache_cluster.bar: InvalidCacheClusterState: Can only delete cache clusters with state in: available, failed, incompatible-parameters, incompatible-network, restore-failed, recovering. Cluster tf-tvzyhadgqq has state: snapshotting.
status code: 400, request id: 0eef8895-3d24-11e7-a41c-bbcf35279727
```
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSElasticacheCluster_'
go generate $(go list …
```

provider/aws: Retry ElastiCache cluster deletion when it's snapshotting

---

builtin/providers/aws/resource_aws_ecs_service.go

```
=== RUN   TestAccAWSEcsService_withLbChanges
--- FAIL: TestAccAWSEcsService_withLbChanges (26.37s)
* aws_ecs_service.with_lb_changes: 1 error(s) occurred:
* aws_ecs_service.with_lb_changes: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer. Please verify that the ECS service role being passed has the proper permissions.
status code: 400, request id: de0cd152-3c58-11e7-b8c6-7502821aaf89
```
Closes #4375
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEcsService_'
2017/05/21 …
```

provider/aws: Retry ECS service update on InvalidParameterException

---

builtin/providers/github/data_source_github_team.go
builtin/providers/github/data_source_github_team_test.go
builtin/providers/github/provider.go
website/source/docs/providers/github/d/team.html.markdown
website/source/layouts/github.erb

This PR adds a data source for Github teams.

Add github_team data source

---

builtin/providers/aws/resource_aws_lambda_function.go
builtin/providers/aws/resource_aws_lambda_function_test.go
website/source/docs/providers/aws/r/lambda_function.html.markdown

provider/aws: Add support for X-Ray tracing to aws_lambda_function

---

builtin/providers/openstack/resource_openstack_networking_subnet_v2.go
builtin/providers/openstack/resource_openstack_networking_subnet_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
vendor/vendor.json

This commit adds the ability to update a subnet's allocation pool.
Fixes #10942

provider/openstack: Add support for updating Subnet Allocation Pools

---

website/source/docs/providers/azurerm/r/sql_elasticpool.html.markdown

provider/azurerm: Fix example on azurerm_sql_elasticpool

---

website/source/docs/providers/azurerm/r/servicebus_subscription.html.markdown
website/source/docs/providers/opc/r/opc_compute_ssh_key.html.markdown

Fixing a couple of minor issues in the documentation/examples

Docs: Fixing typo's

---

builtin/providers/heroku/resource_heroku_addon.go

Adds support for importing addons with the heroku_addon resource.
Resolves #14504

providers/heroku: import heroku_addon resource

---

builtin/providers/openstack/import_openstack_dns_recordset_v2_test.go
builtin/providers/openstack/provider.go
builtin/providers/openstack/resource_openstack_dns_recordset_v2.go
builtin/providers/openstack/resource_openstack_dns_recordset_v2_test.go
builtin/providers/openstack/resource_openstack_dns_zone_v2.go
builtin/providers/openstack/types.go
vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/results.go
vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/urls.go
vendor/vendor.json
website/source/docs/providers/openstack/r/dns_recordset_v2.html.markdown

For #14735 
In addition, while I was testing I stumbled upon a panic condition while updating a DNS zone, so the third commit here addresses that.

add OpenStack DNS V2 RecordSet resource

---

website/source/docs/state/environments.html.md

I've seen this topic and specifically this paragraph being discussed number of times in the hangops Slack and elsewhere. It's often misunderstood as it's very easy to overlook the word "alone" in the first sentence, also many people just stop reading after the first sentence 🙈 , so this should make things clearer. 😄

Explain purpose of environments better

---

builtin/providers/aws/validators.go

Fix typo in validators.go

---

website/source/docs/providers/gitlab/index.html.markdown
website/source/docs/providers/gitlab/r/project.html.markdown

This set of commits improves the general state of the user documentation for the gitlab provider.

provider/gitlab: Documentation improvements

---

examples/azure-traffic-manager-lb-scale-set/Readme.md
examples/azure-traffic-manager-lb-scale-set/main.tf
examples/azure-traffic-manager-lb-scale-set/terraform.tfvars.example
examples/azure-traffic-manager-lb-scale-set/tf_modules/location.tf
examples/azure-traffic-manager-lb-scale-set/tf_modules/outputs.tf
examples/azure-traffic-manager-lb-scale-set/variables.tf

Hi, I've created a template that creates a globally load balanced web service for Azure using scale sets. There's documentation in the code as well as the readme.md. I've read the contribution guide and think this is okay. I've done as much testing. I hope this okay. Tim.

Added example for globally load balanced scale sets

---

builtin/providers/openstack/resource_openstack_networking_network_v2.go
builtin/providers/openstack/resource_openstack_networking_network_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/provider/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/provider/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/provider/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
vendor/vendor.json
website/source/docs/providers/openstack/r/networking_network_v2.html.markdown

Hello, I want create provider network with segment_id.
refs: http://developer.openstack.org/api-ref/networking/v2/?expanded=create-network-with-multiple-segment-mappings-detail

provider/openstack: Add support provider network

---

builtin/providers/digitalocean/resource_digitalocean_loadbalancer.go

provider/digitalocean: Refresh DO loadbalancer from state if 404

---

builtin/providers/fastly/resource_fastly_service_v1_test.go

This is to address the following intermittent test failure:
```
=== RUN   TestAccFastlyServiceV1_updateBackend
--- FAIL: TestAccFastlyServiceV1_updateBackend (2.00s)
* fastly_service_v1.foo: 1 error(s) occurred:
* fastly_service_v1.foo: 400 - Bad Request
Message: An error occurred while connecting to the fastly API, please try your request again.
Detail: Domain 'test.notadomain.com' is already taken by service '4sL5OL5YIwfsJ1y5DCv7VY'
```
```
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (13.30s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (13.72s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: …
```

provider/fastly: Randomize domain names in tests

---

builtin/providers/postgresql/resource_postgresql_role.go

Drop the optional WITH token from CREATE ROLE.

---

builtin/providers/ignition/resource_ignition_user_test.go

A minor fix to ignition user test.

fixed error message

---

builtin/providers/azurerm/resource_arm_cdn_profile.go
builtin/providers/azurerm/resource_arm_cdn_profile_test.go
builtin/providers/azurerm/resource_arm_eventhub_namespace.go
builtin/providers/azurerm/resource_arm_eventhub_namespace_test.go
builtin/providers/azurerm/resource_arm_managed_disk.go
builtin/providers/azurerm/resource_arm_managed_disk_test.go
builtin/providers/azurerm/resource_arm_redis_cache.go
builtin/providers/azurerm/resource_arm_redis_cache_test.go
builtin/providers/azurerm/resource_arm_servicebus_namespace.go
builtin/providers/azurerm/resource_arm_servicebus_namespace_test.go
builtin/providers/azurerm/resource_arm_storage_account.go
builtin/providers/azurerm/resource_arm_storage_account_test.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go
builtin/providers/azurerm/resource_arm_virtual_machine_scale_set_test.go

Fixes issue https://github.com/hashicorp/terraform/issues/14188 and also https://github.com/hashicorp/terraform/issues/11626.

Changes to behaviour of string enum comparison in AzureRM provider

---

builtin/providers/aws/resource_aws_instance.go

Previously `ModifyInstanceAttribute` permissions were required on creating a new instance with an unmodified `source_dest_check` attribute, as we forced the `ModifyInstanceAttribute` set on a new AWS instance.
This change only calls `ModifyInstanceAttribute` if `source_dest_check` was changed from default on a new instance, or if `source_dest_check` was modified.
```
$ make testacc TEST=./builtin/providers/aws TESTARGS="-run=TestAccAWSInstance_sourceDestCheck"
2017/06/01 11:18:31 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSInstance_sourceDestCheck -timeout 120m
=== RUN   TestAccAWSInstance_sourceDestCheck
--- PASS: …
```

provider/aws: Fix ModifyInstanceAttribute on new instances

---

website/source/docs/providers/aws/r/lightsail_domain.html.markdown
website/source/docs/providers/aws/r/lightsail_instance.html.markdown
website/source/docs/providers/aws/r/lightsail_key_pair.html.markdown
website/source/docs/providers/aws/r/lightsail_static_ip.html.markdown
website/source/docs/providers/aws/r/lightsail_static_ip_attachment.html.markdown

**Reasoning for docs update:** This commit complements #14621 and #14685.
**Relevant Terraform version:** 0.9.6 (May 25, 2017)

docs: Update Lightsail supported regions

---

builtin/providers/openstack/config.go
terraform/user_agent.go

Just because it's useful... :)

provider/openstack: Add Terraform version to UserAgent string

---

plugin/discovery/get.go
plugin/discovery/get_test.go

We can filter the allowed versions and sort them before checking the
protocol version, that way we can just return the first one found
reducing network requests.

clean up plugin fetching

---

website/source/docs/providers/kubernetes/index.html.markdown

docs/kubernetes: Document compatible k8s versions

---

builtin/providers/kubernetes/resource_kubernetes_persistent_volume_claim.go

* kubernetes_persistent_volume_claim.test: timeout while waiting for state to become 'Bound' (last state: 'Pending', timeout: 5m0s)
* kubernetes_persistent_volume_claim.test: timeout while waiting for state to become 'Bound' (last state: 'Pending', timeout: 5m0s). Reason: ProvisioningFailed: Failed to provision volume with StorageClass "standard": claim.Spec.Selector is not supported for dynamic provisioning on GCE
------
It would be great if we could fail fast in such cases, but there's no simple way to detect "retryable" (like not enough CPU/mem on available nodes) warnings/errors and non-retryable.

provider/kubernetes: Provide more details about why PVC failed to bind

---

examples/alicloud-build-lnmp/main.tf
examples/alicloud-build-lnmp/outputs.tf
examples/alicloud-build-lnmp/userdata.sh
examples/alicloud-build-lnmp/variables.tf

This PR add a new template of using alicloud provider to build and install LNMP

provider/alicloud: Add new example alicloud-build-lnmp

---

builtin/providers/aws/resource_aws_redshift_cluster.go

This is to address the following intermittent test failure:
```
=== RUN   TestAccAWSRedshiftCluster_kmsKey
--- FAIL: TestAccAWSRedshiftCluster_kmsKey (220.18s)
testing.go:344: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* aws_redshift_cluster.default (destroy): 1 error(s) occurred:
* aws_redshift_cluster.default: [ERROR] Error deleting Redshift Cluster (tf-redshift-cluster-2738252259698769279): InvalidClusterState: There is an operation running on the Cluster. Please try to delete it at a later time.
status code: 400, request id: b96905ed-48f3-11e7-99c9-030a36408bad
```

provider/aws: Retry Redshift cluster deletion on InvalidClusterState

---

builtin/providers/aws/resource_aws_ecs_service.go

This is to address the following test failures:
```
=== RUN   TestAccAWSEcsServiceWithFamilyAndRevision
--- FAIL: TestAccAWSEcsServiceWithFamilyAndRevision (11.63s)
* aws_ecs_service.jenkins: 1 error(s) occurred:
* aws_ecs_service.jenkins: ServiceNotFoundException: Service not found.
status code: 400, request id: 7111c49f-49b4-11e7-8a31-1f4c10a1cce8
=== RUN   TestAccAWSEcsService_withAlb
--- FAIL: TestAccAWSEcsService_withAlb (187.15s)
* aws_ecs_service.with_alb: 1 error(s) occurred:
* aws_ecs_service.with_alb: ServiceNotFoundException: Service not found.
status code: 400, request id: e22e863d-49b4-11e7-9e01-79f4e5b714b9
```
Here's a relevant snippet from …

provider/aws: Retry ECS svc update on ServiceNotFoundException

---

builtin/providers/aws/resource_aws_db_parameter_group.go

```
=== RUN   TestAccAWSDBParameterGroup_limit
--- FAIL: TestAccAWSDBParameterGroup_limit (15.30s)
testing.go:344: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* aws_db_parameter_group.large (destroy): 1 error(s) occurred:
* aws_db_parameter_group.large: InvalidDBParameterGroupState: DB parameter group parameter-group-test-terraform-5586802289934950299 can not be deleted in the current state
status code: 400, request id: 18e90f9b-49b3-11e7-81c7-dbeb5fd7b744
```

provider/aws: Retry DB param grp delete on InvalidDBParameterGroupState

---

builtin/providers/google/import_compute_http_health_check_test.go
builtin/providers/google/resource_compute_health_check_test.go
builtin/providers/google/resource_compute_http_health_check_test.go
builtin/providers/google/resource_compute_https_health_check_test.go

Like the tests in #15101, all 3 health check resources were not performing updates in their update tests.
@danawillow

provider/google: Update health check tests

---

vendor/github.com/digitalocean/godo/CHANGELOG.md
vendor/github.com/digitalocean/godo/README.md
vendor/github.com/digitalocean/godo/droplet_actions.go
vendor/github.com/digitalocean/godo/firewalls.go
vendor/github.com/digitalocean/godo/godo.go
vendor/vendor.json

This allows support for DigitalOcean Firewalls

provider/digitalocean: Bump godo SDK to 1.1.0

---

builtin/providers/librato/resource_librato_alert.go
builtin/providers/librato/resource_librato_alert_test.go

This PR:
- Fixes an error whereby updating an Alert times out due to the change not being properly taken into account, which we've run into several times already.
- Applies a series of improvements to the and very likely bug fixes inspired by https://github.com/hashicorp/terraform/pull/14562

Librato Alerts fixes

---

website/source/docs/import/importability.html.md
website/source/docs/providers/github/r/branch_protection.html.markdown
website/source/docs/providers/github/r/issue_label.html.markdown
website/source/docs/providers/github/r/membership.html.markdown
website/source/docs/providers/github/r/repository_collaborator.html.markdown
website/source/docs/providers/github/r/team.html.markdown
website/source/docs/providers/github/r/team_membership.html.markdown
website/source/docs/providers/github/r/team_repository.html.markdown

provider/github: Add github importability documentation

---

builtin/providers/google/resource_compute_subnetwork.go
builtin/providers/google/resource_compute_subnetwork_test.go
website/source/docs/providers/google/r/compute_subnetwork.html.markdown

Added private_ip_google_access update support to google_compute_subnetwork.
Fix for #15109 
@danawillow

provider/google: Add private_ip_google_access update support to google_compute_subnetwork

---

builtin/providers/aws/validators.go

fix aws cidr validation error

---

builtin/provisioners/chef/resource_provisioner.go

provisioner/chef: use the InstanceState to query any connection details

---

website/intro/getting-started/build.html.md

To avoid `InvalidAMIID.NotFound`
See https://github.com/hashicorp/terraform/issues/11220

Warn that amis are region specific

---

config/interpolate_funcs.go
config/interpolate_funcs_test.go
website/docs/configuration/interpolation.html.md

`contains()` function is to test if an element is present in the list

#15291: config/interpolate_funcs: Added contains() function

---

vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
vendor/vendor.json

This is to get an upstream fix which will in turn address #15321.

vendor: go fetch github.com/apparentlymart/go-cidr/cidr

---

CHANGELOG.md
website/docs/commands/init.html.markdown

update init docs

---

command/init.go

This takes care of a few dangling cases where we were still stringifying empty version constraints, which creates confusing error messages due to it stringing as the empty string.
For the "no suitable versions available" message, we fall back on the "provider not found" message if no versions were found even though it's unconstrained. This should only happen in an edge case where the
provider's index page exists on the releases server but no versions are yet present.
For the message about plugin protocol versions, this again is an edge case since with no constraints this should happen only if we release an incompatible Terraform version but don't release a new version of the
plugin that's compatible. In this case we just show the constraint as "(any version)" to make sure we always show …

command: avoid empty string constraints in plugin install errors

---

CHANGELOG.md

Fixing a simple typo in CHANGELOG.md

Fix typo amd => and

---

website/docs/import/importability.html.md

Depends on terraform-providers/terraform-provider-google#40

Add google_compute_backend_service to imports

---

command/workspace_delete.go

We need to release the lock just before deleting the state, in case the backend
can't remove the resource while holding the lock. This is currently true for
Windows local files.
While we lose some coordination here, there is little loss in safety, since if a process is waiting for a named state, it's not expecting it to be deleted. If it were expecting it to be removed, it must be willing to call `workspace new`, in which case the command will simply fail if it still exists. 
Fixes #15343

Unlock state before workspace deletion

---

helper/shadow/closer.go

The Close methods on shadow.Values require pointer receivers because
they contain a sync.Mutex, but that value was being copied through
Value.Interface by the closeWalker.  Because reflectwalk passes the
struct fields to the StructField method as they are defined in the
struct, and they may have been read as a value, we can't immediately
call Interface() to check the method set without possibly copying the
internal mutex values. Use the Implements method to first check if we
need to call Interface, and if it's not, then we can check if the value
is addressable.
Because of this use of reflection, we can't vet for the copying of these
locks. The minimal amount of code in the Close method left us only with
a race detected within the mutex itself, which leads to a stacktrace
pointing to the …

Make sure shadow.closeWalker doesn't copy Mutexes

---

plugin/discovery/get.go

If the release site is missing the "x-terraform-protocol-version"
header, we should fetch the latest spec'ed release. Downloading the
wrong protocol version can't do any damage, and the version present is
more than likely compatible.
Because the header information is kept out of band, there is a slightly higher chance of it going missing at some point, and provider availability is more important.

allow missing x-terraform-protocol-version

---

backend/remote-state/consul/client.go

When a consul lock is lost, there is a possibility that the associated
session is still active. Most commonly, the long request to watch the
lock key may error out, while the session is continually refreshed at a
rate of TTL/2.
First have the lock monitor retry the lock internally for at least 10
seconds (5 attempts with the default 2 second wait time). In most cases
this will reconnect on the first try, keeping the lock channel open.
If the consul lock can't recover itself, then cancel the session as soon
as possible (terminating the PreiodicRenew will call Session.Destroy),
and start over. In the worse case, the consul agents were split, and the
session still exists on the leader so we may need to wait for the old
session TTL, plus the LockWait time to renew the lock.
We use a Context …

have the consul client manage the lock session

---

website/docs/import/usage.html.md

Based on feedback from #15569 that the previous example was too abstract and did not give enough context about what each of the different arguments mean and how they generalize to other resource types.

website: attempt to clarify "terraform import" usage docs

---

command/plugins_test.go
command/workspace_new.go

I found some errors in the command package that were being ignored.

Fix swallowed errors in command package.

---

builtin/provisioners/chef/resource_provisioner.go

provisioner/chef: fix panic

---

website/docs/backends/config.html.md
website/docs/commands/init.html.markdown

The `terraform init` command has a lot of different functionality now, making it hard to follow all of the options in the previous presentation. Instead, here we describe each of the steps and its associated options separately, hopefully making it easier to understand what each option relates to.
In addition, much of the detail around backend partial configuration is factored out into the backend configuration page, where it seems more "at home"; previously it felt hard to follow exactly how partial configuration would be used, due to the information on it being split over two different pages.

website: more-elaborate "terraform init" docs

---

website/docs/backends/types/s3.html.md

Explain the path generated for state files when using workspaces.
Closes #15358

Update S3 backend docs to reflect new workspaces

---

terraform/context_validate_test.go
terraform/node_data_refresh_test.go
terraform/node_resource_refresh_test.go
terraform/upgrade_state_v1_test.go

I found some errors in the tests for the terraform package that were being swallowed.

Fix swallowed tests in terraform package tests

---

config/loader_hcl.go

This is to prevent mistakes like https://github.com/hashicorp/terraform/pull/9366 and generally to improve dev experience.
I could add a test, but both slices are already tested and it seems unnecessary to test just a one new item in existing slice.

config: Make 'id' a reserved field name

---

website/guides/running-terraform-in-automation.html.md

small typo correction

---

command/hook_ui_test.go
vendor/github.com/mitchellh/cli/README.md
vendor/github.com/mitchellh/cli/autocomplete.go
vendor/github.com/mitchellh/cli/cli.go
vendor/github.com/mitchellh/cli/command.go
vendor/github.com/mitchellh/cli/command_mock.go
vendor/github.com/mitchellh/cli/help.go
vendor/github.com/mitchellh/cli/ui_mock.go
vendor/github.com/posener/complete/LICENSE.txt
vendor/github.com/posener/complete/args.go
vendor/github.com/posener/complete/cmd/cmd.go
vendor/github.com/posener/complete/cmd/install/bash.go
vendor/github.com/posener/complete/cmd/install/install.go
vendor/github.com/posener/complete/cmd/install/utils.go
vendor/github.com/posener/complete/cmd/install/zsh.go
vendor/github.com/posener/complete/command.go
vendor/github.com/posener/complete/complete.go
vendor/github.com/posener/complete/log.go
vendor/github.com/posener/complete/match/file.go
vendor/github.com/posener/complete/match/match.go
vendor/github.com/posener/complete/match/prefix.go
vendor/github.com/posener/complete/metalinter.json
vendor/github.com/posener/complete/predict.go
vendor/github.com/posener/complete/predict_files.go
vendor/github.com/posener/complete/predict_set.go
vendor/github.com/posener/complete/readme.md
vendor/github.com/posener/complete/test.sh
vendor/github.com/posener/complete/utils.go
vendor/vendor.json

The latest version brings autocompletion and allows us to simplify code in tests.

vendor: Bump github.com/mitchellh/cli to latest

---

tools/terraform-bundle/package.go

tools/terraform-bundle: Add missing Ui to ProviderInstaller (fix crash)

---

command/init.go

OCD 👁 ...
```
$ terraform init
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "kubernetes" (0.1.2)...
```
```
$ terraform init
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "kubernetes" (0.1.2)...
```

command/init: Remove extra whitespace

---

README.md

Expose "Getting Started" on the README
------
We recently saw a tweet or two that makes us thing we're not exposing or presenting this information well. We're evaluating things on terraform.io as well as here and the provider repos to hopefully make things clearer.

Update README with link to "Getting started" guide

---

command/e2etest/init_test.go
command/e2etest/main_test.go
command/e2etest/primary_test.go
command/e2etest/version_test.go
e2e/e2e.go
tools/terraform-bundle/e2etest/main_test.go
tools/terraform-bundle/e2etest/package_test.go
tools/terraform-bundle/e2etest/test-fixtures/empty/terraform-bundle.hcl
tools/terraform-bundle/e2etest/test-fixtures/many-providers/terraform-bundle.hcl

This is adding E2E tests for https://github.com/hashicorp/terraform/pull/15826 to prevent us from breaking it again.

tools/terraform-bundle: Add e2e tests

---

config/interpolate_funcs.go
config/interpolate_funcs_test.go
website/docs/configuration/interpolation.html.md

add urlencode interpolation function

---

command/init.go
command/init_test.go
command/test-fixtures/init-check-required-version/main.tf
terraform/context.go
terraform/version_required.go

init: check required_version

---

website/guides/terraform-provider-development-program.html.md
website/layouts/guides.erb

This brings back the provider dev program content with a copy change.
Reviewed by Burzin already, requesting review from Clint.

website: new provider dev program content

---

website/docs/modules/sources.html.markdown

Invalid Terraform in examples = 😢

Add some missing quotes in the Module docs

---

config/interpolate_funcs.go
config/interpolate_funcs_test.go
website/docs/configuration/interpolation.html.md

Addresses #10378
Closes #15308

Added multi-line indent function

---

website/layouts/docs.erb

This also updates the `sidebar_current` to match what's in TFE's index.html.md.

website: Add TFE beta to sidebar nav

---

website/docs/configuration/providers.html.md

website: clarify that provider version does not accept interpolations

---

terraform/ui_output_mock.go

Fixes a test-only race condition.

minor race fix in tests

---

backend/remote-state/s3/client.go

Internal errors from S3 are usually transient, and can be immediately retried.
Make 2 attempts at retreiving the state object before returning an error.

retry on s3 backend internal errors

---

config/module/tree.go

Signed-off-by: Stefan Staudenmeyer <stefan.staudenmeyer@instana.com>

Aliasing the module to omit errors thrown at build time

---

website/layouts/docs.erb

For upcoming LogicMonitor Provider

website: Add logicmonitor provider to sidebar 

---

website/docs/modules/create.html.markdown

Adding a few more requirements to the Creating Modules README docs.

Changes to module documentation 

---

website/docs/configuration/interpolation.html.md

website: fix "contains" interpolation example

---

backend/remote-state/s3/client.go

While #16243 added the ability to retry getting a state from S3, Put can
return the same `InternalError` status. Use the same retry logic when
uploading state to S3.

retry on s3 state upload errors

---

website/layouts/guides.erb

This is a companion PR to https://github.com/hashicorp/terraform-website/pull/39, to enable the right sidebar navigation.

website: Add nav items for Terraform Recommended Practices guide to nav

---

helper/hashcode/hashcode.go
helper/hashcode/hashcode_test.go

I thought this could be useful for creating ids for data sources that
pull in multiple resources.

Adds Strings function for hashing slices of strings

---

website/docs/provisioners/chef.html.markdown

- Added some more details about ssl_verify_mode
Signed-off-by: JJ Asghar <jj@chef.io>

Added an example of ssl_verify_mode

---

website/docs/import/importability.html.md

https://github.com/terraform-providers/terraform-provider-dyn/pull/19 Added the functionality for dyn_record to be an importable resource

Add dyn_record as a resource that can be imported

---

website/docs/backends/types/azurerm.html.md

make it more clear how remote state & locking work with the AzureRM backend. Bring terms into alignment with Azure norms.

add detail to the description of the azurerm backend.

---

website/docs/configuration/modules.html.md
website/docs/configuration/variables.html.md
website/docs/internals/remote-service-discovery.html.md
website/docs/modules/usage.html.markdown
website/docs/registry/api.html.md
website/docs/registry/index.html.md
website/docs/registry/private.html.md
website/intro/getting-started/modules.html.md
website/layouts/docs.erb
website/upgrade-guides/0-11.html.markdown

Various updates of the docs for the bigger changes in the 0.11 release.

Documentation for 0.11 release

---

config/module/registry.go

If registry API discovery fails for a particular host then it's better to generate an explicit error message for that early -- so we can tell the user exactly what happened -- rather than assuming a default path and then failing downstream when we get a 404 from that request.
```
$ terraform init -from-module=example.com/hashicorp/consul/aws
Copying configuration from "example.com/hashicorp/consul/aws"...
Error copying source module: host example.com does not provide Terraform modules
```
---
At the time of this writing there is no discovery document on `registry.terraform.io`, but that change has been checked in and so it will appear in the next release. We'll hold off on merging this until that release goes out, so that anyone building from master won't see public registry installs fail …

config/module: produce explicit error for non-registry hosts

---

website/docs/configuration/interpolation.html.md

Minor update to interpolation.html.md

---

website/layouts/docs.erb

Link to docs for upcoming CloudScale provider, coming soon
Do not merge yet thx

[WIP]: website: Add CloudScale Provider link

---

terraform/transform_provider.go

We can remove the AllowAny option which is no longer used, and providers
don't need to be connected to their resources at this stage, since that
will happen in the ProviderTransformer.
This now only needs to make sure there's a single top-level provider for each type.

further simplify the missing provider transformer

---

website/docs/import/importability.html.md

Linked to terraform-providers/terraform-provider-heroku#18

Adding documentation for all supported imports in the Heroku provider

---

terraform/node_resource_abstract.go
terraform/transform_deposed.go
terraform/transform_import_state.go
terraform/transform_provider.go

ProvidedBy doesn't need to be a slice.

Minor cleanup, ProvidedBy return value is a single string

---

website/docs/registry/index.html.md
website/docs/registry/modules/use.html.md

Thanks @apparentlymart for updating the rest of these docs. I was reviewing it assuming I needed to document all the registry changes but you have already done almost all of it!
These are a few bits left a little stale/inconsistent post 0.11.

Tweaks to Registry Docs for 0.11

---

website/docs/modules/usage.html.markdown

The differences between the implicit and explicit modes of passing provider configurations between modules are significant enough to warrant giving these approaches different names and describing them separately.
This also includes documentation of the current limitation discussed in #16612, where explicit passing requires a proxy configuration block even for a _default_ provider configuration, because that limitation is being accepted for the 0.11.0 release to limit scope.

website: further copyediting for "Providers within Modules"

---

README.md

We want to finalize the FOSSA checks before publishing them

Remove FOSSA from the readme

---

website/layouts/docs.erb

The Null resource was missing from the list of the providers.

Adding the Null resource to the list of providers

---

website/docs/configuration/variables.html.md

Resolves https://github.com/hashicorp/terraform/issues/15595

Fix #15595 - add explanation of TF_VAR_ precedence

---

website/docs/backends/types/s3.html.md

Attempts to resolve https://github.com/hashicorp/terraform/issues/16504
Not sure whether this is the complete set of permissions necessary, though.

Fix #16504 - S3 IAM permissions for remote state

---

website/docs/backends/types/terraform-enterprise.html.md

Recommend `ATLAS_TOKEN` instead of `access_token`

update tfe backend to recommend atlas_token

---

builtin/bins/provisioner-habitat/main.go
builtin/provisioners/habitat/resource_provisioner.go
builtin/provisioners/habitat/resource_provisioner_test.go
command/internal_plugin_list.go
website/docs/provisioners/habitat.html.markdown
website/layouts/docs.erb

This adds a Habitat (https://habitat.sh) provisioner.

Add habitat provisioner

---

website/layouts/docs.erb

Companion PR to https://github.com/hashicorp/terraform-website/pull/76

add opentelekomcloud link to docs

---

helper/resource/testing.go

Currently, the resources test helpers assume that your resources are created within the root module.
This PR expands this helper functionality to allow for testing resources created within modules. This is helpful for expanding acceptance testing beyond simple unit test into testing the logic of complicated modules.
For example (testing my module called configuration-template):-
```
package aws
import (
"fmt"
"regexp"
"testing"
"github.com/hashicorp/terraform/helper/acctest"
"github.com/hashicorp/terraform/helper/resource"
)
func TestAccArrakisElasticBeanstalkConfigurationTemplate(t *testing.T) {
rString := acctest.RandString(3)
keyRegex, _ := regexp.Compile("mega-test")
resource.Test(t, resource.TestCase{
PreCheck:  func() { testAccArrakisPreCheck(t) },
Providers: testAccProviders, …
```

add support for testing resources within modules

---

website/docs/configuration/interpolation.html.md

Copy note from https://github.com/terraform-providers/terraform-provider-aws/pull/2162 into a common area as well as in that specific resource doc

copy doc note from terraform-providers/terraform-provider-aws/2162

---

backend/remote-state/manta/backend_state.go
backend/remote-state/manta/backend_test.go
backend/remote-state/manta/client.go
backend/remote-state/swift/backend_test.go
builtin/provisioners/habitat/resource_provisioner.go
command/apply_test.go
config_unix.go
helper/resource/testing_import_state_test.go
helper/schema/resource.go
helper/schema/schema.go
terraform/context_apply_test.go
terraform/interpolate.go
terraform/module_dependencies.go
tools/terraform-bundle/e2etest/doc.go

Minor vet and fmt changes coming in go1.10. Nothing that is backwards incompatible.

go1.10 prep

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/database-index.html.markdown
website/docs/providers/type/infra-index.html.markdown
website/docs/providers/type/major-index.html.markdown
website/docs/providers/type/misc-index.html.markdown
website/docs/providers/type/monitor-index.html.markdown
website/docs/providers/type/network-index.html.markdown
website/docs/providers/type/vcs-index.html.markdown
website/layouts/docs.erb

@apparentlymart  Here is a second attempt of  #16934 with some minor changes.
Please review and we can discuss in the morning. 
-Chris

Website: terraform.io docs - provider catagories

---

backend/remote-state/s3/backend_state.go
backend/remote-state/s3/backend_test.go

I believe this will fix https://github.com/hashicorp/terraform/issues/16383 and https://github.com/hashicorp/terraform/issues/16387

Fixing issues with workspace_key_prefix for s3 backend

---

website/docs/providers/index.html.markdown
website/docs/providers/type/community-index.html.markdown

Add community provider
and a formatting edit

Provider documentation update

---

website/docs/providers/type/network-index.html.markdown

Fix DNSMadeEasy's name in the provider index

Fix DNSMadeEasy's name in the provider index

---

website/docs/providers/type/community-index.html.markdown

Fix OpenDayLight link
Add new community providers: DigitalRebar; Kibana; Kong; Runscope

update community providers

---

website/docs/providers/type/community-index.html.markdown

Adding community providers:
Acme
AVI
GoCD
Jira

Website Docs: add community providers

---

builtin/provisioners/chef/resource_provisioner.go

Correctly validate Chef provisioner's `use_policyfile` field even if its value is a string type.
This fixes https://github.com/hashicorp/terraform/issues/16655

Fix chef provisioner validateFn

---

website/docs/backends/types/s3.html.md

Correct website typo

---

website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown

Adding three more providers and modifying one provider name.

Website: update provider docs

---

website/docs/state/workspaces.html.md

This PR documents local state files as a supported backend for workspaces.
Resolves issue #17093

Workspaces are supported locally.

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/network-index.html.markdown

add the PANOS provider links to the docs
[Work in Progress] Please do not merge

Website: Provider link

---

command/plan_test.go

The plan shutdown test often fail on slow CI hosts, becase the plan
completes beffor the main thread can cancel it. Since attempting to make
the MockProvider concurrent proved too invasive for now, just slow the
test down a bit to help ensure Stop gets called.

slow down the plan shutdown tests for slow hosts

---

website/docs/providers/index.html.markdown
website/docs/providers/type/network-index.html.markdown

change provider name from PANOS to Palo Alto Networks

Website Update provider name

---

website/docs/providers/type/community-index.html.markdown

Website: Restructure Community providers list

---

website/docs/import/importability.html.md

See https://github.com/hashicorp/terraform-website/issues/20
cc @wjwoodson

Document aws_route53_record importable

---

helper/resource/testing.go

add override to prevent disk cleanup during module load step

---

helper/resource/testing.go

fixed missing module path panic

---

builtin/provisioners/salt-masterless/resource_provisioner.go

In this pull request, I want to solve race condition in ssh client.
When VM instance switches to state READY then ssh is not ready because vm is in booting process.
```
$go test -timeout=60s -parallel=4 github.com/hashicorp/terraform/builtin/provisioners/salt-masterless
ok  	github.com/hashicorp/terraform/builtin/provisioners/salt-masterless	0.022s
```

fix ssh problem with communicator.Retry

---

website/docs/providers/type/community-index.html.markdown

Please review and merge to master + cherrypick to stable-website
Thanks!

Website: Update Community Providers

---

website/docs/providers/type/community-index.html.markdown

Please review and merge + cherrypick to stable-website branch
Thanks!

Website: add two community providers

---

website/docs/configuration/providers.html.md

Trivial documentation fix

---

website/docs/modules/usage.html.markdown

Grammar Improvement

---

vendor/github.com/joyent/triton-go/CHANGELOG.md
vendor/github.com/joyent/triton-go/GNUmakefile
vendor/github.com/joyent/triton-go/README.md
vendor/github.com/joyent/triton-go/authentication/agent_key_identifier.go
vendor/github.com/joyent/triton-go/authentication/private_key_signer.go
vendor/github.com/joyent/triton-go/authentication/signer.go
vendor/github.com/joyent/triton-go/authentication/ssh_agent_signer.go
vendor/github.com/joyent/triton-go/authentication/test_signer.go
vendor/github.com/joyent/triton-go/client/client.go
vendor/github.com/joyent/triton-go/storage/client.go
vendor/github.com/joyent/triton-go/storage/directory.go
vendor/github.com/joyent/triton-go/triton.go
vendor/github.com/joyent/triton-go/version.go
vendor/vendor.json

This will support the features of RBAC in Manta Backends

backend/manta: Update triton-go dependency to 1.1.1

---

website/docs/internals/remote-service-discovery.html.md
website/layouts/docs.erb

Verified locally. Reference: https://github.com/hashicorp/terraform-website/issues/175

docs/internal: Fix sidebar navigation for Remote Service Discovery page

---

builtin/provisioners/chef/linux_provisioner.go
builtin/provisioners/chef/linux_provisioner_test.go
builtin/provisioners/chef/resource_provisioner.go
builtin/provisioners/chef/windows_provisioner.go
builtin/provisioners/chef/windows_provisioner_test.go

This also updates the omnitruck url to the current url.
Signed-off-by: Scott Hain <shain@chef.io>

Updates the chef provisioner to allow specifying a channel

---

website/docs/providers/index.html.markdown
website/docs/providers/type/major-index.html.markdown

sorry for the merge from *master ;)

add oracle pass links

---

website/docs/state/workspaces.html.md

In an earlier commit we added the "Best Practices" situation to try to clarify the intended uses of named workspaces and to warn against using them as an alternative to system decomposition.
However, the prior statement was cautious in its recommendations in the interests of being pragmatic/flexible, and as a result we've seen that users have in some cases misinterpreted these recommendations.
The new "When to use Multiple Workspaces" section aims to be more explicit that having multiple separate Terraform configurations is the preferred solution for many use-cases, and that the current workspace design is intended for a more limited set of use-cases around convenient development and testing. It also emphasizes the analogy to version control branches that was just a footnote in the prior …

website: Stronger statements on when to use named workspaces

---

repl/format.go

The indent function was stripping out newlines, causing multi-element lists and maps to be rendered incorrectly.
We were also not quoting strings in these nested structures, leading to weird behavior if any expression punctuation or newlines were present in these strings.
This part of Terraform will get a more serious overhaul as part of switching to the new parser/interpreter implementation but this is a tactical fix to make the results of this command more usable in the short term.

repl: fix formatting of list and map values

---

website/docs/commands/plan.html.markdown

Typos Corrected

---

website/docs/providers/type/community-index.html.markdown

switch guthub with github global

fix incorrect url

---

.travis.yml
Makefile

Depends on https://github.com/hashicorp/terraform-website/pull/269

make: Add website + website-test targets

---

lang/funcs/cidr.go
lang/funcs/cidr_test.go
lang/funcs/crypto.go
lang/funcs/crypto_test.go
lang/funcs/datetime.go
lang/funcs/datetime_test.go
lang/funcs/encoding.go
lang/funcs/encoding_test.go
lang/funcs/filesystem.go
lang/funcs/filesystem_test.go
lang/funcs/number.go
lang/funcs/number_test.go
lang/funcs/string.go
lang/funcs/string_test.go
lang/functions.go
website/docs/configuration/functions/base64sha256.html.md
website/docs/configuration/functions/base64sha512.html.md
website/docs/configuration/functions/cidrsubnet.html.md
website/docs/configuration/functions/csvdecode.html.md
website/docs/configuration/functions/log.html.md

Port functions from config package to HCL2

Feature: hcl2 functions

---

website/docs/providers/index.html.markdown
website/docs/providers/type/monitor-index.html.markdown

Removing Runscope links until provider it ready for release.

remove runscope links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Stable website sync

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

commit to master, there is a pr to cherry-pick to stable-website here --> https://github.com/hashicorp/terraform/pull/18192

add HetznerCloud provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

add provider documentation links

---

lang/funcs/collection.go
lang/funcs/collection_test.go

Added test cases and refactored where necessary to support unknown values in collections

f-hcl2-functions: unknown values 

---

website/docs/commands/untaint.html.markdown

should be maximum not maxiumum

fixes docs typo

---

website/docs/configuration/resources.html.md

should be provides, not provies

fix for typo in resources.html.md

---

website/docs/providers/index.html.markdown
website/docs/providers/type/monitor-index.html.markdown

This is a cherry-pick of the commit to master branch

Runscope links cherrypick --> Stable website

---

config/module/storage.go
registry/client.go
svchost/disco/disco.go

And fix a few linter warnings while we're at it…

svchost/disco: make sure to close the response body

---

website/upgrade-guides/0-12.html.markdown

Based on some feedback on the initial draft, make some minor updates to how information is presented in the preview upgrade guide for v0.12.
This also includes some minor copy-editing work to try to make the "voice" more consistent between different sections of the guide.

website: v0.12 preview upgrade guide tweaks

---

command/workspace_command.go

We can do a terraform workpsace list in order to list existing workspaces, but we don't know this feature with the helper test.

fix(workspace): add list feature for workspace

---

config/hcl2shim/flatmap.go
config/hcl2shim/flatmap_test.go

Add nil/Null checks to the `FlatmapValueFromHCL2` and `HCL2ValueFromFlatmap` functions.

fix shims to handle nil flatmaps

---

states/statemgr/filesystem.go
states/statemgr/filesystem_test.go

In the old state package we had this as a separate manager `state.BackupState`, but that doesn't work with our new interfaces because we handle lineage and serial within the state managers themselves and
don't expose them to callers anymore.
In practice it being built in to the filesystem manager is not a problem because we only use the backup functionality for local state anyway.
This also slightly adjusts the behavior to be more intuitive. The old `BackupState` relied on the implementation detail that Terraform re-persists the original state early in an apply operation, which meant that by coincidence it would back up the right snapshot. In this new approach, we instead take an in-memory copy during State and then write _that_ to disk in `WriteState` if the new state seems different, so …

statemgr: Backup file support for statemgr.Filesystem

---

website/guides/terraform-provider-development-program.html.md

Update the Provider Development Program doc to mention the Extending Terraform section, and recommend it for getting started

Update some content to reference the extending terraform section

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/infra-index.html.markdown

- Adding Brightbox as new Terraform provider
- Add Arukas provider link to main index
- Add Docker provider link to infrastructure software page

update provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/infra-index.html.markdown
website/docs/providers/type/major-index.html.markdown
website/docs/providers/type/misc-index.html.markdown
website/docs/providers/type/monitor-index.html.markdown

the master branch providers links is behind the stable-website(actually) provider links. This PR catches up the master branch. 
We'll have a new process for merging in to provider docs so that this doesn't happen again. 
Thanks,
Chris

update master branch with provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/major-index.html.markdown
website/docs/providers/type/misc-index.html.markdown

Changes approved in https://github.com/hashicorp/terraform/pull/18615

terraform website - cherry-pick from master

---

builtin/providers/terraform/provider.go
providers/provider.go
provisioners/provisioner.go
terraform/provider_mock.go
terraform/provisioner_mock.go

Add the Close method to the new provider and provisioner interfaces
Create test mocks for the new interfaces.

plugin mocks

---

website/docs/providers/index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/infra-index.html.markdown

Add Community providers:
Dead Man's Snitch
Manifold
Remove TFE Atlas provider links

Website: Add community providers, remove Atlas links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/infra-index.html.markdown

This is a cherry pick commit from https://github.com/hashicorp/terraform/pull/18703

Website: Cherry-pick

---

command/meta_backend.go

This commit fixes a bug that (in the case of the `local` backend) would only check if the selected workspace had a state when deciding to perform a migration.
When the selected workspace didn’t have a state (but other existing workspace(s) did), the migration would not be performed and the other workspaces would be ignored.

backend/migrations: check all workspaces

---

website/docs/providers/type/cloud-index.html.markdown

This is a cherry-pick from master of https://github.com/hashicorp/terraform/pull/18776

Website: [cherrypick] HuaweiCloud link

---

helper/schema/shims.go
helper/schema/shims_test.go

The "id" field is assumed to always exist, and must have a valid value.
Set "id" to unknown when planning new resource changes to indicate that
it will be computed.

 resource ids must always have a value

---

website/docs/configuration/interpolation.html.md

issue #18808  update uuid definition

---

website/docs/providers/index.html.markdown
website/docs/providers/type/misc-index.html.markdown

Add links to the website documentation for the new Netlify provider.

add Netlify provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/major-index.html.markdown

Add Oracle Cloud Infrastructure provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/major-index.html.markdown

Cherry pick from https://github.com/hashicorp/terraform/pull/18884

Cherry-pick provider docs from master

---

website/docs/providers/index.html.markdown
website/docs/providers/type/infra-index.html.markdown

Add links for new RightScale provider

RightScale provider links

---

website/docs/providers/type/vcs-index.html.markdown

This change affects document only.

Fix proper nouns of vcs services

---

website/docs/plugins/provider.html.md

Per https://groups.google.com/forum/#!msg/terraform-developers/vwVVP0WDFEo/GOQZvotRGQAJ

docs: Fix inaccurate plugin CRUD description

---

website/docs/providers/index.html.markdown
website/docs/providers/type/network-index.html.markdown

Website: New F5 BigIP provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/network-index.html.markdown

adding new provider links - cherry-pick from master https://github.com/hashicorp/terraform/pull/18951

Website Cherry-pick

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding a new terraform provider for TencentCloud

[Website] New Provider Links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

PR for master branch https://github.com/hashicorp/terraform/pull/18957

Cherry-pick from master

---

website/docs/providers/type/community-index.html.markdown

Add Aiven and OpenFaaS s community providers

add community providers

---

website/docs/providers/type/community-index.html.markdown

cherry-pick from https://github.com/hashicorp/terraform/pull/18960

cherry-pick community links

---

website/docs/providers/type/community-index.html.markdown

Add two new community providers:
Rollbar
Venafi

[Website] New Communtiy Providers

---

website/docs/providers/type/community-index.html.markdown

Cherry-pick from master branch --> https://github.com/hashicorp/terraform/pull/19003

Stable website cherry-pick

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding two links for the Nutanix Terraform provider docs

[Website] New Nutanix Provider Links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding Nutanix provider links.
This is a cherry pick from https://github.com/hashicorp/terraform/pull/19039

[Website] Cherry-pick from master

---

website/docs/providers/index.html.markdown
website/docs/providers/type/infra-index.html.markdown

Add links for new helm provider release

add helm links

---

builtin/providers/terraform/provider.go

Forgot the internal provider for this change

PrepareProviderConfig for terraform provider

---

helper/plugin/grpc_provider.go
helper/plugin/grpc_provider_test.go

Add any top-level default attributes from the provider schema into Null
config values.

Insert default values into provider config

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Cherry-pick from master branch

[Website] Linode documentation links

---

go.mod
go.sum
vendor/github.com/xanzy/ssh-agent/pageant_windows.go
vendor/modules.txt

for go 1.11 / windows compatibility

vendor: upgrade ssh-agent dependency

---

command/format/state.go

Without using absolute paths any module info is lost in the output. And the attributes were randomly ordered and so changed between different executions of the command.

Terraform show didn’t show absolute paths

---

command/format/diff.go
helper/schema/resource.go
plans/objchange/compatible.go
plans/objchange/objchange.go

checks for nil pointers and nil cty.Valus

panic fixes

---

website/guides/core-workflow.html.md

Screenshots for:
- GitHub Pull Request with resource changes in the TFE status update
- TFE plan-only run for a Pull Request
Requires merging https://github.com/hashicorp/terraform-website/pull/529 first.

Add links to new screenshots

---

website/docs/configuration/resources.html.md

Small grammar fix for lifecycle docs

---

website/docs/providers/type/community-index.html.markdown

Adding a few community providers and fix a fmt bug.

[Website] More Community Provider

---

website/docs/providers/type/community-index.html.markdown

This is a cherry pick merge from master --> https://github.com/hashicorp/terraform/pull/19238

[website cherry-pick] community providers

---

website/docs/providers/terraform/d/remote_state.html.md

I've gotten confused about how these work multiple times over the last year, so here's what I've learned about them.

website: clarify behavior of terraform_remote_state data sources

---

command/command_test.go
command/meta.go
command/meta_test.go
command/plan_test.go
command/test-fixtures/plan-out-backend/main.tf
command/workspace_command_test.go
terraform/hook_stop.go

This set of commits is unrelated aside from all being in the command package and being tests I fixed today. It may be easiest to review these on a commit-by-commit basis since the individual commit messages have additional context in some cases.

command: Assorted test repairs

---

command/apply_test.go
command/init.go
command/init_test.go
command/meta_backend.go
command/refresh_test.go
configs/configload/loader_init_from_module.go

Similar to yesterday's #19319, this is another assorted collection of test fixes in the `command` package which I completed today.
Again, it may be easier to follow to look at it one commit at a time so it's clearer what each change is trying to achieve.

command: More assorted test fixes

---

command/init.go
command/init_test.go
command/meta_backend.go
command/meta_backend_migrate.go
command/state_push_test.go
states/statefile/read.go

Fix a few, regress a few... still a net decrease in test failures, but a couple we already fixed are now failing again, which I'll look into next week.

command: More test fixes

---

states/statefile/testdata/roundtrip/v3-simple.in.tfstate
states/statefile/testdata/roundtrip/v3-simple.out.tfstate
states/statefile/version3_upgrade.go
terraform/valuesourcetype_string.go

Fix wildcard dependencies when upgrading states

---

backend/remote-state/azure/client.go

backend/azurerm: fixing a bug where locks couldn't be unlocked

---

website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/network-index.html.markdown

Cherry-pick from master branch --> https://github.com/hashicorp/terraform/pull/19390

new provider and community links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown
website/docs/providers/type/community-index.html.markdown
website/docs/providers/type/network-index.html.markdown

Adding SelVPC as a new certified provider
Adding and removing a few community provider links

[Website] New certified and community provider

---

lang/funcs/collection.go
lang/funcs/collection_test.go

Now that our language supports tuple/object types in addition to list/map types, it's convenient for `zipmap` to be able to produce an object type given a tuple, since this makes it symmetrical with `keys` and `values` such the the following identity holds for any map or object value `a`:
```hcl
a == zipmap(keys(a), values(a))
```
When the values sequence is a tuple, the result has an object type whose attribute types correspond to the given tuple types.
Since an object type has attribute names as part of its definition, there is the additional constraint here that the result has an unknown type (represented by the dynamic pseudo-type) if the given values is a tuple and the given keys contains any unknown values. This isn't true for values as a list because we can predict the resulting …

lang/funcs: zipmap accepts tuple of values and produces object

---

website/docs/providers/type/cloud-index.html.markdown

[Website] Fix path

---

website/docs/providers/type/cloud-index.html.markdown

[Website] Updates path name

---

helper/plugin/grpc_provider.go
helper/plugin/grpc_provider_test.go

Errors were being ignore with the intention that they would be caught
later in validation, but it turns out we nee dto catch those earlier.
The legacy schemas also allowed providers to set and empty string for a
bool value, which we need to handle here, since it's not being handled
from user input like a normal config value.
Fixes: #19506

catch conversion errors in PrepareProviderConfig

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding provider links for the new Skytap provider

[Website] Skytap provider links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

This is a cherrypick commit from master branch https://github.com/hashicorp/terraform/pull/19562

[Website] Skytap cherry-pick

---

command/format/diff_test.go

This is an initial attempt to get some tests in place to at least cover the simplest changes.
We can then modify these and/or add more test cases with more edge cases with potential bug fixes.

command/format: Add tests for ResourceChange renderer

---

website/docs/providers/type/community-index.html.markdown

Adding six new community providers:
libvirt
Logentries 
Logz.io
oVirt
Proxmox
Sumo Logic

[Website] adding six new community providers

---

website/docs/providers/type/community-index.html.markdown

This PR is a cherry-pick of the changes in https://github.com/hashicorp/terraform/pull/19594

[Website] cherry-pick to stable-website

---

command/format/diff_test.go

Added more tests mainly based on `go tool cover` output.
`TestResourceChange_nestedSet` seems to be redundant at this point as sets come through as `configschema.NestingList` for some reason. I have not looked into it and I don't know if it even is an issue, just something odd I noticed.

command/format: Add more tests to cover non-primitive fields

---

backend/local/hook_count.go
backend/local/hook_count_test.go

backend/local: Fix incorrect destroy/update count on apply

---

command/format/diff.go
command/format/diff_test.go

command/format: Fix rendering of nested blocks during update

---

command/format/diff.go
command/format/diff_test.go

~Depends on #19608 (I can rebase after that PR is merged)~
Fixes #19145

command/format: Fix rendering of force-new updates

---

backend/local/backend_plan.go
backend/local/backend_plan_test.go
backend/local/test-fixtures/destroy-with-ds/main.tf
backend/local/testing.go

backend/local: Avoid rendering data sources on destroy

---

backend/local/backend_plan.go
backend/local/backend_plan_test.go
backend/local/test-fixtures/plan-cbd/main.tf
command/format/plan.go

backend/local: Render CBD replacement (+/-) correctly

---

command/providers.go

fix error that prevents --no-color flag on providers command

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding links to UCloud Terraform provider docs

[Website] links for new UCloud provider

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Cherry-pick from master branch PR https://github.com/hashicorp/terraform/pull/19710

[Website] UCloud Cherry-pick

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Adding links to the Hedvig Terraform provider docs

[Website] Hedvig provider doc links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Cherry pick from https://github.com/hashicorp/terraform/pull/19730

[Website] Cherry-pick Hedvig links

---

website/docs/providers/index.html.markdown
website/docs/providers/type/community-index.html.markdown

Adding 5 new community providers to this listing:
Abiquo
Duo Security
Elasticsearch
Keycloak
Spinnaker

[Website] Add new community providers

---

website/docs/providers/index.html.markdown
website/docs/providers/type/community-index.html.markdown

Cherry-picked from master branch PR https://github.com/hashicorp/terraform/pull/19952

[Website] Cherry-pick

---

.github/ISSUE_TEMPLATE/feature_request.md

This will (hopefully) save us some triaging time. 😉

Add labels to issue templates

---

command/format/diff.go
command/format/diff_test.go

Fixes #19998
The diff we produce may not be the best (see test cases), but the definition of _"best"_ is kind of subjective here.
AFAIK 0.11 used to render `[a, b, c] -> [a, (unknown), c]` as 
```diff
[
a,
~ b -> (unknown),
c,
]
```
but we now render it as
```diff
[
a,
- b,
+ (unknown),
c,
]
```
neither of which is not necessarily right or wrong. [LCS](https://github.com/hashicorp/terraform/blob/15cd6d83002af36fb2264e20dc717cbbee062b01/plans/objchange/lcs.go#L18) is however most likely better than simple index-based comparison.

command/format: Fix rendering of unknown elements in set/map/list

---

command/format/diff.go
command/format/diff_test.go

Fixes #19275
----
I also realized (after fixing the original bug) that we render partially known strings, such as
```
description = "Provider ${github_repository.aws.computed_field}"
```
as `(known after apply)`, which IMO deserves a completely separate issue.

command/format: Fix nested (JSON) object formatting

---

command/jsonconfig/config.go
command/jsonconfig/expression_test.go
command/jsonplan/plan.go

And some bonus expressions tests!

command/jsonplan: fix panic when filteredAfter is null

---

command/jsonconfig/config.go
command/jsonplan/module.go
command/jsonplan/plan.go
command/jsonplan/values.go
command/jsonstate/state.go
command/test-fixtures/show-json/basic-create/main.tf
command/test-fixtures/show-json/basic-create/output.json

Sorting was inconsistently applied to resources.

command/jsonplan: sort resources by address

---

svchost/disco/disco.go

(backporting https://github.com/hashicorp/terraform/pull/20131 to `0.11`)

[0.11 backport] disco: Set transport early (during initialization)

---

svchost/disco/disco.go

This is to allow any external callers to add transports (e.g. for logging) without having to worry about what the default transport should be (and having to import & vendor `cleanhttp` in this case).
See https://github.com/terraform-providers/terraform-provider-tfe/pull/55 which crashes without this patch.

disco: Set transport early (during initialization)

---

helper/plugin/grpc_provider.go
helper/plugin/grpc_provider_test.go

While copyMissingValues was meant to re-insert empty values that were
null after apply, it turns out plan is sometimes not predictable as
well, which would leave perpetual diffs with some collections going from
empty to null or vice versa.
normalizeNullValue is meant to fix up any null/empty transitions between
to values, and be useful during plan as well. For plan the function only
concerns itself with individual, known values, and skips sets entirely.
The result of running with plan == true is that only changes between
empty and null collections should be fixed.
fixes #20082

change copyMissingValues to normalizeNullValues

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

Updating provider name from `selvpc` to `selectel`

[Website] Update provider name

---

website/docs/providers/index.html.markdown
website/docs/providers/type/cloud-index.html.markdown

This is a cherry-pick merge from https://github.com/hashicorp/terraform/pull/20233

[Website] Cherry-pick to stable-website branch

---

website/docs/providers/type/community-index.html.markdown

Adding two new community providers:
Jira (Extended)
Pivotal Tracker

[Website]New community providers

---

website/docs/providers/type/community-index.html.markdown

Cherry pick from master branch https://github.com/hashicorp/terraform/pull/20251

[Website]Cherry-pick

---

command/jsonplan/plan.go
command/jsonplan/values.go
command/jsonstate/state.go
command/show_test.go
command/test-fixtures/show-json/basic-create/output.json
command/test-fixtures/show-json/basic-delete/output.json
command/test-fixtures/show-json/basic-update/output.json

command/jsonplan: add variables to plan output
command/jsonplan: print known planned values for resources
command/jsonstate: added depends_on and tainted fields to state output

command/show: json output enhancements 

---

go.mod
go.sum
vendor/github.com/hashicorp/hil/convert.go
vendor/github.com/hashicorp/hil/go.mod
vendor/github.com/hashicorp/hil/go.sum
vendor/github.com/mitchellh/mapstructure/.travis.yml
vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
vendor/github.com/mitchellh/mapstructure/README.md
vendor/github.com/mitchellh/mapstructure/decode_hooks.go
vendor/github.com/mitchellh/mapstructure/go.mod
vendor/github.com/mitchellh/mapstructure/mapstructure.go
vendor/modules.txt

~Depends on https://github.com/hashicorp/terraform/pull/20302 (I can rebase when it is merged)~
---
Related:
https://github.com/hashicorp/hil/pull/63
https://github.com/hashicorp/terraform/pull/20144
#20287

vendor: github.com/hashicorp/hil@latest

---

website/docs/providers/type/community-index.html.markdown

Adding: Credhub, Sensu, snowflakedb, Zipper community providers

[Website] Adding Community Providers

---

builtin/providers/test/resource_list_set.go
builtin/providers/test/resource_list_set_test.go
helper/plugin/grpc_provider.go
terraform/diff.go

A crucial check in `Diff.Apply` was missing the check for `.%` keys when looking for containers.

Diff apply needs to check for both types of containers keys

---

command/format/state.go
command/format/state_test.go

command/format: fix an issue where data resources were not displaying properly

---

website/docs/providers/type/community-index.html.markdown

adding sops and SQL provider to the community listings

[Website] Two new community providers

---

website/docs/providers/index.html.markdown
website/docs/providers/type/network-index.html.markdown

CHerry-pick from https://github.com/hashicorp/terraform/pull/20440

[Website] Stable website cherry-pick

---

command/meta_vars.go
command/plan_test.go

A common new-user mistake is to place variable _declarations_ into `.tfvars` files instead of variable _values_. To guide towards the correct approach here, we add a specialized error message for that situation that includes guidance on the distinction between declaring and setting values for variables, and an example of what setting a value should look like.
This fixes #19202.
```
Error: Variable declaration in .tfvars file
on invalid-variable-blocks.tfvars line 1:
1: variable "example" {
A .tfvars file is used to assign values to variables that have already been
declared in .tf files, not to declare new variables. To declare variable
"example", place this block in one of your .tf files, such as variables.tf.
To set a value for this variable in invalid-variable-blocks.tfvars, use the …
```

command: Specialized error message for var decls in tfvars
